#+title: 八下道法背诵材料
#+date: <2023-04-07 五 11:09>
#+description: 完全抄某教辅的背诵材料的道德与法治东西

#+setupfile: ../../../setup.setup

#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{a4paper, scale=0.8}
#+LATEX_HEADER: \linespread{1}

* 维护宪法权威
** 党的主张和人民意志的统一
*** 新中国成立后，人民是如何确认奋斗成果的？
新中国成立后，中国共产党领导人民制定宪法，以法律的形式确认了中国各族人民奋斗的成
果，确立了在历史和人民的选择中形成的中国共产党的领导地位。我国的宪法是党的主张和
人民意志的统一。
*** 中国共产党的性质、根本宗旨、目标和地位分别是什么？
1) 性质：中国共产党是中国工人阶级的先锋队，同时是中国人民和中华民族的先锋队。
2) 根本宗旨：全心全意为人民服务
3) 地位：中国共产党是中国特色社会主义事业的领导核心。党政军民学，东南西北中，党
   是领导一切的。
*** 坚持中国共产党领导的重要性和做法分别是什么？
1) 重要性：中国共产党领导是中国特色社会主义最本质的特征，是中国特色社会主义制度
   的最大优势。是党和国家的根本所在，命脉所在，是全国各族人民的利益所系、命运所
   系。党是最高政治领导力量。
2) 做法：必须坚决维护党中央权威和集中统一领导，健全总览全局、协调各方的党的领导
   制度体系，把党的领导落实到党和国家事业各领域各方面各环节。
*** 中国共产党如何坚持依宪执政？
中国共产党领导人民制定宪法和法律，领导人民实施宪法和法律，做到党领导立法、保证执
法、支持司法、带头守法。中国共产党要履行好执政兴国的重大职责，必须在宪法和法律范
围内活动，依据宪法和法律治国理政。
*** 我国宪法的基本原则是什么？
我国是人民民主专政的社会主义国家。国家的一切权力属于人民，这是我国宪法的基本原则。
这一原则归根结底是要保证人民当家做主的权利。
*** 宪法如何确保国家一切权力属于人民？
1) 宪法确认我国的 _国家性质_ ，明确人民当家做主的地位。
2) 宪法规定的 _社会主义经济制度_ ，奠定了国家权力属于人民的经济基础。
3) 宪法规定的 _社会主义政治制度_ ，明确了人民行使国家权力的基本途径和形式。
4) 宪法规定 _广泛的公民基本权利_ ，并规定实现公民基本权利的保障措施。
5) 宪法规定 _国家武装力量属于人民_ ，并规定其任务是巩固国防，抵抗侵略，保卫祖国，
   保卫人民的和平劳动，参加国家建设事业，努力为人民服务。[fn:1]
*** 最大的人权、我国人权的主体、保护对象及内容分别是什么？
1) 最大的人权：人民幸福生活是最大的人权
2) 主体、保护对象：在我国，人权的主体非常广泛，既包括我国公民，也包括外国人等。
   人权保护的对象不仅包括个人，也包括群体。
3) 内容：宪法保护的人权内容也很广泛，既包括 _平等权_ 和 _人身权利_ 、 _政治权利_
   ，也包括 _财产权_ 、 _劳动权_ 、 _受教育权_ 等 _经济社会_ 、 _文化方面_ 的权
   利。
*** 国家如何做到尊重和保障人权？
1) 各级国家机关树立尊重和保障人权的理念，加强人权法治保障，保证人民依法享有广泛
   权利和自由。
2) 尊重和保障人权是立法活动的基本要求。我国宪法规定了公民享有的广泛的基本权利，
   法律进一步明确了公民享有的各项具体权利，规定了侵害权利的法律责任。
3) 行政机关在执法过程中应当树立尊重和保障人权的意识，做到严格规范公正文明执法，
   坚持依宪施政、依法行政、简政放权。
4) 监察机关依照法律规定独立行使监察权，加强对所有行使公权力的公职人员的监督，保
   护公民的各项合法权益。
5) 审判机关、检察机关要依照宪法和法律的规定分别独立行使审判权、检察权，保护公民
   的各项合法权益。
6) 国家加强法治宣传教育，弘扬社会注意法治精神，建设社会主义法治文化，增强全民法
   治观念，形成全民守法的氛围和习惯，努力将人权理想变成现实。
** 治国安邦的总章程
*** 宪法如何设置国家机构？
1) 设置原则：宪法明确国家机构实行民主集中制的原则[fn:2]
2) 设置方式：宪法明确各级国家机关的产生。人民代表大会是人民行使国家权力的机关。
   全国人民代表大会和地方各级人民代表大会都由民主选举产生，对人民负责，受人民监
   督。国家行政机关、监察机关、审判机关、检察机关都由人民代表大会产生，对它负责，
   受它监督。
3) 规范权力运行：宪法授予国家机构特定职权，明确国家机构的组成、任期、工作方式等
   内容，使得国家权力的运行稳定有序。国家机构依据宪法行使权力，以实现和维护人民
   的根本利益。
*** 国家机构贯彻民主集中制原则主要体现在那些方面？
1) 在国家机构与人民的关系方面，国家权力来自人民，由人民选举产生国家权力机关，国
   家权力机关在国家机构中居于主导地位。
2) 在中央与地方国家机构的关系方面，中央和地方的国家机构职权的划分，遵循在中央的
   统一领导下，充分发挥地方的主动性、积极性的原则[fn:3]
3) 在国家机关内部作出决策、决定时，实行民主集中制
*** 为什么要规范权力运行？
1) 权力是把双刃剑，运用得好，可以造福于民；如果被滥用，则会滋生腐败，贻害无穷。
2) 规范国家权力运行以保障公民权利，这是宪法的核心价值追求。
3) 只有依法规范权力运行，才能保证人民赋予的权力始终用来为人民谋利益。
*** 宪法如何规范权力的运行？
1) 加强对权力运行的制约和监督，让人民监督权力，让权力在阳光下运行，把权力关进制
   度的笼子。
2) 国家权力必须在宪法和法律限定的范围内行使，不能超越权限、滥用职权，否则要承担
   法律责任。 /（法无授权不可为）/
3) 国家级机关及其工作人员必须依法行使权力、履行职责，不能懈怠、推诿。 /（法定职责
   必须为）/
4) 国家权力必须严格按照法定的途径和方式行使。凡不按法定程序行使权力的行为都是违
   法行为。 /（按法定程序行使）/
* 保障宪法实施
** 坚持依宪治国
*** 我国现行宪法的构成是怎样的？
我国现行宪法除序言外，设有第一章总纲，第二章公民的基本权利和义务，第三章国家机构，
第四章国旗、国歌、国徽、首都，共四章一百四十三条。
*** 为什么要维护宪法权威？
1) 我国宪法是党和人民意志的集中体现，是国家的根本法
2) 宪法的权威关系国家的命运、社会的安定和人民的根本利益。如果宪法没有权威，法治
   的权威就树立不起来；如果宪法受到漠视，人民的权利和自由就无法保证。
*** 如何维护宪法权威？
1) 坚持依法治国首先要坚持依宪治国，坚持依法执政首先要坚持依宪执政。[fn:4]
2) 任何公民、社会组织和国家机关都必须以宪法和法律为行为准则。一切组织和个人都必
   须维护宪法权威，保障宪法实施，依照宪法和法律行使权利或权力，履行义务或职责，
   都不得有超越宪法和法律的特权，一切违反宪法和法律的行为都必须予以追究。
*** 为什么说宪法具有最高的法律效力？（宪法与其他法律的关系是怎样的？）
|----------------+-------------------------------+--------------------------------------|
|----------------+-------------------------------+--------------------------------------|
| 比较           | 宪法                          | 其他法律                             |
|----------------+-------------------------------+--------------------------------------|
|----------------+-------------------------------+--------------------------------------|
| 规定内容       | 规定国家生活中带有全局性、    | 规定国家生活中的一般性问题，是对国家 |
|                | 根本性的问题                  | 生活和社会生活中某一方面的规定       |
|----------------+-------------------------------+--------------------------------------|
| 法律效力       | 具有最高的法律效力，是其他    | 是根据宪法指定的，不得与宪法的原则和 |
|                | 法律的立法基础和立法依据      | 精神相违背，否则会因为违宪而无效     |
|----------------+-------------------------------+--------------------------------------|
| 制定和修改程序 | 比其他法律更加严格：          |                                      |
|                | 1) 制定：遵循特定的制宪程序   | 依据一般程序，由全国人民代表大会以   |
|                | 2) 修改：由全国人大常委会或   | 全体代表的过半数通过或者由全国人大   |
|                | 五分之一以上的全国人大代表    | 常委会全体组成员的过半数通过         |
|                | 提议，并由全国人大以全体代    |                                      |
|                | 表的三分之二以上的多数通过    |                                      |
|----------------+-------------------------------+--------------------------------------|
|----------------+-------------------------------+--------------------------------------|
| 联系           | 1) 宪法是国家法制统一的基础， | 是中国特色社会主义法律体系的核心     |
|                | 2) 宪法的规定具有原则性的特点 | 各种法律制度是对宪法规定的具体落实   |
|                | 3) 宪法是对公民基本权利的根本 | 确认和保障，其他法律也对公民基本权利 |
|                | 的实现具有不可替代的作用      |                                      |
|----------------+-------------------------------+--------------------------------------|
|----------------+-------------------------------+--------------------------------------|
*** 为什么说宪法是国家法治统一的基础，是中国特色社会主义法律体系的核心？
1) 宪法的规定具有原则性的特点，各种法律制度是对宪法规定的具体落实。
2) 宪法是对公民基本权利的根本确认和保障，其他法律也对公民基本权利的实现具有不可
   替代的作用。
*** 为什么要坚持依宪治国？（宪法的地位/重要性）
1) 我国宪法是党的主张和人民意志的统一，是治国安邦的总章程。
2) 宪法是党和人民意志的集中体现，是国家的根本法。
3) 宪法具有至高无上的权威。
4) 宪法在国家法律体系中具有最高的法律地位、法律权威和法律效力。
5) 宪法是国家法治统一的基础，是中国特色社会主义法律体系的核心。
** 加强宪法监督
*** 宪法监督的主体和主要内容分别是什么？
1) 主体：全国人大及其常委会、地方各级人大
   1) 全国人大及其常委会行使监督宪法实施的职权，全国人大常委会有权解释宪法和法律
   2) 地方各级人大在本行政区域内负有保证宪法和法律实施的职责
2) 主要内容：
   1) 合宪性审查和监督，使法律、法规与宪法不抵触
   2) 审查国家机关及其工作人员的违宪行为，追究其违宪责任，维护宪法权威
*** 为什么要加强宪法监督？
1) 权力行使需要接受监督。监督是权力行使的根本保证，不受监督的权力将导致腐败。
2) 在监督公权力行使的制度体系中，宪法监督制度具有基础性意义
3) 加强宪法监督是保障宪法实施的重要举措
4) 健全宪法实施和监督制度，不断加强宪法监督工作，是全面依法治国的需要
*** 如何加强宪法监督？
1) 需要加强宪法实施和监督，健全保证宪法全民实施的制度体系
   1) 完善全国人大及其常委会宪法监督制度，健全监督机制和程序，使其更好地负担起宪
      法监督职责
   2) 健全宪法解释程序机制，推进合宪性审查工作，加强备案审查制度和能力建设，加强
      对宪法实施情况的监督检查，维护宪法权威
   3) 对各种违宪行为都必须予以追究和纠正
2) 需要人们增强宪法意识。如设立国家宪法日，建立宪法宣誓制度等。
*** 我们应如何增强宪法意识？
1) 学习宪法
   1) 了解宪法产生和发展的历程，理解宪法的主要内容，领会宪法的原则和精神。
   2) 积极参与宪法宣传活动，为增强全社会的宪法意识贡献自己的力量
2) 认同宪法。理解并认同宪法的价值，增强对宪法的信服和尊崇，自觉接受宪法的指引与
   要求，让宪法真正铭刻于心。
3) 践行宪法。将宪法原则转化为自觉的行为准则，落实在实际行动上。\\
   具体来说：
   1) 严格遵守宪法和法律规定，学会运用宪法精神来分析和解决学习和生活中的实际问题
   2) 坚决维护宪法的权威，自觉抵制各种妨碍宪法实施、损害宪法尊严的行为。
*** 为什么要保障宪法实施？
1) 宪法的生命在于实施，宪法的权威也在于实施。维护宪法权威需要我们保障宪法实施。
2) 如果宪法得不到充分、有效实施，受到漠视、削弱甚至破坏，国家权力的行使将会违反
   法治的要求，我们的幸福生活就不能真正实现。
3) 依法治国首先是依宪治国。保障宪法实施是建设社会主义法治国家的需要。
*** 如何保障宪法的实施？
1) 保障宪法的实施，必须坚持依宪治国。
2) 保障宪法的实施，要加强宪法监督。
3) 保障宪法的实施，需要我们每个人增强宪法意识，尊重宪法，维护宪法。
* 公民权利
** 公民基本权利
*** 我国公民基本权利有哪些？
1) 政治权利
2) 人身自由
3) 社会经济与文化教育权利
4) 我国公民还享有平等权、宗教信仰自由等权利，妇女儿童和残疾人等特定人群的权利受
   到宪法和法律的特殊保障
*** 公民享有政治权利的内容和意义分别是什么？
1) 内容：选举权和被选举权、言论、出版等自由和监督权等
2) 意义
   1) 有利于公民依法行使政治权利，参与国家政治生活，通过各种途径和形式管理国家事
      务，管理经济和文化事业，管理社会事务。
   2) 是人民行使当家做主权利的重要形式
*** 公民行使选举权和被选举权的条件和意义分别是什么？
1) 条件：
   1) 年满18周岁的我国公民
   2) 没有被依法剥夺政治权利
2) 意义：选举权和被选举权是公民的一项基本政治权利，行使这项权利是公民参与管理国
   家和管理社会的基础
*** 言论、出版等自由的内容和重要性分别是什么？
1) 内容：我国公民享有言论、出版、集会、结社[fn:5]、游行、示威的自由。
2) 重要性：有助于公民参与国家政治生活，充分表达自己的意愿。
*** 监督权的内容、行使原则和重要性分别是什么？
1) 内容：我国公民对于任何国家机关和国家工作人员，有提出批评和建议的权利；对于任
   何国家机关和国家工作人员的违法失职行为，有向有关国家机关提出申诉、控告或检举
   的权利。
2) 行使原则：依法通过各种途径和形式行使监督权，不得捏造或者歪曲事实进行诬告陷害
3) 重要性：有助于国家机关及其工作人员依法行使权力，全心全意为人民服务
*** 人身自由的含义、内容及意义分别是什么？
1) 含义：指公民的人身不受非法侵犯的自由
2) 内容：包括人身自由不受侵犯，人格尊严不受侵犯，住宅不受侵犯，通信自由和通信秘
   密受法律保护
3) 意义：人身自由是公民最基本、最重要的权利，只有在人身自由得到保障的前提下，公
   民才能独立、自由、有尊严地生活
*** 宪法对人身自由权作出怎样的规定？
1) 人身自由不受侵犯。我国宪法规定，任何公民，非经人民检察院批准或者人民法院决定，
   并由公安机关执行，不受逮捕。禁止非法拘禁和以其他方法非法剥夺或者限制公民的人
   身自由，禁止非法搜查公民的身体。
2) 人格尊严不受侵犯。我国宪法规定，公民的人格尊严不受侵犯，禁止用任何方法对公民
   进行侮辱、诽谤和诬告陷害。公民的人格尊严权包括名誉权、荣誉权、肖像权、姓名权、
   隐私权等。
3) 住宅不受侵犯。我国宪法规定，公民的住宅不受侵犯，禁止非法或者非法入侵公民的住
   宅。通信自由和通信秘密受到法律保护。我国宪法规定，公民的通信自由和通信秘密受
   到法律保护。除因国家安全或者追查刑事罪犯的需要，由公安机关或者检察机关依照法
   律规定的程序对通信进行检查外，任何组织或者个人不得以任何理由侵犯公民的通信自
   由和通信秘密。
*** 社会经济权利（有哪些？）
1) 财产权
   1) 重要性：我们的生存和发展及物质和文化生活需要的满足，都离不开财产
   2) 宪法规定：公民的合肥的私有财产不受侵犯
   3) 内容：占有权、使用权、收益权、处分权
2) 劳动权
   1) 含义：一切有劳动能力的公民有劳动就业和取得劳动报酬的权利
   2) 重要性
      1) 是公民赖以生存的基础
      2) 可以保障人们合理的生活水平，实现自身价值，为国家和社会作出贡献
   3) 宪法规定：公民有劳动的权利和义务
3) 物质帮助权
   1) 宪法规定：公民在年老、疾病或者丧失劳动能力的情况下，有从国家和社会获得物质
      帮助的权利
   2) 保障措施：国家发展为公民享受这些权利所需要的社会保障、社会救济和医疗卫生事
      业
*** 文化教育权利（有哪些？）
1) 受教育权
   1) 内涵：公民有按照其能力平等地从国家获得接受教育的机会，并获得相应物质保障的
      权利
   2) 重要性：为个人人生幸福奠定基础，为人类文明传递薪火，成就民族和国家的未来
   3) 保障措施
      1) 国家实行义务教育制度，保障所有失灵儿童、少年接受义务教育
      2) 国家制定资助政策，不让一个学生因家庭经济困难而失学，努力让每个孩子都能
         享有公平而有质量的教育
2) 文化权利
   1) 宪法规定：中华人民共和国公民有进行科学研究、文学艺术创作和其他文化活动的自
      由
   2) 保障措施：国家对于从事教育、科学、技术、文学、艺术和其他文化事业的公民的有
      益于人民的创造性工作，给以鼓励和帮助[fn:6]
** 依法行使权利
*** 公民应该如何正确行使权利？
1) 公民行使权利不能超越它本身的界限，不能滥用权利
2) 公民在行使自由和权利的时候，不得损害国家的、社会的、集体的利益和其他公民的合
   法的自由和权利
3) 公民行使权利应依照法定程序，按照规定的活动方式、步骤和过程进行
4) 公民权利如果受到损害，要依照法定程序维护权利
*** 公民行使权利遵守正当的程序的意义是什么？
遵守正当的程序，有利于公民实际享受权利，有效避免和化解纠纷，有利于维护权益
*** 公民权利受到损害，怎样依照法定程序维护权利？（维护权利的方式有那些？）
1) 和解
   1) 含义：当事人之间通过协商自行解决纠纷
   2) 适用范围：一些常见的消费、劳动争议和交通事故纠纷等
   3) 具体内容：当事人在自愿、互谅的基础上，依据法律，通过直接对话，摆事实、讲道
      理，分清责任，达成协议，使纠纷得以解决
2) 调解
   1) 含义：通过调解组织解决纠纷
   2) 适用范围：广泛用于调解纠纷
   3) 具体内容：调解人以国家法律法规和政策及社会功德为依据，对纠纷双方进行疏导、
      劝说，促使他们相互谅解，进行协商，资源达成协议，解决纠纷。我国调解方式主要
      有 _人民调解_ _行政调解_ 和 _司法调解_
3) 仲裁
   1) 含义：通过仲裁机构解决纠纷
   2) 适用范围：公民与其他个人或组织之间发生合同纠纷和其他财产争议时，可以申请仲
      裁
   3) 具体内容：当事人根据他们之间订立的仲裁协议，自愿将其争议提交仲裁，并受仲裁
      裁决的约束
4) 诉讼
   1) 含义：通过人民法院解决纠纷
   2) 适用范围：如果受到非法侵害后采取其他方式不能解决问题，或者认定只有通过诉讼
      途径才能维护合法权益
   3) 具体内容：
      1) 公民遇到人身关系或财产关系的争议，可以向人民法院提起民事诉讼
      2) 公民对于某些侵犯自己人身、财产权的行为，可以向人民法院提起刑事诉讼
      3) 公民认为行政机关的行政行为侵犯了自己的权益，可以向人民法院提起行政诉讼
* 公民义务 
** 公民基本义务
*** 我国公民的基本义务有那些？
1) 遵守宪法和法律
2) 维护国家利益
3) 依法服兵役
4) 依法纳税
5) 我国宪法阿海规定了公民应履行的其他义务，包括劳动的义务、受教育的义务、夫妻双
   方实行计划剩余的义务、父母抚养教育未成年子女的义务和成年子女赡养父母的义务等
*** 公民要遵守宪法和法律的原因、表现及做法分别是什么？
1) 原因：我国宪法和法律是全国各族人民意志和利益的集中体现，维护宪法和法律的尊严
   是公民对国家和社会应尽的职责
2) 表现：保守国家秘密，爱护公共财产，遵守劳动纪律，遵守公共秩序，尊重社会公德
3) 做法：忠于宪法，维护宪法尊严，保障宪法实施
   1) 自觉做到尊法学法守法用法，共同营造守法光荣，违法可耻的社会氛围
   2) 自觉学习法律知识，了解法律程序规定，以法律来指导和约束自己的行为，做到依法
      办事。
*** 维护国家统一和全国各族团结的原因和做法分别是什么？
1) 原因：我国是统一的多民族国家，国家的统一和民族的团结，是我国顺利进行社会主义
   现代化建设的基本保证
2) 做法：每个公民都应当把自己的命运与国家盛衰、民族兴亡紧密联系在一起，自觉维护
   国家领土完整和主权统一，维护民族之间平等团结互助和谐的关系
*** 维护国家安全、荣誉和利益的内容和重要性分别是什么？
1) 内容
   1) 维护国家安全包括维护国家的主权、领土完整不受侵犯，国家秘密不被窃取、泄露和
      出卖，社会秩序不被破坏等
   2) 维护国家荣誉包括维护国家的尊严不受侵犯，国家的荣誉不受玷污。
   3) 维护国家利益包括维护国家的政治、经济和安全等各方面的利益
2) 重要性：维护国家安全、荣誉和利益是每个公民义不容辞的责任
*** 依法服兵役
1) 原因：
   1) 保卫祖国、抵抗侵略是公民的神圣职责
   2) 依照法律服兵役和参加民兵组织是公民的光荣义务
2) 我国的兵役制度：我国兵役法规定，我国实行以志愿兵役为主体的志愿兵役与义务兵役
   相结合的兵役制度。
3) 兵役种类：分为现役和预备役
4) 要求
   1) 军人：必须遵守军队的条令和条例，忠于职守，随时为保卫祖国而战斗
   2) 预备役人员：必须按照规定参加军事训练，随时准备应召参战，保卫祖国
*** 依法纳税
1) 必要性：税收是国家财政收入的主要来源，依法纳税是公民的一项基本义务
2) 违反依法纳税义务的行为：逃税、欠税、骗税、抗税
3) 违反依法纳税义务要承担的责任：任何违反依法纳税的行为都是违法行为，情节严重、
   构成犯罪的要依法追究刑事责任
** 依法履行义务
*** 我国公民权利与义务的关系是怎样的？
1) 公民的权利与义务相互依存、相互促进。权利的实现需要义务的履行，义务的履行促进
   权利的实现
2) 公民既是合法权利的享有者，又是法定义务的承担者。任何公民享有权利的同时，必须
   履行义务。
3) 公民的某些权利同时也是义务[fn:7]
*** 为什么要坚持权利和义务相统一？
1) 公民权利的充分实现，可以激发公民主人翁意识，调动其履行义务的积极性和主动性，
   自觉承担对国家和社会的责任
2) 公民自觉履行义务，促进国家发展和社会进步，又为其权利的实现提供和创造了更好的
   条件
*** 如何坚持权利和义务相统一？
1) 任何公民不能只享受权利而不承担义务，也不应只承担义务而不享受权利。
2) 要增强权利意识，依法行使权利；也要增强义务观念，自觉履行法定的义务。
*** 为什么必须履行法定义务？
1) 法定义务是由我国宪法和法律规定的，具有强制性
2) 自觉履行法定义务，是公民不可推卸的责任
3) 公民违反法定义务，必须依法承担相应的法律责任
*** 我们如何履行法定义务？
1) 法律要求做的必须去做
2) 法律禁止做的坚决不做
*** 违反法定义务的行为的含义及其后果是什么？
1) 含义：公民实施了法律所禁止的行为，或者没有实施法律要求做的行为，都是违反法定
   义务的行为
2) 后果：违反法定义务，必须依法承担相应的法律责任
   1) 公民违反民事法律，应当依法承担民事责任
   2) 公民违反行政法律，应当依法承担行政责任
   3) 公民违法刑事法律，构成犯罪的，应当依法承担刑事责任
* 我国的政治和经济制度
** 根本政治制度
*** 地位？
人民代表大会制度是我国的根本政治制度[fn:8]
*** 人民代表大会制度的基本内容是什么？
1) 国家的一切权力属于人民
2) 人民通过民主轩主选出代表，组成各级人民代表大会作为国家权力机关
3) 由人民代表大会产生国家行政机关、检察机关、审判机关、检察机关，这些国家权力机
   关依法行使各自的职权，并对人民代表大会负责，受人民代表大会监督
4) 实行民主集中制，重大问题经人民代表大会充分讨论，遵循少数服从多数原则，民主决
   定
*** 各级人大代表的职权、职权来源和义务分别是什么？
1) 职权：依法审议各项议案和报告 /（审议权）/ 、表决各项决定 /（表决权）/ 、提出
   议案 /（提案权）/ 和质询案 /（质询权）/ 。
2) 职权来源：各级人民代表大会代表宪法和法律赋予本级人民代表大会的各项职权，参加
   行使国家权力
3) 义务：人大代表必须与人民群众保持密切联系，听取和反映人民群众的意见和要求，努
   力为人民服务，对人民负责，并接受人民监督。
*** 为什么要坚持和完善人民代表大会制度？（人民代表大会制度的优越性体现在哪里？）
1) 实践充分证明，人民代表大会制度是符合中国国情和实际、体现社会主义国家性质、保
   证人民当家做主、保障实现中华民族伟大复兴的好制度。
2) 人民代表大会制度是坚持党的领导、人民当家做主、依法治国有机统一的根本政治制度
   安排。
*** 如何坚持和完善人民代表大会制度？
1) 必须毫不动摇坚持中国共产党的领导，依据人民代表大会制度，使党的主张通过法定程
   序成为国家意志。
2) 必须保证和发展人民当家做主，支持和保证人民通过人民代表大会行使国家权力，扩大
   人民民主，健全民主制度，丰富民主形式，拓宽民主渠道
3) 必须全面推进依法治国，通过人民代表大会制度，弘扬社会主义法治精神，实现国家各
   项工作法治化
4) 必须坚持民主集中制，人民代表大会统一行使国家权力，国家机关及有合理分工又有相
   互协调，保证国家统一高效组织推进各项事业
** 基本政治制度——中国共产党领导的多党合作和政治协商制度
*** 什么是爱国统一战线？
由中国共产党领导的，有各民主党派和各人民团体参加的，包括全体社会主义劳动者、社会
主义事业的建设者、拥护社会主义的爱国者、拥护祖国统一和致力于中华民族伟大复兴的爱
国者的广泛的爱国统一战线
*** 中国共产党各民主党派实行的基本方针是什么？
长期共存、互相监督、肝胆相照、荣辱与共[fn:9]
*** 人民政治协商会议（人民政协）的地位、主题和职能分别是什么？
1) 地位：是中国共产党领导的多党合作和政治协商的重要机构，是中国人民爱国统一战线
   组织。
2) 主题：团结和民主
3) 职能：政治协商、民主监督、参政议政
*** 坚持中国共产党领导的多党合作和政治协商制度的意义是什么？
1) 是发扬社会主义民主的重要形式
2) 有利于反映民意，集中民智，促进科学民主决策
3) 有利与协调关系，化解矛盾，维护社会稳定和谐
4) 有利于凝聚人心，反对分裂，推进祖国和平统一大业
** 基本政治制度——民族区域自治制度
*** 为什么要实行民族区域自治制度？
1) 中华人民共和国是全国各族人民共同缔造的统一的多民族国家
2) 我们辽阔的疆域是各民族共同开拓的，我们悠久的历史是各民族共同书写的，我们灿烂
   的文化是各民族共同创造的，我们伟大的精神是各民族共同培育的
3) 五十六个民族在长期的交往、交流、交融中确立了平等团结互助和谐的社会主义民族关
   系
*** 我国的民族区域自治制度是如何实施的？（我国的少数民族是如何实现区域自治的？）
1) 无偶国宪法规定，各少数民族聚居的地方实行区域自治，设立自治机关，行使自治权。
   我国民族自治地方分为自治区、自治州、自治县三集。 /（自治地方）/
2) 民族自治地方的人民代表大会和人民政府是自治机关。 /（自治机关）/
3) 自治机关在行使一般地方国家机关职权的同时，依法行使自治权，即根据本地方、本民
   族政治、经济、社会、文化等方面的特点，自主管理本地方、本民族的内部事务。
   /（自治权）/
4) 我国民族区域自治是在国家统一领导下的自治，各民族自治地方是国家不可分割的组成
   部分，民族自治机关必须服从中央的领导。 /（民族自治地方和国家的关系）/
*** 实行民族区域自治是的意义是什么？
1) 有利于把国家的集中、统一与各民族的自主、平等结合起来。
2) 有利于把国家的法律、政策与民族自治地方的具体实际、特殊情况结合起来。
3) 有利于把各族人民热爱祖国的感情与热爱自己民族的感情结合起来。
4) 实践证明,民族区域自治制度符合我国国情，在维护国家统一、领土完整，在加强民族平等团结、促进民族地区发展、增强中华民族凝聚力等方面都起到了重要作用。
** 基本政治制度——基层群众自治制度
*** 基层群众自治制度的内容、地位及自治组织分别是什么?
1) 内容：依照宪法和法律，由居民或村民分别选举产生居民委员会或村民委员会，实行群众自
   我管理、自我服务、自我教育、自我监督。
2) 地位：是我国的一项基本政治制度。
3) 自治组织城市居民委员会和农村村民委员会。
*** 居民委员会和村民委员会
| 项目   | 内容       | 居民委员会                 | 村民委员会                               |
|--------+------------+----------------------------+------------------------------------------|
|        | 性质       | 城市基层群众性自治组织     | 农村基层群众性自治组织                   |
|--------+------------+----------------------------+------------------------------------------|
|        | 产生方式   | 由居民直接投票选举产生     | 由村民直接选举产生                       |
|--------+------------+----------------------------+------------------------------------------|
|        |            | 凡涉及居民切身利益的重要   | 村民可以通过村民会议等形式,参与本村      |
| 不同点 | 决策程序   | 事务，要提请居民会议讨论   | 公共事务和公益事业的决策与管理           |
|        |            | 决定                       |                                          |
|--------+------------+----------------------------+------------------------------------------|
|        |            | 实行办事公开制度，定期向   | 村民制定自治章程或村规民约，规范村委     |
|        | 管理与监督 | 居民会议汇报工作，接受居   | 会和村民的行为                           |
|        |            | 民监督                     |                                          |
|--------+------------+----------------------------+------------------------------------------|
| 相同点 | ①都是基层 | 公民参与政治生活的重要形式 | ②都是人民群众直接行使民主权利的重要渠道 |
*** 实行基层群众自治制度有什么意义?(基层群众自治制度有什么优越性?)
有利于人民群众直接行使民主权利，管理基层公共事务和公益事业，推动社会主义民主建设，
促进社会和谐稳定。
** 基本政治制度——基本经济制度
*** 现阶段，我国的基本经济制度是什么?
公有制为主体、多种所有制经济共同发展，按劳分配为主体、多种分配方式并存，社会主义
市场经济体制等是我国社会主义基本经济制度。
*** 现阶段，公有制经济的成分包含什么?
公有制经济包括国有经济、集体经济以及混合所有制经济中的国有成分和集体成分。
*** 国有经济和集体经济的内涵和地位分别是什么?
1) 国有经济：
   1) 内涵：国有经济的生产资料属于全体人民共同所有。
   2) 地位：国有经济是国民经济的主导力量。
2) 集体经济：
   1) 内涵：集体经济的生产资料属于一部分劳动者共同所有。
   2) 地位：集体经济是公有制经济的重要组成部分。
*** 现阶段，非公有制经济的成分包含什么?
个体经济、私营经济、港澳台投资经济、外商投资经济等。
*** 公有制经济与非公有制经济的地位是什么?
公有制经济与非公有制经济都是社会主义市场经济的重要组成部分，都是我国经济社会发展
的重要基础。
*** 坚持公有制为主体、多种所有制经济共同发展的意义是什么?
1) 促进生产力的发展、综合国力的增强和人民生活水平的提高。
2) 为人民当家作主奠定坚实的物质基础。
*** 现阶段，我国对待公有制经济与非公有制经济的政策是什么?
必须毫不动摇巩固和发展公有制经济，毫不动摇鼓励、支持、引导非公有制经济发展。
*** 现阶段，我国坚持怎样的分配制度?
现阶段，我国坚持按劳分配为主体、多种分配方式并存。
*** 按劳分配的决定因素和基本内容及要求是什么?
1) 决定因素：是由生产资料公有制决定的。
2) 基本内容及要求：能力社会成员必须参加劳动;在作了必要的扣除后，以劳动者所提供的
   劳动(包括劳动数量和质量)为尺度对个人进行分配，多劳多得，少劳少得。在现阶段，
   要着重保护劳动所得，增加劳动者劳动报酬。
*** 多种分配方式指的是什么?
1) 让劳动、资本、土地、知识、技术、管理、数据等生产要素参与收入分配，由市场评价
   贡献，按贡献决定报酬。
2) 在一定条件下，人们还可以取得社会保障收入，获得社会公益事业的帮助。
*** 市场经济体制的含义和作用分别是什么?
1) 含义：市场经济体制是市场在资源配置中起决定性作用的经济体制。
2) 作用：在市场经济中，生产什么、如何生产、生产多少，主要是通过价格、供求、竞争
   等机制来调节。市场机制就像一只“看不见的手”，在资源配置中起决定性作用。
*** 我国社会主义市场经济体制的特点和优越性是什么?
把社会主义制度和市场经济有机结合起来，充分发挥市场在资源配置中的决定性作用，更好
发挥政府作用，进行科学宏观调控，激发各类市场主体的活力，为人民对美好生活的需求提
供保障。
* 我国国家机构
** 国家权力机关
*** 我国国家权力机关是什么?其产生方式和职责分别是什么?
1) 我国的国家权力机关是人民代表大会，包括全国人民代表大会和地方各级人民代表大会。
2) 产生方式：由人民选举的代表组成。
3) 职责：代表人民统一行使国家权力，决定全国和地方的重大事务。
*** 全国人民代表大会的性质和地位分别是什么?
1) 性质：是最高国家权力机关，代表全国人民统一行使国家权力。
2) 地位：在整个国家机关体系中居于最高地位。
*** 地方各级人民代表大会的性质及其与其他地方国家机关的关系是什么?
1) 性质：是地方国家权力机关。它是本行政区域内人民行使国家权力的机关。
2) 与其他地方国家机关的关系：地方国家行政机关、监察机关、审判机关和检察机关都由
   本级人民代表大会产生，对它负责，受它监督。
*** 人民代表大会的职权
| 职权   | 行使职权的主体             | 职权的内容               | 区分关键词               |
|--------+----------------------------+--------------------------+--------------------------|
|        | 全国人大及其常委会         | 行使国家立法权           |                          |
|        |                            |                          |                          |
| 立法权 | 省、自治区、直辖市以及设   |                          | "制定" "修改" "废止"法律 |
|        | 区的市、自治州的人大及     | 行使地方立法权           |                          |
|        | 其常委会                   |                          |                          |
|--------+----------------------------+--------------------------+--------------------------|
|        |                            | 重大事项决定权。决定、批 |                          |
| 决定权 | 各级人大和县级以上各级     | 准、表决、通过工作报告以 | "批准" "表决" "通过" 等  |
|        | 人大常委会                 | 及关于国家大政方针、重大 |                          |
|        |                            | 事项、规划的通过等       |                          |
|--------+----------------------------+--------------------------+--------------------------|
|        | 各级人大和县级以上各级     | 对相关国家机关领导人员   |                          |
| 任免权 | 人大常委会                 | 及其他组成人员进行选     | "选举" "任命" "罢免" 等  |
|        |                            | 举、决定、罢免的权力     |                          |
|--------+----------------------------+--------------------------+--------------------------|
|        | 全国人民代表大会及其常委会 | 监督宪法和法律的实施     |                          |
|        |                            |                          |                          |
| 监督权 | 县级以上人大及其常委会     | 监督本级国家行政机关、   | "听取" "审议" 等         |
|        |                            | 监察机关、审判机关、检察 |                          |
|        |                            | 机关的工作               |                          |
** 二、中华人民共和国主席
*** 中华人民共和国主席的性质、产生、当选条条件及任期分别是什么？
1) 性质：中华人民共和国主席是中华人民共共和国的国家元首,代表中华人民共和国行使宪
   法赋予的职权。
2) 产生：中华人民共和国主席、副主席由全国人民代表大会选举。
3) 条件：
   1) 有选举权和被选举权的中华人民民共和国公民。
   2) 年满四十五周岁。
4) 任期：中华人民共和国主席、副主席每届任期同全国人民代表大会每届任期相同。
*** 国家主席有哪些职权？
| 职权               | 内容                                                                                                                                              |
|--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------|
| 公布法律、发布命令 | 根据全国人民代表大会的决定和全国人民代表大会常务委员会的决定，公布法律，发布特赦令，宣布进入紧急状态，宣布战争状态，发布动员令                    |
| 任免权             | 根据全国人民代表大会的决定和全国人民代表大会常务委员会的决定，任免国务院总理、副总理、国务委员、各部部长、各委员会主任、审计长、秘书长            |
| 外事权             | 代表中华人民共和国，进行国事活动，接受外国使节;根据全国人民代表大会常务委员会的决定，派遣和召回驻外全权代表，批准和废除同外国缔结的条约和重要协定 |
| 授予荣誉权         | 根据全国人民代表大会常务委员会的决定，授予国家勋章、国家荣誉称号奖章                                                                              |
** 国家行政机关
*** 行政机关的含义及组成分别是什么?
1) 含义：行政机关是依据宪法设立的，依法行使国家行政职权，组织和管理国家行政事务
   的国家机关。
2) 组成：我国行政机关由国务院及其领导的地方各级人民政府组成。国务院，即中央人民
   政府，是我国最高行政机关
*** 国家行政机关和国家权力机关的关系是什么?
1) 国家行政机关是国家权力机关的执行机关，负责贯彻执行国家权力机关通过的有关法律、
   决议和决定。
2) 各级人民政府对本级人民代表大会负责并报告工作;县级以上各级人民政府在本级人民代
   表大会闭会期间，对本级人大常委会负责并报告工作。
*** 行政机关和人民的关系是什么?
1) 人民是国家的主人，行政机关的权力来自人民，是人民授予的。
2) 行政机关必须全心全意为人民服务，努力建设人民满意的服务型政府。
*** 行政机关的职权有哪些?
1) 根据宪法，我国县级以上人民政府主要管理经济、教育、科学、文化、卫生、体育事业、
   城乡建设事业和财政、民政、公安、民族事务、司法行政、计划生育等行政工作。
2) 行政机关层级不同，职权也不同。国务院统一领导地方各级人民政府。
*** 行政机关怎样做到依法行政?
1) 内部：
   1) 严格遵照宪法和法律行使职权，坚持法定职责必须为，法无授权不可为。
   2) 勇于负责、敢于担当，坚决纠正不作为、乱作为，坚决克服懒政、怠政。
2) 外部：为了防止工作人员出现履职不力、监管缺失、失职渎职、徇私枉法等问题，必须
   加强对行政权的监督和制约，切实做到有权必有责，用权受监督，权责要对等，失责要
   追究，侵权要赔偿。
** 国家监察机关
*** 监察委员会的性质、监察对象和组织体系(构成)分别是什么?
1) 性质：监察委员会是行使国家监察职能的专责机关。
2) 监察对象：对所有行使公权力的公职人员进行监察，调查职务违法和职务犯罪，开展廉
   政建设和反腐败工作，实现国家监察全面覆盖。
3) 组织体系(构成)：我国设立国家监察委员会和地方各级监察委员会。
   1) 国家监察委员会是最高监察机关，领导地方各级监察委员会的工作。
   2) 上级监察委员会领导下级监察委员会的工作。
   3) 地方各级监察委员会负责本行政区域内的监察工作。
*** 国家监察机关与国家权力机关的关系是什么?
1) 国家监察机关由国家权力机关产生，对它负责，受它监督。
2) 国家监察委员会由国家最高权力机关产生，对它负责，受它监督。
3) 地方各级监察委员会由本级国家权力机关产生，对它负责，受它监督，同时还对上一级
   监察委员会负责，受它监督。
*** 监察委员会的工作原则是什么?
1) 监察委员会依照法律规定独立行使监察权，不受行政机关、社会团体和个人的干涉。
2) 监察机关办理职务违法和职务犯罪案件，应当与审判机关、检察机关、执法部门互相配
   合，互相制约。
3) 监察机关在工作中需要协助的，有关机关和单位应当根据监察机关的要求依法予以协助
*** 监察机关的职责有哪些？

* To Be Continuied
#+begin_verse
注意！本材料由我纯手工打入，难免会有错字。请谅解。
内容取自 /《广东中考 高分突破》道德与法治 八年级下册 知识宝典/
#+end_verse
* Footnotes

[fn:9]历史突然又活过来开始攻击我（八下历史第一课里就有） 
[fn:8]人大是根本制度，政治协商制度、民族区域自治制度等等都是基本制度（非根本）
/（历史的DNA动了）/

[fn:7]如：劳动、受教育 
[fn:6]如：表彰科学研究、组织艺术表演、修建阅览室等

[fn:5]让我想起《中华民国临时约法》 
[fn:4]/依法治国才是基本原则！/

[fn:3]宪法第三条 
[fn:2]宪法第三条 

[fn:1]宪法第二十九条 
