#+title: Sword Art Online WEB版 第8章
#+date: <2025-09-25 五 18:44>
#+setupfile: ../setup.setup
* Header
#+begin_src text
︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵
更多小说欢迎添加【QQ群】：239789013
打开支付宝首页搜 531912956 领红包，最高99元
每天可以领一个，领到大红包的小伙伴赶紧使用哦！
本作品来自互联网及出版图书，
版权归原作者所有，如喜欢请购买正版。
︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶
#+end_src

#+begin_src text
==========================================
    Sword Art Online     
              Alicization
    Web版
==========================================
    作者：川原 礫
==========================================
    翻译：acadsh(LKID: kazeno)
               rkl(LKID: reekilynn)
    校对/润色：rkl(LKID: reekilynn)
    仅供个人学习交流使用
    禁作商业用途
    下载后请在24小时内删除
    请尊重翻译者的辛勤劳动
==========================================
#+end_src
* 转章Ⅱ 
把洗好的盘子放到晾架里，爱丽丝一边用围裙把手擦干，不经意地往窗外眺望。

透过粗制玻璃看见的树梢，因为这几天骤冷的天气，难得变黄变红的树叶也已纷纷散落。冬
天来的还是比央都快一些。

然而，从久违的清澈如透的青空洒入到索尔斯的阳光让人感到阵阵暖意。近处粗大的树枝上，
一对爬上树的兔子相互依偎，闭合着双眼看似很舒服地享受着日光浴。

不知不觉微笑地看了一阵子，爱丽丝转过头说道：“欸，今天的天气不错，去东边的山丘走
走吧。一定能看到很远的地方。”

没有回应。

在只有两个房间的狭小木制小屋中，大房间的中央放置着一张圆桌。旁边简朴的椅子上坐着
的黑发少年，呆呆地俯视着。

很瘦。原本就没长多少肉，如今竟已比爱丽丝还要纤细了。即便穿上宽松的便服，也能看出
他身上只剩下骨头了。右手边垂着空荡荡的袖子，更是让人感到心痛。

但是，更让人心寒的是他的表情。跟头发一样漆黑的瞳孔中，没有一丝的光辉。映衬着他封
闭了内心的空洞的双眸，绝不会正面去看任何人。

爱丽丝抑制住内心已经感觉过无数次的刺痛，用更加明亮的声音继续说道：

“不过，还是穿厚点好哦。你等一下，我就去准备。”

随即脱下围裙，挂到洗碗槽边上，然后快步走向卧室。

爱丽丝把长长的金发扎在后面，盖上棉布方巾。再把墙上挂着的两件羊毛外套中较小的一件
披在身上，并把另一件夹在腋窝里，回到了客厅。

少年丝毫没有改变姿势，只是重复着缓慢地呼吸。爱丽丝把手轻轻地放在他背上，催促他起
来。少年这才摇晃着膝盖慢慢地起身。

然而，可能的自发行动也就到此为止了，完全没迈出一Mel。爱丽丝移开椅子，把外套披上
去，并绕到前面用皮绳紧紧扣住。

再坚持一下哦。爱丽丝说了一声便急急忙忙跑到客厅的一角。

放在那里的是，用明亮的白茶色木材所制作的椅子。不过，跟刚才少年所坐的不同，四只脚
都是用圆木锯成圆块并在中间嵌入钢芯做成的车轮。是在森林深处独居的一个名叫加里塔的
老人精心制作的。

爱丽丝握住附在轮椅靠背上的握柄，滚动着移到少年的背后。让看起来摇摇欲坠的少年轻轻
坐上去，然后把一块毛线制作的披巾盖在他身前。

“好了！那，我们走吧。”

用手敲了一下少年的肩膀，然后握住把手，嗙地一下推着椅子微微地向着小屋的房门滚去。
这时，少年不经意的改变了一下脸的角度，抬起左右，伸向一边的墙壁开口道：

“那—…那—”

擦过的声音，跟他的脸部有着不同的感情。然而爱丽丝立刻就察觉到了少年的请求。

“啊，抱歉。马上拿给你。”

少年手指着的南边的墙上，用结实的金属制品挂着三把剑。

    右边，是爱丽丝的所有物，黄金的长剑“金木犀剑”。

左边，是少年以前佩带的漆黑的长剑“夜空之剑”

然后中间——是为黑剑命名，如今却已不在的一个少年的纯白的长剑“青蔷薇之剑”。

爱丽丝先把沉重的漆黑的剑从墙上吃力地取下并抱住。然后取出中间的白鞘。它的重量只有
黑剑的一半。因为收着的刀身已经没了一半以上。

爱丽丝抱着两把剑回到门边，放到少年的膝盖上。少年用左手紧紧抱住他们，再次低下脸庞。
他绝不会再放开这两把武器。他只有在找剑的时候会表现出某种反应。

“……那，走吧，桐人”

说完，爱丽丝再次忍住刺向胸中的疼痛，推动了比刚才沉重数倍的轮椅。

出门后，走下非石阶而是平缓的木板搭起的短坡，一阵清凉的微风和充满滋润的阳光包围了
二人。

小屋是建立在森林深处裂开的一块圆形草地上。是爱丽丝亲自劈开圆木，把皮剥去，经加里
塔老人帮忙建造起来的。虽然略显丑陋，不过尽是用的优先度高的木材，建的还是很结实的。
只是，被老人说了数十次从未见过如此蛮力的女孩子。

老人也说过，森林的这块空地曾经是小时候爱丽丝和青蔷薇的所有者尤吉欧两人的游乐场。
当然爱丽丝没有那份记忆。爱丽丝只是跟加里塔老人和其他人说她失去了以前的所有记忆，
然而现实是，整合骑士爱丽丝·Synthesis·Fifty侵占了他们所认识的露莉德出生的爱丽丝·
青贝尔克的身体。可能的话，现在立刻就想把身体归还给她。可是原本的爱丽丝已经随着尤
吉欧离开了这个世界。

挥去一瞬的沉思，爱丽丝推动轮椅向横切草地的小径前进。

小径横穿包围外界的森林，由东向西延伸开去。往西走不到一个小时就能到达露莉德村，不
过无事的时候无论如何都不想去造访。从右前方感受索尔斯的光的同时，走向了东边的小径。

爱丽丝他们在十月即将结束、因季节变迁红叶逐渐飘落的森林中缓缓前行。

“桐人，冷吗？”

虽然搭了话，却当然的没有回答。即使是裸身处在极寒的大雪之中，恐怕现在的桐人也不会
吭一声，只是任由身体冻僵，等待天命耗尽吧。爱丽丝探头确认了一下，上衣的领子都还紧
紧围着。

当然了，想用热因系的法术完全防御周围冷气的进入也是很容易的。只不过，本来就已处在
微妙的立场当中了，还是希望避免被村民看到使用高度的术式而产生奇怪的留言。

推着沉重的轮椅走了大约10分钟，便看见了前方树丛的间隙。

前方是被短草覆盖的小高丘。在没有道路的斜坡上，爱丽丝毫不费劲地推着轮椅，不一会儿
功夫就到达了天边。

视野豁然开朗。广阔的露露湖那湛蓝的水面连着深处的湿地带一望无际。左手边耸立的山脉
宛如冲入天际的墙壁，从正面往右边深处练成一道弧线。昔日，驾驭飞龙轻松翻越那重重山
峰的情景就像是梦幻一般。

面临如此宽广美丽的景色，桐人却视若无物，只是用空洞的黑眼球呆呆地对着虚空。

爱丽丝在旁边坐下，把身体靠在椅子上，喃喃自语道：

“真美丽啊。比挂在大圣堂里的画美丽多了。”

“……是你所守护的世界哦。”

一只白色的水鸟滑过眼底的湖水，荡起点点涟漪，然后高飞而去。

 

不知道坐了多久。

回过神来的时候，索尔斯已经升到挺高的位置了。到回小屋准备午饭的时间了。虽然对自己
的空腹完全不在意，不过，为了一次只想吃一点点的桐人，哪怕是一餐也是不能疏忽的。

爱丽丝站起来，对桐人说回去吧。就在她握住把手的时候——

爱丽丝注意到了踏草登上山丘的细小的脚步声，立刻回头看去。

靠近过来的，是一名戴着黑纱巾并用修道衣把矮小的身体裹的严严实实的少女。在如孩子般
可爱的脸上，一边露出闪耀的笑容一边挥着手。

“姐姐！！”

兴奋的声音乘着微风而至。爱丽丝也边以笑容回应边挥了挥手。

少女在最后10Mel的地方急势冲了上来，并在眼前停住。丝毫不断气地又说了一遍：

“早上好，爱丽丝姐姐！”

又迅速地转身，探了一下轮椅上的桐人，更加精神地喊道：

“桐人也早！”

对桐人的毫无反应完全不在乎一样嫣然微笑的脸，在看到桐人膝盖上的两把剑的瞬间，少女
略感心痛地轻言道：

“……早上好，尤吉欧。”

指尖轻轻地抚摸过青蔷薇的剑鞘，少女再次面向爱丽丝。爱丽丝感到内心犹如一阵暖流经过，
回应道：

“早上好，西露卡。你竟然知道这个地方啊。”

不称呼她为西露卡妹妹也是最近才习惯过来的。自己越是怜爱作为这世上唯一的妹妹的少女，
越是责怪自己是否有感受这份温暖的资格。

西露卡也许早已察觉到爱丽丝无法摆脱的纠葛，毫无顾虑地笑道：

“我可不是用神圣术找到这里的哦。姐姐的所在我立刻就能知道的。我带了早上刚挤出的牛
奶和一点苹果芝士派来。已经放到家里的桌子上，中午的时候吃吧。”

“谢谢，帮了我大忙。我还在犹豫要做什么好呢。”

“以姐姐的做饭手艺，桐人说不定哪天就会逃出去的！”

爱丽丝一边笑着面向啊哈哈哈笑着的西露卡，一边举起右手道：

“哇，你竟敢说！怎么说，我最近也领悟了不少的。”

欢闹的同时，西露卡轻巧的避开爱丽丝的手，蹦入她怀里。就这样闭上双眼，好像很舒服似
的蹭着爱丽丝的胸部。爱丽丝也轻轻地抱住比自己矮小的多的妹妹。

只有这个瞬间，爱丽丝真的想忘记去责备自己的罪过。如果能消去舍弃了剑，逃避骑士的责
务，在森林深处过着安稳日子的这份罪恶感，会是多么的安心啊。因为在做着这种事的同时，
眼前耸立的终焉山脉的另一边，终结的时刻正日渐到来。

 

半年前，那场激斗的最终幕——。

身负濒死重伤，完全动弹不得的身体躺在大圣堂最顶层的地板上，爱丽丝恍惚地感知到战斗
的结果。

管理员跟桐人的死斗。

被丘德尔金执念之火卷入，一同消失的最高司祭。桐人的搭档尤吉欧的死。只有他临终时的
话，在断断续续的记忆中依然鲜明如炙。

另外，还有一个就是，从不可思议的水晶工艺品中传出的声音和桐人之间的对话。几乎无法
理解的奇怪对话终结之时，突然令桐人的身体僵直倒下——世界完全沉默了。

总算恢复了少许的天命，爱丽丝能够行动之时，玻璃窗外，天空正逐渐被索尔斯之光所浸染。
爱丽丝以射入的曙光作为神圣力之源，先治愈倒下的桐人。然而他的意识却无法恢复，只好
让他就这样睡着并给自己施展治愈术，之后又调查了跟桐人交谈的水晶工艺品。

可是，闪耀着紫色光辉的表面已经完全变黑，无论如何翻弄都不再发光。

爱丽丝无计可施，坐住了。虽然相信了桐人的话，为了守护世界的人们和不知身在何处的妹
妹而与绝对的支配者管理员战斗，万没想到自己竟然可以生存下来。认为自己会死在这里，
做好了觉悟才置身于最高司祭的剑下，然而命运使然保住了一命。

既然救了我就要负起责任啊，这样对横躺在旁边的桐人呼喊了无数次，但是黑发的少年却丝
毫不打算张开眼皮。爱丽丝觉得也许他是在说以后的事自己去想吧。

抱膝坐了相当长一段时间后，爱丽丝终于站起行动了。用好不容易回复的金木犀剑费劲心机
地破坏了出入口附近的地板，然后从出现的螺旋楼梯一个人走了下去。

穿过失去主人的丘德尔金的房间，和至今还噗嗤噗嗤地持续着术式的元老大厅，目的地是剑
术老师的所在。在冰几乎融化殆尽的大浴场中，大字悬浮的整合骑士长贝尔库利的身体，幸
好已经从石化术中解放了。爷爷！爱丽丝呼喊道。大个子猛地拍了两下脸，就像是从久梦初
醒一样伸了个懒腰，打了个夸张的喷嚏后，终于醒过来了。

好不容易从紧张中解放的爱丽丝破涕为笑，哽咽着总算是说明白了状况。贝尔库利以严厉的
神色听完一切后，只说了一句话，难为你了，孩子。

之后的事就交给我，如此宣布的贝尔库利迅速行动起来。他把在蔷薇园发现的被桐人他们打
败，却不知为何已经完全治愈的副长法娜提欧，还有同样被石化拘束的迪索鲁巴特和艾尔德
利耶耶这些主干的整合骑士全员都集中到50层的大回廊，把真相尽可能地述说了。

包括跟桐人、尤吉欧战斗的结果，最高司祭管理员战死的事情。

以及最高司祭的人界防御计划，是把半数的人类变成剑骨之兵这件事。

还有骑士团的上部组织——元老院的实体，只有丘德尔金一人的事实。

隐瞒的，只有整合骑士的来历而已。贝尔库利认为原本就对“从神界而来的召唤”有所怀疑
的他还能接受真相，其他的骑士们是不可能的。他只对爱丽丝说，还需要等待解明留在最上
层的数十把剑和神图的秘密。

然而，尽管如此，骑士们还是相当的混乱。也难怪，至今为止，在如同永远的岁月里，最高
司祭曾是唯一绝对的支配者。

讨论的结果，他们选择无论如何都要听从骑士长。讽刺的是，这也许只是被管理员施加了强
制从属术的结果。因为就算最高司祭被消灭了，他们也是隶属于“教会”，而骑士长贝尔库
利是神圣教会的最高权力者也是不容置疑的。

于是，贝尔库利以惊人的精神力向着本来的任务，“守护人界”迈进。他应该也彷徨过，他
已经知道自己被夺走的爱人的记忆，就在触手可及的地方。

但是，比起回复记忆，他选择了准备防御即将到来的黑暗的入侵这个职责。他开始了在数日
内重整整合骑士团的体势，并为了能用于实战而重编四帝国的近卫军的新任务。

见此，爱丽丝与昏睡状态的桐人乘上自己的飞龙悄悄地离开了央都。原因是部分骑士要求处
决叛逆者的意见并没有消失。这是距最上层的激斗5天后的事情。

无尽烦恼的结果，引缰前往北方最边远的村子露莉德又用了三天。在央都的郊外野营期间，
桐人也未曾醒过。要充分治疗，一间像样的屋子和床是必不可少的。但是，想在城里的旅馆
住又没有民间货币在手，也不想摆出整合骑士的权威。

唯一的希望——虽然失去了记忆，在故乡生活的家人应该会热情地欢迎自己吧，爱丽丝抱着
这样的期待，径直往北飞去，横贯诺兰高尔思帝国，到达了与终焉山脉的草原相接，被深邃
的森林所拥抱的小村。

为了不让村民们发现飞龙，低空飞行后停在了离村子不远的森林里。爱丽丝吩咐龙要守护好
三把剑后，背上闭着眼的桐人徒步进入了露莉德村。

无论是横穿翠绿的麦田时，还是从小户农家旁边走过，渡过小河上的桥时，都被众多的村民
们注目。但是，那些都是惊讶和警戒的神色。

在土石交界的路段，从小小的警卫室里冲过来一个年轻人，长着少许雀斑的脸涨红着拦住了
爱丽丝的去路。

站住，外人不能随便进入哦！

边喊着的同时拔出了廉价的剑，毫不客气的把剑端指在眼前的卫士，先是看了一眼背上的桐
人的脸，感觉奇怪似的歪着脖子。自言自语地说，咦，他不是……、之后又盯着爱丽丝看了
一下，然后突然睁圆着眼跟嘴巴。

你……你，难道是。

听了卫士的话，爱丽丝稍微安心了。看来过了九年还是认得自己。她边想边选择语言告诉卫
士。

她是爱丽丝?青贝尔克。并让他去叫一下作为村长的父亲加斯胡特?青贝尔克。

在大圣堂外壁，仅仅听桐人说过一次的名字，竟然没有忘记。卫士的脸色由红变绿，等，等，
等一下，大叫着跑了开去。

晌午过后的村子转瞬间如蜂巢捅破一般骚动起来。从小孩到大人，就像是突然从哪里冒出来
的一样聚集在一起，把爱丽丝远远围住并小声地交谈着。

这时爱丽丝再次感到不安。虽然知道了自己的身世，村民们却浮现出更为警戒的脸色，还带
着不少的嫌恶。

数分钟后，人墙中大步走近来的，是个嘴和下巴都留着整齐胡子的半老的男人。

男人见到爱丽丝的瞬间，脸上扭曲着难言之隐的表情。其深处究竟藏着怎样的感情，爱丽丝
却无法察觉。

慢慢地，像是害怕着什么的步调走到面前的男人，用沙哑的声音说道：

“是爱丽丝，吗？”

然后继续说道：

“为什么在这里？你的罪被宽恕了吗？”

既不是拥抱，也没有泪水，听到“父亲”如此信口开河，爱丽丝感觉手脚都变的冰冷。然而，
她拼命地回看着对方的眼，回答道：

“先不管处罚，我失去了在这个村子里生活的所有记忆。可是，除这以外我没有可以去的地
方。”

能说出的最大限度的真实。

加斯胡特紧紧闭上双眼，抬起头，然后突然转过身去。

越肩传来的话是：

“你走吧。这个村子不允许罪人进入。”

也许是感觉到了爱丽丝因一瞬间的回想而僵直了身体，西露卡抬起头，稍微倾斜了一下脑袋。

“姐姐……？”

被最爱的妹妹担心地询问，爱丽丝一边微笑地简短回答道：

“不……没什么。好了，我们回去吧，西露卡”

那天，受到沉重打击准备悄然回到森林深处的爱丽丝，被树丛阴影里的西露卡叫住。如果没
有明知有违身为村长的父亲的意愿，还叫住爱丽丝的她的勇气，以及她介绍的加里塔老人的
善意，爱丽丝也许到现在还是个无依无靠的逃亡者彷徨在荒野之中。

对西露卡而言，应该也不是件能轻易接受的事情。

唯一的姐姐，竟然忘记了过去的一切。两年前还有所来往的桐人在昏睡。还有，如同哥哥般
存在的尤吉欧的死。

但是，看见西露卡流泪也就一次而已。从那以后都笑容不绝，精神饱满地活动着。对于她内
心的坚强和体贴，不得不让爱丽丝每天感谢和惊叹。比教会司祭们的神圣术更加强大，比整
合骑士的剑更加尊贵。

与此同时，自己是多么的空虚。

得到老人的帮助，在村子边界外的森林搭建了虽小却很结实的住所后，爱丽丝立刻对沉睡的
桐人施展了大规模的回复术。

在广袤的森林中精选最受泰拉利亚的恩宠所润泽的地点，遮蔽索尔斯之光的云一片都没有的
日子里，把那些庞大的神圣力毫无保留地回收并压缩，注入桐人的体内。

产生的治愈之力达到了桐人天命的数十倍之多，而爱丽丝也自负能够施展如此高位术的人在
整个人界也只有自己一人。她相信，无论桐人受的伤有多重，包括被斩掉的右臂在内，都能
在瞬间回复，恍若无事般醒来。

可是，结果却是残酷的。

无论注入再多的蓝色灵光，就像伤口自己在拒绝治愈般，右臂无法恢复——而好不容易睁开
的双眼，漆黑的眼瞳里，没有一丝意志的光芒。

数小时施术的之后终于放弃的时候，也许是受到力的余波，自己脸上扎着的绷带里头，右眼
一切如初般再生了，爱丽丝却只感觉那是在嘲笑自己的无能。

之后，桐人的心完全没有回归的征兆。

虽然西露卡再三鼓励爱丽丝道，姐姐如此拼命地照顾着，有朝一日定能回复往日的桐人。但
爱丽丝却逐渐感到自己做不到而深深恐惧着。

因为，自己只是一个没有心的人形骑士而已。

 

踏着干枯的杂草前行的西露卡，不经意地放缓了步调，爱丽丝又从思虑中回过神来。

察觉到小修道衣的后背，似乎想说什么而踌躇着的爱丽丝稍微放慢了推轮椅的速度问道：

“怎么了，西露卡？有心事？”

“是这样的……、巴博萨的老爷爷，又请求帮忙处理不倒之树了……”

“什么呀，就那样。这又不是你该烦恼的事啊。”

爱丽丝一微笑，西露卡就不由得愤慨地撅起嘴，两手插在胸前。

“那些人太任意了！他们害怕姐姐还把你赶出了村子，一遇到麻烦却又想找你帮忙。我之前
也说过了，姐姐你大可以拒绝的啊。需要什么，我都会带给你的。”

这回爱丽丝稍微出声笑了起来，劝解道：

“谢谢你，西露卡。不过你真的不用放在心上。光是让我住在村子附近就很感激了。让桐人
吃过午餐之后马上就去。就在南边的田里对吧。”

“……嗯。不过……明年春天我就从修女见习升格为准修女了，虽然只有一点还是能拿到薪
水的。从今以后，再也不会让姐姐去帮助那种人了。”

爱丽丝用右手抚摸着跑到身旁以坚毅的表情宣告道的西露卡的头。

“谢谢了……、不过，只要有你在身边，我就感到很幸福了……”

在小屋所在的草地中央，依依不舍的与西露卡再三挥手道别以后，爱丽丝麻利地准备起午餐。

最近，总算熟悉了各种家务事，可做饭的手艺却始终无从以对。比起金木犀剑，从村里买来
的菜刀就像玩具一样又轻又不可靠，小心翼翼地切开材料就用了三十分钟乃至一个小时。

今天幸好有西露卡带来了马上就能吃的派。爱丽丝用叉子切成小块喂到桐人嘴里。耐心地等
待桐人张口，然后轻轻放入他嘴里后，仿佛回忆起起吃饭的不是本人而是嘴巴一样，慢慢地，
慢慢地咀嚼着。

花了很长时间让桐人吃了一小块，又用勺子喂他喝了一口牛奶的同时，爱丽丝用心地品尝着
朴素的手制派。回想起在大圣堂的时候，从四帝国各地收集来的美味佳肴摆满了巨大的桌子，
对随意吃了一点就让人撤下的自己感到无比的羞愧。

爱丽丝收拾完毕之后，再次让桐人穿好外套，把两把剑放到他膝盖。自己也为了藏住身体和
头发而多穿了几件衣服。

推着轮椅来到外面，不知何时已完全改变了方向的阳光从树梢之间洒落大地。最近日子逐渐
变得短暂，午后的天空瞬间改变了颜色。稍微催促着脚步，这次走向了小径的西边。

森林的尽头，等待收割的金黄的麦田豁然开展。沉甸甸的摇坠着麦穗的海洋对面，能看见露
莉德的村子像是要把整个圆形山丘给盖住一般，红色屋顶的房子屋檐并排在一起。在中央，
比周围高出一座尖塔的就是西露卡生活的教会。当然，无论是西露卡也好，指导她的名叫阿
萨利亚的修女也好，对管辖全世界教会组织的中央大圣堂最上层已经成为了无主的废墟之事
都一无所知。

就算大圣堂陷入了大混乱，对地上的工作也不会有任何的影响。禁忌目录依然不变地发挥着
机能，继续束缚着人们的意识。他们真的能拿起刀剑保护国家吗。当然，如果以教会之名下
令的话还是会服从的吧。但是，光是这样是根本无法取得胜利的，至少骑士长贝尔库利是了
然于心的。

既不是武装的优先度，也无关术士的行使权限，最终决定战斗趋势的是意志力。颠覆令人绝
望的战力差，将众多的整合骑士，甚至连最高司祭管理员都打败了的修剑士，桐人的存在就
是证明。

爱丽丝眼睛向下，用余光捕捉着停止农作业，用厌恶的眼神看过来的村民们的身姿，一边自
语道：

“爷爷啊，对他们而言和平也许不过是被人保护的东西。”

而让他们这么想的，正是神圣教会和整合骑士团。像这样在土上生活之后，爱丽丝才开始注
意到，这个世界竟是如此的扭曲。

爱丽丝一边深思着，快步沿着麦田外周的回道，到了扩展到村子南边的开垦地后，停住了轮
椅。

两年前，前面还是比东边森林更加幽深阴暗的原始森林。

然而，那片森林的主人，将神圣力如无底洞般吸入的巨树，被桐人和尤吉欧砍倒。西露卡略
感难过地说过，如今村里的男人们都埋头于开拓田地了。因为在禁忌目录中，严密地规定了
与村子人口相对应的田地面积上限，达到上限后就无法再开垦了。所以在此之前，为了确保
比其他的农户拥有更多的土地，男人们都充满了杀气。

眼前呈现的是被野蛮翻掘的黑土所描绘出的半圆，其对面数十个村民正积极地击响着斧声。
其中指挥着众多人数，叫这唤那的大肚男，就是奈格鲁·巴博萨这个村中第一大农户之长。
全族人数比现任村长青贝尔克家还多，其自大程度连身为原整合骑士的爱丽丝都感到吃惊。

虽然没劲，爱丽丝还是推着轮椅沿着被踩硬的小路前行。过去，被桐人砍倒的巨树如今只剩
下一丝的痕迹。而即使经过那开始腐朽的黑色树桩，也看不到桐人有任何反应，只是依旧低
头抱着两把剑。

最先注意到二人的，是坐在刚砍倒的树干边狼吞虎咽地吃着豪华便当的巴博萨一族的年轻人。
年约十五六岁的这些人，用仿佛要把厚厚缠着的方巾贯穿一般粘滞的视线打量爱丽丝后，把
目光转移到了轮椅上的桐人身上，小声地谈了什么后发出了让人厌恶的笑声。

爱丽丝无视他们，正打算从前面通过的时候，一个年轻人以松散地大声说道：

“老爷~子，来了哦~”

这时，手拦腰部发声怒骂着的奈格鲁·巴博萨迅速回过头来，满脸油脂的圆脸上浮现得意的
笑容。圆形的鼻子和细长的双眼，让爱丽丝不由地想起了元老丘德尔金而感到一阵寒意。

但爱丽丝还是尽可能地以微笑回赠，稍作解释道：

“你好，巴博萨先生。听说您在找我……”

“哦哦，爱丽丝啊，你终于来了。”

摇晃着圆滚滚的肚子，展开双手迎了过来。爱丽丝怀疑他是不是要拥抱过来而感到毛骨悚然，
幸好似乎因为看到了桐人膝盖上放着的危险武器而放弃了。

相对的，在爱丽丝右边五十Cen的地方站好，奈格鲁吃力地转过身躯，指着森林和开垦地的
交界。

“喏，看到了吧。从昨天早上开始就着折腾那棵白金槲树，十个大男人也才砍了一根手指丁
点儿。”

看了一下，直径有1Mel半左右，巨大的白褐色树的枝干和树根向四面八方伸展开去。仿佛是
在顽强地抵抗开垦者们一般。枝干的一边，有两个大男人正在轮流着用斧头敲打着树皮，然
而造成的浅伤却还不足十Cen。

男人们裸露的上半身被染成了一片绯红，汗水如瀑布般流着。胸口和上臂的肌肉都很结实，
然而也许是平时只拿惯了铁锹和锄头，忽然换成斧头的原因，重心的移动和腰的回转都非常
不

这样看着的时候，其中一个男的右脚一滑，往错误方向砍去的斧头从握柄中间部位啪地一下
折飞了。男人抱着双手蹲在地上怒骂着，周围的伙伴则毫不客气地笑他。

“真是的，这帮蠢猪在干什么啊……”

奈格鲁吼道，然后再次看向爱丽丝。

“那个样子，光那一棵树就不知道要花上多少天了。在我们困扰的时候，利达克的贼人们已
经推进20Mel的土地了！”

一提到规模仅次于巴博萨家的麦农，奈格鲁就气急败坏地用鞋子死劲跺着地面。他喘了两口
气平复了一下心态，一下子就在满是油脂的脸上浮现出笑容。

“所以呢，虽说是每个月一次的约定，真是不好意思啊，这一回还请特别再借我一臂之力吧，
爱丽丝。也许你不记得了，我在你小时候可是经常给你糖果的呢……”

爱丽丝暗自叹息，打断了奈格鲁的话，点头道：

“嗯，没问题，巴博萨先生。如果只是这一回倒是无妨的。”

就是这样，排除阻碍开垦的高优先度的树木和岩石现在成了爱丽丝的天职。当然，并不是被
谁赋予的。远离村子落脚后过了一个月左右，因为泥土崩塌一块大岩石堵住了村子的路，而
爱丽丝一个人就把它推开了。听到传闻后爱丽丝就被拜托帮这样的忙了。

事实上，为了生活也是需要点现金的，所以有了个赚钱的手段也是值得庆幸的。但是西露卡
担心所有委托都言听计从的话，男人们就会无休止地发来请求，所以约定一块开垦地一个月
只帮一次。

从禁忌目录到村子的规章，遵守着一切规则的奈格鲁，会发来这种违反商议的委托，很明显
是他们眼里爱丽丝比村民们的地位更低。对着不知道自己的嘴脸已经被看破，笑嘻嘻地搓着
手地奈格鲁，爱丽丝无言地低下头，放开轮椅的手，向大树走去。

看到爱丽丝的男人，有浮现下流笑容的，也有挑明咂嘴的。不过，现在所有人都清楚爱丽丝
的力量了，大家都离开岗位，远远地围观。

爱丽丝对他们看都不看一眼，靠近白金槲的老树后，用右手轻轻敲了一下树的表面，调出了
丝提西亚视窗。天命数值真的很高。像以前一样用借来的斧头是砍不动的。

先小跑到桐人那里，弯下腰，轻声细语道：

“抱歉，桐人。稍微把你的剑借我一下吧。”

轻轻的把右手搭到黑色长剑的剑鞘上，感到桐人的身体僵直了一丁点。不过，耐心地看着他
虚无的漆黑眼瞳，终于松开了左手的力，从喉咙里发出细微的声音：

“……嗯……”

与其说是意志传达了给他，不如说是记忆的残留。不是桐人的心，而仅仅是回忆的残渣促使
他动了那么一点点。

“谢谢你，桐人。”

爱丽丝轻声说道，把黑色的剑从桐人膝盖上拿起，再次走向大树。

话说回来，真是棵不错的大树。虽然还比不上央都圣托利亚建筑用材的古代树，树龄少说也
有百年了吧。

爱丽丝在内心说了一声对不起后，用劲固定脚步。

右脚向前，左脚在后。左手把“夜空之剑”固定在腰间，右手轻轻搭在用黑色皮革缠着的剑
柄上。

“喂喂，想用那种土气的剑砍倒白金槲树？”

一个男的喊道，周围的人也接着笑了。剑会折断的哦，而且在这之前天都黑了呢。在交头接
耳的喊声中，奈格鲁在后面担心地说道：

“啊，爱丽丝，可以的话尽可能在一个小时内解决吧。”

之前，无论什么树爱丽丝都能用借来的斧头在30分钟内砍倒。之所以花费那么多时间是因为
不想破坏斧头。但是，今天却不用担心武器会折断。夜空之剑虽不及金木犀剑却也是拥有世
界最高级别优先度的神器。

“不，不用那么长时间”

爱丽丝像是自言自语般回答道，然后用力握住剑柄。

“……哈！！”

短暂地呐喊。从双脚下，像爆发似的尘土飞扬。

很久没这样挥过真正的剑了，但身体还是流畅地动了起来。拔刀势的左水平斩，化为一道黑
色的闪电疾驰天际。

周围的人，能看清斩击本身的一个都没有。爱丽丝以将剑向右前方挥斩的姿势停止了动作，
她头上的方巾轻轻的解了开来，长长的金发随风飘逸。

被金色的光芒吸引了眼球的男人们，呆立着把视线转回到大树上，怀疑地歪着头。白褐色光
滑的树皮上，除了他们切开的小口外，没有任何的伤痕。

什么啊，没砍中？在这些声音中，爱丽丝缓缓起身，将漆黑的刀身漂亮地收入鞘中。从脚边
捡起方巾后，指着男人堆中的一部分人说道：

“那边，会倒过去哦”

他们像怀疑什么般紧锁的眉头变为惊愕的神色，是在看到缓慢地倒向自己的大树之后。一边
发出呜哇的悲鸣声一边跳后，在一屁股摔倒在地的男人之间，发出猛烈的倒地声被切断的巨
树横倒在那里。

爱丽丝挥了挥卷起的漫天尘土，略微确认了一下树干的切面。年轮鲜明地浮现，就像打磨过
一般光滑的断面上，只有一个小小的倒刺也没能漏过她的眼。

果然技术变钝了。轻声叹息着转过头去的爱丽丝停了下来。奈格鲁再次满脸笑容地张开双手
急速接近过来。

不自主地将左手拿着的夜空之剑拔出一点点，听到咔镪的剑声奈格鲁赶紧停住。不过笑容却
丝毫不减，从喉咙深处发出厚颜无耻的叫声：

“太，太棒了！何等身手啊！卫士长金古之流根本不值一提！简直是神技呢！怎，怎，怎么
看，爱丽丝，我给你付双倍的人工，一周来一次，不，一天来帮一次忙好吗！！”

对扭曲着圆滚滚的身体，像扭在一起般揉着手的奈格鲁，爱丽丝不客气的摇了摇头。

“不……现在获得的金额已经足够了。”

假如，拿来金木犀剑使用完全支配术的话，别说一天一棵大树了，就算是数分钟内把所见范
围内的整片森林夷为平地也是轻而易举的。但真要这么做了，他们就会要求把土地整备成田
地，打沉重的桩子，甚至要她降雨吧。

嗯啊啊啊啊啊，一边呻吟一边扭着身子的奈格鲁，听到爱丽丝说“请付钱吧”的声音后好像
突然回过神来一样眨起眼睛。

“哦，哦，对对。”

把手伸到怀里，从看起来沉甸甸的皮革袋里，捏出约定好的一枚银币。

奈格鲁把它放到爱丽丝的掌上，还恋恋不舍地接着说：

“那，那这样如何。我现在多给你一枚银币，你这个月就不要去帮利达克那些人了，怎么
样……”

爱丽丝按捺住内心厌倦的叹息，这是耳边传来咯当的响声。立刻抬起头，往声源方向看去。

眼前是轮椅横倒在地，被甩了出去的桐人的瘦弱身体。

虽然没有表情，但感觉他是在拼命地伸着瘦骨如柴的左手。从喉咙里不断地挤出啊～啊～的
细微声音。

伸手的方向，是刚才吃着便当的少年，想以二人之力拿起青蔷微之剑。兴奋着通红的脸叫喊
道：

“呜哇，怎么回事，好重啊！！“

“笨蛋，所以那种女人也能砍倒白金槲树啊？”

“得了好好抓住！”

第三个少年叫喊着，为了拔出剑用两手抓住剑柄身体反向倒去。

听到从剑鞘内部发出的与剑相互咬合的危险声音的爱丽丝，比意识更快的，右脚用力往地面
一踢。

“你们这帮家伙……！！”

听到尖叫声的少年们，呆头呆脑地转向爱丽丝。

也许是看到爱丽丝一瞬间从二十Mel以外来到跟前，毫无紧张感的表情，也感到稍微害怕了。
卷起尘土停下来的爱丽丝面前，三人缓缓退去。

爱丽丝大吸一口气，总算把激动的感情压制下去后，一边帮忙扶起桐人一边低声说道：

“那把剑是这个人的。快还给他。”

听了之后少年们的脸上，浮现出挑战的反抗神色。刚才想要拔出青蔷薇之剑，体格最大长着
一头麦秆色头发的那人，一只手指着桐人，歪着嘴唇笑道：

“我们可是跟他说了把剑借给我们的哦”

回到轮椅的桐人，既没意识到放在肩上的爱丽丝的手，也没在意少年的话，只是向着纯白的
剑伸出左手，漏出极细微的声音。

一边嘲笑着桐人，另一个少年龇牙咧嘴继续道：

“然后呢，他就很大方地借给我们了，对吧？啊~啊~地回答呢”

剩下一个人，也帮腔着笑了起来。

爱丽丝必须极力地抑制住自己右手袭来的强烈颤抖。因为那只手毫无疑问正要拔出提在左手
的夜空之剑。

如果是半年前的自己，绝不会有一丝的踌躇，就将搭在青蔷薇之剑的六只手臂斩飞。整合骑
士不受禁忌目录的一切规制，即使是骑士团的内部规定，也只是以“不敬行为”这样暧昧的
基准允许将处罚对象的天命减少至七成。而且，破除了右眼的封印，现在能真正束缚爱丽丝
的法或规则都已经完全不存在了。

但是——

爱丽丝发痛地咬紧牙关，跟袭来的冲动对抗着。

那些少年，是桐人和尤吉欧，用生命跟灵魂换取的想要守护的“人界之民”。不能伤害他们。
桐人也不希望那样。

数秒间，爱丽丝动也不动，也没发出一声。但是，可能是无法隐藏眼里浮现的杀气吧，少年
们不自觉的像是感到害怕一般退去笑容，闭上了嘴巴。

最终，像是闹别扭一般吐舌道：

 “……知道啦，干嘛摆出那么恐怖的脸啊”

麦秆色头发（的少年）从剑柄拿开。剩下两人估计也达到极限再也支撑不下去了，松了口气
般放开了剑鞘，青蔷微之剑发出沉重的声音横倒在那里。

爱丽丝无言地走前数步，弯下腰，故意用右手的三根手指轻易地拿起白色皮革的鞘。回头的
瞬间，狠狠地瞪了一眼那些捣蛋鬼，回到轮椅处。

用外套的袖子把沾在剑鞘的尘埃擦去后，把黑白两把剑一起放回桐人的膝上。他紧紧地抱住
它们沈默了。

再次看向奈格鲁，富农的头领似乎对这场骚动没有任何的兴趣，已经开始埋头指挥男人们了。
爱丽丝向他怒气冲冲地指这叫那的后背行了个礼，推动轮椅背开始原路返回。

原本在内心狂起的激愤，不知不觉已经变成了冰冷的虚无感。

自从在露莉德近郊生活以来，这样的心情已经不是第一次了。大部分村民们不但不跟爱丽丝
交谈，连灵魂受到伤害的桐人也不当人看。

也不能怪他们。在他们看来，打破禁忌目录的人应该跟暗之国的怪物没什么两样吧。甚会想，
至让爱丽丝他们住在村外，卖她们食物和日用品已经算是仁慈了吧。

但是，同时也会情不自禁地去想，为什么，为了什么。

到底是为了什么，我们要渡过重重的苦难，跟管理员战斗的呢。前最高司祭卡迪纳尔跟尤吉
欧失去了性命，桐人失去了语言和感情，付出了这么多究竟又守护了什么。

这份思考总会得到一个绝对不能说出口的疑问——

那些村民们有守护的价值和意义吗？

可以说，这份迷惑，才是爱丽丝舍弃剑和整合骑士第三位的地位，停留在这块大地的边缘的
原因。

在做着这些事的时候，伊斯塔瓦利耶思帝国边界的“东之大门”里，骑士长贝尔库利所率领
的新生守备军，应该正在为迫至而来的大侵略做着完全的准备。虽说召集了四帝国的近卫军
和各地的卫士队，但士气和武装还有人数都还差得远，从立场而言爱丽丝应该是刻不容缓火
速赶去的。

但是，对现在的爱丽丝来说，金木犀剑太过沉重了。

亲自打败了曾经发誓唯一绝对效忠的最高司祭管理员，领悟到天上既没有神界也没有创世三
神，还知道了太多人类的丑陋。丝毫未怀疑自己的善于正去挥动手中之剑的时刻早已远去了。

现在，爱丽丝真正想守护的人只有三个，妹妹西露卡和加里塔老人，还有桐人而已。不禁想
道，只要能守护他们，就算在这个地方如睡梦般一直生活下去也未曾不可。

用赚取的银币买了一星期份的食物，并背着它们回到东边的森林小屋时，天空已经完全被晚
霞所渲染。

正要开门的爱丽丝，察觉到北方传来细小破风而至的声音。掠过树梢出现在低空的，是巨大
的龙影。爱丽丝的骑龙，名字是雨缘。

飞龙大幅地拍了两下翅膀抵消冲势后，轻轻地降落到草地上。伸长脖子，先是对桐人吹了一
下鼻息，然后把巨大的头靠近爱丽丝。

拨了一下带点绿色的银色柔毛，雨缘就从喉咙发出噜噜噜噜的低鸣。

 “你好像胖了点啊。不是湖里的鱼吃太多了吧？”

爱丽丝带着微笑训斥着。像是难为情一样，雨缘从鼻孔呼地吐了一下气，拖着长长的身体绕
到小屋后面的睡窝去。

几个月前，住所完成那天，爱丽丝取下戴在雨缘头上的银嚼子，解除了所有的拘束术。而且
还命令道“你已经自由了，回到西域的飞龙巢去吧”。但是，龙却不想离开森林。

它自己收集了一些枯草在小屋后面做了个窝，白天随意在森林玩耍，到湖里捕鱼，晚上则必
然回来。爱丽丝也不清楚，天性高傲且凶暴，本来只能用强力的神圣术才能将它压制住的，
究竟为何飞龙会留在这个地方。但是，这九年来一直伴随她翱翔天际的雨缘，凭自己的意愿
留在爱丽丝身边让她很是高兴，并不想赶他走。虽然有时会被村民们看到它飞翔的身影，成
为对爱丽丝的恶意传闻的一个原因，不过事到如今也没什么好在意的了。

爱丽丝对枯麦秆上团起来的雨缘说了声晚安后，推着轮椅进了屋子。

晚餐是豆子炖肉丸。虽然豆子有点硬，肉丸也是大小不均，不过觉得味道还是可以的。当然
了，桐人是不会发表感想的。用小勺子喂进嘴里的东西，都只是时不时咬一下，吞进去而已。

至少，能知道他喜欢吃什么不喜欢吃什么也好。可是算起来跟这个少年说话的时间还不足一
天。西露卡曾经在同一间教会里生活了近两周，但是只记得无论吃什么都很开心地狼吞虎咽。
这点跟桐人还真的很像。

过了一段时间总算把盘子里的东西吃光后，礼貌地说了声“我吃好了”。

擦干洗好的餐具，正要摆入架的时候，平时已经安静入睡的雨缘突然在窗外噜噜噜低鸣起来。

爱丽丝赶紧停下手，侧耳倾听。夹杂在吹过森林的夜风中传来的，毫无疑问是巨大的翅膀扇
起的破风之声。

连打开窗户的锁的闲余都没有，爱丽丝直接冲出前庭仰望着天空。透过断断续续的云层看到
星空的背景里，画着螺旋飞舞而降的黑影，正是龙的翅膀的形状。

“难道是……”

爱丽丝吓了一跳，以为是暗黑骑士越过山脉而来，刚把剑取来的时候，看见了受星光反射闪
闪发光的龙鳞。肩膀稍微了松了一下。包括人界和暗之领域在内，驾驭银鳞飞龙的，只有整
合骑士而已。

但是，还不能过早安心。究竟是谁，为什么会飞来这种边境地方。难道过了半年，反叛者桐
人的肃清论还没有消失吗？

雨缘也从小屋后面爬出来，抬起常常的脖子再次低鸣。

不过，很快就停止了危险的鸣声，转为发出撒娇般的高音。其理由，爱丽丝也立刻明白了。

高明地控制缰绳，几乎不发声响地降落在狭小草地上的骑士的龙，跟雨缘很像，略带青绿的
银鳞。肯定就是她（雨缘）的长兄，名为滝刳。也就是说，其背上所乘的白色盔甲的骑士就
是——。

爱丽丝用生硬的声音向左腰挂着长剑，右腰上扎着鞭子作响着站落到地面的骑士说道：

“……亏你找到了这里啊。来这做什么呢，艾尔德利耶耶。”

高高瘦瘦的整合骑士没有立刻回答，先以流利的动作把手贴在胸口行了一礼。缓缓地取下后
发带有长饰角的帽子，出现的是一头艳丽的淡紫色长卷发，以及对男士而言有点过于华美的
脸。动了动像是涂了口红一般鲜艳的嘴唇，流出音乐似的声音：

“久违了，吾师爱丽丝。虽然着装变了依旧无法掩饰您的美丽。一想到今宵月光照耀下师的
秀发必然更加熠熠生辉，便让吾坐卧不定，速持珍藏之美酒驰来。”

突然伸出藏在背后的左手，拿着的正是一瓶红酒。

爱丽丝无力地叹了口气，看着纯粹的剑术弟子，整合骑士艾尔德利耶
耶·Synthesis·Twentysix。

“……很开心你的伤已经好了，不过你的性格还是一点都没变啊。再看一下，你有点像元老
丘德尔金啊。”

爱丽丝背着“诶”地发出奇怪声音的艾尔德利耶，往小屋走去。

“等，等等，爱丽丝小姐……”

“要是有正经事要说就到里面去吧。没有的话你就在那里一个人喝酒好了，喝多少都可以。”

爱丽丝稍微抬头看了一眼半年不见，高兴地互相蹭着头的滝刳和雨缘兄妹，快步回到了小屋。

乖乖跟进去的艾尔德利耶珍奇地环视了一圈狭小的屋子后，瞥了一眼在圆桌边低着头的桐人，
细长清秀的眼稍微咪了一下。但之后就像是已经决定无视曾经的剑敌般，迅速溜到圆桌里头，
为爱丽丝拉出椅子。

“……”

觉得道谢有点很傻的感觉，以叹息代替的爱丽丝扑通一声坐了下去。艾尔德利耶擅自坐到对
面，把红酒放在桌上，不经意地抬起头微微抽动了一下他美形的鼻子。

“好香的味道啊，爱丽丝小姐。说起来，我还没吃晚饭呢。”

“什么叫说起来啊。而且，哪有人大老远跑过来却只拿了瓶酒不拿吃的。”

“我可是对三神发过誓这辈子都不会再吃那乱七八糟的东西的。与其用那种东西来填满肚子，
倒不如饿着等天命耗尽……”

那无聊的回答听到一半，爱丽丝就从椅子站起，走到后面的厨房，从炉灶上的铁锅倒了一些
炖菜回到桌子。

艾尔德利耶怀着一瞬的喜悦和随之而来的疑念看了一下无言地被放在眼前的盘子。

“请恕在下冒昧，这个难道是爱丽丝小姐亲自……”

“没错，怎么了。”

“……没。没想到竟然能吃到吾师亲手做的料理！比您授予吾秘剑的型时还要感动呢”

用紧张的表情握住调匙，把豆子放入嘴里的艾尔德利耶再次发表什么之前，爱丽丝清了一下
嗓子再次问道：

“说回来，你是如何找到这里的。无论是什么探查术也不可能从央都找到这里……而且，现
在大圣堂应该也没有那么多空闲特意分一个骑士来找我才对。”

艾尔德利耶没有立刻回答，先贪婪地吃着炖菜一边赞美道“不是挺好吃的嘛”。最后把吃
的干干净净的盘子放下，直视着爱丽丝。

“是因为我跟爱丽丝小姐的灵魂的羁绊……虽然很想这么说，遗憾的是一切只是偶然啦。”

演戏般突然张开右手。

“最近，有情报说有股暗之领域势力在北方活动。虽然南西北的洞窟全都在骑士长指示下击
溃了，但是担心他们死性不改又挖过来，就派我来确认了。”

“什么……从洞窟……”

爱丽丝皱起眉头。

横穿终焉山脉的四个洞窟中，南，西和北边的洞窟极其狭窄，作为暗之军势核心的兽人和洞
穴巨人是过不来的。所以，推算敌军大部队会集结于东之大门，不过骑士长贝尔库极其心细，
在取得指挥权后立刻将三处的洞窟全部弄塌了。

正是知道这点，爱丽丝才选择隐遁这里的，要是敌人挖洞而至情况就有所改变了。此处会瞬
间从和平的边境沦为战火的最前线。

“结果呢……确认他们的行动了吗”

“飞了一整天，别说兽人了，连哥布林都没看到一只呢”

艾尔德利耶再次耸耸肩道。

“估计是新人骑士把兽群之类的错看成军势了……。哦，在下失言了”

说到新人骑士，最新的整合骑士爱丽丝算是最恰当不过了。爱丽丝对着低下头的艾尔德利耶
轻轻地举起手（刀），想道：

“……你有确认洞窟吗？”

“当然。从对面窥探了一下洞窟，所见范围都被岩石所埋了。要挖开它至少要一个部队的洞
穴巨人吧。……确认这点后，准备回到东边的时候，滝刳奇怪地闹了起来。按他的指引飞过
来看看，就落到这里了。说真的，我也吃了一惊呢。太巧合了……不，一定是命运的指引。”

不知不觉打消了演戏般的口吻，艾尔德利耶以刚直的骑士神态继续道：

“既然在这个时候与您再次见面，我就有责任要说。爱丽丝小姐……请回到骑士团来吧！比
起千万援军，我们更需要您这把利剑！！”

为了逃避着毫无疑念的坚强视线，爱丽丝稍微把头低了下来。

自己也明白。

笼罩人界的脆壳，现在正发出声音就像要碎掉一般。而为了支撑它的贝尔库利和守备军正陷
入绝望的境地。

对于骑士长还有无法还清的恩情，也对艾尔德利耶在内的整合骑士团的朋辈们抱有深厚的感
情。但是，这些还不足以让自己战斗。爱丽丝在与最高司祭的一战中已经领悟到，所谓的强
就是意志的强大。如果颠覆天命与权限那让人绝望的战力差的是意志力，那让最强的刀刃变
钝的也一样——。

“……不行”

爱丽丝用极其细微的声音回答道。

艾尔德利耶用尖锐的声音间不容发地问道：

“为什么”

不等回答，他以跟鞭子同样锐利的视线看向左边轮椅上消沉着的少年。

“是因为这个男人吗。冒犯大圣堂的神圣，对众多骑士刀剑相争的家伙，现在又来迷惑爱丽
丝小姐的心吗。既然如此，我现在就帮你斩除这份迷惑！”

对着卡嚓一声往右腕注入力道的艾尔德利耶，爱丽丝双眼射来带着瞬间恢复的过去的剑气。

“住手！”

虽然抑制了音量，整合骑士只是抬起了手指动作就完全停了下来。

“他也不过是为了自己所信的正义而战。否则，为什么我们这些最强的整合骑士，甚至连骑
士长都全被他打败。他的剑之重，跟他直接交过手的你应该最清楚才对。”

伶俐的鼻梁上，感到些许不甘地皱了一下眉头，艾尔德利耶再次松开了身体。他用失去气势
的口吻，轻声自言道：

“……确实，最高司祭大人想把半数的人类变成剑骨之兵的计划，我也很难接受。而如果不
是这家伙挺身而出的话，任何人都不可能阻止计划的实行。更别说，指引他的，是被管理员
大人驱逐的另一个最高司祭。如果骑士长殿下所言真实的话，事到如今我现在也不想再问罪
于这家伙。但是……正因为如此，我才更加不能接受！！”

像是要把至今为止堵塞在胸口的东西一次过吐出来一样，艾尔德利耶大喊起来：

“这个男人，如果他是爱丽丝小姐所说的那样，是超越了整合骑士的最强剑士的话，为什么
现在不拿起剑来战斗！！为什么落得这副可怜的样子，还要束缚着爱丽丝大人！！要守护人
民的话，不就是现在吗！！”

对如喷着火的艾尔德利耶的话，桐人连一丝的反应都没有。只是用微微张开的黑色瞳孔，空
虚地看着桌子。

积蓄的深深的沉默，爱丽丝用平静的声音打破了。

“……对不起，艾尔德利耶。我还是不行。与这个人无关……只是，我的剑力已经失去了。
要是现在跟你对战，估计坚持不了三个回合吧。”

艾尔德利耶吃惊地抬起头，看着爱丽丝。身经百战的骑士的面孔，一瞬间，如孩子般崩溃扭
曲，最后变为略带领悟的微笑。

“……这样啊。那，我也不说什么了……”

慢慢地伸出右手，小声地快速咏唱起神圣术的起句。骑士以熟练的驱式把生成的两个晶素瞬
间变成闪闪发光的薄玻璃杯。

从桌子上拿起红酒瓶子，手指“呯”地一声将瓶颈切断。倾斜着锐利的切面，以优雅的动作
一点点地把深红色的液体注入玻璃杯后，放下瓶子。

“……要是知道这是离别的酒，我就把西域产的两百年年份酒带过来了。”

艾尔德利耶举起其中一个杯子，一口气喝完后轻轻放回桌上。行了一礼后站起来，扬起纯白
的披风转过身去。

“那，就此别过了，师父。您传授的剑诀，我艾尔德利耶一生都不会忘记的。”

“……保重。祝你平安。”

对爱丽丝勉强挤出的这句话，整合骑士隐约的侧脸上以微笑返回，然后嘎吱嘎吱地踏着长靴
走开了。他的背影充满着毫不动摇的剑士的荣耀，爱丽丝不自主地低下了头。

进屋把门关上，几秒钟后滝刳发出一声响鸣，然后传来翅膀挥动的声音。雨缘跟兄长依依惜
别的鼻声，微微刺痛着爱丽丝的胸口。

爱丽丝一时纹丝不动地做着。

最后伸手拿起剩下的酒杯，让酒轻轻流过嘴唇 。半年没喝的红酒，比起甘甜，苦涩的味道
更加强烈地残留在舌头。随后，用尽短暂天命的两只酒杯化作微弱的闪光消灭了。

爱丽丝就这样弯着腰久久地靠在椅背上。不知道从何处远远地传来不知名的野兽的叫声，爱
丽丝终于站了起来。

对轮椅上的少年轻声说道：

“对不起啊，桐人。累了吧，平常的话早就到睡觉的时间了呢。”

然后小心地将手放到肩上扶他起来。为他脱去黑色的便服，穿上质朴的睡衣，把他消瘦的身
体抱入寝室。

让他躺入靠窗的大床里侧，再从头到脚盖上毛毯。半开着眼的桐人眼都不眨地空虚地看着天
花板。

爱丽丝从床边离开，把墙上的灯吹熄，淡蓝色的黑暗降临到室内。即便如此，桐人还是继续
盯着天花板。而数分钟后，像是某种动力被切断了一般，无声地合上了眼。恐怕并不是睡着
了，只是身体对过去的记忆做出了反应，只要在晚上，躺在黑暗的房间里就应该睡觉罢了。

不过，爱丽丝还是舒了口气，从床边离开，给自己换上睡衣。把客厅的灯也灭掉，闩上门后
回到寝室。

拎起毛毯盖到跟前，一丝温暖慢慢包围着全身。

平时，一闭上眼马上就能逃入安稳的睡梦中。但是，今天睡神的一个抚摸却始终没能等到。

离去的艾尔德利耶的背影，耀眼的白色披风上飘逸着的淡紫色卷发的光辉依然留在眼睑深处，
刺的眼里阵阵发痛。

以前，自己的背影中也应该散发着同样的荣光。用自己的剑守护着世界，守护着正义，守护
着所有的善，这份不容置疑的确信无论何时都甚至能贯彻到手指上。但是，这份力量已经消
失殆尽了。

很想问问曾经的弟子，艾尔德利耶，你到底信奉着什么，为了什么而战斗。

但是，爱丽丝做不到。除爱丽丝和贝尔库利外的整合骑士，对最高司祭那可怕的计划只是最
低限度地知道一点而已。就算是艾尔德利耶，也想不到被封印的最上层还留有自己“过去的
记忆”，以及存在于这份记忆中的“最爱的人”已经完全变样的身躯。

因此，他仍然坚信着教会的正确性。他也从未怀疑，总有一天又会有另一名最高司祭站在他
们的顶点，再次迎来光荣的时代。所以，他英勇地执剑驾驭着飞龙。

过不了多久，最后也是最大的攻防战即将打响。骑士们将一个接一个地倒下，战火延伸，最
终连这山脚下的村子也被吞噬。已经没有任何人可以阻止了。要是真的还有那么一点可能性，
那就是大圣堂之战的最后，桐人跟迷之“众神”所交谈的部分——。

“World End Alter”以及“从东大门出去往南”。只有这两句话还隐约留在记忆里。

但是，大门出去，是黑色的荒野及血色的天空所延伸开去的暗之领域。桐人到底想要在那里
做什么 呢？

爱丽丝在枕头上侧了侧脸，眺望着对横躺在床另一边受伤的少年。

在毛毯中缓缓地向他旁边挪动。轻轻地把手伸过去，像做了噩梦的孩子般抱住他的身体。

只剩下骨头的身体细的让人心寒，本该是右手的空洞刺痛着爱丽丝的内心。

再怎么紧紧地抱住，曾经让爱丽丝的内心深深动摇，使她醒悟并指引她的少年也不做半点的
反应。眼毛的前端动都不动一下。爱丽丝深深地感觉到，在这里的，不过是早已燃烧殆尽的
碳壳。就连缓慢悸动的心脏的跳动，也觉得更加悲哀。

如果，现在右手有把剑的话——。

让它同时贯穿贴在一起的两颗心脏，然后让一切就此终结。

这短暂的思考，热泪从眼角溢出，散落在桐人的脖子上。

“告诉我……。该怎么办啊……”

没有回答。

“我……要怎么做啊……”

一片寂静中，只有，晚秋的夜风摇拽着树梢而过。

* 第八章
** 1
就算是自称超一级的天才的比嘉健，也无法事先预测这两个小时里发生的各种事态。

但是，眼前的状况，可以说令人极为震惊，只能用瞠目结舌来形容。

年约十八九岁的玲珑少女，竟然以纤细的单手，把一个比自己高十五厘米的男人的衣领抓了
起来。恶趣味的夏威夷衬衫像要被撕碎般被拉紧，凉鞋的后跟稍微悬浮在空中。

仿佛燃烧起来一般炯炯发光的双眼，直直地盯着陆军中校菊冈诚二郎的女高中生结城明日奈
用可爱的樱唇放出宛如利剑的话：

「如果桐人君就这样回不来的话，我就杀了你，一定！」

从比嘉的位置，无法看到被照明反射的黑边眼镜下菊冈的表情。但是，柔道剑道空手道加起
来不知道有多少段数的干部自卫官，像是被明日奈的话所压倒，咽了咽口水，双手缓缓地举
在身体左右两侧。

「我知道。一定会负起责任的。所以能不能放我下来。」

凝重的沉默充斥着《海龟》主轴最上部的辅助控制室。

无论是坐在控制台上的比嘉，还是站在旁边的神代凛子，又或者留在室内的数名拉斯工作人
员，谁都不敢说一句话。可见，这里最年轻的少女所释放出来的气魄是多么的惊人。原来如
此，那个女孩不愧是从真正的战场生存下来的人。比嘉不禁在意识的一隅如此思考。

终于，明日奈无言地放开了右手。获得解放的菊冈，几乎是掉到了地上。明日奈则是后退着
晃荡了数步。凛子马上扬着白衣飞上前去支撑住她的后背。

女科学家，以从学生时代就未曾变过的包容力将明日奈紧紧地抱住，轻声说道：

「没事的，一定不会有事的。他一定会回来，回到你的身边。」

温润的声音，明日奈瞬间吃惊地睁大了眼睛。然后马上扭曲着脸道：

「……嗯，是啊。对不起……这么慌慌张张的。」

亚丝娜颤抖着声音回答道。眼角溢出了即使在被袭击的时候都未曾流过的眼泪，滴落在凛子
的肩上。

从房间的一角响起一个金属的声音，好不容易稍微缓和了的空气再度绷紧。

滑门被手动拉开，进来的是海军上尉中西。

白色的衬衫被汗水浸透，肩式枪套上露出大型手枪柄的中西，瞅了一眼明日奈和凛子后，对
右边靠里的菊冈快速行了个敬礼。

「报告。一七三〇（时间），确认第一，第二耐压隔墙已完全封闭，非战斗人员往船首区域
的退避也已完成。

菊冈，整理了一下夏威夷衬衫的衣领向前走了出来，大大地点了一下头。

「辛苦了。隔墙能坚持多久？」

「报……要看对方所持的装备，不过小型火器是无法破坏的。用切割刀切断也最少要八个小
时。要是使用C4或者塞姆汀炸药肯定扛不住，不过他们应该没有。主轴下层里……」

「有原子炉和钚电池啊。」

菊冈把话接了过来，将眼镜的托鼻往上推了推，陷入了沉思。

不过马上又抬起头，在腹前用右拳打在左手上，以格外清澈的声音说道：

「好，整理一下状况。」

迅速环视了一下微暗的辅助控制室，继续说道：

「中西，报告一下人员伤亡。」

「是。非战斗人员受轻伤者三人，在船首医务室治疗中。战斗人员，二人重伤二人轻伤。同
样在治疗中，不过没有生命的危险。能战斗的包括两名轻伤者在内共六人。」

「在那种猛烈攻击下，没出现死者算是万幸了……然后，报告一下船体的受损情况。」

「船底船渠的操作室到处是洞。远程关闭已经不可能了。从船渠到主控制室的通路也一样，
不过这都算是微不足道的损伤吧。最严重的是，因为主电源线被切断……虽然能从各副线向
各处供电，不过不重启一下控制系统就无法转动螺旋推进器。」

「没有鳍的海龟啊。而且腹部还被鲨鱼咬了一口呢。」

「是的。主轴下层的A1到A12区域已经完全被占领。」

头发剪的很短，中西不甘地颦蹙起仿佛代表着刚毅本身的脸。相对的，菊冈像教师般长长的
前发皱皱地扬起，坐在控制台上用脚趾摆弄着木屐。

「从Under World主架构到第一STL室，Light-Cube集群，还有主机都落入了他们手中。不
过……好在，他们的目的不是破坏。」

「是……是吗」

「要是只为破坏，就不会实行这种夸张的突击作战，直接用巡航导弹，或是鱼雷打过来了。
这里还有个疑问，他们都是什么人……比嘉君，你怎么看。」

对突然丢过来的话，比嘉眨了几次眼后，转动了还有点麻痹的大脑。

「啊~，也是~啊。」

发着无意义的呻吟转身走向控制台，右手操作鼠标，在大屏幕上调出了设置在船内的监控录
像。

打开的动画窗口虽然又暗又不鲜明，在适当的地方暂停，操作补正面板后，浮现出来的是，
在狭窄的船内通道屈身奔跑的几个黑色人影。脸用护目镜遮着，头上戴着圆形的头盔，手上
拿着威严的来复枪。

「……嗯，如你所见，从头到身，没有任何一处可以识别身份的标记。装备的颜色，规格，
也不是哪里的正规军啊。拿的枪是斯太尔【Steyr】，但这个枪很泛滥……唯一能说的是，
从体格的平均值推测，恐怕不是亚洲人吧。」

「也就是说至少他们不是自卫队员啊。还真是欣慰呢。」

菊冈挠着下巴，随口说着恐怖的事情。把平时笑嘻嘻的眼眯得跟血线般看向屏幕。

「还有一点，这些人知道Project Alicization。」

「确实，从船渠突击，毫不犹豫地就登上了主控制台。目的很直接，肯定是为了夺取真正的
Bottom-Up AI吧。」

也就是说情报严重泄漏了。但是，比嘉并没有直接道出，抑制住想瞭望室内确认每一个人的
脸的冲动，以乐天的口吻继续说道：

「所幸，主控制台的锁定是赶上了。比起物理破坏更确实地，对主框架的直接操作变得不可
能了。还有对Under World的介入，以及把《爱丽丝》的Fluct Light拿到外面去都不可能。」

「但是，我们也一样吧？」

「确实。用这个辅助控制台，也无法进行管理员权限的操作。但是，这不就等于是我们胜利
了吗？只要从担当护卫的护卫舰派突击队员突击，那些人都是小菜一碟啦。」

「我不知道什么菜……不过问题正是这里。」

菊冈不改严肃的神色，视线投向中西。

「怎样，『长门』动了吗？」

「呃……这个嘛……」

中西想要坚定自己的声音而往下巴注入力量，稍微低了一下头。

「长门收到的命令是，好像是，保持现在的距离待机。看来司令部是把我们当成人质了。」

「什……」

比嘉猛地张开下巴。

「……蠢猪啊！全部人员都退避到这边隔离开了啊！？」

以苦涩的声音回答的是菊冈。

「也就是说，那些黑衣人，有自卫队高层的门路。恐怕，让长门发出突击命令，要等到《爱
丽丝》的Light-Cube确保之后了。当然，估计没有时间上限吧……」

「这么说……那些人，不是普通的恐怖分子啊。这下糟了……如果对方也有专家在的话，也
许会被发现呢。回收爱丽丝的近路……」

「从Under World内部操作……毕竟那边连STL也控制了啊。」

比嘉和菊冈同时看向设置在辅助控制室里面墙壁的门。

紧紧关闭的合金制门上，有一个小小的牌匾。上面写着的文字是「第二STL室」。

虽然现在看不见，不过门里头设置着两台Soul Translator。而其中一台上面躺着一名少年。
他从Alicization计划当初就起着重大的作用，而如今更是左右着计划的方向。

菊冈收回视线，交叉着手臂缓缓说道：

「我们最后的希望，又得托付到他身上了。比嘉君……桐人君的状态怎么样？」

传来稍微强烈的呼吸声，比嘉抬起头，跟被凛子抱着，直直地看过来的明日奈那强烈的视线
对上。

反射性地低下了头，犹豫到底要如何说好。但是很快，一个微小却坚定的声音传入比嘉的耳
朵。

「没关系，请说吧，真实的情况。」

深呼吸后比嘉轻轻点了点头。原本，他就不太擅长为顾虑别人而委婉说话的人。

「一句话概括的话……近乎绝望。」

比嘉改以沉重的口吻说道，再次操作起控制台。

黑衣人的画像消失，别的窗口被打开。显示出来的是，不规则闪烁着的虹色点阵。

「这是桐人君的Fluct Light的三次元显像。」

室内的所有人都静静地凝视着屏幕。

「他因为前几天的事件而停止了心跳，所以Fluct Light中的意识层次和肉体层次的联络回
路受到了损伤。为了给那一部分开启新的通道，用解除限制的STL赋予Fluct Light活性。这
本身并不需要什么复杂的操作……可以理解成就是用电刺激来促进代替死掉的脑神经细胞的
回路的生成。」

比嘉歇了一口气，从旁边拿起矿泉水润了润口。

「为了进行这个治疗，必须让他潜入Under World。不让脑的意识层次和肉体层次同等活动
的话，治疗的效果也出不来。所以跟他在六本木的分局潜行时一样，我们隔离了桐人君的记
忆并让他落到Under World的边境。原本是这么设定的。但是，虽然至今还不明白为什么……恐
怕是损伤的影响吧，记忆并没有被隔离。桐人君，以现实世界的桐之谷和人君的状态被放到
了Under World。我们也是在刚刚他从内部跟我们联络的时候才知道的……」

「慢……慢着。」

插进来的是神代凛子的声音。

「那，他是，在STRA环境化的Under World里，以桐之谷君的姿态度过了那些天数吗？内部
是……几个月……」

「……两年半。」

比嘉沉重地答道。

「在这么长的时间里，桐人君在那个世界跟人工Fluct Light们接触。恐怕，他也知道Fluct
Light们迟早会因为实验的终结而全部消灭……所以，他的目标是设置在Under World的中心，
曾经的初始村庄里的与现实世界的联络装置。菊先生，他打算请你保全所有的Fluct Light
呢。」

眼镜反射着屏幕的光，菊冈向旁边瞥了一眼，继续注视着桐之谷和人的Fluct Light。

「……这不是那么简单的事情。因为联络装置是埋在了现在称之为《神圣教会》的统治组织
的大本营里。因为组织所属的Fluct Light们拥有很高的系统访问权限，被设定为一般人的
桐人君是不可能对抗的。原本，在反抗组织的瞬间，他就会『死去』，从Under World注销
的……但是，他却做到了。因为处于袭击状态，无法确认日志所写的具体内容，估计他是得
到了某些人，当然是人工Fluct Light，也就是同伴的协助。在神圣教会一战中，那些同伴
几乎都死了，其结果，在成功打开这边的线路时，他感到深深的自责。可以说，是他自己攻
击了自己的Fluct Light。而就在这时，因为黑衣人切断电源线而产生了浪涌，从STL放出了
超过界限强度的量子光束。桐人君的自我破坏冲动被强化为现实……结果，他的自我被摧毁
了……」

比嘉停了下来，忧郁的沉默降临在辅助控制室。

传来一个沙哑的声音，是发自依然抱着明日奈双肩的凛子。

「自我……被摧毁？这是什么意思？」

「……看看这个。」

比嘉操作中央控制器，把表示桐之谷和人的Fluct Light活性的实时图像放大。

不定形摇晃着的虹色的云中心附近，萦怀着小股如暗黑星云一样虚无的黑暗。

「跟Light-Cube中的人工Fluct Light不同，人类的生体Fluct Light的构造离完全解析还差
很远。不过大概的结构【Maping】已经完成了。这个黑色的孔，原本在这里的是，简单地说
就是『主体』，Self-image。」

「主体……自己规定的自我形象吗？」

「是的。人类所有的选择都会经由『自己在这个状况下是否要实行』这样的Y/N回路来决定。
以凛子前辈为例，你有在牛肉饭专门店的星野屋点过第二碗吗？」

「……才没有。」

「也没有在心里想过，再吃一点吗？」

「对。」

「也就是说那是凛子前辈的Self-image回路处理的结果。同样的，所有的行动如果不通过这
个回路都无法实际行动。桐人的情况，心，灵魂都没有损伤。但是，因为主体被破坏了，无
论是处理外部的输入，还是输出自发的行动都无法做到。他现在能做的……恐怕，只有渗透
在记忆里的反射性行动吧。像吃啊，睡啊这种程度的事。」

凛子咬了一下嘴唇，像是在思考什么的样子。马上又轻声说道：

「那……现在，他的意识是处于怎样的状况？」

「惨不忍睹……」

比嘉顿了一下，俯视着继续说道：

「连自己是谁，要做什么都不知道，只是被一些经验性的欲求驱动……这样的状态……」

寂静再次支配了这个空间。

** 2

「……呼……」

本该持续下去的音节，被战靴的合成橡胶底踢飞钢板的巨响全然消除。

突击队副队长，瓦沙克·卡扎尔斯好像不太满足只在墙上踢出两三个凹陷，使劲地把不知为
何掉在地上的糖果盒踩破，之后终于停止了骂声的奔流。

流着拉丁裔血的他，把蓬松的波浪形黒长发拢起，清爽地移动到主控制台前，单手抓起站在
那里的男队员的防弹衣领口。

「丫的，你再说一遍看看。」

如鞭子般柔软瘦弱的瓦沙克手上拎着的，是一名瘦的极其夸张的青年。他金色的头发剃到三
毫米左右，皮肤病态般雪白。消瘦的脸上，像是开玩笑般戴着一副粗糙金属架的眼镜，他的
名字叫克里特，是队伍里唯一的非战斗人员。

自吹是有逮捕记录的网络罪犯，名字也不是真名而是网名。不过瓦沙克[fn:1]也一样。世上不
会有父母给儿子起名叫地狱王子的。他是因为麻药交易而无法继续待在当地，被现在的雇主
捡到。

——就是这么回事。

《海龟》袭击部队的十二名队员，除了队长加百列·米勒以外的所有人，都有着黑暗的过去，
是以换取新身份作为保证被饲养的「狗」。作为饲主的民间警备公司本身，也是跟大企业的
黑暗面相连，抬高巨额利益如地狱的看门狗等同的存在。

克里特作为之中的一条狗，被如白刀子般的瓦沙克提起来也没有感到一丝的害怕，大声嚼着
口香糖，用尖锐的声音回答道：

「说几次都行。听好了，这个控制台被狗屎一样的锁屎一样地紧紧锁着。我们带来的笔记本
电脑【lap-top machine】就算到你得睾丸癌归天时都没法计算解除呢。」

「我不是说这个，你个混球！你丫不是说会被锁是因为我们动作太慢了吗！！」

浅黑色皮肤被涨的通红的瓦沙克大声叫着。如果不是走错路，充满野性味道的他帅的甚至能
做个当红的演员，而一旦发起飙来也是怪可怕的。

「喂喂，我只是说事实而已？」

用脏话对骂的二人，其他的九名队员完全没有要阻止的样子在一边猥琐地笑看着。加百列大
大地叹了一口气，拍了拍手插入两人的吵架。

「OK，你们俩都到此为止。没有时间去追究责任在谁了。现在必须要考虑下一步的行动。」

于是，一下子转过头去的瓦沙克用孩子般的口吻说道：

「可是啊，老哥【bro】，不教训他一顿我气不过啊。」

想说不要再叫「老哥」了，却还是把话吞了回去。最初碰面是在战斗训练中，加百列把瓦沙
克在内的十人精锐部队在现实和假想两个领域轻松地全灭了，之后这个年轻人就一直说着
「这辈子跟定老哥了」。

当然，在加百列看来，他这个人除说话奇怪以外没有别的感想了。对把所有人类看成是『光
之云=灵魂的内容物』的加百列来说，瓦沙克所抱有的尊敬啊亲爱之类的感情不过是些难以
理解的代名词。

迟早，将灵魂的抽取-保存技术变成自己的东西时，所有人类的感情，都能通过光之云的色
调或者形状之类的情报被整然地分类吧。如此考虑着， 加百列向两人缓缓说道：

「听好了，瓦沙克，克里特。我对至今为止队伍的行动很满意。只有盖利受了点擦伤，占领
主轴的目的也达成了。」

瓦沙克听了后很不情愿地放开了克里特的防弹衣，两手叉在腰间。

「可是，老哥啊，就算占领了主轴，那个……什么来着，什么light的东东拿不出来的话不
就没意义了吗？」

「所以，我不是说要想出方法来吗？」

「但是，JSDF的人也不会一直缩着吧？要是一直跟着这大笨龟的护卫舰突击过来，只有我们
十一个人加一个赠品，形势也很不利啊。」

不愧是被加百列提拔为副队长的人，瓦沙克拥有单纯的野狗所不具备的形势把握力。稍微想
了想，加百列轻轻耸了耸肩表示道。

「……我也不是很肯定所以一直没说，但是看来我们的顾客跟JSDF的高层，有某种秘密的交
易。宙斯从作战开始二十四小时内是不会行动的。」

「……嗬～」

小声吹着口哨的是克里特。防风镜一样的眼镜里头，浅灰色的眼睛咪了起来。

「这么说，这个行动不过是……——不，还是不说为妙吧～」

「我也这么认为。」

浅浅地微笑着点了点头，加百列再次向所有人环视了一圈。

「好，那先确认状况。布利格，耐压隔墙那边怎样？」

被叫到的巨汉队员，慢悠悠地走出一步回答道：

「不乐观啊。真是块好板，是最新的合成素材吧。用带来的携带型切割刀，二十四小时内根
本不可能。」

「Japan Money健在呀。汉斯，Light-Cube集群呢？」

这次，把胡子整理的非常漂亮的瘦子队员，以洒脱的动作张开两手。

「真是吃惊啊【astonish】。这个房间上边有个巨大的膨胀室，那里有闪闪发光超级漂亮的
这么大的……」

右手拇指比出二英尺左右的幅度。

「Cube堆的密密麻麻。把那些全都搬上潜水艇是绝对不可能的。」

「嗯」

加百列交叉着双手，思考了一瞬间后继续说道：

「……我们的任务，是从那数十万个Cube中找出唯一的那个跟接口一起带走。Cube的ID情报
已经取得。也就是说，只要能操作主控制器，就能轻易地检索Cube并从集群抽取出来。按计
划现在已经手持啤酒踏船而归了。」

「气死，都是那个乌龟眼镜男，平时天天在吹嘘『我的罪状是入侵了五角大楼的中央服务器』
什么的，一个小小的锁都解除不了。」

「哦哦，吓死我了。竟然被平时总说『追我的是哥伦比亚的麻药王』的人说呢。」

瞪了一眼想继续吵架的瓦沙克和克里特，加百列加强了语气。

「到了这一步，决不能空手回去！你们想回到美国【States】后说『被JSDF的小姐们搞砸了』
吗？

所有人一起喊道。

「NO！！」

「你们不过是连正规军的新人训练生都赢不了的门外汉吗！？」

「NO！！」

「那就快点想！！证明你们脖子上顶着的圆东西里装着的不是燕麦粥【oat meal】！」

完美地扮演不屈的指挥官振奋地叫喊着，加百列自己也在静静地思考。

加百列作为灵魂的探求者，取得人类第一次创造出的真正的灵魂并独占Soul Translator技
术是他最大的目的。计划取得这两样以后，就用秘密藏在突击潜水艇里的神经毒气将队伍所
有人干掉，自动航行到第三国家隐藏行踪。

但是，只到目前这个阶段，这个作战都还算符合加百列的目的。用管理员权限封闭了主框架
操作的现在，必须想办法用别的手段找到《爱丽丝》并抽取出来才行。

《爱丽丝》——《A.L.I.C.E》。

把这个代号告诉加百列的临时雇主NSA的，是自卫队【JSDF】《K组织》内的情报提供者
【rabbit】。

加百列也还不知道Rabbit的个人资料。但是，以流出情报的动机是从强夺计划的主谋，高科
技军需企业格罗金ME获取高额报酬这点判断，他应该是不会在这个状况下把自己暴露于危险
之中采取行动吧。

也就是说，不能期待获得耐压隔墙那边的Rabbit的协助了。必须要凭现在的情报和装备，而
且是在段时间内达成目的。

时间——一切都是时间。

有生以来不知焦急为何物的加百列，在二十三小时后逐渐逼近的时间限制器的存在让他不得
不记住某种压迫感。

NSA的奥托曼他们在行动开始前一刻对加百列说了。

K组织的活动，严重动摇着日本的既存军需权利。所以，自卫队的高层对K组织的存在不会感
到高兴——相反，想积极妨碍的势力不在少数。

作为K组织基盘的是陆自【陆军自卫队】和空自的年轻将校，跟海自的疏通非常狭隘。NSA正
是看准这点，通过在日本的CIA人员与某位将官缔结了密约。保护K组织大本营《海龟》的护
卫舰『长门』，在袭击开始后二十四小时内会以『人质安全优先』为名不采取行动。

但是，待机时间过后，考虑今后的媒体对策，护卫舰也不得不行动。这种状况，也不可能命
令突入现场的要员「手下留情」。结果，在压倒性的人数、装备差下，加百列的袭击队伍估
计会全灭吧。

——对奥托曼的这个说明，加百列耸了耸肩表示谅解。

假如真的发展成最坏的结果，也还有只自己逃回潜水艇的策略。但是同时，目标的
Light-Cube和STL机器不在，探求人的灵魂这个伟大的旅程将会倒退到无法挽回的地步。

加百列已经把这个强袭完成以后漫长的人生全都计划好了。

带着STL技术逃到东南亚的第三国家之后，把包括自己的容貌和指纹在内所有的痕迹消除掉。
然后再移居欧洲——最好是南法或者西班牙。

毫不吝啬地使用运用获得的庞大金额的隐藏资产，买入舒适的大宅。在深处的房间里设置
STL，构筑各种不同的假想世界。

这些世界的住人，一开始将只有《爱丽丝》跟加百列吧。但是那也太过寂寞了。也是为了灵
魂的研究这个目的，必须要增加素材才行。

当然，不会犯傻到在当地猎取。最少也要跨越一个国境，寻找年轻又充满活力的灵魂持有者，
将其绑架，用STL将灵魂抽出来后把不要的躯壳处理掉。

光是东北欧或者中东，非洲就能遇到很多吧。但是光那样也还是寂寞。等（事件）平息之后，
还要远征祖国[fn:2]——当然还有VR技术发源地的日本。

日本VR游戏玩家闪耀的生命曾经让加百列深深着迷。当然也不是所有人都如此，一部分玩家，
好像过着（VR游戏）那里才是现实之上的现实一般的生活，毫不吝啬地挥洒现实的感情。

其原因，恐怕跟过去在那个国家只存在了两年的『真实的假想世界』这个事物不无关系。被
开发者所骇，这些年轻人体验了具有真实的生与死的死亡游戏。他们这些「生还者」的灵魂，
有着其他人不具备的对假想世界的适应性。

可以的话，哪怕一个也好，希望能得到他们——特别是被称为「攻略组」的孩子们的灵魂。
封入那些灵魂的Light-Cube，将会放出比任何宝石都要贵重的光芒。

全世界的任何权利者、大富豪无论花多少钱都绝对不能获得的究极的辉石。把它们大量大量
地摆放在宅子的秘密房间里，每天把中意的人载入到喜欢的世界，想怎么玩弄就怎么玩弄。

更为美妙的是，从人类抽取出来封入Light-Cube的灵魂，可以自由地复制和保存。坏掉的，
扭曲掉的，都能彻底消除。在漫长的时间里，逐渐塑造成加百列喜欢的姿态。简直就是在琢
磨原石到让它发出至上的光辉。

到那个阶段后，加百列漫长的旅程将会第一次重获与那个原点同样的无上幸福和欢喜吧。

小时候，在森林的大树下，他见到艾莉西亚·克林格曼的灵魂的美丽光辉。



脑海里闪过了这些念头，加百列把眼睛闭上，后背轻轻地抖了一下。

再次睁开眼睛的时候，已经恢复了如冰一般的思考力。

如果把各国的，还有日本的青年们的灵魂，比喻成围绕王冠周围的颜色缤纷的红蓝宝石，那
中央镶嵌的巨大钻石就非《爱丽丝》莫属了。有着没有任何污秽的究极灵魂的爱丽丝，才有
资格作为自己永远的伴侣。所以，无论如何都要想办法把她的Light-Cube弄到手才行。

但是，集群里堆积的十几万个Cube，一眼看上去是完全相同的东西。物理上的作业是不可能
判别的。

那样，还是只能依赖情报作战了。话虽如此，可就算是一流的电子罪犯克里特也对主控制器
的锁束手无策的样子。

加百列拖着鞋子的声音，移动到快要趴在键盘上一样两只手指高速运动着的克里特背后。

「怎样了？」

代替回答的是，两掌向上高举的动作。

「管理模式的登录让人绝望。可以做的，只有羡慕地偷窥一下上面集群里收着的灵魂们愉快
生活着的童话国度了。」

克里特挥动一下手指，正面显示器的OS画面上打开了一个窗口，显示出奇妙的光景。

非常，不像「童话国度」的样子。天空被染成恐怖的红色，地面则是像碳一样漆黑。

画面中央搭着几个看起来是用皮革粘起来的尖顶帐篷。同时，集结着十个胖墩墩且秃着头的
奇怪生物，不知道在起什么哄。

大体上是人形但怎么看都不是人类。背很驼，手则长的快要擦到地面，而相对曲折的脚却很
短。

「哥布林？」

加百列自语道。克里特则轻轻吹了个口哨，很开心似的说：

「喔，知道的挺清楚啊，队长。是啊，不像是兽人或者女兽人，这应该是哥布林吧。」

「但是，未免太大了啊。这是重步兵吧，重步兵哥布林。」

姗姗来到旁边的瓦沙克，两手叉腰追加了自己的意见。

原来如此，就算精通好几种武器，到底不是士兵而是民间企业饲养的狗啊。加百列如此想道。
原本所属的特殊部队《方差》中，除加百列以外，没人拥有VRMMO游戏的知识。

但是，这个队伍里很多成员都有那一手的游戏经验。或者说他们本来就是为了能在假想世界
里作战行动而被选拔出来的人员，自然是理所当然的了。

加百列看着的地方，十只「重步兵哥布林」的骚动终于变得白热化。最后，两只互相抓住对
方的前胸，扭在一起厮打起来，而围着他们的哥布林也举起双手喝彩。

加百列感到了某种隐约的灵感，向坐在座位上的和尚头说道：

「……克里特—」

「嗯？」

「这些……这些怪物们，跟所谓的Mob AI之类的NPC不一样吗？」

「这……个……嘛，好像是吧。这些怪物从某种意义上来说是真「人」。是上面的
Light-Cube读取的人造灵魂……Fluct Light的一部分吧。」

「什么【哇】！？真的假的【really】！？我的天啊【Oh，my god】！！」

这时，瓦沙克疯狂地叫着跳起来。

啪嗒啪嗒敲打着和尚头，又叫道：

 「这些重步兵都是人类！？拥有跟我们同等的灵魂！？Frisco[fn:3]的老奶奶听了会当场死掉的！！」

「日本人不是信基督啊信佛啊信禅的吗！？竟然做出这样的研究！！对了，上面的闪光光里
收着的都是这种哥布林啊兽人之类的吗！？我们的爱丽丝酱也是么！？」

「不可能～」

厌烦地将瓦沙克的手撇开，克里特订正道：

「听好了，这里的人作出的VR，Under World这东西是分成两个区域的。中央有个《Human
Kingdom》，那里住的是普通的人类。然后呢，外面是《暗之领域》，到处晃悠着这些怪物。
爱丽丝当然是在Human Kingdom的某个地方啦。现在还无法找到她呢。」

「那不简单着吗。既然有人类不是能听懂话么？那只潜行到Human Kingdom，问一下那里的
人知不知道爱丽丝不就完了吗？」

「哇，猪。有头猪在这。」

「你说什么！！」

「告诉你～Kingdom跟你以前窝着的Frisco一样大，里面有十几万人呢。你想靠一两个人怎
么调查啊。」

就像是想说「你就让自己罗罗嗦嗦的话打回去」一样——

克里特拱起猫背，用和尚头用力顶中瓦沙克的下巴，拉丁系的吵架鬼又骂起了脏话，不由分
说地大叫起来。

「慢着。慢着慢着慢着慢着～。谁说是一两个人啊……」

听到这些对话，突然加百列心中暧昧的灵感也突然完整地浮现出来了。

「……对啊。为登录Uner World而预设的帐号……不可能全都是LV1的一般市民啊。对吧，
克里特。」

「Yes。Yes～boss！！」

嗒嗒嗒嗒！

像打击乐一样敲打着键盘，大屏幕里立刻滚动着显示出几个名单。

「如果操作人员要登进去观察或内部操作而准备的帐号，应该会准备所有阶级的身份。军队
的士官……不，将军……。不不，贵族，皇族……说不定连皇帝本人……」

「哦。哦！！那太棒了！！」

瓦沙克擦着快要裂开的下巴叫嚷道。

「也就是说，可以用general【将军】啊，admiral【提督】啊国防长官之类的身份登录
Under World，想下什么命令都可以啊！『全军列队！向右转！找出爱丽丝带回来！！』」

一边发着牢骚，克里特以极其惊人的速度继续操控着控制台。

但是。

数秒之后，伴随着对这个男人来说少有的脏话，列表被中止了。

「日，不行啊。不光是对World的直接操作，连用高级帐号登录都加了牢固的密码。很遗憾，
boss，看来只能以一般市民潜行到Human Kingdom去。」

「……哼。」

克里特和瓦沙克的脸上浮现出明显的失望感，但加百列却依然面无表情，只是稍微斜了一下
脑袋。

已经没有太多的时间去犹豫了。

但是，那也不过是现实时间里设定的限制。屏幕里所延伸的异世界「Under World」里，时
间被1000倍于现实的惊人比率压缩。

有这么多的时间，就算以一般市民登录，找出并抓住「爱丽丝」以后，通过世界内部的控制
台将她抽取到现实世界也不是不可能的事。

不过——也确实是个漫长的事请。

与其这样做，还不如从Human Kingdom的「外侧」攻略更快一点吧。

「克里特。高级帐号有给目标区域外……《暗之领域》预备吗？

「……外面？但是，爱丽丝在那里的可能性无限接近于〇哦？」

虽然一边发着疑问，克里特的手指还是轻快地闪过。

加百列一边看着重新打开的窗口群，一边回答说：

「嗯，确实。但是，区域境界并不是完全不可侵的吧？用赋予帐号的权限，也许能越过境界
呢。」

「喔，不愧是老哥！想法就是不一样！就是说……不是以人类的将军，而是以怪物的大将打
过去对吧！？这个更燃呢！！」

对着哔哔吹着口哨叫喊的瓦沙克，克里特以实在厌倦之极的口吻向他泼冷水道：

「你要燃就燃吧，要是登录的人是你，在那个世界可是个臭熏熏的巨型怪物哦……啊，有了
有了，boss。」

当地一声，随着按键弹开的声音出现的窗口有两个。

「嗯～跟人类那边不同，超级帐号只有两个……好，没有设置密码呢！看看……一个是，
《暗黑骑士【dark knight】》的身份。权限等级是……70！真高啊！」

「喔喔，好啊好啊！这个我要了！！」

无视一边吵闹的瓦沙克，克里特激活另一边的窗口。

「而……另一个是。——这啥啊？身份是空的……LV也没有显示。设定的只有名字。这
个……怎么读来着？……『vector』？」

** 3

比嘉顾虑着打破了笼罩辅助控制室的凝重的沉默。

「怎么～说，呢。他的肉体……或者说，现实世界里桐之谷君面前的状况，就像跟刚才说明
的那样……不容乐观。」

看到被神代凛子抱着肩膀的结城明日奈，惊慌地抖了一下身体，比嘉又慌慌张张地补充道：

「但，但是，还是有那么一点希望的！」

「……怎么说？」

强烈，却像是带着求助般的声音凛子开口问道。

「Under World里的桐人君，还处于登录状态。」

比嘉看向跟主控制室相比小的多的屏幕。移动鼠标点击了几次后画面被切换，由人界以及包
围它的暗之领域构成的Under World鸟瞰图出现了。

「就是说，虽然自我受到损伤，他的Fluct Light本身是活动着的，还接受着各种刺激。事
已至此，只能祈祷Under World里，有某种……奇迹般的治愈会降临到他身上吧……。他因
为过于痛恨自己，责备自己，以致损伤了自己的灵魂。要是有人能够给予他治愈，宽恕的
话……」

比嘉也知道自己所说的话并不科学。

但是，那也是他毫无虚假的真心。

比嘉跟其他的拉斯技术者集合力量跟智慧，创造出继承了NERvGear，Medicuboid的脑接口机
的最终形Soul Translator。但是对这个机器找到的人的意识体Fluct Light，几乎是一无所
知。

Fluct Light是物理现象吗？

还是说——超越唯物论的观念呢？

如果是后者的话。

受伤，累倒的桐之谷和人的灵魂，或许能用某种超越科学的力量来治愈。

比如说，某人的爱。



「……我，要去。」

像是跟比嘉的思考同步了一般。

虽然小声，但却坚定的声音回响在辅助控制室。

室内的人都吃惊地一起看向声音的主人——现场最年轻的少女。结城明日奈将被凛子抱着肩
膀的手拿开，点了点头再一次说道：

「我，要去Under World。在那里找到桐人君，跟他说。你努力了啊，也许发生了很多悲伤
的事情，痛苦的事情……不过你已经尽力了。」

大大的榛色眼瞳里闪着泪光如此说着的明日奈的身姿，就是在抱着把一生都献给学术研究这
种觉悟的比嘉看来也是美的让他喘不过气来。

同样，像是被什么打中一样的表情听着她说话的菊冈，立刻用眼睛的镜片隐藏住表情，望向
旁边的STL室。

「……确实，STL还有一台空着。」

以苦涩的声音说出这句话后，夏威夷着装的指挥官作出复杂的表情，继续道：

「但是，Under World现在……怎么都说不上是平稳的状况啊。按照任务计划，以这边的时
间来算，还有几个小时就会进入最终负载阶段。」

「最终……负载？会发生什么？」

比嘉边比划着手势向皱着眉头的凛子解释。

「这个……简单来说，就是外壳将破损。数百年来将人界和暗之领域隔开的《东之大门》的
耐久值会降为0……暗之军队会涌入人类世界。人类如果有完善的军事体制，最终能反攻回
去的负载。但是，这次的实验……桐人君将统治组织的《神圣教会》毁了大半，所以……真
不知道会变成怎样…… 」

「仔细想来，现在的状况，无论如何都需要让我们这里的其中一人进行潜行吧。」

把手交叉在胸前的菊冈唧咕道。

「侵略一旦开始，在这混乱和虐杀之中，在人界的《爱丽丝》很可能会被杀。那样的话，辛
辛苦苦把主控制台锁死来争取时间也变得没有意义了。也许要让谁用超级帐号进去里面，保
护爱丽丝，并将她带到作为内部控制台的《世界尽头之祭坛》，从那里抽取到这个辅助控制
器才行。」

「对了……你在事故发生前一刻，已经那样嘱托过桐人君了吧。」

「恩。要是他没事，一定能完成的。那时，他刚好跟爱丽丝在一起呢……算是不幸中的万幸
啊。」

「那就是说，内部时间已经过了几个月的现在，两人还在一起的可能性很高？」

「……也，可以这么想吧。也许，还是应该让明日奈小姐潜行比较合适吧……跟桐人君的沟
通力自不必说，要保护爱丽丝也需要内部的战斗能力呢。我们中间，最习惯在假想世界活动
的非明日奈小姐莫属了。」

「那，超级帐号也最好使用最高级的。」

对菊冈的话点了点头，比嘉的手指在键盘上飞驰。

「既然这样，随你挑选吧。骑士，将军，贵族……有各种各样的。」

「喂，等等。」

突然，凛子用略带紧张的声音插声道。

「……袭击者他们，会不会也在想着同样的事情？刚才你不也说了吗？确保爱丽丝的近路，
就是从内部进行操作。」

「啊，没错。确实也可能成为他们的手段。下面的主控制室里，也设有两台STL。但是，他
们应该没有时间去破解超级帐号的密码。可以登录的只有LV1的一般市民哦。无法想象那种
状态能在最终负载阶段的修罗场中活动。」

一边快速地说明着——

比嘉突然，好像忘记了什么似的，感到有一丝寒意从背后走过。

但是，这个思考，被高速滚动的帐号列表忽明忽暗的光分散开了。

** 4

在骑龙停下来之前，暗黑骑士利皮雅·赞凯尔【Lippia Zankel】就从龙背上跳下，自起飞台
向连接城堡的空中回廊全力奔跑。

很快她就感到呼吸不畅，用右手把巨大的黑钢头盔拿掉。

灰蓝色的长发呼啦着飘散开来。用左手整理并撩回背后，利皮雅再次加快了脚步。真想把憋
闷的铠甲和披风都一起扔掉，但是他实在不想让帝宫里蠕动着的恶心男人们看到自己的任何
一寸皮肤。

在弯曲的回廊上飞奔了三分钟左右，从右手的圆柱间能看到屹立的巨城浮现在红色天空的背
景下。

帝宫奥布西蒂亚城[fn:4]，是在广阔无边的暗
之国里最高的峻峰峰顶附近彫筑起来的。

从最上层的皇帝居室，能隐约看到遥远西边耸立的终结山脉，还有嵌在山表的大门。

但是，这数百年以来还没有人确认过这个传说。

暗之国的王座，身为初代皇帝同时也是堕天之神贝库塔的人，在太古之昔回到地底的黑暗处
之后，这个位置就一直空着。最上层的大门拥有极高的天命并用大锁封印着，永远都不能打
开。

利皮雅把视线从漆黑城堡的尖端收回，向直逼眼前的铁门的守卫兵叫道：

「暗黑骑士第十一位的赞凯尔！把门打开！！」

卫兵不是人类而是食人魔族【Ogre】。虽然很结实但相对的转头都显得迟钝，利皮雅来到铁
栅面前时才转动机关。

门刚发出「咣，咣」的沉闷声音打开一点，赞凯尔小小的身体就横着从间隙里溜了过去。

三个月没有回来的城堡，迎接利皮雅的依旧是那冰凉的空气。

地精【Kobold】们每天都愚直地拖着走廊使它一尘不染。穿着铠甲跑在黑曜石地板上发出
「咣咣咣」的声音，前方毫无声息滑步走来的是，身着裙子肌肤若隐若现的两个妖艳女子。

光灿夺目的波浪型头发上，戴着大大的尖顶帽宣告着她们是暗黑术士。利皮雅打算无视她们
直接擦身而过，但其中一人却以尖锐的声音故意说道：

「呜哇，好大的声音啊！是兽人或是洞穴巨人在跑步吗！？」

随后，另一名也轻薄地笑着起哄道：

「那也不至于吧，这个晃动是巨人才对。」

——如果不是因为城内禁止武斗，早就把她们砍飞掉了。

利皮雅如此想着，哼了一下鼻子继续赶路。

暗之国的人族女性，从修炼所毕业之后大多都会进入术师公会。传闻中公会是个极其享乐的
组织，不重纪律而专学放荡，出来的都是只对着装感兴趣的人。

尽管如此，她们对任职比术师等级更高的骑士的女人会燃起极大的对抗心理。利皮雅也曾在
修炼所被同期关系恶劣的女巫师用毒虫诅咒为难。用飞龙的火焰把她们的头发全部烧光之后
才老实了一点。

到底只是毫无『先见』的愚蠢之人。

无论组织还是个人都只会相互仇视，一切决定都取决于力量的优劣。这个国家没有未来可言。

眼前虽然因为十侯会议总算在危险的均衡下不至于内乱，但也持续不了多久。如果在与破入
眉睫的《人界》，兽人跟哥布林们称之为《纽姆国》之间的战争中十侯死去的话，均衡将会
被打破，再次沦为血肉相残的乱世。

告诉利皮雅这个未来的，是十侯之一，直属长官的暗黑骑士团长，同时也是她的爱人。

而现在，利皮雅心中怀着一个他所期盼的情报。

所以，她不会浪费任何一秒钟去拘泥女术师的戏言。

笔直穿过无人的大堂，宽大的楼梯也一步两跨地飞驰而上。尽管多有锻练，到达目标楼层时
也已大汗淋漓气喘吁吁了。

由协商而出支配暗之国全土的十侯中，五个是人族，两个哥布林族，剩下的分别由兽人族
【Ork】，食人魔族，巨人族【Giant】的长老所居。经过长达百年之久的内乱，终于缔结了
类似条约的文书，现在作出了这五族之间没有上下关系这样的约定。

因此，奥布西蒂亚城的皇城正下方，就是十侯各自的私室。利皮雅消去足音跑在圆形的走廊，
然后在最里面的一间房前轻轻敲了一下黑檀大门。

「——进来。」

立刻传来抑郁的回答。

利皮雅在走廊左右看了一下，确认没有人之后，迅速打开门溜了进去。

室内虽然很宽广，但装饰却控制在了最低限度。吸入空气中飘荡的男人味道，利皮雅在大门
口单膝跪下。

「暗黑骑士利皮雅·赞凯尔，现已归至。」

「辛苦了。来，坐吧。」

按捺着激动的心情，利皮雅抬起头往粗壮声音的方向看去。

前面夹着圆桌，在一张巨大沙发的一边横坐着，两手放在枕头上高高地翘着脚的男人，正是
暗黑骑士长——毕克苏尔·乌鲁·沙斯特【Bixel Ul Shaster】，别名暗黑将军。

以人族而言有着出类拔萃的身材。虽然横向不可能跟食人魔族相比，但身高却毫不逊色。

一头漆黑的头发剪的很短，相对的嘴边和下巴却留有长而浓密的美髯。棕色的皮肤下，是几
乎要把朴素的麻衬衫扣子都要撑脱似的饱满肌肉，而腰上却没有一丝的赘肉。虽然保持着一
点都不像是年过四十的完美肉体，但在登上骑士最高位的宝座以后，也是不可或缺地每日进
行着惊人的锻炼这点少有人知。

看到久违的爱人，利皮雅好不容易按捺住想飞奔到他怀里的冲动，起身坐到面向沙斯特的沙
发上。

沙斯特自己也站起来，把桌上的其中一个水晶杯拿给利皮雅，然后用指尖切开像是陈年火酒
的封口。

「很想跟你一起喝上一杯，所以昨天从宝物库里骗了一瓶来。」

一边快速地眨了一眼，一边把芳香的深红色液体注入杯中。这个表情就像顽皮的孩子般，跟
以前真的一点都没变呢。

「谢，谢谢阁下。」

「我不是说了很多次，两个人的时候不要这样叫吗。」

「可是……现在还在任务中。」

沙斯特拿你没办法这样似的耸了耸肩，客气地碰了一下杯。利皮雅呷了一口高价酒，然后深
深地喘了口气。

「……那，来说正事吧。」

自己也干完一杯后，一改严肃的表情边重新倒入一杯，边低声问道：

「卿让使魔来通知的『重要事情』，到底是什么？」

「是……」

利皮雅左顾右盼地探出身子。沙斯特虽然豪放磊落但同时也很谨慎。这个房间被施加了好几
重防御术，就算是术师公会会长的魔女也是不可能偷听到。虽然知道这点，但自己带来的情
报实在太重大了，还是忍不住压低了声音。

直直地盯住沙斯特的黑色眼瞳，利皮雅简短地说：

「……神圣教会最高祭司Administrator死了。」

瞬间，就算是暗黑将军也吃惊地睁大了眼。

呼呼的粗叹声打破了寂静。

「……这是，真的吗……我知道这么问很失礼，我也不是怀疑卿的情报……但是……那个不
死之人……」

「是……您的心情我也很理解。我自己都不敢相信……不过我用了一个星期去确认，确实没
错。我将《听耳虫》藏伏到神圣教会的修道士团员里确认到的。」

「喔……真是乱来啊。要是『逆听』，卿现在已经被大卸八块了呢。」

「嗯。但是，我这种程度的术式都没被探知到，证明这个情报是真的。」

「……恩……」

添了一点第二杯火酒，沙斯特刚毅整然的脸稍稍低了一下。

「——那是，什么时候的事？还有，死因是什么？」

「大约半年前……」

「半年。——你的仇敌，那个『五十号』从山脉消失的时间也是那个时候吧？」

「请别提了。」

利皮雅皱眉反驳道。

「我并没有输给他，因为我还活在这里。——是的，确实是在半年前。至于最高祭司的死
因……我想只是个流言而已，说是『被剑所毙』……」

「被剑。——意思是那个女人被砍了？」

「不可能。」

对着张口结舌的沙斯特，利皮雅大大地摇头道。

「恐怕，虽说是不死之人可也终于耗尽天命了吧。但也许是为了保存号称神人的最高祭司的
灵性，才放出那样的空话吧……」

「嗯……我猜也是。但是……死了啊，Administrator……」

沙斯特闭上眼睛，两手交叉，把身体靠在沙发上。

如此沉思良久后，随着简短的自言自语张开了眼睛。

「机会。」

利皮雅一瞬间屏气，用微小的声音问道：

「什么的，机会？」

立刻就得到了回答。

「当然是……和平的机会。」

在这个城里说出来太过危险的单词，马上溶解在房间的冰冷空气中，消散。

「您觉得……这有可能吗，阁下？」

面对小声提问的利皮雅，沙斯特把视线停留在杯中的红色液体，慢慢地，却是深深地点了点
头。

「不管可不可能，无论如何都必须成功。」

咕地一声把火酒喝尽，继续道：

「从创世之古就把世界分开的《大门》天命已经快要耗尽这点，已是不容质疑的。暗之五种
族的军队，已经等待向深受索尔斯和泰拉利亚恩泽的人界发动大侵略，可以说是箭在弦上了。
上次的十侯会议，还因为如何瓜分人界的土地和财宝，还有奴隶而引发了大纷争。真是……
一群无可救药的贪心鬼。」

对沙斯特直言不讳的话，利皮雅缩了缩头。

「跟被〈禁忌目录〉这种恐怖的大部头成文法支配的人界不同，暗之国的法律只有一条。也
就是——用力量夺取。」

某种意义上，以智谋与武勇登上最高权利的地位，且无止境地把欲望之手伸向人界这个至高
熟果的九个诸侯们相比，可以说沙斯特才是异端吧。

但是，利皮雅之所以深深为这个男人着迷，也正是因为他异样的思考。毕竟，跟其他服侍诸
侯的女人不同，利皮雅不是被强夺过来的。沙斯特向利皮雅这样的普通人献上花束，并跪地
说服了她。

完全没察觉到爱人正在因为他的思考而彷徨无措，沙斯特更郑重地继续说道：

「但是，他们太小看人类的。小看了保护人类的剑……《整合骑士团》。」

利皮雅眨了几次眼，把意识拉了回来。

「一骑当千，如文字所述。暗黑骑士团的长久历史中，被整合骑士所杀之人数都数不清，但
反过来却从没杀过他们。就算是我，也好几次被逼入绝境，只是最后也没被杀死。他们的剑
技是如此的高超，而他们所带的神器也是强力无比的。」

「是……。而且还能使用奇怪的法术……」

「《武装完全支配》吗。虽然让骑士团的术理部研究了很久，但最后还是无法解开。光是对
抗那一个技能，就算上一百个哥布林士兵都不够吧。」

「话虽如此……我们的军队足足有五万。反过来，整合骑士加起来应该也不足五十。我想应
该能完全压制吧……？」

对利皮雅的话，沙斯特讽刺地抓起美髯的一端。

「我刚才不是说了吗，一骑当千。计算起来是不分胜负吧。」

「怎么会……不至于吧」

「嗯，也是。虽然这个算法让人不爽，战线由我们骑士团和食人魔、巨人支撑，后方暗黑术
师们用远距离攻击轰炸，整合骑士们也总会力尽吧。但是，最后一骑坠落时，我们会损失多
少真的难以想象。一万……还是两万呢。」

发出硬硬的声音水晶杯被放到桌上。

沙斯特伸手制止了打算斟酒的利皮雅，把后背埋入沙发。

「而其结果，当然种族之间就会产生力量的不均衡。十侯会议的意义也就丧失，五族平等的
条约将会打破吧。『铁血时代』将再次来临。不，更坏吧。因为这次，人类这个饮之不尽的
蜜海将呈现眼前。要确定那块地的支配权，花上一百年都不够吧。」

这是沙斯特常常危惧的最坏的未来。

而更糟的是，除沙斯特以外的九侯，并不认为这个未来是最坏的。

利皮雅低下头，呆呆地看着进入骑士团以后就朝夕相伴的漆黑全身铠甲被打磨出的耀眼光辉。

儿时比人矮小一倍，又没有腕力的利皮雅，要是在『铁血时代』里肯定不能成为骑士吧。为
了减少生活费被卖给人贩子，在某个街头小巷被杀而结束短暂的人生。

但是，虽然扭曲却还是多亏了那和平条约，她不用卖去奴隶市场而是进入了修炼所，而又得
益于晚成的剑技上的天赋，登上了以人族女人而言几乎不可企及的最高地位。

现在，利皮雅聚集了被父母遗弃到至今还人口贩卖横行的偏僻地里的幼儿，照顾他们直到能
进入修炼所为止。她几乎把所有的工资都用在了运营这样的托儿所上。

这件事，不但对同事，就连沙斯特也保密着。她自己也无法说明，为什么会做这样的事。

只是——

利皮雅总是在内心深处想道，这个世界，有力量的人就可以夺取一切的『暗之国』肯定有什
么地方不对。虽然自己没有沙斯特一般能把理念变成明确的语言这种智慧，但是，她觉得这
个国家，不，包括人界在内的整个世界里，应该存在更为『原始的正确形态』。

这个，所谓新世界，将会诞生于沙斯特所倡导的和平的另一端。现在的利皮雅正是朦胧地理
解到这点，才想为心爱的男人尽一份力。

但是。

「……但是，您打算如何说服其他的诸侯呢，阁下。更何况……整合骑士团会接受和平的交
涉吗？」

利皮雅小声的询问。

「……嗯……」

沙斯特闭上眼睛，右手捋起艳丽的胡子。他在整个对话里最频繁地重复着苦闷的声音道：

「关于整合骑士……还有转机。既然最高祭司已死，现在担任总指挥的应该是贝尔库利那个
老大爷吧。虽然是个老狐狸……不过也是个明理之人。问题，还是在十侯会议。这一边……
虽然我也很矛盾，但看来不能不除掉几个人了。最少也有三人。」

抬起的眼睑深处，稍微发红的黑色眼瞳里，散发着比名剑的剑锋还要危险的光辉。

利皮雅吃惊地吞了一口气，探出身道：

「三人。如此推测……只能是山岳哥布林族的长老，兽人族长老，以及……」

「暗黑术师公会会长。尤其是这个女人，她一直充斥着想获取Administrator的长命秘仪，
某一天登上皇帝宝座的野心。她肯定不会接受和平议案的。」

「可，可是！」

利皮雅高声反驳。

「太过无谋了，阁下！虽然哥布林、兽人的长老不是您的敌手……但是，只有暗黑术师我们
不知道她会使出什么卑鄙的花招来！」

沙斯特顿时说不出话来。

不经意说出的话，完全超出了预想。

「呐，利皮雅。你到我这里来已经过了多久？」

「哈？是……差，差不多……我二十一岁算起……四年吧。」

「已经过了那么久了啊。……一直以来，让你处在暧昧的身份真的对不起。怎样……是时候，
那个……」

左看右看，又沙沙地挠着脑袋，头号暗黑骑士生硬地开口道：

「……正式地、做我老婆吧。如果你不介意我这个大叔的话。」

「阁……阁下……」

利皮雅哑然地睁开眼睛——

感觉有股热量渐渐从内心深处涌出，正要毫不犹豫地飞入爱人的怀抱时。

从厚厚的大门里头，尖锐得像是抽筋般洪亮的声音贯穿了宽广的房间。

「出大事了！！出大事了哦！！啊啊，怎会这样！！诸侯们快来啊，快啊，快啊！！」

隐约记得这个声音，恐怕是十侯之一，商工会头领的人。

与利皮雅的记忆中体格魁梧的大人物不相称，完全不像是他发出的悲鸣还在继续：

「出大事了！！——皇，皇域的！！神铁的枷锁！！在鸣叫呢！！」

** 5

加百列·米勒在无比宽广的玉座之间带着些许感慨眺望着跪地垂头的数十个人工Fluct Light。

这些『存在』们，都是封印在Light-Cube里的人造物。但是，他们在这个世界里却是有智慧
有灵魂的真正的人类。不过，最前排并列的十人中的一半是有着奇怪容姿的怪物。

他们和跟随在他们背后的骑士或者术师们，还有城外驻屯的五万军队，就是给与加百列的战
斗力，也就是《Unit》。以后必须要适当运用这些棋子，歼灭人界的防御力并捕获爱丽丝。

但是，跟现实世界的即时战略游戏不同，这些Unit们不能用指针和命令随意操纵。必须要用
言语和态度去统率、命令才行。

加百列无言地转过身去，看着巨大的玉座后面墙上挂着的镜子。

只有脸型和接近白色的棕色头发跟现实的加百列一样。

但是，额上戴着黑铁色金属上镶嵌深红宝石的宝冠，黑色羊皮制衬衫和裤子上面，披着漆黑
奢华的毛皮长袍。腰上垂着散发出梦幻燐光的细剑，鞋和手套则是精致的银丝刺绣所编。而
背后，还有染成血色的长披风。

视线移到右边，比玉座低一段的位置上，是两手交叉在脑后慌慌张张地到处张望的骑士。

穿着像宝石一样闪耀的深紫色板甲的，是跟加百列同时登陆的副队长瓦沙克。虽然已经告诫
过他，在掌握形势之前，不要得意忘形地乱说话，不过他还是一脸忍耐着想连说脏话的表情
把鞋子弄的喀哒喀哒响。

加百列把叹息吞了下去，再次把视线拉回到自己那连摇滚明星都无地自容的装束上。

穿惯了只重视机能性的战斗服，这个装束总觉得很不舒服。但是，这个异世界「Under
World」里，加百列并不是陆军的一中尉。

是统治广阔无边的暗之领域的皇帝。

而且——也是神。

加百列合上眼睛，缓缓的吸了口气，然后吐出。

扮演的角色，从『倔强且冷酷的队长』切换成『无慈悲的暗黑之神』的开关在意识的某处咔
嚓一声响了。

再次睁开眼睛，把鲜艳的披风往后一翻转过头来的加百列——暗黑神贝库塔，丝毫不带人情
味的声音回响在玉座之间。

「抬起头，报上名来。——从那边开始。」

中指巨大的戒指闪耀着光芒，其所指的方向是最前列左端蹲伏着的体格魁梧的中年男子。

「是！臣是担任商工会头领的琏吉尔·吉拉·斯科卜。」

再次低头叩拜的男子旁边，是大的惊人的——站起来估计有十英尺的身躯上，呈十字状捆着
黑光锁，腰上缠着奇怪野兽的全身皮——亚人种单膝跪着。

把跟人类相比显得异样的长鼻梁和下巴「呱」地抬起，巨人发出如地面震动般地小声报道：

「巨人族长老，希古洛诂。」

加百列在寻味虽然自己能指挥这个怪物，但它却是拥有跟自己同质的灵魂这个事实。而旁边
拖着的细长影子静静地宣布：

「……暗杀者公会首领……弗·萨……」

穿着的羽衣跟巨人相比太过奢华却几乎没有存在感的身姿，让人无法判断年龄，甚至性别。

虽然有那么一瞬间加百列想命令她抬起头来看看脸，不过考虑到暗杀者肯定有不能暴露外貌
等各种各样的规矩吧，先放置一边，把视线左移。

然后，好不容易才忍住不因厌恶而皱起眉头。

把丑恶，这个词表现的淋漓尽致的存在正一动不动地坐在眼前。因为脚太短而无法下跪。胖
墩墩，鼓的圆圆的肚子尽是脂肪，发出闪闪的光泽，跟肩膀一体化的脖子上，像是野兽的头
骨一般的东西哗啷哗啷地垂着。

而其上面摆着的头感觉是七分像猪三分像人。突出的平坦鼻子，和露出牙齿的口，只有细长
的眼睛闪耀着人的智慧，不过这反而让人觉得不愉快。

「兽人族长老，利尔皮林。」

听到这个尖锐的声音，加百列瞬间考虑到这究竟是男还是女的呢，不过立刻就放弃了这个兴
致。既然是兽人，那一定是军团的下层等级吧。不过是用完就扔的Unit而已。

然后行了一礼的，是垂着赤金色卷毛，可以说还是个少年的年轻人。被太阳晒成铜色的上半
身只有革带，下半身则是紧身裤和凉鞋，而两手戴着咣咣响着的金属柳丁拳套。

「斗技士公会首席、伊修凯恩！！」

一边看着跟右边的兽人相比，看起来更加熠熠生辉的少年的眼瞳，加百列在内心疑问，所谓
的斗技士究竟是做什么的。跟士兵有什么不同吗。看来有必要重新检视一下各Unit的等级和
状态。

少年轻快的声音刚一停，立刻想起了咕噜噜噜的野兽的呻吟声。

猛然抬起头来的，是有着虽不及巨人但却远超人类的躯干，长的离谱的双臂顶到地面的亚人
种。上半身几乎被长长的毛皮所覆盖。从他完全的兽头来看，身上的不是衣服而是体毛吧。

「咕噜噜……食人魔的……长老……弗鲁古鲁……噜噜噜……」

虽然不知道那是名字还是单纯的嘟哝声，加百列轻轻点了点头看向下一位。

突然，一个刺耳的尖声唧唧地响起。

「我是山岳哥布林的长老哈噶西！陛下，请务必把头阵的荣誉赐予我族的勇士吧！！」

声音的主人，是个像猴子般的光头两侧突出细长耳朵的小亚人种。

无论是身高还是肌肉，别说之前报上名字的巨人、兽人、食人魔，就连人类都远远不及。

根据潜行前克里特的讲解来看，这个暗之领域里只存在一个法则。也就是「力量支配一切」。
那么，这个怎么看都是个无力的哥布林，是用什么力量能够晋升到跟其他种族对等的位置呢。

不管如何，虽然是比兽人还要低级的最低级步兵Unit，凭着仅有的那么点兴致看向哥布林面
容的加百列，在内心可以接受般轻轻点了点头。

因为哥布林圆而小的眼睛里充斥着的欲望和不满是目前报上名的首领中最大的。

山岳哥布林长老的话刚完，一旁坐着的，只有肤色不同的亚人也尖声叫道：

「不值一提！跟那些人比我们为陛下效劳的作用要大十倍。我是平地哥布林族长库比利。」

「说什么呢，你个吃鼻涕的！是因为潮湿的泥土让你脑子长泡了啊！！」

「你才是，脑浆都被太阳晒干了吧！！」

在尖声对骂的两匹（人）面前——。

啪。啪啪！！

弹出七色的火花，哥布林的首领们发着悲鸣跳开了。

「——你们两个，现在是在皇帝陛下御前！」

伴随着妖艳的声音，把举起的右手收回去的，是用能看到肌肤的衣裳包裹着丰满身材的年轻
女性。花火是女人的指尖像打火机的火石般相互摩擦时飞散出来。

缓缓站起来的女人，像是在夸耀她那连女郎都可以不屑一顾的身材和美貌般转过身来，装模
作样地行了一礼。加百列的左下方，瓦沙克会小声地吹口哨也是没办法的。

奶咖啡色的肌肤，就像是刷过油一样亮泽，胸和腰周围只挂着一丁点的黑色漆布。一直延伸
到膝盖以上的是如针一般的高跟靴。背后披着的是闪耀着黑色和银色光泽的毛皮披肩。其上，
奢华的淡银色直发垂到腰下。

眼影和口红是鲜艳的水色，婀娜地挤弄着与之同色的眼睛，女人报上了自己的姓名：

「暗黑术师公会会长，D·I·L。我手下有术师三千，而我的身心都是属于陛下的。」

如果面对这个视线的是突击队的其他队员，这个瞬间说不定就会飞上前去了。但对着如此的
妖艳，从未被性欲控制的加百列只是大方地点了点头。

这个叫D的巫师瞬间眨了一眼，好像还想再说些什么，不过还是再行一礼后跪下了。

明智的决定。加百列如此想着，把视线移到头领Unit的第十个，最后一人身上。

那里单膝跪下低着头的，应该是个人类，但却有着让人吃惊的体格的中年男子。

包着全身的漆黑铠甲上，刻着无数的伤痕，闪耀着暗淡的光芒。低下去的脸上，额头和鼻梁
上能看到淡淡的伤痕。

低着头说话的男子的声音，是浑厚的男中音【Barytone】。

「暗黑骑士团长毕克苏尔·乌鲁·沙斯特。在献上吾之剑前……我想问问陛下。」

猛然抬起的脸，与加百列在军队中遇见的少数「真正的」军人有着共通的磨练过的风貌。

特别是那双敏锐的双眼下，有着——排在男子右边的九人完全看不到的，某种觉悟。

名叫沙斯特的骑士用仿佛要射穿什么的眼神凝视着加百列，低声继续说道：

「在此时回归玉座的皇帝……是何用意。」

原来如此——这个人，不是单纯的Unit。

必须时刻意识到这点。加百列如此想道，然后戴着的「神的面具」自动配合表情开口道：

「流血和——恐怖。烈火与破坏。死和悲鸣。」

加百列那如被切削的合金一样光滑却又如冰刃般的声音回响在大厅，十个将军们的表情一下
子绷紧了。

按顺序睥睨着这些面孔，加百列翻动长袍，右手高举指向西方的天空。

「把孤从天界放逐的众神所恩宠的蜜地，保护它的《大门》如今就要崩塌了。孤是回矣……
为了将吾之灵威告示天下！孤之所欲只有一个，将同时出现在那片土地的天神的巫女收入掌
中！除此以外的人类，随心所欲地杀死，夺取吧！所有暗之民所盼望的——约定的时刻到
了！！」

回归寂静的空气——

被尖锐的野蛮的熊叫打破了。

「叽~~~！！杀！！杀死那些白纽姆们！！」

使劲蹬着短脚边叫唤的，是细小的眼里滚动着欲望与忧郁的兽人族长。立刻，两匹哥布林也
同时举起双手追随。

「嗬噢噢噢噢噢噢！！战斗！！战斗！！」

「呜啦——！！战斗战斗——！！」

战嗷立刻就传染了其他的将军及他们身后的士官们。暗杀公会的黑法衣随着树枝般纤细的身
体在摇摆，暗黑术师公会的魔女集团也随着娇声散放出色彩鲜艳的火花。

整个广阔的大厅里充斥着原始的喊叫——

加百列发现，只有名叫沙斯特的骑士，依旧保持着跪伏的姿势，没有一丝的动作。

是出于军人的抑制呢，还是因为怀有某种感情呢，从雕像般的铠甲上无法判断。

** 6

「呜哇，没想到老哥竟然还有那样的才能！干脆去做演员不是更好吗！？」

对猥琐地笑着放下酒瓶的瓦沙克，加百列嗤之以鼻。

「只在需要的时候。倒是你，最好记住刚才那样的演说方法。毕竟你比他们的地位更高。」

接过酒瓶用指尖弹开瓶栓，边大口呷着红宝石色的液体，边考虑应不应该在任务中喝酒。

瓦沙克则是不喝白不喝似的把陈年佳酿如啤酒般喝下，边打着嗝边擦这嘴巴回答道：

「比起命令啊演说什么的，我更想看阵前杀人呢。难得潜行到这么厉害的VR里面……这个酒
也好，瓶子也好，在我看来都是真的。」

「相对的，被砍了也会痛会出血哦。因为疼痛吸收在这里是无效的。」

「这不挺好的吗？」

瓦沙克嗤笑着耸了耸肩。加百列把瓶子放回桌上后站了起来。

奥布西蒂亚城最上层是皇帝的私室。豪不逊色于白宫的豪华装修，加上可以从巨大的窗口眺
望眼下遥远的夜景。

将军们为了准备开战而离开了城堡，从都市运输物资的辎重队列的篝火延绵跃动。担当补给
的商工公会头领被命令用尽城里储备的粮食和装备，因此士兵们应该是不会挨冻受饿的。

视线离开无数的光，加百列走到房间的一隅，用手触摸设置在那里的黑曜石柱子——系统控
制台。

迅速地操控菜单，按下外部观察的按钮。时间加速倍率降低，随着回到1：1时的奇妙感觉，
听到了克里特快嘴的声音：

「队长吗！？我才刚刚看你们潜行完回到主控制台呢！！」

「这里已经是第一天晚上了。虽然心里明白……真是奇妙啊。总之，目前跟预定一样进行着。
Unit的准备一两天就能完成，接下来预定向Human Kingdom进军。」

「太棒了。那，确保了《爱丽丝》之后带到那里，操作菜单抽取到外部来。那个控制台是直
接连接主控制台的，那样《爱丽丝》的Light-Cube就归我们了。还有，希望能转告一下瓦沙
克那个笨蛋。」

就像是听到了克里特的声音一样，背后传来短暂的咒骂声。

「现下无法操作管理权限，账号数据的重置是不可能的。也就是说，队长和瓦沙克要是在那
个世界里『死』了的话，那个账号就再也用不了了。之后就只能以一个小兵重新来过。」

「嗯……我知道。当下先不要去前线。JSDF有什么行动？」

「现在还没有。看来还没察觉到你们潜行。」

「好。那先切断通信了。下次联络就是在确保爱丽丝并准备离开的时候了。」

「了解、祝您成功。」

关闭通信窗口，随着轻微的违和感再次回到加速倍率。

瓦沙克还在边絮絮叨叨地咒骂着边和铠甲的卡扣搏斗，最后终于把所有的外装丢在地板上，
只穿着皮革衬衣和裤子站了起来。

「呐，老哥。不如去商业区玩一下……看来不行吧？」

「先忍一下。目标回收之后给你一晚时间。」

「了解。啊……杀人和玩女人都随意啊……。那我就先乖乖睡觉了。我用那边的房间。」

格叽格叽地响动着关节，瓦沙克消失在隔壁的一间睡房后，加百列也吐了口气把宝冠从额头
取下。

把披风和长袍放在沙发上，剑则抛在上面。

之前玩的VR游戏，是把装备卸掉以后回到物品窗口的，不过看来这个世界则没有这样的便利
机能。恐怕这样生活上一个月这个房间就会变的十分糟糕，不过反正明后天就会离开城堡，
下次回来的时候就注销了。

边解开上衣的扣子，边打开瓦沙克对面的房门，加百利吃惊地停下了手。

那边大的恐怖的寝室里，令人吃惊的豪华床铺边——有个跪拜着的小人影。

应该命令过包括佣人在内的所有人，都不得进入城堡御座之间以上的楼层。竟然有人能违背
神的命令，到底是怎么回事。

一瞬间想要去取回剑，但加百列还是就这样踏入了寝室，关上房门。

「……什么事？」

短暂地询问。

回答的是，是有点沙哑的声音。

「……请让我担任今晚的侍寝。」

「嗬？」

吃惊地皱了下眉头，加百列在微暗的寝室里慢慢地走向床边。

双手着地的，确实是个身披薄衣的年轻女子。深蓝色头发用饰带高高地扎起。隐约透露出的
线条来看，连把小刀都没带。

在鲜艳的丝绸床单上坐下并询道：

「是谁的命令？」

女子隔了一瞬间后，用细细的声音回答道：

「不……。这只是我的义务而已。」

「是吗？」

加百列移开视线，扑通一声横卧在床中央。

数秒钟后，女子挺起上半身，无声无息地滑到他右边。

「失礼了……」

如此细语的女子，有着连加百列也忍不住在内心赞叹了一下的美貌。肌肤的颜色较深，但颊
骨周围却透露出某种北欧的高贵气质。

看着轻柔地解开薄衣，准备松开头发饰带的女子，加百利体验到了某种感动。

人工Fluct Light竟然会做到这般地步吗。

而且，这还是不完全的AI吗。那完成形态的爱丽丝会达到怎样的高度呢。

让加百列心动的，不是献出身体的女子的行为。

不是那样——

他已经推算到了从猛地散开出来的头发里女子抓出的，高高举起的小刀。

游刃有余的加百列抓住女子的右手，同时闪现另一只手，抓住她纤细的脖子将她按倒在床上。

「呜……！」

女子露出小小的犬齿，依旧拼命地反抗着想要刺出小刀。她的腕力比想象的还大，但还不至
于让加百列感到慌张。把女子的手臂反转到底，拇指轻轻按住气管封住了她的行动。

虽然因剧痛而扭曲着脸，但女子的灰色眼瞳里透露出的决意却没有丝毫减弱。虽然四肢被强
压着但还想着只要一有空隙就立刻发动攻势。女子最终停止了动作，加百利从上俯视着她。

马上就看出这名女子不是专业的暗杀者。化妆有点不到位，身体也锻炼过头了。那么，抱有
反意的应该不是名叫弗·萨的刺客首领，而是其他九将之一——恐怕是四名人类将军的其中
一人。

稍微贴近脸去，加百列发出与刚才相同的疑问。

「谁的命令？」

女子紧紧地咬着牙，从牙缝中得到相同的答案。

「是我自己的……意志。」

「嗬。那，你的长官是谁？」

「……没有。我是流浪者。」

「哼。」

加百列不带一丝感情，如机械般思考。

《K组织》想要突破的人工Fluct Light的界限点。就是无法反抗一切上位的存在所制定的规
则，法和命令。

跟被无数的法所束缚的人界Fluct Light们相比，暗之领域的住民们看似能更为自由地生活，
但本质却没有变化。只是因为给这边的Fluct Light们规定的法律只有一条，所以表面上感
觉很自由。

那条法律就是「用力量夺取」。这是个拥有更高战斗力的人，可以支配下位的人的弱肉强食
的世界。K组织的实验如果按计划进行，饱含秩序的人界和充满混沌的暗黑界即使没有加百
列的介入也会引发激烈冲突，通过战争状态实现突破。

但是不知道因何理由，计划进入那个阶段前，在人界诞生了被称为《爱丽丝》的突破极限的
Fluctuate Light。Rabbit的暗号文只记载了这些，却并没有暗黑界这边也发生了同样存在
的情报。

也就是说，以小刀企图杀害皇帝的这个女子，也是被绝对的法律束缚着的灵魂。而既然不在
将军之列，那应该就是听令于那十人中的某人。但是从刚才没有回答加百列她的主人是谁来
看——

证明这个女子，比起皇帝而且是神的加百列的命令，更优先忠诚于自己的主人。换句话来说，
她认为主人比皇帝更「强」。

这样一来，要让作战顺利进行，有必要让将军们好好地展示一下自己的力量，让他们认识到
加百列才是这个世界最有力量的人才行。

但是，也不能把贵重的将军Unit全部破坏。要怎么做呢——

不。

反正还是要把将军中的一人处分掉才行。让这个女子抱有暗杀意向的，十人中的某人。

要如何揪出那个人来呢。再联系一次克里特，从外部监视将军Unit吗。不，如果这样做就要
把时间加速倍率调回1倍，那样会消耗贵重的现实世界的时间。

那——

一瞬间考虑至此的加百列，再次窥探向女子炼铁色的瞳孔。

「为何要朕的命。给你钱了？还是答应给你地位了？」

并非毫无思考发出的质问。但是，立刻就得到的答案却出乎意料。

「为了大义！」

「嗬？」

「现在发动战争的话，世界会后退百年，不，两百年！必然会回到弱者被蹂躏的时代！！」

加百列再次感到一丝震惊。这个女子，真的还处在突破极限之前的阶段吗？如果是的话，让
她说出这个台词的是这个女子的主人吗？

加百列把头贴的更近，在眼前凝视着灰色的眼瞳。

决意。忠诚。深处藏着的感情是……

啊，原来如此。

要是那样，这个女子已经没有必要了。正确来说，这个女子的Fluct Light已经不需要了。

加百列遵从做自己的判断，已经无需再发一语，无情地往抓住女人脖子的右手施加了力道。

感觉到骨跟气管被压扁了。女子的眼睛大大地张开，口中发着无声的悲鸣。

紧紧地压住挣扎的四肢，毫不留情地勒紧着脖子，加百列却感觉到与刚才不同的惊讶。

这真的是假想世界吗！？无论是右手传来的人体组织被破坏的感触，还是从裸露的肌肤散发
出来的恐怖和痛苦的味道，都比现实世界更加真实地刺激着加百列的五感。

无意识地震颤着身体，右手反射性地收缩回来。

随着咯唧一声闷响，不知名的女子的颈椎骨粉碎了。

然后，加百列看到了。

从双眼紧闭，咬紧牙关的女子额头——涌现出虹色的光芒！

到底为什么！？这不就是那时——小时候让艾莉西亚丧命时看到的，「魂之云」吗。

瞬间，加百列做出了这数年来从未有过的举动。完全忘记了自省，将口大大的张开，把女子
的灵魂一丝不留地吸了进去。

恐惧，痛楚，辛酸——的苦味。

悔恨，悲伤——的酸味。

还有更多，加百列的舌头被无以言喻的天上的蜜酿所浸渗。

合上的眼睑里的暗黑之中，朦胧的光景在闪闪发光。

在老旧的两层住宅的前庭里嬉戏，小小的孩童们。有人类，有哥布林，还有食人魔。看到这
边，就浮现出一脸灿烂的笑容，张开双手一起跑了过来。

那个映像消失了，这次则是看到了某个男人裸露的上半身。彻底锻炼过的宽阔的胸板，温柔
地，强力地拥抱。

「我……爱你……阁下……」

传来细小的声音，再回响，然后远去。

一切消失之后，加百列依然用力地抱着女子的尸体立着膝盖，张开的双眼就这样往上看着，
身体一动不动。

何等——美妙——

加百列的意识大部分为法悦[fn:5]所震撼，但残存的理性碎片
却试图寻找产生这个现象的原因。

收纳着这名丧命女子的Fluct Light的Light-Cube和加百列的Fluct Light被量子通信回线和
STL介入并有线连接着。大概是因为作为「天命」的生命力归零，被清理掉的量子数据碎片
通过回线逆流了过来。

但是，那样的理由对现在的加百列而言已经无所谓了。

因为穷尽一生去追寻，对反复的脑实验早已失望的『现象』，如今他又再次体验到了。加百
列把死去的女子最后抱有的感情——『爱』毫无保留地摄取，尝尽了。那简直就像是落入荒
凉沙漠中的一滴琼浆玉液。

还要。

还要。

还要更多的杀戮。

加百列像钩爪般弯曲着手指的右手向上直举，发出无言的呐喊。

** 7

只是一张羊皮纸分量的信就写了整整一天，爱丽丝在末尾缓缓署名。

慎重地将信折好，封入信封，然后写上西露卡的名字。另一封，给加里塔老人的并排摆在桌
上。

是离别和谢罪的信。森林里的这个家既然被整合骑士艾尔德利耶发现就已经无法住下去。下
次恐怕就不是艾尔德利耶而是骑士长贝尔库利本人来说服了。那时，能对受剑恩师宣告的言
辞，现在的爱丽丝拿不出来。

所以，又要逃跑了。

爱丽丝做出细长的叹息后抬起头，眺望桌子对面坐着的黑发青年。

「呐，桐人。你想去哪里？西域的《龙之巢》是个非常漂亮的地方哦。还是说，南域的密林
地带好点。那边的话连我都没去过呢。」

虽然用更加开朗的声音询问，但桐人却理所当然地没有任何一丝反应。

空虚的眼睛一声不响地看着桌面。又不得不带着这个受伤的年轻人过流浪的生活，让爱丽丝
感到胸口一阵疼痛。但是，也不能抛下他一走了之。一来不能去摆脱身为见习修女的西露卡
这种无理要求，而爱丽丝也有这个意愿。现在照顾桐人几乎成为了爱丽丝生存的唯一目的。

「……算了，目的地就交给雨缘决定吧。好吧……已经很晚了，睡觉吧。明天要早点动身
呢。」

给桐人换上衣服并让他躺下后，自己也穿上睡衣灭掉灯火，钻入了被窝里。

在黑暗中闭眼躺了几分钟，旁边桐人的呼吸变深缓后，爱丽丝蠕动了身子。

把自己的头靠上少年平坦的胸口。紧贴的耳边，传来缓慢而真实的鼓动。

桐人的心已经不存在于这里了。这个鼓动，不过是回应过去的残响。

每晚伴着他睡眠的这几个月里，爱丽丝一直都这么认为。但同时，也觉得在这深沉而真实的
回响里，还——残留着某种东西。

如果现在的桐人，处于「心是正常的只是无法表现出来」的状态，那自己的这个行为要如何
解释才好呢。如此想着的爱丽丝微笑着，身子更加紧密地贴上去，缓缓进入了梦乡。

惊吓。

突然，紧贴的身体传来强烈的震感，爱丽丝在温暖的黑暗中被唤醒。

想睁开眼，却觉得像被粘住了一样沉重。总算定住了视线，看向东面的窗口，但透过窗帘的
间隙看到的天空还是一片黑暗。从感觉判断，也才睡了二三个小时吧。

桐人再次惊吓着绷紧身体，爱丽丝轻声问道：

「怎么了桐人……还是夜里哦……」

再次闭上眼睛，边抚摸着桐人的肩膀准备继续陪他睡下去，但耳边却传来细微的声音让爱丽
丝终于从半醒状态醒来。

「啊……啊……」

「桐人……？」

现在的桐人不存在自发的欲求。单纯的寒冷或者口渴之类的，应该是不会让他醒来的。然而
少年却更加强烈的震颤着身体，像是要从床上起来一样用脚推着床单。

「怎么了……？」

这很不寻常，难道真的是意识恢复了吗。爱丽丝如此想着跳了起来，连点灯的时间都顾不上
直接生成了一个光元素。

被隐约的白色光亮照出的少年的眼瞳里，跟平时没有任何变化，依旧是充满着空虚的黑暗，
让爱丽丝感到一丝沮丧。但是，那究竟是什么——

这时，窗外传来尖锐的鸣声。

「咕噜噜，咕噜噜！」

雨缘的——警戒声。

爱丽丝吃了一惊，跳到地上，从寝室飞驰到客厅后甩开门。这时，隆冬的寒气紧逼而至。但
是，其中却掺杂着异质的味道。这是，焦臭……？

赤着脚走到前庭。然后迅速睁大着双眼看向上空。

西边的天空——在燃烧着。

摇晃着赤黑的光，无疑是巨大火焰的反射。眯起双眼，能看到好几缕遮云避月的黑烟。

火灾！？

虽然一瞬间这么以为，不过爱丽丝立刻打消了这个想法。顺着焦风而至的，确实是细微的金
属击鸣的声音和——悲鸣.

是敌袭。暗之领域的军队，正在袭击露莉德村。

「……西露卡！！」

爱丽丝露出轻微的悲鸣，立刻准备跑回家中。

然后呆立不动。

无论如何只要也要把妹妹救出来。

但是……其他的村民怎么办？

要是尽可能地救出所有人，就必须和暗之军队正面交锋。但是，现在的自己还有那份力量吗。
过去的「整合骑士爱丽丝」的力量源泉，是对教会的狂热忠诚。如今这个信仰已经片瓦无存
地崩溃了，自己还能挥剑，使用神圣术吗？

冻僵的爱丽丝耳里——

从家里传来「哐当」的声响。

吃惊的转过视线。在那里的是，横倒的椅子，和旁边爬着的少年。

「……桐人……」

睁着眼睛，爱丽丝拖着发软的脚急忙跑回家中。

桐人的眼瞳里，依然没有意志的光芒。但是，他缓慢动作的目的是很明显的。

伸出的双手，直指着墙上挂着的三把剑。

「桐人……你……」

爱丽丝从胸口到喉咙，被热量所哽塞。良久，才发现让视线模糊扭曲的分明就是自己的眼泪。

「……啊……啊……」

发出嘶哑的声音，桐人直朝着剑不停地挪动着身体。爱丽丝毅然擦干两眼，直跑向少年，从
地上抱起那瘦弱的身体。

「我知道了……放心吧，我去吧。我会救出大家的。所以，你安心在这里等着。」

变小声地快速说着，爱丽丝紧紧地抱住桐人。

咚、咚。从紧贴的胸口，传来剧烈的鼓动。

在他胸口深处的，并非残渣而是意志，虽然只是微弱的炽火但确实还存在着。现在爱丽丝可
以清晰地认识到这一点。

嘴唇轻抚少年的脸颊后，爱丽丝把瘦弱的身子微微靠在墙壁上。然后她如同跳跃般站起，没
有任何迷惘地抓起墙壁上的爱剑剑鞘。

半年没握过的金木樨剑极其沉重，但爱丽丝没有一丝踉跄地把剑带从睡衣上面系入腰间。迅
速从门边取来外套并披上，右手抓起鞋子就再次飞奔出前庭。

「雨缘！！」

一声叫喊，立刻从屋后窜出巨大的影子，低下头。

爱丽丝轻轻一跃，跨上它裸露的背，以不减当年的尖锐声音对骑龙发出命令。

「去！！」

呼啦！拍打着一双银翼，经过短暂助跑后龙一口气飞上天空。

取得一点高度后，露莉德村的惨状便如实地映入爱丽丝的视野。

吹起来的赤黑火焰，主要来自村子的北侧。果然袭击者是从《终结山脉》过来的吧。

不知道暗之民是怎样把在贝尔库利的指示下已经完全崩塌的洞窟复原的。但是，两天前来确
认的艾尔德利耶说没有异常，那就是在数十小时内把那大量的瓦砾挪走的。那为此而动员的
士兵必定相当庞大吧。

很久以前，就有少数侦察部队逃过守护骑士的耳目，穿梭于贯穿终焉山脉的三个洞窟。但是，
从没听过有大规模且露骨的行动。看来，整个暗之国都高涨着将人界毁灭的情绪……。

边把抓来的鞋子穿在脚上，爱丽丝如此寻思了一会儿，雨缘一口气飞越茂盛的森林到达了露
莉德外廓的麦田上空。

虽然没有缰绳，用手在龙的脖子上向上摩擦来发出滞空的指示。

爱丽丝探出身子，凝视下方。能清楚的看到从北侧杀入村子繁华大街的众多袭击者的身影。
打头阵的矮小身影应该是敏捷的哥布林吧。前锋已经碰到了家具和木材堆积的临时防御线，
周围互杀的白刃在闪烁发光。

迎战的是村里组织的卫士队。但是，无论人数还是装备以及熟练度都不如哥布林部队。这样
下去，一旦后方传来地震般轰响，渐渐逼近的巨大兽人骨干到达，刹那间就会被粉碎的。

咬紧牙抑制住急躁的心情，再次确认周围的情况。

东侧，西侧的大道上，也已经大群涌入。但是南侧还只有不到十只哥布林，以及零星的火势。

住民大概都到南边的森林去避难了吧，这样想着最后向中央广场凝视的爱丽丝——不禁冲口
而出：

「为什么……！？」

教会前宽阔的圆形广场里，满满地密集着蹲坐的黑色人海。因为人数太多最初没有发觉。那
估计是露莉德的所有村民了吧。

为什么不往南逃呢！？有那么多人，就算是不持剑的农民，用锄头或者天秤棒也足以击退几
只哥布林了啊。

袭击者的主力部队已经到达了东西大道的入口。就算现在开始往南移动也已经来不及了。

爱丽丝忘我地驾驭骑龙冲到村子广场的上空并喊道：

「雨缘，没叫你前在这里待机！」

然后从数十米的高处一口气跳了下去。

羊毛织的灰色外套，以及在火焰映照下闪耀着金红色光泽的长发随风飘扬，在夜晚冰冷的空
气中直线落下。

围成圆形的数百个村民，是打算姑且形成防御态势吧，在外周配置了携带农具的男人。在北
侧边缘，积极发出指示的两个男子身边，爱丽丝随着巨响着地了。

鞋子下方，石板被裂成放射状。虽然是拥有超高优先度的身体，天命还是微微减少了一些，
但爱丽丝本人却更引人注目。

正中下怀地，因为突然从头上降落的人影而吓破了胆，两名男子——带领农民的巴博萨和露
莉德村长加斯胡特都目瞪口呆了。

爱丽丝看着过去的父亲加斯胡特的脸，虽然感到一丝的苦闷，但没有理会产生的瞬间沉默大
声喊道：

「这里是防不住的！现在立刻带领所有村民从南边大路避难！！」

听到这凛冽的声音，农民头和村长露出更为吃惊的神色呆立不动了。

但是，几秒钟后得到的，是巴博萨充满杀气的怒骂。

「说什么蠢话！你没看到南边也有怪物在晃悠吗！！」

对立着青筋叫喊的大男人，爱丽丝语气强烈地反驳道：

「那边还只有几只哥布林！男人们打头阵就能突破，很快从东西而来的大队就要逼近了！」

代替无话可说的巴博萨，村长加斯胡特紧张地低声说道：

「在广场组成圆阵防守是卫士长金古的指示。这个状况下，身为村长的我也只能听从卫士长
的命令。」

这回轮到爱丽丝无言已对。

当遇到袭击之时，天职为卫士长的人会暂时取得全住民的指挥权，这是禁忌目录里记载的条
文。

但是，名叫金古的卫士长，是刚从父亲那里继承职位的年轻人。这个状况下，不认为他能冷
静地指挥判断。加斯胡特的脸上浮现出深深的焦躁，但同时表明村长也是这么想的。

但无论如何对村民而言禁忌目录是绝对的。要立刻开始避难，就要把估计还在北边防御线上
的金古拉过来让他更改命令。但怎么想也没有那么多时间了。

怎么办。怎样才能——

这时，一直站着的爱丽丝耳里，传来幼小却毅然的喊叫声。

「照姐姐说的去做吧，爸爸！！」

吃惊的转过视线，在人群里，有个手上发出青白光芒浮在像是被火烧伤的村民身上（疗伤）
的小个子修女。

「……西露卡！」

太好了，平安无事。爱丽丝正要向着亲爱的妹妹踏出脚步，但在此之前结束治疗的西露卡站
了起来，突然绷紧着脸继续对加斯胡特说道：

「自小，姐姐说的话有错过吗？不，连我都知道。这样下去，大家都会被杀的。」

「可……可是……」

加斯胡特露出苦涩的表情吞吐着。留着的胡子微微震颤着，视线呆滞地在空中傍徨。

代替说不出话的村长，再次爆发出怒吼的是巴博萨。

「小孩子少多嘴！要我们舍弃村子……舍弃自己的家吗！！」

秃头下的小眼偷偷张望的，是建在离广场不远处的自己的房子。正确的说，是刚秋收完的大
量小麦，和长年积蓄的金币吧。

视线回到爱丽丝和西露卡身上，巴博萨突然用出人意表的声音喊了起来。

「啊……原来如此，我知道了，我知道了！把暗之怪物引入村子的就是你啊爱丽丝！！以前，
翻越终结山脉时被暗之力量所污染了吧！！魔女……这个女人是魔女！！」

被肉滚滚的手指所指，爱丽丝哑然了。从北边和东西侧逼近的怪物们的嚎叫，全都渐渐远去。

离开村子生活的几个月，爱丽丝数次帮巴博萨砍倒森林的巨木。每次这个男人都扭着身体感
谢自己。但就为了守护自己的财产，竟然能说出这样的话——多么的——

丑陋。

多么的愚蠢啊。

爱丽丝心中，一个念头如刀子般闪过。

干脆，随你们便好了。

我也不用勉强自己。只带上西露卡和加里塔老人，还有桐人离开村子，去找一个远离这里的
新处所。

紧紧咬住牙关，闭上眼睛。

但是，爱丽丝继续思考。

但是，巴博萨和其他的村民们之所以如此愚昧，那也是，神圣教会数百年来的治世所产生的。

禁忌目录以下，用无数的法与规将人们束缚，赐予温水般安宁的同时不断地夺去了重要的东
西。

也就是，思考的能力，以及战斗的力量。

近乎无限的岁月里被逐渐夺取的，无形的力量被积蓄到哪里了呢？

在仅仅五十人的剑士们身上。

整合骑士——。

也就是，爱丽丝自己体内。

大大地吸了一口气，吐出，爱丽丝如断弦之声的气势张开双眼。

视线所向，巴博萨吃了一惊，像是在惧怕什么一样面无血色地把右手放下。

相反，爱丽丝的体内，感到充满了不可思议的力量。平静，却炽热的青白色火焰。

「……废除卫士长金古的指示。我命令，现在立刻解除阵型，手持武器的人带头，向南边退
避。」

那声音虽然很平稳，但巴博萨也好，加斯胡特也好，像是被什么打中一样反仰起上半身。尽
管如此，还颤抖着声音反驳的农民头的胆量，也许更值得称赞吧。

「你一个，小丫头，凭……凭什么权限」

「整合骑士的权限。」

「什……什么啊，怎么可能！你是……被暗黑污染的魔女，怎么可能是整合骑士……」

瞥了一眼惊声叫喊的巴博萨，爱丽丝用左手轻轻抓住外套的肩膀部分。

「我是……我的名字是爱丽丝。整合骑士第三位，爱丽丝·Synthesis·Fifty！！」

高声叫喊着，猛的将外套剥去。

里面，原本是朴素的棉睡衣。但是，翻转厚布的同时，耀眼的金色光芒包围了爱丽丝的全
身——过去只看过一次的，那个现象发生了。

从双手的手指开始，出现黄金的装甲，变成大型的护臂直围至手肘。双腿也被相同颜色的铠
甲所覆盖。

飘动绣着金丝的纯白短裙，上面展开花瓣一样的装甲板。最后从胸部到肩膀都被裹上耀眼的
铠甲，纯白无垢的披风和长长的金发切裂夜晚的黑暗随风飘舞。

只有金木樨剑是一开始就挂在腰间的，不过也像是因为与主人再会而欣喜般，发出铮铮的刀
鸣。

吵吵嚷嚷的村民们也立刻沉默了。打破寂静的，是西露卡轻柔的声音。

「……姐……姐……？」

把视线落到妹妹身上——爱丽丝温柔的微笑道：

「一直瞒着你对不起，西露卡。这是……给与我的，真正的惩罚。也是，真正的职责。」

西露卡的双眼，泪珠缓缓浮现，摇动。

「姐姐……我……我，一直相信着。姐姐绝对不可能是罪人的。真的……很漂亮……」

随后动起来的，是加斯胡特。

「嘎叽」一声跪下的村长，隐藏着表情粗声喊道：

「遵从您的命令，骑士殿下！！」

迅速站起后，转身面向背后的村民们，拉伸着嗓音下达了指示。

「全体起立！！持武器的人带头，向南门跑！！」

在蹲坐的人群里，不安的嘈杂在蔓延。但那也不过是一瞬间的事。以整合骑士这个最大的武
威为背景，没人任何村民会去反抗。

立刻，守护外周的倔强农夫们都纷纷起立，保护着在内侧的女人和孩子，形成一个纵列。加
斯胡特也加入到带头行列，亲自拿起粗糙的锄头。爱丽丝凝神看着他的眼睛，压抑着声音说
道：

「村民们和西露卡就拜托了……父亲。」

加斯胡特刚毅的视线瞬间动摇了一下，欲言又止般回答道：

「骑士殿下……也，请安全第一。」

这个男人，已经不会再把爱丽丝当成女儿了。这也是被赐予力量的代价。爱丽丝如此铭记内
心的同时，推了推西露卡的后背，让她进入队列。

「姐姐……千万不要勉强啊。」

微笑着向为自己哭泣的妹妹点了点头，爱丽丝转身眺望着北方。

同时，村民们一起行动了。

「啊……啊啊……我的，我的房子……」

没出息地叫喊的，是还一直站着的巴博萨。竟敢把整合骑士的命令和自己的财产挂在天秤上
衡量，也该对他的毅力称赞一番了。

随你自生自灭吧，爱丽丝闭上眼睛，让耳根清净下来。

北侧的防御线还在继续后退，左右也传来敌分队逼近而摇动地面的响声。现在广场上还留有
半数以上的村民，这样下去，全体向南退却之前敌人就会冲进来了吧。

爱丽丝做出判断的时候，北面传来年轻男子的悲鸣声。

「不行了！撤退！撤退——！！」

是卫士长金古的指示吧。听到这个，巴博萨突然气势汹汹的向爱丽丝反驳。

「看……看到没有！！应该留在这里镇守的！！要被杀了！大家都会被杀的！！」

爱丽丝耸耸肩，大致看了一下广场后，温柔地反驳道：

「放心吧，空出这么多空间我就能使用范围攻击了。我会守护这里的。」

「不可能！！就你一个小丫头，怎么可能做到啊！！整合骑士这种鬼话谁信啊！！这个装扮
也是魔女的骗人把戏吧！！」

都已经能看到从东西两边杀来的哥布林和兽人的身影了，巴博萨还骂声连连。再次将他无视，
爱丽丝尽可能让因恐惧而扭曲着脸的村民们退到南面之后，高高举起一只手——叫道：

「雨缘！！」

立刻，上空传来尖锐的吼叫。

把瞠目结舌的巴博萨用左手推到后背，举起的手由东往西挥落，简短的一声：

「——烧掉！！」

咕喔喔！！

如暴风雨的振翅声从夜空倾斜，人们和渐渐逼近广场的暗之尖兵都一起抬头仰望。

被火焰染红的天空划过一个翅膀的黑影，从东急降的巨大飞龙，张大着嘴巴。喉咙的深处，
青白色的光辉闪烁了一瞬——。

嗉！！

耀眼的热线从东边大道，横切过广场中央靠南站立的爱丽丝和巴博萨眼前，直切入西边大道
里侧。

隔了一瞬间。

惊人的爆发从东西的繁华大街膨胀开，直冲夜空。被吞噬的敌分队，随着无数的悲鸣被吹飞，
或在地面被烧成灰烬。

把数十只袭击者瞬间消灭的热线，同时让广场中央的喷水也蒸发了，周围弥漫着白烟。爱丽
丝对从上空掠过的雨缘再次发出待机的指示，随意确认了一下背后的样子。

巴博萨摊着腰倒在石板上，两眼珠子都快蹦出来了。

「什……什……什么……」

放下松弛的脸颊已经抽筋的中年男子，对同样惊恐的村民们说道：

「放心吧，我会死守这个地方的，所以请大家安心，尽快移动吧。」

村民们恢复神智后点点头，重新向南进发，但要全体脱离还需要几分钟的样子。

那时，像是切开弥漫的蒸汽般，从北面而来的几个男人冲进广场。是身穿金属铠甲和红色制
服的卫士们。

在前头拼命奔跑的青年，卫士长金古看到广场一半以上都空了后愕然地尖叫道：

「喂……男人们都去哪里了！？不是说了要在这里防守的吗！？」

「我让他们往南撤退了。」

爱丽丝回到道。像是刚刚注意到一样眨着眼，从上到下全身打量了她数次。

「你是……爱丽丝……？为什么会……穿成那样……？」

「没时间说明了。所有卫士都在这里了吗？有没有被落下的？」

「啊……啊啊，应该没了……」

「好，那你也跟大家一起逃吧。啊啊，那边的大伯也麻烦你了。」

「逃……那些怪物已经到眼前……」

话还没说完——

「叽哩！！」

粗野的吼叫响彻广场。

「在哪里！！纽姆们逃到哪里去了！！」

突破浓雾，直接冲入广场的几只哥布林那恐怖的身影，再次令卫士和村民们从喉咙流露细细
的悲鸣。

爱丽丝轻轻地吸了一口气，右手放在剑柄上。

飞龙的热线不能连发。接下来，爱丽丝必须只身面对敌方主力了。

哥布林看到爱丽丝闪耀的骑士身姿，闪着黄光的眼里立刻生起出可怕的杀意和欲望之色，露
出参差不齐的牙齿。

「叽哩！！纽姆的女人！！杀！！杀了吃掉！！」

长而粗的手上挥舞着铁板一样的蛮刀，直线冲了过来——

看到这个身影，爱丽丝内心伴随着恐惧嘟囔着。

啊……为何会拥有此等恐怖的力量啊。甚至让人觉得其存在本身就是一种罪孽。

整合骑士的这个身体。

「叽哩——！！」

高高跳起后挥落的厚刃刀，爱丽丝用左手轻松地从侧面抓住，如薄冰一样捏碎。咔嚓一声碎
散的金属片落入地面之前，更快地，从剑鞘中拔出的金木樨剑横切哥布林的身体。

山吹色的剑风并没有就此停留，更是把逼近的三只哥布林无声地卷入，连同厚厚的白雾不留
痕迹地吹散。连悲鸣都没有发出，四只敌兵的身体就从中间分离，咋咋地崩落到地面[fn:6]。

看来——最高司祭Administrator确实是错了。

这样的力量仅仅集中在一个人类身上，将其意志封印并训练成人偶。想要把本因遍布世界的
力量全部收纳掌中。那个神人死后，所有整合骑士都不过是刻上巨大的错误的石碑。

而错误已经无法纠正了。

那，至少——

把这份力量，为本该持有的人，用到最后一滴为止。

既不是为了神明，也不是为了信仰而殉身。

而是通过自己的思考，自己选择的战斗。就像过去两个无名剑士所做的一样。



爱丽丝坚毅地抬起低下的视线。

广场北面，可以看到宽阔的大道上已经填满了敌人的主力部队——以兽人为主，混杂着不少
的巨大食人魔，上百个暗之士兵们渐渐冲了过来。

它们跟我，现在是同等性质的存在。一边是为了杀戮和欲望，一边是为了赎罪的愿望，各自
挥舞着武器。

爱丽丝能清楚地感到，自己体内缠附的对神圣教会和最高司祭的依存心正在烧尽，蒸发。爱
丽丝第一次凭自己的力量，发动了过去仅以对神明的盲目归依为基础的究极奥义。

「Release Recollection！！」

吡唏！！

金木樨剑的刀身，放出如太阳般耀眼的光芒。

从剑锋，吹起无数锐利的花瓣，在暗夜中飞舞飘散。

敌方军团主力，化作黑色的波涛欲逼近并吞噬广场和残留的村民。

「岚花——裂天！！」

无数槌音的合奏，向着冬天清澈的蓝色天空飞舞。

** 8

爱丽丝眯起双眼，最后瞥了一眼远处麦田边上隆起的露莉德村。

大袭击至今已经过了一个星期。

以北侧各家为中心，近两成的村子被烧毁，但村长决定让所有村民的天职暂时停止转入作业，
所以重建的工作进展的非常迅速。遗憾的是，从烧毁的废墟中找到了数十具遗体，并在昨天
在教会里举行了庄严的合葬仪式。

爱丽丝受邀出席仪式之后立刻前赴北方的洞窟进行了确认。

受贝尔库利之命使之崩塌的冗长隧道，被再度扩大到足以让巨大的食人魔都能通过。深处，
最接近暗之领域的地方，爱丽丝发现了长期野营的痕迹。

袭击者们在对面的入口将接受挖掘作业的一团人送进去以后，再次让通路崩塌。整合骑士艾
尔德利耶从那个入口确认的时候，已经有作业班潜入内部深处，逐步开通着整个通路了。

在以前，哥布林或者兽人是不可能有这个心机并考虑得那么周到的。仅从这件事就能推算，
这次暗黑侧的入侵是『动真格的』。

爱丽丝离开洞窟以后，并没有立刻将其塌陷，而是暂时堵塞从中央部涌出的鲁尔河的源流，
将内部完全水浸。最后，将设置好的无数的冰素炸裂，不是岩石而是用冰将洞窟封印了。

这样一来，如不是与爱丽丝同等的术者是不可能再次穿过山脉的。

从对面浮现的白色的终结山脉收回视线，爱丽丝把最后的旅袋绑在雨缘的脚带上。

「对了……姐姐。」

拼命忍住泪水帮忙出行准备的西露卡，低着头开口道：

「……爸爸，其实也想来送行的。总觉得他今天从早上开始就心不在焉了。父亲心里……姐
姐能回来其实是很高兴的。这点，希望你能相信他……」

爱丽丝轻轻地抱住妹妹小巧的身体，小声回答道：

「我以罪人只身离开了这个村子，然后以整合骑士的身份回来了。但是下次……当晚成一切
责任时，我会以爱丽丝·青贝尔克的身份回来的。我想那时，一定能说出来吧。『我回来了，
父亲』。」

「……嗯。那天一定会到来的。」

杂着哭声简短地回应后，西露卡抬起头，用袖口毅然地将脸上的眼泪擦干。

把身体转向一边，向旁边沉在轮椅上的黑衣少年，精神奕奕地说道：

「桐人也要打起精神啊。快点好起来，帮助姐姐哦。」

轻轻抱住低垂的头，做完祝福之印后，年轻的少女向后退出几步。

爱丽丝走到桐人身边，从他手上轻轻地取下两把剑，固定在雨缘的鞍上。然后轻轻抬起少年
纤细的身体，让他坐到鞍的前部。

并不是没有考虑把桐人留在村子托付给西露卡。如果前赴最前线东大门的话，爱丽丝会作为
防御部队的主力而忙杀，定然无法像现在一样勤恳地照顾他。

但爱丽丝还是决定带他一起走。

理由只有一个，因为袭击之夜桐人表现出的不寻常的反应。那个时候，桐人毫无疑问，表现
出了取剑前往村子的意志。为谁而战，就是这个人的本质。那么，能取回他的心的大概也就
只有战场了吧。

一旦有变，就算绑在背上也要守护到底。

爱丽丝最后再一次跟西露卡紧紧拥抱。

「……那，我走了。」

「嗯。小心……一定要回来啊，姐姐。」

「我保证。……也替我向加里塔老人问好。……好好保重，要努力学习哦。」

「我知道了啦。一定会成为出色的修女……然后，我也……」

缓缓抚摸着妹妹的头，放开她后，爱丽丝咬着牙依依不舍地慢慢向爱龙走去，在桐人后面骑
到飞龙背上。

向地面的妹妹深深地点了点头后，视线转向遥远的天空。

轻轻地甩了一下缰绳，龙以对两个人和三把剑的重量毫不在乎的强大力量在麦田之间助跑起
来。

一定会再回到这里的。

即使此身在战场上腐朽，内心依旧。

爱丽丝拂去睫毛上的一滴眼泪，放出尖锐的喊声。

「……哈！」

轻柔地。

随着浮游感，离开了地面。

雨缘抓住上升的气流，回旋着一口气冲上天空。

广阔的田地和森林，其中央闪耀的露莉德村，还有拼命挥着双手奔跑的西露卡的身姿，将它
们深深烙入眼里——

爱丽丝将龙引向东方的天空。

** 9
再次让十名将军排成一横列，加百列满足地眺望着它们恭恭敬敬跪拜着的样子。

它们按照命令，在两天内完成了进军的准备。照此来看，也许这些Unit们比现实世界里位居
军队上层的大部分将军们还要优秀呢。

真的，干脆就把它们作为『完成品』好了。完美的任务处理能力，加上这个忠诚心。作为搭
载在战争用机器人的AI，已经无可挑剔了吧。

话虽如此——。

它们的忠诚，是基于K组织不断追求的人工Fluct Light的未完成度，这点可不能忘记。

也就是，正因为灵魂里刻印着『由最强力量的所有者支配』这个绝对的原则，这十个人才会
顺从于持有皇帝账号的加百列。而同时，当加百列的力量受到质疑的瞬间，这里有谁会造反
也绝不奇怪。

对暗杀者而言，比起皇帝，『阁下』才是真正的强者。那么，那个男人自身，没有从内心发
誓效忠加百列的可能性也很高。要是抱着这样的Unit奔赴战场，被人趁机陷害的可能性也不
是没有。

所以，从眼前跪着的十人中揪出那个『阁下』并将其处理掉，是出阵前的最后一项工作。

同时，为了在他们的Fluct Light里永远的刻下谁才是最强之人这一概念，也要让剩下的九
人见识到皇帝的力量。

这时，加百列·米勒，根本没有考虑过会被眼前的十个Unit抓住空挡，也就是在一对一的战
斗中被打败的可能性。对他来说，Under World终归只是服务器里的虚拟世界而已，他仍然
被这里存在的Unit全都是人造物这个固定概念所陷——
** 10



暗黑将军毕克苏尔·乌鲁·沙斯特，保持着跪伏的姿势，脑里回想起师傅的话。很久以前，在
骑士团本部道场里的记忆。

「老夫的师傅的师傅，被人取下脑袋当场死了。师傅则被人贯穿胸部，在回城堡的路上毙命。
但是，虽然老夫掉了一只胳膊，但却活到现在。这是足以自豪的了。」

师傅这样说着，把从肩膀以下被巧妙切断的右手展示给沙斯特看。制造这个伤口的，就是暗
黑骑士的宿敌，也是世上最强的刺客，或者说是最凶狠的怪物——整合骑士长贝尔库
利·Synthesis·One。

「你知道这里有何含义吗，毕克苏尔。」

当时，刚过二十岁的沙斯特只能挠头。师傅把单手放到便装下面，闭上眼睛，轻轻地继续说
道：

「渐渐赶上了啊，终于。」

「赶上——那个人了，吗。」

年轻的沙斯特的声音里混杂着难以置信的感触。就在几天前，当着自己的面贝尔库利展现的
剑技是压倒性的。师傅的手臂伴随着鲜血飞起来的瞬间，如冰柱般贯穿背骨的寒气至今无法
褪去。

「——老夫今年已经五十了。但是，不光挥剑方式，连握剑方式我都还极其在意。我想，等
五年，十年我死掉以后也不会改变吧。」

师傅静静地述说。

「那样，像我们这样短命的人子是无法到达已经活了两百年以上的那个不老者的境地的。虽
然很丢脸，直到双剑交锋的瞬间，老夫还抱着这个念头。但是，惨败逃回来后，我才领悟这
是错的。一直以来，师傅及师傅的师傅们不断挑战那个男人，并不是白费力气的……。毕克
苏尔啊，所谓最强的剑是什么？」

被突然问到，沙斯特反射性地回答：

「是无想之太刀。」

「不错。经过长年的修行与剑合为一体，无需斩，无需拔，无需动，放出的一击才是究极的
剑。师傅如此教我，而今我把它教给你。但是呢……毕克苏尔，那也不是。还有更强的。我
被那个怪物所砍，而领悟到了。」

师傅的脸上，浮现出些许的兴奋之色。沙斯特保持着正坐弹出身去问道：

「还有更强的……那是？」

「无想的反面。是断然的确信。是意志的力量，毕克苏尔」。

突然，师傅从木地板上站起，高举切断的右手。

「看到了吧。那时，老夫被右斜斩斩到。真的是无想的斩击，是我一生中遇到的最快的剑。
拔出那一刻，已经被他取得了先机。」

「是……我也这么认为。」

「但是，但是呢。本来他的招式会被老夫的剑弹开的，结果是老夫的剑反被制压，这个手臂
被砍飞了。……你能接受吗，毕克苏尔，那个瞬间，老夫的刃并没有碰到他的剑！」

沙斯特无言，然后难以置信地摇着头。

「这……这种事……」

「是事实。就像……剑的轨道本身，被他重新规定为远远偏离的方向。只能这样来说明那个
现象了。老夫的无想太刀，被他经过两百年锤炼的意志力打败了。因为他过于强烈地断定了
剑的轨迹，所以成了不变的事实！」

师傅的话，沙斯特无法立刻相信。意志的力量这种无形之物，能击败坚定存在的又重又硬的
剑，无论如何都是不可能的。

师傅早就料到了沙斯特的反应。突然整理便装的下摆，轻快地坐到黑光木板上。

「好了，毕克苏尔啊。老夫来教你最后的剑诀。把老夫——斩了。」

「您……你在说什么！难得……」

活了下来，沙斯特不得不吞下这句话。突然，师傅的双眼如鬼神般闪耀着。

「正因为我们性命相连，才要你斩了老夫。既然被那个人一击打败，在你心里老夫已经不是
最强的了。只要老夫还活着，你就无法跟那个人对等地战斗。你也将老夫斩了，不，杀了老
夫，然后站在与他……贝尔库利同一个高处！！」

师傅说完后站起来，伸出他仅存的右臂。

「快，站起来！拔剑吧，毕克苏尔！！」



沙斯特斩了师傅，结束了他的生命。

同时，用身体领悟到了师傅的话的意义。

被斩飞的师傅的右手握着的无形之刃——名为『意志』的剑，与沙斯特的剑在交错的瞬间散
发出激烈的火花，真实地在脸上划破出一道永不消失的伤痕。

被泪水与鲜血涂抹在脸上，年轻的沙斯特站到了超越《无想之太刀》的境地边上。

岁月流逝——五年前。

沙斯特终于向那个人，整合骑士长贝尔库利发出了挑战。年仅三十七岁，感觉自己的剑已经
到达了顶峰。

师傅以一条胳膊换取了生还，但沙斯特并没有战败而归的念头。因为，沙斯特并没有作为后
继者的弟子。不希望让弟子也背负斩师，再被弟子所斩的命运。他决定以自己的性命为代价，
把血染的连环就此斩断。

承载着所有的决意和觉悟、亦即『意志力』的剑，在与贝尔库利的第一刀正面交锋时，并没
有被弹开。但那一刻沙斯特已经预感到了会败北。因为他不认为自己还能再度使出同等沉重
的斩击。

但是，贝尔库利在两剑相交的同时，粗声笑道：

「不错的刀法。并非只有杀意。回去好好考虑我话里的意义吧，五年后再来——小子。」

要理解贝尔库利话中之意，需要很长的时间。但是，年过四十日趋年迈的现在总算是明白了。
那时，如果沙斯特只带着杀气和仇恨去挥剑的话，恐怕瞬间就败了吧。虽然只是一回合，但
之所以能对等交锋，是因为抱有比杀意更加沉重的觉悟。

也就是——至今为止所有殒命的师傅们，和继承自己的骑士们的命运。

所以，沙斯特在收到最高司祭死亡的消息后立刻决定开始和平交涉。他确信，如果自己能统
合暗之领域的意志，那个贝尔库利必定会接受提议的。

基于同样的理由——

这个突然降临，二话不说就决定开战的自称皇帝的男人，必须除掉。

即使跪地俯首，沙斯特也在锤炼着要承载于必杀的太刀上的『意志力』。

离开暗黑界数百年后再度复活的皇帝贝库塔，是个有着白色肌肤和金色头发的年轻男子。身
躯和容貌，都算不上有魄力。

但是，只有那格外湛蓝的双眼，显示出皇帝并非凡人。那双眼里拥有的是『虚无』。吸收所
有的光，不会放走一切的无底深渊。这个男人，或者说是神，隐持着巨大的饥饿。

如果锤炼的意志力，被皇帝的虚无所吞噬，剑就无法触及。

那时自己将会丧命。但是，意志应该会被后面的人所继承。

唯一的抱憾是，因为昨天没有看到利皮雅而未能传达自己的决意。恐怕是忙于处理出征前的
杂务吧——不，要是跟她说自己去斩杀皇帝的话，她一定不会听劝而要求一起来吧。现在这
样就好。

沙斯特缓缓吸了口气，积存起来。

用手触摸从腰上解下，放在地板的剑，慢慢的，慢慢的注入力道。

离王座大约十五Mel。只要踏前两步就能到达的距离。

必须领悟初动。拔刀则应无想。

把提升到极限的所有意志力，注入触碰的剑。然后把身体化空。

右脚踢地——

就在这时。

皇帝用柔滑而硬质的声音，若无其事地说道：

「就在——昨晚，有人潜入了朕的卧室。带着短剑。」

被抑制的惊叹声摇动着大厅的空气。

沙斯特左边并排的九个将军里，有人轻轻地屏气，有人从喉咙深处低声呻吟，还有人把身子
缩入厚法袍中。

沙斯特也同样震惊。保持着斩前的体势和气势，瞬间沉思了一下。

除了自己外，还有其他人得出要排除皇帝的结论。遗憾的是，皇帝依然健在那就表示失败了
吧——可究竟放出刺客的是十侯中的哪一个呢？

不会是亚人的五侯。巨人，兽人就不说了，就算是比较矮小的哥布林族也不太可能避开卫兵
的耳目潜入皇域。

从潜入寝室这个线索来看，暗杀公会会长弗·萨最为可疑，而实际上也搞不懂那个男人究竟
在想些什么。但是用短剑却让人费解。因为暗杀公会在黑暗的洞穴底下专心致志研究的，是
除开暗黑术和武术外的第三种力，「毒」。 弗·萨一族，是为了能让不受术士行使权限和武
具装备权限优待的人生存下去所集结的集团。

同理，就跪在左边的暗黑术师长D也可以除外。只有权势欲的这个女人，虽然可能会考虑高
举皇帝的首级一口气成为暗黑界的支配者，但D属下的术师并不能装备优先度高到能伤到皇
帝玉身的短剑，何况他们还掌握了很多比刀刃更危险的伎俩。

但这样一来，放出刺客的就不是九将军中的任何一个了。

剩下的——就只有暗黑骑士长沙斯特自己了。

但是，当然的不会是自己。因为他已经决定，在除掉皇帝的时候，要堵上自己的性命去挥剑
了。当然也没有对部下们下达过暗杀的命令，连隐藏的决意也没提到过，一次都——。

不。

不……

难道是。

皇帝放出话以后，沙斯特只思考了一眨眼时间，他已意识到搭在剑鞘上的左手指尖已经瞬间
冰冷了。

原本充满刀身的高涨的意志力瞬间变质了。畏惧。不安。恐怖。然后——变成极低温的确信。

几乎同时，皇帝贝库塔开口说了第二句话：

「朕不想在此追问，派出刺客的人的名字。行使自己所持的力量，欲获得更多力量的气魄很
好。想要取朕的首级，就随时向我的后背砍过来吧。」

皇帝再次睥睨着熙熙攘攘的大厅，白皙的脸上第一次浮现出表情——渗透着浅浅的微笑。

「当然，希望你们能理解，这种赌注是要付出相应的代价的。比如说，这样。」

从漆黑的法衣露出手轻轻做了个手势。

随后，设置王座方向东侧墙壁的小门毫无声息地打开，穿着藏青色裙子和白色蕾丝围裙的女
仆簌簌地走进来。双手捧着个大银盆，上面放着四角的东西，但被黑布遮盖着看不到具体是
什么。

女仆把银盆放到王座面前的绯绒毯上，向十侯，以及皇帝恭敬地低了低头，回到了门里。

森然的寂静中皇帝清淡地，虚无地，带着扭曲的笑意，从托加袍[fn:7]的裙摆中伸出鞋尖，
踩住银盆的盖布将它踢开。

全身，甚至连思考力都已冻僵的沙斯特、双眼捕捉到的是——

比最好的水晶还要通透的，冰的正立方体。

以及它内侧封禁的，是自己最得意的弟子和爱人，也是即将成为自己妻子的女人，永远不能
醒来的睡脸。

「利……皮……」

雅。沙斯特只是动着嘴唇嘟哝着。

包围全身的冷气都消失殆尽，无尽的黑暗与虚无充斥着内心。

沙斯特知道，暗黑骑士利皮雅·赞凯尔在秘密地运营着孤儿院。她把失去父母兄弟，快将死
在路边的孩子们，不分种族地庇护并教育他们。沙斯特从利皮雅的行动中，看到了暗之领域
正确的未来。

所以，沙斯特只对利皮雅说出了自己的理想。打破与人界的持续战争，创造一个不用互相抢
夺，相互扶持的世界，这种无尽的梦想。

但是，自己的话却驱使利皮雅去暗杀皇帝，导致了这种悲痛的结果。虽然杀死她的是皇
帝——无疑也是沙斯特自己。

虽然只是一瞬间，无比巨大的悔恨和自责的风暴，在沙斯特空虚的胸腔肆虐。

然后毫无挣扎地变质成黑色的感情。

杀意。

杀。王座上翘着腿，浮现着浅笑的那个男人无路如何都要杀掉。

就算，以自己的生命，和暗之领域的未来为代价。

接下来，谁才是有问题的那个『阁下』呢。

加百列随着不尽的兴趣，眺望着眼皮底下跪拜着的十个Unit。

作为刺客的女子，打从心里爱着自己的主人。加百利把女子死时发出的，可比拟天界的甘露
的感情毫无保留地品尝吸尽，不仅是女子的思慕，连『阁下』对女子抱有的感情的性质也都
理解——虽然只是模型数据。

所以他确信，把女子的头摆出来，对方一定会有所行动的。把反兵相向的叛逆Unit无情地处
死，让剩下的九个Unit的忠诚状态因恐惧而提升。与现实世界所玩的模拟游戏没有任何不同。

真是群可怜又欢乐的人。

虽然拥有真正的灵魂却被限制了智慧，而且还能随意地杀完又杀不停地再生产。总有一天，
当Under World连同主框架【Main Frame】和Light-Cube归我所有时，从小就被其所苦的饥
饿必然会得到满足吧。

把撑在王座扶手的手腕贴靠在一边的脸上，加百列轻松地等待着。

与Unit们相距超过二十Mel。无论什么武器的攻击，用左腰装备着的剑迎击也是游刃有余的。

当然，没办法处理从系统调入的命令放出的攻击。但是，加百列的不安已经在登录前就被抹
拭了。

超级账号——《暗神贝库塔》是K组织的员工为了对暗之领域进行强制操作而设定的。所以，
称为天命的HP非常高，装备的剑也是最强的，甚至——贝库塔拥有所有命令对其无效的犯规
特性。

被这么多条件庇护的加百列，即使是在十个Unit中最左边的穿着漆黑铠甲的骑士，猛地将弯
曲后背时。

在其全身，都包围着如淡影般的光环时。

甚至在看到骑士的右手如闪电般地握住地上的剑柄，同时猛然抬头，从刚毅的相貌中央，锐
利的双眼中放出非人之物的深红光后——

一步步发生的事情还没有完全理解。

包括这个世界，一半是由服务器演算的程序，但另一半是跟人的灵魂同质的灾变性光子
【evanescent photon】所构筑的事。

还有在自己的强袭部队把主电源线切断的同时，所有STL设置的保险装置都被烧掉了的事。

还有因此，黑骑士发生的纯粹且过于强烈的『杀意』，已经能把死这个概念从他的
Light-Cube向Main Visualizer，然后经过量子通信回路注入加百列所接续的STL中这件事。

沙斯特在染满血色的视界中央，只看得到皇帝的身姿。

以生平最快的动作挥动右手，拔出了剑。

从刀鞘解放的，并不是他从师傅那里继承的神器—《胧霞》所见惯的灰色刀身。如名字一样，
如夜雾般的浓霞包围着长大的刀刃，蜿蜒着卷起漩涡。

这个现象的理论，与长年研究也未能解开的整合骑士的究极奥义——武装完全支配是相同的，
沙斯特察觉不到，也已经不需要去察觉了。

「杀！！！」

随着瞬间的呐喊，沙斯特把所有的愤怒、憎恨、以及悲伤都载于刀上，重重地挥起。

** 11

从人界北端，到遥远的东域之边。

踏入四帝国之中，谜团最多的土地伊斯塔瓦利耶思，无论是整合骑士爱丽丝，还是出生于西
国的雨缘都还是第一次。

眼下连绵的险峻奇岩之间，如琉璃般湛蓝的滔滔河水蜿蜒相接。时而出现在河畔的村落和街
道，跟北方见惯的石造建筑不同，几乎都是用木材建造的。

仰望天空指向自己的人们，头发全都是黑色的。和爱丽丝无论怎样都合不来的骑士团副长法
娜提欧好像就是这里出生的。

把视线移回跟前，爱丽丝握着缰绳的手中呆呆地望着天空的桐人，他的头发也是漆黑的，说
不定他也是东域出生的。本想落到村里，让桐人跟人们接触也许能成为取回内心的契机，不
过现在是一天都不能耽搁了。

晚上在安全的湖岸野营，只靠着雨缘猎取的鱼和干果充饥急行了三天——

终于，遥远的前方，如墙壁般连绵的终结山脉，和用神之斧把岩面切断般垂直的山谷进入了
视野。

「……看到了呢，雨缘，桐人。」

爱丽丝嘟囔着，摸了摸强迫载着重物进行长途旅行的爱龙的脖子。现今，传说级的魔兽已几
乎销声匿迹，飞龙成了拥有最大级天命和优先度的生物。但是，载着两个人和三把神器飞行
也绝非小事。半年里随它吃鱼的生活积蓄起来的余力也已大致用光了。

到了野营地后定给它新鲜肉吃个够。爱丽丝如此想着甩了甩缰绳，雨缘像不知疲倦似的高声
鸣叫，加快了飞行速度。

远处看只是细如纸张，缝隙般的山谷，靠近之后就发现真的是非同小可。

跨度有一百Mel左右。即使让兽人或洞穴巨人的大军以横列突进，宽度也非常足够。

切割山脉笔直延伸的山谷面前，是仿佛要把环形的入口包围一样宽广的草地。无数的帐篷整
然排列形成一个大的野营地。到处都升起煮饭的炊烟，周围则是几个卫士部队在专心地摆阵
训练。晃动的刀光，和散发出的沉重气势甚至传到了爱丽丝飞行着的高空。

士气没有所担心的那么低——但不管怎么说绝对数量还是太少了。

粗略一看，总数不及三千。反过来，暗之领域的侵略军怕是不下五万吧。在人界，卫士是只
赋予极少数人的天职，相对的，山那边是无论男女老幼只要能动的都是士兵。

这个状况下，就算多爱丽丝一人参战也改变不了什么吧。到底骑士长贝尔库利要如何去守护
世界呢……

爱丽丝沉思着飞越了野营地，牵引雨缘向山谷形成的微暗进发。

索鲁斯的光被遮盖的瞬间，冷嗖嗖的寒气立刻包围身体。左右的岩壁，是只有神才能作出的
完美的垂直平滑面。别说生物，连棵草木都看不到[fn:8]。

如此低速飞行数分钟后——

叆叇的雾霭前面，能看到几个巨大的构造物，爱丽丝不禁吞了口气。

「这就是……《东大门》……？」

确实，比高过五百Mel的神圣教会中央大圣堂的主塔要低一点。但是，到顶端为止也有三百
Mel吧。最让人惊愕的是，左右的门都是由没有任何缝隙的一块岩石所筑。此等存在物人手
自然是削不出来的，就连术式进行加工生成也绝对不可能。世界最强的术者最高司祭
Administrator过去创造的最大的构造物，是把央都圣托利亚一分为四的十字巨壁，但它上
面的一块块岩石也远比这个大门的小。

也就是说，这个大门是在世界之始，由神之手设立在这片土地上的。为了把两个世界分
开——也是为了引发三百多年后的惨剧。

让雨缘在空中停滞，爱丽丝再次从近处看向大门。

像是连接左右的门，或者说岩板般，不知为何标记着每个都比人体还大的巨大神圣文字。

「desutora……kuto……ato……za……rasuto，sute-ji……」[fn:9]

虽然试着读了最开始的一段文字，不过却不知道其意义。

正歪头思考的时候，突然，一阵吱吱嘎嘎的恐怖声音震动着空气，爱丽丝和雨缘都惊恐地向
后仰望。乍一看，刚才还很平滑的大门一部分，生出一条如低速闪电般的黑色裂纹并向下延
伸。

长达数十Mel的裂缝刚一停止，表面就伴随着破风之声掉落下几块岩石的碎片，然后在谷底
激起沉闷的冲击声。

直眨巴眼后，左右看了看，产生裂缝和发生脱落的还不光是那里。应该说，巨大的门几乎全
都布满了网目般的黑线。

咽了口唾，爱丽丝轻轻甩动缰绳，让骑龙尽可能地靠近大门。

耳边传来敲钟般沉闷的声音。恐怕是岩板内部也在崩坏的声音吧。爱丽丝战战兢兢地伸出左
手，在空中快速地划出丝提西亚之印，轻轻地敲了下门的表面。

浮现的紫色窗口标记着《东大门》的天命，数值高的让爱丽丝不禁背脊一凉。

最大值是至今为止见过的所有天命中最高的——超过了三百万。相对的，当前值不知为何已
经掉到三千了。而且，最右边的数字就在看着的时候减少了一点。

手掌已经渗出了汗，爱丽丝用口数着数，测量着数字再次减少所用的时间。然后估算出天命
完全消灭的期限。

「……不会吧……」

对自己计算得出的解答难以置信，爱丽丝嘀咕道：

「……五天……只剩下，五天了……？」

怎么可能——俨然耸立超过三百年的世界尽头的门，竟然还有不到五天就要崩坏了。这怎么
可能啊。

接到大战迫近的消息，爱丽丝还傻傻地以为那是一两年后的事情。

西露卡灿烂的笑容和加里塔老人满是深深的皱纹、晒黑着的脸，还有父亲加斯胡特不和悦的
颦蹙着双眉的面容一一从爱丽丝脑中略过。击退袭击他们的哥布林，用冰将洞窟封印还只是
四天前的事。她还以为这样就能让露莉德获得暂时的和平。

如果五天后大门崩坏，过不了几天暗之军队将蜂拥而至，如果守备军防守不住的话，嗜血的
怪物们就会如洪水般涌入人界。其大潮不日就会到达北部边境，露莉德这次则会从南边开始
被吞噬吧。

「必须……必须想点办法才行……」

爱丽丝像在说梦话般自言自语着，无意识地拉动缰绳。与即将崩坏的岩板拉开一段距离后，
雨缘缓缓上升。

不用数分钟就到达了三百Mel高的大门最顶部。

门的对面，也同样是将山脉切裂的山谷连绵接续。但是，那边呈现的却不是蓝色的天空和绿
色的草原……是暗之领域的血色天空和洒满煤渣一样的不毛荒野。

爱丽丝不想看到这不详的光景，但皱眉细看——

朦胧的黑色大地上，能隐约地看到摇晃的微光。

让雨缘飞高一点后，凝神眺望。

光并非只有一点，而是按一定的间隔规则地排列着。数量有十几二十——不，岂止二十，所
见范围直到地平线为止到处都是。那是——

篝火。

是野营地。暗之军队的先锋，已经在眼皮底下架好态势，只等大门崩坏，通往猎物熙攘的狩
猎场的道路打开。

「还有……五天……」

爱丽丝再次轻声嘟囔着。

立刻，像是要逃避现实般，调转龙头，顺着原来的道路向山谷后退。因为如果长时间看着那
无数的篝火，感觉会被巨大压迫感所吞噬而单骑杀将过去。

真要如此，如果对方只是哥布林或者兽人的步兵的话，她还是有自信能取下一两百个首级全
身而退的。但如果敌阵里有食人魔弓弩兵，或者暗黑术师——魔女们的部队，事情就不是那
么简单了。

虽说整合骑士能一骑当千，但也不过如文字所述，只是一个人而已。如果受到剑、术、或者
记忆解放攻击无法企及的从遥远后方而来的远隔集中攻击，是必然会受伤的。即便是轻伤，
持续积累下去也迟早会到达天命的上限。那正是骑士长贝尔库利长年担忧的整合骑士团——
甚至是人界在防御上最大的弱点。

拘泥于过度集中战力的Administrator已死，死藏于大圣堂的大量武器防具已经分配给紧急
编制的守备队。但是剩余的时间太少了。至少有个一万士兵，一年的准备时间的话——

伴随着轻轻的叹息，挥去无意义的思考，爱丽丝对雨缘做出了下降的指示。

弧形飞舞而降的雨缘，用钩爪激起地上的杂草降低了速度。停下前就伸长着脖子向帐篷发出
咕噜噜噜的高鸣。

很快，传来稍低的鸣叫。是兄龙滝刳吧。爱丽丝刚停下飞龙就抱着桐人跳落到草地，并帮它
取下了双脚的重物袋。雨缘迫不及待地就冲向帐篷，从下面伸出头跟兄长相互磨蹭。

爱丽丝不禁会意地微笑起来。但她也马上察觉到从背后跑来的脚步声，慌慌张张地蹦起面孔。
整理了一下质朴的裙子，把被风吹散的头发收到背后。

还没来得及回头，熟悉而轻快的声音就响彻着飞行坪。

「老师啊！吾师爱丽丝小姐！！我一直相信你会来！！」

咋咋地踏着草地滑步而来的，正是十天前才永别的整合骑士艾尔德利
耶·Synthesis·Twenty-six。虽然是在长期野营之中，但他藤色的长卷发和白银的甲胄都依
旧是一尘不染。

「……看你很精神啊。」

对爱丽丝冷淡的言语，极度震惊地颤动着长长的睫毛，似乎还有什么话要说的唇角——完美
地冰冻了。

当然是因为注意到了爱丽丝左手抱着的黑发少年。

拉了一下左脸，猛然反仰起头，年轻的骑士摆出一脸难以置信的表情说道：

「带过来了——啊。为什么，为什么呀。」

爱丽丝也对抗着挺起胸膛回答道：

「当然的。因为我发过誓要保护他。」

「可，可是……一旦开战，我们整合骑士将会立于最前线哦。与敌兵刀剑相接的时候怎么办？
不可能背着他打啊。」

「有需要的话我会那么做。」

仿佛要从艾尔德利耶眼中藏起来一般，爱丽丝抱着无法自己站立的桐人的纤细身体稍微侧了
侧身。但是，不知不觉飞行坪周围已经三三五五地聚集了休息中的卫士和下位整合骑士。他
们耀眼地看看爱丽丝，又惊讶地看看桐人。

为了覆盖浪潮般的吵嚷声音，艾尔德利耶放出锐利的反驳。

「师啊，不可以！这种……请恕我直言，抱着这个包袱作战，不光剑力会减半，连师傅本身
也会陷入险境,这样绝对不可以！爱丽丝小姐有——」

把话中断，戴着华丽的银护臂突然指向周围的剑士们。

「——站在他们前面，率领他们的职责！您怎么可以不全力以赴呢！」

言之有理。虽然没错，但也不能就这样回答。对自己而言，哪一个——为了人界而战也好，
还是守护桐人也好，都是同等重要的。爱丽丝咬紧牙关思考着该如何说明。

同时，对于艾尔德利耶的言辞态势，让她感到惊讶。

与过去在中央大圣堂接受爱丽丝的剑技辅导时的整合骑士艾尔德利耶，有着某种难以诠释的
变化。那时，他把爱丽丝神格化来崇拜着，无论她说什么都言听计从的。

这也是当然的。这个世界的人们，被神秘的「外界的神明」封印了右眼，绝对不会反抗法律
和上位者。就爱丽丝所知，成功自行突破封印的，只有爱丽丝自己，和已故的青蔷薇剑士优
吉欧。连号称拥有神之权限的Administrator和Cardinal，都无法违抗那个封印。

也就是说，艾尔德利耶应该还处于那个封印的支配下。然而现在——也并不是说直接违背爱
丽丝的话，如果强制命令还是会遵从的吧。但确实已经不是过去的「盲从状态」了。会自己
思考，陈述自己的意见。

为他带来这个变化的原因，毫无疑问。

是桐人。和优吉欧。

虽然只与身为世界最大的反叛者的二人进行了短暂的接触，却已深深动摇了艾尔德利耶的灵
魂。

回想起来，即使是在露莉德生活的妹妹西露卡，也时常对村子形式化的规矩和顽固的当权者
们的言语露出不满。还有——把桐人和优吉欧带离圣托利亚养成学校的时候，从人群里走出
的两名女学生。身为一般民众，而且还是年幼的少女，竟然主动向整合骑士说话，这种事本
来是不可能发生的。

最后——连爱丽丝也受到了感染。

与桐人交剑，从大圣堂外壁掉落以前的自己，对世界的构成，教会的支配，以及最高司祭的
绝对神性，没有一丝的怀疑。

但是，在不得已下合力摆脱危机、接受休战、爬上外壁期间，桐人的声音、剑、以及双眸都
使爱丽丝受到强烈的动摇——最终打破了可憎且痛苦的封印……

是的，桐人就是向这个充满虚伪调和的世界挥落的铁锤。榨干自己有限的肉体和灵魂之力，
让世界动摇，震颤，最终敲碎了名为神圣教会的、在世界的中心打入的巨大古钉。

但是，作为代价，他牺牲了友人优吉欧和导师Cardinal，还失去了自己的心。

爱丽丝紧紧地抱住左手支撑的如枯木般的身体。然后，正眼看向艾尔德利耶。

想说。你之所以能变成现在的自己，是多亏了这个人的战斗。但是，肯定不会理解吧。对整
合骑士团而言，桐人始终不过是可恨的叛逆者。

这时，周围的人墙中，像是被看不见的巨人的手拨开一样，突然被切开了。

「呵呵，用不着那么生气的，艾尔德利耶。」

年轻的骑士煞地并立双脚，挺直了腰板。爱丽丝也缓缓地回过头去。

充满东域风格，聚拢在前面显得宽松的青灰色衣服。在稍低一点的位置系着深蓝色的带子。
左腰上，简易地插着无骨的长剑。

然后双脚则趿拉着奇怪的木制鞋子。然而，从彻底锤炼过的巨大身躯散发出的威压感，足以
让周围完全武装的骑士们无法正目视之。

唰地擦了一下剃的很短，跟衣服相似的冰蓝色头发，声音的主人用严厉的嘴角抿嘴一笑。

「哟，小姑娘。看来还精神呐，有没有长胖点啊？」

「……叔父。好久不见了。」

爱丽丝拼命忍住渗着泪水的颤抖声音，勉强作出浅浅的微笑，向世界最强最古老的剑士——
整合骑士长贝尔库利·Synthesis·One行了一礼。

以整合骑士生活的九年里，爱丽丝仅对一个人开怀、拜为师长，并且作为父亲般敬仰。同时，
她确信这个世上也只有他一人——桐人除外——是自己绝对赢不了的。

所以，现在还绝不能在他面前哭泣。

如果贝尔库利说不能把桐人留在这里的话她就只能遵从。当然，现在的爱丽丝就算是贝尔库
利的命令也无法强制她。但是，如果在大家面前抗拒的话，会影响骑士团和守备军的秩序。
因为目前的状况是，现在集结于此的人们，被Administrator的逝世深深动摇，好不容易靠
着贝尔库利的指导力勉强维系了下来。

仿佛完全看透了爱丽丝内心的纠结，贝尔库利唇角保持着宽柔的微笑慢慢地走了过来。

盯着爱丽丝的双眼，然后用力点了点头。

然后骑士长对背后想说什么的艾尔德利耶瞥了一眼将他压了下去，转头看向爱丽丝手中的桐
人。

紧闭了一下唇角。像换了一个人似的蓝色的火焰瞬间寄宿到那敏锐的双眼。

贝尔库利唏嘘着，长吸了一口气。

「……叔父……」

你在做什么，爱丽丝无声地询问。

贝尔库利无疑是在提升着剑气。跟过去，爱丽丝被授予的超越《无想之太刀》的究极之剑、
《心意之太刀》所放的剑气一样。所谓的心意就是神威。有时那把太刀甚至可以不用接触敌
刃将它弹飞。骑士长的神器·时穿剑的「连未来都能斩断」这个记忆解放技，是以他压倒性
的意志力为前提而成立的术式。

也就是说、难道——贝尔库利，要斩了桐人？

是要如文字所述、一刀两断地解决这个问题吗？这是绝对无法接受的。到那时，爱丽丝将以
自己的剑去守护桐人。

被骑士长极度压倒性的剑气所压，周围的骑士卫士们，还有艾尔德利耶，甚至帐篷底下的飞
龙们都陷入了深深的沉默。在重压的难以窒息的空气中，爱丽丝拼命挪动着右手手指，向左
腰的金木樨之剑注入意志。对贝尔库利的心意之太刀，只有相同的技才能对抗。到时只能用
记忆解放术来保护桐人了。

但是——

在爱丽丝实际动手前，贝尔库利动了动嘴角，传来如思念似的声音。

没事的，小姑娘。

「……！？」

那个瞬间，爱丽丝感到一丝迷惑。

贝尔库利全身动也不动，但是两眼一闪放出惊人的光芒。

同时，爱丽丝手中，桐人的身体激烈地震颤了一下。

哔！！

像是什么巨大的东西发出吱吱嘎嘎的声响。随后，贝尔库利和桐人的正中间什么都没有的一
点上，确实弹出了银色的闪光。

——这是！？

爱丽丝惊愕地后退了一步。

这时，贝尔库利刚才的剑气以如幻似的，全身舒缓开来，再次浮现出笑容。

「叔……叔父……？」

转向呆然着嘀咕的爱丽丝，最古老的剑士，跟以前练习时一样用指尖摩擦着宽阔的下巴说道：

「小姑娘，刚才的那个看到了吗？」

「是……是的。虽然只有一瞬间……好像是击剑的闪光……？」

「嗯。刚才，我只拔出了《心意》的刀刃，想要砍这个少年。要是砍中了的话，应该会切掉
脸上的一块皮吧。」

「砍中……的话？那就是说……」

「没错，他接住了。用这个少年自己的《心意》。」

爱丽丝倒吸了一口气，赶紧窥探向抱着的桐人的脸。

但是，期待破灭了。微微张开的黑色眼瞳里，只看到虚无的黑暗。依然没有任何的表情。

不——但是，刚才他的身体确实颤抖了一下。

爱丽丝用右手抚摸着桐人的头发，看向贝尔库利。骑士长缓缓地摇着头，肯定地说道：

「看来少年的心确实不在这里……但是，并没有死。不，刚才他想保护的并不是自己而是你
哦，小姑娘。所以……总有一天会回来的。我觉得，大概当小姑娘你真正遇到危险的时候
吧。」

爱丽丝只能比刚才更加拼命地忍住欲流的泪水。

是的——一定，会回来的。

因为桐人是，桐人才是这个世上真正的最强的剑士。他可是挥舞双剑，把那个半神之人都击
毙了。

不能说是……为了我。为了这个世界生活的，所有的人类而回来……

爱丽丝再也忍不住，低着头双手紧紧地抱住桐人的身体，把头埋入他的肩膀。头上，掠过骑
士长教诲般的声音：

「所以呢，艾尔德利耶。不要那么小气，只是一个少年而已你就照顾一下吧。」

「但……但是……」

在位阶上处于中位的整合骑士艾尔德利耶以更加令人钦佩的气概，向骑士长贝尔库利陈述自
己的意见。

「哪怕只有一点战斗力都还好，可这个状态……而且，就算恢复正常了，一般人的剑使能做
什么呢……」

「喂喂」

伴随着沉稳的微笑，贝尔库利的声音，如名刀一般锋利。

「你忘了吗。这个少年的搭档连我都能赢哦。这个贝尔库利·Synthesis·One哦。」

瞬间，草地全体回归寂静。

「那个小子……是叫优吉欧吧。很强哦，强的难以置信。还没告诉你们，我连时穿剑的记忆
解放都用了。可还是输了。你，迪索鲁巴特，还有法娜提欧不也一样吗？」

到此，艾尔德利耶已经没有言语可以反驳了。当然，一对一能战胜贝尔库利的剑士，无论在
整合骑士团，还是大门对面的暗之领域，恐怕都不存在吧——上百年来谁都是这么认为的。

但是，从某种意义来说，这不是一种过于危险的宣言吗。

骑士长贝尔库利，作为最强者的权威而得以统率聚集的守备军。但是，却自己说出了打败自
己的剑士优吉欧的存在——而且还承认桐人跟优吉欧同列，那……

爱丽丝如此考虑着，抬起头时——

贝尔库利突然像痉挛似的颤抖着望向天空。

「叔……叔父……？」

对爱丽丝擦过的声音作出回答的骑士长的话，完全的出乎意外。

「强大的剑气……瞬间膨胀，消失了……遥远的地方……有什么人死了……」

** 12
组成暗黑界十侯会议的十个将军们，每个人的性向、人品、暗藏的野心都全然不同，但是，
只有一点是完全共通的。

那就是，他们比谁都清楚明白「力量支配一切」这个暗黑界唯一的法则。

应该说，这个法则自幼就已经刻入灵魂，通过不断的努力——自己锻炼也好，排除异己也
好——才最终登上了这个血肉相残的世界的顶点。

所以。

跟暗黑将军沙斯特一同并列在王座之间的九将，在看到最右边的黑骑士以裂帛的气势向皇帝
拔剑时，没有人会在内心感到惊愕。

甚至，大部分人都是「喔，敢在这里动手啊，够大胆啊」这样理解的。就连在这三百年里语
言能力、也就是智力退化了的兽人族和食人魔族长，都想着「这样一来就能看到皇帝这家伙
的实力了」从兽眼中闪耀着锐利的光芒。而对沙斯特作为一个战士抱着敬意的年轻拳斗士，
则是在内心「既然拔了剑就把皇帝给斩了」如此声援着。

其中，在数秒前就预测到这个事态的有两个人。

一个是暗黑术师总长D。与沙斯特激强烈敌对的她，一直在计划着绑架暗黑将军的爱人，早
就知道利皮雅的模样了。

所以，反而是她看到成为冰渍的利皮雅的首级时更为惊讶。D预测这样或许会让沙斯特会任
随愤怒而爆发，考虑着这种情况要如何行动。

虽然想过在沙斯特背后捅一刀，向皇帝卖个人情，不过最终D选择了旁观。如果沙斯特败给
了力量深不可测的皇帝贝库塔就算了，而要是沙斯特赢了，恐怕也已深受重伤吧，那时再把
仇敌烤焦，自己称霸暗黑界就好了。D一边在内心奸笑着，一边为了压制兴奋而舔着嘴唇。

而察觉到暗黑将军叛意的还有一人——

这边，则是立刻行动了起来。

沙斯特心里只抱着一个杀字，猛烈地挥动了爱刀。

如果只计算融入太刀的《心意》的强度，已经确实地超过了过去与整合骑士贝尔库利交刃的
一击。他惊人的愤怒和叹息，使得原本需要冗长术式的「神器的记忆解放」现象即时引发了
出来。

沙斯特所带的长刀《胧霞》，是作为VRMMO数据包的Under World在两百年前自动生成的
Object。其属性为「水」，现在呼应沙斯特的杀意的刀身，变化成了包含着必杀的威力、化
实体为雾状的影子。

这个记忆解放技的特性，是将所有的剑原本持有的、「以利刃切断或贯通对象物给与伤害」
这种攻击过程完全省略。从剑柄伸出的长长的雾带，在触碰到物体的瞬间就会给天命造成直
接斩击伤害。也就是说，除了回避以外所有的防具/防御都没有意义。

身为皇帝贝库塔的加百列·米勒，在沙斯特拔剑的瞬间，也同时拔出了自己腰间的剑，开始
迎击敌人的攻击。

如果事态照此推移，沙斯特的雾刃就会穿过加百列的剑击中他的身体，凝缩的杀意将全部注
进去。

但是。

但是——就在摆出大上段[fn:10]的架势准备踢地而起时。

沙斯特的动作减慢，然后停止了。

不知何时，暗黑将军的重铠左侧腹，厚装甲的细微缝隙上，深深地刺着一根投针。

无声无息缓缓站起的，是用深灰色法衣包裹着全身，瘦骨如柴的身姿。

暗杀公会的首领弗·萨。十侯里存在感最为薄弱，会议中也几乎从不发言的隐形者。也许是
这生当中最引人注目地滑身向前。

讽刺的是，弗·萨之所以能在事前察觉到沙斯特的举动，只因为他是十侯之中最胆小且最神
经质的。

暗黑公会，其实就是弱者聚集的家族。是不受体力、魔力、财力等所有力量的恩惠而活着，
但是又拒绝作为单纯的奴隶被榨取的生存方式的人们，为了磨练最后的力量「毒之暗杀」的
技能而创建的集团。

Under World里的一部分虫、蛇、果实之类的毒属性Object，原本是作为负载实验的一环而
配置的。所以其效果受到限制，住民只要动用必要的智慧就能回复。反言之，威力还不足以
能作为与术式和刀剑对抗的武器。

但是，创建暗杀公会的的人们，编制出了连《拉斯》的员工都没想到的「浓缩」技法，相当
长的岁月里一直潜心强化毒性，换句话来说就是为了增加每个原料单位量的耐久度损耗力。
设在奥布西蒂亚城地下深处的暗杀公会总部里，甚至还有上百年持续煎熬毒果汁的大锅。

但是，好不容易完成的「致死毒」却酿成了暗杀公会内暗杀横行的悲剧。与术式和所有的武
器不同，很难找出毒攻击的加害者。

所以，必然的，统领公会之人不是极度胆小的话是无法存活的。必须能察觉周围人的视线，
不，连气息，杀气的存在都要去感觉。

对弗·萨来说，沙斯特在看到利皮雅的头的瞬间所散发的杀气，甚至比鲜血的臭味还要明了。

而暗黑将军沙斯特又是弗·萨在这个世上最痛恨的人。

目前为止策划又废弃的毒杀计划数都数不清。只是杀人的话还是有自信的。但是，被毒死的
话很明显就是暗杀公会的所为，会变成明确的宣战布告。沙斯特死去一小时后，强大无比的
暗黑骑士团就会袭击暗黑公会本部将他们赶尽杀绝。正面战斗是绝对没有胜算的。

但是，现在，这个瞬间的话。

他有往宿敌体内刺入毒针的大义名分在。因为在拔剑夺取皇帝首级的数秒间，沙斯特既不是
暗黑将军，也不是十侯，仅仅是个反叛者。

弗·萨从法衣的怀里拔出、然后投掷出去的，是暗杀公会首领代代相传的暗器。是从一种叫
「鲁贝利尔毒钢」的稀有矿物中削出，能包在掌中的极细的钢针。把内侧掏空后能储存毒液。

而里面装的，也是集暗杀公会技之精华制作的致死毒。从山野采取名为「千草蟥」的一种蛭，
把五万条放在一起磨碎，经过数次浓缩过滤后得到仅仅一滴的毒液。曾经试过繁殖饲养这种
蛭，但都失败了，所以光是制造一滴毒液就要费上极大的功夫。当然有一点弗·萨是不可能
知道的，在Under World的世界里存在的动植物，都是以单位面积的规定值为基准由系统生
成的，除了指定为家畜Unit的羊和牛等以外，一切的人为繁殖都不可能。

因此，弗·萨所放出的毒针，从素材到内部的毒液，都凝集了暗杀公会的全部力量。同时，
也可以说是数百年来被凌虐的弱者们怨念的结晶。

沙斯特因为把所有的意志力都集中在了挥舞的剑上，几乎完全没有意识到钢针深深刺入体内
时的痛楚。

但是，当他向着王座准备高高跳起的瞬间，全身像是化成了铅一样沉重，猛然张大了眼睛。

双脚失去力量，咔嗞一下单膝跪地后，才感觉到了左侧腹的异物感。

——是毒？

瞬间的思考后，在冰一样的麻痹感传到左手前，迅速把针拔了出来。当沙斯特明白这个带有
粘绿光泽、像玩具一样的小型武器就是那可憎的毒钢制品时，立刻咏唱起对麻痹对抗术。

但是，冷气以惊人的速度从左腹浸透，不一会儿就到达嘴边了。连系统调用的起句都还没说
完舌头就已经失去了感觉，甚至连咬牙都做不到。

左手也已经麻痹，毒针掉落在脚下发出细微的声音。

最后，高举的右手也开始缓缓落下，同时长刀的记忆解放状态也被解除，从灰色的雾再次变
回实体的刀尖铿锵一声微微刺入地面。

跟拔剑前完全一样，左膝跪地垂着头。黑色的法衣下摆无声无息的出现在结成冰块的沙斯特
视野里。

——弗·萨。

——没想到会被这个男人暗算。

「……你一定在想……怎么会败在这种微不足道的小东西上吧，毕克苏尔。」

啾啾的擦声从头上落下，沙斯特唯一还能稍微动一下的眼睛作出严厉的表情。——你这种人，
有什么资格叫的那么熟……

「你是想说，我没资格叫你的名字对吧？但是呢，叫你毕克苏尔并不是第一次哦？」

把法袍缓缓盘绕在地上，身子蹲到同样高度的暗杀者的脸，充满了沙斯特视野的大半。但是，
深盖着的兜帽把光线全然遮住，除了突出的下巴以外都陷入在黑暗之中。

那个下巴轻轻动了起来，更加低沉的声音从黑暗中流出。

「你……大概不记得了吧。在幼年学校里，被你彻底打垮的众多孩子的面孔。而其中有一人，
不忍屈辱跳进了水沟，从学校永远的消失了。」

——什么。这个男人在说什么？幼年学校？

作为一个无名骑士之子出生的沙斯特，从刚能握住木剑的时候不管他是否同意就被关进了暗
黑骑士团附属的养成所里。之后，留在记忆里的，就只有为了活下去日复一日的修行。几乎
赢得了所有的选拔试验，回过神的时候已经被任命为骑士团的士官，被师傅即前骑士长选中
以后就更是只为剑而生了。

在养成所并排着挥舞木剑的孩子们的名字，当然不可能记得。

「……但是呢，我可是一天都没有忘记过哦。从我飘到地底的暗渠，被暗杀公会捡起后，长
年累月地被当成奴隶任意使唤。我积累知识，开发了很多新毒，最终成为了公会首领。作为
代价我失去了很多很多……而这一切都是为了复仇，毕克苏尔。」

扭曲的声音中断的同时，兜帽稍微倾斜了一下，弗·萨把面孔露出在沙斯特眼前。

记不起来。不，就算沙斯特能完全记起以前的同班同学也好，外表也是想不起来的。因为，
弗·萨的脸不知受什么毒的影响，已经严重崩溃，变成比兽人还要恐怖的异样了。

再次被落下的兜帽里，只有两只眼睛闪烁着强烈的光芒。

「你体内循环的毒，是我为了杀你而开发，一点一滴存起来的。根据实验，天命超过三万的
岩鳞龙都能在一个小时内杀死。而按你的天命，恐怕还剩两三分钟吧。好了……是时候偿还
了。寄托在你身上的，我的怨恨和屈辱。」

——怨恨吗。

沙斯特的视线从弗·萨身上移开，落在眼前地板上滚动的毒针上。

——我想只靠愤怒和怨恨去杀皇帝。而这个男人在这个武器里注入了同样的力量来杀我。所
以，我的太刀停下了。执着的《心意》赢不了大义的《心意》。以前，与那个男人……整合
骑士长贝尔库利交锋时掌握的剑诀，我到最后的最后还是忘记了……

连单膝跪地的姿势都支撑不住，沙斯特从左肩滑落到地上。

朦胧的视野中间——

是盛在银盆里、冰的立方体。

原名斐留斯·扎尔戈蒂斯的弗·萨，尽情地品尝着好不容易引来的欢喜的瞬间，连呼吸都忘记
地睁开眼睛。

可以说象征力量和荣誉的暗黑将军，如今在自己的脚边拖着濒死的身体。艳丽的肌肤变成土
色，锐利的目光褪去仿佛盖上了一层灰色的膜。

何等丑陋而悲惨的死相。

而沙斯特的死，也证明了毒杀技术相对于剑术和暗黑术的优越性。只要使用这种新型复合毒，
只要一根针，就能让敌人陷入不能拔剑也不能咏唱的状态而断气。

王座上的皇帝，看到这一幕后也会把暗杀公会作为军队的精锐吧。等新型毒大量生产完后，
就不用看骑士和术师的脸色而苟且偷生了。还能重拾自己的名字，回到抛弃自己的扎尔戈蒂
斯家，成为新的支配者……

沉醉在愉悦的顶点，全身震颤的弗·萨，完全没有注意到，视野外搁置着的沙斯特的剑，正
慢慢地再次把刀身升华为雾霭。

——利皮雅。

沙斯特于天命耗尽之前，在心中呼唤着唯一爱着的女性的名字。

利皮雅会下决心暗杀皇帝，肯定是为了帮助沙斯特实现他所说的新时代的到来。因为她相信，
只要终结三百年来的战争，让新的法和秩序照耀暗黑界，那么自己一个人无法守护的孤儿们
也能获得幸福生活下去的权利。

——弗·萨啊。

——在幼年学校被打垮了？受不了败北而自尽？

——但是，至少你是有机会的。为你出学费的父母，每日三餐都有饭吃，还有温暖的床铺和
遮雨的屋子。这个世界里，还有多少幼小的生命一生下来就被剥夺了最低限度的权利，被当
成废品一样用完后就消失了。

——利皮雅为了这样的世界，拼上了性命去纠正它。这份心意绝对不能白费。绝对。被你小
小的个人仇恨——

「……别碍我！！」

本该完全麻痹了的沙斯特口中发出惊人的怒号，同时，以黑骑士的右手为中心高高地卷起灰
色的龙卷风。

这可以说是神器的「超解放」现象了吧。沙斯特强烈无比的心意藉着爱刀为媒体，开始直接
改写构筑演算全Under World情报的光量子集合体。

卷起的龙卷风，已经化为了超越所有命令和Object的纯粹的「破坏力」。没时间躲避，被龙
卷风包围的弗·萨的法袍在发出干枯的声音后化为了尘烟散去。

全身裸露，瘦骨如柴的中年男子，为了遮住崩溃的面容而抬起了双手。但是，很快他的手也
化成无数的肉片飞散开来——继而全身都变成浓密的血雾飘舞在空中。

最强的暗黑术师D·I·L，在濒死的暗黑将军周围卷起奇怪的龙卷风的瞬间，就产生了极度不
详的预感，大步跳开。

但是，在看到右腿被龙卷风碰到，膝盖以下部分被不留痕迹地粉碎之后，这股恶寒变成了生
涯最大级的惊愕。

D就算是在入浴或就寝的时候，身上也有多达数十个防御术保护着。术式的攻击自不用说，
这些防御术乃是能将包括飞行道具，剑，毒等几乎所有类型的伤害都能弹开的铁壁防守。

当然，拥有同级优先度的十侯全力攻击的话，也有可能会贯穿护盾伤到皮肤。但是，不破坏
护盾，直接连着肉体和天命一口气削去，这种事是绝对不可能的。

但是，无论脑中如何否定，还是眼睁睁地看着超越飞翔退避的速度直逼而来的死亡龙卷风把
右腿削去。像D这样的术者，无论肉体受到何种程度的伤害都能靠治愈术完全再生，但前提
是自己还活着。

「呜……哇哇……！！」

最后，从D的口中发出了尖锐的悲鸣。

但是这个声音，立刻被同时扩散的两个哥布林长的惨叫声给覆盖了。

在D左侧并列的山地哥布林族长哈噶西和平地哥布林族长库比利，拖着短脚拼命跑着想要逃
离龙卷风。但是，连全速飞行的D都能追上的龙卷风的膨胀，想要回避是不可能的。

「叽～～～！！」

随着丑恶的叫声哈噶西的脚一滑，跌到了地上。拼命伸出的左手，如老虎钳一样死抓着库比
利的脚踝。

「呀！！放开！！放——！！」

吧唧。

哥布林的两个支配者，轻易地化成血雾飞散开去。

啧。

D的右腿，从根部以下不留痕迹地吹飞了。

美貌被恐怖和绝望极度扭曲的暗黑术师总长眼皮前——龙卷的膨胀奇迹地停止了。

倒下的沙斯特的身体已经看不到了。以那附近为中心，屹立的倒圆锥形死亡风暴，直径已经
扩大到约二十Mel。其他的十侯都迅速退到了墙边，而大厅南侧排列的十军的干部们也有惊
无险。

在极度混乱的思考中，D还是凭着杰出的思考力，找到了龙卷风的膨胀停止的原因。

为了保护十几名暗黑骑士——自己的心腹。也就是说，那个龙卷风果然是按沙斯特的意志作
出来的。

就像是印证这个推测一样，龙卷风的上半部分渐渐地改变了形状。

出现的是，由半透明的雾霭作成的极其巨大的男子上半身。

那彻底锻炼过的肌肉，和剪的尖尖的胡子[fn:11]，不用说正是暗黑将军沙斯特的影像。

身为皇帝贝库塔的加百列·米勒陆军中尉，也不禁产生像是吃惊的感情，望向屹立的龙卷巨
人。

把暗杀者的头颅示众，看到它的同时最左边的骑士就拔出了剑——到这一步都跟预想完全一
样。对想要斩向加百列的男人，将军Unit的一人用麻痹毒还是什么的将他停止这件事也不觉
得有什么意外。

虽然跟自己一击砍下反叛者的头，以此向剩下的九Unit植入绝对的忠诚心这个计划有所偏离，
但是自行保护皇帝的行动也可以判断为是恭顺的表现。因为这个想法才一直坐观事态进展
的——

但是从倒下的反叛Unit身上突然卷起龙卷风，而被其包围的三个将军Unit一瞬间就被消灭，
就算是加百列也不得不停止了思考。将军Unit应该都是同级的状态。那么，对打的话，应该
是跟现实世界的VRMMO里的对战差不多，HP掉了又回复这样的展开。

但现在，数秒内就把三个Unit的HP吹飞是怎么回事呢？难道说这个《Under World》里还存
在自己所不知道的系统或者理论吗？

就在思考的时候，龙卷风的巨人开了口，发出天摇地动的吼叫。

「噢噢噢噢噢噢！！」

卡擦！！伴随着巨大的声响，装饰王座之间的所有华丽玻璃窗都向外侧飞散。

巨人缓缓地握住如冰柜般的右拳——

轰地一声向加百列挥落。

加百列当即判断，无论是拔剑，还是回避都已无济于事。瞥了一眼视野左边，只是皱了一下
一边的眉头跳开了的副官瓦沙克后，加百列依然在王座上翘着脚，感受敲打全身的灰色拳头。

因沙斯特临死前的心意而发动的死亡龙卷风，是超越了Under World的系统演算的现象。不
是通过数值上的攻击力让弗·萨的天命减少、结果导致了他的死亡，而是直接将「死」的意
念送入的Light-Cube里，先是将Fluct Light破坏，然后再逆算把视觉上的肉体给粉碎。

所以，对加百列的攻击，对皇帝贝库塔这个Unit的天命也是没有影响的。

但是，在沙斯特的Light-Cube里生成的杀意，却通过量子通信回路传到了加百列潜行的STL。

STL如果是完全的状态，那传入Fluct Light的感觉层面以外的信号都会被安全装置完全遮断。

但是，突入部队把《海龟》的主电源线给切断了，受其影响所有STL上的限制机能都陷入了
不完整的状态。

暗黑将军沙斯特，经过四十多年的人生练剑，其灵魂所放出的意志，穿过了限制器，直击加
百列·米勒的Fluct Light核心，即司掌自我和生存本能的核心。

这时，沙斯特的主观感觉到，自己已经和自己放出的浑身的一击完全同化，冲进了皇帝贝库
塔的内部。

不用说，原来的肉体的天命已经耗尽。如文字所述，这是沙斯特生涯里最后的剑了。

唯一的遗憾，就是不能再见一次整合骑士长贝尔库利。但是，那个男人一定能理解。暗黑将
军的愿望，和为什么他会杀了皇帝。

算上暗杀公会首领弗·萨，十侯中最为好战的两个哥布林长也已经死了。被暗黑术师总长D逃
过一劫很遗憾，但那样的重伤想要立刻再生是不可能了。加上骑士团团长，要是连皇帝都死
了，剩下的将军们也不会轻易跟整合骑士团决战吧。

但愿从此——利皮雅盼望的和平的世界能到来吧。

与心意同化的沙斯特，贯穿了皇帝贝库塔的额头，进入到他内部充满灵魂的核心。

只要破坏那里，就算是暗黑神，也必然跟弗·萨一样从根本上被消灭。

随着无声的呐喊，沙斯特的意志与皇帝的灵魂碰撞——

然后、产生了生涯最后的惊愕。

没有。

闪耀的光之云一样的灵魂核心，本该充满生命力的真髓的地方，只有深深的黑暗。

为什么。就算是隐士弗·萨的灵魂，也因为对生命执着到贪婪的地步而闪闪发光。

沙斯特的心意被皇帝内部无限延伸的「黑暗」所吞噬，无力地扩散。

消失，然后蒸发。

这个人——这个男人——

他不知道生命是什么吗。

不知道生命的，灵魂的，还有爱的光辉之人。所以饥渴。所以渴求他人的灵魂。

这个男人，无论是多强大的心意，《杀意之剑》是杀不死他的。

因为，这个男人的灵魂，虽生犹死。

一定刚要传达。给谁。在不远的将来，注定刚要跟这个怪物战斗之人。

谁——给谁……

但是，此时沙斯特的意识，被毫无保留地吸入到了皇帝灵魂的深渊。

……悔恨……

……利皮雅……

两种思考绽裂的最后，暗黑将军毕克苏尔·乌鲁·沙斯特的所有存在在两个世界中完全消灭了。

加百列·米勒在过于强烈的灵魂的光辉贯穿自己时，比起恐怖更多的是欢喜。

黑骑士的灵魂，比几天前吃掉的女暗杀者的灵魂，充满着更加浓厚的感情。对那个女子的
爱——以及那无法理解却是对更加广泛对象的慈爱一样的东西。还有以此为动力源的强烈的
杀意。

爱与恨。这世上还有比这更加美味的存在吗。

此时，加百列完全没有意识到自己把生命暴露在了危险之中。看到因黑骑士的攻击，三个
Unit化成了肉片飞散开去，加百列还是比起自己的安全更渴望吞噬骑士的灵魂。

如果加百列对骑士的攻击感到恐惧而寻求生存的话，沙斯特的杀意就会经过STL破坏加百列
的生存本能，连锁地将Fluct Light全部吹飞。

但是，加百列·米勒是个「不懂得生命」的人。对他而言，包括自己在内，所有的生命都不
过是跟小时候大量杀戮的昆虫相同的自动机械而已。只有解开作为这个机械动力源的「灵
魂」——充满谜团的闪耀之云的秘密才是加百列的心愿。

所以，沙斯特的Fluct Light产生的破坏信号，只是飘渺地通过了加百列的Fluct Light的非
活性部分，未产生任何冲撞就消失了。

这个原理加百列是不可能知道的，但是他一边咀嚼着骑士的灵魂，明白了两件事情。

首先，这个世界上，还存在着通常VRMMO游戏里没有的武器/咒文以外的攻击方法。

而这个攻击方法，对自己好像没有效果。

刚才那个现象的原理，以后还要让克里特去调查一下。如此想着，加百列缓缓地从王座站起。

存活的十侯会议的六人，要么把背靠在墙上，要么一屁股摔在地上，还有人边治疗着重伤边
呆然地仰望着皇帝贝库塔的身姿。

所有人心中残留的，只有恐惧。

暗黑将军沙斯特恐怖的超级攻击——瞬间将三名将军切碎，连被视为十侯中最强实力者的
D·I·L的右脚都被吹飞的可怕技能，皇帝从正面接下却没有受到一丝的伤害。

强者支配一切。

所有人都深信，皇帝贝库塔拥有六将军和背后待命的上百名士官加起来都远远不及的力量。

如微波荡漾一样，全体深深地跪下，对皇帝表示恭顺。就连敬爱的骑士长和他的副官被杀死
的暗黑骑士団，也不例外。

头上，贝库塔那依然毫无起伏的声音滔滔回响。

「……失去大将的军队，马上由下一级士官继承指挥权。一个小时后，按预定计划开始进
军。」

对出现反叛者的事，愤怒和斥责的言辞一句都没有。反而在将军们心中激起更深的恐怖。

好不容易给右脚的伤止血完的D，伸直着手指高高举起右手，叫喊道：

「皇帝陛下、万岁！！」

随后——

高呼万岁的附和声音数次响动全城。
** (中间缺 13-65节)
** 66

克里特不禁将身体靠在控制台上，发出了短短的咒骂声。

数万规模的黑点群，从中心向外被急速消灭。

也就是说，基于瓦沙克的策略而投入Under World的中国和韩国VRMMO玩家们，被通过某个手
段歼灭并自动注销了。

黑色圆环的中央部位，用蓝色表示的人界军和用乳白色表示的日本人部队大概还剩余一千人
左右。就算想无视他们这个数量也太多了，而且如果这一千人有着击破三万中韩联合军的力
就更危险了。

「瓦沙克那个笨蛋到底干了什么啊……」

吐着舌头的克里特又看向主显示器。

在日本人部队的近处，还残存着一个闪着强光的红点。是通过2号STL使用自己的帐号转换进
去的瓦沙克。

是因为被捕获或是别的情况而动不了了吗？还是说，他还有单独一人能够对抗上千敌军的什
么手段呢？

克里特忍住自己跑到隔壁STL室把摇着瓦沙克的衣领把他叫起来的冲动。

在对服务器进行GM权限操作被锁定的现状下，无法将帐号初始化。也就是说，如果瓦沙克被
强制注销，现在这个帐号就无法再次使用了。唯一可能做到的，就是进行具有将The SEED程
序分离的功能的内部时间加速倍率的操作，但就算采取这个措施，也需要慎重考虑时机。

克里特神深呼吸了一下，向下看去。

在Under World的最南端，还有一个红点正在高速移动。是袭击部队的队长加百列·米勒中尉。

现在需要考虑的，是人界军追上并阻止目前正打算捕获或是正在追踪爱丽丝的米勒中尉的可
能性是否依然存在。

将美国、中国、韩国的总计数十万玩家们转换进去的结果，大大阻碍了敌方向南前进的步伐。
如今米勒中尉已经在内部离他们有数百英里了。当然，如果用战斗机的话可以一瞬间飞过去，
但很难想象Under World有这样的工具。恐怕最多就是有翼生物的级别而已。

——他们追不上的。

克里特思考了三秒后作出了这样的判断。

距离护卫舰突入的时间，大概还有现实情况下的十个小时。虽然米勒中尉指示在剩余八小时
的时候再次启动加速，但在从外部投入的玩家集团几乎全灭的现在，维持等倍速率的意义已
经没有了。

那么，就应该再次让内部进入一千倍的加速模式，为米勒中尉捕获爱丽丝的任务提供充足的
时间。

「没办法……瓦沙克，就让我们看看你的胆量好了……」

对着如今在北部战场上仍然一动不动的红点低语后，克里特将手伸向了STRA倍率操作的操纵
杆。

抬头看向和操纵杆联动的主显示器上的滑块窗口时，突然他的视线停在了水平刻度上。

现在滑块的指针位于最下方×1的位置。在那上面跨过×100的刻度，在×1000的位置出现了
第一个分隔线。

其实再将视线向上看去，可以看到×1200的位置又有一个分隔线。这似乎是人类通过STL潜
入Under World的场合时的安全上限。

然后，滑块窗口继续延伸到了×5000的位置。如果居民只有Light-Cube中的人工Fluct
Light的话，可以将内部时间加速到这个倍率。

时间加速倍率是通过操作控制杆，然后按下旁边的开闭式保护盖下的按钮加以确定的。克里
特尽量让自己不要碰到按钮，轻轻将控制杆向上推去。

随着显示器上滑块的上升，他同时将视线切换到旁边的数字。

在×1000的位置，感觉到了一点抵抗感。

加上力后，控制杆再次动了起来，在×1200的位置停下了。之后不管怎么用力，都没有一点
动起来的迹象。

「呼呒…………」

被好奇心刺激到的克里特，仔细观察者像是飞机操纵杆一般的大型控制杆。

然后他注意到，在确定按钮的对面，有一个闪着银色光芒的钥匙孔。

「原来如此。」

克里特用一根手指挠着和尚头轻轻笑了出来。

安全限制是一千两百倍，也就是说实际的危险区域在稍微更高的倍率。在以防内部时间所剩
无几的场合下，试着解除安全装置也不算坏事。

回过头去的克里特，对围着只剩下弹孔的机器人说着「为什么？」「为什么？」的队员们打
了个响指。

「喂，谁会开锁的？」

怎么这么软……味道好香……

这无疑是几个月来睡的最舒服的一觉了，所以比嘉健拼命地抵抗着摇着他想要让他醒来的外
部刺激。

「……喂，比嘉君！稍微睁开眼睛啊，喂！！」

但这么做也太过分了吧。

简直不就是像我快死了一样吗。

不管怎么说也太夸张了。我怎么可能被人刺中或是开枪击中……

「——呜哦！？」

随着意识醒来，记忆也一口气复苏。比嘉睁开眼睛叫了出来。

在他面前的，是黑框眼镜反着强光的三十多岁的男人的脸。

「呜哇！！！」

比嘉又喊了出来。

虽然想要退后，但身体却动不了。代替这个动作的，是比嘉因右肩感到一阵剧痛而第三次发
出的怪声。

——对了。

我在电缆管道里被那个男人开枪打中了……

把大量出血不当一回事，只以STL操作为优先事项。虽然将三个女孩子的Fluct Light输出和
桐之谷君的STL直接连接但他还是没醒……然后，发生了什么来的……

「……桐，桐人君怎么样了？」

比嘉用微弱而沙哑的声音问道。

回答他的女性，用带着清凉感的声音说着：

「Fluct Light活性……已经完全恢复了。不如说活动的过头了。」

「这……这样，吗……」

比嘉呼地叹息了一下低声说着。

从那种状态恢复过来简直可以说是奇迹。而且自己在大量失血的状态下活着也算是奇迹般
的——

这时他才想到确认自己所处的状况。

自己睡在副控制室的地面上。右肩缠着绷带。左臂连接着输血包。

然后，醒来时见到的戴眼镜的菊冈中校和脱下白大褂的神代博士各自坐在自己身体的左右位
置。

菊冈叹了口气，摇摇头说道：

「真是的……居然这么乱来……不，没能发现在技术人员里有间谍的我也有过错……」

一直仔细梳好的刘海如今一片凌乱，眼镜的镜片里也可以看到汗珠。仔细看去，神代博士似
乎也满头大汗。看样子是两人对比嘉做了急救措施吧。那么，如同梦中一般感觉到的那种感
触，那时候是……

——嗯？

是谁做了心脏按摩，谁做了人工呼吸呢？

虽然比嘉不禁想要发问，但还是把话停在了嘴边。在世上还有着不该去知晓的真相[fn:12]。

「Under World……爱丽丝怎么样了？」

菊冈轻敲着比嘉的左臂回答道：

「来自美国、中国和韩国的连接者已经全部被击退了。而且，似乎是桐人君一个人将中韩玩
家解决掉的。该说不愧是他呢还是果然如此呢，那个力量实在太厉害了……这也是，比嘉君
努力的结果呢。」

「诶……还有从中国和韩国来的人吗！？不是作为援军……而是作为敌人！？」

比嘉不禁想要做起身体，但却因为从右肩到指尖传来的剧痛而开始喘气。

「喂，别这么乱来！虽然打穿身体的子弹好歹没有伤到神经……关于中国和韩国的玩家，似
乎是被网民间的紧张推动才会连接过来的。虽然确实有转移战场的效果……」

「是……这样吗……」

比嘉轻轻叹了口气。原本在他参加这个Alicization计划的原因中，为了回报在伊朗战争中
牺牲的韩国朋友这一点就占了相当的部分。明明这样，进行中的计划却加强了日本和韩国年
轻网民间的对立情绪，实在大大出乎他的意料。

他好不容易摇了摇头，将思考转向别的内容问道：

「从中国和韩国……来了多少人？」

「似乎超过了四万人。从日本本土前来支援的两千名玩家几乎全灭……」

菊冈用苦涩的声音低声回答。

「当时中国和韩国的玩家大概还有三万人，幸好桐人君……」

「诶，你说什么？」

比嘉不禁打断了指挥官的话。

「桐人君一个人把三万大军消灭了！？……这不太可能。Under World里根本就没有能发动
如此大规模和高威力攻击的武器或是命令。应该是……没有，的……」

说出这句话的时候，比嘉才彻底想起，被那个间谍——柳井开枪打中前后发生的事情。

柳井似乎是被那个名叫『最高祭司Administrator』的Under World人彻底控制了。到底经历
了怎样的事情，才会变成那样的事态呢。

而且还有那个和桐之谷和人的STL连接的，Main Visualizer内的异常Fluct Light。明明只
是个物品，却有着模拟人类意识的功能，之前根本就没有设想过这种情况。

「……那个……菊先生…………」

比嘉感觉到有别于大量失血的寒气袭向身体，向指挥官低声说道：

「莫非……我们……做出了，什么不得了的……」

这时，从控制台传来的尖锐的警报声响彻房间。

是比嘉设置的时间加速倍率变动警报。

** 67

我将自己和亚丝娜的身体和装备全部转换成Under World内拥有移动速度最快的属性的光元
素，在天空中飞行。

就算这么说，这个速度离现实中的光速也相差甚远。要追上前往遥远的南方的爱丽丝，至少
也要三分钟时间。

想要在这段时间里，向亚丝娜说出的、谢罪的、感谢的话已经多到自己都数不清了。然而，
我却不论怎样都无法直视牵着我的手在右侧飞翔的亚丝娜那闪光的身影。

而其理由——

在觉醒后那如同全身的血液都变为火焰的万能感慢慢平静下来后，近期的记忆开始一点一点
经过整理而鲜明地显现出来。

问题是在昨天的深夜。

亚丝娜、爱丽丝和萝涅围坐在睡在马车货架上的我的旁边，一个一个将我的回忆——或者说
是恶行——揭露出来的那一幕，不称其为地狱又该称为什么好呢。

——桐人前辈还是近侍的时候，可是在超漂亮的上级生毕业的时候送上了只在西部帝国才会
开放的花束，让人家大哭了一场呢——

——这么说来，整合骑士团的女副团长不知道怎么回事也被他迷住了呢。那个人好像还叫他
「小伙子」来的……

「呜…………」

我不禁双手抱住了头。

「呀————」

这算是呻吟吗……

然而在这个瞬间，由于意识不再集中，身体的属性立刻恢复原状。强烈的风压敲打全身，我
一下子陷入了绕着圈子下落的状态。[fn:13]

虽然低声说了一句糟糕，但总之还是将大衣下摆变成翅膀形状，从而控制身体的平衡，然
而——

「呀啊啊啊啊啊啊！！」

按着裙子的亚丝娜从上空笔直落了下来。

我又喊出一声糟糕，慌忙伸出双手。

好不容易将她接住的一瞬间，亚丝娜那大大睁开的榛色眼睛，一下子盯住了我。就是这里。
只能在这里谢罪了。

「亚丝娜……不是这样的！！」

这根本不是谢罪而是借口吧。然而已经没法回头了。

「我和索尔缇莉娜前辈以及法娜提欧副团长之间真的什么事情都没发生过！我向丝提西亚神
发誓，绝对什～～～么都没发生过！！」[fn:14]

听着我拼命辩解的话的亚丝娜的脸——

慢慢缓和了下来。她那小巧的双手揪住我的脸颊，像是被惊呆了一般说道：

「……桐人君你真是一点都没变呢。明明以为你在这里努力了两年，好歹也成熟了……一
点……呢…………」

亚丝娜的双眼突然溢出了透明的泪珠。她的嘴唇如同发抖一般颤动着，挤出了沙哑的声音：

「太好了……桐人君……一点都，没变啊……我的……」

「怎么会……我就是我啊。怎么可能会变啊。」

「因为……那简直就像神一样啊。将那么多人的军队，一瞬间就解决掉了……又把两百人一
下子回复过来……而且，还飞在天上……」

听她说到这里，我不禁苦笑着回答道：

「只是比别人稍微熟悉一点这个世界的机制罢了。像飞行这种程度的，亚丝娜只要习惯了很
快就能做到了。」

「就算做不到也没什么。」

「诶？」

「能这样抱着我飞就好了。」

笑脸上带着泪光的亚丝娜这样说着，将双手从我的脸移到背后，紧紧抱住了我。脸颊被她松
开的我也紧紧抱住她，重新开口说道：

「真的……谢谢你，亚丝娜。明明受了那么重的伤，还保护了人界的人们……明明那么
痛……」

这个世界内痛苦的鲜明程度，我在两年前的终结山脉里被哥布林队长砍到的时候就了解了。
那时，只不过是肩膀被划到而已，就已经痛到让我一段时间内站不起来了。

明明如此，在被外部连接者的大军包围之下，亚丝娜带着全身那凄惨的伤口仍然战斗到了最
后。如果亚丝娜没有这么努力的话，缇卓和萝涅她们所在的人界部队，大概早就被歼灭了吧。

「嗯……不光是我哦。」

听到我的话的亚丝娜，将紧靠着的脸颊稍微转动了一下。

「诗诺诺、莉珐、莉兹、西莉卡、克莱因、艾基尔……还有，瞌睡骑士团和ALO的各位，都
已经非常努力了。而且还有整合骑士雷恩利先生、人界军的卫士们、萝涅和缇卓也……」

说到这里，亚丝娜像是吃惊了一般，突然伸直了身体。

我在听到她的下一句话前，就明白她这样做的理由了。

「啊……对了，桐人君！骑士长……贝尔库利先生，为了追赶敌人的皇帝，一个人……」

「…………」

我慢慢摇了摇头。

我已经感觉到，到头来连对话都没能做到的，贝尔库利那宏伟的剑气，已经不存在于这世上
了。

我曾和他在这战争开始之前，仅有一次以想象力之刃——他称之为《心意》——互相交手。
在徐徐复苏的我的记忆中，贝尔库利在那时已经预感到自己会死去了。

他在三百年人生的终点，选择了为保护爱丽丝而战斗。

领悟到我动作中的含义，亚丝娜的双臂抱的更紧了。她轻轻啜泣着，但很快就停下呜咽，向
我问道：

「……爱丽丝……没事吧……？」

「嗯，还没有被抓到。很快她就会到达世界的尽头……第三个系统控制台了。」

「这样啊……那么，我们一定要保护她。为了贝尔库利先生。」

轻轻和我分开的亚丝娜的脸上，虽然全是泪水，但却充满了强烈的决心。我慢慢点了点头。
然而，亚丝娜的眼睛，却稍微摇动了一下。

「不过，现在……这一会，就这一会，只做我一个人的桐人君吧。」

随着她的低语而靠近过来的嘴唇，将我的嘴唇塞住。

在异世界的血红天空之下，缓缓拍动着黑翼的我，和亚丝娜交换了一个长长的，长长的吻。

在这个瞬间——我终于想起，自己为何会在两年半前落入这个世界了。

在那个六月份的雨天。

在送亚丝娜回家的路上，我们被《死枪事件》的最后一名主犯，《微笑棺木》的干部Johnny
Black袭击了。由于被注射了大量的肌肉松弛药物，记忆完全中断了。恐怕我因为呼吸停止，
脑部受到了相当的损伤，为了治疗我才动用了STL和Under World吧。

可以称之为SAO时代的怨灵的，赤眼XaXa和Johnny Black都被逮捕，而不知为何混在《海龟》
袭击者中间的《微笑棺木》的首领PoH如今也已被变为小树的形态束缚在这个世界。如果时
间加速再次启动，他在被外部强制切断连接前都会在感觉被阻断的状态下度过几天或是几周
的时间，精神上应该会受到不小损伤。至少也和这半年间的我一样。然而我绝对不会认为这
是残酷到做过了头的事情。

因为那家伙说了，他会盯上亚丝娜。[fn:15]

在经过足以让存在融为一体的令人目眩的时间后，我和亚丝娜的嘴唇分开了。

「想起那时候的事情了呢……」

亚丝娜刚一说出话就突然停了下来。我马上就明白她这么做的理由了。

那个时候——是SAO被攻略后，浮游城崩毁的时候，红色的晚霞下的那个吻。没错，那是别
离之吻。

我微笑着，如同要将这不吉利的预感赶走一般坚定地说道：

「那就出发吧。打到敌人，救下爱丽丝，大家一起回到现实世界……」

我的话没能说完。

从我的脑海中响起紧张的大声呼喊：

『桐人君！桐之谷君！！听得到吗！？桐人君！！』

这苦涩的声音是——

「诶……是你吗，菊冈先生？」

『对，能听到！不好意思……出大麻烦了！！时间加速倍率……那帮混蛋，把STRA限制
给……！！』

** 68

克里特带着些微不安，注视着额头上迸出血管，用两根电线插进钥匙孔里来回转动的布利格
留着胡子的脸。

虽然他很有气势地说着「开锁就交给我好了」，但STRA的操纵杆的安全程度和廉价公寓的旧
式转筒锁可不一样。他指尖的动作越来越粗暴，而嘴里吐出的脏话的声音也越来越大。

站在布利格后边的汉斯，看着左手上带着的表，像是很开心的说道：

「喂——，过了三分钟了哦。再过两分钟就要给我五十刀了呢～」

虽然电线戳动的声音与其说是开锁还不如说是破坏行为，但克里特还是把「果然还是算了吧」
的话停在了嘴边。从这两个人打赌开始，到决出结果之前谁都没法阻止他们。

「还剩一分钟了～差不多可以准备钱包了哦～」

「Holy Shit！！」[fn:16]

随着一声大喊，布利格突然站了起来，将电线被切断的一段扔在了地上。

克里特安心下来，想到他果然还是放弃了吗，这时——

脸上一片通红的士兵，无言地从腰间的枪套里拔出巨大的手枪，将枪口指向钥匙孔。

「喂……等等…………」

一声枪响。接着又是一声。

布利格在哑口无言的众人面前将沙漠之鹰收回腰间。接着他先看向汉斯，接着又看向克里特，
耸了耸肩说道：

「开了。」

克里特张大嘴巴，将视线移向如今变成了直径两英寸的黑洞的钥匙孔。

在黑暗的深处，闪起两三次火花后，停在倾斜状态的操纵杆再次动了起来。操纵杆动了大约
五英寸后，带着咔的一声轻响停了下来。克里特看向显示器上的数字，比之前设定的1200倍
稍微往上——的位置，被设定为上限的×5000的数字闪着光芒。

这时，又响起咔的一声。

操纵杆向更深处倾斜。

「喂……骗人的吧…………」

在自言自语的克里特面前，显示的数字超过了5000——超过了10000……

不，还没什么。只要不按确定按钮，实际倍率就不会发生变动。还是可以轻轻将操纵杆拉回，
当成什么事情都没发生的。

「喂……别碰！！谁都别碰！！」

克里特喊着话，挥手将汉斯和布利格从控制台边赶走。

接着他回过头，向操纵杆伸出右手。

砰。

还没等他的手碰到操纵杆，就响起了轻微的爆炸声。

在黑客面前，红色的按钮和透明的保护盖都一起被炸飞了。

主控室正面墙上的大显示器染成一片红色，从扬声器里传来震耳欲聋的警报声。

比嘉在听到时间加速机能被再次人为操纵的警报的瞬间，就再次想要坐起来，因剧痛而扭起
了脸。

「比……比嘉君！都说了叫你不要乱来……」

神代博士跑过来用手撑住比嘉的身体。紧接着……

副控室的主显示器被染成一片红色。

「什……什么！？」

喊出声音的是菊冈。越过跑向控制台的指挥官的肩膀，被支撑着站起来的比嘉拼命凝视着屏
幕。

显示器上用巨大的字体显示的，是通知对STRA机能加以限制的三段限制器全被解除，Under
World整体将进入《极限加速阶段》的倒计时。

「什么…………」

代替无言喘息着的比嘉，神代博士尖锐地问道：

「极限加速是怎么一回事！？STRA倍率的上限不是一千二百倍吗！？」

「那……那个，是有人潜入Under World时候的限制倍率……只有人工Fluct Light的时候，
上限是……五千倍……」

听到如同自动回答一般的比嘉的话，神代打了个冷战睁大了眼睛。

「五千！？也就是说……这边的一秒，对应内部的八十分钟……这边的十八秒在那边不就是
一天了吗！！」

听到神代的声音，比嘉和菊冈对视了一下——然后一起机械地摇了摇头。

「诶……有什么不对的吗？」

「一千二百倍是考虑到现实世界的人类灵魂寿命设置的安全上限……五千倍是从外部可以观
察Under World的上限……哪个都不是硬件层面上的极限倍率……」

比嘉从喀拉喀拉快要干枯的喉咙里拼命挤出了话。支撑着他的神代博士的手臂颤抖了一下。

「那，那么……硬件层面的上限……到底是……」

「就像你已经知道的一样，Under World是用光量子构筑并计算出来的。通信速度事实上没
有限制……也就是说上限，是根据下位服务器搭载的架构规定的……」

「赶紧说啊！到底是多少倍！？」

比嘉闭上眼睛说道：

「在《极限加速阶段》……STRA的倍率，会稍稍超过#五百万倍#。通过卫星线路连接的位于
六本木的两台STL，没法对应那样的速度，所以会自动断线……但对在这里使用STL的两个
人……」

现实世界的一分钟——对应内部的十年。

瞬间心算出这个对应关系的神代博士睁大的双眼轻轻地痉挛了一下。

「怎么会……这样……快点……不让明日奈小姐和桐之谷君赶紧从STL出来的话！！」

这次比嘉紧紧按住了打算站起来的博士的手臂。

「不行，凛子小姐！在已经进入初期加速阶段的情况下，随便把他们从机器里拉出来，
Fluct Light会飞走的！！」

「那就赶紧开始断线处理啊！！」

「我就在想刚才为什么要刻意从电缆管道下去了！STL操作只能在主控室进行！！」

比嘉反驳着，视线转向控制台前的指挥官。

菊冈立刻察觉到了他想说的话。

「……菊先生。我要再下去一次。」

指挥官听到他的话，点点头回答道：

「明白了，我也去。背着你从梯子上下去的体力我还是有的。」

「不……不能去，中校！！」

中西上尉喊了出来。面无血色的他踩着靴子向前走了几步。

「太危险了。这个任务就由下官……」

「隔墙还要再开一次，你们必须做好通道的防御工作。没时间了，这是命令！」

听到带着至今从未有过的锐利表情的菊冈说出的话，中西一下子张大下巴，低下了视线。

比嘉战战兢兢地抬起右手，确认还很痛的指尖还能正常活动，同时拼命思考着。

显示器上显示的，距离进入《极限加速阶段》的倒计时已经不足十分钟了。

然而现在就再度开放耐压隔墙，从那长长的梯子上降下，通过连接装置进行STL切断操作不
管怎么算也要三十分钟。

在这二十分钟的时间差里，Under World内的时间要经过——二百年。

这是远远超过人类灵魂寿命——一百五十年的岁月。

在此之前，Under World度过了这近乎无限的年月……但现实世界的人，到底还是没法承受……

在Under World的内部……

「对……对了！！」

比嘉喊出了声音，左手向着菊冈挥动。

「菊，菊先生！！刚才操作STL的时候，我保留了和桐人君间的通信频道！请呼叫C12号线
路！！」

「可，可是……要说什么……」

「让他们从内部脱离！！在剩余的十分钟内到达系统控制台，或是天命全损的话，STL会自
动开始切断处理！！但是，控制台在进入了《极限加速阶段》之后会无法运转，如果死掉就
会变成最糟糕的情况！！在全部感觉都被阻断的状态下度过二百年……只有这个事情要强烈
警告他们！！」

** 69

「二…………」

二百年！？

我好不容易才将到了嘴边的话收回去。

眼前的亚丝娜带着紧张的表情看着我。她听不到菊冈的声音。

『听好了，桐人君，还剩十分钟！在时间限制前到达控制台，然后自行注销！！如果不管怎
样都做不到的话，也有让自己天命全损的方法……但这既无法确定，而且也非常危险，理
由……』

因为可能不得不在近乎死亡的状态下度过二百年的时光。

领悟到这一点的我，打断了菊冈的话说道：

「知道了，我会想办法从控制台脱离的！当然，我们会带上爱丽丝，所以请做好准备！」

『……抱歉，但是，现在相比确保爱丽丝的安全，你们两个人的脱离更为重要！听好了，就
算在注销后删除记忆，二百年的时间也远超过人类灵魂的寿命了！意识恢复正常的可能
性……接近于零……』

我平静地回答声音中带着苦涩的菊冈：

「别担心，一定会回去的。然后，菊冈先生。半年前……不，是昨晚，对你说了很过分的话，
抱歉。」

『不……我们早就把被指责当成理所当然的事情了。考虑到会被你打一顿，这边已经准备好
药膏了……貌似比嘉君做好准备了，我也要走了。』

「好的。那就十分钟后再见了，菊冈先生。」

之后，通话就切断了。

我拍着将大衣下摆变成的翅膀浮在半空，注视着臂弯里的亚丝娜。

「……桐人君，和菊冈先生取得联系了吗？发生了什么……不好的事情吗？」

慢慢摇了摇头——我回答道：

「不……他只说十分钟后会再次启动时间加速，让我们赶快注销。」

亚丝娜眨了眨眼睛，露出淡淡的微笑点点头说道：

「是呢，要是一直这样子的话就对不起爱丽丝了呢。那就去救她吧！」

「嗯。那就要再飞了呢。」

我紧紧抱住亚丝娜，再次将二人转换成光元素。无数的颜色变成了金色的光辉。

捕捉到前往遥远南方的爱丽丝，和追逐着她的巨大的异样气息——我们再次飞了起来。

被追上了。

在雨缘的鞍上回头看向后方的爱丽丝轻轻咬住了嘴唇。

在血红色天空的背景下，漂浮在空中的黑点，比五分钟前变得更大了。相比逐渐加速的敌人，
两头飞龙的力量则已经消耗殆尽。

虽然是在几乎毫不休息的情况下一直飞行，但努力到这个地步也近乎奇迹了。只花了半天时
间就飞过了数倍于人界直径的距离。两头飞龙无疑是消耗着自己的天命持续着极限飞行。

然而——那个追踪者到底是什么。

通过远视术的确认，那个人似乎坐在和飞龙不一样的奇怪的有翼生物的背上。然而，那种生
物在人界和暗之领域根本就没有见过。

追上来的人应该就是借助了暗黑神贝库塔的《Real World》的人了。

然后，他曾经被骑士长贝尔库利的舍身之剑杀死了。但他却再次获得了新的生命进入这个世
界，追逐着爱丽丝。

爱丽丝为这贬低了贝尔库利的死亡的做法，感到绝不可原谅他的愤怒。

然而，爱丽丝在这数个小时的飞行中，终于明白自己要做的事情了。

如果敌人在这个世界是不死的存在的话——

那就在《Real World》里杀掉他。

为此，无论怎样都要到达《世界尽头之祭坛》。虽然她下定了决心，但似乎怎样都无法将其
实现了。

爱丽丝将视线转回前方，看着透过正前方血红色的天空，那有着惊人规模的伸向天空的薄薄
的断崖绝壁。那就是传说中《世界的尽头》。和可以乘坐飞龙越过的《终结山脉》不同，环
绕暗之领域的断崖，有着几乎无限的高度。

在那断崖近处，和飞龙们差不过相同的高度上——

有一个小小的浮岛飘浮在空中。

底面是尖脚杯的形状。推测不出它是凭借怎样的力量才能在空中漂浮的。

集中视线，在平坦的浮岛上面中央，可以看到人工建筑物。恐怕，那个就是自己所赶赴的
《尽头之祭坛》吧。世界的出口。通向《Real World》的入口。『真实』所在之处。

虽然很可惜，但相比背后的敌人，还是有点远了。

爱丽丝轻轻闭上眼睛，深深吸一口气，然后慢慢呼出。

她用右手轻轻抚摸爱龙的头，命令道：

「谢谢了，雨缘，还有滝刳。到这里就可以了，降落到地面吧。」

两头飞龙鸣着微弱的声音，一起开始螺旋降下。

下面的地形，在稍微一点时间前，变为如同将虚无具现一般的黑色沙漠。在似乎要将神之创
造吞没一般荒凉的沙漠之海中划出长长的轨迹，两头龙以近乎倒下的姿势着陆了。

爱丽丝立刻从喉咙深处发出呼噜噜噜噜的沙哑声音，身体横躺在地上的雨缘背上下来。她摸
索着腰间的口袋，取出最后一小瓶灵药。

将蓝色的液体一半注入飞龙半张着的嘴巴，然后将剩下的一半一滴不剩地注入旁边的飞龙。
就算是神圣教会制作的灵药，也完全不够回复飞龙巨大的天命，但让它们再次起飞还是可以
做到的。

爱丽丝的双手，轻轻抚摸着两头飞龙生长着软毛的下颚。

「雨缘，滝刳。」

爱丽丝呼唤着，两眼间自然地浮出了泪水。她拼命忍耐着，继续说道：

「就在这里分开吧。这是最后的命令……飞到人界，回到西域的龙巢，雨缘去寻找丈夫，滝
刳去寻找妻子吧。生下小孩，将它们茁壮地养育起来。去生下总有一天驮着骑士飞翔的，强
大的孩子吧。」[fn:17]

突然，雨缘抬起头，舔舐着爱丽丝的脸颊。

滝刳将鼻子贴近爱丽丝的腰部，闻者垂在那里的星霜鞭的味道。

在两头飞龙的头离开的同时，爱丽丝下了命令：

「去吧！！不要回头，笔直地向前飞吧！！」

咕噜噜噜！！

两头飞龙同时抬起头，发出高声的鸣叫。

如爱丽丝所命令的一般，它们没有回头，开始笔直地向西助跑。

在咚咚咚咚的沉重脚步声后，伸展开来的双翼卷起了沙漠之风，巨大的身体漂浮在宇宙中。

兄妹龙以双翼几乎碰到的距离拍打着空气，一口气提升了高度。

然后——

雨缘那长长的头转了回来。

它那银色的眼睛，笔直地注视着爱丽丝。在飞龙的眼角，一颗大大的泪珠流过，闪着光辉在
空中消散。

「雨……缘……？」

没等爱丽丝的话说完——

将头转回前方的飞龙和它的兄长，激烈地拍打着左翼，身体转动了九十度。

响起猛烈的鸣叫的同时，两头飞龙开始全速升空，笔直地向着已经接近到可以用视觉确认的
距离的追踪者直线飞翔。

「不可以……不可以！雨缘，不可以！！」

爱丽丝尖叫着跑了起来。

然而，沙漠中黑色的沙粒缠住了她的长靴。

在倒在沙漠中，伸出手的爱丽丝的视线前方，雨缘和滝刳划着两道螺旋，向不死之敌即将到
达的高空突进。

银色的龙鳞反射出赤红色的阳光，如同火焰一般闪耀着。

排列着尖锐牙齿的龙颚大大张开。

两头飞龙毫不考虑追踪者是否进入了射程，拼命吐出了热线。爱丽丝看到了贯穿长空的纯白
光芒，仿佛飞龙的生命在燃烧一般。

坐在怪物背上的敌人，虽然看到了袭来的超高热量，却一点也没有改变行动轨道。

他只是毫不掩饰地伸出左手，张开五指。

他防御不住的。飞龙的热线，乃是除了整合骑士的记忆解放攻击和高位术士的集合多重术式
之外在这个世界有着最高优先度的攻击。而且还是两条。不管怎样他都不可能有在如此短的
时间内组成能够与之对抗的防御术的余地。

爱丽丝推测着——或者是祈祷着。

然而。

伴随高亢的共鸣袭来的两条热线将敌人的身体吞没烧尽的瞬间之前，发生了超出爱丽丝理解
能力的奇怪现象。

以追踪者的左手为中心，漆黑的暗之漩涡扩散开来。

周围的景色如同落入黑暗一般开始歪斜。连包含了惊人的威力的飞龙的热线都不例外。以直
线轨道前进的热线被扭曲，颜色变为蓝紫色，就这样被吸入了那个男人的左手——

只有数道光芒飞散，连声音、闪光和爆炸都没有，两条光线被黑暗吞没了。

虽然那个男人在不论怎样的术式或剑技都无法够到的高空中飞行，从地面上看过去只是一个
黑点，但爱丽丝却看到了敌人的嘴边露出了淡淡的微笑。

紧接着。

咔！！随着震耳欲聋的响声，从男人左手中盘旋的黑暗中，迸出数道漆黑的闪电。

简直就像是将飞龙的热线吞噬、咀嚼、消化后变为自己的力量后吐出的攻击，无情地贯穿了
正在飞翔的雨缘和滝刳的身体。飞龙们的身体剧烈摇晃，鲜血和白烟在空中弥漫开来。

「雨……雨…………」

喘息着的爱丽丝，尽力将手伸向高空喊道：

「雨缘——！！快逃！！已经够了，快逃——！！」

爱丽丝的悲鸣确实传到了飞龙们的耳边。然而两头飞龙宛如听到爱丽丝的声音重新下定了决
心一般激烈地拍打着双翼，再次开始突进。

飞龙的嘴巴大大张开。从牙齿的缝隙间，出现如同阳光一般的热气，白焰闪耀着光芒。

噼啪！！

第二次放出的热线在空中灼烧。

这一次男人再次展开了暗之盾，将光之箭挡了下来。

明明知道和之前一样的反击会再次袭来，两头飞龙仍然果敢地向前突进。飞龙们的双翼猛地
拍动着空气，向敌人直线飞去。

从贯穿两头飞龙的身体的伤口处飞散的鲜血化为火焰，逐个剥落下来的银色鳞片变为闪光的
粒子在空中飞舞。

两头飞龙，将自己变成了光。

飞龙燃尽生命放出的热线，填满了暗之漩涡，使其渐渐饱和了。男人的左手，开始因无法承
受熊熊热气而涌出白烟。

然而——这时。

敌人的全身被蓝黑色的暗之面纱包裹住了。从左手放出的虚无漩涡逐渐增强，紧接着，从漩
涡中央放出的黑色闪电开始将白色的热线推回。

互相冲突的白色与黑色的力量，仅仅持续了一秒左右。

然后一下子逆转了。

无数的黑色闪电，向着因力量耗尽而减慢了拍动双翼的速度的雨缘和滝刳飞去——

「不要啊——！！雨缘！！雨缘——！！」

爱丽丝的尖叫，随着泪水在沙漠的空气中散去的这一瞬间。

星辰从天上坠落。

两个闪光，从天上以惊人的速度降下。

其中一个就这样落向地面。

而另一个，在飞龙和追踪者的中间，毫无缓冲地停了下来。白光一下子飞散，露出了藏在里
面的身影。

是人。

是个剑士。

尖锐的黑发和同样一片漆黑的大衣在风中摇摆。后背上则装备有交叉着的黑白两把长剑。他
将双臂抱在胸前，傲然地注视着袭来的暗之闪电。

啪！！啪！！

随着冲击声，闪电打到了剑士身上。不，正确来说，是还没碰到就被弹开了。在那抱着双臂
站在空中的身影前方，被不可见的障壁阻挡，空然散发着威力消失了。

爱丽丝只是屏住呼吸，睁大眼睛仰望天空。

黑衣的剑士慢慢回头，看向地上的爱丽丝。

虽然还留有少年的痕迹，但那锐利的容貌上却露出了淡淡的微笑，漆黑的双眼闪着强烈的光
芒。爱丽丝感觉到，内心深处散发出剧烈的火花。那与其说是感情，不如说是如同有着真正
的让爱丽丝的心燃烧起来的力量。

爱丽丝意识到从自己的双眼又流出了新的泪水，低声说道：

「桐……人…………」

从长达半年的沉睡中苏醒的青年，一瞬间露出可靠但又有点不好意思的笑容点了点头，接着
转过身体笔直抬起右手。

在他的背后，濒死的两头飞龙正用最后的力量拍动翅膀。飞龙双翼的末端，和长长的尾巴尖
端，宛如被光溶解一般开始消失了。

雨缘看着在露莉德郊外的家中一起住了半年的桐人，歪着头，轻轻发出咕噜噜噜的声音。

桐人向它点了点头，闭上了眼睛。

突然，虹色的光膜覆盖在两头飞龙上，简直就像是用巨大的泡沫包裹住了一般。

然而两头飞龙却毫不害怕，折起双翼，弯下了头，将身体缩了起来。

在爱丽丝的头上，两个光球开始慢慢飞舞而下。

在忘记了呼吸，只是抬头仰望的爱丽丝的视线前方，发生了不可思议的现象。

被七色光芒缠绕的雨缘和滝刳的巨体，一点一点变小了。不，与其说是变小——不如说是变
得越来越幼小了。

锐利的钩爪变圆了。银色的鳞片变成了柔软的绒毛。尾巴和头部也一点点变短，双翼从皮膜
变为长长的羽毛。

等到被爱丽丝伸出的双手轻轻接住的时候，两头飞龙的身体全长已经不足50Cen了。有着蓝
白色毛皮的滝刳闭上了眼睛，似乎陷入了沉睡。

然后，如同绿色软毛球一般的雨缘——变成了和过去，两头飞龙的母亲天命归零时，在臂弯
间悲啼时一样的姿态的爱龙，笔直地仰望着爱丽丝，从珍珠一般的牙齿间发出了短短的声音：

「啾噜」

「雨……缘……」

从低语着的爱丽丝脸颊上流下的眼泪，弹在飞龙的皮毛上闪着光芒。

紧接着，包裹两头幼龙的虹色光开始一口气增加了亮度。爱丽丝的手臂，被切实的硬度压住
了。在她眨了眨眼睛后，臂弯间的两头幼龙已经变成了两个龙卵。

白银色的龙卵一点点变小，直到最后变成可以在手掌中并排的大小后，七色的光辉这才消失。

爱丽丝将两个小小的龙卵轻轻放在脸旁，模糊地推测着这个现象的意义。判断出雨缘和滝刳
的天命已经损耗到无法通过术式回复的程度的桐人，将两头飞龙的天命上限降到了最低限
度——也就是将它们从幼龙还原成卵，使其免于被消灭。

就算是如今已经成为世界最强术士之一的爱丽丝也无法想象要通过怎样整合术式才能实现这
样的效果。然而，她已经不会对此感到惊讶了。

双手温柔地抱着龙卵的爱丽丝，笔直地仰望天空，带着呜咽低声说道：

「谢谢你……欢迎回来，桐人。」

虽然声音无法传到遥远的高空，但黑衣人仍然点了点头，露出了微笑。

爱丽丝的耳边，传来了怀念的声音。

——我才该道谢……这么长时间，让你担心了。

——谢谢你，爱丽丝。

——之后就在《Real World》见面吧。

接着，桐人慢慢转过身体，面对被黑暗缠绕的追踪者。

二人之间的空间，因无法承受压迫空间的心意而发出白色的火花。

「……桐人……」

那个敌人，就算是你，也无法用寻常的攻击击毙。

恐惧着的爱丽丝咬紧了嘴唇。

突然，从旁边传来了声音。

「没事的，爱丽丝。」

爱丽丝回过头，看到穿着珍珠色装备的一名从《Real World》来的少女站在那里。

「亚丝娜……」

柔软的茶色头发在空中飘舞。亚丝娜微笑着拍了拍爱丽丝的后背。

「相信桐人君吧。我们要赶紧去《尽头之祭坛》了。」

「诶，诶诶……」

虽然点了点头，但爱丽丝知道这已经没那么容易了。

重新转向正南方的爱丽丝，仰望着屹立于遥远的地平线上的《世界的尽头》的断崖，和在断
崖近处漂浮的白色浮岛。

「我想《尽头之祭坛》大概就是那个浮岛了……已经没法乘坐飞龙的现在，不管怎么样都到
不了那种高度……」

「没关系，交给我吧。」

亚丝娜点点头，从腰间拔出华丽的细剑。

她将细剑笔直指向远处的浮岛，闭上长长的睫毛。

「啦————」

突然，昨夜听到的天使们的合唱响彻高空。

七色光芒从天空向漆黑的沙漠直线降下。

咚！！

随着沉闷的声音，面前的沙海中，浮现出白色的石板。

咚！咚咚咚咚！

在石板的另一端，出现了更高的一块石板，接着又是一块。

在屏住呼吸的爱丽丝面前出现的伸向遥远天边的白色大理石阶梯，仅过了不到二十秒就与浮
岛连接起来。

完成地形操作垂下细剑的亚丝娜，一下子跪在了沙漠上。

「亚、亚丝娜！！」

「我……没事的。快走吧……距离祭坛关闭，只有不到八分钟了……」

关闭？

爱丽丝仓促间没能理解这句话的意思。在她想要提问之前，右手已经被紧紧握住了。

站起来的亚丝娜以惊人的速度在阶梯上奔驰，被她拉着的爱丽丝也跑了起来。在前进的途中，
爱丽丝又一次回过头，仰望在高处与敌人对峙的黑衣剑士。

——桐人，想要对你说的话，想要对你问的话，已经数也数不清了！！

——一定要赢啊。战胜那个敌人，然后再一次回到我的身边吧。[fn:18]
** 70
漆黑沙漠中的大理石浮空阶梯，和在阶梯上飞奔着的两位少女剑士的身影，美的令人叹息。
可以说是诗一般的象征了。

我将这一景象印入脑海，在心中自言自语。

——爱丽丝，亚丝娜。

——在此……永别了。

我没有将下次时间加速倍率将到达五百万倍，以及如果在此之前不能自行脱离的话就要在这
个世界度过二百年的事情告诉亚丝娜是有原因的。

如果知道了的话，亚丝娜也好，爱丽丝也好，一定会选择和我一起战斗的吧。哪怕这意味着
无法在十分钟的期限内脱离这个世界。

我在感觉到追逐爱丽丝的敌人气息的那个瞬间，就为其异样感而大为战栗。不。已经不能用
气息来表达了。位于那里的，只有虚无。将一切信息吞没的，连光都不放过的黑洞。

在时间限制前将这样的对手击败，然后三人一起平安脱离的可能性相当低。因此，我自然而
然地确定了行动的优先顺序。

让亚丝娜和爱丽丝确实地从Under World注销。

此外的优先事项就没有了。一个都没有。

我将这如同版画一般美丽的景象深深刻入记忆，接着转过视线，笔直看向面前『敌人』的身
影。

终于与我相遇的那家伙——不，那个，可以说是只能称之为奇特的存在。

是一个男人。这点我知道。

然后，我也只知道这一点了。

脸部的外形，如果说这是自己制作的形象的话，恐怕是意图再现『白人男性普通的容貌』吧。
眉毛也好眼睛也好，鼻梁、嘴角、轮廓都没有任何特征。只能表现出白皮肤蓝眼睛，以及淡
金色的头发而已。

体格在白人中也相当普通。既不胖也不瘦的身体上，穿着类似军服夹克的衣服。但也不能就
此说这个男人就是军人。因为在夹克上下涂抹的黑色和灰色迷彩，如同某种粘液一般不断流
动。只能说这是那个男人的『不定』特征的表现形式了。而且，左腰装备的也不是枪，而是
长剑。

在移动中，我已经从亚丝娜那里知道这个男人是袭击了《海龟》的特种部队——恐怕和美军
有关——的一员。那么，他应该是被打算夺取人工Fluct Light相关技术的组织或企业重金
雇佣的佣兵了。然而，我无法想象这个在稍微远一点的地方用如同玻璃一般的眼睛看着我的
男人，只是个寻求现实利益的人。不，甚至感觉不到他像是个人了。

在大约一秒钟的思考与观察结束后，我开口说道：

「……你是什么人？」

即刻传来了回答。男人用顺滑到到像是什么金属一般的声音说道：

「追求、盗取、掠夺之人。」

缠绕男人全身的蓝黑色的暗之蠕动的势头又增强了。我的脸颊可以感到微弱的风。空气，不，
是『信息』被吸进了黑暗中。

「追求什么？」

「灵魂。」

随着问答的一来一去，吸引力也在增强。不仅是构成空间的信息。感觉我的意识也在一点一
点被虚无的重力吸取。

男人嘴边第一次露出了表情。那是如同稀薄的气体一般的笑容。

「你又是谁？为什么会在这里？又是基于什么立场站在我的面前？」

他反过来向我提问了。

我——又是什么人呢？

降临Under World的勇者？——怎么可能。

守护人界的骑士？——不对。

脑内浮现出否定的话语，有什么东西从我的身体里被吸出来夺走的感觉。然而，不知为何思
考就是停不下来。

通关SAO的英雄？——否。

最强的VRMMO玩家？——否。

《黑色剑士》？《二刀流》？——否、否。

不论哪个，都不是我所期望并描绘出的存在。

那么，我又是什么人呢……？

意识逐渐淡薄的瞬间。

那个怀念的声音，从心底深处呼唤我的名字。

我将不知何时低下的脸抬起，叫出那个被呼唤的名字。

「我是桐人。剑士桐人。」

啪！！

飞出的白色火花，将缠绕着我的暗之触手切断。思考立刻恢复了清醒。

刚才的现象到底是什么！？

这个男人——通过两台STL，可以直接干涉到这边的意识吗？

我展开想象力的防御壁，凝视着男人的眼睛。那眼中只有虚无。将他人的心灵吸收的，深不
见底的黑暗。

这场战斗，恐怕要凭借定义自己如何强大，以及对手对自己的定义来决出胜负了。

「你的名字又是什么？」

我无意识地大声问了出来。

男人稍微思考了下，说出了名字。

「加百列。我叫加百列·米勒。」

我凭着直觉明白，这既不是角色名，也不是假名，而是这个男人的真名。

因为，说出这句话时男人的容貌发生了变化。目光变得异常锐利，带着如同寒冰一般的冷酷
感。嘴唇稍微变薄，脸颊也变得瘦削了。

同时，从全身喷出的暗之气氛一口气增加了厚度。

直到这时，我才第一次注意到男人的右臂从肩部向下都有所缺损。到刚才都如同手臂一样蠕
动的不定形的黑暗，开始慢慢伸长，碰到了腰间的剑。

随着滑腻的声音拔出的剑，并没有实体的刀身。

只有蓝黑色的暗如同一米长的火焰一般燃烧着。正所谓非存在的存在。

男人挥动从右肩伸出的影之手臂握着的暗之剑，发出了奇怪的震动声。

我稍微拉开距离，将背后的双剑同时拔出。左手握着青蔷薇之剑，右手则是握着夜空之剑。

如果说是暗色的话，切削基加斯西达的树枝作出的夜空之剑绝不在那把剑之下。然而，与夜
空之剑如同黑曜石般反射着阳光相反，男人的剑简直就像要将空间分离出去一般。绝对不是
资源吸收属性这样的等级。恐怕……

「——上了，加百列！！」

我勇猛地喊出敌人的名字，拍动变形成双翼的大衣下摆。

飞向高空的同时，将双剑在身体前方交叉。

「Generate All Element！」

【生成全部元素】

将全身的体表想象成末端，并同时将全部属性的元素各自生成数十个，我在急速降下的同时
将它们一口气发射出去。

「Discharge！！」

元素化为炎之剑、冰之枪、以及有着其他色彩的几种光线在空中疾驰。

如同要追上术式一般，我挥动手上的双剑。

加百列·米勒没有做出任何回避行动。

他仍然露出淡淡的微笑，只是轻轻张开双手。

八色光芒向着被蓝色的黑暗缠绕的身体突刺。

我没有放过他上半身稍微摇晃了一下的空隙，将右手的剑挥下，左手的剑贯穿过去。黑暗砰
的一声飞散，在交错而过的我的体表留下寒气。

就这样继续全力飞翔，在上升的同时回头的我看到的——

是将流出的暗一点点收回，像是什么事情都没发生过一般回头看向这里的加百列的身影。在
包裹着他的身体的黑夹克上，没有留下一个伤口。

果然。

那个男人的属性，是对斩击、突刺、火焰、冻结、旋风、岩弹、钢箭、晶刃、光线、暗咒的
吸收【Drain】。

在交错的那一瞬间，被虚无之刃划过的我的右肩，大衣和肌肉如同被撕裂一般消失，鲜血噗
的一声飞散开来。

** 71

加百列·米勒确认到了正在漫长的空中阶梯上奔跑着的《爱丽丝》和另一位少女的身影。根
据他的估算，二人距离到达系统终端还需要五六分钟的时间。

因此，已经没有让自己缠身于和突然出现的碍事者间的战斗的余地了。虽然将其立刻无力化
后赶往浮岛是合理的判断，但他却因对新出现的敌人起了些微兴趣，而停在了空中。

敌人一眼看过去不过是个小孩子而已。

相比先前战斗过并同归于尽的老年骑士，他的威慑感可以说几乎没有。虽然他大概是和《诗
浓》一样协助K组织的，来自现实世界的VRMMO玩家，但在给人造成的压力上还不如那个少女。

要说原因的话，眼前这个黑衣的年轻人，几乎没有散发出任何斗气。

只在询问他是什么人的时候，吸出了相当少量的意识，然而这个通路很快就被切断了。此后，
他就像被透明的壳包围了一般不断弹开加百列的思考搜索。和无法体会到心的敌人战斗，实
在太过无趣。

加百列也考虑过立即将他从状态数值的层面上杀死并排除，然后继续追赶爱丽丝。

然而在看到年轻人将大衣下摆变成了蝙蝠翼的形状，而且还同时操纵所有属性的魔法后，他
的想法稍微改变了。加百列感觉到，他已经适应了这个世界。

在确保爱丽丝到手，带着STL技术逃到第三国后，还有着只在自己世界的一角构筑自己爱好
的工作。为了提高这个工作的效率，将年轻人的操作技术夺过来倒也不坏。

为此，就需要破坏那个想象力之壳。

加百列带着淡淡的笑容向黑衣少年说道：

「三分钟。让我好好享受一下吧。」

「……还真是够大方的呢。」

我用指尖轻抚了一下塞住伤口，低声说道。

然而，加百列如此游刃有余也有着相当多的原因。不管怎么说，他可以无伤应对所有属性的
攻击。

——不对，只对唯一一种伤害不适用。将那家伙的右臂从肩部打飞的，恐怕是先行出发的诗
浓吧。她通过想象力做出了狙击步枪，击中了那家伙。也就是说，加百列无法吸收《枪击》
属性的攻击。

理由恐怕和那个男人穿着时髦的军服姿态有关。因为他基于身为士兵的经验所知的大口径枪
支的威力，所以在自己被击中时无法将损伤无效化吧。

然而，诗浓能在Under World内具现出枪支的这一特技，是因为她将爱枪Hecate II当作了自
己身体的一部分才能做到的。我无论如何也做不到这点，就算做出一把手枪，也不会有与其
相应的威力。

因此我需要找到，能让那个奇怪的男人认为会对自己造成损伤的攻击类型。

也就是，要了解这个名为加百列的人。必须看破他过着什么样的生活，期望着什么，又为何
会在这里。

架起手上的双剑，我的嘴边露出了笑容：

「也好，就让我享受下好了。」

那个态度的来源到底是什么。

虽然可以确定那个人在长时间潜入Under World后已经适应了这个系统，但他也不过是个小
孩子游戏玩家而已。明明他知道两手夸张地握着的剑也好，华丽的魔法攻击也好都会被无力
化，为什么还能露出那么厚颜无耻的笑容。

加百列带着淡淡的不快感思考后，得出了他只是为了拖延时间而虚张声势的结论。

就算在这个世界死掉，现实世界的肉体也不会受到任何伤害。那么，他大概是只想要在另一
位同伴确保爱丽丝的安全前尽量延长战斗时间。

到头来不过是个愚蠢的小孩。跟他战斗用三分钟时间都太长了。

用临时作出的右臂晃着手中握着的虚无之刃——加百列将它毫不掩饰地刺入了自己乘坐的有
翼生物的后背。

原本这个怪物是和剑及十字弓一样的，将原本名为《沙多拉撒》的帐号所有的飞行用背包转
换到Under World时的产物。虽然可以通过自己的意识控制，但只用双脚站在上面还是缺乏
安定感。和那个少年一样，将其变为自己的翼才更为合理。

身体被贯穿的怪物，发出了短短的悲鸣，一点点被吸入了虚无。加百列将通过剑流入右臂的
数据转到后背，开始集中意识。

啪嚓。

与翅膀张开的声音一起，和少年一样的黑翼从肩胛骨上伸出。然而，黑翼并非如同蝙蝠一样
的皮膜型，而是生有尖锐羽毛的猛禽之翼，可以说和持有天使之名的自己更为相称。

「……这样就拿到一个了呢。」

将虚无之刃笔直指向年轻人的加百列低声说道。

原本打算将下一次攻击指向被敌人乘坐着的圆盘形飞行生物的我，因被抢了先手而一瞬间判
断力降低了。

加百列没有放过这个机会，展开黑色的猛禽之翼，滑过了我们之间的这段距离。

毫无动作便突入进来的刀刃速度相当惊人。哪怕他对剑技相关的知识毫无了解，这速度也相
当可怕。我如同抢救般将交叉成十字的双剑从下方挥上挡住。

嘎咻！

随着一声异样的声响，蓝黑色的暗之剑停在了我的鼻尖。

青蔷薇之剑和夜空之剑与其激烈地拉锯着。只是没有被虚无吞没而已的情况，不如说是在交
锋中出现了一个封闭空间。不难想象，这对剑的天命会增加巨大的负担。

然而，不通过后退来回避，而是冒着危险挡住他的攻击也是作战的一部分。我利用将从下面
挥上的剑被再次斩下的势头，尽量将身体后转。

「哈！！」

随着一声大喊，我对着加百列的下巴使出一记飞踢。

拖着橙色光芒伸出的脚尖，捕捉到了他尖锐的下颚。随着黑暗「嘣」的一声飞散，敌人向后
仰去。

——怎么样！？

双翼拍动着空气拉开距离的我确认着敌人的情况。如果枪击不行的话，就用《打击》——如
果那家伙真的是特种部队的士兵的话，应该受过格斗术的训练，将打击认知为会造成损害的
攻击的可能性也是存在的。

然而，咔地一声转回头的加百列，身体的表面却毫发无损。

从下颚处飞散的黑暗，立刻凝集回原处变成了光滑的皮肤。用左手抚摸着那里的敌人露出了
轻蔑的笑容：

「原来如此。很遗憾，那只不过是用来在电视上作秀的技巧而已。真正的体术……」

砰！！

加百列说到一半，拍动空气，以如同要让身体模糊起来的速度突破。我反射性地用青蔷薇之
剑弹开从左上方挥下的剑，同时用右手的剑反击。虽然砍进了敌人的肩膀，却感到了如同被
高浓度的粘液包围的手感，连动都动不了。

伸直的右臂被紧紧缠住。是加百列的左臂。他如同黑蛇一般卷住我的右臂，将它慢慢向反向
扭转——

咔。

随着这令人不快的响声，我的脑海中传来如同银色的电流一般的剧痛。

「呜啊……」

加百列在近距离窥视呻吟着的我的眼睛，低声说道：

「……就是这么一回事。」

紧接着，他开始发动猛烈的连续攻击。

虚无之剑以近乎无限连发的连续技进行超高速打击，虽然用右手的剑不断将攻击弹开，但偶
尔会突破防御的一击，还是浅浅地打中了身体。已经根本没有为了回复被折脱臼的左臂而集
中精神的闲暇了。[fn:19]

「咕……哦……」

虽然不禁漏出呻吟，我还是为了拉开距离而拼命拍动双翼。

全力后撤后，用右手的两根手指在拼命握着剑的左臂上滑动。

白光开始聚集的时候。

加百列一下子抬起左手，将五指如同钩爪般弯曲，然后一口气张开。

十余根漆黑的线如放射状伸出，在途中折了个锐角笔直地向我袭来。[fn:20]

我咬紧牙关展开想象力的防御壁。虽然在弹开袭向爱丽丝的飞龙们的同样技能时有着强烈的
确信，但现在的精神却有一半被用于治愈了——这样的认识，使得盾的强度下降——

啪。

身体的数个部位发生了震动。

贯穿了防御壁的三根暗之光线，穿透了身体和双脚。在感觉到疼痛之前，有剧烈的冷气传入
身体。仔细看去，蓝黑色的虚无纠缠着被击中的部位，正吞噬着我的存在。

「咕……！！」

我再次发出呻吟，深吸一口气，大声喊了出来。这才将虚无剥去，从新的伤口出流出了大量
鲜血。

「哈哈哈。」

我听到清脆的声音而抬起头，加百列·米勒如同虚无之刃一般，扭曲着的表情上露出了笑容。

「哈哈哈，哈哈哈哈哈。」

不对，他没在笑。虽然嘴唇扬起，但眼睛却一动不动，在如同玻璃一般的蓝眼睛里涌起了饥
渴的漩涡。

加百列将双臂慢慢交叉在身前，做出如同要让力量集中的动作。

让人不寒而栗的黑暗，如同火焰一般剧烈摇晃，厚度不断增加。

「哈——！！」

他大声喊叫着，将双臂向左右打开。

嘶。新出现的两枚翅膀，从已经存在了的双翼上方伸展开来。然后下面又是一对。

加百列从上向下拍动总计六枚的巨大翅膀徐徐上升。被抚平的金发如同波浪一般伸展，头上
出现了漆黑的光环。

两眼不知何时也已不是人类的眼睛了。只有蓝色的光充满眼窝。

简直就是——死亡天使。

狩猎并夺取人类灵魂的先知。面对有着如此自我印象的人，到底怎样的攻击才会奏效。

我从如同恐怖的具现化一般的这个身影上移开视线，确认拉着手在空中阶梯上奔跑的亚丝娜
和爱丽丝的身影。她们才跑到了一半。到达终端还需要两分钟，不，还需要三分钟。

我已经无法确信，自己能够拖过这短短的时间了。

这是何等的全能感。

在遍布全身的如此强大的力量下，加百列第三次哄笑出来。

原来如此，这就是这个世界里存在着的想象力的精髓——《心意》吗。

终于明白将自己变为龙卷巨人的暗黑将军的力量，和斩断时间的敌方骑士的力量的秘密了。
加百列一直以为他们的技能都存储于未知系统命令之中，但并不是这样。只需要能确信自己
有着强大的力量就可以了。所有的都藏在那个小孩在眼前这样那样的演示的阴影之中。

在感谢的意义上，就给你一分钟吧。

加百列大大张开六枚翅膀，将暗之剑挥向高空。

在一分钟的时间里，将这个小鬼的一切存在切断，抽出他的灵魂并加以吞噬。为了将这更强
大的力量变为自己的东西。

加百列带着蓝紫色的闪电，进入了突击态势。

我只是抬头看着已经无法称为军人的敌人的身影。

已经没法将那个男人——那个存在认知为恐惧和威胁了。而且如同要证明枪击已经无效一般，
应该已被打断的右臂，不知何时也已经完全再生了。

毕竟，我的觉悟还不够。

并不是低估了加百列·米勒这个人。那异样的气息足以让人进入最大警戒状态。但正是如此，
我说不准在这战斗开始之前，或许已经放弃了胜利的想法。如果拖延时间——也就是在爱丽
丝和亚丝娜脱离之前延长战斗的话，我和敌人都会被囚禁在两百年的时间之牢中，无法再次
回到现实世界。

啊……这样啊。

难道说我是在期待着它吗？

超越了艾因葛朗特的，真正的异世界。茅场晶彦期望的，他所要创造出的理想之国。Under
World实在和它太相称了。

我在过去被囚禁在SAO内的两年间，经常会为自己到底是否真的想要离开而迷惑着。能够在
这迷惑中作为攻略组的一员在前线不断战斗，是因为我认识到在那个世界里的生活也是存在
着严厉的时间限制。因为躺在医院的床上的，通过注射而延续着生命的肉体不知何时就会突
破衰弱的极限。

然而，有着时间加速的Under World并非如此。特别是在倍率变为五百万倍的情况下，没有
必要去考虑现实中肉体的事情。我直到灵魂的寿命耗尽为止，都会一直留在这个异世界。虽
然是无意识中的想法，但我真的能断言自己没有这么想过吗？

结果——

我没有想过我最重要的人们，到底会悲伤到什么样的地步。

直叶、妈妈、爸爸、小唯、克莱因、艾基尔、莉兹、西莉卡……还有那众多拯救了我的人。

还有爱丽丝。

亚丝娜。

他们会怎样叹息，怎样痛苦，怎样流泪，都没有……想过……

到头来，我仍然是个无法理解人心的人。

从初中时抛弃了第一个朋友，在假想世界里杀死了他的时候开始，一点都没有改变……

——不是这样的，桐人。

怀念的声音。

冰冷的左手，传来微弱的温暖。

——你不想离开这个世界，并不是为了你自己。而是因为你爱着在这个世界认识的那些人们。

——西露卡、缇卓、萝涅、露莉德村的村民们、在央都和学院里认识的人们、整合骑士和卫
士们……Cardinal女士、说不准还有Administrator……而且，大概还包括了我。

——你的爱，如此宏大，如此宽广，如此深远，足以背负整个世界。

——然而，那个敌人却不一样。

——那个男人，不知道人心，也无法理解人心。所以他才在探求，才会去夺取，才会去破坏。
也就是说……

他在害怕。

加百列·米勒看到黑衣少年的脸颊上流下细细的泪水。他握着剑的双手，如同惧怕一般缩在
胸前。

是恐怖吗。

濒死者的恐怖正是对加百列而言最甜美的调味剂。至今为止加百列都曾用舌头品味着在他手
上死去的无数人的泪水并因此而陶醉。

感觉到了从体内涌上的巨大的饥渴，加百列的舌尖舔着嘴唇，挥动左手的指尖。

渐渐出现的无数黑球，如同蝇群一般嗡嗡叫着。

加百列将指尖指向那个小鬼的同时，黑球全部变为极细的激光，在空中奔驰。

咚。咚咚。

传来确切手感的同时，激光穿透了少年瘦弱的身体。黑暗夹杂着鲜血迸发出来。

「哈哈哈哈哈！！」

哄笑着一口气接近到零距离的加百列，将虚无之剑向后拉去——

一口气贯穿了少年的腹部。

在这时间如同被压缩了一般的刹那。

黑衫和大衣覆盖着的身体，被暴走的虚无撕裂，一下子分断开来。

血肉、骨骼、脏器一起飞散。

加百列将左手刺向如同红玉一般美丽的光辉。

抓住了悬在少年上半身上的，还在跳动着的最大的宝石——心脏，将它扯了下来。

加百列将掌中似乎想要抵抗着咚咚跳动的肉块慢慢放到嘴边，向带着空虚的表情漂浮在空中
的濒死的少年低声说道：

「你的感情、记忆、心灵和灵魂的一切……我现在可要吞噬掉了。」

我只是从半闭着的眼皮下注视着说出这句话的死亡天使的身姿。

加百列将红唇大大张开，如同咀嚼成熟的苹果一般，对着从我这里夺走的心脏露出了纯白的
牙齿。

……嚓。

响起了如同恐惧心在摇晃着一般的巨大声响。

白皙的脸庞扭曲起来，从嘴里流出了大量的鲜血——那无疑不是我的鲜血。

这是理所当然的。

因为他被我在自己的心脏里用钢素生成的无数利刃刺到了。

「咕……」

我对呻吟着按着嘴后退的加百列用沙哑的声音说道：

「心也好，记忆也好，怎么可能……在哪里啊。身体什么的……不过是容器罢了。回忆……
永远都在……」

在这里。

和名为《我》的意识融合，化为一体，永远不会分开。

身体被撕裂的痛楚已经剧烈到无法用痛楚形容的地步了。然而这一瞬间，是最大也是最后的
机会。如果放过的话，就再也没有下一次了。

优吉欧哪怕身体被打断了，也还在战斗。

我将双手中的剑张开——飞溅着鲜血喊道：

「Release Recollection!!!」

蓝白与纯黑色的光芒同时炸裂。

从指向前面的青蔷薇之剑上，流出数株冰之藤蔓，将加百列的身体捆住了两三层。

然后，从笔直指着的夜空之剑上——

巨大的黑暗之柱划向长空。

伴随着轰鸣声向上延伸的漆黑，贯穿深红色的天空到达高处——然后如同与太阳激烈地冲撞
了一般，向四面八方延伸。

天空被覆盖了。

血色以惊人的速度被抹去，正午的阳光消失了。

黑暗在数秒内到达了地平线，然后继续向远处延伸。

不，这不是虚无的黑暗。而是有着光滑的质感和些微温度的——

无限的夜空。[fn:21]

** 72

诗浓一个人躺在在无人的荒野上林立的乱石堆的底部，等待着天命全损的那一刻。

被打断的双腿的伤口的疼痛，让意识有一半以上都模糊起来。虽然右手如同握着生命线般紧
握着留在胸口的项链被打断的那一端，但也已经慢慢使不上力了。

逐渐模糊不清的思考，已经无法分辨是注销的预告还是真正的失神的那一刻。

天空的颜色变了。

明明是中午却被怪异的血色铺满的天空，被从南侧袭来的黑暗以惊人的速度覆盖。太阳光也
被折断，灰色的云彩涂抹天空——之后，黑暗彻底包围了诗浓。

不对。不是彻底的黑暗。

从各处流下的淡淡磷光，将头顶的石山，枯萎的树木和脖子上的锁链映成一片蓝色。吹来的
温暖微风摇晃着她的刘海。

夜晚。将这广阔的世界，温柔而平稳地包裹、治愈的夜晚。

诗浓突然想起了过去的情景。

在和这里不一样的异世界的沙漠中的一夜。诗浓将被每日被幼年时遭遇的事件的记忆折磨的
痛苦吐出，敲打着他，哭着呼唤他的事情。那时轻轻抱住她的后背，将之承受的手臂的坚强
和温暖，正充满了头顶的夜空。

这样啊……这个夜晚，就是桐人的心啊。

那个人绝对不是眩目的太阳。他从没有站在人们的前方，发出灿烂的光辉。

但在痛苦和难受的时候，他无论何时都会在背后支撑着自己。治愈自己的悲伤，擦干自己的
泪水。就像那发出微弱但确定无疑地存在的光辉的星星一般。就像这夜晚一般。

那么，拜托了——将我的心，传达过去。

诗浓湿润的眼睛拼命仰望着夜空，祈祷着。

在她头顶的正上方，一颗淡蓝色的星星闪耀着。

莉法躺在无数Oak和拳斗士们围成的空地上，等待着最后的时刻。

连为了使用泰拉利亚的回复能力而踏出右脚的力量都没有了。被劈砍和贯穿的全身如同被冰
冻一般寒冷，指尖根本无法动弹。

「莉法……不要死啊！绝对不要死掉啊！！」

跪在旁边的Oak族长利尔皮林，如同吼叫着一般喊道。莉法带着淡淡的微笑仰望从他的小眼
睛里流出的透明的泪水，低声说道：

「不要……哭啊。我，一定会……再回来的。」

莉法看着听到这句话的利尔皮林缩起身体颤动着肩膀的样子想着。

——虽然没能直接帮到哥哥，但是这样就已经很好了。我已经很好地完成了任务了。对
吧……？

就在这一瞬间，如同回应了莉法的心声一般——

天空一下子褪去了颜色。

正午的天空突然变成黑夜，让Oak和拳斗士的人群中出现了惊讶的声音。利尔皮林抬起已经
湿润的脸，睁开双眼看向天空。

但是，莉法既不惊讶，也不害怕。如同要追随黑暗一般从南方吹来的，温柔地拂过脸庞的夜
风，让她感觉到了哥哥的味道。

「哥哥……」

她低语着，深吸了一口气。

桐人对莉法而言，可以说是最近也是最远的存在。

哥哥大概在自己发现真相前，就在无意识中察觉到如今的父母并不是自己真正的双亲了吧。
在莉法刚刚懂事的时候，桐人就已经被孤独和隔绝的色彩重重包围了。他绝不和任何人结下
深刻的羁绊，从产生了些许友情时起就不断将自己毁坏。

虽然正是因这个性格让他沉溺于网络游戏，也正是这份沉迷将他导向了『将SAO攻略的勇者』
的结果，但莉法并不将这当成偶然的讽刺，也没有当成预定中的救赎。

那是各个自己选择的道路。选择了这条道路，拼命地背负着什么。这才是名为桐人的他的强
大之处。

头上的夜空一定是桐人将这个世界和世上所有人都背负起来的决心的证明。因为——

……哥哥比我还更像一个剑士。

莉法用最后的力量动起已经失去知觉的双臂，如同握住竹刀一样将双手紧紧握在胸前。

然后，她祈祷着。

将我的心的力量，传达到哥哥的剑上吧。

头上的远处，一颗绿色的星星正发出强光。

莉兹贝特紧握着西莉卡的手，无言地仰望太阳已经消失的天空。

天空被黑夜覆盖的这不可思议的景象，让她想起了那一天发生的事情。

那是SAO开始运营后两年的，初冬某一天的下午。

跑出店铺的莉兹贝特，看到了将上层的底部铺满的系统信息上显示着的，死亡游戏终于被攻
略的通告。那一瞬间，她想，一定是桐人做到了。桐人挥舞着我锻造的剑，打倒了最终Boss。

在回到现实世界后，桐人对莉兹贝特说了这样的话。

——我那时其实已经输了。被希斯克利夫的剑贯穿的我，HP确实变成了零。然而，不知道为
什么，我没有立刻消失。在仅剩的几秒钟内我动起右手，刺穿了希斯克利夫。我想赐予我那
短暂时间的，是包括莉兹、亚丝娜、和克莱因在内的大家吧。所以，在真正的意义上，攻略
的SAO的勇者并不是我。包括莉兹在内的大家都是勇者。

那时，虽然自己笑着说这是什么谦虚话，还敲了敲他的后背，但那大概是桐人的真心话吧。
他曾经这么说过，真正强大的力量，就在人们的心与心的连接之中。

「……呐，西莉卡。」

莉兹贝特将视线从夜空移开，看向旁边的友人。

「我……果然，还是喜欢桐人啊。」

西莉卡也微笑着回答：

「我也是呢。」

然后二人一起回头看向闪着微弱的磷光的黑夜。

闭上眼睛之前，她看到了在稍远处高高举起拳头的克莱因，和双手叉腰低声说着什么的艾基
尔的背影。

莉兹贝特听到了，和他们一样，以各自的方式祈祷着、许愿着的数百名玩家的低语。

——虽然我们只是通过AmuSphere连接到这个世界……但是，一定会传达给桐人的。因为我
们的心连在一起。

在他们头顶，同时出现的数百个星星一下子遍布夜空。

整合骑士雷恩利左手抚摸着骑龙·风缝的头，右手握着少女练士缇卓的左手，连呼吸都忘记，
就这样注视着突如其来的黑暗。

白天变成黑夜，这是教会留下的任何史书上都没有记载过的恐怖现象。然而，雷恩利已不再
害怕了。

在身体被两柄长枪贯穿，正要走向不可避免的死亡时，从空中降下的光之雨将致命伤毫无痕
迹地治愈了。如今的这个夜晚，有着和那场雨几乎一样的温暖。

雷恩利既对自己活到了最后感到不可思议，也无法原谅这个事实。他坚定地认为，像骑士艾
尔德利耶一样在战斗中英雄般地死去，才是报答已经连名字都想不起来的旧友的唯一一条道
路。

然而，雷恩利在那光之雨中感受到了。

连从轮椅上站起来都做不到的黑衣剑士。他也失去了唯一的朋友。之后，他以这死亡责备并
折磨着自己，封闭了自己的心。

明明这样，那个人还是站起来了。然后，操纵着和雷恩利的神器·比翼一样的身为自己和朋
友分身的双剑，发挥出惊人的力量歼灭了数万敌军。他的背影让雷恩利明白了。

活下去。将生存、战斗、生命和心灵连接的东西。那是——只有那才是……

「那才是，强大的证明。」

雷恩利自言自语着，向握着缇卓的手中轻轻注入力量。

用另一只手牵着黑发朋友的手的红发少女，抬头注视着雷恩利。她眼中闪着的红叶色光芒缓
和下来，小心翼翼地点了点头。

三人再次笔直仰望漆黑的夜空，以各自的方式祈祷着。

在瞬间出现的数百个星星中，变为三个闪着强光的星座。

拳斗士团长伊修凯恩，在稍远处注视着被跪在地上的Oak们包围的如今正逐渐走向死亡的绿
发少女，心中有着说不出的感慨。

那个少女的战斗方式，连鬼神都望之莫及。看到她的样子，伊修凯恩觉得自己似乎终于可以
明白为何Oak们会背叛皇帝的命令前来救援拳斗士团的理由了。也就是说，Oak族人相信那个
少女比皇帝还要强大。

然而他弄错了。

Oak族长利尔皮林告诉他，一万名Oak族人服从她——不，是恭顺她的理由只有一个：她说他
们也一样是人类。带着骄傲向伊修凯恩说出这句话的利尔皮林的单眼中，那过去如同漩涡般
的憎恨之色已经如同谎言一般消失了。

「喂，女人……不对，是谢塔。」

伊修凯恩呼唤着站在旁边的灰衣女骑士的名字。

「力量……或是强大，到底是怎样的东西呢……？」

已经成了无刀之骑士的谢塔，摇了摇扎成一束的长发歪起了头。她那冷淡的眼睛，先是看向
站在背后的飞龙，又看向双肩缠着绷带的巨汉，然后才回到伊修凯恩身上。她轻轻开口说道：

「你应该已经明白了吧。比愤怒和憎恶还要强大的力量。」

这个瞬间——

已经看惯的Dark Territory的血色天空，沉入了黑暗之中。

在屏住呼吸向上看去的伊修凯恩正面，只有一个绿色星星闪烁着光芒。

谢塔伸出手指向星星说道：

「就是那个。真正的力量，真正的光芒。」

「……对……对，是这样啊。」

伊修凯恩自言自语着。星星闪耀着的绿光，渗入了他从左眼流出的泪水。

拳斗士长将遍布伤口的拳头，第一次不是为了殴打他人而握紧，为了胜利以外的什么祈祷着。

在离绿色星星稍远一点的地方，红色的星星如同火焰一般燃气。旁边，灰色的光如同紧靠着
一般浮现出来。

紧接着，随着活下来的拳斗士们低声唱和着战歌的声音响起，数百颗星辰遍布天空。

一万名Oak军人和他们一样仰望夜空祈祷着。

在他们背后站着的暗黑骑士们也在祈祷。他们中的一部分，和Oak军一样从谜之军队手中守
护了拳斗士团。

星星的数量逐渐增多，超过了一千，超过了一万。

留在东之大门的人界守卫军、整合骑士法娜提欧、迪索鲁巴特还有几名下位骑士，也都无言
地注视着夜空。

虽然在他们心中游走的思绪各自不同，但祈祷和许愿的想法却是一样的。

法娜提欧为已然离世的整合骑士长贝尔库利所爱着的这个世界，为还在体内孕育的新生命即
将从此度过的世界祈祷着。

迪索鲁巴特用右手轻轻包住左手手指上闪着光辉的小戒指，为和过去曾戴上同样戒指的什么
人一起活在的这个世界祈祷着。

其他的骑士和卫士们，为他们所爱的世界能够回到和平而祈祷着。

遥远北方的山区中，山地哥布林族人们在祈祷。

荒野中，平地哥布林族人们在祈祷。

东方的湿地中，等待丈夫和父亲归来的Oak族人们在祈祷。

西方的高台上，巨人族们在祈祷。

无主的帝城奥布西蒂亚的街区内，有着浅黑色皮肤的人们，和东南部草原地带的Orge们都闭
上眼睛祈祷着。

夜空的前端，越过了终结山脉，一瞬间到达了人界。

在遥远的北方，露莉德村的教会里，正汲取用于洗澡的井水的见习修女西露卡，被从东南角
方向来的黑暗覆盖清澈的蓝天的景象夺走了视线，呆立在那里。绳子从手中滑落，落到水面
的桶激起轻轻的水声，但她并没有听见。

她的嘴边漏出颤抖着的低语：

「……姐姐…………桐人……」

现在，就在这个瞬间——

西露卡通过夜风感觉到，自己比任何人都爱着的二人，正拼命地战斗着。

也就是说，桐人再次醒来了。从失去了优吉欧的悲伤之崖的边缘，再一次站起来了。

西露卡跪在矮草坪上，将双手握在胸前。她闭上眼睛低声说道：

「优吉欧，拜托了……请保护姐姐和桐人吧。」

她随着祈祷而再次抬头看去的夜空中，有一个蓝色的星星闪耀着。

在蓝色星星的周围，出现了各种颜色的星星。一眼看去，之前还在院子里游玩的孩子们，也
无言地跪在地上，紧握着他们的双手。

在教会前的广场上，商人和主妇们在祈祷。

在牧场和麦田中，劳作着的男人们在祈祷。

在村长办公室里，爱丽丝的父亲加斯胡特在祈祷。

在森林的边缘，加里塔老人在祈祷。

没有一个人因这景象而恐惧或慌张。

露莉德村上空，在数秒内被无数的星星覆盖。

同样，在位于南方的扎卡利亚镇的上空，也遍布无数的星辰。

在四帝国各地点缀着的村庄或城镇中，居民们也一样无言地祈祷着。

在位于人界中央的巨大都市圣托利亚，市民们和修剑学院的学生们也在祈祷。

连隶属神圣教会的修道士和祭司们都不例外。

负责操纵大教堂第50层到第80层的升降板的的少女，做出了在漫长的人生中第一次做的事情。
在工作中的她将手从玻璃制的风素生成筒上放开，仰望天窗另一端无限的星空，握住了双手。

她并不了解大教堂之外的世界。最高祭司的死亡也好，暗黑界军队的侵略也好，对少女的人
生从未造成过任何变化。

因此少女只为一件事情而祈祷。

祈祷着能和那两位年轻的剑士再一次见面。

在包围了广阔的Under World全部领土的正午的夜空中，闪着各种颜色光芒的星辰超过了十
万。

这些星辰，从终结之边境起，一个个奏响如同铃音一般的声音向着一个位置流动。

向着世界的最南端。

向着距离名为World End Alter的浮岛近处，笔直指向天空的一把长剑。

** 73

正在好不容易可以看到天边的阶梯上全速奔驰的爱丽丝，发现脚边映在大理石板上的影子，
被更巨大的影子覆盖了。

她吸了口气向后看去，飞入她的视野的，是令人难以想象的景象。

挥舞着虚无之剑的，有着六枚黑翼的敌人。

将那身体重重缠绕，封住动作的冰之藤蔓。

而握着冰藤的来源——闪着蓝白色光辉的长剑的，是有着飞龙之翼的黑衣剑士。

剑士的身体从胸部往下的部分都已经不在了。在瞬时间就会天命全损的状态下，还能继续战
斗的心意之力让人震惊。

然而，真正的奇迹却并非仅此而已。

从向空中高高扬起的剑士的右手握着的漆黑长剑迸发出巨大的暗之奔流，屹立着，覆盖了天
空和广阔的世界。

不，那并不是毫无光明的黑暗。

在遥远的北方闪烁的无限的色彩、无数的光点——那是星星。发出静谧的光辉的星群，让夜
空染上了色彩。

随后——

星星开始移动。

奏出如同银铃又如竖琴版清澈的重奏，笔直地向这里集中。拖着白色、蓝色、红色、绿色、
黄色的长长细线，在夜空中描绘出巨大的彩虹。

爱丽丝感觉到了，那所有的星星，显现出了全世界所有人的心意之力。

人界人。

暗黑界人。

人类。

亚人。

如今，整个世界在祈祷中化为一体。

「……桐人…………！！！」

爱丽丝呼唤着他的名字，高高举起左手。

把我的心也传过去吧。哪怕是这人造的骑士的，仅仅经过了短暂年月的伪造的心，但这份感
情——在这心中洋溢着的感动，一定是真实的。

从左手出发的，闪着令人目眩的光辉的黄金之星，向着桐人的剑直线飞了过去。

亚丝娜没有回头。

她知道，唯一能做到的能够回应桐人的奋斗的事情，就是哪怕连一分一秒都不浪费，向着系
统控制台前进。

所以亚丝娜只是拉着爱丽丝的手，用从心灵到身体的全部力量拼命奔跑着。

然而，充满胸中的这份炽热的感情，却怎样都止不住。

感情化为两滴泪珠，划过睫毛，漂浮在空中。

随着夜风飞舞的两滴泪珠融为一体，变成了闪着七色光辉的星辰。

亚丝娜一瞬间抬头看着在黑暗中拖着极光的痕迹笔直飞上天空的星星，毫不回头地奔跑着。
她相信桐人可以做到。

加百列·米勒没能理解为何自己会被拘束的如同寒冰一般。

难道刚才不是将所有属性的术式攻击和斩击都完全无效化了吗。

确实，嘴被埋伏在心脏里的暂时形成的利刃伤到了。但这也只是口腔将咀嚼的动作实体化了
而已。如今他的全身已经被虚无的想象重重包围了。

我乃收割之人。我乃夺去一切光、一切热、一切存在之人。

我乃深渊。

「NU……LLLLLLLL!」

加百列的喉咙中，迸发出已经无法形容为人声的异质咆哮。

从后背伸出的三对黑翼，全部变为和右手的剑一样的虚无之刃。

虚无之刃发出剧烈的冲击声，将周围的空间全部割裂。终于将蓝白色的藤蔓切开，让身体恢
复了自由。

「LLLLLLLLLLLLL!!」

加百列伴随着咆哮将七把虚无之刃伸展开来。

空着的左手笔直指向前方，为从这一边将那个小鬼绑住而打算放出暗之线的时候——

加百列这才注意到，空中的红光已然消失。

以及从头顶一个个降下的，无数的流星。

在解放夜空之剑的时候，我并没有想象出任何具体的事物。

然而，从剑中迸发出的黑暗将白昼变为了黑夜，如同其名字一般，创造了夜空。

在夜空中突然流过的无数星辰化为虹色光柱流入剑身的时候，我察觉到了发生的事情。

夜空之剑的力量，是从广泛空间内吸收空间资源的能力。

而在这个世界上，最强大的空间资源，绝对不是太阳和大地在系统上供给的空间神圣力。是
人们心灵的力量。是祈祷、许愿、希望的力量。

降下的近乎无限的星光的最后一枚，终于也被吸入了剑身。

然后，仅有两颗的从地面飞舞而上的，金色和虹色的星星与剑刃融为一体的这个瞬间——

整把剑发出了不可思议的纯白强光。

强光从剑柄流入我的手臂，充满了身体。之前已然破碎的下半身，也伴随着白色的强光在一
瞬间再生了。

在被星光包围的左臂前端握着的青蔷薇之剑也发出令人眩目的光——

「哦……哦哦哦哦哦哦！！」

我将两把剑打开，喊出了声音。

「LLLLLLLLLLLLLLL!!」

在我面前，打破了青蔷薇的束缚的加百列·米勒也一样发出了奇怪的咆哮。

加百列的身形，已经不能称作是人类了。如同漆黑的流体金属般闪着不自然的光辉的裸体被
蓝黑色的光晕覆盖，从眼窝里放出的紫蓝色的光简直就像从地狱中发出的一般。

他将右手握着的，狭长的虚无之刃挥向高空，将变为同样刀刃的六枚翅膀全方位张开。

紧接着，从笔直地指向我的左手中出现了无数稠密的冰冷细线，向我飞了过来。

「……哦哦！！」

我大喊一声放出光之壁，将它们全部弹回。

接着，用力将从背后伸出的闪着光辉的翅膀张开。

架好左右两把剑后，一下子踢向天空。

敌我的距离仅差毫厘，突击的时间不过一瞬。然而，围绕着我的加速感，让我感觉这段时间
已经近乎永恒。

我的右边，出现了什么人的身影。

蓄着黑色的美髯，带着巨大长刀的不认识的壮年剑士。抱着浅黑肌肤的女剑士的男人，看着
我说道：

『年轻人啊，舍去杀意吧。那人的虚无之魂，以杀之心意的话是无法斩落的。』

之后，左边出现了威严的老年男人。全身纯白，佩戴着钢色的长剑。骑士长贝尔库利那魁伟
的容貌上露出了笑容。

『少年，无需恐惧。你的剑上，承载着世界的重量。』

在贝尔库利的身边，出现了肤色纯白，披着长长的银发的少女。

最高祭司Administrator，带着谜一样的银色眼瞳向我微笑着说道：

『就让我看一下吧，从我这里继承的，你全部的神威之力。』

最后，如同要抱住我一般，带着学者帽，穿着斗篷的年幼的女孩子出现了。披着茶色卷发，
肩上有一只小小的蜘蛛的，是另一位最高祭司Cardinal。

『桐人啊，去相信吧。汝所爱的，爱着汝的，无数人的心灵。』

小小的眼镜里，深褐色的眼睛温柔的眨了一下。

之后，他们的身影就消失了——。

与最后的敌人，加百列·米勒接近到最近距离。

我将全身的力量充满双臂，放出过去修炼最久，也是最为信赖的二刀流剑技。

《Star-burst Stream》。十六回连续攻击。

「呜……噢噢噢噢噢噢噢！！」

充满星光的剑，以照耀宇宙的轨迹击出。

同时，加百列的六枚翅膀和虚无之刃，从全方位向我袭来。

光和虚无发生激烈碰撞，巨大的闪光和爆炸震荡世界。

快一点。

再快一点。

「噢噢噢噢——！！」

我发出咆哮，将与意识一体化的肉体不断加速，挥舞着双剑。

「NULLLLLLLLLLLLLLL!!」

加百列发出吼叫的同时以虚无之刃还击。

十。

十一。

互相攻击放出的能量灼烧着周围的空间，化作轰鸣的闪电。

十二、

十三。

我的心中，已经再无愤怒、憎恶与杀意。只有充满全身的无数的星辰——祈祷之力驱动着我
和剑。

——去承受、

十四。

——这个世界中的、

十五。

——所有人的心之光辉吧！！加百列！！

最终的第十六击，慢了一步从左上段全力斩下。

用眼睛确认了攻击的加百列的蓝色眼睛，如同确信胜利般眨了一下。

比直接放出的斩击快了一步，敌人左肩伸出的黑翼，将我的左臂从根部斩飞。

充满了光的左臂在一瞬间爆散，空中只有青蔷薇之剑飞舞。

「LLLLLLLL――――――!!」

发出高声哄笑的同时，加百列右手握着的虚无之剑，直接向我的头上挥落。

啪。

响起让人信赖的声音，一双白色的手握住了空中漂浮的青蔷薇之剑的剑柄。那并不是我的手。

与凄厉的炸裂音一起，无数的星辰飞散——

青蔷薇之剑与虚无之剑相击。

握着剑的优吉欧，摇了摇短发看着我说道。

『去吧——就是现在，桐人！』

「谢谢，优吉欧！」

我以坚定的声音回应。

「呜……噢噢噢噢噢——！！！！」

我的第十七击以右上段斩的态势，带着全身的力量挥向加百列的左肩。

漆黑的流体金属飞散，深深斩入的剑，在到达心脏的位置后停了下来。

瞬间——

我和优吉欧、充满了夜空之剑和青蔷薇之剑的所有光芒，注入加百列的身体，在各处奔流。

** 74

加百列感觉到，自己体内突然有压倒数量的正之能量的大瀑布流入了宽广而空虚的深渊。

视线被无数流光覆盖，耳边听到了一个个声音。

——神啊，请让那个人……

——那个孩子，请平安地……

——让战争结束吧……

——我爱你……

——将这个世界……

——将这个世界，

——将这个世界守护吧……！

「……哈，哈，哈。」

虽然心脏被少年的剑贯穿，加百列却张开双手和六枚翅膀哄笑了起来：

「哈哈哈，哈哈哈哈哈哈！！」

何等愚蠢，何等愚昧，简直愚劣至极。

竟想将我的饥渴，将这无尽的虚无填满。

这到头来不过是想要用人手温暖宇宙这样的不敬之举——为何还不明白！！

「那我就一滴不剩，全部吸干——将它们全部吞噬！！」

加百列的双眼和口中闪烁着蓝色的虚无之光喊道。

「你做得到吗！！只不过恐惧着、害怕着人心之力的你做得到吗！！」

全身被黄金波动缠绕着的少年也一样喊了出来。

一层强光覆盖在剑上——产生进一步的热和光，刺入了冰冻的心脏。

视野逐渐白热，听觉也被切断了。

即使如此，加百列仍然大笑着。

「哈哈哈哈哈，哈——哈哈哈哈哈哈！！！」

我已经不再恐惧。

就算敌人深处的虚无如同无边的黑洞，在我心中由人们的心灵和祈祷产生的巨大的银河正闪
着光之漩涡。

加百列眼窝和口腔中的紫红色光，开始一点点变了颜色。

从紫到红，到橙，再到黄——最后是纯白。

噼。

随着微弱的声音，吞没了夜空之剑的漆黑流体金属身体，出现了一道小小的龟裂。

又一道。而且是从胸口到喉咙。

从龟裂中溢出了白光。后背上的六枚翅膀，也从根部被白色的火焰包围。

仍然哄笑着的嘴大大张开，肩部和胸部都开了大洞。

即使身体各处都出现了锐利的光柱，加百列的嗤笑却毫无终止的迹象。

「哈哈哈哈哈哈哈哈哈哈啊啊啊啊啊啊啊啊啊啊啊啊啊————」

声音的频率逐渐上升，最后变成金属质地的高频率声波。

虚无的天使被遍布全身的白色龟裂缠绕——

一瞬间，开始向内崩溃、收缩。

然后解放。

有着令人恐惧的规模的爆炸光，描绘出螺旋形状向天边飞驰。

「————哈哈哈哈哈哈哈！！」

加百列·米勒在哄笑中一下子坐了起来。

映入视野的，是铺着灰色金属板的墙面。接线和管道上贴着几张日语写的注意事项贴纸。

「哈哈哈，哈，哈…………」

带着混乱的呼吸收起笑声，加百列眨了几下眼睛，向左右看去。

这里毫无疑问是〈海龟〉的第一STL室。似乎是因为预料之外的原因自动注销了。

何等美中不足的结局。要是就那样吞噬近乎无限的灵魂之流的话，明明最后就能将那个小鬼
的心也一起吞噬掉的。现在立刻再度登录的话还赶得上吗。

苦笑着回过头的加百列看到的。

是躺在STL的座椅上，闭着眼睛的高个头白人男性的样子。

……谁啊。他一瞬间想着。

袭击小队里有这个队员吗？而且这个家伙，在我用来潜行的机器上做了什么……

想到这里的时候，他才注意到。

那个人，那张脸，是他自己。

是加百列·米勒。

那么，看到这幅场景的我……到底又是谁？

加百列眺望着自己抬起的双手。他看到的，是有着半透明感的，发着朦胧的光的东西。

这是什么啊。发生了什么。

这时——

从背后传来了轻轻的声音。

「……你终于来到这里了呢，盖博。」

加百列一下子回过头。

站在那里的，是一个穿着白衬衫和深蓝色百褶裙的幼小少女。

有着长长的柔软金发的头深深的低了下去，所以看不到她的脸。然而加百列立刻就明白了那
个少女是谁。

「……艾莉西亚。」

加百列自言自语着。

「为什么，你会在这里，艾莉……」

艾莉西亚·克林格曼。加百列为了自己探求灵魂的崇高目的，而杀死的第一个人——身为他
青梅竹马的少女。

加百列一直为没能捕获当时看到的有着清亮光辉的艾莉西亚的灵魂而痛恨不已。然而，那个
灵魂从没有离开他，一直都好好的呆在他的身边。

加百列忘记了自己面前这奇怪的现象，微笑着伸出了右手。

咻。艾莉西亚的左手快速伸出，用细小的五指紧紧握住了加百列的手。

好冷。简直就像冰一样。冷气像是尖针一样一点点刺进了手里。

加百列反射性地想要将手拉回来。然而，艾莉西亚的左手如同钳台一般动也不动。加百列的
笑容消失了。他皱起眉头说道：

「……好冷啊，放开我的手，艾莉……」

听到加百列的低语，金发突然左右摇摆了起来。

「不可以哦，盖博。从此我们要永远在一起啊。来，我们走吧。」

「去是……要去哪里啊。不行，我还有要做的事情。」

加百列低声说着，全身使劲想要将手拉回。然而根本就动不了。反过来，右手还被一点点往
下拉了。

「放开我……放开我，艾莉西亚。」

在加百列稍微严肃地出声的同时。

艾莉西亚一下子抬起了头。

在那仔细梳好的刘海下面的脸进入视野的瞬间——

加百列感觉到心脏一下子收缩起来。

内脏在翻滚。呼吸变得混乱。身体开始起鸡皮疙瘩。

这是什么啊。这个感情到底是什么啊。

「啊……啊，啊，啊……」

发出奇怪呻吟的加百列，慢慢摇了摇头：

「放开我。住手。放开我。」

虽然他无意识中抬起左手，但艾莉西亚却如同飞过来一般将那只手也紧紧抓住了。如同冰冷
的金属一般的手指，一点一点嵌了进去。

呜呼呼。

艾莉西亚笑了。

「这就是恐怖哦，盖博。就是你一直想要知道的真正的感情哦。怎么样，很厉害对吧？」

恐怖。

在至今为止探求灵魂的实验中杀死的人们，在濒死之时露出相同的表情的来源。

然而，这种感觉实在没法说让人感到很舒服。不如说相当让人不快。可不想知道这种东西。
赶紧结束吧。

但是——

「不可以哦，盖博。从现在起要一直继续下去呢。你只会永远感觉到恐怖哦。」

随着吱的一声，艾莉西亚小小的皮靴沉入了金属地面。

接着，加百列的脚也陷了进去。

「啊……啊……不要啊。放开我……不要啊。」

虽然加百列神志不清地说着，可沉陷却根本停不下来。

突然，从地面上砰地飞出一只白色的手臂，缠住了加百列的脚。又是一只。然后又是一只。

加百列的直觉告诉自己，这是至今亲手捕获的猎物们的手。

恐怖感开始不断上升。心脏以惊人的速度跳动，汗水从额头上流下。

「不要……不要，不要不要不要……！！」

加百列终于开始惨叫。

「快过来，克里特！起来，瓦萨戈！！汉斯！！布利格！！」

虽然呼唤着部下们，但面前的大门却依然保持沉默。躺在旁边的STL上的瓦萨戈也没有起来
的迹象。

不知何时，身体从腰部以下都已经没入了地面。拉着自己双手的艾莉西亚，已经只能看到肩
膀以上的部分了。

那张『脸』在完全没入地面前的一瞬间，大笑了一下。

「啊……啊啊啊……呜哇啊啊啊啊啊——！！」

加百列发出了哀鸣。

一次，又一次。

肩膀，脖子，然后连脸都被白色的手缠住了。

「啊啊啊啊……啊啊啊…………啊………………」

随着咚的一声，视野陷入了黑暗。

加百列·米勒因领悟到了自己的命运——将被永远流放而迸出高声的哀鸣。

之后——

Under World的时间流，开始再次加速。

在与此同时切断信号的瞬间，通过AmuSphere进入Under World的几百名日本人也被自动切断
了连接，在各自的房间或网吧单间里，在浸染胸中的各自的感慨中醒来。

他们都无言地记忆着、思考着、在心中刻入在异世界体验到的事情。然后拭去眼角的泪水，
操作着携带终端或AmuSphere。为了向在之前的战斗中倒下并注销的友人们，传达在那个世
界发生的一切。

诗浓和莉法在再次加速的瞬间前，就因天命全损而离开了Under World。

在《拉斯》六本木分室的STL上醒来的二人，等待仍飘在神经中的痛楚的余韵散去，互相对
视着，深深点了点头。

诗浓和莉法都毫不怀疑桐人会苏醒、打倒敌人、拯救世界，很快就会回到现实。

下次见到他的时候——

就算无法传达过去，也要好好地将这份感情说出来。

下定了决心的两人意识到对方的想法，露出了淡淡的微笑。

——然而。

完全解除限制的STRA系统，正将Under World内流动的时间脉搏，向远超过去的高速领域加
速。

超过了一千倍。

超过了五千倍。

向着名为《极限加速阶段》的，相当于现实世界流速五百万倍的时间之壁的远方前进。

** 75

我的身体漂浮在星光已然散去的空中，无力地拍动着背上的双翼。

应该已被斩断消失的左臂不知何时已经再生了。我以仅存的力量拼命握着手中的青蔷薇之剑，
忍住要从眼中渗出的泪水。

我明白，烙印在剑中的，至今为止无数次拯救了我、激励了我的优吉欧的灵魂，在那个瞬
间——毫无动摇地挡住了加百列的剑刃的那一刹那，终于彻底燃尽了。

死者无法复生。

所以回忆才如此宝贵，如此美丽。

「……是这样的吧，优吉欧……」

虽然我低语着，却并未听到回应。

我将手中的双剑慢慢收回后背上的剑鞘。

随后，头顶夜空的颜色开始变淡。

黑暗逐渐溶解流去，光芒在另一端苏醒。

……蓝色。

然而，再次出现的Dark Territory的天空，却并不是之前的血色。

只有清澈透明的湛蓝色，在各处蔓延。

我无法确定，这是因终于开始的《极限加速阶段》的影响而导致的结果，还是十余万人的祈
祷引发的奇迹。

不论哪一个理由，透明的蓝天都美丽到令人想要落泪。我感到自己被强烈的乡愁和感伤浸染，
将这湛蓝一口气吸入身体。

闭上眼睛，呼出长长的一口气，然后将身体转向另一个方向。

睁开眼睛后看到的，是从下方开始无声崩坏的白色大理石阶梯。

我张开双翼，如同要追赶崩解的阶梯一般缓缓向浮在空中的小岛降落。

圆形的浮岛上，有无数有着近乎溢出的鲜艳颜色的花朵在开放。穿过花田的白色石板路，向
中央如同神殿一般的建筑物延伸。

我在石板路上着地，将双翼变回大衣的下摆，接着环视周围。

鼻子里闻到了甘甜而清爽的蜜香。几只琉璃色的小蝴蝶轻飘飘地飞舞，小鸟在树梢上鸣叫。
在蔚蓝的天空与柔和的阳光下的这幅景象，显得如此美丽，简直就是一幅名画。

上面空无一人。

不论是小路上，还是小路前方排列着圆柱的神殿中，都找不到任何人的身影。

「……太好了。赶上了吗。」

我孤零零地自言自语着。

我靠着感觉，知道了随着加百列·米勒被吸入光之螺旋中消失，这个世界再次基于STRA的倍
率开始加速。对于亚丝娜和爱丽丝，能否平安从控制台脱离，可以说是微妙的时间点。然而，
二人在时间限制内跑过了漫长的阶梯，到达了那里。

爱丽丝——身为这个世界产生的理由的灵魂，突破Fluct Light极限的少女，终于开始了通
向现实世界的旅行。

从此以后，大概还有无数的苦难等待着她吧。她必须和运转原理几乎完全不同的世界、不自
由的机械躯体、以及可能将真正的人工智能用于军事领域的企图战斗。

然而，爱丽丝一定能做到的吧。因为，她是最强的骑士。

「……加油…………」

我抬头望向天空，为再也无法相见的黄金的整合骑士祈祷。

没错——

《极限加速阶段》开始的现在，我已经完全失去了从内部自行注销的手段。这个世界内的三
个系统控制台已经全部被冻结，如果天命全损，就只能在没有感觉的黑暗中等待加速阶段结
束。

如今，虽然身处外部的菊冈等《拉斯》工作人员正为关闭我的STL而奋斗，但最短也要二十
分钟才能完成。

在这二十分钟内，我要在这个世界度过两百年日月。

我不知道自己是会因灵魂寿命耗尽而意识消失，还是因无法长时间忍受五百万倍的加速而在
更早的时间点消失。

唯一能确定的，就是我已经无法回到现实世界了。

父母、直叶、诗浓、克莱因、艾基尔、莉兹、西莉卡。

学校里的朋友们，ALO内的玩家好友们。

爱丽丝。

还有，亚丝娜。

已经再也见不到我爱着的人了。

我的双膝缓缓跪在白色的石板上。

用双手支撑着无力的上半身。

视线开始模糊，摇动着无数闪烁的光，一次又一次落到磨光的大理石板上。

大概——我只有现在，才有稍微哭泣一下的权利吧。

为了已经失去的，不会再次回来的，重要的事情而哭泣。从紧咬的牙齿间漏出呜咽，泪水变
为泪珠落下。

啪。啪啪。

耳边传来了水滴落在石板上的声音。

啪。

啪。

——叩。

叩、叩。

突然，响起了有着确切的密度的和声。

叩、叩。离我越来越近了。从指尖传来微弱的颤动。

空气在摇曳。在浓密的花香中，仿佛传来了新的香气。

叩。

……叩。

声音在我的眼前停下。

之后，有什么人，呼唤了我的名字。

** 76

神代凛子坐在副控制室的操作席上，屏住呼吸注视着控制台位于正面偏左位置的小型玻璃舱
门。

舱门上面的液晶窗口，闪烁着『EJECTING...』的红色文字。

抽出压缩空气的声音，在耳边低声回响。

终于，窗口的另一端，出现了一个小小的黑色正方形。液晶窗口变为绿色，闪耀着『FINISH』
的光芒。

凛子伸出颤抖的手，打开玻璃舱门将它拿了出来。

坚固的金属封装。边长约六厘米的正方体。相当沉重。被毫无缝隙地封闭着的一个面上，有
一个超微型连接装置。

《爱丽丝》的灵魂——就沉睡在里面。

从设置在〈海龟〉基部的巨大Light-Cube集群内，依照系统命令弹出了一个晶体立方体，自
动封入金属封装后，又被传送到长长的传送带上，终于到达了这里。

这同时也是从名为《Under World》的内部世界，通向名为《Real World》的外部世界的旅
程。

凛子在一瞬间因不知何以言表的深切感慨而失声，但很快就恢复意识，紧握着金属封装喊道：

「亚丝娜小姐，爱丽丝的弹出工作结束了！接下来是你了，抓紧时间！！」

她瞬间瞥向染成一片红色的主显示器上的倒计时。

「只剩下30秒了！！快点……注销！！」

一瞬间的沉默。

接着，从扬声器里传来的——是意料之外的话。

「对不起，凛子小姐。」

「诶……？为，为什么……？」

「对不起。我要……留在这里。一直以来都麻烦你了。凛子小姐所给予我的帮助，我绝对不
会忘记。」

从扬声器中传来的结城明日奈的声音，安稳而温柔，却似乎已下定了决心。

「爱丽丝就拜托你了。爱丽丝，是个很温柔的人。她有着无数的爱，也被无数的人爱着。为
了那些为她而消失了的灵魂们……还有，为了桐人君，请绝对不要将她用于军事用途。」

在无言以对的凛子耳边，又传来了明日奈最后的话：

「请告诉大家。抱歉……再见了……谢谢你。」

紧接着，倒计时变成了零。

随着长长的警报声音，无数机械的运转声在狭窄的电缆管道内回响。

管壁另一端的冷却系统开始全速运转。几个大型风扇正拼命将支撑Under World的系统群放
出的大量废热吸收并排出。如今如果从海上眺望〈海龟〉的话，大概可以看到金字塔顶端附
近的微弱蒸汽在摇晃吧。

「…………开始了……」

比嘉健低声说道。

「啊。」

以简短的话语回答的，是背着比嘉沿着细长的梯子下降的菊冈诚二郎。

二人在判断无法避免进入《极限加速阶段》的时间点就立刻开始准备，潜入了电缆管道，可
光是用安全绳固定负伤了的比嘉的身体就花了八分钟。

加速在菊冈以汗水如同要喷出来一般流下的势头在管道中降下到达耐压隔壁之前，就已再度
开始。

比嘉以祈祷一般的心情按下对讲机上的开关，呼叫位于副控制室的神代博士。

「凛子小姐……怎么样了？」

在噪音和线路连接音后，另一端却保持着沉默。

「……凛子小姐？」

「……对不起。已经确保爱丽丝平安无事了。只是……」

神代博士拼命忍住声音，说出了后面的话。

比嘉屏住呼吸后，紧紧闭上了眼睛。

「……明白了。这边也会尽力的。开放舱门的时机，会在之后联络。」

挂断通话后，比嘉这才将屏住的气一口气吐了出来。

不知是不是察觉了状况的菊冈并没有问什么。只是以他那全是肌肉的身体拼命地跳跃着。

「……菊先生……」

几秒钟后，比嘉才终于低声向指挥官传达了神代博士的话。

克里特呆呆地看着主显示器上新出现的窗口以及上面的字母。

上面所显示的，是从集群内排出了一个Light Cube，并将其运送到耐压隔壁另一端的副控制
室的消息。

也就是，K组织已经拿到了爱丽丝的意思。

换句话说，从Under World内部发现并夺取爱丽丝的超过了十小时的作战完全失败了。瓦萨
戈和米勒中尉潜入Under World，率领暗黑界的军队侵略人界，展开如同好莱坞电影一般宏
大的战争，还欺骗近十万美国、中国和韩国人卷入的努力全部化作了泡影。

克里特咔咔挠着和尚头，发出一声鼻音后将思考切换到别的方向。

在剩下的五小时里，有没有能够从物理上再次夺取爱丽丝的可能性呢？

耐压隔壁没法从这一边破坏。但是，像之前那样上边开放隔壁的情况就是另一回事了。

再说，之前打开舱门到底又是搞什么？难道他们真的认为让那样一个机器人搭载烟雾弹，这
边就会有什么动作吗？

如果那是佯动作战呢？如果有其他开放隔壁的目的的话，那个目的到底又是什么呢？

克里特回过头，向队员们说道：

「喂，谁把〈海龟〉的设计图拿过来——」

接着，布利格和仍然争吵着刚才的赌博不成立的汉斯，根本没往这边看就将叠成几层的纸拿
了过来。克里特带着一脸「真是的」的表情摇摇头，将设计图接过来展开。

「嗯……？这里是主轴……耐压隔壁在这里横断……机器人突进的楼梯是这里吧……」

此时，显示器上的倒计时变成了零，整个房间都响起了低沉的机械声音。时间加速再次开始
了。然而，因为布利格的乱来破坏了操纵杆，倍率正变成不得了的数值。

然而，Under World变成什么样已经没有关系了。作战失败就等于瓦萨戈和米勒中尉大概在
潜行中『死亡』，他们现在应该在旁边的房间中进行注销处理吧。

现在，在米勒中尉回来之前，需要先行确定下一个作战选项。

克里特在昏暗的灯光下拼命瞪着地图，这才终于注意到它。

「哦，这里也有一个小舱门……这什么啊，电缆管道……？」

** 77

向比嘉健传达完情况的凛子，在沉痛的叹息后将后背靠在操作席上。

为了已确定不可能在时限前脱离的桐之谷和人，自己也留在了Under World的结城明日奈的
决心，是如此的年轻而直率，又是如此的宝贵而美丽。

凛子无论怎样都无法让自己不想起，过去她曾爱着的那个男人，将她留在现实世界，消失在
遥远的异世界的事情。

如果那时，有自己可以一同前往的机会的话，又会做出怎样的选择呢？会选择是和他一样，
在原型STL内将大脑灼烧殆尽，只留下意识的复制体这条单行道吗？

「晶彦……你…………」

闭上眼睛的凛子，以不能称作声音的声音自言自语。

当初他的愿望，应该就是创造由浮游城艾因葛朗特，以及被囚禁在其中的五万名玩家构成的
《真正的异世界》。

然而，在长达两年前的浮游城内的日子里，他看到了什么，知道了什么。这『什么东西』改
变了他的想法。

在前方——更前方，存在的东西。

他注意到，SAO世界并不是终点，而只是一个起点。所以，他才在长野被原始森林包围的山
庄里，将NERvGear的信号输入输出原件加以高密度化，终于完成了将自己杀死的试作机。

被他托付了基础资料的凛子，开发了医疗用高精度NERDLES机器——也就是Medicuboid。

《拉斯》和比嘉健又在与这Medicuboid连续连接了数年的一位少女提供的庞大数据的基础上，
完成了STL。

这样想的话，可以说名为Under World的终极的异世界，就是以他——茅场晶彦的想法而诞
生的。

那么，Under World的完成，就是茅场所期待的那个终点吗？

不，一定不是。

因为，他所留下的另一个种子，名为《The SEED》程序包的碎片还有着未解之谜。

确实，可以说正是因为《The SEED》规格的VRMMO已经标准化，在之前的外部势力袭击Under
World时，日本玩家们才能通过帐号转换加以对抗。

然而，就算是茅场也不可能在几年前就预料到会有这等事态。基于转换机能的Under World
内潜行，只能说是一个副产物。

要是这样，目的又是什么呢……为什么有必要让全世界的VR世界，以共通规格相互连接呢……

「……士，神代博士。」

听到背后的声音，凛子一下子睁开眼睛。

回过头去，有着刚毅容貌的中西上尉，立刻敬了个礼后报告道：

「针对隔壁再开放的对应准备已经完成了。随时可以启动。」

「啊……知，知道了。非常感谢。」

凛子看向显示器确认时间。从进入《极限加速阶段》后，已经过了一分钟。内部时间则
是……十年。

令人难以置信。桐之谷和人和结城明日奈灵魂的年龄，已经超过了凛子。

快一点……一分一秒也好，早一点注销。如果，能在灵魂寿命彻底耗尽前脱离的话，还可以
重置《极限加速阶段》开始后的全部记忆。然而，为了能这么做而剩下的时间，理论上已经
不足十二分钟了。

比嘉君……菊冈先生。

快一点！！

凛子紧咬着嘴唇，在心中说道。

菊冈中校从喉咙里吐出的呼吸声音，已经如同快要坏掉的风扇一般。流下的汗让上衣变色，
连比嘉的衣服都湿透了。

比嘉好几次将「从这里我就自己下去」的话咽了下去。

被柳井射出的子弹击中的右肩，虽然注射了极限剂量的镇痛剂仍然极为疼痛，身体因大量失
血也如同灌了铅般沉重。不管怎样都没法自己抓住梯子。

就算这样——比嘉想着。

在这种事态之下，菊冈中校还如此拼命，实在不让人不感到意外。

身为Alicization计划精髓的，突破极限的Fluct Light《爱丽丝》，已经确保在手中了。之
后只要解析爱丽丝的构造，发现其与之前的Fluct Light间所存在的差异，就可以做到真正
Bottom-Up型Ai的量产。在即将到来的无人兵器时代，能够创立日本独有的技术基础，从美
国军事生产系统中脱离——这一《拉斯》的设立目的也终于达成了。

这就是，名为菊冈诚二郎的这个人的愿望。

在转到总务省前就埋头于SAo事件也好，创造自己的角色和年轻的VRMMO玩家们交流也好，一
切都是为了这个目的。

因此，要说菊冈的行动优先顺序的话，现在应该会选择彻底关闭耐压隔壁，在护卫舰突入前
都死守爱丽丝的Light Cube吧。

哪怕这等于被困在Under World里的桐之谷和人和结城明日奈灵魂崩坏，把一定会激烈反对
的神代博士软禁在房间里也在所不辞。

「你肯定，觉得……这，很意外……吧。」

菊冈中校在急促的呼吸中突然说出的话，让比嘉漏出了奇怪的声音。

「不，不是，那个……嘛，总觉得这么做一点都不像你啊……」

「真……是的。」

菊冈全力向不远距离处的舱门降下，喉咙里嘿嘿笑出了声。

「但是……我说过，的吧。这也是……有，打算过的，行动……啊。」

「诶……诶？」

「我……平常是，考虑到最糟糕情况，的人。现在……敌人，还有，再次夺取……爱丽丝的，
可能性，还是这么想比较好。」

「最，最糟糕……吗。」

还有着比敌人注意到这个电缆管道，在耐压隔壁开放的情况下从下面突入还要糟糕的情况吗。

然而，在比嘉想要推测下去之前，菊冈的战斗靴靴底，终于碰到了钛合金舱门。

代替停下动作，只是剧烈呼吸着的指挥官，比嘉按下了对讲机上的开关：

「凛子小姐，我们已经到了！请解除耐压隔壁的锁定！！」

「啊……搞真的么，居然开了——！」

克里特看着主显示器上显示的耐压隔壁开放警告喊道。

到底为什么。为了什么。

怎么想都不对头。已经确保了爱丽丝的现在，K组织居然故意让防御出现破绽，到底有什么
理由。

然而现在已经没有想这想那的时间了。克里特回过头，挥手向队员们喊道：

「……那个，啊，布利格留下，包括汉斯在内的所有人突入主通道！迂回攻击，确保隔壁另
一侧！」

「还真是简单啊……」

汉斯咋着舌扛起了步枪。十几名队员跟在他的后面。

「喂喂，我又要怎么办……」

克里特看向一脸不服地撅着嘴唇的布利格长着胡须的脸，打了个响指说道：

「好好地有工作呢——需要你的手腕的，重要的任务啊——」

当然他的脑子里想着别的事情。最好别让这个笨蛋离开自己的眼睛比较好。

「听好了——我们两个去看看这边的电缆管道。不管怎么样我都觉得这里才是敌人最重要的
地方——」

「哦……哦，这样啊。是这样没错。」

看着笑了一下，以大剌剌的动作确认突击步枪的枪机的布利格，克里特忍住自己轻轻的叹息。

经过汉斯他们出去的主控制室的门，准备跑向另一个方向之前，克里特瞥了一下里面的
门——第一STL室。

这么说的话，注销需要花这么长时间吗？瓦萨戈那家伙难道是在悠闲地抽烟吗？

虽然想着是不是应该先去确认，但此时布利格已经跑了起来。

再次咽下叹息，克里特追在他的后面。

几十秒后，他们到达了目标地点。一眼看去，只不过是通道的末端而已。然而根据地图，眼
前的小舱门的另一端，应该有一个和主轴上部架构连接的电缆管道。

克里特用渗着汗的手握住回转式的开闭手柄，然后转动起来。

拉开沉重的金属门的克里特最先看到的，是被暗橙色光照着的相当狭窄的隧道。正面的墙上，
设计着近乎垂直的阶梯。

接着他毫不在意地看向脚边——

「……呜哦！？」

克里特发出破碎的声音，一边赶紧后退。

那里嵌着一个身体似乎被弯成了U字形的男人。背后的布利格一下子架起了步枪。然而他接
着就压下声音说道：

「……死了耶。」

确实，侧脸看向他们的男人的颈椎，以不自然的角度弯曲着。克里特紧锁眉头仔细看着那个
男人的脸，眨了几下眼睛。

「诶……这家伙不是他么，提供K组织情报的那个人……怎么回事，难道是间谍身份暴露了
吗……？但是，这种死法……」

战战兢兢地用指尖接触男人的皮肤，感觉冰冷湿润。从温度来看，他恐怕在隔壁第一次开放
时候就死了。也就是说，第一次开放是因为这个男人想要脱离到下层吗？然后，踏空了梯子，
摔死了？

然而，这样的话，为什么隔壁会再次打开呢。

克里特转向布利格说道：

「还是先去看看管道上面怎么回事吧。」

留着胡须的巨汉鼻子响了下，伸出右手随意将间谍的尸体拉到了通道内。他架起步枪，上半
身探入昏暗的隧道里——

喂喂，别连头都伸进去啊。克里特这么想的一瞬间——

「见鬼！！」

随着一声喊叫，突然有人开枪了。

黄色的闪光反射到克里特的视网膜上，有两种音调不同的射击声敲打着他的鼓膜。

压下哀鸣跑过去的他的面前，布利格巨大的身体，像是被看不到的锤子打中一般落到了地上。

「喂！！什么啊，可恶！！」

克里特这么喊着，向后跌倒了。布利格上半身就位于刚才间谍的实体所在的地方，已经一动
也不懂了。不仅是姿势，连命运都和那个间谍一样——这一点再清楚不过了。

——接下来，要怎么办。

全身冷汗的克里特思考着。

把步枪从布利格手中回收，和隧道里的敌人互相射击来复仇吗？怎么可能！我不过是个电脑
死宅，工作只是敲键盘罢了。

擦了擦磨得粗糙的裤子，克里特向主控制室后退，继续思考着。

至少这样可以明白为什么K组织会如此积极攻击的意图了。但是，战斗力很明显是这边占优。
如果战斗的话，那边当然会有牺牲。如果他们失败了，整个上半部分都被占领，爱丽丝也会
被再次夺取。

难道K组织的指挥官还考虑到比这还『糟糕』的情况吗？他想过这里有将〈海龟〉整个炸掉
的火力吗？怎么可能，手持C4炸药连耐压舱门都炸不开……

火力…………

克里特突然倒吸一口凉气。通道前面横陈的两具尸体已经没有了意识。

有。

将〈海龟〉整个破坏，让爱丽丝和K组织全都变成海藻的办法。只有一个。

确实，客户的命令里提到，在判断不可能夺取爱丽丝的场合下，至少也要将其完全破坏。然
而，为此就要让这个巨大的自走式大型浮台，和数十位成员成为陪葬品。

自己下不了这么可怕的决定。肯定会成为缠绕自己一生的噩梦。

克里特站起来，为了得到指挥官的判断，奔跑着。

「菊……菊先生！没事吧，菊先生！！」

比嘉强压声音问道。从管道最下方的舱门出现的敌人，至少用步枪打出了三发子弹。

没有回应。背着比嘉，右手握着梯子一边，左手拿着手枪的菊冈中校，像是把肩膀靠在墙上
一般无力地垂着头。

「菊……」

菊冈先生！！！

比嘉正要喊出来的时候，中校激烈地咳嗽了一下。

「切……喂，真是的……中招了。如今想想，本来该穿着防弹衣来的……」

「那……那是当然的！结果你居然真穿着夏威夷衫就过来了……」

比嘉安心地吐了口气，再次询问是否受伤。

「嗯，貌似中了一枪。相比这个，你没事吧？有没有被跳弹伤到？」

「诶……没有。身体倒没受什么伤。」

「那就抓紧吧。连接装置马上就到了。」

在再次开始降下的菊冈背上摇晃着的比嘉再次在心中深感意外。

原本以为菊冈中校在身体相关的技能上是个相当不擅长的人，但他宽广的后背上的肌肉如同
钢铁一般，还有刚才的射击。挂在梯子上，只用左手向下狙击的这种恶劣条件下，居然只用
两发连射就正确地击中了敌人的喉咙和额头。

真是个不论怎样交往都不知底细的大叔。

比嘉轻轻摇了摇头，在右手中准备用于和已经进入视线的检查连接器连接的线缆。

回到通道里的克里特，听着从上方响起的步枪连射声音，跑向主控制室。

房间里仍然没有米勒中尉和瓦萨戈的身影。还没从STL里出来吗。明明从时间加速再次开始
后已经过了五分钟了。

虽然脑子里这么想着，但克里特还为要不要向他们说明而迷茫着。他相信，听到消息的二人
肯定会立刻下达将〈海龟〉炸掉的命令。他们可不是会关心为了达到目的会牺牲多少人的人。

克里特没能得出结论，只是一口气打开了第一STL室的房门。

「队长！爱丽丝，被敌人…………」

本该接下去的话，却变成了嘎吱嘎吱的声音从喉咙里发出。

在他的正面，躺在一号STL床上的，从额头往上都被巨大的机器吞没的米勒中尉的脸，露出
了之前一次都没见过的表情。

不对。克里特从来没在任何人的脸上看到过那样的表情。

蓝色的双眼像是要飞出来一般大大睁开。嘴部的下颚关节像是脱臼一般张开到极限，而且还
歪斜着。突出的舌头扭向奇怪的方向，简直就像是别的生物了。

「队……队……长……？」

克里特喘息着，膝盖开始颤抖。现在，如果米勒中尉突出的眼球转动一下，他相信自己肯定
会发出惨叫。

克里特的牙齿咔咔咬着，战战兢兢地伸出手，轻轻抓住简直就像是防备着什么一般伸出的中
尉的左手腕。

脉搏已经没了。

身体冷得像冰一样。强袭小队指挥官加百列·米勒中尉，明明身上没有一处伤口，却已经彻
底气绝了。

拼命压下从胃部涌起的翻滚，克里特用沙哑的声音喊道：

「瓦萨戈……快起来！队长……死，死……」

他拖着双脚绕过一号STL，看向里面二号机的位置。

这次克里特真的发出了惨叫。

副队长瓦萨戈·卡扎尔斯，一眼看上去似乎很安详地睡着。闭着眼睛的脸上毫无表情，双手
和身体也伸的笔直。

然而——

闪着黑色光芒的，鲜艳的长卷发，如今已经变成了如同百岁老人一般干枯的白发。

已经不想确认瓦萨戈的脉搏了。克里特没有听到话，颤抖着膝盖后退。身为只信奉理性和代
码的黑客的克里特，相信自己必须赶紧离开这个房间，不能再和两个人对视了。

跌跌撞撞地转过身从还开着的入口跑出，用右脚立刻把门关上。

这时克里特才长出了一口气，拼命地让自己重新开始思考。

既不打算调查队长和瓦萨戈发生了什么，也不想知道发生了什么。能够推测的，就是在
Under World里发生了什么事情，因此他们的灵魂和现实中的肉体大概都被破坏了。

到这里，作战已经失败了。指挥官死掉的情况下，已经无法判断要不要将爱丽丝连船一起破
坏了。已经没有留在这里的意义了。

克里特拿起控制台上的通话机，挤出沙哑的声音说道：

「汉斯……回来。布利格、瓦萨戈和队长都死了。」

几十秒后，跑进控制室的花花公子的脸上，露出如同反着强光的小刀一般异样的表情。

「布利格死了！？为什么！？」

「在……电缆管道里，被从上面射击……」

克里特拼命拉住不知道听没听到刚才的话，架起步枪准备跑出去的汉斯。

「住手！敌人的攻击是佯动。已经，没有战斗下去的意义了……」

汉斯沉默了一会。之后，他敲了一下墙壁发出剧烈的声音，一下子转过身跑了过来。

「……不对，还有一个命令。没法夺取的话，就破坏掉。你肯定有什么办法吧？」

被汉斯一下子提起来，如同自己要被逼问着的他吃掉一般的克里特点了点头。

「啊……啊啊，也不是没有……不，不行啊。没有队长，做不了判断。」

「说啊，给我说！！」

汉斯突然用突击步枪闪着青光的枪口指向克里特。对着和布利格一直以搭档身份在中东和南
美的战场上战斗的佣兵那锐利的眼神，克里特没法反抗。

「发……发动机——」

「发动机？你说这艘船？」

「没错……这艘大船的发动机，是核动力炉……」

** 78

已经经过了十分钟。

神代凛子在无意识中紧握着双手，凝视着无情地刻在显示器上的数字。

进入《极限加速阶段》后，Under World内过去的时间——已经达到了一百年。

桐之谷和人和结城明日奈对着漫长的时间会有怎样的感觉，已经远超过了自己的想象。唯一
能够确认的，就是二人的Fluct Light记忆容量正逐渐接近极限。

根据比嘉的预测，人类的灵魂在蓄积了一百五十年分量的记忆时就会无法做出正常的动作，
开始崩坏。当然，这并非实验所确认的情况。实际的极限可能比这更长——或者，可能比这
更段。

如今只能祈祷能在灵魂开始崩坏之前完成注销处理了。如果能够做到的话，就还有变回二人
原本样子的可能。

比嘉君……菊冈先生。拜托你们了。

正在祈祷的凛子没有注意到，楼下响起的微弱枪声不知何时突然消失了。将这个事情告诉她
的，是跑回副控制室的中西上尉。

「博士！敌人开始撤退了！」

「撤……撤退！？」

抬起头的凛子哑然重复着。

为什么这个时候撤退了。耐压隔壁再次开放的现在，对袭击者来说难道不是夺取爱丽丝的最
后机会吗。放弃的话也太早了。离护卫舰突入还有四个多小时。

凛子敲打着键盘呼出显示舰内各处状况的窗口，向上尉询问道：

「战斗……有出现伤者吗？」

「啊……轻伤两人，重伤一人，不过在治疗中，应该不会有大问题。」

「是……这样吗。」

凛子将屏住的呼吸轻轻吐出。瞥过一眼，注意到有着刚毅面容的上尉在脸颊骨的位置贴着一
块大纱布，从纱布里渗出了一点血。他大概把自己也算在轻伤者中了吧。

为了让他们的奋战不被浪费，一定要将两个年轻人救出来。

至少，敌人开始撤退这件事是个好消息。凛子将视线转回状态窗口，确认船底的水中码头正
在开门。

「嗯，似乎是正在通过潜水艇脱离的样子……但就算这样……也太慌张了……」

正当她皱起眉头，轻轻咬住嘴唇的时候。

与之前完全不同的震动，让主轴整体都摇动了起来。

从巨大的浮台内发出「轰」的如同寒风一般的响声。桌子上的圆珠笔滚落到地面上。

「这……这是什么！？发生了什么！？」

「这是……啊……难道说，那帮家伙……！！」

中西上尉低声呻吟着。

「这个震动，是主机全力运转造成的，博士！！」

「主……机？」

「主发动机……也就是，主轴基部的，压水型核动力炉……」

跑向控制台的上尉，代替愕然睁大双眼的凛子用不习惯的动作操作着状态窗口。在一个个出
现的新窗口中，有一个出现了模糊的图像。

「混帐！！控制棒全都被压下去了！！那帮混蛋做了什么！！」

凛子以沙哑的声音向砰地敲了一下桌子的上尉问道：

「但是，安全装置应该还有的吧……？」

「当然，在炉心到达临界状态前，控制棒会自动突入，将核裂变停下来。但是……这里，您
看这里。」

上尉指向的是显示器上核动力炉所在房间的实时画面。虽然因红光而很难分辨，但大规模机
器的一部分，贴着一个小小的白色东西。

「这个恐怕是C4……塑胶炸弹。虽然这个尺寸应该没法破坏炉心，但这个位置是用于让控制
棒上升到炉心位置的驱动装置，如果这里被破坏了的话……」

「核裂变会……停不下来？这样的话，又会变成怎样……？」

「首先是一次冷却水会蒸汽爆炸，破坏储藏容器……最糟糕的情况下，融解的炉心会落到海
面，引发大量的蒸汽，恐怕会把主轴内部……从主控制室、Light-Cube集群到这个副控制室
整个炸飞吧。」

「什…………」

凛子不禁看向脚边的地面。超高温的蒸汽会打破这坚固的金属袭来——？

要是变成那样的话，好不容易至今都没有出现牺牲者的《拉斯》人员、躺在STL上的和人和
明日奈、还有封存在Light-Cube集群里的十余万人工Fluct Light们，都什么都不会剩下……

「我去拆除炸弹。」

突然，中西上尉低声说道。

「那帮家伙应该是设定了潜水艇足够离开〈海龟〉的起爆时间。差不多还有五分钟……应该
有十分钟。」

「但，但是，中西先生，发动机室里的温度，已经……」

「什么啊，也就是桑拿那种程度罢了。跑进去拔掉引信挺简单的。」

——但那也是穿好防护服之后才能做到的事。然而，已经没有准备的时间了。

凛子没能将心中的这句话说出来。走向房门的上尉那宽阔的后背，如同将一切柔弱和感伤都
赶走的钢板一般。

然而。

有什么人在发出嘎嘎声音的战斗靴到达房门前，从通道一侧拉开了门。

凛子凝视着在昏暗的通道里站着的什么人的身影。

传来了「嗡」的一声。是马达驱动的声音。接着是金属踏上金属地面的喀嚓声。

从像是蹒跚着一般弯下腰的中西上尉的另一侧，出现在灯光下的身影——是有着暗淡光泽的
无骨四肢的、有着搭载了复数个棱镜的头的，人型机器。

「Ni、Niemon……试作二号机！？为什么，自己动起来了……！？」

机器人无视喘着气的上尉，笔直注视着凛子，说道：

『我去。』

这个声音。

飘在房间里的，蜡和油的味道。

几天前，到达〈海龟〉的那一天夜晚，在梦中听到，嗅到的……

凛子慢慢站起，向前走出几步，挤出沙哑的声音：

「……晶……是晶彦吗……？」

发出淡淡绿光的传感器，如同眨眼般闪烁了一下。机器人点了点头。

如同被吸引过去一般接近着的凛子，用颤抖的双周，轻轻触碰着铝制外装。随着微弱的驱动
音抬起的双手，碰到了凛子的后背。

『这么长时间让你一个人生活，实在很抱歉，凛子。』[fn:22]

虽然是电子信号合成的声音，但他无疑是神代凛子过去爱上的唯一一名男子——茅场晶彦。

「居然会在……这种地方见面……」

凛子轻声说着应当早已忘记的方言。她的两眼溢出了泪水，渗入了传感器的光中。

『没时间了。所以，我只把必要的说出来。凛子……我能够和你相遇，感觉非常幸福。能将
我和现实世界连接起来的，就只有你一个人了。希望……以后，你也能这么做。将我的梦
想……如今还被分隔开来的，两个世界……』

「嗯……当然……当然。」

注视着不断点头的凛子的机械的脸上，露出了微笑。

退开身体的机器人，流畅地移动重心转向，以如同跑起来一般的速度向通道走去。

在无意识地想要追上去的凛子面前，门带着微弱的声音关上了。

凛子深吸一口气，紧紧咬住牙齿。现在还不能离开这个副控制室。自己必须确认各处的状况。

所以，她看向发动机室的录像，紧握胸前的火箭模型，最大程度的祈祷着。走到她旁边的中
西上尉，像是叹息一般低声说出「拜托了」的话。

比嘉健在听到电缆管道下方传来的涡轮的沉重声响时，终于明白了菊冈所害怕的『最糟糕的
情况』的真面目。

「菊……菊先生……那帮家伙，把核动力炉……」

沙哑的呻吟被强音盖过。

「我知道。现在还是全神贯注在STL关机作业上吧。」

「啊……知道。可是……」

再次将带状电缆的连接器插入好不容易够到的检测面板，可比嘉后背上的汗却停不下来。

假设核动力炉爆炸，这个工作也就没有意义了。到时候，Under World也好，爱丽丝的
Light-Cube也好，都会被高温蒸汽和高能量放射线彻底破坏掉。

然而核动力炉爆炸可没这么简单。覆盖炉心的厚壁金属容器用小手枪怎么也没法破坏，而且
控制部分也加上了数道安全保护措施。假设无谋地让其不断全力运转，安全装置应该很快就
会运作，将核裂变停下来。

这时，菊冈若无其事地以和平常一样的声音问道：

「嗯，比嘉君。接下去的一个人可以吗？」

「诶……嗯，如果用背带固定在梯子上的话，可以继续工作……但，但是，菊先生，你难道
要……」

「不不，只是去看看情况，不会乱来。马上我就回来。」

菊冈这么说着，马上将固定二人的背带揭开，用几个扣环紧紧固定在梯子上。确认比嘉的身
体已被固定后，他开始向下降落。

「那之后就拜托你了，比嘉君。」

看向上方的黑框眼镜深处，眯细的眼睛露出了笑容。

「小，小心一点！说不准那帮人还留在里面！」

菊冈对比嘉的声音做出一点也不像他的，突出右手大拇指的动作，接着以惊人的速度爬下梯
子。

到达最下端的舱门后，谨慎地窥视里面，然后他爬到了通道内。

当比嘉注意到的时候，菊冈的身影已经消失了。

右手敲着终端的比嘉，用左手胡乱整理系在腹部的背带时，感觉到有什么湿润的东西。他在
大惊中看向左手手掌，被在橘色的紧急灯下显出黑色的液体润湿了。

这并不是比嘉的血。已经再明显不过了。

** 79

几分钟前还被袭击者们占据的主轴下半部，虽然内部摄像头几乎全被破坏，但位于核动力炉
所在的动力室的摄像头仍然完好。

凛子看向将摄像头拍下的画面放大显示的主显示器，双手紧握着火箭模型等待着。

左边的中西上尉靠在控制台上，也一样紧紧握住双手。位于他们背后的，从楼下的防线上来
的警备人员和技术人员们，也做出各种各样的姿势，各自在心中默念着。

凛子之前曾请求他们至少退避到船头的舰桥位置。然而，没有一个人离开主轴。

在这里的所有人，都过着在无法公开的伪装企业《拉斯》进行研究开发工作的人生。他们将
自己的梦想和愿望，托付给了定能开拓真正的Bottom-Up型人工智能的新时代。

直到今天的这个瞬间前，凛子都认为自己不过是船上的一个过客。无论怎样，她都无法和菊
冈诚二郎这个看不透真心的人一起工作。

然而，凛子还是来到了拉斯。然后，她终于明白了。

人工Fluct Light，并不只局限于无人兵器搭载用AI这一狭窄的领域。

同样，Under World也并不仅是社会发展的模拟。

它们都是巨大的变革的开始。

让不断封闭的现实世界改变的，另一个现实。让想要打破现有系统的年轻人们的意志，在他
们眼前以看不见的力量具现出来的世界【An INCarnate RADius】。

——这大概才是你所期望的吧。

你在浮游城里的两年间注意到，发现到的，『他们』的可能性。那是令人目眩的心之光辉。

我一定会将它们连接起来的。所以——

拜托了，晶彦。守护大家的世界。

像是对凛子的祈祷做出回应一般，显示器上的远程录像内终于有了动作。

是被两重厚墙封锁的压水型核动力炉。通向炉心的狭窄通道上，出现了《人工Fluct Light
搭载用人形机器试作二号机》的身影。

不知是不是电池输出功率降低的原因，步伐非常缓慢。机器人像是与钛骨架的脚承受的重量
战斗一般，发出咔嚓咔嚓的声音前进着。

凛子无法想象，茅场晶彦的思考复制体，到底是在什么时候潜伏在那个身体内的。然而唯一
可以确定的就是，现在潜伏在那个机器的物理内存内的程序，应该是他唯一的本体意识。所
有的智能，都无法承受自己是有着复数存在的复制品这一认知。

电子系统几乎裸露在外的试作机器，到底能忍耐炉心的高温到什么程度呢。

拜托了，请平安拆除炸弹，再一次回到我的身边吧——祈祷着的凛子咬紧了嘴唇。

恐怕，茅场晶彦已经有了在这里消失的觉悟了。

过去即使将大脑烧毁也留下了意识的他，终于到达了目标，找到了应当死在的场所。

嗡的一声。马达在鸣叫。

喀嚓一声。是制音器的声音。

虽然极为勉强，但机器人还是步行走到了第一道门前。

它伸出右手，操作开关面板。随着噗的一声油压机的声音，厚合金门向内侧开启——

这时。

从扬声器里迸发出步枪的高声咆哮。

从打开的合金门深处，一个穿着黑夹克的士兵，喊着什么话跑了出来。

如同之前一样，头盔和风镜挡不住他的脸。看上去是个美男子的脸上，留着修正得很整齐的
胡子。

「什么……还留下了一个人！？为什么！？想死么……！？」

中西上尉惊愕地呻吟着。

显示器上，二号机将双臂交叉在身体前方，守护着躯干部位。但接着就被几发子弹打中了。

伴着弹出的火花，铝制外装被打出了几个孔。各处的线缆被打断，细小的齿轮和螺栓飞散开
来。

「住……住手！！」

凛子不禁发出了哀鸣。然而画面内的敌兵似乎在愤怒之下用英语喊着什么，继续扣动步枪的
扳机。机器人蹒跚着后退了一步。

「糟……糟糕！Niemon的简易外装承受不住子弹！！」

虽然已经赶不上了，中西上尉还是拿起手枪准备跑出去。

这个瞬间。

新的枪声从另一侧的扬声器中传来。

第三个人用手枪乱射着，跑进了通道。敌兵的身体左右剧烈摇晃了一下。从二号机的背后，
连一发误射都没有的连续射击。如此厉害的技术，到底是谁——

已经忘记了呼吸，只是睁大了眼睛的凛子面前，敌兵的喉咙部位终于冒出鲜血，瘦高的身体
如同被弹开一般向后倒去，再也没有动弹。

接着，救援者也在通道中慢慢跪下——

身体横着倒了下去。

额前的刘海。已经歪斜了的黑框眼镜。嘴边似乎可以看到淡淡的笑容。

「菊……菊冈先生！！」

「中校……！！」

凛子和中西一起喊了出来。

这次自卫官以如同要摔倒般的势头跑出了房间。凛子已经无法阻止他了。

一名技术人员替代他跑到控制台边，以飞快的速度敲打键盘，在显示器上呼出似乎是显示二
号机状态的窗口。

「左臂，输出为零……右脚，百分之七十。电池剩余容量百分之三十。可以，它还能动！！」

如同听到了技术人员的喊声一般，二号机再次开始前进。

嚓。嚓。随着蹒跚的步伐，被打断的电线上散发出火花。

已被打得破碎的身体穿过门缝，从里面将门关上。摄像头的画面切换到了炉心内部。

第二道耐热门，是用大型控制杆加以物理锁定的。二号机的右臂抓住控制杆，将它按下。肘
部的离合器空转着，有大量火花飞散出来。

「拜托了……」

与凛子的自言自语一起，副控制室里的众人也一起声援着：

「加油，Niemon！！」

「就是那，就差一点了！！」

咔。轰。

控制杆降了下去。同时，沉重的大门如同被内部的压力推开一半打开了。可以从显示器上清
楚地看到里面喷出的大量热气。

二号机蹒跚着前进。后背右侧的粗电线，突然迸出激烈的火花。

「啊……啊，不好！！」

技术人员突然喊了出来。

「什么……怎么了！？」

「连接电池和主控制板的电线损伤了！！那里如果断线的话……整体的电力供应就会停
掉……会彻底动不了的……」

凛子和其他人员都无言以对。

附着在二号机上的茅场自己，大概也意识到这是重伤了吧。像是用右肘按住摇晃的电线一般，
机器人继续慢慢前进着。

终于到达了核动力炉的内部。仍在全力运转的炉心散发出的高热无法排出，内部已经成了人
类无法直接承受的高温状态。

恐怕，很快安全装置应该就会动作，自动送入控制棒将核裂变停下来吧。

然而，在此之前，如果被设在那里的塑胶炸弹爆炸，破坏了控制棒驱动装置的话，从核燃料
里放出的大量中子，会继续让铀原子在链式反应中崩毁，最终导向无法控制的临界状态。

溶解的炉心让下方的一次冷却水一次性大量蒸发，撕碎容器，炉心在重力作用下贯穿船底到
达海面的话——

凛子的脑海中，一瞬间闪过喷出的白烟贯穿〈海龟〉的画面。

她一瞬间闭上眼睛，再次祈祷着：

「拜托了……晶彦……！！」

众人再次开始声援。如同要让将他们按回去一般，试作二号机踏入了主机室。

摄像头的映像再次切换。

接着，扬声器里传来巨大的噪音。显示器上的画面染成了一片红色。

撇开热气，像是拖着一只脚前进着一般的二号机，距离贴在容器上的塑胶炸弹已经只有五六
米了。

机器人向引信抬起右手。身体的各处不断有火花飞散，被割裂的外装碎片落在金属地面上。

「加油……加油……加油……！！」

只有这句话在副控制室里回响。紧握双拳的凛子也嘶哑地喊着。

还有四米。

三米。

下一步——

与此同时，二号机的后背上，迸发出如同爆炸一般的火花。

被打裂而摇晃着的黑色电线，简直就像受伤的内脏一般。

脸上的所有传感器都熄灭了。右臂也慢慢沉了下去。

两膝在油压减震器的驱动下，慢慢弯曲——

二号机，彻底沉默了。

显示器上的状态窗口内摇动着的几排彩虹色的输出显示条，全部落回左端，变成了一片黑色。

技术人员如同低语一般说道：

「……全部输出信号，都……消失了……」

——我从不相信奇迹。

过去，SAO在比预定时间还要更早地被攻略，所有玩家被解放出来的那一天，在山庄内的床
上醒来的茅场晶彦对凛子这样说道。

他的眼睛里充满安稳的光彩，留着乱糟糟的胡茬的嘴边露出了淡淡的微笑。

——不过啊，我今天，第一次看到了奇迹。

——被我的剑贯穿，HP应该完全归零的他，简直是像在反抗系统一般……拒绝了消灭，驱动
右手，贯穿了我的胸膛。

——说不准……我，只是在期待着那个瞬间吧……

「……晶彦！！」

凛子完全没有注意到胸前握着火箭模型的右手已经滴下鲜血，只是大喊着：

「……你是……《神圣剑》希斯克利夫对吧！！是那个《二刀流》桐人的，最好的对手对
吧！！那么，你也……创造一次奇迹，让我们看看吧！！」

咔。

咔咔。

二号机双眼内的测距传感器闪着绿光。

膝盖的关节部位内的齿轮，兹拉兹拉地转动着。

就像是在反抗一般。

状态窗口的左端，紫色的光在微弱的闪烁——

显示四肢与躯干的输出状态条，一口气延伸到了最右端。猛然放出驱动音的各处驱动装置散
发出火花。

「二……二号机，再次启动！」

技术人员发出了悲鸣。

凛子的两眼已经全是泪水。

「去啊——！」

「去吧！！」

所有人都在喊着。

机器人抬起右脚，向前，一步。

伸直身体，向高处伸出右手。

一步。再一步。

小小的爆炸。身体摇晃了一下。再往前一步。

伸长到极限的右手手指，终于碰到了炉心容器下面贴着的塑胶炸弹。

拇指与食指，找到了插进去的引信。

手、肘、肩部的关节都已经如同濒死一般散发着火花，二号机将已经到达时限的引信拉下，
高高举起右手。

闪光将画面染成一片白色。

右手与炸裂的引信一起被吹飞的二号机，整个身体慢慢倒下——。

砰地触及地面。传感器稍微闪动，然后熄灭的同时，出力状态条再次陷入了黑暗。

没有人说一句话。

数秒后，涌起的欢呼声，让副控制室为之摇晃。[fn:23]

** 80

如同寒风般的涡轮咆哮，终于逐渐减弱，最终完全散去。

比嘉长出了一口气。被敌人强制全力运转的核动力炉，终于沉寂了下来。

用左手的袖口拭去额头上的汗水，透过被弄脏了的眼镜凝视着小型终端的显示器。

两台STL的关机处理进程，好不容易完成了百分之八十。从《极限加速阶段》开始已经过了
十七分钟，相当于Under World内的一百七十年。

这是远超过比嘉预测的Fluct Light寿命极限的漫长时间。只从理论上考虑的话，桐之谷和
人和结城明日奈的灵魂已经崩毁的可能性很高。

然而比嘉已经承认，自己根本就不了解Under World和Fluct Light。确实，他设计、构筑并
让这个世界运转起来了。然而，在那闪着美丽光辉的稀土积层晶体内诞生的世界，达到了
《拉斯》技术人员们从未想象到的高度。

而如今，最了解这个世界的现实世界的人，无疑就是桐之谷和人。不过是十八岁的高中生的
他，在那个世界全力承担、适应、进化，最终显现出了四个超级帐号都未能拥有的强大力量。

这并不是名为桐之谷和人的这个人与生俱来的能力。

他一开始就将被《拉斯》的所有工作人员仅仅当成实验用程序的人工Fluct Light们视为和
自己一样的人类。作为人类，和他们接触，战斗，守护他们，也爱着他们。

所以，Under World及生活在那个世界的所有人选择了他。作为一个守护者的他。

如果是这样，在比嘉等人所想象不到的某种奇迹之下，他能够承受两百年的时间流的可能性
也是存在的。

——是这样的吧，桐人君。

——我现在明白了，为什么菊冈中校需要你的帮助到了那等地步。而且，从现在开始，你也
是必要的存在吧。

——所以……

「……拜托了，回到这个世界吧。」

自言自语着的比嘉，紧紧盯视着显示器上进行到只剩最后几个百分点的关机处理过程。

只有凛子一个人留在副控制室。

其他人都为了救助菊冈中校和恢复对主控制室的控制权而抢先跑了出去。

凛子其实很想跑到安放核动力炉的房间，保护应该倒在监控摄像头范围之外的试作二号机和
还留在它的物理内存内的茅场晶彦的复制体。然而，现在还不是可以离开的场合。在比嘉完
成STL关机处理之后，必须去确认还在隔壁沉睡着的桐之谷和人和结城明日奈的状态。

凛子相信，他们两人会平安无事地醒来的。

想要让他们握住爱丽丝的Light-Cube，说出「是你们保护了她」的话。

恐怕在到楼下去的技术人员们处理几分钟后，《极限加速阶段》就会结束，Under World的
时间流速会回到等速率吧。想要向二人传达那个意志和存在守护了那个世界的话——过去曾
将他们囚禁，让他们战斗并在其中受尽痛苦的那个男人，驱动着电源被切断了的机械身体，
保护了Under World和〈海龟〉。

她不想请求他们原谅他。

杀死了两万个年轻人的茅场晶彦的罪，不论怎样都无法补偿。[fn:24]

然而，无论如何都想让和人和明日奈理解茅场留下的想法和目标。

凛子用渗着血的手掌捧着爱丽丝的Light-Cube封装，闭上眼睛的时候，耳边的对讲机里传来
比嘉微弱的声音：

「……凛子小姐，两位的注销处理完成还剩六十秒了！！」

「明白了。马上会让人去迎接他们的。」

「拜托你了。果然我一个人还是没法从梯子爬上去啊……而且，菊先生好像去下面看情况了，
他怎么样了？好像他也受伤了啊……」

凛子没有立刻回答。距离中西上尉前去救助在通向核动力炉的通道里和敌兵互相射击，之后
倒下的菊冈中校已经过了三四分钟，但现在还没传来消息。

然而，菊冈会是为了这个目的而死掉的人吗。那个一直带着轻浮而深不见底的态度的，在幕
后回转自如的男人会这样做吗。

「……嗯，中校可是相当活跃呢。简直就像是好莱坞的动作演员一样。」

「嘿，还真不像他啊……还剩三十秒了。」

「那么我去STL室吧。如果有什么状况再联络。就这样。」

凛子挂断通话，双手轻轻捧着黑色的金属立方体，离开控制台走向隔壁的房间。

在她碰到房门之前，室内的扬声器里传来了楼下工作人员的声音。

既不是中西上尉，也不是赶赴主控制室的技术人员。是为了以防万一，赶往温度开始下降的
核动力炉安放室拆除塑胶炸弹本体的警备人员的声音：

「这里是发动机室！博士……听得到吗，神代博士！」

凛子抑制住砰砰的心跳，切换对讲机的线路喊道：

「嗯，听得到！怎么了！？」

「那，那个……炸弹平安取下来了，但是那个……不在。」

「不在……是，什么不在……？」

「二号机不在。不论在发动机的哪个地方，都找不到试作二号机的躯体！」

便宜的数字表上设定的倒计时，已经到达了零。

跪在强袭登陆用小型潜水艇的座舱里，听着外部声纳的克里特，在确认过了好几秒后仍然没
有理应听到的爆炸声后，吐出了颤抖的气息。

他自己也不明白，这是安心，还是失望。

唯一能确认的，就是安放在〈海龟〉的核动力炉上的C4炸弹因为某个原因而没有爆炸，因此
控制棒驱动装置未被破坏，核反应炉没有发生炉心融解。

如果留在核动力炉那边的汉斯没事的话，大概会手动炸掉吧。但似乎那个男人也被除掉了。

应该只以前为目的的佣兵，却在绝对会死的情况下没有脱离，实在让人意外。汉斯从知道他
的搭档布利各死掉的时候开始样子就很奇怪，总不会是连死地都想和他一样吧。

「……嘛，大概有很多事情吧……」

摘下声纳耳机的克里特自言自语着。

没错，在汉斯他们之前死掉的米勒队长和瓦萨戈，除了钱大概也有各种事情吧。正是这种障
碍，杀死了他们。

要是这么说的话，克里特和潜水艇上其他的其他队员，也被作战以完全失败告终这一相当巨
大的障碍逼迫着。被身为他们所有人的雇主的民间警备公司——实际上是美国军工企业雇佣
的处理违法事件的公司抛弃掉也不过是瞬间的事情吧。恐怕在他们回到本土的那一瞬间，所
有人被灭口的可能性也不是不存在。

克里特透过衣服，轻轻抚摸着内口袋里作为保护自己的保险而从〈海龟〉偷偷拿出的一枚软
盘。[fn:25]

靠这个东西到底能与他们对抗到怎样的程度呢——但至少，被杀的时候大概还是会被爆头，
所以相比瓦萨戈和米勒中尉那吓人的死法还是好的多了。

「真是的……」

克里特鸣了下鼻子，眺望着逐渐接近的显示海狼级核潜艇《吉米·卡特》所在位置的光点。

从《极限加速阶段》开始的，十九分四十秒后——

设置在〈海龟〉第二STL室的两台Soul Translator的关机处理终于完成了。之后又过了三分
钟，时间加速也被解除，冷却系统减速，船内恢复了静寂。

经神代凛子博士之手从机器里解放出来的两位少年和少女，桐之谷和人和结城明日奈——

却仍然没有醒来的迹象。

Fluct Light的活性降低到了极限，基于灵魂的精神活动很明显已经接近消失。

博士握着二人的手，流着泪，拼命地呼唤着他们。

深深沉睡着的和人和明日奈的嘴边，露出了淡淡的微笑。

** 81

叩。

……叩。

声音在我的眼前停下。

之后，有什么人，呼唤了我的名字。

「……桐人君。」

安稳、清澈而慈爱的声音在空气中响起。

「还是一点没变呢，一个人的时候就变成爱哭鬼了……我早就知道你是这样了……什么嘛。」

我慢慢抬起被眼泪沾湿的脸。

两手绕在背后，头稍微歪着的亚丝娜，带着微笑站在那里。

不知道该说什么才好。所以我就这样，一直注视着亚丝娜的脸，以及那怀念的榛色眼睛。

风从旁边安稳地吹过，空中飞舞的蝴蝶从我们中间穿过，消失在蓝天中。

目送它们离去的亚丝娜，转过视线向我伸出右手。

如果碰到的话，大概就会如同幻影一般消失吧。

不，怎么可能会这样。

亚丝娜也明白的。这个世界马上就要被关闭了。再次回到现实世界的话，大概要在那无限流
动的时间的另一端了吧。所以，她才留下了。为了我。如果立场反过来的话，我也会做出同
样的选择。

我伸出手，将亚丝娜的小手紧紧握住。

我就这样被她拉起来，重新注视着近处美丽的榛色眼睛。

果然还是什么都说不出来。

然而，大概已经没有说什么的必要了。所以，我只是，将她纤细的身体拉过来紧紧抱住。

将头埋在我胸前的亚丝娜，轻声说道：

「……回到那边的时候，爱丽丝大概会生气吧。」

我在脑内想象了一下那个好胜的黄金骑士，蓝眼睛如同要放出火花一般地叱责我们的场景，
然后露出了微笑。

「没问题的。我们肯定都会记得的。和爱丽丝一起度过的时间，一秒都不会忘掉。」

「……嗯。是啊。爱丽丝……莉兹、克莱因、艾基尔、西莉卡……还有小唯，我们都一直记
得的话就没问题的，对吧。」

我们放开拥抱彼此的手，点了点头，一起看向无人的神殿。

功能已经停止的大理石遗迹，静静地沉睡在世界尽头的柔和日光之下。

回过头，握着彼此的手，我们就这样在铺着石子的小道上前进。

在无数色彩的花朵间，稍微前进了一段后，到达了浮岛的边缘。

湛蓝色的天空之下，是广阔无边的世界。

亚丝娜看着我问道：

「我、我们要在这个世界，度过多长时间呢？」

我稍微沉默了一下，吐出了真相：

「大概最短也要两百年吧。」

「嗯。」

亚丝娜点点头，露出和过去一样的笑容：

「只要和你在一起，就算一千年也一点都不长……来，出发吧，桐人君。」

「……啊。走吧，亚丝娜。要做的事情还有好多……这个世界，才刚刚诞生呢。」

我们拉着手，张开双翼，向着无限的青空踏出最初的一步。

（第八章 终）

（第八章整体未完）

#+begin_src text
︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵︵
更多小说欢迎添加【QQ群】：239789013
打开支付宝首页搜 531912956 领红包，最高99元
每天可以领一个，领到大红包的小伙伴赶紧使用哦！
本作品来自互联网及出版图书，
版权归原作者所有，如喜欢请购买正版。
︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶︶
#+end_src

* Footnotes

[fn:25]【rkl：这泥马，都2016年了居然还用diskette（软盘）！】 
[fn:24]【rkl：这里怎么回事？我记得Web版也就死了一万人，这里怎么又变成两万了？川
原你不能这么手滑……】

[fn:23]【rkl：没想到，这么一段剧情，能比桐人一刀秒三万人和对加百列的16连击更让我
燃起来……而且这两人肯定是一辈子的好机油……】
[fn:22]【rkl：你们有这个废话功夫还不快去拆炸弹……】 

[fn:21]【rkl：所以我都说了，AW里的心意技什么的都弱爆了……】 
[fn:20]【rkl：总觉得这就是Chrome Disaster(Silver Crow version)的Laser Lance的高
级版……】

[fn:19]【rkl：川原你这是手滑吧，前面还是右臂被折，这里怎么变成左臂了……】 
[fn:18]【rkl：其实那段咚，咚咚咚咚在翻译的时候不由自主地想起了Intel的广告……我自重。】 

[fn:17]【rkl：实际上在这里吐槽我总觉得不合适，但Under World里连动物都有伦理限制系统（众
人：我们都知道你往破坏伦理的方向去想了。）】 
[fn:16]【rkl：这次中枪的是DOTA……】 

[fn:15]【rkl：kirito的方针就是，敢动我妹子的统统去死……】 
[fn:14]【rkl：这句话的吐槽点，就是在神的面前乱发誓……你真的不怕被天罚么……】 

[fn:13]【rkl：你看看你，你看看你……就算女儿不在，你这推土机的黑历史不是照样被曝
光了么……】
[fn:12]【rkl：噗……】 

[fn:11]【acadsh注：根据37节的描述，沙斯特是长而浓密的美髯，没隔几天就换胡子了啊
OTL。】
[fn:10]【acadsh注：剑道里把刀高举过头的架势，比上段更强势。】 

[fn:9]【acadsh注：Destruct at the last stage】\\
【rkl：翻译过来即为『将于最终阶段毁坏』。其实Under World的这些语句都是很容易懂的
英语……】
[fn:8]【acadsh注：也许Under World的文明还没把草木归入生物吧】

[fn:7]【acadsh注：古罗马人穿的半椭圆形的袍】
[fn:6]【acadsh注：山吹是蔷薇科的落叶矮木。按中国人的叫法就是屎黄色OTL。所以这里还是用
回日语汉字比较雅观】 

[fn:5]【acadsh注：听佛法而感到的喜悦】
[fn:4]【Obsidia，rkl注：语源应该是Obsidian-黑曜石】

[fn:3]【acadsh注：德克萨斯州的一个郡】
[fn:2]【acadsh注：原文为非洲，加百列出生于美国北卡罗莱纳州，这里估计是作者笔误】

[fn:1]【acadsh注：源自所罗门七十二柱魔神的第三位魔神，统帅26个军团的王子，司掌苦
行和休息】
