#+TITLE: 关于
#+setupfile: ./setup.setup

* 我想说的
这是我的个人网站，依靠Emacs Org导出为HTML构建

注意，是近纯Emacs，除了使用Emacs和简单的shell脚本之外并没有使用任何其他的软件或
者博客引擎用于构建博客。虽然如此，但我还是觉得我这博客还是“不太纯”，毕竟Shell
的占比也太多了（指开发时间）。

使用样式为由Org官方网页的样式文件修改而来的样式文件。修改部分配色，增加部分样式
规定。

曾经使用过的主题：
+[[https://github.com/yzs249175311/org-html-theme-dull][org-html-theme-dull]] read-the-docs+ （不过它们的文件未有删除）

#+begin_quote
注：这两个主题均会使用其他的字体（来自网络），特别是 =read-the-docs= 这个主题的
加载时间会非常的长（有的网址无法访问）。
#+end_quote
* 一些小介绍
** 源文件的获取
这个网站实际上已经在 /2023.05.14/ 的更新中将源文件合并进了。理论上你能够访问的
html文件你也能够访问相应的Org源文件。就例如本页（首页）的[[http:/about.org][源文件]]。我应该不会再添
加一个源文件的下载列表，所以若想要源文件请自行将 =xxx.html= 改成 =xxx.org= 的格
式以获取源文件。
** 关于草稿的问题
由于脚本尚不完善，所以有很多的草稿文章（或者是烂尾文）会跟着一起发出来，所以请不
要在意，友好地关掉链接即可。
** 关于返回主页
两款主题均没有改动 =Up= 与 =Home= 的链接。在部分文章中 =Up= 链接是有定义的，不过
大多是没有定义链接目标的所以一般会回到文章页面中。而 =Home= 链接则是有定义的，均
为主页。所以如果想要返回主页，使用 =Home= 即可。
** 关于本地构建
由于网页对于 =/= 链接的较广泛使用，在将Github仓库克隆到本地后是无法直接访问的，
需要使用nodejs的http-server工具开启一个服务或者使用nginx配置一下本地服务（我用的
是nginx）
** 关于右下（或左下角）的信息
那些信息部分由Org文档指定，部分由Emacs自动生成。其中 =Date= 一般为文章的创建时间，
而 =Created= 则为Html文件的生成时间。一般可以用于参考文章的最后更新时间，不过有
时网站做出一些调整更新所有的文章时，它就会更新。所以仅作参考，也有部分内容是虚标
的。
