#+TITLE: 我的个人博客
# #+OPTIONS: toc:nil
# #+OPTIONS: num:nil

#+setupfile: ./setup.setup

* 文章
- 关于建站
  - [[./关于建站/使用github.io建立自己的博客.html][使用github.io建立自己的博客 - hexo+hugo+Emacs Org]]
    分别使用Hexo、Hugo、Emacs Org建立自己的博客。
  - [[./关于建站/用github.io建立一个自己的博客网站.html][用github.io建立一个自己的博客网站 - 仅Jekyll]]
    使用github.io和jekyll建立一个自己的博客网站
- 其他
  - 小说
    - [[./其他/小说/SAO/][《刀剑神域》资源索引]]
      由于资源有点多所以做了个分页作索引
- 学习笔记
  - 语文
    - [[./学习笔记/语文/语文笔记.html][语文笔记]]
  - 道法
    - [[./学习笔记/道法/八下早读材料.html][八下早读材料]]
  - C语言学习
    - [[./学习笔记/C语言学习/打印字符使用特殊效果.html][打印字符使用特殊效果]]
      使用ANSI转义字符实现终端输出字符带有特殊效果
    - [[./学习笔记/C语言学习/一些奇妙的编程思想.html][一些奇妙的编程思想]]
      一些我在学编程中用到的思想，或许有用，或许没用
- 一些工具
  - [[./一些工具/我用的小工具盘点.html][我用的小工具盘点]]
    记录一些Linux中有趣但不一定常用的软件
  - Emacs
    - [[./一些工具/Emacs/Emacs学习笔记.html][Emacs学习笔记]]
      我自己尝试写的Emacs入门教程，不喜勿喷，持续更新中
    - [[./一些工具/Emacs/从vim转移到emacs.html][从vim转移到emacs]]
      单纯的口水文
  - Vim
    - [[./一些工具/Vim/使用Vim.html][使用Vim]]
- ArchLinux学习系列
  - [[./ArchLinux学习系列/Archiso——打造属于你的在U盘上的Archlinux Live系统.html][Archiso——打造属于你的在U盘上的Archlinux Live系统]]
    如何使用archiso工具打造一个自定义的U盘上的临时Live系统
  - [[./ArchLinux学习系列/ArchLinux的安装.html][ArchLinux的安装]]
    记录我个人安装archlinux的过程
  - [[./ArchLinux学习系列/ArchLinux的配置.html][ArchLinux的配置]]
    记录我个人的archlinux软件配置

这里放点东西来垫下底。
* 关于
这是我的个人网站，依靠Emacs Org导出为HTML构建

注意，是纯Emacs，没有任何其他的软件或者博客引擎。

使用主题有两个：
[[https://github.com/yzs249175311/org-html-theme-dull][org-html-theme-dull]] read-the-docs

这两个主题均已内置，非外链。

* 目录索引
#+begin_src text
  public/
  ├── 404.html
  ├── 关于建站
  │   ├── 2022-08-04_01
  │   │   ├── 2022-07-02_01-01.png
  │   │   ├── 2022-07-02_01-02.png
  │   │   ├── 2022-07-02_01-03.png
  │   │   ├── 2022-08-05_01-04.png
  │   │   └── 2022-08-05_01-05.png
  │   └── 用github.io建立一个自己的博客网站.html
  ├── 其他
  │   └── 小说
  │       └── SAO
  │           ├── 刀剑神域_文库版_全集.html
  │           ├── 刀剑神域_文库版_全集.pdf
  │           ├── 刀剑神域_文库版_全集.tex
  │           ├── 刀剑神域_文库版_全集.txt
  │           ├── 刀剑神域小说1-18卷
  │           │   ├── （萌动王朝）刀剑神域01 艾恩葛朗特.html
  │           │   ├── （萌动王朝）刀剑神域01 艾恩葛朗特.pdf
  │           │   ├── （萌动王朝）刀剑神域01 艾恩葛朗特.tex
  │           │   ├── （萌动王朝）刀剑神域01 艾恩葛朗特.txt
  │           │   ├── （萌动王朝）刀剑神域02 艾恩葛朗特.txt
  │           │   ├── （萌动王朝）刀剑神域03 妖精之舞 上.txt
  │           │   ├── （萌动王朝）刀剑神域04 妖精之舞 下.txt
  │           │   ├── （萌动王朝）刀剑神域05 幽灵子弹 上.txt
  │           │   ├── （萌动王朝）刀剑神域06 幽灵子弹 下.txt
  │           │   ├── （萌动王朝）刀剑神域07 圣母圣咏.txt
  │           │   ├── （萌动王朝）刀剑神域08 Early and Late.txt
  │           │   ├── （萌动王朝）刀剑神域09 Alicization篇（1）.txt
  │           │   ├── （萌动王朝）刀剑神域10 Alicization篇（2）.txt
  │           │   ├── （萌动王朝）刀剑神域11 Alicization篇（3）.txt
  │           │   ├── （萌动王朝）刀剑神域12 Alicization篇（4）.txt
  │           │   ├── （萌动王朝）刀剑神域13 Alicization篇（5）.txt
  │           │   ├── （萌动王朝）刀剑神域14 Alicization篇（6）.txt
  │           │   ├── （萌动王朝）刀剑神域15 Alicization篇（7）.txt
  │           │   ├── （萌动王朝）刀剑神域16 Alicization篇（8）.txt
  │           │   ├── （萌动王朝）刀剑神域17 Alicization篇（9）.txt
  │           │   └── （萌动王朝）刀剑神域18 Alicization篇（10）.txt
  │           ├── 刀剑神域WEB版+外传、特典
  │           │   ├── Sword Art Online 03 The Dead Gun.txt
  │           │   ├── Sword Art Online 刀剑神域 BD特典 短篇.txt
  │           │   ├── Sword Art Online 访谈录.txt
  │           │   ├── Sword Art Online 圣剑篇（攻略成功）.txt
  │           │   ├── Sword Art Online 圣剑篇SS（攻略失败）.txt
  │           │   ├── Sword Art Online 水之音 锤之音.txt
  │           │   ├── Sword Art Online 唯一的究极手段.txt
  │           │   ├── Sword Art Online 在冬天的阳光下.txt
  │           │   ├── Sword Art Online WEB版 Alicization篇主线
  │           │   │   ├── Sword Art Online WEB版 第1章.txt
  │           │   │   ├── Sword Art Online WEB版 第2章.txt
  │           │   │   ├── Sword Art Online WEB版 第3章.txt
  │           │   │   ├── Sword Art Online WEB版 第4章.txt
  │           │   │   ├── Sword Art Online WEB版 第5章.txt
  │           │   │   ├── Sword Art Online WEB版 第6章.txt
  │           │   │   ├── Sword Art Online WEB版 第7章.txt
  │           │   │   ├── Sword Art Online WEB版 第8章.txt
  │           │   │   └── Sword Art Online WEB版 终章.txt
  │           │   ├── Sword Art Online WEB EX版外传
  │           │   │   ├── Sword Art Online EX01 黑色剑士.txt
  │           │   │   ├── Sword Art Online EX02 Four Days.txt
  │           │   │   ├── Sword Art Online EX03 心之温度.txt
  │           │   │   ├── Sword Art Online EX04 绝剑.txt
  │           │   │   ├── Sword Art Online EX05 圈内事件.txt
  │           │   │   ├── Sword Art Online EX06 红鼻子麋鹿.txt
  │           │   │   └── Sword Art Online EX07 月之摇篮.txt
  │           │   └── Sword Art Online WEB ME版（素材版）
  │           │       ├── Sword Art Online ME02 Early Characters.txt
  │           │       ├── Sword Art Online ME03 Ceramic Heart.txt
  │           │       ├── Sword Art Online ME04 Cold hand，Warm heart.txt
  │           │       ├── Sword Art Online ME05 鼠尾草.txt
  │           │       ├── Sword Art Online ME06 阿尔格特的决斗.txt
  │           │       ├── Sword Art Online ME07 无星夜的咏叹调.txt
  │           │       ├── Sword Art Online ME07 续-无星夜的咏叹调.txt
  │           │       ├── Sword Art Online ME08 胧幻剑的圆舞曲.txt
  │           │       └── Sword Art Online ME09 黑与白的协奏曲（第1章 未完）.txt
  │           └── index.html
  ├── 学习笔记
  │   ├── 道法
  │   │   ├── 八下早读材料
  │   │   │   ├── 八下早读材料.pdf
  │   │   │   └── 八下早读材料.tex
  │   │   └── 八下早读材料.html
  │   ├── 语文
  │   │   ├── 语文笔记
  │   │   │   ├── 语文笔记.info
  │   │   │   ├── 语文笔记.man
  │   │   │   ├── 语文笔记.pdf
  │   │   │   ├── 语文笔记.txt
  │   │   │   └── 语文笔记_typora.pdf
  │   │   └── 语文笔记.html
  │   └── C语言学习
  │       ├── 打印字符使用特殊效果
  │       │   ├── out1.png
  │       │   ├── out2.png
  │       │   ├── out3.html
  │       │   └── out3.png
  │       ├── 打印字符使用特殊效果.html
  │       └── 一些奇妙的编程思想.html
  ├── 一些工具
  │   ├── 我用的小工具盘点.html
  │   ├── Emacs
  │   │   ├── 2023-01-16_01
  │   │   │   ├── 2023-01-16_01-01.png
  │   │   │   └── 2023-01-16_01-02.png
  │   │   ├── 从vim转移到emacs.html
  │   │   ├── Emacs学习笔记
  │   │   │   ├── 01.png
  │   │   │   ├── 02.png
  │   │   │   ├── 03.png
  │   │   │   └── 04.png
  │   │   └── Emacs学习笔记.html
  │   ├── tools
  │   │   ├── ccal
  │   │   │   ├── 11.ps
  │   │   │   ├── 12.ps
  │   │   │   └── 2022.ps
  │   │   └── img
  │   │       ├── 2022-12-02_01-01.png
  │   │       ├── 2022-12-02_01-02.png
  │   │       └── 2022-12-02_01-03.png
  │   └── Vim
  │       ├── 2022-07-08_01
  │       │   └── 2022-07-08_01-01.png
  │       └── 使用Vim.html
  ├── ArchLinux学习系列
  │   ├── 2022-07-02_02
  │   │   ├── 2022-07-02_02-01.png
  │   │   ├── 2022-07-02_02-02.png
  │   │   ├── 2022-07-02_02-03.png
  │   │   ├── 2022-07-02_02-04.png
  │   │   ├── 2022-07-02_02-05.png
  │   │   ├── 2022-07-02_02-06.png
  │   │   ├── 2022-07-02_02-07.png
  │   │   ├── 2022-07-02_02-08.webm
  │   │   └── archlinux.png
  │   ├── 2022-07-03_01
  │   │   └── 2022-07-03_01-01.png
  │   ├── Archiso——打造属于你的在U盘上的Archlinux Live系统.html
  │   ├── ArchLinux的安装.html
  │   └── ArchLinux的配置.html
  ├── img
  │   ├── background.jpg
  │   └── icon.jpg
  ├── index.html
  └── theme
      ├── org-html-theme-dull.css
      ├── org-html-theme-dull.js
      └── read_the_docs
          ├── bootstrap.min.js
          ├── css
          │   ├── htmlize.css
          │   ├── readtheorg.css
          │   └── rtd-full.css
          ├── jquery.min.js
          ├── js
          │   ├── jquery.stickytableheaders.min.js
          │   ├── readtheorg.js
          │   └── stickytableheaders-license.txt
          ├── readtheorg.org
          └── theme-local.setup

  35 directories, 126 files
#+end_src
