.TH "语文笔记" "1" 
.PP
关于语文的阅读理解教学视频笔记,
内容来源于B站UP: https://space.bilibili.com/316069678 \fBat\fP \fI梓墨说语文\fP

.SH "写作手法（表达技巧）"
.SS "修辞手法（10个）"
.PP
一共有６３大类，７９小类
.SS "种类/类型"
.RS
.TP
.ft I
比喻
.ft
.IP \(em 4
定义： 把XX比作XX，让句子、描写的对象更加 \fI生动形象/活泼具体\fP
.IP \(em 4
分类： 明喻、暗喻、借喻
.RE
.TP
.ft I
拟人
.ft
.IP \(em 4
定义： 把XX拟人化/赋予XX人类的动作、情感，让描写对象 \fI生动形象具体\fP
.RE
.TP
.ft I
夸张
.ft
.IP \(em 4
作用： \fB\fI突出,强调\fP 作用\fP
.IP \(em 4
分类：
.IP \(em 4
扩大夸张： 对事物形状、性质、特征、作用等加以夸大（空间）
.IP \(em 4
缩小夸张： 对事物形状、性质、特征、作用等加以缩小（空间）
.IP \(em 4
超前夸张： 把后出现的说成先出现，反之亦然（时间）
.IP \(em 4
例句： 她还没有碰酒杯，就醉了
.RE
.TP
.ft I
排比（３个以上）
.ft
.IP \(em 4
特点： 内容相关，结构相同或相近
.IP \(em 4
作用： \fB\fI突出,强调\fP ，韵律美\fP
.RE
.TP
.ft I
反复（２个以上）
.ft
.IP \(em 4
定义： 一个句子、词语反复出现（不同于排比，但可以与排比结合来用）
.IP \(em 4
作用： \fB\fI突出,强调\fP ，韵律美\fP
.RE
.TP
.ft I
对偶
.ft
.IP \(em 4
定义： 字数相等， \fI结构相同，意义对称\fP 的一对 \fB短语\fP 或 \fB句子\fP ，表达两个意思相近或相反的修辞方式
.IP \(em 4
作用： 更 \fI具文采\fP ，具有 \fI韵律美\fP
.RE
.TP
.ft I
反问
.ft
.IP \(em 4
定义： 借助疑问句传达确定信息
.IP \(em 4
作用： \fB加强语气，突出____情感\fP
.IP \(em 4
答题： 反问可以
.br
\fI加强语气\fP , \fI发人深思\fP, \fI激发读者感情,\fP
\fI加深读者印象\fP, \fI增强文章的气势和说服力\fP,  
.br
为文章 \fI奠定一种激昂的感情基调\fP.
.RE
.TP
.ft I
设问
.ft
.IP \(em 4
本质： 自问自答
.IP \(em 4
作用： \fB引人注意，启发思考\fP
.RE
.TP
.ft I
反语
.ft
.IP \(em 4
定义： 正话反说（褒词贬用）或反话正说
.IP \(em 4
作用： \fB突出\fP 语气、情感，常带有讽刺意味， \fB产生讽刺性\fP （有时比正说更有力量）
.RE
.TP
.ft I
引用
.ft
.IP \(em 4
定义： 说话或写作中引用现成的话
.IP \(em 4
作用： 使论据确凿，增强说服力，是文章富有文采
.RE
.TP
.ft I
借代
.ft
.IP \(em 4
定义： 用同对象相关的东西代替对象（称呼），如结构部分、颜色特征
.IP \(em 4
作用： 以简代繁，语句精简
.RE
.TP
.ft I
互文
.ft
.IP \(em 4
定义： 属于一句（或短语）的意思写入两句话，解释时要上下句意思互补
.IP \(em 4
例句： （均选自《木兰诗》）
.IP 1.  4
原句： \fI东市买骏马，西市买鞍鞯，南市买辔头，北市买长鞭\fP 
.br
翻译： 东南西北市买　骏马、鞍鞯、辔头、长鞭

.IP 2.  4
原句： \fI开我东阁门，坐我西阁床，当窗理云鬓，对镜贴花黄\fP 
.br
翻译： 开东西阁的门，坐东西阁的床，当窗对镜理云鬓、贴花黄
.RE
.SS "小结/速查表"
.TS
 center,box;

c l .
名称	定义/作用
_
比喻	把XX比作XX，让句子、描写的对象更加 \fI生动形象/活泼具体\fP
拟人	把XX拟人化/赋予XX人类的动作、情感，让描写对象 \fI生动形象具体\fP
排比（３个以上）	\fI突出,强调\fP 韵律美
反复（２个以上）	\fI突出,强调\fP 韵律美
夸张	\fI突出,强调\fP
反问	加强语气，突出____情感
设问	引人注意，启发思考
反语	突出,产生讽刺性
对偶	更具文采,具有 韵律美
引用	使论据确凿，增强说服力，是文章富有文采
借代	以简代繁，语句精简
互文	属于一句（或短语）的意思写入两句话，解释时要上下句意思互补
\fI通感\fP	将不同的感觉交叉描写（笑（看的）~>甜（闻的））
\fI双关\fP	一句话表示双重意思
\fI顶针\fP	类似词语接龙，上词末字接下词首字
\fI回环\fP	一句话正读反读意思一样
\fI拈连\fP	将甲物特征形容乙事物
\fI拟物\fP	人当物写
\fI呼告\fP	直呼文中事物
\fI跳脱\fP	语言因特殊情景半路断开了语路
.TE
.TB ""

.RS
注： \fI名称\fP 为斜体的为表中独有的，比较少见，所以仅在表中列出

.RE

.SS "表达方式（5个）"
.SS "拆分理解"
.IP \(em 4
表达： （用文字）说话
.IP \(em 4
表达方式： 用文字说话的方式
.SS "种类/类型"
.RS
.TP
.ft I
记叙
.ft
.IP \(em 4
代表： 记叙文
.IP \(em 4
六要素： 时间、地点、人物、事件（起因、经过（、高潮）、结果）
.IP \(em 4
记叙顺序
.IP \(em 4
顺序： 按照事件发展（或时间）为序
.IP \(em 4
倒叙： 先结果后起因经过
.IP \(em 4
插叙： 叙述中途插入另一相关内容（背景类之）
.IP \(em 4
补叙： 叙述后（文末）补充说明相关、关键内容。
.IP \(em 4
分类
.IP \(em 4
写人：
.IP \(em 4
特征： 重点在写人的故事（塑造人物形象、精神特征），（重点）突出其内在特征
.IP \(em 4
作用： 表达作者情感（赞美、歌颂、怀念、祝福）
.IP \(em 4
写事：
.IP \(em 4
特征： 叙述一件事，传达出作者要表达的情感（常为赞美、喜爱等正能量情感）
.IP \(em 4
写景：
.IP \(em 4
特征： 重点写景（一切景语皆情语）
.IP \(em 4
作用： 烘托、透露、表达出作者的情感（寓情于景、借景抒情）（对大自然的喜爱、赞美，作者的心情愉悦、下定什么决心）
.IP \(em 4
状物：
.IP \(em 4
特征： 写一个物品，但目的是写人
.IP \(em 4
作用： 借物喻人，象征、托物言志
.IP \(em 4
人称
.IP \(em 4
第一人称：便于直抒胸臆，有亲切感与真实感
.IP \(em 4
第二人称：增强文章的抒情性和亲切感，像与读者面对面交谈，便于抒情
.IP \(em 4
第三人称：不受时空限制，能够从多个方面自由叙述（客观、全面）
.RE
.TP
.ft I
描写
.ft
.IP \(em 4
代表： 小说
.IP \(em 4
定义： 用文字描绘、描述、描摹出某物的特征
.IP \(em 4
按照对象分类
.IP \(em 4
人物描写 （外语动神心）
.IP \(em 4
外貌描写（肖像描写）
.IP \(em 4
语言描写
.IP \(em 4
动作描写 答题：动词（用词） \fI\fB准确\fP\fP ,生动,形象,具体
.IP \(em 4
神态描写 例如：XX的心情
.IP \(em 4
心理描写 例如：XXX的心理活动->人格
.IP \(em 4
环境描写（依靠是否有人为因素作为依据区分）
.IP \(em 4
自然环境
.IP \(em 4
社会环境
.IP \(em 4
按照描写角度分类
.IP \(em 4
正面描写（直接描写）
.IP \(em 4
侧面描写（间接描写）
.IP \(em 4
描写方法（动静动静动动静）
.IP \(em 4
动静结合
.IP \(em 4
化静为动
.IP \(em 4
化动为静
.IP \(em 4
以动衬静
.IP \(em 4
以静衬动
.IP \(em 4
小说：以描写、记叙为主的文体
.IP \(em 4
三要素：人物、情节（开端、发展、高潮、结局）（讲故事）、环境
.RE
.TP
.ft I
抒情
.ft
.IP \(em 4
代表： 散文
.IP \(em 4
定义： 直接、间接（表达）抒发（自身）情感的表达方式
.IP \(em 4
分类
.IP \(em 4
直接抒情：直接表白倾吐自己的思想情感
.IP \(em 4
间接抒情：不直接表露自己的情感，借助第三者来抒发自己的情感
.IP \(em 4
借景抒情
.IP \(em 4
借物抒情
.IP \(em 4
融情于事：通过叙述实际抒发感情
.IP \(em 4
融情于理：把情感寄寓在说理之中，理中含情
.IP \(em 4
散文：抒发作者真情实感、写作方式灵活的 \fI记叙类\fP 文字体裁
.IP \(em 4
特点
.IP \(em 4
形散神不散
.IP \(em 4
形散：选材广泛
.IP \(em 4
神不散：中心思想突出（主题明确集中）
.IP \(em 4
语言优美（多读散文提高写作文字的优美）
.IP \(em 4
意境深邃
.IP \(em 4
分类
.IP \(em 4
叙事类散文：叙事不要求完整（鲁迅《从百草园到三味书屋》）
.IP \(em 4
抒情散文：抒情强烈（茅盾《白杨礼赞》）
.IP \(em 4
哲理散文：讲哲理
.RE
.TP
.ft I
说明
.ft
.IP \(em 4
代表： 说明文
.IP \(em 4
概念：介绍与解释
.IP \(em 4
分类（按对象分）
.IP \(em 4
事物说明文（看得见）（《苏州园林》）
.IP \(em 4
事理说明文（看不见）
.IP \(em 4
分类（按说明语言分）
.IP \(em 4
生动说明文：用比较形象的手法说明事物（生动性、形象性）（《昆虫记》）
.IP \(em 4
方法：修辞手法、现身说法、运用适当的叙事和描写
.IP \(em 4
平实说明文：直截了当，不加描写与夸张
.IP \(em 4
说明顺序
.IP \(em 4
时间顺序：事理发展过程先后为序（适用于事物说明文）
.IP \(em 4
空间顺序：事物空间结构为序（同上）
.IP \(em 4
逻辑顺序：事物事理内在逻辑关系为序（个别到一般、具体到抽象、主要到次要、现象到本质、原因到结果）（适用性广）
.IP \(em 4
语言特点： \fI准确性（基础）\fP  \fI严密性\fP \fI生动性\fP \fI平实性\fP
.IP \(em 4
说明方法： \fI举例子\fP \fI分类别\fP \fI打比方\fP \fI作比较\fP \fI下定义\fP
\fI作诠释\fP \fI作引用\fP \fI画图表\fP \fI列数字\fP \fI摹状貌\fP
.RE
.TP
.ft I
议论
.ft
.IP \(em 4
代表： 议论文
.IP \(em 4
定义： 发表意见、评价、观点、讲道理、提出主张
.IP \(em 4
分类：
.IP \(em 4
立论文：提出观点看法并证明
.IP \(em 4
驳论文：反驳别人观点错误并提出证明自己观点的正确性
.IP \(em 4
议论文三要素： 论点（观点）、论据（论证的根据、证据）、论证（用论据证明论点的过程、方法）
.IP \(em 4
语言特点： 同说明文
.RE
.SS "小结"
.TS
 center,box;

l l .
名字	思维导图
_
记叙（记叙文）	\fIfile:///img/2023-01-08_01/14_mpv-shot0002.jpg\fP
描写（小说）	\fIfile:///img/2023-01-08_01/14_mpv-shot0003.jpg\fP
抒情（散文）	\fIfile:///img/2023-01-08_01/14_mpv-shot0004.jpg\fP
说明（说明文）	\fIfile:///img/2023-01-08_01/14_mpv-shot0005.jpg\fP
议论（议论文）	\fIfile:///img/2023-01-08_01/14_mpv-shot0006.jpg\fP
总体思维导图	\fIfile:///img/2023-01-08_01/14_mpv-shot0001.jpg\fP
.TE
.TB ""
.SS "表现手法（15个）"
.SS "定义"
.IP \(em 4
广义： 约等于 \fI写作手法/表达技巧\fP
.IP \(em 4
狭义： 让故事更加精彩的方法(写作方法)
.SS "做题思维"
.PP
看到 \fI“XXX有什么作用”\fP 就要联想到 \fI表现手法\fP
.SS "种类"
.RS
.TP
.ft I
对比
.ft
.IP \(em 4
起突出强调作用
.IP \(em 4
把 \fI对立的\fP 意思或事物的两个方面放在一起作比较，
让读者分清好坏、辨别是非
.IP \(em 4
\fI平等\fP 的比较（无主次之分，共同突出）（以主比主）
.RE
.TP
.ft I
衬托
.ft
.IP \(em 4
为了 \fI突出主要事物\fP ，用类似的 \fI次要\fP 事物或
反面的、有差别的 \fI次要\fP 事物作为陪衬。（常用于描写）
.IP \(em 4
分为正衬（同类）（高衬高）和反衬（相反）
.IP \(em 4
\fI不平等\fP 的比较（有主次之分）（以次衬主）
.RE
.TP
.ft I
铺垫
.ft
.IP \(em 4
渲染气氛，让读者产生期待、盼望的急迫心情，增强作品的吸引力
.IP \(em 4
为下文的人物出现做准备，为表现主要写作对象而提前做的基础性描写
.IP \(em 4
主要情节的基石，增加情节张力，制造悬念使情节具有合理性。
（原则：引而不发、自然合理）
.IP \(em 4
答题参考格式：（叙述了）XXX事件，为下文XXXX做铺垫
.RE
.TP
.ft I
伏笔
.ft
.IP \(em 4
交代含蓄，使文章 \fI结构严密、紧凑\fP ，让读者看到下文时，
不至于感到突兀、疑惑。有助于 \fI全文结构严谨、情节发展合情合理\fP 。
.IP \(em 4
上文看似无关紧要的事或物，对下文将要出现的人物或者事件预先作的
\fI某种提示\fP 或 \fI暗示\fP ，或者说是前文为后文情节埋伏的线索。
.IP \(em 4
有伏必有应，只伏不应是败笔
.IP \(em 4
答题参考格式：运用了伏笔，为后文高潮部分埋下了伏笔。
.RE
.TP
.ft I
象征
.ft
.IP \(em 4
定义：
.IP \(em 4
标准：借助物象来表现某种概念、思想、精神、品德等。
.IP \(em 4
通俗：用具体的物，表示无法直接看见的东西（化无形为有形）
.RE
.TP
.ft I
托物言志/借物抒情
.ft
.IP \(em 4
定义：
.IP \(em 4
标准：也称寄意于物，指作者运用象征或起兴等手法，
通过描绘客观上事物的某一个方面的特征
来表达作者情感或揭示作品的主旨
.IP \(em 4
通俗：借助某个物体来表示某种情感、志向
.IP \(em 4
区别：象征是客观层面的（被普遍认同的）文章局部写法，
托物言志是主观层面的文章整体手法，相辅相成。
.IP \(em 4
可被理解为一种间接抒情方式
.RE
.TP
.ft I
欲扬先抑(先抑后扬) & 欲抑先扬(先扬后抑)
.ft
.IP \(em 4
定义：一种人物描写技巧
.IP \(em 4
原因：人“以貌取人”、“表里不一”
.IP \(em 4
作用：能让文章更加精彩
.RE
.TP
.ft I
照应
.ft
.IP \(em 4
定义：前后意思相近或者相反的两个短语句子或者段落称为照应
.IP \(em 4
常见：前后照应，照应标题
.RE
.TP
.ft I
设置悬念
.ft
.IP \(em 4
定义：使读者 \fI产生好奇心\fP ，迫切需要知道后面的内容就是悬念
.IP \(em 4
例如：设置疑问或矛盾冲突
.RE
.TP
.ft I
以小见大
.ft
.IP \(em 4
定义：通过一件小事，反映出一个大道理
.RE
.TP
.ft I
点面结合
.ft
.IP \(em 4
定义：对某个实物或多个事物的详细描写（点）和
多个事物的概括性描写（面）的有机结合
.RE
.TP
.ft I
虚实结合
.ft
.IP \(em 4
定义：存在(实)的和不存在(虚)的都写出来
.RE
.TP
.ft I
联想
.ft
.IP \(em 4
定义：联想是因一事务而想起与之有关事物的思想活动
.RE
.TP
.ft I
想象
.ft
.IP \(em 4
定义：设想（天马行空）
.RE
.SS "总结"
.TS
 center,box;

c l r .
名字	定义/作用	区别
_
对比	同级间的相反性质的对比	同级
衬托	次一级对主角的正反面衬托	异级
铺垫	为下文做准备的基础性描写	无照应
伏笔	提示或暗示（下文有照应）（越共探头）	有照应
象征	化抽象为具体	
托物言志	借事物的象征意义通过写事物去写自己的思想感情和志向	侧重于表达主观情感和志向
欲抑先扬	先赞扬外在，再贬低内在	贬低内在
欲扬先抑	先贬低外在，再赞扬内在	赞扬内在
照应	稳重前后意思相近或相反的短语或者句子互相照应	
设置悬念	使读者产生好奇心，激发读者的阅读兴趣	
以小见大	通过写一件小事物来传达出一个大理念	
点面结合	先用大场面渲染气氛，再专注于一点	
虚实结合	存在与不存在，缺一不可	
联想	由一想到其他	
想象	从蛛丝马迹想到更多，更自由，侧重于天马行空	
.TE
.TB ""

.IP \(em 4
表现手法的主要作用：
.IP \(em 4
使故事更精彩
.IP \(em 4
吸引读者的阅读兴趣

.IP \(em 4
表现手法与修辞手法的区别
.IP \(em 4
表现手法着眼于整篇文章或段落，目的是让文章内容更加精彩
.IP \(em 4
修辞手法着眼于具体字词短语和句子，目的是让句子更具文采，更生动

.SS "结构手法（5个）"
.SS "种类"
.RS
.TP
.ft I
首段
.ft
.RS
.TP
.ft I
引出下文
.ft
.RE
.TP
.ft I
总领全文
.ft
.RE
.RE
.TP
.ft I
中间
.ft
.RS
.TP
.ft I
过渡
.ft
.RE
.TP
.ft I
承上启下
.ft
.RE
.RE
.TP
.ft I
最后段
.ft
.RS
.TP
.ft I
总结全文
.ft
.RE
.RE
.TP
.ft I
线索
.ft
.IP \(em 4
定义：事情可寻的端绪、路径，或贯穿于整篇文章的思路，脉络等。
在写作中，是将所叙述事件按一定事件串联起来的“线”。
.IP \(em 4
分类：人、事、物、时、空（明线）、情（暗线）
.IP \(em 4
作用：贯穿全文，使文章的结构更加严谨
.IP \(em 4
寻找：
.IP 1.  4
了解文章 \fI体裁\fP 和 \fI内容\fP
.IP 2.  4
注意文章的 \fI标题\fP
.IP 3.  4
线索（某个词或事物）有时会从头到尾 \fI反复出现\fP
.IP 4.  4
线索有时在 \fI议论或抒情中\fP
.IP 5.  4
有时文章具备两条线索： \fI明线\fP 和 \fI暗线\fP
.RE
