#+title: Sword Art Online EX07 月之摇篮
#+date: <2025-10-03 六 17:47>
#+setupfile: ../setup.setup
#+description: 讲在UW极限加速时初期UW内部发生的事情(Recomended)
* Sword Art Online EX07 月之摇篮
** Header(后期找补)
#+begin_quote
整理者的话：\\
原本的文件里面已经找不到头部信息了，但是非常幸运地在网上搜索搜到了应该是原本的译
者名单头信息。链接[[https://tieba.baidu.com/p/4979019703#][在这]]。
#+end_quote
#+begin_src text
  ==========================================
  Sword Art Online （19卷）
  EX07 月之摇篮
  Web版
  ==========================================
  作者：川原 礫
  ==========================================
  翻译：rkl(1-13） 义乐（14-37）
  仅供个人学习交流使用
  禁作商业用途 违反者后果自负
  下载后请在24小时内删除
  请尊重翻译者的辛勤劳动
  ==========================================
  译者注释：
  (1)这是web版，故部分细节会与文库版有区别
  (2)全文共13节，未完结(川原没往下写)。
  (3)本文开始时的时间点为Under World人界历三八三年二月(原文并无年份，根据文库本推测得到)，发生于第八章Under World战争结束的两年后(对应现实世界极限加速开始12秒后)。
  （4）本文后期由义乐进行翻译，故可能会出现命名上的差异，如造成误解还请见谅。
  特别警告：本文为刀剑19卷的先行版，故剧情不会有太多差异，不想被剧透的读者请自行无视。
  ==========================================
#+end_src
** 1
排列着白垩圆柱的走廊里，回响着一人和一匹的脚步声。

跑在前面的是有着飘在空中的略长的黑发，穿着灰色的轻铠甲，腰间挂着细剑的少女。一只
全身包裹着淡黄色皮毛的幼龙摇着长长的尾巴紧紧追在少女后面。尚未生角的龙头比少女还
要高那么一点。

少女名为萝涅·阿拉贝尔。幼龙名为月驱。

这如同童话般美丽到让人微笑的场景，使人完全无法想象这一对搭档数年后会成长为Under
World具有最高战斗力的《整合骑士》。

然而，哪怕是现在，事实上能和这位少女在剑和术式上对抗的人类在人界和暗黑界也不过百
人。少女因在令人恐惧的《东门之大战》及随后的《四帝国大乱》中战斗于最前线，以史上
最初经实战而建立的功勋而被任命为见习整合骑士[fn:1]。

虽然这么说——

此后，经不断磨砺而终于有所成果的少女的剑技，恐怕再也没有在任何场合加以发挥的机会
了。

因为Under World在近三百年的动乱后，终于迎来了真正的和平。

人界人、暗黑界人、哥布林、Oak、Ogre、巨人间缔结了六大种族的永久和平条约。对民众
加以暴虐统治的四大皇帝家族和上级爵士的特权也被废除。通商的马车不断通过已然崩毁的
《东之大门》，在央都圣托利亚的各处也可以见到来自暗黑界的观光客。过去曾将两个世界
分隔的恐怖与不理解，如同暖阳中的残雪一般毫无踪迹地融化。

大概不会再次染上敌人鲜血的剑在腰间摇晃，在因被圆柱遮挡而呈现出斜条纹模样的美丽的
日光中，少女和幼龙仍在奔驰。

「咔咔」「啪啪」的脚步声终于远去消失。

不知从何处冒出来的大蝴蝶，在再次陷入静寂的走廊内快乐地飞舞。

Sword Art Online 外传7　月之摇篮

「萝涅，这边，这边！」

萝涅听到声音踮起脚尖眺望，终于在人墙的另一侧看到了如同要燃烧起来的摇晃着的红发。

在紧挨着的厨师、书记、术师等大教堂职员间说着「对不起，对不起」低头跑过。带着看着
碍事者的表情转过来的人们，注意到萝涅后面鸣着鼻息的月驱，像是吃了一惊般让开了道路。
甚至连饲主看到这个光景都弯下了腰。

终于挤到最前面的萝涅长长地呼了一口气。

「真是的，太慢了！都已经开始了啊！」

萝涅向面前嘟着脸的红发亲友低头再次道歉道：

「对不起，不知道该穿什么……」

「不知道……到头来还不是穿成一副老样子吗。」

露出发呆的表情的少女名叫缇卓·施特莉涅恩，和萝涅一样是见习整合骑士。和头发很像的
红叶色眼瞳闪着光芒，久经锻炼的身体上穿着可爱的毛织上衣和裙子。腰间挂着的红色皮革
剑鞘可以说和这套穿着非常相配。

果然该穿着上周买的那件像是披肩一样的南方产外套过来的啊，萝涅带着这份悔意移开视线，
看到缇卓另一边她所养育的幼龙·霜咲正碰着月驱的鼻子，而更远处的一位青年则呵呵地露
出了笑容。

虽然相比青年更像是少年，但他外观上却更像大人。腰间悬垂着华丽的长剑和弯曲成『く』
字形的投剑。剑的优先度相当高，但那枚投剑更是非凡。如同薄纸一般的银制武器，乃是世
上为数不多的《神器》级武具。

萝涅赶紧右手握拳水平握于胸前，向他行了一个正式的骑士礼：

「早上好，雷恩利大人。」

听到声音的整合骑士雷恩利·Synthesis·Forty-nine在两匹幼龙的另一端苦笑着回答道：

「早上好，萝涅小姐……不用这么害怕也可以啊，今天可是好不容易才有的祭典呢。」

「祭典……是什么呢？」

萝涅反射性地歪起了头。今天，也就是二月十七日，在日历上是完完全全的平日。不论在去
年发布的〈Under World基本法〉上，还是现在正在进行修订工作的〈禁忌目录〉上，都没
有任何一行庆祝这一天的内容。

然而只要环视周围，就能看到在宽广的中央大教堂正面广场上，有着如同令所有职员都挤过
来一般热闹的大批观光客。手拿着茶、酒或是零食的他们引发了相当的骚动。

不仅如此，围绕大教堂的白色石墙，今天似乎也对央都市民开放了。挤在正门左右观光客的
人数恐怕已经超过了一千人。

「嘛，除了祭典倒也没什么可以描述这种状况的了。实在没办法，因为前辈……不，代表剑
士大人做什么事情的时候，肯定就会变成这种样子。」

萝涅对缇卓带着发呆的表情说出的话点点头回答道：

「是这样呢……今天别把大教堂毁了就好……」

三人的视线前面是——

矗立在那里的不知道该说是什么的东西。

那个东西位于铺设着纯白石板的正面广场中央，由黑色和黄色绳子围出的边长一百Mel的正
方形空间的正中，发出奇怪的「噗噗」声音。简单来说，就是《像是金属制的龙一样的东
西》。

然而，尖锐伸出的头部却是由透明玻璃做成，证明它并非只是一个雕像。极为平坦的身体左
右延伸出短短的翼，而从奇怪地膨大着的后部伸出的，并非双腿而是两个巨大的筒。

全长大约五Mel的《那个东西》以最下面的大筒直立着，但从后部可以看到的跳动着的橙色
火焰已经让人搞不清它到底是什么了。

……唯一能确定的，就是有相当不好的预感。

在心里这样自言自语的萝涅将视线从金属飞龙上移开，耐心注视着旁边的三个人影。

这么注视着的时候，其中的一人——栗色的长发飘舞于微风中，穿着珍珠色裙子，腰间挂着
细剑的年轻女剑士，似乎是注意到了萝涅的视线一般转过脸来。之后她露出微笑，抬起右手
向萝涅示意：

「喂，快来这边。」

被缇卓嘻嘻笑着拍了一下后背，萝涅稍微犹豫了一下，还是不由得跨过了面前的黑色和黄色
绳子。月驱也像是理所当然一般地跟在她的后面。

意识到数千人的目光一齐聚集在自己身上，萝涅赶紧缩起头在石板上小跑起来。到达女剑士
的身边后，先伸手行了一个骑士礼才说道：

「早上好，副代表大人。」

「早上好，萝涅小姐。今天可是突然的庆祝日，该更开心一点才好啊。」

看着她令人着迷的美丽脸庞上露出轻松的微笑，萝涅也放松下来回答道：

「是，亚丝娜大人。」

「明明都说了不需要加《大人》这个称呼的。」

哪怕她嘟起嘴这么说，萝涅还是很难接受这么做。

面前站着的这位比萝涅看起来稍微年长的女性——人界副代表剑士亚丝娜，对于全Under
World人来讲，某种意义上是比代表剑士更应当加以尊敬的对象。要说原因的话，众人都相
信她乃是Under World创世三神之一、《生命之神丝提西亚》的转世[fn:2]。

尽管她自己一直坚决否定自己并非神明，但萝涅在过去的大战中，曾近距离目击到亚丝娜一
剑挥下，大地便出现巨大裂缝的场面。看到了那个场面，根本就不会考虑在她的名字后面省
略《大人》这个称呼。

虽然禁忌目录上记载了『不得加上《大人》的称呼』的话就不可能不服从，但萝涅还是带着
坚定的意识摇了摇头。亚丝娜苦笑了一下，耸耸肩切换了话题：

「说起来，萝涅小姐，你最擅长的神圣术是燃素系统吧？」

「嗯，是的。」

萝涅眨眨眼点了点头。亚丝娜将脸贴过来小声继续说道：

「那稍微有一个请求呢。如果存储在《那里》的燃素要暴走了的话，可以告诉我一下吗？」

「诶，诶……？燃素，存储在那里？」

一时间还没明白这句话的意思的萝涅再次眨眨眼转过身去。在视线前方矗立着的金属飞龙旁
边，两个男人正在大声喧哗着。

「听好了，桐小伙子，不管这个燃素密封罐的天命在计算上能承受多少热量，也要对其充分
供给冻素！本来你小子就不擅长冻素术式，哪怕稍微一会来不及生成因子，那个瞬间密封罐
就会爆炸了！」

喊着详细意义不明但实际上极为危险的话的，是留着漂亮胡须的五十岁男性。这个名为姆达
伊的人是萝涅也熟识的，央都圣托利亚首屈一指的锻冶师。之前很长时间都在平民区里过着
隐遁生活，但在《四帝国大乱》中为解放军提供帮助，借此机会成为了大教堂工厂的最高顾
问。

听着名为姆达伊的锻冶师的牢骚，像是小孩子一般嘟着脸的那个人——

则是黑发黑眼的，一眼看去极为平凡的青年。

穿着相当合适他的上衣和裤子，外面套着奇怪的黑皮大衣。腰间没有武器。少年戴着同样是
黑色的皮手套的双手绕在背后，歪着嘴回答道：

「喂喂，这种事情已经听够了啊。再说了，姆先生差不多也别用那个《桐小伙子》称呼我了
好吧。」

「嘛，休想。从五年前你拿着那个超硬的树枝到我的工房，把那个磨成剑耗费了我贵重的三
块砥石的时候开始，我就决定要永远叫你小伙子了。」

「……切，要是没有那把剑的话，现在这个世界可是会变成相当不的了的样子啊……」

嘟哝着的青年突然回过头，看到了萝涅的身影。

从三年前初次见面时起没有丝毫改变的，既像是任性的小孩子又像是历经战斗的剑豪的脸上
露出了大大的笑容。看到他笑出来的萝涅，内心深处紧紧地揪了一下。

格外小心地不将这个感情表现出来，萝涅急忙低头说道：

「早上好，桐人前辈。」

这里本想加上《大人》的称呼，但实际上已经下发了对他禁止称呼《大人》的正式文件。因
此现在萝涅不得已只能使用最初使用过的《前辈》这一敬称作为称呼[fn:3]。

过去是圣托利亚修剑学院的上级生，现在则是人界代表剑士的青年——桐人，带着笑脸挥挥
右手回答道：

「哦，萝涅！月驱也还好吗！」

跟在萝涅后面的幼龙发出「咕噜噜噜」的鸣叫声跳到前面，毫无顾虑地舔着桐人的脸颊。锻
冶师姆达伊将身体转向挠着幼龙颚下的桐人这边，也向萝涅打了个招呼：

「哦哦，早上好，萝涅小姐。」

赶紧靠近露出一反常态的柔和笑脸的锻冶师，萝涅小声询问道：

「那，那个……刚才您所说的，燃素……密封罐，到底是什么啊？」

「就和它的名字一样啊，来，看看那边的《机龙》试作一号的臀部。」

「ji……long？」

虽然是没听过的词语，但萝涅很快就明白所指的是那边矗立着的金属制飞龙。眺望过去，从
膨大的臀部位置，正发出连绳子外面的人都能听到的巨大的「噗噗」声音。

「那边用西方产的阿达曼特钢制造的两个容器里，每一个都封有十个燃素呢。」

「诶……诶诶！？」

听到这句话的萝涅被吓的整个人向后仰去。

燃素乃是神圣术之源的八种属性的因子中最难以对付的存在。与可在空中常时维持的冻素和
风素不同，生成并加以释放的瞬间就会伴随放出的高热反应并消失。如果呼出燃素，在进行
加工处理之前决不能切断意识，因此对于以术师为目标的孩子们，这一教学乃是基本中的基
本。

「怎，怎么会这样……哪怕是耐燃性再好的钢材，如果和十个燃素接触着不管的话，总会熔
化爆炸的吧！？」

「这可花了一番功夫呢。容器外侧，可是绕了用高耐冻性的尤鲁德大蜈蚣的壳造出来的管子
呢。通过跟这些管子连接的冻素密封罐供给冷气，防止燃素罐熔化，可是相当复杂的装置
呢。」

「…………哈，哈啊…………」

虽然说下了番功夫，但对萝涅来讲燃素和冻素乃是归属于神之秘迹一般的神圣术领域，与加
工金属和甲壳的锻冶/冶金术可谓是南北两极的存在。将这两者加以组合会变成什么样子，
这样的事情一次都没想到过。

「…………那，那个的话，应该能正常工作吧……」

听到发呆的萝涅的话，锻冶师姆达伊摊开强壮的双臂说道：

「我也不知道。」

「诶诶！？」

「乘上机龙的又不是我，是桐小伙子啊。」

「诶诶诶——！？」

乘上去——到底是什么意思啊。

萝涅战战兢兢地转过脸，抬头看向坐落在那里的《机龙》的前端。

注意到由透明的玻璃板组合成尖锐形状的头部内侧，设有一个不论怎么看都只能认为是椅子
的东西。椅子周围是弯曲着的金属管，奇怪的圆形板上有着好几个突出位置。板子中央附着
着一根细针，细针似乎正随着「噗噗」的声音微微颤动着。

「…………难，难道说……什么人坐在那里，然后……将燃素解放……从臀部的筒里喷出爆
发力…………」

「嗯。飞起来。就像飞龙一样。」

回答萝涅的是不知何时已经站到旁边的桐人。

此外他的旁边，月驱闻到了《机龙》金属翼的味道，像是被嘲笑了一般从鼻子里发出哼的鸣
叫声。

「太……太，太，太乱来了，前辈！！」

萝涅不由得喊出声来，抓住桐人那件奇怪衣服的袖子哆哆嗦嗦地拉着。

「要，要是燃素暴走的话，整个都会被吹飞的吧！对对对了，还是用风素吧，就像大教堂的
升降盘那样！」[fn:4]

「不行啊……那个是封闭在升降洞里面，所以通过风素的压力就可以上升或者下降了。要是
想在什么都没有的空中飞行的话，就只能靠燃素的爆发力……」

说到这里桐人笑了一下，环视周围继续说道：

「而且，都已经来了这么多人了。现在要是说中止什么的话，肯定要引起第二次央都大乱
吧。」

「把，把他们集合到这里的不就是前辈你自己吗！！」

今天在这个中央大教堂正面广场上集中了这么多人，乃是桐人本人将《大教堂工厂开发部进
行的实验》广而告之的结果。

如今已经成为最大骚动来源的人界代表剑士殿下所做的什么事情又会为迎来和平的Under
World带来什么，对于在上次的《守护龙再生实验》中大为享受的职员和市民来说，再次聚
集过来也是理所当然的。

当时，如果在与苏醒了的白龙的问答中桐人稍微错了一点的话，大教堂的一角稍微缺损这种
程度的结果无论怎样都无法了事。了解这一情况的萝涅不由得身体向后倒去。

在身后支撑住她的，是紧靠在后面的副代表剑士。似乎和桐人交往了很长时间的亚丝娜，带
着像是达观又像是放弃一般的表情说道：

「已经没用了哟，萝涅小姐。都到这个地步了，就只能坚持做下去了呢。」

「怎、怎么会…………不…………也是这样呢…………」

一瞬间摇了摇头的萝涅，在脑海中整理思绪后点了点头。这几年来，她已经彻底理解了桐人
只要想到什么事情就『只能坚持做下去』这一事实。

至少全力避免出现大惨案吧！萝涅在心中自言自语着，将精神集中在《机龙》的心脏部位。

虽然说被任命为见习整合骑士，萝涅终究还是尚未到达自如操作《心意》这一骑士最高奥义
的领域。像桐人等上位骑士那样通过心意将行使神圣术的术式缩小到极限完全不可能做到，
但感知现在生成的因子状态这种程度似乎还是可以做到的。

就和锻冶师姆达伊说的一样，可以感觉到机龙的内侧封有数个燃素。然而，燃素绝不可能像
是大人一般并排排列。它们不高兴地抖动着，以若有缝隙便会将周围的壳一口气吹飞一般的
态势跳动。

因子阶段就已经如此混乱，要是解放出来的话到底会变成什么样子——虽然萝涅感觉一股恶
寒袭过身体，但之后就只能注视着结果了。

「那个……总之已经和燃素建立交感联系了，亚丝娜大人。」

听到萝涅小声说出的话，旁边的亚丝娜也低声回答：

「谢谢你了。那么，就这样保持回路畅通吧。」

「好，好的。」

萝涅点头的时候，位于稍远处的桐人大声说道：

「好，那么就开始吧！亚丝娜，倒计时就麻烦你了！」

「为、为什么是我啊！」

「从过去开始突入Boss房间的时候倒计时什么的都是你做的吧——」

听到桐人谜一般台词的亚丝娜摇摇头说着「真没办法」，伸出右手开始咏唱神圣术的起始句：

「System Call！」

接着，流畅地组成了由风素和晶素组成的《广域扩音术》。尽管她也还在修习心意的途中，
但在术式的把握和应用上，如今大教堂的术士们已经无法与她匹敌了。

亚丝娜向着在空气漩涡中央形成漏斗状的玻璃薄膜，以极为清澈的声音说道：

『前来的各位，让你们久等了！现在，我们将进行中央大教堂工厂开发部所制《机龙试作一
号》的飞行试验！！』

经过放大的声音响彻空中，在远处围起来的大教堂职员们和挤在城壁上的央都市民们一齐发
出了「哇啊！」的欢呼声。如果仰望南侧中央大教堂的白垩质的威容，可以看到位于迪桑三
十层的阳台上，上位整合骑士们的铠甲也反射出耀眼的光辉。

在欢呼与鼓掌中，桐人向观光客们挥手，开始登上由长铁柱组成的，支撑机龙的阶梯。不一
会他就到达龙头位置，随后碰触了透明板的一部分。随着透明板啪的一声打开，桐人的身体
滑入了内部。

在向着天空设置的椅子上坐下，用皮带固定身体，再低下头将奇怪的巨大眼镜戴在脸上后，
桐人向位于地面的锻冶师姆达伊伸出了左手的拇指。

姆达伊老人回过头，后退到比萝涅和亚丝娜所到的位置更后面二十Mel左右的地方。萝涅也
在保持与燃素的交感状态不被切断的情况下，慎重地保持距离。

『那么，开始读秒！各位，请一起和我倒数！』

亚丝娜带着已经习惯了的样子向观众呼喊。之后她高举双手伸出十指：

『准备，十！九！八！…………』

一千多人的声音随着亚丝娜的倒数响起。仔细看过去，可以看到缇卓和雷恩利也带着笑容倒
数着。

紧紧抱着旁边月驱的头，萝涅也一起倒数计时。

『七！六！五！』

突然，燃素的震动开始增强了。桐人开始用心意加以控制它们。

他那如此强大而深远的意识，通过因子的媒介，流入与之交感的萝涅心中。

心中再一次被紧紧揪住。

……不可以，只有这份感情绝对不能表现出来。作为前辈的近侍，直到老去而天命耗尽的时
候之前，都必须让这份感情静静地沉睡。

萝涅尽量不让这个想法被旁边的亚丝娜感觉到，眨了眨已经稍微发热的双眼，拼命喊出声音。

『四！三！二！』

咻…………机龙运转的声音开始逐渐增强。带着暗银色光辉的巨大躯体剧烈颤动，底部的筒
中漏出的光从橙色变为黄色，最终变为纯白。

『一！…………零！！』

倒计时摇晃着广场石板的同时，听到了桐人微弱的喊声：

「Discharge！！」

将因子解放的术式语句。

之后，二十个燃素一齐将其中蕴藏的威力释放出来。

随着「咚！」的一声冲击，从机龙下面喷出了剧烈的蓝白色火焰。火焰将拥有近乎无限天命
的大理石板熔化，卷起了巨大的烟尘。观众间响起一片欢声。

从烟尘内部——

金属龙化作银色的箭，一口气直线飞出。

接着，萝涅听到了至今从未听过的高亢的金属音。机龙的两个大筒拖着长长的火焰尾巴，向
着更高，更高的地方飞舞。

萝涅通过举起的双手传来的痛感，感觉到了被解放的燃素的猛烈程度。本来不论是何种素材
制作的容器都会因超高热而一瞬间天命全损，机龙整体也会发生大爆炸。然而，通过埋入密
封罐的管道逐个送入超低温的冻素，就可以抑制容器的热量。结果，燃素的爆发力就会从喷
射筒向一个方向释放，让那个机龙直线飞行。

也就是说，如今在Under World历史上，第一次有人乘坐龙或大鸟以外的东西在天空中飞翔。

「…………好厉害……」

萝涅的双眼，因与之前完全不同的理由而满是泪水。

已经歪曲的视线远端，银色的龙与中央大教堂的威容平行飞翔，在空中不断加速。

如果机龙只停留在地面上，因为不停生成的冻素的缘故，周围的空间神圣力不过数秒就会枯
竭，然而只要那样移动，就可以通过空间内神圣力的供给加以补足。这样的话，那条龙——
可以到达生物无法呼吸的高空——这种事也是可能的。

想到这里的瞬间，萝涅如同被电流击中一般，领悟到黑衣的人界代表剑士真正的意图。

桐人并没有只将让它飞起来作为目的——如果，通过那个机龙，可以跨越不论何种生物都无
法跨越的《世界的尽头》的话……

然而，这一想法掠过的瞬间，萝涅突然感觉到了燃素膨胀的气息。

密封罐在膨胀。因为热量而熔化了。虽然不明白理由，但恐怕是降低温度用的冻素出现了供
给停滞现象。

「亚、亚丝娜大人！燃素——」

刚刚说出话的瞬间，令人不快的「砰」的声音响起，可以看到一侧的喷射筒漏出黑烟。

机龙很快开始绕着锥形轨道回转。方向向南侧偏移，在它的前面——

是中央大教堂第九十层位置的墙壁。

「要，要撞上了！！」

萝涅双手紧握在胸前喊道。从观众们中间，也传来了高声的惨叫。

之后，突然响起「锵！」的一声。是亚丝娜将细剑从腰间拔出的声音。

世界上最为美丽的刀身将索尔斯之光分为七色闪耀，亚丝娜将细剑径直指向了大教堂。

「……好的！」

在亚丝娜发出这完全不像神一般的声音的同时，细剑的剑尖轻轻向右移动。

就像是被这剑尖拉过去一般，巨大的中央大教堂从第九十层往上的部分，向西侧移动了一下。

拖着黑烟的机龙在这一瞬通过了出现的空间。

在遥远的南侧天空，啪的一声发出令人目眩的闪光。

咚的一声，传来巨大的爆炸[fn:5]。

** 2

虽然已经随着机龙上升而耗费了相当的量，但二十个燃素同时被解放的威力仍然极为惊人。

通常每根手指仅能操纵一个因子，因而不论位居何等高位的术士在极限情况下都只能同时生
成十个因子。虽然在传闻中有着过去于神圣教会执掌权柄的首席元老可以连脚趾也加以利用
而操纵二十个因子、已不在人世的最高祭司将头发也作为末端而能操纵近百个因子的说法，
但萝涅当然一次都没有见过如此可怕的场面。

连身为骑士的萝涅都这样了，挤在大教堂外围的市民们也相当震惊。随着在遥远的高空中产
生的犹如第二个索尔斯般的橙色闪光，像是摇动天地般的轰鸣传到地面的时候，大量的观光
客都双手抱头发出了悲鸣。

然而理所当然的，由于未经加工的燃素只是爆炸的缘故，相比华丽的爆炸场景，爆炸并没有
波及距离数百Mel的地面。

在战战兢兢地抬起头的一千多人的视线前方，浓密的黑烟无声地扩张，掩盖了大教堂的最上
方部位。

在这相当于两个月前简直要将这个广场烧掉的庆祝新年的大篝火数倍规模的爆炸下，乘坐钢
之龙的那个人到底变成什么样了——恐怕所有人无疑都在这么想。同样怀有这个想法的萝涅，
双手紧握在胸前，睁大双眼看去。

「桐…………」

桐人前辈！

喊出话前的瞬间，旁边的亚丝娜砰的一声敲了下她的肩膀说道：

「没事的啦。」

在这毫无畏惧的冷静声音响起的同时，一个小小的影子突破黑烟的底面缓缓落下。是人。虽
然构成机龙的所有金属都已蒸发成为空间力而扩散开来，绕着圈子落下的那个人的黑皮大衣
却看不到一点烧焦的痕迹。

那个人影突然伸出了双臂。

袖子上的皮革如同融解一般流动着，变为薄翼的形状，从肩部伸出。

如同黑龙一般的双翼拍动了两三下后，下落的势头减缓——最后完全停止了。

飞行术——不对，正确来讲这并不是术式。通过心意将衣服变为真正的翼，将『自己是可以
在空中飞行的生物』插入了《世界之理》[fn:6]。

能做到这种事情的人，如今就只有他一个了。抬头仰视的观光客们发出的大声惊呼，随之变
为了巨大的欢呼声与掌声。

虽然当初所定为目标的《机龙飞行实验》可以说有一半失败了，但他——桐人仍带着笑颜向
观众们挥手，缓缓降下。萝涅仰视着他的身影拼命拍着双手。将不得了的想法付诸实施，然
后极可能又引发不得了的结果——桐人的行为不论经历了多少年，似乎都毫无改变。

虽然还在笑着，但萝涅却注意到自己的双眼已经湿润。

紧闭双眼，拂去泪水，她在心中偷偷祈祷着。

如果能实现的话，希望这样的日子能够永远延续下去。

中央大教堂第五十层，被称为《灵光大回廊》的广阔空间，现在成为了《人界统一会议》的
议事堂。

过去只有被磨光的大理石铺设的地面的中央，如今安放了由白橡树的古木切削而成的巨大圆
桌，周围则有二十把椅子环绕。

缩着身体桐人坐在其中一把椅子上，如同仁王般站在他面前的魁伟骑士，以堪比雷鸣的声音
说道：

「今天的事情可是今天就要说的，代表骑士殿下！！」

「…………是。」

「你应该不会忘了自己曾对着剑发誓，说这次绝对不会破坏任何东西了对吧！！」

「………………是。」

对着人界最强的剑士像是教师一般叱责着的骑士，身上穿着粗犷的红铜铠甲。他有着刚毅的
面容，削短的头发和锐利的眼瞳如同火焰一般。名为迪索鲁巴特·Synthesis·Seven的他，乃
是最古老的整合骑士中的一员。

「如果没有亚丝娜大人为我们显现神力的话，现在大教堂的九十层以上都要被烧焦了！虽说
是无人楼层，但拥有历史传统的《白垩之塔》如果变成了《黑炭之塔》的话，央都的百姓们
会是何等的叹息与悲伤！更何况，代表殿下相比您自己所处的需要承担的无数责任的立场，
在自觉性的方面差得太多了！术式及工具的准备，交给以此为天职的术士和锻冶师就可以
了！」

如同要永远持续下去一般的迪索鲁巴特的痛斥，被稍远处靠在桌子上的苗条骑士打断了：

「差不多就这样吧，迪索鲁巴特。代表殿下简直就像日光下的虫子一般要枯萎掉了呢。」

带着笑声以娇艳的声音说出这句话的，是穿着如同镜子一般光亮的铠甲，波浪状的黑发垂到
背上的女骑士。左腰佩带着白银剑柄的细剑、右臂则抱着有着少见蓝发的，约两岁的幼儿。

「但，但是，骑士长……」

「再这么叱责下去，代表殿下恐怕连从家里出去都会犹豫的吧。他可要准备下个月和暗黑界
五种族间的合议呢。」

有着如绽放的大朵兰花一般娇艳的美貌的，被称为骑士长的女性，名为法娜提
欧·Synthesis·Two。从她现在轻轻摇着幼儿的样子，无论怎样都看不出她是位居第二代整合
骑士团长这一要职，拥有世界最高级别剑力的人物[fn:7]。

法娜提欧走到仍然消沉地低着头的桐人面前，带着娇艳的微笑说道：

「经历了这样的事情，差不多也该成熟一点了呢，小伙子。」

听到这句话一下子抬起脸的桐人，脸上带着苦笑回答道：

「《小伙子》这个称呼可比《代表殿下》更让我害怕啊。」

「呼呼，让你害怕的不是就在后面的暗处吗？」

法娜提欧这样说着，斜眼看向抱着双臂站立的副代表剑士亚丝娜的身影。虽然她也带着笑容，
眼睛却微微颤动着[fn:8]。

法娜提欧随后向稍远处站在圆柱旁边的萝涅看了一眼，意义不明地眨了眨眼睛后露出了调皮
的笑容。之后她回过头来，砰的一声拍了拍桐人的肩膀：

「嘛，这次没造成什么损害，所以也就不继续苛责你了。作为交换，到晚饭之前烦请你认真
办公。」

「…………是。」

将垂头丧气地点点头的桐人所坐的椅子转向圆桌，法娜提欧又看向萝涅，招了招手。萝涅慌
忙从圆柱那里跑了过来。

「萝涅，虽然并非你的职责让我有点不好意思，但可以帮我照顾一下贝尔切吗？这种时候让
他一个人玩的话会打扰到的。」

「是、是，我很乐意！」

萝涅这样回答着，伸出双臂，从骑士长手中轻轻接过幼儿。接过来的时候，心里为手臂上的
重量而大为吃惊。虽然萝涅作为见习整合骑士，可以单手挥动长达2Mel的大剑，但她觉得小
孩子的重量和武器可以说有着完全不同的含义。

将双臂重新紧抱在胸前的时候，小贝尔切发出了「呜呀呜呀」的声音，但之后就再次陷入了
沉沉的睡眠中。萝涅行了一礼后，回到了墙边。在那里等待着的月驱，伸出鼻子兴趣满满地
闻着味道。

桐人、亚丝娜、法娜提欧和迪索鲁巴特在圆桌边隔开适当的距离坐下，立刻就开始喧哗地议
论起来：

「首先，是日前报告过的，《终结山脉》南洞窟的再开通……」

「虽然洞窟的挖掘可以做到，但在南方的密林地区建设街道需要相当多的时间……」

今天的会议并非正式评议，因而作为见习的萝涅并没有必须出席的义务。实际上，她的搭档
缇卓就为了学习术式，而将自己关在大图书室里。

然而，萝涅却有着不论怎样都想秘密询问桐人的事情。是上午看到飞行实验的时候，突然想
到的无限的想象。桐人一旦离开自己的眼睛，就马上会跑到大教堂的什么地方——在不好的
情况下会跑到圣托利亚的城区，更过分的时候会飞去《终结山脉》，因此打算在这个会议一
结束就赶紧抓住他。

在心意的修行中，要在细铁柱的顶端单足站立数个小时，怎么说也不可以背靠柱子等待会议
结束。幼龙月驱和缇卓的霜咲相比更加成熟，也不会累的靠在柱子上吧。

萝涅耐心站在柱边，耳边听着活跃的议论的时候，突然怀中的幼儿可爱地打了一个喷嚏。

虽然还没有醒过来的迹象，但不知道他是否着凉的萝涅还是横向移动了几步，让从高处窗户
中射入的索尔斯之光直接照到他的身上。柔软的蓝发闪闪发光，丰满的脸颊也极为顺滑地反
射出光辉，这纯洁无垢的美丽让萝涅一瞬间屏住了呼吸。

…………婴儿，吗……

萝涅带着微笑在心中自言自语。

同时，她的意识，又迷失在上个月回到央都北部的家时，那段实在很难说是开心的记忆中了。

** 3

阿拉贝尔家历代，在旧贵族制度中都是叙列最低级的六等爵士的家族[fn:9]。

生活绝对无法称得上富裕。并没有上级贵族所能拥有的私人领地，收入只有于帝国卫士队任
小队长的父亲的薪资，以及相当少的爵士津贴。这些收入当然比不上无需工作即可获得大量
税收的一等或二等贵族，甚至连圣托利亚中心开设大型店铺的商人都远远不及。

但即使如此，和开朗而擅长家务的母亲、严格而温柔的父亲以及调皮的弟弟一起生活，每天
仍然过得十分开心。

唯一让人忧郁的，是父亲本家——四等爵士家偶尔会召开的宴会。父亲在本家是第四子，祖
父在萝涅还是婴儿的时候就被召还天界，继承家业的长子——也就是萝涅的伯父一家，都是
令人难以忍受的泛着贵族气息的人。虽然讨厌打扮考究的伯母在故意褒奖萝涅母亲穿旧了的
礼服时的表情但也毫无办法，每次一到举行宴会的时候就唠唠叨叨地撒娇，不想出现在宴会
上。

然而，在镇压了《四帝国大乱》后，贵族制度也被大幅度改革了。私人领地上的居民全部被
解放了。贵族的等级也被废止。虽然保留了爵士的定期津贴，但仅靠这些并不足以维持生活，
因而有相当多的贵族不得不去在再编成的《人界君》中谋求职位。

虽然对自古以来的大贵族家可以说是等同于天翻地覆的变化，但对萝涅来说，是终于变成了
应有的姿态。只靠家系就可以带着将军或参谋的肩章炫耀的时代已经过去，现在是凭借剑力
和智力，而拥有经验和知识的人才能担任重要的职务的时代。

也就是在现在，可以说所有贵族家庭的等级都处于同一水平线上的状态。

然而这里只有两个例外。

亦即，在圣托利亚的全部贵族中，只有两人被选拔为见习整合骑士的萝涅和缇卓的本家——
阿拉贝尔家和施特莉涅恩家。

上个月，萝涅在进入骑士团后第一次回家探亲。一年不见的父母和弟弟都还不错，尤其是还
在圣托利亚修剑学院上学的弟弟相当喧闹，甚至还挥起了萝涅的剑——当然做不到拔剑，还
和萝涅掰手腕——当然连半Cen都没掰过去，引发了相当大的骚动。父亲询问了骑士团的这
样那样的事情，而母亲的料理也一如既往的美味，过了相当开心的一夜——然而。

第二天一大清早，父亲的三个兄长和他们的家族就前来拜访，还带来了相当多的令人不可想
象的礼品。

也就是，向萝涅提出的婚约。

总有一天萝涅将被正式任命就职的整合骑士，在旧时代乃是作为神圣教会的守护者，被全人
界的居民因压倒性地畏惧和尊崇而加以崇拜的对象。这种感情，哪怕在教会变为《人界统一
会议》的现在也毫无改变。甚至可以说，因为相当数量的整合骑士在《东门之大战》中殒命，
将他们视为英雄的程度大概还有所增加。

如果能够迎娶这位骑士的话，那么这个贵族的等级和收入将会一口气上升吧——伯父和伯母
们似乎是这样想的。有年龄合适的儿子的家庭就将儿子带来，而没有的就带来了近亲家的继
承者。令人留下深刻印象的聘书之山堆在萝涅的面前，而她的伯父伯母们则喋喋不休地说道：

——就算你是见习骑士，对女人来讲最重要的天职，乃是生养子女啊。听说整合骑士团长就
生下孩子了呢。那么，你这么做倒也不坏啊。就推荐这家的儿子，不，是那家，不对，是这
边这家……

过去，桐人曾私下向萝涅和缇卓说过一点事情。

支配了旧神圣教会的最高祭司，集中全帝国剑技和术力最为优秀的人并将他们提升为整合骑
士。然而在事实上，骑士们被施加了名为《合成之秘术》的禁断术式，抽出了过去的记忆而
封入『自己是无法成为被神界召唤之人』的虚伪记忆加以替代。

无疑，这一令人恐惧的行为存在——在提高骑士团运转的效率这点上可以说是巧妙的手段。
在伯父伯母们喋喋不休的时候，萝涅对此也并不意外。

抑制着自己想要通过烟幕术式从这个场合逃走的想法，萝涅拼命向他们说明即使迎娶了整合
骑士，爵士津贴不会增加，也不会获得领地。然而伯父们根本不相信她的话，到后来他们说
出萝涅每天在大教堂肯定过着相当奢华的生活的时候父亲愤怒地将他们赶了回去，这样萝涅
才总算从危险的境地中逃脱。

然而——

『爸爸，谢谢你。』

虽然这么道谢了，但萝涅的心中无意间并没有这种想法。

父亲虽然对自己说真的没有想要结婚的男性也好，但在内心中肯定是希望早日看到孙子的脸
吧。不，在这之前，父母无疑就真心为女儿成为见习整合骑士的事情而怀抱不安吧。如果没
有发生战争的话，萝涅应该会很平常地从修剑学院毕业，迎娶某个贵族家的次子或三子，继
承阿拉贝尔家的家业吧。

因而二人希望萝涅能够安然结婚生子，这一愿望大概是极为明显的吧。

能够实现这个愿望的话就去实现，想让二人安心的想法萝涅当然也有。

然而萝涅在离开家回到大教堂而在门口向父母行骑士礼的时候，在心中偷偷自言自语道：

——对不起，爸爸，妈妈。我大概，不，是一定，一生都不会结婚生子了。

——要问原因的话，我的心情，已经永远传不到那个人的身边了[fn:10]。
** 4

萝涅的回忆，被抱在臂弯间的，终于醒来的贝尔切咿呀咿呀的声音打断了。

她赶紧以笨拙的动作轻轻摇晃着幼儿，但他的哭闹却毫无停下来的迹象。

「来，好孩子，好孩子……」

虽然萝涅拼命地试图安抚他，可幼儿的脸不一会就一片通红，在表情马上就要扭曲而大哭出
来的时候——

幼儿的襁褓被从前方伸出的手一下子接了过去。

「这种程度可是满足不了这孩子的呢。」

站在那里的是幼儿的母亲，骑士长法娜提欧。有着光滑的黑发加以装饰的美貌上，露出了慈
爱的笑容。

「来，举高高——」

法娜提欧说着便将小贝尔切「嚯」的一声向上抛去。虽然动作看起来很轻巧，但这动作可是
以最强的整合骑士的膂力做出的。

幼儿打着圈子，向着《灵光大回廊》那高到不可思议的天花板不断上升。

「哇……哇啊……啊、呜……！！」

萝涅的口中漏出不连贯的奇怪声音。幼儿在差不多要碰到天花板上的神界绘画的时候才终于
停下——然后一口气落了下来。

之后，被母亲用双手轻轻收回。幼儿似乎很高兴地「哈哈」笑着。

「真是的，可以想象以后是什么样子呢。萝涅，刚才麻烦你照顾了。以后还请多指教。」

法娜提欧留下这句话后便轻快地走向出口。会议不知何时已经结束，迪索鲁巴特等骑士也跟
在她后面走了出去。

「……似乎在养育的方法上也有原因呢……」

萝涅听到这轻声的自言自语而转过头去，看到了站在那里的，带着一半是惊讶一半是恐惧的
表情的桐人。旁边的亚丝娜也露出了相当微妙的笑容说道：

「嘛，嘛，总有一天会成为骑士乘坐飞龙在高空飞翔，不过现在就让他习惯高空倒也……不
是什么好事情啦。」[fn:11]

「谢塔小姐也好，这个孩子也好，再之后的未来大概不难想象……不，是能让人快乐的吧。」

桐人晃了晃脑袋，双手插在腰间对亚丝娜说道：

「接下来，反正今天的工作都已经结束了，我就去看看二号机的情况……」

「诶，诶诶！？还要接着做吗？」

「下次会更厉害的哦。在燃素发动机和游标中间加上风素压缩装置，就像涡轮增压器那
样……」

「我说桐人君你啊，在考虑推进力前先把安全性能搞好吧！」

萝涅不由得举起手插入了用与他人相比掺杂着更多古代神圣语的二人间的会话：

「那，那个……不好意思，桐人前辈……」

「嗯？」

「啊，我，有点……想要问的话……」

桐人的黑眼睛因惊讶而眨了一下，但很快他便带着微笑点头说道：

「嗯，可以。那么，虽然有点早，还是去喝茶吧。亚丝娜呢？」

被桐人看着的副代表剑士「嗯」了一声说道：

「虽然我想说我也去，不过之后还要去大图书室接受神圣术的教导呢。」

「是吗。第二代图书管理员是奥卡纳伊呢。别翘课比较好……」[fn:12]

「只对那些不认真的学生才是那样吧。」

亚丝娜苦笑着看向不由得身体一阵颤抖的桐人，退后一步轻轻抬起右手说道：

「那么就晚饭时再见吧。萝涅小姐麻烦看好桐人，别让他吃蛋糕吃太多了呢。」

「我，我知道了！」

亚丝娜向低着头的萝涅和自言自语着「我又不是小孩子了」的桐人又微笑了一下后，留下虹
色的反射光飒爽离去了。看着她的背影消失在南门后，桐人这才转过头来说道：

「那么，我们就去……很久都没去的第八十层好了。萝涅，我想吃雪桃蛋糕呢——」

「好的，那么我就去厨房准备了。」

「麻烦给我带两……不，是三份！那我就先走了！」

桐人不等萝涅反驳，就穿过通向升降洞的北门一口气消失了。

萝涅摸着懒洋洋地打着盹的月驱的头小声说道：

「还是整个拿过去比较好呢……」[fn:13]

萝涅将浇有纯白的雪桃砂糖的蛋糕整个——被厨师长瞪了——和茶壶一起放进放进篮子，离
开大厨房走向大教堂的第八十层。

乘着自动升降盘一口气上升。过去这个装置似乎是人工操纵的，但在自动化后，听说负责操
作升降盘的少女从原本的天职中解放，现在在工厂的新职位上发挥着自己卓越的风素术式操
纵才能。

《中央大教堂》第八十层，如同其别名《云上庭园》一般，屋内整个被花田铺满。身着黑衣
的人界代表剑士，站在如今丛生着霜百合的淡银色小花的广阔草坪中央凸起的光滑的小山丘
上[fn:14]。

桐人伫立在山丘中央的金木樨的树苗旁边，右手靠着树苗，回过头看着接近过来的萝涅，露
出微笑说道：

「哟，辛苦你了。」

「不必这样，这也是《近侍练士》的职责。」

萝涅笑了一下回答，然后便将餐布铺开。从篮子里取出器皿，然后切下一大块蛋糕，递给眼
睛像小孩子一般闪着的桐人。接着切好自己和月驱的份，再将茶注入两个茶杯后说道：

「请用。」

桐人喊出「我开动了！」之后，就以足以比拟飞龙的速度张口吃了起来。看着他这个样子的
萝涅，意识到心中有某种温暖的感觉一点点扩散开来。

可以在现在就这样和桐人在一起的幸福感，伴着如果有时间冻结的神圣术，可以将这一瞬变
为永恒就好的想法，一起从萝涅的脑海里涌现。

然而，不论怎样的术式无疑都无法操纵时间。时间既无法倒转，也无法停止，只能向着未来
流动。

时间虽然是这样的存在，这个世界也跨越了最大的危机，就这样得到了真正的和平。萝涅总
有一天也会被任命为正式的整合骑士，乘着自己养大的月驱在空中翱翔。虽然她的心中当然
有着等待这一天到来的心情，但同时也有着另一个愿望——期望这时间能够停止[fn:15]。

「……涅，萝涅？」

听到桐人的声音，仍然沉浸在思考中的萝涅一下子抬起了头。

「啊，抱，抱歉！还要一份吗？」

「不，不是，虽然很想要……但不是这个问题。」

桐人这样回答着，将已经空了的盘子递过来，稍稍歪了头继续问道：

「你刚才不是说了有什么想要问我的话吗？」

「啊……」

终于想起自己说过什么的萝涅一下子涨红了脸，这才开口说道：

「对不起！是这样……那，那个，是前辈做的那个铁龙……叫做机、机龙的那个东西。」

大口咬着萝涅递过来的第二份蛋糕的桐人点点头回答：

「嗯。」

「那个，我，不知道为什么就想到了……不，是很在意……」

萝涅无意间看向周围，这才压低声音继续问道：

「前辈难道是打算乘坐那个机龙，飞越《世界的尽头》吗？」

** 5

听到这句话的桐人发出「咕」的一声奇怪声音，左手敲着胸口，右手在空中晃动。萝涅慌忙
让他握住茶杯，将里面的茶一口气喝光。

好不容易吐出了一口气的桐人，带着和初次相遇时完全一样的，像是搞出恶作剧一般的笑容
说道：

「……不愧是近侍练士呢，我的想法根本藏不住。」

「诶？真的是这样吗？」

「嗯，是这样。」

萝涅呆呆地注视着若无其事地点点头，擦着脸颊的桐人。

《世界的尽头》——这是围绕着包含人界和暗黑界在内的Under World的无限绝壁的通称。

萝涅只亲自看过一次这从圣托利亚根本无法注意到的，与蓝色的天空化为一体的绝壁。随同
桐人前往位于暗黑界北部边境的山岳哥布林族的领土时，当注意到地平线远处闪着淡淡霞光
的断崖时，萝涅不禁深吸了一口气。

根据哥布林们的说法，绝壁似乎并非由土建造，而是由具有超高硬度的矿物构成的。想在绝
壁上像挖掘洞窟和阶梯一般开一个小洞都极难做到，而在三百年的历史上，尝试自力攀登绝
壁的哥布林最终都只落得摔死的凄惨下场。

巨人族和Ogre族里也有同样的传说。在如今居住于Under World的无数人的认识中，这个绝
壁已达到了绝对不可侵犯的，与其名称——《世界的尽头》相应的境界。

——应该是这样的。

「那，那个，嗯……」

虽然只是说了稍微预料到的事情，但立刻就被桐人肯定的萝涅还是惊奇地站了起来，拼命整
理自己的思路。含了一口茶后，她才好不容易总结出话来：

「……那个……也就是说，前辈已经自己尝试过通过飞行术式跨越那个绝壁了，是这样吧？」

「嗯。」

桐人虽然点了点头，但立刻又摇摇头说道：

「试过了，然后放弃了。不论是《翼形成》的术式，还是《光素变换》的飞行术都根本飞不
过去。而且，在接近某个高度之后，似乎重力会无限增加……」

桐人双臂抱在胸前，后背靠在金木犀的树苗上，像是相比向萝涅不如更像是向自己说明一般
继续说道：

「……但如果是在极限高度投掷小刀的话，小刀可以飞到相当高的地方。也就是说，绝壁并
非拒绝了一切物体的侵入。恐怕，只是选择性拒绝了被分类为生物的Unit吧。就算把身体变
换为光素，我的Unit ID也不会发生更改……就这样，之后我就只能把可能性赌在系统会将
将我完全封闭为某类移动型外壳的整体认知为非生物的对象了……」

桐人的话渐渐变得有点令萝涅难以理解。她怯生生地举手问道：

「那也就是说，如果只靠肉体飞不过去，乘上那个金属机龙就可以飞过去了，是这样对吗？」

「嗯……？」

这时才抬起头的桐人啪地眨了下眼睛，重重点了点头：

「啊，不好意思。嗯，就是这样……实际上，我也试过用皮革或是纸做的飞机，哦不对，是
龙，用术式和心意操纵它们飞起来。但也不行……如果我自己动起来的话，它们好像就会被
认成和衣服和铠甲一样了。需要让龙以自身的动力飞行。但是，为了承受燃素的热量无论怎
样都需要用金属制作，而想着为了让这个重量的龙飞起来到底要用多少力量就陷入了使用的
燃素数量增加的恶性循环呢——」

「啊啊……好像很难呢……」

萝涅「哈」的一下，从之前不由自主地和桐人一样陷入了思考中的境地中清醒过来：

「不，不是这个！那个，我想问的事情……」

「嗯，是什么？」

「为什么一定要越过《世界的尽头》呢！？虽然我一直在桐人前辈的旁边做近侍，对有障碍
就要越过的前辈的心情也能理解……但总觉得……现在还有很多更重要的事情……」

这时萝涅才注意到虽然一开始的口气还没什么，但后面就不知为何变成了说教的口吻而缩起
了头。桐人轻轻敲了一下她的膝盖回答道：

「谢谢你了，萝涅。一直让你这么担心，总感觉不好意思。」

看着桐人的微笑，萝涅的心跳又开始加快了。她像是没有觉察到一般拼命地抑制着自己。幸
好桐人没有注意到她的样子，将双手绕到头后面，视线朝着上面说道：

「…………但是，我是把越过那个《绝壁》，当作对现在的Under World最为优先的课题的。」

「诶……那是，怎么一回事呢？」

「……绝对不要对他人提起。哪怕是对缇卓和法娜提欧也一样。」

萝涅听到如此突然的话，睁大了眼睛。然而，她好歹还是点了点头。

然而，真正让她惊讶的，是桐人接下来的话：

「——这样下去的话，总有一天战争又会爆发的。」

「…………！！怎么会有这样的事……好不容易才迎来和平时代……」

紧皱着眉头的桐人听着萝涅如同喘息一般的话，轻轻摇了摇头回答道：

「很遗憾，这样的时代恐怕持续不了多久……随着东大门的崩毁，人界变成了暗黑界的任何
人都可以来的的情况，也出现了通商和旅游。如今到访人界的暗黑界的居民们还为少见的风
景和食物而开心。然而……总有一天他们会注意到的。两个世界有着决定性的不同。」

「不同……？」

「对。人界的土地太过丰饶，而暗黑界的土地又太过贫瘠了。萝涅也见到过那个血红色的天
空和如同灰炭一般的地面吧……暗黑界只有首都奥布西蒂亚的周边土地比较肥沃，而支配那
里的并非亚人，而是人族。这样下去的话，哥布林族和Oak、巨人等种族之间恐怕又会出现
虽然极为轻微但却确实存在着的不满吧……我和亚丝娜曾经努力试过能否让亚人族的领土绿
化，但最终还是不行。空间资源……神圣力的供给，少到让人绝望。」

萝涅一言不发地听着桐人的话。

——暗黑界荒凉的景象确实印入了她的脑海。但是至今为止都只认为它就是这样而已。她甚
至根本没有想过用什么方法来改变它。

「……前辈……我……」

桐人的黑眼睛看向低语着的萝涅，露出一个无力的微笑。

「对不起，我也不是打算责备萝涅。实在没办法，Under World一开始就是这样做出来的。
目的就是要让贫瘠的暗黑界和肥沃的人界间爆发战争。而且战争也确实爆发了。经历了无数
的牺牲，总算避免了最糟糕的结果。为了在那场战争里牺牲的人们，不能再让同样的事情重
复上演了。」

「但、但是，这样的话，又该怎么办……」

「答案只有一个。亚人族需要的，不是不断向边境开拓的领土，而是他们足够引以为傲的国
家——不需要再被称呼为《亚人》的，真正的国家。」

** 6

「真正的……国家……」

需要非常费力才能明白的桐人的话里，只有这句话的意义，萝涅不知为何能够瞬时理解。

萝涅曾经亲眼见过的，只有山岳哥布林族的领土而已。他们的国家位于从东大门向东北一直
前进到达的丘陵地带。土地无法种植小麦，河流里无法养殖鱼类——就是和字面上一样的荒
野。

而且，上上代组长巴卡西，以及他的儿子——也就是上代族长科索基相继离世后，才刚刚选
举出新族长的部族迟迟未能复兴。若是在Dark Territory只需服从『力量即法律』的旧时代，
他们大概就会被袭来的巨人和Oak族，或是平地哥布林族消灭掉了吧。

跟随桐人到访他们的土地的萝涅，因病人躺在粗糙的干草床上，饥饿的孩子们微弱地哭泣着
的景象而无话可说。虽然靠着从人界运来的大量救援物资脱离了最糟糕的情况，但这并不能
从根本上解决问题。那片土地，差不多已经无法支撑多产的哥布林族的人口了。

然而萝涅直到刚才，都没有想过『那之后』的事情。不，是拼命地想要让自己忘掉。想要让
自己忘掉那些一个个从自己的手里接过以耐久度为优先而实在无法说美味的硬面包时，如同
身处梦中一般的哥布林孩子们的样子。在那之后，人类应该也还在继续向他们输送物资吧。
那么这又有什么不好的，她向自己说道，而忽视了自己在丰饶的人界，而且还是作为贵族自
由生活着的内疚感。

但在现在，从听到桐人亲口说出『真正的国家』的话时，萝涅没法让自己不意识到这一点。
那片荒地，根本没法称作国家，甚至不能称作领土。那是片流放地。是在那里生存就如同刑
罚一般的土地。

「…………前辈……我…………我……」

萝涅深深低下头，将叉子「锵」的一声落到放着吃到一半的蛋糕的盘子上，用沙哑的声音说
道。

——贵族有着比获得的特权更大的义务。不论何时都必须为没有力量的人战斗的这个义务，
被赋予了古代神圣语《Noblesse Oblige》的名称。

很久之前，这样教导她的，正是面前的桐人。

——明明这样，我却不知怎么就忘掉了……不，不是的。实际上，并没有把哥布林族当成同
样的人类加以对待。虽然觉得他们很可怜，但心底的某个地方，却觉得这样也是没办法的……

从眼里慢慢渗出的泪水滴落到白色的盘子里。一旁的月驱也很担心地发出了「咕噜噜噜」的
喉音。从前方伸出的手，轻轻抚摸着萝涅的头。

「对不起，萝涅。我知道说出这种话，可能会伤害到你。」

与平常一样安稳的声音在耳边响起。

「……不过，不必为此责备自己。如今能够从人界向暗黑界运输救援物资，也是因为阻止了
皇帝们和大贵族的浪费，以及人界能够急速复兴的结果。不论哪一个，如果没有萝涅和骑士
们的力量都不可能实现。所以，萝涅已经为他们尽力了。」

「是……这样吗？」

「对。我经常去山岳哥布林的领土，那里的孩子们直到现在还好好记得给他们面包的你呢。」

与先前有着不同意义的泪水从萝涅的眼中溢出，流过脸颊。桐人用朴素的手帕，擦去她脸上
的泪水。

萝涅拼命压抑着自己想要飞扑到面前的人的身边，将脸贴在他的胸口大哭一场的冲动。只是
就这样低着身体，拼命忍住泪水，抬起头露出了小小的微笑：

「……谢谢。我已经没事了……对不起，在谈话的中间哭了。」

「萝涅是个爱哭鬼这点，从是初等练士的时候开始我就知道了。」

虽然噘起嘴瞪着笑着说出这句话的桐人，萝涅却不得不忍耐再次刺向心底的痛楚。

将这份痛苦连同茶水一起饮下后，她才眨了眨眼拭去最后的泪水，开口说道：

「……那个，前辈所想的事情，我大致都理解了。哥布林们和Oak们也需要和人界一样美丽
而丰饶的国家。这样的地方在Under World已经没有了，所以只能到《终结之壁》的另一侧
寻找。为此，那个机龙无论怎样都要跨越绝壁……是这样对吧？」

「嗯，是这样没错。」

萝涅又老实地继续向深深点头的桐人问道：

「可……可是，《壁》的《另一侧》什么的，真的存在吗？要是那个绝壁向着无限远的位置
永远连续着的话……？」

「这个我也想过。但是呢……如果那个绝壁真的是这个世界的尽头的话，我觉得根本就没有
存在的必要。那样的话就只需要不可侵入的地址……像是虚无一样的东西就可以了。」

「虚无……像是既看不到也进不去的空间一样的东西吗？」

「对。但是，实际上《终结之壁》是有着实体的绝壁。相当高，相当硬，对吧。如果它成为
这种样子的理由，是不让居民面对无法理解的现象的话……我们到达《世界的尽头》时，它
也就不成为《尽头》的可能性也是存在的……一切都要看Main Visualizer有着怎样的余地
和余力了……」

** 7

再次陷入了很难理解的领域的话让萝涅皱起了眉头。桐人很不好意思地挠挠头说道：

「不好意思，跟萝涅说着话结果脑子里想的都是这些。那个……是这样……《世界》本来是
没有什么《边界》的。」

「没有边界……？」

又是一个萝涅不熟悉的概念。

对在北圣托利亚出生长大的萝涅来讲，将城市分割为扇形的巨大城墙就是最初的《边界》。
之后学到了在另一侧有着广大的诺兰高尔思帝国的知识，又知道此外还有三个帝国，加起来
便是圆形的《人界》。

终于知道将人界包围着的《终结山脉》和在那另一边的令人恐惧的Dark Territory，是八岁
进入幼年学校的时候的事情。虽然教师这么说，但并没有提到暗黑界具体的地形——如今想
想，他知道才怪。知道将暗黑界也包围起来的无限绝壁，也就是《终结之壁》的时候，已经
是和缇卓一起志愿参加人界守卫军，赶赴东大门以后的事情了。

换而言之，在萝涅所知的世界里，总是有着《边界》的存在。就算跨越了这个边界，下一个
边界也一定会出现。她相信，总有一天会到达绝对无法跨过的，真正的《世界的尽头》——
然而。

「……那，也就是说……《终结之壁》的另一侧，也有像是人界和暗黑界一样的……草地、
森林、荒野延伸着吗？」

桐人对萝涅带着不确定的语气提出的问题，「嗯」了一下说道：

「要怎么说明才好呢……对了，跟我来。」

他站起后将手伸了过来，轻而易举地拉起紧张地伸出手的，带着剑的萝涅，将她带向《云上
庭院》外围开着细缝的窗户。

「来，看那个。」

黑衣的右臂指向的，是位于蓝色逐渐变深的东侧天空中浮现的白色半圆——也就是月亮
【Lunaria】。萝涅和月驱听着他的话，抬头看向乃是幼龙名字来源的巨大星球。

桐人说出了相当理所当然的话：

「是圆的，对吧？」

「嗯……是的。是圆的。」

虽然想着「要说什么？」，但萝涅还是点了点头。

「那个月亮并非平面的圆盘，而是正圆形的球体。所以才会像那样有着圆缺变换。这个
是……圣托利亚的学校里会教的对吧？」

萝涅苦笑着看向没有自信地确认着的桐人，又点点头说道：

「当然是的。那是浮在位于天空另一端的神界的，露娜莉亚神御座上的巨大的黄金珠子……
幼年学校里是这么教的……」

「这样吗。那个……嗯……实际上，根据我的推测，包含了人界和暗黑界的这个世界，其实
应该是和那个一样的的球形。」

「诶……诶诶！？球形的？」

萝涅不由得喊了出来。一旁的月驱像是想要嘲笑桐人在说什么蠢话一般，吐出呼噜噜的鼻息。

桐人之后花了五分钟，将世界的球形构造——根据他的话，也就是行星——告诉了萝涅。虽
然并非很容易就能接受的话，但只有一个事情是可以深信不疑的。

《中央大教堂》第九十层《晓星望楼》，是对外部完全开放的构造。站在边缘眺望地面时，
可以看到远处的地平线向上描绘出平缓的弧形。

如果世界真的是球形的话，这样也是理所当然——虽然大概如此，但萝涅仍然无法在脑海里
形成理解的实感，只是尽力注视着浮在空中的月亮。

突然，她的口中说出了自己都没有想过的话：

「要是这个世界和那个月亮都是球体的话……月亮上也会有草原、森林和城市，也有人住在
那里吗？」

「嗯……」

这个问题似乎出乎桐人的预料。黑发的剑士眨了眨眼睛，随后平静下来说道：

「……说不准是这样呢。考虑到和月亮间的距离，月亮并非小型卫星而是与这里一样大的行
星也是有可能的……嘛，总有一天去看的话就知道了。」

毫不在意地说出的话，并未让萝涅感到意外地吃惊。反过来讲，她甚至预感到了这个人理所
当然地会说出这种话。

所以萝涅只是微笑着向桐人靠近了一Cen，小声说道：

「到了那个时候，我也一定会去的。作为前辈的近侍练士。」

「那就得造复座机龙了呢。」

两人和一匹飞龙，就这样继续抬头注视着天空另一端的半圆[fn:16]。

在突然决定的茶会结束将餐具送回厨房之后，萝涅一直想着桐人所说的话。

并非终结之壁的另一侧、世界是球形的、或是通向月亮的旅行的事情。而是最初的话题——
『再次爆发战争的可能性』。

萝涅觉得，人界的富饶让亚人族的不满不断积累，这确实是有可能的事情。然而，不管怎样
都没法相信这不满会和真正的战争——也就是再次武力入侵人界会联系到一起。

要说原因的话，现在暗黑界也颁布了名为《五族和平条约》的基本法，所有的种族都应该知
晓这部法律。虽然相比人界的法律更为原始，但其中还是写入了禁止杀人和掠夺的内容。

无疑，这对经历了数百年以力量决定一切——亦即只需遵从『力量即法律』的时代的暗黑界
居民来讲可以说是翻天覆地的大变革，因此在过渡期里，保留了不夺去性命范围内的《决斗
的自由》作为缓冲装置。然而如果变成战争的话，恐怕就没有如此手下留情的余地了。

而且，哪怕是暗黑界的居民，在名为『无法破坏法律』的灵魂封印这一点上和人界人相比应
该也没有任何差异。因此，在上次战争后仅仅过了数年，人界便可以接纳来自暗黑界的观光
客了……

「……萝涅，喂，你在听吗，萝涅？」

右肩啪的被拍了一下，萝涅一下子抬起了头。

本应在大教堂第四层大修炼场的一角进行《心意》的修行的，可却不知何时沉浸在思虑中了。
今天的课题是《端坐无想》，与《素因维持》和《柱顶直立》的修行不同，是很容易被杂念
引开的东西。

然而不知为何，旁边的搭档似乎因杂念而想要挑起话头。萝涅窥视了一下修炼场中央正在指
导下位骑士们修行剑技的教师——今天是《炽焰弓》迪索鲁巴特——的样子，小声向旁边道
歉：

「抱歉，做白日梦了……」

萝涅注意到虽然这么说，但这个状况下道歉总有点奇怪。红发的搭档嘟着脸小声说道：

「什么啊，你没听到吗？……我说了有想向你咨询的事情。」

「咨询？」

萝涅歪着头看向旁边。

从修剑学院时代就是伙伴的见习骑士，缇卓·施特莉涅恩带着一脸事态严重的表情点点头说
道：

「嗯。…………那个，我……被人提出请求了。」[fn:17]

「啊，交手吗！不要决斗了啊！」

萝涅条件反射般地小声喊了出来。缇卓红叶色的眼睛瞪了一下她，然后猛地摇摇头：

「不是啦！正好相反……不是交手……是相亲吗……那个……」

一时间没能明白对方在说什么，萝涅楞了几秒钟，这才明白了这句话的意思。

接着，萝涅不得不以全部心意压制自己想要「诶～～～～～！！」的一声喊出来的想法。取
而代之的是深吸一口气，停顿了一下，再细细地将气吐出。

吐出最后一口气后，萝涅这才战战兢兢地问道：

「…………那么，也就是说，是……结婚吗……？」

** 8

听到这句话的缇卓，视线落向前方的地面，轻轻点了点头。

虽然理所当然地想要问是被谁求婚了，但萝涅却并没有这么做。如今有可能向缇卓求婚的男
性只有一人，也就是上位整合骑士雷恩利·Synthesis·Forty-nine。

他对缇卓的感情，在两年前的异界战争时就已知晓。与其说是意外，还不如说这个求婚来得
太晚了。

萝涅在脑海里描绘着性格内向，但脸上的微笑从未消失的瘦小骑士，说了一句「恭喜你了。」

然而缇卓却像是想要制止一般立刻摇摇头低声说道：

「……我，还没决定要不要回复他。」

萝涅的眼睛惊讶地眨了一下。

「诶……为什么……？你不讨厌他吧，或者说你喜欢雷恩利大人对吧？你们两个不是一直都
在一起吗……」

听到她怯生生的问题，缇卓低下去的脸上，露出了和一直很精神的她一点都不像的哀伤神情：

「我喜欢他啊。可是，喜欢他的理由，我自己也知道。因为……雷恩利大人，有些地方和前
辈很像。」

「…………！」

萝涅不由得倒吸了一口气。

缇卓所说的『前辈』，并不是代表剑士桐人。还是修剑学院的初等练士时，和萝涅担任桐人
的近侍一样，缇卓也跟随了另一位上级生。缇卓从心底仰慕着在平稳的风度和柔和的微笑深
处隐藏着绝不输给桐人的坚强意志和剑力的他这件事，萝涅也知道得很清楚。

然而，他已经不在人世了[fn:18]。

萝涅一直相信红发的亲友已经不再悲伤了。将如同宝石一般的无数回忆珍藏在心底，如同过
去一般精神地再次前进——她是这样想的。

然而缇卓脸颊上的泪珠告诉她，这些想法全都错了。

萝涅皱紧眉头，咬着嘴唇，终于下定决心站起身，向位于修炼场中央大声指示着的迪索鲁巴
特喊道：

「师傅阁下！骑士施特莉涅恩身体不适，请就此暂停今日的修炼！」

留着短发的魁伟骑士，虽然投来了如同钢箭一般的视线，幸好他还是无言地点了点头。萝涅
赶紧让缇卓起身，行了一礼，在不让他人看到她的脸的情况下离开了修炼场。

萝涅就这样抱着缇卓的肩膀，快步走下大楼梯，走向大教堂后院的广阔的蔷薇园。通过时向
旁边据说过去曾是狱卒的，有着魁梧身材的园艺师急忙点了点头，进入迷宫一般的通道，在
谁也不会出现的深处找到小凳子坐了下来。

二月的蔷薇园里，最早开花的品种已经开始结出花蕾，深绿色的叶子和生有棘刺的藤蔓在寒
风中摇晃着。

缇卓红叶色的眼睛注视着蔷薇的花蕾和藤蔓，过了一会才低声说道：

「…………如果和雷恩利大人在一起的话，总有一天会变成回忆的吧，我相信是这样……嗯，
希望是这样。」

「缇卓…………」

萝涅将手轻轻放在她的背上。缇卓无力地倒下身体，头靠在萝涅的肩膀。

「可是……等到注意到的时候，我已经在雷恩利大人的笑容、话语、动作中寻找和前辈的相
似之处了……雷恩利大人也知道我忘不了前辈的事情，可他说这样也没什么。而且，他还向
我求婚了。我很开心……很开心……」

眼泪又一次流过长长的睫毛滴了下来。这次不仅是一滴滴泪珠，更一点点溢出，流过脸颊，
打湿了二人简朴的修炼服。

「虽然很高兴，但我真的不想忘掉……从心底想着想一直和前辈的回忆在一起……我也知道
的……所以，我……」

颤抖的喉咙里深吸了一口气，缇卓将脸紧靠在萝涅的胸前喊道：

「我想见他……想见前辈啊……！」

萝涅只能紧紧抱着全身颤抖哭泣着的亲友的身体，而她的眼中，也有热泪渗出。

两人在修剑学院担任近侍练士的时间不过一个月而已。然而对二人来讲，却是命运的相遇，
是一生中只会发生一次的奇迹。

在很久前的过去，她们曾发誓要跟随这个奇迹，永远不会爱上其他人。所以在某个程度上，
想着缇卓能够找到下一份幸福——然而萝涅现在才明白，这是何等自私的愿望。

因为和萝涅不一样，缇卓已经永远无法见到她所爱着的那个人了。对她来讲，甚至连牵手、
交谈、在远方注视都已经不被允许了。

萝涅没有可以安慰悲痛地呜咽着的亲友的话能够让她说出来。因此萝涅只是一直擦着亲友的
后背，抚摸着她的头发。

** 9

等到缇卓的眼泪好不容易止住，蔷薇园已经被黄昏笼罩了。

红发的亲友像是全部的感情都已经被压榨殆尽一般，就这样将头靠在萝涅的肩上，呆呆地仰
望着沉入地平线的索尔斯。

「…………抱歉，谢谢你。」

听到缇卓沙哑的低语，萝涅轻轻摇了摇头：

「没有的事……我才要道歉啊，缇卓……我一点都没注意到你的心情，只是自私的想着你和
雷恩利大人能够幸福……」

「没什么。我也有一半的想法想成为这样啊。」

缇卓深吸一口气后，以稍微恢复了一点力气的声音说道：

「我拜托雷恩利大人再稍微等一下。虽然在这段时间内，大概什么都不会发生……但是，我
有一个预感。」

「预感……？」

「嗯。从看到桐人前辈造的那个《机龙》的时候开始……还会有什么事情发生，有什么东西
被改变。」

缇卓的话让萝涅也想起了那一瞬间的事情。

在蓝天的背景下，不断上升着的银色光芒。注视着它的时候感觉到的痛楚又开始涌上心头。
确实在那个景象中，有着让人预感到大变革的什么东西。

「…………是呢。我也可以感觉得到。」

萝涅自言自语着，缇卓也轻轻点了点头。

两位少女骑士，就这样在石凳上又坐了一会。几分钟后，听到五点的钟声响起的缇卓站起身
来，看向萝涅，说出了令她意想不到的话：

「然后，萝涅又怎么样？」

「诶……怎，怎么样是指什么？」

缇卓红叶色的眼睛眨了一下，脸上露出淡淡的微笑：

「你有向桐人前辈稍微传达了自己的心情吗？」

「那……那种事情怎么可能啊！」

萝涅不由得喊了出来，缩起肩膀猛烈地摇摇头。

「那种事情……已经根本做不到了吧。我现在这样就可以了。」

「对我这么客气的话，真没有这个必要吗？」

萝涅对着一脸认真地问过来的缇卓再一次做出了坚决否定的动作：

「不是那样，我真的没什么的。因为……前辈已经有亚丝娜大人了啊。而且，还有总有一天
会回到这个世界的爱丽丝大人……人界军队的赛璐璐特将军……说不准还有法娜提欧大
人……」[fn:19]

「萝涅真是的。」

缇卓像是愣住了一般叹息着说道：

「桐人前辈不会只和其中的某一位结婚的吧。而且，现在前辈已经比皇帝还要伟大了，按照
帝国基本法，妻子可以有……三位？还是四位来着……？」[fn:20]

「我，我说啊，前辈不可能做那种事情的吧！」

萝涅又一次喊了出来，像是想要掩饰自己热的通红的脸一般站起身来：

「我真的这样就好了！缇卓还是想想自己的事情吧！」

干脆地宣言后，她转过身去。

红发的亲友再次看了过来，「哈」的叹息了一下后也起身站到萝涅的旁边。

「嘛，桐人前辈自己当然也不会说这种话的吧…………差不多该回去了，萝涅。霜咲它们恐
怕要饿肚子了。」

「嗯。我也想这么说……」

萝涅看向左右由蔷薇形成的墙说道：

「……缇卓知道回去的路吗？」

「……一直在哭的我怎么可能知道？」

二人互相对视了一下，在巨大的蔷薇迷宫深处，又一次发出了叹息。

当天晚上。

躺在位于大教堂第二十二层的自己房间的床上，萝涅却一点都没法让自己入睡。

——都怪缇卓说了奇怪的话。

萝涅恨恨地对着被厚石墙隔开的隔壁房间自言自语。然而马上就反省到她恐怕今晚也一定无
法入睡。

毕竟缇卓在今天，从出生到现在第一次被男性求婚了。

——地点是大教堂的哪里呢？又说了什么呢？

这样的想象很快就飘向了某个方向。

——如果，假如……有万分之一的可能性，桐人前辈向我求婚的话，那个人会选择哪里呢？
大教堂第九十层的望楼吗？……还是有着回忆的，修剑学院的后院呢？……嗯，说不准是用
飞行术式，在云层之上呢……[fn:21]

深吸了一口气，将被套一口气拉到头顶，萝涅打断了自己的思考。

绝对不能再有这样的想法了，她自言自语着。愿望就只有一个，希望像现在这样平稳的日子
能一直持续下去。此外的愿望就没有了。一个都没有。

萝涅转过身将脸埋在枕头里，老实的睡眠精灵终于来访，让她轻轻闭上了眼睛。

第二天，二月十八日。

然而，萝涅在早餐的时候得知，发生了让自己唯一的愿望都动摇起来的事件。

脸色大变地跑进来的下位骑士，跪在桐人面前，喊出的话是——

在央都圣托利亚，山岳哥布林族的观光客，杀死了一名圣托利亚市民。

** 10

即使是人界代表剑士和恐怕比他胆子更大的副代表，也一下子睁大眼睛，倒吸一口凉气。

桐人随后闭了一下眼睛，接着将刀叉放在桌上站了起来：

「亚丝娜，还有法娜提欧小姐，请掌握人界全部军队和卫士队的指挥权。让他们只执行通常
任务，不要对此次事件作出任何特别对应措施。——那个哥布林族现在在哪？」[fn:22]

后半句问向的是传来消息的下位骑士。还留着少年的影子的骑士仍然跪坐着，立刻回答道：

「是，已经收押于南圣托利亚的卫士厅！」

「知道了，辛苦你了！」

刚一说完，桐人的黑衣下摆便飘扬起来，他大步走了出去。这时萝涅才从茫然中回过神来，
慌忙站起来从大圆桌的另一侧喊道：

「请……请让我也一起去，代表殿下！」

听到这句话的桐人想了一下，但之后便点点头说道：

「麻烦你了。可以稍微抄近道吗？」

「啊……啊？诶……」

虽然跑了过去，但萝涅还是反射性地皱起了眉头。要说抄近道的话，《中央大教堂》位于圆
形的央都的中心位置，从南门出去就是曾是旧桑德克洛伊思帝国首都的南圣托利亚市。而且
像卫士厅这种重要设施，肯定位于从大教堂延伸出去的，贯穿城市的大街旁边，也就是说到
目的地怎样都是直线……

桐人用行动回答了萝涅的疑问。他毫不犹豫地走向的地方，不是位于广阔空间南侧的大门，
而是东侧的阳台。

跟在后面的萝涅，看向相当于大教堂约二十层高的地方，突然想到，难道他会……

此时桐人的左臂已经随着他「失礼了」的声音绕过了萝涅的身体。心跳不由得一下子加速——

随着「咻」的一声异响，视线被金色的光吞没了。

不光是风景。注意到自己的身体也被变为近乎透明的光之块，萝涅喊出了声音，但在此之前
二人便以猛烈的势头飞向空中[fn:23]。

大教堂逐渐远去。广阔的央都街区越来越近。已经不能用快来形容了。明明已经达到飞龙的
最大飞行速度的数倍，却几乎感觉不到风压。

等到花了几秒钟才明白这是全Under World内只有桐人能够使用的《光素转换飞行术》的时
候，二人已经如同一条闪电般降落地面[fn:24]。

随着再次响起的不可思议的声音，身体和装备恢复了原样。挥去袭向身体的轻微的眩晕感，
睁大眼睛，面前矗立着巨大的——虽然这么说但却怎样也无法和大教堂相比——石头建筑物。
用红色砂岩切割而成的有着粗糙质感的墙壁，无疑是南圣托利亚市特有的材质。

石阶上的正面出口被穿着红铜厚铠甲的两名卫兵守护着。看到萝涅等人出现的样子的二人，
露出了惊愕和讶异的表情。桐人大步走向带着警戒感提起大型斧枪的两名卫兵。

「什么人！」

卫兵喀嚓一声将枪交叉起来盘问。萝涅在桐人背后以极为严厉的声音喊道：

「人界统一会议的人！」

卫兵的视线捕捉到了短披风搭扣上装饰着的整合骑士纹章。虽然没有见习骑士在下方应有的
编号，但幸好它似乎发挥了足够的效力。卫兵们似乎被弹回去了一般立正站好，右臂碰到胸
甲，发出咔的一声清响。

桐人一口气从卫兵中间跑了过去。萝涅跟在他的后面。

这时萝涅才注意到，人界代表剑士并没有带剑，也没有穿着斗篷，只穿着朴素的黑色麻织衬
衫和同样是黑色的厚棉裤。这样也无法责怪不明情况的卫兵们了。

然而桐人穿过投来可疑视线的卫士厅职员们，直接跑向通往地下的阶梯。简直就像是已经知
道了引发事端的哥布林族人被囚禁在何处一般。

不，恐怕他真的知道。沿着石阶跑到地下二层时，萝涅的耳边响起了富有特征的刺耳尖声：

「……没有！俺什么都没干！什么都没看到！」

「少说谎了，你这个亚人！」

紧接着响起大嗓门的声音，之后又是咚的一声钝响。

卫士厅地下二层，是被黑黝黝的铁格子分隔开的牢房。虽然这么说，通过的多数房间的床上
都布满了尘埃，没有被使用过的样子。这是理所当然的。人界中原则上并不会出现犯罪者，
而极为稀少的情况中，也只会出现不记得禁忌目录和帝国基本法庞杂的内容的细枝末节而成
为『在结果上犯了细微的罪』的人而已——到现在都是这样。

通道的对面似乎是用于讯问的地方，是个没有铁格子的宽敞房间。昏暗的空间中放着一个粗
糙的木桌，而趴在桌子上的，无疑正是那个年轻的山岳哥布林族人。

他矮小的身体被健壮的卫士从后面按住。而站在正面穿着队长制服的男人，现在正要将拔出
的长刀从高处挥下：

「我倒要看看，砍掉一只手臂后你还说不说谎！」

刀上反射出蜡烛的光芒。

——住手！

萝涅正想喊出来，但在这之前——

随着「锵」的一声尖锐声音，如同被不可见的刀刃打到一般，队长的剑散着火花，飞向最内
侧的墙壁，最终钉在石墙的缝隙之间[fn:25]。

** 11

这无疑是桐人所使出的《心意剑》。全力奔跑着使出骑士最高奥义的黑衣青年就这样马不停
蹄地跑进讯问室喊道：

「到此为止！关于此案的全部工作，从现在起交由人界统一会议处置！」

「什么……」

呆然看着被打飞的剑的队长回头看向桐人，脸一下子涨得通红。他正想颤抖着修剪整齐的髭
须，大声喊出来的时候，目光捕捉到了萝涅的肩章。

队长的脸在表情再次激变的同时失去了血色，他和部下立刻单膝跪地，与其说是向着桐人，
不如说是向着萝涅低下了头。

被央都的众人做出这种反应的情况，实际上在不断增多。但不管怎么样都没有习惯的迹象。
毕竟萝涅在两年前还只是个学生而已。在异界战争中志愿参加人界守卫军，此后拼命地挥着
剑，等到注意到的时候已经被任命为见习骑士，而与此对应的觉悟或品格却并未跟上。

如果能够稍微正经一点的话，就不会有这样无地自容的想法了。萝涅在心中这样想着，注视
着桐人的举措。

从外观上只能让人认成是住在央都的普通居民的青年，先是向着缩起身体咔嗒咔嗒颤抖着的
山岳哥布林族的年轻人，像是要让他安心一般低下头，用平稳的声音问道：

「你的，名字是？」

哥布林淡黄色的眼睛剧烈地眨了一下，随后小声回答：

「…………奥罗伊。」

「奥罗伊吗。这个装饰羽，是锯丘的乌波利一族的吧？」

哥布林摇晃着从卷在额头上的皮带里伸出的蓝黄色羽毛点了点头。

「是吗，我的名字是桐人。目前是人界统一会议的代表。」

听到这句话，仍然低着头的两名卫士的身体微微起伏了一下，名为奥罗伊的年轻哥布林睁大
眼睛喊道：

「桐人……知道，俺知道！就是在抓虫子比赛里战胜了乌波利的白纽姆！」

虽然萝涅在心里因想着这个人到底都干了什么而惊呆了，但脸上却并没有露出表情。桐人从
容不迫地点点头继续说道：

「那时候拿到的百人长奖牌我还留着呢。那么奥罗伊，现在开始我要先从这边的卫士们开始，
然后到你，按顺序问话。不会因这些内容就下决定处罚的，所以冷静点，把发生的事情告诉
我。」

被催促着站起来的卫士队长，带着恐惧中夹杂着些许愤懑的表情对桐人说出了下面的话：

——今天上午约11时30分，位于南圣托利亚四号街的卫士所，接到了市民通报的『卡鲁街旅
店里有个亚人拿着刀发狂』的消息。赶到的时候，有个哥布林族拿着带血的短剑站在旅店二
楼的走廊，而一个人类男性流着血倒在里面的房间中。那个男人是旅店的清扫人员，心脏被
一刀刺穿，天命已经被完全消灭。根据状况，他们判断是那个哥布林族用短剑杀死了清扫人
员，立刻将他带到卫士厅开始讯问——

而与此相对的，山岳哥布林族的奥罗伊所说的话则是这样的：

——奥罗伊和同族的五名年轻人一起，在三天前来到圣托利亚观光。同伴在早餐后出去了，
而奥罗伊因为肚子不舒服，在旅店的房间里睡觉。中午之前，有什么人敲了门，但他走到外
面时候，已经没有人影，只在走廊里有一把短剑。他捡起短剑注意到上面有血，之后就被从
楼梯上来的卫兵队在什么都不知道的情况下逮捕了。

「……俺什么都没做……也什么都没看见……」

奥罗伊刚一说出这句话，队长就无法忍受地喊了起来：

「喂喂，我都说过别说谎了吧！那把短剑根本就不是人界的东西！使用那种粗糙的铸造品的
就只有亚人而已！」

「不对，不对！那把剑虽然很像但绝对不是！哥布林的剑在剑柄处会有氏族的纹章的！那把
剑没有，所以肯定是假的！」

队长听到奥罗伊刺耳的反驳，站起来打算喊回去，却被桐人用右手按住了。桐人之后说道：

「检查一下就知道了。队长，那把短剑现在在哪？」

「……啊，保管在一楼的武器库。」

「不好意思，可以让我看看吗？」

听到这句话的队长向部下使了个眼色。年轻的卫士像是被弹起来一般跑过石板——

过了大约五分钟后，卫士还没生出胡子的脸上带着发青的神色回来报告：

「…………没有。」

「什么，你说什么！」

将头缩到极限的卫士对高声怒吼的队长重复道：

「确实没有。武器库里没有那把有问题的短剑。」

** 12

两小时后。

回到《中央大教堂》——这次是坐马车——的桐人，将人界会议的主要人员集合起来说明了
情况。随同他同行的萝涅，作为特例被允许坐在圆桌旁边。

首先打破了充满第五十层·主议事堂这一空旷空间的静寂的，是副代表亚丝娜：

「……那个名为奥罗伊的哥布林现在在哪？」

「啊，我把他从卫士厅带到这里，总之先让他住在第四层的空房间了。在门口设置了警卫，
事实上算是软禁……」

对皱起眉头的桐人，亚丝娜一脸郁闷地回答：

「在解决事件之前，这也是没办法的事情……」

这时从圆桌的对面，响起了骑士迪索鲁巴特低沉的声音：

「不管怎样，二位，可以确信这个哥布林实际上并没有犯下杀人罪行了吧？」

「——啊，我也是这么想的。」

桐人点了点头，将双手在桌上交叉，静静说道：

「从Dark Territory前来人界的观光旅行，是统一会议作为两个世界间的交流事业而运行的。
在越过《东大门》的时候，有必须确认禁止事项的义务。虽然是极为简单的规则集合，但其
中也明确地标示了禁止伤害和杀人的内容。也就是说，如果奥罗伊打破了这个禁忌，杀死了
旅店的清扫人员的话……」

「右眼一定会破裂。」

接过话头的是骑士长法娜提欧。

坐在圆桌边上的众人，在片刻的无言中玩味着这句话的含义。

Under World的所有居民，无论人类还是亚人，都一定会被施加名为《右眼的封印》的术式。
这是当违背法律和规则时，右眼会发生剧痛，而采取实际的违反行动时眼球会被吹飞到毫无
痕迹残留的可怕存在[fn:26]。

而且，普通人也根本不会有违背法律的想法。萝涅自己过去虽然曾数次直面《禁忌目录》和
《帝国基本法》的不公平之处，但却一次也没有反抗过它们。带着这样的想法行动，而最终
右眼破坏的，在目前能够确认的Under World三百年的历史中，也只有三人而已。

而且，山岳哥布林族的年轻人奥罗伊的双眼没有任何异常，这一点萝涅也亲眼确认了。

「……虽说这样……」

老实地说出自己想法的，是整合骑士雷恩利。

向缇卓求婚，现在还在等着她的回答的年轻骑士，似乎因此而带着忧郁的神情，继续说道：

「杀人行为对奥罗伊以外的百姓可以说是最大的禁忌。哪怕是有着超越大多数法律的权限的
我们这些整合骑士，也无法将毫无抵抗的普通人的天命全部消除。也就是说……如果奥罗伊
之外的某个人杀死了那个清扫人员的话，那个人……」

「——他右眼的封印会被破坏，就会变成这样的情况。」

桐人低声说着，嘴边露出了苦涩的微笑：

「真是讽刺。如果是过去曾经存在的《自动化元老机关》的话，现在应该已经查出那个犯人
了。」

但亚丝娜很快就摇摇头说道：

「不可以依赖那种不人道的机制了。」

自动化元老机关，是作为人界会议前身的神圣教会运营的，将数十位高级术士的天命和自我
意识加以冻结，远程搜索违背法律之人——也就是人造的监视装置。虽然战争后束缚《元老》
的术式被解除了，但他们都未能恢复自我意识，在数日后陷入了永恒的长眠中死去了。

桐人似乎想起了这些事情，重重吐了口气回答道：

「啊，我知道了。那个……总感觉，有消除不掉的违和感。」

「比如说？」

桐人的黑眼睛看向提出问题的法娜提欧：

「要怎么说呢……过去打破了右眼封印的三个人，都不是只为了杀死什么人而这么做的，而
是想要坚决抵抗不公平的事物的强烈意志驱使他们这么做了。这样的话，对犯人来讲，受害
者是不论怎样都一定要杀掉的绝对的恶之象征……虽然说是这样没错。」

桐人看了一眼桌上的资料继续说道：

「然而，被杀死的名为亚杰恩的清扫人员，在调查的范围内，是没人会去憎恨的人。他长年
以来在大贵族的私人领地上种植小麦，去年被解放后就在旅店工作，对Dark Territory来的
客人们也毫无隔阂地亲切相待。被抓起来的奥罗伊也说他对亚杰恩很有亲近感。」

「也就是说，那位亚杰恩先生，不可能出现对什么人行使不公平权力的情况……是这样对
吧？」

听到亚丝娜的问题，桐人干脆地点了点头。

「怎么想都不可能。而且……还有那个消失了的凶器的问题……」

在卫士厅的地下牢房里，听到『似乎是用来杀死亚杰恩的短剑从武器保管库里消失了』的报
告的桐人立刻以人界统一会议的名义向厅内的全部卫士质问了。然而没有一个人曾经将它拿
出去。应该没有会反抗指挥着包括卫士厅在内的人界军的统一会议的命令的卫士。也就是说，
那把有问题的短剑，从旅店运送到武器库保管后，被外部的什么人偷走了——或是自动消失
了，就是这样的情况。

「关于这个问题，有人有意见吗？」

桐人环视圆桌问道。

迪索鲁巴特随后发言：

「虽然听说是粗糙的铸造武器，但也不会只使用一次天命就消耗殆尽，在保管中全损吧？」

「嗯……好歹也是金属武器，就算这种情况也不会完全消失，还是会作为铁屑存在一段时
间……」

「呒……确实是这样。」

看着双臂抱在胸前哼着的巨汉，萝涅的脑海里突然出现了一个想法。

看向圆桌的左右两侧，确定没人打算发言后，她这才怯生生地举起了手。

「哦，萝涅，有什么想说的吗？」

「啊……有的，那个……师傅，哦不，是迪索鲁巴特殿下，在箭筒里准备的箭用光的时候，
会用术式补充对吧？」

听到这个问题的弓使重重地点了点头：

「唔。但优先度相比真正的钢箭有所下降。」

「如果和那个一样的话……凶器的那柄短剑，说不准是用钢素生成的《暂时的武器》……不
知道是不是这样……」

** 13
萝涅指出的情况让议事堂陷入了短暂的沉默。

打破这个沉默的是桐人。并非声音，而是动作。他将右手随意伸到桌上，然后眯起眼睛。

手掌下突然亮起了三个银色光点。是连术式和起动句都一并省略生成的钢素。三个光点随后
融为一体，闪着光的同时开始变形。锐利的一端弯曲，而相反的一侧则收缩成细长形状。

随着咚的一声落到圆桌上的，是过去萝涅多次见过的，哥布林族善用的单刃短剑。厚实的刀
身和粗糙削制的刀柄都充满了沉重的存在感——但即使如此，也仍能看出与真正的短剑多少
有些差异。

首先，表面的质感太过光滑了。此外，真正的短剑刀柄上卷着染色的皮革，但这把短剑的刀
柄却和刀身一样是金属质的。只要看到这把短剑，立刻就能分辨出这是用钢素制造的代替品。

桐人拿起自己制作的短剑说道：

「哪怕是对哥布林族的短剑极为了解的我，做出这种程度的代替品也是极限了。然而有问题
的凶器，可是让奥罗伊将其与真货混淆的精密制品……如果是这样的话，那把凶器恐怕是身
居高位的术士花费了相当时间制成的。」

随着他的话音落下，轻轻响起了「嗪」的一声金属声音。是桐人用极轻的心意击中了短剑。
然而仅仅是这样的动作，就让这个《暂时的武器》天命全损，如同玻璃一般粉碎，变为光之
粒子飞散，连一个碎片都没留下。

「……要是这样，问题可就严重了。」

骑士长法娜提欧摇晃着黑发低声说道：

「现在圣托利亚所有的高位神圣术士应该都处于人界军队……或者说是这个统一会议的指挥
之下。是他们中间出现了反叛者么……还是说……」

——是Dark Territory的暗黑术士所为么。

被省略的这句话，让在场的所有人从心底揪了一下。

如果是暗黑术士侵入圣托利亚，为了策划什么阴谋而杀死了无辜的一般人的话，可就是比哥
布林族的奥罗伊因突发的冲动而杀死了亚杰恩的情况让人恐惧数倍的事态了。决不能让刚刚
开始交流的人界和暗黑界间再次发生战争。

「不……可能这就是目的吗……？」

传来了桐人沙哑的声音，但他立刻就回过头断然说道：

「目前所有的情况都还没有超过推测范围。在继续调查的同时，也需要将此事对市民的影响
控制在最低限度。哪怕无法阻止谣言扩大，也绝对要防止因此而诱发的第二次、第三次事
件……亚丝娜，人界军队那边如何？」

被问到的副代表立刻点头回答：

「已经拜托莉娜……不，赛璐璐特将军负责通常任务外的治安维持工作了。虽然将军倒是很
爽快地答应了……但果然旧大贵族的派阀里还是有将Dark Territory来的所有旅行者逮捕起
来这种强硬论调存在呢。虽然已经以统一会议的名义下达命令，可以稍微抑制住他们……」

虽然一瞬间停下了话，但之后榛色的眼睛又闪现出了光彩。亚丝娜继续说道：

「但如果再次出现同样的事件，那么命令就会引发对我们压倒性的不满和不信任吧。而且如
果我是这起事件的幕后操纵着，肯定会引发下一个事件的。」

「嗯，如果是我也会这么做。」

桐人的回答里夹杂着叹息，接着将双手如同要握紧般轻轻拍了一下说道：

「——那么，统一会议的对应措施就是以下四点。第一，公布事件的犯人还没被锁定的消息。
第二，对亚杰恩的遗孤进行充分的说明和赔偿。第三，进入对事件调查的最大动员状态。第
四……与暗黑界的五族会议尽早达成协议。有什么意见吗？」

法娜提欧立刻举手，带着疑惑问道：

「尽早……但就算这么说，离下次和暗黑界侧的会谈还有将近一个月的时间。要将预定时间
提前吗？」

「不。」

桐人摇了摇头，像是极为随便地回答道：

「我去奥布西蒂亚见伊修凯恩。」

会议结束的时候，索尔斯已经没入了西边的地平线。

萝涅急忙跑向中央大教堂西侧的飞龙厩舍，向已经将月驱带来的缇卓挥手致意：

「对不起，我来晚了！」

听到这个声音从草地上立刻抬起头的淡黄色幼龙，「咕噜噜」地鸣叫着跑了过来。萝涅抱住
幼龙软软的身体，搔着幼龙的颚下，又对着缇卓说道：

「谢谢你了，缇卓。这个谢意……也是，精神上……」

「你说的话越来越像桐人前辈了。」

摇了摇头站起来的红发亲友换了一副表情问道：

「然后……会议怎么样？」

与缇卓并排坐在厩舍墙边的板凳上的萝涅将临时会议的梗概告诉了她。

面露难色地听完大致内容的缇卓慢慢低声说道：

「有种什么……不好的感觉，呢……」

「嗯……人界人应该不会杀人，虽然这一点至少骑士他们也想到了……」

「但也有利用法律和规则的盲点，将其歪曲以求方便的家伙呢……」

事实上，之前《四帝国大乱》便是因当时的皇帝们下达了将新组织的人界统一会议定性为反
叛旧神圣教会的军队而加以处决的敕令引起的。如果要将在一度被歪曲了的法律的强烈拘束
力下袭来的四帝国近卫军加以镇压，除了讨伐诺兰高尔思、威斯达尔思、伊斯塔瓦利耶思、
桑德克洛伊思四帝国的皇帝并将敕令废弃之外便再无别的办法。萝涅和缇卓突入北圣托利亚
帝城，最终与皇帝克鲁格·诺兰高尔思四世直接以剑对决时，也感觉到了那个人强烈地膨胀
着的自我意识。

二人不由得同时搓了搓手，缇卓像是想让气氛改变一般开口说道：

「嘛，要是这样的话，就把月驱再交给我照顾一阵子吧。」

「诶？为什么？」

看着缇卓愣住的脸，亲友微笑着说出了不得了的话：

「因为你肯定会去的吧？跟着桐人前辈到奥布西蒂亚去啊。」
** 14[fn:27]
从人界中央都市圣托利亚到暗黑界的首都奥布希迪亚，实际上有超过是三千千路（UW里的计
量单位=1000梅路）的距离。

骑飞龙一天走一千路要用三天，坐马车的话大约要一月，步行的话时间更是这之上数倍。

在之前的异界战争中，作为暗黑界首领的皇帝贝库塔，通过使用秘药和秘术，用五天的时间
让五万大军从奥布席迪亚移动到东之大门。这之后被证实，喝了这种秘药的人，亚人或者野
兽，天命的最大值会减少，是以此作为代价的恐怖的物品。不过，人族因为有马或者马车所
以并没有人喝秘药，但是因为徒步移动的亚人们现在还处于天命减少的状态，现在也可以看
到卡塞多拉鲁的修道士正在拼命寻找解毒方法。

这一次由于事态紧急而决定火速访问奥布希迪亚的人界代表剑士桐人，当然考虑和罗涅一起
骑飞龙过去。但是从卡赛多拉鲁这里到南圣托利亚的卫士厅所需要用到的风元素飞行需要大
量神圣力，在神圣力薄弱的塔酷特力不能长时间稳定使用。

除此持外，桐人前辈因为没有自己的飞龙，必须要和迪苏鲁巴特或者雷利共骑一条龙，如果
是两人同乘一条龙的话会增加飞龙的负担，总之自己是不可能想出什么好的办法了，这样想
的罗涅和提洁只好放弃了。

至少帮忙为旅行做准备，于是罗涅从飞龙厩移动到代表剑士所在的卡塞多拉鲁三十层，遇到
了亚丝娜，并别一脸担心但是又无奈的表情告知：桐人的话现在在工厂哟。

伴随着副代表剑士的不安走了很长一段路，走到了卡塞多拉鲁的后面，也就是曾经的牢房所
在的场所。到那之后，顺着宽广的斜率下去，就可以从敞开的工厂大门窥探到里面的场景。

内部是向下延伸约有三十梅路的大空间，左右两边各有五六个锻造师和细工师，发出㖦嚓咔
嚓的很有气势的锤音。而在这之中，坐立着被无数的光速灯笼照明的巨大人造物。

那是和前几天发生大爆炸的一号机相似的金属飞龙，也就是“机龙”。在那一旁的桐人和工
厂长赛多雷师傅正在交流意见...似地大声呼喊。

“所以说，你到底要让我说几次啊，桐小哥！（キリ坊）这玩意现在还在调整中，是不可能
做到全力飞行的，拜托你好好想想！”

“没关系的，老师，这次不是垂直上升而是水平飞行，换装成靠风力滑行的大型机翼就行
了。”

“可以个鬼啊！你给我听好了，您老人家的目的地可是暗黑界的首都啊，连试飞都还没有，
就要来回飞六千千路，根本不是人能做到的事。”

“冷静冷静，这家伙的热素封闭仓比一号坚固一倍，机体也是老师注入心血打磨出来的，就
算飞一万千路也没有问题，是这样的吧？”

“那，那当然，那么简单就坏掉的也就只会是细工修饰的地方（原文：簡単に壊れるような
ヤワな細工はしとらんが，这句不太明白，还请大神备注）....... 不对！不对！不行！不
行！每次您老人家用那种花言巧语，最终惹出的祸都麻烦得让人坐如针灸。（オオヌマアブ
に尻を刺されるより厄介なことになっとるんじゃからな！）

听了两个人的对话，罗涅感觉自己的脸色苍白（顔から血の気が引くのを感じていた，血液
从脸上退去） 桐人既不是要乘飞龙也不是要坐马车，而是要乘坐这个机龙二号飞到奥布席
迪亚。前几天发生的大惨案还历历在目，罗涅赶紧摇摇头，想着两个人跑过去。

“不，不行的，桐人前辈。赛多雷工厂长说得对，如果事故又发生可怎么办啊!”

“早上好，罗涅，那么近的话衣服上会沾到油的。”

把罗涅的左臂拉开离机龙五十瑟（另一种长度单位），桐人从笑容转变成严肃的表情。

“嘛，如果有什么问题的话我也可以靠自己的力量飞行，整合骑士的各位都很忙，我也不好
意思让他们把我送到奥布席迪亚，乘马车的话又要一月...情况或许比我们想到的还要紧急，
就算早一天也要赶快通知暗黑界，如果晚了不知道会发生什么....”

“但是，就算如此也很危险啊，前辈。”

再走近一步，罗涅拼命先要说服桐人。

“不管杀了清洁工亚泽，并把罪过嫁祸给山地哥布林的人是谁，他都不会受到禁忌目录的束
缚。那么，等前辈离开圣托利亚再进行偷袭也....不对，或许这次事件就是让前辈去奥布席
迪亚的陷阱也说不定！”

“啊...确实那种可能性也不是没有。”

小声嘀咕着，桐人像是在思考什么而陷入沉默。

打破沉默的，是老人深沉的叹息。

“嘛，老朽啊，虽然说想和暗黑界的工匠们交流经验可能是在痴人说梦，但是也不想回到过
去那种状况。”

“诶？老师你已经是大师了，还有要学习的事情吗？”

对于桐人的提问，赛多雷捋着自己灰色的胡子，面带苦涩。

“那是当然的，守备军从战场带回来的暗黑骑士的剑和铠甲，光是外表就看得出来很精致。
从最初使用的钢的种类，老朽就不知道。矿石和制造方式估计临死都不会明白。”

充满伤痕的大手，轻轻敲打着机龙散发着银光的外板，赛多雷如是讲到。

“桐小哥，热素压力计已经到达八成了，还有还是快点决定压力的计量单位比较好。”

“噢！不愧是老师。压力是...一平方瑟上一千姆（重量单位）的重量。”

“请，请等一下！”

对于两人的对话，罗涅慌忙打断。

“机龙的危险性先不说，前辈被袭击的危险还没有解决，相比一个人去暗黑界的话，还是旁
边多一个人会比较好...”

这样说着的罗涅想着机龙的头部仰望，看到开口的位置，突然闭上了嘴。

金属质的椅子，被玻璃围绕着，姑且被叫做操纵席的地方，相比一号机龙要更长。仔细一看，
操纵席的更深处，好像有安装了另一个椅子。

“....那个，前辈？”

“怎么了？”

“这个机龙二号, 难道说可以做两个人？”

“恩..嘛，一号机是因为冻素供应不足而发生爆炸，不过那也是在预料之中。这家伙可以的
靠两人生成冻素，但就像刚才说的，如果水平飞行的话一个人就足够了。”

对于预感到什么而滔滔不绝地说明的桐人，罗涅抢应道。

“我明白了前辈，为了应对袭击的危险，会配备护卫进行防范”

“护，护卫？”

“虽说如此，刚才前辈也说道了上位骑士的大家都很忙，所以这个任务请让作为见习骑士的
我负责！”[fn:28]

“诶，诶诶诶诶！？”

赶在桐人说出什么之前，罗涅右拳放在胸前，左手放在剑柄上，做出骑士礼，并对接受任务
命令进行宣言。

对于晕头转向的桐人，一旁的赛多雷噶哈哈地，愉快地笑了。

“这下子是桐小哥输了，话虽如此， 罗涅姑娘也成了不得了的人了呢。（ロニエ嬢ちゃん
もずいぶん逞しくなったモンじゃわい）”
** 15
对于总算从桐人那里得到许可的罗涅来说，接下来的事情也会很辛苦。

这次当然是第一次去暗黑界的首都奥布席迪亚，在桐人的随行名单里只有自己一人的情况下
自己也没有任何经验。到底应该怎么样准备才好呢，从工厂回到自己二十二层的房间里，将
衣物和大量的小物品罗列出来，不禁开始嘀嘀咕咕.....

突然有人敲门，想着“大概是提洁吧”的罗涅一边回应道“来了”一边走到门口。

“太好了，麻烦你帮忙收拾行李吧”

这么说着得罗涅打开门，面前站立的却不是红色头发的伙伴，而是身穿珍珠色骑士服，有着
栗色长发的美丽女性剑士。

“啊，亚丝娜大人”

慌忙想要做出正式礼的提洁，被亚丝娜伸出右手，微笑地制止了。

“繁忙的时候来打扰真是不好意思，罗涅，可以和我一起去个地方吗？”

“好，好的，那么要去哪里呢？”

点了点头的罗涅，开始跟在亚丝娜后面走到走廊上。

如果这里是北圣托利亚的修剑士学院，像这样被上级剑士交出来，一定会被很多学生包围并
被问道“你最近是不是状态不佳？”想必会是这样的展开。但是在卡塞多拉鲁这种事是不会
发生的。

但是，罗涅单方面对于亚丝娜还有一点点害怕，这也是事实。对方既是人界代表副剑士，也
是从UnderWorld 外侧的异世界过来的人。而说到个人因素，那是一个谁都不能告诉的理由....

亚丝娜降临Underworld的时间，是一年三个月前异界战争的一个黑夜。

罗涅和提洁参见了人界军的诱饵部队，被皇帝贝库塔率领的暗黑界军队猛烈追击。就在诱饵
目的快要达成时险些被全灭。那是罗涅自己也迎战了潜入军队后方的暗黑界将军，但是转瞬
间剑就被打落，就在抱着必死的觉悟时，亚丝娜在那里出现了。

漆黑的夜空中浮现出亚丝娜带有光辉的身姿，除了自己家中装饰用的绘画还有修剑士学院中
的壁画所描绘的女神史提西亚之外，没有别任何与之相似的人了。亚丝娜拿起虹色的细剑，
在地面上制造出巨大的深坑，把打算杀死罗涅的暗黑将军给驱逐了，目睹了这样神威的罗涅，
对于亚丝娜是史提西亚神这件事深信不疑。

后来才明白，亚丝娜和桐人，顺便还有袭击罗涅的暗黑界将军还有皇帝贝库塔，都是
RealWorld人，虽然是明白了，但是罗涅感谢和尊敬的想法，在这一年里却是完全没有淡化。

尽管如此，在两人独处的时候，罗涅心里还是感到有一点点痛。

那是因为亚丝娜，现在是公认的桐人的特别的人，从亚丝娜降临Underworld，帮助心智丧失
的桐人，那样一心一意地。（その一心からだったのだ。）

在窗边阳光下随意谈话时，在吃饭的座位上交递装盐的小瓶时，在训斥代表剑士的鲁莽时，
罗涅都能强烈地感觉到桐人和亚丝娜之间结缔的深深的爱意[fn:29]。

虽然也考虑过介入两人之间，但是早晚...在不远的将来，两人会举行结婚仪式吧，那个时
候还是想要由衷地祝福的。

但是...但是... 不论过去多久，胸口的疼痛消失这件事情，也绝不可能发生吧。

为了回避心中的冲突，四处张望一下，发现已经到了卡塞多拉鲁三层的大武器库前面。

印有索鲁斯和提拉利亚浮雕的大门，曾经是得到骑士长，元老长还有最高祭司许可才可以打
开的。现在，只要在旁边的台子上写下名字，不论是谁都可以参观，当然，从里面拿走东西
还是不行的。

在最近在央都用来代替羊皮纸的雪白纤维所制作的“麻纸”的本子上，用新开发的金属笔写
下名字的亚丝娜，毫无顾虑地打开大门进去了。因为已经是傍晚了，并没有别的参观者的身
影，迎接两个人的只有静静的黑暗。

亚丝娜从们旁边用双手取出一个玻璃管，并开始吟唱神圣术的句式。

“System call, generating and luminous element”

管中立刻生成了十个光速，用手指触碰那一根，这次是风素。由于那个压力，十个光速开始
在布满管子的墙上巡回，把整个武器库全部照亮。（するとその圧力で、壁に張り巡らされ
た管の中を十個の光素が移動していき、武具庫全体を明るく照らす。）

和麻纸还有金属笔一样，这个光素管还有工厂的光素挂灯都是桐人和亚丝娜发明的。和火把
还有油灯不同，没有引发火灾的危险。光也更白更稳定，既是玻璃破了稍微泄露一点也没关
系，只要使用神圣术定期补充就行。在术士众多的卡塞多拉鲁完全可以替换油灯，但是想在
圣托利亚的街区普及还是不可能的。

在十个光素照明的瞬间，整个大武器库变得光彩夺目，既是不是第一次来这里的罗涅也不禁
屏住呼吸。

曾经在修剑士学院大练习场里的五颜六色的铠甲，被整齐地放在这里，高高的墙壁上还挂有
各种各样的剑，枪还有斧子。中上位整合骑士被给予的神器级武器，好像也有，但这对于见
习骑士的罗涅是分辨不出来的。

“还是一如既往地看起来很厉害啊”

罗涅不禁发出感叹，亚丝娜点点头。

“却是呢，不过这之中很多一部分被琳娜还有圣露露多将军的人界军借过去使用了，虽然桐
人也想把大部分卖了换钱，这样人界边境还有暗黑界都可以得到支援，但是迪索鲁巴特他们
却强烈反对。”

“恩，还真是困难的问题呢”

这样回答者，耸了耸肩。

支援暗黑界确实很重要，山地哥布林里有许多饥饿的孩子这点罗涅自己也亲眼见过并理解。
在耳边还能回响起“这样下去，一定会又来一次战争的。”桐人的话语。

如果万一真的发生的话....当然希望北圣托利亚的家人，学院的学生，卡塞多拉鲁的骑士，
术士当然还有缇卓，当然都希望他们没事。为了保存珍贵的战力，留下这些武器也是必要的
吧，不禁这么想。

拍了拍罗涅的肩，亚丝娜为了改变气氛不禁做出鬼脸说道。

“所以说，见习骑士罗涅殿下现在的武器权限是多少呢？”

“诶，诶诶！？为什么亚丝娜大人要提这件事？”

“好啦，好啦”

窥视这位人界第二的剑士的脸，谁都不得不遵从吧。那样的话最近没有确认过，如果下降了
可怎么办...一边想着一边用左手在空中描绘出记号，然后轻轻敲了下右手。

出现的史提西亚之窗，是一个人究极本质的体现，也就是桐人所说的《个人情报》，最后再
非极其特殊情况下最好不要看的礼仪，亚丝娜向后退了一步。罗涅则念出在神圣语【Ｏｂｊ
ｅｃｔ　Ｃｏｎｔｒｏｌ　Ａｕｔｈｏｒｉｔｙ】 处记载的数字。

“那个....是39”

“很厉害嘛。已经变得和有编号的骑士们差不多了。”

微笑着的亚丝娜。一边说着“那么就”一边走到内侧的墙壁处，从罗列着无数颜色和设计各
不一样的单手剑中挑了四把，一只手拿两把放到附近的台子上。

“这些是优先度38和39的，选一把自己喜欢的吧，罗涅。”
** 16
对于亚丝娜意想不到的话，罗涅一时间不知道该说些什么。

说道优先度39，是虽然达不到神器的水平但也绝对是名剑，已经算是魔剑（川原的魔剑是指
比神器弱点的武器，并非那些带有副作用的武器。）的范畴了。实际上，台子上的四把剑全
部都流露出精致的细工水准。不论哪个刀身都是久经打磨，像颜色不同的镜子闪耀着光辉。
法那提欧团长手下的《四旋剑》都还在使用制式剣（就是量产剑，看过高达的朋友应该都知
道量产意味着什么...），所以这绝不是区区一个见习骑士可以得到的东西。

“万万不可，亚丝娜大人！”

罗涅头和双手同时摇动，亚丝娜则笑着说道。

“你那个动作和桐人有些像呢”

“诶...是这样吗”

“呵呵，不用那么谦虚也可以哟，我已经得到法那提欧团长的许可了，何况你是那场战争中
战斗到最后一刻的勇者啊。”

“...就算那样...”

罗涅再一次摇头，但是这次是低着头慢慢摇动。

“...我啊，被亚丝娜大人，雷利大人，还有许多卫士们，从RealWorld 赶来救援的众多骑
士们保护着而已，”在那个黑色骑士（PoH）对桐人做残忍的事情的时候，我什么都做不了。”

“绝对没有那样的事。”

轻轻的上前一步，亚丝娜的双手温柔地绕道罗涅的后背，紧紧贴上那因为太多畏惧而颤抖的
身体。甘甜清香的茉莉花香气还有那隐约的温暖立刻将紧张溶化掉。

“替我（くれた，一种自谦的表达形成，对表示尊敬的人用）保护不能动的桐人，罗涅，缇
卓还有爱丽丝，你们比任何人都要尽力，对于我来说，你们才是真正的英雄，不论怎么感谢
你们都不够。”

将这句话的时候不由自主地带出了点点泪水，罗涅则低声说道。

“爱丽丝大人....要怎么回来呢...”

片刻之后，亚丝娜坚定地回答道。

“我知道爱丽丝在RealWorld一定是很精神的哟，正因为她是这样的，才是连接两个世界的
希望... 一定，一定，总有一天会再见的。”

双臂再一次用力紧紧地拥抱罗涅后，就离开了，亚丝娜再一次微笑道。

“好了，选一把剑吧，这不光光是用来保护你自己的，也是用来保护桐人的武器。”

话已至此，罗涅也无法再推辞了。

再一次，看着亚丝娜选择的这些剑，四柄剑无论是剑柄还是剑身都在单手直剑中属于纤细的，
可见不单单只有优先度，还是按照罗涅的体格选择的。

这也是靠桐人一步步解析才在最近明白的事。优先度超过30的上位武器防具还有饰品，不仅
有在史提西亚之窗上显示的天命值，还有可是说是类似《隐藏能力值的设定》，本身可以带
有耐性应对各种属性攻击，以及毒或者诅咒等，反之也可以帮助生成这些特定的因素。例如
在特定的地方可以提升天命的回复速度，让双眼具有更好的也是能力，甚至还发现会被狗喜
欢这样奇怪的效果。（原文为汉字“奇妙”，受某怕狗的“老鼠”之要求，特改为奇怪。）

此外，现在已经死亡的最高祭司administrator过去赐予整合骑士们的神器，也发现其“能
够强化各自擅长的神圣术”这样的隐藏性能。也就是说，administrator看重骑士的能力配
备武具时，可以看得比史提西亚之窗更加详细得。《把握隐藏属性的神圣术》，为了实现这
个卡塞多拉鲁的术士们似乎相当努力的样子，但是想要实现恐怕还需要很长一段时间吧...
桐人是这么说的。

现在罗涅面前的四把剑，应该也有不一样的隐藏性能，但是光看外表是不可能知道的。按顺
序装备每一把，然后使用所有属性的神圣术，或者跑到卡塞多拉鲁的外边调查天命回复速度，
这样或许能稍微感觉到吧，不过明天就要出发了，也没有余力真的实施了。

到底应该以什么标准选择好呢，就这样毫无头绪地站着，似乎有微弱的声音从记忆深处传来。

“我啊，以前认为这个剑太重了，别说挥动，光是拿起来就已经很辛苦了。”

一边保养着白色的剑身上带有星星青色的美丽的长剑，负责近侍缇卓的上级修剑士优吉欧一
边说道。在他傍边的上级修剑士桐人，一边打磨自己的黑剑一边默默地浮现出笑容。附近的
桌子上放着的沏好的克西路茶和烤制的蜂蜜派散发出美妙的香气。已经快两年了，自那令人
怀念的场景。

当时，罗涅和缇卓都是入学北圣托利亚的帝立修剑学院的初等练士，因为碰巧入学成绩很好，
成为从一百二十名入学生中选出的十二名近侍练士。因为想要自由操纵优先度15的白金樫做
的木剑，于是询问指导生们使用沉重的剑的方式。

虽然外表看起来奢华纤细，但实际上远远比钢铁制的大剑还要重的多的《青蔷薇之剑》，优
吉欧轻轻举起，继续说道。

“硬要说原因的话，只要剑士的武器装备优先度高于武器自身优先度，剑很沉的感觉也就不
存在了。但是，我认为剑和剑士的关系并不是可以单单用数字表示的。仅仅因为自身的权限
就选择低优先度的武器，这样草率的处理而不好好抉择的话，武器是不能回应你的意思的。
从前的我不能挥动这把剑，不仅仅是权限不够，而是对剑注入的爱情不够.... 我是这么认
为的。

“对剑的...爱情”

对于第一次听到的这些话，罗涅和缇卓都感到很疑惑。

两人都出身于下等贵族六级爵士家中，亲人们也都以自己的孩子可以成为不用害怕上级贵族
的裁决权的四等确实作为梦想，不惜花重金用来修炼剑技。在激烈的战斗中弄折木剑，不要
说会惹怒家里人，反而会让家人高兴地马上换把新的。对两个人来说剑就是梦想...不是为
自己而是为父母实现梦想的道具，同时也是牢牢绑住自己未来的枷锁。所以说道向剑里倾注
爱情，对于二人一时无法理解。

对于这样的二人，优吉欧微笑着说。

“不光是剑，衣服，鞋子，餐具....即使是神圣术生成的一粒因素，只要能够心心相映，就
一定能够得到回应。大概，人也是一样。”

于是，之前一直默默倾听的桐人，停止打磨手中的《夜空之剑》，那时还只是叫做“黑色
的”，带着恶作剧般的深深笑容说道。

“是的，我和优吉欧也是心心相映，所以即使吃掉他的那份蜂蜜派也会得到原谅。”

“真是让你失望了，在你吃掉我那份蜂蜜派的瞬间，我跟你之间的联系也就断了。”

听着这一来一往的谈话，罗涅等人不禁笑了，一边笑，一边感觉自己能稍微理解优吉欧话语
中的含义了。

从那天起，两人就在宿管许可的情况下把白金樫木剑从训练场拿回宿舍联系，在训练中的伤
消失之前也认真的练习。（訓練でついた傷が消えるまで丁寧に磨くことにした），这样到
两人能自由控制剑的方向，也没有花多长时间。

如果学院里这严格但又快乐的每一天能够一直持续下去就好了，但是一个半月之后，优吉欧
和桐人为了拯救罗涅和缇卓二人用《青蔷薇之剑》和《夜空之剑》砍了别的上级修剑士并被
带到了公理教会。两人在那之后从地牢里逃跑并开始和公理教会战斗，接连打倒了世界最强
的整合骑士们，并最终击败的人界的统治者，最高祭司administrator。但是，在那场战斗
中，优吉欧也失去了自己的生命，再也回不来了。

“想要见到优吉欧前辈。”想起缇卓哭泣的声音，罗涅强忍住泪水，下意识地伸出了手。

不是人选择剑，而是剑选择主人，只要倾注爱情，心心相映，就一定能得到回应。

罗涅的手，被从左数第三把剑吸引，那是剑柄有着和桐人发色相似光泽的黑色皮革。抓出由
散发白色柔光的刀刃和剑柄组成的长剑，剑柄崭新的皮革感觉有点硬，但是如果倾注爱情的
话一定会变得非常顺手。
** 17
轻轻地深呼吸，然后慢慢地举起剑。

很重，沉重的手感能够切实体会剑的厚实。这种感觉从手指到手腕，肘部，肩膀，再专递到
身体的核心。（体の芯）

但是，并不是令人不快的重量，就像在初等练士时使用的白金樫的木剑，还有一起战斗过两
次的人界军制式剑一样，只要注入爱情的话就可以操纵自如的感觉。

右手握住剑柄，左手轻放到刀身上去感受到的存在，隐约间还可以听到声音。

“...那把剑可以吗？”

对于亚丝娜的话，罗涅认真得点点头。

副代表剑士将剩下的三把剑收回剑鞘，重新直挂会原来的墙上。回到工作台站到罗涅的左边。

“剑的名字，罗涅你也开始想想回比较好，决定了就到管理部，在骑士的装本目录里登记。”

“好，好的。”

因为是第一次拿到没有名字但是需要登记名字的剑，罗涅感到有些不知所措，不过考虑到这
也是持有者的义务，便点点头。以前好像是为了应对最高祭司administrator肆意打造，摧
毁神器，将神器赋予谁又或者从谁那里拿走，为此而准备的。现在，全卡塞多拉鲁的武器防
具饰品的种类全部登记在目录中并被妥善保管。

亚丝娜一边微笑一边点头回应罗涅，实现由此转向了罗涅的左腰。

“那把剑要怎么办？返还给人界军的话，明天联络司令部给送回去吧。”

“啊，诶...是呢...”

对于预料之外的话，罗涅一时间不知说什么好。

一直佩戴在左腰的制式剑，所有权虽然在罗涅这里，但是打开史提西亚之窗，后显示的所有
者却是神圣文字母《P》（不知道指什么，如果谁知道是什么意思还请告知。）表示按照人
界守备军军规被借走的东西。所以在武器更新后不再需要时，必须要返还回去。

剑柄和剑鞘都是深棕色的，精致的细工看起来没有什么实际用途，但是却是使用了南方特产
的库洛伊斯钢所制造的，优先度25的好剑。制作的费用也绝对不会便宜。因为罗涅亲手保养
得缘故天命还剩下好多。

而且本来的话，再被任命为见习整合骑士的一年前，就应该和骑士团的制式剑交换，但是因
为那时大家都很忙所以就一直推迟，罗涅也好，缇卓也罢，都因为非常喜欢这把剑所以就一
直使用下去了。

但是，因为像这样被副代表剑士赏赐了新的剑，也就不得不到了分别的时候了。但是...

“......”（让桐人交你二刀流不就行了）

罗涅右手拿着新的剑，左手轻轻触碰了制式剑的剑柄，亚丝娜点点头说。

“这种心情我明白的，我最初些不想对爱剑放手，让桐人感到很为难呢”

“诶...”

罗涅吓了一跳，注视着副代表剑士的脸。

“亚丝娜大人也？也就是说....是RealWorld 的事？”

“恩，有点不一样。过去，我和桐人是在既不是RealWorld也不是Underworld的世界里战斗，
正确的说...是一无所知的我，被桐人教会了战斗的方式。”

“原来像神一样强大的亚丝娜大人，也有那样的过去啊。”

噗嗤一下笑了的亚丝娜，果然已经美的超越凡人了，就这样在眼镜一瞬间眯成一条缝之后，
罗涅问道。

“那个，亚丝娜大人...最初的那把剑之后怎么样了呢？”

于是亚丝娜就像在怀念那剑的触感一样看了一下右手手掌，抬起头回答道。

“听从桐人的劝说，将剑融为了金属锭，变回金属条，用作新剑的材料，这样剑的灵魂也会
得以继承，就是这样...那个人，在关于剑的问题上有没有什么伤感的地方呢...（剣に関し
てはやたらと感傷的なとこがあるわよね）”

“呵呵呵，很有桐人前辈的样子呢”

两个人又会心地笑了，不过亚丝娜像说“但是”似得嘟起嘴。

“但是刚才的话可不是为了帮助罗涅哦，可不能把人界军的剑熔化掉，何况已经有新的剑
了。”

“不会的，听了刚才的话就已经下定决心了，这把剑会还给人界军的。”

将新的剑放在台子上，从剑带的固定器上取下剑鞘和制式剑，双手递给亚丝娜。

“没问题吗，我想拜托丽娜的话，也可以让你继续持有。”

不，真的没问题了。这把剑，对于现在的我来说太轻了，这我很早以前就意识到了。一定对
于之后的某人来说，这把剑是必要的。

我明白了，那么明天就送还给人界司令部。

郑重地结果制式剑，亚丝娜把它吊挂在腰的右侧，不论人界军的制式剑怎么轻，和左腰的神
器《闪耀之光》一起也有相当的重量，但是却以丝毫未变的步伐走到工作台对面，拿出黑色
皮革上有着银色装饰的剑鞘。

罗涅低着头受领了剑鞘，将其挂在剑带上，身体全身都可以感受到新的重量。接着，亚丝娜
突然站直，注视着罗涅并郑重地说。

“那么，桐人的事情就拜托了。”

“啊，是！”

稍微被怔住了，罗涅认真的回答道，并作出骑士礼的姿势。

“见习整合骑士罗涅·阿拉贝鲁，发誓会赌上性命保护代表剑士殿下！”

确认罗涅的回应礼节后，亚丝娜温柔地笑了。

“赌上性命可不行哟，虽然两个人都能平安归来是最好的，但是如果桐人说逃跑吧就要乖乖
逃跑哦。”

“...那个，实际上，想让亚丝娜大人也和我一起去，如果您在的话...”

“实际上我也都点想呢”

虽然是玩笑般的回答，但那儿应该不是假话而是发自真心的，但是副代表剑士轻轻摇头，在
罗涅打算说些什么之前继续说道。

现在我和桐人并不是不能再圣托利亚分别，每天的议案堆积如山，旧上级贵族对于会议的不
满也不会马上消失。

“...真的非常道歉...”

罗涅下意识地低下头，亚丝娜眨了眨眼睛的瞬间又露出笑容。

“完全没有让罗涅道歉的意思。

“但是，我也是贵族出身，在服侍桐人之前，对于人界的贵族制度一点都没有怀疑过。”

“但是，罗涅和缇卓的父亲一直在卫队和行政厅做着重要工作吧，和那些领地里的人民在辛
苦劳动自己却每天玩乐的大贵族不一样。”

“......”

罗涅再一次不知道该说些什么，这次只能充满感激地低下头。
** 18
距离圣多拉路·卡塞多拉鲁一段距离的旧帝城，现在被设置为帝国行政厅和帝国卫士厅总部。
父亲则和战争前一样，是以卫队长得身份工作。

但是曾经隶属于卫队上级的近卫骑士团已经完全解散了，卫士厅的大部分职能也被率领人界
军的索路迪丽娜·圣露露多将军率领的人界守备军接管。到了将来，把残留的四帝国的卫队
全部统合之后，好像也有缩小军队规模的打算。当然，那是在暗黑界完全没有威胁的时候，
不过到了那个时候，罗涅不知道父亲是不是还留在现在的职位上。

假如因为部队内的调换或是接到调到文职的任命，父亲的话应该也会认真负责地继续工作。
与因为个人领地的丧失而失去不労所得的，也不像人界军和行政厅的人那样工作，堕落到连
认真工作这种事都做不到的大贵族不同....罗涅是这么想的。

但是对于这样的父亲，说不定在罗涅自己的心中也是，残留着那样的想法：自己是贵族所以
和一般民众是不一样的。祖祖代代传承下来的阶级意识很难消失，罗涅算是阿拉贝尔家系的
人，本质上也是上级贵族这点事不会变的。

“亚丝娜大人，干脆...”

对于差点脱口而出的话语，罗涅赶紧咽了回去。

干脆不仅仅是爵士的等级，连贵族制度本身也废止好了。

虽然这么想，但是以整合骑士这一人界最高阶级为目标的自己而言绝不是好事情。而且，想
成为骑士这件事也绝不想放弃，光荣的称号和白色的骑士铠，被授予飞龙，然后一生继续侍
奉桐人...这就是，罗涅唯一的梦想。

对于歪头恭听的亚丝娜，罗涅挥散心中的小小迷茫，继续说道。

“没什么...那个，如果可能的话，也能让缇卓同样选择自己的剑吗？她也一直在使用人界
军的制式剑。”

“恩，我也得到了缇卓的那份许可。”

“太好了，非常感谢您。”

罗涅也有的那把也要告一段落了...这样想的罗涅，不在去思考自己之前想说的事了。

两人人从被逐渐暗淡的光素照明的武器库出来，正好是晚上七点。

在登记本上写下离开时间的亚丝娜，说着要去二层的杂物部就从大台阶下去了。再次成为一
个人的罗涅，面对隔着武器库大窗可以看到的残留紫色的夜空，轻轻叹了口气。

在只待了半年的修剑士学院，有着七点之前必须结束晚餐的规定，如果没有正当理由而迟到
的话就没有晚餐吃了。但是在圣多拉路·卡塞多拉鲁没有那样的规定，所以晚上九点之前在
十层的大食堂都可以吃到热菜，之后在食堂旁边的大厨房也放有制作好的小吃。

虽然今天因为到处奔走还发生了各种各样的事情，肚子应该也饿了，但是不知为何罗涅却不
想吃饭，于是暂且回到自己的房间。

到卡塞多拉鲁二十二层自己的房间，罗涅一直是乘坐电梯的，但是今天为了早点习惯新剑的
重量于是从大台阶爬上去。

将近两年前[fn:30]从地牢逃走的桐人和优吉欧一边和整合骑士战斗一边顺着台阶到了五十
层，已经没有那是激烈战斗的痕迹了。抱着追逐那两个人的心情迈出脚步，带着一点慌乱的
呼吸到了二十二层。

在顺着通道走一点，右侧就是自己的房间，因为还是见习的缘故所以是和缇卓一起的二人间，
但室内没有伙伴的身影，想着应该是去吃饭了吧，罗涅通过公共空间到了自己的寝室。

不知是出于怎样的偶然，卧室和客厅的构造和桐人，优吉欧一起曾经生活过的上级修剑士宿
舍完全一样。但这边的房间要更加宽广一些。基本是进入修剑士学院之前，自己儿时房间的
两倍。最初罗涅因为太过宽敞反而有些不适应，但是随着时间和替换成自己喜欢的家具样式，
作为多次替换的结果，现在已经感觉安心多了。

进入房间，右手边内侧的墙壁上有一个正对东圣托利亚的大窗，左手边则是床和衣柜。然后，
在窗户对面的墙上，安装了一个和武器库里面一样的支架。罗涅走到那里，把剑轻轻取下放
到架子上。黑色的剑鞘在又很多棕色家具的屋子里显得很合适。

“仔细想想，要去一个合适的名字呢”

对着剑轻声低语道，罗涅脱掉灰色的轻装铠甲，随着“碰”的一声放到了剑架的右边。身体
一下子轻了许多，忍住直接扑倒在床上的冲动。因为要开始准备明天的旅行，必须要先好好
收拾行李。

因为是和桐人一起，所以行李对于骑士团配给的中型背包有些太多了，看来有必要进行严格
的筛选。作为一个十七岁的女孩子，罗涅当然也想带上换洗的衣服。因为不单单是旅行而是
作为桐人的护卫，医疗用品和术式的媒介是最优先考虑的。首先是查看自己手头的媒介，不
够的话可以去管理部补充。但是，在这之前....

“....去洗个澡吧...”

这么嘟囔着，罗涅准备好替换的内衣就走出了房间。

卡塞多拉鲁的二十层到三十层是居住区，所以各层也有配备浴室。罗涅和缇卓平常也都是在
那里完成洗浴的。但是偶尔...尤其是长时间离开卡塞多拉鲁的前一天，无论如何都想去那
里。

沿着通道走到楼层最北边的升降洞，将标有刻度的把手提升到最上方的九十层，再按下金属
按钮，升降台下方事先填充好的气罐就会放出风素，一下子把罗涅升起来。

几十秒过后，升降盘开始慢慢减速，随后被固定，罗涅打开金属门。

走出来后再沿着通道走很短一段，就可以看到前方的路被分成左右两边，在岔口前的不远处，
纯白色的布从天花板上方耸拉下来，奇怪的布上写着黑色的奇怪的书法“ゆ”字。

这个布是代表剑士主动要求安装的，字也是他自己写的，至于是什么目的，谁也不知
道[fn:31]。唯一知道原因的亚丝娜副代表剑士听说也只是露出笑容但什么都不说[fn:32]。

每次走这条路的都会浮现出疑惑，一边拨开这个下面被剪成两半的长方形布帘，一边走到岔
路口。于是又看到左右两半都有相同设计的布帘。蓝色的布底，右边用白色的字写着“男”，
左边则用胭脂色的字写着“女”。这表示的含义大概是明白了，不过依然不理解为什么要写
在这样的布上。穿过写着“女”字的布，通道开始向右转，前面是一个更加宽敞的房间。

设置着隔断墙般的大柜子的房间里除了三位女性术士没有别人，身上也只披了一件东方风格
的羽织，正坐在靠墙的藤椅上擦拭头发。注意点罗涅站在那里后赶紧放下双手。

慢慢弯下腰的女性们，一个个有礼貌地低下头打招呼。

“晚上好，骑士大人”“你好，骑士大人”

“晚上好。”

罗涅也好好地弯腰回礼，然后慌慌张张走向房间另一个方向，躲到柜子后头，深深松了口气。
成为见习骑士也不是一天两天了，既是如此，年长的女性对自己用敬语还是怎么也不习惯。
既是被任命为正骑士，大概也无法想法那提欧团长那样挺胸抬头吧。
**  19
一进来，白色的热气就扑面而来，罗涅赶紧往前再走一步并把门关上。

热气散开后，眼前的光景无论看到几次都不可能镇定。

直接使用了大教堂九十层近一半的广阔空间，地板和柱子都是纯白的大理石，南边和东边的
墙上各是一面大玻璃，央都圣托利亚的夜景尽收眼底。然而真正比就帝城的王室还要奢华的
地方在于，整个地板都充满了热水。

南北向的大厅细长的纵深约四十梅路，宽度达到二十五梅路，周围的走道宽约两梅路，从那
里距离地板还有约1一梅路的深度。（南北に細長い広間の奥行きは約四十メル、横幅は二
十五メルに達する。周囲の通路の幅が二メル、そこから床までの深さが一メルなので 我
是没看明白川原到底想写个什么构造...）简单计算一下，热水的总量就有八百七十四立方
梅路[fn:33]。

换成容积单位的话，就是八十七万四千里路（容量单位）这样庞大的数字。不过，在大理石
墙壁的另一侧，也就是写着“男”的挂布所同向的另一端也有完全相同的对称构造，也就是
说整个浴池是这里的两倍。

这就是被桐人成为“中央大教堂最奢侈的地方”的大浴场。

异界战争之前，使用这里的仅仅是三十名整合骑士而已，中间的墙壁也不存在。比现在多出
一倍的浴场只有一个人使用好像也是常有的事情。不过，随着组织的重新编排，大教堂的术
士和工作人员也被允许使用了，同时也分出了男性用和女性用。

虽然现在也有大约二十人在洗浴，但是因为浴池想湖一样宽敞，所以完全没有混乱的迹象。

尽管如此，罗涅还是走到了人少一点的东北角，透明的热水没过脚尖，虽然开始感觉有点烫
但是很快就适应了。沿着大理石石阶走入浴池，坐在左后一个台阶上。

热水没过脖子，居住区一般的大浴池完全没有的开放感让头脑都麻木了，不由自主地发出声
音。

“哦呼...”

“呀，果然还是大澡堂好啊。”

“确实...”

点头了，罗涅愣了一下睁开眼睛，不知什么时候左边坐着一个人。

水面上摇曳的热气散开，看到那个人的脸，罗涅又一次面露吃惊。

紧紧贴在脖子上的湿毛发是浅棕色的头发，和薄青色，栗子般大小的眼睛。比罗涅所坐的台
阶高一级的身体想小孩子一样纤细，外表看来也就是十岁的少女，但实际上绝不是看起来那
样天真。

“晚，晚上好，菲泽鲁大人”

像更衣室的术士们一样郑重地看口问候，少女则一边用手指弹动水面一边回应道。

“大人的称呼就免了，毕竟是罗涅你年纪比较大”

“但，但是因为菲泽鲁大人是正式骑士。”

“恩——这样的对话感觉已经有一百来次了。”

伸展身体浮出水面，用双脚叮咚踢水的少女的名字是，菲泽鲁·辛赛西斯·托提奈（29）

异界战争时期是作为《有编号的见习》这样特殊安置的，不过事情圆满结束后就升职了，是
货真价实的正式整合骑士，配给了量身制作的白色铠甲，得到了名为“悠闲向日葵（閑割ひ
まわり）”的飞龙，最近主要负责人界的侦查任务而飞行。

“菲泽鲁大人，最近一段时间没看到您，因为任务而被派遣出去了吗？”

对于罗涅的提问，菲泽鲁点了点嘴巴已经沾到热水的头。

“恩，西帝国骑士团的残党动向有点奇怪，就去侦查了一下，利梅鲁还在跟着，我为了报告
和补给就回来了。”

“那还真是辛苦呢，据说西帝国的法鲁提雷斯·维斯迪拉斯五世是四皇帝中唯一一个没有发
现尸体的...难道和这件事有关系？”

“恩，西帝城已经完全崩塌燃烧了，所以我不认为那个西皇帝老爷爷能从那个爆炸中活下来，
不过从中活下来的人也是有的。”

从吹着水泡的嘴中说出来的话，怎么想也不会认为是个十岁孩子的。光看菲鲁泽的外表还不
能判断出年龄。在大教堂出生的她，和现在同为整合骑士的伙伴利梅鲁·辛赛西斯·托提艾特
没有接受《秘密整合仪式》，最高祭司任命二人为见习骑士的时候，听说就施加了冻结天命
的术士。也就是说，这两个人是不能从外表看出成长的。

考虑到这些事情，罗涅想要紧紧地抱住菲鲁泽她们，当然过去并没有这么做过。和之前的正
式骑士们的编号不一样，身为见习的她们因为杀了原本带有编号的骑士从而获得了编号，而
且两人曾经打算用毒剑麻痹桐人和优吉欧再取下他们的首级，异界战争时期，入侵人界军后
方的哥布林部队也被她们两人消灭了一大半，之类可怕的谣言还有很多。虽然这么说出来并
没有那么恐怖，但是与其相处时要抱有敬意这点绝对没错。

“说起来，罗涅酱”

对于突如其来的点名，罗涅在热水中挺直后背。

“是，是！”

“我听说了哟~”

水面上咕噜咕噜浮出泡泡，菲鲁泽做出笑脸。

“陪同桐人，去奥布席迪亚去对吧？”

“诶，那个，那是...”

罗涅和桐人去暗黑界也不过算是基本的秘密任务，想到隐瞒大教堂最强的情报员是不可能的，
于是点点头。

“...恩，就是那样”

“那特产就要暗黑界术士公会的混装药剂就行。”

“...我，我会尽量的”

“啊哈哈，玩笑啦，玩笑。”

露出与年貌相符的纯洁笑容，菲泽鲁往上挪了一级，看向玻璃窗外。

罗涅的视线随着过去，以黑暗作为背景，东圣托利亚的灯火像星星一样闪烁。以传统木式建
筑居多的东圣托利亚，因为大多是用纸或者薄板做的灯笼而不是油挂灯，所以接到的颜色也
感觉更加柔和。

在那光明之后七百五十千路，耸立着东之大门，离那里两千五百千路就是暗黑界的首都奥布
迪西亚，在古神圣语里译为“黑曜石之都”这是在修剑士学院里学的，至于名字的由来连老
师也不知道。

用自己的眼睛去见证大概就会明白吧，说起来没想到真的会去那样的地方。现在不禁有这样
的感慨。

“去那边的话...”

菲泽鲁这么嘀咕道，罗涅又将视线移回年幼的骑士前辈身上。

“是...？”

“恩，战争已经结束了，虽然如此我还是有些在意。”

附近没有人，从墙壁上喷出的热水落入浴池的声音让两人的对话不可能被别人听见，既是如
此菲泽鲁还是将脸靠近罗涅小声说道。

“在奥布迪西亚，要睁大眼睛，好好注意周围。”

“好，好的...”

在暗黑界，《力之法则》支配者一切，因为那边现在最强的是融合派的伊修卡恩总司令官，
表面上好像起到了抑制的效果...在有禁忌目录和人界基本法层层束缚的这边，也有通过条
纹漏洞，通过花言巧语曲解的家伙。在禁忌和法律都更加暧昧的暗黑界，既是有更坏的家伙
也不奇怪。
** 20
对于菲鲁泽的话，带来的寒意让罗涅感觉热水的温度都降低了，不由自主地抖动了一下身体，
菲鲁泽则伸出右手轻轻拍拍罗涅的头。

“对不起，我不是想要吓唬你。”

“不，没关系的。对于您的指教，我会牢记于心。”

“恩，等到罗涅酱回来了我们的任务应该也结束了，到时候邀请你参加慰劳会。”

“好的，一定”

罗涅点点头后，菲鲁泽笑着站起来。

“那么我先上去了。”

对着挥动这右手，啪嗒啪嗒地走在大理石地面上离开的骑士少女。罗涅再一次低下头，

菲鲁泽的骑士编号是二十九，三十号的《金樨木骑士》爱丽丝在异界战争的最后启程去了
RealWorld，三十一号的《霜鳞鞭》艾鲁多利尔因为保护爱丽丝而丧命。因为这两个人的编
号会保留下来，所以等到罗涅和缇卓被任命为正式骑士的时候，其中一个就是三十二号，另
一个是三十三号。

虽然距离那一天的到来还很遥远，但是感觉有点到令人窒息，一定是自己的觉悟还不够。以
现在罗涅剑术，体力和心意的强度，对于雷恩这样的上位骑士而言是理所当然的，与外表都
是孩子的菲鲁泽和利梅鲁比都还差得远呢。

一步一步。

即使每一步都走得很慢，只要一步步前进，天天锻炼，认真学习，总有一天会达到目标的。

“...罗涅·辛赛西斯·瑟提斯里（33）...”

不由自主地把那个名字说出来之后，罗涅赶紧环视四周，虽然谁都没有听见，但是还是不好
意思的把头埋入水中，直到不能呼吸为止咕噜咕噜地吐出气泡。

到了第二天也就是二月十九日的拂晓

在大教堂西用地的飞龙厩舎内，罗涅在专心抚摸着爱龙月驱的头。

还是幼龙的月驱一边发出“库噜噜噜”的声音，一边睁开眼睛，这应该是半心情舒畅半犯困
的表现。不光是幼龙，银色围栏里的缇卓也因为犯困而晃起红色的头发。想要早点睡却怎么
也睡不着的罗涅，和缇卓在房间里聊了半天。

明明已经待在再一起快两年了，但是却不可思议地完全不会没有话题，大概和挚友就是这样
吧。桐人和优吉欧也是，从北边的卢利多村出来，一起来到央都，一起进入修剑士学院，一
起成为上级剑士应该也花了好几年。两人总是一起开开心心地聊天，为了讨论剑技而切磋的
时候，既是是沉默的时候也是很舒服的感觉。

现在的缇卓也位于漫漫人生中的岔路口，不论她是接受骑士雷恩的求婚或是拒绝，都想要和
她永远成为最好的朋友。

“那么月驱，走吧，能够好好听缇卓的话，你真是个好孩子。”

罗涅站了起来，幼龙则抬起头发出“库鲁”的声音回应。

和终于有些清醒的缇卓一起来到大教堂后方的工厂，机龙二号已经被拉到了地上的石阶上。

不像一号机那样垂直矗立，和仓库那时一样，三只脚趴在地上，仔细一看，脚的前方和飞龙
不一样，不是爪子而是车轮。

在头部附近可以看到桐人，亚丝娜，法那提欧，还有工厂长赛多雷的身姿。此外还有一个人，
穿着工作服的同龄女性站在侧面，用手指着机体正在吟唱神圣术。察觉到那是风属性神圣术
的罗涅，转过来对着同伴的脸。

“那个缇卓，该不会那个孩子是？”

“啊，是吧，就是自动化之前升降盘的操纵员。”

“诶，很可爱的一个孩子呢。”

“我也是这么想的，那个孩子，据说和迪索鲁巴特先生一个年纪哦。”

“是，是这样吗...”

在里场地还有一段距离的地方停下交谈，桐人注意点二人，于是招了招手。

“喂，缇卓，罗涅，这里这里”

“啊...好的，早上好！”“早上好！”

两人相继问候后就走了过去。

天空还没有亮，在室外的机龙二号比想象的还要巨大，有两个驾驶座位，双翼比真正的飞龙
还要打，尾部的喷射口也很大。全场比一号机多了四成，大概有七梅路。

要坐这个吗，这样想还是会感到紧张，但是因为是自己提出的现在可不是退缩的时候。将脑
海中浮现的一号机毁灭的场景推回去，罗涅在桐人和亚丝娜面前低下头。

“对不起，来晚了。”

“没有，到五点还有大约十分钟。”

通过四点半钟声而判断出现在时间的桐人，视线悄悄落到了罗涅左腰的剑上，露出微笑。

“罗涅，护卫的工作就拜托了。”

“好..好的！”

既是拼上性命，刚想这么说，就想到昨天亚丝娜的话，于是从嘴中说出来的是。

“会，会努力的！”

像是说着好孩子一样，桐人和亚丝娜再次微笑地点点头。

接连和法那提欧还有赛多雷打过招呼后，罗涅从缇卓那里拿过行李。装着慢慢物资和衣物的
沉重中型包，要放到完成的机龙的哪里呢..这样考虑着。

“桐人先生，风素已经填充完了。”

听到后背传来的声音，罗涅和缇卓同时回过头。声音的主人是原升降台的少女，工作服也好
修道服也好，既是穿了贵族礼服也会非常合身吧，少女的美貌让人看了不禁这么想。

“谢了，帮了大忙。”

对于桐人的感谢，名叫艾雅丽的少女表情轻微一变，鞠了一躬后就退到了赛多雷的后面。

之后大教堂的钟奏响了五点的旋律，桐人很有气势地打了个响指。

“那么差不多该出发了，罗涅，你负责看管行李吧。”
** 21(被吞)
#+begin_quote
空白，原帖28楼被吞
#+end_quote
** 22
对于那充满担忧的声音，罗涅不知道该如何回应。

虽然有着能够维持钢铁飞龙飞行的心意力量，战胜了最高祭司administrator和暗黑神贝库
塔，但桐人也绝不是神。既是和罗涅诞生的世界不同，也是会一个人烦恼，一个人迷茫的人
类。

不论受了多少伤也会站起来，将Underworld从消亡的危机中拯救出来，这样的荣誉既是被永
世称赞也不为过，这样的桐人现在也在为世界而奋斗。说到人界和暗黑世界额融合，这是过
去任何人都不曾做到过的远大目标，想要为伸手触及这个目标的桐人献出力量，但是对于现
在的罗涅光是想像那条艰险的路就竭尽全力了，更不要说提出有帮助的话。

如果只是沉浸在自我想象中就糟糕了，那自己的同行也就没有意义了...

在下落的时候，桐人似乎是感觉到了什么，说道。

“但是，罗涅能一起来真是太好了，初次见面的时候，我还让小孩子害怕吧。”

“诶？是那样吗？”

“好像有各种各样的传言，一个人走的时候也听到有人背后议论...嘛，经理了那样的战争
也是没有办法的事情吧。”

轻轻叹了口气，桐人像是转换心情一样用清晰的声音说道。

“那么，差不多要离开圣托利亚了，也是时候将心意飞行转换成元素飞行了。”

“好，好的！”

很有气势地点了下头，罗涅朝前座问道

“那个，我要做什么吗？”

“是呢，想一号机那时一样与元素保持交感状态，如果有什么问题请告诉我。”

“明白了。”

听到罗涅声音的桐人，立起右手大拇指做出信号，然后双手握住两根金属棒。紧接着，开始
吟唱神圣术的术士。

“system call！Thermal generating element！”

桐人的双手发出红光，热素在中空的金属棒内部生成，然后被心意操控着在管中移动，最终
到达机龙中央的密封罐内。

既是是对那样的代表剑士来说，控制巨大机龙的同时用心意控制微笑的元素也是不容易的。
机龙再次开始呼啦哗啦地摇动，罗涅下意识地伸出身子，将双手放到桐人的肩膀上。

即使不用句式去确认，也可以感受到周围旋涡状的神圣力流动正慢慢平息，机龙停止了摇动，
十个热素被好好地收进密封罐中。

“谢谢，罗涅”

轻轻碰碰罗涅的右手，桐人慢慢地深呼吸，然后低声说道。

“释放。”

密封罐中的热素全部释放，产生出巨大的火焰。

火焰由于空间的压力而从罐子的尾部排出，在途中，和起飞前配备的另一罐风素混合，然后
被压缩，就像飞龙喷出火焰般从最后面的喷射口一条直线一样射出。

因为强烈地加速而全身贴在椅子上，罗涅屏住呼吸。

窗外漂浮着的云瞬间向后方流去。比较速度的话，还是桐人用风素飞行术从中央大教堂飞到
南圣托利亚的卫士厅那时比较快。[fn:34]但是现在的机龙，几乎没有被心意的力量所控制，
那样高位术士经过训练的话，应该也有像桐人一样飞行的可能。

挑战《终焉之壁》的原因，说必定也是只为了那方面的考量。一瞬间这么想的罗涅，思维也
狭小空间中的轰鸣声瞬间打散了。罗涅赶紧握住椅子边，大声叫到[fn:35]。

“前，前辈！这个机龙的飞行速度有多少？”

“恩，这么说来。”

用着完全没有紧张感的声音，桐人回答道

“整合骑士的飞龙最高时速应该是一百二十千路左右每小时，因为不能长距离飞行，所以最
大飞行距离大约八十千路左右，但是这家伙，现在的话应该是二百五十千路不到每小时。”

“诶...飞龙速度的两倍吗！？”

“我想全力飞行时能达到三百梅路，赛多雷说现在还只能使用八成的性能。”

这么说着，桐人指了指椅子前方并列着的多个圆盘中的一个，安装的指针，却是是在刻度上
限前面一点摆动着。

“一，一小时三百千路...”

不能想象自己说出的数字，罗涅不知道是第几次摇了摇头。

总算是明白了，如果机龙能够这样飞行的话，那么到达遥远的尽头，三千千路的那一边也不
过用半天就到达了。而且，在这个高度，也没有能阻挡机龙的存在。

我来这里真的有意义吗...罗涅再一次这么想，一边习惯抖动的身体。

越过尽头山脉，在暗黑界红色的天空下继续飞翔，一共飞行了约15小时。虽然中间有两次休
息，但是屁股和背部已经切实感受到疼痛的时候，桐人用手一指。

“看到了。”

目光越过桐人的肩膀，在沉浸在黑暗中大地的另一端，可以看到微微光芒，随着接近变成了
无数光亮的集合。

“那就是...暗黑界的首都...奥布迪西亚。”

用几乎听不到的声音嘟囔了一下，罗涅问桐人。

“...桐人前辈已经去过那里了吗？”

“恩，但是是非正式访问，所以城堡和城市都没有参观过。”

“这次也是一样呢...”

听到罗涅遗憾的话，桐人展露出笑容。

“不，虽然这次是非正式的，而且连伊修卡恩都还没有联络，但是也有办法。”

“有办法？”

仔细想想，和桐人一起的时候，相当大的几率会发生讨厌的事情。[fn:36]这样想着，罗涅
再一次看向窗外。

飞龙的速度降到一半以下，即便如此还是看不清前方被照明的街道的形态，和被整齐划分的
圣托利亚街市不同，无数的光似乎没有规律性可言，仿佛以新月的形状聚集，在那之中，黑
色的岩山像枪锋一样耸立。到山那里就有很多灯光了，那才是皇帝贝库塔的城堡奥布希提亚。
用巨大的山岩，在悠久的岁月中打造出的城池，其威容与公理教会的大教堂比也毫不逊色。
在这黑夜中几乎无法确认其轮廓。

“还剩十千路啊...好，差不多该切换心意之力降落了。”

对于桐人的话，罗涅惊奇地问道。

“啊，就在这前面降落吗？”

“恩，不然这家伙在街区或城楼上降落绝对会引起大骚动的...”
**  23
一边这样回答，桐人一边握住名为《操纵杆》的金属棒，密封罐中控制火焰的心意渐渐衰弱。
小房间（也就是所谓的《操纵室》义乐：此处为川原的备注）里充斥的轰鸣声似乎远去了，
突然间又消失了。

失去了推进力，机龙开始下降，桐人却用心意力强行支撑起来。虽然在中途休息的时候已经
有过着陆的经历，但是还是不能消除紧张感，罗涅的双手紧紧扣住椅子框。

回到圣托利亚后，给后面的椅子加一个可以抓住的棒子吧...一边想着，罗涅一边忍受着和
大教堂升降盘不一样的下落感。不久，伴随着轻微冲击的同时，机龙也静止了。前座的桐人
伸了个懒腰说道。

“辛苦了，罗涅。接下来就要靠人力飞下去了。”

两把剑和大小包各一个，罗涅双手抱着大包。随着桐人的十梅路风素飞行术一下子就飞下去
了。即使在空间神圣力薄弱的暗黑界也可以稳定的飞行十梅路啊，罗涅不禁这么认为。

再一次着陆的地方是，奥布迪西亚城郊的宽广街道上。石板的道路有摩擦的迹象，白天这里
应该有许多人或者亚人，还有马车来回往来吧。但是在大约晚上十点的现在，没有看到人影。

罗涅平常这个时间已经上床睡觉了，所以在脚着地的瞬间，长途的疲劳感和强烈地困意就快
速袭来。赶紧摇摇头忍住，护卫的任务现在才刚刚开始。

罗涅之这么想的。

“那么，去找个过夜的地方吧。”

桐人吧《夜空之剑》挂到左腰的剑带上说道，罗涅则眨眨眼睛回应。

“诶...那么要去城里吗？”

“这时候城门已经关闭了，伊修卡恩应该也睡了，现在偷偷潜入的话，一定会被卫兵当成暗
杀者的。”

“...确实呢...”

南圣托利亚旅店的清洁工亚泽恩被杀死，并将罪过嫁祸给年轻的山地哥布林奥罗伊，为了应
对这个迷之暗杀者不远千里横跨Underworld，如果现在被当做暗杀者可不好笑。

“明白了，但是作为人界人的我们，怎么在不被怀疑的情况下住宿...”

是这样吗，总之在那之前，桐人把自己的手伸进一个小袋子里，取出一个小东西。仅仅依靠
街道的灯光凝视，似乎是一个小药瓶。

“那么罗涅，不好意思了。”[fn:37]

这样说的桐人用手指取出了里面的东西，不由分说地靠近罗涅的脸。

“唔啊啊！”

桐人的手快速地接近，在罗涅的脸上擦拭着什么，罗涅不禁发出悲鸣。惊讶的表情凝固在罗
涅脸上，桐人黏黏糊糊的两只手涂抹的更广了，从脸颊到额头，耳朵，下巴为止来回涂抹之
后，桐人退一步看了看罗涅，点了点头。

“恩，不错的感觉。”

“...为,为什么这么做...”

右手触碰自己的脸颊，发粘的触感已经没有了，指尖上也没有任何东西。一旁的桐人只是满
脸的喜悦而不说话，才一次从瓶子中取出膏状的东西，这次涂抹在自己脸上。比从诺兰加鲁
出身的罗涅还有缇卓要深一点，但仍是人界标准的白色皮肤立刻染黑了。

短短几秒之后，桐人的肤色就比克西路茶的颜色还要深。这个样子，更像沙扎库罗伊斯人，
不对更像暗黑界...想到这里，罗涅终于明白了。[fn:38]

“啊...也就是说要化妆成暗黑界人。”

“对，虽然我和罗涅的头发要更浓密，不过现在是冬天，所以只要颜色改变的话应该不会被
识破。”

听了这些话，虽然有些晚了但罗涅还是在意自己被着色的脸，而用双手托起脸颊。因为见了
这个动作的桐人保持着微笑说了“别在意，其实很适合你”，桐人的话让罗涅手掌下面的脸
颊开始发热。

“前，前辈，这个效果会消失吧？”

掩饰着有点尖锐的声音问道，桐人带着慌张的表情赶紧点点头。

“当，当然，药剂师酷多科尼亚说，差不多八个小时就消失了”

“差不多...那么使用的材料是什么？”

“这个我想你还是不要知道的好。”

闪烁其词地回答后，桐人用手整理了一下罗涅的乱发，视线移向东边。

圣托利亚的话，城和街市的分界处有大门和卫兵营，但是奥布迪西亚不一样，街道两边除了
零星的建筑物之外，就直接连接到街市了，也看不到卫兵的身影。

“...虽然没有关系，但是如果被谁问到身世的话...就装成从法鲁提拉来找工作的样子...
不，就说成是兄妹吧。（直叶：？？？）”

听了桐人的话，罗涅才把手从脸颊上拿下，对于没听过的单词问道。

“那个，法鲁提拉...是？”

“从这里起约三十千路，在西南方的一个暗黑界人的街市。”

虽然罗涅很继续问，兄妹之前那个所谓“找工作的样子”是什么，但还是忍住了并点点头。

“我明白了，那么走吧，前辈。”

罗涅带上外套的头巾[fn:39]，把包放在一个石台上，将还没有取名字的剑挂在腰上。正当
先要伸手拿包时，桐人抢先一步把包拿了起来。

“啊...前辈，自己的行李还是让我自己拿吧。”

“不行不行，现在是兄妹的设定，哥哥帮妹妹拿东西是当然的。（直叶：嘿~我可记住了。）”

再一次微笑，桐人右手提着罗涅的包，左肩挎着自己的皮革包就快步走开了。不得已罗涅只
好追了上去，到了街市就应该叫“桐人”了吗？[fn:40]罗涅不禁对此感到苦恼。

在黑暗的街道上走了一段时间，周围渐渐变得明亮起来，同时擦肩而过的人类和亚人也增加
了，罗涅同时感到安心和紧张。

第一次见到奥布迪西亚的城街，大部分建筑都是用黑乎乎的材料制作的，树木和水池也不较
少，和圣托利亚比给人一种苦闷的印象。但是，每一家的墙壁上都随意安装着挂灯，虽然是
深夜但到处都是红色的，黄色的和紫色的光，给人一种节日的氛围。

“那个挂灯，是靠什么燃烧的呢？”

对于罗涅的提问，桐人回答说。

“是靠附近的山中采集到的一种矿石，拳头那么大的可以燃烧十天左右。”

“诶，那还真是方便呢。”

“我想如果拿到人界的话应该会很值钱，但是很难到手。因为不放入水中就会自燃，长途搬
运起来有点困难呢。”

两人就这样一边对话一边走着，不久前方就变得热闹起来，在那有一个宽敞的广场，路边摆
着几个大摊子，在中央并列的桌子上，许多男人在享用酒肉。

半数是暗黑界的人类，还有少量的兽人和哥布林，但桌子是分开的。果然在暗黑界，种族间
的隔阂还没有消失吗...罗涅这样想着。似乎是看出了罗涅的想法，桐人说道。

“在同一个地方喝酒已经是很大的变化了，看，那边拳斗士的一群人和兽人团体，因为坐在
相邻的桌子上也有交谈不是吗？”
** 24
“啊，真的呢，好像也有碰杯。”

既是是二月也赤裸着强壮的上身的拳斗士，似乎在喊叫着什么举起手中的木质啤酒杯，与落
在邻桌的兽人很有气势地进行碰杯。在广场的门口看到这一景象的罗涅，自言自语地说道。

“据说异界战争的时候，几乎全灭的拳斗士，被赶来的兽人军队给救了...那时率领兽人的
《绿之剑士》，似乎被兽人奉为神明的样子。”

罗涅虽然没有亲眼见过，但是随着战争结束而消失的《绿之剑士莉法》其实是桐人在
RealWorld中的妹妹，这件事还是知道的。

桐人那被涂成黑色的脸，在一瞬间因为悲伤而有些扭曲，但很快又恢复平静的表情点点头。

“啊...能这么快和暗黑界和平相处，也是多亏了莉法的努力。正因如理，我们绝对要守护
这和平。”

“...是。”

罗涅也注意到自己那因为日常繁忙工作而忽略的不安此刻正在蠢蠢欲动，下意识地做出回应。
桐人拍了拍罗涅的背。

“那么，虽然晚了一点，我们也吃晚饭吧，已经厌倦了吃携带食品了。”

“诶...在，在这里吃吗?”

“因为啊，摊子那里传来非常棒的味道...如果这都可以忍住的话，每天也不会惹法那提欧
和迪索鲁巴特生气了。”[fn:41]

用这样毫无道理的话当做理由，桐人拿起包笔直地向广场走去。

罗涅不得以跟在后面，确实飘来的香气进入鼻子后，让人产生了空腹感。广场外围一共有六
个摊子，只是看一眼并不能判断出到底是卖什么的。

这种时候，罗涅就会这样那样地犹豫不决，并且对缇卓能很快做出决定感到吃惊...这已经
是常态了，但是现在自己的身边并没有红发的伙伴。那么代表剑士的决断力如何呢，罗涅斜
眼窥视，“那个烤串，看起来很不错的样子...但是已经这个时间了，要不在那里吃汤面
吧...不行不行，对面的包子也相当...”就这样自言自语的。[fn:42]

说起来，桐人前辈在面对各种犹豫时也是优吉欧前辈帮忙决定的吧...露出微笑的罗涅，突
然想到一件事，于是拉了拉桐人的外套。

“那个，前辈，买东西之前，已经准备好这边的货币了吗？”

“...”[fn:43]

罗涅看着桐人的脸从惊愕转变成绝望。

在人界流通的货币，有一千希尔的金币，一百希尔的银币，十希尔的铜币和一希尔的铁币四
种，确切的说还有一万希尔的白金币，但是只有在行政和大型商铺交易时才会使用，因此和
一般民众或是下级贵族可以说是毫无关系。

对于罗涅来说，从懂事的时候就已经知道，作为钱币的希尔，因为印着公理教会的徽记和史
提西亚的侧脸所以不会再暗黑界被使用。当然，这里应该也有自己的货币。

终于意识到这件事，桐人垂头丧气地说道。

“...因为再大教堂不需要用钱，所以完全忘记了...”

“也...也就是说连希尔都没有带？”[fn:44]

带着像被教师训斥的小孩子一样的表情，桐人点了点头。

罗涅不知道该如何应对这个表情，只好呆呆地盯着桐人。

罗涅一直携带着的剑带的缝隙里，有一枚金币以备不时之需，但是这也改变不了不能使用的
事实。由此想到了进一步的问题，罗涅再次问桐人。

“那个，该不会说，我们也没办法住宿...”

“恩，嘛，就是那样...”

对于郑重肯定的桐人，罗涅不由地回以叹息。

“如果在没钱的时候住下了，到底打算怎么结账呢？”

“那当然，你看，仓库里不是有那种自动换币机吗...”

说着些意义不明的词语，桐人仍带着毫不放弃的眼神在摊铺之间来回看，最后将目光放到贯
穿夜空的巨大城池上。

“没办法了，只能祈祷伊修卡恩已经起床了，或者潜入进奥布迪西亚吗...”

要是当做暗杀者就麻烦了，这可是前辈你说的啊！

正在思考要不要这么吐槽，罗涅再一次深深地叹息，这时。

正在广场一角对话的二人上方出现一个人头，随之出现的还有巨大的身影。

“...!?”

压住差点反射性地拔出剑的左手，罗涅抬起头，站在面前的是一个身高大约有一梅路九十赛
的巨汉。

赤裸的上半身被强壮的肌肉和用钉子连接的皮革带覆盖，而赤红色肌肤上的无数伤疤正是拳
斗士的证明。蓬乱头发的脸，似乎是因为喝了不少酒，在矿石吊灯的光照下能明显看到发红。

“喔，小哥，没有能够吃饭的钱吗？”

因为在这声音中感觉不到一点敌意，罗涅稍微放松了戒备，而桐人则用生无可恋的表情（情
けない表情）点了点头，用听起来就很饿的声音——不是演技而是真的很饿[fn:45]——回
答道。

“额...就是这样，和妹妹一起从法鲁迪拉来找工作，旅费已经都用光了。”

“哦，法鲁迪拉啊，我的父亲就是那出生的。”

听了巨汉的话，想到如果真的聊起只知道名字的街市就糟糕了，罗涅不禁开始冒冷汗，幸好
并不是那样的展开。拳斗士用像带着皮手套一样厚实的巨大右手[fn:46]拍了拍桐人的肩膀，
慷慨地说。

“好吧，既然是老乡那就我请客吧。”

“不，这样也太...”

不用不还意思了，这样就打断了桐人，拳斗士推着桐人的后背像广场里送。没有办法的桐人
只好起步，而罗涅则紧随其后。

拳斗士带两人去的，是六间店铺中最小最昏暗的一个。用长长的汤勺搅拌着已经有一定岁月
的大锅的店长，是一个脸长长刘海遮住的人类男性，除此之外什么都看不出来。从屋檐垂下
的褪色的布的一角，用凌乱的小字写着【奥布迪西亚煮】，看来这里的料理好歹是有名字的。

“在这个广场里，这家店是最棒的，不过我的同伴们却都不这么认为。”

醉醺醺的拳斗士噶哈哈地笑了，桐人则略带抽搐地向后退。

“那个，大叔，我怎么又不好的预感...”

“第一次来这里的家伙基本都这么说，嘛，就带着被骗了的心态试试吧，喂老爷子，给我来
三份。”

拳斗士从吊在皮带上的袋子中拿出三个铜币，叮叮当当地放到发黑的长板上。如果这里的铜
币和人界是同样价值的话，这个“迷之奥布迪西亚煮”只要十希亚，就算是作为小摊的小吃
也很便宜了。

店主毫无回应地在长板上放了三个木碗，用长柄勺把锅里的东西咕噜咕噜地倒进碗中，同时
添了木勺，然后默默地拿走铜币，继续刚才的工作。

大概是习惯了，或是因为喝醉了。拳斗士完全不在意店长极其冷淡的态度，一手拿一个碗递
给桐人和罗涅。

木碗内的东西，如说只说是棕色的汤是不足以描述的，里面形形色色的配料，而且因为汤不
是透明的所以也不能分辨出到底煮的是什么。

被端着自己的碗的拳斗士催促着，桐人和罗涅，带着觉悟拿起了汤勺。
** 25
捞起像是连续煮了三天的炖菜一样粘稠的汤，呼呼吹了几口后就放到嘴里。刚开始感觉很辣，
紧着是混杂而浓郁的苦味，然后隐隐感受到的甘甜又渐渐消失。

“...桐人前辈，这倒底是什么味道...”

罗涅小声询问，同样吃了一口的桐人用复杂的表情凝视着木勺，小声嘀咕道。

“不会错的，这确实算是《煮》，并不是奇怪到不能吃，倒不如说这微妙的味道感觉有点美
味。”

“诶？前辈以前也吃过吗，这个?”

似乎是终于回归自我的桐人看着罗涅，摇了摇头。

“啊，不，没有。以前住过的街市里，有一家很相似的店。或许是因为店主的性格很相似的
缘故，那个无所谓了...我所知道的《煮》辣和酸，苦和甜是相违背的。所以从来没有那样
吃过。[fn:47]但是这个《奥布迪西亚煮》该说是味道非常成熟或者说是圆滑，不知道怎么
形容好...”

“喔，你还真是了解呢，小哥。”[fn:48]

早就吃完了三成的拳斗士，高兴地拍了拍桐人的后背。

“这家伙，据说是用从帝都建成开始，用有着两百年历史的厨具和汤底[fn:49]每天持续熬
着汤。这样的料理人界都不会有吧，啊哈哈哈。”

“确，确实呢...”

“诶，诶！两，两百年...!?为什么料理的天命能持续这么长时间？普通的炖菜和汤，既使
是在寒冬里，五天就坏了...”

“这才是老爷子厉害的地方哟！”

就好像自己是店主的亲戚似得，拳斗士自豪地拍了拍胸脯。

“老爷子每天一步也不离开摊位，不然锅烧空了之后就会焦糊，接着要调整火候。就这样一
直持续着火的话，锅中的天命也不会减少，当然自己的饭也是一日三餐吃这个...能够做到
这点的料理人在全暗黑界，不对，在全Underworld也只有老爷子和我吧。”

“啊，每天，这样吗...”

无语地看向问题桌台，冷漠的店主依然只是附身继续搅拌着锅，仍然看不到正脸。

“也就是说，那个人的天命被冻结了，就这样活了两百年吗？”

对于罗涅的问题，拳斗士第一次开始思考，认真地来回看了看手中的碗和桌台，左右摇了摇
头。

“怎么可能，我听说能够做到那点的只有人界的最高祭司，一定是代代相传吧。”

“也，也是呢。”

罗涅搅动着汤然后捞起不知道是什么的块状物，战战兢兢地放入嘴中，想着恐怕是鸟类的肉，
就这样轻轻咬了下去。美味瞬间流露出来，复杂离奇的味道，如果习惯的话大概会成一种癖
好吧——这种事情大概不会发生吧。

比罗涅早一步习惯的桐人，已经很快吃光了，一脸满足的样子吐了口气。

“啊，真是太靠吃了，这么说一点都不过分。”[fn:50]

深了一个懒腰，接着向邻座的拳斗士鞠了一躬。

“感谢招待，好人大叔，大恩大德今生难忘！”

“啊，不客气。”

也已经吃完的大叔，醉笑着点点头。

“赶紧找个好工作，只要喜欢就再来吃《奥布迪西亚煮》吧，这次是我请...虽然这样说
了...”

用厚实的手掌擦了擦脸，大叔的笑容消失了继续说道。

“现在在奥布迪西亚，兄妹都能够找到工作的，有点困难哦，这个你要知道，小哥。”

“诶，是这样吗？我看就算这个时间也很热闹，感觉很有活力呢。”

“表象而已，那是，单单因为居民增加的缘故...而且，我想这也不会长久下去。”

从卖酒的哥布林那里卖了一小瓶蒸馏酒，喝了一口之后就向桐人递过去。看到其一脸困惑的
表情，自己有因为之前的一大口而呛到不停咳嗽，拳斗士只好收回酒瓶，有喝了一口，笑着
据需说。

“这儿是街道附近住着的平地哥布林做的酒，虽然味道很糟糕但是非常便宜，所以还是卖得
不错的。但也因此让街上的酒店营业量下降了，看商会那咬牙切齿的样子，如果是战争之前，
商会的私人武装大概会袭击哥布林族群把他们都杀光把，但是好在现在有五族和平条约。”

“也就是说，搬来奥布迪西亚的亚人，正在抢夺人类的工作，像这样子？”

“不禁是亚人，人类自身的数量也增多了....这点小哥你也注意到了吧。”

对于桐人的提问，拳斗士耸了耸肩，仰望着昏暗得天空。

“如果你不是从法鲁迪拉来，这些话我也就不说了...在这个暗黑界，无论在哪其实土地都
是贫瘠的人类也好，亚人也罢，谁是都一直在饥渴中受苦，不论是终结《铁血时代》的战争，
还是最初为了得到一个湖泊而争战，所以说...”

对于暗黑界历史不了解的桐人和罗涅，只能默默点头。又喝了一口廉价的酒，拳斗士再次框
框而谈。

“...在这样的暗黑界，我们的祖先存货了下来，为了那个流传的传说。有一天当通往人界
的大门打开的时候，就可以移居到那富饶梦幻的土地上。”

听到这些话的时候，罗涅不禁直起了身子，但是拳斗士并没有注意到。

“小哥也好，妹妹也好，那会都参军了吧。一年前皇帝在这个世界重生的时候，宣扬着向人
界进攻时的气氛真是太厉害了。传说中的时刻到来了吗...这样想...——但是，人界的整合
骑士是比传闻还厉害的怪物，还有不知哪里来的异界军，更混乱的是皇帝还被不知名的人界
剑士讨伐了，战争也就这样结束了。”

罗涅心说，那个《不知名的人界剑士》就在面前，露出了比吃《奥布迪西亚煮》时还要微妙
的表情和冷汗。不知道坐在面前的年轻人真实身份的拳斗士，手臂架在桌子上拖着腮帮子继
续说道。

“...如果继续持续那样的战争，现在五族恐怕都已经灭亡了，所以抱怨和人界达成和平，
入手富饶的土地....根本没有希望也是事实。兽人，哥布林，人类，移居到这里的原因也是
希望活得好一点吧。但是就算是帝都，能容纳的劳动人口也不是无限的。人族的话，说不定
还能被招募到骑士团，但是你和小妹妹都太瘦了。”

醉眼转向二人打算睡着的时候，看到桐人再一次低下头。

“感谢您告诉我各种各样的事，总要一天会报答您的。”

“啊啊...要加油啊，你们俩。”

最后说了这句话，拳斗士就睡着了，为了不吵醒他，两个人轻轻地离开了。

换股广场，之前的那帮哥布林和兽人都不知不觉离开了，只剩下零星几个喝醉的拳斗士，大
部分店铺也开始收摊了，只有奥布迪西亚煮的店主依然没有变化地搅拌着锅，看来暂且待在
那的话也没有问题。

“...那，我们去找旅店吧。”

大大伸了个懒腰的桐人这样说道，罗涅慌忙问道。

“但是，住宿费怎么办？我想应该不会再有人替我们垫付了吧？”

“总会有办法的。”

不得已，罗涅只好追上笑着向市中心走去的桐人。
**  26
离市中心越近，矿石吊灯的数量也增多了，街道也变得更加热闹。

但是听了拳斗士的话之后，为了反抗这被五颜六色灯光照明的贫瘠大地，人们的热闹也正是
为了发泄积蓄的不满，这种事情也可以感觉到。

把随身带着的小刀卖给露天摊的商贩，除此之外也没有别的办法能解决身无分文的问题了。
顺便，桐人还向店主打听了哪里有便宜的旅店，就再次起步。对于因为心情沉重而没有怎么
说话的桐人，罗涅尽量用开朗的声音说道。

“这里的钱，叫做《贝库》吧，一贝库和一希尔是一样的吗？”

“诶...啊，似乎是这样的，所以说一杯奥布迪西亚煮只要十贝库还真是便宜呢。”

“还在想吃的事情吗，前辈？”

“不愧是我身边的剑士，没有能隐瞒的事啊。”[fn:51]

带着终于精神起来的面容，桐人用手摸了摸罗涅的头，然后指向前方右侧的建筑物。

“好像那里就是之前露天摊的大叔推荐的旅店。”

黑色的墙壁，以及和人界相同的带有神圣文字INN样子的铁制招牌凸显出来。看到那个，罗
涅的心中浮现出茫茫多的疑问，像水波一样在脑海中晃动，但是化作言语之前就消失不见了。

“...? 怎么了，罗涅？”

对于转过头来的桐人，罗涅赶紧摇头。

“不，什么事都没有。”

“这样啊...今天忙了一天了，赶紧休息吧。”

这样说着，桐人提起大小两个行李，向着招牌下方的门走去。

尽管时间已经接近半夜，但是好在旅店还在营业。主人是大约四十岁的人族旅行，带着对于
桐人和罗涅抱有怀疑的表情打量了十秒多后，对于兄妹二人是从法鲁迪拉来这件事并没有质
疑的样子。

但是这就又有了一个新的问题，就连桐人也没有预想到。女主人说道：“既然是兄妹的话睡
一间屋子就好了。”这样说完之后就再也不搭理理二人。只是把两人来到二层的一个房
间——一百块的住宿费要两个人好好平摊——进行了这样的提议。

“记得在早上十点的钟声想起之前离开哦！澡堂的火我已经灭掉了，先要入浴的话就到这前
面的浴场去，说是我们店的客人还会给你们打折呢！”

留下这不知道是吝啬还算是亲切的台词，女主人的身影就消失在楼下了。

罗涅呆呆地站着不知如何是好，桐人用不好意思的声音说道。

“怎么说呢...对不起，罗涅，都是因为我要找便宜的旅社，才会弄成这样。”

“不，并不能说是前辈的错...”

“我在外面随便找合适的地方睡就行，这个房间就给罗涅用吧。”

“那,合适的地方...”

“什么公园啊，房檐下啦，我一个人怎么都行。今天就休息吧，我明天早上再过来。”

对于留下这句话，就打算披上外衣从窗户出去的桐人, 罗涅赶紧制止[fn:52]。

“不行的，前辈！外面这么冷，您像拳斗士那样一定会感冒的。”[fn:53]

环视房间，除了朴素的床，还有一个二人沙发，虽然对于罗涅来说脚部还是会超出，但是也
不是不能睡。

“我的话就睡这个沙发了，请前辈睡在床上。”

“也不是不行，但是...我记得不论是禁忌目录还是帝国法，不是都有男女结婚之前禁止睡
同一间屋子吗？难道没有这项条文？”

“没有那样的条文，被禁止的是接吻...还有就是....”

“诶，什么？”

抓住带着疑惑表情贴过来的桐人的双肩，罗涅用尽全力往床的方向推[fn:54]。

“什么条目都无所谓了，前辈是人界代表剑士，而我虽然是见习但是也是整合骑士，所以没
没关系啦。”

“呜，呜哇！”

靠到床而失足的桐人，一笔股坐到了床上。罗涅接着解开桐人外套的纽扣，把双脚从靴子中
脱出，桐人毫无反驳地躺下了。

罗涅将棉质的上衣拉到颈部，轻轻盖住胸口。桐人苦笑地说。

“...总感觉像个妈妈啊，罗涅。”

“啊...对，对不起，因为小时候妈妈也是这样子的。”

“这样啊...总有一天，也要见见罗涅的父母吧。”[fn:55]

对于桐人一边看着天花板一边做出的发言，罗涅想起上个月回家的时候，亲戚提出了各种各
样的婚事，那是好不容易给推辞了。

“...诶，那父母一定会很高兴吧。”

最高兴的应该是你的弟弟吧，做出这样的回答，桐人露出微笑，闭上了眼睛。短短数秒就能
够听见“呼呼”的平稳地呼吸声，那一脸平静的面容，果然从三千千路外的人界让机龙飞到
这里还是太过劳累了吧。

看到桐人静静地躺在床上罗涅也松了一口气，脱掉自己的外套，矿石吊灯的光让人稍微恢复
了一点疲劳。

靠着沙发坐下，脱掉了鞋子并整齐地摆放在地板上，然后罗涅就横卧在沙发上。和预想的一
样，脚部稍微超出了一点，但是用上等的西部羊毛外套代替毛毯盖住之后也就感觉不到冷了。

罗涅马上感觉到了困意，为了与之抗争，就注视着被从窗户射进来的灯光照耀的桐人的侧
脸[fn:56]。


如果前辈真的来家里会怎么样...就这样遐想着，忽然意识到。

桐人的家人里，只提到了作为妹妹的《绿之剑士莉法》。她已经回到了RealWorld了，还有
父母，说不定还有别的兄弟姐妹，除此之外还有朋友。但是至今为止，桐人从来没有提起过
自己的家人[fn:57]。

想要回去...这种想法也是有的吧。

不可能不想，像是家在圣托利亚的罗涅，时不时也想要回去看看父母和弟弟。

但是，向桐人询问这个的勇气，罗涅没有。打算什么时候回去...如果这么问了，不知道会
被怎么回应。而且，也不知道回到RealWorld 的方法。

到底，是什么样的地方呢。

参加异界战争的所有人都不例外，对于连名字都不知道的RealWorld相比亲切感更多的是恐
惧感。即使罗涅也不例外，人界军和暗黑界军几乎都被消灭，那些恐怖的红骑士所在的世
界...罗涅光是想想都感觉手脚发冷[fn:58]。

但是另一反面，RealWorld也是桐人，亚丝娜，还有赶来救援人界军的剑士们的故乡。（义
乐：此段充分表示了日本玩家和世界玩家的平均素质差，此处特别强调是平均。个人觉得还
蛮写实的。）

这个世界有好人也有坏人，RealWorld也是一样的吧。[fn:59]但是现在，罗涅并不想连接两
个世界的门再次打开。

向那个世界启程的爱丽丝，看到了什么，感觉到了什么。和她再次见面，听她说吧的日子总
有一天还会再来吗？

想到这里，和看到旅店看板时一样，心再次奇妙地动摇了，终于忍受不住沉重的眼皮，罗涅
熟睡在这异乡。
** 27
被厚重的钟声叫醒，白光透过薄薄的窗帘越过窗户让房间变得明亮起来。

光几次擦过眉间之后，罗涅坐起上身。把代替毛毯的外套[fn:60]缠在身上，用惺忪的睡眼
环顾屋内。

于是很快就注意到，沙发正对面的床上熟睡着的桐人的身影。经过了八个小时，药膏的效果
也中断了，白色的睡颜显得格外幼稚，让罗涅不禁露出微笑。

这样终于和桐人在一个房间共度一夜了——当然，是分别睡在各自的床上——这点认识还是
有的。就在困意消失的同时脸也开始发热。用因为在大衣外面而有些发冷的双手贴住脸颊，
深呼吸之后总算恢复了平静，就这样一口气站了起来。

走到床的一边，摇晃着熟睡着的桐人的肩膀。

“前辈，请起床，已经到了八点了。”

话说这个声音，罗涅从昨晚就听到过好几次的钟声，在圣托利亚也发现有一个一样的。

到底是什么原因，让人界的公理教会和遥远的暗黑界首都奏出一样的钟声...这样想着，一
边的桐人突然说着不明所以的话然后把头躲到毛毯里。

“呜...在睡一会...”

“啊，不能再睡了！”

罗涅慌忙拉起毛毯，但是桐人像小孩子一样两手抓着边缘不放。

“再睡五分钟，不，三分钟就好，优吉欧...”

听到这个名字，罗涅轻轻地屏住呼吸，手从毛毯离开捂住了嘴，向后退了一步。

作为桐人好友的上级剑士优吉欧，从与最高祭司administrator的战斗中牺牲到现在已经过
去近两年了，但是对于桐人来说，与优吉欧在一起的日子似乎还没有过去，这点对于缇卓来
说也一样。

轻轻地走回沙发，罗涅坐了下来。

对于和桐人住在一个房间的副代表剑士亚丝娜，桐人心里...那隐藏起来的深深地悲伤她知
道吗？还是说就算知道，也可以在桐人身边，一直平静地，温柔的保持着微笑？

回到圣托利亚后，要和亚丝娜好好谈谈吧。当然，罗涅内心中隐藏的感情是不能说的，但是
就算如此想要成为桐人的力量这点对于二人是一样的。

就这样思考着,听着桐人说着令人吃惊的梦话过了三分钟[fn:61]，就见桐人摇摇晃晃地起来
了。睁着一半的眼睛环视房间。

注意到罗涅之后，打了一个大大的哈欠，“早上好，罗涅”这样说道。

“是...是！早上好，前辈。”

“不好意思，我懒床了，现在是几点？”

“刚才八点钟的钟声已经响了。”

“这样啊，那买...[fn:62]不是，结账的时间还来得及。”

又打了一个小哈欠后一咬牙，从床上起来。走到窗边，一口气把灰色的窗帘拉开。

“喔，罗涅你过来看，可以看到城池了哦。”

“真的吗？”

从沙发上下来走到桐人旁边，确实在窗户正对偏右一点，在杂乱的街道对面，可以清晰地看
到漆黑的巨城突入云霄。

那似乎切开了比人界更深红的暗黑领域的朝阳，半自然的岩石裸露在表面相比圣托利亚的大
教堂给人一种粗野的印象。但是反之也因此产生了一种别样的美。就算是第二次访问，桐人
也不禁大大地叹了口气。

“...与最高祭司用超自然的力量造出来的中央大教堂不同，那个城是靠人的手在岩石上雕
刻出来的。”

对于桐人的话，罗涅不由地又叹了口气。

“花了多少个月...不对，是花了多少年才建成的？”

“据说花了上百年。——那么我们也差不多该出发了，在悠闲下去的话就到了午饭时间了。”

“真是的，还不是因为前辈赖床。”

对于罗涅的职责露出像小孩子一样的笑容，桐人开始收纳行李。

重新涂上克西路茶色的药膏，支付完住宿费到了外面，没有矿石吊灯的街道被朝阳染成了红
色。

从旅店到奥布迪西亚城大约有五千路的距离，但是走在充满异国风情的街道上却完全没有感
觉。

随着向城池前进，道路变得越来越宽，左右两边的建筑物也变得很有气派，但是来往的人却
在不断减少，而亚人种则完全看不见了。

不久之后，就看到了在暗黑界算是水量丰富的河流以及石桥，越过桥之后有一个大门，再那
之前还有一段上坡，然后就可以看到由异样锐利的黑曜石之山——帝城奥布迪西亚。

对于在桥头站住的桐人，罗涅小声问道。

“...那么，前辈，怎么才能进入到城内，您有想过吗？”

于是，代表剑士那涂成浅黑色的脸微微倾斜。

“恩...就算我们的样子是暗黑界的人，也是不能容许进入城堡的呢...话说回来，如果飞进
去的话也会被卫兵发现吧...”

“也就是说，没有想过呢...”

于是罗涅这么感叹道，桐人赶紧否定。

“不不，还有从里面接应的办法。”

这样叫到，桐人拉起罗涅的手，沿着河岸的小道向左边走去。离到城里的必经之桥越来越远，
难道是像渡过河水，从岩壁上爬上去入侵到城内吗，这么想的罗涅有些发慌。

桐人所占的地方，河岸变得稍微宽广了一点，将两个皮包放到地上，再一次仰望到奥布迪西
亚城。

漆黑的岩山，底部大约有300梅路宽，而高度更近乎是两倍。看起来说是山不如说是塔，面
对街市的一侧作为城的一部分而被修刻。壮丽的柱子和窗户在朝阳下闪烁着光辉。内侧的岩
山上有似乎作为飞龙起降场的大型天台。

突然桐人伸出右手，一直往城的上方指去，然后把五指打开，仿佛在寻找什么。

“那个，前辈...您到底在做什么...”

不祥的预感一点点涌出，罗涅问道。但是桐人并没有回答，右手又持续这么呆了五秒，像是
完成了什么准备工作，点了点头。

把右手比划成剑的样子，看到其发出白色的光并伴随轻微的震动声，罗涅不禁睁大了眼睛。

桐人什么术式都没有念，那么这就是触动《世之理》的整合骑士的秘奥义，心意技。但是通
常，眼睛是看不到心意发出的声音和光芒的，到底是有多么集中？

“....嚯！”

伴随着短暂的气合[fn:63]桐人的右手以惊人的力道挥了下去。

白色的光，犹如骑士雷利的神器《双翼刃》一样飞了出去，瞬间飞过一千路，命中了奥布迪
西亚城最上面小型天台的栏杆。以罗涅锻炼过的视力看，光刃确实将数片黑曜石从栏杆上打
落。

“等...前，前，前辈，你到底在做什么啊！伤到城墙了啊！”

罗涅一边拽着黑色的外套一边惊慌失措道，桐人则站起身，用着毫无紧张的语气回答道。

“那种程度的伤用碳粉糊一下就没了...可能不行吧。相比那件事，你看。”

桐人再一次举起右手，这一次是用手向上指。很快，被被桐人用心意技打到的小天台上就跑
来一个人。不过因为距离太远了，看不见脸，但是从身材上看应该是人类。注意到扶手上的
伤痕后，就从天台探出身子，往下看。

虽说距离有一千路以上，但是桐人和罗涅所站的河道没有任何可以用来遮掩的东西，阳台上
的人，眼睛似乎注意到二人...罗涅是这么感觉的，那一瞬间。

那个人，右手放到嘴唇上。

呼哨声响了起来，等罗涅注意到时，由城堡内侧突出的大型天台上出现的一只灰色飞龙，早
已展翅起飞。

飞龙顺着城墙的侧面盘旋上升，在出现问题的天台滞空时，人影刷的一下跳上龙背，向罗涅
等人所在的河岸指了指。

“糟，糟糟糟糕了，前辈。对面已经看到我们了。”

“很快啊，真是厉害呢。”

“就算佩服也要看清场合啊！不快点逃的话...”[fn:64]
** 28
但是，桐人反而抓住罗涅拉外套的手，将其拉到自己面前。在这期间，飞龙以肉眼可以辨别
的速度猛然降下。

既然如此只能履行护卫的职责了！于是罗涅握住了不久才被赏赐的长剑的剑柄，但是这个动
作也仅仅维持了三秒钟。

到达上空的灰色飞龙突然快速挥动翅膀，吼叫着做了一个紧急刹车。其背上的骑手纵身一跃，
就算是落到了满是石头的河岸上也没有发出一点声音，可以看出身手很好。因为穿着和罗涅
一样的连帽外套和羽织，所看不到正脸。

虽然没有携带剑，但是既然能够驾驭飞龙一定是上位暗黑骑士。罗涅站在桐人面前，做好了
一旦需要就马上拔剑的准备。

——但是。

骑手稍微迟疑了一下，这时银色的飞龙落到地上发出了巨大的响声，伸长了脖子首先闻了闻
罗涅，之后又闻了闻桐人。接着，咕噜噜...发出了喉音，尖尖的嘴在桐人头部的侧边磨蹭。

“诶...？”

罗涅不禁哑然地盯着眼前这幅景象。暗黑界的飞龙，据说和人界的一样，是一种傲慢又非常
难以驯服的种族。对于初次见面的人，不可能会有这样的反应...这样想着，罗涅发现在被
灰色鳞片包围的身体上，有着无数长枪造成的伤痕。

“啊...难道说...”

比罗涅抢先一步，桐人一边抚摸着飞龙的下巴一边说道。

“不错不错，好久不见呢宵呼，你还好吧？”

对于这个名字，罗涅不会忘记的。在异界战争的时候，对于红骑士大军毫不退让，奋战到底
的传奇飞龙。不是暗黑领域的暗黑骑士，而是人界整合骑士的飞龙。主人也是作为传奇存在
的骑士《无音》——。

“难，难道说是谢塔大人吗？”

骑手的视线[fn:65]因为那小心翼翼的问话而又回到罗涅身上，一边脱下遮帽一边回答道。

“桐人...罗涅，你们在这种地方做什么？”

谢塔·Synthesis·twelve[fn:66]

在现在的整合骑士团里是继法那提欧和迪索鲁巴特之后的老一辈上位骑士。剑技据说也是可
以和贝鲁库利·synthesis·one相提并论的高手。

从最高祭司手里得到的《黑百合之剑》据说没有斩不断的东西，异界战争时面对拳斗士军团
和紧接而来的红骑士展开了足以用一骑当千形容的对决。但是战争结束的现在，她作为人界
代表大使离开了圣托利亚大教堂，在这奥布迪西亚城居住。

也就是说，作为接触对象，对于桐人和罗涅是不二之选。但——问题是，桐人是如何把她叫
到这里来的呢?桐人用心意飞刀撞击城墙，注意到的人正好是谢塔，以这种展开而行动只能
说是顺其自然的作战计划，完全没有考虑后果。

抑制住对于桐人的责问，罗涅默默地听着二人交谈。

“吓到你了真是对不起，谢塔。能够把你交出来的方式，我也只想到了这个。”

同样脱掉遮帽的桐人一边挠挠头一边道歉，谢塔则在那冰山美人的面貌中略带苦笑地点点头。

“确实是吓了一跳，注意到有人在河岸上用心意飞刀的时候，我还一瞬间以为是贝尔库利团
长复活了。”

其语调和过去一样比一般女性要简洁的多，但是相比回去话似乎变多了，声音也温柔了一些。

“...但是，你怎么知道我在那个房间？”

对于谢塔的提问，桐人耸了耸肩，

“那个屋子有着最可怕的气息...大概就是这样。”

这次轮到谢塔不满，并做出了一样的动作。

“原本以为已经可以隐蔽剑气，被想到被你从这么远的地方就注意到了，看来我的修行还完
全不够啊。”

通过这个对话，罗涅终于明白桐人并不是随意放出的心意飞刀，在右手五指并拢积蓄光的时
候，就已经注意到谢塔了吧。这是罗涅绝对无法模仿的奥义，但是——

“那个，前辈。虽然那个技能确实很厉害，但是用像小孩子叫朋友时往对方窗户上扔石子的
方法不也是一样的吗？”

对于突入起来的插嘴，桐人回过头笑道。

“诶，罗涅还有那样子把男孩子叫出来的经验吗？”[fn:67]

“我，我才没有说过这样的话！”

“那，难道说是用别的方法？”

“不，不是说了没有了吗！”

就在拼命否定的同时，罗涅清楚地看到谢塔露出微笑。

“长路旅行很辛苦吧，罗涅。先到城里休息一下吧。”

右手做了一个手势，宵呼就将身体低下，因为没有装鞍，所以勉强挤下了三个人。

前面是罗涅，后面是桐人，正中间是谢塔。三人着这样并列坐在背上。作为经历过战争的飞
龙，既是搭载两把神器级的长剑和三个人也丝毫不畏惧，在河岸上做了一个助跑就离开了陆
地。

用强有力的翅膀一口气上升，以奥布迪西亚城上部为目标飞去。卫兵们应该也注意到了，但
是因为是全权大使的龙，所以也没有引发什么骚动。

用了两分钟左右就飞到之前那个阳台的宵呼，把三个人放下之后，叫了一声就飞回了之前的
起降台。飞龙的身影消失了之后，罗涅走向黑曜石的扶手，检查了心意飞刀命中的地方。正
如害怕的那样，切实留下了一道深度大约一赛的伤痕。

绝对会被骂的，这个...这样想的罗涅移开视线，在看到眼前景色的时候，前一秒的担心马
上就随着感叹就抛到脑后了。

“...呜哇，好厉害...!”

奥布迪西亚全城都尽收眼底，与成放射状排列的央都圣托利亚不同，杂乱的接到语气说是没
有秩序，不如说给人感觉充满旺盛的生命力。

“那边，街道和地面来回交错铺了好几层啊...啊，那个就是斗技场吧，好大呢，前辈。”

把罗涅从梦中拉回的是背后的谢塔。

“还有其他很多地方，如果有时间的话不妨观光一下...虽然很想这么说...”

视线从回过头的罗涅身上移开，谢塔用锐利的目光看向桐人。

“你们不是偷偷跑出来玩的，对吧？圣托利亚，发生什么事了吗？”

“就是这样。”

桐人点点头，挺直了身板。

“全权大使谢塔殿下，我请求火速伊修卡恩司令官。”

阳台内部的房间，有着在暗黑界算是明亮的彩色灯光。墙和天花板被涂上了淡淡的粉色，窗
帘是淡黄色，地板是青绿色。巨大的暖炉里，不是木材而是矿石在燃烧。房间里暖和到穿着
外衣马上就会出汗的地步。

这里就是谢塔的个人房间的话，有些意料之外的有趣呢...这样想的罗涅，马上就注意到这
里的主人并不是她。

与暖炉相反的一侧放着一个长度大约一梅路的小床，向那个走进的谢塔，露出了一个任谁都
会大吃一惊的温柔微笑。

对于站在后面的罗涅和桐人，谢塔悄悄地招了招手。不让脚步发出声音，二人向床上窥视，
被白布包裹的小婴儿正在香甜的顺着。

大概才刚刚出生三个月吧，暗红色得头发像棉毛一样松软，鼻子，嘴，和放在头两侧的双手
都小的让人无法相信。

虽然有听说过，但是没想到这就是婴儿。整合骑士谢塔和拳斗士团长伊修卡恩的孩子。应该
是女孩子吧...罗涅一边这么想，一边小声向谢塔确认。

“...名字，是什么呢？”

“莉泽塔”[fn:68]

带着有些骄傲的声音回答道，谢塔看向桐人。

“最开始的一个音，是取自绿之剑士莉法”

“是这样啊...我才知道。”

这样说着的桐人，注视着熟睡的婴儿露出微笑。

然而这平静只持续了短短二十秒，打破它的是走廊一段的开门声，和在那之上像是迟缓的猫
的声音。[fn:69]

“莉泽塔酱，到了喝美味牛奶的时间了哦~~”

进入房间的，是双手端着碗的年轻男子。留着像是熊熊燃烧般的赤金色头发和一个简朴的银
色头环，既是是冬天上半身也只有一件亚麻的薄布。下面是短裤搭配凉鞋，但是露出的肩膀
和手臂都有无数肌肉和伤痕。而且，因为被挖出而陷进去的右眼，正是经历过战争的证
明[fn:70]。

但是与之相对，现在年轻人的脸上，绽放着比吃了蜂蜜蛋糕的桐人还要灿烂数倍的笑容，，
让罗涅不禁目瞪口呆。

之后，独眼的男子很快也注意到站在床边的罗涅和桐人，慢慢的笑容消失了。粗壮的眉毛因
为惊讶而挤到一起。视线在谢塔而二人之间来回往返了数次。

在男子说出什么之前抢先一步，桐人举起右手问候道。

“哟，伊修卡恩，好久不见。”

于是，作为暗黑界总司令官和拳斗士团长的伊修卡恩，睁大了像是快要飞出去的左眼。

“额，你小子是...桐，桐人吗！？怎么是那种像假发一样的颜色...不管这个，你在这里做
什么！？下次会议是在三月吧？”

“不，因为有急事，没通知就过来了，不好意思。”

“啊，别介意...不，不对，你给我等等！”

伊修卡恩的眉心变得像峡谷一样深，像是滑动一样过去的谢塔从丈夫手中拿走碗。

对这个丝毫不在意，拳斗士团长发出低吟。

“桐人，你小子，刚，刚才的事听到了吗...”
**  29
“刚，刚才的...啊，好喝的牛奶...那个吗? 哎呀，伊修卡恩也完全成了一个父亲呢，哈哈
哈。”

“哈哈哈，你个鬼啊！ 既然那些全部都被你听到了，不好意思你可不要以为可以全身而退，
这一击我要连同你的记忆一起打飞！”

“等，前，前辈...”

对于作为护卫此时不能判断如何行动的罗涅，桐人一边用一只手示意其退下，一边站在伊修
卡恩面前，伸出左掌。

“好，来吧”

“呜啦啦啦！”

随着呐喊，伊修卡恩一踏地板，在空中划过一道红色的轨迹，用罗涅无法捕捉的速度出拳，
正好命中桐人的手掌。

爆发出来的冲击音呼啸而过，让窗帘和装饰布都剧烈地震动。很明显是具有恐怖威力的一击。
然而桐人在身体后仰的桐人用脚踩住地板，就这样单手接下了伊修卡恩的拳头。

拳斗士团长和人界代表剑士在左手和右手相互接触时就静止在那里。[fn:71]不过没过多久
伊修卡恩就抬起头笑了。

“你一点都没变弱呢，桐人”

“恩，你也是，伊修卡恩。”

站在相互偷偷露出坏笑的二个男人傍边，谢塔无言的摇了摇头。（谢塔OS：MDZZ）刚才的轰
鸣声应该吵醒了小婴儿吧，这样想的罗涅向床上看了看，应该说不愧是最强剑士和最强拳斗
士的孩子，莉泽塔对于刚才的骚动像是完全没有注意到似得依然在幸福的熟睡。

把因为轰鸣声而飞速冲过门来的卫兵赶了回去的伊修卡恩，把椅子拉起，这就样两条腿拖着。
然后让它与剩下两条腿一起立放到窗边。[fn:72]卫兵虽然对罗涅和桐人充满怀疑，但是也
接受了总司令官说的“别在意之后再跟你说明”。不知道是《力之法则》的效果，还是因为
伊修卡恩的人品。

卫兵出去后不久九点的钟声就响了起来，以这个作为起床信号的婴儿睁开眼睛，开始辗转和
哭泣。谢塔把她从床上抱起来，坐到椅子上。用在人界也有的，用浮波木的果实加工而成的
奶瓶开始喂牛奶。

成熟的浮波木果实就像透明的玻璃一样，内部是中空的。但是乳头状的凸起正好具备合适的
弹性和通水性，[fn:73]据说是大地之神提拉利亚专门为了婴儿而创造的植物。但是，如果
真是那样的话，实际上就不是提拉利亚神，而是Realworld的人创造的——不禁让人这么想。
看了看因为被吵醒而发出“嗯咕”“嗯咕”声音的莉泽塔，谢塔抬起头说道。

“要试试看吗？”

“可以吗？”

“当然”

谢塔伸出胳膊，用左腕抱住婴儿，右手拿起奶瓶，一边允诺一边靠了过来。

莉泽塔用和母亲差不多的灰色瞳孔看了一眼罗涅，就再一次开始喝起牛奶。虽然在大教堂的
育婴房有过同样几次喂给男婴牛奶的经历，但是因为莉泽塔是女孩子，所以感觉有些不一样。

“虽然我也想过用自己的乳房哺乳，不过拳斗士好像世世代代都是靠秘方调制的牛奶。”

似乎是听到了谢塔的话，在小桌子对面和桐人彼此报告近况的伊修卡恩看向这边说道。

“那是当然的了，喝那个的话不仅能防止生病，还可以强化筋骨，能让孩子茁壮成长。”

在人界，也有通用神圣语——就像《窗帘》和《桌子》一样被一般民众所使用的的神圣语
《牛奶》，就是牛乳或者羊乳加热到人体温度后再加入一些药物成分就可以作为婴儿专用的
代用乳，就是这样。到底加入什么也会因为家族和地域变化有所改变，这也就是所谓的“秘
方调制”。和谢塔说的一样，虽然也听到过母乳再是最好的，但实际情况并非如此。如果使
用浮波果的哺乳瓶和牛奶的话，原本就很忙的农民和商人恐怕要多付出数倍的辛苦来养育婴
儿。

无论是谢塔本人的还是拳斗士团体的秘制牛奶，对都没有任何不满的莉泽塔很快就喝光了，
还打了一个小小的嗝。转眼间又露出很困的表情，于是谢塔从罗涅手里接了回去，把她放回
了床上。

马上走回来的谢塔，坐在椅子上，表情也从母亲变回了骑士。说道。

“那么，发生什么事?”

点了一下头的桐人，开始讲起两天前在南圣托利亚发生的杀人事件。

伊修卡恩和谢塔安静地听着，讲到犯人涉及到山地哥布林奥罗伊的瞬间，二人不禁屏住呼吸。
但是很快又叹了口气。桐人和罗涅是乘坐《龙》从人界飞过来的，昨天才到达奥布迪西
亚——到这里为止。

“...原来如此...话说，还真是麻烦你了。”

对于总司令官的慰问，代表剑士摇了摇头。

“不，这边才是。我想先通知你会比较好，回复的话下个月也可以。”

现在圣托利亚和奥布迪西亚的联络，是靠骑兵通过十几个街道和城堡传令，单程实际上花费
的天数有两周左右。而且，还有被暗黑界栖息的大量魔物袭击的危险。

“啊...这种时候要是有主骷髅头就好了...”

对于伊修卡恩的感叹，桐人也惋惜地点点头，借此机会罗涅问道。

“那个主骷髅头...是什么？”

“啊，我也是异界战争结束的时候才知道的。是异界战争时期，皇帝贝库塔为了命令包括伊
修卡恩在内的十侯所使用的一种神器。一个主骷髅头和十个小骷髅头为一套，对着主骷髅头
传话的话，声音一瞬间就可以穿到小骷髅头所在的地方。”

对于桐人的说明，罗涅睁大眼睛。

“一，一瞬间！？有那种东西的话不久不需要信件和快马了吗？”

“也不是不需要了...因为只能从主骷髅头到小骷髅头单方面传送，只有一套的话还不能进
行交流。”

“但是战争结束时主骷髅头和几个小骷髅头就不见了，对于没有的东西有再多幻想也没有
用。”

又是一声叹气，伊修卡恩伸了一个大大的懒腰。

“比起那个问题是，在人界杀人的方法，是没有的...去人界观光的家伙，都是通过五族会
议和作为总司令官的我的名义所标注的，严禁偷窃和闹事的文件。我是一个一个签署的，只
要《力之法则》还有效果，在全暗黑界能违背那个文件的只有一个人。”

那个人当然是伊修卡恩自己，就在罗涅这么想的时候，谢塔插嘴道。

“是两个人。”

“...只有两个人”

看到面带苦涩进行订正的伊修卡恩，桐人的嘴角稍微露出了些笑意，但是肯快有回到了苦恼
的表情继续说道。

“恩，我也是这么认为的。实际上奥罗伊在人界用来杀死清洁工的短剑在保管库中消失了。
恐怕是用钢素临时生成的《即时武器》，而且注意到这一点的不是我而是罗涅。”

“诶，你还真是培养出一个不错的弟子呢。”

“额，也不能说是弟子...”

就在桐人歪过头的同时，罗涅也开始自考自己究竟算是桐人的什么人，为了不陷入如此的思
考而赶快转换思路，罗涅举起右手。

“那个，我之后也有想过...那个有问题的凶器，奥罗伊先生在看到的一瞬间也以为是真的，
其很好的再现了山地哥布林的短剑，因此我想这件事会不会与暗黑术士有关系...但是...”

说到这里罗涅闭上了嘴，看了看伊修卡恩和谢塔后，又鼓起勇气继续说道。

“...在那之前，现在的暗黑术士公会，到底是什么样的呢？”

夫妻二人交流了一下眼神，伊修卡恩咳嗽了一声回答道。

“这个本来想下次会议再报告的...就目前的情报，暗黑术士公会的状况连我们都不清楚。”

“这是怎么回事？”

桐人皱起了眉毛。

“作为前任总长的迪·安·艾路被绿之剑士莉法杀死后，由一个叫做凯·由·卓伊的女术士继承，
但是既是在不懂暗黑术的我眼里看来，那个女人多少缺些迫力。”

对于伊修卡恩的言论，谢塔补充到。

“以那个人比，我的术力更高。”

“所以说，稍微调查了一下，发现那个叫凯的在迪活着的时候在公会里最靠前的时候也就是
第十名，也就是说，上位的家伙统统都消失不见了。”

“暗黑术士们，在《东之大门》的战斗中战死了两千多人吧，会在那个之中吗？”

对于桐人的提问，伊修卡恩当场否定。

“我不这么认为...那群家伙，对于生存的执念跟魔兽一样。迪的话，如果不是和绿之剑士
战斗的话现在也活下来了吧，上位的十人绝不是那么容易就战死的人。”

视线回到罗涅身上，伊修卡恩继续说道。

“...因此，现在在五组会议中收容暗黑术士公会也没问题，但那终究只是个空壳。真正有
实力的术士现在想必正躲在暗道里伺机待发，这种可能性也是有的。也就是说，和造成人界
的那个事件的可能也有关...但是，你叫罗涅对吧，你不是这么想的吧？”

“是，那个，虽然没有依据否定...但是我想，如果幕后黑手是潜藏在低下的暗黑术士公会，
语气特意用钢素制作仿真武器，直接去弄一把真的山地哥布林短剑也是可能的吧，这样...”
**  30
“确实如此，虽然对于哥布林来说，印有氏族纹章的短剑是非常重要的东西，既是如此因为
是大量铸造的量产品，通过偷取或是买卖，准备一两把也不是不可能。”

伊修卡恩这么说道，桐人对此点点头。

“真凶的目的，应该是让奥罗伊背负杀人的罪名从而让你人界和暗黑界的关系变得紧张，这
样的话，准备真的短剑应该能有更好的效果...——也就是说，真正的犯人，是人界的什么
人...这样子吗...”

“如果是那样的话，就有更大的谜团了。”

谢塔用比她那细长的眼睛还要清秀的手指点明。

“人界人的话，远比暗黑界人受到更严格的法则束缚。杀人是明确违反禁忌目录的，这样的
话杀死清洁工的人界人的话，那他明显可以无视禁忌目录。”

与桐人一起，罗涅也点点头。

而且，事件之后和法那提欧他们交谈时也被告知，既是是整合骑士这样不受禁忌目录束缚的
人，也不可能对于没有犯罪的清洁工这样的一般市民，靠自我独断夺取全部天命。

到了这边也什么都没有了解到，这样说着无奈的叹了口气，桐人慢慢摇了摇头。伊修卡恩也
无语地点点头，暂且做出考虑的表情过后，像是为了转换气氛，拍了拍那那粗犷的双手。

“——好吧，情况我差不多都了解了。虽然很遗憾，但是我想这边去人界的观光事业还是暂
时中止比较好...”

“啊...其实现在正在防止情报泄漏到圣托利亚各地，但是如果有第二起或者第三起事件发
生的话代表议会也不能控制住，届时只能暂时关闭《东之大门》，在人界滞留的观光者也需
要早日回国。”

从心底里感到遗憾地这样说道，接着桐人又用更加沉重的语气说。

“...还有就是，在圣托利亚中央大教堂受到保护的山地哥布林奥罗伊...只有他不能马上回
去，或许还能从他身上知道些什么，比如被陷害的理由。——奥罗伊是居住在锯齿丘的乌波
利氏族吧，对不住了...”

“啊，乌波利那边我会出面，把事情详细告诉他们。”

点头之后，伊修卡恩用独眼瞥了一眼窗外，又再次看向桐人。

“先不说从这里人界的，从人界过来的商队要怎么办？即使在现在的奥布迪西亚，还有一队
正在此停留。”

“呜嗯，怎么办呢...”

桐人抱起胳膊念叨。

所谓的交流事业，是以从暗黑界往人界派入观光团，还有从人界往暗黑界派驻商队开始的。
现在还处于实验的规模，马车数量和携带的商品还处于摸索性买卖的阶段。但是暗黑界有用
于照明的发光石和许多类似的其他珍品，嗅到大生意的大商人为了申请派遣许可而蜂拥而至。

“...如果事件的幕后黑手势有组织的势力，那么可能在这个奥布迪西亚也有同伙，与杀死
清洁工相对...也就是说也可能会发生人界的商人被暗黑界居民杀死的情况。但是，商队里
配有训练有素的人界军护卫和神圣术士，商人们也被要求没有允许不能随便外出，我想应该
不会那么容易...”

对于桐人的言论，谢塔点点头。

“我想也没有必要马上中止合作，商人作为媒介从人界带来贵重药物，因此比预想的要更加
受欢迎...安全起见，在奥布迪西亚的商队我会让我的弟子贴身保护。”

“弟，弟子？...谢塔你是一个人到这里赴任的吧...也就是说，不是一个人来的吗？”

桐人被涂成浅黑色的面孔露出惊讶的表情，伊修卡恩则用骄傲和担忧交织的表情回答道。

“那是因为，现在谢塔是作为人界全权代表兼暗黑骑士团客座大师。”

“客，客座大师是？”

“在去骑士团视察时，被年轻的队长发出挑战，结果用借来的剑...而且不是剑身而是剑鞘，
把对方打得落花流水。现在在骑士团总部还有自己的道场了呢。”

“虽然我的徒弟不到十个人，但是各个身手都不错。”

“这，这样子啊...”

对着说不出话来的桐人，谢塔用认真的表情说道。

“请你务必来道场，和我的弟子们练习。”

“不，不。我的话，根本没有好好学习过传统剑术。”

靠着椅子咔叽咔叽往后挪的桐人，被伊修卡恩伸出的左手抓住肩膀。

“那样也好，去过暗黑骑士团之后再来拳斗士的修炼场吧。对你的强度表示质疑的家伙可是
有不少，趁这个机会好好把《力之法则》印进那帮家伙脑海里吧。”

“什么就好啊！我可是想要当文官的！”[fn:74]

...啊这样一来也就逃不掉了。

看着陷入慌乱的桐人的罗涅不禁这么想。

分别借用谢塔和伊修卡恩专用的浴场，罗涅和桐人洗去了长度跋涉的灰尘和涂抹的颜料，然
后被带到同一层的客房中，对于二人的突然来访，是作为急报员被通知到城内的。

因为桐人隐瞒了人界代表剑士这件事，所以引领的卫兵以“不想使者的轻装”为由，用看可
疑人物的眼光打量了二人一番，但是在注意到二人腰上的剑之后态度马上就改变了。果然在
暗黑界，神器级的武器也和人界一样的稀少。

在两个相邻的客房休息过后，中午起和伊修卡恩还有谢塔夫妇二人一起进餐，午后被带着乘
坐大型马车到之中心的暗黑骑士团本部和拳斗士修炼场，虽然桐人最后统一和作为团长辅佐
的单手巨汉拳斗士认真比试,但也只是一边拼命说着“手下留情”一躲闪。

之后又参观了中央市场和大斗技场，当然也不完全是游山玩水。桐人和伊修卡恩，也就这时
间对这次的事件和交流事业交换了意见。罗涅也履行护卫的职责时刻注意着周围，不过有上
位整合骑士《无音》谢塔同行，就算真的有什么袭击者也没有罗涅出场的份，事到如今罗涅
才注意到这点。而谢塔无论是骑着宵呼下来的时候，还是现在在街市侦查，都没有佩剑。

“那个，谢塔大人，您没有带剑吗？”

对此，骑士一瞬间因为怀念而眯起了眼睛，然后点点头。

“恩，对于我来说《黑百合之剑》是最初也是最后的爱剑。”

“......”

整合骑士失去了心心相映的神器到底是什么感觉，对于现在罗涅来说还想象不出来。对于说
出冒失言论的罗涅，谢塔的指尖轻轻触碰到她的手，露出淡淡的微笑。

现在的我是作为《无音》而是作为《空手》的骑士，对于这件事我反而感到有些高兴。...
只是偶尔想起黑百合，会感到有些寂寞。

“这...样吗...”

——这个人，现在处在我不能想象的更远更高的位置上。

再一次，感受到自己作为见习骑士和上位骑士之间存在的遥远的差距，罗涅咬紧牙关。这次，
是谢塔提出了意料之外的问题。

“那把剑，已经是属于你的了吗？”

“是，是这样的，不过名字还没有决定好。”

罗涅一边点头，一边抚摸银白色的剑锷。

“这样啊，看来联系还很薄弱，但是是很好的剑。一定要珍惜...虽然大战已经结束了，但
是骑士的斗争是不会结束的。”

“——是！”

罗涅用响亮的声音回答道，坐在椅子前面的伊修卡恩和桐人不禁吓了一跳，回头看了看。

不久马车就穿过了市区，按照正规行程通过大桥和城门回到奥布迪西亚城。

高度有五十梅路，是中央大教堂的五十层不到的奥布迪西亚城，并没有配备类似升降台的东
西，也就是说要达到上层必须徒步走上去，这也是对付贼人的一种方式吧。

到伊修卡恩夫妇所居住的四十九层，四人是没有休息一口气爬上去的。夫妻二人和桐人都丝
毫没有喘息的样子，对于有些气喘吁吁的罗涅而言，这样的事情也只能说是修行不足了。

用深呼吸进行了调整，对于等待的三人寒暄了一下。注意到大台阶还在往上而抬起了头。

“那个...谢塔大人，这上面是什么地方？”

回答这个问题的，不是全权大使而是总司令官。

“五十层玉座所在的房间，我也只去过一两次而已。”

“诶...既然是玉座，那是皇帝的？”

这次换成桐人提问了，伊修卡恩皱着眉头点点头。

“近两年前[fn:75]皇帝降临的时候，就是在这上面”

“稍，稍微看一眼可以吗？”

对于兴致勃勃的桐人，伊修卡恩摊开两手。

“当人...虽然我很想这么说，但是五十层的门，在贝库塔死后，确切说是被杀死的瞬间就
被《封印之锁》关上了，自那以后无论用什么方式都打不开。据说从五十层可以看到尽头山
脉和东之大门，所以我也试过上去看看...”

听着拳斗士的抱怨，整合骑士对于“什么东西都不能斩断”这句点头表示赞同。

“我也从借出宝物库里的剑试了试，但是没有能斩断锁链，如果是黑百合之剑的话，一下就
断了[fn:76]”

“...哼...”

从桐人的声音中，罗涅判断出桐人绝对在想“想要用夜空之剑试一试”，于是赶紧拉了拉桐
人的右袖，感觉到罗涅“绝对不可以！”的意思，桐人只好恋恋不舍的望着上面点点头。

“这样了，那我就不去看了。”

“作为代替，晚餐我会让人准备的一些山珍海味，就好好等着瞧吧。”

“我很期待呢。”

看到谈话结束了，谢塔后退了一步。

“那么我去给莉泽塔准备牛奶和晚餐的座位。”

“啊，我也去，今天我只看了她一次呢”

对于做出父母样子的二人，桐人一边挥手一边目送二人。然后又看向通往最顶层的楼梯。对
此罗涅沉默地摇摇头，桐人只好露出苦笑。

“明白了...那么我们也回房间吧。”
** 31
晚饭的座位，是伊修卡恩，谢塔，桐人，罗涅还有莉泽塔一共五个人。温暖热闹的氛围就像
是在被圣托利亚的家中吃晚餐一样开心。

伊修卡恩带着一半恶作剧的心态介绍着像是《尼杰罗伊蜥蜴烤串》，《油炸西巴那蘑菇》等
一个个奇特的美味，而桐人每次都来者不拒然后发出奇怪的声音，就这样每次都会把莉泽塔
逗得呵呵直乐。看到那样的爱女，伊修卡恩和谢塔也露出幸福的微笑。

有宝宝真好，有家人真好。接连发出新的感叹，吃完饭的罗涅，完成了今天第二次洗浴后回
到客房。

浴室虽然与中央大教堂的相比确实要小得多，但是考虑到这里是高度有五百梅路的巨城的最
上层，全天都有热水供应就已经算是奇迹了。而且好像也不像中央大教堂那样是依靠神圣术，
到底是如何把热水运上来的然人觉得有些不可思议。说不定以前是岩石的时候山顶附近就有
热水涌出，加工成城池后就对水源作为洗浴和暖气进行利用。

和昨晚的便宜旅店相比，房间要暖和得多，床也非常柔软，特意换上睡衣的罗涅在九点的钟
声敲响之前就有些困意了。因为明天一早就要开始启程回人界了，所以就这样早点睡觉时最
好不过的了。但是一天就这样结束了感觉有点可惜，于是横躺着注视着北面的墙壁。

墙的对面，桐人也已经准备睡觉了吧，还是已经睡着了呢。从央都出来，和桐人在一起已经
过了四十个小时以上了，但是没有什么可以说得上是大事的事情[fn:77]。

当然，对于比什么都重要的护卫任务，绝不是为了能和桐人聊天才提出同行的——即使如此，
罗涅仍不断拼命忍住起来去敲隔壁房间门的冲动。

对于桐人而言，亚丝娜才是意中人吧。同样最为RealWorld的人，像史提西亚神一样美丽，
虽然对谁都一视同仁的温柔，但是拔出剑来又比任何人都要强。在异界战争时期，罗涅除了
在马车里颤抖什么事情都做不了，但是亚丝娜却身负重伤血流不止，即便如此仍拼命保护着
桐人。和那样的人是不可能有争夺的资格的。

自己的这种心情，是不能说出口的，绝对...

把头埋进优质的毛巾中，罗涅使劲闭上眼睛，但是失去的睡意却怎么都回不来了。

但是因为长途跋涉的缘故，很快罗涅就连矿石吊灯都忘记关就睡着了，不过很快又因为注意
到微弱的声音而醒了。

窗外还是一片漆黑，从身体感觉来说现在听该是半夜两三点左右。横躺在床上挠了挠耳朵，
以为刚才是做梦就再次闭上了眼睛，就在这时。这一次确实听到了，从门外传来似乎很紧迫
的声音，接着是很多慌乱的脚步声。

带着睡意从床上下来，把耳朵贴到门上，等着可能是卫兵的脚步声渐渐远去后才打开门，正
好看到隔壁一样打开门探出头的桐人。

“前辈...到底发生了什么事？”

“不知道呢...卫兵们好像都到下一层去了。”

眨眨眼很快就完全清醒了的桐人，给罗涅肩上披上羽织外套后说道。

“我们也去看看。”

“恩..不过没关系吗？”

“或许可以帮什么忙。”

拍了拍罗涅的肩，罗涅也只能点点头。

“但是如果影响到人家了要马上回来呢！”

呼喊着已经开始奔跑的桐人，罗涅也在后面追了上去。

从楼梯跑下去，到了四十八层的同时就听到了比刚才还要清晰的叫声。

“快下去！”那个声音毫无疑问是伊修卡恩的，点头确认后，就顺着宽敞的走廊往南走。

到尽头后往右转，正前方可以看到两个大门。大概是相当重要的设施，被银物装饰的黑曜石
大门敞开着从里面不断可以听到卫兵充满恐惧和厌恶的叫声。

桐人和罗涅一口气通过长度大约二十梅路的房间，一口气冲进门内。

最终，左右两边亮起无数耀眼的光，让眼睛一瞬间有些眩晕。站在道路前方的几十名卫兵都
提着矿石吊灯，被的灯光照亮的房间被无数的武器和防具装饰，宝石和装饰品也有相似的反
射。这里毫无疑问就是奥布迪西亚城的武器库，不对，是宝物库。

“你这个怪物...!”

卫兵们的对面，再次想起了伊修卡恩的声音。停下脚步的桐人，一下就从拔剑的卫兵所组成
的人墙上飞了过去，消失在另一边。不得已，罗涅也只能把睡衣和作为外套的羽织系紧后就
通过短暂的助跑踩了下地板。

桐人和亚丝娜那里学习到的艾恩葛朗特流剑术，特点除了连续技之外就是对奔跑和跳跃的重
视，对此罗涅每天都有练习。终于发挥出效果从卫兵团上面成功飞过，听到背后传来男人们
惊恐的声音，但是很快就意识到那并不是指自己。

前方数米，穿着睡衣的伊修卡恩和谢塔站在一起，然后，与他们相对的另一面，是两个不知
道是什么的黑漆漆的东西。

怪物，除此之外也没有词可以形容了。整体的样子和人及兽人差不多，但是两个手臂格外的
长，像某种鱼一样的头有着向内凹陷的圆形的嘴，里面长着无数牙齿，嘴也在不停放缩。越
来越细的头部两侧长着四对眼睛，背部长着用很薄的皮膜组成的翅膀，尾巴从腰部耸拉下来。

“哪个是...米尼翁！”[fn:78]

对于桐人交出名字，伊修卡恩和谢塔回头看了看。

“不好意思，把你吵醒了。但是这是内部的问题不能把客人卷进来。那样的怪物，我一个直
拳就可以解决。”

伊修卡恩紧握的拳头，发出火焰般的光芒。但是站在一起的谢塔突然伸出手，制止了丈夫。

“米尼翁的血有毒，不能贴身攻击。”

“呜咕嗯...”

伊修卡恩碎念这，似乎理解了二人的谈话，两只米尼翁开始呼咻呼咻地吐气。

虽然这是第一次亲眼所见，但是罗涅对于米尼翁也是有所了解的。在暗黑领域被暗黑术士操
控的人造生物，在《异界战争》的开局东大门之战被大量投入使用，不过被骑士长贝鲁库利
神器《时穿剑》的武装完全支配术全部消灭了。因为对于人界军完全没有造成伤害，所以在
众人印象中也就是大蝙蝠一样的怪物，但是实际上远比那要可怕的多。身高接近两梅路，长
长的手臂前方的爪子闪着黑光，长而锐利。

而且，对于各种术式以及穿刺和打击攻击都有很强的耐性，对其最有效的方式就是用锐利的
刀锋进行斩击。伊修卡恩也好，谢塔也罢都没有带剑，早知道就从房间里把剑拿过来了，因
此而后悔的罗涅和桐人也自然也是空手。[fn:79]

“总司令阁下，这里就交给我等吧”

后方的一个卫兵这么喊道，但是伊修卡恩依然顽固地没有动。

对峙的米尼翁似乎也受到命令的样子，发出啾啾的威吓声，但是并没有打算攻击的样子。怪
物左右两边的架子倒在地板上，宝石和装饰品散落一地，看来也并不是来抢夺珠宝的。

说起来，这两个怪物到底是如何在不被卫兵注意到的情况下，来到与最上层如此接近的宝物
库...这样想着，罗涅才注意到其背后有一对巨大的翅膀，根本不需要傻傻的爬楼梯，在暗
夜的掩护下飞上来，从窗户入侵。仔细看一下的话，米尼翁后面的窗户和金属框架都被破坏
了。

能够做到这点的话，也就是说....也就是说——[fn:80]

此时罗涅脑的脑中，思维像是激烈的火花一样绽放开来，旁边的桐人也急促地呼吸着。

“你们两个，快躲开！”

喊叫的同时伸出右手，张开的手掌周围是闪耀着青白色的光点——冻素。一口气生成了大约
三十个。

看到那个的伊修卡恩和谢塔，立刻退离原来所在的位置。桐人马上射出冻素，并在米尼翁周
围解放。以远比普通冻素更大威力更广范围扩散开来，用如此高强度术式控制的米尼翁就像
是被冷冻保鲜一样，黑色的巨大身体被冻成了白色。

“嚓呀呀呀”

米尼翁用那长长的头部嘶叫着，知道嘴部被完全冻住才停止，也不动了。其可怕的威力，就
连用黏土制作而成拥有很强抗火性和抗冻性的米尼翁都承受不住。不过就算被这么冻着，天
命也不会减少多少——。

但是这一点，桐人当人也考虑到了。伸出右手，很快下达了指示。

“两位，现在！”

“好嘞！”

伊修卡恩这么叫着，踏了下地板，谢塔也紧跟上去。

“呜啦啊啊！”

伴随着气合来回出拳的伊修卡恩，把右边的米尼翁的身体打个粉碎。谢塔的手刀也将左边的
米尼翁的身体垂直切成两半。

瞬间，左边的就化作无数碎片，右边的也裂成了两半左右旋转，因为被完全冻住了，所以带
有毒性的血一滴也没有漏出来。

背后的士兵发出欢呼声，回过头的伊修卡恩先是愣住了，接着露出感慨的笑容。

“桐人你这家伙，真是比传闻中还要乱来呢。虽然只是元素生成，但就算是上位术士听说一
只手五个就已经是极限了...”
** 32
“有话之后再说，伊修卡恩！”

从打断了对自己称赞的桐人的声音中，感受到了比在对夫妻二人下达指令时还要紧张的气氛。

“米尼翁们，既没有偷取宝物，也没有对我们进行攻击。放出那些家伙的术士的目的，一定
是拖延时间或者佯攻。”

听到这个的一瞬间，罗涅脑海中闪过的光瞬间变成了具体的不安。同时，谢塔的脸色也唰一
下青了。

“难道说...”

小声嘀咕了一下，谢塔猛然跑了起来，从罗涅和桐人，还有卫兵之间像风一样掠过，从宝物
库中奔出。

“我们也去！”

桐人叫喊着，一边拉着伊修卡恩那人界东帝国一样的睡衣跑了起来。

“什么跟什么啊，佯攻是...”[fn:81]

在擦亮的黑曜石地板上啪嗒啪嗒跑着的拳斗士发出疑惑的声音，桐人则用嘶哑的声音告诉他。

“大概，术士真正的目的，是比宝物更重要的东西。”

“更重要的...”

重复一遍的伊修卡恩，单眼突然睁得像鸡蛋一样圆。罗涅甚至觉得自己听到了赤金头发直立
起来的声音。

“莉泽塔。”

低声说出自己爱女的名字后，拳斗士的双脚发出淡淡的红光。

嘎！狂奔过后的地板，被踏出像是蜘蛛网一样的裂纹，以超越常规的加速，把桐人和罗涅抛
在后面，并且仅仅比先走的谢塔晚了几秒到达楼梯处，开始一次四五阶地狂奔上去。那之后
不久，桐人靠着滑步也追了上来。（滑るような足運びでキリトが付いていく）

全力抵抗因为颤栗而麻痹的身体，罗涅也拼命奔跑着，沿着楼梯往四十九层的走廊跑，此时
三人的身影已经看不到了，只能听到脚步声。

就这样追赶着奔跑，通过最初孩子的房间，到达了好像是夫妻寝室的尽头的房间。

刚开门冲进去，扑面而来的是一股刺鼻的恶臭。

只有一个小型矿石吊灯作为灯源，让宽敞的屋子显得昏暗，就算如此，破碎的窗户，那前面
残留着一大片乌黑的血，还有倒下的两个卫兵的身影都看的清清楚楚。

大概地上的那摊血和恶臭都是因为米尼翁的缘故，倒在血泊中的士兵还有呼吸，但是痛苦的
喘息大概是因为受伤了，或是因为中毒的原因。房间里，除了卫兵之外只有伊修卡恩一人的
身影。

“古德，甘波鲁，发生了什么！”

对于一边叫喊着一边靠近的伊修卡恩，一个卫兵一边挥手一边把他推开。

“司令官殿下，不可以碰到这家伙...”

另一个人，带着恐怕是因为痛苦和耻辱而扭曲表情报告道。

“就在您二位同时去下面的时候，突然传出窗户被打碎的声音...进来的，是个黑色的怪
物...就在我们考虑如何应对这个怪物的时候，房间里不知何时出现了一个暗黑术士，对我
和古德施加了眩晕魔法...”

因为呼吸急促，所以二人轮流讲述着，另一个人接过话来。

“我们之后就中了那个怪物的毒，动不了了。那个术士就把莉泽塔从床上抱起来，坐着怪物
从窗外飞走了...这就是我最后看到的了。”

“...这样啊...”

点了点头的伊修卡恩，牙齿咬得嘎嘎作响。

往房间的右侧看，墙边上是夫妇二人使用的双人床，更深处则放置着很小的儿童床。那一定
是莉泽塔的，大概是白天在阳光明媚的自己房间，晚上则到这里和父母一起睡。

把那么可爱，而且只有三个月大的小婴儿拐走，无法接受这么可怕的事情没有被制止，罗涅
只是呆呆地站在那里。从破坏的窗户对面的阳台，桐人和谢塔走了进来。

“...什么都看不到，暗元素探索术也没有反应。”

谢塔这么小声说道，桐人也微微摇摇头。

“我也什么都没感觉到...”

充满懊悔地说着，桐人看向倒在地板上的两个卫兵。举起右手，与宝物库那时一样生成了元
素，不过这次不是冻素和是发着白光的光素。数量有十个，把它们分成一半，碰到卫兵们的
身体。

温暖的光辉包围着二人，就像是被那光辉蒸发了一样，地上的那摊血基本完全消失了。卫兵
们感到不可思议地摸着自己的身体，深呼吸过后，突然跳了起来。向谢塔和伊修卡恩狠狠地
低下头。

“司令官殿下，全权大使殿下，我们不会为自己的失责做任何狡辩。”

“无论如何，对于让本应被保护却被抢走的莉泽塔大人，就让我们用生命...”

对于接连谢罪的二人，伊修卡恩使劲抓住二人的肩膀。

“就算那样莉泽塔也不会回来的，比起那样，为了夺回女儿请把力量借给我！”

尽管心中已经乱成一团麻，伊修卡恩还是用压抑的声音这么说道。至此，二人才重新站直。

“首先我想听一下，闯入这里的暗黑术士长什么样？看到他的脸了吗，或是听到他的声音？”

“是...”

首先做出回应的是名叫古德的高个子卫兵。

“带着乌黑色的头巾，有些偏瘦，但是没有看到脸...从声音判断是女人，但是暗黑术士一
般都是女人。”

“确实...”

伊修卡恩咬了下嘴唇，取代而之的是桐人开口问道。

“从那个暗黑术士逃走，到我们进入房间大概有几分钟？”

回答这个问题的，是体格更健壮些的甘波鲁。

“三...不对，最多应该也就两分钟...”

“两分...？”

带着惊讶的表情，桐人看向窗外的夜空。谢塔也皱起眉头，小声说道。

“坐着负伤的米尼翁，只用两分钟就消失不见了...?”

就罗涅所知，米尼翁的飞行速度，和人类奔跑时差不多。在这高五百梅路的上空，不论往哪
里飞都不可能完全失去身影。虽然对手是暗黑术士，所以或许会使用隐身术。就算如此，桐
人和谢塔发现不了的东西，罗涅至今还不曾见过[fn:82]。

为了不会无力感击倒，罗涅走过地板，来到婴儿床附近，当然箱形的床上已经没有婴儿的身
影，但是奶嘴状的，熊状的，龙状的布偶还残留着。撕裂的感觉突然向胸口袭来。

移开眼睛，就在这时。

注意到飞龙的玩偶上似乎有什么东西掉了下来，罗涅伸出手。

那是卷成一团，用红色纽扣系住的羊皮纸，怎么看都不想孩子的玩具。

“那个...我在床上..找到了这个...”[fn:83]

这样说着拿出羊皮纸，伊修卡恩立刻用闪电一样的速度拿了过来。

用指尖很容易就切断了结实的纽带，伸展开来。伊修卡恩睁大了左眼，从喉咙里不断发出呻
吟——跌跌撞撞的做到了床上。

从手里拿过羊皮纸的谢塔，惊愕的神色一样在骑士的脸上蔓延开，紧紧咬着嘴唇，把它递给
桐人。

站在接过来的桐人的旁边，罗涅也被黑色的文字吓呆了。

【二月二十一日日落之前[fn:84]将人界代表剑士以暗杀暗黑界总司令未遂之名在打竞技场
公开处刑，把首级送到人界。如果没有成功，届时这个无辜孩子的首级就会被送回奥布迪西
亚城。】
** 33
“...怎么会....这样...”

不断喘息着，罗涅接连摇了好几次头。二十一日就是今天，距离处刑的日落，也只有十三四
个小时。

首先想到的是，伊修卡恩和谢塔就不会做出那样的事，那两个人就是这样的。

但也很快，想到把两人爱女的性命放到天平上，真的有比这个还重要的事吗，对于现在的二
人来说。

罗涅无意识地动起左手，然后就碰到了左腰。但是在那个位置并没有剑，和桐人一样放在了
房间里。

而且就算带着剑...如果万分之一的可能伊修卡恩对于绑架犯的威胁选择妥协，到时要和两
人战斗吗？

桐人和罗涅如果逃跑的话，莉泽塔也就死定了。

把那样纯洁可爱的小宝宝抛弃这种事情是绝对不可能做出来的。话虽如此，因为事关桐人被
处刑的问题，作为护卫也绝对不能容许这样的事情发生，绝对！

因为过去完全没有遇到多类似的纠葛，所以罗涅只能呆呆站在原地。虽然想要去看拿着羊皮
纸的桐人的脸，但是连头都不敢动。

“那个...阁下...”

和同事一起站在墙边的卫兵古德，发出了非常客气的声音，似乎是因为在意羊皮纸的内容吧。
伊修卡恩则无力地举起右手往门的方向指去。

“古德，甘波鲁到外面去，谁也不能进来。”

“是...”

两人做了一个暗黑界式的敬礼，就朝门的方向走去。但是中途，甘波鲁停下脚步，回过头。

“那个，我还有一件事要报告...”

四人的目光齐刷刷的看过去，卫兵不禁缩了一下本来就很短的脖子，继续说道。

“可能不算是很重要的事...在暗黑术士和妖怪从窗户出去之后不久就听到了奇怪的声音。”

“声音...是什么样的？”

对于谢塔的询问，甘波鲁几次想要说话但很快又闭上了嘴，反复几次之后说道。

“怎么说呢，像是石磨传动的声音，嘎吱嘎吱的。”

“石磨吗...”

对于这座城无比详细的伊修卡恩似乎也没有什么思路。甘波鲁则再次敬了个礼，就和古德一
起从房间中出去并且关上门。

房间里充满了令人苦闷的沉默，不久后桐人发声了。

“...别在意，伊修卡恩，谢塔，莉泽塔被拐走也是我的责任...”

“....你在说什么傻话，你什么责任都没有哦。”

此时心里恐怕已经坐立不安的伊修卡恩，否定了坐在床上弯下腰道歉的桐人。

“真正可恶的是，对于莉泽塔的警卫工作松懈了，又对那种佯攻完全上钩的我。但是啊...
或许算是借口，暗黑术士的米尼翁，应该是飞到这个高度的。在这里能飞的只有暗黑骑士的
龙骑兵。那是那些人是被禁止着陆在起降台之外的地方的，所以，对于从窗户入侵的贼人恐
怕也没有注意到...”

膝盖上的放着的双手加大了力道，发出咯吱咯吱的声音。向丈夫走过去的谢塔，把自己修长
的手放在上面。

“但是，果然，造成这个结果的，还是我。”

右手拿着恐吓信，桐人再次说道。

“罗涅的话，之前就注意到，人界的杀人事件可能是把我引到奥布迪西亚来的陷阱。但是我
认为，只用一天就来奥布迪西亚的话，什么阴谋都不可能赶上。但是，莉泽塔却被这么容易
的就抓走了...看来那帮家伙，在人界和暗黑界都有同伙，而且有比机龙还要快的练习手段。”

“机...龙？使用那个的话从圣托利亚移动到奥布迪西亚只要一天吗？”

对于谢塔的提问，桐人点点头。

“啊...那个之后会好好说明的，现在最要紧的是莉泽塔...”

桐人再次看了一眼羊皮纸，用低迷的声音继续说道。

“...这些家伙的目的恐怕是，让人界和暗黑界再次敌对。如果无视他们的话，一定会继续
制造威胁，之后我会尽全力夺回莉泽塔...不过,如果到时候没有找到的话，就把我...”

“别说了！！！”

处刑掉，打算说出这个词的桐人，别伊修卡恩尖锐的声音打断。

罗涅以前就被告知，桐人和亚丝娜，是被策划从Realworld 转移到Underworld的。

两个人是躺在Realworld一种名叫《STL》的神器一样的装置里，只有灵魂转移到了
Underworld 里。因此，既是地下世界的天命全损，两个人也不会死。灵魂会回到Realworld，
然后在那边醒来[fn:85]。

现在的桐人，大概在考虑这样的事吧。但是就算回到了Realworld，大概也不可能再次回到
Underworld了吧——对于现在的二人来说。因此，对于罗涅来说，这和桐人的死亡没有区别。
当然，这对于和桐人见过面，一起度过重要时光的所有人都一样。在人界的...不是在
Underworld的全部人来说，桐人都是不可替代的人。

像狂风一样席卷大脑的思考和情感根本无法用语言传达出来，罗涅朝桐人走进了一部，握住
了黑色衬衫的衣角。

注意到这个举动的谢塔，轻轻松了口气。似乎是为了让罗涅放心而点点头，用着被抑制的声
音说道。

“把莉泽塔抓走的暗黑术士和米尼翁，有没有可能是躲到了城里别的楼层？”

皱着眉头的伊修卡恩，低声说道。

“呜嗯...这个时间窗户已经全部锁上了，如果有人打破闯入，各层的卫兵应该都会注意到。
但是...如果城内有内应的话，或许会从内部打开窗户把。”

点了点头的谢塔，用麻利的语气说道。

“让所有卫兵，在城内仔细搜索吧。”

“我和罗涅也来帮忙可以吗？”

对于桐人的请求，伊修卡恩毫不迟疑的点点头。

“拜托了，为了救出莉泽塔你的力量必不可少。你拿着这个。”

打开桌面上的一个小抽屉，从里面取出一个银色的手势轻轻放下。待桐人单手接过后，用右
手大拇指指着自己头上的银环。

这个是暗黑界总司令的证明，那个则是这个的代理证明。看到那个的话就会想到我的名字，
基本上所有地方都能直接通过。

“明白了，谢了。”

把连着印有纹章的银版的锁链挂到桐人脖子上，伊修卡恩又往前大大的走进一步，紧紧握住
桐人的肩膀。

“——拜托了。”

说出这句简短的话之后，伊修卡恩就和谢塔先一步走出房间。门被打开，又被关上。在这期
间，四点钟的钟声就好像在特意等在这个时机一样悄悄地响起。
** 34(被吞)
** 35
“但是...我说。”

赤铜色的肌肤开始发青，伊修卡恩有些结巴的说道。

“能够解开五十层封印的，只有皇帝贝库塔吧...也就是说，莉泽塔的诱拐犯是...”

那个说出口之前，好像是因为恐惧，拳斗士咬紧牙关。

打破充满战栗的沉默的，是谢塔坚毅的话语。

“走吧，去五十层。”

很快，桐人也点点头。

“确实...去调查门吧，说不定能了解什么。”

伊修卡恩似乎很快也从恐惧中回复过来，点点头。

四个人再一次，毫不休息就快速爬到最上层，因为是第二次所以已经可以游刃有余了，罗涅
这次也能够做到不怎么喘气。

到四十九层时一度停止了脚步，仰望要继续往上爬的楼梯，城内似乎还没有收到热水供应，
或者因为其他理由，昏暗的楼梯上冷气慢慢地飘出来。在罗涅脚边环绕。

“...走吧”

伊修卡恩短暂地宣告后，就向着楼梯迈出步，三人跟在后头，

明明只有一层，却在感觉比从一层走到四十九层时还要长的楼梯上走着，接着看到了前方黑
漆漆的那种左右两开的门。虽然已经听说了，左右两开的门北大约有十赛以上巨大的锁链缠
住。而且缠的非常紧，几乎完全没有空隙。

慢慢走到大门前面的短小走廊，伊修卡恩用右手碰了一下灰色的锁链，一边说着“真冷”一
边缩了回来。但是又一次伸出手，这次仅仅地握住锁链，沉腰，伴随着气合开始拉动。但是
锁链只是发出轻微的金属声，动都没有动一下。

“...果然，封印没有解开啊。”

从锁链上移开的右手碰了碰黑色的门，接着是左手，甚至把右耳贴了上去。

“什么都听不到呢...——但是，莉泽塔如果还在这个城里的话，只有可能是这里了吧...”

退后几步的拳斗士，慢慢下沉身体，做出拳击的姿势。

紧握的右手，像是寄宿了赤红的火焰一样。冰冷的空气嗤嗤颤动，罗涅下意识地退后几步。

是打算用赤裸的拳头破坏封印吗...这样想着的时候，桐人站了出来。

丝毫没有被拳斗士那惊人的斗气震慑住的样子，桐人走近过去，把手搭在伊修卡恩左肩上。

“我来吧，伊修卡恩。”

“不...我来做吧。”

“你的拳头，还要为了与米尼翁和绑架犯战斗的时候使用。而且，这也是我擅长的事
情。”[fn:86]


无法反驳桐人的话语，伊修卡恩【呼——】地长叹一口气，解除了驾驶，向后走去。

“真是的，你还是一如既往地乱来，明白了...就交给你了。”

伊修卡恩一边苦笑着，一边退到妻子边上。

代替其站在锁链前面的桐人，张开的右手触碰到发出钝光[fn:87]的锁链，慎重地抚摸了着，
这个动作持续了数次，在锁的中央用食指点了几次。

“这里，虽然太浅了眼睛看不到，但是确实有伤痕，这是谢塔你弄的？”

“对,就像之前说的，如果是用黑百合之剑的话就可以砍断了。”

“是吧...这个伤，就让我来使用吧。”

点了点头，手从锁链上移开，向后退了三步后，桐人终于握住左腰的剑。

唰，看到伴随着清脆的声音拔出剑，伊修卡恩和谢塔不禁发出感叹。

神器《夜空之剑》的刀身不是金属，而是一种带有特殊质感的漆黑材料。和建造奥布迪西亚
城所用的黑曜石类似，但是没有看似湿润平滑的条理然人感觉更沉重的，是诺兰格鲁斯帝国
北边的伫立的巨大杉木类的树木的树枝。现在作为大教堂工厂长的赛多雷老师，当初花费了
整整一年的时间和六块磨刀石才把这把长剑磨出来。桐人用它打倒了不知道多少位整合骑士，
以及元老长丘德鲁金，最高祭司administrator，最终连暗黑界的皇帝贝库塔都斩杀掉了。
毫无疑问，拯救世界的传说之剑。

但是恐怕，虽然这把剑的优先度很高，但是还不足以斩断封印之锁。

毫无疑问，锁链被赋予和中央大教堂的外壁，四分中央大教堂的不朽之壁同样的不可破坏属
性。就算是拥有如神之力的亚丝娜，也只能移动大教堂的墙壁，破坏是做不到的。

能够切断锁链的，不是剑士的技艺，也不是剑的优先度。而是能够重新书写《世之理》的奇
迹之力——唯心意的力量莫属。

桐人又退后了三步，左手前伸，握着《夜空之剑》的右手弯曲到肩膀上方，前后张开的双脚
用力踩着地板，大大地吸了口气，开始蓄力。

摆出并不是传统流派架势的桐人的身体，被红色的光芒包围，从脚底隆起像是龙卷一样的气
流，罗涅把脸背过去，拼命踩在原地。

不久，红色的光就聚集在右手的剑上。漆黑的刀身散发着真红色。产生像寒风一样震动声，
音量慢慢地增加，不久就变成让人联想到飞龙嚎叫的金属质轰鸣声。空气开始哔哩哔哩地震
动，黑曜石的地板和墙壁也开始微微摇动。

“这...这真是胡来啊...”

伊修卡恩呻吟着。

“这...就是桐人的心意...”

谢塔也倾露出惊叹。

突然间，身穿简朴的黑裤子和黑上衣的桐人的身姿，在狂乱的光之风暴中摇曳，变化了——
罗涅注意到了这点。激烈飘扬的，是黑色皮革长外套的衣角，右胸和双肩的部位，闪着钢制
防具发出的钝光。

“噢噢呀！”

短暂的气合之后，桐人蹬了下地板。

右手的剑，满载着心意的力量放出直线的一击。轰鸣的声音打倒了最高点，左右两边的墙壁
出现了细细的龟裂。

距离锁的距离还有大约五梅路，很明显还在攻击范围外，但是就像剑本身增长了一样，像一
柄枪一样迸发出的真红色的光，从封印之锁中央的一点穿过。

声音消失了，光消失了，风消失了，桐人的身姿也复原了。

在寂静之中，封印的锁链从中间毫无声响地分成两半，垂落下来。沉重的大门，仿佛在颤抖
一般——就好像活了一样，一瞬间发出沉重的鸣响。

桐人瘫软地跪在地板上，罗涅赶紧跑了过去。

“前辈！”

在桐人的左臂下方用自己的手臂挽住，帮助他起来。很快，伊修卡恩和谢塔也跑过来帮忙。

“喂，你还好吧，桐人！”

对于伊修卡恩的询问，桐人举起左手回答道。

“啊，很快就能恢复...相比之下，快点把门...系统，不，世界之理很快就会察觉到异变，
把门修好吧。”

“恩”

点点头的谢塔走进大门，用两手推动着雕有不详雕刻的石门。隆隆，门一边震动着，一边向
里侧移动。

“...打开了。”

对于回过头的谢塔，桐人用嘶哑的声音指示道。

“你们两个赶快！绑架犯应该就在里面，或许已经注意到门被打开了...我也很快就赶过去。”
** 36
“噢...好。”

伊修卡恩点点头，巨大的石门被其右脚一踹就开了。那里面有道路继续向深处通行，充满了
和罗涅等人所处场所不一样的黑暗感，周围也缭绕着几乎冻结般的冷气。

但是莉泽塔的父母，毫无犹豫就沿着道路飞奔，几秒之后两人的背影就消失在了黑暗之中。
桐人一口气站了起来，看向罗涅。

“我们也走吧。”

按耐住对桐人的担心，罗涅点点头。

“...好的。”

虽然想在突入之前，应该先召集楼下搜素的士兵，但是就像桐人说的那样现在是分秒必争的
时刻。况且，对面是高等级的暗黑术士，对于法术耐性较低的卫兵不仅不能帮上忙还可能有
危险。

至少还有这个，从系在腰间的旅行袋里取出小瓶的灵药，拔开塞子交给桐人。虽然因为问道
酸苦的味道而皱起眉头，但是桐人还是把它喝完了。用稍微恢复了些血色的面容说了声“谢
谢。”就和罗涅一起穿过门进入到幽暗的通道里。

就好像，有一种穿过透明薄膜的感觉。暖水热气之类的功能似乎完全没有发挥作用，就连呼
吸都能化作白色冷气的温度让整个身体都瑟瑟发抖。但是接下来，微微听到的声音让罗涅忘
记了寒冷和恐惧。

那绝对不会错，是婴儿的哭声。

“......！”

与桐人视线交流后，两人跑了起来。

从通道的前方往左边弯曲了。然后在那里转弯，前方可以看到第二个门。哭泣的声音正是从
那个打开的门对面传来的。

不顾一切地冲进去，里面是巨大的空间。地板上铺着发黑的红色毛毯。在那两侧，有着被雕
成丑陋怪物的浮雕立柱。正面高出连个台阶的地方，在那中央放置着奢华的座椅。那毫无疑
问是皇帝贝库塔的玉座。

大厅的中央，伊修卡恩和谢塔站在一起，更往深处是张开了双翼的黑色怪物——米尼翁。

而且，在玉座的傍边，有一个像影子一样未知的身影。

带着黑色的遮帽和长袍，但是长袍的衣角和柚子像是烟雾一样模糊，无法捕捉到轮廓。虽然
很瘦弱但是各自很高，右手有一把闪着紫色毒光的短剑，而那个刀锋，此时正对准左手抱着
的婴儿。

婴儿的脸色很差，哭声也变得微弱。在这么寒冷的地方呆了两个多小时，天命应该减少了很
多。虽然现在当务之急是马上抢救，但是这种状况下根本无法迂回靠近。焦躁和愤怒的情绪
从谢塔和伊修卡恩的背影中传来。

穿着黑袍的诱拐犯，其视线从幽暗的遮帽内部传来，冲着桐人和罗涅——被发现了。接着，
像是那种人强迫鸟兽说话的语气[fn:88]，发出异样的声音。

“...原来如此，把封印之锁斩断的，是人界代表剑士殿下吗，您真是比传闻还要麻烦...”

从那个声音中，无论是人种还是年龄都不能判断，但是有一点，确实感觉出来了。

“你这家伙...是男人！也就是说，不是暗黑术士。”

对于伊修卡恩的叫喊，绑架犯漏出咻咻的奇妙笑声。

“人界的神圣术士是男人吧？也就是说，暗黑术士是男人也可以吧？”

“...不，那把毒剑，以前有见过...你这家伙，是暗杀公会手底下的人吧！”

“怎样都好吧...这把剑谁都可以使用吧？我说不定是你过去赶出的拳斗士...”

再次，仿佛嘲弄般笑着的绑架犯，发出不想人一样的冰冷冷的语气。

“闲话就到这里了，这个样子也只能放弃公开处刑了，但是代表剑士的脑袋我还是要的。全
权大使，现在马上用你擅长的手刀切掉代表剑士的脑袋，不然你的女儿就没命了。”

从黑袍中伸出的灰色右手，让短剑离莉泽塔又进了一步。

从伊修卡恩和谢塔的背影可以看出，两人像是快要被撕裂一样僵持着。

那个瞬间——

乒！伴随着尖锐的声音，毒剑的刀锋被弹开了。莉泽塔的全身，被白色的光球裹住。诱拐犯
一瞬间差点失手，但是很快又抱住球。

那不是莉泽塔自己做到的，而是罗涅的身边，玉座正对的桐人，其右手正在释放同样的光
芒。，心意的屏障正在抱住着婴儿。

“谢塔！伊修卡恩！”

用着痛苦的声音，桐人叫喊道。

“我坚持不了多久，把莉泽塔...”

“好勒！”

这样回应的伊修卡恩，全身像是燃烧起来一样发出火红的光。

与此同时，黑袍男子念出奇怪的语句。对此作出反应，米尼翁动了起来。

“浮咻咻！”

怪物的咆哮，被拳斗士吼叫掩盖。

“呜啦啦啦啦！”

伊修卡恩迅猛地突击而去，寄宿着火焰的拳头集中米尼翁的腹部。巨大的身体瞬间扭曲，从
腹部到四肢开始扭曲膨胀——

像是装满液体的布袋一样破裂，乌黑的血液大量四处飞散。对于含有毒素的血液，伊修卡恩
两臂交叉用全身挡住了。

在那之后，从伊修卡恩的背后蹿出一个身影。直接躲避了毒液的谢塔，用像一条灰色霞光的
速度冲向玉座。

“....嚯！”

伴随着无音的气合，左手刀一闪而过。

拿着紫色毒短剑的绑架犯右手，被干净利落地切掉在地板上。想要切掉抱着莉泽塔的左手，
谢塔挥动起右手。

——但是。

黑色的遮帽里，嘴还在动。带着不知是什么的小光。

吹针！

谢塔很快用左手停住了吹针，窈窕的身体有些倾斜。

趁机重新抱好被光球守护的莉泽塔，黑色长袍的男子像是滑动一样往玉座左边跑去。但是那
延伸的黑色墙壁前方，肯本没有能逃跑的地方。

不对...

脑海里一次弹出多个想法，但是化作行动之前，罗涅就拔出佩剑跑了上去。

另一边，翻开黑袍的绑架犯向墙壁冲了过去。在他胸前，硕大的宝石发出鲜红的光芒。

墙壁的一部分，开始发出同样的光。被切割出棱角的黑曜石墙壁，沉重的岩石像是在相互摩
擦似得...一边发出石磨一样的声音一边抬了起来。

对着本来不该出现的窗户，诱拐犯纵身一跃——

“呀啊啊啊！”

身体由下而上挤出全部气势，罗涅蹬了下地板。

和绑架犯的距离有十梅路以上。

但是，够到，能够到！

挥出右手的剑。从极其严密地决定的位置，剑和手臂一体化稳定的瞬间，刀身放出炫目的蓝
光。

罗涅的身体，就像被看不见的手加速了，在空中划过一道青白色的轨迹，十米的间隔一瞬间
就补上了。

艾因格朗特流高速突进技——《音速击》

在神圣语里好像是《音速飞跃》的意思，有桐人直传的秘笈剑术，将绑架犯的左腕从根部斩
飞。

之后，桐人的心意屏障消失了，莉泽塔也被抛到了空中。

失去双手的黑袍男子，就算大量出血也没有停下脚步，从窗户跳跃了出去。

如果能更进一步使用剑技的话，就有可能将绑架犯斩获。但是罗涅选择停下脚步接住莉泽塔。

绑架犯则一头冲出窗户，仿佛消失在清晨的光芒中，看不到了身影。同时，罗涅左手紧紧抓
住莉泽塔的身体，抱在怀里，蹲了下来，把剑放到地上，为了给带着微弱哭声的婴儿提供温
暖而用双臂裹住。

“...莉泽塔酱，很害怕吧？已经没事了哟...已经没事了...”

说许是因为那贴着脸颊的拼命安慰，哭声渐渐平息了，小小的手触碰到罗涅的脸颊。从左边，
传来窗户再次被关上的声音。

在什么人触碰到的后背前，罗涅一直在紧紧跑着婴儿。
** 37
尽管花费了一百个卫兵半天的时间，但是还是没有找到诱拐犯的尸体。

从五百梅路的高度，失去双手的状态下飞降下来，应该不可能还活着。并且，伊修卡恩，谢
塔，还有桐人，对这起事件的结束并不保持乐观态度。

城内的事物处理完已经是下午四点了，在窗户已经修好的孩子的房间里，四人再次聚到一起。

在谢塔的怀里，莉泽塔像是完全已经忘记了之前的事件一样，津津有味地喝着牛奶。城内的
医生，高位术士也对谢塔是否有中毒或是暗黑术反反复复地详细检查了，所幸什么都没有发
现。

但是另一方面，关于绑架犯还什么都没了解到。其中最大的谜团，就是除了皇帝本应谁都不
能打开的五十层的窗户，到底是用什么方式打开的还不知道。

“...说不定并不是完全没有关系...”

喝着人界没有的，味道有点像苹果的茶，罗涅说道。

“那个男人在开窗的时候，胸前巨大的宝石发出了红色的光。”

“红色的宝石？”

桐人嘀咕道，谢塔也同时歪起头，两人当然什么都没有想到。

但是把切成大块的木果蛋糕塞进嘴里的伊修卡恩，却皱起眉头说道。

“发出红光的宝石吗...本身是什么颜色还记得吗，罗涅小姑娘？”

被拳斗士团长叫到名字还是第一次，这么想着罗涅回答。

“怎么说呢，并不是那么明亮....像是夕阳啊，血啊那样的暗红色”

“血红色的...不，怎么会...”

“喂，我说伊修卡恩，以【怎么会】结尾可是犯规的。”

桐人插嘴道。

“什么犯规啊...”

带着诧异的表情，伊修卡恩接着说明道。

“异界战争之前皇帝贝库塔降临的时候，感觉王冠上好像镶嵌着那样的石头。因为全身上下
只有那一块宝石，所以还有些印象。”

“贝库塔王冠的...？那应该不可能吧，那个男人在距这里有几千千路的南边岩山，与骑士
长贝鲁库利对决而死了一次，之后复活的时候，已经没有那样的王冠了。也就是说，最初的
装备应该都在王冠那里消失了。”[fn:89]

“但是，这也不是你亲眼所见吧？”

对于伊修卡恩的点明，桐人说着【也对】点点头。

当时的桐人，还处于心灵封闭的状态。当时在骑士长贝鲁库利和暗黑皇帝贝库塔对打现场的
也只有整合骑士爱丽丝。但是她现在已经不再underworld了。

贝尔库利的遗体被爱丽丝用飞龙搬运到了《尽头祭坛》，再由附近的桐人带回人界。现在已
在中央大教堂广阔的花园里树立的墓碑下沉眠。

“...确实，贝尔库利和贝库塔决斗的地方还没有调查过。现在这样，也不是很难做到...”

带着严肃的表情说道，桐人看向窗外。

“...但是，能够开闭五十层窗户的宝石之力，就像伊修卡恩所说是贝库塔的所有物也是可
能的，确实如此。但是，有是谁把它回收的呢？...那个男人又到底是什么人？这些问题还
没有解决...。——说起来，在玉座那时所说的暗杀公会，到底是个什么样的组织？”

回头看向提问的桐人，伊修卡恩一口气把茶喝了个精光，渗透着厌恶感回答道。

“就像说的那样，是以暗杀为职业的一帮人，都是用毒的...作为暗黑界十侯的那家伙，头
目弗·泽卷入暗黑将军沙司塔的叛乱中死了，因此组织很快就弱化了，现在也没有加入了五
族议会。我几乎都忘了还有这么个存在...那个黑色长袍混蛋作为暗杀公会的一员，那家伙
就算是使用米尼翁也散发着一股明显的臭味。”

“与行动不明的暗黑术士合作，照这儿方向调查会比价好。”

多余谢塔的言论，伊修卡恩点点头。

“啊，我打算立刻去和骑士团还有商会的人谈，这也是为了防止奥布迪希亚引起骚动。”

对于做出如此宣言的伊修卡恩，桐人探出身子。

“对于这件事，是不是应该向暗黑术士公会寻求帮助呢？听到迪·阿·艾路的所作所为，暗黑
术士们被冷落也是没有办法的事...就算只有这一次，让她们来作为城市的护卫也好。只有
卫兵的话，对于术式的防卫还是会令人不安。”

对于桐人的言论，罗涅有些难以理解，但是不想得到进一步的说明，只是拼命思考着。

“你这家伙还是一如既往，净说一些让人头疼的事情。”

苦笑着，伊修卡恩耸耸肩回答道。

“不过确实如此。奥布迪希亚城内的人族同胞们如果相互敌视的话，和亚人种之间的问题也
就不可能解决了...桐人，你啊，是不是什么事候都能到这边来？”

这次轮到伊修卡恩凑过去，桐人则直起身子。

“当，当然我会尽我所能提供最大帮助...不过，今天晚上，还是要回人界一趟。那边的问
题，还没有解决...”

“啊，恩，对了...帮我把莉泽塔夺回来还没来得及感谢，好吃的东西要多少有多少...”

像小孩子一样撅起嘴的桐人看向伊修卡恩，像是在怀念什么事情似得，露出惋惜的笑容。

“什，什么啊，那张脸？”

“不，没什么...伊修卡恩的口吻，和我一个老朋友有些相似。哎呀，说起来，下个月预定
有个会议吧？那个时候，会有不少人要过来哦。”

“恩，做好来吃比昨天的美味还要好吃的东西的觉悟吧。...话说回来，这是真实受你照顾
了，这份恩情，毕生难忘。”

站起来的伊修卡恩伸出右手，桐人也挺起腰紧紧握住。看到这样的二人，谢塔和罗涅发出嘻
嘻的笑声。

在被分配的房间里又小睡了几小时，简单吃过饭的桐人和罗涅，在晚上八点从奥布迪希亚出
发了。

这次既没有必要涂药膏，也没有必要靠心意飞行。谢塔骑着爱龙宵呼把二人送到了隐藏机龙
的地方。

看到钢铁的飞龙时，连谢塔都表现出吃惊的样子，但是马上就明白了机龙所包含的可能性。
留下一句【如果这个可以量产的话，我很期待人界和暗黑界自由往来的日子】就从返回了作
为赴任地和自己的家的黑曜石之城。桐人和罗涅也乘着机龙飞翔西边的天空。

飞行非常稳定，呼地叹了口气后，前座的桐人说道。

“说起来，从绑架犯手里夺回莉泽塔使用的《音速击》那一下很漂亮呢，罗涅。什么时候，
也能掌握那样的事了？”

“诶，诶...硬要说的话，大概是在梦里。”

缩了缩头，罗涅触碰了一下放在椅子和墙壁缝隙之间的爱剑的白色剑锷。

“...那个时候，感觉是剑借给了我力量，换做平时，绝对不可能跳那么远。”

“这样啊...真是不错的剑。”

“是”

点点头，罗涅把身体托付给靠背。

从静静飞行的机龙透过防风窗向外看，望向暗黑界的夜空。比人界的星星要少，正中间是三
日月闪耀着柔和的白光。

人界和暗黑界差得很远，但是不论哪的人都看着同样的月亮...

这样想的瞬间，罗涅想起在奥布迪希亚下城，看到旅店招牌的时候，还有听到钟声旋律时那
种不可思议的感觉。这次罗涅抓住了那儿感觉的来源。

“那，那个...前辈？”

“嗯？怎么了？”

“嗯...人界和暗黑界，为什么使用着同样的语言和文字呢？明明在Underworld生成开始，
两个世界就没有交流过，就算使用不同的语言也没什么好奇怪的...”

对于将疑问化作的词语，桐人先是沉默了一会然后回答道。

“确实...创造了这个世界的RealWorld的人的目的是为了让人界和暗黑界开战。相比之下，
两个世界使用不同的语言会更方便，不能沟通的话，也就不可能和平交涉...但是他门，或
许有现实世界人以外的什么东西，有意让语言共同化。这个理由，我不知道。但是，或许是
为了制造一个可以跨越敌意和斗争的世界，也许...”

对于桐人的话，罗涅并不明白，但是也不想得到进一步说明，只是拼命思考着。

夜空中浮现出的月亮，和这片大地一样是个巨大的球。[fn:90]这是桐人说的。所以在接受
索鲁斯的光时，才会时满时缺。

如果月球上也住着人的话，他们也可以把罗涅生活的这片大地，视为是发着白光的三日月吧。
月球的居民们，也说着同样的语言吧？和这个世界的居民一样，犯过错，流过血，尽管如此，
也带着希望世界更好的愿望活下去吗？

夜空中悄然浮现的三日月，就像是哺育了众多生命的摇篮。罗涅慢慢向月亮伸出手。

那手之后又回到爱剑的剑柄，罗涅说道。

“那个，前辈。”

“..怎么了？”

“我，想好剑的名字了。月...叫做《月影之剑》”

“这样啊。恩，是个不错的名字。它绝对会保护好罗涅的。”

对于桐人的话，微笑着说了声【是！】，罗涅点点头，用指尖拭去渗出的泪水。

好想快一点看到缇卓。

对于在对已故的优吉欧上级剑士的思慕和整合骑士雷利的求婚中动摇的亲友，让她知道这次
旅途中的事，还有许多想说的话。

似乎是感觉到了罗涅的想法，桐人让机龙的速度提高了一些。

在淡淡的月光下，钢铁的龙向西，再向西一直飞行下去。

（完）
** 后记
感谢阅读SAO外传7《月之摇篮》。

虽然基本上是结束了，但是这个系列还会继续下去。敌人的真面目还是个谜，罗涅和缇卓的
恋情也没有解决...续篇什么时候开始还不清楚，只要悠闲的等待就好了。

并且根据以往的例子这个页面这几天就会删除。我想年内就会消失，还请谅解[fn:91]。
** 译者后记
大家好，我是义乐。至于名字前面那个“帝皇”是自己年轻时犯下的错误...言归正传，说
实话，能够翻译这篇文章个人真的非常荣幸，一方面这是本篇自08（大概）年完（挖）结
（坑）之后第一次有了新的剧情，其次，能够接手rkl之前的部分也是不胜荣幸。所以这两
份荣幸加起来本应是更多的荣幸，可是为什么，为什么会这样？（死）

首先给大家道个歉，本来预计是在文库发售前完工的，但是因为公事私事＋怠惰导致现在才
翻完。而且就质量而言在天角负责的幽远的应该算是高档餐，rkl的翻译应该算是快餐（也
确实很快），而本人的话应该只能算是路边摊的（而且还很慢），所以某些地方如果造成阅
读不便还请谅解。

文库版如今已经发售了，不出意外我下周也会买到。就目前所知已经有一个小团体愿意接手
这次翻译，虽然我很荣幸能被邀请，但是因为个人学业和时差原因很难做到与别人协作，真
是非常道歉。以后很长一段时间里我应该都会以个人名义进行翻译，不过像这样的长文赢啊
不会有了，现在对于rkl的敬佩真是更上一层楼。之后如果有幸大家应该还能在sao的短篇里
看到我。最后感谢大家阅读本文。

以下是对于sao的个人感想

之前rkl在翻译完18时提出过一个问题，那就是当桐人从灵魂受损到修补之后，还是不是同
一个人。弥补桐人缺失部分的，是亚丝娜，莉法，还有诗浓对桐人的印象，但是这个印象本
身是否又是真实的桐人？我个人对这点持保守态度，毕竟今天的我们也与昨天的自己会有不
同，什么才是真正的自己并没有一个确切的答案。但是，有一点可以确定，在本篇中的桐人，
与各位在18卷末尾认识的桐人，将不再会是一个人。虽然不知道川原是有意还是无意，可以
感觉出桐人正处在一种舍去过去的自己，将自己完全变成属于UW的人。有人吐槽过在本文中，
桐人的能力有些弱化，个人认为这是桐人有意偏向让UW人自己解决问题。不论是使用冰魔法，
还是基于莉泽塔护盾，对于我们所知的桐人来说，本应有更简单的解决方式。虽然当初草草
阅读时并没有什么感觉，但是到了翻译品味的时候，后半段有些让人不快。其中最不爽的应
该是桐人犹豫遵循威胁的时候，感觉他完全没有考虑过如果自己死了，亚丝娜怎么办。当然
文中我也提到了，没人能确定这个加速倍率下能否正常脱出。个人看来，这已经表明在桐人
心中，天平已经向着UW倾斜，哪怕另一端有他最爱的人们。这让我不由得想起绝剑说的，桐
人某种意义上也是活在虚拟世界的人。或许这也可以解释为什么18卷里，桐人的摇光复制体
没有崩坏，或许他本人早已意识到自己有两个不同的认知。而最初，身边的人，现实生活和
并不完美的VR世界让RW的人格占据主导，而当一些都消失，取代而之的是可以完全替代的另
一个世界，VR的人格开始苏醒。而最终当亚丝娜这一最后的枷锁失去时，他便不再会是他，
而是一个一切以UW为首的人。这点或许与现在潜伏于网络的茅场复制体差不多，但是我想唯
一的不同是，茅场从来就没有对于现实世界有所留念，所以他没有变。就川原的后记而言，
接下来应该还会写一些UW的故事，但是从18的结尾而言，很难说有一天，星王不会剑指真实
世界。所以，就我个人而言，我不会对这之后UW里的桐人抱有多少好感，当然这也是本人的
胡乱猜测。接下来就让我们一起期待后续的故事。
* Footnotes

[fn:91]（义乐；没关系，已经拷下来了。）
[fn:90]（义乐：这里算是吃书了，原本UW的设定是个猪鼻子形状。不论怎么想设计成球体
和宇宙都没有意义，所以这里就把锅甩给cardinal吧...）

[fn:89]（义乐：这里应该是桐人判断失误了，加百列并非复活而是换了账号，此时贝库塔
的账号因为死亡需要等待重置，至于装备是否残留在UW还是未知。）
[fn:88]（义乐：那是什么语气...） 

[fn:87]（义乐：就是金属那种看起来就很结实的感觉）
[fn:86]（义乐：你自己也知道自己擅长搞事了吗...） 

[fn:85]（义乐：然而谁都不知道在一万倍加速的情况下是不是能正常登出，最坏的情况可
能是在虚无之中度过两百年。）
[fn:84]（义乐：现在时间是二十一日凌晨） 

[fn:83]（义乐：之前发现了PoH，然后注意到佯攻，现在有找到关键物。小姑娘洞察力max）
[fn:82]（义乐：夏洛特自豪的挺起胸膛。） 

[fn:81]（义乐：智商捉急，话说你这样当总司令官真的没问题吗... 果然内政全部要靠老
婆吗...）
[fn:80]（义乐：罗涅第三次智商爆发...） 

[fn:79]（义乐：罗涅就算了，你不是一直剑在人在吗？） 
[fn:78]（义乐：就是13卷大教堂外围那个） 

[fn:77]（义乐：坐了机龙，吃了奇怪的奥布迪西亚煮，睡了一间房，“偷袭”了主城，参
观了一天...少女你还想要什么事...不过没关系这次你主场一定满足你。）
[fn:76]（义乐：黒百合の剣だったら一振りで切れたけど，我不知道这里到底是哪个会
断...）

[fn:75]（义乐：这里川原又写成一年零几个月，我决定直接无视。） 
[fn:74]（义乐：天底下没有会翻窗户的文官！） 

[fn:73]（义乐：这果实长得真是够邪恶的...） 
[fn:72]（义乐：原文是いでとばかりに椅子を二脚運ばせると、もとからあった二脚と一
緒に窓際に並べさせた。其实也就是，拖起椅子，放到窗边。这句直译起来真是各种变扭。）

[fn:71]（义乐：左手右手一个慢动作...）
[fn:70]（义乐：你像爱丽丝那样弄个眼罩不好吗？你这样不怕吓坏女儿吗...）

[fn:69]（义乐：前方高能！） 
[fn:68]（义乐：我真的很想在这里打成“伊泽塔”，不过长打后样子估计也差不多了） 

[fn:67]（义乐：你不要故意岔开话题啊！喂！） 
[fn:66]（义乐：受读者要求改回英文方便阅读。）

[fn:65]（义乐：话说遮着脸呢，哪里来的视线...） 
[fn:64]（义乐：罗涅这一路作为吐糟役也是辛苦了。）

[fn:63]（义乐：这个词感觉怎么翻译都不到位，具体就是东方武术中所谓的气力合一，大
家自行体会一下。）
[fn:62]（义乐：这里桐人本来想说checkout，后改成汉字） 

[fn:61]（义乐：你还真是准时...） 
[fn:60]（义乐：上节这里是我翻错了） 

[fn:59]（义乐：虽然我知道川原应该没那个意思，但是话里感觉带刺还是让人很不爽的。）
[fn:58]（义乐：然而在那之上还有更恐怖的大人的世界...） 

[fn:57]（义乐：你忘了妻子...） 
[fn:56]（义乐：少女你这样会中沉睡魔法的。） 

[fn:55]（义乐：少年的的思想很危险。） 
[fn:54]（义乐：我已经不知道怎么吐槽了...ロニエは力いっぱいベッドのほうへと押しやっ
た。 附上原句以表清白。）

[fn:53]（义乐：桐人在你心中就这么弱吗..少女你果然是有别的想法...话说这段槽点太多
了，这满满的套路感...）
[fn:52]（义乐：所以你就不会好好走门吗，就算被老板娘发现说是出去吃个夜宵什么不就
好了，你这样翻出去被发现了不是更可疑...果然是修剑士时逃舍管逃习惯了...）

[fn:51]（义乐：认识你的都知道你是吃货好嘛...） 
[fn:50]（义乐：完了，已经中毒了...） 

[fn:49]（义乐：传说中的厨具和百年老汤...）
[fn:48]（义乐：毕竟是艾恩葛朗特第一吃货。） 

[fn:47]（义乐：看来是时候请你尝尝四川的酸辣汤了。） 
[fn:46]（义乐：所以并没有手套，传说中的川原式比喻句。）

[fn:45]（义乐：星王的尊严呢...）
[fn:44]（义乐：我就知道...为什么感觉这一幕似曾相识...） 

[fn:43]（义乐：我就知道...而且你真的带钱了吗？） 
[fn:42]（义乐：吃货的烦恼。） 

[fn:41]（义乐：所以你为了吃又干了什么...） 
[fn:40]（义乐：叫欧尼酱会比较好。） 

[fn:39]（义乐：具体应该和那种带帽子的衣服差不多） 
[fn:38]（义乐：我也明白了，等我去给亚丝娜打小报告）

[fn:37]（义乐：你又开始犯坏...） 
[fn:36]（义乐：果然大家都发现了...）

[fn:35]（义乐：你们该不会没有安全带吧...）
[fn:34]（义乐：所谓风素飞行术就是先生成风素然后用心意固定住加以操控，原因当然是
比直接用心意要节省精力。）

[fn:33]（义乐：这里我大概是明白了，也就是整个大浴池是在长40，宽25，深1的立方体上
铺有宽2，高1，总长63 的多条道路。学建筑的可以补充一下要怎么设计。）
[fn:32]（义乐：这里再科普一下“暖帘”古时候用来保证室内的热气不容易票到外面，现
在在日本只是用来当做一种文化符号。）

[fn:31]（义乐：ゆ字在日文里是汉字“汤”的读音，就是热水的意思，传统的大浴池外都
会有。至于把浴场一分为二的原因当然是为了防止晚上跪“夜空之剑”不要问我怎么知道的）
[fn:30]（义乐：一年半强行四合五入变两年...） 

[fn:29]（义乐：所以说，你们两个秀恩爱能不能顾忌一下周围人的感受啊）
[fn:28]（义乐：这里我不得不说，Good Job!） 

[fn:27] 
#+begin_quote
神奇，上面开头不是说没有继续往下写么，为什么在上面那个百度贴吧的链接还能找得到
14-37的内容？网友还是太给力了。
#+end_quote
[fn:26]【rkl：貌似这个封印，是潜入拉斯的一个间谍搞出来的，外部代码为871（Yanai）。
标出罗马音是因为Yanai就是这位间谍的姓氏（参见终章）。】

[fn:25]【rkl：卧槽，连过剩光都没，这心意技何等可怕……】 
[fn:24]【rkl：用两个字概括，就是外挂。】 

[fn:23]【rkl：抱着学妹飞啊有没有……虽然第八章已经抱着亚丝娜飞过了……】 
[fn:22]【rkl：为什么我有一股莱因哈特皇帝的既视感？】 

[fn:21]【rkl：我又该说什么才好……】 
[fn:20]【rkl：茅场的怒火在海龟里熊熊燃烧……我相信看到这句话的所有人都会有把这小
子的脑煮了的想法……】

[fn:19]【rkl：怎么光UW里就有这么多妹子了！连未亡人都不放过！】 
[fn:18]【rkl：虽然这么说很不负责任，但谁叫机油要和桐人抢妹子（爱丽丝）……顺带一
提，No.49绝对是个好人……】

[fn:17]【rkl：我这里故意没有翻的非常细致，原因见下。】 
[fn:16]【rkl：学妹你想什么呢，就算造出了复座机龙，陪桐人上天的也不会是你吧……】

[fn:15]【rkl：学妹啊……要不要这么苦逼……】 
[fn:14]【rkl：继续注释，第80层是桐人和整合骑士爱丽丝第一次对战的地方……也是爱丽
丝的妹妹将自己冷冻起来的地方。】

[fn:13]【rkl：桐人你怎么成了一个吃货啊！】 
[fn:12]【rkl：如果我的记忆无误，第一代图书管理员为Cardinal。】 

[fn:11]【rkl：作为被Administrator冻结了天命而成为不老存在的整合骑士一旦有了孩子，
那孩子势必将会早于父母而离世……虽然和这里没多大关系。】
[fn:10](由于这段附注内容过长以至于可能会影响观感，故塞进了detials里面供查看。如
果是侧边样式可以尝试双击展开侧边栏，双击收回)
#+begin_export html
<details>
<summary>译者(rkl)的“长评”</summary>
#+end_export
#+begin_quote
【rkl：援引当年和冰爷打麻将时冰爷喜欢说的一句话——这是一个悲伤的故事……  如果
联系到Alicization篇序章（最后一节）的话，倒是有另外两句话可以评价：一见桐人误终
身，解铃还须系铃人。说到底，学妹在SAO全篇桐人的后宫里面（这里计算了亚丝娜、幸、
直叶、诗乃、莉兹、西莉卡、爱丽丝、学姐、学妹以及第二整合骑士）可以算是最悲催的一
个。被学长迷住后结果为了给同学出头而被贵族侵犯（目测文库本会改掉这部分剧情，可能
是改成未遂？），等到被爱丽丝劝导后，亚丝娜又从现实世界杀过来了……如果真的在（还
活着的）妹子们里排位置的话，学妹搞不好只能陪锻造师和驯龙使一起举牌子……不过从序
章的内容来看，最后让学妹解开这个心结的大概还是桐人吧……虽然某个不科学的可能性也
存在就是……】
#+end_quote
【rkl：这里是一些关于Under World部分设定方面的个人意见。
1) 贵族的继承权。从本节我们可以看出，贵族家庭的继承采取的是长子（不论男女）继承
   的方式（推测是通过禁忌目录或帝国基本法规定），这种继承方式在现实的王室中并不
   常见——我只知道瑞典目前的王储是女性（有同父同母的男性兄弟）。虽然如今荷兰
   （Beatrix, Koningin der Nederlanden）、英国（Elizabeth II）、丹麦（Margrethe
   II）的国王均为女性，但均是在没有同父同母的兄弟时才由她们继承王位。围绕女性继
   承权的问题从古至今曾引发过多起战争，这里不再一一赘述。
2) 旧时代贵族的特权。关于领地民和第五章提到的高等贵族的赏罚权，个人猜测川原应是
   参考了中世纪欧洲贵族所拥有的初夜权（即有权享有领地内的女性第一次性交的权利）
   加以修改而成（虽然web版第五章的内容在文库本中可能有部分改动，但赏罚权的基本设
   定恐怕不会变化）。而平民不得拥有姓氏这点，大概是参考了中世纪日本平民不得拥有
   姓氏这一历史（直至明治维新后政府颁布苗字必称令，日本的广大平民才有了姓氏）。
   另外，将Under World的人界设定为西欧风格，某种意义上体现了拉斯的工作人员们（或
   者说是川原自己）内心中『脱亚入欧』这一想法（最早出自福泽谕吉，即一万日元上的
   那位）吧（虽然这可能是过度解读）。
3) 科学和神圣术。（这一条算我蛋疼）Under World神圣术的基本因子共有十种，但无法就
   此认为Under World内的元素和现实世界的一百余种元素有相同或不同之处。因此，我们
   也无法得出Under World人的遗传物质为何种大分子结构，其遗传信息的传递又是如何进
   行的相关信息——甚至我们无法确定，真实世界的人类和Under World内的人（不论人界
   还是暗黑界）是否可以产生后代（主要是针对桐人和亚丝娜在Under World内度过两百年
   提出的疑问，虽然有一个都合主义的解释）。至于物理方面，我认为Under World在宏观
   低速尺度上，大体遵循类似现实世界牛顿运动定律的物理模型（但部分参数可能有所差
   异）。】
#+begin_export html
</details>
#+end_export

[fn:9]【rkl：原文里川原手滑了，写成了五等爵士……应为笔误。】
[fn:8]【rkl：行了，我不说啥了，桐人晚上回家赶紧跪CPU请求老婆原谅吧。啥？你说UW没
CPU？这种事情我管不着啊……】

[fn:7]【rkl：请允许我在此解说并吐槽……上文提到的蓝发小孩就是法娜提
欧·Synthesis·Two和贝尔库利·Synthesis·One（已于Alicization篇第八章战死）的儿子。
不过根据设定，整合骑士间生下的子女，寿命比整合骑士要短。其实这两位整合骑士对彼此
来讲都是备胎……贝尔库利的真爱是最高祭司Administrator，而法娜提欧么……看下文。】
[fn:6]【rkl：这不就是心意飞行么？Silver Crow泪流满面……】

[fn:5]【rkl：你们夫妻俩干脆把UW拆了算了……】 
[fn:4]【rkl：虽然说是升降盘，其实就是类似我们现实生活中的电梯……第七章里有个妹
子天职就是操纵这个电梯。】

[fn:3]【rkl：桐人你蛋不蛋碎。另外，这里桐人的着装就是文库本1-2卷封面上的黑大衣。】
[fn:2]【rkl：在此解释一下(因为第八章还没有翻译)，与桐人新建帐号进入Under World不
同，亚丝娜进入Under World时使用了拉斯提供的超级帐号01《生命之神丝提西亚》(固有能
力：无限制地形操作)。顺带一提，超级帐号02《太阳神索尔斯》(固有能力：无限制歼灭)
和超级帐号03《地神泰拉里亚》(固有能力：无限制自动回复)分别由诗乃和直叶使用。】

[fn:1]【rkl：东门之大战即本篇第四部第八章的内容。】
