#+title: 败犬女主太多了！ 第八卷
#+setupfile: ./setup.setup
* 第八卷

** 序

    台版 转自 轻之国度

    轻之国度×天使动漫录入组

    图源：公子夜殇

    扫图：linpop

    录入：浮波柚叶

    修图：凪のあすから

    放学后的石蕗高中图书室。

    我坐在还书柜台后方，脸从手边的书本前抬起，伸了个大大的懒腰。

    五月下旬，段考也结束了，图书室内冷冷清清。

    「今天没有人来耶。」

    「那、那样比较好吧，用不着说话。」

    在我身旁头也不抬地一边看书一边回答的，是文艺社副社长小鞠知花。

    我们今天来帮忙图书委员，两个人一起照看柜台。

    ——新文艺社诞生后过了一个月。

    假废社期间已过，社团活动重新开始。这段日子出乎意料地平稳。

    不如说假废社那段期间，我家被当作临时社办，是一段地狱般的日子。

    要是觉得我讲得太夸张，麻烦设想一下，高中男生书架后方的秘藏书籍被女生社员传阅时的心情。

    不过，那种耻辱的日子也结束了。一切都过去了——

    我怀着悠然自得的心情，翻阅鸟类图鉴。

    「小鞠，你知道吗？隼其实是鹦鹉的同伴喔。」

    「你、你的脑袋变成鹦鹉了吗？」

    小鞠终于抬起脸，却劈头就这么说。

    我无可奈何地耸了耸肩，将图鉴推向小鞠。

    「是真的喔，书上写了最新的DNA分析结果。」

    「呜呃……是真的。」

    没错，是真的。麻烦你再多相信我一点。

    小鞠低头盯着图鉴瞧，小声嘀咕说：

    「你、你对鸟类有兴趣喔？」

    「是啊，我打算像个年轻人，开始尝试户外活动的嗜好。」

    「为、为什么挑上鸟？」

    「赏鸟用不着真的看见，光听鸟鸣就能享受了。到了田中老师那种境地，好像只要觉得那附近似乎有鸟就行了，连实物都不需要。」

    「那、那种，不是年轻人的嗜好吧。」

    咦？不是吗？鸟可是在户外喔。

    「我们学校不是也有赏鸟会吗？是年轻人的嗜好啦。」

    「那、那个社团，因为观赏鸟之外的东西，正在无期限的假废社喔。」

    从某种角度来看，也很有年轻人的风格。

    小鞠把图鉴推回我这边，侧眼往上瞥向我。

    「话、话说回来，最近那个女生有来吗？那、那个新生。」

    嗯？是说白玉学妹吗？

    「几乎每天都有来吧，每次都不知不觉地出现在社办。」

    「呜呃！？每、每天？」

    「？白玉学妹每天都在社办啊。你应该也知道吧？」

    「……去、去死。」

    我为何挨骂了？

    回想起来，假废社期间结束后，她曾经突然来到我家，在玄关门口被佳树随便找了些理由赶走了。那两个人难道不能处得更融洽一点吗……

    结婚典礼会场的骚动落幕，白玉学妹已经完全融入了文艺社。

    八奈见渐渐被她用点心驯服，烧盐则是老样子。

    我之前很担心的小鞠，现在状况好的时候，与白玉学妹的对话也已经延长到两个单字了。

    至于白玉学妹本人，我不时看见她在走廊上与田中老师交谈。

    看在毫不知情的旁人眼中，只是感情深厚的老师与学生。

    谁也不会发现，她其实是想从亲姊姊手中夺走姊夫的狐狸精——

    在这时，一本书放到我所在的柜台上。原来有客人啊。

    我把书拿到手中一看，标题是《开启细腻的中药生活》。

    借书证的名字是——马剃天爱星。

    「那个，我想借这本书。」

    「啊，好的，我知道了。」

    学生会副会长。注册商标是盘在后脑勺的发型。

    如外观所示，她是个认真的学生，但个性大概有点那个。

    在我办理借书手续的过程中，天爱星同学心神不宁地扫视着周遭。

    「那个，已经办好了。」

    「嗯？啊，不好意思。」

    天爱星同学接过书，但是似乎不打算离开。

    「你还想找其他书吗？」

    「呃，这个嘛，今天我有话想和温水同学说。」

    「喔。」

    天爱星同学的视线短暂瞥向僵在一旁的小鞠，轻声清了清嗓子。

    「温、温水同学！我来找你，是因为我对你有个请求！」

    「喔。」

    「…………」

    为何说到这里就沉默了。

    小鞠在柜台底下用指头戳我，我被迫开口：

    「那个……到底是什么请求？」

    「啊，是的！那个，我想提出的请求，是那个，简单来说我希望温水同学……不对，所以说，啊啊，真是的！」

    天爱星同学的身子向前倾，双手用力拍在柜台上。

    「简单来说，我——想要你！」

    ……突然是在讲什么。

    对着气喘吁吁的天爱星同学，我平静地告诉她：

    「这个嘛，天爱星同学，我现在还在图书室轮班，可以麻烦你等到结束吗？」

    「……啊，好的。那我就在这里等。还有，请不要用名字称呼我。」

    天爱星同学对我低头行礼后，坐到柜台附近的座位上。

    看着开始读起书的她，我暗自叹息。

    ……看来又有麻烦事要开始了。

    还有小鞠，别在柜台底下踢我。

** ～第一败～绝无不良居心

    这阵子白昼显然愈来愈长。

    夕阳的光芒投入社办，柔和地照亮了天爱星同学。坐在椅子上的她正被文艺社的女孩们团团围住。

    「来，马剃学姊，请喝茶。」

    「啊，谢谢。」

    面露笑容放下冒着水气的茶杯的，是一年级生白玉璃子。

    她面露亲切的完美笑容，监视般站在天爱星同学的背后。

    八奈见对显得有些坐立不安的天爱星同学递出饼干盒。

    「马剃同学，要吃这个吗？」

    「啊，好的。谢谢招待。」

    天爱星同学松了口气般接过饼干，表情却渐渐转为困惑。

    「那个……被人一直盯着看，我会觉得不太自在。」

    天爱星同学会不知所措也不能怪她。

    因为八奈见正身子前倾，凝视着天爱星同学的手边。

    我强忍着叹息，轻轻拍打椅子。

    「八奈见同学。好了，可以在椅子上坐好，当个乖孩子吗？」

    「温水，你是不是觉得我自己把点心送给人家，现在却又舍不得了？」

    嗯，我是这么想的。

    八奈见神情无奈地耸了耸肩，沉重地坐在椅子上。

    「我说啊，温水你仔细听好了。这种饼干每一片的热量是七十大卡。」

    「喔。」

    「我原本预定要吃的饼干，现在马剃同学代替我吃掉了——这代表什么意思，你懂吗？来，小鞠回答！」

    「呜呃！？我、我？」

    原本待在社办角落凝视着智慧型手机的小鞠，吃惊地抬起脸。

    「呃，那个人、八奈见会稍微，少胖一点。」

    「……不对。来，换温水回答。」

    原来这是轮流制喔。

    「至少给我一点提示吧？」

    「真拿你没办法。因为把饼干给她了，你觉得我摄取的热量会怎么样？」

    还能怎么样，根本没吃啊。

    「就是零大卡啊。」

    「不对。我原本要摄取的热量传到了马剃同学身上——换言之，就等于负七十大卡。」

    「不等于喔？」

    尽管我真心诚意地吐槽，八奈见仍双手抱胸，继续解说她的谜之理论。

    「所以只要马剃同学吃一百一十片这个饼干，我的体重就会减少一公斤。来，马剃同学，再多吃一些。」

    「一片就好了——啊，好的，谢谢招待。」

    天爱星同学无法回绝，接过了第二片饼干，同时看向我。

    「那个，为什么我现在会在文艺社的社办里吃饼干呢？」

    「图书室关门后还有管理图书的老师在，我想这边会比较少人看到。」

    「这里的人数很明显比图书室还多吧？」

    我也有这种感觉。

    但是八奈见她们就形同土著的妖怪，在意也没用。

    「但是对话不会被社员以外的人听见——其实还满常发生的，但是大可放心。」

    「听你这样说，我还能够放心吗……？」

    「学姊，请喝茶。」

    「咦？」

    叩的一声，白玉学妹将第二个茶杯摆到天爱星同学面前。

    对着并排的茶杯，天爱星同学不知所措地开口说：

    「我记得你是白玉学妹吧？茶已经够了——」

    「请在茶水凉掉之前享用。」

    「啊，好的。」

    天爱星同学发出轻啜茶水的滋滋声。

    同时八奈见凝视着天爱星同学的饼干。嗯，文艺社还是老样子。

    「话说马剃同学，找我有什么事？」

    「要我在这种状况讲吗？」

    是的，就是这样。

    天爱星同学像是做好了觉悟，把饼干塞进嘴里，然后将一张纸摆到桌上。

    「说来话长。那个，简而言之，我想借用温水同学的名字——」

    「在这里写名字就好？」

    我取出钢珠笔后——

    「社长！」

    白玉学妹脸色骤变，阻止了我。

    「有什么问题吗？」

    「是的，在仔细看过之前不可以写名字喔。」

    「温水，你认真一点啦。像我爸爸以前就是到处乱盖章，事情才会变得那么严重喔。」

    八奈见拿起了桌面上那张纸，随后她纳闷地连连眨眼。

    「学生会选举的参选申请书……？这个为什么和温水有关？」

    「我想各位应该知道，下个月的运动会结束后，学生会的任期就结束了。」

    我当然不知道。

    天爱星同学挺直了背脊，正面注视着我。

    「我要登记参选下届学生会长，因此希望温水同学当我的推荐人。」

    「推荐人？你说我？」

    我自己也觉得傻气地重复了这句话。天爱星同学听了，表情认真地点头。

    「是的。也希望能麻烦你进行声援演讲。」

    声援演讲——我记得是投票当天要在体育馆举办的吧。

    我要站在全校学生的面前演讲啊……原来如此……

    「不，我不行。」

    我从八奈见手中抽出参选申请书，放到天爱星同学面前。

    「不好意思，你可以另请高明吗？」

    「温水同学，可以先听我说完吗？」

    天爱星同学仍想说服我，但唯独这件事我办不到。

    「好啦好啦，温水。至少听人家把话说完嘛。」

    八奈见说着，递出第三片饼干。

    天爱星同学在迟疑中接下饼干，八奈见亲切地笑了笑。

    「所以说，如果马剃同学当选了，温水也要加入学生会？」

    「是的，学生会成员是由会长指名，如果温水同学愿意当副会长当然最好。」

    「为什么要找温水？还有其他更好的人选吧。」

    八奈见还是老样子，真是个失礼的家伙。

    天爱星同学听了这句话后深深点头。这个人刚才不是说想要我吗？

    「本届学生会的会长和副会长都是女性，因此希望下届其中一方是男性——老师提出了这样的请求。所以……」

    「所以才挑上温水吗？樱井不是比较好？」

    八奈见，你也该闭嘴了。

    「樱井说他不打算继续待在学生会，我也没有其他比较亲近的男生……」

    天爱星同学神情尴尬地垂下脸。

    原来如此，我很习惯这种消去法。我重整心情，插嘴说：

    「真有必要这么执着于男生吗？现在双方都是女生也没问题，只要好好说明，老师也会接受吧？」

    「因为学生会是学生的代表，目的就是为了尽可能汲取学生的意见。若学生会里全都是异性，学生有事也不方便商量吧。」

    的确，现在的学生会，樱井是唯一的男生兼良心。确实有必要呢，男生。

    「我成为副会长的时候，听说也发生过一些事。在当选后的活动过程中，也需要得到包含老师在内的众人配合。可以请你成为石蕗男学生的代表，助我一臂之力吗？」

    情况我明白了，但是由我来代表男生真的没问题吗？

    我正想着该怎么让她放弃时，八奈见开了口：

    「马剃同学的意思我懂了，但是温水毕竟是文艺社社长，我们也很伤脑筋啊。」

    八奈见第一次说出像是帮腔的话喔。得趁这个大好时机顺水推舟。

    「对啊，就是这样。毕竟我有社团活动要忙，学生会就——」

    「如果要我们出借温水——文艺社也要有相应的好处才行。」

    八奈见挑起嘴角一面露邪恶笑容。

    不妙，我上错船了。

    「好处吗？」

    天爱星同学听见意想不到的话，睁圆了眼睛，八奈见的上半身向她逼近。

    「没错，好处！比方说加入学生会就能恣意运用预算，或是在餐厅吃到饱。没有学生会特权之类的东西吗？」

    「这个嘛，类似特权的东西……虽然社团活动的预算案的确是学生会编列的，但是需要老师核可——」

    「可以决定社团活动的预算吗！？温水，你加入学生会嘛！」

    出卖我的速度也太快了。

    「我不行啦。八奈见同学一定也这样想吧？」

    「可是你不希望社办有冰箱和微波炉吗？要是再有个梳妆台就更好了～」

    那些和社团活动无关。

    这时，在天爱星同学背后静观的白玉学妹双手合十，两眼闪闪发亮。

    「梳妆台不错耶！小鞠学姊一定也很想要吧？」

    「呜呃……书装……？」

    话锋突然转向小鞠，她在社办的角落处浑身一颤。

    「就是化妆台。不能用社团经费买那种东西啦。」

    「化妆台的确不太行。不过想要冰箱的话，学生会室的冰箱也许可以让给你们。」

    「就这样说定了。温水，你加油吧。」

    「并没有说定。我不打算帮这个忙。」

    我断然拒绝后，八奈见对我投出挑衅的眼神。

    「那就采取多数决啊。小白玉你怎么说？」

    白玉学妹用双手食指抵着太阳穴，神态可爱地歪过头。

    「嗯～我想想，社长是学生会成员，感觉好像有点帅。」

    「咦？是吗？」

    白玉学妹对我盈盈一笑。

    「是的，会忍不住想跟旁人炫耀，说我的社长可是副会长喔。」

    「这样啊～很让你自豪啊～可是～」

    「……为什么换成小白玉讲，你干劲就来了？」

    八奈见不知为何不开心地盯着我瞧。

    刚才你不是一直叫我进学生会吗？

    「社员的想法很重要吧？也得问一下小鞠的意见。」

    「去、去死。」

    「看吧，她反对。这样票数就是——」

    八奈见点了点头。

    「嗯，就是二对一，赞成票比较多。」

    「我没有投票权吗？」

    「你是当事人，当然没有。就这样啦，马剃同学，我们讨论出结果了。」

    刚才默默眺望着我们讨论的天爱星同学，突然回过神来般挺直背脊。

    「啊，好的！那么请温水同学在这里签名——」

    当天爱星同学向文件伸出手时，白玉学妹将第三个茶杯沉重地搁在文件上。

    「咦，请问……？」

    「我那一票还没盖章，这样是一对一呢。」

    在袅袅升起的水气另一端，白玉学妹面露天使般的笑容。

    「马剃学姊——请在凉掉前喝茶。」

    ◇

    突如其来的邀请之后过了两天，放学后的家政教室。

    我满心敬佩地看着樱井熟稔地为牛蒡剥皮。

    「那是会长的便当配菜？原来你是在学校做的喔。」

    「是啊。常备菜在放学后做好，要炒的则是早上在家里做。」

    家政教室的另一头，传来料理社员的欢笑声。

    虽然他不是料理社的一员，但好像会不时像这样借用场地。

    「……我都听说了。温水也真是辛苦呢。」

    樱井面露为难的笑容，将切好的牛蒡泡水。

    「如果你这样想，可以代替我当她的推荐人吗？马剃同学今天也在走廊埋伏我。」

    「马剃她好像不想借助我们学生会成员的力量。梦子学姊说她愿意当推荐人，但是被断然拒绝了。」

    「原来三年级也能当推荐人啊。」

    「这方面没有规定，而且推荐人也不是一定要进学生会。」

    哦？是这样啊。不过重点是，天爱星同学不愿意向学生会的其他三人求助啊……

    我不方便更进一步追问，便将视线转向发出喀嗒声的锅子。

    「那边的锅子里在煮什么？」

    「在炖蜂斗菜和油豆腐。是云雀姊喜欢的菜。」

    樱井掀起充当锅子落盖（编注：日本料理炖煮时直接盖在炖煮物上的盖子，用以帮助食材入味，或抑制汤汁的蒸发速度等。）的铝箔纸边缘。

    「会长的口味好像满老派的？」

    「基本上都吃传统菜色。如果放着不管，她就不吃肉和油炸的东西，得多注意才行。」

    哦，这样啊。和八奈见加起来除以二——不，除以四大概刚刚好吧。

    「能够这样照顾云雀姊，运动会就是最后一次了。在那之前还有学生会选举，我想至少帮她做便当。」

    ——能照顾她的时间已经不多了。

    三年级生大多数都会因为升学而离开这个城镇。

    现在天天在同一栋校舍上学的学生们，之后都会各奔东西。

    「会长毕业之后，果然也会离开丰桥吗？」

    「她说为了将来，要去东京。我也差不多该——」

    当他以有些寂寞的口吻接着说下去时——

    「樱井～来，嘴巴张开～」

    料理社的女生突然闯进我们之间。

    外貌华美的女学生，将木汤匙递到樱井的嘴边。

    樱井自然地张嘴吞下后，笑着点头。

    「是冷制茶碗蒸啊。这种汤头，是昆布加鲣鱼吗？」

    「嗯，费了点功夫试着熬了高汤。下次再教你。」

    「我很期待喔。」

    「方便的话今晚来我家吧？我爸妈不在喔。」

    「那样不好意思，还是算了吧。」

    女学生笑了笑，轻轻摆手便离去。

    樱井也对她挥了挥手，接着取出红萝卜——

    「咦？刚才那是怎样！？你们两个在交往吗！？」

    「不是啦。她是料理社的副社长，之前为了让我能借用教室，曾帮忙和其他社员沟通。」

    哦～是这样啊。是有那个人安排，樱井才能借用家政教室啊……这样啊……

    「不是，那和喂食无关吧？正常来说，没有交往不会这样吧？」

    「没有这回事啦。料理社也没男生，她只是觉得好玩而已。」

    樱井苦笑。顺带一提我也是男生。

    「坦白说，如果温水愿意帮忙马剃，我就放心了。因为她认识的男生顶多就我们两个而已。」

    「如果我拒绝了，会怎样？」

    「老师应该会帮忙介绍男生人选吧。」

    樱井轻描淡写地说着，同时关上瓦斯炉的火。

    「因为石蕗的学生会活动不算热络。老师们每年都会适度帮忙安排，以免参选人挂零。」

    「既然这样，我不帮忙也没关系吧……？」

    「前提是马剃和对方能处得来——不过，只要和她一起工作到最后，没有人会说她的坏话喔。她是个懂得为别人设身处地着想的孩子。」

    「你很瞭解她呢。」

    「算是吧。毕竟学生会就四个人，又同样是二年级生。」

    樱井手中正削着红萝卜皮的菜刀停了下来。

    「现在的学生会，云雀姊的存在感无可避免地非常强，马剃不希望我们出手帮忙，一定是有她的用意。所以我也不会插手。」

    樱井清楚地宣告立场后，再度动起菜刀。

    关于天爱星同学的事情，看来没办法有更进一步的开展了……

    为了转换心情，我拿起了削好皮的红萝卜。

    「有什么能帮忙的吗？」

    「那可以帮忙把那个削成薄片吗？用那边的削皮器。」

    「瞭解。今天预定要做什么？」

    「红烧牛蒡和云豆拌芝麻吧。」

    我们两人默默地进行作业时，背后传来雀跃高亢的说话声。

    「樱井学长，不好意思在你忙的时候打扰了～！」「打扰了～！」

    接着前来搭话的是氛围青涩的女生三人组。

    站在中间的女生羞赧地垂着头，左右两侧的女生则是频频催促。

    「好了，快点说啦。」「快点～」

    在两侧朋友的催促下，害羞的女生忽地递出一个小包裹。

    「那个，樱井学长！这是我做的，希望你能品尝看看！」

    那女生手中拿着用心包装的玛德莲蛋糕。

    「谢谢你，我之后会用心品尝的。」

    「我、我会一直为学长打气的！」

    三名一年级女生发出高亢的尖叫声，拔腿就逃。

    「…………刚才那是什么情况？发生了特殊事件？」

    「这个嘛……因为我缺乏男子气概，所以给人好亲近的印象吧？」

    原来如此，我也时常被评为不像个男人，但是并没有学妹来麻烦我试吃。

    我开始思索阶级社会时，樱井以平静的语调说道：

    「……我想好好珍惜这一年。」

    握着菜刀的手不再动作，他用只有我能听见的音量继续说。

    「在我眼中，马剃和梦子学姊，再加上云雀姊，就是学生会的一切。所以，就到这一届为止。见证选举的结果、运动会结束之后，我就要专心读书了。」

    樱井的视线短暂瞥向我，有些尴尬地说：

    「抱歉，帮不上忙。」

    我才该道歉——我本想这么说，但是只回以苦笑。

    坦白说，我原本打算把天爱星的问题全部扔给樱井解决。

    但是他面露笑容反过来向我道歉了，我也只能竖起白旗。

    ……也难怪樱井会这么受欢迎。

    我莫名觉得十分合理，同时默默地继续将红萝卜削成薄片。

    ◇

    我已经完全习惯骑自行车上下学了。

    眼角余光映着一年级时习惯上下车的东八町路面电车站，我骑着爱车奔驰过傍晚的街道。

    之前在太阳西斜后会挟带寒意的风，现在反而令人感到舒畅。

    我帮完樱井之后，为了避免撞见天爱星同学，直接打道回府。

    由于近来天爱星同学出没于西校舍的阴暗处，我决定不再靠近。

    「我回来了～」

    我打开玄关大门，注意到一双陌生的鞋子整齐地摆在地面上。

    ……那么，这是哪种情况？油亮的黑色皮鞋是女用款式，但不是文艺社女孩们的鞋子。是佳树的朋友，或是家庭访问之类的吗？

    我并未深思就推开客厅门，映入眼帘的是——与佳树并肩站在厨房、穿着围裙的天爱星同学。

    「！？为什么天爱星同学会在这里？」

    听了我理所当然的疑问，佳树对我投出责怪般的视线。

    「兄长大人，马剃学姊是佳树的客人喔。我们之前约好要一起做料理。」

    「温水同学，打扰了。还有，请不要用名字称呼我。」

    天爱星同学和佳树约好做料理……？挑这种时候？

    我佯装平静，将背包摆到沙发上，用眼角余光观察两人的状况。

    佳树双手各拿着柴鱼与昆布，滔滔不绝地说明，天爱星同学则是频频点头着做笔记。

    两人确实在聊料理的话题，但不能掉以轻心。

    我提高警戒观察两人，这时玄关的门铃响了。

    佳树用围裙擦着手，走向大门。

    「佳树去应门。兄长大人，麻烦你陪伴马剃学姊。」

    陪伴？都高二了，放着她不管也没差吧？话虽如此，忽视她感觉也不太好。

    我站到天爱星同学身旁，低头看向冒着水气的锅子。

    「……味噌汤？」

    「是的。我不想被人以为，是个连味噌汤都煮不好的女人。」

    天爱星同学说完，双眼凝视着锅里的昆布。

    三月于会长家合宿时，她忘了准备汤头那件事，她还耿耿于怀吗……

    「那次的味噌汤也很好喝喔。该说直接表达了红味噌的味道，或者说非常有红味噌感。」

    「这不是在夸奖吧？好了，请试喝看看。」

    天爱星同学面无喜色地将小碟子推向我。

    我感受到几分压力的同时，将汤汁含到口中，随后熟悉的味道在舌尖漾开。

    「嗯，很不错啊。因为用了平常用的昆布，味道和佳树做的一样。」

    「——兄长大人，不是用同样的材料就能煮出同样的味道。」

    如此说着，佳树走回厨房。

    「食材处理上有些微差异，口味就会截然不同。那就是各个家庭的口味。」

    「是这样吗？可是尝起来很像平常的味道耶。」

    佳树快步走向冰箱，取出麦茶。

    「毕竟是佳树直接指点的。只要反覆练习，马剃学姊自己一个人也能重现温水家的口味。佳树随时都在这里等你。」

    「咦！？」

    天爱星同学一手拿着锅杓，猛然一颤。

    「不、不是，我不是为了这个目的才学的！虽然温水同学平常吃的口味的确令我好奇——咦？我要嫁到这个家了吗！？」

    不，没有人这样讲。这个人还是老样子，情绪很不稳定耶……

    「那个，不是这样，你放心——」

    「咦？是小马耶。怎么在这里？」

    突然飞来的一句话，来自烧盐。

    烧盐一身无袖背心搭配短裤的打扮。她将毛巾挂到脖子上，走进客厅。

    「今天佳树和马剃学姊一起做料理。烧盐学姊请喝茶。」

    「谢谢你，佳树妹妹。」

    烧盐一口气喝干了佳树递给她的玻璃杯中的麦茶，心满意足地吐气。

    「哈～全身沁凉～那我借浴室冲个澡喔。」

    「好的，毛巾已经挂在里头了。」

    烧盐轻轻摆手，走出客厅。

    自从我家变成临时社办，她就时常来我家借浴室冲澡耶……

    「马剃同学，汤已经滚了，不要紧吗？」

    「咦？那、那个，为什么烧盐同学会在这儿冲澡啊！？」

    为什么呢？我也不晓得。

    「啊～……因为我家正好顺路？」

    「就算这样，正常来说也不会去男生家冲澡吧！？该不会你们两位是那种关系！？」

    「是这样吗？兄长大人！」

    不知为何连佳树都兴奋了起来。

    「起初是佳树借她浴室冲澡的吧。好了，快点把火关了。」

    我关了瓦斯炉开关，不理会两人，迳自品味汤头。

    和佳树相比，虽然舌尖上留有几分杂味——不过出乎意料地还不赖……

    ◇

    我终于找到机会逃离厨房后，走向楼梯的同时，视线飘向盥洗室的门。

    没有听见淋浴时的水声。

    我打算加快脚步通过门前的时候——

    「——唉，阿温。」

    烧盐隔着房门叫住我。

    「怎、怎么了！？」

    我不禁吃惊，烧盐则以平常的口吻继续说。

    「运动会的练习快开始了吧？阿温参加什么项目？」

    ……运动会？为何现在要提起这件事？

    「我记得好像是障碍赛跑吧。」

    我若无其事地回答，但是听到毛巾擦过身体的声音，就让我——非常介意。

    隔着一扇门，刚出浴的同年级女生就在里头。别看我这样，我可是健全的男生。

    「呃～这件事之后再说——」

    「唉，你都不问我要参加什么项目吗？」

    这是什么麻烦女友会讲的台词？

    「那……烧盐你要参加什么？」

    「班际对抗接力赛和两百公尺，还有啦啦队竞赛吧。阿温没参加啦啦队竞赛吗？」

    啦啦队竞赛啊。就是各个班级的阳角们唱歌跳舞的活动吧。

    「我没有啊。自己当自己的啦啦队，这样不奇怪吗？」

    「什么跟什么呀，你想太多了啦。」

    烧盐咯咯地笑着。

    我跟着笑起来后，回应的是烧盐添了几分严肃的声音。

    「——小鞠都告诉我了喔。」

    告诉你什么？在我问她之前，烧盐已经接着说下去。

    「她说阿温又想弃文艺社于不顾了。」

    「……烧盐有资格讲这种话？」

    「呃～上次和这次是两回事嘛。」

    是喔，两回事吗？既然烧盐这样说，那也没办法。

    「简单说，就是马剃同学拜托我当会长选举的推荐人。我一直没办法完全拒绝。」

    「推荐人？就这样而已？」

    「还有，她说如果她当选了，希望我当副会长——」

    「阿温，你要加入学生会吗！？」

    喀啦一声，盥洗室的门应声开启，我连忙挪开视线。

    「笨蛋！？不要开门啦！」

    「我穿好衣服了啦。你看，我有包着浴巾啊。」

    浴巾不是衣服。绝对不是。

    不过，既然她本人都说没关系了，稍微看一眼也无妨吗……？

    不理会正天人交战的我，烧盐光着脚一步步踏向我。

    「是喔～我邀你进回家社时，你明明二话不说就拒绝了，小马邀你进学生会，你就会犹豫啊。是喔～」

    「我已经拒绝过了，只是她一直不愿意放弃而已。」

    「明明都拒绝过了，还跑到家里来做饭啊。是喔～」

    我能感受到，视野外侧的烧盐正步步逼近。

    刚出浴时的洗发精香气与烧盐本身的香气，缠上我的脖颈——

    「烧盐同学，你在生气吗……？」

    「我没生气啊？」

    啊，这就是在生气。因为我有个妹妹，女人心我很瞭解。

    我依旧背对着她，低下头道歉。

    「呃，对不起。我会多注意一点，不要让小鞠不安的。」

    「……嗯～算了，今天先这样放过你。」

    被原谅了。当我松了口气的时候，烧盐俐落地绕到我面前。

    「！？会感冒啦，你快点把衣服穿好！」

    「所以说已经有穿了嘛。你这么介意反而会让我害羞耶。」

    （插图009）

    你也稍微害羞一点。裸身裹着一条浴巾，比想像中还要极限喔。

    「阿温，就拜托你多关心小鞠了喔。」

    「我知道了啦！你快回去！」

    确定烧盐回到盥洗室后，我松了口气。

    陌生的洗发精香气仍在此处萦绕不去。

    ……

    ………………奇怪？

    「烧盐，你该不会把自己的洗发精拿到这里了？」

    「嗯，我用的是小千给我的那种。阿温也可以拿去用喔。」

    那么我爸妈应该也注意到陌生的洗发精了——

    ……不，别再想下去了。

    为了甩开难以释怀的心情，我一口气跑上了楼梯。

    ◇

    隔天午休。我一只手拿着咖喱面包和牛奶，造访了旧校舍的逃生梯。

    今天天气不错，气候也宜人。如果不在教室，肯定就在这里——

    「啊，猜对了。」

    在三楼的楼梯间，小鞠倚着栏杆，正在吃奶油面包卷。

    见到我的身影，她似乎吃了一惊，咽下口中面包。

    「温、温水你来了喔。」

    「是啊，我想说小鞠应该在这里。」

    「呜唉……？」

    小鞠好像觉得困扰，但我不理会，站到她身旁。

    既然半裸的烧盐都那样拜托我了，我也只能对小鞠多加关照。这就是所谓的利益交换。

    我递出了盒装牛奶，说出事先想好的台词。

    「呃～我不小心买了两盒牛奶。小鞠，要不要喝一盒？」

    「怎、怎么搞错才会买到两盒？」

    小鞠嘴巴上这么说，还是接过了牛奶。

    「听你这样一说，好像也是。我可以想下一句台词吗？」

    「赶、赶在午休结束前想好。」

    我看着小鞠叼着吸管开始吸牛奶，自己打开咖喱面包的袋子。

    那么，该怎么切入正题呢……

    「小鞠，前几天马剃同学来社办了对吧？」

    「去、去死。」

    也太快吐槽了。

    话虽如此，小鞠心情因此浮躁也不能怪她。

    先是烧盐的退社骚动，之后又陪大有问题的新生闹出两星期的假废社。

    屡次对副社长小鞠造成了心理负担。顺带一提我也十分辛劳。

    「这次不会变成小鞠担心的局面啦。我可是文艺社的社长喔。」

    「不、不要老是拿社长位子压人。」

    「啊，好的，我会注意。」

    唔嗯，这条路也不行啊。

    我拿不出办法，默默吸着牛奶，这时小鞠斜眼瞪向我。

    「烧、烧盐跟你，讲了什么吧？」

    「哎，这个嘛，稍微啦。」

    我不禁语塞，啃着咖喱面包，于是小鞠轻声叹息。

    「我、我知道你是个滥好人。你、你开心就好。」

    「我真的不打算参与学生会选举啦。比方说昨天，也是马剃同学擅自跑来我家。」

    「那、那个女的，还跑到你家了？」

    咦？烧盐没跟她讲吗？不妙，自掘坟墓了。

    「啊～她好像有事找我妹。就是因为学生会的关系认识的嘛。而且当时烧盐也在我家。」

    「连、连烧盐也在？」

    小鞠的视线渐渐转变成看厨余的那种。坟墓深度顺利成长。

    「呃～简而言之，就是你大可放心。」

    「毫、毫无节操的家伙。」

    抛下这句话后，小鞠开始小口地咀嚼奶油面包卷。

    我也尴尬地吃起咖喱面包时，小鞠低声嘀咕。

    「照、照你的个性来看，反正到最后，你一定推不掉吧。」

    「没有——」

    「你真的敢说，没有这回事？」

    ……我不敢。我默默地吃完咖喱面包，尽管迟疑还是开了口。

    「假设，只是假设喔，我成为马剃同学的推荐人也没关系吗？」

    小鞠在掌心中把玩着牛奶的空盒，用放弃了什么似的口吻嘀咕说：

    「要、要进学生会还是要怎样，随便你。」

    「我真的没有要进学生会啦。」

    「我、我说了，随便你。」

    ……唉，我没有信用也怨不得人。我也觉得自己前科累累。

    我用手肘抵着楼梯间的围栏，愣愣地眺望远方。

    在广大市区的彼端，熟悉的低矮山头连绵不绝。

    一阵子没注意，山头的绿意变得更浓了。下星期就是六月，制服换季的季节马上要到了。

    今年的夏天也即将揭开序幕。

    ◇

    当天放学后。我来到距离学校不远的桌游咖啡厅DEJANA。

    我坐在二楼的桌子旁，与我面对面的——是学生会书记，志喜屋梦子。

    浅褐色长发勾勒出和缓的波浪曲线。

    她悠悠地摇头晃脑，那双不知看向何处的白色眼眸转向我。

    「轮到……温水了喔……？」

    「啊，好的。」

    为了避免被发现我刚才直盯着她瞧，我急忙掷出骰子。

    我推动褐色的熊型棋子，同时确认盘面状况。

    我们正在玩的游戏类似两人用的双陆棋。

    虽然当作主角的可爱褐熊与白熊是童话风的外观，但是决定胜败的关键是放在场上的筹码与规则的活用，出乎意料地需要动脑。

    顺带一提，我目前已三连败。

    「这枚筹码我拿走了，请回到起点。」

    「这样子……真的好吗……？」

    喀啦。志喜屋学姊掷出的骰子点数是6。

    「咦？该不会二十点的筹码被抢了？」

    「漂亮的……助攻……」

    心情愉快的志喜屋学姊，用那装饰花俏的指尖拾起筹码。

    当然我们并不是在卿卿我我地享受放学后的约会时光。

    只是我联络她说有点事想商量后，就约好在这里碰面而已。我是说真的。

    我看准了时机，假装若无其事般开口：

    「那个，请问马剃同学最近还好吗？」

    「还好……吧……？」

    志喜屋学姊伸向白熊棋子的手停住。

    「只是有点好奇，她最近在学生会的状态如何。」

    「你不是……想和我……聊天吗……？」

    志喜屋学姊边摇晃边说。

    我总觉得感到几分压力，点头如捣蒜。

    「啊，对。我想和学姊商量马剃同学的事，所以想聊一下……」

    怎么回事，这种难以言喻的诡谲气氛。

    我坐立难安之时，志喜屋学姊忽地歪过头。

    「你想问……会长选举的事？」

    「是的，听说学姊想当推荐人却被拒绝了。」

    「嗯……天爱星……不要我……」

    志喜屋学姊神情悲伤地悠悠摇晃着。

    「为什么学姊想当推荐人，我可以问问理由吗？」

    「因为天爱星……拒绝了……老师替她介绍的人……」

    她左摇右晃着，以纤细的指尖把玩白熊棋子。

    「如果没人……愿意帮她……会落选……」

    摇晃了好半晌的志喜屋学姊，将那双白色眼眸转向我。

    「天爱星……找你帮忙……？」

    「哎，她好像想拜托我当推荐人。虽然我拒绝过了，但是她一直不愿意放弃。」

    志喜屋学姊的摇晃不知何时停摆了。

    「是……这样啊……」

    沉默。

    我如坐针毡，用指头轻戳褐熊棋子。

    「因为天爱星……很中意……你。」

    「那是基于角色，应该说BL之类的原因吧？」

    「无法……否认。」

    志喜屋学姊轻轻放下棋子，游戏继续。

    我无法专注于游戏，扔出骰子的同时继续对话。

    「如果找我上台声援演讲，原本能当选的都会落选的。如果老师能找到合适的推荐人，那样当然最好。」

    「你不想……为她打气吗……？」

    志喜屋学姊的白色眼眸看了过来。

    我缓慢地左右摇了摇头。

    「她个性认真又有工作热忱，我也乐见她当选。」

    短暂迷惘后，我继续说。

    「我明明并不关心学生会活动，只是因为认识就找我来当推荐人，这样真的对吗？而且老实说，要我在众人面前演讲有点——」

    「这些话……你告诉天爱星了……？」

    「不，没讲这么多。我看还是试着拜托她，请她让学姊当推荐人吧？」

    「大概……没用……」

    志喜屋学姊伸向桌游的手再度停摆，直盯着骰子看。

    尽管无风，纤长的睫毛仍微微颤动。

    「我……太黏她……被讨厌了……」

    「呃，我想应该没有那回事……」

    我不知该怎么回应，这时志喜屋学姊突兀地站起身。

    「温水……这边……」

    「咦？学姊，等一下。」

    她一说完就抓住我的手，把我拉向房间角落。

    「学姊，到底是怎么——」

    「蹲下……」

    「啊，好的。」

    我顺从地蹲下，身子缩在无人餐桌的后方。

    ……我们的手好像还牵着。

    志喜屋学姊那细致肌肤的触感。

    寒气缓缓渗向我，渐渐夺走我手指的感觉。

    「怎么了……？」

    「那个——没有，没事。」

    今天天气也满热的，冰凉一点也许比较好。嗯，毕竟中暑很可怕嘛。

    ……志喜屋学姊就蹲在一旁，我用眼角余光偷偷打量她的神情。

    她依然像平常那样面无表情，只把脸探出桌面上方。

    假睫毛围绕着忘记眨眼的白色眼眸。

    飘荡在四周的甘甜香气有种成熟的感觉，是她最近常用的香水。

    当我愣愣地看着她时，志喜屋学姊朝手表瞥了一眼。

    「正好……下午五点……」

    「你约好了要和谁碰面吗——」

    「安静……头压低……」

    我压低了头，同时沿着志喜屋学姊的视线看过去，一名石蕗女生正从阶梯走上楼。

    现身的是马剃天爱星。她有些紧张地环视二楼后，坐到距离楼梯最近的餐桌旁。

    她挺直了背脊，凝视着楼梯，大概是在等什么人吧。

    「马剃同学怎么会来这里？」

    我小声问完，志喜屋学姊神情有些得意地回答：

    「是我……叫她来的……」

    「如果是要三个人坐下来谈，在学生会室就可以了吧？」

    「你讨厌……和我玩……？」

    「我——不讨厌。」

    不知为何有点害臊，我将视线转回天爱星同学身上。

    这时天爱星同学缓缓地从书包中取出了某物。

    小小的圆盘状物体，好像是化妆用的粉盒。

    她打开盖子，「啪啪啪」地将粉扑拍在脸颊上。

    ……感觉好像昭和年代的老妇人。

    「为什么我们要躲起来看啊？」

    「天爱星……愿意来……好开心……」

    志喜屋学姊雀跃地轻轻摇晃着身子。

    话说回来，这两个人好像是能够轻易解开胸罩背扣的那种关系。

    虽然我不太懂，不过这也是情趣的一环吧。放置＆观赏，等级还真高……

    当我为了大人的世界而脸红心跳时，不知何时天爱星同学正笔直地盯着这里看。

    「天爱星同学是不是在看这里？她的表情很恐怖耶。」

    「这个瞬间……令人欲罢不能……」

    原来如此，这就是大人的世界。

    我不禁感叹时，天爱星同学快步走向这里。

    「你们两个都在啊！？为什么不跟我打招呼？」

    「怕打扰……你化妆……」

    志喜屋学姊摇晃地站起身，伸出手臂圈住天爱星同学的身子，将脸靠近到鼻子几乎相触。

    「化妆不拿手……太可爱……违反校规……」

    「没有那种校规——咦？我化妆技术很糟吗！？」

    「这一点……特别可爱……」

    「请不要磨蹭我的脸！」

    唔嗯，介入这两人之间只能说是不识趣。

    我回到座位上，啜饮完全凉掉的咖啡。

    苦涩与酸味的合声，在舌尖上漾开。

    「温水同学，你别只顾着看，救救我——等等，学姊是在摸哪里啊！」

    我看着紧密交缠的两人，又将一口咖啡含在口中品味。

    冰凉的咖啡——和百合十分相配。

    （插图010）

    ◇

    「这是怎么一回事啊！？你们两个到底想做什么！」

    天爱星同学用汤匙搅拌着咖啡，同时恶狠狠地瞪我。

    「而且叫我过来的当事人，说什么已经满足了就离开，到底是怎样！？」

    「我也答不上来……」

    没错，志喜屋学姊已经离开了，只剩我一人承受天爱星同学的怒气。明明就不是我的错。

    「温水同学也不帮忙拦住她，为什么你一直在悠哉地玩手机啊？」

    「我想拍影片——不是啦，志喜屋学姊和天爱星同学就是那种船过水无痕的成人间的关系吧？我也不好意思打扰你们。」

    「没这回事好吗！？还有请不要用名字称呼我！」

    气呼呼的天爱星同学仰起头大口饮用加了牛奶与三匙砂糖的咖啡。

    过了一段时间，大概是糖分与咖啡因使她终于镇定下来了，天爱星同学放下咖啡杯，发出细微的声音，随后清了清嗓子。

    「所以说那个……特地找我出来是要谈什么呢？」

    ……嗯？她在说什么？

    「我起初根本不晓得马剃同学会来这里啊。」

    「我是听志喜屋学姊这样说才来的。」

    咦？怎么回事。所以说志喜屋学姊把我当作钓饵，约了天爱星同学来到这里吗？

    我感到困惑时，玻璃碎裂的高亢声音传入耳中。

    「这是什么声音？」

    「喔喔，是志喜屋学姊传讯息来。」

    我看向智慧型手机，一条讯息滑入了通知栏。

    ——回敬圣诞节那次。

    ……中招了。

    我不禁仰头看天。去年的平安夜，我为了让志喜屋学姊与月之木学姊碰面，以圣诞灯饰当幌子，约了志喜屋学姊出来。

    简单说，就是在回敬当时那场骗局。

    「温水同学，请不要自己一个人明白就不解释了。发生了什么事？」

    「这个嘛，简单说我曾经招惹志喜屋学姊的怨恨，这次就类似报复。」

    「招惹怨恨？你做了什么事？」

    嗯，哎，做了不少事。我含糊地蒙混过去，假装饮用已经喝完的咖啡。

    志喜屋学姊安排我们两个面对面的意义。

    我思考着这件事，开了口。

    「那个，关于学生会选举的事情。」

    「啊，请说。」

    我暂且停顿，观察天爱星同学的反应。

    天爱星同学挺直了背脊，等候我的下半句话。

    ——为何拒绝了志喜屋学姊的好意？我原本想问，但是打消了主意。

    「我是文艺社的社长，不打算和学生会扯上关系。就算是当推荐人，一个对学生会没兴趣的人，只在形式上这么做感觉也不对。况且我——」

    我想面露自嘲的笑容，表情却变得僵硬。

    「不擅长在大家面前讲话。」

    天爱星沉默地听完我的理由，一度欲言又止，最后深深叹息。

    「……我明白了，我不会再强求了。」

    奇怪？这么干脆就愿意放弃了啊。

    我不禁愣住时，天爱星同学以不经意的动作将智慧型手机摆到桌面上。

    忽地发亮的待机画面上，映着美少女的插图——不对，是美少女角色周边的照片。为什么天爱星同学会有这种照片……？

    我不禁看了两次，下一瞬间，身子不禁从椅子上浮起。

    「咦？那是《擦边出局少女群》小奇卡的店面海报！？马剃同学怎么会有？」

    「我亲戚有人在做生意，好像是促销用的周边——吧？时常会送给我。大概是觉得我年纪还小，喜欢动画和漫画吧。」

    天爱星同学一脸若无其事地将智慧型手机推向我面前。

    「这类东西我不太懂，想说如果能分给喜欢的人就好了。」

    「既然这样……！」

    我猛然起身，撞得身后椅子发出声响，但在短暂迟疑后，又慢慢坐回椅子上。

    「呃……是这样喔。希望你能找到想要的人。」

    「哎呀，没关系吗？印象中温水同学的钥匙圈和这个角色很像呢。」

    「是这样吗？毕竟类似的角色也不少。」

    我不禁调整背包的位置。

    岂止是类似——我挂在背包上的吊饰就是小奇卡。

    所以说，天爱星同学是事先知道我推的角色才使出了这招。我可不能随随便便就上钩。

    …………

    ………………不，但是……听她把话说完也无妨吧……

    我的视线不时飘向天爱星同学的手机萤幕，这时她轻轻一笑。

    「这个可以送给你，麻烦你当推荐人——」

    「！」

    「我不会这样说的。如果有人想要，我愿意转让。」

    「咦？真的可以吗？」

    这句话说出口的瞬间——我意识到了自己的败北。

    天爱星同学的嘴角浮现了感到有趣似的笑容。

    「可以是可以，不过我对那张海报也稍微有了些感情。如果你能在不勉强的范围内给我一点回报，我会很高兴的。」

    咕，果然会变成这样吗？对着提高戒心的我，天爱星同学以不经意的口吻说：

    「你可以再教我念书吗？」

    ……咦？念书？这样就可以了吗？

    对着戒备落空的我，天爱星同学露出有点尴尬的表情。

    「前几天的考试，结果同样不太好。」

    「我最近成绩也在退步就是了。你不介意的话是可以。」

    「没关系，温水同学的教法简单易懂，对我很有帮助。」

    听她这么说，我当然也不觉得反感。

    但是学生会选举这件事，她真的那么简单就愿意放弃吗……？

    我还无法完全放下怀疑，天爱星同学挪开视线，对我问道：

    「志喜屋学姊传的讯息，你特别设定了铃声吗？就是刚才的玻璃碎裂声。」

    「是啊，不用特别看就知道是谁的联络。事先设定好，很多时候都很方便。」

    比方说若听见小拔老师的铃声，我可以选择刻意忽略讯息。

    我一说完，天爱星同学便开始操作智慧型手机。

    ——叮铃。

    我的手机传出通知音效。

    我看向萤幕，天爱星同学送来了空白的讯息。

    「这是什么？」

    我为她谜样的行动纳闷时，天爱星同学露出感到无趣的表情，将智慧型手机收进书包。

    「我的来讯音效还是预设的铃声啊。」

    「呃，哎，是没错。」

    是怎么了？她心情不知为何突然变差了喔。

    天爱星同学拍了拍裙子，站起身。

    「那么明天星期六，请空出下午的时间。」

    「明天？不会太急了吗？」

    「哎呀，你有其他预定行程吗？」

    预定行程——并没有。

    我摇了摇头后，天爱星同学便盈盈一笑，转身背对我。

    ◇

    当天晚上，我将数学教材陈列在书桌上，双手抱胸俯视桌面。

    明天的读书会，要带什么去呢？全部带去好像太拼命了，稍嫌土气，但要是带得太少，可能不够撑过教学时间。

    教科书与笔记一定不能少，参考书和题库只要带精选的一本就够了吧。

    放进背包里也不会太重，感觉不错。接下来就是挑选服装。

    陈列在床上的是有领子的短袖衬衫、质地较薄的奇诺裤。当然全都没有图案。

    近来因为偶然的不幸频繁发生，有图案的衣物大多都不能穿了，只剩素色的选项。

    「很好，万无一失——」

    「兄长大人，明天要出门吗？」

    妹妹佳树不知何时站在我背后。

    「是啊，到车站附近一趟。」

    「哎呀，要到图书馆念书吗？」

    佳树瞥了一眼背包这么问。

    明天和天爱星同学约在车站前的精文馆书店碰头，然后再移动到读书会会场。

    虽然没有做任何亏心事，但是让佳树发现会很麻烦。嗯，很麻烦。

    「哎，这个嘛，稍微去买点东西。」

    「……要和某位人士开读书会啊。」

    佳树低声嘀咕。

    「咦，不是……」

    「该不会是和女性一起！？难不成是到对方家里的读书会约会！」

    「没有没有，不是那样啦。朋友——对，是跟男生朋友一起念书。」

    佳树听了我的随口搪塞，双眼闪闪发亮地左右摇头。

    「听说樱井学长明天要协助亲戚采收高丽菜。绫野学长要上补习班，兄长大人没有其他会一起念书的男性朋友了。」

    每次提起朋友，佳树总是不留情面。

    「说到我的男性朋友的确只有这两位。为何你知道他们的行程？」

    「前几天马剃学姊来的时候，佳树向她请教了兄长大人的交友关系。果然是和女性开读书会吧！该不会是会长或志喜屋学姊？还是——」

    「好了，不是你想的那样。已经到国中生该睡的时间了喔。」

    「呜～佳树已经是大人了。」

    我将抗议之声当作耳边风，推着佳树的肩膀，把她赶出房间。

    ……真是的，佳树爱凑热闹的个性也真让人伤脑筋。

    奇怪？仔细一想，佳树和绫野应该彼此不认识吧。绫野和天爱星同学也只是点头之交，朝云同学的联络方式也从佳树的手机里删除了——

    「我不知不觉间提到绫野了吗……」

    唉，我自己的记忆也不可靠啊。

    我再度检查了背包的内容物，把忘记放的笔盒塞了进去。

    ◇

    与天爱星同学约好碰面的场所，是丰桥车站前的精文馆书店总店。

    我比指定的时间还要提早抵达，先确认了轻小说与漫画的新书，之后才前往一楼的杂志区。我们约好下午两点在该处碰头。

    「还有点时间啊……」

    我漫无目的地走在流行杂志区时，在眼前见到了熟悉的人影。

    「奇怪，这不是温水吗？」

    「八奈见同学？你在这种地方做什么？」

    没错，正在看免费杂志的就是八奈见杏菜。

    八奈见将她正在读的《吃遍三河》递给我。

    「小白玉找我来的。说有免费餐券，要不要一起去吃甜点自助餐。来，你把杂志打开。」

    「你们两个有熟到会一起出来玩喔？」

    「也没那么熟，但是有甜点自助餐的免费餐券喔？是吃到饱的喔？」

    八奈见抬起手，故作潇洒地撩起头发。

    「小白玉真是个好孩子耶！我一直以来都误会她了。」

    八奈见的信赖，要价甜点自助餐一次。算得上便宜。

    「你一定很期待吧。那我差不多该走了。」

    「这间叫KADOWARA的店，感觉就很好吃吧？拉面里有加白萝卜耶，吃了会不会瘦啊？」

    「也许会吧。那个，我——」

    「淋上甜酱的鹌鹑蛋好像也很美味耶。啊，麻烦翻下一页。」

    ……拜托不要看免费杂志还找人帮你拿书。

    我按照她说的翻页，同时用眼角余光扫视周遭。

    天爱星同学是不是快到了？我们两个要碰面虽然不是秘密，但在这个选举问题悬而未决的时间点被发现，也很麻烦啊……

    我心神不宁地左顾右盼时，八奈见双眼直盯着杂志，低声呢喃：

    「唉，你果然还是想当马剃同学的推荐人？」

    「我好好拒绝了喔。我觉得她已经明白了，应该吧。」

    「是喔～那你从刚才就一直注意着附近，是和谁约好碰面吗？」

    「啊，没有，我只是来逛逛新书——」

    八奈见从我手上拿起杂志，眯眼看向我。

    「……和谁？温水你除了文艺社还有其他朋友？」

    「有啊，比方说绫野和樱井。」

    「你要和那两个人碰面？」

    「呃～这个嘛……」

    不妙，八奈见完全在怀疑我。

    我想逃离八奈见的视线时，一阵芳香轻轻拂过我的鼻间。

    「咦？是社长吗？」

    听见那声音回过头后，便见到白玉学妹身穿白色圆点图样的藏青连身裙站在该处。

    短裙下摆处隐约可见到轮廓优美的膝盖。

    八奈见离开我，突然间就抱住了白玉学妹。

    「小白玉！谢谢你今天邀我一起来！」

    「能和学姊一起，我也很高兴。」

    白玉学妹溜出八奈见的拥抱，神态可爱地朝着我歪着头。

    「社长也要一起去吗？」

    「咦？不，我正好有点事情要忙——虽然没到那么重要，但是不太凑巧。」

    「哎呀呀，被拒绝了呢。」

    白玉学妹开玩笑般这么说，从小巧的手提包中取出两张票。

    「八奈见学姊。我先领之前订的书再过去，可以麻烦你先入场吗？我马上就会过去。」

    「可以是可以，但是我一个人先吃，感觉不太好意思。」

    先吃会不好意思。原来八奈见也有这种情感啊。

    当我感到一阵新鲜的惊讶时，白玉学妹模样可爱地双手合十。

    「不好意思，因为要是比预约时间晚到就会视作取消。不早点过去，最有人气的烤牛肉也许会被吃光喔？」

    「连烤牛肉都有吗！？我知道了，我先过去了喔！」

    不只价格适中还很好讲话，八奈见接过票券后，迫不及待地推开玻璃门，离开了书店。

    白玉学妹轻轻摆着手，目送八奈见离去后，嘻嘻轻笑。

    「学姊这么开心真是太好了。幸好我有急忙准备票券。」

    「咦？不是有免费的票吗？」

    「是这么回事没错。对，正如学长所说。」

    白玉学妹灵巧地转身面向我。

    「我最近和佳树交换了联络方式呢。」

    「和佳树？」

    话题突然转变，令我有些讶异。

    就我所知，两人关系应该不太好。她们之间发生了什么事……？

    「这样啊。你什么时候跟佳树变好的？」

    白玉学妹没有回答这个问题，只是微微一笑。

    「佳树真可爱呢。只要一提到兄长大人，马上就会认真起来。」

    「喔……」

    白玉学妹将双手指头在背后互勾，压低上半身，用那姿势从下方看向我。

    「真～的好可爱。比方说自以为在试探，其实什么都藏不住。毕竟就连碰面的地点都不小心说溜嘴了嘛。」

    「呃～你是在说什么……？」

    「你猜，我是在说什么呢？」

    白玉学妹挺直身子，将视线投向我背后。

    「……哦～原来是副会长啊。」

    「咦？」

    「你不想让八奈见学姊看见吧，不过我是不在意啦。」

    到底是在说什么——不，白玉学妹究竟知道多少？

    「那个，难不成你是知道我在这里——」

    「那我就先走了喔。我也不想当电灯泡。」

    「咦？喔喔，改天见。」

    白玉学妹走过不禁战栗的我身旁时，在我耳畔轻声低语。

    「社长——别看我这样，其实是个方便的女人喔？」

    ◇

    与天爱星同学会合之后，她不知为何一语不发，步伐格外急促。

    自杂志区旁边的玻璃门离开书店，来到常盘通上，自可丽饼店前方的队伍旁边走过，一路走向拱廊商店街的深处。我好不容易追上，走在天爱星同学身旁。

    「那个，你在生气……？」

    「我并没有生气。只是以为你邀那两个人一起来念书，有点吃惊罢了。」

    「我没有告诉任何人啦。刚才是单纯被缠上而已。」

    天爱星同学默默点头，背对商店街边缘处的巧克力店，走过转角。

    又走了好一段时间，她这才放心似地用手按着胸口，吐出一口气。

    「呼……都到这里了，应该不用担心了吧。」

    「咦，担心什么？」

    「因为那一带很容易被人注意到。最近周遭有些喧闹。」

    天爱星同学扫视周围，向我跨出一步。

    「……温水同学，你知道赏鸟会吗？」

    「就是贩卖偷拍照，被废社的社团吧。」

    「正确来说是无期限的假废社。但是由于会长帮忙求情，学校允许他们以新闻社的名义继续活动。」

    「我们学校有新闻社吗？」

    「没有。所以会长原本是一片好心，希望他们作为新闻社为石蕗有所贡献，借此重启赏鸟会……」

    赏鸟会真有必要这么大费周章地留存下来吗？

    「所以，那个新闻社怎么了？」

    「他们开始做些模仿八卦杂志的行径，频频跟踪和选举有关的人。同好会不在学生会的管辖范围内，没办法干涉。」

    天爱星同学按着额头叹息。

    同样身为爱鸟人士，我也想道歉，但是那些家伙们喜欢的八成不是鸟类。

    我与天爱星同学并肩而行，同时观察四周。

    一旦从广小路通走出拱廊商店街的北端，路上行人便骤然变少。

    话虽如此，也不算冷清，过去想必有商店与事务所并排的街道上，仍留有当初的氛围，现在是一整排住宅。

    其中也包含保留了商店氛围的建筑物，以及依然继续营业的店家。

    建筑物之中也有几间新开张的餐饮店，街道在平缓的步调中转变的过程呈现于眼前。

    天爱星同学的步伐不带一丝迟疑，她大概对这一带很熟吧。

    「马剃同学，读书会地点在哪？」

    「哎呀，抱歉，我没有说明。我们正前往我家，因为就在这附近。」

    哦，原来天爱星同学的家就在这附近啊。要在那边开读书会……在天爱星同学家……

    「唉！？要去你家喔？现在就去？」

    「我爸妈都出门了，请别介意——啊，我不是那种意思喔！？我弟弟在家，请你别打歪主意！况且——」

    天爱星同学面红耳赤地补充说明：

    「我弟弟有女朋友了！」

    这是想强调什么？

    不过，虽然有家人在，但是进入异性的家里这种事真的可以吗……？

    换作是恋爱喜剧肯定有事件要发生，而若是成人游戏的世界，那可是大量获取剧情图的机会喔。

    「不，但如果是为了集满相簿的话……？」

    「温水同学，你从刚才就一直在嘀咕什么？」

    啊，不妙。一个不注意就栽进大人的世界了。

    我回过神来扫视周遭，这地方让我觉得眼熟。这地面的石砖是……

    「这里是花园町附近？」

    「对，你知道啊？」

    「我常来这前面的超商，偶尔会经过。」

    这一带都是老旧的商店街。

    虽说是商店街，但大多数店门都铁卷门深锁，有在营业的店家年年减少。

    其中一栋崭新的高大建筑物映入眼中。

    「这里以前就有这栋公寓吗？」

    正要经过建筑前方的天爱星同学停下脚步，抬头仰望建筑物。

    「最近盖好的。原本住在这里的居民们都搬走了。」

    「哦～是这样啊。」

    「听说一直到我祖父母那一辈，这条商店街也很热闹。不过，这是也没办法的事。」

    她以没有起伏的语调说完，再度迈开步伐，走过转角。

    「我家就在前面——」

    「哎呀，这不是天爱星妹妹吗！」

    一位体态发福的大婶的声音，轻易地盖过天爱星同学的话。

    天爱星同学迟疑了一瞬间，然后低下头行礼。

    「道重女士，您好。」

    「哎呀，是怎么了？平常明明都喊我婶婶的，怎么客套起来了。」

    「没有啦，那个……」

    「婶婶好寂寞喔～天爱星妹妹都长得这么亭亭玉立……了……？」

    道重大婶似乎是这时才注意到我，她睁圆了眼睛。

    「哎呀～哎呀哎呀！天爱星妹妹？哎哟～」

    「您、您误会了！」

    「嗯嗯，婶婶明白，只是误会吧。婶婶也有过这种时期喔？和孩子的爹不是同一个人。要保密喔。」

    「真、真的不是那样啦！？」

    「婶婶明白，婶婶明白得很。不好意思，打扰你们了啊。」

    摆出一副毋需多言的态度，道重大婶连连点头，笑着走过我们身边。

    不知为何对我竖起了大拇指，然后——

    「天爱星妹妹也即将要——成为大人了吧？哎呀哎呀……」

    邻居大婶的破坏力，会让天爱星同学不禁双手掩面、浑身颤抖，也是人之常情。

    ……八奈见将来也会变成那样吗？

    ◇

    马剃家就在道重夫人遭遇现场的不远处，是一栋面对道路的三楼透天民宅。

    一楼部分以前或许是店铺，面向道路的那一侧是玻璃。

    天爱星同学拉开玻璃门后，先走进屋内，并对我招手。

    走进去一看，店铺部分光线昏暗，四周的架子上堆满了服装箱与纸箱。

    「不好意思，家里很乱。」

    天爱星同学害臊地说着，走向房间深处。

    「不会啦。这里以前是什么店？」

    「到我祖父那一辈，做的是徽章的生意。」

    「徽章？」

    「这个嘛，比方说胸章、奖杯、旗帜————这一类的商品。因为赢不了竞争对手，最后关店了。」

    哦，也有这种生意啊。

    「啊，所以天爱星同学才会在制服上戴名牌啊。」

    「不，因为那是校规。还有请不要用名字称呼我。」

    天爱星同学轻描淡写地带过这话题，推开店内深处的门。

    门后方是脱鞋用的空间，更里头是架高一阶的居住空间。

    进入居住空间，右手边便是通往二楼的阶梯。正面则是客厅。

    「我房间在三楼。鞋子到那边再脱。」

    「啊，好的。我会这么做的。」

    ……我不由得用了敬语。

    充满生活感的女生家，而且是不怎么熟识的对象，反倒令我更加好奇。

    踩着颇陡的楼梯来到三楼后，走廊上并排着两扇门。

    「贵司——你书包记得要收好。」

    天爱星同学如此喊道，经过第一扇门前。

    在家里就是个真正的姊姊啊。然后弟弟，幸好你有个普通的名字呢。

    「虽然我房间没什么意思，请进。」

    天爱星同学有些迟疑地请我进入她的房间，是个铺榻榻米的三坪房间。

    一眼能注意到的家具是床铺、书桌、书架和矮桌。传统风格的简单和室。

    就高中女生的房间而言虽然朴素，但是铺在矮桌下方的防滑垫和窗帘都是淡粉红色让人眼睛一亮。

    平淡之中隐隐约约透出不起眼的少女心，成了绝佳的点缀。

    「请坐在那边的坐垫上。」

    「啊，好的。」

    我动作僵硬，在坐垫上跪坐。

    紧张也是人之常情，毕竟我是第一次进入『女生的房间』。

    小鞠是和弟妹同房，而且当时事态紧急，我认为不算数。

    天爱星同学轻巧地坐在我对面，静不下心似地伸手拨弄浏海。

    「那、那么，我们开始吧？」

    「喔、喔喔……就这么办。」

    明明只是要念书，这气氛是怎么回事？

    我们沉默不语，慢吞吞地取出教科书。

    「这个……今天一样可以麻烦你教我数学吗？我对数列实在不太行。」

    「正好，这部分我也不太行。」

    我随便回答后，天爱星嘻嘻笑了起来。

    「一点也不正好啊。那我们就一起努力吧。」

    虽然不太明白，不过似乎过关了。我在心中松了口气，翻开教科书。

    「话说回来，之前的考试结果怎么样？」

    「该说各科都呈现了改善的空间吧？状况没有分数那么糟糕。」

    天爱星同学握紧了拳头。嗯，积极正面是好事。

    ——读书会开始后大概过了三十分钟。

    我对完答案抬起头，便见到天爱星同学一脸认真地在解题库。

    盘起的头发与粗眉毛，颈子上的痣清晰地浮现在白皙的肌肤上。

    脸庞出乎意料地小，乍看之下没有化妆，但在周末有稍加用心打扮——

    「……我的脸上沾到什么了吗？」

    天爱星同学不知何时已经抬起脸，狐疑地歪着头。

    「啊～不，没什么，只是觉得有点好奇而已……」

    我口齿不清地支吾其词。天爱星同学上半身向前倾，神情愉快地追问。

    「咦？在意什么？我很好奇这点。」

    「啊～没有啦——只是想说，原来真的不是想邀我进学生会。」

    笑容倏地自天爱星同学脸上消失。

    ……我自己也觉得这回答不行。

    「照情况而定，我原本有这个打算。只要带进家里，接下来就任我摆布了。」

    天爱星同学的口吻分不出是开玩笑还是认真的。

    奇怪，视情况而定的意思是……

    「……所以你现在没有这个打算了？」

    「其实参选会长的申请已经在昨天截止了。而且到了傍晚，也只有我一个人申请参选。」

    她的脸上透出几分坦白自己的恶作剧似的神色。

    「咦？所以没有要办会长选举啊。」

    「是啊。只有发表政见和信任投票，也没有声援演讲。」

    既然这样，过去这段时间的骚动算什么啊？

    话说回来，我们不是昨天才在桌游咖啡厅见过面吗……？

    「昨天傍晚，你为何不告诉我？」

    「对不起。严格来说在换日之前都不算确定，所以我来不及说。」

    是这样啊。比起生气，我更松了口气，不由得放缓嘴角。

    「……哎呀，该不会你稍微起了想帮忙的念头？」

    「是啊，我正好觉得如果只是帮忙选举，倒也无妨。」

    「呵呵，现在你要怎么放马后炮都没差了。」

    「反正也只是说说而已。」

    听了我不负责任的话，天爱星同学开心地笑了。这个人会这样笑啊……

    我们对彼此笑了好半晌后，天爱星同学擦去眼角泪光，说道：

    「万一真的有需要，我还准备了一个能说服温水同学的最终手段，不过现在没必要了呢。」

    「最终手段是什么？」

    「哎，其实也没什么好玩的就是了。」

    天爱星同学笑着蒙混过去。

    ……等等喔。我这次确实是被天爱星同学拿小奇卡的促销周边当钓饵叫过来的。

    既然这样，所谓的最终手段就是——

    「那个，可以给我看看吗？」

    「咦？可是……」

    见到我显露兴趣，天爱星同学不由得迟疑起来。

    看这反应，肯定是非常罕见的收藏品。

    「天爱星同学的最终手段，我真的很想知道。」

    「那个，可是喔，那也不是值得特别展示出来的东西……」

    「没这回事。我会当成只属于我和天爱星同学的秘密，不告诉任何人的。」

    「秘、秘密……！」

    我的热情似乎说动了她。天爱星同学嘴唇缓缓颤动，抬眼看向我，点了点头。

    「这个嘛……虽然我不晓得能不能满足你的期待。」

    天爱星同学从书桌抽屉中取出了某物，就这么藏在身后，重新回来坐下。

    看来应该不是尺寸多大的周边。是压克力立牌之类的吧？

    在我的屏息守候之下——

    「那么我就豁出去了！」

    天爱星同学将那样东西，缓缓戴到头顶上。

    然后双手摆出猫一般的姿势，用可爱的口吻说：

    「请为我打气喵。」

    （插图011）

    …………

    ………………你突然是怎么了，天爱星同学？

    眼前的天爱星同学戴在头顶上的是——猫耳发箍。

    她突然间猛踩油门，让我不禁愣住，这时天爱星同学一张脸红到了脖子。

    「唉……？不是，你不要误会！那个，我只是想说温水同学也许喜欢这种的，我自己没有那种嗜好！」

    「咦、不，我是喜欢没错——」

    「你喜欢吗！？」

    天爱星同学激动呐喊的瞬间——

    啪嗒，房门突然间开启。

    「姊姊，我出门一下——」

    「贵司！？」

    现身的是身穿橘色体育服的清爽少年，年纪大概和佳树相仿。

    少年见到姊姊的模样，愣了半晌，最后似乎决定当作没看见。

    他对我低头行礼。

    「啊～……欢迎来玩。我是她弟弟。」

    「啊，不好意思到府上打扰了。我叫温水。」

    尴尬的气氛再度充斥房内。

    马剃弟弟用复杂的表情注视着姊姊，随后再度低下头。

    「呃……我吃过晚餐才会回来。那个，请随意。」

    砰。房门关上，下楼梯的急促脚步声传来。

    定住的天爱星同学有如没上油的机器，脸庞僵硬地转向我。

    「温水同学……怎么办？」

    怎么办？我也不晓得。

    天爱星同学的脸庞直到刚才还一片通红，现在已经转为惨白。

    我为了让心灵镇定而深呼吸，接着开口：

    「呃，你弟弟视力好吗？」

    「不晓得……他提过最近视力有点变差了。」

    这就对了。我大大地点头。

    「搞不好他根本没看见天爱星同学的猫耳吧。」

    「咦？有这种可能吗？」

    「你仔细想像一下。亲姊姊戴上猫耳，对陌生的男生说『喵』喔？」

    「咕！」

    天爱星同学按住胸口发出呻吟。还没完，你再多忍耐一下。

    「照理来说，就连保持平常心都不可能。但是你弟弟看起来神态自若吧？」

    「……是吗？我第一次见到弟弟露出那种表情喔。」

    「不，他神态自若。不会错。既然这样，就能反过来推论，你弟弟并没有看见猫耳。只有这种可能性。」

    天爱星同学惨白的脸庞渐渐恢复了血色。很好，只差一点了。

    「那『喵』呢？『喵』也没听见吗？」

    「是啊，当然没听见。开门时的声音正好呈现反相位，彼此抵消了。我在物理课上学过了，不会错。」

    「原来如此……因为我选修的是生物，没有注意到。」

    真巧，我也是选修生物。

    天爱星同学似乎听信了我的随口胡诌。

    她从头上摘下猫耳，放心了似地吐气。

    「说的也是，我稍微冷静下来了。不好意思，刚才陷入混乱。」

    「没事，你明白就好。一切都不用担心。」

    还有，天爱星同学，你最好再多怀疑别人一点。

    「……你说的对。话说回来，请不要从刚才就一直用名字称呼我。」

    因为天爱星同学被骗更正，因为她接受我的说法了，事情顺利收场。

    接下来只要平安结束读书会，拿到小奇卡的周边即可。

    她弟弟出门了，也不会导致无谓的误会——

    奇怪？双亲本来就不在家，现在弟弟也外出了。所以说这就是——

    「两人独处……？」

    「什么！？」

    不妙，脱口而出了喔。天爱星同学弹跳似地猛然站起来。

    「你突然在说什么啊！？」

    「不不不，我没有奇怪的意思。你要知道，男生来到女生的房间，男生这一方也得操心。万一旁人投以奇怪的眼光，也会给对方带来麻烦。」

    听了我诚挚的说明，天爱星同学维持着戒心，缓缓回到坐垫上。

    「没、没事，唯有温水同学是不可能出差错的嘛。毕竟我是女的。」

    相信我吧。虽然最后说了奇怪的话。

    「那个，我的恋爱对象并不是同性。」

    「是的，我明白。该不会你以为我无法分辨妄想与现实？」

    嗯，我这么认为。

    天爱星同学见到我的表情，假咳一声清嗓子。

    「哎，虽然的确有过一段无法分辨的时期。」

    「还真的有过啊。」

    「作为对策，我最近会将心里想的事情写成文章。」

    「文章是指日记之类的？」

    天爱星同学点头后，手指抵着眉心开始沉思。

    「比方说……在我心中温水同学是鬼畜攻，而会长是男生也是受，对吧？」

    我要怎么回答？天爱星同学一脸认真地继续说明：

    「但是，我把这句话也写成文章，隔几天重读一次，就会觉得『不可能是这样』，就能分辨妄想与现实了。这也是一种认知疗法吧？」

    我反而想问，必须等待几天才能分辨吗？症状比想像中还严重。

    天爱星同学的表情有几分得意，她打开题库本。

    「所以你大可放心，我有好好地正视现实。会长是女性，而温水同学是喜好女色的鬼畜攻。」

    还有一些妄想残留喔。

    一边哼歌一边解题的天爱星同学手突然停了下来。

    「……我刚才说了什么奇怪的话吗？」

    「别担心，一如往常。」

    「就、就是说嘛！温水同学喜欢的是女性，是鬼畜攻……毫无……操守……」

    天爱星同学的表情一瞬间变得开朗，马上又急遽变化。

    「这、这个，我那个，虽然是女生，但不是那种想入非非的对象。」

    「啊啊，嗯，没错，马剃同学不是那种对象。」

    「不是吗！？」

    咦咦……我该怎么回答才行啊。

    哎，不过年轻女生轻易让男生来家里的确危险。

    我是个诚实的男人才没关系，换作是坏男人，至少也会摸一下腿。

    我清了清嗓子，正色面对天爱星同学。

    「这个嘛，马剃同学，所谓的男人，是种容易误会的生物。」

    「误会？」

    「对。男人在女生家里两人独处，就会擅自心生误会——以为对方在诱惑自己。」

    「咿！？」

    坐在榻榻米上的天爱星同学连连向后退。

    「今天是我所以没关系，但换作是其他男人——」

    「咦？那、那个……」

    天爱星同学的双手握紧在胸前，身子频频颤抖。奇怪，我是不是说过头了？

    面对心生不安的我，天爱星同学那颤抖的嘴唇轻声说了：

    「你、你想要吗……？」

    「咦？要什么？」

    听了我的疑问，天爱星同学的脸庞变得一片通红。

    「还会是什么，就是那个——等等，你想让我说什么啊！？」

    那个究竟是指哪个？我无奈地想反问的瞬间，天爱星同学的智慧型手机响了。

    「电、电话！我接个电话喔！」

    天爱星同学站起身，把智慧型手机贴到耳畔。

    「……老师？在星期六联络真是辛苦您了。啊，是，可以。」

    天爱星同学一边讲电话，一边走到走廊上。

    从走廊上传来的话语声听起来十分凝重，是不是考不及格了？

    ……话说回来，这个人还是老样子怪怪的。

    为了请我当推荐人就把我带到家里，还戴上猫耳。

    到头来其实没这个必要，完全是白费工夫。

    既然这样，本来就用不着在天爱星同学家开读书会吧……？

    喀嚓。开门声打断了我的思索。

    回到房间的天爱星同学脸色铁青。

    「发生什么事了吗？」

    天爱星同学伸手按着胸口，深呼吸后，以认真的口吻说：

    「老师说，在昨天晚上即将截止的关头，收到了学生会会长的参选申请。」

    这表示……不是信任投票，还是要举办选举吗？

    我为此吃惊时，天爱星同学冲向我似地坐到我面前。

    「温水同学，你刚才说过了吧！？你说愿意帮忙我打选战！」

    「咦，这种话——」

    我也许说了。汗水自额头渗出。

    「不，等一下，虽然我的确有说，那句话是那个意思没错，但不是那种意思——」

    「拜托你！只靠我一个人，没有自信能赢过他！」

    话虽如此，找我当友军也改变不了什么喔。

    ……刚才天爱星同学说了他？

    「申请参选的是谁？我认识的人？」

    天爱星同学缓缓点头，开口说：

    「——樱井弘人。学生会会计樱井。」

    「！？不，可是樱井说过他没那个打算……」

    如果这是真的，我看不到天爱星同学胜选的未来。况且我也会投票给樱井喔。

    见到哑口无言的我，天爱星同学取出的是——猫耳发箍。

    她缓缓地戴到头顶上，以颤抖的话语声开口：

    「请、请陪我一起打选战……喵。」

    天爱星同学在颤抖中摆出了招财猫的姿势。

    呃……这下到底该怎么办才好？喵。

** Intermission 最宝贵的回忆

    放学后的学生会室。

    学生会长放虎原云雀用拧干的抹布，仔细地擦拭着自己的桌子。

    方才在整理书架的会计樱井弘人转过头来，嘴角浮现笑意。

    「任期还有一个月，也太急了吧。」

    「到了离开前夕才急忙开始收拾，不符我的个性。所谓的敬意是日积月累的。」

    放虎原回答后，用水桶中的水清洗抹布。

    注意到樱井担心的视线，她耸了耸肩像是要他不要操心。

    「我也从之前的学长姊那边继承了许许多多的事物，交棒给下一届就是我的职责。」

    她再度用力拧干抹布，接着开始擦拭椅子。

    「云雀姊在学生会待了两年，想必有很多回忆吧。」

    放虎原怀念地笑了笑。

    「是啊，上一届会长是个罕见的奇人。甚至不下古都学姊。」

    「幸好我今年才进来。」

    樱井说完笑了笑，表情忽地转为严肃。

    「梦子学姊没问题吗？好像又惹马剃生气了。」

    「别担心，这证明她们感情很好。在马剃面前，志喜屋总是生气十足。」

    副会长马剃天爱星。她已经申请参选下届学生会长。

    现在没有其他候选人，只要过了信任投票这关，就是下届学生会长了。

    放虎原云雀卸任后，自己就不会再参与学生会事务。樱井已经如此决定。

    没有她在的学生会，他没有兴趣——

    樱井在心中再度确认后，面露一如往常的平稳微笑。

    往那边一看，放虎原大概是用抹布打扫得满意了。

    她将抹布挂在水桶边缘，仔细打量桌面。

    「对了，趁我还记得，先给你吧。」

    放虎原拿起一册档案。

    「未决事项我都整理好了。调整预算的会议每年都会吵架，要先做好心理准备。」

    樱井看向递到自己眼前的资料，感到疑惑般摇了摇头。

    「云雀姊，我不会留在学生会喔。」

    「……说的也是。不好意思，太习惯了。」

    放虎原苦笑着，抚过档案夹的表面。

    「我总有种弘人会接手的错觉。虽然我早就明白了。」

    放虎原凝视着手中好一段时间，随后像是要甩开什么般，将档案放回桌面上。

    「好了，今天就到此为止吧。弘人，有什么我能帮上忙的吗？」

    她说着，握住了水桶的提手。

    下一个瞬间，提手发出声音并松脱。

    「云雀姊——」

    在手伸到一半的樱井面前，放虎原灵敏地用空着的手抓住水桶的边缘。

    两人都松了口气。

    「我也不会老是麻烦你照顾。」

    「是啊，感觉放下了肩上的重担。」

    「想必变轻了很多吧。」

    两人相视而笑。

    这时，樱井的智慧型手机响了起来。樱井看向萤幕，脸上笑容消失。

    「……是小春吧？别顾虑我，尽管接电话吧。」

    樱井看着萤幕好半晌后，直接将智慧型手机翻面，摆在桌上。

    「之后我再打回去。在这个时间打来，不会是什么急事。」

    他以平板的语气说完，走向放虎原的桌子。

    「云雀姊，刚才的档案给我看一下。」

    「怎么了，有什么在意的吗？」

    放虎原递出的档案。

    他注意到自己的视线下意识地无法从那上面挪开。

    所以樱井彷佛做好了某种决心，以认真的表情伸出手。

    「——是啊，我稍微有点兴趣了。」

** ～第二败～肩膀随着重量摇摆

    周末过去。星期一的课程结束，只剩班会时间。

    2年C班的班导师甘夏古奈美扫视我们之后，使劲一拍讲桌。

    「你们听好——所谓的六月新娘就是陷阱。」

    ……又开始了。

    升上二年级后过了两个月，班上同学们也渐渐习惯了甘夏风格。

    当这个人开始胡闹时，只要想着天气的事情并保持安静就好。

    「那些家伙们，就是想抢我的夏季奖金。你们知道吗？二十八岁就是周遭旁人接二连三开始结婚的年纪。这个嘛，简单说明的话——」

    甘夏老师用粉笔在黑板上开始画图。

    「高中毕业之后，就职组在两到三年就会迎来第一次结婚高峰期。哎，就是年轻可爱的新娘子。然后升学组大多会因为搬家等等使人际关系一度归零，所以在毕业后五到六年那个就会到来……！」

    她在黑板上潦草地写下『第二次结婚高峰期！』几个大字，转身面对我们。

    「你们听好了，接下来才是真正的地狱！」

    砰砰砰！甘夏老师激动地拍打黑板。

    「过去互相舔舐伤口的战友，不知不觉间就会成为敌人！嘴巴上说什么古奈美很可爱，很简单就能找到对象喔～真的简单就找一个来给我瞧瞧啊！很简单不是吗！？」

    甘夏古奈美，二十八岁。发自灵魂的呐喊。

    很遗憾平均年龄十六岁的2年C班反应平淡。

    我任凭甘夏剧场左耳进右耳出，视线投向樱井的背影。

    不知怎地有些尴尬，还没向他提起选举的话题。

    突如其来参选，究竟是何种心境变化呢？和他好好谈过会比较好吧……

    「六月每个周末都有婚礼，太奇怪了吧……？最近小拔也愈来愈难约，今年老家也不再寄相亲照片来了。虽然我说过要自己找，但是也体谅一下女儿强撑面子的心情……」

    今天的抱怨比平常还长。

    六月在即，尚未现身的新娘们正侵蚀着甘夏老师的心灵。

    「要是发现大好机会来了，劝你们一定要顺势而为……啊～有什么联络事项吗？」

    甘夏老师随手翻动手边的手册，最后欠缺干劲地挥了挥手。

    「听好了，你们可不要满脑子都是谈情说爱啊。那么今天就下课了～」

    甘夏老师又使劲拍了一次讲桌，同学们纷纷应声起立。

    那么，我得先逮到樱井才行。

    在我站起身之前，教室门已经飞快打开。

    闯进教室里的是——天爱星同学。她笔直地走向我，将一叠纸张沉重地摆到桌上。

    「温水同学，星期六那件事我们还没谈完。」

    「……你是指哪件事？」

    我不禁如此回应，天爱星同学的上半身逼向我。

    「在我房间谈的那件事！你该不会忘了吧？你都让我打扮成那样了！」

    「那是马剃同学你自己——不对，这里不太方便，要不要换个地方！？」

    这种对话会导致旁人误会。不，其实不全然是误会，这一点更糟糕。

    我战战兢兢地扫视周遭，便发现八奈见与小鞠、甚至连姬宫同学都对我投出恐怖的视线。话说甘夏老师为何要拍我的照片……？

    天爱星同学一眼瞥向樱井，清了清嗓子。

    「说的也是。看来还是换个地方谈比较好。先到能两人独处的场所吧。」

    嗯，没错。但是讲法还是希望你能考虑一下。

    ◇

    石蕗高中的中庭设有石制的大桌子与椅子。

    我按照指示坐下后，天爱星同学开始在桌面上陈列文件。

    「马上来谈选举的事情吧，投票一星期前要公告政见。在那之前是准备期，候选人可以去听取学生的意见——」

    天爱星同学飞快接连说道。

    经过附近的联络走廊的学生们，纷纷向我们投出疑惑的视线。

    「……那个，天爱星同学，这里不会很醒目吗？」

    「有一段距离，其他人听不见的。还有请不要用名字称呼我。」

    天爱星同学轻描淡写地说完，翻动纸张。

    「事先能做的准备我都想做好，也得让温水同学瞭解学生会才行。不好意思，这阵子可以麻烦你放学后空出时间吗？」

    「那个，稍等一下。」

    「啊，不好意思，我自己一个人说个不停。温水同学，请说。」

    天爱星同学面露羞赧的笑容。

    「那个，有关学生会选举的事情……」

    「是的！」

    不知为何天爱星同学用充满期待的眼神注视我。

    我挪开视线，继续说：

    「我本来就有文艺社的活动，那个……可能还是没办法投入那么多时间。」

    「可是在我房间——」

    天爱星同学说到一半，后半段的话语消失。

    沉默了好一段时间之后，天爱星同学收拾了摊在桌面上的文件，站起身。

    「说、说的也是，温水同学也有文艺社要顾。」

    用有些颤抖的声音说着。

    「不好意思，我把客套话当真了。没问题的，我会一个人设法解决。明天起制服就要换季了，请多留意喔。」

    天爱星同学连忙把文件塞进书包里，就要离开这里。

    「——等一下。」

    抢在思考之前我已经站起身，抓住了天爱星同学的手。

    「温水同学……？」

    「虽然没办法当推荐人，但是那个……只是在找到替代人选之前帮忙的话——」

    这大概是同情或自我狡辩，绝非正面的感情。

    我自己也察觉了，我伸出的手发自半吊子的心情——

    「可是，会给温水同学造成麻烦。」

    「学生会的各位也帮过我不少次。在这种时候，我也该回报一下。」

    天爱星同学被抓住的手上渐渐失去力道。

    「……在这里的不是学生会，而是我。」

    「什么意思？」

    我不禁发问，天爱星同学对我缓缓地左右摇头。

    「没事。温水同学与樱井也很要好，偏袒我以后不会尴尬吗？」

    「我想应该没关系吧。那家伙有很多朋友，我想他不会介意。」

    「我也有朋友啊。」

    天爱星同学低声吐槽后，重振精神似地轻轻一笑。

    「帮大忙了，我没有其他比较熟的男生。」

    「我熟的男生也很少啦。」

    「熟识的异性比较多，我觉得不太对就是了。」

    再次的打趣，让两人间的气氛转为和缓的瞬间——

    「马剃学姊，请喝茶。」

    「「！？」」

    保温瓶的杯子被递到天爱星同学面前。

    在杯子冒出的水气另一侧，白玉学妹盈盈一笑。

    「白玉学妹！？」

    「咦？为什么你会在这里……」

    「我在联络走廊上远远看见了。而且我想说两位牵着手，应该是觉得冷吧？」

    「你、你误会了！是温水同学硬抓着我！」

    说得太难听了。天爱星同学慌张甩开我的手。

    白玉学妹仰头喝光了无处可去的茶水后，表示理解似地点头。

    「那么社长你这边决定要帮马剃学姊了吧。」

    「你都听见了啊——等等，我这边是什么意思？」

    我反问后，白玉学妹模样可爱地歪过头，说道：

    「社长还不晓得吗？樱井学长的推荐人，是八奈见学姊喔。」

    ◇

    隔天，星期二的第一节课是运动会的练习。

    当天有班际对抗的啦啦队竞赛，不过参加与否是志愿制。

    当然我没有意愿，因此我倚着操场角落的树，愣愣眺望着练习的风景。

    志愿参加啦啦队竞赛的成员中有八奈见与姬宫同学，男生则包含了绫野与樱井他们。

    正式上场时，男生会穿立领制服，女生则会换上啦啦队的打扮，不过姬宫同学穿成那样不会出问题吗？难免要蹦蹦跳跳的说……

    就在我思考着惯性法则时，练习似乎结束了。

    音乐停止播放，啦啦队的众人各自散开。

    我不经意地投出视线，樱井正与班上女生有说有笑。

    上课时与女生闲聊，真不愧是阳角。而且还借到了毛巾。

    「樱井果然很受欢迎啊。」

    「哎，是没错。不过温水也不输给他喔。」

    绫野光希这么说着，来到我身边。

    他沿着我的视线看过去，纳闷地说：

    「你和樱井出了什么事吗？从昨天就感觉特别见外耶。」

    「也不是那样啦，只是有些在意的事情而已。」

    「……原来如此，我懂了。」

    绫野的眼镜发出一道闪光。他绝对没搞懂。

    「温水——你终于有了喜欢的对象啊。」

    「不，不是。」

    我就知道你没搞懂。

    「不是吗？昨天你和马剃同学好像有些事吧？」

    「我会跟马剃同学来往只是情势所逼，或者该说是交易对象之类的。」

    仔细一想，我还没拿到小奇卡的周边。

    只有天爱星同学的猫耳扮相，怎么算都不够啊。

    「如果不是马剃同学的话——」

    眼镜再度闪亮发光。

    「咦？什么？」

    「……温水，加油吧。」

    绫野意有所指般竖起大拇指，默默地离开我身旁。

    到底是怎样？算了，绫野有时候本来就有点少根筋……

    我迳自如此解释时——

    「不可以偷懒喔，温水。」

    这回来到我面前的是八奈见，她笑得洋洋得意，举起双手摆出姿势。

    「你看，我的打扮怎么样？」

    「呃，是食蚁兽的威吓姿势……？」

    「不是。你对我的啦啦队打扮没有什么感想吗？」

    「八奈见同学，但你现在穿的是体操服。」

    听了我理所当然的回答，八奈见无奈地耸肩。

    「温水你问题就出在这里啦。你听说我要参加啦啦队竞赛，一定想像了我穿啦啦队服的样子了吧？」

    「不，没有。」

    「你可以想像一下喔？」

    咦……我现在很累，不想为了无谓的事情动脑啊。

    这个嘛，八奈见的啦啦队装扮啊。手拿着彩球，头发会绑在后面吧。

    裙摆偏短，胸围稍微有点紧绷——

    「啊，小腹会露出来，你最好当心点喔。」

    「你是在想像什么啦！？」

    「八奈见同学的——不，当我没说。」

    八奈见傻眼地摆了摆手。

    「唉，我是看温水你从早上就郁郁寡欢，才特地来关心你的耶？」

    所以才有刚才的交流吗？麻烦你多用心一点。

    「那个啊……八奈见同学，你要当樱井的推荐人吧？」

    「哦～你在意啊？」

    八奈见的声音紧接而来，我有种心情被看穿的感觉，转移视线。

    「八奈见同学出乎意料地会怯场，我是担心你声援演讲行不行。」

    「我已经不是那时的我了。况且，不管我和温水哪一边赢了，文艺社都会出一位副社长，这不是很好吗？」

    「八奈见同学打算当副会长喔？」

    对着吃惊的我，八奈见理所当然般地点头。

    「因为月之木学姊以前也同时加入学生会和文艺社啊。一定可以吧。」

    「也许是可以啦……」

    八奈见的视线快速扫过周遭，接着压低声音说：

    「——说穿了就是权力。」

    权力？我愣住时，八奈见表情嚣张地继续说明：

    「冰箱这种梦想太渺小了，我要把系统厨具搬进文艺社，两边都能站人的那种。」

    「学生会的权力没有那么大喔？」

    原来八奈见有进学生会的想法啊……

    我没来由地沉默时，八奈见悄悄用肩膀撞了我一下。

    「唉，你跟马剃同学发生了什么事吗？」

    「什么事也没有啊。」

    「之前明明还提不起劲，昨天莫名其妙就亲热起来了嘛。」

    「没有啊？」

    我如此断言，八奈见从下方直盯着我瞧。

    「你去了马剃同学的家吧？」

    「我没去——」

    不，我去了。天爱星同学戴上了猫耳。见到我语带踌躇，八奈见挑起单边眉毛。

    「什么？真的假的？你中了美人计？」

    「不，不是。只是和她用动画周边当交换条件而已。」

    「动画周边……？」

    八奈见的脑中开始议论时，一道娇小的身影走向她。

    「八、八奈见，差不多，又要开始练习了。」

    走来向她搭话的是小鞠。她提着一台老旧的CD播放器，感觉很沉重。

    「啊，小鞠，你借到电池啦。」

    「体、体育教师室，好恐怖……」

    小鞠泪眼汪汪地连续点头。奇怪，既然小鞠手中提着那个——

    「该不会小鞠，你也志愿参加啦啦队竞赛？」

    「我、我负责的是放音乐，还有拍照。」

    不知为何小鞠满脸得意。

    「只、只要参加了啦啦队竞赛，其他个人竞技，就不用参加了。」

    是这样啊。真好，我还得参加一点都不想跑的障碍竞赛。

    「那我们走吧，小鞠。话说你想不想上场当啦啦队？」

    「不、不想。」

    八奈见的手伸向播放器的提手，与小鞠两个人一起提着机器，走向操场。

    ……勉强蒙混过关了。

    当然了，并非有什么需要蒙混的事情。

    虽然没有，但是在天爱星同学的房间享受猫耳游戏，以及于心不忍才决定要帮忙，这些事情坦白说出口也只会招惹误会。

    我在脑海中找借口时，不知为何八奈见与小鞠停下脚步，转过头来，侧眼盯着我瞧。

    「……怎么了？」

    我胆颤心惊地询问后，两人回以挑衅般的口吻放话道：

    「我们堂堂正正地对决吧，温水。」

    「花、花心大萝卜。」

    （插图012）

    ……讲得真是难听。

    为了逃离经过的同班同学的好奇视线，我抬头仰望蓝天。

    ◇

    两天后的放学后，选战终于正式开打了。

    我与天爱星同学并肩走过走廊，同时翻动拿在手中的纸张。

    「呃，接下来是拜访美术社。三十分钟后和垒球社约好了，把移动时间也算进去，二十分钟就要结束。」

    「我知道了。我认识美术社的副社长，事先问过大致状况。」

    天爱星同学加快步伐走上楼梯，我紧跟在她身后。

    ……我之前完全看轻了学生会长选举的准备。

    我原本以为顶多就是帮忙准备传单，没想到要像真正的选举般四处拜票。

    「唉，直接去拜托其他学生投票，这不算违反规定吗？」

    「听取选民的意见并没有违规。我已经向老师确认过了。」

    天爱星同学走上楼梯后，瞥了手表一眼。

    「看来应该能准时抵达。」

    「不，这条走廊比想像中还长。得再稍微加快脚步，不然赶不上约好的时间。」

    「为什么你知道得这么详细？」

    这还用说。是为了打发下课时间，苦心钻研的结果。

    我无言地微笑后，加快脚步追过天爱星同学。

    ◇

    结束与垒球社面谈的回程途中，天爱星同学在体育馆前方停下脚步。

    「怎么了？今天预定的行程结束了吧。」

    「没有，只是想到男子篮球队应该正在练习。因为迟迟约不到队长，我想直接去拜托他。」

    我在天爱星同学身旁一起脱鞋，一边提出单纯的疑问。

    「约不到？原来男子篮球队有这么忙喔。」

    「被经纪人挡住了，不给我机会见队长。对方好像以为我企图亲近男生……」

    天爱星同学叹息道。男生社团中篮球队和足球队并列女生人气的双璧。我曾侧耳听过班上女生提过。

    「人气社团还真难为。幸好文艺社都没有闹男女问题。」

    「…………」

    天爱星同学用欲言又止般的眼神盯着我。

    是怎么了？有话就请直说。

    「虽然我不是没意见，不过先约好会面时间才是第一要务。」

    天爱星同学朝着体育馆的沉重大门伸出手。

    我也一起出力推开门，嘈杂人声从中如洪流般奔出。

    体育馆内一半是男子篮球队，另一半是女子排球队在练习。

    我用眼角余光确认了天爱星同学走向经纪人，远远观察男子篮球队。

    虽然我不懂女人心，但是个子高又爽朗的男生看起来的确不同凡响。

    啊，刚才投篮命中的十号还真帅气……

    我愣愣地眺望着练习时，注意到篮球队的队员们不时侧眼看向我。

    怎么了？阴角有这么稀奇吗？

    我做好封闭心灵的准备时，发现篮球队频频偷看的不只是我。

    在他们视线的另一端，女子排球队正在练习……奇怪？打练习赛的队员之中，有我认识的学生喔。

    ——是八奈见杏菜和樱井弘人。

    两人仍穿着制服，笑着将高高飞过空中的球打回对面。

    ……这是什么和女生嬉戏的画面。

    男子汉大丈夫，在女生簇拥之下玩得忘记本分，实在令人扼腕。

    在我忧国忧民之际，大概是嬉闹时间结束了，樱井留下了正与看似队长的人有说有笑的八奈见，跑向我这边。

    「温水你也来了啊。和马剃一起拜访各社团吗？」

    「哎……算是吧。」

    我模棱两可地回答后，樱井像是介意着旁人的视线般，对我微微低下头。

    「……抱歉喔。」

    「咦，也没什么要道歉的——」

    我说到一半，樱井面露平常那样伤脑筋的笑容。

    「因为之前明明说要退出，现在却又出来碍马剃的事。就结果来说也对温水撒了谎。」

    「我是没关系啦……」

    我眼角余光瞥见天爱星同学似乎正与男子篮球队的经纪人有所争执。

    樱井面露苦笑。

    「在学生会室也有点尴尬。」

    哎，想想也是。

    天爱星同学是个好孩子，但是不太擅长隐藏自己的情绪。

    「但是既然你决定要参选会长，表示你也有你的想法吧。」

    「谁晓得呢。心情这种东西，有时候反而是本人最搞不清楚。」

    樱井有些伤感地笑了。

    「——我也没想过，自己居然这么不懂得死心。」

    那独白般的口吻，让我不禁看向樱井的脸。

    这时，傻里傻气的声音打破了这段短暂的沉默。

    「咦？温水你也来了啊。」

    八奈见用手帕擦着汗水，靠近我们两人。

    「是啊，找男子篮球队有点事。」

    「就是那个吧？要发人家说的毒馒头吧。」

    「毒馒头？」

    吓人的名词让我不禁反问，八奈见一脸得意地双手抱胸。

    「我听说过，选举的时候要到处发毒馒头（编注：指乍看之下充满诱惑，实则蕴含风险的事物。在政治方面多指以好处拉拢敌方阵营人员的情形。）。一定是好吃到会死掉的馒头吧。」

    是这样吗？换作是八奈见，明知有毒应该也会吞下肚就是了。

    「让你久等了，温水同学。明天放学后，练习前有点时间——」

    天爱星同学一边在笔记本写字一边走向我，这时她抬起脸。

    「哎呀，樱井也来了啊。」

    「是啊。你约到男篮队了啊？真厉害，我被拒绝了说。」

    樱井朝着八奈见投出意有所指的视线。

    说起来，八奈见之前好像拒绝了男篮前队长的告白来着……

    也不晓得是否有注意到那视线，八奈见连连拍打我的肩膀。

    「唉，温水，那个是在干嘛？」

    「嗯？」

    沿着八奈见的视线看过去，体育馆大门外有个女生正举着单眼相机。

    那名裙摆偏短、打扮流行的女生一注意到我们的视线，就立刻消失无踪。

    「是赏鸟会的残党呢。虽然现在变成新闻社了。」

    天爱星同学一脸不愉快地说。那就是传闻中的新闻社啊。

    乍看之下是个可爱的短裙女生，还真是人不可貌相呢……

    「温水，我脸上沾到什么了吗？」

    「啊，没什么。」

    不妙，我无意识间盯着八奈见看了喔。

    在八奈见再度开口前，天爱星同学闯入我与她之间。

    「那么温水同学，我们差不多该动身了。」

    「今天的行程不是已经结束了吗？」

    「工作还堆积如山。快走吧，会打扰人家社团活动喔。」

    天爱星用肩膀硬是推着我向前走。

    我因为谜之压力而不知所措时，八奈见拉扯樱井的衣服。

    「那樱井，我们也去开作战会议吧。」

    「说的也是。那么两位，我们也要走了。」

    「咦？喔喔……」

    八奈见瞥了我一眼后，抓住樱井的手臂。

    「对了，胡桃红豆馅面包有两个，就给樱井一个吧。」

    「不是两个都是八奈见同学的份吗？」

    「我决定减重时期只吃一个。」

    我用眼角余光追逐两人的身影，同时对天爱星同学发问：

    「所以接下来有什么工作？」

    「不晓得，有什么工作呢？」

    奇怪，你刚才不是说工作堆积如山吗？

    见到我露出纳闷的表情，天爱星同学有些不开心地用力撇开了脸。

    ◇

    隔天，星期五傍晚。

    我拖着疲惫的身体，好不容易抵达了自行车停车场。

    没错，连日的社团访问终于结束了。

    而且到了尾盘，天爱星同学也能避免和人家吵架了。真了不起。

    ……话说回来，她的推荐人找到了吗？

    如果她是打算顺势让我半推半就地当推荐人，我可无法回应她的期待。

    别看我这样，我可不会因为同情就放弃坚持——

    在我立下坚定决心之时，注意到我的自行车前方就站着小鞠。

    「小鞠，你在这里做什么？」

    「在、在等你。」

    ……我想也是。我尴尬地搔着脸颊。

    「抱歉，这段时间没空到文艺社露面。八奈见同学有去吗？」

    「她、她偶尔会跑来，塞炸猪排三明治给我吃。」

    八奈见似乎正采取八奈见风格的选举策略。会胖喔。

    「我下星期也会去文艺社的。况且马剃同学也要开始忙运动会的工作了。」

    「这、这次是真的吗？」

    「是啊。剩下的只有公告政见的原稿，还有拍海报照片而已。接下来一直到投票日当天的演讲之前，都不会有什么大动作……我是说真的喔？」

    小鞠默默地投出不悦的眼神。

    「我讲好几次了，我不会进学生会的。」

    「可、可是你在帮副会长，做事吧？」

    「是的。」

    我再度挪开眼神。

    「毕、毕竟温水你，一到紧要关头，老是被人随便牵着鼻子走。」

    「不，我可没那么好搞定喔。」

    我微弱地抗议后，小鞠自浏海的隙缝间凶狠地瞪向我。

    「回、回家社那次，你忘了吗？」

    「是的。」

    我已无从反驳。我如坐针毡地垂首不语，随后小鞠忸忸怩怩地开口说：

    「明、明天，你有空吗？」

    「你问星期六的话，是没什么特别的事。」

    「那、那就空下来。我、我有话，要说。」

    小鞠板起脸抛下这句话后，便裙摆一甩，转身跑远了。

    怎么回事？是邀我约会——这怎么可能。而且她好像在生气，有点恐怖……

    我深深叹息后，把背包放进自行车的置物篮。

    ◇

    星期六早晨。抬头一看，是个令人目眩的大晴天。

    我从丰桥车站搭公车约十分钟，站在大型生活百货店前方。

    看着头戴圣诞帽的企鹅招牌，我不禁嘀咕：

    「……要挨骂了。」

    小鞠突如其来地约我出来，意思铁定只有一个——就是说教时间。

    约好的地点在前一刻从中央图书馆改成这里，也是佐证之一。

    毕竟这间生活百货店，在市内可是排行前几名的阳角去处。一定是想趁我精神衰弱时落井下石……虽然我觉得小鞠也会同样衰弱。

    糟糕，既然这样，为了讨好小鞠，我也得准备一下供品。

    八奈见只要给她烤地瓜就行了，换作小鞠就是BL周边之类的吧。

    但是BL底下喜好派别多，还是给图书卡——不，干脆给现金吧？

    当我开始检查皮包里装了多少钱时，注意到小鞠正凝视着我。

    小鞠穿着朴素的棉质短袖衬衫，搭配裙子与褐色背心。稍微土气这点虽然惹人怜爱，不过说出口会惹她生气，我决定放在心里。

    小鞠表情尴尬地垂着视线，小声呢喃说：

    「温、温水，让你久等了。」

    「咦？这两个孩子是……」

    没错，小不点——她的弟妹进弟弟与阳奈妹妹，分别站在小鞠的左右两侧。

    「那、那个，我爸妈突然有工作……我把两个小不点，一起带来了。」

    小鞠边说边用指尖把玩着浏海。

    见到姊姊的反应，进弟弟对我低下头。

    「大哥哥，今天请多多指教。」

    「喔喔，我才该请你多多指教。」

    进弟弟好像是国小四年级吧。比我和姊姊还懂得待人接物喔。我在他这个年纪，脑袋里只有打电动而已。

    然后躲在小鞠后面看着我的是小鞠阳奈。

    估计年龄为四岁，是丰桥引以为傲的可爱生物。

    「……姊姊的朋友。」

    「好久不见了。大哥哥叫做温水。」

    我压低身子对她微笑，阳奈妹妹从小鞠后面慢慢现出身影。

    「……温水。」

    「对，温水。」

    阳奈妹妹点头后，又躲回小鞠后方。好可爱～

    看着我们交流的小鞠似乎松了口气。

    「你、你没关系吗？」

    「完全没关系。不，不如说有他们一起更好。」

    既然带着弟妹一起来，我也不会被骂得太惨。这个机会可不能放过。

    我蹲下身，对阳奈妹妹投以微笑。

    「好啦，阳奈妹妹，今天想去哪里呢？」

    阳奈妹妹抓着姊姊的裙子，小声回答：

    「阳奈，要买东西。」

    「好，大哥哥什么都买——」

    「喂、喂，不要随便乱讲。」

    马上就挨骂了。姊姊的管教真严格。

    「那么我们快点走吧。要买什么？」

    「不、不要跟阳奈——喂、喂，你们两个，不要用跑的。」

    小鞠追赶手牵着手跑进店内的弟弟妹妹。

    我怀着几分怀念的心情守候着这一幕，跟在后头走过了自动门。

    ◇

    热闹的店内各处都堆满了商品，鲜艳的原色标价牌令脑袋晕眩。

    小不点们四处游走，我和小鞠在后头并肩而行，这时我注意到特价的清洁剂。

    这满便宜的耶。我不禁停下脚步时，小鞠用手拉扯我的衣角。

    「温、温水，会迷路喔。」

    「可是你看，这个很少特价耶。」

    「今、今天先忍耐。」

    好的，我会忍耐。

    定睛一看，小不点们正在中元礼品区看点心礼盒。

    「刚才阳奈妹妹也说要买东西，难道是要买中元礼品吗？」

    「怎、怎么可能。幼、幼儿园要办过夜活动，来买，新睡衣。」

    是喔，原来没有互赠中元礼盒的四岁孩童啊。

    小鞠守候着四处晃荡的弟妹，小跑步追上去握住两人的手。

    「要、要是跑太远，会和温水一样迷路喔。」

    小鞠真懂得怎么逮住孩子。我不禁莞尔地观察时，小鞠对我投以不开心的眼神。

    「是、是怎么了，一脸恶心的表情。」

    「只是想说小鞠以后应该会是个好妈妈。」

    「呜唉！？去、去——」

    小鞠话说到一半，注意到阳奈妹妹正注视着自己，便干咳几声。

    「温、温水，你问题就出在这里喔。」

    见到小鞠换了种说法，阳奈妹妹双眼灿烂发亮。

    「！温水，你有问题喔！」

    「嗯，对呀，大哥哥也许是有点问题呢。」

    模仿姊姊的阳奈妹妹真可爱。然后小鞠，不要对我投以看厨余的眼神。

    在小鞠的催促下搭乘电扶梯上楼后，该处是玩具卖场。

    见到两个小不点眼神发亮地跑进卖场，小鞠叹息。

    「做、做好觉悟。一旦变成这样，会很麻烦。」

    见到小鞠追向阳奈妹妹，我走向进弟弟的方向。

    进弟弟站着不动，侧眼注视着变身英雄的腰带。

    ……最近的玩具还真精致耶。我拿起试用的腰带。

    「嗯？这个要怎么用？」

    「不是把卡片插进去，是把卡片滑过去读取喔。」

    哦～原来是这样啊。我按照他说的，让腰带读取卡片后，腰带发出光亮，英雄喊出必杀技的名称。

    「原来如此，这样就可以了啊。这个每张卡片的声音都不一样吗？也太厉害了吧？」

    「不只是这样。把卡片同时刷过这里，就能发动组合技。」

    这是怎样，也太厉害了。

    我按照进弟弟的指示，大略试了一次，最近的玩具真的做得好精致啊。

    「换进弟弟玩玩看吧？」

    「我不用了。这种玩具，我最近已经毕业了。」

    是喔，我刚才玩得很开心耶。

    「那在学校之类的地方，现在流行什么？」

    「还是电玩吧。你知道魔物吗？」

    我记得是和伙伴合作狩猎巨大魔物的游戏吧。

    系列最新作的口碑非常好，其实我也有点兴趣。

    「知道是知道，可是那个的前提是多人合作吧？一个人玩不寂寞吗？」

    「当然是和朋友一起玩啊。一定的吧。」

    这样啊，一定是和朋友一起玩啊。是喔……

    走过特摄区后，我们来到电玩卖场，进弟弟在该处拿起一盒游戏。

    「只有我一个人没有，每次都只能在旁边看。但是，领到下个月的零用钱就能买了。」

    「真了不起。真亏你存得到。」

    「对吧？最近我完全没在花钱。」

    进弟弟有些得意地羞赧笑道。姊姊是不是也该仿效一下。

    我感到敬佩之时，进弟弟压低了声音问我：

    「……唉，你今天原本要和姊姊约会吗？」

    「不是啊。」

    我下意识这么回答后，进弟弟露出纳闷的表情。

    「两个人一起出去玩，和约会有什么不一样吗？」

    的确，哪里不一样？

    毕竟我约会的经验，只有和烧盐的那一次而已……

    「你想问约会和出游的差异，对吧？」

    「差异是什么？」

    我正面直视进弟弟认真的双眸。

    「应该是——牵手吧。」

    「牵手？我和阳奈还有姊姊也会牵手啊。」

    「大哥哥我也常常和妹妹牵手，但是很遗憾家人不算数。原本没关系的男生和女生两个人一起出门，手牵着手——这才叫约会。」

    我表情得意地断言后，进弟弟露出有些遗憾的表情。

    「姊姊从昨天就一直在挑衣服，我还以为一定是约会。」

    哦～小鞠现在也会关心穿着打扮了吗？

    我为了小鞠的成长而感到欣慰时，进弟弟左顾右盼地环视周遭。

    「话说回来阳奈呢？」

    「和你姊姊在一起。啊～我记得是那个方向。」

    我和进弟弟一起寻找小鞠她们，随后在玩具卖场的一角发现两人的身影。

    该处摆的是让小巧的动物玩偶在迷你模型的房屋中生活，长年来高人气的系列玩具。

    阳奈妹妹一看到我，就把兔子与熊的玩偶拿到我眼前。

    「这个，是姊姊和哥哥！」

    「是喔，原来是姊姊和哥哥啊。」

    嗯，这是在说什么？

    我求助地投出视线，小鞠抚着阳奈妹妹的头，回答道：

    「她、她常把同样的玩偶，取我和进的名字，玩扮家家酒。」

    哦～是这样啊。兔子和熊是一对姊弟，家庭环境好像很复杂呢……

    当我针对家族的意义深思时，阳奈妹妹拿起了水獭玩偶。

    「这个，是温水！」

    我？所以我会是阳奈妹妹的哥哥——不，应该是爸爸吗？

    这感觉也不差。我凝视着接到手中的水獭。

    「啊！」

    阳奈妹妹伸出手，拿起架子上的小盒子。那是个造型可爱的三层床铺的迷你模型。

    「这个！到处都没有卖！」

    「不、不行，没有要买喔。」

    小鞠想收走盒子，但阳奈妹妹把盒子抱进怀里。

    「阳奈一直在找这个耶。」

    「没、没有要买喔。好、好了，进也该走了。」

    「喂，小鞠。」

    小鞠牵着进弟弟离开了——乍看如此，但她马上躲到附近的货架后方。

    ……也太明显了。不只是那束头发，连脸都露出来了。

    我一靠近，小鞠就慌张地猛摇头。

    「温、温水，她会发现，我躲在这里。」

    「完全没藏住喔。阳奈妹妹由我来顾，你们两个先走吧。」

    小鞠对我投出怀疑的眼神，低声嘀咕说：

    「不、不要买喔。」

    ……嗯，我尽量。

    小鞠与进弟弟走远之后，我在阳奈妹妹身旁蹲下。

    「你真的那么想要那个吗？」

    阳奈妹妹一语不发，微微点头。

    「家里应该也有差不多的吧？今天就先忍耐，回家找找看吧？」

    「家里的不一样。床只有两张。」

    ……原来、如此？她有的那个是两层床铺，这个是三层床铺吧。

    别人无法理解的坚持，对当事人可是重大问题。

    戴眼镜的学姊教导了我这件事的重要之处。主要是以左右问题为例。

    「这样啊，看起来是很帅没错。阳奈妹妹特别喜欢哪一点？」

    刚才再度沉默的阳奈妹妹小声嘀咕：

    「可以和姊姊、哥哥，三个人一起睡。」

    啊～我懂了。对阳奈妹妹来说，这样的想法被否定会让她伤心吧。

    可是如果我擅自买给她，会被小鞠骂啊……

    「可是啊，大家分开睡在不同张床上，会觉得寂寞吧？」

    「会寂寞吗？」

    阳奈妹妹一脸意外地说，我对她点头。

    「嗯，进哥哥和知花姊姊一定都还想和阳奈妹妹一起睡。所以说，你愿意再陪他们睡同一张床一下吗？」

    阳奈妹妹愣住一段时间后，微微地点了点头，把盒子放回架上。

    「真了不起。那我们去找姊姊吧。」

    我和阳奈妹妹手牵手，朝小鞠刚才离开的方向迈开步伐。

    感觉到细小又温暖的触感收在掌中，我回忆起自己的童年。

    自己的感受无法传达给别人的焦躁感。

    但是连自己也不清楚自己在想什么——

    「阳奈妹妹也是大人啊～」

    我不经意地自言自语时，险些与躲在货架后方的小鞠撞个正着。

    「呜唉！？呃，啊。」

    「喔喔，小鞠你在这里喔。」

    阳奈妹妹松开我的手，抱住小鞠。

    「姊姊，在这里！」

    「我、我在啊。我们，去买东西吧？」

    「嗯！」

    像是完全忘了我，阳奈妹妹在小鞠身旁打转，一同迈开步伐。

    我心中感到几分寂寞，同时加快脚步走到小鞠身边。

    「我记得是来买阳奈妹妹的睡衣吧？」

    「对、对。童装、卖场。」

    她说幼儿园有过夜活动吧。

    我模糊地回忆起自己的幼儿园时期，这时小鞠自言自语般接着说：

    「阳、阳奈用的，大多是我和进穿过的，所以想给她买新的。」

    哥哥姊姊穿不下的啊。我是长男，佳树则是反过来想要我穿过的，害爸妈很伤脑筋呢。

    我忆起别人可能难以感同身受的往事时，小鞠有所察觉般扫视周遭。

    「温、温水，进跑去哪里了？」

    「奇怪？刚才不是和小鞠在一起吗？」

    「我、我去看看。」

    小鞠走进玩具卖场后，便见进弟弟与她交替般走出卖场。

    进弟弟将他手中的黄色塑胶袋塞到阳奈妹妹怀里。

    「阳奈，拿去。」

    「哥哥～这是什么？」

    「只有这次喔。」

    进弟弟板起脸这么说，把脸转向一旁。

    阳奈妹妹一脸不可思议地取出袋子的内容物，表情随之灿然发光。

    从袋中露出的是刚才阳奈妹妹想要的三层床铺的迷你模型。

    「哥哥～这是阳奈的？」

    「对啦，快点收起来不要给姊姊发现。」

    「嗯！」

    进弟弟刚才跑去买这个来给阳奈妹妹啊。

    我感到敬佩时，气喘吁吁的小鞠回来了。

    「进、进……不要随便……乱跑。」

    进弟弟挪开视线不看肩膀上下起伏的姊姊。

    「我只是去买个东西。」

    小鞠一看到阳奈妹妹抱在怀里的袋子，大概就瞭然于心了吧。

    她苦笑着轻抚两个小不点的头。

    「阳、阳奈，有好好，说谢谢吗？」

    「有——没有！哥哥，谢谢你！」

    「不用啦，我自己也想要而已。好了，我们去买东西吧。」

    洋溢着兄妹之爱的优质傲娇。

    「喂，进，不要用跑的。」

    「哥哥，等一下～」

    进弟弟为了遮掩害臊而向前跑，小鞠姊妹追赶在后。

    我为了克尽观察者的职责，在三人后方缓缓跟上去。

    ◇

    我们结束购物，来到美食广场围绕着桌子。

    坐在孩童区的矮椅子上吃芡汁义大利面，真是不可思议的感觉。

    当我看着照顾阳奈妹妹的小鞠时，她回以疑惑的视线。

    「怎、怎么了？你不吃吗？」

    「小鞠，换我来吧。你都没在吃吧？」

    「我、我没关系。你帮我顾着进。」

    「姊姊，我已经能一个人吃了啦。」

    进弟弟不满地鼓起脸颊，将加了配料的奶油可乐饼送进口中。

    我们正在吃的是丰桥的知名店家CIAO的芡汁义大利面。

    能在美食广场吃到是很方便，不过这间店的义大利面分量惊人。

    小鞠与进弟弟两个人吃一人份，阳奈妹妹吃的是给小孩子的儿童餐。

    我一个人要吃完一份也很吃力，八奈见会不会突然路过啊……

    在我不停将芡汁义大利面送进口中时，阳奈妹妹突然想拿出塑胶袋里的东西。

    「这个啊，这件睡衣，和姊姊的一样是星星的。」

    「不，不可以喔，先吃完再说话。转过来，嘴巴沾到了。」

    我一边看着小鞠擦拭着阳奈妹妹的嘴边，一边用叉子卷起被铁板稍微烤焦的义大利面。

    这感觉就是周末时的家庭出游嘛。为何我也置身其中……？

    直到最后我都怀着不可思议的心情，将义大利面塞进口中。

    ◇

    东西买好了，午餐也吃过了。

    我们忙完所有正事——来到了隔壁的电玩游乐场。

    我看着小不点们在夹娃娃机之间穿梭奔跑，磨蹭着自己吃得太撑的肚子。

    「小不点们真有精神。」

    「今、今天因为有你在，比较安份。」

    真的假的？小鞠，真是辛苦你了。

    看着两个小不点嬉闹的模样，小鞠面露柔和的笑容。

    「不、不过，小不点们，好像很开心，太好了。」

    「算是有让他们开心了吧。」

    小鞠点头。

    「我、我爸突然有工作，原本出门玩的约定取消，阳奈也忍不住哭了。」

    「原来如此，所以今天我就是爸爸吧。」

    「呜唉！？」

    随口开了玩笑，我做好心理准备要挨骂时，小鞠满脸通红，一语不发地颤抖。

    「呃～不是奇怪的意思喔？」

    「……笨、笨蛋。」

    小鞠用力转开脸。啊～看来是我说错话了……

    我深切反省时，小不点们跑到我们面前。

    「姊姊，我们玩那个吧！正好有四个人。」

    「呜唉……只、只能玩一次喔。」

    「那个是什么？」

    「在这边！」

    「温水，这边～！」

    我任凭两个小不点拖着走，被带到气垫球的机台前方。

    「要四个人一起玩这个吗？」

    「你、你怕了吗？」

    小鞠挑起嘴角，对我投出挑衅的视线。

    哦，这要当作公然宣战也无妨吧？我开始舒展筋骨时，进弟弟走到我身旁。

    所以说小鞠和阳奈妹妹一组吗？

    「不用让分也没关系吗？」

    「温、温水要我让分吗？」

    小鞠毫无惧色地回嘴，将硬币投入机台。

    「……姊姊很强喔。」

    进弟弟表情认真。仔细一想，她本人也说过这种话……

    话虽如此，厉害也只是相较于弟弟妹妹吧。

    红色气垫球从侧面滑入场中。

    好，开始了。气垫球缓缓移动至小鞠面前，下一瞬间——

    咻匡！

    响亮的声音发出，气垫球消失在眼前的球门中。

    「！？等一下，看不见球路耶！？」

    「我刚才就说了啊！马上又要来了喔！」

    咦？接下来换我们发球吧？

    我感到纳闷时，无数的小气垫球开始流入场中。

    最近的气垫球桌还有这种功能吗！？

    在我慌了手脚时，气垫球接二连三地冲进我们的球门中。

    「温水，好好防守！」

    「不，话是这样说，连看都看不到啊！？」

    于是游戏的最终得分是——870对120。堪称是单方面的屠杀。

    面对着互相击掌的小鞠姊妹，进弟弟拍了拍我的肩膀。

    「别在意，温水哥哥。」

    被小学四年级生安慰了。进弟弟真温柔。

    然后小鞠的嚣张表情刺激着我的伤口。

    （插图013）

    「……小鞠，兑币机在哪里？」

    见到我取出千圆钞票，小鞠嗤之以鼻。

    「那、那一张够吗？」

    「别担心，还有涩泽荣一压阵喔？」

    对决的结果就不特此记述了。如果真要提起的话——唯有我皮包中的涩泽先生变成了数张北里先生这一点吧。

    ◇

    有种说法是四岁孩童拥有无限体力。先不论这说法的真伪，开关确实存在。

    开关切断的瞬间，四岁孩童就会落入深深的睡眠之中——

    连接市区与物流园区的公车上，我们四人并肩坐在长长的车尾座位。

    被我抱在怀里的阳奈妹妹睡得香甜，隔着小鞠坐在另一头的进弟弟也闭起了眼睛，任凭巴士摇晃着身子。

    「不、不会重吗？」

    「不会啊。因为我平常都让佳树坐在大腿上，阳奈妹妹和羽毛差不多。」

    「把、把阳奈还来。」

    为什么啦。

    当我轻轻拍着阳奈妹妹的背时，小鞠低声呢喃般说：

    「今、今天谢谢你。」

    「气垫球是我自己想玩的啊。」

    「我、我是说，陪我们一整天。」

    啊，是这个部分啊。虽然没做什么值得被道谢的事情，但我就心怀感激地接受吧。

    巴士的车内安静得不可思议，摇晃唤来宜人的睡意。

    小鞠朝着睡着的进弟弟伸出指尖，梳理他的浏海。

    「进、进每次都太宠阳奈，伤脑筋。」

    小鞠嘴巴上这么说，脸上却挂着温柔的笑容。

    我感受着阳奈妹妹的重量压在大腿上，开口说：

    「进弟弟明明说他在存钱买游戏，没问题吗？阳奈妹妹的玩具，也不便宜吧？」

    「大、大家都很宠阳奈——」

    小鞠对我露出笑容，像是要告诉我别担心。

    「至、至少要有我宠他才行。」

    即使在学校是吉祥物角色，小鞠在这里也是个姊姊啊。

    我看着螃蟹招牌自窗外通过，静静地开口说：

    「……话说回来，你今天本来有话想跟我说吧？」

    昨天傍晚，小鞠的确这样说过——当时她的眼神似乎有些心事。

    我虽然一直在担心会挨骂，但是也不能不听她说。

    小鞠仔细打量进弟弟的睡脸后，开了口。

    「原、原本有话想说，但已经不用了。」

    「是学生会选举的事吧？」

    我反过来主动提起后，小鞠微微摇头。

    「虽、虽然不信任，但是我相信。」

    小鞠面露柔和的表情，轻抚着进弟弟的头发，低语道：

    「因、因为你说过，你会陪我。」

    ——喀当。

    公车摇晃，沉默再度充斥我们之间。

    车内广播响起，大概没有人要下车吧。公车没有在公车站停车，就这么直接驶过。

    「我真的那么没信用吗？」

    我打趣般这么说完，小鞠恢复了平常嚣张的表情。

    「你、你就很好搞定啊。」

    下一个公车站有一名乘客下车，巴士内只剩下了我们和驾驶。

    公车再度开始行驶，下一站就轮到我们下车了。

    小鞠忽地开口。

    「你、你常常跑去……马、马剃家吗？」

    为什么你会知道——啊，之前天爱星同学在教室大声公开了啊。

    「我只是去跟她拿小奇卡的周边而已，而且那个……她弟弟也在家。」

    我没有说谎。虽然我还没拿到周边。

    「她、她会跑来温水家吗？」

    「唉？马剃同学从没来过我家——」

    ……不，有。虽然正确来说是佳树的客人。

    我转开视线不看小鞠怀疑的双眼，寻找着能当借口的字句。

    「啊，可是泡过浴缸的只有你喔？烧盐也只是淋浴而已。」

    「……去、去死。」

    这家伙发现弟弟妹妹睡着，就开始口无遮拦了。

    这时阳奈妹妹扭动着身子，睁开了眼睛。

    「……温水？姊姊呢？」

    「在、在这里喔。」

    「姊姊比较好……」

    睡眼惺忪的阳奈妹妹朝小鞠伸出双手。

    趁着公车等红灯的空档，小鞠从我这边接过了阳奈妹妹，看起来有点沉重似地重新抱稳。

    「可以吗？」

    「没、没问题。进，差不多要下车了，起来。」

    进弟弟一脸想睡地揉着眼睛。

    「……途中就醒了。」

    公车一停，进弟弟便头一个站起身。

    他不知为何板着脸，不过经过今天一天，我和进弟弟也变得熟悉了。

    虽然年纪有差距，不过彼此都是男生，总是有些心意相通之处吧。

    下了巴士，正要一起迈开步伐时——

    啪。突然间，进弟弟一掌用力拍在我的腰部。

    「咦？怎么了？」

    「温水大笨蛋！」

    「！？」

    进弟弟又打了我一下，接着拔腿从我身旁跑走。

    「不、不可以喔，进！」

    小鞠开口责备后，进弟弟转身面对我，对我吐出舌头。

    「温水大笨蛋！大木头！」

    进弟弟就这么朝着家的方向跑远了。

    咦咦……他心中究竟发生了何种变化？

    我呆若木鸡之时，小鞠对我露出尴尬的表情。

    「抱、抱歉，回家以后，我会骂他的。」

    「用不着骂他啦。只是刚才的进弟弟，到底是怎么了？」

    小鞠对歪着头的我投出欲言又止的视线。

    「可、可是温水也有错喔。」

    是喔，我也有错吗……是喔……

    「等等，为什么？我做了什么坏事吗？」

    「你、你自己想。」

    小鞠抛下这句话，转身背对我。

    ◇

    周末过去，星期一的放学后。

    我在中庭的石桌旁，与天爱星同学召开定期会议。

    周末的全家出游——更正，是与小鞠一族出游，度过了一段称得上非常平稳的时光。然而回程时进弟弟的反应是怎么回事呢？

    进弟弟说的『大木头』是指迟钝的家伙，难道小鞠一族有在临别时骂人的习俗吗……？

    我不禁陷入沉思之时，天爱星同学清了清嗓子。

    「温水同学，可以听我说吗？」

    「啊，抱歉。你刚才说什么？」

    「日后的预定行程。下周要公告政见和张贴竞选海报，再隔周则是——」

    「投票日吧。」

    天爱星同学沉重地点头。

    「是的。候选人演讲和推荐人的声援演讲一结束，马上就要投票。很容易想像演讲时的表现会直接左右投票结果。我们必须事先确认彼此的讲稿内容。」

    「我只是帮忙而已，不是推荐人啊。」

    「是的，我明白。」

    天爱星同学表情认真地点头。

    「志喜屋学姊告诉我，温水同学只要再三拜托就行，我想尝试动之以情。」

    我的同情心正在被挑战吗……

    「我可没有那么简单就被说动喔？好了，总之要先准备公告政见。」

    「关于这部分，我事先准备了草稿。」

    天爱星递出了几张纸。

    我接过一看，纸上陈列了从之前的访视内容统整的学生要求，还引用了与之相关的校规与市政府的条例等等……好沉重。

    「学生会要做到这个地步吗？」

    「当然没有那种权限和预算，但是可以向老师提出希望。与老师分享学生的意见是一大重点。」

    天爱星同学伸手翻动我手中的原稿。

    「我写的文章好像太过生硬，不容易传达给别人。如果身旁就有擅长写文章的人就好了，但我想不到适合的人选。」

    是这样啊。顺带一提，在你旁边的是文艺社员。

    「这个嘛，找学生会的学姊们呢？」

    我重整心情如此说道，天爱星同学的表情转为僵硬。

    「我不打算找学姊们帮忙。因为这是我自己的战斗。」

    天爱星同学大概是注意到自己的口吻强硬，她清清嗓子，换了个说法。

    「……因为樱井也参选了，我不想让她们为此费心。」

    对会长和志喜屋学姊而言，天爱星同学和樱井都是可爱的后辈。

    无论偏袒哪一边，或是拒绝请求，肯定都免不了费心伤神吧。

    「他比较有人望，这是事实。正因如此，针对未来这所学校应有的样貌，我想向大家发出提问——」

    「可以暂停一下吗？」

    我插嘴打断后，天爱星同学挺直了背脊。

    「好的，温水同学请说。」

    「这个地方啊……从其他教室和教职员室都能看见，如果可以的话，能不能在室内谈？」

    听了我的提议，天爱星同学像是出乎意料般，眨了眨眼。

    「之前也说过了，这里距离联络走廊和校舍都有段距离，不用担心对话被人听见。我觉得非常适合谈选举策略。」

    回想起来，上次拿到围巾时，也是被她叫到大池中央处碰面。

    天爱星同学的说法也有道理，不过来来往往的学生们的视线实在令人介意。

    「那就回过头来。首先在公告政见时吸引赞同者，在布告栏收集意见——」

    「稍等一下，好像有讯息传来了。」

    彷佛天赐良机，我取出智慧型手机一看，动作不禁暂停。

    显示在萤幕上的是来自小鞠的讯息。

    ——现在马上来二年级教室的走廊。

    ◇

    走廊上的布告栏前方聚集了十几个人。

    平常放学时间之后，教室周边就没什么人了，究竟是怎么了？

    我心生畏缩而杵在一旁，这时天爱星同学猛然闯进人群之中。

    「不好意思，可以借过一下吗？」

    我对强硬的天爱星同学感到敬佩，跟着她开出的道路走上前。

    呃～布告栏上贴了什么吗？

    「温、温水！」

    「咕！？」

    砰！有东西从死角直刺我的心窝。

    我强忍着痛楚往下方看，小鞠的身影就在眼前。

    「到、到底是怎么了……」

    「不、不知不觉间就被包围，出、出不去了。」

    小鞠浑身颤抖着，抓住我的领带。

    我和小鞠两边拉扯领带时，这回是天爱星同学用力拉扯我的衣服。

    「温水同学，请看那个！」

    在天爱星同学所指之处，布告栏上贴了一张报纸尺寸的纸张。

    「石蕗新闻，学生会选举特辑……？」

    虽然说要我看，不就是学生会选举的报导吗……

    我看向新闻的标题，不禁睁圆了眼睛。

    『学生会选举其实是恋爱代理战争！？』

    ……什么跟什么。不是，真的是莫名其妙。

    我看看，本次选举的开端是围绕着二年级某位美少女的爱情纠纷，有关人士之一是拈花惹草的女性公敌，周旋于复数女同学之间……？

    哼哼，这就是在说樱井吧。那家伙很受欢迎嘛。

    所以写在这上面的，以副会长宝座当作诱饵，吸引男人注意的会长候选人该不会就是——

    天爱星同学整张脸红到脖子，浑身剧烈颤抖。

    「……不、不是的！我不是那样想才找你的喔！？」

    「我当然知道啦。嗯，我知道我知道。」

    「你根本不知道吧！？况且本来就是温水同学不好喔！？老是说些让人误会的话，把我耍得团团转——」

    咦？怎么突然批评起我了。就连小鞠都紧抓着我的领带，点头如捣蒜。

    「我、我知道了啦！众目睽睽之下，小声一点如何？」

    啊啊，周遭的视线刺得我好痛……

    我努力安抚天爱星同学，继续阅读校园新闻的后续。

    呃～女性公敌的男同学从篮球队已经毕业的前主将手中，夺走了校内的人气美少女——二年级生A子，却在百般玩弄之后弃之不顾啊。

    而且传闻中他与学生会成员的女生脚踏两条船，魔掌还伸向了新进的一年级女生。

    樱井也被写得太糟糕了吧……

    我深感同情并继续往下读，但是报导在中途就结束了。

    在最后用红字记载的是——

    欲知详情请至网站！于新闻社官网购买！

    我看着那黑体字型的红字，说出今天不知第几次的感想。

    「……什么跟什么。」

** Intermission 别看我这样其实很受欢迎

    傍晚，丰桥车站前的咖啡厅UNO-UNO。

    八奈见杏菜与姬宫华恋并肩坐在吧台座位，隔着玻璃眺望丰桥车站前的景致。

    「杏菜，学生会选举已经忙完了吗？」

    手上拿着草莓牛奶杯子的华恋歪过头问，发丝轻盈摇摆，周围有闪闪发亮的光点洒落。

    「公告政见的原稿也写好了，接下来只剩拍海报的照片而已。樱井也要开始准备运动会了，这阵子应该没空忙选举吧。」

    店员将冰淇淋苏打端上桌后，八奈见双眼闪闪发亮。

    「话说回来，运动会就是学生会最后的工作了吧？好像很辛苦呢。」

    「高中生出乎意料地忙碌嘛。啊，这个真好吃。」

    华恋看着大口品味冰淇淋的八奈见，紧张兮兮地问：

    「那个……杏菜和樱井是什么关系？」

    「还能有什么关系，就同班同学啊。华恋不也一样吗？」

    八奈见回答得理所当然，华恋露出了意外的表情。

    「我只是在想，如果只是普通同班同学，你为什么会当他的推荐人。」

    「因为马剃同学把温水邀走了啊。」

    「就算是这样，为什么——」

    神情疑惑地思考的华恋，突然间朝四周放射光芒。

    「这就是那个意思吧，杏菜！」

    八奈见点了点头，回答道：

    「没错，不管哪一边赢都能卖人情给学生会。背地里是学生会副会长听起来也很帅气，大学推甄也能任我选择喔。」

    八奈见端起杯子，直接开始饮用混杂冰淇淋的苏打水。

    「……原来是这样啊。可是进了学生会很辛苦喔。」

    「万一忙不过来，我再找温水帮忙。他不会拒绝我的请求的。」

    真的会这么顺利吗？

    虽然有许多疑问，但是对这位友人，操心也只是白费工夫。

    华恋放松了肩膀的力气，俏皮地吐出舌尖。

    「是那样就好。我还以为你是故意和温水作对——」

    话说到一半，华恋连忙闭上嘴。

    「华恋，你说的是那个校园新闻写的事情？」

    「呃，那个——那上面写的东西，我觉得不要太在意比较好喔？大家都知道那些都是乱写的。」

    八奈见像是毫不介意的样子，面露淘气的笑容。

    「这也没办法。哎，我刚入学的时候也算小有名气嘛？」

    「咦？」

    她洋洋得意地说着，举起智慧型手机。

    映在萤幕上的，是石蕗高中校园新闻的付费版。

    「杏菜，你买了喔！？」

    「哎呀，毕竟也是当事人嘛？我想说自己读过会比较好。」

    八奈见面露不怀好意的笑容，将视线转向萤幕。

    「真的是随便乱写一通耶。说什么我和温水交往过，又说我被甩了？根本就没说中，不如说是我甩了他才对。」

    「咦？」

    华恋不由得惊呼出声，用双手捂住嘴巴。

    「不过，围绕着校内的人气美少女A子的恋爱代理战争，这标语听起来倒是不差。温水是女性公敌这点，其实也没说错。」

    八奈见愉快到甚至哼起歌来。

    观察着她的反应，华恋迟疑地举起一只手。

    「那个～杏菜，我可以问一下吗？」

    「好啊，华恋你请说。」

    「现在杏菜和温水——没有在交往吧？」

    「不管现在或以前，我们都没交往过啊？」

    华恋表情严肃地点头。

    「既然这样，难道不会因为这个契机，让马剃同学和温水的距离飞快拉近吗？」

    「那个古板的副会长怎么可能嘛。那个人老是对温水凶巴巴的，温水反而不擅长应付她吧？」

    「那她为什么会邀请温水当推荐人呢？」

    「说是没有其他男生朋友。毕竟是个认真的女生，也说不擅长和男生相处。」

    「哦～所以温水跑去马剃同学家，你也不介意啊。」

    八奈见手中的智慧型手机晃了起来。

    「哎、哎，毕竟是温水嘛？我跑去他家的时候，他也没什么反应……」

    八奈见的动作戛然而止。

    她凝视着萤幕不再动弹，华恋则担心地注视着她。

    「杏菜，怎么了吗？」

    「…………」

    没有回应。智慧型手机从八奈见手中滑落至地面。

    华恋疑惑地拾起手机，视线停留在画面中的报导。

    ——虽然刚开学时A子在男生之间的人气很高，但是她的时代在短短一个月便落幕。

    因为转学生K的到来，使她完全走入了历史。

    人气与男人都被夺走的A子，能否在本次学生会选举中取回过去的荣光呢——

    ……华恋读到报导的最后，连忙把智慧型手机藏到背后。

    「好了好了，杏菜！这种乱写的东西不可以读啦！」

    「我一点也不在意喔……？嗯……我真的不在意……」

    八奈见的气场急遽转弱。

    这可不妙。华恋在八奈见面前摊开菜单。

    「好了，我请你吃点东西，转换心情吧！你想吃什么？」

    「咦？可以吗？点什么都可以？」

    生气重回八奈见的脸庞。

    「当然，别客气！这间店的蛋糕很好吃喔。」

    「既然什么都可以点，会很迷惘耶～卡波纳拉义大利面是不错，不过牛肝菌菇的奶油酱也难以割舍……」

    「杏菜，你要吃义大利面喔？」

    「嗯？华恋，你刚才有说什么吗？」

    华恋默默地摇头。

    没错，在八奈见的笑容面前，吐槽都是不解风情。

    华恋看着八奈见欣喜地扫视菜单时的侧脸，由衷祈求着好友的幸福。

** ～第三败～红之狂想曲

    在那之后的一星期。先前的骚动彷佛不曾发生般，持续了一段平稳的时光。

    天爱星同学与樱井两人为了学生会最后的重大活动——运动会做准备，忙得不可开交。

    于是来到了周末的星期日。我和八奈见、小鞠三人从丰桥车站搭乘电车与地下铁，经过数十分钟后来到了名古屋市的田径竞技场。

    这里正在举办烧盐出赛的东海高中综合体育田径竞技大赛——也就是争夺所谓的全国大赛出赛权的比赛。

    上午的一千五百公尺的预赛，烧盐已经以第一名的成绩通过。

    只要在接下来即将开始的决赛中排进前六名，就能打进全国大赛——

    观众席的长椅上人影稀疏。

    小鞠坐在我和八奈见之间，摆出祈祷般的姿势，低声呢喃：

    「烧、烧盐她，没问题吗……」

    八奈见一边把手伸进爆米花的袋子里，一边对着神情担忧的小鞠说：

    「不用担心啦，柠檬跑得那么快。」

    「这、这里每个人，都跑得很快。」

    小鞠提出再合理不过的反驳后，突然站起身。

    从阶梯处出现在观众席的是——文艺社的毕业学姊，月之木古都。

    她一找到我们就大动作地挥手。

    「抱歉抱歉，我来晚了！」

    耳熟却教人怀念的声音。

    「学、学姊！」

    小鞠蹦蹦跳跳地跑向她，两人握住彼此的手，为了重逢而欣喜。

    我们也走上前去想加入其中时，前社长玉木也接着从楼梯处现身。

    「大家好久不见了。」

    众人轮流久违地打招呼后，玉木学长来到我身旁，眺望着欢天喜地的女生们。

    「大学还好吗？」

    「要跟上课程都很吃力。我真没想到光是一年级的实习和报告就会忙成这样。」

    「那应该没空能看动画和轻小说了吧。」

    「没这回事。独自生活真是太棒了。充满了名为对自己负责的自由。」

    玉木学长挑起嘴角一笑。

    「我跟你讲，动画可以边写报告边看。想摄取漫画或轻小说，不睡觉就好了。」

    玉木学长神情兴奋地将双手紧握成拳。

    「海报和挂轴别说填满墙壁，就算要贴满天花板也不会有人唠叨喔。只要我愿意，要放抱枕也行。」

    「月之木学姊都没有意见吗？」

    「……和古都的房间比起来，那样只是儿戏罢了。」

    玉木学长顿时露出看向远方的眼神。

    「那家伙的房间，不管往哪个方向看都有半裸的男人喔。而且就好像咖啡厅的背景音乐一样，随时都在播放BL的广播剧。」

    两人的爱巢似乎变成这副德性了。

    称不称得上放闪有点难以断定，不过肯定十分恩爱吧。

    「听起来过得满顺利的。」

    「哎，勉强过得去啦。那温水你呢？」

    「我怎样？」

    我不禁反问后，玉木学长把脸靠向我。

    「都没有和谁有进展吗？该不会是传闻中的新生吧？」

    「什么事都没有喔。况且我根本不被当成男人看待。」

    我想这样一笑置之时，学长的话语让我不禁回问：

    「咦？学长知道新社员的事情喔？」

    「听说是个难得的人才。今天没来吗？」

    的确是稀世罕见的人才，至于是哪方面的才华暂且不提。

    话说回来，我记得她说过今天在决赛前会来到会场。

    我扫视周遭，恰巧见到白玉璃子从阶梯现身。

    白玉学妹与我四目相对后，挥着手小跑步朝我这边靠近。

    「社长～不好意思来晚了～！」

    「还没开始，不要紧的。」

    ……

    …………白玉学妹，跑得还真慢。

    好不容易来到我面前，白玉学妹手按着胸口，长长吐出一口气。

    「呵呵，想早点见到社长，忍不住就跑起来了。」

    说完，她像是这时才发现，眨了眨眼睛注视着玉木学长。

    「该不会是毕业的玉木学长吗？初次见面，我叫白玉璃子。」

    「是啊，初次见面。我是在文艺社待到去年的玉木。那边的是月之木——」

    玉木学长说到一半，白玉学妹突然用双手包住他的手。

    「！？」

    「学长的钥匙是不是掉了？来，请收好喔。」

    「咦？啊啊，是喔。谢谢你。」

    玉木学长语气生硬地道谢，白玉学妹握着他的手，亲切地微笑。

    「真是好险呢。如果我是坏孩子的话，说不定会偷偷溜进学长家里喔？」

    「哎呀～你这样的孩子的话我很欢迎……」

    （插图014）

    这个人在惊慌之下在说什么啊。虽然强作镇定，但是笑得合不拢嘴喔。

    我感到傻眼时，月之木学姊硬是抢进两人之间。

    「你就是白玉学妹？初次见面，我是毕业的——」

    「哇～该不会是月之木学姊吗？时常听闻学姊的大名。」

    放开玉木学长的手后，白玉学妹低头致意。

    「哎呀，我留下的名声大概是恶名昭彰吧？」

    「没有，学姊就如传闻中一样漂亮，让我吓到了。文艺社的学长姊们个个都很出色，让我忍不住紧张呢。」

    「是、是吗……」

    月之木学姊的敌意被挥散，呆站在原地。

    场上充斥着古怪的气氛，白玉学妹纳闷地歪着头。

    「怎么了吗？大家要不要坐下来聊？」

    ◇

    我上过厕所，回到面朝操场正面的观众席时，四百公尺的女子决赛正好开始。二十分钟后就轮到烧盐登场了。感觉连我也紧张起来了……

    我正要走向座位时，不知谁从我身后伸出手臂，揽住我的肩膀。

    「嘿，温水。」

    「啊，学姊好。」

    月之木学姊事先埋伏般逮到我。

    不，大概真的是在这里等我吧。她那放射光芒的眼镜转向我。

    「我都听说了喔。你最近和马剃好像在搞什么吧？」

    「啊～算是吧，稍微帮忙了选举。」

    「所以当选之后你打算进学生会？」

    「我没有这个打算喔。」

    我挣脱月之木学姊的臂弯。

    「学姊二年级时当过副会长吧？那时候的选举感觉怎样？」

    「很累人啊～会长是个大而化之的人。明明邀了我，却没准备任何竞选活动。」

    「哦～所以全部都是学姊准备的啊？」

    月之木学姊摇了摇头。

    「我也一样，什～么也没做。我做的顶多只有声援演讲。」

    「咦？这样就当选了吗？」

    「这样就当选了啊。声援演讲结束后被老师们团团包围，也是宝贵的回忆呢。」

    ……你做了什么好事？

    我害怕得不敢问，月之木学姊流露怀念之情，继续说：

    「现在回忆起来，当初会长为什么要邀我呢？我成绩不好，也不是老师特别中意的学生。」

    「喔……」

    学姊没有更进一步说明，而是默默地看向操场。

    循着她的视线看过去，正好是四百公尺吊车尾的选手越过终点线的瞬间。

    同一个操场上，有赢家也有输家。

    我愣愣地注视着那一幕时，月之木学姊静静地开口。

    「选举结束后，温水打算怎么做？」

    「……咦？」

    我刚才不是说了吗？我不会进学生会。

    当我思考着问题的用意时，月之木学姊放缓了表情。

    「抱歉说了句怪话。好了，我们回到大家那边去吧。」

    「啊，好的。时间也快到了。」

    我与月之木学姊并肩而行时，她突然伸出手乱搔我的头发。

    「哇，等等，请不要这样。」

    「温水你接下来才要辛苦喔。好好加油吧。」

    现在就已经很辛苦了啊。

    我面露死鱼眼，任凭她不停搅乱我的头发。

    ◇

    女子一千五百公尺决赛。烧盐在第五跑道。

    场内广播喊出她的名字后，烧盐举起一只手臂行礼。

    与和我对决的那天不一样，此时她浑身散发着一种成熟的气质。

    我们屏息等候起跑的瞬间。

    话说回来，坐在我旁边的白玉学妹有种好闻的味道。是不是又换了香水……

    在我注意力被白玉学妹吸引时——

    ——On your marks.

    耳熟的句子自播报器传出。

    选手们在起跑线前呈前倾姿势的下一瞬间，枪声响起，同时烧盐一口气冲到了最前方。

    观众席的最前排，石蕗高中田径队的预备区立刻爆出欢呼声。

    八奈见等人不禁喊叫的同时，小鞠的双手在胸前紧握，默默地注视着比赛。

    无关乎小鞠的担忧，烧盐继续提升步调。

    与策略或抢位无关。彷佛跑道上只有自己一人，烧盐渐渐甩开其他选手。

    ——称霸全国。

    那一天在保健室，烧盐的确这么说过。

    那家伙十分笨拙，却比外表纤细更多。也因此比任何人都强悍。

    最后一圈。与第二名的差距不停拉开。接下来只剩跨过终点线。

    我无意识间站起身，呐喊烧盐的名字。

    胜败明明早就揭晓了，我自己也不晓得感情为何如此激昂。

    一旁的小鞠也站起身，大声欢呼。

    烧盐比第二名早了十几秒抵达终点后，意犹未尽般缓缓放低速度，朝着观众席高高举起左臂。

    「赢、赢赢、赢了！好、好厉害！」

    兴奋的小鞠展臂就要抱向我——又慌忙转变目标，与八奈见互相拥抱，蹦蹦跳跳。嗯，我想也是。

    我的双臂空虚地举在半空中，玉木学长拍了拍我的肩膀。

    「不嫌弃的话，我的胸膛空着喔。」

    「虽然我一度犹豫，但还是算了。」

    我们在怪怪的气氛中相视而笑，这时——

    「两位学长，我的胸膛也空着喔？」

    白玉学妹在我们面前展开双臂。

    ……咦？可以吗？

    我不禁迷惘的瞬间，月之木学姊从白玉学妹背后将她整个人抱起来。

    「好，姊姊来帮你填满心里的空缺！」

    「呜哇～月之木学姊力气好大喔。我会被带到哪里去？」

    ……白玉学妹被搬走了。

    过去想靠近玉木学长的女生，都是被她像那样排除的吧。

    没有喘息的空档，一个娇小的人影哒哒哒地跑了过来。

    是朝云同学。她的额头闪闪发光，双手的拳头不停上下摆动。

    「赢了！柠檬同学！好厉害！」

    「朝云同学也来了啊。烧盐跑起来真的很厉害呢。」

    大概是一时说不出话来，朝云同学默默地点了点头后，转身跑了出去。

    ……真是个静不下来的人。奇怪，既然朝云同学在这里——

    在朝云同学奔跑的方向上，我看见了绫野的身影。

    那家伙正用手帕按着眼角。这种心情我懂，可是你女朋友在场喔……

    虽然与我无关，但我不禁心惊胆跳之时，操场上的男子一千五百公尺竞赛开始了。

    今天的竞赛项目尾声将近。石蕗选手出赛的项目好像也结束了，接下来只剩下颁奖典礼了。

    我为了让心情平静下来，再度坐回板凳上。

    烧盐那家伙，该说是言出必行吗？以压倒性的实力差距赢得了前进全国的门票。

    称霸全国的那句话，说不定会实现喔……

    「哎呀～柠檬跑得真快耶～」

    八奈见以悠哉的语气说着，坐到我身旁。

    「那可不只是快而已喔。这成绩如果是在去年，在全国大赛也有机会站上颁奖台。」

    「哦哦，真不愧是柠檬。」

    八奈见大口咀嚼爆米花。

    「所以，还要赢几次才能进全国大赛？」

    ……嗯？八奈见的眼眸如玻璃珠般澄澈。

    「呃，刚才的比赛就确定能打进全国大赛了。」

    「哦～……」

    八奈见又抓了一把爆米花塞进嘴里。

    「咦？所以刚才的是决赛！？柠檬也太快了吧！？」

    「啊～对啊，烧盐跑很快呢。」

    我善尽八奈见负责人的职责，面露笑容点头——

    东海高中综合体育田径竞技大赛，女子一千五百公尺决赛。

    石蕗高中二年级，烧盐柠檬，这一天，她以第一名的成绩夺得全国大赛的出赛权。

    ◇

    隔天星期一。一直到了放学后，昨天的余韵仍萦绕在我心头。

    我怀着轻飘飘的心情，抬头仰望贴在走廊上的樱井的竞选海报。

    樱井面露爽朗的笑容，朝这边伸出一只手。

    还有女学生在拍海报的照片，樱井果真是个大红人耶……

    贴在旁边公告政见的海报上，陈列着学生会透明化、同好会制度改革——等等的项目。

    ……奇怪，最后好像写了一条奇怪的东西喔。

    「哼，这样胜负就揭晓了吧。」

    现身的同时撩起头发的，正是八奈见。

    她表情嚣张地轻敲写着政见的那张纸。

    「最后一条政见，是我想的。怎么样？温水也想投票给他了吧？」

    八奈见的指尖前方，写着『于学生会官网公开学生餐厅的菜单！』。

    太好了，樱井还保有理智。

    「八奈见同学有在去学餐吗？你不是都吃便当吗？」

    「肤浅，太肤浅了，温水。」

    八奈见同学从口袋中取出一包吐司边，在我眼前甩动。

    「你听好了，一边看学餐的菜单一边吃便当——你觉得会怎样？」

    「饭粒会掉满地吧。八奈见同学你常常掉饭粒啊。」

    「并没有啊？我说啊，一边看菜单一边吃，心情上就不只便当，甚至连学餐的每日套餐都品尝了喔。一餐就得到两餐份的满足感，可说是究极的减重法。」

    八奈见面露得意表情，啃食着吐司边。

    发言内容先不论，八奈见同学只吃一餐肯定是一种减重。

    我觉得合理的同时，视线转向贴在一旁天爱星同学的政见公告。

    上面是增加社团活动预算、学生会活动公开化等认真的内容。

    顺带一提，为了将天爱星同学写的原稿字数压缩至规定范围，令我煞费苦心。主要是在说服天爱星同学这点上。

    我感触良多地回忆起辛劳时，八奈见同学用吐司边戳我的脸颊。

    「唉，马剃同学的海报呢？还没做吗？」

    ……奇怪，话说天爱星同学的海报是什么状况？

    我取出智慧型手机后，彷佛看准了时机，天爱星同学捎来的讯息滑入画面中。

    ——能来平常那个地方吗？

    ◇

    天爱星阵营的竞选总部，也就是中庭的石桌。

    虽然我来了，但是天爱星同学不见踪影。

    自己把人叫来却让人等候，还真不像喜好埋伏的天爱星同学的作风……

    我环顾四周，便发现有个女生正从联络走廊朝我这边走来。

    当季动画《擦边出局少女群》的小奇卡（第二季版本）。

    紧抓住我心不放的，就是那双直条纹的过膝袜。

    于第九话的『绝对领域大作战』中，终于改成100％棉制——

    …………

    ………………小奇卡？

    不妙，我这下终于看见幻觉了吗？

    我揉了眼睛好几次，但小奇卡仍旧站在眼前。

    那少女身穿一袭石蕗高中的制服，以直条纹的过膝袜与偏短的裙摆，构筑起诱人的绝对领域。

    头发是长直发。在大约耳朵上方的高度束起一小撮头发，朝左右两侧稍微探出头，是人称披肩双马尾的发型。

    来到我眼前的小奇卡，眉毛似乎比常人稍微醒目些，颈子有颗痣——

    ………………天爱星同学，你在做什么？

    在呆若木鸡的我眼前，天爱星同学害羞地压低视线。

    「让、让你久等了，温水同学。」

    「喔、喔喔……我也才刚到。」

    天爱星同学忸忸怩怩地用鞋尖在地面上画圆。

    「你、你有发现哪里不一样吗？」

    「呃，你问哪里……」

    从头到脚都不一样啊。在我迟疑着该不该吐槽时——

    「你、你看～……这个。」

    天爱星同学满脸通红，用手掌从下方轻轻拍着朝左右两侧伸出的头发。

    「你看～看嘛。」

    「…………」

    现在到底出了什么状况？

    我不知该如何应对，索性决定这边贯彻『静观』。

    那个认真古板（？）的天爱星同学，不知是吃错什么药，现出这副德行。

    不烙印在眼底才叫有失礼数吧。

    「那个，温水同学……你看……那个……」

    气势渐渐衰竭了。天爱星同学的脸都红到脖子去了。

    我好奇她能撑到何时而静观，天爱星同学开始浑身颤抖。脸色已经突破了通红的极限，反倒开始发青了。

    「天爱星同学，我看还是——」

    「温水同学！你至少也说句话吧！？」

    天爱星同学终于怒气爆发。

    「不，那个，我完全跟不上事情发展……」

    「可是温水同学，你说过你喜欢这个角色吧！？」

    天爱星同学直逼向我面前。

    我是喜欢，但为什么你会打扮成这样？

    我完全陷入混乱时，不知何人靠近我们。

    「不好意思，在两位正忙的时候打扰～我是新闻社的～」

    看向对方，是个手拿单眼相机的女学生。

    裙摆特别短的新闻社女生面露笑容行礼。

    「马剃同学，竞选海报的照片还没交吧？」

    「呃，我记得我已经把照片传给老师了。」

    「那张是去年新学生会刚上路时的纪念照吧？老师说要三个月内拍的近照才可以喔。」

    哦，是这样喔。原来规定得这么细啊。

    天爱星老实地低下头。

    「那真是不好意思。那么改天我会过去新闻社拍照。」

    「可是老师叫我今天就要交出照片。那，我们走吧。」

    新闻社女生面露亲切的业务笑容，抓住了天爱星同学的手臂。

    「咦！？请等一下。我现在穿成这样——」

    「今天之内就要连海报印刷都解决才行。老师刚才就说在等你喔。」

    「咦？不是，那个——」

    ……天爱星同学被拖走了。

    她虽然对我投出求助似的眼神，但既然是规定，我也爱莫能助。

    我独自一人被留在中庭，仰望还很明亮的天空。

    到头来，天爱星同学的Cosplay究竟是怎么一回事……？

    ◇

    车站前常盘通商店街的北端，有一间咖啡厅。

    位在建筑物二楼的这间老店气氛沉稳，顾客群的年龄层也偏高。

    「不是……真的不是那样……」

    冲击的Cosplay事件之后过了两天。

    天爱星同学趴在桌子上发出呻吟声。

    发型已经换回平常的样子，对此我稍有遗憾。

    「话是这么说，不过你摆的姿势还满有兴致的嘛？该不会其实很开心？」

    映在手机萤幕上的是学生会长候选人马剃天爱星的竞选海报。

    天爱星同学两手食指作势转圈，也就是小奇卡的标准动作。

    「我有什么办法！人家叫我摆出姿势，之前练习的姿势不由得就——等等，不要在这种地方看照片！」

    天爱星同学猛然撑起上半身。嗯，太好了，看来很有精神。

    天爱星同学似乎这才察觉周遭状况，狐疑地扫视咖啡厅店内。

    「……话说回来，为什么把我带到这里？」

    「是马剃同学自己说想离开学校的吧。还有这个，因为你一直没回话，我就自己帮你点了。」

    把红葡萄果汁摆到她面前，天爱星同学神色疑惑地拿到手中。

    「……不是咖啡啊。」

    「马剃同学不怎么喜欢咖啡吧。」

    「你怎么知道我不爱喝咖啡？」

    「因为之前去桌游咖啡厅的时候，你加了很多砂糖和牛奶一口气喝完。」

    我拿起自己那杯葡萄汁。

    「况且，我想疲劳的时候喝点甜的比较好。平常我都点咖啡，不过我也久违地点来喝喝看了。」

    天爱星同学默默地凝视着玻璃杯，最后轻轻叼起吸管。

    「好好喝……」

    「对吧？听说用的是从安昙野的酒庄采的葡萄。」

    天爱星同学似乎也稍微镇定下来了。

    我也想喝果汁时，天爱星同学不愉快地盯着我，低声嘀咕：

    「……果然很熟练。」

    「咦？什么意思？」

    「温水同学，你好像很习惯对待情绪低潮的女生呢。像是把人带进从外面看不见的宁静咖啡厅，端出甜的哄骗人家。」

    我好像被说得很难听。

    「只是小时候家人带我一起来过而已。」

    「原来如此，所以把女性带进这里才会成为你的常套手段。」

    真是失礼。除了佳树之外，我带到这里来的人，天爱星同学可是头一个喔。

    那么，既然天爱星同学恢复平常心了，差不多也该切入正题了。

    「所以，你之前为什么打扮成那样？」

    「噗」的一声，天爱星同学喷出了果汁。

    天爱星同学用手帕按住嘴，湿润的双眼由下往上看向我。

    「那个理由，有必要说明吗？」

    「因为也和选举有关啊。」

    「那个，那是……就是……」

    唔嗯，那我也别无选择了。

    我将海报照片显示在智慧型手机的萤幕上后，天爱星同学便连忙将身子压过来。

    「是美人计！我想用美人计，让温水同学来当我的推荐人！」

    天爱星同学气喘吁吁，吸了一口葡萄汁。

    原来我在大庭广众下被施展美人计了吗？完全没注意到喔。

    「所以说，你打算打扮成那样，然后说『拜托你当我的推荐人喵』吗？」

    「是的！但是我不会加上喵！」

    天爱星同学已经完全放弃掩饰，将空的玻璃杯用力放回桌上。

    「那么我们言归正传。可以请你重新考虑吗？我希望温水同学为我声援。」

    天爱星同学挺直了背脊，以认真的口吻说道，双眼笔直地凝视着我。

    ……为何要这么执着？我在迟疑中开口：

    「为什么是我？老师帮你介绍的人，一定能拿到更多选票喔。」

    「也许是这样。但是我想拜托你。」

    这样又绕回原点了。如此一来只能清楚回绝了。

    我下定决心要开口时，天爱星同学先发制人般开了口。

    「你知道为什么我当初会被指名为副会长吗？」

    「我记得好像是志喜屋学姊推荐你的吧？」

    天爱星同学点头后，注视着已经空无一物的玻璃杯。

    「为什么要推荐在那之前几乎没有交谈过的我？为什么要指名我当副会长？我一直害怕得不敢问。」

    天爱星同学回顾当初记忆般继续说：

    「起初会认识学姊们，是当志工去帮忙学生会的时候。坦白说，我当时也没有派上什么用场。」

    「不，这不一定——」

    天爱星同学缓缓地左右摇头。

    「你也知道，我是个古板又不知变通的女生，也曾经和周遭旁人起冲突，靠会长出面帮忙打圆场。所以我去年被找去当会长选举的推荐人时，原本还以为是说笑。」

    天爱星同学用双手握住装水的玻璃杯，注视着摇晃的水面。

    「现在回想起来，那也许是出自同情。她们觉得老是和旁人起冲突的我可怜，才好心把我放在方便照顾的位置也说不定。」

    天爱星同学抬起脸。

    「所以我想赢。为了作为对等的友人，今后也和学生会的大家继续相处下去。」

    「这个目的——为何需要我？」

    「因为会长她们是那么看重你。我觉得在你身上，能找到我所缺少的东西。」

    认真的眼神。

    我无法转开视线逃避天爱星同学的眼眸，面露模棱两可的笑容。

    「讲得也太夸张了。」

    「一点也不夸张。」

    天爱星同学以毫无迷惘的口吻回答。

    「我去年在放虎原会长的声援演讲时，两条腿不停打颤。」

    「对喔，马剃同学也上台声援演讲过啊。」

    「……当时温水同学应该也有听才对。」

    嗯，听你这么一说，是有这种感觉。

    天爱星同学清了清嗓子，回到正题般再度开口：

    「那个女人是不是得意忘形？有会长撑腰就狐假虎威——这一年来，一直有人这样说我。今年我自己成为候选人，要与去年的会长以同样的立场站到台上。坦白说，我害怕到不行。」

    天爱星同学手按胸口，缓缓地深呼吸，真心诚意地说：

    「我想要你的话语。徒具形式也好。只要你为我说话，我就觉得能抬头挺胸地站在台上。所以——」

    天爱星同学笔直地凝视着我。

    「只要现在就好——可以请你只推我一个人吗？」

    天爱星同学这段也像是独白的话语告终。

    那超乎想像的率直，让我找不到可以回应的话语，只是保持沉默。

    「不好意思，突然说这些。」

    「不会，我是无所谓……」

    沉默再度造访。

    大概是想要改变气氛，天爱星同学叫住了一旁经过的店员。

    「我请客。就点杯咖啡吧。」

    「咦？你不是不爱喝咖啡？」

    「是啊，我不爱喝。但是温水同学喜欢的话，我想慢慢习惯。」

    为何我喜欢咖啡，你有必要去习惯……？

    我感到不可思议时，天爱星同学从书包中取出摺叠起来的纸张。

    「话说回来，我把校园新闻印出来了。选情分析意外地写得有模有样喔。」

    天爱星同学在桌面上摊开那张纸。

    「新闻社还有做选情分析喔。」

    「好像是做了投票对象的问卷调查。请看这里。」

    天爱星同学的纤细指尖，指着标了支持率的圆饼图。

    樱井45、天爱星同学30、尚未决定25——

    甚至还记载了各年级与男女分开统计的结果。

    樱井主要是在一、三年级的女生与二年级生的支持较稳固，天爱星同学则在一年级男生中颇有优势。

    目前看起来没有任何数据显示有利。

    看着天爱星同学严肃的表情，我拿起了校园新闻。

    「不过这份新闻写了一堆八卦，我觉得别太在意比较好喔。还把樱井写成女性公敌，根本就乱写一通。」

    虽说是敌人，但是樱井被诽谤中伤，还是教人不舒服。

    听了我这句话，天爱星同学面露难以名状的复杂表情。

    「你怎么了？」

    「……我想这里写的『女性公敌』指的是温水同学。」

    「啥！？别说是脚踏两条船了，我连女朋友都没交过喔？」

    「是的，我明白。因为温水同学比较喜欢男性嘛。」

    「不，您误会了。」

    我不禁以敬语反驳后，天爱星同学立刻取出了笔记本。

    「你在做什么？」

    「不好意思有点突兀。关于需要审议的事项，我会像这样先写在笔记上，之后恢复理智时再重新读过。」

    原来你现在失去理智了啊。你刚才滔滔不绝地讲了不少喔。

    天爱星同学口中念念有词，在笔记本上写着。

    「呃，温水同学……不分男女……见一个……爱一个……」

    这也是误会。请不要边写边偷看我。

    我很想吐槽，但是现在必须忍耐。不可以打扰病人的疗程。

    为了逃离危险的目光，我将视线转向校园新闻。

    我把文中写的当作自己，重新读过一次后，便觉得这写得还真口无遮拦。

    我好像是个到处挑逗女生，最后却不跟人家交往的烂人。

    还有，这个『二年级的美少女A子』，就是Y奈见A菜同学吧。她被写得比我还惨，内容却与我的认知莫名相符，这点格外恼人……

    ——啪，阖上笔记的声响结束了我的沉思。

    「让你久等了。我已经没事了。」

    天爱星同学面露清爽的笑容，短暂犹豫后喝了一口刚送上桌的咖啡。

    「黑咖啡没问题吗？」

    「这个嘛，也许意外地可以。不过我加点砂糖好了。」

    看着加入砂糖的天爱星同学，我不禁莞尔，啜饮一口咖啡。

    「……这个好像特别好喝？你点了什么？」

    「吉力马札罗咖啡。因为上面写说这是咖啡之王。」

    那种的很贵喔。这杯咖啡，你真的会请客吧……？

    某人害我犯了疑心病，我啜饮着咖啡时，天爱星同学的视线短暂飘向手表。

    「那么，下午六点差不多到了。」

    嗯？是有门禁之类的吗？

    天爱星同学从书包中取出智慧型手机。

    「校园新闻第二号会在六点上线。」

    「欲知详情上网看的那个？」

    「虽然我不太清楚制度是怎样，但是只要付钱好像就能阅读全文。上面说一年方案比较便宜，我就订阅了。」

    这样啊，不太清楚的契约别乱签比较好喔。

    以认真的表情注视着手机的天爱星同学，突然间将萤幕转向我。

    「温水同学，请看！」

    「呃～马剃副会长的公开Cosplay只在付费版公开——」

    「不是那边！」

    天爱星同学要我看的是最新版的投票意愿问卷调查。

    樱井从上次略微增加至50。而天爱星同学——上升15个百分点，来到45了。

    天爱星同学双眼亮起，兴奋地将上半身前倾。

    「大进步！果然是我的政见公告打动大家的心了吧？」

    「也许吧。可以给我看一下细项吗？」

    我将最新报导与上次的投票结果互相比较。

    「从上次至今明显成长的是男性票。女性票反倒减少了。呃，虽然难以启齿……」

    我语带踌躇，天爱星同学的身子猛然靠近。

    「是什么？请不要客气，尽管直说。」

    「是Cosplay的选举海报——吸引了男生吧？」

    听见这句话，天爱星同学猛然一震。

    「我、我那个打扮……？」

    嗯，哎，其实还不错喔。

    我向天爱星同学借了智慧型手机，浏览报导。

    「啊，新闻社的官网有讨论区啊。」

    「讨论区？上面写了什么？」

    「呃～你等一下。」

    我遮住智慧型手机的萤幕不让天爱星同学看。

    这可是高中生匿名发表意见的讨论区，天晓得上面写了什么。

    『这个人为什么在Cosplay？』『太夸张了吧。』『出卖色相喔？』

    果然否定的意见也不少。

    海报照片采取由下往上的构图，加上天爱星同学惊慌失措的表情，拍得十分有魅力，不过对于认真向学的石蕗生，刺激似乎太强了。

    紧接在后的讨论也很有炎上的潜力，这可不能让天爱星同学看到——

    『绝对领域！我绝对会投票！』『小奇卡、小奇卡！』『小奇卡棒棒！』

    ……嗯，不能让她看到呢。

    「怎么了吗？」

    「这些本人还是别看比较好——」

    「那种打扮都在全校学生面前公开了，已经太迟了。」

    天爱星同学说得非常合理，她从我手中取走智慧型手机。

    默默凝视着萤幕的天爱星同学眯起眼睛。

    「……有预料中的反应，也有未曾预料到的反应。」

    「这个嘛，那个像在喊口号的，是第一季第八话棒球回的梗……」

    「那个我知道。打扮成那样之前，我把《擦边出局少女群》的动画十二集都看过了。」

    是喔，第二季已经开播了，最好也看一看。

    「请问这句『我也被擦得快出局了』是什么意思？」

    「谁晓得。绝对不可以上网搜寻喔。」

    出乎意料，石蕗生中有不少似乎能成为朋友的人。

    总而言之，天爱星同学似乎不介意讨论区上的诽谤与中伤（？）。

    虽然是件好事，不过令人在意的是投票倾向的民调结果。

    差距虽然缩小到5个百分点，但是剩余的游离票也是5个百分点。

    假使投票比例真的按照民调结果，要赢得所有游离票才能勉强打平。

    若要获胜，就必须进攻樱井的支持群体。

    「上面也有人在讨论樱井，支持者好像是女生居多呢。」

    「在讨论区上看到的性别，别相信比较好喔。」

    我指点她网路的基本常识，同时想着樱井阵营。

    如果樱井就这么获胜了，八奈见就会成为学生会副会长。

    文艺社本来人就不多，近来小鞠的写作步调也变慢，我想避免流失更多战力……

    默默看着萤幕的天爱星同学大大吐气。

    「一直到上星期我都觉得没有胜算，不过现在应该有办法较量了。」

    天爱星同学以认真的眼神凝视着我。

    「我想要赢。不是靠同情，而是以自己的能力当上学生会长。我不会强求你加入学生会。请你当推荐人，助我一臂之力。」

    ……她之所以会成为副会长，绝不是因为同情。

    不管是会长、志喜屋学姊或樱井，都信任着天爱星同学。

    但是在信任的同时，肯定也同样担心着她。

    所以，天爱星同学一定无法彻底相信自己。

    我喝完了几乎凉掉的咖啡，放下杯子。

    「……我不想打会输的比赛。」

    天爱星同学默默点头。

    「如果要我当推荐人，我只有一个要求希望你能接受。」

    「！？该不会是——」

    「不，不是你想的那样。」

    我打消天爱星同学粉色的误会，将选举海报映在智慧型手机的萤幕上。

    「当天的候选人演讲，我希望马剃同学用这个打扮上场。」

    「这点小事当然——你说什么！？」

    天爱星同学凝视着选举海报的照片。

    「……原、原来如此，是这么一回事啊。」

    「你懂了吗？」

    天爱星同学深深点头。

    「简单说就是羞耻玩法——」

    「不是。」

    这个人没救了。

    我怀着向小孩子解释般的心情开始说明：

    「按照刚才的问卷结果，一年级、特别是男生的支持率成长最多吧？」

    「可是女生票变少了吧？」

    「女生票下滑的部分是二年级。出风头的同年级生容易吸引批评，这部分只能放弃。再给我看一次调查结果。」

    天爱星同学再次用手机开启了校园新闻，放到桌面中央。

    「樱井则相反，他成长的几乎都是女生票。而男生票岂止是遭遇瓶颈，在一年级与三年级生间甚至减少了。」

    我和天爱星同学一起低头看向手机萤幕。

    「樱井的确可爱，但是不容易凝聚男生间的人气。反而是觉得他有魅力的男生，很可能会为了否认自己的想法，去投票给他的对手。」

    「…………真的有这种心理吗？」

    真的有。详情我不会多提。

    「简而言之，就是用小奇卡的打扮针对男生票重拳出击。要从现况逆转胜利，除此之外别无他法。」

    「不会被女同学们讨厌吗？」

    「现在已经没人气了，不用担心。」

    「呜！」

    天爱星同学捂住胸口。事实虽然残酷，但不接受就无法向前进。

    「怎么样？」

    「……一、一言为定喔。」

    天爱星同学红着脸，脸庞自手机萤幕抬起。

    「如果下星期一的投票日，我用那个打扮上台演讲——」

    「对，我就会——成为天爱星同学的推荐人，进行声援演讲。」

    我也从手机萤幕抬起脸。

    身子向前倾的我，眼前恰巧就是天爱星同学的脸——

    「「！」」

    我们连忙向后抽身，为了排解尴尬而拿起咖啡杯。

    「……呃，那就照这样决定吧。」

    「啊，好的，麻烦你了。」

    于是在同一时间想喝咖啡的我们，察觉杯中已经空无一物，苦笑着将杯子放回桌面。

    「怎么了吗？温水同学，你好像在忍笑喔。」

    「天爱星同学才是，用不着忍耐喔。」

    四目相对，我们终于笑了起来。

    对着彼此笑了好半晌后，天爱星同学用手帕轻拭眼角。

    「请不要害我笑成这样。还有温水同学……」

    「怎样？」

    「请不要用名字称呼我喔。」

    天爱星同学这么说，语气听起来分外愉快。

    ◇

    决定要成为推荐人之后，时间转瞬即逝。

    投票日前夕的星期天夜里。

    坐在自己房间的书桌前，我朝着切换成扩音模式的智慧型手机说：

    「那么，我们的演讲稿就这样完成了。」

    『好的，辛苦了。』

    智慧型手机另一头的天爱星同学客套地打过招呼后，不知为何嘻嘻轻笑。

    「有什么好笑的？」

    『没什么。最花时间的居然是声援演讲的讲稿，总觉得很有趣。』

    呜……被指出这一点，我身为文艺社员的面子实在挂不住。

    「不是啦，因为声援演讲的讲稿是最后才准备的嘛？毕竟也不能和马剃同学的演讲内容重复。」

    『哎呀，今天不用名字称呼我啊。』

    「呃，这个嘛……」

    完全被她调侃了。

    我找到时机结束对话后，将蓝色钢珠笔放在笔记本上。

    「好了，接下来只要把原稿整理好……」

    天爱星同学的优势，在于打从一年级就有副会长的经验。

    我的声援演讲首先要强调过往的种种实绩。

    用意是在后面天爱星同学的候选人演讲中，塑造放虎原政权继承人的印象。

    演讲时间是明天午休结束后。

    因为演讲一结束就直接投票，演讲的印象会直接左右结果——

    「兄长大人，不稍微休息一下吗？」

    这时，佳树的声音突然自耳畔传来。

    佳树在桌面上摆了个冒着水气的茶杯。这香气应该是洋甘菊茶。

    「你什么时候就在我房间了？」

    「不晓得，是从什么时候呢？」

    佳树开玩笑般回避问题后，拉开房间的窗帘。

    「今晚有云，看不见月亮呢。」

    「是啊，深夜好像会开始下雨喔。」

    我一边闻着洋甘菊的茶香，一边让身体靠向椅背。

    虽然原本没有这个打算，但是半推半就地答应当推荐人了。

    这样下去，最后会不会落得连副会长之位也接下啊……？

    ——虽然不信任，但是我相信。

    我忽地回忆起小鞠的话语。

    唯独这点我该拒绝。别看我这样，我也是懂得说NO的男人。

    喀锵一声，我将茶杯放回碟子上，这时窗边的佳树彷佛在等这时机般转过头。

    「兄长大人要进学生会吗？」

    「我没有这个打算——咦？你知道学生会选举的事喔？」

    「是的。只要有关兄长大人，佳树就无所不知。」

    佳树说着令我笑不出来的玩笑，轻轻坐在床畔。

    佳树和学生会的人彼此认识，消息全都走漏了吧……

    「我不会进学生会喔。马剃同学要参选学生会长，我在帮她。」

    「是这样啊。有点遗憾呢。」

    佳树坐在床边，摇摆着双腿。

    「明年开学典礼时要是有兄长大人照顾，一定会很美妙的说。」

    「在烦恼这个之前，佳树要先考上才行喔。」

    我用有些坏心的口吻说完，佳树鼓起脸颊，躺到床上。

    「佳树有在用功念书啊。要坐在兄长大人的后面，一起到石蕗上学。」

    「自行车不可以双载喔。」

    近来佳树的确开始认真念书，到石蕗露面的次数也减少了。

    我不理会在床上翻来覆去的佳树，开启了笔记型电脑的电源。

    之后大概过了二十分钟。

    我整理好声援演讲的讲稿，在椅子上伸了个大大的懒腰。

    ……话说回来，佳树好像一直很安静耶。

    我看向床铺，便见佳树把枕头抱在怀里，睡得正香甜。

    （插图015）

    我把棉被盖到佳树身上后，为了关起半开的窗帘而走向窗边。

    ——新闻社官网的讨论区，在那之后留言仍然在增加。

    天爱星同学的Cosplay依旧评价两极，男生人气上升的同时，来自女生的批评也在持续着。

    虽然嘴巴上说不在意，但是她都特意向我报告了。想必天爱星同学一定也觉得受伤吧。

    让她打扮成那样站在选举演讲的台上，我这个选择到底是对是错——

    「绝对要让她赢啊……」

    我自言自语并看向窗外，注意到家门前有个左摇右晃的黑影。

    ……？那是什么？我定睛仔细一看，似乎是个人影。

    能像那样融入黑暗的人，我只认识一个而已喔……

    这时，摆在书桌上的智慧型手机，传出了玻璃碎裂的高亢通知音。

    ——是志喜屋学姊传的讯息。

    ◇

    在自家的玄关大门前方，我将行动电源递给志喜屋学姊。

    「谢谢……明天……还你……」

    被她叫到家门外的理由出乎意料地单纯。因为智慧型手机电量快耗尽了，希望我借她行动电源。

    回想起来，曾有个女生用同样的理由闯进我家啊……

    智慧型手机的光芒微微照亮志喜屋学姊的脸庞。

    我不经意地看着那张脸，半是下意识地开了口：

    「学姊怎么会在这里？」

    「因为最近……在练习搭公车和电车……的关系？」

    志喜屋学姊歪着头，说出了彷佛漫画中的千金大小姐的台词。

    「仔细一想，学姊上学时都是请家里的人载你到途中的样子？」

    「嗯……不知不觉间……就会被载到陌生的地方……所以我不搭公车……」

    志喜屋学姊轻盈摇晃。

    「但是……也不能……永远这样……」

    志喜屋学姊的话语消散在夜色中，不知为何遗留在我心里。

    那究竟是何种情感，在我的心接受之前，志喜屋学姊的视线开始游移。

    「电车站……在哪……？」

    「喔，沿着这条路笔直走过去，就会到大街上。」

    「知道了……不好意思……这么晚打扰……」

    志喜屋学姊摇摇晃晃地迈开步伐，但她随即停下脚步，背对着我低声说：

    「那个啊……你和……天爱星……」

    「天爱星同学怎么了吗？」

    志喜屋学姊只是沉默。

    我再一次想开口时，明明没有风，志喜屋学姊的发丝却摇摆起来。

    「没事……没什么……」

    志喜屋学姊再度迈开步伐，那背影看起来迷蒙得彷佛会消融在夜色中。

    萦绕着好像会直接消失在某处似的虚幻阴影——

    因为这种感觉，我向前踏出一步。

    「——那个，我送学姊到半路上吧。」

    志喜屋学姊的动作停止。

    她的颈子缓缓转动，白色眼眸映出我。

    「嗯……拜托了。」

    ……抵达大街前的短短几分钟，我们默默地不停向前走。

    志喜屋学姊的脚步比起平常还要缓慢一些，我有这种感觉。

    一面揣摩着缠绕于胸口的感情究竟为何物，我们两人走在星期日的夜里。

    虽然有许多话想说，但是不知为何没有任何一句说出口。

    大街上车流往来的声音从远方渐渐靠近。

    我怀着意犹未尽的心情向前走，来到了路面电车经过的大街。

    在十字路口旁，写着『常夜灯』的偌大石灯笼发着光。

    路面电车站就位在那前方，跨越斑马线的道路中央处。

    志喜屋学姊在石灯笼前方停下脚步，突然开了口。

    「那个啊……我……现在……也会骑自行车……」

    「咦？那样不危险吗？装辅助轮之类的会不会比较好？」

    尽管我说了失礼的话，但是志喜屋学姊愉快地摇晃起身子。

    「能办到的事……一点点变多……很开心……」

    「这样啊。很好啊。」

    志喜屋学姊变多的一点点，正慢慢地拉远我与这个人之间的距离。

    ……明天，天爱星同学或樱井的其中一方会成为下届学生会长。

    运动会一结束，本届学生会就会解散。

    志喜屋学姊与放虎原会长，都会为了春天毕业后的出路正式开始准备吧。

    ——毕业只在转眼间喔。

    月之木学姊曾几何时这么说过。上星期见到的学姊已经完全像个大人。

    看似一切没变，却已不再是当初在石蕗的月之木古都。

    所有人都会抛下我成为大人，这种焦躁涌现心头，但是每个人都一样，一旦时候到了，就必须走向下一个世界。

    就算没做任何准备，就算没有任何觉悟，我也迟早会改变——

    当我沉浸于愁绪之中时，志喜屋学姊注视着我。

    「怎么了……吗……？」

    「只是在想，志喜屋学姊是个大人了呢。」

    听了我老实说出的一句话，志喜屋学姊一脸疑惑地摇头。

    「我……还是小孩子喔……？」

    志喜屋学姊露出带着几分迷惘的神情，朝我伸出手。

    但是在触及我脸庞的前一瞬间，她的手停止了。

    「那个啊……明天的选举……天爱星……」

    果然志喜屋学姊是为了明天的选举来见我的。

    志喜屋学姊和天爱星同学那么亲近，而且对手还是樱井，肯定会担心吧。

    我等候着下一句话时，志喜屋学姊罕见地欲言又止。

    「学姊？」

    「那个啊……我啊……演讲……」

    志喜屋学姊再度语塞。

    就这么缓缓地左摇右晃的志喜屋学姊，忽然神色悲伤地压低视线。

    「天爱星……真的在……躲我……？」

    「没有那回——」

    这次轮到我语带踌躇。

    天爱星同学在这次选战中，一直与现任的学生会保持距离。

    逃离学姊们的光芒——为了靠自己发光。

    「学生会一结束……天爱星……马上就回家……」

    「那不是因为在躲志喜屋学姊……」

    ——她想避开的不只是志喜屋学姊。

    但是这样的事实，对眼前这个人而言不构成任何安慰。

    「……最近她在陪我写声援演讲的原稿。我想她是因为这件事特别忙。」

    志喜屋学姊没有回应我的话，任凭身形融入夜色般静伫。

    行经国道一号线的车辆车头灯照亮她，将志喜屋学姊从幽暗中拖回现实。

    「你要……让天爱星……赢喔……」

    用微弱到几乎听不见的声音说完，她悠悠地向后退。

    「学姊，前面！」

    志喜屋学姊一脚踏向红灯亮起的斑马线——我一把抓住她的手，使劲拉回来。

    志喜屋学姊没有抗拒，像是扑进我的胸怀般倒向我。

    刚才志喜屋学姊所在之处，卡车发出轰隆隆的声响驶过。

    ……我将志喜屋学姊抱在怀里，调匀呼吸。

    志喜屋学姊虚脱似地将体重倚向我，以遮盖了感情的白色眼眸仰头看过来。

    那身体娇小得出乎意料。

    好像只要稍微使力，就能够挤碎似的。

    「那个，学姊——」

    「……有点……痛。」

    无意识间手臂使上了力气。

    即使我放下圈住她的手臂，志喜屋学姊依旧让身子倚在我胸前，一动也不动。

    带着些许汗水气味的香味，撼动我的意识。

    「没有受伤吗？」

    「嗯……没事……」

    维持着这个姿势，志喜屋学姊的指尖捏住我的衬衫，仰起头用那双眼眸看向我。

    我稍微挪开视线，同时向后退开一步。

    通往路面电车站的斑马线号志灯，已经变成绿色。

    「学姊，绿灯了喔。」

    尽管如此，志喜屋学姊依旧站在原地不动。

    「真的没问题吗？回家路上请小心喔。」

    志喜屋学姊悠悠摇晃，看似要迈开步伐时——

    「……我打。」

    咚。她往我的胸口挥出一记孱弱的拳头。

    「那个，学姊？」

    志喜屋学姊默默转身背对我，朝着路面电车站，迈步跨越斑马线。

    然后，她在途中只回头了一次——以细如蚊蚋的声音嘀咕。

    那有如呢喃的细微声响，几乎被车辆往来的噪音掩盖。

    那勉强抵达我耳畔的细语声，似乎是这么说的。

    ——女性公敌。

    ◇

    投票日的早晨。

    天空被黑压压的厚重云层笼罩，城镇彷佛被黎明前的昏暗所笼罩。

    我比平常更早到校，走过四下无人的百合木林荫道，一边重读声援演讲的讲稿。

    声援演讲是三分钟。开场先介绍天爱星同学的为人，之后则是强调过往实绩。

    必须留意着不要流于自吹自擂，并接续到天爱星同学的候选人演讲——

    「……感觉好像紧张起来了。」

    虽然凭着气势扛起这职责，早知如此就该拒绝……

    我为了让心情镇定下来而看向操场，田径队目前正在晨练。

    继一千五百公尺之后，烧盐于三千公尺的项目也打进了全国大赛。

    在田径队中同样格外醒目的她，不同于正在暖身的队员们，已经开始练跑。

    当我远远地眺望她时，八奈见无忧无虑的说话声向我传来。

    「你很有干劲耶，温水。」

    「早安。八奈见同学才是，比平常更早到吧？」

    「算是吧，我也充满了斗志喔。来，这个给你吃。」

    八奈见把装着炸猪排三明治的盒子塞给我。

    近来八奈见一直在吃炸猪排三明治，口袋里则装着制作时剩下的土司边。

    我们两人边吃边走过林荫道，不知怎地紧张感也渐渐消退了。

    八奈见边走边掉面包屑，好像还有麻雀跟在后头……

    「话说回来，八奈见同学也要上台声援演讲吧？在全校面前上台，没问题吗？」

    八奈见将沾在指头上的酱料舔干净，对我眨了眨眼。

    「对策万无一失啦。你也听过吧，把人当成蔬菜就好。」

    「喔喔，把观众当成马铃薯或南瓜之类的啊。」

    八奈见点头，拿起下一份炸猪排三明治。

    「就是那个。马铃薯能做成奶油马铃薯，南瓜则是炖煮特别好吃，红萝卜生吃也行吧？只要这样想就一点也不紧张——糟糕，口水都滴下来了。」

    一边吃炸猪排三明治一边想像其他食物的女人。这家伙从一大早就发挥本色。

    话说这个炸猪排三明治，猪肉的油脂与酱料的浓郁口味，被高丽菜丝完美地中和。我原本以为一大早吃炸物会很腻——

    「……满好吃的耶。」

    我不禁说出感想，八奈见便洋洋得意地挑起嘴角。

    「对吧？拿去多吃点吧，温水。你该多长点肉。」

    「这是要讨吉利（译注：日文中「炸猪排（とんかつ）」包含了「胜利（かつ）」的音，时常用在求好兆头。），所以不该给我，应该给樱井吧。」

    我不知为何有些烦闷地说道，八奈见脸上的笑容顿时漾开。

    「哦～你该不会是嫉妒了？因为我和樱井走得很近？」

    「啥？没这回事。」

    我断然否认，八奈见连连拍打我的肩膀。

    「别吃醋别吃醋。选举就到今天为止不是吗？明天起又是普通朋友了，你这样紧张兮兮的也没意义嘛。」

    「话是这样说没错——等等，我并没有吃醋。」

    「温水真是不老实耶～你大可承认喔？」

    还是老样子教人心烦，不过八奈见说的话也有道理。

    天爱星同学希望学生会的成员能将她作为一个独立的人认同。

    然而那与破坏当下的关系只有一线之隔——

    「……也许真的像八奈见同学说的。」

    「咦？那是什么意思——」

    糟糕，我自己在心里迳自下结论的坏习惯又来了。

    我停下脚步，转过身正色面对八奈见。

    「我只是觉得，理所当然般待在身旁，有些事反而难以察觉。八奈见同学应该也明白吧？」

    「是、是啊，该说是亲身经历吧，我是明白啦。」

    八奈见动作僵硬地反覆点头。

    太好了，你明白就好。我加快速度继续说道：

    「所以我觉得，为了更进一步，需要有一个机会重新确认彼此的心情或关系。所以应该好好将心情——」

    「唉！？等一下等一下！这不是一大早该在学校讲的吧！？」

    「？可是今天下午就要投票了喔。」

    八奈见顿时浑身僵住。

    「……温水，你是在说什么？」

    「我是在说马剃同学的事。就算明天起恢复为普通朋友，但那个人老是全力冲刺，看不见周遭吧？和学生会的那些人像是不欢而散也不好——咦？你怎么了，八奈见同学？」

    「…………」

    八奈见沉默不语，大口咬了炸猪排三明治之后，用力踢我的脚。

    「好痛！？咦，怎么了！？」

    「温水你问题就出在这里啦！」

    八奈见使劲甩开脸，抛下我一个人走进校舍。

    咦咦……到底是怎样？我拖着发疼的脚走进校舍后，险些撞上不知为何停下脚步的八奈见。

    「八奈见同学，这次又怎么了？」

    「温、温水同学，早安。」

    站在鞋柜前方的那人是小奇卡……不，是特殊造型的马剃天爱星。

    直条纹过膝袜与绝对领域。

    束起的头发朝左右两边翘起的披肩双马尾——

    天爱星同学面红耳赤地以双手食指对准八奈见。

    「八、八奈见同学！虽然不好意思，但我们也会拿出全力获胜的……！」

    见到天爱星同学以生硬的小奇卡招牌姿势指着自己，八奈见有些吓到般点头。

    「嗯、嗯……彼此都好好加油吧。」

    八奈见，别用那种眼神看我。

    ……我自己也有点退避三舍。

    ◇

    午休已经结束，在体育馆嬉戏的学生们也回到教室了。

    「候选人与推荐人都到齐了吧。那么接下来开始说明流程。」

    在寂静的体育馆舞台上，放虎原会长依序看过我和天爱星同学、樱井与八奈见等四人的脸庞。

    「一开始是弘人组。八奈见的声援演讲是三分钟，弘人的候选人演讲则是五分钟以内。结束后轮到温水与马剃上场。演讲结束后，学生们要尽速回到教室进行投票。希望各位严格遵守时间。」

    确认所有人都理解后，会长嘴角浮现笑容。

    「大家都彼此认识，有种难以言喻的心情，不过这也是种缘分吧。各位都为了不留下遗憾，尽情表达心中想法吧。石蕗生一定会接受的。」

    会长还要继续说的时候，一道幽暗的影子在她背后升起。

    「云雀……老师……在叫你……」

    「知道了，我马上过去。」

    放虎原会长一甩长发转过身，但志喜屋学姊仍站在原地。

    一瞬间——要这样形容稍嫌太长的一段时间，她凝视着天爱星同学。

    在沉默产生意义之前，志喜屋学姊一语不发地转身离去。

    被留在舞台上的我大大地吐气。

    我身旁的天爱星同学在胸前握紧了双手，微微颤抖。

    「你在紧张吗？」

    「是、是的。全校学生马上就要聚集到这里了。我才想问，温水同学没问题吗？」

    「虽然紧张，但这次是合法的。也不用担心被抓，就这点来说算是轻松吧。」

    「……温水同学，你和我在说同一件事吗？」

    哎呀，说溜嘴了。我已经金盆洗手，再也不搞犯罪了。

    「马剃同学呢，演讲都准备好了？」

    我不着痕迹地转移话题后，天爱星同学脸色苍白地点头。

    「因为副会长的工作，我已经习惯在大家面前讲话了。但是一想到要用这么羞人的打扮站在全校学生面前就……」

    「就怎样？」

    咕噜，咽下唾液的声音。长着痣的白皙颈子诡异地起伏着。

    「感、感觉身体好像在发烫，心跳得很快……这果然是紧张的感觉吗？」

    ……天爱星同学，该不会又要推开全新的奇怪大门了吧？

    算我求你了，心中的大门记得锁好。

    ◇

    没过多久，学生们开始进场。

    我们四个人的等候区位在学生们右手边的舞台侧边。

    在隔着舞台的另一端，会长与志喜屋学姊正和老师确认流程。

    听见体育馆内的嘈杂声渐渐增加，我静不下心地反覆深呼吸。

    就算想复习演讲的讲稿，也看不进去，因此我放弃努力并抬起脸。

    樱井与八奈见两人看起来没有特别紧张，两人小声地有说有笑。

    ……总觉得那两人距离是不是有点近？不，也没那回事吧。

    我重整心情，看向天爱星同学的状况，发现她似乎格外介意裙子。

    「怎么了吗？」

    「裙摆实在是太短了，我担心从台下角度是不是会看见裙底……动画里也是这个长度，我想应该没问题就是了。」

    「不，动画里是靠一种不可思议的力量，让人看不见裙底。你最好多注意点。」

    「……我去那边调整一下。」

    天爱星同学留下这句话，退到后场。

    糟糕，刚才维持现状也许能争取更多男生票——

    我心里这么想的同时，樱井自然而然般站到我身边。

    「因为我的任性，害你被卷进很多麻烦呢。」

    「这不是樱井的错啦。不管是谁，不管有什么理由，都可以参选啊。」

    我未经深思就回答后，樱井便直盯着我瞧。

    「怎么了？」

    「原来如此，问题就出在这里啊。」

    终于连樱井都这样说我了喔。

    这时，体育馆大门关闭的沉重声响传来。学生进场已经结束了。

    「抱歉了，这次我一定要赢。」

    樱井留下这句话，回到八奈见那边。

    ……为什么要道歉？

    我感到纳闷时，天爱星同学回来了。

    「让你久等了。差不多要开始了呢。」

    「裙子的长度看起来好像没什么改变。没问题吗？」

    「我想了想，还是不能少了这种紧张感——不是，我是说时尚感。」

    真的没问题吗？该不会新的大门已经几乎开启了吧。

    在我提心吊胆时，会长平静的说话声传到耳畔。

    「各位同学，那么接下来，学生会长候选人的演讲会即将开始。」

    刚才还骚动不已的体育馆刹那间安静下来。

    「——学生会长候选人，樱井弘人的声援演讲。2年C班八奈见杏菜，请上台。」

    ◇

    学生会长候选人　樱井弘人声援演讲　～八奈见杏菜～

    八奈见站到舞台中央的讲台前方，将麦克风转来转去调整位置。

    「啊～测试、测试。」

    花上许多时间测试麦克风后，她清了清嗓子。

    「呃～大家好，我是八奈见杏菜。我和学生会长候选人樱井是同班同学，哎，就是这一类的关系。」

    虽然起头十分随意，不过第一个上场必须面对尚未暖场的观众。如同相声的开场白般缓和气氛，一边揣摩观众的反应有其必要。

    八奈见闲话家常般聊了两、三句后，身子朝着麦克风向前倾。

    看来开场白就到此为止，她要切入正题了——

    「虽然突然，不过各位是面包派，还是白饭派？」

    ……不，也许她打算用闲话家常撑到最后。

    不理会会场中的困惑氛围，八奈见以充满自信的态度继续说着。

    「我习惯早上吃面包，中午吃饭。没空档的早上用方便的面包解决，中午则坐下来品尝便当盒的白饭。换言之，为了撑过下午的课程与放学后漫长的时间——没错，需要白米饭的力量。」

    八奈见如此断言后，环视下方的会场。

    「说到这里，想必各位也都明白我想说的意思了。」

    抱歉，我不明白。

    这样真的好吗，樱井？我心生不安而投出视线，只见他面露觉得有趣似的表情，望着八奈见。樱井的包容力竟然如此之高……

    八奈见再次清过嗓子。

    「没错，樱井就是白米饭！无论是何种菜色，白饭都能温柔地接纳。无论是浓汤还是关东煮，白饭能够包容一切！」

    八奈见的引擎转速升高。将整个会场甩在后头，八奈见剧场继续上演。

    「如果我是明太子，而他的朋友有的是炸鸡块、有的是芝麻盐，虽然各有不同，但是他绝对不会分别看待！」

    八奈见的指头猛然转向舞台侧边。

    在她所指之处，樱井不动声色地现身。

    「樱井不像芝麻盐同学那样，老是说些用雕刻刀捅人心窝似的失礼言词，也会认真听我说话。最好多仿效一下人家。请多学着点。」

    虽然不晓得芝麻盐同学是谁，但被骂得还真惨啊。然后八奈见，为何要看我？

    八奈见再度转头正视前方的观众。

    「所谓的学生会，是为了让各位过上更好的校园生活而存在。话虽如此，有些时候也需要借助各位的力量，让大家一起迈步向前。这种时候，若有大碗白饭般的樱井弘人，就能接纳各位的想法并且美味地品尝！」

    砰！八奈见用双手拍打讲桌。

    「绝不会让各位饿肚子！樱井弘人！请用各位的力量将樱井弘人煮成白米饭！」

    （插图016）

    一瞬间的沉默。

    从被谜之魄力震撼的学生们处，发出稀疏的掌声。

    接着就在八奈见高举单臂，离开讲台的瞬间——盛大的鼓掌声充斥了体育馆。

    ◇

    凭着气势炒热了气氛是事实，但是刚才的演讲是什么？这种状况，换作大家空腹时可就危险了……

    八奈见回到舞台侧边，与樱井击掌。

    我对八奈见的嚣张表情视而不见，观察樱井的状态。

    樱井一如往常，面露沉着平静的笑容。

    像是集中精神般，笔直凝视着舞台。

    被八奈见剧场扰乱思绪、骚动四起的会场中，会长的声音响起。

    「——接下来，是学生会长候选人演讲。2年C班，樱井弘人。请上台。」

    ◇

    学生会长候选人演讲　　～樱井弘人～

    樱井站在麦克风前方，低头行礼。

    「大家好，我是本届学生会会计，樱井弘人。」

    气氛与刚才截然不同，是沉稳的开场白。

    樱井缓缓扫视会场。

    「话虽如此，我不太常在大家面前露面，我想应该也有不少人不认识我。」

    会场中响起好几声女生说「认识喔～」的嗓音。

    什么跟什么。樱井，我明明把你当朋友。

    「我在学生会的职责是辅佐大家工作，在背后提供协助。虽然没有足以自豪的实绩，但我想为各位介绍学生会过去的工作。」

    樱井的演讲意外地采取正面进攻，是认真至极的演讲。

    因为他也是学生会的一员，会强调在学生会留下的实绩，也在预料范围内。

    校内设施预约的数位化、重新审视活动预算、为女子运动社办楼设置照明——

    他精准地挑选了虽然不起眼但效果显著的政策。

    我听着樱井的演讲，渐渐心生疑惑。

    该不会这是……？此时天爱星同学伸手触碰我的手臂。

    「温水同学，讲稿请给我看一下。」

    「好，等一下喔。」

    在我们的计划中，我的声援演讲预计要强调过往的实绩，天爱星同学则要强调将来的学生会方针。

    写在我的讲稿上的天爱星同学的实绩是，校内设施预约的数位化、重新审视活动预算、为女子运动社办楼设置照明——

    「这是……」

    天爱星同学表情紧绷地点头。

    没错，樱井在演讲时举出来的是天爱星同学实行的政策。

    ——完全被针对了。

    当然，政策的实施有赖学生会全员一同努力，而且樱井也先清楚说明了自己的职责是辅佐。

    没有一句话是谎言，也没有引人误会。

    然而——接下来如果我们强调同样的实绩，岂止是依样画葫芦，甚至可能给人争夺功劳的印象。

    「……不妙啊，我没想到樱井居然会来这招。」

    「这是正当的战术。我们也同样利用了演讲的顺序，选择用服装打扮吸引注意力。樱井只是选择了将先上场的不利转变为有利的战术而已。」

    天爱星同学面露懊悔的表情，握紧拳头。

    「放弃事先准备的讲稿吧。请用你最擅长的自由发挥，撑到我上场。」

    「我没有那种特技啊！？」

    当我惊慌失措时，八奈见讶异地看着我。

    「你们从刚才就在吵什么啊？差不多该轮到温水上场了喔。」

    鼓掌声传到我们耳边。樱井的演讲结束了。

    樱井对着观众席深深低下头后，回到了舞台侧边。

    天爱星同学双手抱胸，迎接他回来。

    「居然来这招啊，樱井。」

    「抱歉，马剃。之后要我怎么赔罪都可以。」

    樱井该道歉的对象应该是我吧？

    ……不，之后再抱怨。

    我连忙低头看向讲稿，但是愈看愈发现内容都与樱井的演讲重复。

    难道我真的只能在全校学生面前挑战即兴自由发挥了吗……？

    「那么接下来，是马剃天爱星的声援演讲。2年C班温水和彦，请上台。」

    放虎原会长的凛然声线响起。轮到我上场了。

    ◇

    学生会长候选人　马剃天爱星声援演讲　～温水和彦～

    ……只能硬着头皮上了。我闭上眼睛深呼吸。

    好，渐渐萌生觉悟了喔。只要再深呼吸一次就走上台吧。

    「温水同学，在叫你了喔！」

    「喔喔，嗯，没问题。感觉状态愈来愈好了，再一下。」

    「剩下的请你在台上解决！」

    「啊，等等——」

    被推上舞台的我，集中了全校学生的视线。

    我逃离视线般走向讲台，用颤抖的指尖开启麦克风的开关。

    「呃，那个……我是有幸担任马剃同学推荐人的温水。」

    马上就陷入语塞的我，生硬地清了清嗓子。

    独自一人站在舞台上的紧张感，与四月的社团说明会完全不同。

    「马剃同学，那个……个性很认真……」

    话语再度停歇，体育馆的寂静压向我的身体。

    ——在现实中即便走投无路，也不会有深藏体内的力量因此觉醒。

    我的意志彻底受挫，将视线转向舞台侧边的天爱星同学。

    映入眼中的是天爱星同学傻眼的表情——不对。

    与我的预料相反，天爱星同学正以认真的表情注视着我。

    用那充满信赖的坚定眼神。

    ——可以请你只推我一个人吗？

    她在咖啡厅中的这句话。

    直到这时，天爱星同学依然相信我。

    相信在全校学生面前现出丑态的我。

    「……我第一次遇见她，是在去年石蕗祭之前。」

    我抬起脸，承受全校学生的视线。

    不管是有所觉悟，或是干脆豁出去，我都只是不起眼的一介学生。

    身为平凡无奇的温水和彦，只能述说相遇之后还不到一年的天爱星同学。

    「她给我的第一印象是个非常认真的学生。这个嘛，虽然她在石蕗祭上穿着女仆装学猫叫，但整体而言是个认真的学生。」

    舞台侧边的天爱星同学好像正在朝我释出压力喔……

    「这次的学生会选举，在校园新闻与新闻社官网的讨论区上，有人在写关于她的流言蜚语，不过内容绝大多数都是中伤之类的话。」

    提起讨论区的时候，天爱星同学的表情。

    虽然表面上佯装不在乎，但心里确实受伤了。这点小事我也看得出来。

    「哎，该怎么说才好，有不少部分我也能理解。她的个性不知变通，顽固又倔强，也有些任性之处——」

    我害怕着天爱星同学不断增长的压力，用力深呼吸。

    「但是她的任性从来不是为了自己，而是为了他人。所以我觉得这次参选，对她而言是第一次为了自己而任性。」

    ——也许由樱井来当会长比较好。

    他的能力优秀，更重要的是有人望。

    如果没成为当事者，我应该也会投票给樱井吧。

    「我为了帮她实现第一次的任性而成为了推荐人。我也同意，和现在的会长相比之下，她看起来恐怕不够可靠。」

    然而我是当事人。是马剃天爱星的推荐人。

    「但是她就是她，马剃同学有马剃同学的优点，一定能成为称职的学生会长。如果听完我这么说，还有人觉得马剃同学不好的话——」

    所以既然站在此处，我——就算只有我一个人，也要推她。

    「请尽管来找我！如果有人说了她的坏话，我会还以好几倍的夸奖！过去我亲眼见到的马剃同学的那些笨拙却坚强且正直，体恤他人之处——要我一一细数到天亮都行！」

    吐露脑海中的一切后，我深深吸气，扫视体育馆。

    学生们彷佛冻结了似地鸦雀无声。

    我该不会搞砸了……？

    我畏畏缩缩地看向舞台侧边，只见天爱星同学满脸通红，摆出小奇卡的招牌姿势指着我。那个是代表哪种心情？

    ——就在这时，一阵冰凉的风抚过我的脖颈。

    「我也想……细数到天亮……」

    「！？」

    就连吃惊的空档都没有，「啪」的一声，体育馆的灯光突然熄灭。

    无法想像现在是白天，黑暗笼罩了体育馆，台下四处传出不知所措的声音。

    一瞬间，眼前视野猛然摇晃，眼睛逐渐习惯黑暗的我，不禁吃惊得瞪大眼睛。

    不知不觉间，我已经站在演讲开始之前的舞台侧边。

    「啪」的一声再度响起，体育馆的照明一齐再度点亮。

    骚动声有如涟漪，在体育馆中散开。

    舞台中央处，站在讲台前方的是——志喜屋学姊。

    面对着麦克风，志喜屋学姊悠悠摇晃，喇叭传出尖锐的回授声。

    在那声音平息之时，志喜屋学姊缓缓开了口。

    「3年E班……志喜屋梦子……选手……换人……」

    在场所有人都屏息的瞬间。

    体育馆天花板的照明再次开始闪烁，一部分女学生发出轻微的尖叫——

    ◇

    学生会长候选人　马剃天爱星声援演讲　～志喜屋梦子～

    当然，这对放虎原会长来说也是预想之外的事态吧。

    她在另一头的舞台侧边摇着头，对志喜屋学姊招手。

    志喜屋学姊不理会她，以细微的声音开始说：

    「学生会长候选人……天爱星……就如大家知道的……现在是……副会长……」

    我愕然凝视着这一幕时，天爱星同学拉住我的手臂。

    「为什么志喜屋学姊会在那里啊！？」

    「不，我也搞不清楚状况……」

    对着被逼问的我，八奈见用力竖起了大拇指。别这样，人家会误会的。

    我一面安抚着天爱星同学，一面看向舞台，志喜屋学姊的演讲仍在持续。

    她提起的似乎是去年四月，天爱星同学参加校内美化志工时的经过。

    「天爱星……和其他人……处得不太好……」

    与周遭起冲突的天爱星同学的样子，很轻易就能想像。

    刚相遇时的她，比起现在稍微（？）偏激一点，肯定闹出了不少事吧。

    「但是……在我请假一阵子的时候……她帮我……把宝贵的花坛……整理得漂漂亮亮……」

    志喜屋学姊摇摇晃晃地让视线在半空中游走。

    学生们也跟着看向头顶上，那里当然空无一物。

    「我原本以为枯掉了……所以很开心……」

    那缺乏抑扬顿挫的音节中，透出志喜屋学姊笨拙的情感。

    就连我都听出来了，天爱星同学一定也感受到了吧。

    刚才还杀气腾腾的天爱星同学，肩膀缓缓垂了下来。

    「——志喜屋学姊有个习惯，会放弃自己心爱的东西。」

    天爱星同学自言自语般呢喃道。

    大概是注意到我的视线，她以生硬的口吻补充说明：

    「所以旁人必须代替她帮忙保护才行。」

    照顾花坛的往事，发生在天爱星同学加入学生会之前。

    当时彼此的交情还不深，为何她能如此瞭解志喜屋学姊？

    「……为什么你会这么想？」

    「看就知道了啊。因为我也一样。」

    天爱星同学看着我的脸这么说，视线再度转回讲台。

    舞台上，志喜屋学姊断断续续的细语声仍持续着。

    「那孩子……就算对方说过自己的坏话……也会不介意地……伸出援手……」

    志喜屋学姊的摇晃幅度愈来愈大。

    「就算没有人看见……没有人称赞……也会为大家着想……有所行动……」

    说完，志喜屋的动作蓦地静止。

    没问题吗？不用喂她喝水蜜桃水之类的吗？

    在全校学生担忧的守望下，志喜屋学姊再度动了起来。

    「可是……最早发掘那孩子的……不是我……」

    我记得一开始推荐天爱星同学加入学生会的，是志喜屋学姊。

    我一直以为就是志喜屋学姊发掘了天爱星同学。

    「告诉我的……有个好孩子的……是樱井……」

    「咦？」

    在我身旁，天爱星同学发出轻微的惊呼声。

    在她的注视下，樱井有些尴尬地搔了搔鼻头。

    「他说有个努力……又懂得为人着想的孩子……所以想推举进学生会……」

    志喜屋学姊打着节拍般，欣喜地摇晃着身子。

    「实际上一见……既可爱……认真……又好骗……是个温柔的孩子……」

    细数天爱星同学的优点时，志喜屋学姊看起来非常开心。

    被夸奖的本人则是一脸不自在，显得心神不宁。

    「痔很可爱……有肥皂的香味……背后很敏感……很可爱……」

    奇怪，话题好像走偏了。

    天爱星同学刚才还遮掩着害臊的笑容，现在表情渐渐变了。

    「胸罩的尺寸……不太合身也可爱……但是最近有种……成长的预感……」

    啊，天爱星同学握紧拳头，开始颤抖了喔。

    志喜屋学姊大概是把想说的全部说完，心满意足了，她静静地在舞台上左摇右晃。

    在剩余时间不多时，志喜屋学姊再度开了口。

    「天爱星……是懂得……为人付出……的孩子。」

    她的身体猛然朝着讲台倒下，会场中传出惊呼声。

    志喜屋学姊用双手握着麦克风，支撑住身子，以气若游丝的声音说：

    「所以我希望……大家投给……天爱星……但是……」

    她绞尽最后的力气般吸气。

    「樱井也是……可爱的学弟……所以希望大家……好好考虑……再投票……」

    说完的瞬间，阳光自体育馆的窗口投入室内——照亮了台上的志喜屋学姊。

    以此为契机响起的掌声，让刚才的一切都彷佛是一场梦般，撼动了体育馆。

    ◇

    志喜屋学姊回到另一侧的舞台侧边，被放虎原会长用手刀敲了头。真可爱。

    我观察天爱星同学的状况，便见她垂着脸，浑身颤抖。

    「真的是……每个人都……！」

    不妙，这个人好像快发飙了。

    「不过好像也顺利撑过去了。差不多要轮到天爱星同学了喔？」

    「每个人都爱怎样就怎样耶！？能不能适可而止啊！？」

    你跟我抱怨也没用。

    「——让各位久等了。接下来将继续学生会长候选人演讲。2年F班——马剃天爱星，请上台。」

    原本还一脸不吐不快的天爱星同学，听见会长的广播后，绷紧脸庞。

    她手按胸口，深呼吸。

    「……那我也只能照我想做的去做了呢。」

    「咦？你有什么打算吗？」

    天爱星同学用指尖轻轻弹了一下在头侧边束起的头发，露出洁白的牙齿对我笑起。

    「那么我出发了，温水同学。」

    ◇

    学生会长候选人演讲　　～马剃天爱星～

    天爱星同学从舞台侧边现身的模样，令体育馆喧闹四起。

    虽然险些忘记，但这个人其实正在大庭广众下玩Cosplay……

    天爱星同学在讲台旁边停下脚步，朝会场深深鞠躬后，站到麦克风前方。

    「我是本次参选下届学生会长的马剃天爱星。」

    虽然打扮成那样，开场白却是一本正经。

    因为志喜屋学姊的登场而浮躁的气氛，渐渐沉静下来。

    「与刚才的樱井相同，我也是本届学生会的一员，担任副位长。想必在座各位中也有人在校内活动中与我打过交道吧。」

    天爱星同学确认了会场的气氛后，以柔和的口吻继续说：

    「我原本想告诉大家，这一年来我在学生会做了些什么——不过刚才已经被樱井抢先说完了呢。」

    短暂轻笑后，她将视线投向舞台边的樱井。

    会场中随之传出笑声。

    天爱星重新面对正前方，以严肃的口吻开始说道：

    「国中时代，石蕗高中在我心目中是憧憬的目标。」

    ……她面露怀念神色说出的内容，与事先讨论的完全不同。

    「在这里上学的学长姊们是我心目中的男主角与女主角。那时我一直梦想着，有一天要考上石蕗高中，一起度过高中生活。」

    那口吻不像是面对眼前的听众，而是在与过去的自己对话般。

    天爱星同学独白般继续说道：

    「普通地在石蕗高中上学、参加社团挥洒汗水，度过普通的校园生活——」

    说到这里她暂且打住，以认真的表情凝视会场。

    「我原本以为只要考上这所学校，我也能成为石蕗的『普通』之一。但是，现实并没有这么简单。」

    天爱星稍微迟疑后，再度开口。

    「我的成绩实在不算好。不，要说差劲也无妨吧。每次光是要合格都很勉强。」

    ——那是过去她一直想隐藏的秘密，是她的自卑之处。

    「运动也不拿手，和朋友的对话中，也时常让我察觉彼此的差距。我一入学就深切体认到，我无法成为曾经向往的『普通』。」

    说到这里，天爱星同学面露抛开了烦恼般的表情。

    「恰巧就在去年这时候，参加了学生会主导的志工活动的我，在学姊们的邀请下进入了学生会。不过看来当时向学姊推荐的我的人，正是那边的那位樱井。」

    她淘气地轻笑，继续说道：

    「关于加入学生会之后的我，想必也有听闻过不少的同学吧。」

    天爱星同学打趣般说完，立刻绷紧了表情。

    「坦白说，我过去给各位带来了许多麻烦，也曾因为自己的幼稚而伤害过别人。」

    不知不觉间，樱井站到了我身边。

    樱井的神情看似欲言又止，我用手肘轻轻顶他一下，小声告诉他「船到桥头自然直，谢谢」。樱井回答我「不客气」——这样就结束了。

    接下来就只剩并肩站在这里，见证天爱星同学的真心。

    「——透过学生会活动我发现了，我无法成为小孩子时向往的男主角与女主角。但是，我可以支持那些男主角与女主角……！」

    天爱星同学从支架上拔下了麦克风。

    「没错，石蕗的各位——在座的各位！就是我从小向往、一心想成为的男主角与女主角！」

    真情流露的大音量，响遍整个体育馆。

    「我——学生会将会为各位打造！让各位能用心念书、投入社团活动的环境！」

    不理会尖锐的回授声，天爱星同学朝着麦克风呐喊。

    沐浴在暴力般的强烈感情之中，学生们一动也不动，注视着天爱星同学。

    「就算这样，有时候还是会因为力有未逮，给大家造成麻烦吧！大家一定也会有所不满吧！这种时候请尽管告诉我！我会全部接受！请尽情表达出来！用不着客气！」

    总觉得话语背后似乎有另一扇大门若隐若现，不过这种时候就全力忽视吧。

    ……不过情况很不错。虽然天爱星同学稍嫌激动，但学生们没有因此吓到。

    整个会场反而被天爱星同学直来直往的热情所影响。

    毕竟刚才的种种事态在心中累积的问号，大家都无处排解。

    天爱星同学脸上泛起红潮，将上半身压向讲台。

    「所以……所以……！」

    话说回来，情绪是不是有点太兴奋了啊？要是兴奋过头的话——

    「我——！？」

    天爱星同学连忙用双手捂住鼻子。

    脱手掉落的麦克风掉在讲台上，发出沉重的撞击声。

    ……不会吧。

    天爱星同学的肩膀开始颤动。呃～这恐怕是——

    演讲戛然而止，会场开始骚动。

    「唉，马剃同学怎么了？吃太多了？」

    口中不知咀嚼着什么的八奈见靠近我，投出了担心的视线。我说你啊，现在算上课时间喔。

    先不管八奈见，这下不妙了。

    虽然我也不太清楚怎么个不妙，但是我得想办法……

    我在口袋中寻找面纸时，不知何时天爱星同学不再颤抖。

    在那眼眸中燃烧的是——觉悟的光芒。

    天爱星同学下定决心般松开双手，抓住了麦克风。

    ——任凭血从鼻子流出。

    「也就是说，各位都是我的『推』！所以！」

    抛开一切般的呐喊与鼻血。

    然后天爱星同学使劲吸气——将今天最大的声量砸向观众。

    「拜托了！请让我推各位吧！」

    （插图017）

    叽……喇叭传出尖锐的回授声。

    超乎想像的魄力使得体育馆一片寂静，只有天爱星同学气喘吁吁的呼吸声回荡。

    接着，她再度用力吸气，将指头笔直地指向舞台边的志喜屋学姊。

    「还有志喜屋学姊！请不要在大家面前，用名字称呼我！」

    天爱星用袖子抹去流淌而出的血，朝着石蕗的全校学生——

    「以上！我是马剃天爱星！」

    嘶吼道。

    这一天，马剃天爱星被指定为石蕗高中下届的学生会长。

    而她在日后，将被这样称呼——

    ——红之学生会长。

** Intermission 收拾善后的时间到了

    傍晚的学生会室。

    放虎原云雀与志喜屋梦子两人，在墙上的白板上提笔书写。

    放虎原打破了短暂持续的沉默。

    「志喜屋，你那时可吓到我了。万一马剃落选了，那可不是闹着玩的。」

    「嗯……幸好……天爱星赢了。」

    志喜屋说得彷佛与自己无关，用红色麦克笔画了圆圈，在四周补上花瓣。

    「天爱星……有好好……回到家……？」

    「有，弘人送她回去了，别担心。」

    放虎原似乎对自已写的字不太满意，抹去其中几个字又重新写过。

    「呐，志喜屋。」

    「怎么了……？」

    「我还是想不透。为什么你会做那种事？」

    ——那种事。

    用不着说，当然就是声援演讲。

    志喜屋停下手，为了寻找贴切的话语般，视线在半空中游移。

    「两个人……都可爱……老是气氛紧张……我讨厌……」

    她露出些许撒娇般的神情，歪过头。

    「抱歉喔……？」

    「为什么要道歉？我可没有生气。」

    「因为……樱井……落选了……」

    见到志喜屋歉疚的态度，放虎原面露苦笑。

    「心意更强烈的一方被选上了，这是令人满足的结果。」

    「没关系吗……？」

    「是啊，把学生会交给马剃，我也能安心。」

    放虎原手中的麦克笔在白板上奔驰。

    「我不是说……那个……」

    只说到这里，志喜屋不再说下去。

    放虎原迷惘着该露出何种表情，同时以平淡的口吻回答：

    「那些事早就都过去了。」

    接下来好一段时间，只有麦克笔滑过白板的声音在学生会室回荡。

    大概是写好了令她满意的字，放虎原大大地点头。

    「我才想问志喜屋，已经决定好了吗？」

    听见突如其来的这句话，志喜屋的身体猛然摇晃。

    「嗯……一点一点……在决定……」

    「这样啊。」

    沉默再度造访。

    看着放虎原画的图，志喜屋低声呢喃：

    「天爱星说……要拜托樱井当副会长……」

    「嗯，我也觉得会是这样。弘人那家伙，应该答应了吧？」

    「嗯……」

    「话说回来，有提到其他成员吗？只有两个人的话，人手是真的不够喔。」

    「天爱星……好像……有些想法……」

    原本还要追问的放虎原，嘴角浮现自嘲的笑意。

    「即将离开的人操心过头也是不识趣……好，画好了。」

    「我也……好了……」

    两人盖上麦克笔盖，向后退开，眺望白板。

    中央处醒目地写着『将来就交给你们了！』的文字。四周点缀着模样可爱的插图与留言。

    「云雀……这是……企鹅……？」

    「很可爱吧？企鹅人的新形态，企鹅叔。」

    「须……审议……」

    志喜屋的身影飘动般绕到放虎原身后，背靠着背，将体重倚向放虎原。

    接着她将手掌举到比自己头顶的更高处。

    「云雀……长高了……？」

    「也许吧。真是的，只有个头长得特别高。」

    看不见彼此的表情。

    两个人感受着从背后传来的呼吸声，有些眷恋地开口：

    「……这段时间很开心呢。」

    「嗯……很开心……」

    本届学生会将在后天的运动会结束后解散，交接给下届学生会。

    时间的流动永不止息。

    有限的三年时间，不允许她们驻足在同一个场所。

    「话说回来，志喜屋，我之前就一直想问。」

    放虎原纳闷地注视着白板上的猫。

    「这只『喵子』到底是什么？和猫不一样吗？」

    那插图是一只躺在巨大枕头上的猫，还标上了喵枕的名称。

    「因为喵子……很可爱……？」

    「因为可爱啊。原来如此，我明白了。」

    放虎原赞赏似地点头。

    志喜屋注视着那张侧脸，突兀地问道：

    「可以……亲一下脸颊吗……？」

    「不可以。留到真正需要的时候吧。」

    放虎原断然回绝后，面露满足的表情，一直注视着白板。

** ～第四败～女性公敌是在说谁？

    石蕗高中运动会当天，天不从人愿，是个万里无云的大晴天。

    会长选举已经顺利落幕，本次运动会一结束，本届学生会就会解散。

    当然对于绝大多数的石蕗生而言，这与自己毫无瓜葛。对我而言也一样，既然选举都结束了，与我已经无关——

    我心中这么想着，放眼眺望在加油声中奔跑的阳角们。

    我已经参加了必须全班参加的赛跑与拔河，精疲力竭。

    尤其关于赛跑，我原本以为在三月时练就了超过高一男生平均水准的跑步能力，应该能跑出普通的成绩，但我有件事失算了。

    ——大家都升上二年级了。

    而且和我一起跑的五个人都远超过平均值，包含田径队等参加运动社团的家伙们，再加上袴田草介。

    袴田那家伙，居然赢过田径队男生拿到第一名，所谓的主角威能真是恐怖。而我当然是吊车尾。

    感觉肩膀也开始发痛了。参加个拔河就如此满身疮痍，我是不是已经没救了呢……

    「喂，温水，时间差不多了喔。」

    「啊啊，我知道。」

    我和绫野互看一眼，视线再度转回操场上。

    现在正要进行的项目，是男女混合接力的班际对抗赛。

    虽然这种阳角氛围全开的竞技与我无缘，但唯独这回无法忽视。

    因为烧盐上场担任了2年E班的最后一棒。

    我们在第四弯道附近占了个好位子守候时，棒子交到了烧盐手上。

    「你看，交棒给柠檬时还是第一！」

    「我有在看，不要拉我的衣服啦。」

    最后一棒要跑比其他人更长的四百公尺。

    烧盐一拔腿奔跑，操场便随之掀起骚动。

    速度快得难以想像她最拿手的是中距离，一口气就逼近第一弯道。

    ……真快。当然去年也很快，但魄力更强烈了。

    我看着她奔跑，不禁受到震撼。这时绫野双手抱胸，兀自点头。

    「你知道吗？其实柠檬那家伙短距离的成绩也进步了喔。」

    「咦？是喔？」

    「是啊，她说接力赛之前要测速当参考，就刷新了她的最佳纪录。」

    不知为何绫野洋洋得意，我则刻意对着他耸肩。

    「你说的最佳纪录是和我对决之前的官方纪录吧？不好意思喔，她早在三月和我赛跑的时候就已经刷新纪录了。」

    绫野听了，眼镜发出一道闪光。

    「那你知道这件事吗？柠檬说她比赛当天不吃固形物喔。她说果冻和饮料之类的比较容易调整状态。」

    哦？是这样喔。八奈见绝对办不到吧。

    先撇开这件事不谈，有女朋友的家伙摆出一副自以为很懂的态度，真的好吗？

    「绫野，这你知道吗？烧盐在比赛前会为了集中精神听音乐。」

    「啊啊，这我当然知道。」

    「我想也是。不过接下来才是正题。之前的大赛上，她的音乐不是从耳机播出来，而是从手机外放了，她说那时候很害羞。」

    「哦～真有柠檬的风格。」

    「对吧？」

    我们炽烈地互别苗头之时，烧盐的身影来到第四弯道。

    一瞬间，眼神对上——萌生这种感觉的下一个瞬间，烧盐对我竖起食指，转瞬间就从眼前跑过。

    然后她最后一次再度加速，甩开追在后头的男生，突破终点线。

    烧盐沐浴在轰然的欢呼声中，身影跳向2年E班接力队之中。

    我们先是被烧盐的奔跑之姿所震慑，回过神来面对彼此。

    「「——刚才她是在跟我打暗号吧？」」

    为何会异口同声？

    我无奈地叹息，将手摆到绫野肩膀上。

    「你冷静想想看。虽然是朋友，但烧盐会对有女友的男生特别表示，这实在很难想像。换言之用消去法来思考，认定她示意的对象是我比较自然。」

    「这无关吧。见到为自己加油的朋友，比个手势又不奇怪。」

    「照你这个道理，那个对象是我也不奇怪吧？我也是烧盐的朋友，这可是你自己讲过的。」

    绫野听我这么说，沉思了好半晌后，神气地用指尖推高眼镜。

    「……关键在眼镜。」

    「什么意思？」

    「因为眼镜的反光，柠檬才会注意到我。不然在这么多观众之中，她不可能找出我吧。」

    「是不是太刺眼了妨碍她专心啊。我渐渐觉得她刚才比的是中指了。」

    我和绫野的视线在半空中无言交锋。就在第二回合即将开打之时——

    「光希同学～！」

    朝云同学现身了。她向我微微低头打招呼后，对绫野投以微笑。

    「有看到柠檬同学刚才的接力赛吗？真的好快喔。」

    「是啊，千早也在看啊。那家伙果然了不起。」

    「就是说啊。温水同学，可以和你借一下光希同学吗？我有些话要跟他说。」

    我默默点头后，朝云同学用双手抓住绫野的手臂。

    「千早，有什么事吗？」

    「嗯，会是什么事呢？我们到那边谈吧。」

    绫野被强行带走，我对着他的背影双手合十。

    ……刚才的对话一定被听见了吧。

    哎，都有女友了还对自己拒绝过的女生看得目不转睛，是你不好。好好反省吧。

    那么，上午的竞技也差不多到了尾声。

    其他还有什么项目吗……？

    我想取出口袋里的竞技表，这时八奈见跑向我。

    「你在这里啊！」

    「怎么了？急成这样。」

    八奈见调匀呼吸，以澄澈的眼眸看向我，对我伸出双手。

    「温水，便当给我！」

    「不要。」

    我立刻回答，但八奈见无奈地耸了耸肩。

    「真拿你没办法，我就说明到温水也能明白喔。」

    「我的回答不会变喔？」

    我再度强调，但八奈见不理我，继续说：

    「啦啦队竞赛是下午赛程的第一个项目，对吧？我们一到午休就要立刻换衣服，一边吃便当一边讨论事情。」

    「喔。」

    那与我有何关系。

    听了我无所谓的回应，八奈见恶狠狠地瞪向我。

    「你想想，从早上就运动，自然会肚子饿吧？所以——」

    「……你提早吃了便当。」

    「我只是稍微试吃而已，没想到便当那么没毅力。」

    毅力。原来便当有这种隐藏数值啊。

    虽然得知了原委，不过佳树的特制便当可不能交给这种不懂价值的人。

    「去贩卖部买面包不就好了。」

    「接下来我还要参加咬面包赛跑，没空去买嘛。你帮我去买一下。」

    「你干脆把咬到的面包当午餐吧？」

    「你觉得那样够吗？」

    嗯，应该不够吧。我明知故问。

    我点头答应，八奈见道谢后便准备离开。

    「等等，面包钱先给。可不能欠钱。」

    「……我看起来像是欠钱不还的女人吗？」

    对此我不予置评。

    八奈见在短裤口袋中翻找，摸出一枚五百日圆硬币。

    「就这样啦，拜托挑个有毅力的面包喔。」

    八奈见挥着手跑远，我目送她的同时歪着头。

    有毅力的面包……是哪一种？

    ◇

    离开贩卖部的回程上，我双手抱满了面包。

    保存期限只到今天的特价咖喱面包，我买到了多达七个。

    咖喱面包应该满有毅力的，八奈见也会眉开眼笑吧。

    我哼着歌沿着围绕中庭的走道移动时，一名可爱的女学生迎面走来。

    是白玉学妹。她一注意到我，就马上踩着小碎步跑来。好可爱。

    她很可爱毋庸置疑，不过今天的她有点不一样。

    头上戴着兽耳发箍，身穿柔软质地且附有尾巴的野兽服装的她，可爱程度更加提升。

    白玉学妹来到我面前，高举双手。

    「社长，嘎哦～！」

    她模样可爱地吓唬我。

    「这该不会是啦啦队竞赛的服装？」

    「是的，我们班上要跳狐狸和狸猫的动物舞。我变成狸猫了。」

    白玉学妹淘气地吐出舌尖。真会装可爱。而且好可爱。

    她看向我抱在怀里的咖喱面包，睁圆了眼睛。

    「呜哇，社长要吃这么多啊。」

    「没有，这个是——」

    「八奈见学姊吗？」

    白玉学妹嘻嘻轻笑，由下往上直盯着我的眼睛。

    「1年E班的啦啦队竞赛，社长愿意来看吗？」

    「咦？可以啊，只要时间和我们班没冲到……」

    我口齿不清地回答，白玉学妹对我展现花朵般的笑容。

    「哇～我好期待！我跳舞的时候会给你打暗号喔。请一定要看仔细了。」

    「咦？对我？」

    「……只对社长一个人喔？」

    白玉学妹耳语般柔声说。

    她俐落地转身，装在服装后方的狸猫尾巴在空中轻盈舞动。

    ◇

    上午的竞技结束，来到午休时间。

    因为樱井和绫野都参加了啦啦队竞赛，我在校园角落处独自享受一人的便当时光。

    置身树荫下，能听见枝枒摇晃的沙沙声，头顶上则不时传来鸟啭。

    「偶尔像这样平静度过也不错啊……」

    那么，在培根鹌鹑蛋之后，接下来要吃什么呢。

    串好的迷你关东煮，或是王道的炸鸡块——

    我欣赏着佳树的特制便当时，有道影子盖住我手边。

    我抬起头一看，见到手拿着便当布包的小鞠。

    「呜唉……那个……」

    小鞠忸忸怩怩地轻触浏海。

    「咦？啦啦队竞赛的成员，不是要一边开会讨论一边吃便当吗？」

    「我、我正式上场时没事做。音、音乐也是执行委员，会帮忙播。」

    「哦～是这样喔。那为什么跑来这种地方——」

    「呜哪！？那、那个，是……」

    见到小鞠慌张起来，我深深点头。原来如此，是这么一回事啊。

    「我懂了，你在找没有人会看见的地方吧？」

    「……呜唉？」

    我用大拇指示意背后。

    「我推荐那边的草丛后面。既安静，地面又长着草坪般的草，坐起来很舒服。我是为了听鸟叫才选这里，不过整体而言是那边更优。」

    很好，我做了件善事。同是阴角，本就该互相扶持。

    我心满意足地用筷子夹起炸鸡块时，小鞠对我低声说：

    「……去、去死。」

    为何要骂我？

    我因为突然的语言暴力而纳闷时，一股花香随风飘来。

    那轻快又庄严的背景音乐正朝着这里快速靠近——

    「太好了，原来在这里！」

    跑向此处的是身穿啦啦队服装的姬宫华恋。

    姬宫同学在小鞠面前急踩刹车，男生的梦想依循惯性法则猛烈上下摇晃。

    ……好厉害。是什么我就不说了，总之好厉害。

    我因为超乎想像的魄力而愣住时，姬宫同学用力握住小鞠的双手。

    「呐，小鞠，你能不能参加啦啦队竞赛？」

    「呜唉！？」

    「刚才小鸟游同学脚扭伤了。她是要被抬起来的那个人，一定要有人代替！」

    小鸟游同学，我记得是和小鞠差不多娇小的女生。

    姬宫同学朝着小鞠步步进逼。

    「小鞠应该记得全部的流程吧？可以代替小鸟游同学，负责被抬的位子吗？」

    「那、那个……」

    害怕的小鞠向我求助。我悄悄挪开视线。

    「拜托！现在只能拜托小鞠了！」

    「叫、叫八奈见代替……」

    「因为杏菜很重——不是，因为她力气大，我希望她负责出力抬人。别担心，大家都会帮忙的！」

    光彩夺目。面对姬宫同学的灿烂笑容，小鞠的生气渐渐流失。

    小鞠的头无力地向下垂。

    姬宫同学把那反应当作答应，硬是拖着小鞠离开。

    ……好像很辛苦呢。

    我手拿着关东煮串的竹签，仰望头顶上的枝枒。

    啊，刚才的是黄尾鸲耶，是不是来不及飞向北方呢……

    我一面听着悲伤的鸣啼声，细细品味着吸饱汤汁的蒟蒻。

    ◇

    下午的赛程没多久就开始了。

    操场上的喇叭播放轻快的音乐，2年C班的啦啦队竞赛开始了。

    我们班的表演是啦啦队女孩＆制服男子加油团。

    运动会特有的简单舞蹈有种令人莞尔的温馨感，不过那都是其次。

    ——姬宫华恋。暴力级的胸围与美貌，以及光芒璀璨的存在感支配了全场。

    就好像只有她身旁有不同的物理法则在运作般，装满梦想的某种东西在空中弹跳。

    这真的是在大白天的公立高中出现也没关系的情景吗……？

    不知不觉间，观众也莫名地变多。我敢说全校男生都聚集到这里来了——

    顺带一提，吃了七个咖喱面包的八奈见也精神饱满。

    啦啦队服装是小腹若隐若现的款式，不过之前担心的八奈见的赘肉也不太醒目。自从被白玉一族评以『长胖了』之后，她似乎一直努力在减重。

    不过，那么多的面包究竟装到哪里去了……

    八奈见时隐时现的小腹令我在意的同时，我寻找小鞠的身影。

    原本还担心她是不是逃走了，但我在女生们背后发现她低调挥动彩球的身影。

    ……那家伙很擅长躲在视线死角啊。啊，又不见了。

    我怀着守候野生动物的心情眺望表演时，曲子来到了高潮处。

    啦啦队女孩改变队形，所有人围绕着某个人。

    被围绕的是——小鞠。

    加油团中的绫野吹响哨子，啦啦队女孩便将虚弱地抵抗的小鞠抬高至肩膀的高度。

    成为瞩目焦点的小鞠脸色铁青，动作有如机器人般，将双手的彩球举到头顶上。

    这时音乐停止。

    哨子声再度响起，啦啦队女孩伴随着号令——将小鞠抛向半空中。

    当小鞠的惨叫声响遍操场时，啦啦队女孩接住了坠落的小鞠。

    这瞬间——盛大的掌声响起。漂亮的演出。

    看着被女生们团团围绕的小鞠，我感触良多地点头。

    小鞠真的长大了呢。虽然她本人好像失神了。

    ◇

    那么，我也得去看看白玉学妹的表演了。

    我占据了能清楚看见1年E班啦啦队的位置，双手抱胸，观察周遭。

    当然了，我只是作为社长来关注后辈的活跃而已，绝不是因为她说会向我打暗号，心生邪念地跑来看表演。等等，是不是再靠近一点，会看得更清楚……

    1年E班的啦啦队表演似乎是不分男女都扮成狐狸或狸猫跳舞。

    男女活泼嬉戏的情景实在令人嫉妒——不，我是说莞尔。

    白玉学妹在那之中也显得特别醒目，不过她只和男学生有互动耶……

    音乐开始后，1年E班的众人摆出招财猫的姿势，可爱地跳起舞。男生也用可爱的动作引人发笑也算特色之一吧。

    一加上动作，白玉学妹就更加醒目了。一举手一投足都可爱如偶像，流露小心机的招手动作简直抵达了炉火纯青的境地。

    如果这是偶像团体，想必会因为人气差距而闹出内哄。

    大概是白玉学妹的可爱渐渐传开，观众人数也渐渐增加。

    ……人这么多，也没办法对我打暗号了吧。

    没错，白玉学妹是大家的偶像，不再是我一个人的学妹了——

    我感到几分寂寥时，突然间与白玉学妹四目相对。

    白玉学妹盈盈一笑，用双手朝我送出飞吻。

    ……那女人是来真的。

    感觉很害臊，而且好像有点心跳加速。

    我独自觉得心神不宁时，附近的男生们起了骚动。

    「她刚才对我抛出飞吻了吧？」「笨蛋，是我啦。」「不，一定是我。」

    我在内心苦笑着，撩起头发。

    不好意思，她的飞吻是给我的。希望各位日后遵守分寸，继续推白玉学妹——

    「哎呀，温水也来看表演啊。」

    「啊，老师好。」

    不知何时站在我身后的是田中老师。

    老师稍微弯曲膝盖，在我耳畔问道：

    「最近和璃子妹妹处得还好吗？」

    要问好不好喔……哎，最近已经有融入我们了吧。大概。

    「这个嘛，状况还算是稳定吧。而且她好像不知不觉间和妹妹交换了联络方式。」

    「是说温水你的妹妹？」

    田中老师不知为何一脸吃惊。

    「是啊，她们两个起初好像处不太来。不过最近白玉学妹来到我家时，我妹妹也不会再洒盐了，我想应该和解了吧。」

    「盐……？而且璃子妹妹已经会到你家玩了？」

    「算是吧，只是偶尔会来而已。」

    奇怪，仔细一想，田中老师好像还以为我和白玉学妹正在交往？

    哎，不过实际上我们并没有交往，误会不久后也会自然解开吧。

    「我才想问老师，最近和白玉学妹处得还好吗？」

    我自己也觉得这问题有点危险，但是见到田中老师轻松的表情，让我拂拭了不安。

    「嗯。我现在也是被璃子妹妹叫来的，她说会给我打暗号，希望我来看。」

    「是喔～白玉学妹这样讲喔……是喔～……」

    白玉璃子……那女人真是……

    1年E班的表演结束，田中老师鼓掌。

    我站在田中老师身旁鼓掌的同时，向他平稳的侧脸投出视线。

    ……这个人大概作梦也想不到，白玉学妹正对他虎视眈眈吧。

    「话说璃子妹妹好像有在写小说？」

    「咦？哎，有是有。」

    田中老师对我面露充满兴趣的表情。

    「不管我怎么拜托，她总是说难为情，不愿意给我读。她写了什么样的作品呢？」

    白玉学妹的小说，主角是以田中老师为范本，其未婚妻已经过世，而女主角是未婚妻的妹妹——嗯，真的不能给他读。

    「她写的是时代小说，不过自己要读家人写的小说，或是自己写的小说给家人读，心理障碍都很高的。像我妹妹写的小说，我也要拿出觉悟才敢读。」

    「听你这样说，也许真的是这样。」

    也许是感同身受，田中老师点头表示理解。

    「等到作品更完整了，我再一并给老师。」

    「好啊，我很期待喔。」

    田中老师拍了拍我的背，离开此处。

    我一眼瞥向被男学生包围的白玉学妹后，走向自己的班级。

    我参加的障碍赛跑时间快到了。

    那么，这次就稍微展现出一点帅气之处吧——

    ◇

    运动会执行委员会的本部帐篷，同时也充当临时保健室。

    我会特意来此不是为了其他原因——因为我跌倒磨破了膝盖。

    虽然华丽地钻过了障碍物赛跑的网子下方，但是在拔腿开跑的时候，脚勾到了网子。运动会太危险了，最好还是禁止举办。

    「不好意思～……」

    我畏畏缩缩地朝着活动帐篷内打招呼，身穿白衣的小拔老师转过身。

    「哎呀，你是怎么了呢，温水。特地来找我的吗？」

    「不是，脚破皮了，想消毒。」

    「还是老样子冷淡呢。来，坐在那边的椅子上。」

    小拔老师检查伤口后，向背后的学生招手。

    「这个只要消毒就可以了。执行委员，可以麻烦你吗？」

    「好的，我知道了。」

    与小拔老师换手的学生——是樱井。他苦笑着坐到对面的椅子上。

    「刚才真是辛苦你了。很可惜啊。」

    一点也不可惜，六个人之中排名第五，光是能免于吊车尾就谢天谢地了。

    选举结束之后，樱井为准备运动会忙得不可开交，也没有时间坐下来好好聊聊。虽然觉得有几分尴尬，但是我仍然开了口：

    「你们连这些事都要负责啊。」

    「学生会也是执行委员，算是最后的工作吧。来，会刺痛喔。」

    樱井用吸了消毒液的脱脂绵拍打伤口。

    看着樱井熟练地处理伤口，我不禁说：

    「原来当时向学姊们推荐马剃同学的人，就是樱井你啊。」

    樱井停下手，在迟疑中开了口。

    「一起当志工的时候，有个小团体讨厌马剃，老是传一些有的没的，搞得很麻烦。」

    大概是回忆起某些事，樱井的表情蒙上阴影。

    「可是啊，当那个小团体带头的人闹出麻烦而被孤立时，只有一个人站在那孩子身边。那个人就是——」

    「就是马剃同学啊。」

    樱井默默地点头，继续为伤口消毒。

    ……原来天爱星同学有过这样的过去啊。

    不管是容易被人讨厌，或挺身保护讨厌自己的人，都很符合天爱星同学的作风。

    学生会的三人深知天爱星同学的许多优点，认为她是重要的伙伴。

    也许我打从一开始就没有必要担心。

    话说我们学校的志工活动，暗藏那么多勾心斗角喔……真可怕……

    「好了，这样就行了。」

    膝盖经过消毒，贴上一块纱布遮盖伤口。

    我感到钦佩时，一个女生匆忙地跑进帐篷。

    盘起的头发与粗粗的眉毛，正是下届学生会长，天爱星同学。

    「樱井，可以麻烦你来准备闭幕式吗？志喜屋学姊一直想解开背扣，我没办法做事——」

    这时天爱星同学注意到我，连忙跑过来。

    「温水同学，你该不会受伤了吧！？我来帮你包扎！」

    「啊，樱井已经帮忙了，不用麻烦。」

    我站起身，用脚尖轻踢地面。

    「咦？是这样啊。」

    天爱星同学手拿着消毒液与绷带，垂下肩膀。樱井瞥了她一眼，从椅子站起身。

    「准备闭幕式对吧？那这里就交给马剃照顾了喔。」

    「啊，好的，请放心交给我。」

    于是帐篷内只剩下我们两人。偏偏这种时候小拔老师不在。

    自从鼻血选举之后几乎没聊上几句话，总觉得有点尴尬……

    「那个，那我也该——」

    「接下来我会参加借物赛跑，温水同学会来看吗？」

    盖过我的后半句话，天爱星同学这么说。

    「哎……借物赛跑也满少见的，我是有打算看。」

    「呵呵，很少见吧。感觉好像少女漫画似的，我一直有点向往呢。」

    天爱星同学散发着轻松的氛围笑了笑，用双手轻推我的背。

    「不好意思拦住你。温水同学，我上场时请一定要看喔。」

    「啊，好的，我知道了。」

    继白玉学妹之后，连天爱星同学也讲这种话。选举都结束了，有什么目的吗……？

    我纳闷地歪着头，走向自己班上。

    ◇

    所谓的借物赛跑，就是从会场借取字条指定物品的竞赛。

    指定的题目基本上是头带或眼镜等物品，也有时候会是『尊敬的人』之类的。

    换作是少女漫画，常见桥段是男主角拿到写着『你的宝物』的字条，将女主角拦腰抱起，跑向终点。

    原来天爱星同学向往那种情境啊。我还以为她只对BL有兴趣……

    我感触良多地观看一年级的借物赛跑，这时一旁的绫野眉开眼笑地说：

    「等一下千早会上场。万一漏看了，她之后会很啰唆啊。」

    抓到机会就放闪，真是不能掉以轻心的家伙。

    「话说回来刚才你没事吗？刚才朝云同学不是把你带去谈谈了吗？」

    「千早把我……？你在说什么？」

    「就那个啊，在男女混合接力赛为烧盐加油之后。」

    「为柠檬加油……？」

    绫野似乎真的没有头绪，双手抱胸陷入沉思。

    咦？等一下。朝云同学对绫野干了什么好事……？

    「——接下来是借物赛跑，二年级组。选手请到起跑线预备。」

    像是要为我拂拭恐惧般，通知声传遍操场。

    很好，绫野夫妇的事情就这么忘了吧。

    每班派出两位选手，一共十二名选手并排在起跑线上，朝云同学与天爱星同学也在其中。

    朝云同学向天爱星同学搭话后，天爱星同学似乎感到害怕而颤抖，我劝你相信这份直觉。

    执行委员在起跑线前方摆好指定品项的字条后，竞赛很快就开始了。

    朝云同学在枪响的同时冲出去，对字条瞥了一眼后，马上就笔直跑向我们。她手中的字条写的题目是——

    「我的题目是『眼镜』，光希同学的眼镜可以借我一用吗？」

    「喔喔，小事一桩。加油喔。」

    「好的，光希同学！」

    朝云同学不知为何自己戴上眼镜，左摇右晃地跑了出去。

    她跑的方向和终点不一样喔，真的没问题吗……

    「绫野陪她一起去比较好吧？朝云同学往反方向跑过去了喔。」

    「是喔？我没有眼镜完全看不到耶。」

    嗯，当然的结果。反正他们两个好像也很开心，就别管了吧。

    我将注意力转回操场上，见到另一个女生跑向我们这边。

    是天爱星同学。她在我面前停下脚步，呼吸急促，白皙肌肤泛着血色。

    「那个，温水同学，你可以跟我一起来吗？」

    「咦？我？」

    怎么了？你抽到的题目是『阴角』之类的吗？

    在我询问内容之前，天爱星同学一把抓住我的手。

    「那我们要跑了喔！」

    「咦？等等！？」

    在同班同学好奇的视线中，我被她牵着手往前跑。

    这什么状况？是不是有点像少女漫画的女主角？我是说我。

    「唉，天爱星同学，你到底抽到什么题目？」

    「要加速了！会咬到舌头喔！」

    天爱星同学没有回答我的疑问，加快步调。

    这样一来根本没空讲话。我配合着天爱星同学的步调，跑向终点。

    与我们错身而过的其他班选手，纷纷吃惊地看着我们。

    我现在正和女生手牵着手，跑在全校学生面前吧？感觉突然紧张起来了喔。

    奇怪？要先跨出左脚还是右脚才对……？

    当我紧张得险些双脚打结的瞬间，天爱星同学使劲一拉我的手，突破了终点线。

    天爱星同学调整呼吸时仍然握着我的手，等执行委员的女学生靠近时，她才放开我的手。

    「不好意思，要检查题目。」

    「辛苦了。来，请看。」

    天爱星同学取出纸条，举到执行委员眼前。

    女同学睁大眼睛愣住，天爱星同学对她柔和地微笑。

    「可以吗？」

    「啊，可以。」

    天爱星同学转身背对点头如捣蒜的执行委员，对我低下头。

    「温水同学，真的很谢谢你帮我这个忙。」

    「是没关系啦，话说题目是什么？」

    「你很好奇吗？」

    我当然好奇，但是感觉好像有点麻烦……

    我犹豫该如何回答时，一阵刺眼的反光夺走了我的视野。

    定睛一看，戴着眼镜的朝云同学就在身旁。

    「这声音是温水同学？所以旁边的是马剃同学吧？」

    朝云同学毫不掩饰好奇心，透过眼镜直盯着我们看。

    「我的题目是眼镜，马剃同学的题目是温水同学吗？」

    听了那纯粹的疑问，天爱星同学轻轻一笑，牵起朝云同学的手。

    「差不多。朝云同学，这样很危险，我带你到等候区喔。」

    「哎呀，谢谢你的关心。顺便问一下，终点在哪里呢？」

    「终点已经到了喔。来，请往这边。」

    天爱星同学引导着朝云同学，从我身旁走过。

    「所以题目——」

    见到我欲言又止，天爱星同学面露恶作剧似的笑容。

    就在错身而过时——

    「既然这样，今天放学后，可以借我一点时间吗？」

    她在我耳畔如此低语。

    ◇

    石蕗高中运动会闭幕，在我身上留下了擦伤与肌肉酸痛。

    有大有小的啦啦队女孩，烧盐的飞驰与白玉的舞姿，还有佳树的特制便当——

    记忆已经转变为回忆，就连最后是红组还是白组胜利，都即将消失在记忆的彼端。

    「时间快到了啊……」

    我一眼瞄向手表上的数位显示，之后愣愣地仰望逐渐转暗的天空。

    ——从石蕗高中骑自行车约十五分钟，我正置身向山大池的桥上。

    上次来到这里已经是半年前。为了取回月之木学姊写的真人题材BL同人小说，我被天爱星同学叫到这里的时候。

    与那时候相比，白昼已变长了许多。

    从蓝色转为靛蓝的傍晚天空，引人产生不安与憧憬混合的躁动情绪。

    有什么好像正要过去，却又不知道那是何物。类似焦急的情感。

    ——还是十六岁。已经高中二年级。

    虽然不矛盾，却彼此相反的话语，在脑海中载浮载沉。

    话说，她为何不选中庭的石桌区，而是在这里碰面？

    根据天爱星同学所言，中庭因为旁人听不见声音，十分适合谈秘密的话题。

    所以说，她选择这个地方——想遮蔽的不是听觉，而是视觉。

    简而言之，有什么不想让人看见的东西。

    借物赛跑的题目只是幌子，真正的用意是——

    「……动画周边吧。」

    冲击性的事件接踵而来，让我几乎忘了这回事，但是我起初决定帮天爱星同学的契机是小奇卡的促销周边。她一定是想把东西交给我吧。

    要在校内递交动画周边想必令人却步，话虽如此，也没必要叫我来这种地方吧。

    我满心雀跃地扫视四周，发现横跨湖面的长长桥面另一头，有个身穿石蕗高中制服的女生正在靠近。是天爱星同学。

    我在桥面较宽的位置等候，这里甚至设有板凳。上次我来这里的时候，天爱星同学已经等在这地方了吧……

    我怀念地回忆时，天爱星同学大概是注意到我的视线，小跑步奔向我。

    「不好意思，让你久等了。工作拖得有点久。」

    身穿制服的天爱星同学伸手按住翘起的发丝，微微低下头。

    「没关系啦，我也才刚到。」

    我撒了个小谎。天爱星同学对我微笑并招手。

    「啊，请看那边，温水同学，有母鸭带小鸭耶。」

    「大概是花嘴鸭吧，现在正好是繁殖期。」

    今天的天爱星同学好像情绪特别兴奋。

    天爱星同学让身子倚着桥上栏杆，指向花嘴鸭亲子。

    「大只的是母亲吧。父亲在哪里呢？」

    「应该不在这里。一旦母鸭生下蛋，花嘴鸭的公鸭就会离开。」

    「啊，是这样喔……」

    兴奋之情微微下降了。奇怪，对话选项错了吗……？

    天爱星同学莫名愉快地看着在池面上划水的母鸭与小鸭。

    那么，我何时才能拿到小奇卡的周边呢？

    我站在她身旁，愣愣地眺望鸭子时，天爱星同学的话声传来。

    「声援演讲时——第一次遇见我的那些事，你都还记得啊。」

    「初次见面就挨骂，也忘不掉啦。」

    到学生会室缴交文件时，我看向天爱星同学的名牌，她就向我发难了。

    天爱星同学举手掩嘴，嘻嘻笑道：

    「那次是我失礼了。因为当时我以为文艺社是一群很夸张的人。」

    「哎，这个嘛，其实也不见得是错的。」

    「真是的，我都帮你说话了，这番好意不就白费了吗？」

    天爱星同学难忍笑意般，笑出了声音。

    「回想起来，你也曾把违反校规的同人志带进学校呢。」

    「把那个带来学校的不是我，是月之木学姊。」

    「哎呀，是这样喔？」

    天爱星同学面露捉弄我似的表情，我见状不禁苦笑。

    「天爱星同学也是，和以前不一样，愈来愈敢说了呢。」

    我这么说，等候天爱星同学吐槽。

    ……

    …………奇怪？吐槽呢？

    天爱星同学的两边手肘抵着栏杆，仰头看着我。

    「怎么了？不好意思，我没听清楚。」

    「啊，没事——只是在想，今天的天爱星同学都不会生气。」

    「没有人惹我生气的话，我也不会生气啊。」

    原来如此，真有道理。

    天爱星同学是因为我老是说些惹她生气的话，才会老是在生气吗……

    「呃，可是，你不稍微表示讨厌，总觉得提不起劲。」

    「我就知道，你每次都是故意耍着我玩吧！？」

    不妙，不小心说溜嘴了。

    天爱星同学气呼呼地对我说教。

    「你的问题就出在这里！每次都那样捉弄我，从来不愿意认真听我说话。」

    「没有啦，我真的没有捉弄天爱星同学啊。」

    「都讲几次了，请不要用名字称呼我！」

    很好，恢复到平常的状态了。

    天爱星同学傻眼地叹息道：

    「难得我今天想为之前那些事道谢，这下都被你糟蹋了。」

    「咦？是这样喔。道谢已经没有了吗？」

    「是啊，真是可惜呢。」

    刻意鼓起的脸颊没有持续太久。

    天爱星同学毫不遮掩微微扬起的嘴角，手肘再度搁在栏杆上。

    「……我是真的很感谢温水同学。陪伴我的任性，陪我一起打选战。」

    「虽然锋头都被志喜屋学姊抢走了。」

    「是啊，我也吓到了。」

    志喜屋学姊担心天爱星同学的那份心意。

    那个人肯定和天爱星同学同样笨拙。

    所以才会以那种形式表现心情吧——

    当我陷入沉思时，用手撑着脸颊的天爱星同学注视着我。

    「……你正在想志喜屋学姊吗？」

    「咦？因为正好聊到她啊。」

    「心里想的不是在这里的我，而是学姊啊。」

    天爱星同学忽地转开脸。

    ……为何突然间变得好像麻烦女友。

    我也学她在一旁用手肘抵着栏杆，眺望渐渐转暗的天空。

    「下届学生会，要请樱井当副会长对吧？」

    「是啊，还好他愿意接。虽然我还想要再多一个人帮忙就是了。」

    天爱星同学意有所指般，对我使眼神。

    「呃～我不行啦。我已经是文艺社社长了……该怎么讲，有触犯法令之虞嘛？」

    「哎呀，你知道这么难的单字喔。」

    「勉强知道啦。该不会以后不用再教你国语了？」

    我有些挖苦般地说，天爱星同学笑得露出白牙。

    「好啊，没关系。反过来由我来教你吧。」

    「那以后就靠你了。」

    聊着无关紧要的话。偶尔笑一笑。

    虽然只是这样，但这感觉出乎意料地惬意。

    当我们视线交会的时间增加，话语也随之减少时——

    我感受到类似尴尬的不自在，让身体离开栏杆。

    「那个……风也愈来愈凉了啊。」

    「是啊，感觉稍微变冷了。」

    那么，就在天色变黑之前回家吧。

    我准备迈开步伐时，天爱星同学忽地叫住了我。

    「不好意思，有件事忘了。」

    啊，对喔。我忘了重要的事情……！

    「小奇卡的——」

    「借物赛跑的题目，说好要告诉你的，对吧？」

    ……咦？那件事我没那么在意就是了。

    对着满心疑惑的我，天爱星同学用双手递出了一张小小的纸片。

    「请看。」

    「咦，啊啊，谢了。」

    也不必故意拒绝就是了。

    一定是因为无法率直地道谢，才会把这个当作约我到这里的理由吧。

    不经意地看向字条的我，见到写在上头的文字——呼吸暂停了一瞬间。

    ……

    …………

    ………………这个，是借物赛跑的题目吧？

    写在纸上的文字是——喜欢的人。

    呃，抽到这个题目，天爱星同学带我来到这里，这代表……？

    天爱星同学的眼眸凝视着完全陷入混乱的我。

    天爱星同学在胸前双手十指交叉，投出祈求般的眼神。

    接着她彷佛下定了某种决心，开口说道：

    「温水同学，我喜欢你。」

    （插图018）

    突如其来，又唐突的爱的告白。

    「呃，那个……」

    不，等一下，要判断是告白还太早了。

    换作是爱情喜剧，这一定是误会事件——

    「当然我指的是恋爱的喜欢。你愿意和我交往吗？」

    这是告白。

    绝对不是一时误会或听错。

    我——被告白了。

    只在轻小说中看过的事件，我现在成为当事人，在我眼前发生。

    选我……真的好吗？

    和天爱星同学相处很开心，她的外表也很可爱。

    不管怎么想，都是我匹配不上的对象。

    我只要回答一声『好』，原本只存在于妄想中的女友就会——

    「呃，那个……」

    我干涸的嘴唇终于张开。

    「那个，就是……我是把马剃同学当作朋友。」

    ……奇怪？

    「因为太突然，我吓到了，那个……」

    ……我在说什么啊？

    天爱星同学是个好孩子，长得又可爱，相处起来也开心。

    起初虽然有点不容易亲近，但是熟识之后就知道她的笑容十分纯真。

    「第一次有人对我这么说，我可能有点混乱吧。」

    两个人独处时感觉也很轻松。

    如果和她交往，一定——会很开心。

    我找不到任何拒绝的理由，所以我只要说出一句『好』就可以了。

    光是这样，我就能与天爱星同学交往——

    「那个，我……」

    我虽然开了口，却找不到下半句，就此沉默。

    ……我是在做什么？说不定再也没有这种机会了喔。

    我强迫自己一定要说出什么话的时候——

    「请稍等一下！」

    天爱星同学打断了我。

    「呃，那个——」

    「真的太突然了吧！呃，其实我虽然自认有了心理准备，或者说以为告白之后就会有所觉悟，但脑子也一片空白——」

    天爱星同学伸手按住胸口，当场蹲下身子。

    「还好吗？」

    「……是的。那个，温水同学。」

    仍然蹲着的天爱星同学开始深呼吸，缓缓抬起脸。

    「——我们能从朋友开始做起吗？」

    这么说着，她对我伸出手。

    「朋友……我觉得我们已经是朋友了啊。」

    「温水同学已经把我当作朋友了，我感到很开心。但是——」

    抓住我的手，天爱星同学摇摇晃晃地站起身。

    「如果能够更随意地搭话，或一起出门的话，我会很高兴的。」

    「喔，只是这样的话……」

    我愣愣地回答后，天爱星同学对我投以温柔的笑容。

    「然后……有一天你喜欢上我就更好了。」

    ——突袭。

    除此之外无法形容。

    在我保留回答之后的前方等待着我的，天爱星同学的笑容。

    那笑容对我而言太过刺眼。

    胸口一阵刺痛。

    在感情失去方向的我眼前，天爱星同学用手掌搧着发红的脸颊。

    「现在我才觉得紧张起来。呜哇，我好像说了很大胆的话耶！」

    看着她的反应，我也尴尬地搔搔脸颊。

    「那个，你对我告白，我真的很高兴。所以，我会认真考虑……」

    好不容易挤出话语后，天爱星同学面露羞赧的笑容。

    「好的，我很期待能得到正面的回答。不过，毕竟我也是女生——」

    天爱星将双手交缠在背后，压低身子抬起脸看我，接着说：

    「——你还是早点喜欢上我比较好喔？」

** 尾声 走向大人的阶梯

    冲击的告白后，一夜过去。

    昨晚我睡得不好，一整天睡眠不足，就这么到了放学时间。

    我在印刷室愣愣地看着影印机吐出的原稿。

    ……昨天的天爱星同学，怎么想都是认真的。

    现在回想起来，为何我没有马上答应呢？

    只要用一声『好』回答她的告白，在这个当下我已经有女朋友了。

    是女朋友喔。我原本以为只存在于二次元的女朋友，只差一点就显现于现实世界了。

    如果天爱星同学别管我的心情，攻势更猛烈一点就好了……

    「温、温水，影印机，停了。」

    小鞠打破了我的沉思。

    她将印刷好的原稿敲在桌上，对齐边缘，同时对我投出担忧的视线。

    「你、你没事吗？比、比平常更死鱼眼喔。」

    「啊～……小鞠你在喔。」

    「去、去死。」

    被骂也不能怪她。放学后我和小鞠两个人在印刷社刊。

    我深深叹息，抬头仰望天花板。

    「……唉，小鞠。」

    「怎、怎样？」

    「你——谈过恋爱吗？」

    哗啦啦。小鞠拿在手中的整叠纸张洒了满地。

    「怎么了？小鞠也累了吗？」

    「去、去死！现在，死在这里！」

    为什么要这么生气啊。令人费解。

    我蹲下身子捡起纸张，小鞠也蹲在我身旁伸出手。

    「温、温水，八、八奈见的小说，顺序错了喔。」

    咦？真的耶。收尾那一页跑到最前面了。

    「不，只要坚持说这是种表现手法……」

    「住、住口，重新来过。」

    「……好的。」

    八奈见的小说进入了新篇章。

    我的高中生活也将进入全新的阶段——但我自己对那可能性喊停了。

    「话说小鞠这次也没写啊。遇到瓶颈了吗？」

    「呜唉！？」

    小鞠不知为何惊慌起来。

    哼哼，这反应不会错……她现在写的是BL吧。肯定是见不得人的那种。

    我面露温柔的笑容，将整理好的整叠纸递给小鞠。

    「嗯，毕竟最近很忙嘛。我懂我懂。」

    「你、你这个人，真恶心耶。」

    这种遮掩害臊的方式，现在的我也能宽容视之。

    毕竟我可是距离女朋友只剩一步之遥的男人。

    不，但是为什么我没有马上答应啊……

    我陷入沉思时，小鞠对我投出怀疑的目光。

    「你、你今天真的怪怪的喔。真、真的没事吗？」

    「没事啦。就某个角度来说，我可能真的跟以前的我不一样了。」

    小鞠无奈地叹息后，指向印刷室的门。

    「剩、剩下的我会弄好。你、你回社办等着。」

    「啊，好的。」

    不由分说。面对冷酷的板凳宣告，我老实地点头。

    ◇

    文艺社活动报告　～八奈见杏菜《向你道早》

    之前每天早上造访的便利商店的改建结束了。真是漫长。

    我坐在建筑前方的长椅上，打开了贴着特价贴纸的咖喱面包袋子。

    季节改变，夏天已经快到了。虽然夏天要到了，但也没预定要做什么。

    我吐出多愁善感的叹息，发现××站在长椅的另一端。

    「A子同学，这里的工程结束了啊。」

    ××说完，仰望这家店的招牌。

    我不搭理他，继续吃面包，但××仍不死心，继续向我搭话。

    「我记得你之前说过，要我期待改装结束的这一天吧？」

    是的，我是这样说过。可是那又怎样？

    我继续不理他，××抬头仰望建筑物的招牌。

    「所以，那到底是什么意思？」

    这男生讲话老是挖苦人，一定是这样才会没朋友。

    明明没有朋友却老是跟女生如胶似漆，这种行为最好改一改。

    我叼着咖喱面包，同样仰望招牌。

    大字写着『洗衣天国』的招牌。

    没错，我平常来的这间便利超商，重新装潢之后变成了自助洗衣店。

    原本还以为会有新的便利商店进驻，让我大失所望。

    一定是××不好。我也不晓得就是了。

    「A子同学喜欢自助洗衣店啊。」

    不，并没有特别喜欢。

    听了我的回答，××随口应了声「是喔」，坐在板凳的角落处,开始吃起菠萝面包。

    真是不懂体贴。

    说到为何，是因为最近的我刻意避开甜食。理由是秘密。

    我挪开视线后，面朝道路的偌大招牌映入眼帘。

    为何这里的招牌上面画了狸猫呢？

    我这么一问，××就摆出傻眼的表情。

    「这是浣熊喔。斑纹完全不一样啊。」

    当然，这点小事我也晓得。因为说到洗衣当然就是浣熊嘛。

    只是因为我刚睡醒，一时没想到而已。

    这么不懂女人心的家伙，愿意好心陪伴他的肯定就只有我一个。

    虽然不晓得他为何跑来这里吃面包，一定是觉得寂寞吧。

    偶尔陪他吃早餐也无所谓就是了。

    我吃完咖喱面包，瞥了他一眼后，××就转身背对我。

    「做什么？不会给你喔。」

    这个人真够失礼的。

    我看起来是会讨别人食物的女人吗？

    但是聪明体贴的男生，就算我不开口，也会主动分我一口吧？

    真受不了。既然他还这么孩子气，现在我还得多照顾他才行……

    ◇

    我被逐出印刷室之后，为了前往社办而穿过走廊。

    今天的我可能真的因为睡眠不足而情绪不稳。

    因为昨晚我辗转难眠到深夜时，睡昏头的佳树想钻进我的被窝，闹出了一段小插曲……

    上完厕所回房间时居然搞错，佳树也真是冒失。

    我就要通过布告栏前方时，连忙停下脚步。

    贴在布告栏的是——校园新闻的最新一号。

    本次的特辑包含了学生会选举与体育会等话题，内容丰富。

    头版新闻自然是学生会选举。

    不顾流鼻血而放声嘶吼的天爱星同学的照片，大大地印在上头。

    这新闻，天爱星同学一定读过了吧……

    我阅读报导内文，看来本次演讲会上的脱稿演出，似乎是围绕着某女性公敌男学生A的骚动。

    志喜屋学姊的闯入是男学生A事先安排的，而A菜同学的谜之演讲，则是因为被甩了而当众指桑骂槐。真是人渣耶，男学生A。

    话说回来，这谣言也太离谱了吧。学生会那些人怎么可能喜欢我——

    ……

    …………不，不全然是谣言。

    天爱星同学喜欢我。

    将这当作前提，回顾之前发生的种种，我是不是做了很差劲的事啊……？

    我整理过去的回忆放进心中的置物柜时，校园新闻的一则广告映入眼帘。

    ……打进全国大赛的烧盐的珍藏版照片，收费公开？

    用这种东西赚钱真教人不齿，不过，看都没看就批评也不好。

    让我瞧瞧，收费版要怎么买……

    在我将手机镜头转向QR码的时候——

    「阿温，你在做什么？」

    开朗嗓音传来的同时，烧盐使劲拍打我的背。好痛。

    「我只是在看校园新闻啦。话说烧盐你不用练习吗？」

    「因为是休息时间，我在校舍里面跑。要是在操场上跑，会被教练骂休息也很重要。」

    烧盐露出淘气的表情，用手肘连连顶向我的侧腹。

    「咦？做什么？」

    「你应该有话要跟我说吧？」

    ……对喔，这阵子忙过头了，没有直接跟她提过。

    「啊～恭喜你打进全国大赛。」

    我害臊得板起脸回答后，烧盐嘟起嘴唇表达不满。

    「……就这样？」

    「咦？你不是说这件事吗？」

    「是这件事没错。但是我有两个项目进入全国耶，阿温的喜悦也太平淡了吧？不会想大声欢呼，或是一把抱住我吗？」

    不会喔。阴角一天二十四小时都活得战战兢兢。

    「毕竟还没完嘛。你不是要称霜全国吗？」

    「是没错，那是我的目标喔。」

    烧盐挑起嘴角，露出好胜的笑容。

    「既然这样，赢下全国大赛再麻烦你给个拥抱吧。」

    什么跟什么。我只有好处嘛。

    当我想像着与田径制服打扮的烧盐拥抱的场面时，烧盐睁圆眼睛看着布告栏。

    「话说回来，阿温在看什么？校园新闻？」

    「啊，没有啦，这是——」

    烧盐阅读报导，脸庞渐渐失去表情。

    读到最后一个字之后，她对我投出不愉快的目光。

    「……啊，女性公敌在这。」

    「只是谣言啦。况且这里写的男学生A也不一定是我吧？」

    「就是阿温啊。」

    是这样没错，但不是这么回事。

    我迷惘着该如何解释时，烧盐的视线盯向我的智慧型手机。

    「咦？怎么了？」

    「……唉，你刚才该不会是想买我的照片？」！不妙，我忘记自己刚才启动了手机相机。

    「没有啦，那个喔，只是手指偶然摸到才启动相机……」

    我支支吾吾地辩解时，烧盐面露不怀好意的笑脸——使劲一拍我的背。真的很痛。

    「又怎么了！？」

    「阿温果真是女性公敌。我要跟小千打小报告。」

    「为何扯到朝云同学！？」

    虽然与她无关，但我很不愿意。因为很恐怖。

    我惊慌失措时，烧盐再度拍打我的背，随即俐落转身，拔腿跑远了。

    ◇

    我回到社办时，温馨的情景正在眼前上演。

    「八奈见学姊，嘴巴张开～」

    「我来了，啊～」

    八奈见张大了嘴，白玉学妹就把迷你竹轮抛进她嘴里。

    和我在竹岛水族馆的海狮秀见到的情景十分神似。

    「你们两个在做什么？」

    注意到我走进社办，白玉学妹亲切地微笑。

    「亲戚送了一些竹轮，我想分给大家一起吃。社长也要我帮忙喂吗？」

    「谢了。我就不用了。」

    近来这两人不知为何特别亲近。

    据说决定性的关键在于白玉学妹帮忙捡了橡皮擦，不对，是饭团。不过那究竟是何种状况，而八奈见是否吃了捡回来的饭团，至今仍疑点重重。

    「温水，社刊印好了吗？我们都准备就绪了耶。」

    八奈见手拿钉书机，对着空气夹出喀喀声。

    我和小鞠负责印刷，八奈见与白玉学妹则负责装订。

    「很快就会结束了。顺带一提我被裁员了。」

    两人异口同声说「啊～」。看来今天的我在每个人眼中都不中用。

    既然如此，我索性真的当个女性公敌，把工作扔给女生们，自己悠闲度过。

    我坐在椅子上看向墙壁时，叩叩的敲门声传来。

    八奈见说「请进～」之后，房门开启了。

    「打扰了，请问温水同学在吗？」

    走进社办的是天爱星同学。

    因为昨天才发生过那种事，我不禁从椅子上跳起来。天爱星同学见状，表情似乎松了口气。

    「呃，那个，你直接跑来社办是怎么了吗？」

    「我把之前约定好的东西送过来。一直错过能给你的机会。」

    ……约定好的东西？天爱星同学向我递出一个模样可爱的纸袋。

    我看向里头，装了好几种小奇卡的店家宣传海报。

    「我可以收下这个？真的？」

    「我们之前不是说好了吗？」

    是这样没错，但是我的辛劳直接得到回报，这还是入学以来第一次，让我吓到了。

    呜哇，这是第一季开播之前的超稀有海报耶。

    我拿到海报而眉开眼笑之时，天爱星同学仔细打量我的表情。

    「温水同学，你今天会忙到很晚吗？」

    「呃～因为要做社刊，大概会有点晚吧。」

    「哎呀，真可惜。因为学生会的事提早忙完了，我本来想和你一起回去的说。」

    「咦？和我？」

    喀嚓。八奈见按响钉书机。

    「……选举都结束了吧？为什么要两个人一起回去？」

    「也没有什么特别的理由。既然是朋友，放学偶尔一起走也不错。」

    天爱星同学轻描淡写地说完，转身面对白玉学妹。

    「那么我就换借白玉学妹吧。可以麻烦你跟我来一下吗？」

    「好的，不要太久的话没关系。」

    白玉学妹瞄了我一眼，站起身。为何天爱星同学要找白玉学妹？

    对着表情讶异的我，白玉学妹神态可爱地眨了眨单边眼睛。

    「社长，我决定要加入学生会了。」

    「咦？」

    罪犯也可以进学生会吗？

    呃，不对，反正上届会长也是共犯，也许在这方面出乎意料地宽松。

    我迳自释怀后，天爱星同学向我稍稍低下头。

    「是我向她提出请求的。当然我也会特别关照，避免影响文艺社的活动。」

    我才该道谢。你愿意一起管理未爆弹，真是求之不得。

    「我们社团没问题。那么马剃同学，白玉学妹就麻烦你了。」

    就要走出社办时，天爱星同学转过头来。

    「哎呀，今天你不用名字称呼我啊。」

    「因为，你不是讨厌人家用名字称呼你吗？」

    我发出单纯的疑问——回答则是天爱星同学的笑脸。

    「温水同学的话没关系喔，用名字称呼我也可以。」

    允许用天爱星称呼……居然有这种事？

    见到我愣住，天爱星同学再度嘻嘻一笑，带着白玉学妹离开了社办。

    我确认房门关闭后，沉重地坐回椅子上。

    虽然今天勉强撑过去了，但是往后可不容易啊……

    「……盯～」

    八奈见一边加上效果音，一边直盯着我看。这是怎样？

    「你有什么话想对我说吗？」

    「刚才那是怎样？你和马剃同学之前就像那种感觉？」

    「那种感觉……什么感觉？」

    「你称呼我永远都是姓氏加『同学』，对马剃同学就用名字称呼？是喔～」

    原来如此，你要针对这点吐槽啊。原来如此啊……

    我双肘抵在桌面上，十指交叉挡住嘴巴。

    「哎，八奈见同学你听我说。我和马剃同学的确在经历选战之后，加深了对彼此的认识。与新学生会长建立人脉，也能强化文艺社日后的地位，这和八奈见同学的目的也相符吧？」

    听了我完美的说明，八奈见表情依旧不快，把迷你竹轮放进口中。

    「所谓的学生会选举，是要选出学生代表的神圣活动喔？你表面上打选战，背地里跟女生打关系，是不是有点心术不正啊？」

    「要这样讲的话，八奈见同学还不是一样。」

    「我怎样？」

    八奈见听了我脱口而出的话语，表情狐疑。

    「八奈见同学在选举期间也和樱井一直在一起吧？那家伙很也受女生欢迎，你那样我觉得不太好喔。」

    「樱井？那个人一直在忙学生会的工作，也没有常常在一起——」

    八奈见话说到一半，突然间露出有所惊觉般的表情。

    「八奈见同学，怎么了吗？」

    八奈见没有回答，突兀地站起身，在我身旁猛然坐下。

    ……咦？是怎样？很恐怖耶。

    对着胆颤心惊的我，八奈见以捉弄般的口吻说：

    「温水——你果然就是在吃醋嘛。」

    ……唉？吃醋？我？

    八奈见同学你是在说什么啊。我连忙摇头。

    「不是啦。我只是觉得樱井被人家传些有的没的，也会觉得很烦吧。」

    「……为什么主角变成樱井了？」

    八奈见的表情突然变得严肃。

    「你问为什么？我一开始就是在讲樱井啊。」

    「不对吧！？刚才说的是因为我和樱井走得很近，温水就吃醋了吧！」

    就是同一件事啊。呃，所以说，换个讲法就可以了……？

    「我的意思是说，如果和八奈见同学传出奇怪的谣言，樱井很可怜——」

    「有什么好奇怪的！？」

    已经很奇怪了喔，八奈见同学。果然不能放心把我的樱井交给她啊……

    八奈见无奈地叹息后，手伸进迷你竹轮的袋子里。

    「你的问题就出在这里啦，温水……来，这个很好吃喔。」

    八奈见将迷你竹轮递到我嘴巴前方。

    我不假思索就吞进嘴里，竹轮的香气在口中漾开。

    「啊，这个有加胡椒啊。」

    「很不错吧？我最近特别迷这个。」

    不知为何八奈见心情又突然转好，将最后一个竹轮放进嘴里。

    我愣愣地看着她的吃相，同时思考八奈见说的话。

    ……在这家伙眼中，我看起来似乎像是在吃醋。

    樱井是我少数的男性友人，看他与八奈见走得很近，的确让我有种疏离感。

    要用吃醋来形容这种感觉，也许也不算说错。

    同样的道理，与樱井出双入对的八奈见也是我朋友，那种疏离感也就更强了——

    自己的心情得到了解释，让我松了口气，这时吃完竹轮的八奈见用指尖卷着发梢，对我提问：

    「……这些先不提，话说马剃同学借物赛跑的题目，到底是什么？」

    「为什么你会在意这种事？」

    「因为马剃同学在全校学生面前牵着男生的手跑向终点喔？在校园新闻里头也被写得很夸张，不说明清楚会被误会喔。」

    误会……不全然是误会。

    天爱星同学抽到的题目是——喜欢的人。

    校园新闻写得天花乱坠的八卦报导中，唯独一点说中了事实。

    「这种东西愈是反驳就会拖愈久。无视最好啦。」

    很好，这回答满分。这样八奈见想必也会接受我的说法。

    「这样说也有道理。所以呢？题目是什么？」

    ……嗯，她没有接受。

    总觉得视线有点恐怖，随便蒙混过去吧。

    「朋友——对了，是男生朋友！」

    「哦～不晓得会由谁抽到的题目，会写男生朋友啊？」

    八奈见嘀咕般自言自语，手撑着脸颊，对我投出怀疑的目光。

    「事、事实如此……」

    「哎，算了，反正也把小白玉送进学生会了。」

    「这是什么意思？」

    「你说呢？会是什么意思？」

    八奈见用装模作样的口吻搪塞之后，猛然站起身。

    她就这么走向窗边，我看不见她的表情。

    ——在桥上被天爱星同学告白的时候。

    坦白说，我感到疑惑。

    不是对于告白，而是对于迟迟不回答的自己。

    更重要的是——在我即将说『好』答应告白的瞬间，在眼前一闪而过的身影。

    那道身影的意义与自己的心情，才过短短一晚，我什么都还分不清楚。

    到天爱星同学决心向我告白为止，究竟度过了几个夜晚呢——

    「天色愈来愈暗了呢。」

    眺望着窗外的八奈见拉起窗帘。

    「……做什么？一直盯着我看。」

    不开心与傻眼，以及其他的情感。

    八奈见面露那混杂了好几种情感的表情，默默凝视着我。

    尴尬的沉默。

    我无法忍受下去，正要开口说话时，八奈见忽然——笑了。

    「——温水，你真的是女性公敌耶。」

** 后记

    终于！《败北女角太多了！》第二季决定制作了！

    这一切都是多亏了支持本作的各位，以及为此努力的诸位相关人士！

    我在第七集的后记提到了动画化，不过实在没想过第八集就能向各位报告第二季决定要制作的消息。

    看来前世的我又拯救世界了啊……

    在第一季（能这样称呼的喜悦！）播放后，围绕本作品的种种状况随之改变。

    于『这本轻小说真厉害！2025』有幸获得综合第一名，本作的舞台丰桥市也有许多粉丝前来圣地巡礼。

    听说其中也有人再三造访，甚至有人决定要搬到丰桥定居。

    这一切也是多亏了丰桥市的各位愿意接纳本作品粉丝心意的宽大心胸。

    距离动画第二季的播放虽然还有段时间，不过已经有第一季动画、原作、漫画版、合作活动与圣地巡礼。

    还有许多乐趣等在后头。

    希望各位也一起成为石蕗高中的一员，一起享受青春吧！

    ……其实我写这篇后记的时间，恰巧是在昭岛市举办的『石蕗高中文艺社课外活动』的隔天。

    饰演角色的声优们、ぼっちぼろまる老师、もっさ老师带来了最棒的表演，兴奋之情至今仍未平复。

    在第二季发表的瞬间、会场充满喜悦的瞬间，我一辈子都不会忘记吧。

    希望今后也能抱持着这份感动，继续书写败女的故事。

    那么，本次第八集的主角是天爱星同学。

    拿出勇气跨出那一步的她会有怎样的将来，希望各位继续温暖地守候下去。

    这次也为本书孕育了无数神插图的IMIGIMURU老师。

    充满耐心陪伴我改稿的岩浅编辑。

    非常感谢两位的照顾！

    以及购买第八集的各位！

    希望还能在下一集再次相见！

** 特典 证明我可不迟钝

    运动会的啦啦队竞赛结束后，男学生们在2年C班的教室更衣。

    绫野光希一边解开立领制服的扣子，一边向在旁更衣的友人搭话。

    「唉，你觉得最近的温水怎样？」

    「你是指什么？」

    樱井弘人因为突兀的问题而歪着头。

    他拍打脱下的立领制服，拂去沙尘，同时表情纳闷地反问。

    「那家伙最近时常和马剃同学在一起吧？在我看来，那两个人好像感觉不错。」

    「不晓得耶。马剃的确对他特别敞开心房就是了。」

    突如其来的恋爱话题令樱井纳闷。

    「为什么突然提起这个？」

    「因为之前我和千早的事情，受到温水不少照顾。为了回报恩情，我想对他的恋爱提供协助。」

    如果是这样，直接和他本人商量应该比较好吧？

    虽然这么想，但樱井没有说出口。樱井弘人是个大人。

    「首先得确定温水的心情。你前阵子不是才说，他和烧盐同学的关系很可疑吗？」

    「我之前一直都这样想，但是迟迟没有变化。我觉得温水好像没这种念头。」

    「哎……毕竟温水也不是会对女生猛攻的那种个性。」

    樱井一边说一边穿上运动服，这时绫野的眼镜朝着他亮起。

    「是柠檬这样的女生喔，凡是男人当然都会喜欢。然而他却迟迟没有告白的迹象，就表示温水另有其他心上人。」

    见到充满自信的绫野光希，樱井弘人陷入思考。

    视自己当下的回答，有可能会招惹麻烦。

    「这个嘛，我对烧盐同学不太熟……不过既然是这么优质的对象，产生的感情也可能是憧憬或尊敬之类的吧？」

    为了蒙混过关而搬出的中规中矩的常理，让绫野立刻反应。

    「原来如此，有道理。的确我也是——」

    话说到一半的瞬间，放在桌面上的绫野的智慧型手机萤幕发亮。

    「……啊啊，是千早啊。」

    「她有事找你吗？」

    「不是，我偶尔会收到千早送来的空白讯息。」

    绫野喜上眉梢，咧嘴而笑。

    「她说是因为重读我传的讯息时，不小心就送出回讯。真伤脑筋。」

    「那还真是多谢招待。」

    ……深入追究这话题不太妙。本能的直觉令樱井产生这种感受，他改变话题。

    「话说回来，你和温水是同一个国中的吧？那时候他给人的感觉是怎样？」

    「虽然同一个国中，但是不同班。起初是柠檬告诉我，她班上有个和我一样老是在读书的同学，我才会在补习班和他搭话。当时柠檬那家伙——」

    绫野的智慧型手机萤幕再度发亮。

    ……这话题也不太恰当。虽然说不出理由，但樱井有这种感觉。

    樱井的视线转向绫野脱下的立领制服，再度改变话题。

    「先不提这个，绫野，国中时的制服真亏你还穿得下。」

    绫野表情得意地拿起立领制服。

    「千早帮我加长了制服的袖管。手艺很不错吧。」

    「哦，真是了不起。完全看不出修改的痕迹。」

    樱井神色钦佩地打量立领制服，视线停留在某一点。

    「怎么了吗？」

    「只有第二颗钮扣特别新，该不会是在毕业典礼时给了别人？」

    「我可没遇过那种事件……真的耶，钮扣换新了。」

    他大概在这时才发现钮扣被更换了吧。

    绫野起初显得不可思议，随即有所察觉般羞赧地微笑。

    「一定是千早那家伙想要第二颗纽扣吧。老实跟我说不就好了。」

    樱井险些开口，但因为绫野的笑容而咽下话语。

    「…………嗯，就是说啊。」

    绫野的女友朝云千早，樱井自放虎原口中听闻过她的事迹。

    虽然心中有些想法，但是就别再深究下去了。

    没错，有些时候变得迟钝——也是必要的。

** Animate特典 夹缝之国的天爱星同学

    网译版 转自 轻之国度

    图源：小村雏

    翻译：K4tze、逍遥过、玉米、灰鸽Gizensha、pe77、木之本樱、占位符、赤道煮雪、Miuna、幽幽

    校对：Hau-45、优秀的黑羊、小村雏

    石蕗高中二年级，马剃天爱星。

    品行端正，在教师们眼中也是认真负责的形象。

    「真的没问题吗……」

    学生会选举前的某个休息日。

    有着如此评价的她正在房间的穿衣镜前打量着自己的倒影。

    平时束起的头发被松开，双耳上方一些的位置扎起了轻巧可爱的小马尾。

    校服裙子向内折短，腿上穿着竖纹及膝袜。

    ……不行，不能临阵脱逃。

    天爱星露出破釜沉舟的表情，慢慢竖起双手的食指。

    接着滴溜溜地转动起来。

    「瞄准你的心脏——知佳兔光线！」

    手指径直对准镜中的自己。

    ……完美。天爱星满意地点了点头。

    嘎吱一声，房间的门被打开了。

    「姐，你朋友来了——」

    打开房门的是天爱星的弟弟——贵司。

    尴尬的空气弥漫在相视而立的姐弟之间。

    「哦，在忙啊。」

    「会、会长？！」

    在贵司背后现身的，是石蕗高中学生会会长放虎原阳叶里。

    总算从僵直状态缓过来后，贵司转过身，表情仍旧复杂。

    「那个……放虎原学姐，请自便。」

    只剩两人之后，放虎原苦笑着拢了拢头发。

    「正巧路过这里就想着顺便来看一下，是不是打扰到你了？」

    「没、没这回事！请问……刚才的您听到了吗？」

    「嗯？听到什么？」

    「不不，没什么！我去拿些点心上来！」

    放虎原递出一个袋子，打断了想要逃走的天爱星。

    「点心的话我带过来了，饮料也有。」

    「……劳您费心了。请坐下聊吧。」

    相对而坐后，放虎原兴趣盎然地打量起天爱星的打扮。

    「这就是所谓的改变形象啊，你可真有勇气。」

    「没有，这是……动画片里一个叫知佳兔的角色的打扮，我只是……」

    「噢，原来是Cosplay啊。没想到马剃还有这种兴趣。」

    「这哪里是我的兴趣了？！」

    看到急忙否定的天爱星，放虎原双手合十。

    「原来如此，是为了迎合对方的兴趣啊，这样就说得通了。」

    「请不要妄下定论！我就没有那种对象！」

    面对又一次否定的天爱星，放虎原露出了疑惑的神情。

    「但是你和志喜屋，不是那种所谓的纯肉体关系吗？」

    「怎么可能？！我很尊敬志喜屋学姐，但是我们绝不是那种关系！」

    既不是天爱星自己的兴趣，也不是为了迎合志喜屋——

    「那么——是有其他中意的对象吗？」

    放虎原一脸疑惑地问道。

    「啊，其他对象……哦，是草莓大福！我很喜欢吃这个！」

    天爱星露骨地转移开话题，从袋子里拿出了点心。

    「这个啊，是在八町那边的点心店买的，我爸妈是那儿的常客。」

    「那家的点心很好吃呢……话说会长，我的脸怎么了吗？」

    感觉到放虎原的视线，天爱星露出了诧异的表情。

    「不好意思。只是有点惊讶你头发松开后居然有这么长。」

    「这个是在美容院接的假发。当然是在校规允许范围内的。」

    「没必要遮掩，挺合适的。」

    放虎原满脸微笑地注视着羞怯地按住头发的天爱星。

    轻松的谈笑结束后，天爱星咳嗽了一声，重新面向放虎原。

    「话说回来，会长突然来找我是有什么事吗？」

    「感觉你最近有点在勉强自己的样子，所以就想着来慰问一下。」

    「这话说的，特意来关照我的话对樱井同学不公平吧？」

    面对有些闹别扭的天爱星，放虎原洒脱地笑道：

    「弘人和你都是我重要的学弟学妹，两边我都加油。」

    「……谢谢会长。」

    意识到自己敌不过会长后，马剃松弛一笑。放虎原借机抛出疑问：

    「马剃，有件事想问一下你。」

    「好的，是什么事？」

    天爱星咽了口唾沫，毕恭毕敬地挺直身子。放虎原一脸严肃地开口道：

    「刚才的知佳兔光线——是什么东西？」

    「明明听到了嘛！？」

    放虎原不顾满脸通红地抗议着的天爱星，接着说道：

    「从『瞄准你的心脏发射』一句来看，这种光线大概是有催情作用。也就是说，马剃是想色诱某个人，但这个人又不是志喜屋，那么——」

    「这个话题已经过去了！」

    学生会选举前，某个休息日的午后。

    丰桥市花园町的旧商店街里，回荡起了马剃天爱星的悲鸣——

** 蜜瓜特典 各有所求的蓝与白

    体育节下午场开始，操场的欢呼声甚至传到了文艺部活动室。

    一年级F班的白玉莉子穿着啦啦队比赛时的衣服，用手机自拍。

    重拍了几次后，似乎终于拍到了满意的一张。

    在一边哼着歌一边将照片发给了某人之后，她开始脱起衣服。

    「有人吗——，我开门了哦——」

    伴随着无忧无虑的喊声，活动室的门被打开了。

    「下午好，八奈见学姐。」

    大摇大摆地走进活动室的，是八奈见杏菜。

    她身上穿着啦啦队比赛用的队服。

    「小白玉，你在这里换衣服啊。」

    「我和班里的女生们处不太来，还是这里更方便一点。」

    「哦、哦……」

    听到白玉轻描淡写地说着令人难受的事，八奈见不禁有些狼狈。

    面对失态的八奈见，白玉疑惑地问道：

    「学姐才是，为什么会来这里换衣服？」

    「刚把小鞠送到了医务室，来这边换更近一点。」

    「小鞠学姐出什么事了吗？」

    看着白玉担心的表情，八奈见一脸严肃地摇了摇头。

    「与其说是出事，不如说是出名——她成了传说。」

    一瞬间，白玉下意识地打算继续询问，转念一想后还是点了点头。

    「我明白了，是这么一回事啊。」

    「嗯嗯，就是这么一回事。」

    八奈见露出满意的表情，脱起了上半身的衣服。

    白玉也继续换起衣服。静默的活动室里，缓缓传来布料的摩擦声和打开包时的拉链声。

    片刻的沉默后，远处传来『哇』的欢呼声和示意冲线的枪声。

    瞟了一眼墙上的时钟后，八奈见的目光停在了正在换衣服的白玉的身体上。

    「……好细。」

    八奈见不自主地流露出心声。

    白玉手里拿着擦汗布，回应道：

    「怎么了吗？」

    「啊，没什么……只是想问问你平常一般吃什么。」

    面对八奈见的试探，白玉将手指贴上脸颊，摆出努力思考的可爱姿势。

    「因为我喜欢蔬菜，所以应该总是在吃沙拉吧。」

    「只吃蔬菜？肉和米饭呢？」

    「光吃沙拉就饱了呀。我说不定不是貉狸，而是小兔子呢。蹦——蹦——」

    「只吃沙拉……就饱了……？」

    八奈见咕哝着定在了原地。

    看到自己的表演被无视，白玉若无其事地继续换起衣服。

    「其他的话——肉的话最近一直在钻研鸡肉火腿。很有意思的。」

    「火腿……！我就说嘛，也要算上这个嘛！」

    说服自己后，八奈见以上半身只穿着内衣的样子摸索起书包。

    看到这幅光景，白玉无意识地喃喃道：

    「……有了那个的话哥哥也——」

    八奈见晃动着从包里拿出的喷雾，疑惑地问道：

    「你在说什么？」

    「不不不，没什么。顺便问一下，八奈见学姐平常一般吃什么呢？」

    「嗯——，我更注重平衡吧。」

    八奈见一边回答着，一边喷起止汗喷雾。

    「原来如此，学姐会考虑营养平衡啊。」

    「差不多就是这么回事。吃了咸的东西后，会想吃甜的东西对吧？然后吃了甜的东西后，又会想吃咸的东西，这样不就无限循环了吗？」

    「嗯，是的。」

    当八奈见谈起食物的时候，绝不能反驳她。

    白玉莉子老老实实地点头。

    「也就是说，放有柿种的雷神巧克力是最优解。靠油渍柿种就可以调整甜味和咸味的比例，所以吃无限个都没关系——咦，我们在聊什么来着？」（注：柿种，一种米果。）

    八奈见一脸疑惑地将体操服套过头顶。

    「秘诀果然还是健康的肠胃吧……」

    白玉凝视着八奈见那引入注目的胸口。

    八奈见一边用手整理着头发，一边盯着白玉的细腰。

    互相注视的两人口中，流露出了同样的呢喃：

    「「……好羡慕。」」

** 精文馆书店特典 教教我☆小鞠老师

    精文馆书店总店的参考书专区。

    可以看到小鞠知花和烧盐柠檬的身影。

    烧盐扫视着书架，向一本参考书伸出手。

    「我看看，高二数学是这本吧。」

    「别、别急。」

    小鞠果断制止了烧盐。

    「怎么了，小鞠？」

    ——不愿伤害友人。

    小鞠考虑了一会后，慎重地开口：

    「那、那个……不局限于学年，找到自己真正需要的参考书，很重要。」

    「哦——，是这样啊。小鞠你真聪明。」

    烧盐语调轻快地回应道，接着歪头询问：

    「那应该怎么选？」

    「等、等一下。」

    小鞠翻看起几本参考书。

    「这、这本怎么样？基础知识写得很清晰。」

    「我看看，字也很少，感觉不错啊！」

    烧盐一边说着一边哗啦啦地翻动参考书，接着又一次询问道：

    「但是这里不是写着『初中三年级』吗？」

    「别、别局限于学年。」

    「哦——原来如此。」

    烧盐不明所以地赞同着，啪的一声合上了参考书。

    「好，参考书也选好了，这么一来备考策略就完成了！」

    「不、不好好学习的话，可是没有用的。」

    听到小鞠的提醒，烧盐一时僵住了。

    「没有那种只要拥有就能提升智力的参考书吗？」

    「没、没有。」

    「……我想也是。」

    直面残酷的现实后，烧盐握紧参考书，下定决心。

    「好，就用这本书好好学习。这样备考策略就完成了！」

    「只要数学就够了吗？」

    「我想想，其他还有——」

    烧盐一边扫视书架一边掰起手指。

    「世界史、古文跟现代文，生物跟英语，这些全都挺危险的。」

    「所、所有科目啊。」

    「……嗯。」

    小鞠看着参考书的书架，脸上露出几近面如死灰的表情。

    「从、从一年级的教科书开始重新过一遍吧。」

    「到头来只能这样了啊——」

    烧盐绝望地仰天哀叹。突然，她像是意识到了什么似的朝小鞠探过头。

    「等等？你刚才说重新过一遍的意思是？」

    「就、就是说——」

    小鞠害羞地摆弄起刘海，小声说道：

    「不、不介意的话，我可以教一下你。」

    「小鞠，真的吗？！」

    话音未落，烧盐就把小鞠抱了起来。

    「干、干嘛！？放、放我下来！」

    「有什么关系嘛，就让我抱着你走吧。」

    「有、有损店容！会被禁止入内的！」

    听到『禁止入内』一词，烧盐突然老实了下来，放下了小鞠。

    「啊——，嗯……禁止入内可不行啊，会被妈妈骂的。」

    「发、发生什么事了吗？」

    烧盐盯着手里参考书的封面，没有回答。

    「既然是从高一开始重新学的话，这本参考书应该用不——」

    「还、还是要了比较好。」

    小鞠打断了她的话。

    牵着无力点头的烧盐，小鞠走向了收银台——

** Bookwalker特典 健康学习会

    ※请先阅读正文剧情后再阅读该短篇。

    某一天的放学后，我来到石蕗高中的主楼里。

    我避开其他人的视线，打开了写着「学生指导室」的房门，迅速钻了进去。

    我打开灯，眼前是一间死气沉沉的房间，里面只有一张桌子和两把椅子。

    我把背包放在桌子上，茫然站在原地时，房门再次被打开，一位女生安静地进入了房间。

    女生反手锁上了房门。她是石蕗高中学生会副会长——马剃天爱星。

    「你真准时。」

    「温水同学，这边从窗外可是看得一清二楚的啊。」

    天爱星同学快步走到窗边，拉上了窗帘。

    「你进房间的时候有没有被人看到？」

    「嗯，应该没有……」

    天爱星同学像是终于松了口气似的，把包放在桌子上。

    大概谁都不想知道她在跟我这种阴角男生密会吧。

    我坐在椅子上，内心泛起苦笑。

    说是「密会」，但其实并非目的不纯。

    因为天爱星同学会时不时突然要求我开秘密学习会。

    今天她说想让我教她古文，但我的水平也没有好到可以教别人啊……

    「麻烦你特地过来，真不好意思。这次备考实在是没什么进展。」

    天爱星同学难堪地坐在对面的椅子上。

    「毕竟马剃同学还有学生会的工作嘛，不怪你。」

    「哎呀，温水同学你不也有文艺部的活动吗？还是说根本就不组织活动呢？」

    「那是——」

    我话音未落，看到天爱星同学兴趣盎然的神色后便耸了耸肩。

    「没办法，我也很忙啊。今天就麻烦你了。」

    「当然。你有什么不懂的我教你。」

    说罢，天爱星同学微微窃笑。

    其实她的成绩并不好。

    我最近的成绩也顺利下滑了，但天爱星同学则是经常差点挂科。话虽如此，她跟全科不及格的烧盐比起来绝对算得上优等生。

    秘密学习会静悄悄地开始了。

    我们翻开笔记和课本，从头开始复习考试范围内容。

    房间里暂时只能听到翻书和自动铅笔在纸上划动的声音。

    换作是在文艺部的活动室，就会因为吃零食的声音分心，今天安静一点就挺好的……

    大约过了十五分钟。

    「……《枕草子》初中的时候也教过吧？」

    天爱星同学看着笔记，喃喃自语道。

    说起来，好像还真教过。

    我正搜寻着模糊的记忆时，天爱星同学一副怀念的样子继续说道：

    「那时候根本想不到古文居然会这么难。」

    「毕竟初中的课程是为了让我们爱上古典文学。以前有印象深刻的句子就跟朋友互相讨论，还聊得兴高采烈呢。」

    天爱星同学听完我的话，诧异地抬起头。

    「咦，你初中的时候还有过这样的经历啊。」

    「没有，我说的是身边的人。我当时又没有朋友。」

    「……不好意思，请当我没说过吧。」

    天爱星同学，你这个时候应该笑才对。

    在莫名严肃的气氛下，我们的学习会继续进行着。

    我默默地翻看了一会儿笔记后，瞥了一眼天爱星同学的样子。

    她貌似在背诵活用表，嘴巴微微开合。

    ……仔细想想，现在这个情况，我们是在一起学习吧。

    放学后、密室、男女二人、备考——

    咦，难不成我现在正在体验青春？很明显吗？

    ……等等。去年夏天八奈见在地下资源馆也说过类似的话，但当时青春早就全速从我身边飞驰而去了啊。嗯，是我搞错了。

    ——天爱星同学扎着往常的盘发。

    她皱起稍显靓丽的眉毛，用自动铅笔的笔尖连续敲击参考书。

    天爱星同学的脸其实比我想象中要小，而且她头发是往上拢起来的，使得洁白的脖子非常醒目，但由于学生会还有其他美女，所以我老是会无意中忘记这一点。

    总感觉她脖子上的黑痣也很色——呃，我就不明说了。要是她待人好一点的话应该会很受欢迎吧。

    我焦躁不安地思考着这些事情时，天爱星同学不知不觉间一脸讶异地凝视着我。

    「温水同学，我怎么了吗？」

    「啊？没有，我看你面露难色，就想着你是不是遇到了什么困难……」

    我随口掩饰过后，天爱星同学叹了口气，用手指抵住眉间。

    「唉……真是谢谢你。古文的活用表我记不住。」

    「哦，活用表我也费了好大劲才记住的。」

    「真是一记就忘。本以为终于能记到最后，结果开头的部分又记不住了。你有什么诀窍吗？」

    天爱星同学把参考书推到我的面前。

    「嗯……按标准方法的话——我会把这些知识跟其他记住的知识串联起来。」

    「串联？」

    天爱星同学疑惑地眨了眨眼。

    「比较著名的就是英文字母歌了吧。谐音梗好像也是这样，除此之外我还会——」

    我从文具盒里拿出一只圆珠笔。

    「把它们写在手上。」

    「啊，打小抄吗？」

    不是。

    「没有，你不是想记活用表吗？比如说你要用笔写，那就固定食指写下一段活用，中指写サ行变格活用。据说这样记忆，考试的时候看一眼手指就能想起来了。」

    「原来如此……就是写在身体上辅助记忆对吧。」

    天爱星同学重重点头，拿起圆珠笔在自己手上写了起来。

    啊，她要在这里写，不是回家写啊。

    不过既然都给出建议了，再叫她别这么做也不太合适啊……

    我有些尴尬地看着笔记，天爱星同学突然乐呵呵地笑了。

    「还蛮有意思的。」

    「在自己手上写字像小孩一样。感觉有意思起来了。」

    天爱星同学继续在手上写着字，时不时偷笑。

    ……算了，她自己开心就行。而且她好像连歌都哼起来了。

    我听着天爱星同学哼歌，重新看回课堂笔记。

    大概又过了三十分钟。

    我终于复习完所有考试内容，伸了个大大的懒腰。

    天爱星同学已经彻底安静下来，手握圆珠笔愣着不动了。

    「马剃同学，怎么了吗？」

    「那个，我手上没地方写了，该怎么办？」

    天爱星同学略显窘态，她的左手上都写满了活用表。

    这么一看感觉挺诡异的。

    「嗯……你要不写右手上？」

    「我本来想写的，但我是右撇子。」

    哦，确实有道理。

    正当我径自理解时，天爱星同学将圆珠笔递给了我。

    「所以……温水同学能帮我写上吗？」

    啊？写上，是指写在天爱星同学的手上？我来写吗？

    「不不不，你先暂时擦掉左手的字不就能继续写了吗？」

    「按你的说法，这样记忆其实是为了把所见知识和记得的知识联系起来。在同一根手指上写不同的东西，不会记岔吗？」

    天爱星同学有时候说的话还挺正经的。

    「可是这样写我就得碰马剃同学的手了……」

    我本打算婉拒，却反而刺激到了天爱星同学。

    她满脸通红地说道：

    「请、请不要误会！我可没有想跟你牵手好吗？！」

    「呃……嗯，我明白。说到底还是为了学习嘛。」

    「没错！所以——」

    天爱星同学越过桌子猛地朝我伸出右手。

    「为了学习，就算玷污这副身体我也毫无怨言！」

    她太言重了。

    而且这句话放在黄色漫画里面相当于乌鸦嘴，还是别说出来的好。

    「呃，要是马剃同学愿意的话就行……」

    我也越过桌子伸出手后，天爱星同学面露不满。

    「你在我对面，写的字不都反过来了嘛。能到我旁边来吗？」

    「呃，那……」

    「来，请吧。」

    我连人带椅子移了过去，轻轻地抓住天爱星同学的手掌。

    她的手掌虽然缺乏志喜屋学姐的妖艳，却很有少女感，小而纤细。

    ……天爱星同学也是女生啊。

    我正想着自己都觉得很失礼的事情，战战兢兢地将圆珠笔靠近天爱星同学的手掌——

    「嗯！」

    笔尖刚一碰到手掌，天爱星同学的口中便吐露娇声。

    「那个，你要是痒的话……」

    「没、没问题。请继续。」

    天爱星同学低着头，咬着嘴唇说道。

    我无言点头后，慢慢地将圆珠笔的墨水刻画在她的手掌上。

    始于上二段活用的玩法——纠正，是记忆术，马上就要轮到ナ行变格活用了。

    正当我在她的小指上写起『ぬ』字时，天爱星同学的肩膀突然一个激灵。

    「温、温水同学，你、你不要老是画来画去的……」

    「没办法啊，『ぬ』字曲线太多了。你再稍微忍忍吧。」

    「好、好的。ナ行变格活用的第二个是——」

    「是『ぬる』吧。」

    「唔……！」

    ぬ、ぬる、ぬれ、ね——

    天爱星同学小指上ナ行格形活用的字符渐渐多了起来。

    她颤抖的脖颈上微微渗出了一层汗水——

    ……不好，感觉连我的心情都变奇怪了。

    说到底这只是为了学习。绝对不是什么特殊玩法。

    真的，绝对不是这样。

    我在默默说服自己的同时，写完了最后一个字，随后天爱星同学难受地吐了一口气。

    「请、请让我休息一下……！」

    「呃，比起休息，还是继续借着这股劲儿写ラ行变格活用吧。」

    「ラ行变格活用是……」

    天爱星同学眼眶泛泪地看向参考书。

    ら、り、り、る、れ、れ——

    和ナ行变格活用比起来曲线要少一些。

    天爱星同学依旧面红耳赤地点了点头。

    接下来是无名指。

    当笔尖慢慢划过时，天爱星同学的肩膀便微微发抖。

    天爱星同学现在还没有注意到。

    ——ナ行变格活用最后要连续写两遍『れ』。

    ——一个月后，我被天爱星同学告白了。

    回想起来，或许从这时候开始就出现了这个迹象。

    我后知后觉地如此心想道。

◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆

更多精彩热门日本轻小说、动漫小说，尽在轻小说文库(Www.WenKu8.Com)