#+TITLE: 高中语文古诗词合集
#+DESCRIPTION: 仅用于缩印背书用，请勿模仿
#+DATE: <2026-01-10 六 01:20>
#+SETUPFILE: ../../../setup.setup

#+begin_quote
May the force be with you.

愿原力与你同在！

    ——《星际大战》
#+end_quote

* 原文
** 必修上
*** 短歌行（曹操）
对酒当歌，人生几何！

譬如朝露，去日苦多。

慨当以慷，忧思难忘。

何以解忧？唯有杜康。

青青子衿，悠悠我心。

但为君故，沉吟至今。

呦呦鹿鸣，食野之苹。

我有嘉宾，鼓瑟吹笙。

明明如月，何时可掇？

忧从中来，不可断绝。

越陌度阡，枉用相存。

契阔谈讌，心念旧恩。

月明星稀，乌鹊南飞。

绕树三匝，何枝可依？

山不厌高，海不厌深。

周公吐哺，天下归心。 
*** 归园田居（其一）（陶渊明）
少无适俗韵，性本爱丘山。

误落尘网中，一去三十年。

羁鸟恋旧林，池鱼思故渊。

开荒南野际，守拙归园田。

方宅十余亩，草屋八九间。

榆柳荫后檐，桃李罗堂前。

暧暧远人村，依依墟里烟。

狗吠深巷中，鸡鸣桑树颠。

户庭无尘杂，虚室有余闲。

久在樊笼里，复得返自然。
*** 梦游天姥吟留别（李白）
海客谈瀛洲，烟涛微茫信难求；
越人语天姥，云霞明灭或可睹。
天姥连天向天横，势拔五岳掩赤城。
天台四万八千丈，对此欲倒东南倾。

我欲因之梦吴越，一夜飞度镜湖月。
湖月照我影，送我至剡溪。
谢公宿处今尚在，渌水荡漾清猿啼。
脚著谢公屐，身登青云梯。
半壁见海日，空中闻天鸡。
千岩万转路不定，迷花倚石忽已暝。
熊咆龙吟殷岩泉，栗深林兮惊层巅。
云青青兮欲雨，水澹澹兮生烟。
列缺霹雳，丘峦崩摧。
洞天石扉，訇然中开。
青冥浩荡不见底，日月照耀金银台。
霓为衣兮风为马，云之君兮纷纷而来下。
虎鼓瑟兮鸾回车，仙之人兮列如麻。
忽魂悸以魄动，恍惊起而长嗟。
惟觉时之枕席，失向来之烟霞。

世间行乐亦如此，古来万事东流水。
别君去兮何时还？且放白鹿青崖间，须行即骑访名山。
安能摧眉折腰事权贵，使我不得开心颜？
*** 登高（杜甫）
风急天高猿啸哀，渚清沙白鸟飞回。

无边落木萧萧下，不尽长江滚滚来。

万里悲秋常作客，百年多病独登台。

艰难苦恨繁霜鬓，潦倒新停浊酒杯
*** 琵琶行（并序）（白居易）
浔阳江头夜送客，枫叶荻花秋瑟瑟。

主人下马客在船，举酒欲饮无管弦。

醉不成欢惨将别，别时茫茫江浸月。

忽闻水上琵琶声，主人忘归客不发。

寻声暗问弹者谁，琵琶声停欲语迟。

移船相近邀相见，添酒回灯重开宴。

千呼万唤始出来，犹抱琵琶半遮面。

转轴拨弦三两声，未成曲调先有情。

弦弦掩抑声声思，似诉平生不得志。

低眉信手续续弹，说尽心中无限事。

轻拢慢捻抹复挑，初为霓裳后六幺。

大弦嘈嘈如急雨，小弦切切如私语。

嘈嘈切切错杂弹，大珠小珠落玉盘。

间关莺语花底滑，幽咽泉流水下滩。

水泉冷涩弦凝绝，凝绝不通声渐歇。

别有幽愁暗恨生，此时无声胜有声。

银瓶乍破水浆迸，铁骑突出刀枪鸣。

曲终收拨当心画，四弦一声如裂帛。

东船西舫悄无言，唯见江心秋月白。

沉吟放拨插弦中，整顿衣裳起敛容。

自言本是京城女，家在虾蟆陵下住。

十三学得琵琶成，名属教坊第一部。

曲罢常教善才服，妆成每被秋娘妒。

五陵年少争缠头，一曲红绡不知数。

钿头银篦击节碎，血色罗裙翻酒污。

今年欢笑复明年，秋月春风等闲度。

弟走从军阿姨死，暮去朝来颜色故。

门前冷落车马稀，老大嫁作商人妇。

商人重利轻别离，前月浮梁买茶去。

去来江口守空船，绕舱明月江水寒。

夜深忽梦少年事，梦啼妆泪红阑干。

我闻琵琶已叹息，又闻此语重唧唧。

同是天涯沦落人，相逢何必曾相识。

我从去年辞帝京，谪居卧病浔阳城。

浔阳地僻无音乐，终岁不闻丝竹声。

住近湓江地低湿，黄芦苦竹绕宅生。

其间旦暮闻何物，杜鹃啼血猿哀鸣。

春江花朝秋月夜，往往取酒还独倾。

岂无山歌与村笛，呕哑嘲哳难为听。

今夜闻君琵琶语，如听仙乐耳暂明。

莫辞更坐弹一曲，为君翻作琵琶行。

感我此言良久立，却坐促弦弦转急。

凄凄不似向前声，满座重闻皆掩泣。

座中泣下谁最多，江州司马青衫湿。
*** 念奴娇·赤壁怀古（苏轼）
大江东去，浪淘尽，千古风流人物。
故垒西边，人道是，三国周郎赤壁。
乱石穿空，惊涛拍岸，卷起千堆雪。
江山如画，一时多少豪杰。

遥想公瑾当年，小乔初嫁了，雄姿英发。
羽扇纶巾，谈笑间，樯橹灰飞烟灭。
故国神游，多情应笑我，早生华发。
人生如梦，一尊还酹江月。
*** 永遇乐·京口北固亭怀古（辛弃疾）
千古江山，英雄无觅，孙仲谋处。舞榭歌台，风流总被，雨打风吹去。斜阳草树，寻常巷陌，人道寄奴曾住。想当年，金戈铁马，气吞万里如虎。

元嘉草草，封狼居胥，赢得仓皇北顾。四十三年，望中犹记，烽火扬州路。可堪回首，佛狸祠下，一片神鸦社鼓。凭谁问：廉颇老矣，尚能饭否？ 
*** 声声慢·寻寻觅觅（李清照）
寻寻觅觅，冷冷清清，凄凄惨惨戚戚。乍暖还寒时候，最难将息。三杯两盏淡酒，怎敌他、晚来风急！雁过也，正伤心，却是旧时相识。

满地黄花堆积，憔悴损，如今有谁堪摘？守着窗儿，独自怎生得黑？梧桐更兼细雨，到黄昏、点点滴滴。这次第，怎一个愁字了得！ 
*** 劝学
君子曰：学不可以已。

青，取之于蓝，而青于蓝；冰，水为之，而寒于水。木直中绳，𫐓以为轮，其曲中规。虽有槁暴，不复挺者，𫐓使之然也。故木受绳则直，金就砺则利，君子博学而日参省乎己，则知明而行无过矣。

吾尝终日而思矣，不如须臾之所学也；吾尝跂而望矣，不如登高之博见也。登高而招，臂非加长也，而见者远；顺风而呼，声非加疾也，而闻者彰。假舆马者，非利足也，而致千里；假舟楫者，非能水也，而绝江河。君子生非异也，善假于物也。

积土成山，风雨兴焉；积水成渊，蛟龙生焉；积善成德，而神明自得，圣心备焉。故不积跬步，无以至千里；不积小流，无以成江海。骐骥一跃，不能十步；驽马十驾，功在不舍。锲而舍之，朽木不折；锲而不舍，金石可镂。蚓无爪牙之利，筋骨之强，上食埃土，下饮黄泉，用心一也。蟹六跪而二螯，非蛇鳝之穴无可寄托者，用心躁也。
*** 师说
古之学者必有师。师者，所以传道受业解惑也。人非生而知之者，孰能无惑？惑而不从师，其为惑也，终不解矣。生乎吾前，其闻道也固先乎吾，吾从而师之；生乎吾后，其闻道也亦先乎吾，吾从而师之。吾师道也，夫庸知其年之先后生于吾乎？是故无贵无贱，无长无少，道之所存，师之所存也。

嗟（jiē）乎！师道之不传也久矣！欲人之无惑也难矣！古之圣人，其出人也远矣，犹且从师而问焉；今之众人，其下圣人也亦远矣，而耻学于师。是故圣益圣，愚益愚。圣人之所以为圣，愚人之所以为愚，其皆出于此乎！爱其子，择师而教之；于其身也，则耻师焉，惑矣。彼童子之师，授之书而习其句读（dòu）者，非吾所谓传其道解其惑者也。句读之不知，惑之不解，或师焉，或不（fǒu）焉，小学而大遗，吾未见其明也。巫医乐师百工之人，不耻相师。士大夫之族，曰师曰弟子云者，则群聚而笑之。问之，则曰：“彼与彼年相若也，道相似也。位卑则足羞，官盛则近谀。”呜呼！师道之不复，可知矣。巫医乐师百工之人，君子不齿，今其智乃反不能及，其可怪也欤！

圣人无常师。孔子师郯子（tán）、苌弘、师襄、老聃（dān）。郯子之徒，其贤不及孔子。孔子曰：三人行，则必有我师。是故弟子不必不如师，师不必贤于弟子，闻道有先后，术业有专攻，如是而已。

李氏子蟠，年十七，好古文，六艺经传皆通习之，不拘于时，学于余。余嘉其能行古道，作《师说》以贻之。 
*** 赤壁赋（苏轼）
壬戌之秋，七月既望，苏子与客泛舟游于赤壁之下。清风徐来，水波不兴。举酒属客，诵明月之诗，歌窈窕之章。少焉，月出于东山之上，徘徊于斗牛之间。白露横江，水光接天。纵一苇之所如，凌万顷之茫然。浩浩乎如冯虚御风，而不知其所止；飘飘乎如遗世独立，羽化而登仙。

于是饮酒乐甚，扣舷而歌之。歌曰：“桂棹兮兰桨，击空明兮溯流光。渺渺兮予怀，望美人兮天一方。”客有吹洞箫者，倚歌而和之。其声呜呜然，如怨如慕，如泣如诉；余音袅袅，不绝如缕。舞幽壑之潜蛟，泣孤舟之嫠妇。

苏子愀然，正襟危坐而问客曰：“何为其然也？”客曰：“‘月明星稀，乌鹊南飞’，此非曹孟德之诗乎？西望夏口，东望武昌，山川相缪，郁乎苍苍，此非孟德之困于周郎者乎？方其破荆州，下江陵，顺流而东也，舳舻千里，旌旗蔽空，酾酒临江，横槊赋诗，固一世之雄也，而今安在哉？况吾与子渔樵于江渚之上，侣鱼虾而友麋鹿，驾一叶之扁舟，举匏樽以相属。寄蜉蝣于天地，渺沧海之一粟。哀吾生之须臾，羡长江之无穷。挟飞仙以遨游，抱明月而长终。知不可乎骤得，托遗响于悲风。”

苏子曰：“客亦知夫水与月乎？逝者如斯，而未尝往也；盈虚者如彼，而卒莫消长也。盖将自其变者而观之，则天地曾不能以一瞬；自其不变者而观之，则物与我皆无尽也，而又何羡乎！且夫天地之间，物各有主，苟非吾之所有，虽一毫而莫取。惟江上之清风，与山间之明月，耳得之而为声，目遇之而成色，取之无禁，用之不竭。是造物者之无尽藏也，而吾与子之所共适。”

客喜而笑，洗盏更酌。肴核既尽，杯盘狼籍。相与枕藉乎舟中，不知东方之既白。
*** 登泰山记
泰山之阳，汶水西流；其阴，济水东流。阳谷皆入汶，阴谷皆入济。当其南北分者，古长城也。最高日观峰，在长城南十五里。

余以乾隆三十九年十二月，自京师乘风雪，历齐河、长清，穿泰山西北谷，越长城之限，至于泰安。是月丁未，与知府朱孝纯子颍由南麓登。四十五里，道皆砌石为磴，其级七千有余。泰山正南面有三谷。中谷绕泰安城下，郦道元所谓环水也。余始循以入，道少半，越中岭，复循西谷，遂至其巅。古时登山，循东谷入，道有天门。东谷者，古谓之天门溪水，余所不至也。今所经中岭及山巅，崖限当道者，世皆谓之天门云。道中迷雾冰滑，磴几不可登。及既上，苍山负雪，明烛天南。望晚日照城郭，汶水、徂徕如画，而半山居雾若带然。

戊申晦，五鼓，与子颍坐日观亭，待日出。大风扬积雪击面。亭东自足下皆云漫。稍见云中白若樗蒱数十立者，山也。极天云一线异色，须臾成五采。日上，正赤如丹，下有红光动摇承之。或曰，此东海也。回视日观以西峰，或得日或否，绛皓驳色，而皆若偻。

亭西有岱祠，又有碧霞元君祠。皇帝行宫在碧霞元君祠东。是日观道中石刻，自唐显庆以来，其远古刻尽漫失。僻不当道者，皆不及往。

山多石，少土。石苍黑色，多平方，少圜。少杂树，多松，生石罅，皆平顶。冰雪，无瀑水，无鸟兽音迹。至日观数里内无树，而雪与人膝齐。

桐城姚鼐记。
*** 静女
静女其姝，俟我于城隅。爱而不见，搔首踟蹰。
静女其娈，贻我彤管。彤管有炜，说怿女美。
自牧归荑，洵美且异。匪女之为美，美人之贻。 
*** 涉江采芙蓉
涉江采芙蓉，兰泽多芳草。

采之欲遗谁？所思在远道。

还顾望旧乡，长路漫浩浩。

同心而离居，忧伤以终老。
*** 虞美人（李煜）
春花秋月何时了，往事知多少。小楼昨夜又东风，故国不堪回首月明中。

雕栏玉砌应犹在，只是朱颜改。问君能有几多愁，恰是一江春水向东流。
*** 鹊桥仙·纤云弄巧
纤云弄巧，飞星传恨，银汉迢迢暗度。金风玉露一相逢，便胜却人间无数。

柔情似水，佳期如梦，忍顾鹊桥归路。两情若是久长时，又岂在朝朝暮暮。 
** 必修下
# 懒得搞那么多了，看着课文后面要求背的或者印象中比较重要的才塞进来吧。
*** 子路、曾皙、冉有、公西华侍坐
子路、曾皙、冉有、公西华侍坐。

子曰：“以吾一日长乎尔，毋吾以也。居则曰：‘不吾知也！’如或知尔，则何以哉？”

子路率尔而对曰：“千乘之国，摄乎大国之间，加之以师旅，因之以饥馑；由也为之，比及三年，可使有勇，且知方也。”

夫子哂之。

“求！尔何如？”

对曰：“方六七十，如五六十，求也为之，比及三年，可使足民。如其礼乐，以俟君子。”

“赤！尔何如？”

对曰：“非曰能之，愿学焉。宗庙之事，如会同，端章甫，愿为小相焉。”

“点！尔何如？”

鼓瑟希，铿尔，舍瑟而作，对曰：“异乎三子者之撰。”

子曰：“何伤乎？亦各言其志也。”

曰：“莫春者，春服既成，冠者五六人，童子六七人，浴乎沂，风乎舞雩，咏而归。”

夫子喟然叹曰：“吾与点也！”

三子者出，曾皙后。曾皙曰：“夫三子者之言何如？”

子曰：“亦各言其志也已矣。”

曰：“夫子何哂由也？”

曰：“为国以礼，其言不让，是故哂之。”

“唯求则非邦也与？”

“安见方六七十如五六十而非邦也者？”

“唯赤则非邦也与？”

“宗庙会同，非诸侯而何？赤也为之小，孰能为之大？”
*** 鸿门宴（司马迁《史记》）（非必背）
沛公军霸上，未得与项羽相见。沛公左司马曹无伤，使人言于项羽曰：“沛公欲王关中，使子婴为相，珍宝尽有之。”项羽大怒曰：“旦日飨士卒，为击破沛公军！”当是时，项羽兵四十万，在新丰鸿门；沛公兵十万，在霸上。范增说项羽曰：“沛公居山东时，贪于财货，好美姬。今入关，财物无所取，妇女无所幸，此其志不在小。吾令人望其气，皆为龙虎，成五采，此天子气也。急击勿失！”

楚左尹项伯者，项羽季父也，素善留侯张良。张良是时从沛公，项伯乃夜驰之沛公军，私见张良，具告以事，欲呼张良与俱去，曰：“毋从俱死也。”张良曰：“臣为韩王送沛公，沛公今事有急，亡去不义，不可不语。”良乃入，具告沛公。沛公大惊，曰：“为之奈何？”张良曰：“谁为大王为此计者？”曰：“鲰生说我曰：‘距关，毋内诸侯，秦地可尽王也。’故听之。”良曰：“料大王士卒足以当项王乎？”沛公默然，曰：“固不如也。且为之奈何？”张良曰：“请往谓项伯，言沛公不敢背项王也。”沛公曰：“君安与项伯有故？”张良曰：“秦时与臣游，项伯杀人，臣活之。今事有急，故幸来告良。”沛公曰：“孰与君少长？”良曰：“长于臣。”沛公曰：“君为我呼入，吾得兄事之。”张良出，要项伯。项伯即入见沛公。沛公奉卮酒为寿，约为婚姻，曰：“吾入关，秋毫不敢有所近，籍吏民，封府库，而待将军。所以遣将守关者，备他盗之出入与非常也。日夜望将军至，岂敢反乎！愿伯具言臣之不敢倍德也。”项伯许诺，谓沛公曰：“旦日不可不蚤自来谢项王。”沛公曰：“诺。”于是项伯复夜去，至军中，具以沛公言报项王，因言曰：“沛公不先破关中，公岂敢入乎？今人有大功而击之，不义也。不如因善遇之。”项王许诺。

沛公旦日从百余骑来见项王，至鸿门，谢曰：“臣与将军戮力而攻秦，将军战河北，臣战河南，然不自意能先入关破秦，得复见将军于此。今者有小人之言，令将军与臣有郤。”项王曰：“此沛公左司马曹无伤言之。不然，籍何以至此？”项王即日因留沛公与饮。项王、项伯东向坐，亚父南向坐，——亚父者，范增也；沛公北向坐；张良西向侍。范增数目项王，举所佩玉玦以示之者三，项王默然不应。范增起，出，召项庄，谓曰：“君王为人不忍。若入前为寿，寿毕，请以剑舞，因击沛公于坐，杀之。不者，若属皆且为所虏。”庄则入为寿。寿毕，曰：“君王与沛公饮，军中无以为乐，请以剑舞。”项王曰：“诺。”项庄拔剑起舞，项伯亦拔剑起舞，常以身翼蔽沛公，庄不得击。

于是张良至军门见樊哙。樊哙曰：“今日之事何如？”良曰：“甚急！今者项庄拔剑舞，其意常在沛公也。”哙曰：“此迫矣！臣请入，与之同命。”哙即带剑拥盾入军门。交戟之卫士欲止不内，樊哙侧其盾以撞，卫士仆地，哙遂入，披帷西向立，瞋目视项王，头发上指，目眦尽裂。项王按剑而跽曰：“客何为者？”张良曰：“沛公之参乘樊哙者也。”项王曰：“壮士！赐之卮酒。”则与斗卮酒。哙拜谢，起，立而饮之。项王曰：“赐之彘肩。”则与一生彘肩。樊哙覆其盾于地，加彘肩上，拔剑切而啖之。项王曰：“壮士！能复饮乎？”樊哙曰：“臣死且不避，卮酒安足辞！夫秦王有虎狼之心，杀人如不能举，刑人如恐不胜，天下皆叛之。怀王与诸将约曰：‘先破秦入咸阳者王之。’今沛公先破秦入咸阳，毫毛不敢有所近，封闭宫室，还军霸上，以待大王来。故遣将守关者，备他盗出入与非常也。劳苦而功高如此，未有封侯之赏，而听细说，欲诛有功之人，此亡秦之续耳。窃为大王不取也！”项王未有以应，曰：“坐。”樊哙从良坐。坐须臾，沛公起如厕，因招樊哙出。

沛公已出，项王使都尉陈平召沛公。沛公曰：“今者出，未辞也，为之奈何？”樊哙曰：“大行不顾细谨，大礼不辞小让。如今人方为刀俎，我为鱼肉，何辞为？”于是遂去。乃令张良留谢。良问曰：“大王来何操？”曰：“我持白璧一双，欲献项王，玉斗一双，欲与亚父。会其怒，不敢献。公为我献之。”张良曰：“谨诺。”当是时，项王军在鸿门下，沛公军在霸上，相去四十里。沛公则置车骑，脱身独骑，与樊哙、夏侯婴、靳强、纪信等四人持剑盾步走，从郦山下，道芷阳间行。沛公谓张良曰：“从此道至吾军，不过二十里耳。度我至军中，公乃入。”

沛公已去，间至军中。张良入谢，曰：“沛公不胜桮杓，不能辞。谨使臣良奉白璧一双，再拜献大王足下，玉斗一双，再拜奉大将军足下。”项王曰：“沛公安在？”良曰：“闻大王有意督过之，脱身独去，已至军矣。”项王则受璧，置之坐上。亚父受玉斗，置之地，拔剑撞而破之，曰：“唉！竖子不足与谋。夺项王天下者必沛公也。吾属今为之虏矣！”

沛公至军，立诛杀曹无伤。
*** 谏太宗十思疏（魏征）
臣闻求木之长者，必固其根本；欲流之远者，必浚其泉源；思国之安者，必积其德义。源不深而望流之远，根不固而求木之长，德不厚而思国之理，臣虽下愚，知其不可，而况于明哲乎！人君当神器之重，居域中之大，将崇极天之峻，永保无疆之休。不念居安思危，戒奢以俭，德不处其厚，情不胜其欲，斯亦伐根以求木茂，塞源而欲流长者也。

凡百元首，承天景命，莫不殷忧而道著，功成而德衰。有善始者实繁，能克终者盖寡。岂取之易而守之难乎？昔取之而有余，今守之而不足，何也？夫在殷忧，必竭诚以待下；既得志，则纵情以傲物。竭诚则胡越为一体，傲物则骨肉为行路。虽董之以严刑，振之以威怒，终苟免而不怀仁，貌恭而不心服。怨不在大，可畏惟人；载舟覆舟，所宜深慎；奔车朽索，其可忽乎！

君人者，诚能见可欲则思知足以自戒，将有作则思知止以安人，念高危则思谦冲而自牧，惧满溢则思江海下百川，乐盘游则思三驱以为度，忧懈怠则思慎始而敬终，虑壅蔽则思虚心以纳下，想谗邪则思正身以黜恶，恩所加则思无因喜以谬赏，罚所及则思无因怒而滥刑。总此十思，弘兹九德，简能而任之，择善而从之，则智者尽其谋，勇者竭其力，仁者播其惠，信者效其忠。文武争驰，在君无事，可以尽豫游之乐，可以养松乔之寿，鸣琴垂拱，不言而化。何必劳神苦思，代下司职，役聪明之耳目，亏无为之大道哉！
*** 阿房宫赋（必背）
六王毕，四海一，蜀山兀，阿房出。覆压三百余里，隔离天日。骊（lí）山北构而西折，直走咸阳。二川溶 溶，流入宫墙。五步一楼，十步一阁；廊腰缦回，檐牙高啄；各抱地势，钩心斗角。盘盘焉，囷囷（qūn）焉，蜂房水涡，矗（chù）不知其（广东版教材为“乎”）几千万落。长桥卧波，未云何龙？复道行空，不霁（jì）何虹？高低冥迷，不知西东（也做“东西”）。歌台暖响，春光融融；舞殿冷袖，风雨凄凄。一日之内，一宫之间，而气候不齐。

妃嫔(pín)媵（yìng）嫱(qiáng)，王子皇孙，辞楼下殿，辇（niǎn）来于秦，朝歌夜弦（xián），为秦宫人。明星荧(yíng)荧(yíng)，开妆镜也；绿云扰扰，梳晓鬟（huán）也；渭流涨腻，弃脂水也；烟斜雾横，焚椒兰也。雷霆乍惊，宫车过也；辘（lù）辘（lù）远听，杳（yǎo）不知其所之也。一肌一容，尽态极妍，缦立远视，而望幸焉。有不见者，三十六年。燕、赵之收藏，韩、魏之经营，齐、楚之精英，几世几年，摽（piāo)掠其人，倚叠如山。一旦不能有，输来其间。鼎铛（chēng）玉石，金块珠砾，弃掷逦（lǐ）迤（yǐ），秦人视之，亦不甚惜。

嗟乎！一人之心，千万人之心也。秦爱纷奢，人亦念其家。奈何取之尽锱（zī）铢（zhū），用之如泥沙？使负栋之柱，多于南亩之农夫；架梁之椽（chuán），多于机上之工女；钉头磷磷，多于在庾（yǔ）之粟(sù)粒；瓦缝参差（cēn cī ），多于周身之帛（bó）缕；直栏横槛（jiàn），多于九土之城郭；管弦呕（ōu）哑（yā），多于市人之言语。使天下之人，不敢言而敢怒。独夫之心，日益骄固。戍（shù）卒叫，函谷举，楚人一炬，可怜焦土！

呜呼，灭六国者六国也，非秦也。族秦者秦也，非天下也。嗟乎！使六国各爱其人，则足以拒秦；使秦复爱六国之人，则递三世可至万世而为君，谁得而族灭也？秦人不暇自哀，而后人哀之；后人哀之而不鉴之，亦使后人而复哀后人也。 
*** 六国论（苏洵）
六国破灭，非兵不利，战不善，弊在赂秦。赂秦而力亏，破灭之道也。或曰：六国互丧，率赂秦耶？曰：不赂者以赂者丧。盖失强援，不能独完。故曰：弊在赂秦也。

秦以攻取之外，小则获邑，大则得城。较秦之所得，与战胜而得者，其实百倍；诸侯之所亡，与战败而亡者，其实亦百倍。则秦之所大欲，诸侯之所大患，固不在战矣。思厥先祖父，暴霜露，斩荆棘，以有尺寸之地。子孙视之不甚惜，举以予人，如弃草芥。今日割五城，明日割十城，然后得一夕安寝。起视四境，而秦兵又至矣。然则诸侯之地有限，暴秦之欲无厌，奉之弥繁，侵之愈急。故不战而强弱胜负已判矣。至于颠覆，理固宜然。古人云：“以地事秦，犹抱薪救火，薪不尽，火不灭。”此言得之。

齐人未尝赂秦，终继五国迁灭，何哉？与嬴而不助五国也。五国既丧，齐亦不免矣。燕赵之君，始有远略，能守其土，义不赂秦。是故燕虽小国而后亡，斯用兵之效也。至丹以荆卿为计，始速祸焉。赵尝五战于秦，二败而三胜。后秦击赵者再，李牧连却之。洎牧以谗诛，邯郸为郡，惜其用武而不终也。且燕赵处秦革灭殆尽之际，可谓智力孤危，战败而亡，诚不得已。向使三国各爱其地，齐人勿附于秦，刺客不行，良将犹在，则胜负之数，存亡之理，当与秦相较，或未易量。

呜呼！以赂秦之地封天下之谋臣，以事秦之心礼天下之奇才，并力西向，则吾恐秦人食之不得下咽也。悲夫！有如此之势，而为秦人积威之所劫，日削月割，以趋于亡。为国者无使为积威之所劫哉！

夫六国与秦皆诸侯，其势弱于秦，而犹有可以不赂而胜之之势。苟以天下之大，下而从六国破亡之故事，是又在六国下矣。
*** 登岳阳楼（杜甫）
昔闻洞庭水，今上岳阳楼。

吴楚东南坼，乾坤日夜浮。

亲朋无一字，老病有孤舟。

戎马关山北，凭轩涕泗流。
*** 桂枝香·金陵怀古（王安石）
登临送目，正故国晚秋，天气初肃。千里澄江似练，翠峰如簇。归帆去棹残阳里，背西风，酒旗斜矗。彩舟云淡，星河鹭起，画图难足。

念往昔，繁华竞逐。叹门外楼头，悲恨相续。千古凭高对此，谩嗟荣辱。六朝旧事随流水，但寒烟衰草凝绿。至今商女，时时犹唱，后庭遗曲。
*** 念奴娇·过洞庭
洞庭青草，近中秋，更无一点风色。玉鉴琼田三万顷，着我扁舟一叶。素月分辉，明河共影，表里俱澄澈。悠然心会，妙处难与君说。

应念岭海经年，孤光自照，肝肺皆冰雪。短发萧骚襟袖冷，稳泛沧浪空阔。尽挹西江，细斟北斗，万象为宾客。扣舷独啸，不知今夕何夕！ 
*** 游园（汤显祖）
原来姹紫嫣红开遍，似这般都付与断井颓垣。良辰美景奈何天，赏心乐事谁家院！朝飞暮卷，云霞翠轩；雨丝风片，烟波画船——锦屏人忒看的这韶光贱！
** 选必上
*** 论语十二章
子曰：“君子食无求饱，居无求安，敏于事而慎于言，就有道而正焉，可谓好学也已。”(《学而》)

子曰：“人而不仁，如礼何？ 人而不仁，如乐何？”(《八佾》)

子曰：“朝闻道，夕死可矣。”(《里仁》)

子曰：“君子喻于义，小人喻于利。”(《里仁》)

子曰：“见贤思齐焉，见不贤而内自省也。”(《里仁》)

子曰：“质胜文则野，文胜质则史。文质彬彬，然后君子。”(《雍也》)

曾子曰：“士不可以不弘毅，任重而道远。仁以为己任，不亦重乎？死而后已，不亦远乎？”(《泰伯》)

子曰：“譬如为山，未成一篑，止，吾止也。譬如平地，虽覆一篑，进，吾往也。”(《子罕》)

子曰：“知者不惑，仁者不忧，勇者不惧。”(《子罕》)

颜渊问仁。子曰：“克己复礼为仁。一日克己复礼，天下归仁焉。为仁由己，而由人乎哉？”颜渊曰：“请问其目。”子曰：“非礼勿视，非礼勿听，非礼勿言，非礼勿动。”颜渊曰：“回虽不敏，请事斯语矣。”(《颜渊》)

子贡问曰：“有一言而可以终身行之者乎？”子曰：“其‘恕’乎！己所不欲，勿施于人。”(《卫灵公》)

子曰：“小子何莫学夫《诗》？《诗》可以兴，可以观，可以群，可以怨。迩之事父，远之事君。多识于鸟兽草木之名。”(《阳货》)
*** 大学之道
大学之道，在明明德，在亲民，在止于至善。知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。 物有本末，事有终始。知所先后，则近道矣。

古之欲明明德于天下者，先治其国。欲治其国者，先齐其家。欲齐其家者，先修其身。欲修其身者，先正其心。欲正其心者，先诚其意。欲诚其意者，先致其知。致知在格物。物格而后知至，知至而后意诚，意诚而后心正，心正而后身修，身修而后家齐，家齐而后国治，国治而后天下平。自天子以至于庶人，壹是皆以修身为本。
*** 《老子》四章
三十辐共一毂(gǔ)，当其无，有车之用。埏埴(shān zhí)以为器，当其无，有器之用。凿户牖(yǒu)以为室，当其无，有室之用。故有之以为利，无之以为用。(第十一章)

企者不立，跨者不行(xíng)，自见(xiàn)者不明，自是者不彰，自伐者无功，自矜者不长(cháng)。其在道也，曰余食赘(zhuì)行，物或恶之。故有道者不处(chù)。(第二十四章)

知人者智，自知者明。胜人者有力，自胜者强。知足者富，强(qiǎng)行者有志。不失其所者久，死而不亡者寿。(第三十三章)

其安易持，其未兆易谋，其脆易泮(pàn)，其微易散。为之于未有，治之于未乱。合抱之木，生于毫末；九层之台，起于累(léi)土；千里之行，始于足下。为者败之，执者失之。是以圣人无为，故无败；无执，故无失。民之从事，常于几(jī)成而败之。慎终如始，则无败事。是以圣人欲不欲，不贵难得之货，学不学，复众人之所过。以辅万物之自然而不敢为。(第六十四章)
*** 无衣
岂曰无衣？与子同袍。王于兴师，修我戈矛，与子同仇！

岂曰无衣？与子同泽。王于兴师，修我矛戟，与子偕作！

岂曰无衣？与子同裳。王于兴师，修我甲兵，与子偕行！ 
*** 春江花月夜
春江潮水连海平，海上明月共潮生。

滟滟随波千万里，何处春江无月明。

江流宛转绕芳甸，月照花林皆似霰。

空里流霜不觉飞，汀上白沙看不见。

江天一色无纤尘，皎皎空中孤月轮。

江畔何人初见月？江月何年初照人？

人生代代无穷已，江月年年望相似。

不知江月待何人，但见长江送流水。

白云一片去悠悠，青枫浦上不胜愁。

谁家今夜扁舟子？何处相思明月楼？

可怜楼上月裴回，应照离人妆镜台。

玉户帘中卷不去，捣衣砧上拂还来。

此时相望不相闻，愿逐月华流照君。

鸿雁长飞光不度，鱼龙潜跃水成文。

昨夜闲潭梦落花，可怜春半不还家。

江水流春去欲尽，江潭落月复西斜。

斜月沉沉藏海雾，碣石潇湘无限路。

不知乘月几人归，落月摇情满江树。

(注:斜(xiá))
*** 将进酒（李白）
君不见黄河之水天上来，奔流到海不复回。
君不见高堂明镜悲白发，朝如青丝暮成雪。
人生得意须尽欢，莫使金樽空对月。
天生我材必有用，千金散尽还复来。
烹羊宰牛且为乐，会须一饮三百杯。

岑夫子，丹丘生，将进酒，杯莫停。
与君歌一曲，请君为我倾耳听。
钟鼓馔玉不足贵，但愿长醉不愿醒。
古来圣贤皆寂寞，惟有饮者留其名。
陈王昔时宴平乐，斗酒十千恣欢谑。
主人何为言少钱，径须沽取对君酌。
五花马、千金裘，呼儿将出换美酒，与尔同销万古愁。
*** 江城子·乙卯正月二十日夜记梦（苏轼）
十年生死两茫茫。不思量，自难忘。千里孤坟，无处话凄凉。纵使相逢应不识，尘满面，鬓如霜。

夜来幽梦忽还乡，小轩窗，正梳妆。相顾无言，惟有泪千行。料得年年肠断处，明月夜，短松冈。
** 选必中
*** 屈原列传（第三段）
屈平疾王听之不聪也，谗谄之蔽明也，邪曲之害公也，方正之不容也，故忧愁幽思而作《离骚》。
“离骚”者，犹离忧也。夫天者，人之始也；父母者，人之本也。
人穷则反本，故劳苦倦极，未尝不呼天也；疾痛惨怛，未尝不呼父母也。
屈平正道直行，竭忠尽智以事其君，谗人间之，可谓穷矣。
信而见疑，忠而被谤，能无怨乎？屈平之作《离骚》，盖自怨生也。
《国风》好色而不淫，《小雅》怨诽而不乱。
若《离骚》者，可谓兼之矣。
上称帝喾(kù)，下道齐桓(huán)，中述汤、武，以刺世事。
明道德之广崇，治乱之条贯，靡不毕见。
其文约，其辞微，其志洁，其行廉。
其称文小而其指极大，举类迩而见义远。
其志洁，故其称物芳；其行廉，故死而不容。
自疏濯淖(zhào nào)污泥之中，蝉蜕于浊秽，以浮游尘埃之外，
不获世之滋垢，皭(jiào)然泥(niè)而不滓(zǐ)者也。
推此志也，虽与日月争光可也。
*** 过秦论（贾谊）
秦孝公据崤(xiáo)函之固，拥雍州之地，君臣固守以窥周室，有席卷天下，包举宇内，囊括四海之意，并吞八荒之心。当是时也，商君佐之，内立法度，务耕织，修守战之具，外连衡而斗诸侯。于是秦人拱手而取西河之外。

孝公既没，惠文、武、昭襄蒙故业，因遗策，南取汉中，西举巴、蜀，东割膏腴之地，北收要害之郡。诸侯恐惧，会盟而谋弱秦，不爱珍器重宝肥饶之地，以致天下之士，合从(zòng)缔交，相与为一。当此之时，齐有孟尝，赵有平原，楚有春申，魏有信陵。此四君者，皆明智而忠信，宽厚而爱人，尊贤而重士，约从离衡，兼韩、魏、燕、楚、齐、赵、宋、卫、中山之众。于是六国之士，有甯(nìng)越、徐尚、苏秦、杜赫之属为之谋，齐明、周最、陈轸、召(zhào)滑、楼缓、翟(zhái)景、苏厉、乐(yuè)毅之徒通其意，吴起、孙膑、带佗、倪(ní)良、王廖、田忌、廉颇、赵奢之伦制其兵。尝以十倍之地，百万之众，叩关而攻秦。秦人开关延敌，九国之师，逡(qūn)巡而不敢进。秦无亡矢遗镞(zú)之费，而天下诸侯已困矣。于是从散约败，争割地而赂秦。秦有余力而制其弊，追亡逐北，伏尸百万，流血漂橹；因利乘便，宰割天下，分裂山河。强国请服，弱国入朝。延及孝文王、庄襄王，享国之日浅，国家无事。

及至始皇，奋六世之余烈，振长策而御宇内，吞二周而亡诸侯，履至尊而制六合，执敲扑而鞭笞天下，威振四海。南取百越之地，以为桂林、象郡；百越之君，俯首系颈，委命下吏。乃使蒙恬北筑长城而守藩篱，却匈奴七百余里；胡人不敢南下而牧马，士不敢弯弓而报怨。于是废先王之道，焚百家之言，以愚黔首；隳(huī)名城，杀豪杰；收天下之兵，聚之咸阳，销锋镝，铸以为金人十二，以弱天下之民。然后践华为城，因河为池，据亿丈之城，临不测之渊，以为固。良将劲弩守要害之处，信臣精卒陈利兵而谁何。天下已定，始皇之心，自以为关中之固，金城千里，子孙帝王万世之业也。

始皇既没，余威震于殊俗。然陈涉瓮牖绳枢(wèng yǒu shéng shū)之子，氓(méng)隶之人，而迁徙之徒也；才能不及中人，非有仲尼、墨翟之贤，陶朱、猗(yī)顿之富；蹑足行伍之间，而倔起阡陌之中，率疲弊之卒，将数百之众，转而攻秦；斩木为兵，揭竿为旗，天下云集响应，赢粮而景(yǐng)从。山东豪俊遂并起而亡秦族矣。

且夫(fú)天下非小弱也，雍州之地，崤函之固，自若也。陈涉之位，非尊于齐、楚、燕、赵、韩、魏、宋、卫、中山之君也；锄櫌棘矜(chú yōu jí jīn)，非铦(xiān)于钩戟长铩(shā)也；谪戍之众，非抗于九国之师也；深谋远虑，行军用兵之道，非及乡时之士也。然而成败异变，功业相反，何也？试使山东之国与陈涉度(duó)长絜(xié)大，比权量力，则不可同年而语矣。然秦以区区之地，致万乘之势，序八州而朝同列，百有余年矣；然后以六合为家，崤函为宫；一夫作难(nàn)而七庙隳(huī)，身死人手，为天下笑者，何也？仁义不施而攻守之势异也。
*** 报任安书（节选）
#+begin_quote
虽被删除但仍要考(似乎)
#+end_quote
古者富贵而名摩灭，不可胜记，唯倜傥非常之人称焉。盖文王拘而演《周易》；仲尼厄而作《春秋》；屈原放逐，乃赋《离骚》；左丘失明，厥有《国语》；孙子膑脚，《兵法》修列；不韦迁蜀，世传《吕览》；韩非囚秦，《说难》《孤愤》；《诗》三百篇，大底圣贤发愤之所为作也。此人皆意有所郁结，不得通其道，故述往事、思来者。乃如左丘无目，孙子断足，终不可用，退而论书策，以舒其愤，思垂空文以自见。仆窃不逊，近自托于无能之辞，网罗天下放失旧闻，略考其行事，综其终始，稽其成败兴坏之纪，上计轩辕，下至于兹，为十表，本纪十二，书八章，世家三十，列传七十，凡百三十篇。亦欲以究天人之际，通古今之变，成一家之言。草创未就，会遭此祸，惜其不成，是以就极刑而无愠色。仆诚以著此书，藏之名山，传之其人，通邑大都，则仆偿前辱之责，虽万被戮，岂有悔哉！然此可为智者道，难为俗人言也！
*** 五代史伶官传序（非必背）
呜呼！盛衰之理，虽曰天命，岂非人事哉！原庄宗之所以得天下，与其所以失之者，可以知之矣。

世言晋王之将终也，以三矢赐庄宗而告之曰：“梁，吾仇也；燕王吾所立；契丹与吾约为兄弟；而皆背晋以归梁。此三者，吾遗恨也。与尔三矢，尔其无忘乃父之志！”庄宗受而藏之于庙。其后用兵，则遣从事以一少牢告庙，请其矢，盛以锦囊，负而前驱，及凯旋而纳之。

方其系燕父子以组，函梁君臣之首，入于太庙，还矢先王，而告以成功，其意气之盛，可谓壮哉！及仇雠(chóu)已灭，天下已定，一夫夜呼，乱者四应，仓皇东出，未及见贼而士卒离散，君臣相顾，不知所归。至于誓天断发，泣下沾襟，何其衰也！岂得之难而失之易欤？抑本其成败之迹，而皆自于人欤？《书》曰：“满招损，谦得益。”忧劳可以兴国，逸豫可以亡身，自然之理也。

故方其盛也，举天下之豪杰，莫能与之争；及其衰也，数十伶人困之，而身死国灭，为天下笑。夫祸患常积于忽微，而智勇多困于所溺，岂独伶人也哉？
*** 燕歌行·并序
汉家烟尘在东北，汉将辞家破残贼。

男儿本自重横行，天子非常赐颜色。

摐金伐鼓下榆关，旌旆逶迤碣石间。

校尉羽书飞瀚海，单于猎火照狼山。

山川萧条极边土，胡骑凭陵杂风雨。

战士军前半死生，美人帐下犹歌舞。

大漠穷秋塞草腓，孤城落日斗兵稀。

身当恩遇常轻敌，力尽关山未解围。

铁衣远戍辛勤久，玉箸应啼别离后。

少妇城南欲断肠，征人蓟北空回首。

边庭飘飖那可度，绝域苍茫无所有。

杀气三时作阵云，寒声一夜传刁斗。

相看白刃血纷纷，死节从来岂顾勋！

君不见沙场征战苦，至今犹忆李将军。

(注: 摐(chuāng),旆(pèi),塞草腓(sài cǎo féi),箸(zhù),飖(yáo))
*** 李凭箜篌引
吴丝蜀桐张高秋，空山凝云颓不流。

江娥啼竹素女愁，李凭中国弹箜篌。

昆山玉碎凤凰叫，芙蓉泣露香兰笑。

十二门前融冷光，二十三丝动紫皇。

女娲炼石补天处，石破天惊逗秋雨。

梦入神山教神妪，老鱼跳波瘦蛟舞。

吴质不眠倚桂树，露脚斜飞湿寒兔。 
*** 锦瑟
锦瑟无端五十弦，一弦一柱思华年。

庄生晓梦迷蝴蝶，望帝春心托杜鹃。

沧海月明珠有泪，蓝田日暖玉生烟。

此情可待成追忆，只是当时已惘然。 
*** 书愤
早岁那知世事艰，中原北望气如山。

楼船夜雪瓜洲渡，铁马秋风大散关。

塞上长城空自许，镜中衰鬓已先斑。

出师一表真名世，千载谁堪伯仲间！
** 选必下
*** 离骚（课文第三段）
纷吾既有此内美兮，又重之以修能。

扈江离与辟芷兮，纫秋兰以为佩。

汩余若将不及兮，恐年岁之不吾与。

朝搴阰之木兰兮，夕揽洲之宿莽。

日月忽其不淹兮，春与秋其代序。

惟草木之零落兮，恐美人之迟暮。

不抚壮而弃秽兮，何不改此度？

乘骐骥以驰骋兮，来吾道夫先路！
*** 蜀道难 
噫吁嚱，危乎高哉！
蜀道之难，难于上青天！
蚕丛及鱼凫，开国何茫然！
尔来四万八千岁，不与秦塞通人烟。
西当太白有鸟道，可以横绝峨眉巅。
地崩山摧壮士死，然后天梯石栈相钩连。
上有六龙回日之高标，下有冲波逆折之回川。
黄鹤之飞尚不得过，猿猱欲度愁攀援。
青泥何盘盘，百步九折萦岩峦。
扪参历井仰胁息，以手抚膺坐长叹。

问君西游何时还？畏途巉岩不可攀。
但见悲鸟号古木，雄飞雌从绕林间。
又闻子规啼夜月，愁空山。
蜀道之难，难于上青天，使人听此凋朱颜！
连峰去天不盈尺，枯松倒挂倚绝壁。
飞湍瀑流争喧豗，砯崖转石万壑雷。
其险也如此，嗟尔远道之人胡为乎来哉！

剑阁峥嵘而崔嵬，一夫当关，万夫莫开。
所守或匪亲，化为狼与豺。
朝避猛虎，夕避长蛇，磨牙吮血，杀人如麻。
锦城虽云乐，不如早还家。
蜀道之难，难于上青天，侧身西望长咨嗟！
*** 蜀相 
丞相祠堂何处寻？锦官城外柏森森。

映阶碧草自春色，隔叶黄鹂空好音。

三顾频烦天下计，两朝开济老臣心。

出师未捷身先死，长使英雄泪满襟。
*** 陈情表 
臣密言：臣以险衅，夙遭闵凶。生孩六月，慈父见背；行年四岁，舅夺母志。祖母刘愍臣孤弱，躬亲抚养。臣少多疾病，九岁不行，零丁孤苦，至于成立。既无伯叔，终鲜兄弟，门衰祚薄，晚有儿息。外无期功强近之亲，内无应门五尺之僮，茕茕孑立，形影相吊。而刘夙婴疾病，常在床蓐，臣侍汤药，未曾废离。

逮奉圣朝，沐浴清化。前太守臣逵察臣孝廉；后刺史臣荣举臣秀才。臣以供养无主，辞不赴命。诏书特下，拜臣郎中，寻蒙国恩，除臣洗马。猥以微贱，当侍东宫，非臣陨首所能上报。臣具以表闻，辞不就职。诏书切峻，责臣逋慢；郡县逼迫，催臣上道；州司临门，急于星火。臣欲奉诏奔驰，则刘病日笃，欲苟顺私情，则告诉不许：臣之进退，实为狼狈。

伏惟圣朝以孝治天下，凡在故老，犹蒙矜育，况臣孤苦，特为尤甚。且臣少仕伪朝，历职郎署，本图宦达，不矜名节。今臣亡国贱俘，至微至陋，过蒙拔擢，宠命优渥，岂敢盘桓，有所希冀。但以刘日薄西山，气息奄奄，人命危浅，朝不虑夕。臣无祖母，无以至今日，祖母无臣，无以终余年。母、孙二人，更相为命，是以区区不能废远。

臣密今年四十有四，祖母今年九十有六，是臣尽节于陛下之日长，报养刘之日短也。乌鸟私情，愿乞终养。臣之辛苦，非独蜀之人士及二州牧伯所见明知，皇天后土实所共鉴。愿陛下矜愍愚诚，听臣微志，庶刘侥幸，保卒余年。臣生当陨首，死当结草。臣不胜犬马怖惧之情，谨拜表以闻。
*** 兰亭集序 
永和九年，岁在癸丑，暮春之初，会于会稽山阴之兰亭，修禊事也。群贤毕至，少长咸集。此地有崇山峻岭，茂林修竹；又有清流激湍，映带左右，引以为流觞曲水，列坐其次。虽无丝竹管弦之盛，一觞一咏，亦足以畅叙幽情。

是日也，天朗气清，惠风和畅。仰观宇宙之大，俯察品类之盛，所以游目骋怀，足以极视听之娱，信可乐也。

夫人之相与，俯仰一世，或取诸怀抱，悟言一室之内；或因寄所托，放浪形骸之外。虽趣舍万殊，静躁不同，当其欣于所遇，暂得于己，快然自足，不知老之将至。及其所之既倦，情随事迁，感慨系之矣。向之所欣，俯仰之间，已为陈迹，犹不能不以之兴怀。况修短随化，终期于尽。古人云：“死生亦大矣。”岂不痛哉！(悟 一作：晤；趣 一作：曲；快 一作：怏)

每览昔人兴感之由，若合一契，未尝不临文嗟悼，不能喻之于怀。固知一死生为虚诞，齐彭殇为妄作。后之视今，亦犹今之视昔，悲夫！故列叙时人，录其所述，虽世殊事异，所以兴怀，其致一也。后之览者，亦将有感于斯文。
* COMMENT 部分译文
** 选必中
*** 屈原列传（第三段）
屈原痛心怀王惑于小人之言，不能明辨是非，小人混淆黑白，使怀王看不明白，邪恶的小人妨碍国家，端方正直的君子则不为朝廷所容，所以忧愁苦闷，写下了《离骚》。“离骚”，就是遭到忧愁的意思。天是人类的原始，父母是人的根本。人处于困境就会追念本源，所以到了极其劳苦疲倦的时候，没有不叫天的；遇到病痛或忧伤的时候，没有不叫父母的。屈原行为正直，竭尽自己的忠诚和智慧来辅助君主，谗邪的小人来离间他，可以说到了困境了。诚信却被怀疑，忠实却被诽谤，能够没有怨恨吗？屈原之所以写《离骚》，其原因大概是从怨愤引起的。《国风》虽然多写男女爱情，但不过分而失当。《小雅》虽然多讥讽指责，但并不宣扬作乱。像《离骚》，可以说是兼有二者的特点了。它对远古上溯到帝喾，近世称述齐桓公，中古称述商汤和周武王，用来讽刺当时的政事。阐明道德的广阔崇高，国家治乱兴亡的道理，无不完全表现出来。他的文笔简约，词意精微，他的志趣高洁，行为廉正。就其文字描写来看，不过寻常事物，但它的旨趣是极大的（因为关系到国家的治乱），举的是近事，而表达的意思却十分深远。由于志趣高洁，所以文章中称述的事物也是透散着芬芳的，由于行为廉正，所以到死也不为奸邪势力所容。他独自远离污泥浊水之中，像蝉脱壳一样摆脱浊秽，浮游在尘世之外，不受浊世的玷辱，保持皎洁的品质，出污泥而不染。可以推断，屈原的志向，即使和日月争辉，也是可以的。
*** 过秦论
秦孝公占据觳山与函谷关的险固关隘，拥有雍州的土地，君臣牢固地守卫着这些地盘，以便伺机夺取衰弱的东周王朝，有席卷天下、征服列国、控制四海的意愿，有并吞八方、统一中国的雄心。在那时候，有商鞅辅佐他，对内确立法律制度，致力农耕纺织，修缮防守与进攻用的器械，对外推行连横之策并使诸侯相互争斗。于是秦人很容易夺取了黄河以西的大片土地。

孝公死后，惠文王、武王、昭襄王继承先人的基业，沿袭前代的策略，向南攻取了汉中，向西攻占了巴、蜀，向东割取了肥沃的土地，向北占据了重大的城邑。六国诸侯都很害怕，于是结盟商讨削弱秦国的办法，不惜珍贵的财宝以及肥沃富饶的土地，用来招纳天下有本领的人，采用合纵策略缔结盟约，相互援助，结为—体。在这时，齐国有孟尝君，赵国有平原君，楚国有春申君，魏国有信陵君。这四位公子，都明达聪慧而又忠诚讲信用，宽宏厚道而又爱惜人民，尊敬贤才而又重视士人，他们相约合纵结盟，以离间秦国的连横之策，聚合了韩、魏、燕、楚、齐、赵、宋、卫、中山等国的民众。于是，六国的谋士，其中有甯越、徐尚、苏秦、杜赫这些人为他们谋划；齐明、周最、陈轸、召滑、楼缓、翟景、苏厉、乐毅这些人沟通他们合纵抗秦的主张；吴起、孙膑、带佗、倪良、王廖、田忌、廉颇、赵奢这些人统率他们的军队。他们留以十倍于秦国的土地，以百万士兵的军队，攻打函谷关而攻击秦国。秦人打开函谷关迎击敌军，然而，九国的军队犹豫、徘徊而不敢前进。秦人没有破费一支箭杆失去一支箭头，可是天下的诸侯已经疲惫不堪了。于是合纵离散，盟约失败，六国诸侯们争着割让土地去贿赂秦国。秦国也就有了富余的力量制服他们，追击逃走的败兵，杀得败军横尸百万，流的血水竟能漂浮起盾牌来：秦国趁着有利的条件，乘着好的形势，宰割诸侯的国家，占有诸侯的山河。强大一些的国家请求接受归顺，弱小一些的国家则前去朝拜称臣。延续到孝文王、庄襄王，他们统治的日子很短，国家没有发生什么战争。

等到秦始皇即位，他发扬了六代君王遗留的功业，挥鞭用武力来征服各国，终于吞并了西周、东周而且灭亡了诸侯各国，登上了至高无上的皇帝宝座而制服了天下，掌握各种刑具来奴役天下的百姓，威风震撼四海。他向南攻取了百越的土地，把它划为桂林郡和象郡；百越的部落首领，只得低着头用绳子捆住脖子表示投降，把自己的生命交给狱吏掌握。于是又派蒙恬到北方去修筑长城并固守边境，把匈奴赶退七百余里；匈奴人不再敢南下放马，六国的勇士再也不敢拿起弓箭来复仇。于是，秦始皇废除了先王的治国之道，焚毁了诸子百家的著作，用这种办法来愚化百姓；毁掉著名的城池，杀掉了许多英雄豪杰；收缴天下的兵器，集聚到咸阳，销熔兵刀箭头，铸成了十二尊铜人，用这种办法来削弱天下百姓的反抗力量。此后，依仗华山作为城墙，凭借黄河作为护城河，占据高达万丈的华山，又面对深不见底的黄河，把它作为固守的据点。又派优秀的将领拿着强劲的弓弩守卫着战略要地，派可靠的臣子和精锐的士卒摆着锋利的兵器，盘问来往行人。天下已经平定，秦始皇的心意，自以为关中的险固地势，像是千里长的铜铁铸成的城垣，正是子孙称帝称王万代的基业。

始皇去世之后，他的余威依然震慑着边远地区。可是，陈涉不过是个破瓮做窗户、草绳做户枢的贫家子弟，是氓、隶一类的人，（后来）做了被迁谪戍边的卒子；才能不如普通人，并没有孔丘、墨翟那样的贤德，也不像陶朱、猗顿那样富有。（他）跻身于戍卒的队伍中，从田野间突然奋起发难，率领着疲惫无力的士兵，指挥着几百人的队伍，掉转头来进攻秦国，砍下树木作武器，举起竹竿当旗帜，天下豪杰像云一样聚集，回声似的应和他，许多人都背着粮食，如影随形地跟着。崤山以东的英雄豪杰于是一齐起事，消灭了秦的家族。

况且那天下并没有缩小削弱，雍州的地势，崤山和函谷关的险固，是保持原来的样子。陈涉的地位，没有比齐、楚、燕、赵、韩、魏、宋、卫、中山的国君更加尊贵；锄头木棍也不比钩戟长矛更锋利；那迁谪戍边的士兵也不能和九国部队抗衡；深谋远虑，行军用兵的方法，也比不上先前九国的武将谋臣。可是条件好者失败而条件差者成功，功业完全相反，为什么呢？假使拿东方诸侯国跟陈涉比一比长短大小，量一量权势力量，就更不能相提并论了。然而秦凭借着它的小小的地方，发展到兵车万乘的国势，管辖全国，使六国诸侯都来朝见，已经一百多年了；这之后把天下作为家业，用崤山、函谷关作为自己的内宫；陈涉一人起义国家就灭亡了，秦王子婴死在别人手里，被天下人耻笑，这是为什么呢？就因为不施行仁政而使攻守的形势发生了变化啊。
*** 五代史伶官传序
啊！国家的兴盛与衰败的道理，虽说是天意，难道不是人为的缘故吗？探究庄宗得天下和失天下的原因，就可以知道了。

世人传言晋王李克用临死时，曾把三支箭交给庄宗，并对他说：“梁是我的仇人，燕王是我扶持的，契丹与我结为兄弟，但都背叛了我而归附于梁。这三件事，是我的遗恨。给你三支箭，希望你不要忘记你父亲报仇的心愿。”庄宗收下箭藏在宗庙里，此后打仗时，就派官员以少牢之礼祭祀于宗庙，恭敬地取出箭，放入锦锻织的袋子里，背着它冲杀在前，等打了胜仗，又把箭放回宗庙。

当庄宗用绳子捆着燕王父子，用木匣装放着梁王君臣的头颅，进宗庙，把箭交还先王，禀告报仇成功的消息的时候，他意气之盛，可以说是豪壮啊！等仇敌已灭，天下平定，一个人在夜间呼喊，叛乱的人四方响应，庄宗慌张东逃，还没等见到敌人，官兵们就离散了，只剩下君臣互相瞧着，不知投奔哪里是好，以至于剪断头发，对天发誓，眼泪沾湿了衣裳，这又是多么衰败啊！难道真是得天下难而失天下易吗！还是推究他成功或失败的原因，都在于人为的缘故呢？

《尚书》说：“自满招致损失，谦虚得到好处。”忧患与勤劳可以使国家兴盛，贪图安逸享乐可丧失性命，这是很自然的道理。所以当庄宗气势旺盛时，天下所有豪杰无人能同他对抗，等到衰败时，几十个伶人就可使他命丧国亡，为天下人所耻笑。可见祸患常常是由微小的事情积累而成的，聪明勇敢的人反而常被所溺爱的人或事困扰，难道仅仅是伶人的事吗？于是作《伶官传》。
