#+title: 无职蛇足篇1
#+setupfile: ./setup.setup

* 无职蛇足篇1
** 信息头
#+begin_quote
内容利用pandoc转自epub电子书，图片不留
#+end_quote

#+begin_src
制作信息

──────────────

天使动漫录入组录入

作者：理不尽な孙の手

插画：シロタカ

译者：陈柏伸

图源：真妹控

录入：kid

天使动漫：[[file:www.tsdm39.com]]

仅供个人学习交流使用，禁作商业用途

下载后请在24小时内删除，TSDM不负担任何责任

请尊重翻译、扫图、录入、校对的辛勤劳动

转载请保留完整的资讯，否则往后一律禁止

──────────────
#+end_src

** 简介
在毕黑利尔王国的决战最后，鲁迪乌斯•格雷拉特赢得了胜利。

描写他身边的人们在那之后的故事合集，《蛇足篇》在此开幕！

本系列的第一集收录了诺伦的结婚故事〈诺伦的婚礼〉，

描写露西第一次上学的〈露西与爸爸〉，

加上杜加与伊佐露缇的婚活故事〈阿斯拉七骑士物语〉，

以及描写基列奴返乡的特稿短篇，

〈从前被称为狂犬的女人〉，共四篇。

决战之后，人生依然继续──

鲁迪乌斯在这段人生中有着何种想法，完成了何种创举......

人生重来型转生奇幻小说，激斗之后的故事在此开幕！

** 诺伦的婚礼
*** 「诺伦出嫁　前篇」

在毕黑利尔王国的那场战斗之后已经过了几个月。

人神自那之后便一直保持着沉默，持续过着感觉不到敌人气息的每一天。

话虽如此，我要做的事也没什么改变。

为了面对八十年后与拉普拉斯的决战，我不断走访各地，不动声色地做好事前的准备......

可是，我最近待在自宅的时间却变多了。

因为我们发现艾莉丝和洛琪希在同一时期怀孕。

果然是在打倒基斯之后过得太放纵了吧。

这是颓废的生活所导致的结果。

尽管就结果来说很令人开心，但在怀孕期间会导致命运的力量变弱，让人神有可趁之机。

所以我也希望尽可能地与怀孕的妻子们待在一起。

如此这般，现在我久违地取得了与家人相处的时间，整理设立在各地的佣兵团所提供的情报，并与奥尔斯帝德开会，根据情报商量今后该怎么行动，每天过着这样的生活。

\\

就在这样的某一天。

那天，我与奥尔斯帝德两人在讨论有关下次要前去的国家的情报。

那个国家的下任国王虽然现在还年幼，但将来会是个杰出的人物。我们本来应该是在讨论该不该趁现在先打声招呼，好在日后活用这段关系。

奥尔斯帝德没有明确表示拉拢那个下任国王的手段，始终保持着沉默。

可能是基于某种理由，在这次的轮回中并不存在足以用来拉拢下任国王的关键人物，再不然就是本来应该要在更后面的时间点才跟他搭话，目前并没有能确实拉拢这个人的手段。

这样的话，我该怎么行动呢？

我听奥尔斯帝德描述那个杰出的人物后画了人像图，看着那张画像反复思考。

事情就是在那时发生的。

\\

「让诺伦•格雷拉特结婚吧。」

\\

「咦......？」

这句话非常唐突。

奥尔斯帝德突如其来地打破了沉默，讲了句没头没脑的话。

唐突到即使是对奥尔斯帝德相当注意遣辞用句的我，也差点就不假思索地说出「你突然说这什么鬼话啊？」。

因为我现在正思考着该如何拉拢那个杰出人物，他却牛头不对马嘴地说出这种话。

这时，我突然想到一点。

不，他会这样说，难道真的没有他的道理吗？

随后我便得到了一个答案。

「......您的意思是策略婚姻吗？」

从对话的走向来想，为了要拉拢那个杰出人物，就需要把诺伦......是这么一回事吧。

「虽然谈不上是策略婚姻，但考虑到将来的话是有这个必要。」

「意思是......单靠我的力量还不够吗？」

然而，这很令我不甘心。

这代表奥尔斯帝德判断就算我前去拜会，也无法说服那个杰出人物。

不，如果只是这样还好。毕竟我也不是对自己特别有自信，没有足以说服那个杰出人物的手段。如果那个杰出人物和保罗一样是个天字第一号大色胚，不准备个女人给他就不行的话，我也能理解奥尔斯帝德为何会这样提议。

可是，就算这样。

这件事不可以落在诺伦身上。

诺伦将来总有一天会结婚。

但是，就算保罗是个无与伦比的大色胚，我也不能把诺伦交给他的同类。

该怎么说呢，诺伦的对象必须是个更诚实的人。而且还必须要经过我的认可才行。我不能把诺伦交给一个来路不明的家伙。这样的话我可没脸见保罗。就算目的再怎么崇高，我也不能舍弃家人让自己前进。

「不是那个意思。」

「那么是为什么？」

「我曾受过诺伦•格雷拉特的孩子帮助。」

「帮助......？也就是说，不是指诺伦怎么样，而是诺伦的孩子能派上用场？」

「也不到能派上用场。在这次的轮回也不见得那么重要。」

这段话听起来让人摸不着头绪。

虽说搞不清楚奥尔斯帝德话中真正的意图也不是今天才开始的，但从至今的模式来看，我可以知道他打算表达的意思。

简而言之，就是布局。

尽管诺伦的孩子并不重要，但因为他曾在以前的轮回中派上用场，所以打算先处理好这件事。

「明白了。」

我挺起身子。

然后，低头看着坐在椅子上抬头看我的奥尔斯帝德。

他现在没有戴着头盔。尽管长相依然是那么可怕，但现在肯定是我的表情更加吓人吧。

「如果无论如何都要那么做的话，三天后的正午，能请您来北方的森林一趟吗？」

诺伦，放心吧。

你的贞操由我来守护。即使对手是奥尔斯帝德，我也不会退让。

所以保罗......借给我力量吧。保佑我有办法打倒这个强大的敌人，并活着回来。

「慢着。你误会了。」

「误会？」

「即使是我，在无数次循环的两百年时光当中，也有人会令我念念不忘。诺伦•格雷拉特的孩子就是其中一人。我受到她的关照，好几次被她所救。所以如果可以的话，我希望她能够诞生在这个世上。因为照现在这样下去，这个愿望想必是无法实现的。」

确实，诺伦身边感觉不像有男人。

她毕业之后依然待在家里。虽说是在家里，但也并非没有工作。她现在透过在学校建立的人脉进入了魔术公会，在本部担任办事员。也就是所谓的OL。

尽管魔术公会里面也有不少男人。但诺伦身边感觉不像有男人。

她在假日也不会出门，一直待在家里帮忙顾小孩或是做家事。

在学生时代似乎也没有和特定的对象交往过。

我本以为诺伦总有一天也会有对象。不过说实话，我也认为她再这样下去可能就会不结婚，孤独终老。

「......」

在这个世界，有一定地位的人多半都会被人安排相亲。我虽然是个半吊子，姑且也有一定地位，应该算具有人脉和管道吧。

既然如此，这样的提案其实也没那么奇怪。

「......呃，可是小孩子不是一个人就能生出来的。应该也不是与任何对象都能生出同一个人吧？」

如果是一国之王，确实是具有相当的地位。

但是，我不打算这么简单就答应。除非亲眼见上一面，确认对方是什么样的人。

「还是说，您说的那个杰出人物，就是诺伦本来的对象吗？」

我思考着这点，同时恶狠狠地盯着奥尔斯帝德，随后他皱起了眉头。

他的长相依然还是这么可怕。

但是，我对这个表情有印象。是在表示「你突然说什么啊？」的脸。

然后，他像是会意过来那样，微微松开眉头并开口说道：

「不......抱歉。与那件事无关。」

「咦？」

「这是另外一件事。」

另外一件事......所以，意思是这样吗？

「和下次攻略的国家无关，单纯只是在商量诺伦的结婚对象？」

「没错。」

这样啊。原来如此，是这样啊。

「奥尔斯帝德大人。」

「怎么了？」

「要改变话题的时候，我认为最好先声明要『换个话题』或是『话说回来』之类的。」

「说得也是。我下次会注意。」

收拾了这个局面后，我重新坐回椅子上。

\\

★　★　★

\\

我重新整理好心情，继续进行对话。

「那么，请问诺伦的对象是谁？诺伦每次都会和那个人结婚吧？」

「嗯，就我所知，诺伦•格雷拉特的对象是注定的。」

诺伦命中注定的另一半。

真是个幸福的家伙。只要活在世上，竟然就能与我家诺伦结婚，实在是三生有幸。如果他是个怠惰地过着每一天的那种浑浑噩噩的家伙，我就把他绑架来拉正吧。要采用斯巴达教育。从早上起床到晚上就寝为止都要彻底地进行训练。只要把他锻炼成只会说是、YES还有谢谢的家伙，想必也不会外遇吧。

至于标准的话，这个嘛......若是想成为诺伦的伴侣，再怎么样也要有被艾莉丝揍了一拳后还不会昏过去的实力──

\\

「是瑞杰路德•斯佩路迪亚。」

\\

思考顿时停住。我的脑海浮现那个活了大约五百年的光头战士的脸。

不对，已经不是光头了。

他长出了一头漂亮的绿发，是个顶天立地的男人。

「他们两人的孩子是斯佩路德族最后的战士，继承了晚年因为疫病而倒下的瑞杰路德的遗志，为了挽回斯佩路德族的名誉而站在人族这边与魔族战斗，是在最后了结了拉普拉斯的存在。沉重、痛苦，不受到任何人认同......但是，这次有许多斯佩路德族活了下来。那孩子应该是不至于再背负那么沉重的使命了吧。」

在我思考停止的这段时间，奥尔斯帝德也依然滔滔不绝地说道。

他肯定是想起了那个孩子的一生吧。

既然他会打倒拉普拉斯，说不定与奥尔斯帝德曾是合作关系。

这样的话，原来如此，也不难理解奥尔斯帝德为何会提出这个提案。

「......」

不过呢，这次的状况不同。有我在。还发生过转移事件。

尽管我不晓得诺伦与瑞杰路德在以前的轮回当中是怎么与彼此发展关系，但这次他们两人并没有发展出奥尔斯帝德所知道的那种浪漫爱情故事，这点毋庸置疑。但就算我突然跟诺伦提起结婚的话题，她也有可能会说不要而直接回绝。

毕竟两人的年龄差了五百岁。瑞杰路德肯定也会很困扰吧。

能与瑞杰路德成为血亲，对我来说绝没有任何不满。

但是，这种事情还是不应该由我独自决定。嗯。

「......以我的立场来说，我想要重视诺伦的心意。」

「好吧。这件事并没有那么急迫。」

奥尔斯帝德这样说完，点了点头。

\\

在这之后，我麻烦奥尔斯帝德告诉我诺伦在以前的轮回经历了哪些事。

在没有我的世界里，诺伦好像成为了冒险者。

会唱唱歌、写写诗，像这样进行着冒险，是个有办法在唱歌跳舞的同时战斗的吟游诗人。她和一群志同道合的伙伴们组成队伍，在北方大地旅行。

话虽如此，即使是说客套话，诺伦的剑术与魔术的本事也不算杰出。

以冒险者的基准来看，顶多也只到B级。

所以，在进行某个任务的途中，他们的队伍遭到魔物全灭，诺伦也因此奄奄一息。

在那时出现的，就是我们的瑞杰路德。

他三两下打倒袭击而来的魔物，将诺伦从危机中拯救出来。

于是，诺伦对瑞杰路德一见钟情。

她后来就那样跟着瑞杰路德旅行，与他一起寻找斯佩路德族，也同时展开了小小的攻势。

瑞杰路德当时好像并没有把诺伦视为恋爱对象，但后来他得知斯佩路德族因为疫病全灭之后，顿时陷入了绝望的深渊。

诺伦在这时献身安慰了瑞杰路德，而瑞杰路德也对这样的诺伦动了感情，两人因此成为了夫妻。

于是，他们在毕黑利尔王国的一隅开始生活。

不久，诺伦生下了瑞杰路德的孩子，但瑞杰路德却和其他斯佩路德族一样，罹患疫病去世了。

诺伦被留下之后负起责任养育孩子，一直到寿终正寝。

我本以为她临终时应该是寂寞又难受的，但据奥尔斯帝德所说，诺伦死的时候露出了满足的表情。

尽管这段爱情故事令人难以相信，但男女之间不管发生什么事情都没什么好不可思议。

话是这样说，在这次轮回让从未有过这样经历的诺伦和瑞杰路德凑在一起真的好吗？

与不喜欢的人在一起，诺伦会高兴吗？

瑞杰路德会接受吗？

「......」

不过，我一个人在这烦恼也没什么意义。

重要的是诺伦的心意。

诺伦身边虽然没有男人的影子，但也差不多到适婚年龄了。就算有一两个喜欢的男人，或是有过一两段恋情其实也很正常。说不定只是我不晓得，其实她有正在交往的男性，这样也没什么好奇怪。

然后那家伙会在某一天突然被带回家里，对我这样说「父亲大人，请把女儿许配给我」，然后我就这样说了「谁是父亲大人啊」......「叫我哥哥」......

离题了。

总之，我必须先问出诺伦的心意才行。

然而像这种时候，总觉得由我来问不太恰当。我不认为由我去问的话诺伦会愿意告诉我。

那么，还是交给女性去处理吧。

不过爱夏不行。要是让爱夏去问，总觉得会出什么状况。

既然这样，果然还是该交给希露菲或者是洛琪希。尤其诺伦非常尊敬洛琪希，交给她应该比较适合吧。

但要说到尊敬的话，艾莉丝应该也可以。毕竟艾莉丝长久以来都在指导诺伦剑术。

诺伦从学校毕业之后，也会每天早上与艾莉丝一起慢跑，或是进行空挥练习。

她相当敬重艾莉丝，这点一目了然。

但是，我不认为艾莉丝的指令表里面有「不经意地询问」这样的技能。

果然还是交给洛琪希吧。不对等等，「不经意地询问」这个技能等级比较高的应该是希露菲。

虽说和尊敬的含意有些不同，但起码诺伦应该认为希露菲在这个家是最伟大的。

不，干脆直接和三个人都商量看看......？

包括我在内的四人一起讨论，决定谁最适合担纲这个任务。最好也要有希露菲与洛琪希的意见。

慢着慢着，不只是她们三人，也应该要询问莉莉雅和塞妮丝吗？

「......」

我坐在客厅的沙发上，一个人独自思考着这些事......

就在这时，一位女性的身影映入眼帘。

「啊。」

是诺伦。诺伦走进了客厅。

「哥哥，我回来了。」

「......欢迎回来。」

不管怎么样，这样一看就能发现诺伦确实成长为美女了。

脸蛋长得很像年轻时的塞妮丝。不仅胸部很大，金发也柔顺飘逸。

在学校应该也很受欢迎吧。

「......怎么了？」

「没事......啊，诺伦，你要喝茶吗？」

「好。」

我拿起放在桌上的茶壶与一个茶杯，慢慢往茶杯里注入红茶。

诺伦接过茶后，露出了疑惑的表情。

「......已经凉掉了。」

「咦！」

这不是莉莉雅刚刚才泡的茶吗？

我这样心想，用手碰了茶壶确认，发现确实凉掉了。我手中的茶也是凉的。

这是怎么回事？该不会是受到了某人的攻击？

「......奇怪？话说起来诺伦，你今天不是去工作吗？」

「我现在刚下班回来。」

我不经意地望向窗外，发现时间已经到了傍晚。

和奥尔斯帝德开完会后回来，麻烦莉莉雅泡茶的时候才刚过中午，换句话说在那之后已经过了两个小时吗？

「啊，抱歉，我刚才好像有好一阵子都在发呆。」

「请你至少等年纪大一点再做这种事......我去重新泡一壶。哥哥先等一会儿吧。」

「......咦？没有人在家吗？」

直到刚才为止，希露菲和艾莉丝应该还在。

洛琪希......这个时间应该还没回来吧。

「希露菲姐和艾莉丝姐在我回来的时候刚好带着孩子们出门散步了。莉莉雅小姐则是去买东西。」

「......爱夏呢？」

「不知道。应该还待在佣兵团那边吧？」

诺伦这样说完，便端着茶壶走进了厨房。

不过，这样啊，原来没有人在啊。只有我和诺伦两个人......

某种意义上，这个状况对我来说应该算是求之不得吧。

嗯。不需要拐弯抹角，我应该采取正攻法。如果这样行不通，之后再尝试其他手段。这样才算是真诚地对待诺伦不是吗？

嗯，嗯。等到别人都打理好了才知道这件事，诺伦一定也会很不是滋味。更何况她是要结婚的当事人。

首先，就告诉诺伦本人吧。

「来，请喝。」

「谢谢。」

当我如此左思右想的时候，诺伦回来了，她将倒入红茶的茶杯放在我面前。

看到诺伦坐在对面之后，我抿了一口茶。

「诺伦，你现在很会泡茶了呢。」

「因为在学校有学过。」

「不是向莉莉雅小姐学的？」

「莉莉雅小姐......大概不会教我喔。」

也对，就算诺伦对她说「请教我怎么泡茶」，那个人八成也会回说「那种事交给我来就行了，你没有学的必要」。

「不过，如果你跟她说一声，她应该还是会教才对。」

「是这样没错，但难得有地方供我学习，在那里学就可以了。何况在家里泡茶的机会也不多，但在学校就经常会遇上这种状况。」

「说得也是。」

在学生会、自己在宿舍的房间，还有现在她工作的地方也都有这种机会。

不过，不管怎么样都是诺伦自己的选择。

「......」

好了，既然讲了些轻松的话题缓和了气氛，应该就这样巧妙地切入正题。

该怎么说好呢？该从哪里说起好呢？

「唔......咳，呃咳......」

「......」

我清了清喉咙，诺伦随即用疑惑的眼神盯着我。

「......有哪里觉得不够的吗？」

「呃，不是，嗯。红茶非常好喝。」

我这样说着，同时喝了一口还冒着热气的红茶。

并不是说特别美味，但也不至于难喝到会吐出来。很有诺伦的风格，是很平凡的泡法。虽然能得到良却无法得到优，就是这样的感觉。

也就是说，很好喝。

不过先把这件事放在一边......

「话说，诺伦，最近......怎么样？」

「怎么样，是指？」

「嗯，比方说......工作方面怎么样？」

「也没有怎么样，就很普通。虽然现在还处于需要前辈指导工作内容的阶段......但应该也处理了不少工作。不过如果是爱夏的话，肯定能够做得更好吧。」

「不要和爱夏比较。」

我这样说完，诺伦点了点头。

爱夏正在从事别的工作。既然两人的工作性质不同，随便比较并不是好事。

「那么，关于你刚才提到的前辈......是那个吗？长得很帅的那种？」

「她很漂亮。哥哥不是也有跟她说过一次话吗？就是在我担任会长那段时期的副会长。」

「......是那个身材魁梧的兽族吗？」

「不是那一位，是另外一位女性啦。」

哦，是那位女性啊。

原来如此。虽然不记得名字，但那个女孩当时确实也在场。仔细想想，在诺伦就职时好像也听她提起过那件事。说是进了同一个部门什么的。

「原来如此，是女性啊......前辈当中没有男的吗？」

「当然有啊。」

「那个男性的前辈......是不是长得一表人才？」

「有长得帅的，也有不帅的。」

诺伦的职场好像有帅哥。这点很重要。

「哥哥，你从刚刚开始到底想说什么？」

「冷静下来，诺伦。先不要急着做出结论。」

「我觉得看起来不冷静的反而是哥哥。」

我可是很冷静的。我这个人一向都是既酷Cool聪颖Clever又诚实Clean。

是CCC鲁迪乌斯。里面绝对没有混着疯狂Crazy之类的单字。

「话说回来，诺伦......嗯哼，比方说那个，呃，你觉得那个帅哥，很帅吗？」

「是问我喜不喜欢他？」

「你喜欢他吗？」

啊，搞砸了。不小心就问得太直接了。

「并不喜欢。」

好吧，我豁出去了。

「那......你现在有喜欢的人吗？」

「............有喔。」

居然有啊！

从现在这个对话的过程，竟然会回答有！

你竟然......这么诚实地回答我吗！

「这......这样啊！原来有啊，也对，诺伦的年纪也不小了，当然会有嘛，这没什么好奇怪的，嗯。」

「不过哥哥现在倒是非常奇怪就是了。」

「怎么这么说呢。」

我一点也不奇怪。奇怪的是这个世界。是这个世界有问题，一定是这样。

「所以，你说的那个喜欢的对象，是什么样的人？」

「......比我年长。」

「哦？」

「很可靠。」

「哦哦？」

「总是保护着我的人。」

符合这三个条件的......

「难道......是我？」

「哥哥还没睡醒吗？」

抱歉。是我得意忘形了。

「比哥哥来得年长许多，在紧要关头也不会惊慌失措，是个既沉着冷静又有威严的人。」

「哥哥也是喔，最近呢，就算在紧要关头也是从容不迫的喔。」

「请回想自己刚才的态度再说这句话。」

咕唔唔......

不过，这样啊，比我来得年长许多，又有威严是吗？可恶......

「年长许多......意思是，对方比我大十岁以上？」

「还要大更多。」

「......诺伦意外地是个大叔控耶。」

「什么大叔控......不过，我承认自己喜欢年长的人。」

既然大更多，想必超过二十岁以上吧。

换句话说，就是四十岁或五十几岁的人。而且还很有威严，这样说不定是那种肥胖的大叔呢。

毕竟重心一旦偏在下方，自然就会有种稳定感，又散发着威严。虽然前世的我压根没有威严就是了。

「......」

可是我现在脑海中浮现的，是那种头衔是黑心贸易公司的社长，外表脑满肠肥的狸猫脸大叔啊。

尽管我不会因为交往的对象年纪差距过大而斥责诺伦，但不管怎么想那个画面看起来根本就是援交啊。

我不认同，这种事我绝不认同。

不过，假如那个狸猫大叔是个超乎想像的正直男人......就算有年龄差距其实也不是重点。不能光凭外表判断一个人。

「不过，我知道这段恋情是不可能实现的。」

「不可能实现......难道对方是有妇之夫？」

「不......他的妻子已经去世了......」

去世了。这个说法说不定只是那个人单方面的说词，也有可能是离婚了。

是说，尽管我一直强迫自己不去想到那个人，但这该不会......

「不过，听说我好像长得有点像他已故的夫人。」

啊，这样的话肯定不是他。再怎么说也不可能是他。因为他不会说这种话。

「听起来真像泡妞时的老套说法啊。」

缠上比自己年轻许多的女孩子，说对方很像自己的妻子，根本就是泡妞时老套的说法。

就好像是在表示「你对我来说是会考虑到结婚的对象」。

不过等等，仔细想想，其实这也不像泡妞时会讲的话？如果说什么「你和妻子完全不同」「我是第一次见到像你这样的女孩子」的话，反而比较像是泡妞时会讲的吧？

「咦......他是在追求我吗？」

诺伦不禁用手遮住有些通红的脸庞。

或许是因为很高兴自己受到对方追求吧？这样啊，原来不是对方迷上诺伦，而是诺伦喜欢上他啊。

不过诺伦啊，你也很有可能被骗了喔。

若是现在说这种话，肯定也只会和诺伦吵起来，我还是先闭嘴吧。

「话说，哥哥为什么突然问起这种事？」

「哎？不，呃。」

「有什么特别的理由吗？」

诺伦像是瞪着我那样望向这边。

那张脸就像是在表示「我都已经实话实说了，请哥哥也老实告诉我原因」。

我也没想到她会这么坦白地讲出内心的想法。

本来只是想说要自然而然地看着她的脸，同时问她是否有喜欢的人，确认一下她的反应就好了。

「......听你刚才说了那些话后，再讲这种话是有点过意不去。」

「请说吧。」

诺伦微微探出身子，稍稍抬起头看着我。

「其实，诺伦，我跟其他人有聊到你的婚事。」

诺伦听到这句话，顿时愣住了几秒。

她瞪大眼睛，嘴巴也抿得死紧，用力盯着我。

「婚事啊......知道了。我答应这件事。」

「不，我知道。不用特别讲出来，既然这样，这件事就当我没提过吧。」

「不，我都说要答应了。」

我望向诺伦，想必我现在的眼神一定充满了疑惑吧。

「......你不是有喜欢的对象吗？」

「没关系。反正这份恋情不可能实现。」

诺伦露出稍微思考了一下的举止之后，继续说道：

「我们家虽然不是贵族，哥哥的地位却与贵族相当，所以我的朋友也说过迟早会有这样的事情发生。而且，当我听说哥哥在各国牵线的时候，也已经预想到自己会被用在这种时候。」

「别说用什么的。我没打算把家人当作道具。」

我以稍稍严肃的语气这样说道，诺伦听了后顿时会意过来，低下了头。

「说得也是......对不起。」

我妹妹真是坦率。

「诺伦不愿意的话，这件事就当没提过吧。」

「不......也不是说讨厌。既然哥哥会对我提起这件事，代表对方肯定也不是什么坏人对吧？」

「嗯，那倒是......」

以结婚对象来说......应该不坏。况且在毕黑利尔王国战斗的时候，他们看起来也很要好。

瑞杰路德是个彻头彻尾的老实人。

「不过......说得也是。毕竟我也不是无论如何都想结婚，也没有说不想结婚。既然哥哥都这样说了，如果这件事能当作没提过的话，我也松了一口气。当然，假如对方无论如何都想和我结婚，请哥哥不用在意我的感受，继续促成这门婚事也无所谓的......」

诺伦这样说完，把视线从我身上移开。

看样子她果然不是很想结婚，只是愿意遵从我的决定而已。

对我来说虽然是求之不得，但对诺伦来说，这并不是件好事。

「不，其实我还没和对方提过这件事。所以不要紧的。」

「这样啊......谢谢哥哥。」

既然诺伦都这样说了，虽然很对不起奥尔斯帝德，不过这件事就算了吧。

「......啊，我想顺便问一下，对方是什么人呢？是哪里的王族吗？还是阿斯拉王国的贵族？」

「不是王族也不是贵族......是诺伦也认识的人。」

「我认识的人......？啊，该不会是札诺巴前辈？」

「我想那家伙应该是不会结婚啦。」

札诺巴的事情先放一边吧。

毕竟茱丽都像那样不断释放出爱情光线了，两人之间却什么都没发生，更别说要和金洁凑在一起。

那家伙八成是打算和人偶过一辈子吧。

「是瑞杰路德喔。」

我说出了那个对象的名字。

「......」

当我注意到时，诺伦已经把手撑在桌上，往前探出身子。

\\

她露出了非常严肃的表情。脸整个涨红，看起来也很像在生气。

怎么了？难道我说了什么不该说的话吗？

毕竟诺伦也很尊敬瑞杰路德，果然还是不能把他视为恋爱的对象吧。

嗯。对不起啦，是哥哥误会了。所以不要这样瞪我啦。

「也......也对，再怎么说也不可能嘛。先不管种族上的不同，基本上年龄差距就太大了，你肯定也──」

\\

「哥哥，请你务必谈妥这门婚事！」

\\

诺伦打断了我的话，用难以隐藏兴奋与喜悦的声音如此说道。

\\

★　★　★

\\

到头来，或者该说果然是这样。

诺伦喜欢的对象似乎就是瑞杰路德。

从小时候，瑞杰路德好像就一直是她憧憬的对象。

听说这份从小开始的憧憬一直慢慢培育，发展成恋情，然后她在毕黑利尔王国的事件重新意识到了自己的心意。

自己喜欢着这个人。

然而，诺伦知晓瑞杰路德的过去，她深信自己根本不会被瑞杰路德当作对象看待，便决定像理所当然那样压抑住自己的恋慕之情，就这样活下去。

「我知道了，尽管交给哥哥吧。」

我得知一切之后，拍着胸脯这样与她约定。

*** 「诺伦出嫁　中篇」

交给我吧。

我这样放完话后，便直接开始打点结婚的事宜。

诺伦这边是没问题，但问题在于瑞杰路德。

既然他是个大人，听到我问他是否愿意和我妹妹结婚的话，想必会轻易点头答应吧。

以状况来思考，与我的家人结婚也对斯佩路德族有好处。

毕竟如果只看头衔的话，我可是龙神奥尔斯帝德的心腹。

自古以来，所谓结婚也有着增进同盟羁绊的重要意义。

一旦诺伦与瑞杰路德结婚，斯佩路德族便不会再违逆龙神阵营，而我们也不会切割斯佩路德族。这样的构图会自然而然地形成。

这是幸福的构图。

但是，这样真的好吗？

这样诺伦真的能得到幸福吗？

假如瑞杰路德是因为「无可奈何」才决定结婚，诺伦是否有办法心满意足呢？

当她发现自己其实不受对方所爱的时候，她有办法不因此落泪吗？

瑞杰路德现在是与毕黑利尔王国交涉的负责人。

这样一来，诺伦到时就得到斯佩路德的村子生活，不会继续待在魔法都市夏利亚。

在毕黑利尔王国的那起事件之后，所有村民姑且也都认识她了。

所以村民想必会接纳她吧。

但是，身边都是与自己不同种族的人，而且那里不管是常识还是生活方式，恐怕都与魔法都市夏利亚有所不同，诺伦真的有办法顺利与他们相处吗？

最坏的情况，会不会导致只有诺伦在附近的城镇分居呢？

真担心。实在很担心。

我和三位妻子商量了这方面的担忧后，洛琪希回说「诺伦的话应该没问题吧」，艾莉丝回说「瑞杰路德的话没问题的」，而希露菲则是说「你想太多了喔」。

换句话说是没问题的。

但我还是会担心。

因为我不能忍受诺伦遭遇到任何不幸。

万一诺伦到时每天以泪洗面，保罗大概也会出现在我的梦里，恶狠狠地盯着我。塞妮丝也会在我睡得香甜时坐在我的枕边，使劲狂拍我的脸颊。

为了他们两人，我必须要为诺伦铺起一条通往幸福的康庄大道。

就算是否能顺利步上轨道还得看诺伦自己，我也必须这么做。

当然，我知道瑞杰路德是值得信任的男人。即使他不会真心爱着诺伦，也一定会将她视为妻子好好善待吧。我很清楚他会顾虑到诺伦的感受，绝不会让她哭泣。

可是，凡事都有个万一。

比方说，瑞杰路德其实并没有那么喜欢诺伦。

所以，只要我帮他们两人准备一个可以能增进感情的事件就好了。

这样是不是就能让瑞杰路德的感情向着诺伦了呢？

如此一来就皆大欢喜了。

「......好。」

如此这般，我来到了毕黑利尔王国，斯佩路德族的村子。

这个村子在几个月前还处于百废待举的阶段，但如今已经完全有了村子的样子。

村子周围围起了高耸的栅栏，里面则是住家林立，尽管还没有农作物可以收获，但已经耕好了田地。

斯佩路德族的战士们一看见我便低头致意，爽快地让我踏入村子里面。

我向他们简单问候了一下，便快步移动到瑞杰路德家。

当然，这里是新盖好的房子。

由于瑞杰路德在这个村子的地位颇高，房子也很大。

嗯，应该是足够两个人生活。就算有了孩子也很放心。

「......瑞杰路德先生，你在吗？」

「鲁迪乌斯吗？」

瑞杰路德在家。

或许是刚吃完饭，他在房间中央的地炉旁盘腿而坐，好似在冥想那样闭着眼睛。

「......」

我坐在他的前面。

是用跪坐。瑞杰路德在这时睁开双眼，朝我投以疑惑的视线。

「......怎么了？」

他郑重地这样询问之后，我张开手掌，伸到瑞杰路德眼前。

「请先等一下，我还在思考该怎么说。」

「............嗯。」

然后，我便沉默了。

我望着劈里啪啦燃烧的火焰，以体感来说过了将近一个小时。尽管这样讲或许也很奇怪，但我并没有事先想好一开始要怎么起头。

我已经决定好要问什么了。

要问瑞杰路德是怎么看待诺伦的。是喜欢还是讨厌，是否能把她视为结婚对象。

话虽如此，到底该怎么开口才好？

像是，你愿意和诺伦结婚吗？

不对，结婚与心情是两回事，我不能将两者混为一谈。

「......」

瑞杰路德看到我始终不发一语，也没有特别想什么话题跟我说话。

他在等着我自己说出口。就好像是在表示他并不着急，所以我可以把要讲的事情慢慢讲出口。尽管我不清楚他现在有没有什么事情要办，但他应该也不是闲来无事。

想必他也一定是用这样的态度在对待诺伦吧。

说不定，诺伦反而会对这样的瑞杰路德觉得不耐烦。

可能会顶撞瑞杰路德说「请你说点什么吧」。

不，这不可能。

正因为瑞杰路德的个性如此，诺伦才会喜欢上他吧。不会因为陷入沉默所苦，这样的对象实属难能可贵。虽然我现在有点痛苦就是了。

「......话说回来，最近我有麻烦诺伦帮我泡茶，她现在变得非常熟练了呢。」

「哦，诺伦泡的茶吗？」

我用试探的方式如此说道，瑞杰路德果然上钩了。

看来，他果然对诺伦感兴趣吗？

那这样算是通过第一关了......？

不，先等等，如果沉默了一个小时的男人突然说了什么，不管是什么样的话题都会接吧。

不要着急。对话就是要循序渐进。

「听她说是因为在职场总是会泡茶才进步的。」

「这样啊......以前，我在她来这个村子的时候曾喝过她泡的茶。确实很好喝。」

瑞杰路德像是想起了什么那样眯起眼睛。原来他已经喝过诺伦泡的茶吗？很好喝啊。可以认为他的意思是还想再喝吧？难道他希望诺伦能每天为了他泡茶吗......

可恶，我该怎么问才好啊？

真希望眼前跳出选项候补。

难不成，奥尔斯帝德和我说话的时候也是这样的心情吗？

那么，我应该直截了当地问他吗？

怎么办？我到底该怎么办啊！

「不仅是茶，料理方面也不错。」

在我犹豫的时候对话也依然在进行。因为对话就是循序渐进，而且不会停止。

不过，先等等，他刚才说了什么？亲手做的料理？

「你吃过吗？」

「嗯。」

诺伦亲手做的料理？就连我也没吃过耶？

「这样啊......」

我不禁很在意诺伦是做什么样的料理。

是马铃薯炖肉？还是咖哩？或者是蛋包饭？难不成是俄罗斯牛柳饭？我也好想吃。好想吃吃看诺伦亲手做的料理。

不对，先别管我怎么想了。

不管怎么样，既然他说还不坏，代表不是不行。

尽管还不到抓住他的胃，但好像也没有觉得难吃而拒吃。既然如此，在他们婚后就不会看到爆瘦的瑞杰路德。

「诺伦怎么了吗？」

当我还在胡思乱想的时候，瑞杰路德这样问道。

他果然很敏锐。

不，是因为我板着脸走进来，然后没头没脑地提到诺论，也难怪他会这么问。

「不，没什么啦......她也没有怎么样，我只是闲聊一下而已。」

不过，要开门见山地直接问他，我还是缺少了一些勇气、觉悟以及毅力。

「你喜欢诺伦吗？」「你爱她吗？」「可以现在立刻抱紧她吻下去吗？」

要是我这样问，他的回答却是「完全不喜欢」「没办法跟她结婚」「就算结婚了也不可能爱上她」......这样的话该怎么办？

假如真的是这样，我一定会受到严重的打击吧。

我会当场找碴说「你到底对我家的诺伦有哪一点不满啊！」。

「诺伦现在成年了，也开始工作了，不过还是有些孩子气的地方......我总觉得，她实在是没有异性缘。所以我不禁会想，她是不是能够顺利结婚。」

我这样说完，望向瑞杰路德。

这样是不是讲得太露骨了？瑞杰路德露出了疑惑的表情。

「......人族的话，有着由当家安排结婚对象的规定吧？诺伦的对象，不是由你来决定的吗？」

「不不不──我们家不算贵族啦。我想说，诺伦的对象应该让她自己找就好了。嗯。」

我不时瞥向瑞杰路德，他的表情依然没什么变化。

不对，是在疑惑的表情上面，追加了些许严肃感吧？

他该不会觉得我是个不负责任的家伙吧？

「不！当然了！要是诺伦带来一个不像样的男人，我就会，那个，把那家伙带到荒野去。然后告诉他『想要诺伦的话就打倒我！』。因为我绝不会把诺伦交给那种来路不明的家伙！」

我慌张地找了借口搪塞过去。在推荐诺伦给他之前，要是瑞杰路德认为我是个不负责任的人就糟了。

虽然我也不清楚到底是哪里糟糕，总之就是糟糕。

「也就是说，想娶诺伦的话，必须先打倒你吗？」

「不......！其实强不强也不是那么必要啦！可是！就是啊，那个，胆识......对，我想要看到对方展现出过人的胆识。」

在关键时刻会因为害怕而逃跑的家伙是不行的。

我不能把诺伦交给那种家伙。

我虽然也经常会害怕，但好歹有着不会逃跑的胆识。所以呢，就是需要那种即使知道会输也会挺身而出的气概。

「这样啊。」

「就是这样。」

当然了，这一点瑞杰路德是没问题的。

我将带有这个含意的视线投向瑞杰路德，但他的表情毫无变化。

依然还是带有严肃的氛围......

这代表他果然对诺伦没兴趣吗？

「......」

也对。毕竟诺伦对他来说还是个小孩子。

自她还小的时候认识之后，诺伦在他眼里就一直是个弱小的孩子。而瑞杰路德绝对不会对孩子抱有情欲，他就是这样的男人。

「瑞杰路德先生......我就开门见山直接问了。」

「好。」

即使这样，我还是得问出他的想法。

就算这个结果会让诺伦变得很可怜，我也必须这么做。不能只凭他的脸色做出结论。

我也做好心理准备吧。

「你是怎么看待诺伦的？」

「......」

瑞杰路德沉默了。

他默不吭声，露出仿佛在瞪着我的眼神看了过来。神情很严肃，真的很严肃。

刚才疑惑的神色已经完全从脸上消失了。

「......」

真奇怪。

如果是平常的瑞杰路德，应该会立刻回答的。

是孩子，或是战士。应该会回答这两者之一。

「......你喜欢诺伦吗？」

我下定决心了。

若是不说的话，就什么都无法开始。我现在也许说了不应该说出口的话。这句话可能不应该由我来说，而是由诺伦主动说出口。

「这样啊。」

瑞杰路德听到这里，如此低喃了一句，随后便像是下定了决心那般站起身子，把立在旁边的长枪拿在手里。

「......鲁迪乌斯，出来外面。」

我不明白这个举动的意思，抬头看着他。

瑞杰路德眼见我一脸困惑地抬头望着他，用更强硬的语气说道：

「出来。」

「......好的。」

感受到这股无形的压力，我唯唯诺诺地听从了指示。

\\

离开斯佩路德族的村子后，我们朝向地龙谷的森林深处移动了十几分钟。

最后来到了位于深邃森林之中的一个开阔的广场，我和瑞杰路德面对面站着。

「......」

瑞杰路德从刚才开始表情就一直很严肃。

说不定是我做了什么惹他生气了。

在讲了那番话后，再询问他是不是喜欢诺伦果然是个失败的决定吗？

或者，他可能是误会了。

他以为我打算以政治目的把诺伦献给他。

他可是瑞杰路德，肯定会表现出男子汉的风范教训我，说「既然作为哥哥，你就要保护诺伦，不应该利用她取悦别人」。

就是因为他有这么可靠的一面，我才会如此地信赖他......

「原来你早就注意到了啊。」

然而，从瑞杰路德口中说出的话和我的预想完全不同。

「......？」

我注意到了什么？

现在，我在这个瞬间还依然不明所以，脑袋一片混乱耶？就算说客套话，我的观察力也不能说好啊？

「注意到什么？」

「不用再说了，我要上了！」

这就是所谓的多说无益啊。

事出突然，我根本还没打开预知眼，当然看不到瑞杰路德的动作。

「──好痛！」

瑞杰路德一瞬间拉近距离，我顿时倒在地上。

即使如此，与十几年前相较之下，我还是知道刚才发生了什么事。归功于平日训练的成果，我在紧要关头反应过来了。

瑞杰路德从右侧挥枪攻击，我立刻用魔导铠「二式改」的护手挡住。

紧接着，瑞杰路德使出一记低踢，我抬起单脚挡住，但是在变成单脚站立的时候，瑞杰路德将长枪顺势转过，用枪尾扫倒了我的轴心脚。

「如何？」

瑞杰路德用长枪抵着我的脖子，面无表情地俯视着我。

「我投降。实力果然了得。」

我搞不懂他说的如何是指什么，所以也只能这样回答。

尽管脖子没有被直接贯穿，但这种状态下明显已经分出胜负了。

「足够吗？」

什么意思？是指什么足够啊？

「反而该说是我修炼不足吧。」

「......那么，意思是很足够吗？」

不知道他说的足够是指什么，不过在这种情况下不可能说不够吧。

轻易就被打倒在地的我就算再说什么也只是丢脸而已。

「很足够。」

这样回答后，瑞杰路德把抵着我的长枪移开了。

我挺起身子，然后当场坐下。接着用自己也觉得很丢脸的表情抬头望向瑞杰路德。

「那么，按照约定，你的妹妹就归我了。」

下一刻，瑞杰路德说出了奇怪的话。

妹妹......归我。妹妹是什么来着？我们有做过这样的约定吗？

奇怪？他是在说什么？

感觉两边讲的话有点牛头不对马嘴。

「正如你所推测的一样。」

我推测了什么？

「我恋慕着诺伦。」

「恋慕......」

我拼命地在脑海中回想恋慕的含义。记得是......思恋和爱慕的意思吧。

「......咦？」

也就是说，瑞杰路德喜欢诺伦？

不对等等，不能太快下结论。我的坏习惯就是容易误会。

「也就是说，瑞杰路德先生，你......」

「............我喜欢她。」

说不定，他是在捉弄我？

如果我现在兴高采烈地说什么「那我就承认你和诺伦的婚事吧」然后将身穿白无垢的诺伦带来这里，瑞杰路德是不是会拿着「整人大成功」的牌子出现在我眼前？这是会对我造成严重打击的精神攻击。诺伦也有可能就这样卧床不起。这铁定是人神干的好事！

可恶！想不到瑞杰路德竟然是人神的使徒！

「这是在开什么玩笑吗？还是说，这是什么惩罚游戏吗？」

「这不是开玩笑。」

瑞杰路德露出有点不悦的神情这样说道。也是，瑞杰路德不会开玩笑。更何况是在这种场合。

「什么时候开始的？」

「几个月前，在毕黑利尔王国战斗的时候。因为她无微不至的照顾，我不禁产生了这样的感情。」

确实，他们两人当时关系很好。

但是，这难道不仅仅是诺伦的单相思吗？

诺伦只是像个自己送上门的老婆那样照顾瑞杰路德，我还以为瑞杰路德对她没有任何想法。

「当然，我并不打算对她出手。」

意思是如果诺伦不是我的妹妹，他就已经出手了？

想必已经出手了吧。根据龙神所知的以前的轮回来看，他们每次都会发展到那种关系。然后诺伦会成为女人，成为妻子，成为母亲。

「但是，你注意到了这件事。所以才会突然跑来说出那种话。」

「......」

怎么可能。

我知道的只有诺伦喜欢瑞杰路德而已。

怎么可能从这点就能知道你们其实是两情相悦。

我不可能那么敏锐。我可是迟钝系男主角啊。锋利度可是足以媲美晨星锤耶。

「我郑重地再说一次，我希望娶诺伦•格雷拉特为妻。」

瑞杰路德这样说着，拿起了刺向我脖子的长枪。

「所以，我让你见识了我的胆识。」

所以才会发生刚才那种事情吗？会演变成现在这种状况，都是因为我说了那种话吗？

为了让我见识他的胆识，所以才跟我决斗的吗？我的实力可不足以确认瑞杰路德的胆识啊......不过，事到如今根本就不需要确认那种事。

但是，该怎么说。

就是那个，比想像中还要混乱啊。

进行得太顺利了。

这是陷阱吗？是谁为了陷害某人设下的陷阱吗？

搞不懂。到底是怎么回事？

「那个......你之前的妻子和孩子没关系吗？」

因为我还摸不着头绪，决定继续提出疑问。

我坐在地上，抬头仰视着瑞杰路德，说出了这句话。

「之前也说过了，我不会被过去所束缚。」

只是还没有合适的对象，记得他以前确实这样说过。瑞杰路德见我不站起来，便把长枪刺入地面，也直接盘腿坐了下来。

我也把姿势改为跪坐，这样我们的视线高度就相同了。

「也就是说......」

瑞杰路德只说到这里，面有难色地低着头。

「......」

然后，他陷入了沉默。

因为我突然来到这里拆穿了他内心的爱恋之情，他便决定坦承自己的想法，把我带出来让我见识他的胆识。但是，他原本就是个不擅长言词的男人。接下来想说什么、该说什么，想必有许多事情都还没有整理好吧。

「......」

我太过着急了吗？

就算从奥尔斯帝德那里听到那些话，也没必要立刻撮合他们两人吧？

应该还是要研拟更加拐弯抹角的作战计划，来拉近两人的心才对吗？

比如说，想个诺伦遭到绑架的设定，然后向瑞杰路德求助之类......

不对，这样只会让诺伦更加迷恋他，应该要让瑞杰路德掉入陷阱之类。

等等，要是这么做我会被诺伦讨厌的。

「我迟早会和人族结婚。」

正当我烦恼时，瑞杰路德这样说道。他说的迟早是什么意思？

「这是什么意思？」

「多亏了你，斯佩路德族的复兴非常顺利，毕黑利尔王国的人民与鬼族都非常爽快地接纳了我们。斯佩路德族总有一天会像鬼族那样，与王族或是贵族通婚吧。既然如此，最适任的第一号人选当然就是我了。」

「哦？」

这种事......嗯，确实有可能。

瑞杰路德就立场上来说，相当于斯佩路德族的族长辅佐。

而且，他也是从前那场战争的英雄，受到族人尊敬。村里的偶像......这种说法可能不太对，不过算是类似守护神的存在。

这样的瑞杰路德会与毕黑利尔王国的王族或贵族结婚。对毕黑利尔王国来说，若是斯佩路德族愿意守护王国的话，想必也会安心吧。

「但是，如果我有选择的权利......鲁迪乌斯，我希望选择你家。」

听到这句话，我感到有种温热的东西涌上心头。

与毕黑利尔王国建立友好关系，是为了斯佩路德族。

比起和我家变成姻亲，这样做势必对斯佩路德族更有帮助。

可是，瑞杰路德愿意选择我家。

他选择了我！

啊，不是我。不好不好，差点就变成少女乌斯了。

当我想到这里，突然会意到一件事。

「选择诺伦真的好吗？」

「什么意思？」

瑞杰路德一脸疑惑地反问。

「诺伦她......该怎么说，其实相当任性。还有她做事不顾前后，有时候还会说些对方讨厌的话。你们夫妻到时吵架的话，她可能会神经大条地把瑞杰路德先生以前的事情拿出来吵。」

「......」

我讲出了自己从未想过的话。

真是奇怪。我在立场上必须要为诺伦加油，要帮她说好话才对。

然而说出口的，却都是诺伦的坏话。

「虽然所有的家事好像都难不倒她，但也不晓得她能不能胜任专业主妇这个工作。尽管她会念书，但好像不太能灵活应用或是动点巧思，如果第一次挑战什么事情，多半都会以失败收场。在夏利亚能简单做好的事情，在斯佩路德村都必须想个办法才能处理好。那孩子一定会给瑞杰路德先生添麻烦的。」

不对，我并不是想说这种话。

在我家，还有其他妙龄女性。

比方说爱夏。老实说，爱夏比诺伦优秀。

她不仅能做家事，也能照顾小孩。诺伦能做到的事情，爱夏没有一件做不到，她就是这么优秀。这样一想，我就会不由自主地涌起一个想法，让瑞杰路德选择诺伦真的好吗？

我想为诺伦加油。

但是，我也喜欢瑞杰路德。

也许正是因为我希望两人都获得幸福，才希望双方都没有不满吧。

「──但是，那也是她全力以赴的结果。」

打断我这番话的，还是瑞杰路德。

「不论是诺伦的优点还是缺点，我都很清楚。」

眼见我哑然失声，瑞杰路德继续说下去。

「你也很清楚吧。」

「当然。」

诺伦也有许多优点。

虽然我并不是那么了解最近的诺伦。但是，现在诺伦已经能为别人设想了。

她现在不会再被拿来和爱夏比较，所以也不再那么自卑。

歇斯底里的一面减少，也不再和爱夏吵架了。

而且她也很会照顾人。尽管在家里看不出来，但她在学校也受到同学和后辈所仰慕。

像十五岁生日的时候，也来了许多朋友为她祝贺。

现在也是，学校的后辈会跑到我们家，找诺伦商量关于学生会或念书方面的事情。

诺伦不论做什么事都总是全力以赴。

她全力以赴去做的结果，虽然没办法让她拿到第一，但已经能够完成自己原本不擅长的事情。

因为诺伦对很多事情都不擅长，和其他人相较之下，也许不会显得那么出众。

跟爱夏相比，两人的差距更是显得天差地远......

但是，其他人怎么样都无所谓。

她一直在努力，而且脚踏实地地往前迈进。她今后想必一辈子都会贯彻到底。

现在的诺伦，就是这样的女孩。

是个非常出色的女孩。

也是我引以为傲的妹妹。

而且，瑞杰路德也非常清楚这点。因为她知道诺伦是个总是全力以赴的女孩。

不需要我多说什么。

而且，他也很了解诺伦的缺点。

从很久以前，他就了解诺伦的缺点，并且包容了她。

将这些全部包括在内，对诺伦产生了爱意。

「......不论什么时候，你都会愿意守护诺伦对吧？」

「嗯。」

瑞杰路德坚定地点头。

也对，如果是他，肯定会保护诺伦，至死不渝。

「一旦结婚，诺伦身边就都是不同的种族，也会与家人分开，我想一定会非常辛苦，你会好好支持她吧？」

「嗯。」

瑞杰路德坚定地点头。

也对，如果是他，肯定会支持诺伦，至死不渝。

「就算诺伦只是因为遇到小事就闹别扭，说出惹人厌的话，你也愿意亲切地对待她吗？」

「嗯。」

瑞杰路德坚定地点头。

也对，如果是他，肯定会温柔地抚摸诺伦的头。

「诺伦是米里斯教徒......你不会花心吧？」

「嗯。」

瑞杰路德坚定地点头。

也对，这是当然的。瑞杰路德怎么可能被女色诱惑。

「诺伦是个比我更严重的爱哭鬼，没关系吧？」

「嗯，所以你也别哭了。」

我已经泪流满面了。

他的回答虽短却充满真诚，表情非常认真，眼神极为真挚。

「没问题。我全都明白。」

这时，我想起来了。

自那起转移事件之后，旅行到中央大陆的这段期间。

是因为在瑞杰路德的身边，所以我才能安心。不管什么样的魔物来袭都很放心，认为他一定会保护我们。当然，除了对付魔物之外，他有些事情倒是很靠不住，不过既然是人，这也是没有办法的事。

毕竟人不可能十全十美。

瑞杰路德不擅长的事情，交给诺伦帮他就好。

如果是现在的诺伦，一定能够做到这点。

她已经用行动证明了。

否则，瑞杰路德不可能会说自己要收下诺伦。

我这样想着，顿时松了一口气。

放心了。

「我妹妹......就拜托你照顾了。」

最后，我低下头。

*** 「诺伦出嫁　后篇」

★诺伦★

\\

我已经确定要跟瑞杰路德先生结婚了。

这件事的进展实在快到令人惊讶。

被哥哥逼问了各种事情之后，我老实地回答内心的想法。

后来不到十天，哥哥便把我和瑞杰路德先生一起叫来，瑞杰路德先生当场对我做出爱的告白，同时我也接受了他的求婚。

在我开心得飘飘然的时候，这门婚事也不断地在进行。

再过十天就要举办婚礼了。

哥哥和瑞杰路德先生正一步一步地准备着相关事宜。

至于我这段期间做了什么，就是与斯佩路德族的女人一起制作结婚礼服。

那是瑞杰路德先生平常穿的那种带有斯佩路德族风格的衣服。

婚礼似乎要采用斯佩路德族的传统方式举办。事实上我确实有些憧憬着米里斯举办婚礼的方式，不过这么做感觉就像是强调了我要嫁给瑞杰路德先生的事实，所以并不排斥。

斯佩路德族的大家也都是好人。说真的，我也不想再奢求什么。而且瑞杰路德先生应该也讨厌在人前亲额头吧。

不管怎么样，哥哥都说了「交给我吧」，我只要心怀感激地接受就行了。

不过，我或许还是想要一条「米里斯项链」。

要不要拜托哥哥呢？

毕竟这一定也是向哥哥撒娇的最后一次机会。

「......」

我在思考着这些事情的同时，整理着自己的房间。

自瑞杰路德先生把我和爱夏一起带来这里之后，我就一直使用着这间房间。

因为长时间都在宿舍生活，两者相较之下，我反而觉得宿舍那边感觉更像自己的房间。

不过整理之后，才发现每样东西都充满着回忆。

札诺巴前辈给我的瑞杰路德先生的人偶。一开始看到的时候就觉得很感动，不禁央求他给我，直到毕业之前都一直摆在宿舍的房间。

不管怎么说，每天看着这个人偶已经变成了例行公事。

虽然外观与瑞杰路德先生稍稍有些不同，不过一看就可以知道是瑞杰路德先生。

我以前总是看着这个人偶，希望能见上他一面。

然后，是这把木刀。

自艾莉丝姐教我剑术之后，我就几乎每天挥剑练习。

尽管没有进步得很明显，我也明白自己没有才能，但这样也无所谓。

只要能够挥着剑我就很开心了，毕竟我并不想成为世界最强。

在夏利亚，从来没人自以为是地说什么「没有才能就别练了」这种话。

哥哥就不用说了，艾莉丝姐也好，洛琪希姐也好，希露菲姐也是......甚至是札诺巴学长与克里夫学长都没这样说过。

大家明明都充满了才华，却从未说过这种话。

如今，我才明白这是多么难能可贵的事情。

而且也了解到非常一件重要的事，那就是即使没有才能也要努力。

否则，我不可能会当上学生会长。

我担任学生会长那段时期的学生会成员，大家都没有什么才能。

有一部分的教师也说过，这是魔法大学创校以来最平庸的一届学生会。

不过吉纳斯副校长说过：「学生们比爱丽儿担任会长的那段时期过得更加安稳呢」。

实际上，在我担任学生会长的那段时期，校内的暴力事件与犯罪事件似乎比爱丽儿会长的时期还要少。虽然也有可能只是运气比较好，但我认为会不会是因为学生会的大家没有才能的关系呢？

正是因为我们很平庸，学生会才能站在学生的角度去思考，而学生也会为学生会着想。或许他们也曾想过必须要帮助我们。

因为这所学校的学生高达一万人，比起只有十几个人的学生会独自努力，肯定是一万名学生稍微花点心思注意，才能让学校变得更好。

衣橱里的学校制服也已经不会再穿了。

我听说这件制服好像是七星小姐所设计的。

在那之前，每个人穿的服装都是五花八门。

在我入学的时候，大家都已经把制服或是长袍穿在身上了。

不管长相多么凶神恶煞的学生还是妖艳的美女，大家都穿着同样的衣服。

之所以能交到这么多的朋友，我想也是因为大家都穿着同样衣服的缘故。

若是穿着不一样的服装，我应该也没有办法与现在的朋友变得这么要好。

毕竟不管是魔族还是兽族，有时也会穿着不会让人打算上前搭话的打扮......我是不太清楚啦。

不过，爱夏在自己的佣兵团也效法七星小姐采用了制服制度，所以我认为让所有学生都穿上同样的衣服是很有效的做法。因为就连那个爱夏也是这样做的。

然后是挂在墙壁上的，爸爸的剑。

据说爸爸在跟妈妈结婚之前就一直在使用这把剑。

是哥哥在分配爸爸的遗物时，分给我的剑。

另外一把剑分给了爱夏，后来因为哥哥会在战斗中使用，所以立刻就拿走了。至于铠甲则是放在妈妈的房间当摆饰。

每当发生什么事情，我就会向这把剑祈祷。

爸爸不是米里斯教徒。看在米里斯教徒的眼里，肯定会对他的为人皱起眉头，但我还是很喜欢他。

如果爸爸现在也还活着的话，一定也会满腹牢骚......不过，我不会讨厌他。

因为，爸爸总是那么地努力。

不管是对哥哥来说，还是对我来说，都有就算再怎么努力也办不到的时候......所以我应该会永远喜欢着爸爸。

而我今天也向爸爸，向这把剑祈祷。

「我就要结婚了。」

不，这并不是在祈祷，而是在报告吧。

哥哥曾经说过。他说自己也经常一个人去爸爸的坟前，向爸爸报告事情。

明明他那么忙碌......还是很注重这种地方，真的很厉害呢。

「哥哥代替爸爸承担了爸爸的角色。我从以前到现在，对哥哥来说肯定都是个沉重的负担，他总是为了我而拼命行动，从来不抱怨一句话......实在是千言万语也无法表达我对哥哥的谢意。」

原本是要向爸爸报告自己结婚的消息，却变成在表达对哥哥的感谢。

哥哥他真的代替了死去的爸爸以及变成那样的妈妈来守护我。

当然，因为哥哥十分忙碌，有时也会没办法顾及到我。

所以我看着这样的哥哥，不禁曾经想过，哥哥是不是因为爸爸过世才会心不甘情不愿地照顾我。不过，我现在知道并不是那样。

尽管我没办法说明得很清楚，但哥哥确实有好好地承担起爸爸与妈妈的职责。

我还记得很久很久以前的记忆。

那是我出生没多久那时的记忆。

当然，整体来说很模糊，并没有记得那么清楚。

那是我还在牙牙学语，不太会说话的时候。记得当时......我和爱夏在比赛。虽然不晓得为什么在比赛，但我记得妈妈就待在终点。

当然，我输给了爱夏。

爱夏用非常快的速度爬到妈妈那边，随后妈妈抱起了爱夏，夸奖她是个好孩子，做得非常好。

我看到这一幕后，哭了。

感觉妈妈离我好远，就好像爱夏把妈妈抢走了一样，我觉得自己是不是没办法被夸奖，于是就哭了。

然后，妈妈是这样说的。

「诺伦，妈妈会在这等你的。过来这里吧。」

妈妈这样说完，等着我爬到她那边，也好好夸奖了我。

哥哥也同样像这样等着我。

不管我多么笨拙，他都愿意等我。

他会努力忍受，有时候会露出苦笑，或者是一脸慌张，但绝对不会对我弃而不顾，而是一直等着我。他就是这样的人。

所以，我知道他确实也有扮演好妈妈的角色。

「......」

像婚事的准备工作也是。

哥哥把所有的事情都处理好了。

如果爸爸还活着的话，我想一定会像哥哥一样帮我到处张罗。

说不定，他会不太中意瑞杰路德先生，而稍微发生了一点小冲突呢。不过，等到我真的要结婚的时候，爸爸肯定会说「交给我吧！」，替我东奔西走打理好一切。

爸爸要和妈妈结婚的时候，想必也是这样子吧。

「......」

我一边想着这些事情一边整理房间，很快就收拾好了。

原本这个房间就没有放太多东西，现在我的私人物品也都清出来后，变得空空荡荡的。

这个房间之后好像会给露西使用，只要整理成这样应该就没问题了吧。

再来，只要把私人物品和一些有回忆的东西一起带到瑞杰路德先生家里就行了。

去斯佩路德族的村子，瑞杰路德先生的家里。

老实说，我感觉这就像是在作梦一样。

我竟然要和好久以前就一直憧憬的瑞杰路德先生结婚。

这件事令我感到雀跃，也很兴奋。希露菲姐好像也是这样，与男人开始展开两个人的生活，会有种混着期待与紧张的心情。

尽管瑞杰路德先生的年纪比我大上许多，可是我们一旦结婚，势必也会做哥哥与希露菲姐他们在做的那种事情。

虽然我有学过做法，但没有实践过。

有些不安呢。他会温柔地对待我吗？我能做好这件事吗？

不过比起不安，我明白内心更多的是期待。对此感到很兴奋。

那一天，哥哥提到瑞杰路德先生的名字时，我反射性地要求哥哥促进这门婚事，真的是太好了。

没错，我打从心底这样认为。

「嗳，诺伦姐......有空吗？」

这时，突然传来了敲门声，还听到了这样的声音。

会叫我诺伦姐的只有一个人，是爱夏。

「有空喔，怎么了吗？」

「嗯......可以说一下话吗？」

爱夏走进房间后，有点忸忸怩怩地把门关上。

真难得。说不定这还是第一次看见爱夏对我露出这样的态度。

「先坐下吧。」

「嗯。」

这样敦促爱夏后，她便坐到了床上。

我将刚才整理好的那些要带去瑞杰路德先生家的行李推到旁边，坐在椅子上。

「那个......诺伦姐，恭喜你结婚......不对，应该说订婚吗？」

「谢谢。」

话说起来，哥哥在宣布结婚的消息时，我收到了很多人的祝福，但爱夏并没有祝贺我。

「总觉得怪怪的呢，诺伦姐要结婚什么的，对吧。」

「你是为了说这件事才来的吗？」

「呃，不是啦，那个......诺伦姐，结婚是什么样的感觉？」

爱夏并没有看向我这边。

她别开视线，像是在询问什么禁忌那样如此询问。

「什么感觉......？」

「诺伦姐，你为什么要结婚呢？」

......啊，这么说来，我想起来了。

以前好像曾经被爱夏这样说过。

她说：「你明知道自己没有才能，为什么要这么做？」

妹妹依然没有变。话虽如此，以前这种话听起来会像是在讲坏话或是在刻意挖苦，但我最近明白其实并不是那样。

爱夏也有自己的烦恼，她在各方面的才能都过于优秀，所以反而对许多事情感到迷惘。

就因为什么事情都能轻松解决，所以才没办法体会「明明没办法做得很好却还是要做」的那种感觉。不......如果是以前的爱夏，在说这种话的时候多少会带有一点挖苦的语气吧。所以以前我非常不擅长应付爱夏。

然而，最近这种令我困扰的感觉也消失了。

爱夏是从什么时候开始对我讲话不再挖苦的呢......是在我当上学生会长之后吗？不对，应该是在更早之前......现在已经无从得知了。

只不过，至少在露西出生之后，我认为爱夏身上确实起了很大的变化。

「你问我为什么......因为这场婚姻很有意义，而且我也很喜欢瑞杰路德先生。」

「喜欢是什么感觉？」

「......就是想要和那个人在一起，看到对方之后就想抱住他，或是想被他抱住之类的，会自然涌现这样的心情。」

「我也喜欢哥哥，跟那种喜欢不一样吗？」

「这......我不是爱夏，所以我也不是很清楚。」

「也对啦......」

这样说完，爱夏坐在床上把脚一伸，就这样直接躺了下去。

「好难懂啊......」

爱夏一边晃着脚，同时念念有词地嘀咕着。

「不管是莉妮亚还是普露塞娜，她们俩最近一直吵着说要结婚什么，真的是烦死了呢。说是错过了适婚期，或是到了这个地步已经没办法妥协之类的。有必要为了结婚那么拼命吗？难道就非得要结婚不可吗？就道理上来说，我知道最好还是要结婚的喔。可是，也不是每个人都想走到这一步吧？」

「爱夏不想结婚吗？」

「我连自己想不想结婚也不太清楚。」

「你没有喜欢的对象吗？」

「没有，小时候一直想要跟哥哥结婚，可是对象是哥哥的话又感觉有哪里不太一样，而且我也没有办法想像离开这个家之后会是什么样子......」

爱夏从小就一直黏着哥哥。

我和她第一次见面是在米里斯，当时爸爸刚重新振作起来，开始做着了不起的工作。

说实话，我那时候真的没办法把爱夏当作是自己的妹妹。

应该像是宿舍的朋友说的那种「再婚对象的小孩」。

当时莉莉雅小姐也是，与其说是把爱夏当作女儿，反而更像是把她当作自己底下的女仆那样使唤。

我是什么时候开始认为她是自己的妹妹呢？

是一起在米里斯的学校上课的时候吗？

还是说，是与瑞杰路德先生还有金洁小姐一起在夏利亚旅行的那段期间呢？

到了现在，我已经回想不起来了。至少当我们开始在夏利亚一起生活的时候，我已经把她当作妹妹了。

「诺伦姐现在是什么样的心情呢？」

「我觉得......很幸福。」

「幸福？那是什么样的感觉？」

「用讲的很难解释，要怎么说好呢，我现在没有任何讨厌的感觉。虽然我自己也明白今后不会一直发生好事，但也相信今后会有好事发生，就是那种感觉。」

当我这样说完，爱夏从床上挺起身子，目不转睛地看着我。

就这样过了一会儿，她喃喃这样说道：

「那样子会幸福吗？」

「......那样子是？」

「因为我平常一直都是这样喔。」

「这就代表爱夏一直都很幸福吧？」

我这样说完，爱夏又倒回了床上。

「我觉得......应该不算幸福。总觉得好羡慕啊，感觉第一次输给了诺伦姐。」

「我倒是不觉得自己赢了......」

「不，我输了。我大概输给了诺伦姐。」

我不禁感到意外。

自我出生之后，无论做什么都从来没赢过爱夏。

不只是爱夏。我就算在学校里面也没有特别优秀。攻击魔术的模拟战胜率也大约只有四成五，就算很努力念了书，考试的平均分数也顶多是在八十分上下。

当然，我也根本就不是首席。

如果比赛的项目是我有学过，爱夏却没有学过的，确实有办法赢个一两次，但要是持续比个十几二十次的话，我就会完全赢不了她。

爱夏就是那么容易掌握诀窍，成长快速，也很擅长领悟事情的精髓。

而这样的她说自己输了......可是我却没有那么开心。

其实我在这件事上面没有努力，也没有打算要与她竞争。

我不是为了赢过爱夏才结婚的。

「嗳，诺伦姐。」

「怎么了？」

「结婚之后，我可以偶尔去找你吗？」

这句话也让我感到意外。

因为最近这阵子，我感觉爱夏好像有刻意要跟我拉开距离。

虽说在照顾哥哥的孩子时，是不会表现出那样的一面，但至少在我一个人的时候，不会没事就主动走过来或是找我搭话。

「嗯......当然可以。」

「如果小孩出生了，也要让我抱抱喔。」

「好。」

小孩......

我已经从希露菲姐那里听了这方面的事情。

尽管我觉得目前还太早了，但总有一天也会怀孕，而且我也做好了这样的心理准备。不过，在前一个阶段的心理建设做得更加充足就是了。

爱夏现在依然在照顾哥哥的小孩。

希露菲姐也说过爱夏帮了很多的忙。

仔细想想，一旦离开这个家，我就必须靠自己养育孩子。

关于这点也令人担心。我有办法做到吗......

如果是希露菲姐，想必会说诺伦一定没问题的，洛琪希姐的话就会跟我一起烦恼。艾莉丝姐姐八成会说随便养养就好了......但我还是很担心。

「应该说，关于养育小孩方面如果有什么不懂的事情，我也希望你能教我。」

「这个就包在我身上吧！」

「好......呵呵。」

我不禁笑了。

因为爱夏的笑容感觉很开心，我也跟着笑了。

那天，我跟爱夏就这样一直聊到深夜。

对话的内容也只是闲话家常，就是不断说些没办法得到结论的垃圾话。

然后到了隔天，我便带着行李搬到瑞杰路德先生家去了。

\\

★鲁迪乌斯★

\\

诺伦与瑞杰路德的婚礼办在斯佩路德族的村子。

是采斯佩路德族的方式举行。

满月之夜，村里的人们会个别带着料理前来参加，大家一边用餐一边祝福新郎新娘。

我虽然不是村人，但也理所当然地带了料理过来，名正言顺地带着家人一起参加。

因为我们是诺伦的家人，这点我绝不退让。

不过并没有人嫌弃我们，反而相当欢迎。

料理是由莉莉雅与爱夏制作的。

爱夏对诺伦要结婚的这件事其实抱着复杂的心情。

自诺伦的婚事敲定后，我偶尔会看到她躺在沙发上想着事情，然后遭到莉莉雅责备。

话说起来，爱夏在婚礼的几天前还跑到诺伦的房间，两个人一直聊到深夜。

尽管我不清楚对话的内容......但想必她也有许多自己的想法吧。

不管怎么样，爱夏也不可能不祝福自己的姐姐。

带来婚礼的料理也没有丝毫懈怠，反而是竭尽全力展现了她的厨艺。

她从米里斯及阿斯拉调度了材料，制作了一个巨大的水果蛋糕。

虽然我对斯佩路德族是否喜欢吃甜食打了个问号，但这点似乎已经由洛琪希打包票了。

不过，也有可能只是洛琪希自己喜欢吃甜食啦......

这好歹是诺伦人生当中的重要时刻，所以我们家人是全员参加。

不仅亚尔斯和齐格这么小的孩子，就连雷欧、次郎还有比特也一起带来了。

另外虽然不是家人，但促成这场婚事的奥尔斯帝德也同样被请到角落悄悄地参加。顺道一提，我也邀请了诺伦还留在魔法都市夏利亚的友人，请他们积极参加婚礼。

诺伦那群学生会的后辈一听到她要结婚，就说请务必让他们参加，甚至还低头拜托我。

于是，在到处都挤满了斯佩路德族的广场，可以看到有一群同样出席这场婚礼的人族正全身发抖，这个光景实在有点可怜......

但就算这样，大家在看见诺伦一脸幸福的样子之后，紧张感似乎也逐渐消失。在宴会进入高潮的时候，他们甚至还有余裕去向诺伦敬酒。

没错，诺伦看起来很幸福。

在家里，应该说在我面前经常会摆出臭脸的诺伦现在坐在瑞杰路德旁边，始终挂着害羞的笑容。

而且诺伦偶尔会看向瑞杰路德，瑞杰路德查觉到之后也转头望向诺伦，她这时总是会面红耳赤地低下头。

诺伦身穿斯佩路德族的女性缝制的传统新娘礼服，在五花八门的料理前面红着脸看着瑞杰路德，露出微笑。

而且很棒的一点是在婚礼途中也用惊喜的方式，融入了米里斯式的婚礼。

瑞杰路德与诺伦两人透过换装穿上纯白的礼服回到会场，此时作为神秘嘉宾的克里夫登场，为他们献上了米里斯式的祝福祷告。

最后，瑞杰路德单膝跪地，帮诺伦戴上了事前准备好的米里斯项链，诺伦满脸通红，用生硬的动作亲吻了瑞杰路德。

诺伦从头到尾都是一脸诧异，直到一连串的流程结束时才露出泫然欲泣的表情笑了出来。

那是无比幸福的笑脸。

如果这不是幸福，那什么才是幸福呢？

「诺伦姐真的好漂亮呢。」

爱夏看见这样的诺伦，称赞她很漂亮。

是因为礼服很适合所以漂亮吗？还是说她看起来幸福的模样很漂亮呢？

尽管不清楚是哪个，但爱夏看起来很羡慕诺伦。

「爱夏总有一天也会像那样的。」

「我不会啦。」

爱夏秒答。

看来她不打算结婚。

对我来说，不只是诺伦，也想要看到爱夏出嫁的那一天......

不过，结婚并非人生的全部，就这样待在家里也没什么不好。

「......」

不过话说回来，诺伦已经出嫁了啊。真是感慨呢。

在米里斯相遇的时候她还很小，也对我很有攻击性。在入学校就读后，也曾经把自己关在宿舍的房间。

诺伦当初给我的印象是个令人担心，做事不灵巧且笨拙的孩子，但不知不觉间加入了学生会，成为了出色的学生会长，受到许多后辈仰慕，并且在今天结婚。

「......嘶。」

想到这里，不禁鼻头一酸。

敬启，父亲保罗。

膝下诺伦已经成长为一个非常漂亮又优秀的孩子。祢在那个世界看着吗？当然正在看着吧。如果没有的话，请祢快点过来看看吧。

「哥哥，这种时候不要哭啦。」

「俺才没有哭咧。」

「咧什么啦......与其远远地看着，不如去跟诺伦姐说几句话吧。」

「嗯，嗯～」

现在整场宴会正处于高潮，出席婚礼的来宾正依序向新郎与新娘送上祝福的话语。

听说斯佩路德族的婚礼没有这样的习俗......或许是克里夫说了什么吧。

诺伦一边笑着一边问候着所有人。

那是一段幸福的时光。这种时候我过去真的好吗？

感觉就这样在远处守望着比较好。

「诺伦看到我会不会摆臭脸？」

「怎么可能啦。」

「是这样吗？」

「就是这样喔。」

「......爱夏可以陪我一起去吗？」

「大家一起去不就好了吗......」

也对，其实没有嘴上讲的那么需要担心。

真的要担心的反而是我。因为我绝对会哭出来。明明是诺伦重要的场合，我却会哭出来。

而且是哭得泣不成声，表现得很丢脸，大家都会指指点点，说诺伦的哥哥是个爱哭鬼。

不，这样是没关系，但我前阵子才被瑞杰路德说过要我别哭。所以我不是很想在这个场合落泪。

起码也要等到回家之后，把脸埋在希露菲的大腿上哭泣。

「知道啦，那我们走吧。」

不过，我非去不可。

我带着大家走到诺伦面前。

「啊。」

诺伦看见了我们后，有一瞬间抿紧了嘴唇。

尽管她立刻挂上了笑容，但她可能有什么话想说。

她要说什么，好可怕......当我在害怕时，希露菲已经走过我旁边，率先站在诺伦前面。

「诺伦，恭喜你结婚了。」

「谢谢你，希露菲姐。」

「虽说接下来的日子肯定会发生许多让你感到不安的事情，但基本上都能船到桥头自然直，有什么事的话记得要和瑞杰路德先生好好商量，要加油喔。」

「好的，我会加油的。」

希露菲这样说完，对诺伦露出微笑，接着便退到了旁边。

下一个站到前面的是艾莉丝。

「诺伦，恭喜你！」

「是，谢谢你，艾莉丝姐。」

「剑术的修行，不可以偷懒喔。虽然瑞杰路德很强，但总有一天会有必须要由你保护他的时候。」

「好的，我会铭记在心。」

语毕，艾莉丝一脸满足地点头，退到了旁边。

然后她走到瑞杰路德眼前，开始说了些什么。好像是在说「要是没好好保护诺伦，我可饶不了你」之类的。对艾莉丝来说，这件事才是重点吧。

此时，洛琪希从艾莉丝的旁边走到前面。

「诺伦，恭喜你。」

「谢谢你，洛琪希老师。」

「这种时候就不要叫我老师了......不，既然是最后了，我就说点像老师的话。异种族之间的婚姻，比起当事人，反而是周围的意见会比较多，但你不用在意。只要照往常那样去生活，总有一天大家都会认同你们的。」

「......是，老师！」

接着，莉莉雅与塞妮丝站了过去。

「诺伦大小姐，恭喜你。」

「莉莉雅小姐、妈妈......谢谢你们。」

「其实，我一直认为自己对诺伦大小姐而言是个令人不悦的存在。爱夏也三番两次害诺伦大小姐难过，这一切都是我的责任......」

「不，没有这种事情。莉莉雅小姐也是我的妈妈，爱夏也是我的妹妹，以前确实有发生过一些不愉快的事情，但那也不应该责怪莉莉雅小姐，就只是一些普通的小事而已。」

「......能听到您这么说，呜呜......呜呜......」

莉莉雅露出难以言喻的表情，接着立刻潸然泪下。

最近的莉莉雅真的很容易落泪呢。看着那样的莉莉雅，塞妮丝摸了摸她的头。

过了一会儿，塞妮丝缓缓移动到诺伦身边。

「妈妈？」

「......」

塞妮丝稍稍露出微笑，执起诺伦的手。

她用双手像是在包住重要的东西那般温柔地握着。

「妈......妈......妈妈......」

塞妮丝什么也没说。

但她的心意确实已经传达出去，诺伦的双眼顿时扑簌簌地地流下泪珠。

我立刻就明白她刚才的表情是在强忍泪水。

「妈妈，谢......谢谢你......呜，一......一直以来的......照顾......」

诺伦已经几乎说不出话。

轮到我的时候，诺伦脸上已经满是泪水与鼻水。

婚礼可是人生中重要的一刻啊......

「哥哥......」

总之我先从怀里拿出手帕，放到诺伦的鼻子上。

「来，先把鼻水擤出来吧。」

「我自己可以弄啦！」

诺伦将手帕抢了过去，用力地擤了鼻子。

她擤完之后一脸不知所措地看着手帕，我便收下它放回口袋收好。

然后重新面向诺伦。

「那个......诺伦......恭喜你。」

「哥哥......」

诺伦抿紧嘴巴，用严肃的表情抬头看着我。

该说什么才好呢？虽然我记得自己准备了一些话，但突然间全忘光了。

「哥哥，那个，谢谢你一直以来的照顾。我现在很幸福。不过之所以会这么幸福，一定都是多亏了哥哥。」

当我还在犹豫该说什么时，诺伦先开口了。

她说自己现在很幸福。这种事情我一看就知道了。

「不......这都是因为诺伦很努力。」

「努力的人并不是我。连这场婚事，也都是哥哥帮我打理了一切。」

「要是诺伦没有努力，瑞杰路德也不可能主动说要和你结婚的。」

瑞杰路德只会用战士或小孩来评断他人。

如果诺伦和以前没变依然是个小孩，这件事情肯定不会发生。

「但是，我还是认为这都多亏了哥哥。真的，很谢谢你。」

眼见诺伦又差点哭了出来，我再次从口袋拿出手帕，这才注意到手帕还是湿的。这时，突然有人从旁边递出手帕。

是爱夏。

我把手帕接了过来，替诺伦擦去眼泪。

「诺伦。」

「是。」

「那个，我没办法表达得很好，而且重要的事情大家也都说完了，我能说的其实不多。」

「嗯。」

「今后虽然也会遇上辛苦的事情，或是令你难受的事情......但你要加油喔，那个，以后也要永远幸福下去。」

不可思议的是我没有流下泪水。

我本来以为自己绝对会哭出来，刚才也是泪眼汪汪的，但话说出口的时候，眼泪也顿时收了回去。

我现在只是抱着骄傲的心情，站在诺伦眼前。

「......好的！」

随后，诺伦也停止了哭泣，笑容满面地重重点头。

\\

★　★　★

\\

就这样，诺伦结婚了。

瑞杰路德和诺伦，尽管这一对无论身高还是年龄都有很大的差距，但他们意外地契合，一年之后就生下了小孩。

脸长得很像诺伦，有着绿色的头发及可爱的尾巴，额头上有颗宝石，是斯佩路德族的女孩子。

这孩子被取名为「瑞雪莉亚•斯佩路迪亚」。

听到这个名字时，奥尔斯帝德露出了很可怕的表情。

但那张恐怖无比的表情其实是笑容。看到那个足以令全身竖起寒毛的笑容后，我才会意过来。

那个名字一定与他的回忆中一致吧。

** 露西和爸爸
*** 「露西的开学当天　前篇」

时光流逝。

艾莉丝与洛琪希的孩子平安出生了。

两个都是女孩子。

洛琪希的女儿取名为莉莉，艾莉丝的女儿则是取名为克莉丝蒂娜。

于是我们有了四个女儿、两个儿子，家里也开始变小了。或许应该也要考虑增建这个家，规划一下家庭计划。

另外，露西已经七岁了。

说到七岁，就是小学一年级。

小学这种地方，就是让同世代的孩子们一起共同生活，学习生活所需的基础知识。

当然，知识只要由父母教导就行。

在学校最重要的关键字，就是集体生活。

人们是群居动物。大部分的人都无法一个人生存下去。互相支援、彼此合作，有的时候会发生争执，但还是会解决纷争一起生活下去。虽说也有人拥有足以独自生活下去的强悍，但这种人是少之又少。

学校同时也是教导如何结识朋友以及伙伴，并且学习如何与他们相处与吵架的地方。

然而，在这个拉诺亚王国没有小学这种设施。因为没有义务教育，这也是理所当然的。

一般人普遍认为学校这种地方只要想去的人去就行了。

但是，我还是认为孩子应该要去上学。

虽说我前世的教育水准只有高中辍学，不过在这个世界从学校获得了各方面的知识。与札诺巴变成好友，与克里夫相遇，遇见了巴迪冈迪、七星还有艾丽儿......还与希露菲结了婚。

我现在之所以会有如此丰富的人际关系，毫无疑问是去拉诺亚魔法大学上学之后建立起来的。

所以，我认为应该要去上学，应该要送露西去上学。

于是我在去年的家庭会议提出这件事，获得了过半数成员的赞成。

赞成去上学的是希露菲、洛琪希还有莉莉雅。

艾莉丝虽然说「不用去也无所谓」，但也没有强烈地反对。

如此这般，决定要让我们家的小孩从七岁开始进入拉诺亚魔法大学就读了。

尽管入学的并非只有同世代的小孩，但是在那里学到的东西，我认为势必会对孩子的将来派上用场。

然后，今天是露西第一天上学。

接下来七年，假如留级的话就会更久，这是她漫长学校生活的第一天。

「露西，有没有忘记东西？」

「没有！」

露西身上穿着有些宽松的学校制服，背着与体型相较之下稍大的背包，站在玄关前面。

身上所有东西全都是新买的。

背包里面装的是初学者用的魔杖、长袍、魔术课本甚至还有便当盒，全都是新的。露西或许是因为全身上下都是新品，她透过穿衣镜看着自己，不断地傻笑。

可能是因为这样，她回应得稍稍有些敷衍。

算了，反正昨天晚上也确认过好几次了，而且要带的东西也不是那么多。

应该没问题吧。

不过，还有那个，我想说她会不会忘了那个，稍微提醒她一下应该可以吧？

「手帕带了吗？」

「在口袋里面！」

「笔记用具呢？」

「在背包里面！」

「便当呢？」

「在背包里面！」

「那出门时要给爸爸的亲亲呢？」

「不可以！」

不可以！怎么可能......不应该是这样的......

不对。

呃，还有什么来着？容易忘记的东西......比如说将来的梦想，或者希望，还是真理之类......？

「鲁迪，不要紧啦。」

正当我思考到一半，希露菲拍拍了我的背。

「露西也已经长大了，没问题的。」

长大了。她确实是长大了。已经七岁了。七岁的话，已经有很多事情可以一个人完成。

一个人也○得到！[fn:1]

「爸爸，不要紧的！我会加油的！」

露西握紧了拳头，同时这样说道。

她的举动实在既坚强又惹人怜爱，也让我非常不安。如果我是绑架犯，看到这么可爱的孩子肯定会马上掳走。没错，虽说露西长大了，但她还很小。

「露西，不可以跟着不认识的人走喔。」

「知道！」

「如果对方要来硬的把你带走，要大声喊出自己的名字喔，知道吗？」

「知道！」

「万一嘴巴被堵住了，或者是被威胁说再吵就杀了你，就把爸爸给你的信让那个人念出来，可以吗？」

「可以！」

顺带一提，那封信上写着我对绑架犯的请求。

上面写着我是某某大人物的部下，与哪些人有着密切关系之类的事情，还写到万一伤了露西一根寒毛会有什么后果。

尽管对方也有可能看不懂文字，但我已经事先跟奴隶商人打点过了，要是有人敢掳走我们家的孩子，我希望能给对方尝尝什么叫社会性的私刑教育。

敢掳走我女儿的罪犯，同时也会受到犯罪社会体制内的制裁。

然而就算这样，内心依然有种不安的感觉挥之不去。

无法预测的事情不计其数。我真的很担心露西会不会被卷入那样的风波，担心得不能自己。

「露西，如果在学校里被同学欺负了，要跟老师说喔。」

「好。」

「虽然我觉得不会有这种事，但如果被老师欺负了，就跟蓝妈妈或是副校长说喔。他们两人都在教职员办公室。」

「好。」

「若是觉得没办法告诉蓝妈妈或是副校长，就找白妈妈、红妈妈、爱夏姑姑、莉莉雅奶奶、艾莉娜丽洁婆婆......总之就是要找人商量。当然还可以找爸爸或爸爸的朋友，千万不要一个人憋在心里喔。」

「好～」

「然后，如果你觉得其他孩子被欺负的话......」

说到一半，我的后颈就被抓住，把我拉向了后面。

我转头望去，发现希露菲正摆出可怕的表情。至于露西，看起来则是有点无精打采。

「爸爸，我不要紧的喔......？」

露西抬头望着我，有点不安地这样说道。

我是不是吓到她了呢？是不是应该多告诉她一些学园生活开心有趣的地方呢？比方说要努力交到一百个朋友之类的？

不过这件事至关重要。

所谓的霸凌，有时甚至会陷入一种谁都不愿意帮我的心情，但肯帮助自己的人其实就在身边。

「鲁迪，你要多信任露西。」

「............好。」

不过也对。

就是为了提高孩子的自主性才让她上学的。

不能认为什么事情都要由我来解决。

总有一天露西也会长大成人，到时她就会离开家里自立门户。

当然，那还是好久好久以后的事情，但就是为了让她到时候能自己一个人生活下去，所以才让她去上学的。

没错，这是家人一起决定的。

「露西，跟大家说你要出门了。」

「我出门了！」

露西这样说完，把门打开后精神饱满地从家里飞奔而出。

我向那样的露西说了路上小心，目送她离开。

「......」

送行的有我、希露菲、艾莉丝、雷欧以及莉莉雅与塞妮丝。

洛琪希已经去学校上班了。

爱夏因为佣兵团那边出了点问题，一大早就先出门了。

其他的孩子们都还在睡。

「我去练空挥了。」

「那么，我去洗衣服。」

「那我去扫地吧。」

大家各自有事而纷纷离开，剩下我一个还盯着门。

雷欧也和我在一起。我们心里肯定想着一样的事。

好担心啊。

说不定露西现在已经迷路了。虽然她已经和希露菲及洛琪希一起走过好几次前往学校的路，但今天是一个人，真令人担心。

或许还是不该让七岁的孩子一个人走在路上。

不应该让那么可爱的孩子一个人走在路上。

应该要让好几个精悍的保镖跟着她才对。

比方说，有着绿色头发，手持白色的长枪，喜欢小孩子的家伙。

然后，就是上课。

希露菲、艾莉丝以及洛琪希都对露西实施了英才教育。

所以她不至于跟不上课程，但反而有可能因为进度超前太多，而导致她在班上变得很突兀。

她并不是特别生。

吉纳斯副校长有主动提过这件事，但我认为还是要好好累积普通的经验，所以让她以一般学生的身分入学。而且也有乖乖参加了考试，分数相当不错。

我不晓得这么做的结果究竟是好是坏。

内心也很担忧自己这样是把露西当作实验对象看待。

「雷欧。」

「汪。」

雷欧用叫声回应了我的呼唤后抬起了头，仿佛在表示无须多言。

不愧是我们家的守护神。这就是所谓的心照不宣。

我们之间不需要言语。

「鲁迪！不可以喔！」

当我把手放在玄关的门上，希露菲就从后面扯高嗓音如此说道。

我回过头，发现希露菲双手叉腰，露出可怕的表情站在那里。

「我们昨天不是已经说好，要暂时什么都不做，在旁边守护她吗！」

「不，不是啦，是雷欧说想要去散步啦。」

我才刚讲完，便发现雷欧转过去往走廊移动，溜到了小孩子的房间。

这家伙竟然背叛我。

它虽然会保护孩子们不受外敌侵扰，但是在我受妻子责备时却不愿保护我。

「听好了，鲁迪。」

我僵在原地不动，希露菲依然双手叉腰，叹了口气。

「我之前也说过了，我觉得自己是因为了离开鲁迪才有办法成长。鲁迪教了我魔术，也教了我该怎么念书，我以这个经验为基础，学习到了各种事情。不管是鲁迪不在之后，还是因为转移事件而到了爱丽儿大人那边之后。」

「嗯。」

「我觉得教导各种事情，好好保护露西确实是很重要。可是，只是一味给予是不行的。若是不自己发现，不是自己去了解的话，这样无论过了多久都没办法自己站起来往前迈进。」

我一直很期待着今天。

我本打算作为露西的监护人陪她一起去学校，向老师拜托说「我家的孩子就麻烦你照顾了」，带着露西参观学校。

为了这件事，我还特地选在今天休假。

我拜托奥尔斯帝德让我休息，所以才空出了一天。

但是希露菲从昨天就像刚才那样主张。

她说绝对不准我跟着过去，要让露西自己一个人上学。

这就是她的主张。

「所以，我们现在就静静地在旁守护她，好不好？就算有什么事情失败了，也肯定对露西有帮助的。」

「......好。」

我接受了。

希露菲这七年来一直在旁守望着露西，扶养她长大。

既然她都如此自信地把露西送出家门，我就应该要尊重她的想法。

不能什么事情都由我帮她处理好。

嗯，我也知道是我自己担心过头。

露西是个坚强的孩子。她不仅很照顾弟弟妹妹，也很坦率，我听说她还受到附近孩子们的仰慕。说不定会比我更简单地融入学校生活。

那么我要做的事情只有一件。

就是祈祷露西能够享受学校里面的生活。

我的神就在学校，这个祈祷想必能够实现吧。

「......那么，我去奥尔斯帝德大人那里一趟。」

「嗯，我知道了，如果发生什么事情就交给我吧。」

......不过，还是会觉得寂寞。

我这样心想，朝向奥尔斯帝德的事务所移动。

\\

这是一个小时之前的事情。

「发生了像这样的事情。」

「......」

「确实像希露菲说的那样。不管是我还是希露菲，都是离开父母身边之后才开始成长。这点毋庸置疑。」

现在我正在发牢骚。

我已经接受了。既然希露菲这样决定，我也打算乖乖听从。

所幸我在魔法大学有许多熟人，危险也很少。

归功于诺伦积极地推动学生会的活动，听说治安也变得相当好。

爱夏所率领的鲁德佣兵团也逐渐壮大起来，整个城市的治安也好上了许多。

不过，我还是很担心。因为有种说不出来的郁闷感。

「不过啊，露西才七岁而已。明明还那么小，却让她一个人去上学实在......不，我记得我去艾莉丝家当家庭教师的时候也是七岁，五岁的时候已经在村子里到处散步了......可是，至少应该让我送露西去上学吧。奥尔斯帝德大人，您觉得呢？」

「......」

奥尔斯帝德露出可怕的表情。

那个表情是在表示：这件事与工作有关吗？

我说不定搞错了商量的对象。仔细想想，奥尔斯帝德是我的上司。不应该对他发这种牢骚。

如果是与人神相关的话题，像这样发牢骚应该也是没问题的。

不过再怎么说，还是不应该把家里的事情带到职场来讲。

奥尔斯帝德也是，就算听到这些话，他也不知道该怎么回答我吧。

毕竟露西不存在于奥尔斯帝德所知道的历史当中......

但不知为什么，我觉得奥尔斯帝德一定会了解我的心情。

了解我现在这个坐立难安的心情！

「......」

想着想着，奥尔斯帝德就站了起来。

看起来充满了压迫感。

当然，我与奥尔斯帝德已经相处了很长一段时间。

我知道他不会因为这么一点小事就生气。

他完全没有生气。要是让奥尔斯帝德生气的话可是很不得了的。

「你真是愚蠢。」

奇怪？生气了？他没有生气吧？

看起来像是在生气一样。好奇怪，他生气了耶。

「......用这个吧。」

奥尔斯帝德递给我一顶黑色的头盔。

那是具有减轻诅咒效果的备用头盔。

「......」

他要我用这个做什么？

\\

「你不是担心女儿，纯粹只是想看看她对吧？」

「！」

原来如此，我懂了！

我只是想去看看，而不是担不担心露西。不，当然也有这样的想法就是了。总之我只是想看看露西在教室里自我介绍、在老师提出问题时迅速举手回答、在图书馆为了拿书而踮起脚尖的样子。

魔法大学没有家长参观日。

我以前也很想看诺伦上课的情况，但就是看不到。所以至少想看看露西上课的样子。

这样的心情最为强烈！

「可......可是，如果我跑去看，希露菲一定会生气的。」

「......」

我这样说完，奥尔斯帝德默默地脱下了自己的外衣。

然后将它披在我的肩上。简直就像是在说「这个也拿去用」。

刚才的头盔也好，这件衣服也好，他到底要我做什么？

「那个，这是？」

「不需要由你过去。」

奥尔斯帝德大人，我不明白您在说什么。请再说得浅显易懂一点，让愚蠢的我也能听懂啊。我明明想去却不能去。这种机智问答请交给一休和尚吧。[fn:2]

「......嗯？」

不对，等等，也就是这么一回事吗？

鲁迪乌斯禁止过这条桥。[fn:3]

既然这样，只要过桥的人不是鲁迪乌斯就好了。

所谓的地位就是来自衣服。

只要衣服改变，地位也会随之改变。

一旦地位改变，人也会改变。

我的话就是身穿老鼠色的长袍，地位是奥尔斯帝德的左右手。

可是，假如我戴上黑色头盔，穿上白色外衣的话呢？

「......」

于是我戴上头盔，披上外衣。

头盔有点重，外衣厚实，穿起来很暖和。要是长时间穿在身上，肩膀一定会僵硬的。

不过那种事情根本无关紧要。

我站在镜子前面。

「这就是，我......」

映在镜子上面的那副身影，毫无疑问就是......龙神奥尔斯帝德！

没错，只要将黑色头盔与白色外衣穿在身上，连我也能成为龙神奥尔斯帝德！

既然我去会被骂，只要由奥尔斯帝德去就行了！

万事解决！

「......」

......不，再怎么看也不一样。

和奥尔斯帝德完全不像。

不仅身高不同，肩宽也不一样。基本上，从整体的氛围来看就完全不行了。没有奥尔斯帝德浑身散发出来的那种非比寻常的强者氛围。映在镜子里的那个家伙，不管怎么看都是山寨版奥尔斯帝德。

明眼人一看，立刻就会认出这家伙是冒牌货。

「嗯......这个，肯定会被发现吧？」

「只要不知道是你就行了。」

说得也是。

也对，就是这样。不是奥尔斯帝德也没关系。

只要不是我就行了。这样的话，老实说只需要头盔就好了吧。

不愧是奥尔斯帝德大人，头脑真的很好。

「奥尔斯帝德大人。」

「......」

「非常感谢您。」

「嗯。」

奥尔斯帝德露出伤脑筋的样子，重新坐回椅子上。

看来他打算整理一些文件。说不定我碍到他了。

毕竟我原本今天是休假的。

「那么，我出发了。」

我用奥尔斯帝德的打扮跑出了会议室。

不能再继续磨蹭下去了，立刻赶去魔法大学吧。

\\

我以龙神的打扮离开了事务所。

外面的天气真的很好。

是个很适合露西第一天上学的晴天。

然后，或许是因为穿成这样，莫名有种变强的感觉。这就是所谓的狐假虎威吗？如果是现在的我，感觉用一根小指头就能轻松地解决掉北神。

「奥尔斯帝德大人，您要出门吗？」

「......！」

就在我这样想时，有人从事务所的角落唐突地向我搭话。

望过去一看，那里站着一个手持大剑的少年。

亚历山大•雷白克。北神卡尔曼三世。

他该不会听到我刚才的心声了吧？

不，事情不是这样的。虽然我觉得能解决他，可是该怎么说呢，这种感觉就像是看过拳击电影后就感觉自己也变强了一样。只是对着从天花板垂吊下来的电灯绳子做着挥拳练习而已，也就是所谓的云玩家，就是这样。

「奥尔斯帝德大人，您今天打算去哪里吗？要我陪您一起去吗？」

「......？」

一瞬间，我还以为他在开我玩笑。

但是亚历的眼神无比清澈，声音也非常真诚。

「啊，前几天谢谢您的指导。想不到北神流的四足之型竟然有着那样的优点......实在没想到奥尔斯帝德大人对北神流竟然也如此透彻。这让我领悟到自己还远远不够成熟。回想起在毕黑利尔王国时的自己，我都要羞愧得在地上打滚了。」

难道这家伙没发现我不是奥尔斯帝德吗？

不，怎么可能。最近亚历无时无刻都会待在奥尔斯帝德身边。住的地方甚至是事务所地下的其中一间。他现在的立场就好比是奥尔斯帝德的看门狗。

看门狗要是认错主人的话可是很糟糕的吧？

「你没发现吗？」

「怎么了吗？」

不，既然他是北神流，这也可能是在欺骗我。

这是死神的幻惑剑。困惑对手的技术。

「老实说吧。你已经知道了吧？」

我这样说完，亚历的表情顿时愣住，随即切换成认真的神色，将手抵在下巴。

接着他歪了歪脖子，皱起眉头。好像可以看见空中好像浮了个问号。

这张脸，看来他是真心不懂啊。艾莉丝偶尔也会这样。如果是演技的话真的很厉害。

「非常抱歉。毕竟我非常迟钝，不晓得是什么事情。」

「......真的吗？有什么地方跟平常不一样吧。」

「是指细微的部分吗？非常抱歉，我是不太注意小细节的那种类型，所以也没办法回避陷阱，虽然知道这样很不好，但这种地方似乎是天生的......」

甚至还找借口了。他是真的不知道吗？

不仅身高不一样，体格不一样，连嗓音也不是很像，基本上声色就不一样吧。

诅咒也是，虽然已经减轻了，但应该还是会让人涌起不快感......

骗人的吧？咦？真的假的？

「......事务所的社长室里有正确答案。」

「原来如此，我知道了！」

亚历这样说完，得意洋洋地往事务所里面走了进去。

在毕黑利尔王国对战时，应该是更加敏锐的家伙，他是怎么了啊？

难道他平常总是这种调调吗？

说得也是。像我在战斗时和其他时候的集中力也不同。应该就是那样吧。

话虽如此，把那家伙放在奥尔斯帝德身边好吗？稍微不安起来了......

算了，现在比起那种事，重要的是露西。

从亚历的反应来看，起码证明了远远看过去不会发现我就是鲁迪乌斯。

这样的话想必没问题吧。

\\

★　★　★

\\

亚历山大走进事务所后，与柜台的法莉亚斯缇雅对上了眼。

她看到亚历山大后，一瞬间犹豫有件事不知道该不该问，最后还是开了口。

「那个，亚历山大大人。」

「法莉亚小姐，怎么了？我现在正要去社长室确认什么是『正确答案』，请长话短说。」

「刚才鲁迪乌斯大人打扮成奥尔斯帝德大人的样子出去了......请问那是在做什么呢？」

听完这句话后，亚历山大露出真的吓到了的表情。

「咦......鲁迪乌斯大人打扮成奥尔斯帝德大人的样子......？」

亚历山大从没想过这种事。

因为如果是自己的话，就会害怕到根本不敢模仿那个奥尔斯帝德的打扮。

同时，他咽了口口水。

鲁迪乌斯为什么要扮成奥尔斯帝德的样子？

这个理由连想也不用想。

他一定是打算去做乔装成奥尔斯帝德之后才能做的事情。

恐怕是当诱饵之类的。

扮成奥尔斯帝德来引诱敌人，借此绊住他们。

趁着这段期间，由奥尔斯帝德达成某个目的。

这样的话，他们要面对的就是非得由奥尔斯帝德出马才能应付的强大敌人。

还没见过的列强，是技神？还是说，是让亚历山大留下痛苦回忆的死神蓝道夫？难不成是杀死魔神的三英雄其中一人，甲龙王佩尔基乌斯？还是北神卡尔曼二世，亚历山大的父亲亚历克斯？

不管是谁都是鲁迪乌斯一个人无法应付的对手。

尽管只要穿上那套魔导铠就能与之一战，但这样就失去担任诱饵的用意了。

亚历山大也晓得鲁迪乌斯有多么勇敢。

他无所畏惧。

亚历山大理解他的战斗力比自己还要低，但他在毕黑利尔王国让自己见识到的动作仍是历历在目。他会靠着一股傻劲面对比自己还要强大的存在。

亚历山大已经很清楚那是什么了。

就是勇气。

鲁迪乌斯是阿托菲拉托菲所承认的勇者。

然后亚历山大注意到了。

这就是正确答案。

「法莉亚小姐，这件事还请你保密。」

「好......好的......」

尽管法莉亚斯缇雅歪头的幅度慢慢上升，但亚历山大并没有在意，而是把手放在通往社长室的门上。

但愿奥尔斯帝德能赐我与勇者一同战斗的荣誉。

他内心如此盼望。

没过几分钟后，亚历便从奥尔斯帝德口中听说了所谓的「正确答案」。

*** 「露西的开学当天　后篇」

我走在路上。

尽可能地选择行人较少的道路。

即使如此，还是会感觉到自己受到注目，想必是因为我现在这身变装吧。

这肯定是错觉。

大众应该不会对自己以外的人那么感兴趣。不对，感觉确实有许多人在看着这边。

这也是当然的。

因为奥尔斯帝德在这个城镇的郊外成立事务所之后已经过了一段时间。

尽管看过这身打扮的人不多，但已经有不少人听说过特征。

黑色的头盔、白色的外衣。我现在这身打扮，正是奥尔斯帝德的象征。

穿成这样走在路上，自然会引起关注。

不如说现在是没有诅咒的状态，反而有可能给人们留下好印象。

如果是这样，干脆走大路看看吧。像之前自称Dead
End的时候一样，试着做些好事看看能不能提升形象也不错。况且要去学校的话走大路也比较近。

「嗯，这主意不错。」

这就是所谓的一箭双雕。

奥尔斯帝德的评价变好的话，对我来说也有加分效果。

对了，下次就提议办个让大家穿着黑色头盔与白色外衣，开心跳舞的祭典好了，名字就叫「龙神祭」。

我这样心想，迈出脚步走向大路。

「呜喔！」

就在这个瞬间，我转身躲进右边的遮蔽物后面。

因为有个眼熟的红头发身影出现在大路上。也可以看到红头发身影带着一只白色大型犬。顺带一提，狗的背上有两个小孩子。

是艾莉丝和雷欧。

骑在雷欧身上的是菈菈跟亚尔斯。

雷欧那家伙，明明我刚才要带它散步时先溜了，现在竟然和艾莉丝一起散步。

不对，其实我也不是要散步。那只是伪装成散步的自我满足行为。艾莉丝与雷欧正在领地上巡逻。那才是真正的散步。

不过这下麻烦了。

想不到会在这种地方遇到艾莉丝，不对，如果是艾莉丝，说不定能用我的三寸不烂之舌骗过去。

没错，就让我们两个一起去看露西吧。

「......」

不过这身打扮要怎么解释？

她应该不会突然就砍过来吧？

而且我也担心孩子们。毕竟我现在明显就是在做坏事，打破了与希露菲的约定。能让孩子们看到这种可悲的样子吗？

不。

......仔细想想，这么做还是不太好。

竟然还不惜这样变装。果然还是回去比较好。

虽说我一时鬼迷心窍来到了这里，但在家乖乖待着，与希露菲一起等着露西回来再迎接她，难道不是最好的做法吗？

............唉，可是我还是很想参与露西人生的重要时刻。

我知道这只是在任性。

但是，这和希露菲说的不一样。

绝不是因为我不信任露西才会做出这种事。

我不是为了在暗地里偷偷帮助露西才做这种事。

我保证。向神明发誓。就算露西差点哭出来，我也不会当场就出手帮她。

而是等露西回家以后告诉我这件事，我才会帮助她，教导她。

听好了，鲁迪乌斯同学。这就是底线。不会破坏与希露菲承诺的底线。

虽然我现在没有与希露菲商量就自作主张，但只要遵守这点，我也不会打破与希露菲之间的承诺。

即使如此，等事情结束之后，我也会好好地坦承一切，跟她道歉。

就说我其实因为太想看露西上课的情形，就跑去看了。

跟她说对不起，我没办法忍住这样。

可以吧？办得到吧？你可以老实地被骂吧？嗯！可以！很好──乖孩子，鲁迪乌斯。

「汪！汪！」

唔，看来雷欧已经发现我了。

它抽动着鼻子，望向我这边。

「什么啦，你怎么了？」

艾莉丝也注意到了。

虽说被发现也不会困扰，不过要解释为何会穿成这样会拖一段时间。要是被拦住也很麻烦。现在就先绕过他们吧。

「躲在那里的家伙，给我出来！」

当我这么想时已经太迟了，艾莉丝也发现我了。

因为我的打扮实在太引人注目......

好啦，该怎么办？要出去吗，还是不出去呢？假设出去好了，我该怎么说明？

不，可是，嗯。距离还很远。如果远远看过来应该不会穿帮。

「......」

我只探出上半身。

艾莉丝的手放在腰间的剑上，雷欧则是摇着尾巴。

而且我还和坐在雷欧身上的菈菈，以及抱着菈菈坐着的亚尔斯对上了视线。

两人用茫然的表情看着我。多么纯真的眼神。

「奥尔斯帝德......？」

艾莉丝露出疑惑的表情，将手从剑上移开，我见状后顿时转身。

装得若无其事，就像是在路上突然看到那样。

「......等一下。」

「唔......！」

艾莉丝把我叫住。穿帮了吗？

她好歹也是剑王。是个能与前剑神战得不分轩轾的强者。

该不会只是看了动作，她就能一眼看出我不是奥尔斯帝德吧？

「不，是错觉吧，算了，我们走吧，雷欧。」

然而，当我停下来后她随即这样说道，转身掉头走去。

雷欧虽然一直偷偷地看着我，但没有朝我这边追来，而是跟着艾莉丝离开。

作战成功了。

「......」

突然，我与坐在雷欧背上的菈菈与亚尔斯对上了眼。

菈菈一脸茫然，亚尔斯则是有点愣住。他们坐在雷欧的背上看着我。在他们两人的目送下，我离开了现场。

\\

抵达了学校。

我避开正门，翻过围墙侵入学园。

然后，就这样朝着学校的教室前进。

虽说我不太常上课，但好歹也有认真来了学校几年，知道一年级上课的教室在哪里。

我避开了在学校中庭上课的学生以及空堂时间到处移动的学生目光，直驱一年级的教室。

这里也没什么变呢。

虽然距离我毕业之后也还没过上几十年，但我真心这样觉得。

只不过，不熟悉的学生变多了。不知道是不是错觉，比起我还在学的时候，增加了许多长耳族精灵、兽族和小人族这类种族，魔族好像也不少。

吃饭的时候有从洛琪希那里听说，主要的原因好像是最近学生会的主要成员当中增加了长耳族与小人族的族长血亲。

人族以外的种族得到了更强的发言力与立场，其结果就是来自各国的其他种族入学率随之增加。

这是爱丽儿当学生会长时没办法看到的景象。

其他种族虽然增加，却没有因此变得过于趾高气昂，想必也是诺伦担任学生会长的时期所留下的影响。

基本上她不会容许别人有种族歧视。

而这点也形成了学校现在的风气。

魔法三大国的部分贵族虽然对此颇有微词，但就我个人来说倒是十分骄傲。

我想着这些事情走在走廊，就在经过转角时突然......

「唔。」

「啊。」

正好与从转角另一边来的人物撞上。

那名人物带着五名学生。

不，与其说是带着，给人的感觉更像是被他们死缠着不放。

用纠缠这种讲法虽然会有点令人讨厌的感觉，简而言之就是那个人很受学生欢迎，所以才会陪她走在一起。从学生们手上拿着笔记本这点来看，似乎是在请教上课时不懂的地方吧。

这样的举动值得赞许。

没错，只要问那个人，她什么都会愿意回答。

而且，从那个人口中说出来的话是真理。虽说有的时候会搞错啦，但包含搞错的部分在内也是真理。你们现在正在接受启示啊。这是觉醒Liberation。那个人所说的话比任何事物都能响彻心扉，意义非凡，还能化为自身的力量。各位学生啊，你们现在必须诚挚地聆听她所说的话语，仔细思考其中的意义，活用在自己的人生。各位学生啊，你们现在非常幸福。

「............奥尔斯帝德？」

那位人物有些惺忪的眼神闪过一丝疑惑后，抬头看着我。

几秒钟后，她睁开了双眼。

「不对，是鲁迪？你是鲁迪吧，是鲁迪没错吧？」

不愧是洛琪希。

我无法骗过那双慧眼。

「......为什么会知道是我？」

即使如此，我还是要问。

因为愚蠢的我忍不住想要知道真相。

我明白的。洛琪希冰雪聪明，无须任何理由便能找出真相。

「当然知道啊，在这个城镇有勇气打扮成那样模仿奥尔斯帝德的人，肯定只有鲁迪了。」

原来是有理由的。不愧是洛琪希！

「奥尔斯帝德大人知道这件事吗？」

「嗯，这姑且是奥尔斯帝德大人的提案。」

「原来如此......那么，这么做是有意义的对吧。」

洛琪希点了点头，目不转睛地看着我的打扮。

感觉她好像以正面的方向误会了我的目的。

「......」

不过，这样真的好吗？我要欺骗洛琪希吗？为了我一时的任性，就要欺骗洛琪希吗？

这样好吗？鲁迪乌斯啊，这样真的好吗？

「不，其实没什么意义。」

当然不好了。我不可能对洛琪希说谎。

不对，虽说在重要的场合对洛琪希说谎也是不得已的，但这件事不一样。

要是现在说谎，下一个瞬间大约二十年后的未来的我就会飞过来，直接赏我一发岩砲弹Stone
Cannon。再不然，就是我在这个瞬间将失去自我认同，从手脚开始不断溶化，堕落成不定型的存在吧。

「那么，你为什么打扮成这样？」

「那个......就是想来看看露西......」

「......看露西？你不是和希露菲约好了吗？」

「我不会在暗地里帮助露西，或是对她过度保护，只是那个，就纯粹地......想看看她上课时是什么样子......」

我语无伦次地这样说着，洛琪希一直抬头盯着我看。

那是责怪的眼神。周围的学生也因为事出突然而感到困惑。

对不起，对不起。

「......我知道了。」

然而，洛琪希忽然移开了视线。

「如果你不会出手帮忙，而是好好在旁守护她，我可以视而不见，当作是奥尔斯帝德大人来学校视察。」

「老师......！」

「只有这次喔。」

「那当然。回去后，我也会向希露菲道歉的。」

「那样才对。」

得到原谅了。我在洛琪希面前已经抬不起头了。

从此之后要向洛琪希所在的方位跪拜三次，一天五次。

「那么，我在下堂课之前都必须要教这些孩子......顺带一提，你知道露西的教室在哪吗？」

「是，那当然。」

「那么，先这样。」

洛琪希这样说完，我又再次握紧了拳头，朝着走廊走去。

学生们纷纷讨论「刚刚那个是谁啊！」同时追着洛琪希移动。

真是受欢迎。这也是当然的。毕竟她是我的老师。

「好。」

我重新打起精神，在走廊上移动。

\\

★　★　★

\\

抵达了教室。

我从走廊的方向往教室偷看，但突然想到在走廊果然还是不太妙，便绕到了外面。

毕竟要是传出了奥尔斯帝德在学校偷窥的流言，可是会关系到我们公司的命运啊。

我如此心想，为了让周围的人看不到我，在靠近教室的窗户做了个屏风，随后从窗户......

「......咦？其实我直接以视察的名义，在旁边参观教学也可以吧？」

因为洛琪希也原谅我了。

感觉只要取得许可，进入教室直接看就好了。如果向吉纳斯副校长说明原因，他应该会帮我安排得很像那么一回事的，真是失策。

算了，总之现在只要能看见露西我就满足了。

我这样心想，打开了千里眼观察着教室。

教室的桌椅排列整齐，看起来像是一年级的学生们在里面排排坐好。

大部分都是超过十五岁的大人。

尽管有少数看起来只有十岁上下，但几乎没有七岁左右的孩子。

看起来七岁的孩子几乎也都是小人族。

有一般的人类、魔族、长耳族、小人族以及兽族。

有的人长相善良，有的人一脸和气，有的人看起来很调皮，种类五花八门。

坐在教室后面的大概是冒险者吧，感觉很凶。

露西会不会被那种人缠上，遭到他们欺负呢？

不对，再怎么说他们也不可能欺负七岁的孩子。

话说露西在哪里呢......啊，找到了，她坐在最前面的座位。

不愧是我的女儿。竟然坐在最前面，真是有干劲。

我虽然这样想，但问题似乎在于桌子对露西来说太大，很难看到前面。

尽管她一脸认真地听老师讲课，写着笔记，但桌子的高度让她有点吃力。

明天开始或许最好让她带个座垫或什么的来学校。

坐在旁边的是约莫十岁的少女。

或许是小人族吧。不对，感觉应该是人族。头发整理得很整齐，从这点来看可能是贵族。

她偶尔会找露西说话，看着自己的魔术课本。

她似乎不了解做笔记的这种文化。

露西很认真地指向她的魔术课本，好像在说着什么。

声音太小了，听得不是很清楚，但说不定是在教些什么。

她这么快就交到年纪相仿的朋友了吗？已经成为朋友了？

或许是因为才第一天上课，老师似乎也没打算认真教课。从板书的内容来看，充其量只是从魔术的基础中的基础开始。对露西来说是她好几年前就已经走过的路。想必很轻松吧。

「老师！」

才刚这样想，露西就举手了。

「怎么了？」

「我听说总魔力量不是一辈子都一样，只要从小时候开始用魔术就会增加，老师好像讲错了！」

学校教的内容与希露菲和洛琪希那里教给她的有些差异。

但是露西啊，有时候最好别这么主张自己的想法。

被学生指出自己的想法有问题时，不会有几个老师会觉得舒坦的。

「你的名字是？」

「露西。露西•格雷拉特。」

\\

「格雷拉特......那么，你是洛琪希老师家里的女儿吗？」

「是！」

「原来如此，你似乎从小就接受英才教育啊。」

教师的眼睛闪闪发光。

虽然我觉得没这个可能，但这个教师该不会要在这里诋毁洛琪希吧？

他应该不会在女儿面前诋毁她的母亲吧？

我今天已经下定决心要忍耐了。话是这样说，但从明天开始或许就不是这样。你从明晚开始可能都会走在危险区域喔。

「确实，有部分人士提出了这样的说法。我记得你的父亲还有母亲可能都是这样的人。再来，你父亲的弟子，茱丽叶特小姐说不定也是这样。但目前这种说法还不能确定是否属实。也许是因为你的父亲、母亲还有茱丽叶特小姐都是特别的存在。这套法则也有可能不适用在魔族与兽族身上。再不然，也有可能是你的父亲及洛琪希老师误会了。毕竟目前还没经过完整的验证，我本身也没有参与这项研究。因此，我教导的是『总魔力量是一辈子都相同的』。因为我自己就是这样。」

教师滔滔不绝地说出自己的想法。

像是在讲给露西听的，也很像是讲给自己听的。

露西摆出很认真的表情听着这番话。

「各位同学也仔细听好了。今后各位将要学习各式各样的知识。有魔术，还有魔术以外的事情。无论是就学期间或是从学校毕业之后，想必都会不断地学习。在学校的期间，我们身为魔术师的前辈会教导你们各式各样的知识。各位可以相信我们的教导，也可以不相信。认为一件事是错误的，也可以去证明那是错的。一旦成功证明了自己的理论，这次就轮到各位来教导我们。要让我们接受那真的是正确的。」

没错没错。

看来他的思考十分灵活，似乎不是什么坏老师。

应该说可能是个好老师。

「就是这样，露西同学，还有什么问题吗？」

「没有了！谢谢老师。」

「好，那请坐吧，我们继续上课。」

教师莞尔一笑，请露西坐下。

下一刻，周围开始拍手。

露西露出错愕的表情转过头，随后面红耳赤地低下了头。

很好喔露西。你现在说了很正确的话。

姑且不论是不是真的，觉得正确的人们都在纷纷帮你拍手。

所以你就挺起胸膛吧。

才刚这样想，旁边的孩子就摸了摸露西的头，然后说了些什么。

下一刻露西就抬起头，露出腼腆的微笑。

嗯嗯，要跟我家的孩子好好相处喔。

要吵架也没关系，好好相处喔。

\\

后来我看了一阵子露西上课的模样。

有好的老师，也有不好的老师。

但露西不会害怕问问题，而是直接请教师解开她的疑惑。

有些教师会回答，有些教师会岔开话题，有时会指出露西问题当中的错误，继续上课。

露西相当引人注目。

七岁的少女如此积极地参与上课是很罕见的事。

午休吃便当的时候，露西身边围绕了一群人，到了傍晚露西已经成为班上的风云人物。

他们围着露西，提出各式各样的问题。

有人询问双亲，有人询问家人，有人询问她住在哪里，有人询问关于露西的事。

简直就是个人气王。

其中想必也有人知道她是我女儿，想借故巴结。

但这样也没关系。人的相遇都是难得的缘分，就算起初是为了自己考量，但最终还是会产生各种不同的结局。

人生还很长，最好也要让露西有一些与坏孩子打交道的经验。

「呼。」

最后一堂课结束了。

我也满足了。露西第一天就适应了学校生活。

当然，我并不担心。毕竟露西是希露菲的女儿，洛琪希与艾莉丝也与她一起好好教育了露西。没有任何不安的要素。

不，这个嘛，还是有不安的要素，因为她是我的女儿。

开学第一天就坐到角落，成天装睡来度过学校生活，这种状况也并非完全不可能。

不对，实际上并有没发生这种事。

接下来的日子或许也会有辛苦的时候，但一定没问题的。

再来就是每天去学校，在晚餐时听露西说着在学校经历的快乐回忆就行了。

想必我会回忆起今天发生的种种，笑咪咪地吃着美味的米饭吧。

好啦，回去吧。

总之，先把外衣和头盔还给奥尔斯帝德。

我这样心想，用魔术解除了化为屏风的土壁Earth Wall。

「......啊。」

土壁的另一边，站着一名女性。

白色的头发、苗条的体态，穿着容易活动的裤子与无袖的上衣。

从肩膀延伸出来的白皙手臂扠在腰间，生气地板起一张脸。

是希露菲。

「嗯咳......有事吗？」

我努力装出奥尔斯帝德的声音。

「鲁迪，你为什么在这里？」

当然是徒劳无功。

「不，那个......希露菲叶特小姐为什么会在这里？」

「菈菈说在散步途中看见了爸爸，还说他把脸遮起来，穿得很奇怪。」

「噢......原来如此啊。」

是雷欧吗？雷欧那家伙竟然背叛我。毕竟那家伙不是用眼睛，而是用鼻子确认是我。

再不然就是我身上虽然也混了奥尔斯帝德的味道，但只要雷欧认出我了，菈菈自然也会发现。

毕竟我听说雷欧与菈菈可以心灵相通。

难怪菈菈一直盯着我。

「......竟然还打扮成这个样子。」

希露菲的肩膀都在颤抖了。

这是在生气吧。希露菲生起气是很可怕的。

我无法具体解释到底是哪里可怕。虽然无法解释，但希露菲生气、心情不好时多半都是我的错，所以在家里也会有各种责备的视线朝我飞来。

那样会很难受。

而且，说不定会有一周左右我晚上都得一个人寂寞地入睡。

「你就那么不相信我跟露西吗？」

希露菲的眼睛流下了泪水。

不妙，这个状况很不妙。这比生气还要不妙。

总之我当场跪坐，向希露菲解释。

「不，不是，不是的，我只是想看露西的英姿而已。只是想看露西在上课时勇敢地向老师发问，认真向学的样子。我，就是，那个，因为我没什么参与到露西成长的重要时刻嘛。」

我语无伦次地回答后，希露菲一边哭着一边看着我。

「真的吗？」

「真的，我只是因为没办法忍耐才这么做，所以原本就打算一切都结束后也把这次的事告诉你的。」

「............那是骗我的吧？」

「是真的，我本来就打算道歉了。」

「你这么想看露西上课吗？」

「对。」

我这样说完，希露菲伸出手，协助我站了起来。

也停止哭泣了。

「那么，其实是我不对呢。因为鲁迪明明那么想看，我却禁止你这么做。」

「不，希露菲没有错。毕竟我当时也同意了。」

「嗯............啊。」

我们聊到一半，希露菲的视线突然往上看了过去。

她露出「糟糕了」的表情。我回头望去，立刻知道了理由。

「啊──......」

不知不觉间，学生们都从教室的窗户看着我们。

其中当然也有露西的身影。

露西用有点生气的表情，看着我和希露菲。

\\

★　★　★

\\

「那个，今天啊，我和一个叫贝琳达的女孩成为好朋友了喔。」

结果，我、希露菲还有露西三个人感情要好地回家。

我们握着露西的手，三个人并排走在回家的路上。

我以为露西应该会因为我跑去学校而生我的气，但没有这回事。

好像是因为第一次上学发生了许多快乐的事情，她逐一向我们说明。

「贝琳达听说是拉诺亚王国大臣的女儿喔。她说自己虽然很小却很聪明，所以才能进去学校就读。说要成为学校最厉害的，让爸爸刮目相看。」

「哦，真厉害呢。」

「还有，一开始上的是蓝妈妈的课喔。蓝妈妈一开始被大家小看，害我也气得脸都鼓起来了，可是蓝妈妈她秀了一点魔术之后，大家就安静下来了，蓝妈妈说『不过，听不听我的课是你们的自由』！真的好帅喔！」

「这些话等晚餐的时候再跟蓝妈妈说吧，她一定会很高兴的。」

虽然与计划中不同，但这样其实也不坏。

我握着露西的手，与希露菲走在一起。

尽管在道路上横着一列走路并非好事，但不用在意，这里是我的城镇。

「露西，在学校开心吗？」

「嗯！」

露西非常开心地点了头。

看到她的反应，我不禁心想，根本不用为她担心。

「那个，爸爸，露西没问题对吧？」

简直就像是看穿了我的思考那样，露西如此说道。

「是啊，你没问题呢，很了不起喔。」

「不愧是爸爸的女儿吧？」

「啊哈哈，你比爸爸厉害多了。」

露西真是了不起。不管从哪个角度来看都很出色，根本不需要监护人陪伴。

相较之下，爸爸呢？问题可大了。需要监护人陪在身边。

「话说回来，鲁迪。」

希露菲忽然用手指指向我。

「嗯？」

「你要维持那个打扮到什么时候？」

我不禁看了看自己的样子。

有点厚度的白色外衣、黑色头盔，我现在依然是假奥尔斯帝德。

「明天会还的。」

呃，嗯。明天再还应该没问题吧。毕竟奥尔斯帝德也没说今天就要还回去，看起来也不急。话又说回来，这件外衣的质感真好......

感觉起来很类似红龙皮的触感，问问爱夏或许会知道吧。

「......话说回来，露西。」

就在我想东想西时，脑海中突然浮现一个疑问。

就是想说姑且确认一下好了的那种很小的疑问。

「怎么了～爸爸？」

「考考你，爸爸的头发是什么颜色呢？」

当然，这个问题并不是我不相信露西，而是为了以防万一。

「褐色的！」

「答对了，露西真聪明啊。看来将来值得期待呢，不愧是我的女儿。」

「讨厌啦～不要把我当笨蛋嘛～」

眼见露西有点闹起脾气，我笑了笑，幸福地踏上归途。

「不过鲁迪，你打破了约定，要让你忍耐三天喔。」

「是。」

尽管得稍微忍耐一下，但没关系，因为我很幸福。

\\

隔天。

镇上到处流传着奇怪的流言。

那就是奥尔斯帝德盯上了露西。

不过，想必是因为我打扮成那样走在路上吧。

俗话说流言不过七十五天。除了我以外，希露菲和我们家里所有人也都知道这件事毫无根据，所以就放着不管了。

我这样心想，带着外衣去还的时候，奥尔斯帝德用可怕的表情瞪了过来，为了辩解这件事害我费了一番工夫......不过那又是另外一段故事了。

*** 「露西的家人」

我的名字是露西•格雷拉特。

是格雷拉特家的长女。

我有许多家人。

三个妈妈。

三个妹妹。

三个弟弟。

两个奶奶。

两个姑姑。

三只宠物。

总共是十三人又三只，非常多。

\\

先从妈妈开始介绍吧。

妈妈有三个人，有白头发的妈妈，蓝头发的妈妈还有红头发的妈妈。

白头发的妈妈是把我生下来的妈妈，也是爸爸的第一个老婆。

爸爸说她是三个妈妈中最年轻的，也是最爱撒娇的。

白头发的妈妈讲话很唠叨，平时总是这样对我说：

「交朋友是很重要的喔。还有，绝对不能欺负弱小。」

白头发的妈妈叮嘱我珍惜朋友的重要性。

蓝头发的妈妈是菈菈的妈妈，是爸爸的第二位老婆。

爸爸说她虽然在三个妈妈中看起来最年幼，但其实是最年长，也最可靠的。

蓝头发的妈妈虽然个性比较沉默，但有时也会对我说：

「要随心所欲地活着，如果有不懂的事情就找人问吧。」

蓝头发的妈妈虽然没有向我叮嘱过什么，但她什么都知道，只要问问题，她什么都会告诉我。

红头发的妈妈是亚尔斯的妈妈，是爸爸的第三位老婆。

爸爸说她虽然在三个妈妈中看起来最年长，但其实是最小的。

红头发的妈妈不太会说话，但也常常对我说：

「保护别人是很重要的。为了办到这点就必须变强才行。」

红头发的妈妈这样说着，锻炼了我。

我打算遵守三个妈妈的教诲。

要交朋友，并为了保护那个朋友而变强。可是绝对不会欺负弱小。然后，伤脑筋的话就要问蓝妈妈该怎么做。只要这样做就肯定没错，而且也会被夸奖。爸爸也会表扬我说：

「露西真聪明，不愧是姐姐。」

\\

妹妹和弟弟有六个人。

最大的妹妹菈菈是个很温柔的孩子。

和蓝妈妈有着同样的发色，把长长的头发绑成一条辫子。

菈菈是个不可思议的孩子，常常会和金发的奶奶和宠物比特说话。

奶奶和比特都不能说话，只有菈菈可以跟他们对话。

她就是这样的一个孩子，可能是因为一直在发呆，去广场游玩的时候，常常会有附近的小孩拉她的辫子欺负她。

虽然我马上救了她，但她的表情却没有那么讨厌，让我有点失落。

菈菈最喜欢睡午觉。常常坐在雷欧的背上，一脸舒服地睡着觉。

\\

最大的弟弟亚尔斯是个勇敢的男孩子。

和红妈妈有着同样的发色，剪得又短又整齐。

虽然是个小大人又调皮，不过总是会保护我和菈菈。我想他一定和我一样，遵守着妈妈的教诲吧。红妈妈对他的期待很高，最近他每天都在跑步或是练习空挥。

他和爱夏姑姑感情很好，和姑姑在一起时他总是很高兴。

\\

最小的弟弟齐格是个很爱哭的男孩子。

他总是摇摇晃晃地跟在亚尔斯的后面，如果被丢下的话就会哭。

每次看到我就会凶亚尔斯。然后亚尔斯就会牵着齐格的手，让他坐在雷欧的背上。

菈菈会在齐格要爬上雷欧的时候向后退一点，把他拉上来坐到前面。然后为了避免齐格掉下去而从后面抱紧他，自己舒服地睡着。

还有，其实只有我知道，齐格的力量很惊人。因为他能轻松举起非常重的箱子。

\\

还有一个弟弟叫克莱夫。

他和亚尔斯同年，但不是真正的弟弟。

他是白妈妈的奶奶生的孩子。妈妈说好像是类似堂兄弟那样。

虽然不知道应该怎样叫他，但我把他当作弟弟看待。

他常常来我家玩，感觉和亚尔斯处得很好。

他好像也喜欢我，会常常抱过来，如果摸摸他的头，他总是会笑得一脸害羞。

\\

最小的两个妹妹是莉莉和克莉丝蒂娜，她们才刚出生。

因为还很小，我不太了解她们。但她们肯定都是好孩子。

我是这群兄弟姐妹中的姐姐。

因为是姐姐，必须要可靠一点，这句话妈妈们说了好几遍。我想要照着她们说的去做。因为弟弟妹妹们都很可爱，我想要保护大家。

\\

奶奶也有两个人。

金发的奶奶是爸爸的妈妈，名字叫塞妮丝。

虽然是个很漂亮的人，但她不会说话，就算跟她说话也不会回应。

她总是在发呆，多半都会和比特一起待在庭院。可是当我难过或是生气的时候，她不知为何都会来摸我的头，是个不可思议的奶奶。

\\

褐发的奶奶是爱夏姑姑的妈妈，名字叫莉莉雅。

原本好像是服侍爷爷家的女仆，她的举止简直就像个女仆一样。

虽然三个妈妈都很看重这个奶奶，但以前我不明白为什么褐发的奶奶是我的奶奶。

以前，路边有个陌生人说「女仆只是下贱之辈，用下巴去使唤她们就行了」，我也试着这样做，结果刚好在附近的红头发妈妈对我大发雷霆。把我的屁股打到整个变红，然后要我一个晚上都在外面反省，就把我扔到家外面了。

当我和宠物雷欧依偎在一起发抖的时候，褐发的奶奶让我进了家里。

奶奶在那时候告诉了我为什么会被这样处罚。

我在那个时候才知道，褐发的奶奶虽然是女仆，但她是我的奶奶，不可以用下巴使唤她。

\\

姑姑也有两个人。

不管哪一个都很年轻，所以如果叫姑姑的话她们会生气。姑姑虽然是姑姑。但对我来说她们的存在就像姐姐一样。

大姑姑是金发奶奶的女儿，爸爸的妹妹，名字叫诺伦。

她总是非常努力，经常会陪我一起玩，教会了我很多东西。

我非常喜欢这个姑姑。

也想着将来要成为像这个姑姑一样的人。

不久前她出嫁了，现在不在家里，偶尔才会回家。

不过，一回来就经常和小姑姑吵架。

虽然她们看起来关系不太好，但有时候也会一边吵架一边笑着，看起来很开心的样子。

\\

小姑姑是褐发奶奶的女儿，是爸爸同父异母的妹妹，名字叫爱夏。

她和褐发的奶奶一样总是穿着女仆装，掌管着家里的事。

我在家里想做什么的时候，来照顾我的基本上都是这个姑姑。

无论是煮饭还是洗衣服，她什么都教了我。

妈妈说，爱夏姑姑是个无所不能的人，非常优秀。她好像也有在帮忙爸爸的工作。

可是，她偶尔会惹褐发的奶奶生气，真是不可思议。

\\

宠物有三只。

白色的大狗是雷欧，它是这个家的守护魔兽。

雷欧非常聪明，也理解我们说的话。

感觉它一直在守护着整个家族，爸爸也说过，如果出了什么事就要依赖雷欧。

它很喜欢菈菈，在家的时候就会黏着她。

\\

犰狳次郎是蓝妈妈的交通工具。

个性很胆小，要是责备它，它立刻就会把肚子露出来，不然就是缩得像颗球一样。

可是，如果在我们出去时发生了什么事情，它也会发出低吼威吓对方。

它在用自己的方式保护我们。

\\

魔木比特是爱夏姑姑种的菜园的守护神。

它是植物型的魔物，所以完全不知道它在想什么，但常常会和金发的奶奶或是菈菈在一起。

它对想要扰乱菜园作物的对象毫不留情，爸爸最喜欢吃的东西是「米」，小鸟之类的经常会想把那个的果实吃掉。比特会把它们抓起来，变成自己的养分。

虽然有点可怕，但它从来没袭击过我们家人。

不仅如此，若是我们靠近的话就会帮忙把门打开，还会给我们树果。它也是家人。

\\

十三人与三只。

我有许多家人。

有很多妈妈、妹妹还有弟弟。

可是，爸爸是一个。

只有一个人。

我最喜欢爸爸了。

在还没懂事之前，我好像会避开爸爸，但现在最喜欢他了。

爸爸的气味让人很安心。

虽然有时胡子蹭起来痛痛的，但这样也很喜欢。

爸爸不怎么让我摸他的胡子。

偶尔会有胡子长得很长的时候，如果我想去摸他的胡子，他就会温柔地拉着我的手，说「对不起，我现在就去剃掉」然后往浴室走去。

我是觉得不用这样，但爸爸也有他自己的想法吧。

虽然不愿意让我摸他的胡子让我觉得可惜，但我不会因为这种事就讨厌爸爸。

不过，我想爸爸对我并没有抱有太大的期望。

虽然不知道为什么，但就是这么觉得。我觉得爸爸虽然会担心我，也很爱我，却不对我抱有期望。

这肯定是因为爸爸是很厉害的人。

嗯。虽然我不是很清楚，但也大概知道爸爸是个很厉害的人。

爸爸在我这个年纪的时候，早就学会了圣级魔术。别说是去上学，他甚至已经在负责教人。

五岁之后，我会到镇上或是公园游玩，向各种不同的人说早安问好，但那些人全都认识爸爸，而且很尊敬他。

尤其是那种特别伟大的人，就更会称赞爸爸。

妈妈们也很厉害，我虽然是个小孩，但也知道爸爸是与众不同的。

就是因为爸爸这么厉害，所以才会对我......不对，是对我们不抱有期望，我觉得这也是没办法的。

可是，我想被爸爸夸奖。

我会遵守妈妈们的教诲，也会保护弟弟妹妹们。这样的话，妈妈们就会不断夸奖我。

可是，我也想要被爸爸夸奖。

我已经七岁了。

从今天开始要去上学。那是大人也会去上的学校，是白妈妈、蓝妈妈还有爸爸上过的学校。

红妈妈虽然没去上过，但听说有时候也会以老师的身分去指导剑术。

你不会有问题的。只要好好照着以前教给你的去做就可以了。虽然蓝妈妈这样说，但我还是有点不安。

那个地方有很多大人。我能顺利适应那种地方吗？能交到朋友吗？

虽然会期待，但更加不安。

可是，只要在那里好好加油，爸爸一定也会夸奖我的。

「露西真了不起，不愧是我的女儿。」像这样夸奖我。

然后，他一定也会对我抱有期望。

所以，我想以那个为目标来努力。

** 阿斯拉七骑士物语
*** 「婚活的伊佐露缇　前篇」

很久之前。

那是在还没有水神流这个流派的时候。

某个国家遭到名为海龙王的存在所威胁。

他们因为在海龙王的领地捕鱼，惹怒了海龙王。

结果，每天都会有渔船被袭击，海龙也会在港口都市出没。

尽管骑士团奋起对抗，但有着巨大的身体，同时又能在海里自在活动的海龙十分强大，导致国家快速地凋敝。

这已经变成王国存亡的危机。

国王相当重视这个事态，对外宣布若是有人讨伐了海龙王，便能迎娶他的女儿，并授予王位。

听到这个消息，许多骑士、勇者、英雄都纷纷向海龙王发起挑战，然后遭到击败。

这时出现的，是在腰间挂着一把破旧的剑，衣物破烂的一个男人。

虽然近年来由于穿凿附会，都把他形容为一名花美男，但根据实际的传说，他绝对算不上是一名美男子，据说他的脸因为污垢而发黑，相貌就如同流浪者。

那个人自称列达尔。

列达尔落落大方地朝着国王走去，如此说道：

我直接打倒它也没问题吧？

国王理所当然地点了头。毕竟他已经半放弃这件事，同时也认为这个脏兮兮的男人不可能干得了什么大事。

但是，列达尔很强。

他将一整面海冻住，阻止了海龙们的行动，转眼间就逼近了海龙王。

海龙王将冰击碎，痛苦得翻腾的同时，袭向列达尔。

列达尔用那把破旧的剑架开海龙王必杀的一击，并加以反击将它的头击落。

后来，他带着海龙王的首级回去。

国家将其视为英雄迎接......本该是这样的。

国王给了列达尔能玩乐一辈子的财宝。

不过，也只有这样。

眼看就要把王位和女儿给这个脏兮兮的男人时，国王反悔了。

列达尔没有发怒。

但是，他陷入了深深的悲伤之中。

因为他喜欢公主。

公主总是在游行与典礼之类的活动当中出现在民众面前，列达尔深深爱着一直以来只能在远处望着的她。

他转念一想，既然与公主的婚事无法实现，那么自己就离开这个国家吧。

只要他认真起来，明明就有可能靠着实力让自己成为国王。

然而，有人代替列达尔对此事大发雷霆。

那个人正是公主。

公主训斥国王，打了他，将他踢飞，随后从城里飞奔而出。

然后，她追上了想离开这个国家的列达尔，抱住他的膝盖如此说道：

「我舍弃了祖国，已经不再是公主，也没有了姓氏。即使你得到了我，不仅无法得到这个国家，也没办法成为国王。倘若这样你也无所谓的话，就请娶我为妻吧。」

列达尔莞尔一笑，抱起了公主，就这样离开了王国。

两人结为夫妻，不知消失到什么地方去了。

几十年后。

据说在世界的某处诞生了名为水神流的流派。

\\

为了效法这个逸话，诞生了「水神的伴侣必须舍弃自家」的规矩。

\\

★　★　★

\\

伊佐露缇•克尔埃尔。

她是阿斯拉王国的水神流负责人，也是阿斯拉王国骑士团的剑术指导之一。

虽然现在是水帝，但前阵子已经习得了水神流五大奥义中的其中三个，几个月后就会举行水神袭名的仪式，是即将成为水神的人物。到时候，想必世人将会称她为水神列妲。

年龄不详。

外表看起来像二十几岁。

有着一头带点蓝色的美丽黑发，以及凛然的相貌。

无论看在谁的眼里都是个美女，但根据一部分的传闻，说是因为她装年轻才会有这样的成果。

在阿斯拉王国，知道她年龄的只有爱丽儿一个人。

然后，这样的她，现在正卯足全力进行着婚活。

由于当上了水神，漫长的修行日子也到此告一段落。

尽管之后她也会继续锻炼，但既然到了这个人生阶段，也是时候认真寻找结婚对象了。

然而，她的婚活始终没有进展。

当然，她并非没有对象。

毕竟她是即将成为水神的人物，许多人对她兴致勃勃。

比方说，同为水神流的剑士们。被伊佐露缇的美貌所吸引，看到她真挚地不断修炼的模样，被她打动的男人也不在少数。

话虽如此，他们也是剑士。

是梦想以剑术扬名立万的一群人。

没几个人拥有迎娶比自己更强的女人为妻的度量。

对伊佐露缇来说也是。若是剑士，最好与自己有着同样水准，不然起码也要有王级实力，所以她不断地挑选着对象。

比方说，阿斯拉的贵族。

水神流的女剑士在阿斯拉王国本就很受欢迎。

个性被动的水神流女剑士与剑神流的女性不同，不会过度主张自己，举止柔和，端庄贤淑，但也有挑衅的一面，确实有着自己的主见。

而且伊佐露缇也懂得阿斯拉王国宫廷的礼仪规矩。

既年轻漂亮，个性又好，又尊重男方。

再加上她还是个本事出众的女剑士。自然会有人想娶这样的人为妻，让她在早上随侍在侧，晚上则是在床上翻云覆雨。

有许多阿斯拉贵族都有这种想法。

当然，以这种变态的趣味为目的，露出下流的笑容接近的对象，伊佐露缇当然是敬谢不敏。

但是偶尔也会遇到一些人，让她觉得「这个人好像也不错」。

长相俊俏，个性不错，家境也很好。

而且剑术也有一定程度。像这种帅哥会把自己的变态嗜好巧妙地隐藏起来，露出洁白的牙齿笑着接近她。

是王子殿下。

面对这样的对象，伊佐露缇会轻易陷入情网。

虽然周围的人都说「那家伙在私底下干些很渣的事情，劝你不要」，但伊佐露缇依然会陷进去。

因为那些王子殿下的长相与态度相当不错。只要表面上光鲜亮丽，伊佐露缇便会轻易陷入情网。

这个人好像也不错嘛──这样。

但即使是那样的王子殿下，只要伊佐露缇提出一个条件就会轻易拒绝她结婚的请求。

「我总有一天会成为水神，自称水神列妲•莉亚。一旦与我结婚，就必须舍弃自家。因为水神的伴侣是不能持有姓氏的。」

这是水神的规定。

不遵守这件事不会有任何损失，遵守了也不会有任何回报。

然而这是代代水神都持续遵守的规定。前任水神列妲，也就是伊佐露缇的祖母也遵守了这个规定。

伊佐露缇的爸爸也没有姓氏。克尔埃尔是母亲那边的姓。

因此，尊敬着祖母的伊佐露缇也打算继续遵守下去。

但可惜的是，用花言巧语蒙骗伊佐露缇的王子殿下也同样是贵族。

作为贵族而生，作为贵族而活。他们是靠着门第活到今天。

就算对伊佐露缇再怎么有好感，也没有一个人即使舍弃家族也要与她结婚。

伊佐露缇烦恼着。

婚活已经开始了几年。

尽管会发展到不错的关系，但总是在最后的阶段绊倒。

再这样下去，会不会直到袭名水神之前都还没办法结婚呢......

她有着自信，不仅打扮仪容非常得体，也很擅长煮饭，化妆同样是轻而易举。

就连肌肤与头发也都会每天保养。

她认为自己的话术也很了得。在水神流的训练中也包含学习对话技巧。那是借由激怒对手，让对方率先攻击的话术。只要加以应用，将对方捧上天，就能轻易让对方眉开眼笑。

即使是这样，她也努力了。

可是，她却没办法结婚。就连那个艾莉丝还有妮娜都做得到的事，自己却做不到。

当然，她们有青梅竹马。结婚时也没有特殊的规定。

可是，伊佐露缇认为那部分能靠自己的魅力来弥补。

虽然她也觉得自己挑三拣四，但还是认为总有一天应该能找到理想的对象。因为，她已经做出了努力。

「这样是第几个了？」

「..................第二十一个。」

但是她被二十一个人甩了。

假如加上她甩掉的对象，想必会更多吧。

「这样啊。」

现在，伊佐露缇在自家的客厅，面对着自己的兄长。

自家就邻接着道场。

伊佐露缇的哥哥丹托里斯•克尔埃尔是水神流的上级剑士。

他虽然是克尔埃尔家的长兄，但才能与妹妹相比并没有特别出众。

尽管努力到头破血流，到头来他的才能也只能止步于上级。

但是，他是个很正直的男人。

祖母列妲喃喃发着牢骚说「不如给你圣级吧」的时候，他一口回绝，说「我不需要与自身实力不符的名号」。

所以列妲还健在时，就把道场的经营交给他管理。

另外，也包括伊佐露缇的将来。

「你是不是期望太高了？」

「不会，应该没有那种事......」

「你有才能，也有地位，我认为你有选择适合对象的权利，但过于挑三拣四，导致没有候补的话，就没有意义了。」

「我明白。」

伊佐露缇从以前就在哥哥面前抬不起头。

两人的双亲很早就去世了。

所幸还有身为水神的祖母在，并不会因为生活所苦，但祖母很忙，几乎没什么时间照顾他们两人。

在那时，是由丹托里斯代替双亲照顾着伊佐露缇。

他代替双亲支持伊佐露缇，扶养她长大。

所谓剑术道场是讲究实力的世界。拥有才能的伊佐露缇在十岁前便已超越了哥哥。

但基于这样的背景，她至今依然无法在哥哥面前抬起头。

「你无须考虑克尔埃尔家的面子。既然要作为水神生活下去，将来势必会有残酷的命运等着你。既非容貌也非家世，去找一个你可以打从心底接受的对象吧。」

「......」

丹托里斯已经结婚了，也有了孩子。

当然，伊佐露缇也见过，曾经说过话。不过，她不怎么喜欢兄长的对象。

那个人是阿斯拉王国贵族的千金。

是某个贵族为了和水神列妲结缘，两人才会结婚。她明显看不起丹托里斯，也不了解剑术。甚至从来没在道场出现过。

尽管生了小孩，但与丹托里斯几乎处于分居状态。

不想和这样的对象结婚。正因为这样想，伊佐露缇才会慎重地挑选对象。

......不过，也只是会因为长相和态度就轻易妥协的程度。

即使这样，还是附了剑术至少在中级以上的条件。

她不打算拘泥于家世。但成为了剑术指导后，护卫爱丽儿的机会增多，导致有机会交谈的也只剩下那类对象。

其实不管是贫穷的贵族还是平民，甚至是冒险者之类的也无所谓。

只要有能弥补这一点的特质就行了。

「我并不认为自己挑三拣四。」

「那么，应该也可以选我帮你安排的对象吧？」

「不，我认为自己的对象应该要自己寻找。」

然后，她执拗且顽固。

当然，有部分也是因为丹托里斯推荐的对象尽是一些丑男......

嘴上说着不会挑三拣四，但自己的条件也绝不让步。

这样根本就不可能结婚。

「这样啊......」

对丹托里斯来说，他也不想为此苛责妹妹。

因为这也不是水神身边第一次没有伴侣。自己已经留下了克尔埃尔的血脉。不过，他希望见证妹妹顺利获得幸福，而且既然妹妹想透过结婚变得幸福，内心自然会想支持她的决定。

话是这样说，既然妹妹没有寻求协助，丹托里斯也不打算多管闲事。

因为他虽然没有才能，好歹也是学习水神流剑术的习武之人。

「话说，伊佐露缇，今天陛下不是传唤你过去吗？」

「......对。」

「时间没问题吗？」

「还有时间。」

「即使是万一，也不能让陛下久候。今天我们先说到这，你快去吧。」

「好的，兄长。我出门了。」

伊佐露缇这样说完行了一礼后，返回了自己的房间。她等等整理好服装仪容，应该就会前往王城了吧。

目送她离开后，丹托里斯叹了口气。

「呼......」

再这样下去，伊佐露缇在袭名水神之前是不可能结婚的吧。

丹托里斯在这样想着的同时，为了训练年轻人而朝着道场的方向走去。

\\

伊佐露缇走在阿斯拉王城银之宫里面。

白银胸甲绘有持盾的女武神徽章，随着步伐发出响声。蓝白色的外衣随风飘舞，移动时鞋子也喀喀作响。

看到在王城里行走的她，巡逻的士兵都直立不动，立起长枪。他们眼神当中缀有憧憬的色彩。水帝伊佐露缇的名字在阿斯拉王城无人不晓。同时，对她那凛然的姿态抱有憧憬的士兵也不在少数。

顺带一提，没几个人知道她脑中想的是「不想当剩女」或是「有没有好男人掉在路边呢」。

「这不是伊佐露缇小姐吗？你打算上哪去呢？」

挡在她面前的，是一名男性。

他身材瘦弱，既不高，头发又少，是个整体看起来很软弱的男人。

年纪大概是四十出头吧。

他是人族。如果鲁迪乌斯见到这样的外貌，说不定会觉得「他可能是窗边族」。

怎么看也不像是骑士或剑士，但他也穿着与伊佐露缇身上那套很相像的白银胸甲。

只是，那套铠甲的图案和伊佐露缇的不同。

那是头戴城墙形金冠祈祷着的少女的徽章。

「这不是伊弗利特卿吗？别来无恙。」

「啊，免了免了。我们是同级别的，不需要下跪......」

希尔贝斯托•伊弗利特。

是阿斯拉七骑士之一「王之城墙」。

他有着与此名号不符的外貌，是负责阿斯拉王城银之宫警备任务的最高负责人。

伊佐露缇仅是一介骑士。

骑士虽然是下级，但也与贵族相当。

但是，希尔贝斯托是城内骑士、士兵当中最高的级别，而且他还是中级贵族。

如果是一般情况下，伊佐露缇必须靠到走廊的角落，在他离开前都屈膝低头才行。

「可是......」

「我们是女王陛下的骑士。」

听到这句唐突且尖锐的话语，伊佐露缇立即挺直了腰杆。

「这样就行了。我们并不是为了国家，而是为了陛下工作。要屈膝的对象，只有女王陛下一人。」

面对希尔贝斯托发出的惊人气场，伊佐露缇点了点头。

希尔贝斯托是个小兵。

他体弱多病。剑术绝算不上好，魔术也是一样。

尽管如此，他依然是在王国的骑士学校以次席毕业的男人。

他熟知如何培育人才，并加以运用。是真正理解了人尽其位、位得其人这个道理的男人。为了这唯一的一项才能，爱丽儿特地把原本待在阿斯拉王国农村的一隅隐居的他叫回本国，让他担任自己的骑士。

「话说，伊佐露缇小姐要去哪？」

「我收到陛下的传唤。」

「喔喔，这样啊，那么你也没时间在这种地方被我这样的人耽搁了。」

「请问，有什么要事吗？」

「没什么，并不是什么大不了的事。犬子希望我介绍伊佐露缇小姐给他，不好意思，如果你时间允许的话，希望能听我那个笨儿子的请求见他一面，我只是想告诉你这件事。」

对伊佐露缇来说，这件事令她相当感兴趣。她很想仔细听听关于那个被称作笨儿子的犬子是什么样的人。

但是说实话，现在主君正传唤着自己。

「明白了。那么，这件事等下次有时间再详谈吧。」

伊佐露缇露出凛然的表情如此说道，便赶紧移动了。

\\

愈是走向王城的深处，人就愈少。

穿着简易铠甲的士兵变少，身穿高价铠甲的骑士变多。

尽管只是与下级贵族相当的骑士，但他们也是发誓效忠爱丽儿的人。

这些骑士背叛的可能性极低。

然后，往最深处走去，人影变得更少。

四周已经看不见士兵与骑士，无人的走廊一直往前延伸。

偶尔会与动作十分灵敏的女仆──近卫侍女擦肩而过，但也仅此而已。

这些近卫侍女们也同样直属于爱丽儿。背叛的可能性比骑士们更低。

然后，她来到了爱丽儿所在的「王之间」。

\\

在那豪华的门前，站着一个男人。

身穿黄金铠甲，拿着巨大战斧的一名巨汉就站在那里。

那个人是阿斯拉王国最强的门卫。

他没有一丝一毫背叛爱丽儿的可能。

他隶属于阿斯拉王国的黄金骑士团，也是阿斯拉七骑士之一。

「王之门卫」杜加。

他的黄金头盔有着犹如将水桶倒过来放的外形，上面绘有在门前站着的女武神的徽章。

「伊佐露缇•克尔埃尔。在此报到。」

「......哦。」

杜加听伊佐露缇自报姓名之后，缓慢地动了。

尽管动作看起来十分笨重。但伊佐露缇看出他的动作并没有任何破绽。

他知道这个杜加在紧要关头会以可怕的速度挥动战斧。

然后，她也察觉到假设杜加认真起来，自己是没办法突破这个男人到达门后的。

「......嗯？」

这样的杜加，向着伊佐露缇伸出了手。

伊佐露缇见状，眉毛不禁抽动了一下。

杜加的长相朴素。虽然并不粗俗，但并非伊佐露缇中意的类型。

要让自己不喜欢的对象触摸身体，伊佐露缇对此有着些许的厌恶感。

「要搜身吗？请。」

但是，这是国王的房间。

理所当然的，就算是骑士，也不允许带着武器进入国王的私人房间。

城内的人都知道，杜加绝对不会让人带着武器走进国王的房间。

即使是阿斯拉王国的大臣，杜加也会亲自仔细地搜身，就算是一个小小的木勺也不能带进去。

搜身也是理所当然的。

伊佐露缇心想，说不定还会碰到胸部之类的地方，但她决定忍耐。

「哦。」

然而，杜加并没有触摸伊佐露缇的身体。

他的手伸过去的地方，是头发。他把手伸向头发，并摘下了什么。

「......？」

杜加的指上捏着一片花瓣。

「沾到了。」

\\

「？」

「因为伊佐露缇，很漂亮，不能沾到，这种东西。」

杜加位于头盔里面的脸露出了和蔼的笑容。

伊佐露缇听了后虽然愣住了，但身体的僵硬也解除了。

「啊，武器。」

然后，她猛然想到，将剑从剑带拿出来，交给了杜加。

但是，杜加并没有收下。

「伊佐露缇，是爱丽儿大人的骑士。需要武器，守护爱丽儿大人。」

「......」

不仅没被搜身，武器也没被拿走。因为自己是爱丽儿大人的骑士，受到这个男人信赖。被在阿斯拉王国有着排名前五实力的这个男人所信赖。

想到这点，不知为何心跳稍稍加快。

（不，可是，那张脸不行啊......）

伊佐露缇一边摇着头，一边深呼吸。

「伊佐露缇•克尔埃尔。请求进入。」

「请进。」

等爱丽儿回答后，伊佐露缇走进了房间。

\\

★　★　★

\\

阿斯拉七骑士。

\\

那是以「王之心腹」路克•诺托斯•格雷拉特为首，发誓绝对效忠爱丽儿的七名骑士。

在骑士当中，他们也被赐予了特殊的立场，允许他们在某种程度上独自行动。

伊佐露缇也是其中一人。

阿斯拉七骑士之一「王之大盾」。

在发生万一时保护国王，是与水神流剑士相符的称号。

伊佐露缇、希尔贝斯托、杜加。

人称他们三人为「左翼三骑士」。

在阿斯拉七骑士当中，主要负责警备爱丽儿安全的三骑士。

但是，伊佐露缇对此感到有哪里不对劲。

所谓的阿斯拉七骑士，意指发誓绝对效忠爱丽儿的七名骑士。

至少，世间是如此认为的。

会有这种想法，是因为伊佐露缇对这七个人集合的经过并不是很清楚。

尽管他们对爱丽儿竭尽忠诚，但大部分都与阿斯拉王国没有关系，是从外部召集过来的人员。

所以，他们很有可能都有自己无法背叛爱丽儿的理由......

但是，伊佐露缇不一样。

伊佐露缇知道自己有背叛的可能。是因为前任水神。与伊佐露缇的祖母死去的那时有关。

前任水神列妲死了。

在爱丽儿试图拿下王位的争夺战中，被站在爱丽儿那边的龙神奥尔斯帝德亲手杀害。

当然，这是在战斗中发生的。

伊佐露缇也是剑士，既然战斗已经结束，她也不打算被不必要的感情所束缚。

况且，祖母已经将水神流托付给伊佐露缇。假如违抗爱丽儿，水神流很有可能会被逐出阿斯拉王国。因此，她从来没想过要背叛爱丽儿或是反抗她。

伊佐露缇对这件事的态度很干脆。

但不管她内心怎么认定，就算嘴上说不会再违抗爱丽儿，谁也不知道这番话是真是假。

没有任何人看得到他人的内心深处。

坦白说，她确实有可能对祖母被杀一事怀恨在心，因此对爱丽儿的性命虎视眈眈。或者她想杀的并不是爱丽儿，而是当时下杀手的龙神奥尔斯帝德。

实际上，爱丽儿在取得王位时，谋杀了许多骑士与贵族。

有不少人对此怀恨在心。

他们平常摆出漠不关心的表情发誓效忠爱丽儿，同时也在窥伺着机会。

伊佐露缇在立场上就算被这样看待也很正常。

实际上，伊佐露缇不仅进行了骑士的宣誓，也发誓要效忠爱丽儿。

然而，那并不是被爱丽儿的人品所吸引，也并非出于爱国心所致。

她是为了保护水神流，保护自己的容身之处与矜持。

尽管目前还维持着信赖关系，但如果有什么对此产生了威胁，她或许也没办法保证今后不论发生什么事都能守住忠于爱丽儿的誓言。

她也不是想要背叛。

但是，确实存在着背叛的可能性。

伊佐露缇自己也十分清楚这点。

尽管如此，她依然被选为七骑士。

她觉得不太对劲。认为其中是不是有什么内幕。

「伊佐露缇。你不打算透过我介绍去相亲吗？」

所以在王之间被这样提案时，她有着高度的警戒。

「陛下，您为什么如此提议？」

「对我来说，即将成为水神的你若是能定下来，在工作上也有加分的效果。候补者都与我有血缘关系，虽然许多人在性癖上有些问题......但里面想必也有人符合你的喜好吧。」

「和陛下有血缘关系的意思是......王族的人吗！」

「嗯，是那样没错。」

与王族相亲。

听到这件事，伊佐露缇的内心不由得激动起来。真好搞定。

「不过，一旦我成为水神，对方就必须舍弃自家。对王族的人来说，这样应该会有很大的影响吧？」

「即使舍弃自家，依然存在着血缘关系。不代表必须与家族完全断绝关系吧？」

「呃，确实是这样没错。」

「不要紧的。大家都同意了这件事。我已经和他们约法三章，就算和你结婚，王家也依然会慷慨解囊。你要做的就是亲自和他们见面，选出心目中最好的人选。」

这是意图要怀柔我吧，伊佐露缇这样心想。

不管怎么说，条件实在太好了。

与爱丽儿有血缘关系的王族。虽然也可能是旁系，但这样的对象可以说是真正的王子殿下。

不是贵族子弟，也存在着微粒子级别的可能性成为国王，是真正的王子殿下。

而且，阿斯拉王家每个人都是一表人才，相貌出众。

「如何？我认为这条件还不错。」

「请务必！」

伊佐露缇二话不说就答应了。

没有拒绝的理由。

假如她是老奸巨猾的阿斯拉贵族，也许就会设想到爱丽儿这番话中背后的真意而回绝。

但不巧的是她只是一介剑士。只是在进行着婚活的少女。

她并没有想得那么复杂。

「那么，从后天开始相亲吧。麻烦你先告诉路克或希尔贝斯托哪几天比较方便。接下来的事情由我们这边安排。」

「是，拜托您了。」

「好的。那么，你可以离开了。」

伊佐露缇带着宛如作梦般的心情离开了爱丽儿的私人房间。

（与王族相亲......）

感觉就连脚步也变得轻快了起来。

她现在心花怒放，无比雀跃。

立刻告诉希尔贝斯托自己最近哪几天放假吧。

她这样心想，突然发现自己喉咙渴到不行。

也许是因为在不明究理的情况下遭到传唤，导致自己有点紧张。

「口渴了呢。」

「哦。」

当她喃喃如此说道的瞬间，突然有人从后面叫住了她，伊佐露缇把腰往下沉，同时迅速回头。

站在那里的人是杜加。

他拿着与那庞大身躯体很不搭轧的小杯子。

「请，是冰的。」

「......非常感谢。」

伊佐露缇接过杯子，有那么一瞬间怀疑里面是否有毒，随后还是含在嘴里，一口气喝下。

正如杜加所说，那杯水就像直到刚才还是冰块般清凉，滋润了伊佐露缇的喉咙。

感受到水渗透了身体深处之后，伊佐露缇注意到了自己比想像中还要紧张，十分疲惫。

「......呼。」

「伊佐露缇，辛苦了。」

杜加喝着水，看着叹着气的伊佐露缇，露出了和蔼的笑容。

即使透过铠甲的缝隙间，也能看出他的笑容没有任何邪念，极为纯朴。

「......」

真是个体贴的人。

至少对自己来说，应该能毫不犹豫地把背后交给他吧，伊佐露缇自然而然地这样想。

虽然长相不符合自己的喜好就是了。

「杜加先生也辛苦了。请你继续努力做好守卫的工作。」

「哦！」

不过，这件事姑且放到一边。

伊佐露缇想到接下来每天都要随心所欲地相亲，嘴角不禁扬起了笑意，从那里离开了。

*** 「门卫杜加　前篇」

在阿斯拉王国，有被称为七骑士的七名骑士。

他们都发誓绝对效忠爱丽儿•阿涅摩伊•阿斯拉。

名列第一的护卫骑士「王之心腹」路克•诺托斯•格雷拉特。

\\

掌管攻击的右翼三骑士。

「王之大剑」香杜尔•冯•格兰道尔。

「王之斧枪」奥斯华•艾乌洛斯•格雷拉特。

「王之猎犬」基列奴•泰德路迪亚。

\\

掌管防御的左翼三骑士。

「王之门卫」杜加。

「王之城墙」希尔贝斯托•伊弗利特。

「王之大盾」伊佐露缇•克尔埃尔。

\\

这七个人。

尽管有人的来历与出身明确，但其中有一半是爱丽儿与路克所独自挖角。从平民、下级贵族到高级贵族，乃至不死魔族与人族的混血，聚集了各式各样的人物。

据说他们有个共通点，就是对爱丽儿有着绝对的忠诚心。

这次要谈的，是当伊佐露缇正在烦恼自己对爱丽儿所说的「性癖上有些问题」的「有些」感觉到认知上的差异时，关于另一个骑士的故事。

\\

★　★　★

\\

他出生在阿斯拉王国多纳提领地的一个小村庄。

这孩子稍微有些迟钝，被村子里的孩子们当作小弟般使唤。

但他身强力壮，没有疾病，非常健康。

那名少年的父亲是保护村子的士兵，一整天几乎都在外面度过。

因为士兵寥寥无几，几乎没有休假，晚上不在家也已经是司空见惯。

少年五岁的时候，妹妹出生了。妹妹是与母亲相像的可爱女孩。但母亲在产后恢复的状况不好，就这样过世了。

少年哭了。

就算被朋友殴打、被蜜蜂叮也总是若无其事、不曾哭泣的少年在那时嚎啕大哭。

父亲对哭得泣不成声的他说道：

「现在可以哭，但等你不哭了，你就要负责保护这个孩子。」

他抬头望向抱着妹妹的父亲，连连点头。

然后，从那天起他就不再哭泣。

而且从隔天开始，他就忠实地执行着父亲的嘱咐。

就是要保护妹妹的那句话。

为了保护妹妹，少年决定守住家里的玄关。一整天都拿着放在家中角落的砍柴用斧头站在家门前。只有当妹妹哭的时候才会跑回屋子，照顾妹妹。

看到他这个样子，朋友们都嘲笑他。

你在做什么啊？在家里看着她嘛。

村里的大人对他说：

不然，由我们家照顾你妹妹吧？我们家小孩多，增加一个人也不要紧的。

但是，顽固的少年没有答应。

尽管他会请教该如何照顾乳儿，却从未把妹妹托给别人照顾。

有一天。村里发生了异变。

晚上某户民宅的家畜小屋遭到破坏，里面的家畜被残忍地咬死了。

从足迹的大小来看，村民推测是野狼干的好事。士兵们在村里奔走，告知村民晚上记得要把门上锁，绝对不要打开。

第二天。一户人家遭殃了。

野狼不知是如何在半夜闯入家里，一瞬间咬碎了婴儿的头将其杀害，并从窗户逃之夭夭。

家人早上起来时不晓得出了什么事，只是沿着地上的血迹追了上去。随后，他们在郊外发现了一滩血，以及血泊中的婴儿服时，几近疯狂了。

因为这一连串的事件，士兵们才意识到自己的看法是错的。

潜入村子的并不是野狼，而是魔物。尽管体型娇小，大小顶多与野狼相同，却相当狡猾。

如他们所猜测的，下手的是魔物。

这魔物的头与后脚都是野狼，但长在肩膀上的是猴子的手，有时用两只脚走路，甚至还会爬树。

大小与大型犬差不多，但是它的头却大到很不自然。那颗头给予了它智慧。

这是突然变异的魔物。

尝过人类味道的魔物潜伏在某户人家的麦田，仿佛在嘲笑害怕的村民般，花了一天时间锁定下一个目标。因为那户人家的大人晚上也不会回来。他追赶魔物，忙着在错误的地方寻找。

留在家里的是两个小孩。

魔物舔了舔嘴唇，用猴子的手臂爬上屋顶，并从壁炉侵入到住家里面。

第二天。

完成了夜间巡逻的少年父亲一回到家，率先映入眼帘的是一滩血迹。

他心想「不会吧」铁青着一张脸环视家中，立刻发现凄惨的尸体倒在地上。

那是魔物的尸体。头直接被敲碎的魔物尸体。

而且，自己的儿子就站在那具尸体与躺在床上睡得香甜的女儿之间，他紧紧握着砍柴用的斧头，表情狰狞，打开双脚站在那里。

可以看出这里经历过一番死斗。

少年满身是血，手臂也骨折了。

但是，也就如此而已。

魔物虽小，但体型也足以被误认为野狼。换句话说少年面对的是比自己大上两倍的魔物。

但他依然用一把不够锋利的砍柴用斧头打死了魔物。

他保护了妹妹。

这就是少年──后来被称为北帝杜加的男人第一场战斗。

\\

在那之后，杜加也持续过着担任门卫的人生。

十岁的时候，他守护着村子的大门。

转移事件发生的不久之前，魔物整个大失控。从阿斯拉王国的森林里面大量涌出魔物，有许多村子都深受其害。甚至有些村子遭到大量魔物袭击而因此毁灭。

杜加的村子也同样遭到魔物袭击。

但是杜加勇猛果敢地挥动伐木用的斧头，击退了魔物。杜加当时击退的魔物数量，据说高达百只。

尽管他让魔物尸横遍野，但是，他的父亲却在这场战斗中死去了。

杜加在父亲的尸体前茫然自失。

看到这幕的骑士，向王都守备队推荐杜加。

眼见杜加以要保护妹妹为由而不愿答应，他这样说道：

「听好了小弟弟，我们远离家人，去了很多地方守护着村子。换句话说，我们保护的是这个国家本身。只要国家和平，家人就可以安心生活。也就是说，保护国家就等于保护家人。」

当时，迟钝的杜加还不能理解这句话。

最终促使杜加做出行动的，是金钱方面的问题。

父亲死去的现在，他需要钱。只要前往王都，就能拿到足以两个人生活的薪水。

听到这点，他下定决心前往王都。

杜加成为了王都的士兵。

这样的他守护的，是分隔贫民区与下级市民街之间的小门。

这道门是为了在贫民区的人化为暴徒涌入下级市民街时，作为阻挡用的隘道所设立的。尽管禁止在夜间通行，但其实这道门并没有特别值得守护。不过也可说是个相当适合在乡下长大，没有学识的少年的地方吧。

和妹妹一起搬到王都之后，他被分配了一个房间。

虽然狭窄，但能和妹妹一起生活的房间。

他从那里到兵营通勤，每天从早到晚，偶尔还会通宵当门卫值班。

杜加虽然迟钝，但不可思议的很讨人喜欢。

也有人因为他才十岁出头就当上士兵而讨厌他，故意找他麻烦。

然而他纯朴的个性以及为妹妹着想的坚定态度，不知不觉间解开了同僚的心结，一年之后，杜加已经被士兵们认同是自己的伙伴了。

然后第二年。

有一天晚上，有一名女性逃到杜加镇守的那道门。

那名女性缠住杜加，恳求他的帮助。当杜加为此不知所措时，立刻出现了表情严肃的一群人，他们向杜加大喊「把那女人交出来」。

杜加困惑了，他不知道该如何是好。

说不定，只要和杜加一起值班的汉斯没有打瞌睡，他就会帮忙做出判断吧......

女性看到杜加正在困惑，立刻试图穿过大门。

杜加见状，随即抓住她的脖子，将人拉了回来。因为他被交待任何人在晚上都不能通过这里。

然而在那个瞬间。

查觉到女人要逃走的男人们袭击过来。

杜加挥动战斧。这是在成为士兵的时候，村里的工匠送给他当饯别礼的战斧。

他杀害了所有人。

看到浑身鲜血站着的杜加，女性不禁漏尿，吓得四肢着地瘫在那里。

汉斯听到声响后迅速起身，看到门口的惨状，顿时大吃一惊。

他认为事态非常严重。杜加犯下无差别杀人，而打瞌睡的自己也会受到惩罚。汉斯这样心想，脸色铁青地检查尸体，然而在看见尸体的脸后注意到了。

这些人是在下级市民街到处为非作歹的盗贼团。因为是在下级市民街作乱，骑士团也没办法腾出人手处理，是令他们非常头疼的一群对象。

而杜加一个人就把这些人全灭了。

杜加因此晋升。

从守护下级市民街与贫民区之间那道门的士兵，晋升为守护中级市民街与下级市民街之间那道门的士兵。不知为何，汉斯也一起晋升了。

之后有好一段时间，杜加都持续守护着那道门。

不论刮风下雨，都持续守着门。即使长大成人之后，也一直持续着这份工作。汉斯帮助了迟钝的他。

不知不觉间，汉斯成了最了解杜加的人。

然后，杜加的妹妹在这段期间也成长为一个美女，与汉斯结婚了。

说不定汉斯的目标就是杜加的妹妹。但对杜加来说这件事无所谓。因为汉斯虽然是个会打瞌睡的男人，但绝对不是坏人。

而且他在圣米里斯面前发誓，要让杜加的妹妹获得幸福。

杜加变成了一个人。

由于妹妹已经结婚，他直到最后都遵守了爸爸的嘱咐。

已经不需要守门了。

可是，杜加依然继续守着门。不论刮风下雨，都持续守着门。

有一天，王都起了很大的震荡。

爱丽儿•阿涅摩伊•阿斯拉宣布要举行加冕典礼。

这个加冕典礼是为期好几天的祭典。士兵们在这段期间会拿到更多薪水，也能免费获得食物。杜加的同僚对此喜不自胜，连汉斯也手舞足蹈。

但这样一来，也代表士兵的工作会增加。

不是中级市民街，其他地方的警备也得变得更加森严。

王国从城里的人里募集临时士兵，而杜加那些本就是士兵的人，则是负责更加重要的地方执行警备任务。

杜加与汉斯因为薪水增加，想要买些好东西给妹妹，心悦诚服地工作。

就这样，加冕典礼的日程到了中期的某一天。

杜加在那一天不知道是什么因果使然，担任了王城紧急出口的门卫。尽管那个地方鲜少有人经过，但偶尔会有拿着许可证的佣人进出。汉斯并没有和他在一起。

杜加与其他数名士兵守着这道门。

这时，有一名男子出现了。是个身穿老旧铠甲，手持长棍的男人。

他这样说。

「可以让我通过这里吗？我想去谒见爱丽儿陛下。」

当然，门卫拒绝了他的要求。

「没有获得许可的人不能通过这道门，出示许可证！」

「我没有许可证，但希望能见爱丽儿陛下一面。」

「既然没有许可证就不能让你通过，回去！」

「那也没办法了，幸好是来这道门，毕竟这下子可能会在这大喜之日害陛下的威望蒙上一层阴影。」

男人这样说完，试图要强行突破这道门。

他像魔法那样使着棍子，一瞬间就打倒了其他的门卫。

但只有杜加没有倒下。不管男人的棍子怎么打中他的要害，他依然屹立不摇，守护着这道门。

杜加挥舞着斧头，但没有一次打中那个男人。自己挥动的斧头没有打中人，这对杜加来说是初次的体验，但他还是耿直地持续挥舞着斧头。

男人非常喜欢杜加这样的战斗方式。

「太棒了！想不到有如此了得的男人被埋没在这种地方。好吧。就看在你的面子上，我不过这道门了。哎呀，抱歉。虽然这样不知道算不算赔罪，你要不要当我的弟子？你一定会变强，你有才能，来吧！」

杜加不能理解这个男人在说什么。

但是，他知道这男人终于放弃通过这道门，一瞬间放松下来，昏迷了过去。

是在站着的状态下昏倒的。

而当杜加清醒时，那个人还在那里。

他拿着杜加的斧头，像是守着门那样站着。只是，他被大量的士兵围住。

「嗨，早安！我代替你守了这道门喔！」

这就是杜加与香杜尔──北神卡尔曼二世，亚历克斯•卡尔曼•雷白克的相遇。

\\

杜加成为了亚历克斯的弟子的那天，一回到自己的房间便直接倒在床上沉沉睡去。

赶到现场的士兵中有治愈魔术师，所以伤口完全没有留下。

但是，与北神卡尔曼的战斗让杜加深不见底的体力完全耗尽了。

杜加自出生以来，第一次因为疲劳而入睡。

连续睡了两天之后，他醒来了。

这时，枕头边有泪流满面的妹妹，以及一脸放心的汉斯。

另外，还有看起来莫名高兴的香杜尔。

「早安，我的弟子啊，跟我来吧。」

香杜尔以惊人的力气扶起杜加，帮他穿好铠甲，打算带他去某个地方。

杜加不知道这是什么状况，转而向汉斯求救。

「抱歉啊杜加。不过，这不是什么坏事。我现在也很混乱，不太清楚状况，但我觉得这很光荣，总之你就去吧。加油啊，可别失礼喔。」

「嗯。那个，哥哥，请你加油。」

听了汉斯不得要领的这番话后，杜加顿时睁大双眼，但他没有抵抗香杜尔的力量，就这样朝着他前几天守着的那道门走去。到了门口，香杜尔从怀里拿出许可证炫耀之后，通过了门。

他们转眼间来到了王城里面。

杜加初次见识到这般金碧辉煌的空间，一边惊叹着眼前的景象一边跟在香杜尔后面。

然后，当他回过神来，眼前出现了一名金发的漂亮女性。

「就是这个人吗？」

「是的，陛下！」

「让我稍微和他聊一下。」

被香杜尔推着背，杜加站到了女性的正面。

这位女性非常漂亮，该怎么说，有股神圣感。

「我是爱丽儿•阿涅摩伊•阿斯拉，你呢？」

杜加不知道这个名字。

尽管是王都的士兵，但他连举行加冕典礼的人叫什么名字都不晓得。

当然，他也没有实际看过。

可是回过神来，杜加已经跪在地上。他说不出个所以然，但就是认为必须这么做。

「我......我叫......杜加。」

「你为什么成为士兵呢？」

「爸......爸爸，要......要我保......保护妹......妹妹......」

杜加的舌头打结。

他并没有健谈到可以向别人阐述自己至今为止的漫长人生。

但爱丽儿轻松就理解了杜加所说的话。

「原来如此，你是为了保护妹妹啊。真是了不起呢。」

「但......但是，妹妹，已经有汉斯保护，那个，汉斯和妹妹在一起，那个......」

爱丽儿使了个眼色，随后站在他身旁的骑士便「他妹妹和一名叫汉斯的士兵结婚──」这么补充说明。

杜加虽然不认识，不过那个人是路克。

「所以说，我已经，已经不需要再保护了......」

眼见杜加露出有些无精打采的表情这样说道，爱丽儿莞尔一笑。

「不对喔，杜加。」

「咦？」

「你并不是不需要保护了。」

「什......什么，意思？」

「汉斯变成了你的弟弟，你现在有了妹妹和弟弟，必须要保护两个人，是之前的两倍。」

听到那句话，杜加顿时受到了震撼。他从来没有这样想过。

但是，眼前这人说得没错。汉斯说要保护妹妹，也确实是称杜加为哥哥，那么他就是自己的弟弟。

如果必须要保护妹妹，当然，自己也必须要保护弟弟。

「这......这样啊，原来，我必须保护更多东西才行。」

「没错。不过照你现在的做法，或许没办法保护好他们两人。」

「咦！为......为什么？」

「你的臂力惊人，但手的距离有限，当他们两人陷入危机时，也有可能是在你触手不及的范围。」

杜加看了看自己的手。

他想起了父亲为何而死。明明父亲就在很近的地方，却依然遭到杜加视线之外的魔物所杀。

「那......那么，我该怎么办，才好呢？」

「请保护我。」

「咦？」

「我为了这个国家工作，让国家变得更好。保护我，就等于保护国家。而守护了国家，就是守护了那两个人。」

杜加无法理解她的意思。

为什么保护眼前这个人就算守护了那两个人呢？他完全搞不懂。

但是，他明白爱丽儿的这番话是认真的。

与此同时，他想起了好像有人说过类似的话。就是写信推荐他去王都守备队的那名骑士。

「听好了小弟弟，我们远离家人，去了很多地方守护着村子。换句话说，我们保护的是这个国家本身。只要国家和平，家人就可以安心生活。也就是说，保护国家就等于保护家人。」

当时杜加还不能理解这句话。正因为他无法理解，才会为了钱而工作。

不过，现在可以自然而然地理解。虽然现在杜加在保护着截然不同的东西，妹妹和汉斯依然幸福地活着。

「杜加，发誓向我效忠吧。你愿意保护我，进而守护这个国家吗？」

「是，陛下。」

「那么杜加，我任命你为骑士。」

这天，杜加成为了七骑士之一。

\\

在那之后，杜加持续守护着最后一道门。

最后一道门，也就是通往王之间的门。

他有时也会接获爱丽儿的命令前去看守其他地方，一天当中也有几个小时会在离爱丽儿的私人房间稍微有点距离的场所请香杜尔陪他训练。

一个月会有一次休假，他偶尔也会去妹妹与汉斯的家一起吃饭。

杜加不在的时候，会有其他人看守王之间。

基本上都是由「王之大盾」伊佐露缇•克尔埃尔负责。

但是，一开始并不是那样。

被任命为骑士之后，杜加获赠闪闪发光的黄金铠甲，他始终顽固地站在「最后之门」的前面动也不动。就像是在表示既然决定要守护了，就不可以交给不成气候的人。

事实上，在刚开始守门的一个月，他从未把这个地方交给香杜尔以外的人。

如果爱丽儿不叫他去休息，他就会不吃不喝不睡好几天。

接近王之间的人全都会被进行搜身。

不管是男是女都一视同仁，就连一根小小的叉子也会被收走。

这个时候，七骑士加入一名人物。

「王之大盾」伊佐露缇•克尔埃尔。

她的工作是教导剑术，在基列奴还没当上七骑士的时候，她是七骑士里唯一的女性，被认为非常适合当公主身边的护卫。

有一天。

香杜尔为了招募黄金骑士团的成员，决定前往阿斯拉王国的各地奔波。

一旦香杜尔不在，就没有人和杜加轮班。若是一个月都站着不动，想必杜加的身体也会撑不住的。

因此，香杜尔让杜加与伊佐露缇比了一场。

当时，香杜尔让杜加自称「北王」。

明明才刚开始教导，杜加已经非常有实力了。

但结果不用说，是伊佐露缇获得了压倒性的胜利。她将杜加的战斧犹如微风那样弹开，一次又一次地使出反击，打倒了杜加。

如果这场对决是用真剑，并抱有杀意战斗的话，伊佐露缇一瞬间就会杀了杜加。

尽管杜加以无穷无尽的体力袭向伊佐露缇，但连她的一根手指都碰不到，就这样败北了。

犹如花朵般瘦小的女性，弹开了比自己身体还大的战斧，发出像刺一般的攻击。

杜加接下了好几次这样的攻击，最后认同她是代替自己守护这道门的不二人选。

同时也理解了。

这名女性，是一朵优美的花。

是自己不该触碰的存在。

也就是说，杜加他────爱上了伊佐露缇。

\\

★　★　★

\\

「你最近没什么精神呢......」

和妹妹夫妻俩吃饭时，他们向杜加这么说。

在桌上，摆着虽然朴素但可以让身材高壮的杜加饱餐一顿的料理。

这些料理后面则是妹妹与她的丈夫汉斯。汉斯的旁边还坐着他可爱的女儿。

杜加单手拿起倒了满满葡萄酒的酒杯，呆滞地看着汉斯。

「身体不舒服吗？」

「......为......为什么？」

杜加为了不让他察觉内心的动摇而这样回答，汉斯听了后指着料理。

「你根本没吃嘛。」

仔细一看，桌上的料理确实没什么减少。

他最喜欢吃妹妹煮的料理。

以往杜加都会默默地扒饭，露出幸福的表情将脸颊塞得鼓鼓的，吃得一干二净。

杜加喜欢的葡萄酒也是。

他很喜欢只有在庆祝的时候才能喝的葡萄酒，这种时候他总是会像把酒洒在身上那样猛灌。

因此，汉斯家里总是会备有一整桶。

但不知道为什么，料理只减少了一半，葡萄酒也是小口小口地喝。

认识杜加的人看在眼里，都会觉得这是奇怪的光景。

「身体不舒服的话，记得要去给城里的治愈术师看看喔。因为你已经是骑士了，这种事只要说一下就可以了吧。不过，你的脸色倒也没有说不好。」

「......？」

杜加茫然地歪了歪头。

他并没有发现自己异常的行为。

「如果累了，干脆多休息一下怎么样？当然，你做事很勤劳，担任陛下的守卫也是很光荣的工作。不过要是太认真工作而倒下，就得不偿失了......是说，也无法想像你倒下的样子就是了。」

「哦。」

杜加点了头，开始吃饭。

但是，确实很怪。

味道一如往常，很好吃。但是当食物通过喉咙的瞬间，好像又有那里不对劲。

假如是平常的话，感觉就是不断咀嚼，然后一口气吞下去，「再吃下一份！」那样。

但今天不同。每当食物通过喉咙，从肚子里就涌起了某种类似抗拒的感觉。

就好像吃饱的时候一样，但是那种感觉更不舒服。

葡萄酒也很奇怪。总觉得不是那么好喝。喝葡萄酒时，一直以来都是「噗哈──」的那种感觉，今天却是「呼......」。

这种事情还是第一次。难道，自己真的生病了？还是像汉斯说的一样，累了吗......

「喂，到底发生了什么事啊？说说看吧。」

「......」

眼见杜加默不吭声，汉斯进一步追问。

「哥哥，不对，杜加。从当初还在城邑的时候，我就一直受你照顾。要是连你的烦恼都没办法帮你分担的话......我以后该用什么脸活下去？也没办法面对圣米里斯啊。」

「......嗯，但是，我也不太清楚。」

「像是最近在城里发生的事也行，什么都好，你就说说看吧。」

汉斯露出严肃的表情这样说完，杜加抬起头。

杜加依他所言，循着自己的记忆开始零零碎碎地说起。

在警备最后之门时，有只猫迷路跑进来，把中午的便当稍微分给它后，那只猫就变得常常过来，非常高兴。

在镇上穿着这身铠甲走路时，被一名年轻的士兵叫住，他说「我很尊敬你」，非常高兴。

在警备最后之门时，伊佐露缇来了，帮她把头发上的花瓣取下来，她说谢谢，非常高兴。

香杜尔教新的招式时，夸奖说「你果然很有资质」，非常高兴。

从城里回宿舍的途中，差点被马车辗过，虽然被车夫大骂「滚开，慢郎中！」，但路克立刻从马车上下来赔罪，并送他回宿舍，非常高兴。

被香杜尔命令训练骑士团而去了训练场，去了之后发现基列奴和伊佐露缇也在，非常高兴。

走在城里时，听到卫兵说「伊佐露缇好像要结婚了」的传闻，不怎么高兴。

负责派对的警备任务时，看到身穿礼服盛装打扮的伊佐露缇相当漂亮，非常高兴。

看到她和一个陌生的男人跳舞时，不怎么高兴。

贵族子弟毫无根据地骂了伊佐露缇，不怎么高兴。

看到伊佐露缇和一个帅气的男子走在一起，非常难过。

伊佐露缇──

「好了，我知道了，我完全知道了。」

汉斯打断了杜加的话。

听了刚才说的，他大致上掌握了状况。

「简单来说呢，你爱上了那个叫伊佐露缇的女人。」

「......」

杜加的脸突然变得红通通的。

不知道为什么汉斯听了刚刚那些话就能发现这点，但确实说中了他的心事。

「然后，你听说那个伊佐露缇要结婚，又看到了可以证明这件事的景象，因此受到了打击。」

「............哦。」

杜加变得非常沮丧，可以说是一目了然。

看样子，这也是正确答案。

「原来如此。」

看了杜加的反应，汉斯理解了。

这个看似与恋爱无缘的哥哥，似乎是恋爱了。

同时，汉斯的脑海里想起自己初恋的回忆。

是住在汉斯老家隔壁的那个蔬果店的独生女。尽管两人年纪差了五岁，但依然是青梅竹马，从小就一直受她照顾。

她是个温柔又可靠的美丽大姐姐。从五岁左右开始，就一直喜欢的大姐姐。

汉斯将来的梦想是和大姐姐结婚。

实际上他也打定了主意，一旦成年就去当兵，等薪水稳定之后就向她求婚。

然而就在汉斯十二岁的那年夏天，她和隔壁肉舖的独生子结婚了，并继承对方的家业。

汉斯也知道那个男人。他在汉斯懂事的时候就已经是个大叔了。

和她好像差了五岁吧。这样想想，其实也不算是大叔啦......

起初，汉斯是不相信的。

那个人体形虽好，但实在说不上是个美男子。

她一定是心不甘情不愿才结婚的，总有一天一定要把她抢回来，汉斯这样想着。

但一年后，看到她一脸幸福地依偎在男人身边，肚子也已经鼓起来的模样，汉斯终于接受了事实，哭得整颗枕头都湿了。

说不定，只要自己早一点去告白的话，就不会有那样的回忆了吧。

当然，他也并非讨厌现在的生活。

若是和她结婚，想必就无法和杜加的妹妹结婚了吧。

妹妹与杜加完全不像，身材娇小又可爱，个性稳重。

和她所生的爱的结晶，现在就像在代替杜加一样大口吃饭。这个孩子很坚强，也聪明得不像汉斯，更重要的是很可爱。

现在的汉斯有比任何人都还幸福的自信。

但这样的幸福，正是因为曾经历过刻苦铭心的失恋。

归功于那次经验，汉斯在发觉自己爱上了杜加的妹妹之后立刻就采取了行动。

一开始也许被认为很轻浮。但从头到尾，汉斯都是以非常真挚的态度面对杜加的妹妹。

门卫的工作也比以前更加卖力。

自从告白之后，他就再也没抱过妓女。

最终，他赢过许多对手，成功掌握了现在的幸福。

正因为这样，汉斯说：

「现在立刻去向那个伊佐露缇小姐求婚。」

听了这句话，杜加抬起头，愣愣地看着他。

「不，就算不结婚也无所谓，交往也可以。不然，就算只是告诉她你喜欢她也行。」

「......」

「再继续这样袖手旁观，你绝对会后悔的。」

「......可是。」

「别想着自己配不上她什么的。你是代表阿斯拉王国的黄金骑士之一。是我们守备队的骄傲，更是憧憬，你大可抬头挺胸。」

杜加稍微想了一下。

关于家世是否匹配什么的，杜加不是很清楚。但他对美丑还是稍微懂一些。

自己配不上美若天仙的伊佐露缇。

他对这件事稍微思考了一下。

「就算死马当活马医也好，把你的想法告诉她，好好地被拒绝吧。再这样下去，你甚至没办法祝福她结婚喔。」

但是，听了汉斯的这句话以后，他马上得出了结论。

「哦！」

去向伊佐露缇告白看看吧。

*** 「伊佐露缇与杜加　后篇」

「这是第几个了？」

这里是与水神流道场稍有距离，伊佐露缇的自家。

她在客厅与自己的哥哥相对而坐。

「............第二十六个。」

伊佐露缇低下头如此回答。

丹托里斯想看着她的眼睛，但伊佐露缇却依然移开视线。

「根据我的小道消息，是你把他们甩掉的。」

「......是。」

「为什么？」

伊佐露缇抿紧嘴巴。

「不，那个......大家都非常优秀。不仅个性很好，举止也很稳重......只是......」

「只是？」

「或许是因为太好了，缺点反而更明显。」

伊佐露缇回忆起和自己相亲的对象。

也就是爱丽儿所介绍的那些王族。

他们都很年轻、开朗，在相亲会场让伊佐露缇相当乐在其中。

只是......他们都很诚实。也许是因为爱丽儿这样交待的，他们也说出了自己的性癖。

五个人都毫无保留，开诚布公地说了出来。

长相好看，个性温柔，说一旦结婚就会全心全意支持伊佐露缇的亚托雷•奥尔佩斯•阿斯拉。

长相好看，身材强壮，深深理解水神流的贝吉尔•温缇•阿斯拉。

长相好看，举止优雅，说会在经济方面支持水神流的的卡洛斯•席欧德斯•阿斯拉。

长相好看，谈吐风趣，在对话中好几次都把自己逗笑的丹尼尔•利普斯•阿斯拉。

长相好看又可爱，不禁会想要守护他的艾略特•斯奇隆•阿斯拉。

他们坦承了一切。想和伊佐露缇在床上做，不然就想在床之外的地方做，希望她穿什么服装做，最后还说想要伊佐露缇怎么做之类......

虽然也不是说很夸张，但经验值不高的伊佐露缇跟不上这样的话题。

回过神来，她已经拒绝了对方。

甚至觉得他们没有一个正常的。

长相俊俏的他们竟然会抱有这样的欲望，甚至让她感到不寒而栗。

说实话，伊佐露缇现在已经有些不信任男人了。

她也知道并非所有男性都是那样，但她认为世上的男人大半都会想做那种事。

这样一想，她不禁有点觉得就算不结婚也没关系了。

「缺点是指？」

「我说不出口，是不能讲出来的那种事。」

「原来如此......毕竟是阿斯拉王族嘛。」

许多阿斯拉贵族有着变态的嗜好，这点相当闻名。

由于上流阶级的人会在全方面都获得满足，所以无法满足和身分低贱的人做着一样的事。

「不过这样就伤脑筋了呢，没想到你会拒绝所有人。」

「不，并不是所有人，现在还剩下几位。」

「话是这么说，照这样看来你肯定决定不了吧......」

丹托里斯想起以前的事，这样说道。

从以前开始，当伊佐露缇可以自己选择的时候，就会有这个不要，那个也不要，过于精挑细选的坏习惯。

想要的东西会在她这么做的时候被人挑走，导致她只能选剩下的。

也是因为这样才会错过了适婚年龄。

「......好，不然就这样吧。」

丹托里斯考虑到她的个性，得出一个结论。

「和下一个对象结婚吧。」

「可是，这样......」

「对象的条件对你来说应该是可遇不可求的。就是因为你可以自己做选择才会在意他们醒目的缺点。不过只要等你们结婚后一起生活，这些缺点说不定就会变成不重要的小事。也有可能会发现刚相遇时还无法立刻知道的更棒的优点。」

丹托里斯也不喜欢用这种强硬的论述说服她。

他认为要得知一个人的本性，选择的时间也是必要的。

但因为是「爱丽儿介绍的」，导致他认为可以靠这种强硬的方式设法解决。

既然是爱丽儿介绍的，就不会发生严重的失败才对。

真是太抬举她了。

「............我知道了。」

沉默了一阵子后，伊佐露缇也下定了决心。

确实，自己太挑三拣四了。从以前开始就是这样，肯定没办法立刻改变。

这种个性与水神流非常契合，所以她就快要当上水神了，但实在不适合在结婚时表现出来。

再这样下去，她可能会一个人孤老终身。

成为水神确实是值得骄傲的事。

想必会被周围的人赞赏、夸奖、赞美吧。

以笑脸回应他们，与其交谈，心情畅快地回到家。然后，在没有其他人的房间一个人吃饭，回到寝室换好衣服，独自入睡。

实在是太空虚了。

自己并不是为了被人称赞而成为水神的。

伊佐露缇的心中存在着与剑士不同的自己。

那个存在总是孤独的。因此感到了无止境的空虚。

也不知道结婚以后有了丈夫与小孩，是否就能治愈另一个自己。

但是，当自己受到称赞回到家之后，最好还是有个能听她自夸的对象。

说不定那个对象会在伊佐露缇自夸完之后，提出非常变态的行为......

......不对，已经做好觉悟了。

「所以，下次的对象要什么时候见面，在哪里？」

「是，听说今天会派马车过来这边迎接。」

「王族亲自来迎接，是吗......」

「对。」

结婚候补还剩三人。

伊佐露缇虽然不晓得，但她已经轻描淡写地拒绝了五个人，这让剩下的几人决定拿出真本事。

他们透过严格的抽签结果决定顺序，打算逐一认真地对她发动攻势。

「......嗯？」

这时，伊佐露缇注意到了。

「道场那边有点吵呢。」

道场就邻接克尔埃尔家。

话虽如此，这个地方也可以说是水神流的当家，占地面积相当广。

本来的话是听不到声音的，但伊佐露缇好歹也是水帝。

既然听到吵杂的声音，而且其中还带有怒气与杀气，再怎么样也会注意到。

「会不会是已经到了呢？」

「比我听说的时间还要早......不，也有可能是我记错时间了。不管怎么样，我先过去了。要是有个万一，对王族失礼可就糟糕了。」

「说得也是，赶紧过去吧。」

伊佐露缇与丹托里斯互相点头，随后走向道场。

\\

道场吵吵闹闹的。

穿着道服的门徒围着一个男人，对着他发出怒吼，不断挑衅。

「啊，师傅，有人来踢馆！这个男人突然出现，说要叫师傅出来！」

伊佐露缇和丹托里斯听了，顿时脸色发青。

门徒用这种态度对王族的话，很有可能导致道场被勒令关闭。

想必他并没有自我介绍吧。说自己是阿斯拉王家的人，是来迎接伊佐露缇的。

「快住手！」

伊佐露缇大声喝斥，现场顿时鸦雀无声。

「把路让出来！那个人是我的客人！」

「......但是，这个男人......」

「所有人都到道场的旁边跪坐！」

伊佐露缇一声令下，门徒们便像鸟兽散那样纷纷让开，移动到道场的旁边列队而坐。从上一代开始，就只有这个动作大家都很快。

总之，先不管这个。必须快点赔罪才行。

伊佐露缇这样心想，望向门徒们退开之后的前方。

「......？」

在那里的是身高超过两公尺的壮汉。光肩幅就将近一公尺，有着犹如岩石般的巨躯。

然而，伊佐露缇对那个巨躯有印象。

「杜加？」

「......哦。」

伊佐露缇一叫，转头过来的脸果然是他。

实不相瞒，他正是阿斯拉七骑士之一「王之门卫」杜加。他有点怯生生地把身体缩起来，一脸无所适从地站在原地。看到伊佐露缇后，他便用松了口气的表情重新朝向这边。

「你们捡回了一条命呢。这男人是北帝杜加，如果他认真起来，只要单手将能将你们......」

伊佐露缇说到这里，不经意地注意到了杜加的服装。

那是骑士的礼服。

伊佐露缇没看过杜加穿礼服的样子。因为他平常总是穿着黄金铠，不然就是深灰色的铠甲。就像在表示那才是正装一样，而且爱丽儿也没有说什么。

现在他的模样看起来和平常不同，感觉很拘束，而且手上还捧着花束。

因为杜加身材高壮，花看起来很小，但也是相当大的花束。

「你为什么在这里？陛下出了什么事吗？还是说，是紧急召集？」

伊佐露缇疑惑地皱起眉头。

与她对照之下，杜加用慢条斯理的动作靠近，将手上那把花束递给她。

在这个当下，伊佐露缇不禁觉得「该不会......」。

正装、花束。

当然，「不可能有那种事」的想法也同样强烈。

但是杜加的下一句话证实了她心中的「该不会」。

「伊......伊佐露缇•克尔埃尔小姐......我喜......喜欢你！请......请和我......结婚！」

\\

想不到，杜加竟是阿斯拉王家的人。

\\

仔细想想，这件事有迹可循。

他是唯一负责爱丽儿私人房间警备工作的男性。

除了路克是特例以外，那个房间连香杜尔也不能带武器靠近，而杜加负责在那警备。

即使在深夜，他也依然站在爱丽儿的私人房间前面。

而且，也没听过他已经去势的传闻。

尽管传言说杜加是个安全且无害的男人，但他终究是个男人。

这身巨躯加上北帝级别的战斗力。有这两个条件，要袭击爱丽儿的寝室根本是轻而易举。

伊佐露缇一直抱有疑问，为什么会是这样的男人守在那里？

不过，没错，如果他是爱丽儿的亲人呢？

如果彼此是从小就熟识的关系......

听说杜加出身于阿斯拉王国偏远地区的乡村，但王族也是有各式各样的人。

就像爱丽儿也曾经一度逃到遥远的异国之地，若杜加也是在年幼时期隐藏身分的话......

「伊佐露缇。」

听到丹托里斯的呼唤，伊佐露缇从思考之海返回现实。

刚才的想法说不定很危险。杜加恐怕是阿斯拉王国黑暗面的一角。要是随便触碰，就算是伊佐露缇也可能被消失。

「怎么了？」

该面对的是眼前的现实。

「......没事。」

伊佐露缇重新看向杜加。

他刚才是这么说的。

「请和我结婚」。

他肯定是这么说的。

因为这是伊佐露缇有段时期非常想听到的话，不可能听错。

杜加的态度非常坦荡。他光明正大地从大门进来，亲手递上花束，告诉伊佐露缇「请和我结婚」。

伊佐露缇个人是比较喜欢再浪漫一点。

不过，根据想法的不同，这样做其实也可以称为浪漫。

在众目睽睽之下递上花束，堂堂正正地告白，在伊佐露缇脑内的浪漫清单当中也记载了这样的场景。

当然，地点并不是在充满汗臭味的道场，而是像美丽的喷泉前面，或是金碧辉煌的派对会场之类......

这点就睁一只眼闭一只眼吧。

其他的各种大小事情也可以视而不见。

「......这时机恰到好处不是吗？如果是享誉盛名的阿斯拉七骑士，也配得上你了吧。」

「是......不过，可是......」

这时，伊佐露缇注意到周围的视线。

是门徒们的视线。

「总之，先换个地方吧。杜加，请跟我来。」

「嗯。」

伊佐露缇转过身。

杜加因为递出的花没有被她收下，一瞬间露出了难过的表情，但立刻就跟在伊佐露缇的后面移动。

\\

就这样，杜加被邀请到伊佐露缇的家中。

现在，他坐在沙发上僵硬地缩起身体，坐得很拘谨。腿上依然放着那把花束。

然后，伊佐露缇坐在他对面。

她的坐姿凛然美丽。其氛围令人感受不到气息，面无表情。

说不定会让人产生她其实什么都没在想的错觉。

丹托里斯并不在这里。

他把两个人留在接待室后，便去准备茶水了。

「......」

在这段期间，伊佐露缇目不转睛地看着杜加的脸。

杜加感受到那股视线，不禁摆出严肃的表情。从脸颊在不断颤抖的这点来看，他显得相当紧张。

但是，伊佐露缇看的不是那边，是脸。

纯朴的脸。不是伊佐露缇喜欢的类型。就算对许多事情睁一只眼闭一只眼，但他终究不是自己喜欢的类型。

「............」

老实说，她甚至觉得与杜加相较之下，反而是之前的五个人更好。

既然几乎都是一样的条件，那么脸更为俊俏的他们自然更加出色。

但是，下一个来的王族说不定会比杜加还丑。

话虽如此，自己才刚跟哥哥有过那番对话。

必须在这次决定才行。

「不过话说回来，没想到你竟然是王族，真是让我惊讶。」

伊佐露缇在叹了口气的同时这样说道，杜加听到后露出错愕的表情。

「我，不是，王族。」

「......咦？那么是养子还是什么吗？」

意思是他在隐藏自己王族的身分吗？

伊佐露试探性地这样询问。

「我，出生在多纳提领地的小村庄，一直都在当门卫。爸爸是村子里的士兵──」

但是，从杜加说出的是一个极为平凡的士兵飞黄腾达的故事。

不对，或许并不平凡。

伊佐露缇想从这番话的内容当中听出一些端倪，但是杜加说到妹妹结婚的时候，突然就流下了眼泪，让伊佐露缇不小心带入了感情，差点就哭了出来。

「然后，我，听到，伊佐露缇......小姐要结婚了，想说至少要在那之前，把自己的心意告诉你。」

「......」

不过，这代表他是与王族完全无关的人。根本不是爱丽儿介绍的王族。

伊佐露缇认为这样的话，还是得拒绝他。

虽然有点可惜，但必须给愿意介绍王族给自己的爱丽儿一点面子。

（嗯？可惜？为什么？）

然而，她此时突然对自己的想法产生了疑问。

不过，立刻就有了结论。

他是个老实人，勤勉、一心一意。就刚才听到的感觉，关于性癖那方面似乎也不会让人退避三舍。

具有足以成为北帝的实力，既然是七骑士，代表薪水很稳定。虽然喜欢喝酒，但也不会酒后乱性，而且也与花钱的玩乐无缘。

不行的只有脸。也不是说真的不行，只是稍微不太符合伊佐露缇的喜好。

「那......那个......！」

和面有难色的伊佐露缇相较之下，杜加意志坚定地说道：

「我......我，第一次见到，伊佐露缇小姐的时候，就觉得你像这朵花一样漂亮，后来就，那个，一直喜欢你！」

杜加这样说完，再一次把花递给伊佐露缇。

「这样啊，从第一次见面的时候。」

伊佐露缇的视线里满是花朵。

那是深蓝色的花。伊佐露缇不晓得这种花的名字，但她觉得很美丽。

被说像这朵花，让她不禁心动了一下。

「......哦。」

如果伊佐露缇没记错的话，与他第一次相遇是在战斗中。

为了选出爱丽儿的护卫，而与杜加战斗的那个时候。

他说从当时就一直喜欢着自己。

回头想想，他对伊佐露缇比较温柔，一直信赖着她。明明要进去爱丽儿的房间却也没把武器收走。

当然，有部分是因为他们同样都是七骑士，但或许不仅如此。

这样一想，杜加以认真的表情看着伊佐露缇的那张脸，帅度大约增加了两成左右。

不知为何，现在觉得这张脸也不坏。

若是以不同的角度来看，反而还有点可爱。毕竟他平常都戴着头盔，根本就看不见。

她甚至开始这样想。

「不对不对......！」

伊佐露缇摇了摇头。

「非常抱歉，我已经与爱丽儿殿下说好要和她介绍的王族结婚。」

没错，假如现在和他交往的话，很可能会有损爱丽儿的名誉。

伊佐露缇也是骑士。尽管并没有发誓要绝对效忠，但她发过誓要对爱丽儿尽忠。

绝不能因为自己的理由损害到爱丽儿的名誉。

「既然你也是陛下的骑士，就不能违抗陛下的意图吧？」

「......哦。」

杜加露出有点困扰的表情。

就像是伊佐露缇决定这么做一样，杜加也是骑士。

而且杜加为人勤勉。就算他不是王族，也因为获得了爱丽儿的信任而成为了那个场所的门卫。他不可能会做出背叛爱丽儿的行为。

「......那么，请你回去吧。」

「哦。」

伊佐露缇本以为他会稍微纠缠一下，但杜加随即起身，背对伊佐露缇。

非常干脆地就离开了。

他的背影看起来甚至意气风发。简直就像是打从一开始就知道会被拒绝，只是把想说的说完以后痛快多了那样。

正因为觉得他有点不错，那样的态度反而让伊佐露缇感到有点可惜。

「......呼。」

伊佐露缇叹了口气，望向桌子。

有片蓝色的花瓣落在眼前。

并不是花束。想必他已经带回去了。

「至少该把花束收下才对呢......」

伊佐露缇用手指捻起花瓣，喃喃这样说道。

\\

到头来，伊佐露缇那天依然拒绝了下一个王族。

\\

★　★　★

\\

隔天。

伊佐露缇城里在练兵场从事着剑术指导的工作。

在教导士兵与见习骑士剑术的时候，她反省了昨天的事。

昨天的王族。

弗雷札•卡利乌斯•阿斯拉。性癖依然很糟糕，但不是什么坏人。

可是与杜加相比，他明显不够诚实。

不过，应该不用那么快拒绝，而是选择先暂时保留的话，关系也不会恶化......

不管怎么样，还有两个人。只剩下两个人。

必须仔细地看清这两人的本质，选出其中一个才行。

当她这么盘算时，传令兵走到她身边。

「伊佐露缇小姐！陛下有要紧事找你！」

听到这句话，伊佐露缇便了解爱丽儿的目的了。

八成是因为自己不断拒绝候补者，爱丽儿要直接斥责她了。

必须欣然接受责备才行。伊佐露缇自己也认为必须向爱丽儿赔罪。

「我知道了。」

伊佐露缇这样回答后，离开了练兵场，直接走到练兵场出口的骑士隔间，迅速拍掉了尘土。本来起码得冲个澡才行，但既然爱丽儿十万火急，想必不这么做也会通融的吧。

随后，她快步地走向王之间。

「嗯？」

愈靠近里面，愈觉得不对劲。

这里好像比以往更加吵闹。平常明明不会有士兵或是骑士，走廊上始终是空无一人才对，但现在却看到士兵手忙脚乱地到处走动。

发生什么事了吗？

虽然这样想，但现在以陛下的传唤为最优先。

伊佐露缇没有特别去问周遭的人，迈步走向王之间。

\\

然后，她到达王之间。

在入口豪华的大门前，伊佐露缇皱起眉头。

因为应该在那里的人不见踪影。

有着犹如岩石般的巨躯，身穿黄金铠甲的男人。

爱丽儿在这个房间的期间他绝对不会乱动，是阿斯拉王国最强的门卫。

杜加。竟然哪里都没看到他的身影。

仿佛是在代替他似的，驻守在城里的骑士整齐地列队在王之间的周围。

全员的腰间都佩戴着武器。

戒备森严。

而且，所有人都是高手。甚至还有原本无法靠近这里的那些下级、中级贵族出身的骑士。想必是希尔贝斯托的指挥吧。这种时候他不会惧怕有什么后果，而是采取最适当的行动。

「伊弗利特卿！」

然后，伊佐露缇在那里看到了一个人。

那就是王城的警备负责人「王之城墙」希尔贝斯托•伊弗利特。

「这不是伊佐露缇小姐吗？你来得真快呢。」

「这到底是出了什么事？」

这样一问，希尔贝斯托顿时面有难色。那是在烦恼该怎么说明才好的表情。

几秒后，他耸了耸肩，这样说道：

「陛下在叫你。」

就像是在表示所有事情都进了房间之后再问吧。

伊佐露缇放弃由他说明，敲了敲门。

「伊佐露缇•克尔埃尔，前来参见陛下。」

「请进。」

爱丽儿的声音一如往常。

与周围森严的气氛相反，她的声音实在过于正常。

「失礼了。」

伊佐露缇开门进去。

接着呈现在眼前的，是不可思议的景象。

坐在办公桌旁边的爱丽儿。在旁边环着双臂，一脸疲惫的路克。一脸严肃，拿出武器在旁待命的近卫侍女们。

然后，是杜加。

鲜少进入房间的杜加就在那里。他抱着黄金头盔，另一支手拿着稍稍枯萎的花束。

「伊佐露缇，辛苦了。你来得真快呢。」

「因为我刚好在练兵场............请问，这到底是怎么一回事呢？」

伊佐露缇这样询问，爱丽儿便轻描淡写地回答。

「杜加说，他不当我的骑士了。」

「咦！」

伊佐露缇看向杜加。

杜加的表情很严肃。好像不是为了开玩笑而做出这种事。

「呃，所以，这是怎么一回事？」

「好啦，这点就请杜加说明吧......杜加，可以再说一次吗？」

爱丽儿这样说完，把视线移到杜加身上。

杜加点头，开始说道：

「伊佐露缇，说了，因为我是爱丽儿大人的骑士，不能和我结婚。」

「......！」

他只说了这句话。

伊佐露缇从这句话就察觉到自己为什么会被叫到这里。

「不是的！我只是不希望让陛下丢脸，所以才会说『既然是陛下的骑士，就不能违抗陛下的意图吧？』──」

「请你安静地把话听到最后。」

听到爱丽儿沉静的声音，伊佐露缇顿时静了下来。

但是，伊佐露缇的内心并不平静。

根据对话的走向，很有可能会变成是自己在唆使杜加背叛。

不，根据房间外面那种煞有其事的状况来看，想必已经被这样认为了。

明明没有那个意思啊......

「杜加。」

或许是因为杜加对伊佐露缇内心的想法不得而知，他在爱丽儿的敦促下用结巴的语气说出理由。

「我，仔细想过了。我，和爸爸约好要保护妹妹。爱丽儿大人说过，保护国家就等于是保护妹妹。因为爱丽儿大人是国王，保护好爱丽儿大人，就是保护这个国家。」

「可是，妹妹她这样说，我已经保护她很久了。不需要我再操心，这次就去保护自己喜欢的人吧。」

「我，喜欢，爱丽儿大人。也喜欢这国家，想要保护这里。可是，我更加，特别喜欢伊佐露缇。所以，我不当，爱丽儿大人的骑士。不当之后，我想保护伊佐露缇。」

杜加说着说着，将黄金头盔放到办公桌上。

接着他转身，将花束递给伊佐露缇。

「......」

递到伊佐露缇眼前的深蓝色的花，已经有些枯萎了。

和昨天同样的花束。

「所以，事情就是这样......伊佐露缇，你决定如何？」

「咦？」

听到突如其来的告白，伊佐露缇不断眨眼。

「我不知道你提出了什么样的条件，但他似乎是选择你，而不是阿斯拉七骑士。真是幸福的女人呢。你打算怎么做？」

这句话──

看样子不是想要责备伊佐露缇唆使杜加背叛。

而是在问伊佐露缇要怎么回答杜加的告白。

「可......可是，爱丽儿大人介绍的那些人......」

「你就忘了那群人吧。」

\\

伊佐露缇的胸口从刚才开始就不断狂跳。比起在毕黑利尔王国与斗神对峙的时候更令她心跳加速，仿佛会这样直接晕倒。

实际上，伊佐露缇现在满脸通红。

「我......我......」

这时，她突然想起初代水神的轶闻。

舍弃一切，嫁给水神的那位公主。

根据昨天听到的那些话，杜加是个几乎一无所有的男人。

巨躯与力气、为数不多的家人。然后，就是阿斯拉七骑士的地位。

他只拥有这些。

这样的他不惜舍弃自己的家人与七骑士的地位，选择了伊佐露缇。

而且这件事情昨天才刚发生。他虽然说仔细想过，但几乎是立刻做出决定。

杜加刚才那番话，就是伊佐露缇在他心里比任何东西都更有价值的证明。

与至今的贵族还有透过爱丽儿介绍见面的王族不同。他们并不会为了追求伊佐露缇而舍弃自己所拥有的最重要的东西。

没错，杜加就像嫁给初代水神的公主那样......

在这个世上如此喜欢伊佐露缇的，说不定就只有杜加一个人。

这样到底还有什么不满呢？

长相根本就无所谓了不是吗？

「......」

回过神来，伊佐露缇已经接下了花束。

大大的花束，蓝色的花。稍稍枯萎的花，犹如在象征着伊佐露缇。

就算花朵枯萎，杜加也肯定还是会喜欢吧。

到头来，花的美丽也不过是一时的。

「小女子不才，请多多指教。」

「......哦！」

眼见杜加笑容满面，周围自然地响起热烈的掌声。

\\

★　★　★

\\

后来，在王之间的求婚事件被广为流传，就连底层的士兵都知道。

杜加的前同事高兴得流下眼泪，对伊佐露缇抱有憧憬的人则是哭湿了枕头。

杜加不当七骑士，而是成为了伊佐露缇的丈夫。不是七骑士杜加，而是家庭主夫杜加......虽然大家都是这样想的。

「虽然你说不当我的骑士，但伊佐露缇也是这个国家的骑士。她的实力虽然非常高强，但一旦我死去，国家就会变得不稳定，这样一来她也有可能遭到谋杀。当然，你到时应该也会保护她......不过只要我不死，这种事就不会发生。如何？你要在保护伊佐露缇的同时，顺便保护我吗？」

杜加被爱丽儿的花言巧语所哄骗，继续维持骑士的地位。

贪婪的爱丽儿是不会让北帝杜加逃出自己的手掌心的。

当然，为了追究他让王之间陷入骚动，给他追加了一点劳动作为惩罚，但也不是什么大不了的事。

至此，不仅是伊佐露缇，爱丽儿也成功地让杜加对自己更加忠诚。

阿斯拉七骑士的关系变得坚如磐石，这样的结果对爱丽儿来说自然是再好不过。

虽然因为之前要求其他王族去相亲而欠了他们人情，但不过只是小事。

不过在结婚之后，杜加守护王之间的时间锐减。

他晚上会准时回家，当伊佐露缇出远门时一定会跟在身旁。

就结果来说，伊佐露缇的工作内容也改成爱丽儿的专属护卫，不过这件事先暂且不管。

就算笨拙，伊佐露缇也答应了杜加的婚事。

她设下在结婚之前要交往一阵子的规定，实际结婚是在一年后。

由于有过这样的期间，所以即使在结婚之后也流传着一个传闻。那就是其实只有杜加单方面地释出好意，伊佐露缇会不会没那么喜欢杜加？

因为在王城的时候，伊佐露缇对杜加的态度比以往都还要冷淡。

但是这样的传闻也因为伊佐露缇在士兵前面不小心叫了杜加一声「达令」，然后脸红地订正过来的这起事件为开端，很快就消失了。

在两人独处时，他们肯定就像一对鸳鸯般相亲相爱吧。

就这样，两个人成为了夫妻。

** 「从前被称为狂犬的女人」(特稿短篇)

最近，吾友杜加好像结婚了。

北帝杜加。没错，是我的救命恩人，温柔体贴又力大无穷。

老实说，听到他要结婚的消息时我很不安。

因为他很纯朴。我想说他肯定是被坏女人蒙蔽了双眼。

万一他遭到坏女人所骗，这次就轮到我去救他了。我要向爱丽儿告状。

我像这样提起干劲打算调查的时候，艾莉丝收到了一封信。

是一名叫伊佐露缇•克尔埃尔的女性寄来的。

没错，就是那个水帝伊佐露缇。在毕黑利尔王国的战斗时救了我们的清纯系美女。

她寄来的信上写到她顺利当上了水神，继承了列妲之名。

而且，也因此结了良缘，顺利结婚......

......那个对象，据说就是杜加。

换句话说，杜加和那位端庄的女性结婚了。

真是值得庆祝。不过，虽然在毕黑利尔王国承蒙她的帮忙，但说不定她平常是个坏女人。这样的可能性是无所不在的。

我抱着这样的疑虑询问艾莉丝她是什么样的人，但似乎并不是坏人。

不过，不能因为艾莉丝对她没有坏印象就不是个坏女人。

我抱着这样的疑虑前往阿斯拉王国，自然地向爱丽儿打听这件事，不露痕迹地向路克打听这件事，意有所指地向基列奴打听这件事，从遮蔽物后面观察杜加，前去水神流的道场打招呼，向克尔埃尔的当家打听这件事......

当我做了这些事情之后，爱丽儿挖苦地说「没想到你这么闲呢？」。

不，你误会了。我不是因为很闲才做这种事，只是不希望救命恩人莫名其妙遭到陷害。

不管怎么样，这么做的结果让我得知了一个事实。

伊佐露缇似乎会凭长相来挑选结婚对象。

果然是坏女人啊伊佐露缇，那么我鲁迪乌斯也不能保持沉默了......我持续调查的结果发现，这两个人──好像很恩爱。

杜加看起来非常幸福，伊佐露缇好像也会在没有旁人的地方叫杜加达令，跟他打情骂俏腻在一起。

尽管有情报指出伊佐露缇会看长相挑选男人，但最后她选择了杜加。想必她在那个当下从杜加身上发现了长相以外的优点吧。她肯定是经过了一番迂回曲折，才认为杜加是个不错的对象。

不过我也半斤八两就是了。直到被杜加救了一命之前，我都觉得他是个派不上用场的慢郎中，我是个坏男人。Bad
guy。那么我也只能承认伊佐露缇了。

由于得到了这样的结论，我便对他们两人献上祝福，就这样回去了。

不过话又说回来，伊佐露缇和杜加啊......谁会和谁在一起真的是难以预料呢。毕竟我自己也没想过竟然会和三个人结婚。

我内心涌起这样的感慨，踏上归途之后过了几天。

\\

「我想去兽族的村子！」

\\

是艾莉丝。

她最近因为伊佐露缇结婚而显得相当开心，不过现在是躺在沙发上发懒的时间，为什么会突然切换到这个话题？

「怎么了，这么突然？」

我在艾莉丝的右侧坐下，这样询问。

顺便说一下，艾莉丝的左侧是普露塞娜。她躺在艾莉丝的腿枕上看着书。

所以我的座位有点窄。

不管是莉妮亚还是普露塞娜，现在感觉都像是艾莉丝的手下，普露塞娜同时也是雷欧的随从，经常会待在我家，也常像这样和艾莉丝腻在一起。

普露塞娜很像狗，所以才会很亲近愿意陪她的艾莉丝吧。

顺带一提，莉妮亚很不擅长应付艾莉丝。因为那家伙很像猫，好像讨厌对方太过积极。

再补充一件事，雷欧现在缩在艾莉丝的脚边，菈菈与齐格在缩成一团的雷欧怀里睡着午觉。

就算艾莉丝刚才那么大声，他们好像也没有要醒来，想必已经习惯了吧。

这段和平的时光让我感到无比平静。

好啦，不过话说回来，兽族的村子啊。

对艾莉丝而言，兽族的村子算是乐园，也是剧药。

去了兽族的村子，那里有很可爱的兽族，回过神来发现那个兽族的小孩在我们家......如果真的发生这种事可不是闹着玩的。

「你还记得以前去的时候，我们不是和莉妮亚她们的妹妹很要好吗？我很在意她们现在过得怎么样！」

是叫蜜妮托娜和提露塞娜来着吧？

我记得她们两人现在应该都甩开自己的姐姐，成为出色的战士长候补了。

......要是普露塞娜没有失势，她们可能就不是候补，而是辅佐之类的位置吧。

普露塞娜也是，她也有可能不是躺在这种地方慵懒地过着生活，而是作为战士长当个工作俐落的职业女性。

不过，虽然说是失势，普露塞娜现在好歹也是我们鲁德佣兵团的副团长。

她正为了我们公司鞠躬尽瘁。

佣兵团如今已壮大不少，感觉她们也爬上了与其相符的地位。

所以她们看起来并没有那么着急。

「记得吗？你之前说过等菈菈长大就要过去吧！」

「......我记得当初是说等菈菈十五岁之后吧。」

「就算在那之前去又有什么关系！」

「这样讲也没错。」

菈菈是会成为救世主的存在，既然她和雷欧今后也依然会是心灵相通的关系，那么从小就让她与兽族深交也不错。

话是这样说。

「突然过去会不会给他们添麻烦？」

「不要紧啦！对吧，普露塞娜？」

「突然跑过去也没问题的说。」

普露塞娜不以为意地回应。

「你虽然说没问题，但你也要去喔。」

「那又怎么了的说？」

「你不会抗拒吗？」

普露塞娜上次对村子里的库存粮食出手而被押送到牢房，话虽如此，由于也有酌情从宽的空间，便判处她担任雷欧的随从。

如果她一直做到菈菈成年为止，好像会让她回到族长候补的位子啦......

不过这样看起来，她似乎已经没办法出人头地了。

普露塞娜现在才回去摆出族长候补的架子，我不认为那群顽固的兽族会认同她。

「老大，我是鲁德佣兵团的副团长......就算说是这个群体的副队长也不为过的说。虽然待在莉妮亚底下让我很不是滋味，但必须对其他群体摆出具有威严的态度才行的说。」

「不，你好歹也是德路迪亚族的族长候补吧......」

这家伙该不会已经放弃当族长了吧？

该怎么说呢，她是不是觉得就算当不成族长，如果是鲁德佣兵团的副团长的话倒也不错这样？我们在世间只算小型企业耶。

「呵呵，老大根本什么都不懂的说。身为鲁德佣兵团副团长的我将会成为德路迪亚的族长。因为这代表德路迪亚族能与强大的群体扯上关系的说。这点在族长选拔当中会是领先别人一步的要素的说。简而言之就是凯旋而归的说。能抬头挺胸回去的说。」

与我建立关系的当下，德路迪亚族应该就已经和鲁德佣兵团有关了就是......

话虽如此，也不知道何时会切断与我之间的关系。

意思是将血缘分散到两边会更让人放心吧。

「啊，不过可以过一阵子再带圣兽大人与菈菈大人回去的说。」

「哦。那是为何？」

「对兽族而言，圣兽大人踏上旅程具有特别意义的说。一定会举办仪式之类，会有一半的成分当成祭典盛大举办的说。原本是要等到那天才会第一次看到救世主大人的说。而且这样做是有意义的说。」

所以，现阶段最好别让他们看到菈菈的脸。

「德路迪亚族肯定会花上好几年进行准备的说。他们到时会征求大森林各个种族的协助，盛大地举办的说。」

「原来如此......关于金钱方面，其实由我支援也没问题。」

如果是整个种族一起举办的祭典，靠我口袋里的钱或许不够用。

不过，我也是格雷拉特家的一家之主。

既然是我女儿菈菈的重要时刻，我就会堂堂正正地向我们公司的社长下跪借钱。

「那样不行的说。德路迪亚族也有自尊的说。我们种族就是为了这点才会被交付担任兽族的队长的说。全都会由自己负责的说。」

应该是所谓的习俗或是惯例吧。

尽管很没效率，但既然德路迪亚族是抱着自尊处理一切，我就没有一丝妨碍他们的意思。

「不过，现在就开始安排也没关系的说。」

「说得也是。」

我们这边不知道到时会举办什么仪式，当然也不晓得该让菈菈做好什么准备。

虽然应该不会是什么危险的仪式，但还是先知道会做什么比较安心。

「那么，我们就去一趟吧。」

「决定了呢！」

艾莉丝猛然起身。普露塞娜顿时倒了下去，发出了惨叫。

或许是这时压到了雷欧的尾巴，雷欧发出了低吼，普露塞娜立刻低头道歉，菈菈用惺忪的睡眼抬起头看了一眼，朝着我张开双手，所以我将她抱了起来。

「好啦，我们走吧！」

「先等一下，我得先请示奥尔斯帝德大人。毕竟说不定会很忙。」

「咦──！」

艾莉丝表现出不满，但我不打算抛下工作跑出去玩。

话虽如此，既然是与菈菈有关的事，社长也不可能会反对。

基本上，一直以来他从未说过「如果有时间去做那种事，不如先完成这个」之类的话。

而且也不能一直承蒙好意。

「啊，对了。」

我开始朝着要去的方向研究时，打算离开客厅的艾莉丝像是突然想到什么那样发出声音。

「也带基列奴一起去吧！」

「呃，她不会去吧。」

我不是很清楚基列奴在德路迪亚村受过什么样的待遇，但想到裘耶斯当初的态度，肯定不会有什么像样的过去。

「为什么啊！基列奴是阿斯拉王国的骑士耶！前阵子遇到她的时候还穿着金色的铠甲！如果照普露塞娜说的，就是凯旋而归吧！」

「......艾莉丝说得没错的说。」

普露塞娜完全不把视线朝向这边，而是一脸尴尬地把尾巴从双腿间拉出来，用手指不断摆弄着前端。这家伙完全屈服于同侪压力了。她那张脸，绝对知道基列奴在村落那边遭遇过什么样的待遇。

「......」

不过，感觉基列奴对德路迪亚族也没什么特别的想法。

裘耶斯最后好像也对基列奴的看法改观了，或许有个和解的机会也未尝不可。

照这样下去，基列奴一辈子都无法回到村落，说不定在临死之际会突然说出「要是至少回去个一次也好」。

「好吧。去问问看。」

「太好了！」

艾莉丝意气风发地离开了客厅。

不知为何，雷欧也跟在她的后面离开。齐格依然坐在它的背上。

留下来的只有普露塞娜，还有重新在我怀里入睡的菈菈而已。

总之，我注意不要吵醒熟睡的菈菈，重新在沙发上坐好。

普露塞娜也像什么事都没发生过那样坐在沙发上，将头靠在我的腿上。

我动了脚把她的头甩下去。

「好痛的说。」

「别擅自把头靠在人妻的腿上。」

「小气的说。而且老大不是妻子的说，是丈夫的说。」

「在艾莉丝面前我会变成少女啦。」

「法克的说。」

也没什么小不小气的。要是在我心爱的女儿面前产生发情的味道该怎么办。

这样一想，普露塞娜就改变了头的位置，将脚靠在我的腿上。

嗯，这样倒是可以。今天她不是穿裙子，所以也看不见腿。而且普露塞娜的尾巴前端好柔软，摸起来很舒服。

「我想问一件事......对你们而言，基列奴是什么样的存在？」

「爸爸他们似乎有自己的想法，但对我们来说是个帅气的姑姑的说。离开村落，只靠一把剑就让自己爬上剑王的位子，这种事很难办到的说。她是崇拜对象的说。我们那个世代的人大概都是这样想的说。」

「哦──这样啊。」

虽然内心还是有些不安......

不过既然普露塞娜都这样说了，应该是可以设法处理看看。

若是基列奴本人说不想去的话，这件事就到此结束，但我不认为那个基列奴会拒绝艾莉丝的邀请，就以她会去为前提来处理吧。

\\

★　★　★

\\

社长二话不说就答应了。

他说务必去一趟，甚至还让我们带了伴手礼。

听到这件事的新进员工在旁边聒噪地说什么「要去哪里！要和谁去！是和那个剑王基列奴吗！到底要和什么人战斗！」，我想说就算详细说明他也没办法理解，就随便敷衍了一下，他就自己接受了。那家伙好像意外地很好打发。

\\

然后，出发当天。

莉妮亚＆普露塞娜与基列奴正式碰面。

「初次见面喵！我是莉妮亚娜•泰德路迪亚喵！」

「我听过很多你的传闻的说！我是普露塞娜•亚德路迪亚的说！」

见到基列奴的这两人显得相当毕恭毕敬。

该怎么说呢，就像是见到老前辈的体育系一样。

「我们两个非常憧憬先离开村落，扬名立万的基列奴姑姑喵！」

「本想说等到我们总有一天也出名了，再去向姑姑打招呼的说！」

「我是基列奴•泰德路迪亚。请多指教。」

至于基列奴，就像是引退的暴走族族长那样落落大方地点头。

她的态度绝不会过于谦卑，但也没有摆架子，甚至还显得游刃有余。

感觉就像经过仔细调教过的大型犬。

是我所认识的，一如往常的基列奴。

「不过话说回来，你真的可以一起去吗？不是有什么要事吗？」

我与艾莉丝一起去见基列奴的时候，她在练兵场正与香杜尔还有伊佐露缇在讨论些什么。我本来想说她正在忙的......

「嗯，其实之后要教骑士们新的剑术......」

「这么说来，是有听过这件事。」

我是从爱丽儿那边听来的。

现在在阿斯拉王国负责指导剑术的凑齐了剑神流、水神流及北神流的三个人。

虽然其中一人是个根本不打算教导剑术，却总是想对培育后辈的方针插嘴的老害小鬼臭老头......但先不提这个，有三个不同流派的人，势必会引发什么状况。于是，他们在香杜尔的提案下决定要进行某个实验。

那就是取出剑神流、水神流及北神流的优点，创造一个全新的流派，发展成属于阿斯拉王国骑士的剑术。

剑王、现任水神以及前任北神都各自教导自己的流派，然后再由前任北神巧妙地统整起来，创造出新的流派。

要我说的话，「这样只是诞生出北神流的新派阀而已吧？」，可是──

「我只知道以前教过你的那套做法。细微的调整就交给别人了。」

基列奴的存在意外地起了不错的作用。

基列奴虽然认真却很笨拙，也只会用自己知道的那套方式教人。

因此，阿斯拉骑士剑术是以剑神流为主体，再将水神流与北神流融合起来。

「不过，正因为这样反而更忙吧？」

「是啊......不过，艾莉丝大小姐都那么说了。」

基列奴的视线前方正如所料，可以看到艾莉丝的身影。

艾莉丝环起双臂摆出熟悉的姿势，看起来比平常更加开心。

「我已经不是大小姐了！」

「说得也是，艾莉丝夫人。」

基列奴露出苦笑后，莉妮亚与普露塞娜也嘻嘻笑了。

「什么啦。」

「今天的艾莉丝看起来很开心喵！」

「感觉比平常还要像小孩子的说。」

「什么啦......」

艾莉丝依然是摆着同样的姿势，用力把脸转到旁边。

不管怎么说，艾莉丝现在依然非常喜欢基列奴。

现在不仅有新的家，也有自己的家人。但是对艾莉丝来说，菲托亚领地的要塞都市罗亚......也就是以前在她老家的家人，感觉就只剩下基列奴而已了。

应该就像是年纪有些差距的姐姐或是堂姐，再不然就是关系很好的姑姑。

一想到又能和基列奴一起出外旅行，她就开心得喜不自胜。

「那么，我们走吧。」

就这样，我们再次前往大森林的德路迪亚村。

\\

★基列奴★

\\

我的人生刚开始的时候，绝非是一帆风顺。

\\

兽族偶尔会生出被称为「还兽」的孩子。

一言以蔽之，就是没有理性的孩子。

特征是从出生的时候就长着牙齿，仿佛在畏惧着什么的野兽般大吵大闹。

连语言都记不太起来，只是对一切露出敌意。

我也曾是那样。

尽管年幼时期的事情几乎不记得了，但我懂事时内心就被愤怒所支配。

对身体的一切感到拘束、痛苦，对所有存在都感到不耐烦。

周围的所有人都是敌人。

我从未想过自己为何会那么想。到了现在也依然不明白。

只是，如今那股愤怒依然盘据在我的内心深处，要是有什么事情不顺眼，立刻就会火冒三丈。

存在于记忆中的，尽是发出怒吼的大人以及一脸畏惧的那些兄弟。

「还兽」现象多半会随着成长而收敛，基本上会在五岁左右缓解成脑袋稍微有点不舒服的症状。

但我并不是那样。就算过了五岁，我依然逞凶好斗。

是个让人束手无策的坏孩子。

说到五岁，某种程度上已经是能够思考事情的年龄，但我的脑袋空空如也。是个始终脾气暴躁的孩子。

同年龄的孩子基本上都曾经被我打了个半死。这么做没有任何意义。只是因为看到的时候很不爽就动手了。

德路迪亚村会把那样粗暴的孩子脱光，将冷水泼到身上。根据状况的严重程度，也会将他一整晚都关在漆黑的仓库。

大部分的兽族被这样惩罚之后就会变老实。因为我们的天性就是如此。

不过，我并不是这样。因为「还兽」的孩子并不是这样。

......不，就算是现在我也无法理解。有人会因为被那样对待就屈服吗？

总之，如同你们也知道的，无法治好的孩子会在某天发生「意外」而死。

就像是要那个孩子去死一样，会在晚上故意将人丢在魔物横行的森林。

我也差点就被这样做了。不，他们确实这么做了。

我是笨蛋。连自己受到什么样的对待都不晓得。

就算这样，我还是隐隐约约地感觉到整个村落都想把我排除掉。

因为我对那样的味道特别敏感。

我当初之所以没死，是因为一位还在进行武者修行之旅的剑士......加尔•法利昂收养了我。

「不要这家伙的话，就给老子吧。」

加尔•法利昂说了这句话后收养了我。

他把我带出了村落，真的就像是把被丢掉的东西捡起来那样。

虽然被他救了一命，但我并没有因此而亲近他。真的是个不可爱的孩子。

我咬他，用力抓他，对他大吼大叫，但加尔•法利昂却轻易地一一化解，把我压住，戴上项圈，让我拿起剑后这样说道：

「根据老子的看法，你是个彻头彻尾的剑士。在跟人吵架时就用那个吧。」

现在想想，加尔•法利昂──师傅的脑袋很奇怪。

因为就是这样吧。他让我拿剑，又说要用那玩意儿尽情去砍喜欢的东西。

他这样对我说耶？连我都不会这么做。

不过，师傅拥有最低限度的道德观念。

因为在那之后，有好一阵子我们都没去人类的村落。

而是在森林里面晃来晃去，狩猎野兽与魔物维生。

\\

早上会被师傅狠狠教训一顿，结束之后他就会把我拖到魔物面前，让我跟它们战斗。

我发了疯似的拼死战斗。尽管会因此受伤，也曾受过重伤，但没有死。

想必他将我的实力以及对手的实力拿捏得很清楚吧。他会让我和那种勉强可以应付的对手战斗。

过了中午后就吃下杀死的魔物，再来就是自由时间。

一开始，我为了杀死师傅还袭击他。

这就是所谓的自不量力吧。

我被轻易玩弄在股掌之间，吃了一点苦头，但我没有因此收手，而是一而再再而三地站起来攻击他。

师傅基本上总是边窃笑边挡下我的攻击。他并没有特别指导剑术，想必是知道我根本听不进去吧。

唯独一点，就是在我没有拿剑就发动袭击的时候另当别论。

一旦我在战斗中把剑丢掉，师傅就会咂嘴一声，比平常更激烈地痛殴我，让我昏迷不醒。然后当我清醒时，手上已经绑着一把剑了。

\\

经过一年之后，笨蛋如我也稍微学到了一点东西。

我赢不了眼前的这个人，就算随便乱打也只会吃苦头。

当时的我竟然有学习到这点的脑袋，现在想想实在很不可思议。总之，无论是什么样的野兽，只要过了一年好歹会知道自己赢不了对手。

对我而言，那是人生第一次学到东西。

学到这点后，大约在同一时期师傅就开始教导我剑术了。

他用口头说明这里该这么做，该那样做才对。要合理地思考，一招一招稳稳地将对手逼到绝境......

我脑袋不好，师傅教给我的百件事情当中连十件也记不起来。到了现在也是。

不过，师傅很有耐心。

想必他明白一个道理。那就是只要反复教同一件事，就算再怎么笨的家伙剑术也会进步。

不过，我好像有那个才能。剑术慢慢地进步了。

同时，或许是拜此所赐，虽然只有一点点，但「还兽」的影响也出现了改善的余地。

可能是因为我每天都到处杀死魔物，发泄内心的冲动，后来就算看到别人也不会像以前那样烦躁。

不过只是看了之后不会烦躁，要是有人向我搭话就会立刻爆炸......

不管怎么样，师傅判断当时的我就算去人类的村落也没有问题，于是我来到了城镇。

就算多少习惯了人群，一开始的感觉也是「好拘束」或是「好烦」。

毕竟有许多人对我抱有敌意......

就算是现在也依然有着这样的心情。

只是，师傅说过：

「不用在意，只要你变强了，对方也不会明目张胆地做这种白痴的举动。非但如此，他们还会对你毕恭毕敬。甚至还会有人像条小狗一样亲近你。」

当时的我觉得就算有不认识的家伙像条小狗一样亲近过来也只会令人烦躁......但是遇到艾莉丝后我就舍弃了这样的想法。与其被人讨厌，还是被喜欢比较好。

先把这件事放到一边，总之呢，我总算成功地融入了人类社会。

虽然真的是很边缘。

在我的印象中，当时从没和其他人有过正常的交谈。毕竟我连话都说不好。

啊，不对。师傅一直用兽神语跟我说话，因为他将近十年都待在德路迪亚村，所以会兽神语。

而我从没说过。

我已经不记得第一次有像样的对话是在什么时候。

不过，应该是和师傅在说话吧。是在顶嘴还是在提问呢......虽然记不太清楚了，但师傅并没有特别惊讶，也回应了我吧。既然不记得了，表示就是这么一回事。

到我能够进行对话的时候，旅程就结束了。

因为我们抵达了剑之圣地。

那里对我来说是个很舒服的地方。

不需要交谈，只要看不顺眼就能教训一顿，这点很棒。

在德路迪亚村如果三番两次地教训同一个对手就会遭到别人嫌弃，可是在剑之圣地不断地教训同一个对手就会被投以尊敬的视线。既不会有人抱怨，也可以任性。

换句话说，只要能够不断地打倒对手，那里就是乐园。

简单明了。

在那样的地方生活了几年时间，我不知不觉就获得了剑王的称号。

不过，或许是因为我安于现状，某天我被师傅赶出了剑之圣地。

既然升到剑圣以上就要外出做武者修行，这似乎是剑之圣地的规定，或许是这样没错，但他完全没提到这件事，总之就是把我赶了出去。

他要我去看看外面的世界。

后来我就到了外面，成为冒险者，与保罗相遇，离别......

\\

★　★　★

\\

「然后，就遇见我了对吧！」

大森林，圣剑大道。

我在行驶于这条道路上的马车里面，说出了关于自己的半生。

尽管我认为讲这种事情哪里有趣了，但艾莉丝像平常一样听得很开心。

莉妮亚与普露塞娜也兴味盎然地听着我说话。

「是啊。」

艾莉丝看起来无比欢喜，就像在表示「之后的事情我已经知道了」那样。

她听了我造访剑之圣地的这段往事，一脸骄傲地说：「就是啊！要打倒好几次才会受到认同呢！」

不管是对我还是艾莉丝来说，剑之圣地都像是第二个故乡......

不，对艾莉丝来说是第三个，对我来说或许......算是第一个，嗯。

至于莉妮亚与普露塞娜，我感觉她们用有些错愕的眼神看着我，嘴巴也半张着。

以前只是看到这样的嘴巴就会打从腹部深处涌起一股怒气，我也稳重了不少啊。

「哎呀──真是壮烈的人生喵......是我的话，在一开始被泼水的当下就会变成一个乖孩子了喵......实际上就是这样喵......」

「我也是，只要不给我吃肉就会变成乖孩子的说。我和莉妮亚不同原本就是个乖孩子，所以只是恢复原状的说。」

「我也是乖孩子喵。」

「和我相比，你们两个都是乖孩子。」

我这样说完，两个人都害羞地搔了搔后脑勺。

「后来我遇见了鲁迪乌斯，学习到了最低限度的知识之后，就发生了转移事件。」

「我记得后来是在菲托亚领地与艾莉丝重逢，又跑去剑之圣地修行了喵？」

「嗯，是啊。」

「修行结束后，就和老大一起去了阿斯拉王国，变成了爱丽儿的仆人的说？」

「大致上是这样没错。在事情都结束之后，她希望我继续留在那里，给了我这副铠甲。」

就是我现在穿着的金色铠甲。

和爱丽儿陛下报备我要去德路迪亚村时，她说绝对要穿着这套铠甲过去，所以我才会穿在身上。

尽管在路上一度脱了下来，但因为就快到了，现在又穿了回来。

「爱丽儿真聪明喵。」

「没错的说。让别人见识到自己的力量果然重要的说。她很了解这点的说。」

「什么意思？」

莉妮亚与普露塞娜是年轻的德路迪亚族。我记得莉妮亚是裘耶斯的女儿吧？

这两个人去上了学，以首席毕业......现在经营着佣兵团，底下似乎有超过五百名部下。

佣兵团是鲁迪乌斯的部下，所以她们算是奥尔斯帝德的部下。

这两个女孩很聪明，七大列强还交给她们一个大群体管理，可以说是出人头地。裘耶斯想必也很骄傲吧。

有点想不起来裘耶斯长什么样子就是了。

「听到那个基列奴姑姑竟然跃升为阿斯拉王国七骑士之一，肯定没有人相信的喵。」

「没错的说。不过只要看到那金闪闪的铠甲就一目了然的说。因为上面绘有阿斯拉王国的徽章的说。凯旋而归的说。大家的眼神都会不同的说。」

「是这样吗......」

虽然我也不是很懂，但既然这两个优秀的德路迪亚族都这么说了，应该没错吧。

「没错！我不会让他们抱怨的！」

艾莉丝在我穿上这副铠甲后，呼吸比平常还要急促。

尽管她说很适合，但这副铠甲会过度反光，我并不是很喜欢......如果是在黑暗的地方倒还可以。

不过，要说没有不安是骗人的。

残留在记忆中的德路迪亚村，我在那从来不被众人所接受。

虽说随着年纪增长变得比较稳重，但那群人想必不会将以前的事情付诸流水吧。

「唔。」

「喔。」

「靠近了的说。」

尽管还没进入视线当中，但闻得到怀念的味道。这是德路迪亚族村落的味道。是没什么美好回忆的味道。

这样一想，尾巴的根部就变得有点痒痒的。

感觉要从喉咙深处发出低吼。内心有种想立刻起身往前冲去的冲动驱使着我。

「鲁迪乌斯，你怎么看？真的不要紧吗？」

如果是以前的我，想必不会问这种事情吧。

不，隶属于黑狼之牙的那段时期，我好像也经常这样询问保罗。

保罗他平常总是怎么样回答的呢？

「咦......啊，应该不要紧吧？不过就算有可能搞砸我也会设法处理的。请交给我吧。」

坐在车夫位子上的鲁迪乌斯这样回答。

我想起来了。保罗以前也总是这样回答我。

「不过，应该不要紧吧。就算不行也总会有办法的，对吧？」

听到他的回应，基斯、塔尔韩德与艾莉娜丽洁三人会露出傻眼的表情叹气，这个画面恍如昨日。

但回想起来，确实都设法解决了。

唯一没有处理好的，就只有保罗与塞妮丝结婚之后离开的那个时候。

从车夫的位子那边传来了「嗯，大概不要紧......毕竟奥尔斯帝德大人也给了我伴手礼，我也准备了点心盒......不过莉妮亚和普露塞娜也在......」这样的声音。

鲁迪乌斯正按着肚子，看起来状况有些不好。那家伙从以前开始只要我一聊到往事就会这么做。到底是为什么？

话虽如此，那家伙也已经是个出色的大人了。

他从小就头脑很好，也很善于处世之道，现在更是七大列强之一，奥尔斯帝德的心腹。既然他都说会设法解决，应该就会言出必行吧。

「基列奴姑姑也会觉得不安喵？」

「我懂你的心情的说。爸爸他们是脑袋顽固的死脑筋的说。很难接受像我们这种已经习惯都市的新一代德路迪亚族的想法的说。」

「不要紧，因为鲁迪乌斯很厉害的！」

听到艾莉丝说出和以前相同的那句话，我不禁嘴角上扬。

望向窗户外面，可以发现有几名战士与马车以同样的速度移动。

可以知道他们躲在森林的深处，像猫那般灵活，像老虎那般凶恶地观察着这边。

他们在下风处，闻不到他们的味道。

但是弥漫在这一带的味道，确实是同族所发出的。

就这样，我回到了德路迪亚村。

\\

★裘耶斯★

\\

基列奴•泰德路迪亚这个女人对于我们这个世代的德路迪亚族而言是令人畏惧的对象，也是侮蔑的对象。

她异于常人的状况并不寻常。

从以前到现在，像这样的孩子会被称为「还兽」，但是那家伙是更为异质的存在。

她不是人。这句话的意思并非她无法用语言沟通。而是完全无法进行任何交流，她无法理解对方的想法。

身上总是散发着愤怒与不满的味道，一旦眼神对上，就会理所当然地发动攻击。

我都不知道差点死在她手上几次了。

每次她都会被扒光衣物，被泼冷水，然后关进仓库里面，但完全治不了这个毛病。

只要受到那样的惩罚，不管是谁都无法重新振作，甚至也会怒气全消，陷入忧郁的情绪当中。

所有人都是这样。

可是，那家伙，就只有那家伙不一样。

就算被泼了冷水，就算一整天都被关在暗处，她反而会更进一步地涌起怒火，大吵大闹。

父亲下了决定，要杀死基列奴，这件事失败的时候也没有变化。

当她被一个好事的旅行剑士带走时，我打从心底松了口气。

尽管她没有死在德路迪亚族的村落，但这下总算能放心了。反正那种生物不管在哪肯定都无法长命，会在某个地方横死街头。

\\

所以当我听说了「剑王基列奴」这个名字时，也立刻怀疑了起来。

德路迪亚族的剑士基列奴？不可能。肯定是知道基列奴名字的哪个笨蛋用那个名字招摇撞骗，往自己脸上贴金吧。

我们这个世代都带着半分畏惧以及半分颤栗的心态说着这种话让自己安心。

孩子们听到基列奴的传闻后，眼睛都闪闪发亮。他们不认识基列奴，所以看起来就像是离开村落的人在外面功成名就吧。

不管怎么样，我实在无法想像基列奴成为大人的样子。

因为那个再三伤害他人的存在，不可能会没有人杀死她，顺利长大成人。

就算成为大人，理解「还兽」的可悲，负面的情感依然回荡于胸口深处。

基列奴在外面的世界是不会获得成功的，我不能允许这种事发生。

每当听到基列奴的名字，内心就会涌起这样的情感。

在距今十年以前，有两个小孩被魔族战士带来这里，因此得知了基列奴的近况。

从他们口中听到的真相令人难以置信。

那个基列奴竟然会教导孩子剑术，并且请对方教导她文字与算术......

我想说这是在开什么玩笑。

长大成人后的基列奴应该要一瞬间就把孩子活活咬死吃下肚。

因为她就是那样的生物。

不过那个孩子──鲁迪乌斯•格雷拉特这样说道。

不管是谁都会改变的。

我无法相信。我认为那个人一定只是和自己所知道的基列奴有着相同名字的不同人。不，我这样希望。

\\

然而，那个基列奴就在我的眼前。

\\

「......」

不仅基列奴，鲁迪乌斯先生与艾莉丝小姐，甚至连两个笨蛋女儿都在。

我问他们是来做什么的，得知是来讨论鲁迪乌斯的女儿，也就是圣兽大人所选上的救世主菈菈大人在成人之际要做些什么。

确实，德路迪亚族会在圣兽大人的搭档，也就是救世主诞生之际举办仪式。

会倾整个大森林之力举办盛大的仪式。

这个重要的仪式得花上好几年时间准备。

身为其他种族，而且对德路迪亚族的造诣也没有那么深的鲁迪乌斯先生愿意协助我们，实在是非常感谢。

八成是莉妮亚与普露塞娜带出了这个话题吧。

负责照顾圣兽大人的她们离开村子后就一直没有下文，看来她们有在认真完成自己的职责。

而且她们现在还是鲁迪乌斯先生的部下，率领着名为鲁德佣兵团的群体。

作为父亲也感到很骄傲。

关于选定战士长一事，虽然不至于把上次的失态一笔勾消，但蜜妮托娜与提露塞娜因为被迫等待选定战士长而累积了许多不满，这样的功绩应该也足以让两人信服吧。

蜜妮托娜与提露塞娜很有上进心。

想必会受到这件事的激励，继续精进自己的能力吧。

「救世主大人......菈菈大人与圣兽大人一起踏上旅程的仪式，必须征求住在大森林的所有种族的同意以及出席。如果人脉广的鲁迪乌斯先生愿意协助我们，实在是感激不尽。」

「能听到你这么说我也很开心。因为我原本还以为你会说『全部交给我们处理，你只要闭上嘴巴把女儿交给我们就好』。」

「哈哈，如果是面对其他人族应该就会这样说了，但你理解这对德路迪亚族来说是重要的仪式，我是不会说那种话的。」

与鲁迪乌斯先生的讨论过程始终很平静。

不知道是不是错觉，鲁迪乌斯先生或许也在注意别让自己提到有关基列奴的话题。

他身上散发出这种味道。

「那么，我现在就逐一通知各种族，请他们开始准备。不过我们这边能准备顶多是菈菈的衣服而已。」

「因为是传统服饰，所以也没有必要劳烦你们。不过......」

「不过？」

「衣服素材来自某个魔物，它栖息于大森林的深处。这件事向来都是由历代的战士长负责去取的......不过，现在村子里没有战士长......」

「啊......」

我瞥向女儿她们，其中一个像是事不关己那样把脸别向旁边，另一个则是狂啃眼前的肉。

这两个败家女......

「虽然还没有决定详细内容，不过几年后会举行选出战士长的仪式，到时会顺便让当事人前去狩猎那头魔物。」

「听起来真是头疼呢。」

「你可以理解吗？」

鲁迪乌斯先生深深点头。

他以前来的时候我也这样觉得，这个人现在变得相当成熟。

甚至无法想像他和当初那个躲在木箱偷窥女儿们入浴的少年是同一个人。

相较之下，女儿们成何体统。

当初是因为今后会积极与人族交流，为了让她们学习做人处事的道理才会让她们去远方的学校，结果竟然是这副德性。

然而，就算看在我的眼里是难以管教的败家女，她们却能在人族社会担任着佣兵团的团长与副团长，是族群的领袖。

既然这样，说不定是我误会了。

「普露塞娜也对这种方式没异议吧？」

「没问题的说。不然现在就开始也无所谓的说。我会把蜜妮托娜与提露塞娜好好教训一顿的说。」

「你相当有自信嘛。」

「当然的说，你以为我平常都是在跟谁训练的说？」

她这样说完，望向艾莉丝小姐。

不，也许......是看着基列奴吧。

没想到不仅艾莉丝小姐，基列奴甚至还锻炼了普露塞娜吗......

「因为我很久没去大森林，要找到魔物或许会花一点时间，但有些让步反而刚好的说。」

在普露塞娜旁边，莉妮亚露出无所不知的表情点着头。

以前要是普露塞娜摆出这种态度，她立刻就会冷嘲热讽，说自己更厉害，但现在她却什么也没说，只是默默点着头。

代表她的实力有这么强吗？

虽然很不放心这两个人，但既然已经确实做好了准备，那就足够了。

不过话又说回来，普露塞娜有可能会成为战士长吗？

真令人不安。

「那么，等到决定正确的日期，我再另外联络。」

「知道了的说。那么我派佣兵团的一位魔术师留在这里负责联络的说。」

鲁迪乌斯先生好像会在这个村落设置魔术式的留言板，会用那个联络吗？

真是方便啊。

而且，莉妮亚与普露塞娜已经爬到了可以派人处理的地位。

因为两个人都离开德路迪亚村很长一段时间，想法说不定已经偏离了德路迪亚族的常识，但是新的知识与物品也有可能为村落吹起新的一阵风。

那肯定不是什么坏事。

「所以......」

对话到此中断。

关于仪式的事情也说过了。选定战士长的事宜也说过了。

已经没有其他要提的了。

那么，就吃个东西，今晚好好地休息一下，虽然很想这样说......

「......」

从刚才就默默坐在旁边的基列奴令人感到很不舒服。

如果是我所知道的基列奴，应该不可能这么长时间坐在原地。

会在经过一半的时间时失控大闹，导致有人因此负伤。

我甚至怀疑她真的是基列奴吗？不过味道不会骗人。

会让尾巴根部痒痒的那种不擅长应付的味道。

从前只要这股味道逼近，我就会立刻逃走......

「基列奴。」

我不禁说出了她的名字。

再继续沉默下去也不会开始。我也已经是德路迪亚族的族长了。

作为德路迪亚族的族长，态度必须表现得大大方方。

「怎么了？」

基列奴的尾巴微微一颤，望向这边。

「事到如今，你是有什么脸回到这个村落？」

这番话刚说出口，我就感觉到自己的背顿时喷汗。

如果是以前的基列奴，想必只要这句话就会把我打个半死。

现在的基列奴......看起来千锤百炼，会觉得她的举止怎么会如此俐落。假如是初次见面，光是这样就足以让我判断应该要对她毕恭毕敬。假如拥有如此实力的基列奴依然是以前那样，就算我的脑袋当场飞掉也很正常。村里有人死去也不足为奇。现在应该立刻就不容分说地把她轰出去。

但是，既然艾莉丝小姐特地把基列奴带来，我就不得不面对她。

由身为知道当时状况的人，身为现任族长的我来面对。

「......！」

艾莉丝小姐试图起身，将手放在腰间的剑上。

随后她皱着眉头，就这样重新坐下。

因为不知不知间，基列奴的手已经押在艾莉丝小姐的手上。

「......我在剑之圣地修行，获得了剑王的称号。实力获得阿斯拉王家赏识，现在正于那边仕官。你看这身铠甲。地位相当高。王家也待我不薄......嗯，就是以那种脸回来的。」

这番话讲起来有点结巴。

但是基列奴却露出满不在乎的表情如此回答。

「我以为，你肯定很怨恨村里的人......」

「怨恨？为什么？」

基列奴微微歪头，如此询问。

「为什么？我们可是排斥你，甚至打算杀了你啊？」

「......要是有只不懂语言的野兽待在村里，这样做也是理所当然的吧？我根本没理由怨恨。」

基列奴以平静的语气继续说下去。

「当我被允许自称剑王的时候，师傅这样告诉我：『你是德路迪亚族的剑王基列奴。大可自豪地这样报上名号。要是有事情想发誓，就以德路迪亚族之名立誓吧。』」

「自豪？」

「是啊。」

别开玩笑了。像你这样的女人不准自称德路迪亚族。

我没办法这样大喊。

为什么呢？连我自己也不晓得，但看到说出刚才那番话的基列奴，内心不禁有种很痛快的感觉。

「我就算曾受德路迪亚族之名的帮助，也从未因此受到妨碍。根本不会怨恨。」

一想到这是为何，脑海中就浮现出以前自己还年轻的时候，当上战士长之前那时的记忆。

是在剑王基列奴的传闻开始流传到村落里的时候。

剑王基列奴的名号虽然有点恶名昭彰，但并非尽是不好的传闻。

反而有一半以上是正面的。

在这些传闻当中，还听说她攻略了困难的迷宫。这对一名冒险者来说是非常光荣的事情。

是以德路迪亚族的基列奴之名。

怎么可能有这种蠢事。那家伙肯定是冒牌货。

我这样主张给自己听，同年纪的人也纷纷异口同声地赞同这个说法。

但是，我难道对此没有一丝喜悦吗？

我对德路迪亚族感到骄傲。正因为这样，村落出身的人扬名立万，难道不会让我有一丝喜悦吗？即使那是遭到村落舍弃的人......

「我反而觉得很过意不去。抱歉，当初的我是个笨蛋。」

基列奴这样说完，低下了头。

道歉了。那个基列奴竟然道歉了。

「这样啊......」

我闭上眼睛。

早就应该明白了。

基列奴只是发生了「还兽」最严重的症状。

虽然连双亲都撒手不管，但原本「还兽」就是会随着年龄治好的。

换句话说，基列奴成长得十分出色。

就算遭到村子的众人弃而不顾，她依然在村子外面学到了常识与知识。

而且，她对德路迪亚族之名感到骄傲，即使获得了名声，依然自称德路迪亚族，然后在今天，在这个日子光明磊落地回到村落。

而且面对身为族长的我，也表现出诚恳的态度。

那么，我该说的话已经有定案了。

「剑王基列奴•泰德路迪亚。很高兴看到你回到德路迪亚村。我族长裘耶斯•泰德路迪亚在此欢迎你。」

「劳你费心了。」

基列奴一度起身，随后单膝着地，低头致意。

这个礼仪作法，记得是剑神流的剑士在问候地位比自己高的人时会做的动作。

那个基列奴竟然会如此正式地问候别人。

这样啊，基列奴，你把我当作上位者看待吗......

\\

「今天就住一晚，让我听听你旅行时的事情吧。」

「好吧。有许多有趣的故事。」

我决定接纳她。

尽管过去不会付诸流水，但也已经到了改朝换代的时期了。

在下一个世代中至关重要的女儿们实在令人不放心......不过，她们总有一天也会产生变化的吧。

不管是我的父亲还是祖父，都是一边抱着这样的烦恼，同时完成族长的职责，再传承给下一代......

\\

就这样，基列奴•泰德路迪亚顺利地返回故乡。

*** 〈艾莉丝与蜜妮托娜〉

艾莉丝来到了兽族的村庄。

她对鲁迪乌斯说想去那边看看，于是鲁迪乌斯就带她来了。

当时艾莉丝说「基列奴也应该一起去！」。这是因为前几天在阿斯拉王国见到基列奴时，基列奴显得有些落寞地望着天空。

基列奴其实并没有特别思念故乡。

但对艾莉丝来说，那种事并不重要。

既然普露塞娜可以凯旋，基列奴也应该可以凯旋。

艾莉丝坚信这样会有好结果，肯定只会有好事发生。

如艾莉丝所想，基列奴确实凯旋了，裘耶斯也恭敬地接待了她，最后大家都很高兴。

艾莉丝为这个结果感到满意，决定去见曾经关系要好的蜜妮托娜和提露塞娜。

兽族的村落对艾莉丝来说简直是天堂，当她在村里四处闲逛时──

「蜜妮托娜！提露塞娜！好久不见！」

她找到了两人。

她们正在教新手战士剑术，远比记忆中的两人更加成熟。

作为战士长候补，她们在年轻人中展现出领导能力，这点从远处也能看得一清二楚。

她们知道艾莉丝来后顿时感到惊讶，恭敬低头。

「艾莉丝！......好久不见喵！」

「好久不见，艾莉丝小姐看起来相当健康，真是再好不过。」

「......」

艾莉丝感觉有点不太一样。

该怎么说呢，因为自己记忆中的蜜妮托娜和提露塞娜更像是小猫和小狗，是一种无比可爱的存在。

不过艾莉丝知道，蜜妮托娜和提露塞娜也为她们的重逢感到高兴。

身为伯雷亚斯家的一员，艾莉丝只要看兽族的尾巴和耳朵的动作就能明白她们内心的想法。

「听说你们两个都出人头地了！」

「是的喵。现在我们是战士长候补！离族长只差两步喵！」

「我不会输给普露姐姐的！」

「有志气！」

艾莉丝是蜜妮托娜和提露塞娜的朋友，但同时也是普露塞娜的朋友。

顺便说一下，与其说是朋友，她的立场更像是饲主，但这只是不重要的小事。

所以到时一旦战斗，她希望自己这边的孩子能赢，相反地也不希望她们赢了后离开，希望她们能一直待在身边。

因此，要支持谁是个困难的问题。

话虽如此，艾莉丝是剑王。

所以她也会这样想「无论支持谁，时候到了自然会有结果」。

在现在这一刻回忆过去，和她们一起开心地玩耍，这才是艾莉丝需要考虑的事情。

「我可以久违指导一下你们的剑术喔。」

不过，艾莉丝能想到的有趣游戏有限。

「真的喵？大家，剑王要为我们展示招式喵！」

「要好好看着喔！」

听到两人的呼喊，年轻的兽族们迅速排成一列。这是因为兽族的上下关系很严格。

艾莉丝看着这幕景象，心想能不能至少带一个回去，但很快就浮现希露菲和爱夏生气的画面，立刻打消了念头。

在这段时间，蜜妮托娜迅速做好准备。她将木刀递给艾莉丝，自己也拿着木刀站在艾莉丝前面几步。

「容我向你讨教喵！」

她举剑的姿势和以前见到的时候相比，洗练得仿佛判若两人。

破绽很少、动作锐利。尽管看得出些许的破绽，但艾莉丝知道那是陷阱。

她不是可以一击就轻易解决的对手。

艾莉丝对这个事实很满意，摆出了平常的架势。

「......！」

周围的气氛为之一变。

艾莉丝的动作毫无任何懈怠。这场战斗是所谓的模拟战，不是说非赢不可，但她不是会在面对战斗时放松警惕的女人。

「开始！」

「喵啊啊啊啊啊啊啊啊啊！」

在提露塞娜打出信号的瞬间，蜜妮托娜大叫。

「嘎啊啊啊！」

蜜妮托娜用的是兽族的吼声魔术，虽然不晓得艾莉丝是否也注意到了，但她也吼了出来。

用自己的斗气强行纠正被带有魔力的吼声扰乱的三半规管，眼见蜜妮托娜在发出声音的同时冲过来，艾莉丝毫不犹豫地挥出光之太刀。

艾莉丝的一击朝着蜜妮托娜的手腕击去，那是流畅而完美的一击。但蜜妮托娜的剑稍微动了一下。

艾莉丝的剑尖被引到蜜妮托娜的剑锷，铿一声碰了一下。

就在那一瞬间，艾莉丝的剑靠在蜜妮托娜的剑上，轨道稍微偏离......艾莉丝略为踏进一步。

「喵呜！」

蜜妮托娜手上的剑被击飞了。

剑在不断旋转的同时飞了出去，撞到墙上直接落地。

这时，艾莉丝的剑已经架在蜜妮托娜的脖颈了。

胜负已分。

「怎么可能喵......我明明完美地化解了......」

蜜妮托娜望着离开自己手中的剑，一脸茫然。

她有信心。自己比以前艾莉丝来的时候变得更加强大。她认为现在应该能和艾莉丝一较高下，让艾莉丝称赞她。明明是这样想的，却事与愿违......

「好厉害！那是水神流的招式对吧！你是在哪学的！」

「咦......自......自从艾莉丝你们来之后，村子里就经常会有冒险者出没喵......其中一个就是水神流......」

「原来如此！刚才那招非常好！虽然还是我赢了！因为我和伊佐露缇交过手，对付水神流已经有点心得了！」

艾莉丝充满精神兴奋地说着，蜜妮托娜则是呆滞了几秒。

「真是的，艾莉丝还是老样子喵......」

她这样喃喃自语，露出笑容。刚才的斗志完全消失了。

「艾莉丝的招式才厉害喵。我以为自己有那么点机会赢的，结果还是不行喵。」

「毕竟我为了打倒龙神奥尔斯帝德进行了许多修炼。没那么容易让你赢的！」

「龙神奥尔斯帝德......我想要听听看详细的经过喵。」

「好啊！」

就这样，艾莉丝她们聊了很多积在心里面的话题，久违地重温了友情。

\\

Short Story first used in Animate Japan

\\

*** 〈与老友重逢〉

某天，我和一位难得的对象一起造访了新生的罗亚。

这位难得的对象，就是莉莉雅。

她依然是我们家可靠的女仆长，也是妻子们可靠的义母，有时也是孩子们慈祥的奶奶。不过自诺伦嫁出去后，她似乎放松了不少，应该说感觉有点老态。

所以我向她提议去旅行换换心情，她便回答说想见一个人。

于是，我请鲁德佣兵团帮忙搜集情报，确定了那个人的所在处，并前来拜访。

「这一带明明曾消失过一次，却感觉莫名地熟悉呢。」

「是吗？我只待了几天，对以前的样子不是很清楚......」

「因为我以前到处找工作，当时对这里很熟悉。不过现在已经记不得了。」

「......说不定是依照以前的感觉重建的？」

进行这段对话的是莉莉雅和洛琪希。

我们这次要见的人物也是洛琪希的熟人，所以她主动要求同行。

「啊，好像在下一个转角右转。」

「咦？在靠近大街的地方吗？我记得以前好像是在小巷深处才对。」

「毕竟这个城市也才刚刚建成，需求很大。」

「如果我来的时候也是这样......不，那样，我就不会遇见鲁迪你们，以结果来说是好事......」

我们聊着聊着在大街上右转，前方就看到了一栋巨大的建筑物。

那是冒险者公会。

阿斯拉王国的菲托亚分部。

现在也有许多冒险者从建筑物里面进进出出，络绎不绝。

据洛琪希说，以前这里更小，人也很少。

当时的领主绍罗斯实施了「驻扎骑士制度」，至少要派遣一名骑士到各个村镇维护治安、并定期派出私兵驱除魔物。在其他国家本应由冒险者执行的这些工作，在这里几乎都是由国家当作事业进行。

虽说是阿斯拉王国的边境，但好歹也是繁荣之地，轮不到冒险者大显身手。

这样公会规模当然也会变小。

然而，在灾害之后人手不足，基础设施也未能完善，自然没办法像之前那样依照制度执行，所以菲托亚领地逐渐成为阿斯拉王国冒险者的中心。

我们站在有着崭新气象的大型冒险者公会前面，推开了门。

在里面环顾四周，发现一群年轻──但绝不算年幼──的中坚冒险者纷纷将视线转向我们。

我们大大方方地承受着众人的视线迈出步伐，此时听到有人说「喂，那是那是洛琪希•米格路迪亚」「是S级的......」心中不禁感到高兴了起来。

洛琪希有点害羞，低声说「其实我是A级的」。如果我是冒险者公会，势必会为洛琪希颁发S级证书。如果不够的话，我们公司的新进员工是SS级，就从他那里拿个S吧。没什么，不用担心，那家伙好像是半不死之身，区区一个S大概随便就会长出来了。

我如此胡思乱想并往前走去，很快找到了目标人物。

她人就在柜台。

看到她，莉莉雅罕见地大声喊道：

「维拉小姐！」

「咦？啊......啊──！莉莉雅小姐！」

在柜台的是从前和保罗同样隶属于菲托亚领民搜索团，甚至为了救出塞妮丝，一起前往贝卡利特大陆的维拉。

没错，现在她在冒险者公会担任接待员。

顺便说一下，她已经不穿比基尼铠甲了。现在穿着白色衬衫和素雅的长裙。

原本发尾往外翘的头发也已留到肩膀，看起来很有公会接待小姐的风格。

「好久不见！啊，请稍等一下。我处理完这些家伙就过来......」

无视冒险者们「这些家伙是什么意思啊」的抗议声，维拉迅速地在纸上写下什么，然后说了句「好，辛苦了。下次也要加油喔，啾！」把文件和飞吻一起塞给冒险者，急忙跑进了公会里面，开始大喊「雪拉！莉莉雅小姐他们来了！啊，公会长，事情就是这样，我先出去一下」。

我们姑且有事先通知我们会来。虽然没有告诉她具体的日期和时间，但说过会在近日拜访。

所以，她想必已经跟身边的人说过了。

话虽如此，工作时间离开岗位也会给公会带来困扰。

公会长嘟囔着说「到底是谁来了......？」走出办公室。从他那凶狠的眼神，可以感觉出若是他判断对方无足轻重，就打算将人赶跑的一股意志。

然后，他和我对上了眼。当然，我认识他。毕竟他也有参加菲托亚领地的落成典礼，当时也有过一些交流，想必对方也记得这件事吧。他露出有些诧异的表情向我点头问候，随后拍了拍维拉的肩膀说「可别失礼啊」，便回办公室去了。

在这种时候，权力真是方便。

「好......好久不见......」

一位将兜帽压得很深的女性从办公室里怯生生地走出来。

我尽量不去看她，同时也从原本的位置往后退了一步。

雪拉似乎依然害怕男性的视线。

「那么，我就去找个地方消磨时间了，有什么事请随时通知我。」

所以，我不会参加这次的女子会。

虽然雪拉好像说如果是我的话就没关系，她可以忍耐，但毕竟她们是旧识，这次还是希望她能和曾经一起在贝卡利特大陆冒险的三人好好享受这次重逢。

「好的。鲁迪乌斯老爷，麻烦你了。」

「不客气，祝你们玩得开心。」

不过话说回来，这两人也算找到了一份稳定的正当工作，这样就放心了。

我如此心想，离开了冒险者公会。

\\

Short Story first used in Gamers Japan

\\

*** 〈杜加结婚前夜祭〉

我打算只叫一些男人来，给杜加庆祝一番。

毕竟结婚后就没了所谓的自由嘛。所以当然要在婚前大肆庆祝一下，娼馆......杜加感觉不会想去那种地方，这个就算了，喝酒......杜加也不会喝呢，总之就是一起吃点好吃的，大伙一起狂欢庆祝，跟他说声恭喜这样。

结果老婆说「开什么玩笑，你想帮我哥哥庆祝，却把我排除在外？」对我大发雷霆。

于是我们决定简单的叫些认识杜加的人，在酒馆订一个角落，大伙一起热闹一下。

所以，现在我眼前的是一个全天包场的酒馆，里面整个是人山人海。

「杜加、伊佐露缇，恭喜你们订婚！」

随着我的声音，坐在生日大位的杜加被纸片喷了一脸。

杜加吹熄了眼前蛋糕上的蜡烛。这可不是在过生日啊。

顺便说一下，不知为何，他的未婚妻伊佐露缇就坐在他旁边。

虽然这不是那种庆祝活动，但好像是杜加自己叫她来的，那就算了。

不过话说回来，竟然聚集了这么多人啊。我只是随便叫了几个朋友，回过神来才发现酒馆里面挤得到处都是人。

男女老少，各种人都有。

有些是我认识的，也有些不认识，但无论如何，这些人想必都和杜加有某种关系。

因为坐在那边的，是阿斯拉七骑士的希尔贝斯托和香杜尔吧？

然后在那边的是杜加未婚妻的哥哥。

他们相识的契机与彼此的关系似乎也各有不同。

搞不好连杜加自己也不一定认识所有人吧？

不过，至少大家似乎都喜欢杜加。喜欢到听说杜加和那个伊佐露缇订婚之后想要帮他庆祝，或是出席这场庆祝活动。

所以杜加坐在生日大位虽然有些害羞，但面对眼前的山珍海味，还是笑得很开心。

杜加本来就不太会说话，话也不多，是个难以捉摸的男人，但他肯定知道大家在为他庆祝。他不时与旁边的伊佐露缇交换视线，两人都显得很害羞。还真是恩爱啊。

算了，我要来痛快喝一顿啦。今天就算喝个烂醉了也会被原谅。

人生中总是要有这种日子！

「唔嗝，哦，这瓶酒还没喝完？我可以喝吗？」

「啊，我来倒吧。」

「喔，不好意思啊。哎呀，不过说真的，第一次近距离看到杜加的未婚妻，就那个伊佐露缇小姐，她也太美了吧？杜加那家伙是不是又被骗啦？」

「真巧，我也这么觉得。所以我自己也调查了一下，结果她出乎意料地清白。」

「是吗？我听说她当初还对阿斯拉王国的贵族精挑细选呢。」

「但最终她选了杜加，代表她不是只看外貌和血统的女人。毕竟就算从我们男人的角度来看，杜加也不是那种会靠外貌被选中的类型。」

「你这样说也对......」

顺带一提，我不认识眼前的这个男人。感觉好像在哪见过，但想不起来。

算了，无所谓了。重要的是眼前这家伙和我一样，都是来祝贺杜加的。那么他今天就是我的好兄弟。

「啊，不过嘛！还很难说喔！结婚后她可能会突然变了一个人到处花心呢。如果真是那样，我可不会坐视不管！」

「你不会坐视不管？对方可是即将成为水神的人喔。」

「那又怎样！就算对方是那个被称为水神列妲的女人，我也会大闹一番的！毕竟我欠了杜加很多人情，况且他还是我大舅子，是我哥哥啊！那我这个做弟弟的不帮忙怎么行！」

「杜加也对我有恩。到时候我们一起闹吧。请记得叫上我。」

「喔──当然啦──！」

我拍了拍那个男人的背，继续寻找下个要攀谈的对象。

真的很开心。

该怎么说呢，杜加那家伙不擅长社交，看起来也容易被骗。

这样的杜加竟然找到了这么漂亮的老婆，还受到大家的祝福。

看看这么多到场的宾客。我本以为会来祝贺杜加的人顶多十个，结果聚集到的人数甚至让我得包下整个酒馆。

当初一起干卫兵时认识的朋友，明明用一只手都数得出来，没想到回过神来，杜加已经结交了这么多自己不晓得的知己。

这让我没来由地感到高兴。

所以我走向杜加，坐在他旁边，靠在他肩上，疯狂喝酒然后长叹一声。

「杜加、杜加！哥哥！真的太好了啊！」

「哦。」

「我啊，在鼓励你之后，其实有一点后悔。虽然世人都说『与其不做而后悔，不如做了再后悔』，但其实这种事情很难说啊。也有些事情是不做会更好。但我还是不负责任地鼓励你......」

「......没有，那种事。」

听到杜加以不同以往的嗓音给出回应，汉斯停了下来。

「听到汉斯，那样说，却不做的话，我肯定，会后悔的......」

听到他支支吾吾说出这番话，汉斯手里拿着酒，仔细聆听。即使喝醉了，他也能分辨出哪些话该听哪些话不该听。

「谢谢你。」

听到杜加最后以这句总结，酒后爱哭的汉斯变得感性起来，泪流满面。

\\

*** 〈某个斯佩路德族青年的记录〉

我们感到很烦恼。

之所以会这样，是因为前阵子瑞杰路德迎娶了一位人族，而我们不知道该如何对待她。

当然，她是拯救了我们村子的人之一，我们对她表示欢迎。

那个人是诺伦•格雷拉特，现在改名为诺伦•斯佩路迪亚。

她表面上看起来平静地过着生活，但会在空无一物的地方绊倒，面对我们时也显得有些慌张，可以看出她内心的动摇。

说不定，这段婚姻并非她所期望的。

不管怎么样，既然她来到了斯佩路德族的村落，就是我们的伙伴。应该要以友善的态度温柔对待她。毕竟瑞杰路德这个人完全不懂得如何应付女性。

虽然我们这么想，但与人族的交流才刚刚开始，我们也不太清楚该用什么方式关照她比较妥当。

就这样到了某一天。

有群人族来到了村子。

由于我们不习惯彼此的语言，费了很大工夫才问出他们的目的，总结起来就是：

「交出莱德里奥斯那个男人，我们要把他带走。」

在得知这一点后，负责对应他们的我立刻跑去找瑞杰路德。

「大事不好了，瑞杰路德。莱德里奥斯惹怒了人族。」

莱德里奥斯是一个年轻人，约十年前才刚取下尾巴。

由于他年轻，没有什么遭到迫害的经历，好奇心也很旺盛，不像我们这样对人族有偏见。

因此，他在与人族交流时经常被选为代表。

但也正因如此容易发生问题。这次显然就是如此。

在我们正准备与人族建立友好关系的时候，竟然这么早就惹出了麻烦。

「......莱德里奥斯闯下了什么祸？人族为何生气？」

「关于这点......我们也搞不太清楚。他们只是不断强调说要我们交出莱德里奥斯，说什么夺走了、报酬啊、补偿啊要带他走这样。我猜莱德里奥斯可能弄坏或是偷了什么东西，他们打算惩罚他......但莱德里奥斯自己似乎不记得有这回事......」

「那家伙不是那种男人。」

「是啊，不过这谁也说不准。也许他无意中弄坏了人族重要的东西。」

「唔......」

瑞杰路德表情险峻，发出沉吟。

瑞杰路德也没有那么了解人族。毕竟人族这种生物，可以在短短五十年内彻底改变自身的价值观。

话虽如此，最好还是得先安抚他们，让莱德里奥斯出面道歉；如果这样他们不愿接受，或许就得用武力赶走他们。

一旦采用击退的方式，好不容易与人族缔结的友好关系可能会化为一张白纸，但斯佩路德族不会抛弃同族。毕竟我们是一起度过了数百年的家人。

「那个......」

正在我这么苦恼时，一直默默泡茶的诺伦小姐开口了。

「要我去听听他们怎么说吗？」

「......你吗？」

「是的。即使是斯佩路德族的各位不明白的事，如果是我或许就能明白......」

听了这句话，我和瑞杰路德对视一眼，随即点头答应。

\\

★　★　★

\\

诺伦小姐出面后，事情瞬间获得了解决。

来村里的是治理这个地区的领主派来的使者，一位在人族年龄中属于中老年的男子。

明明国王刚决定要让斯佩路德族与人族建立友好关系才没过几年，他也毫不掩饰自己的不满。

面对这样的男人，诺伦小姐一开始也显得有些紧张，但她平静地解释自己是格雷拉特家的人，有责任调解斯佩路德族与人族之间的关系后，使者似乎接受了她的这番说词，刚才那不悦的态度像是骗人似的缓和了下来，向诺伦小姐重新解释了一遍来意。尽管他口中的奇怪措辞是百年前没有的，但诺伦小姐似乎听得懂。

「呃，简而言之，领主的女儿来到了平原野餐，不幸遭到魔物袭击，这时被莱德里奥斯先生救了？」

「没错。我一开始就这么说啦。」

「然后，领主的女儿对莱德里奥斯先生一见倾心，想见他、感谢他，甚至想把他留在自己身边。于是领主打算把他叫过来领取奖赏，便派你来到此地？」

「嗯。」

「那么......你为什么这么生气？」

「怎么能不生气！我从小姐还小的时候就负责照顾她，结果她竟然被一个来历不明的男人给骗了！」

「啊......嗯，不过既然你是使者，说话时是否能冷静点呢？斯佩路德族的各位对这种态度很敏感，会以为你是来吵架的。」

「唔......总之，莱德里奥斯先生必须跟我回去。」

「我明白了。」

就这样，诺伦小姐从他身上问出了来龙去脉，转向我们说：

「那么，请带莱德里奥斯先生过来。」

「为什么？在这里感谢就足够了吧？再说这个男人明明说是来给谢礼的，怎么什么都没带？」

「人族的贵族认为就算要表示谢意，也必须在他们准备好的华丽场所，依正式的流程进行。只要把它想成是人族的大人物举办的仪式就行了。」

「唔──人族的仪式啊。原来如此。但只有莱德里奥斯去吗？他们应该不会把他骗去杀掉吧？」

「啊，既然这样，我和瑞杰路德先生也陪他一起去吧。」

于是，事后将由诺伦小姐、莱德里奥斯和瑞杰路德先生三人前往领主的城堡，接受赏赐。

诺伦小姐轻而易举地解决了这次纠纷的起因。

「你相当熟练啊。」

瑞杰路德喃喃说道。

「咦？啊，是的。毕竟在魔法大学经常遇到这种事情。我在学生会处理过不少问题，所以可能是习惯了吧。」

「这样啊......以后也要继续拜托你了。」

「啊......好的！」

看到诺伦小姐自豪地回答，我们也意识到了一件事。

我们不需要自不量力地考虑如何关照她。只要把她当作家人，彼此依赖就好了......

#+begin_src
图源＆录入：halo
#+end_src

* Footnotes
[fn:1] 注：日本NHK的教育节目

[fn:2] 注：原文有用到动画《一休和尚》在中场休息时会用的台词

[fn:3] 注：原文为「はしをわたるべからず」。《一休和尚》着名的故事
