#+title: 无职蛇足篇2
#+setupfile: ./setup.setup

* 无职蛇足篇2
** 信息头
#+begin_quote
内容利用pandoc转自epub电子书，图片不留
#+end_quote

#+begin_src
制作信息

──────────────

天使动漫录入组录入

作者：理不尽な孙の手

插画：シロタカ

译者：陈柏伸

图源：真妹控

录入：kid

天使动漫：[[file:www.tsdm39.com]]

仅供个人学习交流使用，禁作商业用途

下载后请在24小时内删除，TSDM不负担任何责任

请尊重翻译、扫图、录入、校对的辛勤劳动

转载请保留完整的资讯，否则往后一律禁止

──────────────
#+end_src

** 简介
毕黑利尔王国的决战最后，鲁迪乌斯•格雷拉特赢得了胜利。

描写他与他身边的人们在那之后的故事合集，《蛇足篇》在此开幕！

本系列的第二集收录了叙述制作自动人偶时发生了什么状况的〈来制作自动人偶吧！〉、

描写为了与家族制造回忆而企划的旅行〈米里斯旅行手记〉、

加上鲁迪乌斯、艾莉丝、亚历以及奥尔斯帝德

一起拜访当代剑神吉诺•布里兹时的经过〈居住在剑之圣地的神〉，

以及描写鲁迪乌斯孩子们日常生活的特稿短篇〈鲁迪乌斯的孩子们〉，共四篇。

决战过后，人生依然继续──

鲁迪乌斯在这段人生中有着何种想法，完成了何种创举......

人生重来型转生奇幻小说，延续本篇之后的故事集，第二集！

** 来制作自动人偶吧！
*** 「人偶行走之日　前篇」

那天下着暴风雨。

猛烈的雨水拍打着草原，数道粗大的闪电直直劈向大地。

闪电的光芒照亮了一座房屋。

那座房子伫立在空无一人的草原中央。

在其屋内，两名疯狂科学家正放声大笑。

「哼哼、哼哈、哼哈哈哈哈！终于，终于成功了啊！」

「是啊！终于啊！终于完成了！」

两位疯狂科学家面带笑容握着手，在房间里兴奋地跳起了舞。

「能走到这一步，全都要归功于师傅您卓越的技术与智慧啊！」

「不不不，札诺巴同学，若没有你那渊博的知识与构想，绝不可能完成这项发明的！」

这两人正是鲁迪乌斯与札诺巴。

他们互相赞美着彼此，随后停下了舞蹈。

他们所在的房间深处，摆放着某个物体。

那是散发着诡异光芒的石制床铺。在那个床上躺着一名少女，全身赤裸。

「走到这一步真的好漫长啊......」

鲁迪乌斯回想起了那些失败的日子。

一开始，连启动都无法做到。

为了完成试作一号机，他们进行了无数次小规模改动和性能调整。

最终虽然成功启动，但结果只是个会无条件服从命令的魔像。

虽然这样的产品也可能有市场需求，但与他们真正追求的目标相去甚远。

从试作二号机开始，他们投入了大量时间和精力，开发搭载人工智慧的核心，并追求更接近人类的身体构造。

当然，失败依然接踵而来。

尽管身体部分逐渐接近人类，但只要为了实现更接近人类的动作而调整材料，就会出现耐久度的问题，为了模拟人类的动作而调整核心，又会导致启动失败。

这让两人不禁感叹，人类竟然是建立在如此绝妙的平衡之上，也为此深深苦恼。

就这样，一次又一次地失败。

他们多次研究狂龙王卡奥斯的笔记，也从甲龙王佩尔基乌斯那里得到建议，获得了魔法阵和精灵召唤的提示。在龙神奥尔斯帝德那里获得了稀有的魔石以及与材料相关的知识。

然而，纵使他们做了这么多努力，失败始终如影随形。

这是即使那个狂龙王也未能踏足的领域。他们曾因自己或许无法涉足那个领域而落泪。历经失败，泪流满面地重新挑战，然后再次失败。但每一次失败，都带来了些许新的发现，不断地慢慢进步。

然后在一个月前。

他们终于，终于成功了。虽然只是临时拼凑的人偶，但确实启动了。

那就是试作三号机。脸部光滑、没有五官的人偶确实是成功启动了。

他们因为这次成功而欣喜若狂，从试作三号机搜集数据之后，他们立刻投入下一台机体──试作四号机的制作。

试作四号机有着近乎成品的规格。

她拥有与人类相同的身体与脸庞，可以开口说话，也能运用手脚自由行动。

但严格来说，他们并没有完成试作三号机所需的所有实验步骤。

意思就是，他们并没有找出所有的问题点。

因为他们无法抗拒想让理想中的人偶以理想姿态运行的这份渴望。

于是，他们略过了几项本应在试作三号机上完成的工程，直接着手制作规格更接近完成品的试作四号机。

话虽如此，他们觉得这样也无所谓。

试作三号机能完成的事情，试作四号机同样能做到。

利用试作四号机检测系统，测试完成品素体的相容性。

这样不就行了吗？

这也是迈向下一步的过程。

我们想看的就是这个。

满怀热情才能造就工作，这才是我们所追求的自动人偶。他们这么告诉自己。

「那么！要开始启动喽～！」

「好！」

札诺巴带着雀跃的表情将手指伸向少女保守胸口正中央的魔石。

核心位于这颗魔石的深处，也就是少女的胸口中央。

上面刻满了复杂且细致的魔法阵，那不仅是少女的大脑，也是文字意义上真正的心脏。

核心一旦启动，人偶便能靠自己的双脚站立，自主学习、自行判断，并凭借自己的力量汲取魔力，实现半永久的活动机制。

这是一个可完全自行动作的人偶。

当然，也可能无法达成这样的目标，导致她因魔力不足而瘫倒。

不过在那种情况下，只要将她放回这张床上补充魔力便可再次运作。

最初当鲁迪乌斯提出这样的设计时，札诺巴曾提出异议，这样说道：

「将再启动寄托于人类之手，是否会显得不够完美？」

然而，鲁迪乌斯却这么说：

不，这样才完美啊。

人类在跌倒后若无法靠自己起身，是会借助他人的帮助站起来的。

「......」

札诺巴伸出的手指带有一丝犹豫。

即使是他，也会因为触碰幼小少女的胸口而有所忌惮吗？

不，他并不是会对这种事情犹豫不决的男人。

「............师傅，还是由您来吧？」

「不，能走到这一步全是多亏了你的努力，由你来吧。」

其实，札诺巴感到害怕。

这是两人的理想化为现实的瞬间，也是历经将近十年的努力实现梦想的时刻。

然而，札诺巴绝非胆怯之徒，是个与犹豫无缘的男人。

「本人明白了......那么，要开始了！」

「好！」

札诺巴的手指缓缓触碰少女的胸口。

动作轻柔得如同呵护一件易碎品那般，他的指尖在少女的肌肤上滑动，触碰了魔石。

启动所需的魔力量并不多。因为他们的设计理念就是任谁都有办法启动。

「......『苏醒吧，吾之爱女』。」

札诺巴咏唱启动用的咒语，魔力也随之流入魔石之中。

床边的指示灯这时由红色转为蓝色。确认到这幕后，札诺巴慢慢收回手指。

「......」

数秒的寂静在房间中蔓延。

两名男子屏气凝神，注视着少女是否顺利启动。

启动后的程序已经完全自动化。

咏唱启动咒语激发魔力后，只需要静静等待即可。

「......」

少女无声地睁开双眼，黑色的眼眸在瞬间点亮。

同时，伴随着轻微的「啪嚓」声，她与床铺之间的物理连接断开了。

在那之后，少女缓缓挺起上半身。

她的肌肤白皙细腻，身形纤细得令人怀疑是否没有任何肌肉。

尽管乳房偏小，但形状却极为完美，身体线条美丽得不像一名少女所有。

这具身体，是札诺巴与鲁迪乌斯多年制作人偶培育而出的技术结晶。

少女的身体由人工制造的肌肉和与魔导铠相同材质的骨架构成。

人工肌肉是以鲁迪乌斯利用土魔术制作出的黏土为基底，混合了赤龙鳞片与幻蝶鳞粉等具有强大魔力的材料，最后加入长老魔木的树液与不死魔族的血液制成。

经过反复错误的修正，运用这些昂贵的高级材料而诞生的这具人工肌肉，不仅具有半永久的高耐久性，还拥有极其接近人类肌肉的质感。

用来驱动这些人工肌肉的则是刻满魔法阵的骨架。

在骨骼上刻下的魔法阵能让人工肌肉像真正的肌肉一样活动。

技术的原理几乎与魔导铠相同。

但在关节部分嵌入了以毁灭者骷髅兵的骨粉制成的零件。

这些骨粉能大大地提高魔力的导通率。

尤其是高阶的毁灭者骷髅兵的骨粉，其魔力传导率极高，使人偶能更接近人类的动作。

少女举起双手，伸了个懒腰，随后张开手掌，再重新握紧。

这些动作流畅自然，几乎与人类无异。

然而，这份过于自然的举动却比想像中更加强调她的腋下与胸部，甚至还流露出一丝妩媚的气息。

「咕嘟。」

鲁迪乌斯忍不住咽了口口水。

「制作的时候没什么感觉，但看到她动起来，怎么说呢......比想像中，还要不妙啊......」

「......」

札诺巴没有回答。

但从他的表情可以看出，他的心情与鲁迪乌斯完全相同。

少女接着默默地仰躺下来，依次抬起双腿。

白皙水嫩的大腿交替上升，随后她维持这个姿势，开始弯曲、伸展膝盖，或是将双腿开合。

精巧制作而成的人偶隐私部位随着这个动作在两人面前若隐若现。

顺带一提，这些动作并非是出于情色目的而卖弄身体。

因为他们已事先设定好程式，让人偶在启动时会自动对关节部位进行动作检查。若检查发现异常，人偶会透过自己的嘴巴报告故障部位的相关错误。

「已正常启动。」

最后，人偶轻轻甩动及肩的黑色长发，宣告所有检查在此结束。

从人工声带响起的这个声音，与两人熟悉的某位人物极为相像。

「呼......」

两人神情依然紧张，就这样缓缓吐出一口气。

至今为止，他们无数次在这个阶段惨遭失败。

像是肘部以下在试图举起手臂时竟犹如火箭飞拳那样飞向天花板，或是膝盖发出闷响，弯向奇怪的地方，又或者是股间裂开，整个身体变成像是古怪雕像的姿势，随着一声闷响往后蜷缩之类的......

这些动作由人类做的话，肯定是令人毛骨悚然的场景，已经在试作三号机的制作过程中上演了好几次。

问题在于人偶的骨架与魔导铠是相同材质。

穿上魔导铠时，需要穿戴者自行控制力量。

而这种控制力来自长期使用魔术或肌肉的那些经验。

由于人偶没有这类经验，往往会以最大力量运作，从而导致自我损坏。

因此，他们在身体各处加装了限制器。

不过，骨架的材质依旧与魔导铠相同。

虽说设有限制，但耐受极限很高，足以承受与圣级剑士同样级别的动作。

总之，这个先放到一边。

看到经历多次失败的膝盖与手肘弯曲时的人工肌肉力量设定，以及可动范围设定没有任何问题后，两人终于松了口气。

「嗯，看来没有问题。」

「是啊。」

仿佛对两人说的话有反应那般，人偶依旧躺着，将犹如玻璃般无机物的眼睛转向札诺巴。

然后就那样开口说道：

「Master，请告诉我您的名字。」

「本人是札诺巴！」

「Master札诺巴，已完成登录。请下达命令。」

「将这位先生登录为Sub master。」

「明白了。这位先生，请告诉我您的名字。」

「我是鲁迪乌斯。」

「Sub master鲁迪乌斯，已完成登录。请下达命令。」

这行云流水的互动，在试作三号机的实验中也反复测试过好几次。

人偶在启动后，会先进行主人的登录，否则无法接受命令。

「嗯。那么，现在从床上下来，站到地板上吧。」

人偶听从指令从床上下来，笔直地站着。

看到这一幕，鲁迪乌斯握紧了拳头，兴奋地说：

「很好很好，不仅成功登录了Master的名字，也会听从命令。」

鲁迪乌斯抱着感动的心情低头看着人偶。

一开始真的满是挫折。

比方说，只要说札诺巴的名字，会被登录为「Master本人是札诺巴」。

其他还有人偶不从床上起来，甚至听不懂「站起来吧」中的「吧」这种细微语气......

这些问题，是透过佩尔基乌斯亲自传授的建议后才得以解决。

他们根据得到的提示不断改良魔法阵，再三地从头构筑术式。

所以现在才得以用这种形式实现。

他们完成的召唤魔法阵当中刻有核心，里面涵盖了人类本能的所有行为。

「轻轻跳跳看。」

「遵命，Master。」

人偶双脚并拢，轻轻跳了起来。

这个跳跃相当有力。

尽管人工肌肉具有足以破坏骨架的力量，但看来她能够确实地自律控制。

「在跳跃的同时张开双手。」

「遵命，Master。」

「把双脚打开......停下。」

「遵命，Master。」

「接着边跳边转动双臂。」

「遵命，Master。」

「双脚每跳跃一次就跟着做开合动作。」

「遵命，Master。」

人偶听从札诺巴的命令，同时精确地执行着指令。

短发随着动作摆动，肢体的动作充满跃动感，平衡感也相当良好。

「做个有趣的表情看看。」

听到札诺巴突如其来的命令，人偶有一瞬间停顿了一下。

「遵命，Master。」

她将手贴在脸颊，轻轻挤压脸部。

只是面无表情地歪着脸颊，看起来很奇怪。或许算不上有趣的表情。

不过，这是人偶基于自身的理解所执行的结果，换句话说，这结果符合预期。

「嗯，状况不错。」

「是啊......」

然而，鲁迪乌斯看到这个情况后，稍稍面露难色。

他的目光落在会随着跳跃晃动的小巧胸部，以及制作精巧的私密部位。

为了鲁迪乌斯的名誉必须事先声明，他并非以性欲的眼光看待。

毕竟这是他自己制作的人偶。只是，眼见完成度超乎想像，他不禁感到一丝恐惧。

是畏惧自身的才能吗？

非也。

「不过，真的太像了......不仅是脸，就连声音也意外相像。」

鲁迪乌斯看向人偶的脸。

人偶虽然与鲁迪乌斯四目相接，却笑也不笑。尽管她也具备微笑的功能，但没有命令就无法作用。然而，鲁迪乌斯视为问题的并不是这点。

「这绝对会生气吧......」

人偶的容貌与两人的一位熟人极为相似。

\\

「师傅指的是七星小姐吗？」

\\

没错，七星静香。

她是两人的朋友，目前沉睡于空中要塞Chaos Breaker的异世界人。

人偶与她惊人地相似。不仅是脸，头发虽然长度不同，但也同样是黑发，而且身高与体型也与她极为接近。

一具外貌酷似熟人的全裸人偶。

拥有性特征的胸部与实用性的下体构造。

「笨蛋，我说的是希露菲她们啊！」

没错，鲁迪乌斯真正害怕的，是自己妻子的怒火。

「不过，我们会这么做，不正是因为需要找一个人代替长眠的七星小姐吗？」

「是这样没错。」

没错，他们是有理由的。

她的朋友有可能会转移到这个世界，为了在这个假设成真时能加以应对，在将七星的名字流传后世的时候，最好也保留她本人的形象。基于这样的理由，他们将这个人偶制作得与七星非常相似。

「师傅的夫人们应该也知道这件事才是。」

「她们知道我在制作自动人偶，但还不知道我把人偶做得跟七星很像啦。」

话虽如此，鲁迪乌斯也不认为妻子们会因人偶的外貌酷似七星而责怪他。

毕竟他有充分的理由，而且七星本人也同意了这件事。

只要好好解释清楚，想必她们也能接受才对。

「问题是这胸部和下体啊。」

但是，假如这些构造可能被用于性用途的话就另当别论了。

与朋友十分相像的人偶有可能被利用在性行为上面。

要是他的妻子们得知这个事实，内心肯定无法平静。

根据解释的方式不同，鲁迪乌斯可能会在床上彻底遭到冷落。

希露菲可能会鼓着脸颊说：「既然你都花这么多心思做出来了，干脆去抱人偶如何？」，也可能反过来大哭一场，或者陷入沮丧。

无论如何，这对鲁迪乌斯来说都不是好事。

「其实没必要做到这么精细。」

「怎么会呢，这个造型如此精湛，毫无保留地体现出师傅的技术不是吗？特别是这乳头实在是非常色情。」

「笨蛋！札诺巴，我都刻意没说得那么露骨了，别直接讲什么乳头啊！」

「失礼了。」

为什么胸部和下体的部分要做得如此精细呢？

确实，当初构想这个计划时，曾经有过那样的设计概念。

那就是充气娃娃。

但现在已经远离了那种想法，本应该克制住才对。无论是胸部还是下体，都应该避开R18的设计，简单敷衍过去就行了。乳头根本没有存在的必要。

再说，这还只是试作四号机。

没必要在试作阶段就把她做得这么像七星。鲁迪乌斯显然是得意忘形了。

「总之，这事绝对不能告诉希露菲她们。」

「毕竟师傅是妻管严啊。」

「要说我爱老婆。」

目前知道人偶是以七星的外型设计的人屈指可数。

有奥尔斯帝德、佩尔基乌斯，以及七星本人。

当然，鲁迪乌斯本来打算在完成后公开展示，告知相关人员。

甚至还预定在接下来的计划中使用这个人偶......不过，若是那些相关人员知道鲁迪乌斯把人偶做得如此精巧，说不定也会用异样的眼神看他。

洛琪希可能会用阴沉的目光瞪视鲁迪乌斯，然后冷冷说出：「那个人偶身材比我还好呢？」，再不然就是摆出阴郁的表情与鲁迪乌斯保持距离。

要是洛琪希真的这样做，鲁迪乌斯只能选择切腹自尽了。

「唔嗯......我觉得师傅的夫人们不会因为这种事情而大动肝火。毕竟师傅您一向精力旺盛，大家都心知肚明。」

「若只是普通的人偶的话我也会这么认为，但偏偏她长得像七星，很有可能引来一场腥风血雨。」

鲁迪乌斯发出苦恼的声音，戳了戳人偶的胸部。

虽然触感还是与人类有些许不同，但非常柔软。如果不是自己制作的，或许会感到非常兴奋。但这份兴奋感也许会被解读为出轨的证据。

如果她们真的认为鲁迪乌斯出轨，艾莉丝可能会抿紧嘴巴，然后哼一声扭腰挥拳揍过来，将他压倒在地并坐到他身上。

然后会让鲁迪乌斯彻底了解自己是属于谁的，让他再也不敢出轨。

哎呀，这对鲁迪乌斯来说好像并不是件坏事。

「......」

顺带一提，人偶只是盯着戳在自己身上的手指，除此之外没有任何反应。

虽然有被碰触的感觉，但也就这样而已。

她并未被设计成会产生性方面的快感。

若是让艾莉娜丽洁或爱丽儿积极参与这项研究，说不定也有那样的可能，但她们现在忙于育儿，无暇分心。

「那么，干脆直接报废如何？」

札诺巴这样建议，但神情显得很低落。

对他来说，丢弃人偶并非令人愉快的事。无论是什么人偶都是如此。

「......不！其实完成度还是挺高的，就这样报废太浪费了！」

鲁迪乌斯环起双臂，陷入了苦恼。

如果考虑到最糟的情况，或许应该直接报废，重头设计一个新的比较妥当。因为就目前的技术来说，要更换胸部或下体部位的零件是不可能的。

如果未来进入量产阶段是可以考虑这么做，但现在这个是独一无二的试作品。

「不过，要是想到被人发现的话......」

「不会被发现的。我们不就是为此才特地把研究所盖在这种地方吗？」

「哎，说得也是啦......」

他们现在位于阿斯拉王国的菲托亚领地边界。

鲁迪乌斯向伯雷亚斯家借用了目前复兴当中的菲托亚领地一部分，将一栋房屋改建成了研究所。

知道这地方的人少之又少。

因为这间研究所不存在入口，只能透过转移魔法阵进出。

「你倒是无所谓，反正茱丽发现了也不会生那么大的气。」

「不，之前也跟师傅说过，最近茱丽会发脾气了。」

「啊，对，你有说过这件事。」

就连共同参与这项计划的茱丽也不晓得研究所的位置。

尽管她协助制作了人工肌肉与骨架，但并不知道最终会在哪里被组装。

这是在故意排挤她。因为最近每当札诺巴购买一些色情性感的人偶，茱丽会明显表现得很不悦。

虽然她再怎么样也不会破坏那些人偶，但偶尔会将人偶藏到札诺巴找不到的地方。

这也是无可奈何。

虽说茱丽早已成年，成为了一名大人，但她的年龄正值青春期......正是敏感的时候。

两人对于正值青春期的少女还是有一定的体谅之心。

「不过，茱丽可能会发现地下的转移魔法阵吧？」

通往这个研究所的转移魔法阵位于札诺巴工房的地下。

如果茱丽进入地下室，发现了转移魔法阵，并因为好奇心的驱使踩了上去......

她就会目击到这具自动人偶。

到时她肯定会大受打击。

「请放心，这扇门是从内侧锁住的。而且唯一的钥匙就在本人手上。」

「这种锁茱丽可以自己打开啦。毕竟我教过她怎么用土魔术开锁了。」

「不，茱丽与本人有过约定，她绝对不会打开本人上锁的门。」

「原来如此。」

茱丽与札诺巴虽然有着不寻常的默契，但彼此依然是主仆关系。

她也明白有些状况是不能逾矩的。

「先言归正传吧。我们接下来该怎么做呢？」

札诺巴的提问让鲁迪乌斯重新陷入沉思。

仔细想想，那具人偶只是附了乳头和下体，其他没有特别危险的地方。

况且，这毕竟只是试作四号机，要报废的话，先等搜集完数据再说也不迟。

「好吧，虽然可惜，但先搜集数据后再报废吧。」

鲁迪乌斯最终得出了这样的结论。

不能责怪他没有立刻下定决心报废这个人偶。毕竟他在这具人偶投入了大量金钱与精力，加上本应在试作三号机进行的实验也尚未完成。

仅仅因为乳头看起来过于色情就直接报废，这样也实在太浪费了。

就在这时，札诺巴灵机一动，如此提出建议。

「对了师傅！」

「怎么了？」

「给她穿上衣服不就行了吗！」

「哦？喔喔，对啊！你说得没错！」

听到札诺巴的提议，鲁迪乌斯也顿时恍然大悟。

归根究柢，看得见才是问题所在。

给人偶穿上衣服的话，自然也能遮住色情的部位。只要不是什么强奸犯，就不可能突然剥掉她身上的衣服。换句话说，只要不说就没人知道。

「好──先等我一下。」

鲁迪乌斯这样说完，立刻冲向隔壁房间。

那里有着他事先准备好的衣服。

那套是厚实的米色连身裙，在魔法都市随处可见。

不仅如此，他还备妥了内裤和胸罩。

当然，这些都是全新的。因为他本来就计划给人偶穿上衣服。

两人完全忘记了这件事，所以才因为赤裸少女如此色情而颤栗不已。

「来，把这件衣服穿上。」

「遵命，Master。」

「穿好后，回到床上躺着。」

「遵命，Master。」

鲁迪乌斯吩咐杵在原地不动的人偶穿上衣服，让她重新躺回床上。

穿上衣服后，原本悖德且色情的感觉瞬间消失。

现在，床上只有一个长得很像七星的女孩，贴紧床铺安稳地躺着。

完全没有悖德的感觉。虽然她双眼睁得老大、眨也不眨，感觉是有些诡异。

但如果是这副模样，好像就解决了所有问题。

「......总觉得好累啊。虽然有点早，但今天就先到这里吧。」

「说得也是。」

确定了暂时的方针后，鲁迪乌斯松了一口气，坐到椅子上。

虽然今天只完成了启动实验，但结果很不错。没必要着急，明天再开始教导人偶各种知识就行了。

鲁迪乌斯这么想着，轻轻拍了拍手。

「总之，今天就来庆祝一下吧！为我们计划伟大的第一步干杯！」

「是！本人早就知道师傅会这么说，已经事先准备好了，请看！」

札诺巴把放在房间角落的酒桶举起，接着放到中央，用拳头敲碎桶盖。

破裂的声音响起，里面的液体溅出了些许。

「喔喔，准备得很周到嘛！」

札诺巴拿出早已准备好的杯子，从酒桶中舀起内容物。

不久，杯子里面装满了半透明的紫色液体。

这是阿斯拉王国出产的葡萄酒。

「啊，有吃的吗？」

「只有一些储备干粮。」

「嗯，那个就行了。」

两人从地下室拿来大量干粮，堆在酒桶旁边。

接着，他们举起倒满葡萄酒的杯子。

「那么，为人偶计划有所进展。」

「为我们能实现梦想。」

「干杯！」

两人的庆祝酒宴就此开始。

\\

★　★　★

\\

「不过，该从什么开始教她呢？」

「总之，目前已经完成了基本的动作确认，再来想要测试她的应变能力、记忆能力，以及思考的柔软度极限这些呢......」

「需要调查的事情还很多，我们尽可能多验证一些吧。」

两人一边喝酒，一边商讨着接下来的计划。

刚才启动的时候，并没有让人偶做什么复杂的动作。

但是，人偶已经能对模糊的指令做出合理的解释，并付诸实行。

她会凭借初期设定中具备的基础知识，自动进行学习。

然而，她的智能究竟能成长到什么程度，目前仍是未知数。还无法得知最终能记住多少、能做到什么、能够自行思考到什么程度，判断能力又到哪里......

「请包在本人身上。本人会负起责任，教导她各种事情的。」

「你可别把不该教的也教了啊？」

「这句话，本人就原封不动地还给师傅吧。」

「你现在也懂得开玩笑了啊。」

「哈哈哈哈哈。」

两人思考着未来的发展，开怀大笑，边喝酒边填饱肚子。

这时，札诺巴忽然换了个话题。

「对了，师傅制作的『副产品』也很有销量。」

「听你这么一说，在研究途中确实做了不少东西，原来拿去商店卖了吗？」

「其中评价最好的，应该是那个『青蛙袋』。」

「啊......」

鲁迪乌斯曾为了模拟人类肌肤的质感重复了无数次错误尝试。

其中，强固青蛙的颊囊不仅特别薄，也具有极佳的延展性，而且十分坚韧，不容易撕裂。当初他本打算用这种材料制作人偶的皮肤，结果后来找到更好的材料，便放弃了这个方案。

不过，这种材料反而制造出其他东西，那就是......

「避孕套吗？」

简而言之，就是保险套。

「没错。尤其是路克先生非常中意，还提议要在阿斯拉建设工厂。」

「阿斯拉贵族真的很喜欢这种东西啊......」

「话虽如此，师傅您也在用吧？」

「嗯，是啊。」

是的，鲁迪乌斯也是爱用者。

而且几乎是每晚都会用到。

在三女莉莉和四女克莉丝出生后，他们之间有个不言而喻的共识，那就是下一个生孩子的是希露菲。

因此，他现在主要的对象是希露菲，与洛琪希和艾莉丝的恩爱时间相对减少。

然而，或许是因为种族特性，希露菲一直没有怀上第三胎。能怀上露西和齐格或许只是刚好遇上周期与运气加成，再不然就是神明在对他们开玩笑吧......

虽然不清楚真正的原因为何，可是一旦次数减少，艾莉丝便会开始坐立不安。

尽管与某个时期相比已经有所收敛，但艾莉丝依然有着极为强烈的性欲。

那头野兽，正在对鲁迪乌斯虎视眈眈。

再这样下去，鲁迪乌斯会被轻易地压倒在地，让艾莉丝再次怀孕。

这时，避孕套便派上了用场。

只要用了这个，哎呀真是不可思议，不仅能让艾莉丝这头野兽满足，也不会怀孕。

如此一来，希露菲就不会看到艾莉丝的肚子怀着第三胎，搔着脸颊、露出寂寞的表情，艾莉丝也不会露出非常心虚的表情说：「什么啦......」，家人之间的气氛也不会变得尴尬。

这个奇迹般的产品，现在竟然只需一枚阿斯拉银币。

「......嗯，该怎么说呢，明明照顾的人手没有增加，却只有孩子变多也不是什么好事吧。」

「那么雇个佣人不就成了吗？」

「要是雇了佣人，我就没办法自己照顾孩子了吧。现在六个孩子都已经有点多了。别看我这样，我还是希望能一个一个地照顾他们。」

「哈哈哈......真像师傅的作风呢。」

札诺巴愉快地笑着。

鲁迪乌斯看着他，忽然问了他一个长久以来积在心里的疑问。

「话说，你和茱丽怎么样？」

「怎么样是指？」

「那个，你不打算再婚吗？」

「和茱丽是吗？」

「嗯，是有点年龄差距，茱丽的身分也不算高......不过你现在也不觉得自己是王族了吧？结婚可是很棒的喔。有孩子围绕在身边，你可以夸奖他们，偶尔被他们恶作剧，事后再好好教育他们一番之类的。」

听到鲁迪乌斯的话，札诺巴缓缓摇了摇头。

「本人......不会结婚。」

「......这样啊。」

听到札诺巴的语气如此果断，鲁迪乌斯只是这样回应，就闭上了嘴。

每个人都有不想让别人涉足的领域。札诺巴之所以这样说，并非是单纯因为「不想」而不做，其中还牵涉到许多事情。像是王族的身分、曾经的那段婚姻、遭到杀害的弟弟以及帕库斯等种种因素。

「其实也没什么大不了的，您想知道吗？」

「如果你愿意说的话。」

「本人是神子，拥有怪力和坚韧的身体，但代价是皮肤的感觉相对迟钝。」

「意思是？」

「活生生的女性肌肤对本人过于柔软，不够刺激。」

这番话让鲁迪乌斯像是被揍了一拳那样震撼。

原来是关于黄色的那种。不过，这样有些事也就说得通了。像是札诺巴为什么总是拿铜像来用之类的。

「当然，并不是只有这样。比如说帕库斯、朱利亚斯，还有其他种种。不过最主要的理由，是本人觉得若与无法生育的人成婚，对方想必也会为此痛苦。」

「这样啊......不过，该怎么说，有机会的话，或许你也可以问问茱丽。她说不定会觉得，不一定......非得要有孩子不可。而且，也可以考虑用领养的。」

鲁迪乌斯的语气略显犹豫，这是因为他自己已经有六个孩子了。

「哈哈，说得也是。」

看到札诺巴强颜欢笑，鲁迪乌斯决定收敛这个有关结婚的话题，转回原本在聊的事情。

现在正在开庆祝的酒宴。

应该要好好享受，痛快地喝才对。

「总之，先别管什么保险套了！其他东西呢？卖得好吗？」

「其他的倒是普普通通。那些似乎被当作奇异商品，顶多只有部分爱好者会买来收藏。」

「我觉得还挺实用的啊......像吸尘器什么的，爱夏可是高兴得不得了......」

鲁迪乌斯制作的副产品可谓五花八门。

种类包括用魔法阵制作的电风扇、吸尘器、防水用品、保冷箱等等。

尽管每样东西都很方便，无奈能够普及的少之又少。

因为这些东西的功能大多能透过魔术重现，而且因为材料特殊，价格也非得设定得较高。

假如对材料的相关研究有所进展，或许能降低售价，但这并非鲁迪乌斯的目的。

「这些东西是很方便，但阿斯拉和米里斯早已有类似效果的魔道具存在。而且雇个佣人可能来得更快、更方便。」

「我倒觉得雇个佣人反而麻烦啊。」

鲁迪乌斯大口喝酒，叹了口气。

尽管他在这个世界生活了许多年，已经可说是这边的人了，但内心深处依然带有前世的观念。

「算了，把技术留下来也好，说不定后人会用得上。至少把制作方法汇整成一本书吧。」

「哦哦，这是个好主意。肯定会在今后出现继承师傅遗志的人，将这本书视为梦幻之书吧！」

「就取名叫《鲁迪乌斯之书》之类的？」

「哈哈哈，后世的魔术师们一定作梦也没想到，冠以龙神左右手之名的魔导书，上头记载竟然的是日用杂货的制作方法！」

两人就这样愉快地喝着酒。

随后，他们的脸色越来越红。一整桶葡萄酒对他们来说似乎还是有点太多了。

「克里夫和巴迪陛下不在这里，实在很可惜。」

「......以克里夫先生的为人，恐怕不会允许制作这样不贞的人偶吧。」

「克里夫前辈可能会很傻眼，但还是会接受的。要进行下一步时邀请他吧。甚至可以在米里斯的克里夫房间里举杯庆祝。」

「就这么做吧！噢，对了！不如透过这次的试作机确实完成研究，再把光荣的自动人偶第一号送给克里夫先生当礼物如何？」

「好主意！啊，不过，既然是送给克里夫，少女型就不太适合啊......改成少年型吧。」

「少年型也不错！」

「哎呀，札诺巴殿下，原来您对那方面也有兴趣？」

「尽管本人不好男色，但自认很了解年幼少年人偶的魅力。难道师傅对这方面不清楚吗？」

「我也懂啦。如果菲兹前辈是男的，我大概也能接受吧。」

「哈哈哈，不愧是师傅！」

随着酒宴的气氛热络起来，两人逐渐喝得酩酊大醉。

这酒喝起来很痛快。与老友一同研究、以成果为话题饮酒作乐。

「好──那下一个就做少年型吧。要做一个帅到让克里夫嫉妒的那种。」

「哈哈哈！哈哈哈哈哈！」

......然而，他们并没有注意到。

在他们畅饮美酒时，有一道目光正紧盯着这边。也没发现他们愉快的谈话内容已经被彻底听了进去。

更没发现，那个人听完后，咧嘴一笑。

\\

★　★　★

\\

「唔喔......头好痛。」

隔天早上。

鲁迪乌斯用解毒魔法缓解酒醉的头痛，慢慢起身。

当他看向窗外，发现暴风雨早已平息，眼前是一片万里无云的晴空。

「已经中午了吗......喝得有点多了啊......」

但不管怎么说，和男人一起喝的酒总是特别好喝。

尤其是庆祝的酒，那就更是如此了。尽管昨天被人偶的下流模样搞得有些不知所措，但现在回头想想，既然试作机完成度就这么高，那将来必定大有可为。

梦想无限扩大，希望涌现，爱意满溢而出。

怀抱着这样的情绪，鲁迪乌斯打算靠近人偶，看看她的脸......

「......奇怪？」

她不见了。

人偶不在床上。

眼前只剩下一张空荡荡的床。

「等等，咦？什么情况？呃，札诺巴～！人偶去哪了～？」

鲁迪乌斯心想，或许是札诺巴先醒来，正在教导人偶一些知识吧。

他抱着这种想法环顾四周。

就在这时，裹在毛毯里的札诺巴从房间角落慢吞吞地爬了起来。

「嗯～......师傅，人偶应该在床上停止动作了吧。」

「停止？」

听到这句话，鲁迪乌斯才忽然想起。

确实，昨晚他让人偶穿上衣服后，将她放回床上。

没错，绝对是放回去了。

「............我有停止她吗？」

然而，要让人偶停止机能，需要下达停止命令或是休眠命令。

必须将手放在胸口的魔石上，咏唱咒语。

他记得自己并没有这么做。

「快......快找！」

「明......明白了！」

两人慌张地开始寻找人偶。

但是，无论在研究所里面还是外面，都不见人偶的踪影。

人偶就这样忽然消失不见了。

*** 「人偶行走之日　中篇」

那一天，艾莉娜丽洁正牵着儿子一起去购物。

她与儿子克莱夫手牵着手出门买东西。

尽管她已经生养了许多孩子，但能和自己的孩子牵着手一同出门，始终令她感到开心。

尤其是克莱夫，他与丈夫克里夫非常相像。

无论是与克里夫相似的发色、与克里夫相似的嘴角，甚至连毫无根据地相信自己是最棒的那种地方，都与克里夫如出一辙。每当与克莱夫在一起，艾莉娜丽洁便会想起刚认识时的克里夫，嘴角自然地流下口水......更正，是露出一抹笑容。

「妈妈，买南瓜！我们买南瓜！买南瓜嘛！」

「哎呀，说得也是。这个季节的南瓜特别好吃呢......」

「不是啦！因为吃南瓜会长高的喔！」

「这是谁告诉你的？」

「露西！」

艾莉娜丽洁的儿子克莱夫是个俊美的少年。

尤其是眼睛与脸部轮廓之类，与艾莉娜丽洁非常相像。他将来肯定不仅在人族会很受欢迎，甚至在长耳族精灵也会成为众人追捧的对象。

然而，他的身高遗传了父亲，比平均身高略低。

克莱夫似乎对此有些自卑。因此，他在家中经常动不动就说自己想要长高。

「你长那么高要做什么呢？」

「秘密！」

克莱夫脸上微微染起红晕，这样说道。

不过，艾莉娜丽洁早已知道这个答案──是露西。

克莱夫喜欢比他大两岁的露西。

他之所以想要长得更高，是为了让露西觉得他很帅气。

「希望你能快点长高呢。」

艾莉娜丽洁很喜欢看到儿子这种男孩子气的一面。

「哎呀？」

就在这时，艾莉娜丽洁的长耳朵捕捉到一个熟悉的声音。

（喂喂，这世上可是有个常识叫礼尚往来啊。）

（这位小姐姐，告诉我们你会发出什么样的声音好不好？）

声音是从小巷传来。

艾莉娜丽洁循着声音望去，有名少女在一家酒馆的后巷被两名男子抓住了手。

她认识那名少女。

以艾莉娜丽洁来说实属罕见，因为她有印象的并非男性的声音。

「问我会发出什么样的声音？就是现在这个声音。」

「你是这样想吗？不过，人类其实可以发出更棒的声音呢。」

「过来，让我们去前面的旅社听听看吧，好不好？可以吧？如何？」

女孩虽然没有明显表现出反感，但就艾莉娜丽洁所知，她不是会喜欢这种邀请的人。

虽然表面上没有流露情绪，但她应该很困扰吧。

「你们等一下。」

艾莉娜丽洁将手中的购物袋放下，向两人打了声招呼。

男人们立刻转过头来，这样说道：

「你是谁啊？」

「那位小姐是鲁迪乌斯的朋友。要搭讪的话我建议你们换个目标。」

两个男人的视线将艾莉娜丽洁从头到脚打量了一遍。

「换个目标......比如说你吗，这位姐姐？」

「嘿，明明旁边还带着那么小的弟弟，真是个淫乱的女人。」

「哎呀，居然说他是弟弟，真会说话呢。」

艾莉娜丽洁用手轻抚脸颊，羞涩地露出微笑。

虽然表面上态度轻佻，但她已经看出这两人是外地人。

他们八成是流浪的冒险者吧。如果居住在这个城镇，听到鲁迪乌斯的名字不可能还会死缠烂打。

「你们......哎呀？」

话才说到一半，满脸通红的克莱夫就突然站了出来。

他手上还拿着不知道从哪里捡来的木棒。

「不准碰我妈妈！」

「克莱夫，妈妈很感谢你的心意，但对付这种程度的对手，妈妈不要紧的。你先退后吧。」

「唔哇......」

艾莉娜丽洁轻轻把克莱夫提起，放到自己身后。

她心想待会要好好夸奖一下这孩子，同时将手搭上腰间的剑柄。

「这种程度？......我们可是A级冒险者啊。」

「哎呀......真厉害，年纪轻轻就能达到A级，看来你们非常有才能呢。」

「咻～你看起来倒挺轻松的嘛。看来你对自己的本领很有自信啊。」

「不，非常不巧，我只是个普通人。」

随后，男人拔出身上的剑，看得出那把剑是他们惯用的武器。

艾莉娜丽洁也带了护身用的剑，遗憾的是她惯用的盾并不在身边。如果对方实力真的很强，二对一势必会是一场硬仗。

「放心吧，让你稍微吃点苦头之后，就会让你爽个够的。」

艾莉娜丽洁没有拔剑。

两人见状，认为她八成是怕了，脸上露出猥琐的笑容，缓缓靠近她。

看到他们与少女拉开距离后，艾莉娜丽洁深深吸了一口气，放声尖叫。

「呀啊啊啊啊啊啊啊！救命啊啊啊！有人要绑架我────！」

尖锐的叫声回荡在巷弄之中。

两个男人顿时被这声音吓了一跳。

「唔喔！」

「我......我们又不是绑架犯......！」

然而，艾莉娜丽洁的声音只是徒然地响彻四周。

没有任何人被她的叫声引来，巷子里依然是一片安静。

「......嘿，竟然敢吓我们。这里可是白天的酒馆后巷，怎么可能有人会来。」

「如果你想叫的话，待会儿在床上随便你叫......」

就在这时。

突然间，四周建筑物的房门接连打开。

「磅！磅！磅！」的声音以时间差响起，门一扇接一扇地被推开，随后一群男人从里面走了出来。

这群男人身穿漆黑大衣、毛发浓密，大衣背后画着一个徽章，看起来像是......黄色的老虎。

是鲁德佣兵团。

他们正好在处理佣兵团的工作，帮忙酒馆搬运晚上要卖的酒。

「艾莉娜丽洁大姐头！」

「你们两个！知道自己惹的是谁吗！」

「是想跟我们鲁德佣兵团作对吗！」

「竟敢挑衅我们，找死是吗！」

他们平常礼仪端正，维护着地区的和平，可是一旦面对无赖或伤害他们团员的人，会立刻变得犹如凶神恶煞。

而且，鲁德佣兵团的人数至少超过十个人。

如果是鲁迪乌斯，想必在遭到恐吓的当下就道歉了。不，他会在窗户以及房门打开的瞬间就把头贴在地面，肯定是这样。

「............啊，对不起。」

「我们不知道......这个人这么了不起......因为我们昨天才到这里......」

僵住的两名男子在两秒后扔下手中的剑，立刻开始道歉。

恭喜，鲁迪乌斯的名声被守住了。他并不是一个胆小的懦夫。

没错，要是从建筑物里面跑出一群毛发浓密的佣兵，想必任谁都会低头认错。

「大姐头，要怎么处理？」

「他们还没对我做什么，适当教训一下就行了。请顺便告诉他们这一带的规矩吧。」

「明白！好，那你们过来一下！」

「啊，可是我们，那个──」

「给我过来。」

「待会儿还跟人有约──」

「少废话，快点给我过来！」

目送两名冒险者遭到兽族佣兵押送到酒馆之后，艾莉娜丽洁走近那名少女。

「七星，好久不见了......已经到了你醒来的日子吗？真难得你会来镇上呢。」

那名少女正是七星。

七星挂着不以为意的表情点了点头。

「我是昨晚醒来的。」

「是吗......？总之，在这种地方也不妥当，我们快点离开吧。」

艾莉娜丽洁这样说完，握住七星的手。

这时，她忽然察觉到异样。

「哎呀，七星......你的头发是什么时候剪的？」

在艾莉娜丽洁的记忆中，七星的发型一直是长发。

然而现在却剪成了齐颈的短发。

这让艾莉娜丽洁有些不解地歪了歪头。

被称作七星的少女听到这个问题，嘴角微微上扬，莞尔一笑。

那笑容看起来很不自然。仿佛是在透过笑容掩饰着某些困扰或难以启齿的事情，又像是有什么企图那样......

敏锐的艾莉娜丽洁看到她的表情，顿时心领神会。

「看来你似乎有些隐情呢......如果不介意的话，我可以听听你的状况。你现在有空吗？」

「目前没有重要的任务。」

「那我们去那边的咖啡厅坐坐吧。」

艾莉娜丽洁牵起有些不悦的克莱夫，捡起地上的购物袋后这样询问。

「克莱夫？哎呀，你为什么不高兴呢？怎么？因为没办法保护妈妈而不甘心吗？真是的，你该保护的不是妈妈，而是该去保护你喜欢的女孩子喔......好了，七星，你怎么愣在那里？过来啊。」

随后，艾莉娜丽洁便带着七星前往附近的咖啡厅。

\\

★　★　★

\\

「不过话说回来，刚刚还真是危险呢。幸好是在酒馆后巷，很快就有人来帮忙。」

几分钟后，两人已经面对面坐在咖啡厅内。

现在她们面前摆着相同的果汁。

因为在艾莉娜丽洁点完后，七星依样画葫芦点了同样的东西。

顺带一提，克莱夫的面前放着一份略为精致的甜点。

最近，这一带的砂糖价格较为便宜、出货稳定，因此店家开始制作糖渍水果的这类点心。

七星看起来像是第一次来这家店，她四处张望，脖子和眼珠不停动来动去。

「所以，你发生了什么事？」

「目前存在着诸多事实，难以归结于一点。请缩小问题范围。」

「......你以前是这样讲话来着？」

艾莉娜丽洁顿时有些疑惑，但随即想到，人一旦经历了难受的遭遇，说话方式发生变化也是常有的事，就这样自己做出了解释。

人一旦变得固执，语气也会变得强硬起来。

「那么，麻烦你从头开始说起吧。」

「从头开始吗？」

「对，从最开始的地方。」

七星眨了两下眼，然后开始说道：

「我是在昨晚醒来。醒来时，札诺巴大人与鲁迪乌斯大人就在身边。」

「哎呀，居然跑进少女的寝室，他们也真是不像话。」

「他们两位看到我一丝不挂的身体，神情显得相当开心。」

「啥......？」

「接着，他们要我伸展手脚，触摸我的胸部，对我的身体进行了彻底的检查。然后，他们开始讨论是否该使用我，一轮下来满足之后，得到的结论是将我用完就丢。最后，他们让我躺回床上，置之不理，自己就这样去睡了。」

就算是艾莉娜丽洁，听到这里也有一瞬间陷入了呆滞。

她脑海中浮现的画面，是带着猥琐笑容的鲁迪乌斯和札诺巴在七星熟睡时剥去她的衣物，强行叫醒她之后对她做出色色的行为。

艾莉娜丽洁见过许多类似的男人，这样的想像对她而言并不困难。

「所以，你没有抵抗吗？」

「抵抗是无意义的。」

「也对。毕竟对方可是鲁迪乌斯和札诺巴啊......那么佩尔基乌斯大人与其他人并不在场吗？」

「只有他们两位。」

艾莉娜丽洁不太了解佩尔基乌斯的日常生活。

不过，就算是佩尔基乌斯，也有可能会离开城堡外出吧。

「这......这件事是......第一次发生吗？」

「是的。不过，看来札诺巴大人与鲁迪乌斯大人早有计划，正在进行相关的准备──」

「意思是，他们有可能从很久以前就计划好了吗？」

如果是他们两个，要知道佩尔基乌斯会在哪一天外出想必是轻而易举。

而且，要掌握佩尔基乌斯外出的那天碰巧与七星醒来那天重叠的时间点，也并非难事。

「......」

艾莉娜丽洁是一个冷静的女人。

她会根据丰富的经验，从容地展开思考，是个在突发状况下也能冷静行动的女人。

然而就算是她，一旦遭到自己信任的人背叛，也足以令她感到动摇。

她实在无法相信鲁迪乌斯会这么做。姑且不论看起来没有异性缘的札诺巴，那个平日身边总是有妻子与孩子们陪伴，既被爱也充满爱的鲁迪乌斯......？

那个为了保护家人，不惜抱着必死的觉悟挑战奥尔斯帝德的鲁迪乌斯？

那个夜晚在床上要希露菲和洛琪希那样还有这样的鲁迪乌斯？

那个夜晚在床上被艾莉丝那样还有这样的鲁迪乌斯？

他竟然会对七星......对那个拼命找方法回去故乡的七星？

她心里觉得这怎么可能。

一定是有哪里搞错了。

鲁迪乌斯总是真诚地帮助那么努力的她不是吗？即使希露菲因此嫉妒，他也从未放弃帮助七星不是吗？

为了拯救她，他甚至不惜前往魔大陆，还与魔王阿托菲交手不是吗？

但是，看看七星的表情。除了刚才那一抹让人感到不对劲的笑容，她脸上始终没有任何表情，像人偶一样。

不笑，也不哭。甚至连头发也剪短了，直接剪到肩膀的位置。

七星虽然看起来那样，但其实很用心在保养头发。

然而，现在却显得有些干燥，失去光泽。

艾莉娜丽洁与七星的关系并非那么亲密。

不过，两人也算认识了很长一段时间。她与七星有过一定程度的交流，自认对七星的个性有一定了解。但是，她从未看过七星这么受到打击。

要说这是七星编造的谎言，实在也不太可能。

她不晓得真相到底是什么。

说不定，这是某个人为了陷害鲁迪乌斯和札诺巴而设下的圈套。

确实。这世上存在着许多能够用来改变自身外表的魔力附加品。

话虽如此，就算真的动用了那种道具，要潜入空中要塞的深处并对七星做些什么是不可能的。能做到这一点的，只有对佩尔基乌斯的行动有一定程度的了解，且能自由进出空中要塞的人。

符合这个条件的人少之又少。

「......」

艾莉娜丽洁这几年来从未像现在这样如此混乱。

究竟发生了什么事？事情的真相到底是什么......

她唯一能确定的只有一件事。

「你很难受吧。」

艾莉娜丽洁站起来，移动到七星旁边，紧紧抱住她。

她唯一能确定的，就是眼前这名少女的内心受到了严重的伤害。

「艾莉娜丽洁大人，我的话还没......」

「不要紧，已经够了。谢谢你愿意把这么难受的事说出来......虽然有点难以置信......不对。背叛信赖是不可饶恕的。我一定会好好惩罚鲁迪乌斯他们。」

因此，艾莉娜丽洁决定之后再追查事情的真相，现在最重要的是安慰七星受伤的心灵。

「鲁迪乌斯大人犯了什么罪吗？」

「是啊，他做了非常过分的事。」

「请问是什么事？」

「他伤害了你。不对，不仅是伤害你而已。根据状况，他甚至也伤害到了他的妻子......希露菲、洛琪希与艾莉丝。」

「但我并未受到伤害。」

「不，你的心受到了伤害。」

「心......」

艾莉娜丽洁紧紧抱住七星，但随即涌起了一丝不协调感。

总觉得，这个怀抱的触感有些奇怪。正因艾莉娜丽洁拥抱过无数人，所以她才能感觉到，以前从未有人抱起来是这样的触感。虽然无法明确说出那种不协调感的具体来源，但那感觉就仿佛她不是人类那样......

「找到你了！」

就在这时，一声大喊响彻宁静的咖啡厅。

艾莉娜丽洁抬头望向门口，只见一名穿着老鼠色长袍的男人正指向这边。

那人是鲁迪乌斯。他的身后还跟着札诺巴。

不仅他们两人，还有鲁德佣兵团的成员。

「抓住她！」

听到鲁迪乌斯的呐喊，艾莉娜丽洁抱紧七星的力道变强，差点大喊叫他们等一下。

但是在那之前，自己怀中的人已采取行动。

七星以远远超乎艾莉娜丽洁想像的力道甩开她的手，随后又以惊人的速度把桌子掀了起来，再从附近的窗户一跃而出。

玻璃碎裂的声音响起，七星的身影瞬间消失。

她的速度快得吓人，仿佛达到了圣级剑士的水准。

在场的所有人都没办法追上她。

鲁德佣兵团的成员也纷纷因为她那超人的速度而目瞪口呆。

「会长、札诺巴大人......她的速度太快了，那样根本追不上。」

「这也难怪。那可是师傅制造的自动人偶。那具身体无论力量还是速度，都并非平凡战士可以望其项背。」

「不是那个问题啦......总之，她现在还没办法隐蔽行动，先派人四处搜寻吧。只要知道她的藏身处，我和札诺巴就能设法捉到她。」

鲁迪乌斯露出疲惫的表情指挥着佣兵团，同时走向艾莉娜丽洁。

眼见克莱夫瞪大双眼拿着叉子，鲁迪乌斯轻轻拍了拍他的头，确认他是否没有受伤。

随后，他向艾莉娜丽洁伸出手。

「对不起，艾莉娜丽洁小姐，你没事吧？她没对你做什么吧？」

「......嗯，当然没有。」

艾莉娜丽洁握住他的手站了起来。

「所以，究竟发生了什么事？」

「啊，简单来说呢......」

在听完鲁迪乌斯的解释后，艾莉娜丽洁稍稍松了一口气。

啊，果然是自己误会了什么。

\\

★　★　★

\\

艾莉丝在家里面要做的家务，就是带着雷欧与孩子们散步。

当然，她也会教导孩子们剑术，或在学校指导部分学生。

但要说到真正属于「家务」的工作，就只有散步而已。

若没有其他要紧的事，她通常会选择在午后出门散步。

由于带着全部孩子出门也很危险，所以通常只带两三个。

当雷欧外出散步时，菈菈总是自然而然地跳到它的背上，这让艾莉丝实际上只需要照顾一到两个孩子。

这天，菈菈与齐格坐在雷欧的背上，还年幼的莉莉则坐在艾莉丝的肩上。

像这样带着孩子们在镇上走走，然后在一个合适的地方看着他们玩耍，这就是艾莉丝每日的例行公事。

不久之前，她是带着露西、菈菈和亚尔斯这三个孩子，有时候克莱夫也会加入。

那时的菈菈经常被附近男孩拉扯头发，露西看到之后就会上前阻止。

不过，最近菈菈或许是因为经过艾莉丝的锻炼，经常会直接反击。一个不注意，就会看到菈菈脸上挂着伤痕、流着鼻血站在那里。而不远处，会有个疑似被她打哭的男孩蹲在地上。

菈菈每当这种时候与艾莉丝对视，就会面无表情地竖起两根手指，宣告自己的胜利。

艾莉丝看到这样的场景，心里会有些挣扎。

自己小时候要是每次打架让对方哭了，都会遭到大人责骂。

会被念说「贵族的女儿不该打架。若是对方说了什么，你就用嘴巴反驳回去」。

因此她会有一瞬间犹豫，觉得自己是否也该训斥菈菈？

然而，大多时候她还是会选择夸奖。

因为菈菈这孩子本来话就不多。

她是为了保护自己而打倒敌人，也对此感到自豪。

这种时候怎能不好好夸奖她说「干得好，不愧是我的女儿」。

当然，假如菈菈攻击的对象明显比她弱小，比如说让齐格哭了之类的，即使是艾莉丝也会生气，甚至可能把她屁股打到红肿起来。

可是，那些男孩子既比菈菈高大又比她年长。所以，艾莉丝认为表扬她才是正确答案。

想到菈菈明年就要上学，只是夸奖她可能也不太妥当，但艾莉丝并没有考虑到这么远。

不过，今天艾莉丝决定不带孩子们去常去的公园，而是带他们到别的地方。这样想必菈菈也不会跟人打架了。

变更目的地并没什么特别的意义，纯粹只是当下的心情使然。

「不可以跑太远喔！」

如此这般，今天他们来到了郊外的河边游玩。

菈菈和齐格脱光衣服在河里玩耍，雷欧也混在他们里面一起游玩。

艾莉丝则是在看着莉莉。

莉莉最近才总算开始蹒跚学步。

或许是对河流感到新奇，她小心翼翼地触碰水面，感受到冰凉后惊喜地发出尖叫，然后扑向艾莉丝的怀里，反复着这样的动作。

「呀！妈妈──！妈妈──！」

「什么啦，你怕水吗？」

「好冷！」

听到这模棱两可的回答，艾莉丝浅浅一笑，摸了摸莉莉的头。

莉莉的长相与菈菈非常相像，但个性就稍微内向了点。

不过，她比菈菈更像个好奇宝宝，对新奇的、第一次看到的事物都会表现出强烈的兴趣。

这时，莉莉似乎发现了什么。

「妈妈！亮晶晶！」

「......亮晶晶？」

「闪闪发亮！」

艾莉丝循着莉莉指的方向望去，河面上反射着阳光，而其中有一道特别亮的光点。

是鱼。

一条和中指差不多大的小鱼在水中悠然游动。

「有鱼呢。」

「绰绰有余！」

「不是绰绰有余！是鱼喔。一个字就好了。跟我说一遍，『鱼』。」

「鱼！那个，妈妈，帮我抓！帮我抓鱼！」

「好好好......你看着喔。」

艾莉丝卷起袖子，仔细观察着水面。

几秒钟后，挥拳的声音响起，河川水面炸出了水花。

当莉莉反应过来时，鱼已经在艾莉丝的手里。那条鱼睁大了眼睛，嘴巴不断地一张一合，似乎还没搞清楚发生了什么。

「给你。」

「哇！哇！」

艾莉丝将鱼放在莉莉的手心上。

这时，鱼或许是终于意识到事态的危险性，开始跳动起来激烈挣扎。鱼最终滑出莉莉的手上，扑通一声掉回河里。

「被它逃掉了......」

「呵呵，被逃掉了呢......嗯？」

就在她们亲子互动的时候，艾莉丝突然感觉到某人的气息，转头望向远方。

「......有东西过来了。」

有某个物体从城镇方向高速接近，速度相当快。

这个速度，说不定与穿着魔导铠「二式改」的鲁迪乌斯，或者跟自己是同一级别。

「雷欧，让他们起来！衣服也穿好！」

艾莉丝这样大喊后，雷欧似乎也注意到了。它低吼一声，轻轻推了推菈菈的背。

菈菈很听话。

因为她能和雷欧交流，想必马上就理解了当下的情况。

相较之下，齐格还想继续玩闹，显得有些拖拖拉拉的，不过在菈菈拉着他的手后，他也不情愿地爬了上岸，开始用带来的布擦拭身体。

「菈菈，帮齐格穿衣服！」

齐格最近才刚学会自己穿衣服。

由于他连扣一个钮扣都要花很长时间，若是没人帮忙可能会拖得更久。

艾莉丝感到有点焦急。尽管从接近的那人身上感受不到敌意，但若要带着孩子们逃跑，对方的速度未免也太快了些。

就算对方是敌人，自己应该也能战胜，但最好还是先让孩子们逃走。

把三个孩子都放到雷欧的背上，自己留下来迎战对手。况且在这附近还有奥尔斯帝德的事务所。北神卡尔曼三世和龙神奥尔斯帝德就待在那里。

只要到了那里就一定安全，但是......

「......嗯？什么嘛。」

然而，当艾莉丝看清楚来者的身影后，不禁松了一口气。

因为那是张熟悉的脸。

拥有一头黑发的少女。

「原来是七星啊。」

七星原本打算直接跑过去，但听到有人叫了自己的名字，猛然停下脚步，回头看向艾莉丝。

「早安。恕我冒昧，能请您告诉我您的名字吗？」

「艾莉丝啊。怎么，你忘了吗？」

「艾莉丝大人。我记住了。」

艾莉丝感到有些不太对劲。

她头发变短了，动作异常快速，说话的语气也和平常不一样。

不过，艾莉丝和七星本来就不算特别亲近，她认为七星对自己的态度大概也就这样吧。

再说，艾莉丝的个性本来就不会在意这种小细节。

「怎么了？用这么惊人的速度跑过来，有人在追你吗？」

「是的......不，请容我订正，似乎已经甩开了。」

七星边回头看向背后一眼，同时如此回答。她身后只有一片广阔的平原。

「妈妈！妈妈！好厉害！」

这时，艾莉丝忽然看到莉莉缠在七星的脚边。

她正用小手不断拍着七星的小腿，眼神闪闪发亮。

「呀！」

七星用双手将莉莉抱了起来，莉莉随之开心地发出声音，笑了笑。

「早安。」

「呀、呀！」

莉莉一边笑着，同时抓住七星的头发轻轻拉扯，时而用手摸着她的脸颊，又时而抚弄她的鼻子。

艾莉丝不晓得为什么莉莉会那么亲近七星。

不过，她认为再怎么说也不能太失礼，便把莉莉从七星手中接过，将她抱到自己的肩上。

「咿──啊──妈妈，给我那个──」

「不行，这样很没礼貌。」

莉莉虽然发出有些不满的声音，但艾莉丝还是没把她放下。

七星见状，拨起了自己的一缕发丝。

「想要这个吗？」

「......嗯。」

在莉莉小心翼翼地点头后，七星竟然直接拔下几根头发，递给莉莉。

「请收下。」

「哇！」

莉莉接过后，脸上又露出了欣喜的神情。

艾莉丝不明白她为什么会这么高兴......不过还是暂时下了个结论，认为是因为黑发对莉莉来说很稀奇。

「艾莉丝大人，我可以问您几个问题吗？」

这时，七星转向艾莉丝，这样开口询问。

「什么事？」

「艾莉丝大人是鲁迪乌斯大人的妻子那位艾莉丝大人吗？」

「是啊。」

被对方称为妻子，艾莉丝骄傲地挺起了胸膛这样回答。

被这样再次确认，不由得让她感到自豪。

生下长子，像这样照顾着孩子们的自己，毫无疑问是名妻子，她对此充满自信。

「若是艾莉丝大人知晓我的存在，会对鲁迪乌斯大人生气吗？」

「存在......？我才不会因为那样生气。」

尽管不明白七星这个问题的意图，艾莉丝还是坦率地回答。

七星是鲁迪乌斯的朋友，只是聊聊天也没什么好生气的。

假如鲁迪乌斯对七星出手，或是要迎娶她成为第四个妻子，这样或许会有点生气，但也仅仅是「有点」而已。

「那么，希露菲大人与洛琪希大人呢？」

「我想她们也不会生......啊，不过......」

艾莉丝说到这里，突然想起希露菲曾经提到过某件事。

「之前希露菲有说过。如果『连七星也这样』她好像会无法接受。」

「无法接受，是吗？请问是指什么样的无法接受呢？」

「我不知道。不过，她真的很喜欢鲁迪乌斯，应该有一些自己的想法吧？」

艾莉丝虽然毫不避讳地公开表达自己爱着鲁迪乌斯，但她也对希露菲的奉献精神非常认同。

如果是为了鲁迪乌斯，希露菲甚至可以牺牲自己，强忍所有事情。

当然，艾莉丝在战斗方面，也有为了守护鲁迪乌斯而死的觉悟。

但那终究只是她自己想做的事情。艾莉丝对于自己绝对不想做的事情，恐怕很难妥协到最后。就算那是为了鲁迪乌斯也一样。

但希露菲能做到，为了鲁迪乌斯，她会容忍一切。

因此艾莉丝认同希露菲这样的地方。

「了解了。我想向希露菲大人询问一点事情，请问她现在在哪里？」

「她今天应该在家。」

「明白了。感谢您回答我的问题。」

七星微微鞠躬，嘴角露出一抹扭曲的笑容，随之转过身子，朝城镇的方向走去。

「结果她到底是想说什么啊？」

艾莉丝环起双臂，双脚微微打开到与肩膀同宽，用鼻子哼了一声。

这是最近亚尔斯经常模仿的姿势。

「......妈妈。」

艾莉丝回头望去，从雷欧身后看到蓝色与绿色的头发。

那是菈菈和齐格。仔细想想，刚才明明遇见了熟人，却没让孩子们跟对方打招呼。

这样的行为是不是不太好呢？平时雷欧总是会率先上前迎接对方，艾莉丝会在这时顺便让孩子们打招呼，但这次却一直没有让他们站到前面。

正当艾莉丝心中涌起这样的疑问时，菈菈轻声说道：

「......刚才那个人，不是七星小姐。」

菈菈的这句话让艾莉丝感到一股难以言喻的不安，紧紧地抿起嘴角。

而在她的肩上，莉莉正拿着七星给她的头发扯来扯去。

「............」

艾莉丝不晓得这股不安源自何处，认为应该立刻回家。

她原本是这样打算，但看向身边的孩子们，又改变了主意。

「我们现在去事务所。你们两个都骑到雷欧背上。」

艾莉丝决定先把孩子们送到安全的地方之后再回家。

随后，她让孩子们坐上雷欧的背，往事务所走去。

\\

★　★　★

\\

艾莉丝抵达事务所后，感觉四周弥漫着一股紧张的气氛。

她看到熟悉的鲁德佣兵团团员聚集在事务所前面。

不仅他们，也能看到札诺巴、茱丽、艾莉娜丽洁、克莱夫以及北神卡尔曼三世亚历山大等人。

然而，没有平常的那种不快感。

看样子奥尔斯帝德并不在事务所。

「艾莉丝！你怎么会来这里？」

从这个集团当中，鲁迪乌斯突然冲了出来。

看到他，艾莉丝顿时感到一阵安心。

同时，她也确信自己先前感到的那股不安很有可能与这里的状况有关。

「我在散步途中遇到了一个怪人。」

她并未回答问题，而是直接说出这件事，这让鲁迪乌斯的眼神瞬间严肃了起来。

「那是什么样的人？」

「一个看起来很像七星的家伙。」

鲁迪乌斯的表情明显变化，仿佛在说「那家伙是鲁○啊」。[fn:1]

他肯定是想立刻追问那人去了哪里，发生了什么事。

但比起这些，他更关心眼前的人。

「这样啊......所以，她有对你们做什么吗？应该没有人受伤吧？」

「孩子们都没事。」

鲁迪乌斯露出担心的表情，看着孩子们。

菈菈、齐格，还有正玩着头发的莉莉。

「艾莉丝呢？你有受伤吗？」

确认孩子们安然无恙后，鲁迪乌斯开始仔细确认艾莉丝身上是否受伤。

从脚尖到头顶，然后摸了摸她的脸，抓着她的肩膀让她转身，将手顺势按在胸口的隆起，就在这时他的下巴被拳头打中，直接裂开。

「我没事啦！这点小事用看的就知道了吧！」

「素滴......」

「她没对我们做什么，不过雷欧有察觉到那人是冒牌货，所以我才带孩子们先来这里避难。」

艾莉丝这样说着，看向雷欧。

下一刻，不知为何是菈菈露出了骄傲的神情，鼻子还得意地喷着气。

艾莉丝轻轻地拍了拍菈菈的头后，转身面向鲁迪乌斯。

「所以，那到底是怎么回事？」

「呃......」

鲁迪乌斯开始解释事情的来龙去脉。

其实，是他和札诺巴一起制作的自动人偶逃跑了。

由于现场留有转移魔法阵被使用过的痕迹，他们推测人偶应该还在魔法都市夏利亚。

于是鲁迪乌斯利用魔法阵回到工房，把正在睡懒觉的茱丽叫醒，并动用了鲁德佣兵团来搜寻整个镇上。

因为艾莉娜丽洁那起骚动，他们一度发现人偶的踪迹，但很快就跟丢了。

随后，他们掌握的情报指出人偶正在朝镇外移动，鲁迪乌斯从城墙上使用千里眼环视四周，确认到人偶正朝事务所的方向前进。

他们推测人偶的目的地是事务所后，决定先绕过去埋伏她。

正当他用千里眼观察人偶有可能过来的方向时，艾莉丝来到了这里。

「她看起来不像那么坏的家伙啊？」

「目前是这样。但如果不快点找到她，不知道会发生什么事......」

鲁迪乌斯以坚定的语气这样说道。

他确信这个人偶有着缺陷。

自动人偶的核心烙印着基本原则。那就是对人类的安全保障、服从命令以及自我防卫。

也就是所谓的机器人三原则。

但是，人偶居然无视命令逃跑了。

从这点可以说明，至少在「服从命令」这条项目已经出现了问题。

人偶目前只有和艾莉娜丽洁与艾莉丝对话过，似乎还没有造成实质伤害。

不过如果要借此认为「对人类的安全保障」这条原则有在运作，这种想法无疑过于乐观。

假设「对人类的安全保障」这条原则并没有确实运作，那么谁也无法预料人偶会因为何种契机而开始大开杀戒。

「艾莉丝，可以再详细地告诉我你们聊了些什么吗？」

「你问我聊什么，也没有，就只是普通的闲聊啊......我记得──」

艾莉丝回想她与人偶进行了什么样的对话，这样回答鲁迪乌斯。

然而，随着她叙述得越多，鲁迪乌斯的脸色也越来越僵硬。

自己与札诺巴的对话、人偶与艾莉娜丽洁，还有艾莉丝之间的对话。

他将这些情报综合起来后，脑海中浮现出有关人偶行动的一个假设。

根据艾莉娜丽洁的叙述，人偶在与她的对话中反复询问有关鲁迪乌斯妻子的问题。

昨晚，鲁迪乌斯曾说过妻子会生气，所以要把人偶报废。

而那具人偶听到了这句话。

目前看来，「服从命令的原则」并未发挥作用。

然而，如果认为「自我防卫的原则」正在运作，那么她会采取防卫行动也很正常。

从这个状况来看，所谓的防卫行动是什么？

那就是──排除那些试图排除自己存在的对象。

而打算排除自己的人就是......鲁迪乌斯的妻子。

尽管实际要下手报废她的是当时在睡的鲁迪乌斯与札诺巴，但他们却没有成为攻击对象，也许是因为他们在事前就被登录为「Master」。

虽然这行为显得矛盾，但如果系统出现了漏洞，也难怪她会做出前后矛盾的行动。

因此，人偶现在或许锁定了鲁迪乌斯的某个妻子，要将她找出来，打算将其杀害。

话虽如此，艾莉丝身为应该被排除的对象之一，人偶只是与她进行了对话。

那么，这个假设是错的吗？

不，并非如此。从人偶对艾莉丝提出的问题内容来看，感觉她似乎在仔细斟酌应该优先排除哪位妻子。

换句话说，她在判断谁对自己来说最具威胁。

她的计划恐怕是从最具威胁的对象开始逐一排除。

而在与艾莉丝的对话中，她明确掌握了那个最具威胁的人是谁。

「最后她说要去找希露菲问一下事情，然后就回镇上了。」

听到这句话，鲁迪乌斯的脸瞬间铁青。

「希露菲有危险！」

鲁迪乌斯急忙往家的方向跑去，但又立刻停下来，转身回到事务所前面。

然后，他在那深吸了一口气。

告诉自己要冷静下来，同时环视周围。

这里有鲁德佣兵团、札诺巴、茱丽、亚历、艾莉娜丽洁与克莱夫，还有自己的孩子们。

鲁迪乌斯首先找到在这群人当中看起来闲得发慌的亚历，朝他深深一鞠躬。

「亚历，孩子们和茱丽可以留在这里交给你照顾吗？」

「嗯，没问题。」

现在最重要的是确保孩子的安全。

如果奥尔斯帝德在场，他或许会拜托奥尔斯帝德，然后要亚历去做其他事情，但既然奥尔斯帝德不在，这也没有办法。

总之，如果能由亚历来保护，孩子们应该是安全的。

茱丽在工房睡觉时被人偶无视直接走过去，所以应该不要紧，但由于在事务所内的谈话中似乎提到她也表示反对，因此鲁迪乌斯选择让她留在这里待命。

「艾莉丝还有艾莉娜丽洁小姐，麻烦你们去学校那边看看。人偶说不定往洛琪希那里去了。我已经有派部分佣兵团过去学校，你们到时再和他们会合。」

「好吧。」

「知道了。」

鲁迪乌斯已经事先派莉妮亚率领一队过去学校搜索。

尽管艾莉丝说人偶是朝希露菲那边去的，但基本上也不知道她会做什么。

为了以防万一，还是派增援过去比较妥当。

「半数佣兵团先回爱夏那里，向她汇报目前的进展。顺便帮我通知她，万一有需要，也许会请求佩尔基乌斯大人协助。」

「收到！」

如果能借助佩尔基乌斯的力量，像阿尔曼菲想必能一瞬间就捉住人偶。

因为没想到事情会闹得这么大，所以没有事前跟家里联络，也比较慢通知各方，这点令鲁迪乌斯相当懊悔。

不过，佩尔基乌斯本来就不一定会帮忙。

「剩下的半数佣兵团成员就先回札诺巴的工房支援。」

「明白了。」

人偶虽然到处移动，但说不定这只是在诱敌，真正的目的是要逃离鲁迪乌斯。

既然是危险的存在，让她跑了或许也无所谓......但这是自己做出来的东西，必须负起责任处理到底。

「札诺巴，你跟我去家里，保护希露菲她们的安全。」

「了解。」

「好，那么，所有人开始行动！」

随着鲁迪乌斯一声令下，众人各自散开，分头行事。

\\

最后，事务所里只留下了孩子们、雷欧、茱丽。

以及亚历。

「来，在你们的爸爸回来之前，哥哥陪你们玩好吗？」

眼见因为父母突然离开而露出不安表情的孩子们，亚历露出和蔼可亲的表情安抚他们。

*** 「人偶行走之日　后篇」

这时，希露菲正在照顾四女克莉丝蒂娜。

「很好，克莉丝，就这样放开手，来妈妈这里。」

「嗯──！妈妈──你过来嘛......！」

与早早就开始蹒跚学步的莉莉不同，克莉丝目前还只是抓着东西走路的阶段。

因此，妈妈们最近总是像这样训练她。

不过，克莉丝似乎不太喜欢训练，正半哭着摇头拒绝。

「克莉丝要自己过来喔，好了，慢慢来。」

「嗯──！嗯──......妈妈......过来嘛......」

「不──行。来，在这里而已。」

克莉丝开始哭哭啼啼。

话虽如此，她并非做不到的孩子。

这只是在撒娇而已。

「嗯──嗯──......嗯！」

她最终还是闭上眼睛，踉踉跄跄地跑到希露菲的怀里。

「好乖好乖，你做得很好呢，克莉丝，很棒喔。」

「嗯......」

希露菲一如往常地抱起克莉丝，轻轻抚摸着她的头。

克莉丝虽然抽噎着，但紧紧地抱着希露菲不放。

与好奇心旺盛且活泼的莉莉相比，克莉丝显得胆小又爱撒娇。

更别提她还喜欢宅在家，不太喜欢外出。虽然偶尔被艾莉丝带出去，但每次都只会黏着艾莉丝不放，一旦有事就嚎啕大哭，导致常常提早回家。

因此，克莉丝也不会跟大家一起去散步，经常选择待在家里。

「真是的，克莉丝真的很爱撒娇呢。到底是像谁呢......」

希露菲嘴上这么说，但她毫无疑问是像鲁迪乌斯吧。

「妈妈......爸爸还没回来吗？」

「嗯，他应该还没有要回来喔。」

克莉丝是个典型的爸宝。

自出生以后她就老是哭闹，但只要被鲁迪乌斯抱着，立刻就会停止哭泣。

与亚尔斯完全相反。

最近，鲁迪乌斯的大腿逐渐成了克莉丝的专属座位。

「啊！」

「......嗯？」

就在这时，门口传来动静。

是不是有人回来了呢？

「是爸爸？」

「不晓得......但我觉得应该不是爸爸......」

鲁迪乌斯从昨天就出门了。

尽管她没询问鲁迪乌斯回来的正确时间，但他有说过预计会过两三天才回来。

那应该不可能是他。

「是姐姐？」

「如果是姐姐，就回来得有点太早了呢。」

然而，无论是去学校的洛琪希还是露西，还是去佣兵团的爱夏，都不可能这么早回来。

或许是去散步的艾莉丝她们？

不对，今天有好动爱玩的齐格一起，他们应该还会再晚一点。

那么，会是出去买东西的莉莉雅和帮忙她的亚尔斯吗？

不可能，他们两人才刚出门没多久，再怎么说也太快了。

虽说也有可能是忘了东西回来拿，但应该不是......

莫非是塞妮丝吗？

她应该在自己房间休息，但有可能不知何时去了庭院。

希露菲一边思考，一边将克莉丝轻轻放到软垫上。

「克莉丝，你先待在这里喔。」

希露菲抱着些许疑惑，走向玄关。

穿过客厅，来到走廊，耳边传来轻微的「嘎吱」声。

玄关门半开着。

不过，希露菲的目光并未停留在门上。

「......」

那个人站在门的内侧。

夕阳的余晖从半开的玄关门泄入屋内，将她的轮廓映照得逆光分明。

那是名黑发少女。若是熟悉她的人一看到，想必会喊出七星这个名字。

说不定，还会亲切地跟她打招呼。

但希露菲看到她的瞬间，却微皱眉头。

「......你不是七星吧？」

听到这句话，少女笑了。

她的嘴角微微上扬。

逆光在她的脸上形成一道黑影，让嘴角看起来裂成诡异的形状。

「是的。我不是七星。请问您是如何看出来的？」

「因为七星来过这个家很多次了，她开门时有个习惯。她会轻轻敲两下门，若没人回应，她会稍微犹豫一下，然后再轻轻推开门，低声说『不好意思打扰了』。」

希露菲在回答的同时，悄然把魔力灌注在右手。

眼前有个来历不明的存在化作熟人的模样侵入了这个家。对于决心要保护家庭的希露菲来说这是理所当然的行为。

目前，她从眼前的少女没有感觉到敌意。

语气虽然不带感情，但依然保持着礼貌。

然而，希露菲并没有天真到会乐观地认为对方是自己人。

「你是谁？假如你是人神的手下，那么就由我来对付你。」

她这样告诉对方，但同时也绞尽脑汁思考。

该如何瞒过眼前这名少女，将客厅里的克莉丝和二楼的塞妮丝安全带离这里？希露菲假定过敌人入侵这个家的可能性，尽管多次在脑海模拟过这样的情境，但自己是否真的能做到？

虽然没听到战斗的声音，但门柱上的比特是否已经被击倒了？

她刚刚将魔力注入戒指，向艾莉丝和洛琪希发出了讯号，她们是否能察觉到？

在事务所的奥尔斯帝德与亚历是否有掌握到这个状况？

应该选择逃跑，还是应该拖延时间？

希露菲心中充满各种想法，努力让自己面无表情，瞪视着眼前的少女。

「我还没有名字。」

「......？」

「可以请教您的名字吗？」

「希露菲叶特•格雷拉特。」

被突然询问后，希露菲下意识地回答。

「那么，您就是鲁迪乌斯大人的妻子，希露菲大人。」

「是啊......」

对方确认了自己的名字。

虽说反射性回答了，但希露菲现在觉得刚刚或许该保持沉默，依然全神贯注地注视着对方。

这个少女看起来手无寸铁，全身充满了破绽。

但依然不能大意。因为能够赤手空拳制伏自己的人比比皆是。

「希露菲大人，你会因为我的存在而对鲁迪乌斯大人生气吗？」

「......？」

「为什么希露菲大人无法接受我呢？」

「我不懂你的意思......你到底想表达什么？」

希露菲觉得自己被对方的话牵着走，不应该问她的。

说不定这样的询问是某种术式。

她瞬间想到这个可能性，抱着戒心往后退了一步。

「危险。」

瞬间，少女突然喊了一声并伸出了手。

她的速度远远凌驾于希露菲。

对方的动作明显比自己更快。但是，希露菲早就料到这点。

不至于让她完全看不见，也不足以让她无法应对。她准备在退后一步时稳住身子，迅速侧身化解对方的攻击，并以魔力直接反击。

希露菲瞬间做出了这样判断，正准备行动时......

「！」

她突然注意到克莉丝在自己脚下。

是何时出现的？

不知道什么时候，克莉丝已经爬到了玄关。

\\

克莉丝并没有听从要她「待在原地」的吩咐，阴差阳错地爬到了希露菲即将踩下去的位置。

当希露菲察觉时已经太迟了。

她为了避免踩到克莉丝，设法扭动身体，成功避开了。

然而，这个动作让她的重心失去平衡，身体摇摇晃晃，根本无法回避对方的攻击。

就在此时，希露菲的目光捕捉到少女以惊人速度伸向自己的手......

\\

★　★　★

\\

当鲁迪乌斯抵达家中时，整座房子静得令人毛骨悚然。

有比特缠绕着的门、爱夏的菜园、次郎的小屋、雷欧的狗屋。

每个地方都空无一人。

打开未上锁的玄关大门，便可看见干净整洁的走廊与半开的客厅门。

整个房子十分安静。

不，并非完全没有声音。屋内唯一响起的是哭声。

那是熟悉的声音，克莉丝的哭声。而且还是悲恸的哭声。

简直就像是失去了某种重要的东西，充满了深切悲伤的哭声。

对鲁迪乌斯来说，这是再熟悉不过的哭声。每当自己靠近，便会立刻停止的哭声。

明明听得到这个声音，但他却觉得屋内显得很安静。

「......佣兵团在外面待命。」

鲁迪乌斯在玄关这样下令后，尽可能不动声色地进入屋内。

房子里依旧寂静。眼前是那条整洁的走廊，他不经意地瞥向旁边，可以看到设置在玄关的镜子映着自己苍白的脸庞。

但是，为什么？

有股刺鼻的气味扑面而来，闻到这个味道绝对不会有舒服的感觉。要是长时间闻着，甚至会让人感到反胃。若是放任不管，肯定会招来成群的苍蝇。

鲁迪乌斯被这股气味引导着，沿着走廊前进。

他要前往的是客厅。哭声正是从那里传来，而他也确信气味的来源就在那里。

鲁迪乌斯走到紧闭的客厅门前，深吸一口气，鼓起勇气将门推开。

\\

呈现在眼前的，是难以置信的场景。

\\

首先映入眼帘的是桌子上方。

仰躺着的克莉丝正放声大哭。

而以半蹲姿势覆盖在克莉丝身上的，是一个黑发的人偶。

那人偶的手上沾满污垢。

像是干涸的血迹般呈现褐色。

那褐色的污迹依然带着湿润感，散发出浓烈的气味，刺鼻得令人作呕。

这个味道该不会是......

「啊──真是的，大便都沾到手了。」

「没有问题。这种程度的脏污并不影响行动。」

「不行！要好好擦干净，来。还有，弄脏的尿布要像这样卷起来，放进这个篮子，等下要拿去洗。」

「所以，一有脏污就要迅速清洁。我学到了。」

于是，希露菲开始帮忙擦拭人偶手上的污渍。

人偶手上沾着的东西，还有散布在整个走廊的气味来源，正是克莉丝的大便。

她被放在桌上仰躺着，脏掉的尿布被脱了下来，哭得声嘶力竭。

「爸爸！是爸爸！」

然而，当她看到鲁迪乌斯的身影时，立刻停止哭泣，露出如花般灿烂的笑容。

「......咦？」

鲁迪乌斯原本已经做好一定程度的心理准备。

脑中浮现的是奋战中的希露菲、满身伤痕的家人......甚至是倒下后不再动弹的家人。

完全没想到出现在眼前的，竟是人偶笨拙地替克莉丝换尿布的画面。

「啊，欢迎回来，鲁迪。」

「希露菲......你没受伤......好像没有吧......？」

「嗯，当然没有啦。」

希露菲点头，人偶就站在她背后。

那人偶面无表情。她以毫无生气的脸伫立在眼前，仿佛随时会从希露菲胸口冒出短剑般令人不安。

然而，当人偶察觉到鲁迪乌斯的视线后，她微微地缩回身体，躲在希露菲身后。

仿佛是在把希露菲当作盾牌一样。

在鲁迪乌斯眼里，这举动显得有些奇妙。

看起来简直就像人偶在害怕他。

「希露菲，你能先离开那家伙吗？」

「......为什么？」

然后，希露菲也像是有意护着人偶那样，站到她的身旁。

「那个人偶，是我和札诺巴一起制作的，但她现在失控了。我猜，她可能听到了我们的对话，打算取代希露菲或是将你排除掉。」

鲁迪如此说明，但内心却觉得有点不太对劲。

「不过，情况跟我想的好像不太一样。」

话虽如此，目前依然不了解人偶有什么意图。

鲁迪乌斯没有解除警戒，瞪视着人偶。

「哦，跟我听到的情况不太一样呢。」

「你听到的？」

见鲁迪乌斯困惑地歪了歪头，希露菲莞尔一笑。

「嗯。我想聊聊这件事，先坐下来吧。」

「好......」

鲁迪乌斯依言在地板上盘腿坐下。

看到这样的姿势，希露菲疑惑地歪了歪头。

「咦？鲁迪，应该不是这样坐吧？」

「咦！啊，好。」

鲁迪乌斯从希露菲的语气感觉到某种情绪，连忙改变坐姿。

在希露菲的语气中蕴含的情绪，正是愤怒。既然这样，鲁迪乌斯也只能跪坐了。

「好，来吧。」

希露菲确认他坐好后，自己往后退，将人偶往前推。

人偶被推到鲁迪乌斯前面，用没有感情的表情低头看着他。

「Master鲁迪乌斯，您打算将我报废吗？」

「嗯，我会这么做。」

眼见鲁迪乌斯毫不犹豫地回答，人偶却一动也不动。

然而，鲁迪很清楚。

这具躯体由与魔导铠相同材质的骨架及特制人工肌肉所组成，其性能堪比圣级剑士。

既然如此危险的人造物不听从命令，唯一的选择就是毁掉她。

此刻的鲁迪乌斯身穿魔导铠，开启了魔眼，绝对不会落于下风。

话虽如此，还不能掉以轻心。

「............我......不想被报废。」

就在这时，鲁迪察觉到了一件事。

「......」

人偶正在害怕。

她表面上只是站在那里。

脸上面无表情，语气也很平淡，但可以知道她正感到害怕。

人偶将视线转向希露菲。

尽管她的眼神冷漠，但希露菲不知为何感觉那是在求救的眼神。

「鲁迪好像还不太明白状况，所以你就从头开始告诉他吧。」

希露菲这样提议后，人偶看了一眼鲁迪乌斯，以及不知不觉间走进屋内的札诺巴。

随后，她以平静的语气开口说道：

「鲁迪乌斯大人和札诺巴大人曾说过，我的存在会惹鲁迪乌斯大人的夫人生气。艾莉娜丽洁大人说过，鲁迪乌斯大人的夫人是希露菲大人、艾莉丝大人和洛琪希大人。艾莉丝大人提到，希露菲大人以前曾说过她无法接受七星......艾莉娜丽洁大人将我称为七星。我因此推测，我是因为与七星大人过于酷似，所以才会被报废。然而，我并非七星大人。因此，我认为应该还有其他方法。」

尽管语气一如既往地平淡，但言语中流露出一丝迫切。

因为人偶在拼命寻求某个方法。

「我不想被报废。鲁迪乌斯大人与札诺巴大人为我的诞生而感到喜悦。我希望能为两位做更多事。假如遭到报废，这一切将无法实现。」

召唤魔术有时会因为其力量过于强大，而给术者带来灾祸。

然而，被召唤出的魔兽基本上无法违背术者，对主人是忠贞不二。灾祸的发生，往往是它们为了术者的利益而行动的结果。

而这个人偶，同样被嵌入了类似的术式。

毕竟她是以佩尔基乌斯的召唤魔术为基础所制作的，自然不会缺少这样的术式。

她与佩尔基乌斯的十二精灵同样会思考、会自己行动。

没错，佩尔基乌斯的精灵拥有自我意识。自被召唤的那个瞬间开始，便会以自我的意志行动。

为了主人，为了活得更久，为了成为更有用的存在。

「因此，我基于现有的情报，判断希露菲大人最有可能忌讳我的存在，所以决定向她请教。」

其实，她的机器人三原则并未损坏。

只是身为召唤精灵的天性比原则更为优先。

「如何才能让您接受我的存在呢？」

人偶突然现身，擅自闯入家里。

希露菲见状，自然会比以往来得更为警戒。

但是，人偶打从一开始就没有任何敌意。

就算面对满是敌意的希露菲，她仍露出拙劣的笑容，渴望对话。

当希露菲差点踩到女儿，因而失去平衡时，人偶及时扶住她，贴心地询问她是否有受伤。

当克莉丝因差点被踩到而吓得漏屎漏尿时，她也立刻关心，并主动提出帮忙更换尿布。

她对希露菲这样说道：

我不想死，如果有缺陷，我会改正。我希望能对各位有所帮助，请不要杀了我，求求您。

她真挚的话语深深打动了希露菲。

「鲁迪，我不会生气的。毕竟我知道你在制作这类人偶，虽然没想到她这么有人性啦......不过，她是个好孩子。就算有些缺陷，我也希望你能善用她。」

希露菲说出这番话后，人偶的解释到此告一段落。

接下来，就等鲁迪乌斯如何回应了。

不知不觉间，鲁迪乌斯默默地将嘴唇抿成一条线，双手环胸低下头。

他的肩膀微微颤抖着。

「呜呜......」

仔细一看，站在后方的札诺巴也开始颤抖着身体。

就在希露菲感到疑惑的瞬间──

「唔喔喔喔喔喔！」

札诺巴大叫一声，冲向人偶。

「原来你是这样想的！一切竟然都是为了我们！抱歉！本人居然误解你，说你失控了！真的很抱歉！」

他涕泪滂沱，同时紧紧抱住人偶。

鲁迪乌斯见状，也忍不住鼻头一酸。

他的眼眶也同样有泪水在打转。

鲁迪乌斯从怀中取出手帕，大声地擤了擤鼻子后站起来，握住了人偶的手。

「札诺巴说得对。如果有人当着你的面说要报废你，谁不会想逃呢？肯定会设法改变现状吧......我明白了。就算希露菲生气也没关系，我和札诺巴会把你彻底完成，并好好善用你的。」

「那么，本人也愿意承受茱丽的怒火！」

两人紧紧抓住人偶，泪流满面地哭了起来。

在希露菲眼中，人偶看起来像是一脸茫然。

那表情像是在说，问题明明还没解决，却意外得到了原谅。

不管怎么样，事情总算告一段落。希露菲内心满怀欣慰，松了一口气，并抚摸着因得不到鲁迪乌斯关注而开始闹脾气的克莉丝。

这时，她突然想起一个问题。

「鲁迪，我最后还有一个问题，就目前为止的情况，你为什么觉得我会生气？」

鲁迪乌斯听到这句话，猛然一颤。

他转过身子，正襟危坐。

然后清了清嗓子，开始说明。

「其实这个人偶......那方面也做得很精细──」

希露菲生气了。

\\

★　★　★

\\

最终，这起事件的结果是报废人偶的计划取消，决定尽可能保留他们制造的自动人偶。

因此这起事件的核心人物被列入正式编号。

她成为了自动人偶的第一号机。

今后，她将在研究所与魔法都市夏利亚参与各种实验，也会被鲁迪乌斯用于各种计划。

\\

还有，七星后来也得知了人偶的秘密。

当她发现这个以自己外貌为基础的人偶竟然具备性行为的功能时，露出了明显厌恶的表情。

不过，由于鲁迪乌斯低声下气地解释，加上他说自己向希露菲保证不会基于这样的用途使用，才勉强平息了她的不满。

「算了，那么这孩子的名字是什么？」

「名字......还没取。」

「这样啊，那可以让我来取吗？」

在七星的命名下，自动人偶第一号机被取名为「安」。

此外，假如后世出现了七星的熟人，为了让对方可以借由带有日式风格的名字得知七星的存在，她还给安取了一个别名──「七星一」。

如果她将来遇到七星的熟人，对方询问她的名字时就这样自我介绍，想必就能说明她与七星之间的关联。

正式名称为「自动人偶 SS──01 安」。

尽管不晓得二号机是否会被命名为「杜」，三号机是否会被命名为「特洛瓦」，但就那样吧。[fn:2]

顺带一提，SS是「Seven Star七星」的缩写。

就这样，「七星系列」纪念性的第一作「安」诞生了。

她的兄弟姐妹将在漫长的岁月中慢慢增加。

然而需要特别注明的是，拥有乳头设计的只有她一个。

*** 「在事务所的一天」

我从睡梦中醒来。

这是个令人愉悦的早晨。

从前，这个瞬间令我最为恐惧。

因为若是在睡梦中被杀，那么醒来的地方便不会是温暖的床，而是阴暗的森林深处。

直到找到真正安全的住所前，我始终害怕入眠。相对地，我也曾因为不眠导致注意力涣散而丧命。自从学会在睡觉的同时警戒着周围的技巧后，这种情况才稍有改善......

但是，当时的我无论如何也无法想像，自己能够在这样的地方清醒。

「......」

我调整着呼吸后，朝事务所的书房走去。

书房里堆满了这次轮回与过往不同之处的相关文件。

这些内容分为两部分，「基础」与「差异」。

「基础」记录了若我什么都不做时历史应有的发展，而「差异」则记载了因我行动所引发的变化与后果。

撰写这些文件的目的，就是为了打倒人神。

为了这个目的，必须尽可能减少消耗，抵达他的面前。

其中最为关键的，就是八十年后的第二次拉普拉斯战役。

如何在此战中减少消耗，会直接关系到能否彻底打倒人神。

因此，要运用「基础」与「差异」改变历史，用最低限度的消耗克服这个问题。

当然，这些文件无法带到下一个轮回，所以必须在轮回前整理行动，重看好几遍直到记住为止。

然而，这次与以往有所不同。

因为鲁迪乌斯•格雷拉特。每当他行动或与他人接触时，世界便会自行改变。起初，我也只是想记下差异点，但曾几何时这些文件已变成他的观察日记。

几乎所有页面上都写着鲁迪乌斯的名字，而且数量庞大到无法完全记录。

尽管我打算持续记录到这次轮回结束，但最终恐怕会遗漏不少情报。

坦白说，这样的行为可能没有太大意义。

这次的轮回，总觉得有些不对劲。感觉有什么特别的事情正在发生。

而下一次轮回，鲁迪乌斯还会出现的可能性很低，即使记录这么多也有可能会徒劳无功。

恐怕，我非得在这次战胜人神不可。

命运就是那样注定吧。

我必须趁现在积蓄战力，为即将到来的时刻做好准备，保留魔力，在尽可能不耗费魔力的情况下解决拉普拉斯，然后在与人神的最终决战中全力以赴。

我是这么打算的。

但是，这并不能成为停止记录的理由。万一这次失败，而下一次轮回中依然有鲁迪乌斯的存在，这些情报或许将成为确实迈向胜利的武器。

话虽如此，这些东西不能让鲁迪乌斯看到。以他的个性，一旦看到这些纪录，也许又会产生什么奇怪的误解。

「......」

我抱着这样的想法，今天也继续记录新的情报。

首先，是夜里从通讯石板收到的情报。归功于这个通讯石板，搜集情报变得方便许多。若是在过往的轮回，每次出现变化我都必须亲自前往现场搜集情报才能得知结果。

虽说已经习惯了，但对带着诅咒的我来说，这件事相当棘手。

如今我只需坐在这里，便能掌握足够的情报。

回想起来，以前为了弄清一个变化的结果，有时需要多次轮回才能确认，与现在相比实在是天壤之别。

不过，若不是因为鲁迪乌斯的存在，或许也不需要如此庞大的情报网。

我一个人的话，状况不会有这么大的差异。他带来的变化之多，甚至让我对下一步的行动方向感到迷茫。

鲁迪乌斯制作的自动人偶也是一个令人头疼的存在。

我也亲眼见过那个被命名为「安」的自动人偶，实在无法想像那是经由人类之手制作出来的。

佩尔基乌斯也感到很惊讶，她的形体竟然比自己的精灵更接近人类。

或许，那正是狂龙王卡奥斯梦寐以求的存在。

卡奥斯虽然已经身亡，不在这个世上，但如果他依然在世，或许会与鲁迪乌斯他们一起制作这样的人偶吧......如果还有下一次轮回，或许可以延后回收卡奥斯秘宝的时间。

「嗯。」

当我正这样思考，同时看着通讯石板时，一条有趣的情报映入眼帘。

是来自爱丽儿的情报。

伊佐露缇和杜加似乎结婚了。据我所知，他们两人从未成为夫妻。

基本上，伊佐露缇结婚的可能性本来就微乎其微，更遑论生儿育女。

这八成也是鲁迪乌斯的影响吧。

在目前这个阶段，我完全不晓得该怎么做才能重现这样的结果......

不过是否要重现，可以等到观察这对夫妻的孩子将成为怎样的人，又会扮演什么角色后再做决定。

在某些情况下，说不定我会在下次轮回阻止他们的孩子出生......

这样的话，鲁迪乌斯恐怕会表示反对吧。

「......」

我已经不想再对鲁迪乌斯说谎，或是有所隐瞒。

即使到了下次轮回他就会遗忘一切，我的想法也不会改变。

\\

★　★　★

\\

「早安！」

我整理文件过了一会儿时，鲁迪乌斯现身了。

「......嗯。」

「今天也在写东西吗！哎呀～奥尔斯帝德大人真是勤劳呢！」

「我一向如此。」

「能每天持之以恒的这种态度才是关键！人生很漫长，持续一点一滴地努力才是正道！不愧是奥尔斯帝德大人，果然深谙此道！」

鲁迪乌斯有时会像这样异常亢奋。

平常他表现得要更为沉稳一些，但他的这种态度是有迹可循的。

他像这样情绪高涨时，多半是遇上了什么好事。

相反，要是他显得战战兢兢，一脸歉疚时，多半是有什么难言之隐。

真是好懂。

「今天怎么了？」

「不愧是社长！瞒不过您的法眼！咕呵......呃，其实是这样的，今天早上菈菈突然对我说，她今天想要和爸爸整天待在一起！咕呵。虽然克莉丝一向很亲近我，但我没想到菈菈会这么说，害我忍不住有些飘飘然了呢，咕呵──」

「你带她来了？」

「是。菈菈和齐格都坐在雷欧的背上一起来了。」

连齐格也一起来了？这有点出乎意料。

或许是我的想法表现在脸上，鲁迪的脸色立刻一变。

「啊，关于齐格！他说自己是亚历的粉丝。好像是上次听亚历讲了毕黑利尔王国的故事后，他觉得特别有趣。这次说如果能见到北神大人，就想再听一次故事。所以现在亚历正在陪他。」

「这样啊。」

「那个......把孩子带来职场，还是有点不妥吗......」

「不，无所谓。」

鲁迪乌斯最大的弱点就是家人。

这家伙重视家人，为了家人而活。

他为了家人可以不顾一切，一旦家人受到威胁，他就会与之敌对。

他总是一次又一次地不顾后果地发动攻击，一旦快要输了，即使对方是人神也会毫不犹豫地背叛，连自尊心都可以抛到九霄云外，低头求饶。

这种人，在我所知的范围内并非少数。

要让鲁迪乌斯保持作为盟友的立场，就必须对他的家人多加关注。

至少，绝不能对他们冷眼相待。

关爱他的家人，尽可能保护他们的安全。只要我能持续守护鲁迪乌斯最重视的事物，他就不会背叛。这点是人神无法做到的。

当然，撇开这些算计不谈，鲁迪乌斯的孩子似乎对我的诅咒免疫，而且我也不讨厌他们。这种热闹的气氛其实也不坏。

这种感觉，就仿佛自己也变成了一个普通人一样。

「你的孩子很可爱。」

我努力挤出一抹笑容，试图夸赞他的孩子。

然而，鲁迪乌斯的表情却变得严肃起来。不妙，他这副表情通常不代表好事。

当鲁迪警戒时，就是这样的表情。

我必须小心为上。这个男人总是会一脸镇定地开始做些意想不到的事情。虽说应该不至于，但他也有可能趁我睡觉时突然将我活埋。

现在这个瞬间，要解决他是轻而易举，但若是让他先发制人......

「就算是奥尔斯帝德大人，我也不会把女儿交给你喔。」

「......不是那个意思。」

我这么说后，鲁迪乌斯的表情恢复了正常。

「待会儿我再带两个孩子过来打声招呼。」

「无妨，不用这么拘谨。」

「是吗......毕竟菈菈这孩子有些调皮，这样或许也好。」

鲁迪乌斯这样说完，坐到沙发上。

「那么，今天我们也努力工作吧！今天要做什么？是用魔导铠『一式』进行模拟战？还是调整防止诅咒的头盔？或者是报告『三式』的开发进度，也可以调整『零式』呢。再不然，重新讨论接下来的行动计划也行......」

鲁迪乌斯提到的每一项都是由他主导进行的工作。

看来是想在女儿与儿子面前好好表现吧。

但是，刚才整理文件时，我想起了一件事。

虽然是件小事，但如果未来与拉普拉斯开战，最好趁现在先处理一下。

「嗯，关于这件事......」

今年，中央大陆南部的一个国家将持续面临干旱，导致饥荒发生。

有许多家庭会活活饿死。不过，这件事本身无所谓，是自然的道理。

但问题在于，其中包含了某家人。

这家人并不特别，唯独最小的儿子不一般。他长大后会成为一位出色的指挥官。在第二次拉普拉斯战役当中，他将负责指挥东部港防御战。他会在这时展现出卓越的指挥能力，让王龙王国军成功坚持了很长时间。

通常，我会选择不引发与拉普拉斯的战争，也会因考虑魔力消耗而放任不管。

然而，这次会与拉普拉斯开战，鲁迪乌斯也在。

因此，趁现在出发帮助这家人比较妥当。

「就是这样。」

听完我的说明，鲁迪乌斯露出了失望的神情。

「出差的话，就没办法让菈菈看到我工作的样子了......」

「如果需要，可以明天再出发。」

眼看他如此落寞，我便这样提议。鲁迪乌斯却摇了摇头。

「不，既然不记得这家人饿死的正确日子，还是早点行动为上。虽然应该不会来不及，但人类是很脆弱的，什么时候死都不足为奇。我已经准备好随时都能在这种时候出发旅行，应该立刻动身。」

反而是我被说服了。

「......如果你没问题的话就好。」

「是。那么，我马上去准备。」

鲁迪乌斯迅速起身离开房间，前往事务所的仓库取早已备妥的装备。

他回来的时间大约是在十五分钟后。

鲁迪乌斯背着背包，带上食物，以及卷轴推进器这类旅途用的装备。

他走向我，指尖并拢摆在额头敬了一个礼。

「那么，可能要劳烦您在有空的时候送菈菈和齐格回家。虽然有雷欧在应该没问题，但要是发生什么万一就太迟了。」

其实这件事不用他提醒。

我当然不会忽视鲁迪乌斯愿意待在我身边的理由。

「嗯。」

「那么，我出发了。」

鲁迪乌斯说完最后一句话后，迅速奔向位于地下的转移魔法阵。

这几年来，他在这种情况下的判断和行动速度都有了显着提升，而且几乎总是能确实完成任务。

在过去的轮回中，我也曾视某些人为棋子使用过。

也曾经......有过能称为部下的人跟在身边。

然而，从未有过像鲁迪乌斯这样灵活又能干的人物愿意如此老实地听从我的指示。现在我能稍微体会人神操控使徒时是什么样的心情了。

「......」

我察觉到自己不自觉地皱起了眉头。

鲁迪乌斯确实是个值得信赖的男人，但也不能过于依赖他。

至少，不该抱着像人神操控使徒那样的心态对待他。

话虽如此，以目前的情况，我能做的事情也不多。在这次轮回当中，我已经消耗了太多魔力。虽然决定与鲁迪乌斯并肩作战，但这并不构成我滥用魔力的理由。

「......」

总之我戴上了防止诅咒的头盔，走出了书房。

穿过接待处时，法莉亚斯缇雅看到我，身子猛然一颤。

「啊！社长！」

看来她是被我吓到了。

不过，幸好有这顶头盔，最多也就是被吓到的程度。如果没有它，情况势必会糟糕许多。这头盔的制作方法我已经整理在文件了。虽然很难改良，但至少有办法重现。下次轮回时再制作一顶吧。

「刚才鲁迪乌斯大人外出了，奥尔斯帝德大人也要出发吗？需要人随行吗？」

「不需要，我只是稍微外出，很快就会回来。」

「明白了。」

一踏出室外，侧面便传来一阵声音。

「就在那时！咻一声！狂剑王艾莉丝的剑抓住一瞬的破绽，斩下三世的手臂！」

那戏剧化的声调是从事务所后方的日阴处传来。

「三世失去单臂，这时挡在他面前的，是北神卡尔曼二世与魔王阿托菲拉托菲！背后则是狂剑王艾莉丝与魔导王鲁迪乌斯！不论前后尽是些不听人说话的家伙！多说无益！这场对决胜负已定！三世，觉悟吧！就在所有人都这么认为的瞬间──喝！三世逃入了地龙谷！」

阴影处，有一名男子坐在石头上。

另外，还有一名幼小的男孩直接坐在地上。

坐在石头上的是北神卡尔曼三世，亚历山大•雷白克。

另一名幼小的男孩，则是齐格哈尔德•萨拉丁•格雷拉特。

与之前见到他时相比明显长大了许多。岁月的流逝果然飞快。

「三世逃走了。他判断只要能在这里顺利逃过一劫，最终还会有翻盘的机会，于是逃入了地龙谷！实际上，当时在场没有任何人能追进那片深谷。只有满身伤痕的父亲亚历克斯，还有魔王阿托菲！」

「那两个人不是人类吗？」

「没错，这两个人并非人类！他们是继承不死魔族血脉的强者！而三世判断自己若是面对这两人的话，勉强还能逃脱！但是！砰！突然传来一声巨响，庞然大物飞扑而至！是谁跳进了谷中？是二世？是魔王？还是狂剑王？不！是鲁迪乌斯•格雷拉特！」

「是爸爸！」

齐格入迷地听着亚历说故事，但菈菈在哪？

我这样心想，试着感应周围的气息，发现在事务所庭院的稻草堆上有个气息。

转头望去，便看到稻草堆的顶端躺着一个蓝发少女，正舒服地睡着午觉。

在稻草堆的底下，白色的巨兽正抬头看着上方，来回踱步。

那是菈菈•格雷拉特与圣兽雷欧。

虽然菈菈被圣兽承认为救世主，但这个孩子的行动丝毫无法预测。不过，她之前还说想与鲁迪乌斯在一起，现在竟然已经睡着了。自从在事务所入口与鲁迪乌斯暂时分开后，明明还没经过一个小时......

这么说来，我听说菈菈喜欢恶作剧。

说不定菈菈做了什么恶作剧后害怕被骂，才会利用自己的父亲来躲避麻烦吧。

假如真是这样，鲁迪乌斯还真是可怜，刚刚还得意成那样......

「他启动已经破烂不堪的魔导铠，孤身一人追击我！只有他一人！然后，他在空中抓住了无法动弹的三世！轰隆！轰隆！用魔导铠的巨躯一拳接着一拳，不停地猛击！轰嘎啊啊啊啊！三世与鲁迪乌斯一起坠入地龙谷！从沙尘中站起来的，是失去了一只手臂和一只脚的三世！以及穿着满是裂痕的魔导铠的鲁迪乌斯！没有人再追上来。一对一的决斗！」

「一对一！」

看来，亚历目前正在向齐格讲述毕黑利尔王国战役的情况。

菈菈把他带到这里后，自己早早就睡着了，所以现在是由亚历在陪伴齐格。

「不过，鲁迪乌斯并没有足以战胜三世的力量。尽管他用奇袭成功击中三世，却无法一举定胜负，而这正是他的败因！三世这样认为，并开始小心翼翼地观察鲁迪。他大意了，觉得鲁迪乌斯身为魔术师，一旦战斗开始肯定会拉开距离，使出他擅长的岩砲弹。面对这种只会逃避的对手，自己是绝不可能输的！然而，鲁迪乌斯正是利用了这一点！他一边奔跑，一边发射岩砲弹！即使轻视对手，三世仍是身经百战的强者！为了闪避岩砲弹，他瞬间往后退了一步。但是，岩砲弹却在他眼前消失了！是虚招！」

「虚招！」

「咻磅──！就在三世注意到时，斩击已经挥下！砍得太浅了！因为刚才的虚招，因为向后退了一步，没有给鲁迪乌斯致命的一击！但即使如此，他还有机会！三世试图往后跳......这时他发现脚浮了起来。没错，是鲁迪乌斯所为！他在最后关头亮出了自己的王牌！重力控制！他用了能与王龙剑卡夏库特比肩的魔术，让三世微微地浮空！砰！当三世意识到时，自己已经被打中了！咚嘎嘎嘎嘎嘎嘎！猛攻！猛攻！猛攻！不停地猛攻！鲁迪乌斯最强的魔道具将三世轰成了碎片！喀啦啦啦！三世失去了意识......再也站不起来。当啷......！他手中的王龙剑掉落在地。鲁迪乌斯胜利了！」

「赢了！」

齐格发出欢呼。

亚历满足地描述着自己的败北。

看到这样的光景，我感到一丝温馨，不禁走近亚历。

「亚历山大•雷白克。」

「哦，这不是奥尔斯帝德大人吗！您要外出吗？」

「不，刚才鲁迪乌斯已经出发了。」

「是的。他拜托我照顾孩子们，到了适当的时候再送他们回家，并向他的妻子说明情况。」

原来如此，鲁迪乌斯甚至将这件事也交代给亚历了。

那么，我就不用自己送他们了......是吗？

「既然你已经听说了就好，交给你了。」

「是！」

我听到他的回应后点了点头，返回书房。

\\

★　★　★

\\

傍晚，我的记录告一段落后，再次离开书房。

亚历似乎还没有送两人回去，天色已经逐渐暗了，还是早点让他们回去比较妥当。

法莉亚斯缇雅的上班时间似乎已结束，接待处空无一人。

「你爸爸平时的态度就像个没用的懦夫。实际上，他的本性确实有些胆小。不过要是惹怒了他，他会比任何人都要可怕。」

回来后，发现他们还在继续谈话。

只是，此刻亚历的语气已经不像在叙述，更像是在教导、启发。

齐格也一脸认真地听着。

「我曾被他的气势压倒，最后落败。听说奥尔斯帝德大人也有过类似的经历。当然，那位大人并没有像我这样被压制，但他认同了你爸爸的那股气势，才会将他纳入自己的麾下。不过，你知道为什么我和奥尔斯帝德大人会对你爸爸另眼相看吗？」

「不知道？」

「那是因为啊，他很强。」

「爸爸很强吗？可是爸爸常输给红妈妈耶？」

「没错。嗯。但这和普通的强大不太一样。」

我也很好奇亚历是如何看待鲁迪乌斯。

「你爸爸唯一的优势是魔力。因为他天生就无法在身上缠绕斗气。

状况判断能力绝不算高，遇到突发状况就容易惊慌失措。

视力也不好。即使拥有魔眼，也只能勉强达到比我和奥尔斯帝德大人低一阶的水准。

他的身体反应也很慢。哪怕魔眼能提前预见未来，他的身体也跟不上魔眼看到的动作。

会对杀人犹豫不决，若是面对活生生的对手，他总是难以狠下心下杀手。

能够使用无咏唱魔术是他的强项，他释放魔术的速度在魔术师中也算是出类拔萃。但即使如此，他的速度也远远追不上我们这些剑士。

我可以在他准备一发足以杀死我的『岩砲弹』之前杀他三次。

总而言之，只要我们认真起来，可以彻底『封杀』他。

无论他拥有多么千变万化的战术，也毫无任何意义。

而且，我并不是世界上最快的人。单纯只论速度的话，我比速度顶尖的高手还要慢一两个层次。

当然，若是拉开距离，他可以尽情使用魔术攻击，但这种情况并不多见。

也就是说，就总体来看，他其实不太适合战斗。」

「爸爸......很弱吗......？」

齐格露出悲伤的表情。

眼前有人如此批评自己的父亲，想必不太可能会有孩子不感到难过。

尤其鲁迪乌斯又一心一意地爱护着自己的孩子。

「啊，不要露出那种表情，话还没说完呢。你要知道，你爸爸真正厉害的地方，是他非常清楚自己的弱点。所以，他会想办法消除自己的弱点、发挥长处。」

「想办法？」

「嗯，那就是能将他的速度提升数倍的魔导铠。靠着这个，你爸爸即使被我们先发制人，也有办法存活下来。也就是说，他不会遭到我们『封杀』。当然，这不代表平分秋色，他依然没有占到优势。不过，他能够晋升到我们这个水准。一个无法缠绕斗气、唯一优势是魔力量庞大的魔术师，竟能做到这一点。而且，他并没有选择逃避，而是正面与我们应战。有时会堂堂正正，有时卑鄙地从背后偷袭，有时借助同伴的力量，有时甚至独自一人战斗。你知道为什么他明明屈于劣势却选择挺身而出吗？」

齐格摇了摇头。

「是为了保护你们。他为了守护自己所爱的家人，甚至不惜牺牲自己的性命。」

亚历这样说完，齐格的眼神闪闪发亮。

他兴奋地握紧拳头，抬头仰望亚历，脸上喜形于色。

「爸爸果然是切达人！」

「没错，他是切达人，是真正的英雄！」

突然出现了陌生的词汇。

切达人？这到底是什么暗喻？还是某个人物？在这几千年来从未听说过这样的存在。

那么，说不定是鲁迪乌斯新创的词汇。

那个男人总是有事没事就创造新的语汇。

下次再直接问问他吧。

我这样想着，在脑海的记事本追加了「切达人」这个项目。

「那个，北神大人！我也想成为切达人！」

「可以的，真正的英雄是靠努力而成。我那伟大的父亲是个真正的英雄，他就是这么说的。你爸爸没这么说过吗？」

「爸爸没说过。」

「是吗？不过，等你再长大一点，爸爸就会这么告诉你了。」

「要怎么努力？」

「就是变强。」

「怎么变强？」

「锻炼身体，学习剑术与魔术。」

亚历极其冷静地教导齐格，对他晓以大义。

然而就在此时，齐格像是下定决心那般，抬头看着亚历，这样说道：

「我明白了，那么北神大人！请教我剑术吧！」

「咦？我吗？」

「不行吗？」

「剑术的话，你妈妈应该正在教你剑神流吧？」

「我想要北神大人教我！我想让爸爸和妈妈大吃一惊！」

「可是，我......虽然我自认剑术还算不错，但弟子们几乎都更想去接受父亲的指导，这证明我不太会教人，应该不适合当老师喔。」

北神卡尔曼三世亚历山大•雷白克年轻时的记忆充满苦涩。

他成为北神时，曾有二十多名弟子向他师事。然而，短短几年内，那些弟子便离开了他，选择了其他道路。

在那以后，亚历再也没有收过任何一名弟子。

「可是，北神大人战斗时的样子很帅啊。要学的话，我想学北神流！」

「但我还不够成熟，要收弟子实在是......」

看着一脸烦恼的亚历，我的脑海不禁浮现了鲁迪乌斯的身影。虽然称自己并不成熟，却教会了许多人许多事情。而且那些受到教导的人，无一不心怀感激。

而我也是其中之一。

「亚历山大•雷白克，你就教他吧。」

我这样说完，亚历惊讶地抬起头。

那个反应仿佛是完全没察觉到我的接近。

不过，这是不可能的。

「奥尔斯帝德大人......可是，我作为北神还不够成熟......」

「正因如此，你就试着去锻炼那孩子吧。只专注于那一个孩子，只培养那一个孩子，真正明白北神流的精髓，也借此看清自身的不足之处。」

依原本的历史，北神卡尔曼三世亚历山大•雷白克是在败给剑神吉诺•布里兹后才改头换面。

后来，他在失意中将一名小孩收为弟子。那个孩子并非天赋异禀，但亚历透过观察弟子，重新审视自我，慢慢成长为真正的北神。

在第二次拉普拉斯战役中，北神卡尔曼三世被誉为历代最强的北神。

尽管不晓得在这次的轮回那个孩子会有什么未来，但亚历已经历过败北，并且有所改变。

既然这样，提前教导他人也未尝不可。

更何况，齐格似乎有剑术的才能。或许是因为拉普拉斯的因子，他比一般孩子更有力气。尽管不及神子札诺巴，但未来的他很可能轻松以单手挥动双手剑。

若是与普通人类不同，那么他的归宿多半就是北神流。

也让他趁现在开始学比较妥当。

再者，亚历似乎还有一件事没有理解。

鲁迪乌斯的优势不仅是在于魔力。

鲁迪乌斯拥有会在紧急时刻赶到他身边的伙伴。

这些伙伴是在战斗以外的情况下建立关系的。

对于一向以一对一决胜负的亚历来说，或许难以理解这种状况......但透过与鲁迪乌斯的孩子接触，他说不定也能逐渐明白。

而一旦理解，也许他会成为比原本历史中更加高洁、更加强大的北神。

「鲁迪乌斯那边，由我向他说明。」

「......既然奥尔斯帝德大人都这么说了，那我明白了。」

亚历露出了笑容，转头看向齐格。

「好吧，齐格，我从明天就开始锻炼你。不过，如果你想让爸爸和妈妈惊讶，这件事就要对大家保密，知道吗？」

「嗯！」

齐格用闪闪发亮的眼神仰望着亚历。

亚历似乎对久违的这名小弟子感到些许困惑，但同时又因为久违地要认真指导某人剑术而充满干劲。他们一定会成为一对好师徒。

然而......

「......亚历山大•雷白克，我能问你一件事吗？」

「是！」

「你背上的那些东西是什么？」

亚历的背上黏满了大量的苍耳子。就是人族的孩子们经常用来丢着玩黏在衣服上的那个。在孩子间也将其称为「黏黏虫」。

「啊，这是菈菈小姐的杰作。她可能是觉得无聊，就从后面偷偷靠近，把这些黏在我身上。」

「......」

「只是孩子的恶作剧罢了。我待会儿就清掉。」

原来菈菈这么淘气，是吗？原来如此，可以理解。

「菈菈现在在哪？」

「刚刚好像进了事务所......？」

一瞬间，我还以为她是不是去了地下，跳上了转移魔法阵。

不过，我感知了一下气息，发现菈菈正好从事务所中走出来。

她一副若无其事的样子，与雷欧在一起。法莉亚斯缇雅的气息也还在事务所。

法莉亚斯缇雅八成刚刚都在二楼陪着菈菈。

「菈菈小姐！雷欧！差不多该回去了！」

「......嗯。」

菈菈这样回应，牵起齐格的手，将他扶到雷欧的背上。

接着，她自己也爬上雷欧，坐在后方抱住齐格。

「那么，我送他们回去。」

亚历走在前头，雷欧则小跑着跟上。

正当他们经过我身边时，菈菈瞥了我一眼，露出一抹得意的笑容。

这笑容是什么意思？

尽管不明白，但我目送他们离开后，便回到了事务所。法莉亚斯缇雅又回到了接待处，从这点来看，她应该是和菈菈一起下楼的。

我告诉她差不多可以准备下班后，便朝书房走去。

「唔......」

刚进书房，我便明白了菈菈那抹笑容的含意。

是椅子。

我常坐的那把椅子上散落着大量的苍耳子。

要是就这么坐下去，这些果实肯定会全黏到我的屁股上。

这是个恶作剧。

我不禁微微扬起嘴角，将那些苍耳子搜集起来，放进袋子里。可是就在我打算将袋子收进桌子时，突然感觉到了一丝不对劲。

「唔......？」

那是非常细微的不协调感。这种感觉，与当初被刺客下毒时如出一辙。

有魔力附加品与龙圣斗气护体，毒根本对我不起作用，但依然让我感到不对劲。

「......」

即使如此，我还是毫无戒心地拉开了书桌抽屉。

下一秒，几只活生生的蝗虫从里面蹦了出来。一共五只。

\\

看来，这是菈菈想以苍耳子为饵让我大意，再以这些蝗虫吓唬我的两段式作战。

她八成是躲在接待处的某个地方，算准我离开后再偷偷侵入书房，完成了这场恶作剧。

也难怪她会笑得那么得意。

「......」

不过唯独菈菈，我实在无法预测她会成长为什么样的人。

人神究竟在害怕这孩子的什么地方......

\\

★　★　★

\\

几天后，鲁迪乌斯回来了。

他不仅成功拯救了目标的一家，还让周围地区下了场雨，设法缓解了饥荒。这男人真的很能干。

听过一番报告后，我向他提出关于齐格的事。

「......我想让齐格哈尔德定期过来我这里。」

「这是......为什么？」

理所当然的，他露出了疑惑的表情。那么，该如何解释呢？

「有件事让我有点兴趣，我想在旁亲眼看看。」

「............会有危险吗？」

「不会。」

「可以给他设个门禁吗？」

「无妨。」

「明白了。那么我也先向妻子说一声。」

尽管我没有说明得很详细，他却这么干脆地答应我，是出于对我的信任吗？

还是说，他早就不奢望我能把话说得更仔细一点了吗？

「没有其他要问的吗？」

「不用。虽然不知道为什么要瞒着我......不过谁在做什么，我大致能猜到。」

「嗯。」

「我也觉得这样比较好。请代我转达给亚历，说齐格就麻烦他多多关照了。」

已经看穿了吗？不过这样也好。

今后与鲁迪乌斯的关系还会继续下去。若能简单看透对方的想法，交流起来也会更加轻松。

隐瞒对方的事情还是越少越好。

「那么，我也该回去了。」

「嗯，辛苦了。」

当鲁迪乌斯正要转身离开时，我忽然想起一件事，便叫住了他。

「鲁迪乌斯。」

「什么事？」

「切达人是什么？」

鲁迪乌斯一瞬间愣了一下。

「是一个脸用起司做的英雄。他会到饿肚子的孩子面前，撕下一块自己的脸让他们吃，还会一拳打倒那些威胁人们的坏蛋。」

「......你原本的世界里有这样的人吗？」

「在我的世界其实是填满红豆馅的面包。不过，因为『红豆』这个概念没办法让人理解，所以我改成了切达起司。哄孩子睡觉的时候，我总会讲这样的故事。」

鲁迪乌斯这样告诉我。

切达人是吗？居然会把自己的脸撕下来给别人吃，实在莫名其妙。

「请问这件事怎么了吗？」

「不，纯粹有点好奇而已。」

「这样啊。那么，我告辞了。」

目送鲁迪乌斯回家后，我也回到书房。

望向桌上，上面还留着菈菈留下的装满苍耳子的袋子。

而那些蝗虫早已逃之夭夭，不见踪影。

不知道菈菈回去后，是否会因为在家里的恶作剧而被狠狠训斥一顿呢？

「呵。」

我忍不住笑了出来。

菈菈、法莉亚斯缇雅、亚历山大、齐格，再加上鲁迪乌斯和切达人是吗？这次的轮回真是充满了新鲜感。

** 米里斯旅行记
*** 「问候拉托雷亚家」

孩子们正茁壮成长。

露西已经逐渐适应了拉诺亚魔法大学的生活。

菈菈似乎不喜欢念书，但健康活泼，这样也挺好的。

亚尔斯像艾莉丝，稍微有点粗暴，但意外地很认真，也不会欺负弱小，应该不用担心。

齐格还小，依然是个爱哭鬼，但或许是因为最近被某个人锻炼过，似乎变得更坚强了一些。

莉莉和克莉丝还很年幼，但早已断奶，最近开始接受英才教育。

虽说第七个孩子没出生，但家里还是有六个小孩。

每天都过得很热闹，问题也层出不穷。

话虽如此，随着菈菈与亚尔斯开始上学，莉莉和克莉丝逐渐学会用自己的脚站起来走路，开始学习各种知识，感觉生活也慢慢稳定了下来。

人神感觉依然没有任何动作。这阵子确实过着平静的每一天。

\\

那天晚上也依然热闹。

自己的事情已经有办法自己来的露西，因为在玩食物而被凶的菈菈，因为挑食而被训斥说这样不行的亚尔斯，脸颊塞满了饭的齐格，一边喝汤一边把可爱的围兜弄得脏兮兮的莉莉，坐在我的腿上，张着嘴等着我喂下一口的克莉丝。

然后是三名妻子，一个妹妹，两位母亲。

整个餐桌都充满欢笑。

不仅是餐桌，最近整个家里都很热闹。

这也是当然的。毕竟有六个孩子，不可能不热闹起来。

亚尔斯和菈菈调皮捣蛋，经常惹出各种骚动。莉莉与克莉丝虽然是同龄，但感情不太好，经常大吵大闹。露西虽然是个稳重的孩子，齐格也算是比较老实，但也不可能都一直很安静。

每天喧嚣声不绝于耳。

就在这样的日常中，我突然想到，这样的时光或许是只有现在才有的。

当孩子们长大后，也不晓得到时会怎么样。

或许会和奥尔斯帝德并肩作战，或许会离开夏利亚，到某个地方。

在大家成年后，会送他们去阿斯拉王国的学校读三年，到时也许会定居在那里。

也有可能在还没成年之前就因为某些状况而离开这个家。

就像保罗当年与父亲吵架后离家出走一样，说不定我家也会发生这样的事情。

我因为担心人神的影响，经常想要干涉孩子们的各种大小事。不过，孩子不可能总是听从父母的安排。像菈菈就很讨厌念书跟锻炼，经常趁机逃跑。

不过，这也无妨。

总而言之，我是这样想的。

孩子们全都聚在一起的日子，肯定也只有现在了。

所以，我想说要趁现在这个机会办个家族旅游。

\\

★　★　★

\\

当然，并不是要环游世界。

只是打算用一个月的时间，拜访许久未见的人，让孩子们稍微看看这个城镇以外的地方。

仅此而已。

如此这般，这次的目的地是米里斯大陆。

计划是这样的。

首先，用转移魔法阵前往米里斯神圣国，在那边停留十天左右。前半段时间拜访塞妮丝的娘家，向克里夫以及米里斯教团打声招呼。后半段则是参观冒险者公会总部和魔术塔这类有着米里斯神圣国特色的地方。

之后再搭马车沿圣剑大道北上，稍微参观一下大森林，然后去青龙山脉泡温泉。最后在那一带设置转移魔法阵，返回夏利亚。

由于以前打算与鑛神接触，但一直延后到现在，所以我也打算藉这个机会为该计划铺路。

大概就是这样。

我在执行的半年前告诉家人这项计划。

毕竟洛琪希是老师，她有课程上的安排，我也必须要随时请示社长奥尔斯帝德的吩咐。孩子们也有各自要学的东西，大家也都有自己的安排。

话虽如此，家人们都欣然同意了这次旅行。

尤其是露西，她可能还记得之前去阿斯拉王国旅行的事，一听到要去旅行，脸上就满是兴奋之情。

我顺便问了艾莉娜丽洁要不要一起去，她也爽快地答应了。

她很高兴找到了这么好的借口。

尽管她一年内会有几次与克里夫见面，但其实还是想和他时时刻刻待在一起吧。

我也希望克里夫能早日飞黄腾达，把艾莉娜丽洁与克莱夫接过去，但米里斯教团内部的权力斗争似乎比想像中更为复杂。

这次的计划还包括拜访拉托雷亚家，因此塞妮丝和莉莉雅也会一起同行。

我也想顺便请神子帮忙听一下塞妮丝的心声。虽然菈菈好像能和塞妮丝对话，但她不太愿意告诉我。就算我直接问，她也总是一脸嫌麻烦的样子。

或许，以她的年龄还无法理解这种事的重要性。

先把菈菈的事情放一边。虽说这算是个人的私事，但我提前半年就和神子与教皇这些米里斯相关人士约好时间，想必不会见不到面。

另外，我这次还邀请了诺伦一家。

我曾答应克蕾雅带诺伦去拜访她。

不对，好像也没有约好。无论如何，我认为让她看到诺伦婚后过着幸福生活会比较好。顺带一提，结婚的消息我也早已告诉她了。

我用自己的观感清楚告诉她对方是什么样的人。当然，包括伴侣是魔族的事情在内。

不过，她一直没有回应，也许是在生气。

也有可能是假装没听见。

不管如何，这肯定算是必要的交代。

起初，诺伦以孩子还小为由，拒绝同行。

她的女儿瑞雪莉亚成长得很快，早已断奶，牙齿也长齐了，能摇着遗传自父亲的绿色头发和可爱的尾巴蹒跚走路，但她还是不想让女儿离开自己的视线。

然而，这时瑞杰路德对诺伦这样说：

「孩子由我照顾，你就去吧。」

「可是......」

「要珍惜亲人。」

这句话听起来格外沉重，于是诺伦便答应了。

至于瑞杰路德，他似乎也想要跟我们同行。他说虽然自己对人族的文化不太了解，但如果需要问候，自己也应该参与。

然而，带着小孩一起旅行一个月本来就很困难，更何况是斯佩路德族。

就算能像齐格那样戴上帽子，尾巴却无法隐藏，再加上她不只是头发绿色，还是真正的斯佩路德族......这样一来不仅会引起骚动，甚至会对孩子造成心理创伤。

此外，瑞杰路德在村子和毕黑利尔王国都有自己的工作。

于是，他抱着断肠之痛送走了诺伦。

「我明白了，但我只是去打声招呼。不会去泡什么温泉，会直接回来。」

「不用那么着急。好好享受这趟旅程。」

「但我想和瑞杰路德先生和瑞雪莉亚在一起。」

诺伦就像这样在我面前放闪，然后心不甘情不愿地答应与我们同行。

至于家里的留守工作，我拜托了佣兵团和札诺巴负责。

比特和次郎会留守家中。毕竟若是家里有窃贼闯入就麻烦了，况且家庭菜园也需要有人照顾。

总之，旅行计划大概就是这样。

整体来说比较随性，但要是安排得太紧凑，被行程追着跑也不会好玩。

这样想必刚刚好吧。

\\

★　★　★

\\

过了半年后。

魔法都市夏利亚依然围绕在一片白雪之中。

我们在家门前集合叫了马车，搭乘后穿过被积雪覆盖的街道，前往事务所，在那里向奥尔斯帝德打了声招呼，便踏上了通往米里斯神圣国米里希昂的魔法阵。通过魔法阵后，我们来到了位于米里希昂的根据地。

转眼间就抵达米里斯大陆。

虽说想要出门旅行，但这样根本也没有什么好感慨的。

如果可以的话，我是希望带孩子们去移动到城外的魔法阵，从外面好好看看米里希昂。毕竟亲眼看到那座巨大无比的高塔，并体会穿越高耸城墙进入城内时的兴奋感，并不是随时都有机会体会到的。

不过，这些景象在离开城镇时同样能看到。

因此也不必急于一时。

我们在根据地换乘了事先准备好的马车，直接前往米里希昂的拉托雷亚家。

包含我在内计是十四人加一只。

因此，我们准备了两辆大型马车。

第一辆马车坐着我、洛琪希、塞妮丝、莉莉雅、菈菈、克莉丝和雷欧。

第二辆马车则是希露菲、艾莉丝、露西、亚尔斯、齐格、莉莉、爱夏和诺伦。

至于艾莉娜丽洁和克莱夫，则在这里暂时与我们告别，他们将直接前往克里夫那里。

孩子们因为第一次旅行而兴奋不已，三位妈妈都忙着控制他们的情绪。

尤其是菈菈，她或许是很中意米里希昂的景色，甚至喘着粗气从马车窗户望向窗外。

这对没有情绪波动又总是爱睡觉的菈菈来说，实属罕见。

「菈菈，别把身体探出窗外。」

「......好。」

由于菈菈偶尔会把身子探出窗外，洛琪希注意到后便这样提醒她，将她拉了回去。

然而，她还是喜欢把下巴靠在窗框上，东张西望地看着外面。

虽然担心她会突然探出身体掉下去，但有雷欧叼住了她的衣摆，应该不会有事。

「......蓝妈妈，这里的颜色比家附近多很多。」

「米里希昂有许多知名设计师，他们会为平民设计服装，这里的人都很喜欢打扮。」

「明明是冬天却没下雪，也不冷。」

「这一带并没有那么会下雪，但某些季节会大量降雨。不过，那座高塔能保持水量稳定，所以镇上不会洪水泛滥。」

看着洛琪希耐心地向兴致勃勃的菈菈解释，心头不禁涌起一股暖意。

这样看的话，菈菈果然很像洛琪希。

感觉就是迷你版洛琪希。

「爸爸，我肚子饿了。」

克莉丝坐在我的腿上，心情一直很好。

或许是因为害怕外面的环境，或者是马车的颠簸让她不安，她紧紧抓着我的袖子。

如果强行拉开她的手，想必她会哇哇大哭吧。

「等到了曾祖母家再吃饭，好吗？」

「好。」

克莉丝很乖巧，愿意听从我的话。

如果她在跟其他几位妈妈说话，这时可能会撒娇说要马上吃点什么。

虽然有点对不起希露菲她们，但和克莉丝在一起，会让我有小小的优越感。

不过，看着克莉丝拉着我的手轻轻摸着她的小肚子，确实想买点什么给她吃。

前面有个小摊贩，去买颗甜苹果吧。什么？不知道哪颗比较甜？那整间店都全包了吧。不用担心，多的就带去拉托雷亚家当伴手礼──会让人想这么说呢。

话说回来，为了讨好拉托雷亚家，我准备了各式各样的伴手礼，不知道克蕾雅夫人会不会开心呢？

要是她说出「我不需要这种下贱的东西」的话，那该怎么办？

不，应该不至于讲得这么无礼吧？

正当我胡思乱想时，突然注意到莉莉雅的脸色有些僵硬。

「......莉莉雅小姐，你怎么了？」

「我有点不安。」

「不安什么？」

「是关于克蕾雅夫人的事。」

这趟旅行中有一个麻烦。

那就是我的祖母，克蕾雅•拉托雷亚。

这位性格固执的外婆在听说我们要去米里斯旅行后，马上跟我联络，说要我们住在她家。

我们其实也可以拒绝。

也可以选择只是仅仅拜访，而不住在她家。

想到她过去对诺伦、爱夏和莉莉雅的「那种态度」，难免令人感到不安。

不过就我来说，我对这位固执的外婆并没有特别讨厌。

克蕾雅确实有很大的缺点，但还不至于拒绝让她与我那可爱得不行的孩子们共度短暂的几天时光。

因此，不管怎么样，就先让彼此见上一面。如果接触后觉得真的不行，再另外找住宿的地方也不迟。

我们在家庭会议上得到了这个结论。

话虽如此，莉莉雅之前确实被她说过许多尖酸刻薄的话。

一想到之后有可能再听到那些，自然会感到不安。

「再怎么说，克蕾雅夫人还是会考虑到我们的感受的。虽说她的想法有点死板......啊，不然，就请你躲在我身后好了。」

「不，我不是担心自己。」

莉莉雅的目光落在洛琪希和菈菈身上。

没错，这次同行的有洛琪希和菈菈......也就是身上流着魔族之血的人。

更别说诺伦还与魔族结了婚。而且，这次三位妻子也全员同行。

而克蕾雅是一个虔诚的米里斯教徒，还是排斥魔族派系。

虽然我曾经提醒过她不要对我家的方针挑三拣四，但那是好几年前的事了。人很容易把几年前的小约定抛诸脑后。

当然，洛琪希也早就对这件事做好了心理准备。

在家族会议上，她也自信地表示「没问题」。

她还提到，菈菈和莉莉可能会稍微受到委屈，但也能趁这个机会教导她们，让她们知道有着魔族血统的人在人族生活的地方可能面临到的问题。

至于诺伦，她想必也知道自己有可能会被说什么，已经做好了觉悟。

至于我，除了对魔族相关问题有些担忧外，更担心菈菈被说了什么不中听的话后，会不会做什么奇怪的事情。菈菈的恶作剧总是令人捏一把冷汗，毕竟她没在管对方是谁。

「莉莉雅小姐，放心吧。」

洛琪希这样说道。

「如果真的不行，当初也不会说要接待我们了。」

「是这样吗？」

我心里也有些疑虑。

并不是说我不信任克蕾雅。

但她确实主动邀请我们。

特意邀请我们来，却只是为了说些刻薄的话，应该不符合贵族的礼节吧。虽然我对米里斯贵族的规矩不是很清楚，不过，应该不至于对专程从远方来访的人如此无礼。

只是，人类这种生物就算懂得那些常识，当面对讨厌的事物时，依然不晓得会做什么。也有事到临头才发现无法接受的情况。

「......」

就在这时，塞妮丝握住了莉莉雅的手。

虽然她没有说话，但可以知道她在传达着什么。我轻拍了菈菈的肩膀。

「奶奶说了什么？」

菈菈一脸不耐烦地看了我一眼，又看了塞妮丝，最后回头对我说：

「......她说，曾祖母只是有些爱操心，不会有问题的。」

「谢谢你。」

菈菈难得愿意帮忙充当翻译。

总之，既然塞妮丝都这么说了，那肯定没问题。

\\

★　★　★

\\

我们抵达宅邸时，迎接的氛围相当友善。

女仆们个个笑容满面，管家的态度也十分礼貌。

至少，感觉比我上次来米里希昂时还要受到欢迎。

我们将行李交给佣人后，被带到了克蕾雅所在的房间。

「长途跋涉，辛苦了。」

克蕾雅见到我们，依然坐在椅子上并如此说道。

她没有起身。不过也没办法说她态度不好，毕竟她是这个家的主人。

「不会，毕竟现在很快就到了。」

「是这样没错呢。虽然我还是很难理解这种事......」

克蕾雅按住太阳穴，似乎有话想说，但最后还是吞了回去。

她刚才咽下去的，大概是对我将转移魔法阵当成私人交通工具的不满吧。

毕竟转移魔术在这里仍然被视为禁忌。

「我来介绍一下家人。」

「好的，请吧。」

我将家人依序站好。

向她介绍孩子们、三位妻子，以及诺伦和爱夏。

今天的爱夏不是穿着女仆装，而是一件可爱的连衣裙。

乍看之下其实也挺像长女的。莉莉雅虽然也没穿女仆装，但她和塞妮丝先一起去了别的房间。

「玛莉。」

「是，夫人。」

克蕾雅命令身旁的女仆，并伸出手。

女仆像是在帮忙扶起那般将克蕾雅抱起，并递给她拐杖。

克蕾雅吃力地站了起来。手拄着拐杖，看起来没有力气，与我上次见到时那份充满威严的模样完全不同。我们来的时候她之所以一直坐着，原来并非出于傲慢。

「您身体不舒服吗？」

「只是上了年纪罢了。」

「您的年纪应该还不至于腿脚不便吧......」

虽然她已到了被称作曾祖母的年龄，但我这个孙子以及我的孩子们都是比较早出生的。尽管我没刻意过问她年龄，但塞妮丝大约四十岁，那么克蕾雅应该也就在六十到七十岁之间。

「如果需要的话，我可以帮您使用解毒或治愈魔术。」

「不用了。你虽然是位出色的魔术师，但这里是米里希昂，而我是贵族。」

意思是她不缺乏治疗魔术方面的治疗资源吧。

嗯，既然她这么说，那应该是真的没问题。但看到她衰弱的模样，还是让人有些担心。

「与其担心我，我更希望你先把家人介绍一下。」

「说得也是。」

于是，我开始逐一介绍。

首先从希露菲、洛琪希以及艾莉丝这三位妻子开始。

「这位是希露菲，她是我的第一任妻子，目前负责家中的大小事务。」

「我是希露菲叶特。今天承蒙您的邀请，十分感谢。还请多多指教。」

不愧是希露菲，连一次简单的问候都展现出她的从容与优雅。

谁也不会想到，她其实出身于菲托亚领地的乡下。

「这位是洛琪希。她是米格路德族......也就是魔族。虽然看起来很年轻，但实际年龄比我大，目前在魔法大学担任教师。」

「我是洛琪希，虽然您可能会稍微介意我个人魔族的出身，但接下来几天请多多关照。」

洛琪希自我介绍时提到自己是魔族，但克蕾雅连根眉毛也没动。

尽管这次是双方第一次见面，但这些资讯姑且已经事先告诉过她了。

看来，她并不会因为魔族身分而说三道四。

「这位是艾莉丝，剑神流的高手，同时是阿斯拉王国大贵族伯雷亚斯家现任当家的妹妹。」

「我......我是艾莉丝，请多多指教。」

艾莉丝的问候还是显得有些僵硬。

虽然她在阿斯拉王国的宴会上表现得很自然，但面对我的祖母克蕾雅时，可能还是会紧张吧。

「......」

克蕾雅并没有多说什么。总之，她对我有三位妻子的事没有说任何怨言。

接着是介绍孩子们。

「这位是长女露西。」

「我是露西•格雷拉特！曾祖母您好，很高兴第一次见到您！接下来几天请多多指教！」

露西捏着裙角，优雅地行了一礼。

克蕾雅的脸上稍稍露出了笑意。即使对孙子再怎么严厉，克蕾雅还是觉得曾孙很可爱吧。

「这位是次女菈菈。」

「......菈菈。」

菈菈依然表现得冷淡且不耐烦，看起来对一切都兴致缺缺。

克蕾雅见状，微微皱起眉头，看来这跟对方是不是曾孙无关。

「他是长子亚尔斯。」

「亚尔斯！快八岁了！请多多指教！」

话虽如此，表现得很冷淡的也只有菈菈。

其他孩子们都表现得很有礼貌，克蕾雅的眉头也没再皱起来。

排在亚尔斯后面的齐格哈尔德、莉莉和克莉丝也顺利完成了介绍。

「你们也来问候一下吧。」

在我的敦促下，诺伦和爱夏走向前。

两人步伐一致，用堪称优雅的举止行了一礼。爱夏自不必说，诺伦的动作也相当得体。

「我是诺伦•斯佩路迪亚。久违了，祖母。」

「我是爱夏。今天承蒙您的邀请，感激不尽。」

从举止来看，她们的问候显得无可挑剔。克蕾雅拄着拐杖，微微抬起下巴回应。

「嗯，久违了，你们两个。」

只有这样。

她并没有询问诺伦结婚的那件事。她认为这件事不适合在这种场合谈论吗？

总之，至少一开始的气氛没有变糟。

这多亏了大家很得体地进行了问候。

太好了太好......啊，菈菈居然在挖鼻孔，待会儿还是稍微叮嘱她一下吧。

「这位是克蕾雅•拉托雷亚。她是你们的曾祖母，接下来的十天我们会住在这里叨扰她，别做出失礼的举动。」

我这样说完，克蕾雅优雅地行了一礼。

她的动作依然完美得令人赞叹。希望孩子们务必拿她作为榜样。

「我是克蕾雅。我代替不在家的主人欢迎你们的到来。你们可以随心所欲地吩咐家中的女仆与管家。或许会因文化差异而让你们感到困惑或不快，但请将这里当自己的家，好好放松吧。」

「非常感谢您的厚意。来，大家快向曾祖母道谢。」

「谢谢您！接下来请多多关照！」

孩子们齐声道谢后，克蕾雅略显疲态，坐回椅子上。真是辛苦她了。

就这样，我们这一家的米里希昂观光之旅正式开始了。

\\

「鲁迪乌斯先生，我有些话想与你谈谈，可以请你留下来吗？」

我以为事情已经结束，正准备离开房间时，克蕾雅叫住了我。

我示意其他家人先行离开，自己留在房间。

克蕾雅的表情......嗯，很平静。看起来也不像在生气。

「请坐。」

「失礼了。」

我依言坐在她正对面的椅子上。

这时，仿佛椅子上设了什么开关那般，一杯热茶迅速端了上来。

这样可能会让人觉得「为什么没有端给我的家人？」，但归根究柢，是因为我没让他们坐下。

况且椅子也不够嘛。

「不用这么拘谨，我不是要责备你。」

她似乎看穿了我的心思。不过考虑到以前的事情，保持一点警戒也是正常的吧，希望她别想太多。

「那么，请问有什么事呢？」

「只是闲聊罢了。」

我看向克蕾雅的表情。

她一脸平静地啜着自己的茶。

举止依然优雅。难道说喝茶的方式都有一套规矩吗？

我也学着她的样子喝了一口茶。嗯，使用的茶叶品质确实不错。

「说到茶......最近爱夏开始种植茶树了。我带了一包她亲手采的茶叶过来，还请您品尝看看。」

「那么，我就明天试试吧。」

「希望您会喜欢。」

爱夏每隔几年就会尝试种不同的东西。

有段时期她曾种植类似香草的东西，并拿来用于烹饪，但后来放弃了。

当时是因为什么来着？

啊，对了。我记得好像是因为克莉丝对香草过敏。每当香草散发香气的时候，克莉丝就会鼻水流个不停。过敏症状虽然能用解毒治疗，但体质本身是无法改变的。

「那么，爱夏还没有结婚吗？」

「她似乎还不打算结婚。」

「诺伦已经结婚了吧？」

「是的。」

「她的丈夫是什么样的人？」

本以为会很简单地结束，但果然还是避免不了这个话题。

不过她是问我，而不是直接向诺伦发问，真是体贴。

「是魔族。」

这件事我在信中已经提过了，事到如今隐瞒也没意义，所以我直言不讳。

「这点我已经知道了。他今天似乎没来，我想问的是他是什么样的一个人。」

哦，原来她想知道的是这个。也对，毕竟对方让刚结婚的妻子自己出远门。

克蕾雅是想知道他没来的理由吧。

「他因为两人的孩子还小，所以选择留在家里照顾他们，并对诺伦说『至少你要去向祖母问候』，所以才让诺伦过来拜访。这绝不是因为他轻视克蕾雅夫人或者拉托雷亚家......」

克蕾雅的眉头皱了起来。

「我问的应该不是他没来的理由，而是他是什么样的一个人才对？」

「咦？啊，他这个人很值得信赖。我记得信里也提过，他是一个扶弱惩恶的正义之士。虽然他的家世与人族的标准不同，不过他曾在一支大规模军队中担任过亲卫队的队长，在他的族群中也有着重要的地位。啊，而且他还是那位『杀死魔神的三英雄』佩尔基乌斯大人也另眼相看的人物。再来就是......」

「......可以了。」

克蕾雅打断了我的话，目不转睛地看着我的眼睛。

难道是我说了什么不该说的话吗？

「从刚才那番话，我就明白你将诺伦交付给了一位值得信赖的对象。虽说我心中也有自己的想法，但既然如此，也没必要多说什么了。」

「我很感谢您能这么说。」

「不必感谢。毕竟我之前与你之前有过约定，不会干涉的。」

「原来您还记得啊。」

「那当然。虽然腰不太好了，但脑袋还是清醒的。」

太好了。不过既然这样，她为什么还想问这些呢......啊，毕竟是闲聊嘛。

「话说起来，洛琪希小姐看起来真是娇小啊。」

「那是因为她是米格路德族，实际年龄比外表看起来大很多。啊，不过，还请千万别对本人说她娇小，因为她对这点似乎有些在意。」

「我明白。我也是拉托雷亚家的人。虽然嘴巴不好，但不会拿他人的外貌开玩笑。」

我本来是半开玩笑地说的，她却正经地回应了。

「另外，我也由于之前的经历，在努力地理解魔族与兽族这类人士。」

「我认为这是件好事。不论是喜欢还是讨厌，了解总是很重要的。」

应该说，有时候反而正是因为不了解才会产生偏见。人类常会瞧不起自己不熟悉的东西，觉得低俗。这就像挑食一样。

「不过，菈菈这个孩子确实有点问题吧？」

「......是。」

「当然，我说的并不是因为她是魔族与人族的混血，而是她对初次见面的人表现出的那种态度。」

「非常抱歉。我本来也打算让她至少要好好向您问候，但她最近有点不太听话。」

「......我无意多加干涉。不过，我认为有时候严格地管教也是必要的。」

她的语气虽然委婉，但如果对方是自己的女儿，她应该会不惜动手管教一番吧。

嗯，有时候这确实是必要的。不过，菈菈在这方面倒是很精明，

该怎么说，她总是能巧妙地踩在艾莉丝要不要打她屁股的边缘线上。看似随心所欲，却意外地精于算计。

「为什么必须这么做，我想你应该能够理解吧。」

「是为了她的将来。」

「没错。一个简单的问候，就足以改变他人对自己的印象。有时会因为没有在一开始就表现出应尽的礼仪，而导致未来陷入困境。这也是我们贵族要学习礼仪规矩的原因。」

哦，听起来开始像是在训话喽。

但不知是不是我的错觉，克蕾雅的表情看起来有点开心。

「不过，她的母亲洛琪希小姐虽然是魔族，却非常懂得分寸，举止得宜。」

「是吗？」

「是的。刚才她也非常尊重身为正室的希露菲小姐，始终站在稍微靠后的位置，问候也十分得体，真的很不错。从她的态度，就能知道她充分理解自己的立场。」

哎呀，她竟然有考虑到那种事。

其实，我并没有打算用什么正副之分来安排顺序......不，这样想就错了。洛琪希是认为这样能避免不必要的麻烦，才刻意这么做的。

「至于艾莉丝小姐......既然是武人，多少是无可厚非吧。」

「能听到您这么说我就放心了。」

「......」

克蕾雅看起来好像还想要发其他牢骚。

不过，希望她别再多挑剔什么，艾莉丝那样其实也已经很努力了。

「总之，鲁迪乌斯先生。」

「是。」

「谢谢你带他们过来。」

克蕾雅这样说完，缓缓低下了头。

她并没有特别指谁，不是诺伦，不是爱夏，也不是洛琪希。

而是感谢我带来了「大家」。

在理解这句话含意的同时，我也意识到一件事。

看来我还是有点太紧张了。

其实，我大可把这次拜访当作是去奶奶家玩的那种轻松的旅行......

就这样，我们的米里希昂观光正式开始了。

*** 「亚尔斯在米里斯观光」

亚尔斯之所以想要尝试一个人行动，纯粹是因为无聊。

他刚到这座城镇时，首先映入眼帘的是那些巨大的塔。

白妈妈说那些是巨大的魔道具，正因为有它们，这座城镇才能一年四季保持舒适的环境。

再来，是那座闪耀着银色光芒的巨大建筑。

红妈妈说那是冒险者公会的总部，大多数冒险者都会造访一次的地方。

这些建筑让亚尔斯想近距离亲眼看看。

当然，只要开口，父亲一定会带他去。

就像今天，他说想看那座金光闪闪的建筑，父亲便笑着答应，带他到了那里。

然而，尽管父亲带他到了闪着金光的建筑参观，在建筑内部却不让亚尔斯自由行动。亚尔斯进入里面后，每当他打算像个好奇宝宝四处探索，父亲总是限制他「那里不行」「那里不能进去」。

说实在的，这样的限制让亚尔斯感到窒息，也觉得无趣。

亚尔斯并不知道，鲁迪乌斯是出于对米里斯教团总部的考量。

这里是大圣堂，其中心部更是教团总部的重地，未经允许不得擅自进入。

因此，带着一个调皮的孩子进入这样的场所并不妥当。

不过，亚尔斯还是个孩子。他知道只要说一声，不论是塔还是银色建筑，父亲都会带他过去。

但是行动一定会受到限制，肯定会像今天一样无趣。

他就是这样觉得。

所以，当父亲他们随着被一群护卫保护、胸部丰满的女人进入金碧辉煌建筑的中心部，嘱咐孩子们在他们回来之前先在中庭玩耍的时候，亚尔斯认为这是个千载难逢的机会。

（我要靠近看看那座银闪闪的东西，还有那座塔。）

回想起来，从出生到现在，他的行动总是受到父母限制。

「不要去那里」、「不要一个人在城里乱走」。每当要出去玩的时候，身边也总是有爱夏或雷欧陪着。小时候他对此唯唯诺诺，现在也不打算反抗。尽管他并不完全理解妈妈们的叮嘱，但也知道遵守这些是很重要的。

他虽然是个孩子，但也明白外面充满危机，一个人行动是非常危险的。

再说，他也不讨厌和爱夏单独一起出门。

然而，就算是这样。

他偶尔还是会想试着摆脱监视，自由行动。

「喂，菈菈姐，我们要不要偷偷溜出去，去看看那银闪闪的东西和塔？」

于是，亚尔斯邀请了菈菈。

今天的菈菈难得是独自一人。雷欧因为和那位被称为「神子」的人身边的守护魔兽──白枭有话要说，便将菈菈一个人留在这里去了其他地方。

而菈菈也觉得现在正是个好机会。

菈菈从小就和雷欧感情很好。

当然，现在也不讨厌雷欧，但最近她开始觉得雷欧总是跟在身边，还频频规劝她的行为，实在有些烦人。

因此当亚尔斯邀请她时，菈菈微微勾起嘴角，点了点头。

「我也正想这么做。」

就这样，两人避开了爱夏的视线，偷偷开始行动了。

他们趁着克莉丝哭喊「爸爸不见了！」的时候，悄悄移动到灌木丛中，再从灌木的阴影躲到另一处阴影，朝出口方向前进。

「嗳，你们两个要去哪里？」

就在这时，齐格察觉到他们的行动。

「嘘──只是出去玩一下而已啦。」

「小孩子自己跑出去会被骂的喔。」

「你最近不是也一个人偷偷从后门溜出去吗？我可是知道的喔。」

「我......我才没有......」

亚尔斯其实很清楚。

齐格常常一个人偷偷跑出去。但令人感到奇怪的是只有他一个人能独自出门而不被责备。

亚尔斯认为，这是因为他身边没有像爱夏和雷欧这样的人看着他。

而对于只有弟弟能自由自在地到处乱跑这点，他感到有些不满。

但实际上，齐格并非真的是独自一人。

亚尔斯自是当然，齐格本人其实也不知道，每当齐格一个人从后门偷偷溜出去时，鲁德佣兵团的成员都会在暗中保护他。

当然，这一切都是爱操心的鲁迪乌斯指示的。

「我会帮你保密，所以你也别把我们的事情说出去。」

「......嗯，我知道了。」

「没问题啦，我们只是去看看那银闪闪的东西和那个很大的塔而已。」

「咦？你们要去冒险者公会吗？」

听到银闪闪的建筑，齐格的眼神亮了起来。

他曾从亚历那里听过许多英雄传奇，其中经常提到冒险者公会的总部，让他对此产生了浓厚的兴趣。

「嗯。」

「那我也要去！」

就这样，亚尔斯一行人离开了米里斯大圣堂。

他们抱着一点点恶作剧的心态，以及无限的好奇心迈向外面的世界。

\\

★　★　★

\\

亚尔斯带着齐格与菈菈穿梭于镇上。

与魔法都市夏利亚截然不同的房屋，从未见过的建筑形态，以及令人耳目一新的风景，让亚尔斯的心情无比兴奋。

虽然之前在移动的马车上也有看过，但像这样用自己的双脚走过这些地方，感觉还是不太一样。

或许是因为地面石板的纹路有所不同吧。

不管怎么样，仅仅是在陌生的街道上行走，就让他感到雀跃无比。

这是个只有孩子组成的集团，尤其是齐格的绿发引来了不少异样的目光，但这根本无所谓。

在夏利亚生活时，他们早已习惯这样的视线。

「菈菈姐，走路要好好看前面，这样很危险喔。」

「嗯。」

菈菈虽然应了一声，但依然用闪闪发亮的眼神打量四周。

她对这个干净整洁的城镇饶富兴味，甚至比亚尔斯还要好奇。

「对了，应该也要找露西姐一起来的吧？要是她知道自己被排挤，一定会生气喔。」

「露西姐肯定会说不行啦。」

相较之下，齐格依然有些胆小。尽管他最近有在偷偷锻炼，剑术本领也进步神速，但亚尔斯还是不太懂他的个性为什么这么胆小。

「啊，菈菈姐！那是什么！」

这时，亚尔斯指着前方，眼前有一个奇怪的雕像。

那是个有着猫头鹰形状的雕像，看起来极为生动。

尽管外形类似刚才在金闪闪的建筑中见过的大白鸟，但显然是人工制作，稍微带了一点诡异的感觉。

菈菈看了看，充满自信地回答。

「......那是喷泉。」

「哪有那么奇怪的喷泉啊。」

「但就是喷泉。」

「咦──......绝对不是啦......」

然而，就在亚尔斯看过去的时候，雕像的嘴巴突然开始喷水。

「啊，真的是喷泉！好厉害！你怎么知道的？」

「我在茱丽小姐家看过类似的。」

其实，那是鲁迪乌斯的「副产品」，以鱼尾狮为灵感的喷泉雕像。

这座喷泉模仿了神子的守护魔兽「纳斯」的样貌，在完成后送给了神子。

话虽如此，这座雕像实在不适合放在教团总部。由于它外观看起来有点像剥制标本，神子不喜欢将它摆在身边，于是就被安置在靠近教团的街道上供行人观赏。

「哦──」

在亚尔斯与齐格满怀敬佩的注视下，菈菈骄傲地挺起胸膛。

三人聊着聊着，跨过了一座桥。

随后，周围的景色摇身一变。建筑物变得低矮，行人数量也增加了。

有人腰间佩剑，甚至许多都穿着铠甲。

不知道是不是错觉，周围多了不少长相凶悍、肌肉发达的行人。因为他们从神圣区来到了冒险者区。

「感觉变普通了呢。」

「是啊。」

不过，对于生活在魔法都市夏利亚的他们而言，这样的景象反而更加熟悉。

基本上，虽然那些人个个都是外表凶悍的肌肉棒子，但比起鲁德佣兵团的人来说，还是显得瘦弱许多。

与红妈妈相比，更是有着天壤之别。

「菈菈姐，那个银闪闪的地方在哪？」

「嗯，那边。」

「好，那我们走吧！」

亚尔斯意气风发地向前走去，身后跟着满脸兴奋的齐格，以及虽然看起来有些爱困，但嘴角微微上扬的菈菈。

「哇，好厉害！」

「哇──！」

三人一到大街上，就立刻找到了冒险者公会的总部。

毕竟闪耀着银光的巨大建筑物就屹立在大街尽头。当然一眼就能看到。

「亚尔哥！快一点快一点！」

齐格兴奋地跑了起来。

刚才明明还在反对的，现在完全变了个样。

不管嘴上怎么说，「冒险者公会总部」这个经常出现在英雄故事开头的重要场景，其魅力果然让他无法抗拒。

「啊，等等我啦！」

亚尔斯和菈菈也满怀期待地追了上去。

他们想要快点靠过去亲眼看看。

看到这三个孩子突然跑起来，周围的人瞬间在内心想着「好危险」。

毕竟孩子突然奔跑，不小心撞到人或被马车撞到的情况并不少见。

但出乎人们意料的是，三人以稳健的步伐及速度轻松穿过人群，看起来丝毫不像小孩子。而且，还是在马车无法通行的道路边缘。

这都要归功于他们平日接受的训练。

\\

「喔～！」

三人来到了冒险者公会的入口阶梯前，齐格忍不住发出感叹。

如此宏伟且庄严的建筑，他从来没有见过......倒也不然。

在魔法都市夏利亚也有像魔法大学那样巨大的建筑物。

不过该怎么说呢，这里与那些地方的感觉不同。冒险者公会总部是银色的，闪闪发光。

而魔法大学则是红色与褐色，给人一种土气的感觉。

「亚尔哥，这里就是冒险者公会呢！」

「喔喔，这里就是冒险者公会啊！」

「和我们家附近的完全不一样！」

「毕竟我们家附近的感觉很小嘛！」

「不过这里的味道倒是差不多。」

「嗯，有点臭臭的感觉。」

虽然这些话颇为失礼，但三人还是慢慢地穿过了冒险者公会的门。

这个动作非常安静。因为蓝妈妈之前曾说过，孩子若随意出入冒险者公会，可能会有一些脑袋比较笨的冒险者找碴。

若是真有人来吵架，亚尔斯其实求之不得，但如果让红妈妈知道他们不仅偷偷跑出来，甚至还跟人打架，她肯定会勃然大怒。

红妈妈生起气来是很可怕的。屁股毫无疑问会被打到整个红肿。

若是齐格或菈菈因此受伤，那么到时生气的想必可不止红妈妈。

要是蓝妈妈和白妈妈也发起脾气......想到这里，亚尔斯的脚颤抖了起来。

不过，一想到爸爸会不会也生气，他就有点想要跟人吵架看看。

目前为止，他大多数时候都是受到爸爸的表扬或是宠爱，几乎没有被他责备过。

他甚至也没看过爸爸真的生气的样子。

「哇～」

冒险者公会的内部正如外观能想像到的那样金碧辉煌。

虽然内部的装潢透露着岁月的痕迹，却有一种厚重的质感，接待处的数量也很多。

连冒险者的数量也比夏利亚来得多，装备风格更是截然不同。

在魔法都市夏利亚，大部分的魔术师看起来都像新手，而战士与治愈术师则都较为老练。然而在这里正好相反，新手似乎以战士和治愈术师为主，而魔术师会更有老手风范。

「亚尔斯。」

正当亚尔斯满意地观察这样的光景时，身后传来了菈菈的声音。

「好像有四层楼。」

菈菈指着楼梯前的指示牌这样说道。

亚尔斯听了后也看了一眼，发现上面显示冒险者公会有四层楼。

一楼是接待区与等候区，二楼有公会直营店在贩卖武器与素材，三楼是能够享用轻食的餐厅，四楼则是为了大规模阶级的公会提供的集团室。

「我们上去看看吧！」

亚尔斯意气风发地打算朝楼梯走去，突然，一道影子落了下来。

他抬头一看，一名浓妆艳抹、胸部丰满的女人站在他的身后。

「这里可不是小孩该来玩的地方喔。你们来这里做什么？」

「来......来观光的！我们是从拉诺亚王国来的......」

亚尔斯反射性地这样回答，因为爸爸早就教过他们这么应对。

「父母呢？」

「现......现在只有我们。」

「这样啊......那么，我带你们参观一下怎么样？虽然看起来这样，但我可是职员喔。今天的工作在上午就结束了，你们不介意的话如何？」

女子这样说着，秀出了别在肩上的徽章。

确实，这个和接待处的人身上的东西一样。

「麻......麻烦你了！」

亚尔斯内心暗自兴奋，这样思考。

他非常喜欢丰满的胸部。当然就算是小的也不讨厌，但大的更让他心动。

眼前这名女性的胸部与爱夏的差不多大，也就是说，这个尺寸已经足以让亚尔斯心跳加速了。

「好，那就交给我吧。来，一楼就如你们所见，是接待区。」

这位女性职员露出亲切的笑容，开始一一介绍起来。

三人跟着她，在冒险者公会总部到处参观。

一楼、二楼、三楼、四楼......这位女性职员以不像对待孩子的态度，细心为他们进行了详细的导览。

他们原本打算自由探索，却变成了有导览员陪同的参观行程。

虽然与预期不同，但看到的一切都让人耳目一新。

尤其是在夏利亚的冒险者公会里见不到的集团室。那富丽堂皇的内部装潢，完全不像是冒险者的所有物，让他们的内心激动不已。

\\

「介绍就到这里。觉得有趣吗？」

带他们参观一轮后，女性职员这样说着，低头看向亚尔斯。

「嗯，非常有趣！谢谢你！」

「不用谢谢我啦......那么接下来你们打算怎么办呢？爸爸或妈妈会来接你们吗？」

「不......不会......」

「哦～那要不要我送你们回去？」

「不用了。我们自己可以回去！」

亚尔斯之所以拒绝，是因为他们还没去塔那边。

他原本可以撒谎说有人会来接，但要是他们继续往城外移动，这位女性也肯定会察觉的。

他们还没有到达目的地，不能就这样回去。

抱着这样的想法，亚尔斯带着大家离开了冒险者公会。

虽然预定有些乱了，但结果还算顺利。

「好啦，去一个地方吧！」

亚尔斯指的不只是塔的方向，还有已经过了正午、开始倾斜的太阳。

\\

★　★　★

\\

前往塔的途中，他们见到了各种新奇的事物。

蜿蜒复杂的水道、在水道上航行的小型船只、疑似从魔物身上采集来的大量素材正被运输车辆装载，还有负责护送这些东西的一大群冒险者......

每当发现新奇的景象，亚尔斯等人都会发出赞叹，彻底乐在其中地享受这一切。

然而，或许是因为他们一路上东张西望，又或是看似不远的塔实际上相距甚远。

他们抵达塔时，已经是夕阳时分了。

「哦哦～这个也好大喔......」

在夕阳的余晖下，眼前的塔令亚尔斯等人看得叹为观止。

那根柱子粗得小孩可能需要几分钟才能环绕一圈，并且高耸到只能一直抬头仰望。

而且靠近一看，塔的表面隐约刻有一些纹章。

整座塔都是魔道具......其实不然，这是为了保护内部的魔道具，而在塔上施加了坚固的结界魔术所致。

当然，亚尔斯对此一无所知。

他只是记得莉莉很喜欢这样的东西，所以她看到应该会很开心吧。

「亚尔哥，好像真的进不去里面。」

「是吗？算了，那也没办法。」

齐格找到了一个状似入口的地方，但那里有两名士兵驻守，似乎不允许任何人进入。

不过，这也是理所当然的。虽然亚尔斯也很想登上塔，从上面好好观看眼前的美景，但既然没办法也只能放弃，他还是有这样的判断力的。

「唉～......那我们回去吧！」

「嗯！」

「嗯！」

充满干劲的亚尔斯带头踏上归途，菈菈和齐格也跟在后面。

「菈菈姐，今天真有趣呢！」

「嗯，很有趣。那个挂在集团室墙壁上面的龙头，我也想要。」

「那等我长大后帮你拿回来！」

「到时我也会帮忙的。」

他们看到平常无法见识到的事物，十分满足。

特别是齐格，他显得格外兴奋，从刚才就一个劲地对菈菈说话。

但是，亚尔斯走着走着，心中突然泛起了一丝不安。

他心想「该不会......不，怎么可能」。

「嗳......嗳，亚尔哥，冒险者公会里摆着一把大剑对吧，你知道那是什么吗？」

「不知道耶？」

「那个啊，是四十八魔剑之一喔！」

「哦～真亏你知道呢。」

「我觉得挂在那里的应该是仿制品，但之前亚历先生有画图给我看过。」

「哦......」

「啊，等一下啦亚尔哥！」

亚尔斯敷衍地回答齐格，但脚步却加快了。

齐格看到亚尔斯突然变得沉默起来，歪着头感到疑惑，但还是继续边走边和菈菈聊天。

菈菈虽然也有点在意亚尔斯的态度，但她同样没有说什么，继续听着齐格的话。

三人就这样走着。

由于平时经过锻炼，他们并未喊累，也没有抱怨脚痛得走不了。

然而，齐格看着亚尔斯默默地走在前方，自己的话也逐渐变少。

最后，他完全陷入了沉默，三人就这样一言不发地走着。

在夕阳的余晖中，迈着疲惫的步伐。

就这样，太阳完全落下了。

\\

夜幕降临后过了几十分钟。

他们茫然地站在一条昏暗的巷道里面。周围鸦雀无声，感觉不到人的气息。

「嗳，亚尔哥，还要走多久才能到？」

「......不知道。」

亚尔斯其实也没打算弄成这样。

他并非完全没有考虑过该怎么回去。

来的时候，只要朝着那座巨大的塔走就行了。那么回去的时候，只要以金色的建筑为目标走就可以了。

毕竟，那可是金色的建筑。不仅远远就能看到，回去时也只需要顺着来时的路折返，应该非常简单。

亚尔斯原本是这么想的。

然而，黄昏时分的夕阳将一切染上了金黄色。

而且，伴随夕阳而来的长长阴影，改变了刚才走过的道路给人的感觉。

再加上他们在走去塔的路上不停地被各种新奇的事物吸引，想必也是忘记路线的原因之一。

「不知道是什么意思──」

「吵死了！不知道就是不知道嘛！」

见亚尔斯大声怒吼，齐格吓得身子一颤。

加上一向可靠的哥哥突然大声喊叫，齐格现在终于意识到事态的严重性，眼眶渐渐湿润。

他虽然开始在亚历的指导下开始修行，但依然只是个年幼的孩子。

加上他是个性温顺的孩子，还不习惯被人斥责。

「亚尔斯。」

菈菈以平静的语气这样叫他。

这时，亚尔斯才猛然回头。站在眼前的是随时都快哭出来的齐格，以及一如既往面无表情的菈菈。

只是，她的站姿中包含着些许怒气。

「......对不起，菈菈姐。我迷路了。」

「嗯。」

「菈菈姐，你知道路吗？」

「......不知道。」

菈菈无力地摇了摇头。平时无所畏惧、天不怕地不怕的姐姐，现在竟露出如此无助柔弱的模样。

看到她的反应，亚尔斯顿时感到一阵绝望。

但他没有说丧气话，也没有哭，而是紧握双拳。

「没......没事的！交给我吧！」

亚尔斯认为这是他自己闯的祸，必须由自己设法解决。

亚尔斯执起菈菈与齐格的手，用力一握。然后，为了让他们安心，他用平常根本不会用的大脑，努力思考。

他想起蓝妈妈曾经说过。

遇到危机时不要慌张，先想清楚自己能做什么。

「呃......对了，先找到大马路吧！那里应该有人，再向他们问路就好了。金色建筑没有那么多，他们应该会知道的。」

现在才刚入夜。

只要到了大马路上，肯定还有许多人，向那些人问路是最简单的方法。

蓝妈妈也这样说过「要是遇到不懂的事情，不要害羞，要主动询问」。

「......如果问到的人很坏，不肯告诉我们怎么办？」

齐格带着哭腔说出了负面的发言，亚尔斯听了后一时语塞。

虽然他相信总会找到知道的人，但也很难说对方一定会告诉他们。

蓝妈妈还曾这么说过。

不过，不是所有人被问就会愿意告诉你，甚至也有可能会说谎，所以要小心。

「那时候......啊，对了！爸爸说过，如果在镇上和妈妈走散了，迷路的时候就去找教会，在那里说出克里夫叔叔的名字就能得救了！如果是神父的话就不会说谎吧？」

「啊......对耶！」

尽管神父也非常有可能会信口开河，但此刻齐格脑中浮现的是克莱夫的爸爸，也就是克里夫的脸。虽然他们见面的次数不多，但齐格认为他是个绝不会说谎的人。

「这样我们就能回去了。」

「嗯，可以的。所以你也别哭了。切达人可是不会哭的喔。」

「我......我才没哭呢！」

随着齐格的表情逐渐恢复，亚尔斯的内心也开始有了些许余裕。

他向菈菈投以感激的笑容，因为是她让自己重新找回了冷静。

「好。」

总之，要找到大马路，不然就是教会。

尽管周围感觉不到人的气息，但只要途中发现有人，到时再直接问就好。

只是这样应该很简单。在如此思考的同时，亚尔斯的内心悄悄浮现另一股不安。

他擅自离开，迷了路，还把菈菈和齐格牵扯进来。妈妈们一定会大发雷霆。

红妈妈会非常生气。而蓝妈妈和白妈妈也会狠狠凶一顿。

平常要是遭到责骂，会有爱夏帮忙调停，但这次他们正是避开了爱夏的眼线偷溜出来的。

想必连爱夏也不可能帮他们说话。

「呜......」

「亚尔斯，你在哭吗？」

菈菈突然凑到亚尔斯的脸前，轻声问道。

亚尔斯用袖子迅速擦掉快要从眼角流下的眼泪，撅起嘴说道：

「我......我才没哭！只是有沙子跑进眼睛而已！菈菈姐也是！不要跟丢了！要是在这里分散就完蛋了！」

「......嗯，我知道了。亚尔斯真可靠呢。」

「别这样说啦。会搞成这样也是因为我吧。」

「我也有责任。」

菈菈轻轻拍了拍亚尔斯的头，用手抚摸着。亚尔斯有些脸红，同时转向前方。

得赶快移动。继续待在这种昏暗又没有人的地方，仿佛真的会哭出来。

现在已经肯定会挨骂了。就做好心理准备吧。说不定连爱夏也会因此讨厌自己，但还是要好好向她们道歉。

亚尔斯这样想着，然后转过眼前的街角。就在这个瞬间。

「哦。」

他差点撞上一名女子。

那是一个胸部丰满的女人，亚尔斯看到那熟悉的胸部大小，不禁叫了一声。

「啊......」

「咦？你们是白天的......」

那正是白天在冒险者公会总部带亚尔斯他们参观的女性职员。

「大......大姐姐？你怎么会在这里？」

「咦？你问我为什么，我当然是刚下班正要回家啊，因为我家就在这附近。倒是你们怎么还在外面？天都这么黑了，再不回去可是会挨骂的喔？」

亚尔斯松了一口气。因为在这个时候遇到了认识的人。

虽然他应该不晓得「绝处逢生」这个成语，但对他来说无疑是道曙光。

「那个......我们迷路了。你知道大马路......不对，教会或者那个金色建筑在哪边吗？」

「金色建筑？你说大圣堂吗？」

「对！没错！大圣堂！」

「那我当然知道啦，住在这个城镇的人怎么可能不知道大圣堂在哪呢。」

亚尔斯与齐格顿时互看对方一眼。

但是，亚尔斯这时绷紧表情，清了清嗓子。

他想起自己有跟白妈妈好好学过向人求助时应有的态度。

「那个......如果可以的话，能麻烦你带我们去吗？我爸爸应该会帮你准备谢礼的。」

「......真是的，迷路的孩子不用那么客套啦。好了，跟我来吧。」

亚尔斯突然想到。

白妈妈说过，人与人之间的连结非常重要，甚至哪怕只有短暂的交集，对方也有可能在自己陷入困境时伸出援手。

他觉得，大概就是这么一回事吧。

亚尔斯在这天，变得更像大人了。

\\

★　★　★

\\

「好了，到了喔。」

在女性职员的带领下，亚尔斯等人终于抵达了目的地。

\\

「咦？」

\\

他们原本是这样认为的。

映入眼帘的，是一条昏暗的小巷。

周围毫无人迹，巷子的墙壁上满是猥亵的涂鸦，地上到处散落着垃圾，整个地方还弥漫着莫名的恶臭。

就算四周再怎么暗，也看得出来周围没有那个金色建筑。

「那个，这里是？咦？」

「不可以喔。你爸爸没教过你们不能跟着陌生人走吗？」

听到脚步声响起，亚尔斯猛然回头。

几名男子挂着下流的笑容出现在他们身后。

亚尔斯立刻看出他们是绑架犯。

但就算看出来了，他的脑袋也还在混乱。

这个大姐姐是冒险者公会的职员，还亲切地带他们参观公会。

这......到底是......啊，她刚才说刚下班，但她一开始说早上就结束了......

「原来你说自己是职员是骗人的！」

「我才没骗人呢。这只是副业，赚点零用钱罢了。这个城镇里，多得是像你们这种想要当冒险者的孤儿呢。来到冒险者公会，没办法成为冒险者就离开了。而我呢，会在他们离开后跟踪他们。如果到晚上还没回家，就会像现在这样。」

「可恶！」

亚尔斯在情急之下，捡起掉在地上的木棍，为了保护姐姐与弟弟将身子微微压低。

「亚尔哥......」

齐格身子微微颤抖，紧紧抓住亚尔斯的衣角。

菈菈依旧面无表情，但脸色看起来似乎有些铁青。

亚尔斯觉得至少必须保护好他们两人。

\\

原因都怪自己。是因为自己判断失误才会变成这样。可是在这种时候，这种时候应该怎么办才好？妈妈们以前教过什么？是什么......到底是什么......！

「有人吗！有人在吗！我们遇到绑架犯了！请救救我们！」

亚尔斯大声呼救。

若是发生了什么事，与其一战不如先寻求帮助。这是蓝妈妈的教诲，还是白妈妈的？或许是爱夏的？不，说不定是爸爸说的。

「再怎么哭喊也没用，这里不会有人来的。」

亚尔斯认为这也是当然的，同时回忆起下一条教诲。

他想到了红妈妈说的话。

「首先，要好好观察敌人。」

亚尔斯摆好架势，冷静地观察四周。他们被困在一条死路，前面有一人，后面有两人，所有人身上都配有剑。不过，这些人和红妈妈比起来要弱得多。

没有霸气，也没有杀气，这种水准在夏利亚随处可见。

若是面对红妈妈，这些杂碎恐怕早就被吓得屁滚尿流。

亚尔斯手中只有一根敲下去就会立刻折断的木棍，但他曾学过徒手战斗，也会运用一些魔术。只要依照练习时的方式应对，一定可以赢。

一定，应该，不要紧，大概。

「亚尔哥......你要战斗吗？我......我也......要......要......要战斗......」

「齐格，你退后！」

明明这样做出了判断，亚尔斯的膝盖依然在发抖。他紧握木棍的手颤抖不止，呼吸急促，眼眶几乎泛起泪水。在这漆黑的夜里，不仅要与三个成年男子战斗，而且还要保护姐姐和弟弟，这样的沉重压力对他来说还是第一次的体验。

「哟～哟～你这个当哥哥的还挺勇敢的嘛。不过，反抗也是没用的，这些人虽然是落魄的冒险者，但还是有两把刷子喔。」

「闭嘴！不准你们碰齐格和菈菈姐！」

「......唉，你们几个，别把他们伤得太重。他们应该是有钱人家的小鬼，肯定能换一大笔赎金。」

背后的两人应了一声，开始行动。

亚尔斯感到仿佛胃部抽痛的不适感，但他还是将所有魔力聚集到拳头，准备给对方杀个措手不及──

\\

啪。啪。啪。

\\

突然传出的声响，打破了沉默。

那是拍手的声音。声音来自包围他们的两个男人身后，让在场的所有人都停下了动作。

同时，一道白色的身影越过两个男人，落在亚尔斯的面前。

白色的身影绕着亚尔斯他们转了一圈，还特地在菈菈身上闻了闻味道，确认她是否受伤，随后再转向男人们，露出锋利的牙齿。

「嘎噜噜噜噜......」

「雷欧！」

那是雷欧。

然而，拍手的恐怕并不是它。毕竟它没有手能够这么做。

「好了好了～到此为止～」

那是亚尔斯非常熟悉的声音。

从早晨睁眼到晚上入睡，这是他每天都会听到的熟悉声音。

接着，那名有着深色褐发、可爱虎牙的熟悉女性从暗处现身。

她穿着女仆装，胸前曲线丰满，手里提着一盏粗犷的提灯。

「爱夏姐！」

亚尔斯大声呼喊出那人的名字。

她不是姐姐。虽然并非真正的姐姐，但如果叫她「阿姨」，她可是会生气的。

「嗨嗨～亚尔斯弟弟，我来救你们喽。」

眼见爱夏露出灿烂的笑容，亚尔斯几乎快哭出来了。

不过，感到安心的并不只有亚尔斯一行人。看到从暗处走出的只是一名女仆和一只大狗，男人们依然保持着强硬的态度。

「你这家伙，是哪里的女仆......」

「格雷拉特家的喔。啊，在这一带的话说拉托雷亚家可能比较好吧。就是那位担任神殿骑士团大队长的卡莱尔•拉托雷亚的那个拉托雷亚家，你们应该听说过吧？」

神殿骑士团。听到这个名字，男人们顿时一阵慌乱。

他们或许对贵族的名字不是那么清楚，但好歹也对神殿骑士团有所耳闻。那是一群以狂信徒着称的米里斯教团私兵。

「我劝你们放弃绑架这些孩子去要求赎金喔。否则下场可是会很惨的。」

「要......要是怕什么神殿骑士，哪还能当绑架犯啊！」

他们心里并非没有感到害怕。

关于神殿骑士逮住异端者时会如何拷问，坊间曾有过这样的传闻。

据说他们会将犯人的四肢绑住，然后用锤子从脚尖开始一点点地敲碎。

如果这种行为只是基于嗜虐的心理，倒也并非无法理解。

但他们打从心底相信这是一种善行，会在对方的脚被打烂、痛苦尖叫时由衷地露出微笑说：「您发自内心的求救，神一定会听见的。换句话说，您可以返回神的怀抱了，真是太好了呢。」

尽管这些传闻是空穴来风，但这些男人确实相信这件事。

「如果不怕神殿骑士的话......那么，鲁德佣兵团呢？他们可是会在超美丽会计顾问的指挥下，将你们追杀到天涯海角，还会受到生不如死的对待喔。」

「为......为什么会提到鲁德佣兵团？」

「当然是因为鲁德佣兵团里面最伟大的人，就是这些孩子的爸爸啊。」

男人们顿时错愕不已，看向亚尔斯等人。

「哥......哦，鲁德佣兵团的会长鲁迪乌斯•格雷拉特。他是龙神奥尔斯帝德的左右手，是与各国都有交情的高强魔术师。平时性格温和，就算在宴会上被人泼酒也能一笑置之。但他对家人非常重视，若是知道自己的孩子被绑架了，你们觉得犯人会有什么下场呢......」

「......胡......胡说八道！」

「你真的这么认为吗？其实我已经开始懒得说服你们了。」

「哼，反正只要在这里解决你，结果也一样。」

「是吗？那么，雷欧，上吧。」

听到爱夏一声令下，那头白色巨兽犹如疾风般冲出。

首先，它咬住了眼前那名朝着自己方向的男人的腿，猛然甩头。

男人的腿随着「喀嚓」声应声断裂。随后雷欧松开了嘴，男人飞上半空，撞上了墙壁。

另一名男人听到声音回头时，已经太迟了。

他甚至来不及拔出腰间的剑，手臂就被咬住了。正当他听到「喀嚓」一声，就随即被拉倒在地。他的脸遭到雷欧咬住，高高举起，随后被狠狠地甩来甩去，直接昏了过去，然后一样撞上了墙壁。

「咿......！」

最后，那名女职员也无路可逃。

她试图爬上巷弄尽头的墙壁逃跑，却被雷欧咬住臀部，和其他两人一样被甩来甩去，最后撞上墙壁昏厥过去。

「......」

亚尔斯哑然地看着整个过程。

他知道雷欧的实力了得，也大概能理解爸爸和妈妈为什么总是叮嘱他要和雷欧在一起。

但这是他第一次亲眼见识到它的厉害。

而且，他发现雷欧刚才似乎还手下留情。要是有那种力量，应该也能轻易咬碎对方的脸或脖子。

但它并没有那么做。

它只是像在轻咬那样咬住对方，再用甩的让他们骨折，最后砸到墙上让其昏迷而已。

就这样轻易解决了亚尔斯感到害怕的对手。

「大家都没事吧？没有受伤吧？」

爱夏根本没看那些已经昏迷的人一眼，而是像什么都没发生过似的蹲在亚尔斯他们面前，举着提灯仔细检查三人的身体。

「没......没有，我们没事。」

「是吗？那我们回去吧。」

爱夏对困惑地点头的亚尔斯露出虎牙，莞尔一笑。

\\

在一片黑暗的路上。

三人骑在雷欧背上，跟着爱夏手上提灯的微光踏上了归途。

那些绑架犯已经被爱夏使用犬笛叫来不知从哪里现身的鲁德佣兵团团员带走，听说会直接交给当局处理。

亚尔斯走在回去的路上，一直在想自己肯定会被骂。

为什么要擅自跑出去？为什么还把菈菈和齐格也牵扯进去？

爱夏平常很少生气。

就算亚尔斯做了多么顽皮的事情，甚至给别人添麻烦也不会生气。

她也只会说一句「真拿你没办法」就帮他擦屁股。事后还温柔地教训他「不可以再这样喽，要从错误中学习喔」。

但这次如果再迟一步，事情可能会无法挽回。

而且，这样的行为根本不把总是照顾他的爱夏放在眼里。爱夏虽然还是来找他们，但她肯定已经被爸爸和妈妈骂过了吧。

明明当爸爸和妈妈不在时是她要负责照顾他们，她却没有看好。

被自己看管的对象悄悄溜走，还因此遭到责备，就算是温和的爱夏，恐怕也会心生不满。

亚尔斯虽然没有明确地想到这些，但还是隐隐约约地推测出爱夏现在应该在生气。

「爱夏姐......对不起。」

因此，亚尔斯向她道歉。

「嗯？为什么道歉？」

「我......没有告诉爱夏姐就偷偷跑出来，还让大家陷入危险......」

「咦～？你在说什么啊？」

然而，爱夏却是笑了笑，摸着亚尔斯的头。

从她的举动中，完全感受不到丝毫生气的迹象。亚尔斯不禁疑惑，爱夏是原谅他了吗？但为什么呢？

「看，我们到了喔。」

「......！」

听到爱夏这样说，亚尔斯才发现自己已经站在拉托雷亚家的门前。

望着眼前的豪宅，亚尔斯不由得咽了口口水。

爱夏或许是原谅了他，但妈妈们肯定会发脾气。妈妈们一直教导他们要保护自己的兄弟姐妹，而这次他显然辜负了她们。至少，自己还是该先做好被红妈妈打屁股的心理准备。

说不定就连爸爸也会生气。虽然很难想像爸爸生气的样子就是了。

「门卫，辛苦了。」

跟随着爱夏，亚尔斯等人从后门进入了家中。

他们穿过屋内宽敞的走廊，来到家人应该待着的房间，轻轻推开了门。

家人就在那里。

三位妈妈、两位祖母、一位金发的姑姑、面容稍显严肃的曾祖母，还有爸爸。

「我们回来了。」

爱夏低头行礼后，所有人将目光转向亚尔斯他们。

他们肯定是怒发冲冠，亚尔斯心想，最先生气的一定是红妈妈。因为红妈妈总是第一个发火的人。

「哎呀，欢迎回来。你们回来得真晚呢。」

然而，红妈妈的语气却一派轻松。

「冒险者公会好玩吗？」

蓝妈妈的嗓音也是那么温和。

「不过，下次不能这么晚还在外溜达喔。就算有爱夏和雷欧陪着，夜晚还是很危险的。」

「说得没错。爱夏，就算有你陪在身边，也不能让他们这么晚还在外面闲晃。你就不能让他们早点回来吗？」

白妈妈和莉莉雅的语气虽然稍稍严厉了一些，但并没有真的在生气。

诺伦和克蕾雅虽然一句话也没说，但她们以视线表示赞同。

「没关系啦，虽然晚了点，但反正晚餐也还没吃，就算了吧。比起这个，你们有看到什么有趣的东西吗？」

爸爸一如既往地好说话。

「......」

塞妮丝奶奶像平常那样不发一语，但也感觉不到责备的意思。

虽然塞妮丝奶奶看起来那样，但真的生气的时候还是能隐隐约约感觉得到。

「呃......」

亚尔斯无法理解眼前的状况，不晓得该如何回答。

在短暂的沉默之后。

「冒险者公会的集团室里，挂着一个龙的头。」

菈菈轻声说道。从她的表情来看，她似乎已经知道了答案。

或许是在亚尔斯不知情的时候，从雷欧那里听来的吧。

「啊，爸爸，我跟你说，冒险者公会里有魔剑喔！」

随后，齐格露出兴高采烈的表情开始讲述冒险者公会的见闻。

看来，他已经完全把刚才遇上的危机抛到了脑后。

「好了好了，待会儿再说吧。先去叫露西她们过来，准备吃饭吧。」

于是，气氛变得一片和乐，大家开始享用晚餐。

\\

★　★　★

\\

晚餐结束后，亚尔斯离开了宽敞的餐厅。

朝分配给自己的房间走去。他转头望向理所当然地跟在自己身后的爱夏。

「为什么？」

亚尔斯一开口便这样问。

为什么没人责骂他？为什么大家都知道他们去了冒险者公会......这个「为什么」包含了许多含义。

听到这个提问，爱夏的嘴角微微上扬。

「想知道吗？」

「嗯。」

看到爱夏的表情犹如恶作剧得逞那般，亚尔斯认真地点了点头。

「因为我在大圣堂的中庭看到你们偷偷摸摸地溜出去啊。我想说你们大概是真的太无聊了，打算要搞点恶作剧，我就跟大家说我要带你们去冒险者公会看看，然后就追上去了。」

亚尔斯听后，恍然大悟。

原来爱夏早就看穿了一切。而且她没有和亚尔斯他们会合，而是选择放任他们自由行动。

她只是跟在后面，并打算一旦发生什么事就及时出面解决。

「不过，我倒是没想到你们会跑到魔术塔呢。」

她一直在背后默默地守护。就算在他们迷路、差点哭出来时，她也没有伸出援手......

「......那为什么......在那个时候，在发现我们迷路的时候，你却不愿意帮我们啊？」

「嗯～？这种事亚尔斯弟弟应该自己知道吧？」

爱夏以开玩笑的口吻说道。亚尔斯闻言，不禁咬紧牙关。

当然，亚尔斯自己也明白。

陷入那种情况，都要归咎于他自己。

妈妈也曾经教过他，若是因为自己做了什么而陷入困境，就应该靠自己努力解决。

事实上，在察觉到迷路的那个瞬间，亚尔斯并没有放弃。

他绞尽脑汁，试图找到解决办法。当时，一切还没有结束。

所以，爱夏只是在旁边观察，认为还没到需要出面的时候。

最终当局势演变到可能受伤的状况时，爱夏才现身解危。

由于亚尔斯做出了错误的选择，让三人陷入险境，她才总算挺身而出。

假如那名女性职员只是好心地帮他们带路，而非绑架犯的同伙，爱夏想必直到最后都不会现身吧。

不应该责怪爱夏。一切都是自己不好。

爱夏只是像以前那样在帮他收拾烂摊子罢了。

「......爱夏姐......对不起。」

「光说对不起可不行喔，亚尔斯弟弟。你觉得自己到底错在哪里呢？」

「因为我没告诉爱夏姐，就偷偷溜出去......」

「嗯～不太对喔。」

听到爱夏否定，亚尔斯惊讶地回过头。

这很少见。因为爱夏几乎不会规劝亚尔斯的行为。

即使亚尔斯犯了错，她也只会说句「真拿你没办法」帮他擦屁股，不会针对这件事多说什么。

但爱夏低头看着回头的亚尔斯，脸上一如往常露出了那个绰有余裕的微笑。

「亚尔斯弟弟是因为觉得我很烦，才想要只和其他孩子偷偷跑出去吧？」

「我......我才没有觉得......烦。只是有一点点......啊，可是，我还是很喜欢爱夏姐喔。」

「是吗？嗯哼哼，谢谢你喔，被亚尔斯弟弟说喜欢，真是令人害羞呢～」

爱夏把手贴在脸颊，故意扭了扭身子。

「总之，亚尔斯弟弟想避开我的视线，偷偷跑去冒险者公会和魔术塔看看，对吧？」

「嗯。」

「那么，你就该这么做。」

「咦？可是......这样会让大家担心的......」

「当然，不可以让大家担心呢。」

「嗯。」

「不过啊，亚尔斯弟弟一开始也没打算让大家担心吧？毕竟你不是那种坏孩子嘛？」

亚尔斯点了点头。

关于这点，他的确有点欠缺考虑，但他的目的并不是要让大家担心。

「你本来是打算去冒险者公会和魔术塔看看，回来之后，当我问你『去哪里了？』，你也会装作什么事都没有一样和菈菈还有齐格对望，笑着回答说『秘密』。对吧？」

正如爱夏所说的。

虽说他没有明确做出规划，但听爱夏这样描述之后，亚尔斯发现那确实是他的理想构图。

偷偷跑出去玩，在外面享受一下，趁大家还没担心之前回来。

爱夏或许会因为他们离开自己的视线而稍微担心一下，但只要很快回来，她应该也会松一口气，想说「原来这么近啊」。

「你错的地方在于，没有做到这点。」

爱夏直截了当地说道。

亚尔斯有自己的目标。

不带上爱夏、或是其他闲杂人等，自己前往冒险者公会。

姑且不论他为什么后来又带着姐姐与弟弟一起同行，总之当亚尔斯有这个念头时，就产生了一个目标。

而爱夏所说的是，既然有了目标，就应该努力达成。

「......虽然你这么说......但如果是爱夏姐的话会怎么做？」

「嗯──老实说就算是我，也很难在那么短的时间内同时去冒险者公会和魔术塔，因为距离实在太远了嘛。所以我会今天只去冒险者公会，魔术塔应该就留到下次再去。是说，你也根本不知道时间不够吧？所以我会在前一天就先打听好行程，然后制定一个完善的作战计划。」

「啊，是这样啊......」

「再来，我会携带武器，也会带上可以和人联络的道具吧。有时候光靠自己一个人是无能为力的，所以需要在危急关头向别人求助。」

爱夏说得很具体，亚尔斯听完，终于理解到底错在哪里。

他冷静回想，发现自己确实过于冒失。

太过莽撞，想得不够周全，会导致自己陷入那样的困境也是当然的。

同时，亚尔斯也不禁心想，爱夏果然很厉害。

「......我知道了。下次我一定会更谨慎，避免再犯错。」

「嗯嗯，这想法不错呢。不过，你可别因为太过谨慎而害怕失败喔。这样的话会真的什么都不敢做的。所以你要多多尝试，多多失败！」

「咦？可是，万一又变成像今天这样......」

「没关系！就算失败了，我也会像今天这样帮你收拾残局！亚尔斯弟弟不用害怕，尽管去挑战各种事情吧！」

爱夏用力拍了拍自己的胸口这样说道。

亚尔斯感到一阵莫名的害羞，但还是对爱夏露出了微笑。

「嗯，我知道了，爱夏姐！谢谢你！」

「不客气～！哎呀～亚尔斯弟弟真是又坦率又可爱呢──！」

爱夏收到自己想听到的话，将亚尔斯抱入怀中。

亚尔斯被柔软的胸部包裹着，感受着爱夏用力揉着他的头，同时在脑海强烈反省今天发生的事。

*** 「洛琪希与使命」

那天，我坐在庭院的椅子上看书。

在眼睛的余光中，可以看到艾莉丝和齐格正在练习挥剑。

都出门旅行了，其实不用那么做也可以的。

亚尔斯直到刚才还在一起练剑，但被鲁迪的阿姨特蕾兹叫走后，就不知道跑去哪里了。现在说不定正在房间里吃着点心吧。

这样是没什么关系，但那孩子在面对胸部丰满的女性时，总是会露出一副色咪咪的样子。将来恐怕会在女性问题上吃不少苦头。

至于菈菈，她从刚才开始就和雷欧在庭院里四处闲晃。

大概又在策划什么新花样了吧。

毕竟最近那孩子老是做出一些会让人头疼的行为......

不过，只要亚尔斯、齐格和菈菈这三人能老老实实待在家里，今天应该就不会发生什么大问题。

希露菲和诺伦带着露西和克莱夫去参观冒险者公会。

她们本来邀请我一起去，但我婉拒了。毕竟我可不想在孩子们面前听到那些年轻的冒险者说「为什么你们要邀请年纪相仿的人组队啊？」这样的话。

再说，魔族在米里希昂四处溜达，难免会引来异样的目光。

不过，有一部分是因为我想照顾莉莉和克莉丝就是了......

现在，莉莉和克莉丝已经午睡了，手边没事的我终于得以享受久违的悠闲时光，沉浸于阅读之中。

幸运的是，拉托雷亚家的书库里有不少有趣的书籍。今天我拿到了一本《神击魔术的起源》。其中关于死灵魔术的描述让我特别感兴趣。

「在人魔大战期间，魔族曾使用某种魔术来折磨米里斯的人类。

其名为死灵魔术。这是一种复活死者，并加以操控的魔术。这种禁术至今仍以骷髅兵、幽魂与会动的铠甲那类魔物残留下来。

神击魔术正是为了对抗死灵魔术而诞生的。在第一次人魔大战中期，人族的神击魔术与魔族的死灵魔术发展成一种剪不断、理还乱的竞争关系。

而在战争结束后，死灵魔术被列为禁术而失传，而神击魔术虽然逐渐衰退，但依然流传至今。」

这本书没有详细记载魔法阵与咏唱咒语，也不打算尝试死灵魔术，但读起来却莫名地激起了我的好奇心。

遥远古代的魔术大战，真是浪漫呢......

「......洛琪希大人。」

「是？」

背后传来呼唤声，我将视线移开书本、抬起头，发现拉托雷亚家的女仆站在身后。

有股不祥的预感。

「夫人......克蕾雅大人请您过去一趟。」

克蕾雅•拉托雷亚。

虽然年纪可能和我差不多，但名义上算是我的义祖母......

目前为止，她没有对我显露过任何不悦，但考虑到她属于排斥魔族派系，我不认为她会对我有好脸色。

不知道会被说些什么，说实话，我很想逃避......

我这样心想，瞥向艾莉丝一眼。

「好了，手臂再收紧点！下巴再往回缩！」

她今天也热心地指导着剑术。如果克蕾雅真的只是要针对我是魔族这点说教，其实倒也还好，但如果不是......比方说要谈孩子们的教育方针的话，之后也有可能会叫艾莉丝过去。

艾莉丝没办法谈论复杂的对话，也无法委婉地表达自己的想法。若是有人对她说闲话，会直接挥拳反击。

她的个性就是这样。

她或许能强硬地回应克蕾雅，但这样很有可能演变成争执。

「我明白了。」

或许，这也是作为鲁迪妻子的责任吧。

\\

★　★　★

\\

虽然下定决心了，可是......

「......」

目前为止，房间的主人克蕾雅只是静静地喝着红茶，而我只是坐在她面前，连一句话也说不出口。不知为何，莉莉雅与塞妮丝也在房间。莉莉雅的内心状态和我相同。

塞妮丝倒是老样子就是了......

老实说，这种氛围令人窒息。尽管茶水旁边放着我喜欢的点心，我也不敢伸手去拿，总觉得如果拿了就会被说些什么。比方说「这样晚饭会吃不下的」之类的......不对，这是我经常对菈菈说的话。

克蕾雅会把我和莉莉雅同时叫来，肯定不是偶然。

我和莉莉雅各自嫁给不同的丈夫，尽管彼此都有身为妻子的立场，但就算以妾室称呼也不为过。

在米里斯教中，妾室的存在是不被允许的。

不过，我早有觉悟。

尽管最近对此稍有放松，但我随时都有应对苛刻言词的心理准备。

「......」

我这样心想，将视线投向莉莉雅，恰好与她对上了目光。

看来莉莉雅的想法与我一致。或者说，她比我在更早之前就做好了这样的觉悟。不管怎么说，艾莉丝没有被叫来这里，已经算是不幸中的大幸了吧。毕竟我实在不认为她能在这样的场合中全身而退。

「鲁迪乌斯先生似乎出门了呢。」

克蕾雅终于开口，这是她自我进入房间以来的第一句话。

「他去克里夫先生那里送礼。」

「也就是说，是工作吗？在与家人一起度假的期间，竟然还要忙于公务......这种地方真是和卡莱尔一个样呢。」

今天一大早，鲁迪就与艾莉娜丽洁一起带着「那个人偶」前往克里夫的住处。不过，我不确定这算不算工作......

那个人偶是为了照顾克里夫而制作的自动人偶。

尽管鲁迪跟我说明过安的状况，我也对她没有什么特别的意见，但这次新制作的人偶让我感到有些不舒服。

因为那人偶的外貌与艾莉娜丽洁几乎一模一样，连动作和语气也极为相似，只有耳朵稍短而已。

外貌好像是由艾莉娜丽洁亲自提议的。听说最近克里夫的地位提升，越来越受女性欢迎，甚至有各方人士劝他结婚。所以把艾莉娜丽洁人偶放在他身边也可以用来赶走烂桃花。

此外，这样做还有一个目的，就是若克里夫与这样的女性结婚，可以在不透露对方是长耳族的前提下，逐步让周围的人接受这段婚姻。

艾莉娜丽洁甚至花了好几个月的时间亲自教导人偶模仿自己的言行举止。

不过，我猜她内心可能设想着其他用途。

毕竟她曾因为没有某种必要的东西而颇有微词。

虽然细节上不完全相同，但乍看之下实在是极为相似，甚至让人感到不舒服。鲁迪以前也制作过我的人偶，但如果是能动的那种，我是绝对无法接受的。若他来征求我的同意，我应该会果断拒绝。就算是鲁迪，也不可能未经允许就制作这样的东西吧。

再说，我本人就已经在他身边了，只要直接找我就行了。

虽然我不像希露菲那样百依百顺，但只要鲁迪开口，除非是太过分的请求，我通常都不会拒绝。当然，我是希望他不要提什么太变态的事情。

不过话又说回来，我与克里夫并没有那么熟识，虔诚的米里斯教徒看到那种东西真的会开心吗？

鲁迪说这礼物是个惊喜，但反而会惹他生气吧？

话虽如此，这也并非我该插手的问题。

「我想应该算不上工作吧。毕竟克里夫与他关系匪浅。」

「是吗？如果是我的话，除非是什么见不得人的东西，否则我肯定会让家里的仆人代为送去。也许这就是常识的不同吧。」

不，那东西确实不适合随便见人。

如果鲁迪和艾莉娜丽洁没有加以说明，克里夫肯定不会收下那个人偶吧。

「对了，莉莉雅小姐，今天爱夏在做什么呢？」

「爱夏今天一早去佣兵团露脸，听说下午就会回来。」

爱夏正待在佣兵团那边。

不过，她是在听到「亚尔斯今天会一直待在家里」之后才突然决定的。

她大概是不想待在这个家吧。回想起来，诺伦在得知希露菲要和露西她们出门时，似乎也同样临时起意一起过去。

当然，诺伦或许有部分是因为露西央求她一起去。

「那些孩子，似乎不太喜欢这个家呢。」

克蕾雅哼了一声，抿了一口红茶，但或许是对味道不满意，她皱起了眉头，就这样面露难色，将视线投向莉莉雅。

「莉莉雅小姐，以前你来这里时，我对你说了一些刻薄的话。」

「......不，完全没有那回事。」

「我想为那时的事情向你道歉。当时，有个声称是塞妮丝丈夫，来历不明的男人向我们家寻求援助，后来，我以为他找到了塞妮丝，结果又出现了一位自称是他另一位妻子的女人，还带着女儿一起出现在我面前，我当时确实很不愉快。」

「您的心情我能理解，真的不必在意。」

「不过，爱夏倒是一直惦记着这件事。」

这个剑拔弩张的气氛是怎么回事？感觉胃都开始隐隐作痛了。

「我的担忧并未成真，你对格雷拉特家非常尽心尽力。塞妮丝成了现在这样，你本来可以借此拥有更大的话语权，却选择退居幕后，专心照顾塞妮丝。」

「......您过奖了。我并没有什么强大的话语权。」

「那只是你这么认为而已。昨天，我透过神子听到了塞妮丝的心声。也因此明白，格雷拉特家中的每个人都感谢着你。」

「......」

确实如此。鲁迪或许没有特别意识到这件事，但他将莉莉雅视为与塞妮丝地位相当的存在。

塞妮丝与她并没有上下之分。

话虽如此，塞妮丝如今无法正常表达意见。要是莉莉雅有那个意思，她或许也可以不当女仆，晋升为一位正式的「母亲」。这样一来，也许我们家的环境就不会像现在这样舒服，塞妮丝的待遇也可能会与现在有异。

正是因为莉莉雅没有逾越本分，选择在幕后默默支持，才会有现在的格雷拉特家。

听到克蕾雅这么说，我才觉得确实是这样。

「洛琪希小姐，你也是。」

「咦？」

听到自己的名字被突然提及，我忍不住抬起头。克蕾雅的目光并未看向我，而是注视着她自己的手和塞妮丝。然而，她的视线又开始移动，转向窗外。

「这几天，我观察了那几个孩子。每个人都很健康又充满活力。菈菈虽然有些淘气，但个性并没有扭曲。」

「......请问，菈菈该不会做了什么？」

「昨天早上，她送了一只青蛙给我当礼物。」

我顿时感到一阵晕眩。那孩子到底在搞什么啊？

「呃......那个，非常抱歉，我不知道该如何道歉才好。」

「不用道歉。我已经在下午茶时，让人将那只青蛙烤熟后作为点心回礼了。」

我的头又再次感到晕眩。听她这么一说，昨天下午菈菈确实在吃某种像是串烧的东西。

我问她吃的是什么，她只回答「秘密」......

「当然，那经过我们家的厨师专业调理。我自己不常吃，但这一带有不少以青蛙为食材的料理。」

在雨水丰沛的米里斯大陆，青蛙或蜥蜴料理相当常见。

我曾经是名冒险者，当然也经常享用这类料理。在还不会使用解毒魔术的时候，甚至曾因误食毒蛙而差点丧命......不过既然是厨师确认过后判断没问题的食材，应该不用担心菈菈会吃到毒蛙吧。

然而，这着实教人意外。

根据鲁迪的描述，我以为她是一个不苟言笑，不会做这种事情的人。

「今天早上，菈菈还说『昨天的点心非常好吃，我一定会回礼的』。虽然不清楚她打算怎么回礼就是了......」

这是在责备我吗？

克蕾雅的语气仍旧尖锐，脸上丝毫看不出笑意。

这应该是在责备我没错吧。

「呼......」

这时，克蕾雅叹了一口气，看来她终于要切入正题了。

「我不晓得你们为什么这么紧张，但鲁迪乌斯先生已经对我耳提面命，不要干涉你们的家庭事务。尽管有很多话想说，但我会遵守约定。」

用这种严厉的语气训斥，听起来没什么说服力啊......

「今天请你们来，是因为你们与其他人相比更为稳重。希露菲叶特小姐还很年轻，艾莉丝小姐则略显幼稚。我不晓得塞妮丝在变成这样之前是什么样子，但她如今无法照顾他人。就我的观察，你们两位能够以退为进，观察大局。所以......咳、咳......」

说到一半，克蕾雅突然咳嗽起来。几名女仆看到这幕慌忙跑向她。

我也站起身，打算靠近施展解毒魔术，但克蕾雅示意自己没事制止了女仆们，然后端起红茶一饮而尽。

「没事的，只是稍微呛到......哎呀？」

克蕾雅的视线移向了塞妮丝。

直到刚才还呆望着虚空，无视周围谈话的塞妮丝。

现在没有依赖莉莉雅的帮助，就自己站了起来，以空洞的眼神看向克蕾雅。

「您还是休息一下比较好吧？」

说出这句话的是莉莉雅，但听起来却像是从塞妮丝口中说出的。

「......受不了，我只是稍微呛到而已，真是大惊小怪。每个人看到我拄着拐杖都一副惊讶的表情......我虽然腰不好，但没有连胸腔的状况都变糟。塞妮丝，你也别摆出那种表情，坐下吧。」

那种表情？听到这句话，我再次看向塞妮丝的脸，她的表情依旧很茫然。

当我疑惑地转头看向克蕾雅时，她也显得很惊讶。

总之，我默默回到自己的座位。

塞妮丝也由莉莉雅牵着手重新坐回椅子上。

「......」

房间里一时陷入了沉默。克蕾雅脸上的惊愕逐渐消退，但内心似乎没有那么快平复。

「......第一次进入社交圈......」

克蕾雅低声开口。

「那是塞妮丝第一次参加贵族的宴会时，我在回程的路上从楼梯上失足摔了一跤。」

她的语气带着些许怀念。

不知不觉间，克蕾雅的视线渐渐下垂......她低下头，声音中开始混杂着轻微的呜咽。

「伤势并不严重，很快就用治愈魔术治好了......但不知为何，我感觉刚才好像看到了塞妮丝当时的表情。」

克蕾雅低着头，有某样东西一滴一滴地从脸颊滑落。

她拿起放在旁边的手帕轻轻擦拭眼角。

「塞妮丝曾是个备受赞誉、让人骄傲的孩子。我从来不觉得......自己的教育方式......出了问题......」

看着克蕾雅的肩膀微微颤抖，我却不知该说些什么，只是静静地注视着她。

「......」

我突然冒出一个念头。

自己是否曾经认真考虑过孩子们的未来。

自与鲁迪结婚，生下菈菈、生下了莉莉后，我就将孩子们交给家人照顾，自己则在魔法大学专注于教职。

在家里，有希露菲和莉莉雅负责照顾孩子们，而我则是照顾那些进入学校的孩子们。

这样的生活很充实。

对于孩子的教育方式，我从未怀疑过。

关于菈菈，自己生的女儿跟露西相比显得既不认真又喜欢恶作剧，这一点曾让我有些烦恼。我也曾思考过是不是因为我是魔族，或者是因为她是人族与魔族的混血才会这样。

但是，在我多年来烦恼着这些事情的时候，菈菈也渐渐长大了。

她在孩子们中间并不会显得格格不入，与亚尔斯、齐格也处得很好。等她再长大一些，肯定会更加稳重吧。我是这么认为的。毕竟我自己就是这样......应该是吧？

不过，我没什么考虑过更远的未来。

菈菈似乎身负救世主的重责大任，但我现在还是不晓得她具体来说需要做些什么。她可能会参与对抗人神的战斗，但在那之后呢？

没错，战斗结束后，人生依然会继续走下去。

老实说，我也明白现在烦恼这种事或许是没意义的，但是......

「抱歉，刚刚有些失态了。」

「不会。」

「到了这把年纪，泪腺就变脆弱了呢。」

克蕾雅的眼睛微红，将手帕放回桌上。

她昨天在大圣堂聆听神子扮演塞妮丝说话的时候，也忍不住流下了眼泪。

「嗯咳。在这个米里斯神圣国，有句话是这么说的：『扭曲的家庭会教育出扭曲的孩子』。我也对这句话深感认同。」

克蕾雅这样说着，用锐利的视线看着我们。

「你们格雷拉特家的孩子们看起来很健康，没有任何扭曲的迹象。塞妮丝当年也绝非那种孩子。不过，今后你们必须千万注意。因为孩子们若是出现异常，第一个察觉的，应该是像你们这样退一步观察全局的人。」

异常。就像当年塞妮丝出奔时那样的异常。

确实有这个可能性。尤其是菈菈。我根本不晓得她在想什么。

不对，或许并不是菈菈，看似顺利成长的孩子更有这个可能，比方说露西就很危险吗？她在学校表现得像个优等生，可是......

我能够察觉那些异常吗？

呜......一受到期待，胃好像就开始痛了。

「今天叫你们来，就是为了说这件事。」

克蕾雅说完后，将身体深深靠向椅背。

我与莉莉雅对视了一眼。

与正感到困惑的我相反，莉莉雅像是下定决心那般，看着克蕾雅。

「我明白了，请交给我。」

那态度仿佛接受了重大任务的军人。

她之所以能这么说，或许是因为养育了诺伦和爱夏给她带来了自信。

哦，还有鲁迪也是。

「我也会尽力而为。」

我也这样说道。

老实说，我并没有自信。尽管我作为教师见过各式各样的人，但现在也不认为自己适合教导他人。不过，如果是无法融入希露菲与艾莉丝教育框架的那些孩子，我应该能为他们提供新的选择。如果是这样的话我一定能做到。

我必须这么做。

不仅如此。克蕾雅明明内心有些想法，却依然以平等的态度看待我。

她属于排斥魔族派系，对于我这样的人，应该多少有些想法才对。然而，她仍然对身为魔族的我说出了这些话。正因如此，让我更想回应她的期待。

「嗯？」

这时，房间的门被推开。

一只白色的大狗慢悠悠地走了进来，而坐在它的背上当然是菈菈。

菈菈现在不知为何浑身泥泞。就连鞋子和衣服也不例外。

明明我一再提醒她进家里之前要先把鞋上的泥清理干净......

「菈菈，在屋子里不要骑雷欧，下来吧。」

我想说至少跟她说一声，菈菈听了后露出不耐烦的表情，从雷欧身上跳了下来。

在学校，她也经常趁人不注意时这么做，让人忍不住想叹气。

随后，菈菈缓缓地走向克蕾雅。

「曾祖母，我找到了好东西。」

「是什么？」

「这个。」

菈菈从口袋里掏出来的，是一个圆形的金色物品。从我这个位置看不太清楚，大概是某种吊坠吧。

克蕾雅看到那东西后，顿时瞪大双眼。

「这是在哪里找到的？」

「掉在庭院。曾祖母在找这个对吧？」

「对，我一直在找......可是，你怎么知道？」

「昨天奶奶说的。说你以前总是戴着它，肯定是一直去找它掉在哪里，才会把腰弄坏的。」

菈菈在说着这些话的同时看着塞妮丝。

\\

前几天用神子的力量重现塞妮丝的内心话时没提到这件事......可能是菈菈今天早上或昨天自己去问的吧。

「所以你才去帮我找出来？」

「是昨天点心的谢礼。」

「......」

「虽然那个也很好吃，不过，我比较喜欢吃这个点心。」

菈菈说着，把视线转向桌上。

上面摆着红茶的茶点。

「你可以吃喔。」

「我开动了。」

菈菈伸手抓起茶点，放入口中，毫不犹豫地一个接着一个，转眼间就把桌上的东西一扫而空了。我才正准备要提醒她至少先洗个手的......

「啊。」

我的份也被她吃了。

「......」

算了，无所谓。反正现在只要拜托鲁迪，随时都能吃到甜的东西......

我不会因为食物被小孩子拿走就生气的。不过，那是我的点心......

「嗯呼～」

菈菈鼓着双颊，满足地眯起眼睛咀嚼，然后一口吞了下去。

雷欧一脸愕然地看着她，仿佛在问「我的呢？」

我想我的表情大概也跟雷欧差不多吧。

「果然比青蛙好吃。」

「那么，明天再让你吃一些吧。」

「好期待。」

菈菈说完，迅速跳上雷欧的背，骑着它离开了房间。

我不禁傻眼，甚至忘了提醒她不能在室内骑雷欧，只是目送她这样离去。

「那......那个......对不起，那孩子实在不太懂礼貌。」

我急忙向克蕾雅道歉，但她只是目不转睛地盯着菈菈带来的东西。

我凑近看了一眼，才知道那是一个金制的怀表，里面放着一位年轻男子的肖像画。

「这个......是卡莱尔在我们结婚前送给我的。」

「......」

「这对当时的卡莱尔来说是件非常昂贵的东西，但他说『结婚之后，我将成为拉托雷亚家的一员。到时我就不能用自己的钱单独送你东西了』，便硬着头皮买下了这件礼物。」

克蕾雅的语气透着一丝怀念。

「大约一年前弄丢后，我一直弯着腰到处寻找，最后甚至把腰弄坏了，只好放弃......」

连女仆们都对这件事非常惊讶。

说不定克蕾雅甚至没有把这件事告诉家里的人。

「洛琪希小姐。」

「是。」

「回礼代表的是关心对方的态度，不需要拘泥于形式呢。」

「......呃。」

「菈菈是个懂得礼数的好孩子，我以前似乎对她有些误解。」

不，菈菈应该不是那么懂事的孩子......应该不是。不过也很难说呢。

不过，如果要说的话，我自己在这之前也误解过克蕾雅这个人。

鲁迪提到她会面露难色，爱夏甚至明显表露出厌恶。因此我对她心存戒心，不过现在觉得......

说不定，她也是在见过鲁迪后才有所改变的。

毕竟鲁迪确实对许多人产生影响......

不管怎么样，我想自己应该可以与她和睦相处。

虽说她的人生可能已走进尾声，在这次相会后，或许不会有机会再见面......

「不可以让那孩子走上歪路喔。」

「好的。」

听到克蕾雅的叮嘱，我重重点头。

*** 「前往圣剑大道」

时间过得很快，十天的行程在转眼间就过去了。

第一天，我们前往大圣堂致意，将塞妮丝带去与神子见面，借由神子的能力聆听塞妮丝的心声。

克蕾雅也有一起过来，结果她在途中就忍不住泪流满面。

我也差点哭了出来，但听到塞妮丝依然过得很幸福，还是忍住了。

这段期间，我看到孩子们觉得无聊而让他们在外面等，但由于后来与教皇和神子的交谈甚欢，意外花了不少时间。

也可以说是因为神子自豪地讲述自己每天的锻炼，还用得意的表情炫耀自己变苗条了，导致对话一直迟迟无法结束......

果然，孩子们在外面似乎感到很无聊。听说爱夏因此带着亚尔斯、菈菈和齐格去了冒险者公会的总部参观。从他们回来得很晚，以及亚尔斯回家时那张表情来看，似乎在那边又发生了一些问题......不过，我想爱夏肯定已经妥善处理了吧。

至于被留下来的露西是否对他们的行为很不满呢？其实并没有那么一回事。

她似乎和留在大圣堂的克莱夫一起参观了大圣堂，对此感到很满意。

或许是因为她喜欢那里的庭园，不然就是克莱夫是个非常好的玩伴吧。

从露西没有详细说明的这点来看，我猜应该是后者。

虽然不清楚详情的话就会想打破沙锅问到底，但我决定忍住。

总之，希望克莱夫今后能一直保持这样诚实的态度。

第二天、第三天和第四天则是去到处拜访。

因为是「龙神麾下的鲁迪乌斯来到米里希昂」，所以要到每个地方去拜访一趟。

首先是教导骑士团的骑士团长，然后是拉托雷亚家的分家，也就是我那些舅舅、阿姨们，其中当然也包括特蕾兹。不过很遗憾，她至今仍然未婚。

后来结束与教皇的正式会面之后，他还帮我引见了米里斯王家的成员。

这次见到的是王位继承权排名第五的王子殿下。说是王子，其实就是个超过四十岁的大叔。更麻烦的是，他们还帮我安排在几天后谒见国王。

这是以龙神代理人身分去向国王问候。

据奥尔斯帝德所说：「和米里斯王家可以之后再建立关系。」但我事前就有问过，只是打个招呼是不成问题的。

明明是来休假，为什么会变成这样？虽然会这样觉得，但原本的目的就是让孩子们进行社会体验。

我自己本身倒是无所谓啦。

第五天，我去了克里夫那里，把那个人偶送给他。

当时克里夫也带来了一个好消息。这五年来他的工作成果得到了极高的评价，听说已经内定要升为主教了。

原本像克里夫这么年轻是无法成为主教的，但其中有些内情，这与他所负责的教区是个有些特殊的场所有关。

位于大森林的最南端。当我还在旅行时，这里只是一个无名的驿站城镇。

然而，这个地方在这十年人流增多，规模也日益壮大。

尽管这座城镇不隶属于任何国家或种族，但随着规模的扩大，自然也会牵扯到利益纠葛。为了调解这些利益，各种族的代表会齐聚在这个镇上，共同制定各式各样的规范。

米里斯教团派出的代表是一位被称作枢机卿心腹的大主教，属于排斥魔族派。

这个人是人族至上主义者，鄙视的不仅是魔族，连兽族之类的也瞧不起。但他聪明能干，必然能为教团争取不少利益。然而考虑到他的个性，也有可能导致教团与居住在大森林的种族之间的关系恶化。而且，与其他种族的关系恶化正是排斥魔族派当中的极端分子所乐见的。

于是，克里夫被选为了代表。

他与兽族占多数的鲁德佣兵团关系良好，与德路迪亚族的血亲熟识，交际广泛且毫无偏见，而且还隶属于教皇派。因此，他的阶级跟着提升，并派他随行担任监察之职。

克里夫苦笑着说，自己并不是只凭实力获得了评价。

然而，只要他在那座城镇完成工作，就能名正言顺地成为主教。一旦当上主教，权力将大幅提升，若能与大森林的居民维持良好关系，他迎娶长耳族为妻的正当性也会更加充分。

这样一来，他想必也能邀请艾莉娜丽洁与克莱夫一起移居米里斯......就是这样。

听到这里，我想说庆祝他升迁，顺便拿出了人偶给他当礼物！

结果被狠狠训了一顿。

他说，要是这种时期让人知道他迷恋女性，会酿成严重的后果。

话虽如此，他并没有拒绝接收人偶，我想他应该还是感到开心的。

毕竟他一脸兴致盎然地确认人偶细节部位的魔法阵。

希露菲说，要是有什么万一，只要让人偶戴上墨镜穿上男装就行了。

人偶也具有战斗力，希望能在主教的工作中发挥护卫作用。

毕竟谁也不能保证那位大主教不会对他下毒手。

顺带一提，那天回到家后，我发现克蕾雅心情很好。

听说菈菈捡到她一年前遗失的纪念怀表，并将其物归原主。

真是个感人的故事。女儿为别人立功，作为父母也感到非常自豪......不过，我猜八成是雷欧找到的吧。

另外，洛琪希似乎提高了育儿的动力。

她说「接下来大家都要上学了，我得好好照顾他们才行」。

虽然充满干劲的洛琪希很可爱，但她是那种太有干劲就容易出错的类型，这点让我有些担忧。

顺便说一下，希露菲与诺伦好像带着露西和克莱夫去了冒险者公会。

露西笑容满面地跟我讲述那边的午餐有多么丰盛。

看来她对冒险者公会本身似乎没什么兴趣。

第六天到第八天，没有特别安排什么行程。

我们出门逛街，带孩子们看看附近的观光景点，搭马车去城镇外面，看看附近的牧场，在附近的小溪边玩耍，感觉就是照那天的心情去玩。

第九天，我们谒见了国王。

米里斯王是一位面容和蔼的老人。在米里斯，教团拥有强大的势力，而王族相对较弱。

我本来就与教团关系良好，这个问候充其量也只是个形式。

原本想让孩子们看看城堡内部，但还是作罢了。这也没办法。

不管怎么样，我们已经在米里希昂充分地享受了美好时光。

\\

然后到了第十天，我们从米里希昂出发。

乘上马车，沿着圣剑大道一路北上，前往温泉。

「直到大森林的入口前不会有魔物出没，但听说驿站城镇聚集了不少流氓。只有你们倒还好，但既然带着孩子，就得格外小心──」

出发时，克蕾雅苦口婆心地叮嘱我们。

由于之前见面时，我曾要求她不要干涉，所以一开始她还没那么啰唆，但到了第十天，她的唠叨和说教便多了起来。

只是，我不会觉得那么不舒服。我想她大概也抓到了与我们之间的距离感吧。

不过在我们即将告别时，克蕾雅面向诺伦。

「诺伦小姐，这次虽然没能好好聊聊，但有一件事，我可以说一下吗？」

「......好的。」

诺伦的表情仿佛在说「终于来了」。

这十天以来，她一直在回避克蕾雅。即使瑞杰路德叮嘱她要珍惜亲人，她仍选择保持距离。

但是，不要责怪诺伦。因为一旦与克蕾雅交谈，她也有可能贬低瑞杰路德。到时，诺伦也不得不为瑞杰路德辩护。

而克蕾雅又那么固执，很可能不会订正自己的说法，最后演变成大吵一架。

「你已经不再是拉托雷亚家或格雷拉特家的人。」

「是。」

这一瞬间，诺伦的表情变得极具攻击性。

她肯定以为克蕾雅会借此批评她成为魔族妻子。

因为克蕾雅的语气就是有那么犀利。连我都一度误以为她会说些不好听的话。

「你现在是斯佩路迪亚家的妻子，也是母亲。请你对这点有所自觉，为你的丈夫与家庭尽心尽力。」

「咦？」

但克蕾雅接下来的话却极有道理。

虽说语气还是带有些许命令的感觉啦......

「虽然我对魔族的习俗不太了解，但身为妻子的责任与觉悟，就是抚养孩子与守护家庭，这点应该是相同的。」

「......」

「明白了吗？」

「啊......明白了！」

诺伦先是愣住，露出像是被攻其不备那样的表情，随后便老实地点了点头。

她的回答让克蕾雅也满意地点头，那副表情就仿佛卸下了一个重担。

我认为克蕾雅在这十天发生了一些改变。

或许是因为这样的变化，洛琪希和莉莉雅在最后几天感觉也过得格外放松。

尤其是洛琪希与克蕾雅之间的关系，应该比刚开始来的时候亲近了不少。

不管怎样，克蕾雅不再歧视魔族，这让我觉得很开心。

毕竟歧视问题并不是简单一句话就能解决的。

拜此所赐，诺伦与克蕾雅之间的隔阂应该也稍微缓解了一些吧。

......不过，爱夏那边还是老样子。

\\

★　★　★

\\

从米里希昂向北移动了约莫半天，我们抵达了青龙山脉的入口。

停下马车后，我让孩子们下车。

然后回头望去。

「......」

呈现在眼前的景色，是流入首都的蓝色河流、一望无际的绿色草原、生活十天左右的米里希昂，还有王城白之宫、金光闪耀的大圣堂、银光辉映的冒险者公会。

和艾莉丝、瑞杰路德一同见到这些景象，已是将近二十年前的事情了。

虽然与当时相比，细部建筑和居住的人应该都已经改变，但像这样从远处望去，一切几乎都是一往如昔。

「怎么样？」

这种宽广的风景，在这个世界并不少见，但能在亲自探索后像这样远眺的机会不多，应该会有一种难以言喻的感慨才是。

我这样想着，回头看向孩子们的反应。

「哇～！」

孩子们的反应各不相同。

露西纯粹地发出感叹的声音，笑容灿烂。

尽管她最近总是摆出姐姐的架子，但这种时候依然像个孩子一样老实。

......哎呀？站在她旁边的克莱夫似乎在犹豫是否要握住露西的手。

不过，最终还是没有握住，而是因为露西转头笑着说「好厉害呢！」而脸红，结果说出「又......又没有那么厉害」。

果然是男孩子啊......看着他，我忍不住笑了出来。我自己也有过这样的时候吧......不对，有吗？好像没有。

顺带一提，这次克里夫也一起同行。他的理由是赴任前要视察驿站城镇新建的教会，但明显只是借口。

这应该是教皇为了让他有时间与艾莉娜丽洁相处而特意安排的。

「......将来我想住在这里。因为有很多甜点。」

菈菈花了几秒睁开惺忪的睡眼后这么说道。

洛琪希之前在马车上有提到，克蕾雅好像非常宠爱菈菈，每天都为她提供甜点。

所以菈菈好像每天都洋溢着幸福的笑容。

或许是因为这样，感觉她比旅行前圆润了一些。如果有一个不用动手就有甜点吃的乐园，自然会想住下来吧。

「那个，爸爸和红妈妈以前也来过这里吗？」

「嗯，比你现在再大一点的时候来过。」

「哦......」

亚尔斯点了点头，握紧拳头。或许他正在考虑将来要成为冒险者吧。

「妈妈，妈妈！那就是尼古拉斯河吧！然后那边就是有哥布林的森林！」

「没错，那你知道那是什么吗？」

「那个是凯旋门吧！凯旋门是结束战争后，圣米里斯回来时的那个门，所以比其他的门都大！」

「答对了，真是清楚呢。」

齐格满脸兴奋地看着眼前的景色，一个接一个地向洛琪希提出问题。

他最近似乎从亚历那里听了各式各样的冒险故事，知识也因此变得丰富。

相较之下，他似乎比亚尔斯更有可能成为冒险者。

「爸爸，抱抱！」

克莉丝对着我张开手。

「......克莉丝还不太明白吧？」

「嗯～......」

我将她抱起后，她就像是在表示对风景没兴趣那样，把下巴放在我的肩上。

克莉丝还是这么可爱啊......

「......」

我望向莉莉，发现她正被希露菲抱着，手里摆弄着几天前在摊贩上买的魔道具。

看来她对风景也没有兴趣。对这两个孩子来说，欣赏风景这样的行为可能还太早了。

不对，一般来说应该都是这样吧。也许露西她们那样单纯为景色感动的样子反而显得早熟。

「......真让人怀念啊。」

突然，艾莉丝来到我身边。

「当时根本没想到会变成现在这样。」

她说着这番话，一脸怀念地望着米里希昂。

红色的头发随风飘扬，露出纤细的颈部。虽然还很年轻，但那张已经褪去稚气的侧脸，与美人这个形容十分贴切。

「那你觉得会变成怎样？」

「......我以为这个世界会更单纯一些。」

意思是她不再认为这个世界那么单纯了吗？艾莉丝并不是会深思熟虑的人，但也不是毫无想法。也许是因为生了两个孩子，她变得更加稳重，毕竟岁月会改变一个人。

「我喜欢你，鲁迪乌斯。」

艾莉丝突然转过身来，直视我的双眼说道。

心跳不由得加速了，怎么办？我现在大概满脸通红吧。

「我也是，艾莉丝。」

我努力装出平静的样子这样回答，艾莉丝稍微靠近了一些。

虽然这是个抚摸她身体的好机会，但可惜我的双手正抱着别的宝贝。

于是我选择抚摸着克莉丝，她露出怕痒的表情，笑着叫了一声「呀哈！」。

「爸爸，别搔痒我啦！」

「哦，对不起。」

「不会再搔痒我了吧？」

「不会不会。」

听到这段对话，艾莉丝轻笑一声，在我脸颊上吻了一下。

然后也在克莉丝的头发上落下一吻，随后便离开我的身边。

「好，差不多该出发了。」

随着艾莉丝的这句话，我们返回了马车。

\\

分割青龙山脉的深谷。

若将纵穿大森林的这条路譬喻为圣剑大道，这里便相当于圣剑的剑柄部分。

左右两侧是耸立的陡峭峡壁，虽无落石威胁，但昏暗的山谷无止境地延伸下去。

孩子们看到这样的景象时，一开始是露出雀跃兴奋的表情。

尤其是菈菈，她难得发出了「哦～」的惊叹声。

冒险的开端。接下来究竟将前往什么地方？是否会遇见魔物？据说这一带有青龙出没，我们能看到吗......？

这些期待在数天之内就被打破了。

风景毫无变化。

因为不在季节中，也没看到青龙，当然也没有魔物出没。只有不断延续的峡谷。

这样的日子，孩子们在三天后便开始厌倦。

菈菈直接大喊着「好无聊好无聊」，偶尔会说「带雷欧散步」就跑出马车，骑在雷欧身上移动。

说不定她只要一有机会就会试图爬上峭壁。

亚尔斯、齐格和克莱夫虽然嘴上没说，但他们显然更期待停车时与艾莉丝的剑术练习、孩子间的模拟战或是与洛琪希的魔术训练。毕竟那样总比什么也不做地坐在马车上摇来晃去好多了。

克莉丝则抱怨「被困住了」，还哭了起来。莉莉开始分解她买来的魔道具，拆得七零八落。

安静的只有露西，她默默地阅读着从拉托雷亚家借来的书。

坐在马车里看书，真亏她居然不会晕车。

马车里已经逐渐化为人间炼狱。我和希露菲她们合作安抚孩子们，但还是很困难......

虽然这条路很安全，但难得出门旅行，或许应该选择一些更有趣的路线来前进的......

不过──

正因为在这样疲惫不堪的状态下，当抵达驿站城镇时，孩子们显得莫名兴奋。

\\

「到了啊啊啊！」

亚尔斯、齐格以及菈菈一看到穿过山谷后出现的小镇，就从马车上跳了下去。

「喂，给我停下来！」

眼看他们直接朝城镇跑去，艾莉丝和希露菲立刻追了上去，分别抓住了亚尔斯和齐格的后颈。

然而，载着菈菈的雷欧却灵巧地溜了出去，爬到了一块稍高的岩石上。

话虽如此，也不需要惊慌。

这里是圣剑大道，并没有什么危险。

「菈菈！我们要先一起移动到旅社！」

艾莉丝这样大喊，但语气中却难掩兴奋之情。

她也是在这几天积累了不少郁闷的其中一人。虽然相比过去更加成熟稳重，但人类的本质不会那么容易改变。艾莉丝基本上是个无法安静待在一个地方的那种人。

亚尔斯和齐格虽然一脸不情愿，但还是回到了马车上。

但是，菈菈没有回来，而是在上面凝视着眼前无尽延展的大森林。

「菈菈，快回来。」

希露菲的呼唤让菈菈回头，但雷欧却没有动。

菈菈看了看希露菲，又看了看雷欧，然后从雷欧的背上下来，轻轻拍了拍它的背。

看到雷欧这样仍然不动，希露菲微微皱起眉头，忍不住走向了菈菈。

正当她要伸手时，菈菈却伸手制止了她。

「再等一下。」

「明天也可以慢慢看，快点叫它回来。」

「雷欧第一次这样看着故乡，它说想再多看一会儿。」

「这样啊......」

希露菲露出困惑的表情，转头看向我。

想让菈菈与雷欧继续待在这里，但我们现在是团体行动，其他孩子们也已经快要失控了，还是尽快移动比较好。

怎么办？就算是跟雷欧在一起，但总不能把拉拉丢在这边。希露菲大概是这么想的吧。

我从马车上下来，走向菈菈身边。

「希露菲，菈菈由我带过去吧。」

「......明白，要趁天还没黑之前跟我们会合喔。」

希露菲或许是听到这句话后就察觉到我的用意，干脆地点头，回到了马车上。

我在雷欧站着的岩石旁坐下。

随后，菈菈也跟着坐到了我旁边。我与菈菈并排坐着，眺望大森林。

虽说这条路几乎是平坦笔直，但或许是因为沿山而行，还是能俯瞰整片森林。

眼前是一望无际的绿色，其中穿插着一道褐色的笔直小道，很是壮观。

仔细想想，以前经过这里时并没有回头看看呢......

「菈菈。」

「什么？」

「雷欧是在怀念吗？」

「......它看起来不像觉得怀念。」

竟然没有啊。

「哦......」

「......」

那么，它现在是什么心情？

虽然有宠物语言翻译机，但我们家这台装置总是不愿意详细说明。要是反复询问，她甚至会发出一种「别拿我当翻译机」的气场。

「......菈菈。」

「什么？」

「本来想等你十岁再说的，你成年后会去德路迪亚族的村庄进行圣树仪式。」

「我知道，有听说过。」

「谁告诉你的？」

「雷欧。」

竟然是圣兽大人亲自告知。

「你知道普露塞娜吧？」

「爱夏姐的狗。」

这话讲得也太过分了，虽然没错啦......

「你会和她一起去。」

听到我这么说，菈菈露出了疑惑的表情。

「......爸爸不会一起去吗？」

「我很想去，但这对兽族而言是特别的仪式，人族可能无法旁观。」

或者......菈菈是那个吗？因为会觉得很害羞，不希望爸爸去看？

不过她现在应该还没到叛逆期吧......

这时，雷欧转头看向我。

「汪！」

「......雷欧说没关系。」

「没关系」的意思是我可以去参观吗？

既然菈菈还特地翻译出来......至少菈菈应该不是讨厌我吧。

话虽如此，等她再长大些，肯定会开始嫌弃我吧。

比如说，会喊着「不要和爸爸的内裤一起洗啦！」之类的。

克莉丝现在似乎还愿意说要当爸爸的新娘，但等她长大了又会怎么样呢？

「爸爸。」

「嗯？」

「没问题的，只要期待就好。」

「......嗯，我会这么做的。」

虽然不太清楚她指的期待是什么意思，但我还是点了点头。

菈菈似乎对此感到满意，也点头回应，随后站了起来。应该是准备走了吧？

这么想着，我回头准备起身时──

「唔喔......！」

突然感到肩膀有很重的东西坐了上来。

看到视线中晃动的小鞋子，我便意识到是菈菈跳到了我的肩上。

「背高高。」

「......是要我代替雷欧吗？」

「现在想跟爸爸撒娇。」

原来是想这样啊。那就让她撒撒娇吧。鲁迪乌斯先生可是很宠女儿的。

「汪呜呜呜呜呜呜呜────......」

就在我站起身的瞬间，雷欧发出了一声长嗥，声音甚至响彻到大森林的远方。

*** 「温泉」

说到山，自然少不了温泉。

后来，我们穿过驿站城镇，一路推开看到雷欧便蜂拥而至的兽族群众，顺利抵达了住宿的地方。

在驿站城镇观光了一圈后，我们和提前约好的向导──矿坑族矮人的塔尔韩德会合。等孩子们都安然入睡后，夜晚就跑去酒馆，只有我们大人热闹了一番。

在旅社过夜后，隔天一早我们便出发了。

在塔尔韩德的带领下，我们来到了温泉区。

听说这里会有魔物出没，但实际位置比想像中更靠近城镇。眼前的风景就像是原本是岩石地带的地方被乳白色的温泉填满那般。宽广的温泉区周围筑起了石墙，以防范魔物的侵袭。

从我们爬上来的方向回望，能远远看到眼下的驿站城镇。

也就是说，这里是一个风景绝佳的露天温泉。

理所当然地是混浴，但泡温泉的人并不多。

而且几乎没有人族。能看到的大多是矿坑族、小人族哈比人，以及形形色色的兽族。或许温泉这种文化在人族与长耳族中尚未普及。

毕竟在人族中，好像也只有贵族才有用浴缸泡澡的习惯。

好啦，这里人不多，也几乎没有人族。

话虽如此，还是有男人。

虽然也有女人，但确实有男人。

让我挚爱的妻子和女儿的裸体暴露在陌生男人面前，这样好吗？

不，当然不好。

尤其这次，不仅仅是我家的女眷。

艾莉娜丽洁也在。即使她曾是冒险者业界鼎鼎大名的妖艳脱衣舞者，但如今她已经成为人妻，我看到这个妖艳长耳族的裸体真的好吗？

不，当然不行。

基于这些考量，我特意准备了浴衣。

这是一种用深色布料制成的简单罩衫，没什么特殊抗性，但穿起来就像泳衣一样自然，舒适轻便。设计师是爱夏•格雷拉特。

「爱夏姐！那边有瀑布！」

「咦？在哪里？」

「快来，爱夏，这边这边！」

「啊，等一下啦，妈妈！」

爱夏和第一次体验温泉而兴奋不已的艾莉丝、亚尔斯、齐格一起，在宽广的温泉池内溅起水花，四处探险。

由于布料颜色较深，虽然不会透过去，但湿布紧贴在身上，让身体的曲线显露无遗。她们毫不在意地将这一切展现在人前，跑过来又跑过去的......

艾莉丝可能没注意到这一点就算了......但爱夏真的不觉得害羞吗？

算了，这里是任何人都可以进入的温泉区。只要重要的部位有遮起来就好。

觉得害羞的人才羞羞脸。

不过，还是希望她们不要给其他入浴者添麻烦。

像这种地方，应该也有基本的礼仪吧。

「那个，蓝妈妈以前也来过这附近吗？」

「是啊，很久以前了。」

「我要听！」

「好吧。这是我刚离开魔大陆、刚从新手冒险者阶段毕业时的事情──」

洛琪希一边抱着莉莉，同时向露西讲述她的过去。

克莱夫也在附近聆听着这段往事。不过他脸红红的，是不是因为穿得很单薄的露西正坐在旁边？不过，小小年纪就懂这些还是太早了啊，克莱夫小弟。

我和你爸爸可不会允许这么早熟的恋情喔。

「......所以圣兽大人，这位就是救世主？」

「汪！」

「原来如此！」

「......」

至于菈菈和雷欧，他们现在被一群兽族包围。菈菈还是那副老样子，摆出天不怕地不怕的表情，似乎有些不耐烦。毕竟从驿站城镇开始他们就一直围着她。

「克莉丝小姐，如果觉得热了请告诉我，我也准备了饮料。」

「嗯......」

莉莉雅让塞妮丝泡着脚，同时照顾着克莉丝。

克莉丝一开始是由我抱着一起泡温泉，但她似乎不太喜欢热水，很快就上去了，现在正紧紧依偎着塞妮丝。

哎，应该没问题吧。

\\

「......哈──！真是太棒了......！」

「我是第一次喝矿坑族的酒，后劲好强......但很好喝。」

然后，我、希露菲、艾莉娜丽洁、克里夫以及塔尔韩德五人正聚在汤池的一角喝酒。这是我们在驿站城镇买到的矿坑族秘酿的酒。现在用冰块冰镇后饮用。老实说，这是我从未喝过的味道，完全喝不出这酒是用什么酿造的，但味道很好。

一开始的口感柔和但带有爽利，滑过喉咙时，淡雅的花香随之飘散。

冰凉的美酒渗透进因热气而发烫的身体，随后又从内部缓缓散发出暖意。

「鲁迪，也分我一点嘛。你来喂我喝吧？好吗？」

希露菲很快就喝醉了，她带着微醺的表情靠在我身上。

喝醉的希露菲依然这么可爱。她讲的话可爱到完全想不到是生了两个孩子的母亲。这模样可不能让孩子们看到。

「嗯，当然可以。」

泡在温泉里，一边轻抚美人的腰一边喝着美酒。

棒极了。这里就是天国啊。

「......」

不过......

「......」

不知为何，从刚才开始就有一股寒意。

「......」

我知道这股寒意的原因。

是来自于我正面安静喝酒的那个男人。

塔尔韩德。他是保罗之前隶属的「黑狼之牙」的队伍成员之一。

现在依然以S级冒险者的身分单独行动，实力也值得信赖。

「......」

我没有理由怀疑他。

即使他真的做了什么，我应该也能应对。

之前做了详细的面试，已确定他不是人神的使徒。

当然，也不能忘记基斯的例子。

那家伙在被询问时面不改色地撒谎，完全把我耍得团团转，所以没办法百分之百保证。不过要这样讲的话，就无法再相信任何人了。所以我决定相信塔尔韩德。

可是，为什么呢？

只要对上塔尔韩德的视线，我的背脊就会感到一阵寒意。

在来温泉区的路上也是如此。

我们是由艾莉丝走在队伍的最前面，艾莉娜丽洁和我作为前卫，塔尔韩德则紧随其后，希露菲与洛琪希则守在马车后面。我移动时会用土魔术整平道路，让马车能比较轻松地通过，但有好几次感到一股寒意。

每当这时回头一看，就会发现塔尔韩德正在看着我。

当然，我们前进的方向一致，走在前面的我一旦回头，自然会对上他的视线。

可能是因为带着孩子走在会有魔物出没的地方，导致我过于敏感了吧？

我试着这样说服自己，可是......

直到现在，他的视线依旧投向这边，而那股寒意也依然存在，怎么想都觉得不合理。

「那个......有什么事吗？」

我终于忍不住，开口询问塔尔韩德。

「你是指什么？」

「一路上，你好像总是在看我......是怎么了吗？」

「啊......没什么，只是觉得你越来越像保罗了，所以才忍不住一直看着。」

「像我父亲？」

「嗯，当你和艾莉娜丽洁并肩走在前面的时候，让我想起了从前。艾莉娜丽洁、基列奴、保罗的背影，还有从后方传来的基斯和塞妮丝的声音......当初我们作为『黑狼之牙』一起探索迷宫的日子......」

塔尔韩德抚摸着胡须，露出怀念的神情如此说道。

我自己看不到自己的背影，所以不晓得，但或许就是那样吧。

不过，这样的话为什么会涌起寒意呢？真不可思议。

「鲁迪乌斯，要小心点喔，这个矿坑族可是男女通吃的。」

「咦？」

将头靠在克里夫肩上的艾莉娜丽洁这样说道，我不禁惊呼出声。

听到这话，塔尔韩德顿时板起一张脸。

「喂，别用这种容易引起误会的说法。」

就是嘛。

受不了，艾莉娜丽洁小姐这个人真是的。总是喜欢把事情往色情方面联想。

这个调皮的淫乱精灵。

「我可是只喜欢男人的。」

淫乱矿坑族！

不对，等等。

那么，这股寒意的来源是那回事？我被盯上了吗！

要......要是敢对小女子动手，艾莉丝绝对不会袖手旁观！会把你劈成两半的喔！

我不由自主地抱住希露菲，身体轻微颤抖着。

而希露菲也立刻像是在保护我一样，用锐利的目光盯向塔尔韩德。

「......放心吧，我不会对已婚者或者对男人没兴趣的人出手。」

唔，看来他还是有道德底线的。

不过，也对啦。他只是喜好和一般人稍微不太一样罢了。打个比方来说就是他的好球带和别人不同，而且还相当狭窄。这样想想也算正常吧。

「不过，你还是会忍不住盯着男人的屁股吧？」

「盯着屁股是男人的本能......你懂的吧？」

听到艾莉娜丽洁这样开着玩笑，塔尔韩德露出有些无奈的表情回应。

这本能我很能理解。毕竟我从刚才也一直盯着艾莉丝在水中走动的屁股。

啊，艾莉丝转过来了！她不会是感觉到寒意了吧？

啊，她居然遮住了胸口！果然感觉到了吗！可是要遮的地方错了喔，毕竟我看的不是胸部，是屁股啊！

「说你有点像保罗，让我感到怀念，这是真的......不过，如果你介意的话，我就不看了。」

「没关系，请尽情地看吧。」

「呵呵，那真是抱歉啦。」

塔尔韩德说着，眯起眼睛，拿起酒瓶。

「来，再喝一杯怎么样？」

「那我就不客气了。」

每个人都有自己的爱好，只要对方在交流时能维持道德底线，我也没必要太过警惕。反正我的身体被多看几眼也不会少块肉。不过，塔尔韩德的身材像熊一样壮硕，要是比较的话，我可能还会有点自卑。

「不过话说回来，我没想到这次会是由你来担任向导。」

艾莉娜丽洁突然这么说道。

「这话是什么意思？」

「你不是一直在避免自己前往故乡吗？这个温泉区也算是矿坑族的地盘吧？万一遇到熟人不是会很麻烦吗？」

塔尔韩德似乎有些隐情。

话说起来，在保罗以前的队伍成员当中，我对这个人的了解是最少的。

不过，可能是因为我本身对他的兴趣不大吧。

「............哼。你自己不也是吗？以前和我们一起旅行时，你还说绝不可能和一个男人定下来。」

「只要活着，总是会改变想法的。」

「我也一样。这是个好机会，我觉得差不多该跟过去做个了结了。」

「哎呀，真有男子气概呢。」

「不用说这种客套话。只是看着你们，我就觉得自己几十年来一直逃避家人的行为实在太丢脸罢了。」

塔尔韩德说着，面露苦色地举起杯子一饮而尽。

「也就是说，你打算回故乡吗？」

「是啊。」

「喂，鲁迪乌斯。」

听到有人叫我，我转头看向艾莉娜丽洁。

一瞬间，我不明白为什么会被叫到，但很快会意过来。这大概是要提醒我趁着这个机会向他提出请求吧。不过，他也有自己与家人的事情要处理，这样拜托他真的好吗？

算了，反正拜托一下又不用钱。

「塔尔韩德先生，其实我也有意与鑛神接触......」

「鑛神？」

「是的，如果你方便的话就好，不用勉强也没关系，希望能麻烦你告诉他，我......龙神的属下想向他问候一声。」

我不清楚塔尔韩德在故乡的地位如何。

被人当作联系窗口可能会给他带来麻烦，所以我讲得比较保守。

「嗯......不过，那家伙可是很难搞的。」

的确如此。奥尔斯帝德也曾这么说过，鑛神个性古怪，很难取悦他。

据说他喜欢的东西有酒、宝石，以及适合制作武具的矿石或金属。

但仅仅以他喜欢的东西为诱饵，也未必能够让他同意结盟。

「就算我出面帮忙，也有可能被拒绝喔。」

「你认识他吗？」

「算是吧......」

塔尔韩德露出为难的表情点了点头。

难道，他和鑛神是家人吗？看来等回去后，我得先和奥尔斯帝德再商量一下这件事。

「不方便的话请不要勉强。塔尔韩德先生应该也有许多事情要考量。」

「是啊......」

塔尔韩德一边思考，同时喝下了酒。

他的脸颊泛红，酒气随着他的呼吸散开。然后，他微微眯起眼睛看着我。

「让我稍微考虑一下吧。」

「好的，不好意思，讲这种为难你的话。」

当我正准备低头致歉时，塔尔韩德拿起酒瓶，将瓶口朝向我。

这个意思想必是「别道歉，喝吧」。

我依他的意思，请他帮我在杯子倒满了酒。

\\

泡完温泉后，我们回到了驿站城镇。

让家人留在旅社后，我和洛琪希、塔尔韩德、艾莉娜丽洁一起前往寻找适合设置转移魔法阵的地点。同行的人严格挑选了习惯于山林行走的人选。艾莉丝本来也想跟来，但我拜托她负责保护家人。

我们四人进入了山区深处。

这里比温泉区更远一些。

毕竟转移魔法阵最好设置在尽可能不会有人出没的地方。

爱丽儿曾提过「将来想要建设连接主要大国之间的转移门」，相关的规划也已经开始进行......但这件事还要很长一段时间。

解除转移魔术的禁令。这项计划能否实现还不得而知，因此我个人制作的转移魔法阵会设置在人烟稀少的地方。如果设置在过高的地点，可能会进入青龙的地盘，所以选址仅限于人类可到达的范围。

「就挑这地方吧......」

找到合适的地点后，我便开始建造建筑。

结构基本上参考了龙族遗迹的风格，设有四个房间，其中一个房间内设置了隐藏的楼梯通向地下，而转移魔法阵就放置在楼下。

我拜托洛琪希和艾莉娜丽洁在外看守，我则用土魔术挖掘地下空间，并塑造房间结构。至于内部的装潢与房间的大小之类，则是拜托塔尔韩德协助。

虽然将转移魔法阵设置在不容易被发现的地方，但这个魔法阵是用来通往事务所的。

毕竟如果不小心被人发现魔法阵，那可就麻烦了。

因此，我将整个建筑伪装成一座普通的遗迹，并为了让旅人能够满意，在房间深处放置了几个看似宝箱的东西。顺便也设计了一些供人休息的设施。

营造出「这是很久以前旅人用来休息的设施喔～」这样的氛围。

为此所需的装饰，全部是由塔尔韩德帮忙制作的。

他不愧是矿坑族出身，手艺非常精巧。

只用我制作的一把超硬凿子就凿开石头，雕刻出精致的石材装饰，让整个房间散发出古老的韵味。

当太阳下山时，整个内部已经呈现出仿佛存在了百年的氛围。

「果然厉害。这样的话，不论谁来看都没问题了吧。」

「哼。这里一点苔藓和霉菌都没有，明眼人应该一下子就能看穿。」

哦，看来这位工匠对自己的完成度还有些不满。

话虽如此，应该不会那么快被人发现吧。

等到建筑真正被找到时，应该已经因自然侵蚀而看起来更加古老了。

反正也没人会来打扫。

「话说回来，我现在才想到，在这里随意建造建筑真的没问题吗？这里应该是矿坑族的领地吧？」

「对矿坑族来说，山是属于神明的，建筑是献给神的礼物。无论谁建了什么，矿坑族都不会有意见。」

原来是这样啊。

既然这样，或许一开始不该设在地面底下，而是堂堂正正地建造在地上还比较好。入口设在地下，反而像是在表示这里有什么见不得人的东西一样。

不过，现在说这些也晚了。

「既然完成了，那我们走吧。」

「请稍等一下。」

最后，我启动了魔法阵，进行了一次转移。

确认转移目的地正确无误地连到了事务所的地下后，又返回原地。

「没问题了。」

「......」

「塔尔韩德先生，如果有需要，你也可以随时使用这个魔法阵。」

「不了，我喜欢用走的。」

塔尔韩德摇了摇头，拒绝了我的提议。总之，这样转移魔法阵就完成了。

接下来只要回去就行了。

\\

隔天，我们一大早就准备离开驿站城镇。

将在这里与克里夫及塔尔韩德分开。我们坐上马车，与他们两人道别。

克里夫今天要去教会视察，几天后将返回米里希昂。

「克莱夫，要当个好孩子喔。」

「好！爸爸！」

克里夫依依不舍地和克莱夫道别。

虽说并不是好几年见不到面，但与家人分离总是令人难过。

「不管是学业还是剑术都要好好努力。还有，不准让喜欢的女孩哭，要对她温柔点。」

「我......我才没有喜欢的女孩！」

「那就对所有你认为喜欢的女孩都温柔一点，明白吗？」

「......明白。」

克里夫轻轻拍了拍克莱夫的头，随后转向我。

「鲁迪乌斯，麻烦你这几年再多照顾一下丽洁和克莱夫了。」

「嗯，我知道的。克里夫学长，也请你好好加油。」

「嗯。」

克里夫就像是在表示没有需要再多说什么，退到后方。

之所以选择沉默，正代表他对我的信任。我也希望回应他的信任。

不过，艾莉娜丽洁非常可靠，我基本上没什么要做的。

这个嘛，顶多就是......万一克莱夫成年后跑来跟我说「请把露西交给我」，我应该在那之前帮助他成为一个好男人吧......不过，这样做可能也不会有什么好结果。在他遇到问题的时候伸出援手才是最合适的做法吧。

我这么想着，走向稍远处正在与艾莉娜丽洁和洛琪希交谈的塔尔韩德。

塔尔韩德似乎准备先返回米里希昂，可能是因为前往矿坑族的聚落还需要一些准备。

不知道要准备的是物品，还是心理上的建设就是了。

「塔尔韩德先生，真的非常感谢你。」

「嗯。」

「希望你与家人的事情，还有故乡的事情......都能顺利解决。」

「哼，竟然连那个保罗的儿子都开始替我操心，实在很不是滋味......」

塔尔韩德这时将视线落在我的身上。感觉他好像特别关注我的双腿之间。

「今早我突然想到，鑛神只要看到你的那个，说不定就会兴奋得同意见面了。」

「那个？」

「昨天你给我看的那个，又黑又硬的东西。」

「咦！」

在我双腿之间的又黑又硬的东西？

难道说......鑛神该不会也是男同性恋吧？

是说，我那里应该没那么黑吧......硬倒是没错啦，很硬喔。虽然我没和别人比过，也不确定算不算硬。洛琪希，你怎么脸红了！快说点什么啊。比如「那是我的」之类的！

「塔尔韩德，你讲又黑又硬又粗的东西别人听不懂啦。可以说得更直接一点吗？」

「我可没说粗。就是那个。鲁迪乌斯用土魔术生成的那块石头。不知道是矿石、岩石还是金属......我也不晓得该怎么说。」

原来是石头啊。仔细想想，昨天建筑时我确实生成了不少黑色的石头。

就是为了追求坚固度而产生的特别坚硬的材料。

什么嘛～原来是石头啊......哎呀，洛琪希你脸红了，怎么啦？刚才是在想像什么啊？讨厌啦～洛琪希也太羞羞脸了吧～不过，我自己刚才也联想到了同一个东西。

「如果有样品，我就带回去试着拜托他，如何？」

「明白了。」

我立刻当场用土魔术制造了一根黑色的石棒。

又黑、又硬、又粗。

当然也很重。长度约十五公分，重量想必超过十公斤。

这个重量要是加上金箔的话，八成能对人谎称是金条。不过比金或白金硬得多，我想很快就会被识破。

「这样的可以吗？」

「不错，能再多拿几根吗？」

塔尔韩德从我手中接过五根石棒，眯起眼睛掂了掂重量，然后点了点头。

手上拿着五根应该相当重才对......他果然也是老练的冒险者。

「那么，保重。」

塔尔韩德转身准备离开，洛琪希上前一步。

「塔尔韩德先生，请多保重。」

「你也是，别生病了。」

「是。」

塔尔韩德说完后笑了笑。

洛琪希也与朋友道别，稍稍露出微笑。

\\

就这样，我们的家族旅游圆满落幕。

回想起来，大部分时间都在忙着工作，但依然是一次不错的旅行。我希望这能成为孩子们宝贵的经历，成为他们未来的养分──

虽然这样说有点装腔作势，不太适合我啦。

不过，希望他们能健康地成长下去。

*** 「险峻山峰之塔尔韩德」

塔尔韩德被称为「险峻山峰之塔尔韩德」，是五十一个兄弟姐妹中的第三十七个。

他出生于矿坑族的一个普通家庭，与众多兄弟姐妹一起成长。

五十一个兄弟姐妹当然并非由同一名女性所生。对一般人而言不太为人所知的是，在矿坑族的聚落中，同一世代的孩子会被集中起来抚养。

这种方式类似学校，孩子们即使成年后离开了这个群体，也会一辈子被视为兄弟。

像这样让同辈的孩子们作为兄弟姐妹一起生活，目的是为了消除家庭间贫富差距的意识，为将来成为聚落的砥柱时奠定顺畅的合作关系。

在这些兄弟姐妹中，有人成为首领，有人成为他的支柱，有人则成为妻子。

当然，这一切仅限于矿坑族聚落这样一个优越的环境中才可能发生。

走出聚落的矿坑族人则没有这种风俗。

塔尔韩德在这样的环境中与数十名兄弟姐妹一同成长。

他是个普通的孩子，对土壤与金属感兴趣，喜欢酒香，崇拜工匠与建筑师。

有些与众不同的一点是，他比起女性更喜欢男性。

然而，他的兄弟中有一位极不寻常的人。

那就是他的弟弟，五十一名兄弟姐妹中的第三十八个。

名为「荣耀顶峰之戈德巴尔德」。

戈德巴尔德天赋异禀。矿坑族的孩子一旦开始懂事，就会灌输他们锻造、手工艺以及简单的土魔术。在这些学习的过程中，戈德巴尔德的表现压倒了其他人。

一旦手握铁锤，就能打造出与成人无异的坚韧钢铁﹔做起手工艺来，能创作出令人难以置信的精美饰品﹔只要观察建筑结构，便能转眼间修复问题之处。

矿坑族的寿命比人族还长。

当戈德巴尔德展现才华时，还有经历过拉普拉斯战役的老人健在。

他们看到戈德巴尔德后感慨地说「他简直就是拉普拉斯战役中死去的先代鑛神大人再世」。

老人的这番话让戈德巴尔德被视为下一任鑛神候补，开始受到特别待遇。

孩子们也被迫尊敬他，视他为未来的领袖。

从那时起，塔尔韩德开始改变。

他对锻造和手工艺失去了兴趣，因为无论他多么努力，自己的作品在戈德巴尔德的作品面前总是相形见绌。他从未被拿来与谁比较过。毕竟，成年人只看戈德巴尔德的作品，根本没有比较的余地。

那么，塔尔韩德想成为第一吗？

不对，他并非想成为第一。

那么，他讨厌尊敬戈德巴尔德吗？

这也不对。塔尔韩德与戈德巴尔德的关系很好。

与大家刚成为兄弟时，他最先亲近的就是戈德巴尔德。

塔尔韩德的初恋对象也是戈德巴尔德。因此，戈德巴尔德成为鑛神，对塔尔韩德而言是一件值得高兴的事。

简而言之，塔尔韩德只想设法帮忙戈德巴尔德的忙。

他想弥补戈德巴尔德的不之处，成为他最可靠的左右手。

于是，塔尔韩德开始专注于魔术的修行。

他最想学会的是矿坑族中不受重视的水魔术和风魔术。

据说初代鑛神是一位神级土魔术师，能自己用魔术创造矿石，打造出绝世名剑。然而根据传说，鑛神在创造名剑的过程中，有一位精通风魔术和水魔术的长耳族协助他。

锻造并非仅靠土与火便能完成。需要风来助燃，水来冷却钢铁。尽管这是毋庸置疑的道理，但矿坑族的成年人却无法接受这个观点。

传统、规范、以前的祖先都不擅长水魔术与风魔术等等......

他们将种种理由搬上台面，目的就是阻止塔尔韩德学习水魔术和风魔术。

实际上，塔尔韩德的土魔术比水魔术和风魔术还要强。

但戈德巴尔德对他这样说：

「我觉得这样很好。聚落里的大人太顽固了。」

塔尔韩德因为这句话而产生了勇气，更加沉浸于魔术之中。

就这样，他与矿坑族的其他男性越来越疏远。

于是，他的兄弟中也有人开始批评他。

有人指责他太过软弱，说他像个娘娘腔一样不锻造，这样根本不算矿坑族的男人。他们认为，魔术只需要能稍微削弱坚硬的岩盘就够了，锻造所需的材料应该来自大自然才是。

塔尔韩德虽然对那些批评感到厌恶，但依然一步步钻研自己的技艺。

这一切都是为了戈德巴尔德。等戈德巴尔德成为鑛神后，一定会需要自己的力量。

他是这么坚信的。

成年后，那些批评的声音变成了嘲讽，遭到聚落的兄弟排挤，被称为整个聚落最乖僻的怪人。就算如此，他依然坚信不疑。

然后，那一天到来了。

戈德巴尔德被任命为鑛神的那一天。

鑛神的袭名仪式遵循着古老的传说，候选者必须锻造五把剑。

而锻造这五把剑时，每一把都需要由候选者选出的最值得信赖之人协助完成。

这些人可能是妻子、挚友，或是未来成为鑛神时能够辅佐矿坑族聚落的干部，要由鑛神亲自挑选自己的助手。

塔尔韩德理所当然地自告奋勇。

毕竟自己就是为了这天钻研自己的技艺。

然而出乎意料的是，戈德巴尔德并没有选择他。他选择了当时聚落中被认为最有本事的工匠们，也选择了自己的恋人......这些都还说得过去。但他最后选择的，是一名过去经常辱骂塔尔韩德是愚蠢之人的顽固老者。

塔尔韩德因此抗议了。

他说「怎么可以有这么荒谬的事！我是为了你才努力到今天的啊！」。

然而，戈德巴尔德却这样说了：

「你能锻造出像样的剑吗？」

当然，塔尔韩德如此回答：

「可以，我有办法做到，所以给我一次机会。」

戈德巴尔德听到这个恳求后面露难色，但最终同意了他的提议。

于是，他要那名顽固的老者与塔尔韩德各自锻造一把剑，看谁的更为出色。

另外，戈德巴尔德还为了公平起见，广邀其他有自信胜出的人参与这场对决。

当天聚集了众多参加者。

塔尔韩德为此感到愕然。

尽管水魔术与风魔术都是为了这一天而锻炼的，但自己从孩提时期就几乎没有进行过锻造方面的修行，好好锻打出一把剑的经验屈指可数。

这实在太过不利了。

「等等，我是想作为你的助手铸剑啊！」

然而，这样的恳求却被一句话断然回绝：

「连靠自己铸剑都没办法的人，怎么可能理解我的意图？若无法理解意图，又怎么能成为我的助手？」

这句话让塔尔韩德感到莫名其妙。因为他一向认为，没有人比他更懂戈德巴尔德的想法。

然而，为什么却被他这样否定......？

塔尔韩德陷入混乱，最终未能制定出有效的策略便匆匆上阵......

结果败北了。

塔尔韩德遭受沉重的打击，在周围人投来的冷眼之下黯然退场。

几天后，他在远处看着鑛神的袭名仪式举行，离开了这个聚落。

\\

后来，塔尔韩德以冒险者的身分四处漂泊。

基本上都是孤身一人行动。

因为戈德巴尔德的那件事，让他很难再信任他人。

而长年遭到排挤的经历，也让他不晓得该如何与人相处。

还有，喜好男色这点也是他感到自卑的原因之一。

虽然塔尔韩德的锻造技巧在矿坑族中属于最低阶，但归功于多年钻研的经验，他作为魔术师的水准倒是还过得去。

尽管如此，也仅仅是还过得去。因此，他身穿沉重的装甲，采取了一种介于战士与魔术师之间的战斗风格。即使如此，要当一个独行的冒险者，对塔尔韩德来说也并非难事。

当塔尔韩德升到冒险者B级时，他遇见了一个人。

艾莉娜丽洁•杜拉冈罗德。一开始，她的目的是塔尔韩德的身体。

她甚至可能怀着「偶尔品尝一下矿坑族的小伙子也不错」的心态。不过，塔尔韩德喜好男色，对艾莉娜丽洁毫无兴趣。无论她如何诱惑，塔尔韩德都不为所动。

但即使如此，艾莉娜丽洁的诱惑还是让塔尔韩德感到烦躁，最终他坦白了自己的性取向。

听到他的告白，艾莉娜丽洁一时愣住，随后放声大笑。

这笑声让塔尔韩德感到不快。

但他也忍住了，因为他认为自己终于可以摆脱这位好色的长耳族。

但出乎意料的是，艾莉娜丽洁并没有离开塔尔韩德身边。至于理由也不得而知。

或许艾莉娜丽洁是认为与塔尔韩德同行的话，就不会惹来麻烦吧。

之后，塔尔韩德与艾莉娜丽洁多次临时组队。

身为优秀战士的艾莉娜丽洁，与身穿厚重装备的魔术师塔尔韩德非常容易配合。

尽管塔尔韩德对这位让人烦躁的搭档颇有微词，但说来奇怪，他觉得这种感觉还不坏。

或许是因为艾莉娜丽洁是个不受常识、传统、习俗和规矩束缚的人。

话虽如此，两人也从未提及要固定组成一个队伍。

直到一位少年的出现，才改变了这一切的走向。

那个少年就是保罗•格雷拉特。

保罗主动联系了当时都是一匹狼的艾莉娜丽洁、塔尔韩德、基斯与基列奴，组成了队伍。

那就是「黑狼之牙」。

虽然组成的过程中也出现过一些小插曲，但那些事就暂且不提。

「黑狼之牙」的成员都遭到自己生活的世界所排挤。

虽然塔尔韩德是其中唯一的男同性恋者，但每个人都忠于自己的欲望。

尤其是保罗，他做事特异独行且随心所欲。当保罗知道塔尔韩德的性取向后不仅不在意，还笑着说「我要女人，艾莉娜丽洁要男人，你再把剩下的吃掉，这样就不浪费了」。

保罗明显就是个坏小子，总是做些让人忍不住叹气的事情。

然而，他的行为从未受限于任何束缚。

这些行为既非源于常识，也未必符合世人的道德标准。即使是被社会视为恶行的事情，保罗依然随心所欲地行事，并以一句「关我屁事」嗤之以鼻。

保罗笑着做出的这些行为，让塔尔韩德犹如醍醐灌顶。

他的行为，确实让「黑狼之牙」及其成员变得恶名昭彰，但那段时光却很快乐。

每当保罗干出什么事，塔尔韩德总能像典型的矿坑族那样，嘎哈哈地大笑。

对保罗等人的感情与恋慕有些相似，但又不完全相同。

那大概就是所谓的信任吧。对塔尔韩德来说，他们是人生中第一批真正能信任的伙伴。

然而，这份信任最终被粉碎了。

因为塞妮丝的加入，摧毁了这一切。

保罗这个曾经无拘无束的男人，为了让塞妮丝对自己刮目相看，开始说出一些符合常识的言论。

毫无疑问，这样的改变使保罗在人格上有了明显的成长。

但保罗最终还是犯了一个错误。为了与塞妮丝结婚，他引发了一场骚动，给在场的每一个人心里都留下了难以抹去的创伤。从旁观者的角度来看，这场骚动或许只是鸡毛蒜皮的小事。

然而，塔尔韩德却在那时下定决心，再也不跟人组什么队了。

之后，他自己旅行了一段时间，然后发生了菲托亚领地消灭的事件。

他再次与艾莉娜丽洁重逢，并结识了洛琪希，与她们一起组成队伍，这才稍稍改变了「不再组队」的想法......

不管怎么样，他内心对保罗这个男人依然有着深刻的情感。

在魔大陆来回奔波后，塔尔韩德再次与保罗重逢。

多年未见的保罗......已不再是自己记忆中那个坏小子。他成为了一个成熟的大人，一个拼命寻找自己家人的父亲。这让塔尔韩德不禁心想「这男人变了啊，已经成长为一个大人了」。

至于第一次见到保罗的儿子，则是在贝卡利特大陆。

那个保罗的儿子，鲁迪乌斯•格雷拉特。塔尔韩德原本以为他会是个不成材的纨绔子弟，后来却发现这孩子意外地可靠。但想想也很合理，毕竟他是成长之后的保罗的儿子。

保罗与鲁迪乌斯。

当塔尔韩德看着他们时，心中总是涌上一种难以言喻的压抑感。

他不晓得理由是什么。

\\

后来，保罗死了。

\\

他的死来得过于突然。

塔尔韩德虽然也很震惊，但看到鲁迪乌斯受到的打击远比自己来得更大，便不忍心表露情绪，依旧以平静的态度喝着酒。

后来，他离开了贝卡利特大陆，在那里，保罗的儿子向他介绍自己的家人。他看到保罗的儿子已经成家立业，盖了属于自己的家稳定生活，随后去祭拜了保罗的墓，并在墓前开怀畅饮，便离开了魔法都市夏利亚。

那一刻，塔尔韩德感到内心有个东西画上了句号。

自成为冒险者以来，就一直存在的某种情绪消失了。

\\

在虚无感中，塔尔韩德忽然做出了一个决定。

开始钻研锻造的技术吧。

塔尔韩德不明白自己为何会做出这样的决定，但他立刻前往阿斯拉王国，一边从事冒险者的活动，一边借用锻造场反复进行训练。即使在基斯因赌博被捕、几乎失去所有财产、需要前往米里斯大陆赚钱的时候，他也没有停止。

他将自己能使用的所有魔术都投入到锻造中。

火、土、水、风，将全部魔术用来辅助。

他铸剑、锻造护手、制作盾牌、再一次铸剑、锻造铠甲、制作头盔，又再次铸剑。

不可思议的是，他在这个过程中逐渐明白了戈德巴尔德当年那句话的含义。

像是呼吸、时机、节奏、力量的轻重缓急，他开始理解了无法用言语表达的那类细腻的动作。

塔尔韩德进步神速。

能有这样的成果，一方面是因为戈德巴尔德锻造时的动作早已深深烙印在他的脑海，另一方面则是冒险者的经历让塔尔韩德知晓何种武具会更为出色。

运用魔术的技巧也与还在聚落时截然不同。

作为冒险者生活的每一天，确实锻炼了塔尔韩德的技艺。

随着这样的日子不断持续下去，也开始有人愿意购买塔尔韩德的武具。

其中包括鲁德佣兵团。因为是鲁迪乌斯的熟人，佣兵团的分部长成了塔尔韩德的赞助者。

拜此所赐，他得以在米里希昂的一隅设立了自己的锻造场。

然而，塔尔韩德依旧不明白自己为什么要做这些事。

在冒险者的工作之余模仿工匠的工作，究竟有什么意义。

直到某天，鲁迪乌斯带着全家从魔法都市夏利亚来到这里，他才终于明白。

那位保罗的儿子与拉托雷亚家的地位至少平起平坐，同时还抚育着自己的孩子们。

看到这一切，塔尔韩德顿悟了，同时也理解了。

自己必须回到那个聚落，必须为当年的事情做个了断。

这正是他锻造的意义。

\\

★　★　★

\\

在收到鲁迪乌斯给予的黑色石块后，塔尔韩德回到了自己的锻造场。

自己从以前就构想过如果能用魔术制造这样的石材，应该如何加工，甚至连理论都已思考完备。

从前这些不过是梦想，但现在，他已经为此累积了足够的训练。

「......」

首先，他用土魔术和锤子将鲁迪乌斯的黑色石块分解。

接着，将其与砂铁混合后放入炉中加热。由于普通炉火无法熔化这些材料，他并用了火魔术与风魔术，尽可能提升炉内的温度。

不论是核心材料还是玉钢，塔尔韩德均采用混合了鲁迪乌斯石块粉末与砂铁的原料。

尽管比例有所不同，但基本制法一致。

若使用赤龙的鳞片或九头龙的坚骨，或许能打造出更为惊人的武器，但塔尔韩德并未这样做。那样的话，就失去意义了。

接下来，他仔细地进行淬火，整夜未眠，逐步倾注气力与魔力，同时坚定不移地挥下每一锤进行锻造。

最终，他完成了一把剑。

这是一把拥有漆黑刀身的坚韧之剑。

虽然没有任何特殊的装饰，也不具备特殊效果。

但塔尔韩德对这把剑感到非常满意。他制作了剑鞘，并用上等的毛织物小心包裹起来，将其背在身后。

随后，他将剩下的黑色石块装入袋中，离开了米里希昂。

目的地是矿坑族的聚落。

\\

他久违地造访矿坑族的聚落，发现这里几乎没有改变。

这个石造村落依然位于悬崖边，被高耸石墙环绕的镇上不断传来敲打铁器的声响。

塔尔韩德没有受到特别的盘问就通过了入口。

尽管他早已不再是聚落的一员，也并非人族。

但矿坑族的守卫并不会过于仔细地盘查陌生的同族。

「......」

崖壁上挖出的巨大洞口中，可以看到滑车来回不断地穿梭。

裸露上身的男人满身汗水地搬运着煤炭和铁矿石，妇女们则用双肩扛着大量的蒸红薯，走向矿山前的休息区。

眼前的景象让塔尔韩德感到怀念。仿佛时间在此凝结，什么都没有改变。要说唯一的不同，顶多是不认识他的人增加了吧。

走在路上时，偶尔会感受到狐疑的视线，但鲜少有人对他投以冷漠的眼神。

大多数的人可能并不认识塔尔韩德，或是早已将他遗忘。

塔尔韩德神情平静，没有在意这些，笔直地朝族长的宅邸走去。

要去的地方只有一个。

「......好久不见，『险峻山峰』。你来这里做什么？」

但是，当然也有人记得他。挡在塔尔韩德面前的，是他的兄弟之一。幼年时曾嘲笑他，并被选为鑛神心腹的那名男子。

「我来见鑛神大人。」

「搞清楚自己的立场，我怎么会让你这种人见他呢。」

「......」

听到这句话，塔尔韩德默默取出了背在身后的东西。

当他揭开上等毛织物，将剑从鞘中拔出的一瞬间，对方倒吸了一口气。

映入眼帘的是漆黑的刀身。它仿佛吸收了所有的光芒那般漆黑，却不带丝毫邪恶或卑劣的气息，反而流露出一种清新与自豪的美感。

美得令人叹为观止。

「这是......？」

「是我锻造的。」

「怎么可能......」

对于矿坑族来说，自己所锻造的剑说明了一切。优秀的矿坑族能打造出优秀的武器。

因此，他无法相信这把黑剑会是塔尔韩德锻造的。

「我要献上这把剑。」

鑛神这个称号，是世界上最为优秀的锻造师的称号之一，同时也被视为矿坑族的骄傲。

当散落在世界各地的锻造师锻造出精心之作时，鑛神有义务鉴定这些成品的完成度。

当然，若是只有半吊子的水准，在那之前便会被精于鉴别的矿坑族筛选剔除。

而眼前的这名男子，正是那位鉴别者。

「......」

这名男子并不喜欢塔尔韩德。

然而，剑无法说谎。这把黑剑上没有任何装饰，也未使用特殊技术。

但是，恐怕极其坚硬。在一般的战斗中也不会绝对折断。

这是一把上乘的武器。身为矿坑族，他不能对这把剑撒谎。

「准许你通过。去吧。险峻山峰之塔尔韩德。」

「感谢你，炎刃之钢杜特尔。」

塔尔韩德想起这位昔日兄弟的名字，向他低头致意，将剑收入鞘中，再次用毛织物包裹背起。

在抵达鑛神所在之地前，塔尔韩德多次被拦下。

但每当他展示这把剑后，所有人都会让路。

\\

「鑛神」──荣耀顶峰之戈德巴尔德，比塔尔韩德的记忆中稍微老了些。

这也是当然的，毕竟塔尔韩德离开这个聚落已经有段漫长的岁月。

「你老了啊，塔尔韩德。」

「你也一样。」

「我还以为你早已饿死路边了。」

「我原本也是这么打算的。」

两人进行简短的寒暄。戈德巴尔德的妻子与心腹站在一旁。

看到这个久违的「聚落第一怪人」，他们表现出戒心，但在塔尔韩德与戈德巴尔德之间却没有丝毫紧张气氛。

因为此刻，塔尔韩德以平静的心面对着戈德巴尔德。

「......」

「......」

话虽如此，塔尔韩德并未打算与戈德巴尔德谈论什么。

他有千言万语可说。比如自己在聚落外看到了什么、经历了什么。

但他依然什么都没说，因为话语只是多余的。他默默地将自己带来的东西递给了戈德巴尔德。

戈德巴尔德也一语不发地将剑从鞘中拔出，望向剑身。

「......哦？」

看了一眼，戈德巴尔德便忍不住发出了赞叹之声。

他拿起那把黑剑，透着光线检视。

「这是一把蕴含信念的好剑......没有迷茫，也没有半点稚嫩，但多处仍可见未熟之处。若使用相同的材料与工法，我定能打造出远胜于这把剑的杰作。」

听到对方这么说，塔尔韩德的嘴角浮现一抹笑意。

这是当然的。即使他在这几年全心投入锻造，但相比于百余年不断精进的鑛神，他根本不可能望其项背。这种事他早已心知肚明。

「......呵呵。」

「有什么好笑的？」

但塔尔韩德并不是在笑那句评价。

「你想知道材料与工法吗？」

「我很好奇，这确实是一把奇特的剑。」

献上剑后，将材料与制作工法告诉鑛神并不罕见。

献剑于鑛神的目的，便是为了将制作方法留传后世。使用了何种材料、采用了何种工法，又加上了哪些创意，想要将这些留在历史的人，并非少数。

「材料是透过土魔术制成的石块。经过土魔术将其变成沙粒后，与砂铁混合，然后利用火魔术与风魔术将熔炉的温度提升到极限来熔化。再来就如同平常那样敲打、锻造，再进行淬火。冷却时，也要同时用上水魔术。」

「用土魔术制成的石块......」

戈德巴鲁德听到这番话感到些许疑惑......随即恍然大悟。

他对这种工法并不陌生。年幼时期，眼前这位乖僻的家伙曾再三地提及这种技术。

「你这是在报复吗？」

「不。我只是想为当年的事做个了结罢了。」

「......难不成你以为我看到这把剑后，会叫你回来吗？」

「没有。不过你已经说出了我一直想听的话，这样就足够了。」

就是──我定能打造出远胜于这把剑的杰作。

仅仅这句话，便让塔尔韩德感到满足。宛如从幼年时期积压于心中的阴霾终于得以释放。

是啊，没错。若戈德巴鲁德以相同的材料与工法来锻造，势必能制造出比这更为卓越的武器。

但若不借助魔术，这石块无法被敲碎，炙热的铁也无法凭区区的水彻底冷却。

没错。意思就是，假如没有人能够使用适合的魔术......

不过，如果是眼前这位天才锻造师，即使不采用与塔尔韩德相同的方法，也能巧妙地处理这些石块吧。

「那么，塔尔韩德，你有办法制造这块『石头』吗？」

「......不，能制造这东西的，是我一位朋友的儿子。」

塔尔韩德从背包中取出三块石块。

他将那些整齐地摆放在戈德巴鲁德面前。戈德巴鲁德伸手拿起其中一块，感受到其沉重时，不禁瞪大了眼睛。接着他试图将石块劈开以确认断面，但无法成功，就算用锤子敲打，也未能击碎。他对这石块的坚硬与韧性感到震惊。

同时，他的脑海中浮现了一个念头「若用这种石头来打造武具......」。

戈德巴鲁德的脸上浮现了笑容。

塔尔韩德看到那表情，满意地点了点头。

从孩提时代，戈德巴鲁德的表情就一如往昔，简单易懂。

「再过几天，那家伙会亲自来找你。」

「......」

「到时，你愿意见他一面吗？」

塔尔韩德脑中浮现出鲁迪乌斯的脸，以温柔的嗓音说出这番话。

自己已经达到目的了。从想要的人那里听到了想听的话。

再来，就是帮那位给予他契机的男人实现请求而已。

「他看起来或许有些靠不住，可能还会提出风险极高的麻烦请求......不过，虽然从外表看不出来，他其实是个非常有骨气的男人。见他一面不会吃亏的。我能以这把剑跟你保证。」

戈德巴尔德的目光在剑与石块之间来回审视。

他身旁的妻子和心腹似乎想要发表意见，但他并未打算理会。

塔尔韩德与从前相比仿佛脱胎换骨。其原因之一也许与制作这些石块的魔术师有关。

这让戈德巴尔德涌起了兴致。

「好吧，他的名字是？」

「鲁迪乌斯•格雷拉特。」

「嗯。」

戈德巴尔德点头，将这个名字深深记在心中。

看到这个反应，塔尔韩德挺起身子。

虽然仅仅是口头的约定，但已经足够了。戈德巴尔德不是会违背承诺的男人。从前塔尔韩德曾一度以为自己被他背叛，但事实上，那并非违背承诺。

那只是因为当时的塔尔韩德过于不成熟，不知天高地厚罢了。

「你要走了吗？」

「是啊。」

「以你现在的实力，不会有人再对你有怨言了。」

「我已经在米里希昂拥有自己的锻造场。想必会在那里待到生命终结吧。」

塔尔韩德如此说道，转身离开了鑛神的居所。曾几何时，居所周围已经聚集了他从前的那群兄弟姐妹。

他们的目光带着锋芒，其中有些甚至毫不掩饰对他的轻视。

「不好意思，让个路吧。」

塔尔韩德迈开步伐后，这些人还是让开了道路。

在混杂着困惑与轻蔑的视线中，塔尔韩德逐渐走向聚落外面。

没有人向他搭话，也没有人追上他。

然而，塔尔韩德的步伐轻快，心情也如久违的晴空般明朗。

长久以来的诅咒，终于解开了。

\\

而鑛神以大量石块为条件，与龙神联手的消息，则是在一个月后才传开。

** 住在剑之圣地的神
*** 「剑神吉诺·布里兹」

剑神吉诺•布里兹。

他被称为剑神史上最弱。

生涯从未离开过剑之圣地，也没有击败过强敌的逸事。

在所有剑神之中，他的知名度最低，后人甚至评价为「只是因为世代交替而成为剑神的存在」。

至于他是否真的是最弱，实际去确认的人少之又少，但有一件事毋庸置疑。

他是历代剑神中最为长寿的一位。

\\

吉诺•布里兹出生于剑之圣地。

父亲是剑帝，母亲是剑神的妹妹。

他在三岁时开始懂事，最早的记忆是练习挥剑。手持孩童用的木剑，由父亲教导他挥剑的方法。

随着这段记忆的展开，吉诺的孩提时代几乎全被剑术所占据。

每天早晨起床后进行跑步与挥剑练习，吃完早饭后开始训练，午饭后继续训练，日暮时稍作休息，吃完晚饭后再挥剑，然后入睡。

他过着这样的生活。

话虽如此，吉诺其实并不喜欢剑术。

尽管他像是理所当然那般持续训练，但那终究只是基于父母的要求而做。

他从未有过自己想要主动练剑的念头。

年幼时，这样其实也没什么问题。吉诺身边不是正在练剑的人，就是曾经练过剑的人。其他孩子也理所当然地参与训练，而身为剑帝的父亲与剑神之妹的母亲，每当吉诺学会新的招式就会赞扬他。

即使是已经隐退的邻居爷爷，每当看到吉诺拿着木剑来回奔跑时，也会夸他是个勤奋的孩子。

剑术对吉诺来说就是生活，没有任何怀疑的余地。

但吉诺慢慢长大，随着他年纪增长、级别升高，周围的环境开始改变。

一开始只因他持剑就满足的剑帝父亲，在他晋升为上级后变得更加严厉。

「要为了变得比对手更强而挥剑。你现在还太弱，不要因为一点天赋就骄傲自满。」父亲这样告诉他，比以前更加严格地进行训练。

在道场出生长大的大人们也是。他们起初露出和蔼的笑容守望着吉诺，但随着他顺利地升上中级、上级，在比试中慢慢赢不了他之后，便开始露骨地以不悦的眼神看着他。

从那时开始，剑术对吉诺而言变得索然无味。

话虽然这么说，他也没有其他想做的事情。

倘若他是其他国家的孩子，说不定会说自己想成为冒险者之类的。

然而奇妙的是，在吉诺的脑海中从未有过「离家出走」的念头。

这是因为他的父母从未教导过他这些事情，也无需教导。直到某个时期之前，吉诺甚至不知道剑之圣地外面还有另一个宽广的世界。

对吉诺来说，剑之圣地就是他的全世界，所谓的剑术与呼吸、进食一样平常。

因此，他继续挥剑。

他的青梅竹马妮娜是他唯一的朋友。

妮娜是剑神的女儿。在剑之圣地，未达到圣级的人不得进入本道场，上级以下的人包括孩子在内，都只能在家附近的道场练习。尽管妮娜是剑神的女儿，但也不例外。

虽说同辈的孩子不只妮娜一人，但能在剑术上与吉诺平分秋色的只有她。

两人之间话题相投。在剑之圣地的孩子，话题大多围绕着剑术。

尽管吉诺并不喜欢剑术，但他是个天才，这使得他的理论从孩提时代起就显得有些飞跃。

而能跟得上他的想法的，在同辈当中只有妮娜一人。

妮娜是孩子王，集结了同年龄的孩子，由自己站在这些人的顶点。

不仅是同一个道场的孩子，而是整个剑之圣地，所有道场的孩子们的顶点。

有一部分是因为她是剑神的女儿，但她也拥有相符的实力。在孩子们当中，她的剑术是最强的。对于剑之圣地的孩子们来说，剑术的实力是衡量一切的标准。

妮娜趁着剑术训练的空档，将孩子们聚在一起，建立了一个秘密组织。

那是个只有孩子的组织。吉诺在其中被任命为副队长，有一部分是因为他是第二强的人，同时也是因为他与妮娜最聊得来。

妮娜与吉诺。

他们在这群人当中，或许是唯二对剑术有不同见解的人。

证据就是，听从妮娜指示的孩子中，几乎没有人能在日后获得剑圣以上的段位。

这个组织维持了约五年，后来在妮娜成为剑圣的同时便跟着消失了。

没错，妮娜和吉诺几乎在同一时期成为了剑圣。

从历史上来看，他们达成这个成就的速度相当惊人。

尤其是吉诺，他年仅十二岁就破例成为了剑圣。

当吉诺当上剑圣时，周围的人都惊叹地说着「他应该是最年轻就当上剑圣的吧？」。

父母也高举双手拼命夸奖他。

然而，吉诺本人却不以为然。对他而言，这只是依照别人的吩咐去做而得到的结果，根本不觉得是什么了不起的事，而且他知道比自己大四岁的妮娜更强。

在妮娜与吉诺成为剑圣后，两人被允许进入本道场进行训练。

话虽如此，生活并没有变化。

日复一日，依然做着剑术修行。

没有变化。由于年龄与实力接近，总是妮娜陪他训练。

没有变化。妮娜也依然将吉诺当作自己的跟班，带着他四处行动。

没有变化。围绕在妮娜身边的人换成了年长的女性剑士，但她依然是那个孩子王。

唯一的变化，顶多就是从家里到道场的距离更远了些。

啊，不对。他接受妮娜的父亲剑神加尔•法利昂指导的机会也增加了。

他说了和吉诺的父亲截然不同的话。

「要为了自己而挥剑。」

如果要总结加尔的话，大概就是这个意思。

而吉诺的父亲，则经常在晚餐时说什么「要为了变强而挥剑」之类的话。

吉诺隐约察觉到两者的微妙差异，但究竟是什么意思，哪个才是正确的，他却始终无法明白。

无论哪一种说法，吉诺都无法真正理解。

不管怎样，只要做好自己被分配的训练量，就不会被责骂。

此外，只要在偶尔举行的模拟战中不要输得太惨，也不会有人对他说什么。

搬到本道场后，模拟战的胜率有所下降，但对手都是比他大十岁以上的成年人，就算输得多了一点，也不会受到指责。

虽然有变化......但吉诺认为并没有太大的不同。

发生重大变化的，果然是在那一天。

她来了。

艾莉丝•格雷拉特。

\\

★　★　★

\\

艾莉丝刚到剑之圣地，就以令人印象鲜明的方式登场。

她转眼间就击败了吉诺和妮娜，令在场的众人留下了深刻的印象。

完败。

但这件事本身对吉诺来说，并不算是什么重大的变化。

对吉诺而言，打输是家常便饭。

虽然他在同辈之中被吹捧为天才，但对上妮娜，他一直都是输的一方。

尽管这么突如其来的败北还是第一次，但每次与父亲或剑神交锋时，也都是以类似的结果告终。

所以不管怎么样，对他来说都没什么不同。

当然，不甘心的情绪还是有的，但剑神断言「是吉诺太天真了」，加上当晚又被父亲训斥了一顿，那些情绪很快就消散了。

他只不过是学到了一件事：「啊，原来也可以这么做啊」。

不过就算学到了这一点，吉诺还是有分寸的。他明白「在道场做这种事会引来反感，还是少做为妙」。

真正发生重大变化的，是妮娜。

妮娜与吉诺不同。她带着伤痕的脸因为不甘而涨红，那天他们两个一整天都没有说话。

在道场的训练结束，回到家后，她独自躲在后院哭泣。

一边哭，一边练习挥剑。

嘴里不断地低声重复着「饶不了你，饶不了你，饶不了你......」。

吉诺犹豫该不该跟她搭话。对妮娜而言，输给同辈想必是生平第一次的经验。而且还不仅是输在剑术上。吉诺事后听说，妮娜甚至使用了内含金属的木剑，但依然落败。

她输得并不光彩。

被击倒在地，还被压在底下痛殴，甚至因恐惧与疼痛尿湿了裤子，输掉了胜负。

这是一次极其丢脸的败北。对她来说，这样的经验还是头一遭。

从那以后，妮娜便开始针对艾莉丝发动攻击。

一开始，妮娜与其他女性剑士联手试图孤立艾莉丝。

但是，艾莉丝打从一开始就不打算与任何人为伍，这样的行为以失败告终。

艾莉丝比任何人都纯粹地渴望变强，一点也不在意剑之圣地的内部斗争。

妮娜遭到艾莉丝忽视，日常中积累了不少挫折感。

每当遇到什么事情，她总会到处散播艾莉丝的坏话，有时甚至会向吉诺抱怨。

吉诺不太喜欢那样的妮娜。在她还是个孩子王的时候，个性更为爽朗。就算不喜欢同伴中的某个人，也不会刻意排挤对方。

看在已经认识许久的吉诺眼里，当时的妮娜也相当地讨人厌。

事情的转机发生在某一天。

妮娜没有告诉任何人要去哪，突然间消失了。

当然，没有人为此感到担心。

妮娜虽然是个几乎不曾踏出剑之圣地的井底之蛙，但好歹是个剑圣。

有人认为她可能受到艾莉丝的刺激，自主地出外展开武者修行。

不仅没有人担心，反而有不少人对此表示佩服。

连吉诺的父亲都对他说「你或许也该出去看看外面的世界了。如果能斩杀一头赤龙，你这副松懈的表情或许也会有所改变」。

吉诺一度考虑是否真的应该那么做，但最终还是没有付诸实行。

因为，他对至今从未接触过的外面的世界并没有多大的兴趣。

真要说的话，甚至还抱有几分恐惧。

剑之圣地的大人们，多半知晓「外面的世界」。

不过，那也仅限于邻国或自己曾居住过的国家。

亲身游历过世界各地的人少之又少。偶尔会有人讲述一些经历，但往往是关于自己在哪里遇到什么人，又如何击败对方的武勇故事。

然而，其中有位大人没有谈论自身的武勇故事，反而分享了失败的经历。

她就是基列奴•泰德路迪亚。剑王基列奴。

她曾作为一名冒险者行走世界各地，并坦言自己实在太过愚蠢，险些在各地丧命。

「在这个世界，无论剑术多么高超都可能被杀。如果不懂魔术、算术，甚至连基本的识字能力都没有，很快就会丧命。」

基列奴以一本正经的神情这样说道，而吉诺对此深信不疑。

因为吉诺和剑之圣地的其他孩子一样，并不识字，也不懂魔术及算术。

他对这些东西没有兴趣，反倒是因为只靠剑术无法活下去而心生畏惧。

因此，他没有动念前往外面的世界。

总而言之，吉诺没有追随妮娜的脚步，就这样继续过着每一天。

两个月后，妮娜回来了。吉诺询问她旅途中的见闻，但妮娜什么也没告诉他。

不过，她的确经历了一些事情。

从那天起，妮娜变了。

她停止骚扰艾莉丝，对剑术变得更加认真，态度也更为诚恳。

她几乎不再与其他女性剑士来往，傲慢的态度也不复存在。

她将大部分的自由时间用于特训。虽说是特训，也只是一直与吉诺进行实战形式的对练。吉诺如同她的小跟班那般奉陪着她，一次又一次地交锋。两人之间没有多余的对话，只是反复切磋。

这样的日子一直持续下去。

而吉诺就是在这时开始被妮娜吸引。

\\

他发觉自己对她产生爱意，是在经过很长一段时间之后。

在这段期间，发生了许多事情。北帝奥贝尔的出现、水神列妲的出现等等。

对吉诺而言，这些事情都让他不感兴趣，但对妮娜来说并不是这样。

妮娜受到了艾莉丝的刺激，实力突飞猛进。

而吉诺因为陪着她特训，也被她带着逐渐成长。

但是，他却渐渐地无法再战胜妮娜了。

尽管以前也不常赢，但胜率变得越来越低。

不知不觉间，妮娜和吉诺之间已经拉开了巨大的差距。

对于这件事，吉诺倒也没有特别在意。

毕竟从以前开始，他就赢不了妮娜。现在只是从五次中赢一次变成十次中赢一次，对他来说并不算是多大的变化。

但是为什么呢？他不由得涌起自己被远远甩在后头的感觉。

某一天，剑神加尔•法利昂把艾莉丝、妮娜和吉诺三人叫了过来。

剑神询问他们「剑圣、剑王与剑帝的不同」并让他们回答。

吉诺完全不晓得答案为何。

但艾莉丝和妮娜不同。妮娜在思考后给出了答案，而艾莉丝则坚持自己被说错误的答案是正确的。

剑神认为这样也无所谓，然后让妮娜和艾莉丝两人决斗。

还宣布胜者将成为剑王。

结果，是艾莉丝胜出。她成为了剑王，而妮娜哭了。

看到哭泣的妮娜，吉诺心中涌现出一种难以言喻的情绪。

他下意识地握紧拳头，抿紧嘴唇。

他无法理解这份感情的本质，也不明白理由为何。或许是感到焦躁，或许是感到不甘。为什么自己没有站在那里？为什么连与那两人决斗的资格都没有？再这样下去，自己会变成什么样子？

吉诺是第一次产生这样的感情。

同时，他察觉到了一件事。

剑神加尔刚才问了妮娜「要是老子说要你从和吉诺结婚或是成为剑王两者之间抉择，你会选哪边？」这个问题。

当他听到这句话，感觉自己的脸顿时烫了起来，说不出否定的话语。

他这才明白，自己似乎喜欢妮娜。

\\

从那之后，吉诺有了些许改变。

日常的行动并没有变化，他依然完成父亲与剑神交付的训练，并持续和妮娜进行特训。即使艾莉丝离开剑之圣地，这一切也未曾改变。唯一不同的是，他与妮娜的对练变得更有水准。

产生变化的是他对剑术的态度。

他比以往更加积极，开始思考平常训练的意义，仔细分析每一招每一式，并尝试各种可能性。

这带来了显着的效果。

转眼间，他就变强到能与妮娜旗鼓相当。

这并不奇怪。吉诺本就拥有天赋，日积月累的训练也奠定了扎实的基础。

妮娜也有了变化。她成为了剑王，在艾莉丝离开剑之圣地后，会开始造访附近的村庄和城镇。她会狩猎魔物、在大城镇的道场指导剑术。

妮娜不仅提升了自己的剑术本领，也开始积极参与这类活动。

反观吉诺，他依然将自己封闭在剑之圣地。

外面的世界虽然已经不再令他感到害怕，但也始终提不起走出去的兴致。

他自己也不晓得理由。说不定根本就没有什么理由。不过要这样说的话，其实也没有非得出去外面的理由。即使妮娜不在的时候，吉诺依然埋首于训练之中，有时甚至还与身为剑帝的父亲进行对练。

然而，他却无法再更上一层楼。

他始终无法企及身为剑帝的父亲。剑神加尔曾对他说「再过不久就认可你成为剑王」，但也仅止于此。

就技术层面而言，他已经追上了父亲。

他面对妮娜时也是如此。想必面对同为剑王的基列奴与艾莉丝也是一样吧。

但他就是赢不了。总觉得还差了那么一步，缺少了某种东西。

这点他早已心知肚明。而且，他也知道该怎么做才能赢。

可是，他始终无法付诸行动。尽管心态上变得更加积极，却仍然不愿将自己置身于艰苦的环境之中。不，他曾经打算这么做。每当这个时候，他总是会这么想。

为什么非得要忍受这种痛苦来做这种事？

他没有找到答案，时光便这样流逝了。

\\

某一天，去观看阿斯拉王国加冕仪式的妮娜回来后，对吉诺这样说道：

「嗳，吉诺。我们也结婚吧？」

听到这句话，吉诺点了头。

他并不是经过深思熟虑才点头的，只是没来由地觉得这一天迟早会到。他喜欢妮娜，而且也从未感觉妮娜会与其他男人发展成这样的关系。

随后，妮娜以她一贯的急性子拉着吉诺进了自己的房间，立刻发生了关系。

两人都是第一次，虽然过程有许多生疏的地方，但就他们沉迷了整个晚上来看，至少他们在那方面非常契合。

在这令人眩目的快感中，吉诺这样心想。

我还想要更多。

回想起来，这或许是吉诺在人生中第一次如此强烈地渴望某样东西。

隔天。

吉诺带着妮娜去见了剑神。

不是妮娜带着吉诺，而是吉诺带着妮娜。

这是为了告诉剑神他们想结婚。吉诺会像这样积极主动，是极为罕见的。

「不行。」

然而，剑神二话不说就拒绝了。

一直以来对女儿教育方式不置一词的剑神，第一次给出了否定的答案。

理由很简单。看在剑神眼里，吉诺毫无魅力可言。

没有丝毫自主性，缺乏冒险心，也没有野心，只会听从别人的指令，像个摆设一样的男人。

剑神还不晓得他们已经发生了关系，但他猜想，这次结婚肯定也是妮娜先提起的。

因为吉诺这个男人从未自己真正渴求过什么，也从未试图争取任何东西。

这样的男人竟然想结婚？真是笑死人了。

不过，剑神同时也这样想。

这样也未必是件坏事。于是他说：

「想结婚的话，那就来打败老子吧。只要赢了老子就允许你们。」

剑神的本意只是想激发吉诺的斗志。

他希望能设下一个障碍，让吉诺稍微燃起干劲。

「......！」

但就在这一刻，吉诺理解了什么。有种齿轮恰好卡入正确位置的感觉。

吉诺理解了。啊，原来是这样啊。

他明白了剑神一直挂在嘴边的话。明白了自己欠缺的是什么，也明白了那个「为什么？」的答案。

原来是这样。原来事情这么简单。

吉诺感觉到眼前的雾正在慢慢消散。活到现在一直搞不清楚的那些疑问，在此刻迎刃而解。他终于得到了最后一块拼图，自己不足的一步。

也就是「目标」。

「我明白了！」

接下来的事情就很简单了。

\\

★　★　★

\\

吉诺变了。

彻底变了。

就像变了一个人。

他不再去做之前被吩咐的所有训练，也不再与妮娜进行特训。

他偷懒了？怎么可能。这是因为他开始独自训练。

这种训练不需要对手。

从前与妮娜的特训、与父亲的对练，以及多次的模拟比试，已经让他累积了足够的对战经验。

吉诺拥有致胜的理论。

如果是面对剑神流的剑士，他脑中早已有个清晰的蓝图，能让自己确实拿下胜利。

但要实现这蓝图，需要超乎常人的努力。必须要克服充满痛苦与艰辛的日子。

因此，他一直以来都没有这么做，因为没有这么做的理由。

只是依靠悔恨或焦躁那类的感情，是不可能撑过去的。

不过，现在不同了。吉诺有了目标。他想要妮娜，无论如何都想得到她。就算得承受痛苦，也想要得到她。这个目标将痛苦与艰辛，转化为乐趣与期待。

再来，他只需要磨练自己。

锻炼自己的肉体，提升挥剑的速度与力量。为了证实自己的理论，这是必不可缺的。

训练、特训、对练，这些词都无法精确地描述他的行为。

如果要找一个更贴切的词......没错，就是「作业」。

吉诺默默地完成自己该做的事。为了将自己的肉体改造成能够战胜剑神，他每天都在执行完美的作业。吉诺就像是要精确地练到自己的极限那般持续作业。若是一般人早已崩溃，不然就是搞坏了身体。

但吉诺做到了。因为他原本就具备这样的天赋。

动力、经过长时间思考的理论、完美的作业流程。

再加上他原本就有足以掌控这一切的天赋。

这四者结合，使吉诺的剑术钻研到了极致。

\\

★　★　★

\\

然后，命运的那一天到来了。

那一天，吉诺在清晨起床后，便前往住在隔壁的青梅竹马家，再次向她求婚。

他们拿起木剑对峙，吉诺将妮娜击倒后，对她说「成为我的女人吧」。

在妮娜接受后，吉诺便前往剑神的所在地。

时间是下午，本道场正好在进行模拟战。

这是剑之圣地定期举行的实战训练，用来展示每个人对自己招式的精进程度。不过在这种场合，会允许两人联手挑战更高段的对手。

吉诺默默地出现在训练场。

他身为剑王，不是独自面对两名剑圣，就是面对同级的妮娜，再不然就是两人一起挑战剑帝。

妮娜今天缺席。

那么按照惯例，他理应迎战两名剑圣。

然而，吉诺在走到道场中央后，直接将木剑指向了剑神。

道场内瞬间鸦雀无声。

「吉诺！你这是在干什么！」

最先站起来大声斥责的是吉诺的父亲，剑帝堤摩西•布里兹。

他拿起放在身边的木剑，杀向吉诺。

不，是准备杀向吉诺。但是在他刚撑起身体试图起身的时候，前倾的膝盖就被击碎了。同时，握着木剑的手也被打断，剑也应声掉在地板上。

剑帝堤摩西•布里兹震惊得瞪大双眼。

他对疼痛早已习以为常，并未露出任何痛苦的表情，但身体却不断冒出冷汗。

他的眼瞳捕捉到了挥剑后的吉诺。

吉诺只朝父亲瞥了一眼，随即转向剑神。

「剑神大人，我来迎娶妮娜了。」

他与刚才相同，将木剑指向对方，如此撂下狠话。

剑神加尔•法利昂看到那把剑，不禁露出狞笑。

「很好，那就──」

──放马过来。

话还没说完，吉诺就动了。

但几乎在同一时间，加尔也动了。

应该说，加尔的速度更快。毕竟他早已摆好了架势。

在剑帝被击倒时，加尔便从地板上捡起木剑，稍稍起身，摆出居合的架式。

这个姿势虽然有些不利，但对加尔来说并不构成真正的劣势。无论何种姿势，他都能凭借远远凌驾于对手的剑速取胜，所以才是剑神。

然而，他却无法超越吉诺的速度。

吉诺出手的速度几乎与剑神相同。不过，两把木剑虽然几乎是同速挥动，交锋的位置却稍稍偏向了吉诺那边。这说明剑神的速度依旧略胜一筹，也代表剑神挥出的剑有着速度的加成。

但就在这一瞬间，剑神感觉到了不对劲。

这一击，对剑神来说已是近乎完美。

剑神流的宗旨为一击必杀，要是被对手挡下攻击是非常不利的。

但剑神流也有一种理念，就是先用第一击破坏对手的平衡，在下一击确实将其击倒。

一直以来都是如此。

在首击拿到优势的剑神加尔•法利昂从未被反击过。

他是这么想的，但吉诺的剑比加尔至今所感受到的任何一把剑都来得沉重。

吉诺依然纹丝不动。

当然，加尔的姿势也没有被打乱。

五五波。

对加尔来说，许久没有在初次交锋体验到五五波的局面。

即使加尔的剑挥得更深，依然只是五五波。

既然如此，下一招就不同了。

加尔的剑已挥出，还需要些时间才能收回。吉诺的剑却不同，虽然挡下了加尔的剑，仍旧处于能迅速收回的位置。

双方都没有失去平衡，就时间来说也只是微乎其微的差距。

为了确实地战胜剑神加尔•法里昂，吉诺利用了这微小的差距，犹如穿针引线那般，亲手创造出这决定性的差距。

加尔•法里昂无法挥出第二剑。

\\

那一天，吉诺获得了他所渴望的一切。

\\

★　★　★

\\

剑神吉诺•布里兹。

他得到了他所渴望的一切。

妮娜•法利昂。她就是吉诺想要的一切。「剑神」这个最强剑士的称号，对他来说只不过是附赠品。

据说，他生涯都未曾离开剑之圣地。因此他的知名度在所有剑神中最低，甚至被传为史上最弱的剑神。曾师事于前任剑神的剑圣们也对他颇为排斥。

不过，吉诺并不在乎这些。对他来说，传闻根本毫无意义。

因为他击败了所有向他挑战的敌人。

这些敌人，也就是想成为下一任剑神的剑士，或是听闻了「最弱剑神」之名而来的挑战者。而吉诺将他们全数击倒了。

在成为剑神之后，未尝一败。这就是吉诺•布里兹的战绩。

若他走出剑之圣地，说不定也有可能击败水神列妲、死神蓝道夫等强者。

但吉诺并没有这样做。对他来说，剑之圣地就是他的全世界。

从一开始到最后，他从未对外面的世界有着任何渴望。

然而在成为剑神之后，无疑扩大了他的世界。

除了敌人之外，还有许多人来访，试图与剑神吉诺•布里兹加深友谊。

他们并未与他交手，有时向他请教剑术，有时与他进行商业往来。

鲁迪乌斯•格雷拉特也是其中一人。

没错。他在某一天突然造访剑之圣地。

身旁还有与吉诺关系匪浅的狂剑王艾莉丝。

甚至还带着北神卡尔曼三世，以及龙神奥尔斯帝德......

*** 「在当座之间」

现在，我正在剑之圣地的道场。

据说这里被称为「当座之间」。

我的右手边是亚历。他面带微笑，当然了，丝毫感觉不到杀气。

他的腰间佩戴着一把双手剑。那是我用土魔术制造黑色石块，再由鑛神亲自锻造而成。剑上似乎没有附加任何特殊力量，但毕竟是冠以神之名的人制作而成，品质相当不错。亚历似乎很喜欢这把接近两公尺长的剑，现在已经爱不释手。

奥尔斯帝德在我的左手边。他戴着黑色头盔，现在还没说过一句话。

就宛如静止的画面般站着，一动也不动。

虽然他安静得足以让苍蝇停在身上，但散发出惊人的威慑感，连蚊子都不敢靠近。

不过在场除了我们的人以外，都未将注意力放在我、亚历或奥尔斯帝德身上。所有人的目光都集中在站在我正前方的那个人。

那是艾莉丝。

她手握木剑站在那里。虽然表情严肃，但并未释放任何杀气。

但是，可以看得出她将手中的木剑握得极为用力。

艾莉丝站在当座之间的中央，手持木剑。

而一名手腕被折断的剑圣，正倒在她的眼前。

「......我认输。」

那名剑圣一脸懊悔地这样说道，随后起身行了一礼。

他没等艾莉丝回礼，便退到道场的一侧。

道场的边缘，有许多剑神流剑士排排站着。

应该有将近二十个人吧。

他们每个人都是剑圣，让人感到世界真是狭窄。竟然有一群剑圣聚集在这种狭小的地方。

而在艾莉丝的正对面，坐着一对年轻的男女。

我不晓得男方的年龄，但看起来大约与我相仿，这样想来，也很难判断到底该不该以年轻形容，不过在场的剑圣多半是三四十岁，相较之下他确实属于年轻一辈。

他让女子坐在旁边，搂着她的肩膀。

跟其他剑圣比起来，显得相当放松。

而且，他现在还是在奥尔斯帝德的面前。就算可以借由头盔削弱诅咒的效果，但他面对着那个奥尔斯帝德，竟然还是如此轻松。

吉诺•布里兹。

该说不愧是剑神吗？让女人陪侍在侧，还是展现出堂堂气度，完全不像与我同龄的人。

至少我根本不可能在面对奥尔斯帝德时还让妻子坐在旁边，随意地搂着肩膀或抚摸腰部。

如果我真的这么做，大概会挨揍吧。主要是被艾莉丝。

不过，偶尔看到吉诺伸手想碰触妻子的胸口，却被毫不客气地打掉，这副模样倒是让我有些好感。

女方名叫妮娜。

听说是艾莉丝的朋友，以阶级来说是剑帝。但我完全看不出她有半点剑帝的气场。

她幸福地依偎在吉诺身边，偶尔拍掉这位老公伸往胸口那不安分的手。

感觉像是完全不把我们放在眼里一样。或许这就是人们所说的「笨蛋情侣」。

「......」

那么，为什么场面会变得如此剑拔弩张，就让我来说明一下吧。

\\

前情提要！

嗨，亲爱的小朋友们，大家好！我是鲁迪乌斯•格雷拉特，请多指教！

今天，我来到了北方大地上最火热又酷炫的观光景点──「剑之圣地」。

考虑到未来的计划，我们必须先跟剑神流把事情谈妥，而且还要解释艾莉丝与前任剑神之间的因缘。

为了将这件事情做个了断，我决定前来剑之圣地问候一声。

上一次造访时没能跟现任剑神打招呼，所以这次算是二度回访。

同行的成员当然是我和艾莉丝！

据我所知，剑神流的人好像大多是还没动口就先挥剑的那种类型。所以，我决定这次尽可能不带魔术师同行。这点和上次来时一样。

当然，他们应该也懂得基本的人情道德，但这次情况与上次不同，我们在毕黑利尔王国的战斗中杀了加尔•法利昂，而他是现任剑神的义父。

在这个前提下，我要是开口请求他们帮忙，各位觉得有可能不出问题吗？

哎呀，如果现场气氛不适合开口说那种话，我也会默默打道回府。总而言之呢，因为不晓得会发生什么事情，所以就找了熟悉剑之圣地的艾莉丝和我一起旅行。

──原本预定是这样的，但这时却发生了一件惊喜。

当我提到要前往剑之圣地时，奥尔斯帝德居然罕见地表示自己也要同行。感觉他当时好像话中有话。

他可能是担心我说了什么不该说的话，惹怒了剑神吧。

换句话说，他是为了保护我才一起过来的。

反正我也没理由拒绝，就答应他了。毕竟有奥尔斯帝德在确实比较可靠。

后来，听到奥尔斯帝德说要去，亚历也跳出来说「那我也去！」。

亚历。没错，就是那个稍微有点英雄情结的家伙。就像以前的克里夫一样，以完全不懂察言观色而闻名的那位！

其实，我本来是想说「抱歉，我们不收容易惹事的人」。

虽说他平常会帮忙照顾齐格，但这是两码子事。

不过，奥尔斯帝德大人却说「随便你吧」。

如此这般，变成了我、艾莉丝、奥尔斯帝德和亚历四人一起前往剑之圣地。

\\

就这样，我们来到了剑之圣地。

呈现在眼前是一片白雪覆盖的田园村庄，是种很宁静的景色。

虽然我心里有些忐忑不安，但之前来过一次，更何况这次还有三位可靠的同伴。「这景色不错啊。」「以乡下而言，这里的刀剑种类还真不少。」「哦，发现第一位村民了！」我一个人说着些无聊的话，走着走着就抵达了剑神流的本道场。

笑脸迎人的剑圣们把我们带到了当座之间。

每个人脸上都挂着笑容，给人和谐的气氛，但不知为何，我却觉得背脊一阵发寒。

肯定是错觉吧！先不管那些，还是赶紧问候他们吧！

正当我准备开口时，一位剑圣却先说了。

「首先，我想见识一下据说打败了前任剑神的狂剑王艾莉丝小姐的剑技。」

一开始就来这招？我还来不及回头看艾莉丝的反应，剑神就耸了耸肩说「随便你吧」。

于是，修罗场正式开幕。

那些面带笑容的剑圣依旧保持着微笑，但全身却散发出惊人的杀气，一个接一个地挑战艾莉丝。

虽然脸上带笑，手中也只是木剑，但可以明显看出他们的杀意。

因为他们打算假借对练之名，直接用木剑将艾莉丝置于死地。一看就知道他们完全没有打算点到为止。

不过，艾莉丝好歹也是剑王。

她没有让任何一位剑圣讨到便宜，轻而易举地将他们一一击倒。

每当艾莉丝一个又一个地收拾掉对手，剑圣们脸上的笑容也逐渐消失，逐渐变成充满怨恨的神情，甚至连杀气都懒得隐藏了。

但在这种充满肃杀之气当中，仍有一个人感觉置身事外。

那就是吉诺。就连妮娜都被剑圣们的杀气搞得有点不知所措，吉诺却像是在表示这种事情根本无所谓一样。

结果，就演变成现在这种剑拔弩张的场面啦！

\\

我试着勉强自己打起精神说明了经过，可是......

唉，胃好痛。为什么事情会变成这样啊......

感觉一开始就搞砸了吧？这下肯定不行了。这种气氛根本不可能好好讨论啊。

不过让我辩解一下。刚才根本来不及阻止啊。我说真的，事情发生得太快了。

吉诺的一句「随便你吧」还没说完，艾莉丝便理所当然地拿起木剑，走到了场中，而那名剑圣也早已在道场中央等候多时。

当我要落坐现在这个位子的瞬间，艾莉丝已经打倒了一个对手了。

接着还没来得及阻止，那群剑圣就纷纷说着「下一个是我！」「接下来轮到在下！」一个接一个涌上来。你们是当自己当成「碗子荞麦面」吗？

不过，我感觉也是时候该阻止这场闹剧了。

剑圣的人数约莫二十多人，而艾莉丝已经击败了二十个人以上。

现在正在对决的是最后一名剑圣。

那么，想必会轮到那个人出场吧。

剑神吉诺。

即使他现在一副悠然自得的模样，但若是底下的人全都被击倒，他应该也不得不站出来。而那些剑圣们想必就是在等待着那一刻。他们期待剑神出马，击杀那名红发女剑士。他们等待的是向杀害前任剑神的仇人复仇的瞬间。为此，他们提议了这场比试，甚至自愿担任「前菜」。

我现在感到很后悔。

也许我们根本不该来这里。就算是艾莉丝，对上剑神也很难全身而退。而我也无法想像自己有办法在这样的距离下与剑神过招。

不过，同时我也感到庆幸。

就算我无法及时反应，奥尔斯帝德和亚历应该能挡下剑神的剑。

艾莉丝或许无法毫发无伤......但只要不死就是万幸了。

她自己也应该早有这样的心理准备。总之，我非常感谢愿意陪同前来的那两个人。

是说，如果打扰了剑神与艾莉丝之间的战斗，肯定也没办法跟他们交涉了。

实在无法预测具体上会怎样发展......

不过接下来的发展肯定会让人胃痛，这点倒是毋庸置疑。

尽管如此，我还是得阻止他们对决。我的工作就是努力将局面引导到对话上面。

听好了，鲁迪乌斯。这些人虽然血气方刚，但只要诚心诚意地跟他们沟通，应该还是会听进去的。

你会努力吧？Let's fight！

「唔......我认输。」

就在这时，最后一名剑圣也倒下了。

他和之前的剑圣一样，捂着自己的手腕。

更确切地说，基本上每个人都是手腕中招。虽说有右手跟左手的不同，但艾莉丝八成是以同样的招式收拾对手吧。不过剑圣们的怒火也因此更加高涨。

接下来会是妮娜吗？不，妮娜似乎没有打算动作。虽然是我的猜测，但应该会是剑神先有所行动。

若是剑神动了，就轮到我出马了。

我要仔细看准时机，后发先至。在剑神刚起身的瞬间，我就要用很谦逊的姿态这样说。

「每场都是精采的比试呢。光是看着就让人口渴了。不如先稍作休息，来喝杯茶如何？」就以这样的台词开场吧。

嗯？这样讲真的可以吗？

听起来会不会像在挑衅？

应该要再好好夸奖一下败北的剑圣们才对吧。

「哎呀～剑之圣地的各位果然非常投入对练啊」......就这样讲吧。

这样一来，他们也可以找个借口说「毕竟这只是对练，输了也无所谓」。

好，我准备好了，要出手喽，我要上喽。

「......」

然而，剑神没有任何动作。妮娜似乎也没有站出来的打算。

「结束了吗？」

在这剑拔弩张的气氛中，剑神吉诺•布里兹以轻松的语气说道。

他的语气显得轻描淡写。

「所以呢？你们来这里有何贵干？」

嗯？看来他在战斗之前愿意先听我们说话。

感觉不像是剑神流的作风......不过，这是个好机会。我稍稍往前踏了一步，这样说道：

「......首先是想向各位道歉。」

「为什么道歉？」

「是关于前任剑神的那件事。」

话语刚落，周围的剑圣们气氛瞬间转变，仿佛在心中大喊着「好耶！」。

对方主动给我们一个契机！好了就是现在！复仇Let's go──！

如果他们是狗，想必已经摇着尾巴兴奋地狂吠起来了。

我有一瞬间也不禁觉得应该换个婉转一点的说法，但这样也没意义。

因为这的确是事实。

「......」

然而，剑神却露出了疑惑的表情。

看到他这种表情，反倒让我也感到困惑。

难道我说错了什么话吗？差点害我忍不住四处张望。

然而，剑神好像很快领悟到了什么，点了点头。

「啊，这么说来，我很久以前有听妮娜提过。她好像说要协助你们来着？也对，既然你们杀死了要合作对象的父亲，当然需要道歉呢。」

他讲起这番话来真的很像事不关己一样。

在场的剑圣们反而比我还要傻眼。

「不过，师傅......前任剑神加尔•法利昂是基于自己的意志向你们挑起战斗的吧？既然这样，反而应该是我们该向你们道歉不是吗？如果这是剑神流全体的问题，那破坏协定的是我们才对。这部分要怎么看？其实我对这些情况不是很了解。」

我才想问你「现在到底是怎样啊？」。

我现在真的在跟剑神流的头头对话吗？

我原本预想的，是一个像阿托菲那样难以沟通的对象啊......

吉诺的态度太沉稳了，他给人一种很奇妙的感觉。真要说的话，更像在和北神流的人对话。当然，是除了阿托菲之外的北神流剑士。

「呃......」

冷静点，先回答对方的问题。

「妮娜小姐与艾莉丝只是稍微谈过这件事，还没有正式签订协定。其实，我们以前曾为了这件事来过一次，但当时你似乎有要事在身，所以只好先离开......后来妮娜小姐有没有向你提过这件事呢？」

「我有说过，不过就那么一次。」

妮娜含糊地点了点头。听到这句话，吉诺也随之点头。

「至少，我们从未听说『要与龙神奥尔斯帝德阵营敌对』这件事。但既然发生了战斗......」

吉诺微微眯起了眼睛。

「这代表，前任剑神选择了与你们为敌的道路吧？」

周围剑圣们的气势顿时高涨。

感觉可以听得到他们在内心呐喊着说：

好耶！说得太好了！来，快拔剑，快跟他战斗！快点，快点！

「......等等，请你先冷静一下。」

我反射性地这样说道，吉诺听到后却是耸了耸肩。

「我现在看起来像是很慌张吗？」

「不，你非常冷静。只是，你想想看，我们是为了避免与你们继续为敌才来这里道歉的。我们并不希望与拥有强大武力的剑神流诸位为敌，反而希望能与各位强者好好相处。我们已经准备好与你们建立友好关系。不论是剑或粮食的流通、基础设施的维修，还是建筑相关方面我们都能提供协助。反过来说，若是选择与我们敌对，就会完全失去这些好处，应该会造成不少损失才是，对吧？」

「唉......」

见我滔滔不绝地这样说明，吉诺叹了口气。

也许是我说明得太长了。如果把对象换成阿托菲，应该再讲更短一点才对。不过他看起来也没有单纯到只要提供一瓶梦幻美酒就能让他说「好耶我要成为你们的伙伴！」。

吉诺瞥了我一眼，一脸嫌麻烦地说道：

「非得从头解释你才能明白吗？前任没有对我们说过什么。也就是说，那并非剑神流整体的决定，他是以个人身分选择与你们交战。因此，这与我们毫无关联。所以我也不打算与你们争斗。比起那些，我更重视这个。」

语毕，吉诺将妮娜拉到身边，将脸埋进她的发间。

妮娜虽然脸上泛着红晕，却坦然接受了这举动。

看起来是很甜蜜啦，但在人前应该克制一下吧？

看看艾莉丝，她都满脸通红、睁大双眼，还环起双臂张开双脚，摆出了一副随时准备开战的姿势。

不过，现在跟我对话的真的是剑神吗？

他的应对过于理性，反而让人害怕，整个很毛骨悚然。

一般来说，剑神流这么高阶的人物应该比较像是那种「闭嘴！少说些莫名其妙的废话！我要报杀父之仇！宰了你们！」然后拔剑冲过来吧？啊，不对，那是阿托菲的风格，是北神流才对。

不过，应该也很类似吧？

啊，该不会现在站在我面前的其实是个替身，或者只是负责对外联系的事务员。

「......」

但若真是这样，我倒是求之不得。

虽然亲人遭到杀害依然能如此平静，稍微有点令人不舒服就是......

不过，若是他们是在经过深思熟虑之后，才决定将自身的感情摆在一边，优先考虑未来的话，倒是可以理解。

他们想必从很久以前就在思考这件事，并做出了决定。

「既然这样，那么容我郑重地......」

「请稍等！」

这时，有位剑圣突然大喊一声站了起来。

他的脸涨得通红，指着我们......正确来说，是指向奥尔斯帝德。

「我们尊敬着前任剑神，看着他的剑获得启发，精进自我，让自己变得更强！可是他却被杀了啊！就是被这群家伙！他们杀害了对我们有大恩的前任剑神，难道我们要默不作声地接受这一切吗！让他们这样瞧不起我们剑神流真的好吗！」

「那就由你上吧。去拿真剑过来，我会在旁边看着你的。」

吉诺不假思索地这样说道。

剑圣顿时愣住。

「啊......？」

「他们本来就是抱着这个打算才来的吧。狂剑王艾莉丝、龙神奥尔斯帝德、北神卡尔曼三世。在他们的背后，还有鲁迪乌斯•格雷拉特用魔术支援。即使你们所有人联手，势必也无法伤到他们分毫，只会落得全灭的下场吧。」

「这......」

「好了，你上吧。我会负责帮你们收尸，也会为你们举行葬礼。我不晓得你们死后是否能保全所谓的荣誉，但肯定能感到满足吧。」

「......」

听到这番话，剑圣坐了下来。

他无比懊悔地紧握着拳头。

接着，他用颤抖的声音说道：

「我们......真的只能屈服于他们吗？对前任剑神的仇人，不战而降......」

「所以我就说了，不希望那样的话你就自己动手吧。我可没打算强迫你们什么，一切随你们自己的自由，像父亲他们那样。」

吉诺看起来很不耐烦。

对我来说，与其现在招惹他们的怨恨，还是希望他们能干脆地接受现实。

不过，若是接受的方式牵涉到生死，就有些沉重了。

「话说起来，剑帝不在呢。」

就在这时，艾莉丝随口说了一句。

吉诺转头看向艾莉丝。

「父亲他们已经离开了剑之圣地。他们似乎很不满我成为剑神。」

看来刚才所说的「剑帝」并不是指妮娜。

从吉诺的话来看，他所指的应该是前代剑神的直系弟子，也就是那两位剑帝。

听他这么一说，在场确实看不到类似的人物。

「他们现在大概是在阿斯拉、米里斯，或者王龙那边开设道场吧。不过，其实当初是我离开也可以啦......」

吉诺耸了耸肩，这样说道。

「那么，你们的目的就只是为了道歉吗？老实说，我反而觉得你们不用为这种事专程过来一趟。」

果然让人有些不舒服。虽然我并不打算对别人的事情说三道四，但吉诺这个人给人的感觉有些冷淡，还是该说太豁达了......总之就是很不舒服。

「不，其实说来话长，我们现在正与一个名为『人神』的存在战斗──」

尽管内心是这样想的，但我还是将我们与人神之间的战斗详细告诉了他。

不管怎么说，吉诺看起来算是一个能够沟通的对象。

如果能在不动干戈的情况下达成协议，那自然是再好不过。

虽然跟预期的状况不太相同，但这结果也不算坏。抛开剑神这层滤镜来看，吉诺其实是个通情达理的好青年。既然如此，不如先争取到合作，待会儿再一起喝杯茶，增进感情吧。

这样一来，那股诡异的感觉肯定也会消失吧。

「──总之，为了未来，希望在此郑重邀请剑神流的各位与我们合作。」

「我拒绝。」

......嗯？什么？

「我们不会合作。」

剑圣们闻言，顿时大声高呼「哦哦！」，但他们也显得很困惑。

「............意思是，你们要站在人神那边吗？」

「不，我们也不会与你们敌对。」

嗯──？

「也就是说......你们选择中立？我能问一下理由吗？」

「我要遵守师傅的教诲。」

「教诲？」

「师傅常把一句话挂在嘴边。『要为了自己而变强』。说实话，我当时完全不懂这句话的意思。我想，在场也没有其他人能理解这句话。就连父亲他们也不明白。不过，当我渴望得到妮娜的时候，我总算明白了师傅说的话。剑，应该要为了自己而挥。只是纯粹地，为了实现自己的目的而挥剑。」

吉诺滔滔不绝地说着，他的声音中充满了确信。

他认为自己现在所说的便是真理，并对此深信不疑。

「所以，我无法与你们合作。我只会为了自己挥剑。这一切都是为了我自己。」

「......就算家人陷入危机，你也不会挥剑吗？」

「不。如果那时候我依然爱着家人，我会挥剑。」

说到这里，吉诺第一次直视着我。

他的眼神坚毅而凛然，那样的目光与艾莉丝所形容的那名人物截然不同。

「还是说，如果不合作，你们就打算杀了我的家人？」

道场内的气氛瞬间一冷。

吉诺的话语同时释放出寒意与杀气，让人不禁汗毛直竖，全身冒出冷汗。如果现在只有我一个人，搞不好已经尿裤子了。

因为他是剑神。是那个瞬间击败前任剑神加尔•法利昂的现任剑神。

虽然给人的感觉诡异，但他无疑是当今世上屈指可数的强者。

我现在终于明白了他的可怕之处。

「不会。毕竟我也爱我的家人。」

「是吗，那我就放心了。」

杀气收敛了。

「鲁迪乌斯先生果然和传闻中的一样。」

「什么样的传闻？」

「你为了家人而自愿成为龙神的属下，甚至还摧毁了一个国家。」

「嗯......基本上是这样没错。不过，我可没有摧毁整个国家。」

「而且，比我想像中还要有胆识。」

吉诺的视线稍微移动了一下。

他的目光看向我的左右──艾莉丝、亚历，以及那些剑圣。他们全都将手放在剑柄上，有些甚至已经拔出了剑。

我回头看了看身后的奥尔斯帝德，他丝毫不为所动，果然了得。

我虽然一样动也不动，但我不好意思说自己只是被杀气吓得动弹不得。

「也就是说，你是值得信赖的人。」

你到底怎么得来「也就是说」这个结论的？

「正因为你是这样的人，我才能安心地告诉你。我不会跟你们合作。我的剑，只会为我与我所爱之人而挥。」

「......啊，原来如此。」

我稍微能理解吉诺•布里兹这个人了。

简而言之，他想亲手保护自己所爱之人。这一点和我没什么不同。

我当初就是没能做到，才会哭着向奥尔斯帝德求助。不过，他肯定相信自己能做到，并且也拥有那样的实力。顺带一提，他也没有打算去做其他事情。

当然，他有剑神这个身分，就算宣称中立，也免不了会有敌人找上门。

不过，他显然不想让自己主动树敌。

虽然我不晓得前任剑神为什么没有被归类为「所爱之人」就是了。

不对......我想错了。前任剑神的理念是「为了自己而活，也为了自己而死」。所以他认为自己要是因为前任剑神的死而指责我们的话，也未免太无理取闹了。

「......唔──」

看来很难说服他啊。

吉诺已经厘出自己的结论。除非我们放弃与人神战斗，或者他像我一样，意识到仅凭自己的力量无法保护所爱之人，否则他的想法是不会改变的。

无论我再怎么努力说服他，也只是徒劳无功。毕竟他心意已决。

一旦决定了就会贯彻到底，真不愧是剑神流的头头。

「这样啊......那么，如果在梦中遇到人神，还请你千万小心。不要因为他以家人的名义说谎，而导致你最终失去一切。」

「好的。」

虽然遗憾......但也只能作罢了。

至少从刚才的对话，可以确定他并不打算与我们为敌。

虽然不会成为盟友，但也不会成为敌人。他了解我是怎样的人之后，选择信任我，并表示「希望维持中立」。这话应该别无虚假。

既然如此，这次就这样打住吧。

「如果有一天我死了，由别人接任剑神的位置，就请你到时再来吧。这终究只是我个人的选择而已。」

「我会这么做的。」

我转身看向奥尔斯帝德。

他的表情被头盔遮住，害我完全不晓得他在想什么。

「所以，奥尔斯帝德大人，这样可以吗？」

「......嗯。」

听到我这样询问，奥尔斯帝德缓缓点了点头。

\\

随后，我们帮剑圣们治疗了伤势，接着由亚历带着他们对练。

现在我被安排坐在道场的主位，看着亚历依序与剑圣们进行实战练习。

剑圣们虽然手中握的是木剑，但他们的每一剑都蕴含了强烈的杀气。

他们大概觉得，万一在对练中失手杀死亚历也不会有什么问题吧。

亚历倒是应付得很轻松就是了。

但或许是因为剑圣们实力不俗，又或者是亚历有所大意，偶尔也有人能击中他。

用的是光之太刀。

不过，说穿了也只是木剑。击中的瞬间，木剑便应声断裂，而亚历毫发无伤。

斗气也太作弊了吧。

不过，剑之圣地的木剑还真是特别。

据说木剑的内芯嵌入了类似铁的材料，大概是为了模仿真剑的重量吧。

若是无法缠绕斗气，一旦打中要害是很有可能会丧命的......

啊，所以这里才只有剑圣啊。因为只有上级以上的人才能使用斗气嘛。

「话说，奥尔斯帝德大人......您这次为什么会同行呢？」

我忽然压低声音，这样询问坐在旁边的奥尔斯帝德。

「我想亲眼看看吉诺•布里兹。」

「意思是，要确认他和以前的他有什么不同吗？」

「嗯。」

吉诺依然让妮娜随侍在旁，默默地观看着对练的情况。

艾莉丝坐在妮娜的旁边，两人似乎正在交谈。

由于不时能听到「加尔•法利昂」这个名字，她们大概是在谈论前任剑神是怎么死去的吧。

「那您觉得如何？」

「没变。单纯执着、顽固，只为自己而活。」

「哦？」

「年轻时的吉诺相当不稳定，因此，他也会因为人神的话而动摇。但就他现在的样子来看，就算放任不管也不成问题。」

「原来如此。」

不会敌对，站在中立的立场。换个角度来想，这样对我们来说也算是同伴。

更何况他也不太可能成为人神的使徒。

虽然他不会采取任何着眼于未来的行动，但其实其他国家也并非都有积极地投入这件事。重要的是，他不会成为人神的爪牙。

虽说无论他愿不愿意，也可能会在哪一天成为我们的敌人......

但如果揪着这一点不放就没完没了了。

「我......我认输......！」

伴随着沉重的声响，一名剑圣倒在了道场中央。

下一名剑圣立刻喊道：「接下来换我！」随即站到道场中央。

......回过神来，我才发现剑圣不是瘫坐在地上，就是已经倒下了。

剑圣全灭（今天第二次）。真不愧是北神卡尔曼三世。

「......」

道场内一片寂静。

「──最后，他是这么说的：『自由活着的家伙更强，真棒啊』这样。」

在这片沉默中，艾莉丝的话语轻轻响起。

她似乎很惊讶自己的声音听起来竟然如此清晰，不由得抬起了头。不过，她很快抿紧嘴角，用威吓驱散了那些剑圣聚集过来的视线。

剑圣们低着头，发出了懊悔的声音。

他们的视线不时飘向吉诺。

还能听到一些低语，例如「让弟子去战斗算什么」或者「把剑神流的名誉当作什么了」。

吉诺依旧摆着飘然自若的表情，对这些话充耳不闻。

搞不好他平常就经常听到这类指责。

「剑神大人，您也一起参加对练如何......？」

或许是见吉诺没有回应，其中一名剑圣这样说道。

他正是最先挑战亚历、屡战屡败的那个男人，脸上还留着一大片瘀青。

这人也是刚才喊出「请稍等」的那个人。

「我就不用了。」

「这是为什么！」

「为什么？是你们说想让他们来指导对练，所以我才拜托他们的。既然你们已经练完了，事情也就到此结束了吧？」

剑圣的脸变得扭曲。

他全身颤抖，似乎无法压抑住内心的愤怒，终于大声喊了出来。

「前任在的时候还比较好！那位大人一直在守护剑神流这个流派的名誉！就算有这种家伙踏入这里，也绝对不会让他们嚣张！这样剑帝大人们离开这里也是情有可原！您身为剑神，却连一个示范都不肯为我们做！修行全都是独自进行，每天在道场只顾着让女人伺候，打情骂俏！现在仇人都找上门来了，说要让我们屈服在他们底下，您却依然无动于衷！若是放下这笔仇恨，选择臣服也就罢了，但您却只是模棱两可地宣称中立！而且还只是因为不想树敌？您究竟是怎么样啊！这到底算什么剑神啊！」

道场内顿时一片死寂。

吉诺的表情毫无波动，依旧是一副飘然自若的模样。

不过也可以说他愣住了。他的表情就仿佛在说「这家伙在说什么啊？」。

然而，那名男子似乎也意识到自己说得有些过分，脸色微微发青。

「剑是属于个人的。就算我赢了，也不代表你们得到胜利，也无法守护你们的名誉。」

吉诺淡淡地说道。

「我是因为想和妮娜像现在这样腻在一起，才会击败前任剑神。所以现在也在这么做。我并不是想要守护名誉，也不是为了照顾你们。如果不满，你们也大可离开。我就算不当剑神也无所谓，但如果让出这个位置，你们一定会赶我出去吧？要我离开可以，但现在不行，毕竟孩子还小。」

剑圣们低声说着「啊......」再一次低下了头。

仿佛能听到他们内心无奈地说着「不是这样的，为什么您就是无法理解呢？」

一种令人不快的气氛弥漫在道场中。

剑神与门下弟子们之间的关系，显然并不融洽。

或许吉诺还是太年轻了。如果无法处理好这些问题，他很有可能会在内部树敌啊。

「别这么说，至少示范一次给他们看吧？」

打破沉默的是妮娜。她原本靠在吉诺身上，这时坐直了身体，端正跪坐。

「我也想看看你战斗的样子。」

「好吧，既然妮娜都这么说了。」

吉诺缓缓站起身来，动作轻巧得仿佛刚才那副沉重的模样是装的一样。

该不会他其实被妮娜吃得死死的吧？是说，这种状态真的算得上「稳定」吗？在我看来反而显得很不稳定。

真的没问题吗？

「艾莉丝，你也来体验一下怎么样？吉诺变得很强喔。」

「......好吧。」

听到妮娜将话题转给自己，艾莉丝也站了起来。

她看向我这边，然后随手扔了什么东西过来。我下意识接住后，发现那是她的剑。

魔剑「喉笛」，那把曾为前任剑神所爱用的武器。

吉诺与艾莉丝走向道场中央。那里站着亚历，他耸了耸肩问道：

「那么，谁先上呢？」

「当然是弱的那个。」

艾莉丝这么说着，把亚历推到一边。

亚历像是在表示同意那般点了点头，随后走回我们这边。

他连一滴汗都没流。其实我好像还没看过他流汗......啊不对，之前在毕黑利尔王国看过一次，当时他全身都湿透了。

「......这里的人不行啊。」

亚历坐到我旁边，小声嘀咕了一句。

「明明有机会能与比自己强的人对练，却毫无学习的心态。」

「这点我也看出来了。」

「对吧？这样的话，我奶奶那边的人要强多了。」

阿托菲亲卫队应该不太一样。因为他们是不学的话就会死，只能逼着自己变强。

正当我这么想时，目光重新回到道场，只见艾莉丝已举起木剑。

那是一如往常的上段动作。

是进攻型的架式。

而与之对峙的剑神吉诺则是把剑摆在腰间，是居合。提到居合，让我想起了基列奴。

不过相较之下，吉诺的动作显得十分沉静。基列奴在摆出居合架式的同时，尾巴也会轻轻摇晃，带着仿佛随时准备伺机咬住猎物般的凶猛气息。

而吉诺的架式则是「无」。就如同刚才的奥尔斯帝德，仿佛时间停止了一般静止在那里。

没有丝毫破绽。

「......」

艾莉丝微微向前拉近距离。

对手是剑神，如果没有刚才那番对话，我现在早已看得心惊胆战。

就算被击中，应该也不至于致命吧。

应该不要紧吧？还是姑且用一下预知眼好了。不过就算用了，我也看不见他的剑路......若是真的发生要害会被击中的那种状况，奥尔斯帝德会及时出手制止吗......？

「艾莉丝小姐的话，应该不用谁来喊开始吧？」

「嗯。」

艾莉丝点了头。

当我这么想时，战斗就已经结束了。

﹝艾莉丝的惯用手被打断，单膝跪地。﹞

﹝艾莉丝的木剑飞上半空，撞到道场的墙壁，掉落在地。﹞

我的预知眼只看到这些。

而一秒后，这一切成为了现实。

「......」

在我眼中，似乎是艾莉丝先发制人。

就在那声「嗯」尚未落音时，她的木剑前端已经化为残影。

然而，结果却是艾莉丝败北。恐怕是速度不敌对方，导致惯用手被击断。

不对，不仅是惯用手。

仔细一看，她起步的那只脚的拇指也歪到了诡异的方向。

两次挥剑......所以是连击吗？

艾莉丝的手臂被打断，脚趾也被打断。

但是，她并没有停下来。这种程度的伤势是不可能让她停下的。她的脸上挂着狞笑，依然用剩下的那只脚往前突进。

......我本来是这样以为的，但她放松了身上的力气。

不打了。

「到此为止。」

道场内响起奥尔斯帝德的声音。

随着他的声音，场内传来了一些「哦哦」或「真精彩」的赞叹声。

然而，这些声音零零散散，感觉好像还带着一丝困惑。

「刚才发生了什么事？第一剑被闪开了吗......？」

「第一剑是针对脚踝的攻击。她没能完全躲过，所以脚趾就......」

「但第二剑呢？」

可以听到剑圣们这样低声讨论。

刚才的对决快到甚至让他们无法判断是否已经分出胜负。

然而，结果是显而易见的。艾莉丝满脸冷汗瘫坐在地，而剑神吉诺则手持木剑，把手放下站在那里。

明明要求示范，结果却连对方做了什么都看不出来。

这样也失去了示范的意义啊。

剑圣们似乎为此感到懊悔，表情都很僵硬。

但同时，场内也浮现出松了口气的氛围。他们大概是觉得这样一来至少保住了剑神流的体面吧。如果这能让他们一吐怨气，也算是皆大欢喜。

「不愧是剑神大人！第一剑瞄准的是出脚的脚踝，而那剑路以最短距离从脚踝袭向手腕。无论是击中脚踝，还是被对方闪避，都能让对手的第一剑稍稍延迟，从而完美衔接到对手腕的反击。若是对自己的剑速没有绝对的自信，是无法办到这种技巧的！」

亚历稍稍拉高了声音，以剑圣们也能听得见的音量这样说道。

剑圣们听完他的解释后，也纷纷点头说着「原来如此」。

感谢你，解说员亚历先生。

亚历一副理所当然地坐着，但看向吉诺的眼神中带着些许责备之意。

那副表情仿佛在说「既然是师傅，就应该教导他们啊」。

「如果是以前的艾莉丝小姐，就算是现在这种情况也会继续冲上来吧。」

「如果现在必须逞强的话，我就会这么做。」

「原来如此，不愧是艾莉丝小姐。」

吉诺微微一笑，缓缓点头。

而艾莉丝也随之露出浅笑。不过，她的额头已满是冷汗。虽然她不是那种会因为手腕和脚踝骨折就发牢骚的女人，但还是会痛的。我站起身，快步跑向艾莉丝身边。

「你还好吗？」

「......没事。快点用治愈魔术，不要乱碰喔，这里可是有人的。」

「好。」

我立刻咏唱治愈魔术，治好艾莉丝的骨头。

由于事先被警告过了，手并没有往胸部或屁股伸去。

虽说是模拟战，但这股冲击力甚至能打断骨头。万一这种攻击打在头部或颈部，光是想就让人不寒而栗。

不过，奥尔斯帝德也在场，只要身体和头没分开，应该还算安全吧......

不过话又说回来，剑神啊。前任剑神也是如此，根本看不清他们的剑路。

真的很不想与这种人为敌。

「感觉如何？」

「......很强。虽然不甘心，但我根本赢不了。」

我原本是问她伤势的，但艾莉丝的回答却是这番话。

她的嘴唇抿得死紧，看来是真的很不甘心。艾莉丝虽然已经生了两个孩子，但她一直都很认真看待剑术。想到这里......不对，应该只是单纯输了让她觉得不甘心吧。毕竟她从以前就很讨厌输。

「那么，换我来吧。」

带着艾莉丝回到座位后，亚历满脸兴奋地站了起来。

然而，他忽然回头看向奥尔斯帝德。

「奥尔斯帝德大人......可以吗？」

「无妨。随便你吧。」

奥尔斯帝德这个回答，是在允许亚历打倒吉诺吗？

如果亚历能在这里打倒吉诺，七大列强的顺位也有可能因此而有所变化。

宣称中立的吉诺•布里兹。现在因为他击倒了艾莉丝，使剑圣们心中有所释怀。

这样剑之圣地应该会继续维持中立的立场。

但若是剑神败北，事情就另当别论了。不论吉诺本人如何，剑之圣地的大部分人都可能会选择与我们为敌。

怎么办？我应该阻止他们吗？

......不，既然奥尔斯帝德说可以，那我也无须多言。

我只需要考虑如何处理比试结果带来的影响即可。

「开始吧。」

亚历走上前。

虽说是使用木剑进行模拟战，但他们可是北神与剑神。就算说是......七大列强之间的对决也不为过。

毕竟现在的第七位只是徒有虚名嘛。

谁会赢呢？就经验上来看，果然还是亚历有利吧。虽然吉诺击败了前任剑神，但他还年轻，经验不足。而亚历想必也有背负着北神卡尔曼三世之名的自尊。

更何况，亚历刚才已经先看过剑神的剑路了。

「......」

亚历摆出了中段架式，吉诺则保持着居合的动作。

到底是谁会先出手？通常情况下，应该是剑神流的吉诺主动进攻，北神流则采取防御。

但也有可能出现相反的情况。

「......！」

先动的是亚历。

这次我看见了。

他的中段架式突然化为没有前置动作的突刺。

然而，吉诺以更快的速度挥出剑。他配合突刺的前端挥剑，稍微偏转了亚历剑尖的攻击角度......我也只能看到这里。

下一瞬间，吉诺的木剑消失了。

再次看到时，亚历的左手已经被打断。同时，他往后退了一步，地板上留下一道黑色的线痕。这恐怕与刚才击败艾莉丝时相同，是依序攻击手腕与脚部的连击。

亚历以被打断的手重新举起木剑。

原本以为断掉的那条手臂几乎是在瞬间愈合。

这是拥有不死魔族的血统才能展现的绝活。他的眼神燃起斗志，仿佛在说接下来才要让对方见识北神流真正的实力。

可是，吉诺继续向前推进，展开了压倒性的猛攻。

每当吉诺挥剑，亚历的手臂或腿便再次被打断。不过区区骨折似乎能迅速愈合，亚历并没有陷入无法战斗的状态。

\\

但也仅此而已。吉诺丝毫没有给亚历反攻的机会。

亚历或许尝试了许多战术。

但看在任何人眼里都一目了然，这些攻击都未能对吉诺造成威胁......

「......我认输。」

最终，亚历放下了木剑。

他身上没有伤痕，但衣服已经裂得破烂不堪，木剑的剑尖也已经裂开。

反观吉诺，他依然毫发无伤。身上仅仅泛着一层汗水......展现出压倒性的实力。

我没想过他们之间的差距竟然如此悬殊。亚历明明已经那么强了......

此刻的吉诺，或许已经具备了列强级别的实力。不对，他本来就是列强。

「哎呀，实在厉害。果然是人外有人，天外有天。」

「不，毕竟你是单手，而且如果是实战，还不晓得结果会怎么样。」

「如果用真剑，恐怕我现在早就被砍成碎片了吧。」

亚历坦然承认了自己的败北。吉诺仅仅使用了一把没有剑鞘的木剑使出居合，便展现出如此实力。

如果是真正的居合，速度只会更快，也就是说用真剑的话，两人之间的差距可能还会更明显。

「那么......」

亚历手持木剑，回到了我们这边。

他明明输了，但脸上的表情却很痛快。

尽管看起来还是有点不甘心......但没有像毕黑利尔王国时那样大喊大叫。

这代表他也确实改变了。

「......嗯？」

突然间，我注意到道场内的视线全都集中在我身上。

就连吉诺也是，明明比试已经结束，却依然站在道场中央。

目光直直地看向我。

「列强第七位......」

「我们能看到列强之间的战斗了。」

「虽然剑神大人不可能会输，可是......」

「或许还能见识到龙神奥尔斯帝德的招式。」

可以听到剑圣们这样低声议论着。

咦？嗯？什么情况？

「鲁迪乌斯大人，请让他们见识一下吧。当初击败我的魔导铠之威！」

亚历低声在我耳边这样说道。

我听到后，立刻脱口说出早已准备好的台词。

「哎呀～剑之圣地的各位果然对修行十分有热忱呢！不过天色已晚，肚子也有些饿了。不然我们就先到此为止吧！」

大家对我很失望。

\\

就这样，我们在剑之圣地的拜访结束了。

虽然我在剑圣们之间被贴上了「胆小鬼」的标签，但我根本不在乎。

剑之圣地......不，吉诺•布里兹想必会在他有生之年坚守中立的立场。

对我来说，这样就足够了。

*** 「妮娜·布里兹」

那天，鲁迪乌斯等人在剑之圣地留宿了一晚。

他们被安排在本道场的一间客房过夜。

然而，唯独艾莉丝被妮娜邀请到了她家。原本艾莉丝也打算和鲁迪乌斯等人一起在道场过夜，但在妮娜的强烈请求下，她同意了。

妮娜的家，也就是吉诺•布里兹的家。

当艾莉丝对鲁迪乌斯表示她会独自前去过夜时，鲁迪乌斯有些担心，同时稍微反对了一下。这是因为刚刚剑圣们刚才表现出来的那种态度。

他们因为加尔的死而充满杀气。想必鲁迪乌斯也感受到了那股杀气吧。

不过据艾莉丝所知，剑之圣地一直以来都是这样。

基本上大部分剑士并不是想变强，而是想被别人认为自己很强。

尽管如此，他们也没有胆量在道场外对更强的对手发动奇袭。

会做那种事的，顶多只有以前的艾莉丝吧。

于是，艾莉丝留下鲁迪乌斯等人待在道场，独自前往布里兹宅邸。

那个地方位于道场稍远处，是个与「剑神」的名号极不相称的小房子。

「来，请进。吉诺这个时候应该还在修行，还没回来。」

「打......打扰了。」

艾莉丝带着紧张的情绪走进了玄关。

回想起来，这或许是艾莉丝人生中第一次去朋友家作客。

虽然她经常在造访阿斯拉王国时与住在首都的伊佐露缇见面，但从未去过她家。

如果是去邻近的道场倒还是有，但要说「到家里作客」感觉又不太一样。

「欢迎回来──！」

迎接紧张中的艾莉丝的，是充满活力的声音。

随着「咚咚咚」的脚步声，同时从屋内跑出来了两个孩子。

「妈妈！欢迎回来！」

「欢迎回来──！」

一个是充满活力的男孩，右手握着一把木剑，脸上挂着灿烂的笑容。

另一个是女孩，看起来还很幼小，正追着男孩小跑步冲了过来。

两个孩子跑到玄关，一看到艾莉丝的身影后忽然愣住，脸上露出惊讶的表情。

「这是我的儿子涅尔，还有女儿吉儿。你们两个，这位是艾莉丝，是妈妈的朋友喔。」

「我......我是艾莉丝，请多指教。」

被妮娜介绍为朋友，艾莉丝抿着嘴，微微低下头。

涅尔听到「艾莉丝」这个名字后，眼睛瞪得圆圆的。

「红色头发！难道说，你是狂剑王艾莉丝？」

「红──头发！」

吉儿似乎没听懂，但还是模仿着哥哥的话复述了一遍。

虽然不太明白发生了什么事，但吉儿似乎对艾莉丝产生了兴趣。她露出闪闪发亮的眼睛，缓缓靠近艾莉丝。

八成是对红色的头发感到好奇吧。吉儿伸出手，想要触摸艾莉丝那波浪般的红发。

但在她碰到之前，便被妮娜一把抱了起来。

「不可以──」

「啊──红的──！」

吉儿不满地发出抗议，挥舞手脚动来动去。

看到这一幕，涅尔惊慌失措地大喊。

「吉儿不可以！那是狂剑王喔！碰到会被吃掉的！」

「会咬人吗？」

吉儿用怯怯的眼神看向艾莉丝。

见状，艾莉丝浅浅一笑。

因为这两个孩子的互动，不由得让她想起了几年前的亚尔斯与齐格。

「我不会吃你的。」

「......说这种话，只是想让他们放松警惕再吃掉吧？」

说这句话的是妮娜。被她用怀疑的眼神看着，艾莉丝立刻抿起嘴唇，板起一张脸。

看到她这样，妮娜不禁笑了，然后将吉儿递给她。

「开玩笑的。要抱抱看吗？」

「好。」

艾莉丝从妮娜手中接过吉儿。

吉儿一开始还有些害怕，但或许是察觉到艾莉丝抱孩子的手法比自己母亲还要熟练，心情立刻好了起来。

她抓住艾莉丝的红发，开心地笑着说「红色的，好漂亮──！」随后将头发含进了嘴里。

「啊，喂，吉儿！不能吃！」

「......唔──」

被妮娜训斥后，吉儿立刻把嘴松开。虽说头发是红色的，但毕竟是头发，怎么可能好吃。此时艾莉丝的头发已经变得黏糊糊的。

「反而是我被吃了呢。」

艾莉丝笑着说，同时轻轻抚摸吉儿的头。

看到这一幕，妮娜露出意外的神情。

想不到那个艾莉丝竟然会有这种反应。

不，之前去阿斯拉王国时也曾目睹过类似场景。艾莉丝如今也是一位母亲，所以能表现出这种母性的举动。

「知道不好吃的话，以后就不要再吃了喔？」

「嗯！」

艾莉丝将吉儿放下，吉儿开心地蹦蹦跳跳，随后跑回了屋内深处。

「我是涅尔•布里兹！」

就在此时，涅尔像是与吉儿互换那般上前一步。

他单膝跪地，行了一礼。

「狂剑王大人！您是本人吧！能见到您是我的荣幸！」

「......我是艾莉丝•格雷拉特。不用对我低头啦。」

「不！那个！那个！我从以前就一直......」

涅尔眼中闪烁着光芒，抬头仰望着艾莉丝。

他露出期待的表情，正准备说些什么。

「好了好了，到此为止。涅尔，你要把艾莉丝堵在玄关到什么时候？至少等晚餐后再说吧。」

妮娜在这时突然插话，打断了涅尔。

她将手放在涅尔头上，然后用稍微带点力道的动作揉了揉他的头发。

「好......」

涅尔露出不满的表情低下了头。

他很想继续听艾莉丝说话，如果可以的话，甚至希望她陪自己对练......但母亲一定会反对的吧。一直以来都是这样。每次有知名剑士来到剑之圣地，母亲从不允许他与这些人接触。

不满的涅尔被晾在一旁，艾莉丝则被妮娜引导进了屋内。

\\

「大家都变了呢。」

晚餐后，艾莉丝在客厅休息，与妮娜聊了起来。

吉诺不在这里。他在晚餐后带着孩子们进了另一个房间。

从里面传来了孩子们的笑声，看来他正在陪孩子们一起玩耍。

「从来没想过大家会变成这样呢。」

妮娜、艾莉丝和吉诺。

以前在三人之中，总是吉诺略逊一筹。他都以一副不服气的样子挥剑，对剑神的提问也无法给出像样的回答。而如今他不仅迎娶了妮娜，甚至达到了能一击打倒艾莉丝的境界。

艾莉丝对这样的事实感到难以置信。

尽管加尔也曾经提过，但亲眼见到后，艾莉丝发现吉诺完全变了个人。

「妮娜。你也变了。在道场时竟然连剑也不拿。」

妮娜也变了。

曾经那么拼命追求变强的她，却只是在道场里看着艾莉丝比试，甚至还任由吉诺上下其手。如果是以前的妮娜根本无法想像到这种画面。

「因为啊，我肚子里已经有下一个孩子了。」

妮娜这样说着，轻抚自己的腹部。

\\

从外表看不太出来，但仔细观察，能发现她的小腹确实已经微微隆起。

「吉诺要我继续以剑帝的名号自居，但我大概已经准备退休了。」

「你这样就满足了吗？」

看到妮娜的笑容带着一抹自嘲，艾莉丝将疑问脱口而出。

妮娜垂下视线，但脸上却浮现出满足的神情。

「嗯......我很满足。虽然也有点想继续练剑的念头，但怎么说呢？不可思议的是，心里并没有多少遗憾。或许在被吉诺打败的那一刻，我的剑就已经结束了吧。」

「你输了？」

「是啊，在吉诺挑战剑神之前，他对我说，如果他赢了，就要我成为他的女人。然后我们认真决斗了一场，结果我输了。」

「很浪漫的求婚呢。」

「对吧？」

妮娜回想起当时的情景，轻轻笑了。

在那天之前，妮娜一直梦想成为世界上最强的剑士，也就是剑神。

然而，那个梦想在一瞬间就破灭了。吉诺的实力就是如此强大。就像要让妮娜的努力显得有多么渺小，仅用一击便击败了她，就像白天的艾莉丝那样......

说不定，如果对手不是吉诺。

不是那个从小就像跟班一样被自己使唤的青梅竹马，或许她也不会有这种想法。

如果是其他人，妮娜可能会像输给艾莉丝时那样，奋起直追，即使流着泪也会将心力投入到剑术。

但对手是吉诺。

吉诺为了与自己结婚而变强，然后击败了她。

接着，他直接走到剑神加尔•法利昂的面前，拿下了胜利。

随后吉诺带着剑神的称号回来，霸道地夺走了妮娜的唇，顺势将她压倒在地。

那一天，无论是心还是身体，妮娜都完全变成了吉诺的人。

妮娜深知，不可能靠着平凡的努力就成为剑神。

光靠努力，仅凭天赋都是不可能的。哪怕是同时拥有这两项条件，也未必能达成那个境界。

在那之前，吉诺就像被妮娜拉着般，付出了与她同等的努力。

而在建立了那样的基础后，他又超越了妮娜，付出呕心沥血般的努力。

最终，吉诺达到了那个境地。

那就是名为剑神的境界，是只有极少数人才得以触及的高峰。

所以，妮娜认为吉诺理应获得「相符的回报」。

用加尔•法利昂的话来形容，这份回报就是「随心所欲」。剑神是可以随心所欲的。

正因如此，就算吉诺表现出像今天这样的态度，妮娜也不会说什么。她有自己的想法，也有想说的话，只要自己一开口，吉诺肯定会听。

不过她会觉得，假如自己多说什么，反而会让吉诺的实力瞬间削弱。

妮娜没办法这么妨碍他，因为吉诺已经成为自己憧憬的对象。

总之，妮娜舍弃了剑术，选择投入另一件事。

那就是养育孩子。她对此感到满足。

「那我问你，艾莉丝，你现在满足吗？」

「很满足。」

「明明丈夫还有两个妻子？」

「没什么，这很正常吧。我父亲只娶了母亲，但我祖父却对好几个人出手。而且，鲁迪乌斯的爸爸也有两位妻子。」

「虽然我不是米里斯教徒......但我还是无法想像多妻的生活。」

艾莉丝当然也有不满的时候。

她也曾想过，若是鲁迪乌斯的妻子只有她一人，肯定会非常幸福。

没有人来打扰，两人可以从早到晚一直独处。

不过说穿了，也就只有两人而已。

一旦与「现在的格雷拉特家」相比，这样真的会更好吗？

如果家里没有希露菲和洛琪希......那么，势必也不会有露西、菈菈、齐格还有莉莉。

亚尔斯与克莉丝依然会在，虽然少了其他孩子，但艾莉丝和鲁迪乌斯之间或许会生出更多孩子。但是......艾莉丝无法想像比他们更好的孩子。

没错，正是因为了解现在的生活才会感到不满足。

一天的训练结束，全身汗水淋漓时，会有人递来毛巾擦汗。

当她准备进浴室冲洗汗水时，会有满身泥巴的菈菈被推过来一起洗。

帮孩子洗完澡离开浴室后，会发现替换的内衣和衣服早已准备好了。

这些互动既不会过于黏腻，又能随意分担彼此的工作，保持着一种恰到好处的距离感。

希露菲与洛琪希。艾莉丝实在很难想像要如何将她们从现在的生活中剔除。

再说，现在的生活就很充实了。看着孩子们的成长不仅令人开心，也很有成就感。

再过不久，也会更正式地教孩子们剑术。

相比剑术，露西更重视魔术，菈菈还有些懵懵懂懂，不过亚尔斯与齐格对剑术充满兴致。齐格甚至已经开始学习北神流了。

该如何教他们，想像他们会如何成长。

就算只是思考着这些事情，艾莉丝也感到幸福。

「艾莉丝，你也变了呢。」

「是啊。」

「以前的你，恐怕会直接踹飞那些孩子吧。」

「真失礼，我才不会踹孩子。」

「以前还像个孩子一样，现在却能好好照顾孩子了。」

「毕竟我已经生两个了。」

「那第三个呢？」

「孩子已经够多了。」

「那方面呢？」

妮娜突然问道，艾莉丝的脸瞬间染上了红晕。

「......那......那方面倒是还想要再多一点。」

这是艾莉丝的真心话。

不过，她实在是不喜欢怀孕期间那种沉重且不自在的感觉。

「不管怎么样，现在的艾莉丝真的很好相处。」

「我也觉得现在的妮娜比较好。以前总觉得......有点麻烦。」

「我想也是。」

以前的妮娜个性锋利尖锐。

她不仅自以为是最强的，也觉得地位比自己低的人怎么样都无所谓。

如今她之所以能彻底放下那份傲慢，一部分原因是与艾莉丝的接触，但更重要的是因为与吉诺结婚。

「啊，对了。伊佐露缇也结婚了，你听说了吗？」

艾莉丝忽然想起了另一个人。

伊佐露缇•克尔埃尔，如今被称为水神列妲，担任水神流宗主的女人。

「嗯，我收到的信上有提到她要举行婚礼了。不过我现在怀孕没办法去。」

「那她生了孩子的事呢？」

「这我还是第一次听说。男孩？女孩？」

「女孩。她叹气地说自己身为水神，没办法生那么多孩子，很可惜无法生个继承人。」

「她也辛苦呢。不过，她的伴侣是北帝吧？伊佐露缇生了女孩，他没有生气或觉得遗憾吗？」

「杜加不会说那种话。他是个好人。」

艾莉丝一边这么说着，一边回忆起往事。

回想起来，对伊佐露缇和杜加的婚事提出最多意见的人，或许是鲁迪乌斯。鲁迪乌斯对杜加有着强烈的信任感，因为杜加在毕黑利尔王国的战斗中救了他一命。

他是鲁迪乌斯的救命恩人。

因此，当鲁迪乌斯得知那个单纯、正直又有些容易受骗的杜加要与那个外貌协会的伊佐露缇结婚时，他第一个反应是「该不会是为了钱吧？」或是「她会不会搞外遇？」甚至为此偷偷调查了伊佐露缇的背景。

明明伊佐露缇也帮过鲁迪乌斯啊......

总之，杜加是个深受鲁迪乌斯信赖的单纯男人，绝不可能因为孩子的性别而感到遗憾。

艾莉丝还记得之前看到杜加的时候，他笑眯眯地把长得像母亲的女儿扛在肩上。

听说他还主动包办了扫地、洗衣和照顾孩子的工作。

甚至连一向不怎么处理家务的艾莉丝听到后都忍不住说「伊佐露缇也应该做点什么吧？」

她永远记得伊佐露缇在那时尴尬地移开视线，低声说「因为他比我还会处理家事嘛......」。

「希望以后换我们的孩子们成为激励彼此、共同成长的伙伴。」

听到妮娜的话，艾莉丝也点了点头。

「是啊，不然你也可以让他们去魔法大学留学。」

「听起来很有意思。不过要去留学的话，吉诺肯定不会同意的。他是那种想把自己爱的人永远留在身边的类型。」

「这样你的孩子们一辈子都无法离开剑之圣地了呢。」

「等时候到了，他们会自己跑出去的。」

与艾莉丝这样的对话，让妮娜轻笑出声。

如果是和以前的艾莉丝，实在难以想像两人会有这种对话。

「嗯？」

艾莉丝忽然感觉到什么，转头望去。

在通往客厅的入口处站着一名少年。

是涅尔。他手上拿着一本书。当他与艾莉丝四目相对后，他好似下定了决心那般快速地朝她走来。

「那个！狂剑王大人！」

「......怎么了？」

「你......你认识这本书上的人吧！」

他递过来的那本书的书名是《斯佩路德族的冒险》。

这本书艾莉丝很熟。是由诺伦撰写，鲁迪乌斯将其整理成册，札诺巴与爱夏负责销售的那本书。

「你是指瑞杰路德？还是诺伦？」

「诺伦......呃，您居然连作者也认识吗！啊，对耶，你们的姓一样......！」

「诺伦是我的义妹，是鲁迪乌斯的妹妹。」

「您说的是列强第七位『泥沼』鲁迪乌斯对吧！又名龙神的左右手，『魔导王』鲁迪乌斯！」

「没错。你知道得很清楚嘛。」

「我从妈妈那里听说过关于斯佩路德族还有艾莉丝小姐的事！也听吟游诗人讲过泥沼和狂剑王的故事！我想说真的好厉害，一直都很想亲眼见您一面！」

涅尔用闪闪发亮的眼神仰望着艾莉丝，激动地说道。

对这名少年来说，艾莉丝是在吟游诗人讲述的故事当中的登场人物。

换句话说，就是传说中的存在。与父亲吉诺不同，他对「外面的世界」兴致勃勃。

涅尔希望自己有一天能离开这片土地，成为会被吟游诗人传唱的那种存在。

这正是他的梦想。

「是吗，那是我的荣幸。」

艾莉丝感觉到自己的嘴角好像快要上扬了。

但是，为了不破坏眼前这位少年的梦想，她绷紧表情，装得一本正经地点了点头。

脑海中浮现的是洛琪希那副端庄的神情。

「鲁迪乌斯和奥尔斯帝德也有来这里，你可以在他们回去前去见他们一面。北神卡尔曼三世也在喔。」

「可以吗！」

涅尔抬头看着艾莉丝，激动得几乎要跳起来了。

因为能同时见到列强第七位、列强第二位，还有以北神英雄传奇而闻名遐迩的卡尔曼。

父亲的实力犹如怪物般强大，而他们是与父亲同等水准，甚至在那之上的存在。

涅尔从未想过竟然会在这样一个普通的日子遇上那样的传奇人物，简直是梦想成真。

「那个......」

这时，涅尔低下头，将书藏到身后，忸忸怩怩地磨蹭着膝盖。

「狂剑王大人，您曾经在世界旅行对吧？」

「是啊，从魔大陆到米里斯大陆，甚至连中央大陆的边缘都去过。我还去过天大陆。不过，贝卡利特大陆倒是没去过。」

「您能不能......能不能告诉我当初冒险的故事呢？」

「我的？不是鲁迪乌斯的吗？」

「是的！我想听狂剑王大人的故事！」

艾莉丝听了后嘴角上扬，直接点头答应。

回想起来，以前自己也很喜欢听这类故事。她经常缠着基列奴，要她讲述各种冒险经历。

然而，她从未想过自己有一天也会成为那个讲故事的人。

当然，亚尔斯和齐格也时常缠着艾莉丝，要求她讲以前的经历......但和那种感觉又有点不同。

因为这次她不是以母亲的身分，而是被视为英雄看待。

不过艾莉丝无法理解为何会这样，只觉得有点高兴。

「我想想......那就讲讲当初被转移到魔大陆的故事吧。」

艾莉丝一脸欣喜地开始讲述往事。

看到这一幕，妮娜的嘴角也不自觉地露出一抹微笑。

「真的变了呢......」

自己改变了，艾莉丝也改变了。

就算讲得再好听，现在也很难说她们两人是激励着彼此的伙伴，但妮娜却感觉与艾莉丝的距离变得更近了。

最初见面时，她认为自己绝对无法与艾莉丝好好相处。

在艾莉丝成为剑王，离开剑之圣地的时候也是。尽管内心对她抱有某种程度的尊敬，但要以挚友形容彼此的关系是有点牵强。

但现在不同了。尽管对艾莉丝的尊敬有所减少，但却多了一种从未感受到的情感。

虽说有好一阵子没见面了，如果再次见到伊佐露缇，说不定也会有类似的感觉。

妮娜几乎没有什么从小一起长大的朋友，这种感觉对她来说非常罕见。

「艾莉丝。」

「──然后，瑞杰路德突然就杀了那个绑架宠物的犯人......怎么了？」

「下次我们带着孩子，一起去找伊佐露缇玩吧？」

听到这句话，艾莉丝先是错愕地眨了眨眼，随后点了点头。

「好啊。」

吉诺成为剑神后，一切都变了。

照剑神那个样子，剑之圣地今后势必会发生更多的变化。

目前的状况应该不会持续太久。

吉诺也说不定会在某一天被其他人轻易击败。

这就是作为剑士而活之人的宿命。剑士本就是不稳定的一种生物。

不过，这份友情一定能长存。

因为自己已经不再是剑士了。

妮娜如此深信着。

** 「格雷拉特家的孩子们」(特稿短篇)

「咚！咚！咚！」一阵声音响起。

清脆的木剑碰撞声中，夹杂着人的喘息声。

「喝！」

「哼！」

在格雷拉特宅邸的庭院里。

两名年轻人正以单手持着木剑展开对峙。

其中一人是栗子发色的少女。

她身上的披风随着动作飘扬，运用充分的离心力挥舞木剑，虽然年纪尚轻，攻击却异常锋利。

最引人注目的，是她没有持剑的左手。

她将那只手轻轻张开，不时在空中拍一下。伴随着这个动作，她的身体便像撞墙的皮球般弹跳，动作瞬间变得难以捉摸。

少女借此大幅左右移动，甚至偶尔加入上下摆动，逐步给对手一击又一击的有效攻击。这些变幻自如的动作既难以预测，却又显得优雅而美丽。

她的对手是红发少年。

他穿着稍微有些脏污的练习服，紧握木剑努力迎战。与少女相较之下，少年的动作稍显僵硬。

他并未像少女那样使用魔术，而是仅以剑技对抗。

尽管没有使用魔术，但他稳稳踩踏地面，展现出稳健有力的动作，抵挡少女的木剑，同时勇敢地发起反击。

遵循了剑神流之型的朴实斩击忠于剑术基础，比少女的动作更加迅速。

然而，他却始终无法击中少女。不是被闪避就是遭到化解，反而还露出致命的破绽被对方轻轻还以一击。

「好，一分。」

「还没完呢！」

实力差距显而易见，但少年毫不气馁，继续向少女发起挑战。

而这场比试，有三个人在一旁愣愣地看着。

并排而坐的是一名蓝发少女、一名绿发少年。他们旁边还站着一名金发少年。

顺带一提，还有一只体型硕大的白犬，蓝发少女正将脸埋在这只狗身上，半梦半醒，似乎对这场比试毫无兴趣。

栗色头发的少女与红发少年。

两人的对决持续了一段时间，终于，少女果断地向前踏出一步。

「哈！」

伴随着如裂帛般的气势，木剑由上而下猛然挥落，击中了少年的额头。

「砰！」响起了清脆的撞击声。

「好痛啊啊啊啊！」

少年的额头被劈出伤口，痛得在地上来回翻滚。

伤口深深裂开，鲜血顺着额头滴到下巴。

「啊，抱歉，下手太准了。」

少女慌张地跑向少年，默默地将手靠在他的额头上。随后，一道绿色的光芒涌现，少年额头上的伤口以肉眼可见的速度愈合了。

「唉──」

少年乖乖地接受治愈魔术的治疗后，直接仰躺在地。

「果然还是赢不了露西姐啊。」

「这也没办法吧，毕竟亚尔斯才十岁嘛。」

「可是我只比露西姐小三岁而已啊......」

「差个三岁就差很多了吧。而且你也没输给齐格啊。」

露西与亚尔斯。

自从米里斯那次旅行结束后，亚尔斯远比以前对剑术更有热忱。

他的母亲艾莉丝对所有孩子向来一视同仁地教导剑术。看到亚尔斯展现出干劲后，她不禁非常激动，努力将自己所知的一切倾囊相授。

接受英才教育且才华洋溢的亚尔斯转眼间吸收了母亲们的教导，逐渐成长为一名像样的剑士。不过因为自己还没拿出什么像样的成果，他没什么真实感。

所以，亚尔斯经常会像这样单独召集孩子们，反复进行秘密特训。

以艾莉丝的角度来看，她大概会说亚尔斯并非缺乏实战经验，而是空挥练习还做得不够。但亚尔斯是继承了艾莉丝血统的男孩，会觉得只是空挥太无聊了，他想要的是一个对手。毕竟艾莉丝在他这个年纪时也是如此，想来也是理所当然。

「是说，露西姐，你从手放出风来改变身体方向的那招很厉害耶。是跟白妈妈学的吗？」

「不是喔。是我听说爸爸以前用过，然后自己想出来的。」

「哦，爸爸以前也是像那样战斗的吗？」

「现在应该不是了吧？他说那只有小时候才会用......」

「那我也应该试试吗？」

「嗯......要是用在实战中，威力可能会不够，所以我觉得你还是努力提升剑神流比较好。如果不是在剑术的对练，我自己也不会用这招，毕竟我是魔术师嘛。」

「可是露西姐的魔法剑术很帅耶。克莱夫哥之前也夸奖过你吧。」

「是吗......」

露西表现得对此不以为意，但她的视线却偷偷瞥向了正在一旁观战的金发少年。

与坐在旁边的齐格感情要好地聊着天的那名少年，名叫克莱夫。

由于他也是亲戚，偶尔会参加这群孩子们的秘密训练。

所以虽然是训练，露西也刻意在训练服上面披上了自己喜爱的披风，而且不只是用剑术战斗，还运用魔术让披风飘扬起来。

她想要成为风之妖精那般的存在。

就是以前父亲讲过的童话故事里面提到的四大精灵之一，风之西尔芙。

西尔芙有着一头绿发，身边总是缠绕着微风，在空中翩翩起舞，是一位美丽的精灵。

露西曾经深信这位精灵真实存在，但她在学校跟朋友说这个故事后，对方却回应说「我从没听说过有这种东西」。就算向老师请教，老师也说不晓得。甚至在图书馆中翻遍文献后，依然没有找到任何提及西尔芙的纪录。

风之西尔芙跟切达人一样是想像出来的生物的这个事实，让露西大受打击。

但即使如此，风之妖精对露西来说依然是个憧憬。

想让自己在意的男孩子看到这个模样，或许正是露西的少女情怀所致吧。

「比起那个，快做伏地挺身！我们约好输的人要做的吧！」

「知道啦～」

亚尔斯在露西面前摆好伏地挺身的姿势，随后数着「一、二」开始运动。

在这个孩子们的秘密特训场有个规矩，就是输的人必须进行基础训练。

「来，下一个，该轮到菈菈了吧！快点上来！」

照理说，这时应该会轮到下一位对手登场，但......

「......已经五轮了。休息一下吧。」

菈菈明显提不起劲，整个人懒洋洋地靠在雷欧身上。

不过她没装睡就已经算不错了。

菈菈以魔术师来说相当优秀，擅长用狡猾的战斗方式出奇制胜，另一方面，她在剑术方面却显得兴趣缺缺。也许她没有那么喜欢活动身体吧。

不对，每次她搞恶作剧时总是敏捷地到处乱窜，或许单纯只是不擅长剑术罢了。

不过她虽然表现得心不甘情不愿，还是参与了这个特训，或许内心有些自己的想法吧。

「那齐格呢？」

「嗯，我也不打了......」

齐格才八岁，是这四人当中胜率最低的一个。

但是在膂力方面，却拥有完全不像是这个幼小的年龄应具备的力量。在陷入剑锋互抵的胶着状态时，他甚至会有一瞬间压制住亚尔斯。

另外，他的战斗方式也与露西和亚尔斯略有不同。

他和亚尔斯一样，战斗时都以剑术为主，但其中掺杂了明显不是从艾莉丝那里学来的动作。

......不过，齐格是在哪里向谁学了这些剑术，其他三人都心知肚明就是了。

「那就休息一下吧。」

露西这么说着，坐到了还在做伏地挺身的亚尔斯旁边。

看来要坐在克莱夫身边还是会觉得有点害羞。毕竟她正值这个年纪。

况且，克莱夫现在正在和齐格聊天。

她不知道他们聊的是什么，但克莱夫年纪轻轻却成熟稳重，知识渊博，讲话内容也很有趣。

想必是在讲最近读过的某本书，让齐格听得津津有味吧。

「我说露西姐。」

忽然，正在伏地挺身的亚尔斯低声说道。

「你从学校毕业后要做什么？」

「去下一所学校。」

听到他那略显认真的问题，露西随口回答。

「爸爸不是说我从拉诺亚魔法大学毕业后，要去阿斯拉王国的王立学校就读吗？虽然我不知道为什么非得去那种地方，但可能是因为我们家也算阿斯拉贵族的一员，需要学点贵族的规矩之类的吧......？」

「我不是问那个，是再之后的事。」

听到亚尔斯继续追问，露西再度看向亚尔斯。

亚尔斯在伏地挺身的同时低头看着地面。

「亚尔斯，你应该会继承爸爸的衣钵吧？」

「我是不知道啦，但妈妈她们是这么说的。」

主要是艾莉丝偶尔会说「亚尔斯是我们家的继承人！」从那以后，格雷拉特家就理所当然地将亚尔斯视为继承人。希露菲和洛琪希似乎也没有异议。

不过就算被称为继承人，亚尔斯也不清具体要做些什么。

将来是否会像鲁迪乌斯一样，去奥尔斯帝德那里工作呢？

「什么叫不知道啦。亚尔斯，大家对你这个继承人可是寄予厚望耶。菈菈也好像有什么重要的使命，你们两个应该更有干劲才对呀。」

「要这么说的话，露西姐继承不就好了？你的剑术和魔术都比我们强啊。」

「我......因为，又没有人对我抱有期待......」

「没那种事吧？」

亚尔斯这样脱口而出。

「就是有！」

露西突然大声喊了出来。

「爸爸从来没说过对我抱有期待，或者问过我将来想要做什么！就连生日礼物也是，你们收到的是剑或魔杖，而我却......！」

不仅是亚尔斯，连坐在远处的其他三人也瞪大双眼看向露西。

露西顿时感到难为情，觉得自己很丢脸。

到底在对比自己小三岁的弟弟说什么啊？

爸爸对自己不抱期待，明明是因为自己努力不够......

「......！」

露西的眼角泛起了泪光。

她明知道哭也无济于事，但眼泪还是扑簌簌地落下。

她一直不懂，为什么爸爸从不对自己抱有期待？

无论是剑术还是魔术，她都认为自己已经足够努力了。在学校的课业也是，她的成绩一直很好，作为一个姐姐，她也自认有尽力做好榜样。

可是，爸爸从未对她说过希望她做些什么，希望她成为什么样的人。

他总是对露西说「你就随心所欲地生活吧」。因为她是长女，不需要特别照顾，就冷漠地对待她。

「我......我也是啊，爸爸也从来没对我说过期待什么的啊......」

\\

亚尔斯一边这样说，同时慌张地四处张望。

在亚尔斯眼中，姐姐露西是个无可挑剔的人物。

至少在他们这群兄弟姐妹之中，露西无疑是最出色的。

由于她年长三岁，露西在亚尔斯眼中总显得特别成熟。

三年后，当亚尔斯与现在的露西同样年纪时，他也无法做到露西现在能做到的事情，也不敢保证自己能照顾莉莉和克莉丝这些年幼的妹妹。

除了剑术以外，亚尔斯觉得自己在其他方面根本无法胜过露西。而即使是剑术，在可以使用魔术的模拟战他也不是露西的对手。

如果连露西都不被期待，那么家里的孩子们又有谁会被期待呢？

假如爸爸真的对露西不抱有任何期待，那么对自己应该也是这样。

再说，亚尔斯从来没听爸爸说过希望自己成为继承人之类的话。

只是红妈妈和爱夏提到过这件事，其他妈妈们也没有特别否认，所以亚尔斯才隐隐觉得自己就是继承人而已。只是因为自己是长子，而阿斯拉贵族有这样的规矩，所以他才会这样认为。

「那个......露西姐......」

如果是平常的亚尔斯，听到露西说这种话肯定会激动地反驳回去。

要不是当场发怒，就是憋在心里默默地生气。

亚尔斯的个性就是这样。

不过，露西是第一次说出这种话。印象中她也从来没像这样生气过。

即使是被菈菈的恶作剧气到，她的生气也只是像「气噗噗」那样可爱的感觉，终究只是为了教训菈菈而发脾气。

没错，露西一直都是个完美的姐姐。

她从不会像这样表露内心的情绪，不做坏事，也不会抱怨、不会示弱，是个帅气的姐姐。

所以，亚尔斯此刻的情绪不是愤怒，而是困惑。

他不知道该如何回应才好。

如果对方是偶尔会吵架的菈菈或齐格，他或许已经直接回嘴了，可是现在......

「露西，你还好吗？」

不知何时，克莱夫已经移动过来，坐到露西旁边。

「......」

比亚尔斯年长一岁的这名少年，比实际年龄更加成熟。

他为人认真，在学校成绩优秀，个性温柔又善解人意，不过有时也会对学弟妹相当严厉。与同龄的菈菈相比，他显得更加沉稳。

「我们都知道露西很努力。」

「......嗯。」

克莱夫轻轻地抱住露西，抚摸着她的头安慰她。

「等一下再向亚尔斯道歉，好吗？」

「......嗯......不，我现在就道歉。」

露西吸了吸鼻子，然后向依旧保持伏地挺身的姿势、僵在原地的亚尔斯低下了头。

「对不起，亚尔斯。姐姐刚才讲了很坏的话。」

「不会，嗯......我也很对不起......」

亚尔斯也向露西道歉。

尽管他不清楚自己究竟做错了什么，但他记得有人教过他，一旦让女孩子哭了，无论如何都要先道歉。好像是蓝妈妈说的，也有可能是白妈妈说的，搞不好是爱夏说的。

总之，自己一开始就不该问露西从学校毕业后要做什么。

不过，他就是想问。

他想知道这位完美的姐姐对将来有什么规划。

而且听到露西表现出完美姐姐的风范，给出漂亮的回答之后，亚尔斯认为自己或许能从中得到什么启发。

只是他万万没想到，姐姐竟然会像这样大吼大叫。

「对不起，亚尔斯。我先带露西回家喔。」

「啊......嗯，我知道了。」

克莱夫这样说完，便搂着露西的肩将她带回屋内。

亚尔斯一句话也说不出来，只是愣在一旁看着他们。

而在露西与克莱夫离开的同时，菈菈和齐格也走了过来。

还有看起来很担心的雷欧。

「我吓到了。」

菈菈这样开口说道。

「没想到露西姐也会那样生气......」

齐格也附和道。

亚尔斯听着感情要好的姐姐与弟弟这样说，稍微冷静了下来，点了点头。

「该怎么说呢......原来露西姐也有很多烦恼啊......」

他原本以为露西完美无缺，没有任何烦恼，但事实并非如此。

「露西姐──」

菈菈像是要接着亚尔斯的话，突然开口。

这个总是让人摸不清在想什么的姐姐，有时会说出一些关键的话。

亚尔斯感觉她似乎对这件事知道些什么，于是集中精神仔细听着，生怕漏掉重要讯息。

「她一定会和克莱夫结婚吧。」

然而听到的却是这句话。

「啊......那当然啦......」

他有些无语地点头。菈菈经常会让人以为她要说些重要的话，结果却冒出一些让人意想不到的内容。

她关注的部分总是和亚尔斯他们不太一样，感觉有些脱节。

「不过我不是说这个啦......」

「克莱夫是独生子，所以结婚后，露西姐应该也会搬去米里斯住。」

然而，这次看来和平常不一样。

尽管她的开头让人摸不着头绪，但随着话题继续下去，亚尔斯也理解了她的意思。

「意思是露西姐会离开家里，嫁出去吗？」

「对。」

克莱夫出身于格利摩尔家，和格雷拉特家是亲戚，两家关系一直很好。

虽然亚尔斯对这种事还不太能理解，但贵族好像会为了巩固家族之间的联系而安排子女结婚。那么，就算真的有让露西与克莱夫结婚的计划在私下进行也不奇怪。

这就是所谓的「未婚夫」吧。

「露西姐果然对这件事感到不满吗......？」

「她心里应该还是很乐意。」

「毕竟露西姐喜欢克莱夫哥嘛......那她为什么会那么生气啊？」

「少女的心思是很复杂的。」

对亚尔斯而言，这实在有点难以理解。

他觉得露西看起来明显有不满的情绪。

甚至让人觉得她认为自己才应该是格雷拉特家的继承人。

就连亚尔斯自己也认为由露西当继承人才是更合理的选择。

不过也或许是亚尔斯对自己的不成熟深有痛感，才会有这样的想法吧......

不管怎么样，亚尔斯决定稍后再问问爱夏这件事。他想到了这点后，便决定换个话题，向菈菈这样提问。

「菈菈姐你呢？对将来有什么想法？」

「我要跟一个愿意包办打扫、洗衣服、煮饭的优秀男人结婚，然后每天窝在家里。」

「结婚......菈菈姐，你也有未婚夫吗？」

「没有。」

「呃......」

亚尔斯忍不住想吐嘈「那有谁会愿意这样伺候你啊？」，不过他还是克制住了。

毕竟菈菈说奇怪的话也已经不是一天两天的事了。

「不过，总有一天会找到的。」

「是喔。希望你能找到。齐格呢？」

亚尔斯觉得跟这位麻烦的姐姐继续聊下去只会越来越累，直接把话题抛给弟弟。

随后，齐格目不转睛地看着自己手中的木剑。

「我要成为世界最强的剑士。」

结果他的回应比姐姐还要离谱。

「成为世界最强后，我要守护世界和平。」

齐格喜欢「切达人」的故事，也对北神的英雄传说情有独钟。

所以这样的回答一点也不奇怪。不过，亚尔斯认为现在正在讲正经事，不该说出这种孩子气的幼稚梦想。

因此他叹了口气，这样说道：

「最强什么的，至少得先赢过我一次再说吧。」

「我总有一天会赢的嘛。」

「『总有一天』是什么时候啊？」

「就是总有一天！」

「随便你哪天，但要称自己最强，等打赢我之后再说！」

亚尔斯这样说完，齐格不高兴地鼓起了脸颊。

亚尔斯目前还不觉得自己会输给齐格，但他也知道齐格一天比一天还要强。

在剑术方面，或许有一天他真的会败给这个弟弟。

现在看似荒唐无稽的梦想，将来说不定就并非遥不可及。

这样想来，齐格的梦想反而还意外地正经。

......不对，就算打赢了亚尔斯，也不代表他就是世界最强。毕竟这个世上还有许多强得离谱的剑士。

「亚尔斯哥，你讨厌继承我们家吗？」

齐格忽然这样回问一句。

亚尔斯微微噘起嘴，低声嘟囔。

「我也不知道啊......」

格雷拉特家的继承人。

......他对这个称号还没什么具体的感觉，谈不上喜欢或是讨厌。

不过经过刚才那番对话，他现在能够以稍稍不同的视角来看待这件事。

格雷拉特家是龙神奥尔斯帝德的臣下，同时也是阿斯拉王国的旁系贵族。要继承这个家，想必还要作为一名贵族与其他贵族交流吧。

所以这样也能解释他们为何不仅要上拉诺亚魔法大学，也必须去阿斯拉王国的学校就读了。

「......嗯──」

话说回来，所谓的贵族到底要做什么？虽然这些应该可以在学校学到，但现在的亚尔斯根本对此一无所知。

他听说贵族重视家族之间的联系，考虑到这点的话，说不定将来还是会和陌生的女性结婚。

「......不太想那样啊。」

亚尔斯对女性其实有自己的喜好，虽然害羞得说不出口，但他确实有喜欢的对象。

不过，如果这一切早就已经决定好了，即使亚尔斯不情愿也没办法任性。

因为要是他真的这么做，露西肯定会生气的。

她会说「我都这么忍耐了，亚尔斯到底在想什么啊？」。

至少，亚尔斯必须对继承人这件事抱持积极的态度好好努力，否则露西心里肯定不会好受。何况亚尔斯也不希望被姐姐讨厌。

只是，他根本不知道该怎么努力才好。

问爱夏的话说不定会有答案，但自他过了十岁生日后，就算他希望爱夏教他什么，爱夏也很少直接告诉他答案。多半都是只给一点提示，然后告诉他要自己想想。

可是，亚尔斯不擅长自己思考。

去了米里斯之后，他开始反省各种事情，也试着让自己多花点心思去思考，但依然会像现在这样，无法顺利找到答案。他每次都想立刻用剑术或魔术来解决事情。

「......」

亚尔斯低下头，看着自己的手。

他想起露西使用的魔术，那魔术既漂亮又高明。

尽管只是简单的风魔术，效果却非常显着，让她的动作变幻自如，真的很强。

假如自己能学会那招，肯定也能变得更强吧。

「好。」

虽然他还不太清楚自己该做什么，但今天就先模仿那招试试吧。

亚尔斯这样想着，握紧手中的剑，挺起身子。

* Footnotes
[fn:1] 1. 注：出自《鲁邦三世》的角色钱形警部的台词

[fn:2] 1. 注：Un,Deux,Trois为法语的一二三
