#+title: 同人文或笔记
#+HTML_LINK_HOME: /
#+html_link_up: ./index.html
#+setupfile: ../../../setup.setup
#+Author: web

* 相关评论
** 禁断？乱伦？无职转生爱莎篇真的毁了这部作品吗？
Author: 76号旅人 - 没有特长，没有背景

#+begin_quote
原文: [[https://zhuanlan.zhihu.com/p/142949222][（知乎）禁断？乱伦？无职转生爱莎篇真的毁了这部作品吗？]]
#+end_quote
*** 关于本文
本文以个人观点为主，并参考了大量其他人对于爱莎篇的观点和看法而成文，很感谢浏览本篇文章。如果对本文看法不予认同，请保持自己的观点，毕竟每个人的观点肯定都有出入，也感谢阅览我所总结出来的观点。

如果你是还没有看过爱莎篇的读者，在听说了爱莎篇的争议后还在犹豫请参考下列两种情况。

1. 如果你是一般的轻文读者，只是想在忙碌工作和学习间去寻找乐趣的，不建议去读爱莎篇。

2. 而如果你是想去对无职转生剧情有更多的思考的，请在看之前多代入下无职世界观，这样就会容易接受很多。因为完全抛下作品中的大环境背景这个客观因素去仅仅用今天的价值观去衡量这个作品也是一种何不食肉糜的行为。

本文中名字没有完全统一使用，一部分使用了web译名一部分使用了台版文库译名。所以在开头将两版名字差异列出以便阅读。

- 卢迪乌斯·格瑞拉特 = 鲁迪乌斯·格雷拉特
- 简妮丝 = 塞妮丝
- 艾丽娜利兹 = 艾莉娜丽洁
- 爱莎·格瑞拉特 = 爱夏·格雷拉特
- 洛克希 = 洛琪希
- 艾丽丝 = 艾莉丝
- 艾丽爱尔 = 爱丽儿

本文有大量小说原文的引文所以有剧透风险

*** 前言
爱莎篇作为无职转生蛇足篇最具争议的一部分引起了国内外无职爱好者热烈的讨论，有人认为这是作品的点睛之笔，将描写力度稍显不足的爱莎刻画的更加鲜活。还有人认为爱莎篇是完全败坏无职转生这个小说的名声，不论是剧情还是文笔都是作者理不尽不认真对待的产物。、

对于爱莎这个角色，其实在看第十三卷时已经初见端倪，即使经历挫折，父亲亡故，受到歧视，爱莎依然活泼待人，积极向上。这在无职这样一个追求感情合理性发展的故事中是有违初衷的，我当时的想法是要不就是爱莎有可能会是一个隐藏很深的角色，要不就是作者纯粹为了满足读者所杜撰的一个角色，毕竟是轻文这种文体。但即使在这种我做好反转心理准备的前提下，爱莎篇依然给我带来了很大的冲击。

在爱莎篇中，我看到了作者的野心，作者不仅仅是想刻画一本众人皆赏的轻小说，而是当成一个表达自己想法的文学作品来创作，但是他的剧情触及了很多无职转生核心读者的禁区，在编排上又显得不足，没有展现出无职转生应有的魅力。

而引用我在异世界文化差异章说到的一句话理不理解是一方面，而接不接受是另一方面。即使能够理解这件事的发生，但能不能接受便得由读者来主观判断了，至少自始至终卢迪是没有接受这件事。

*** 目录
1. 主要争议
2. 两级分化的读者
  - 爱莎和阿尔斯的乱伦究竟会有什么影响？
3. 混乱的叙事节奏
4. 爱莎·格瑞拉特/爱夏·格雷拉特
  - 爱莎·格瑞拉特究竟是什么样的一个人？
  - 爱莎的性格是怎样产生的？
  - 爱莎自己究竟是怎么想的？这个角色有人主动去理解过她的心情吗？
  - 所以今天来看，爱莎究竟有没有那么的痴迷卢迪？
5. 阿尔斯·格瑞拉特
6. 卢迪乌斯·格瑞拉特/鲁迪乌斯·格雷拉特
  - 作者借卢迪的视角对于爱莎与阿尔斯这一系列事情究竟是什么态度？
  - 卢迪为什么没有察觉爱莎的变化？
  - 但卢迪为什么最终还是选择了原谅他们？
7. 异世界的文化差异
  - 各角色对于此事看法
8. 爱情转移
  - 爱莎是怎么喜欢上阿尔斯的？
  - 但是爱莎真的如歌词中唱的那样幸福吗？
9. 童话真的是童话吗？
10. 写在最后，我永远喜欢爱莎这个角色。
11. 参考文献

*** 主要争议
首先从爱莎篇的删除公告中可以看出作者给出的一些关于他自己对爱莎篇的想法。对于作者来说，爱莎篇并不完全是一个可有可无的剧情，这个剧情是作者很早就已经想好的，也就是说即使作者重新再写，爱莎篇的主要框架仍然是不会改变，即阿尔斯和爱莎的感情。

读了大家的意见，反省之余，重复着审视哪儿不好、然后作出小幅修正的作业。但就算重复这一过程，却还是陷入了再怎么修正也很难让人接受的困境。
这说到底也只是赠品而已，有着写或不写都可以的认知。 但因为爱莎篇是「必要的内容」，抱有这等认知的话可不行。
内容本身因为是很久以前就已经决定要写的了所以还好。（删除公告）
那么这就意味着在剧情中饱受争议的两个点仍然有可能难以得到改善，首先是爱莎究竟是不是真的爱上一个人亦或是对卢迪的情感转移。其次就是近亲乱伦，而且这次理不尽所写的近亲乱伦并不是时不时会见到的同辈产生情愫，而是两人有着很大的年龄差的忘年恋。

最后就是这个篇章发布的时机，在皆大欢喜的大团圆结局，突然发出这么一篇反差很大的文章。这样令人始料未及的行为让我想到了《Re：从零开始的异世界生活》的剧情，在剧情广受好评的时候让其中人气最高的雷姆强制下线。

*** 两级分化的读者
无职转生这部轻小说和普通穿越轻文相比最大的一个优势就是他选择了一个非常清晰的线索去展开：“家族”。不论是卢迪前世的家族对他为人处世的影响，还是到后期建立了一个庞大的格瑞拉特家，家族是这个故事不可分割的一部分。此处用词“家族”而不是“家”是因为在无职转生中每个家庭之后的背景以及亲族也对故事有不可分割的影响，所以我认为用家族来形容无职转生的核心是比较妥当的。同时大部分主要角色都有较为足够的篇幅去描写其心理以及行动，从这些描写中读者可以感受到每一个角色各自不同的魅力。

然而这也仅限于留下来的读者，很多人包括我安利的朋友都因为开头冗长，内容模板化，前期不爽等原因没办法坚持到这部作品后面发力的阶段。我自己也认为冒险篇的剧情稍显冗长所以看起来并没有那么舒服。但这也说明所能看完的读者基本都是能接受这种以较为合理且稍显平淡的方式展开剧情，同时有细腻感情刻画的慢热读者。而这些读者追求的，或者说被作品深深吸引的部分或多或少都在于卢迪一手创造并守护了一个完整的家族。这个家族虽然不一定是百分百美满，但是却符合绝大部分读者对于理想家庭的构想，而卢迪所娶的三位妻子也满足轻文读者对于家庭的幻想。当然也包括爱莎和诺伦，两位性格迥异的妹妹也是不可分割的一部分。

作者通过用第一人称叙事来增强读者的代入感，而卢迪的行为举止和心理活动也基本是符合读者对于后续剧情的期待。其中在父亲死后，卢迪以兄代父使得读者对两个妹妹的亲切感进一步达到了顶点。这样的波折不但让作品代入感上升也让作品更具有人情和真实感。在这样的剧情推动下，爱莎篇的展开无疑是挑战了读者对于完美家族的设想。而这其中无疑也有爱莎篇中其他的角色集体下线这么一个因素，但是一个核心因素便是无法接受乱伦。在爱莎篇中，作者以卢迪为视角寻找爱莎的过程中却不断的被亲朋好友询问【为什么反对他们？】便能反映出作品中的人物对于此事的看法。

这便映射了一个问题，爱莎和阿尔斯的乱伦究竟会有什么影响？

作者在这个问题上选择了遵从设定而不是遵从常理，即乱伦在异世界是正常现象，尤其在有地位的人中也很常见。但不是所有读者都能接受这一点，因为大家在看的时候仍然很大一定程度上套用了现实的伦理道德和自己的认知。如果完全不论现代医学方面对于近亲繁殖的概念（毕竟异世界难以套用当今的医学），引用知乎上高赞回答的一句话：

【我们活在一个有这种规定的社会之中，使得我们会按照规定那样反感这种被禁止的行为。因此，逻辑上并不是因为它不道德所以我们反感，也不是因为我们反感它所以它不道德，而是因为它作为/一个禁忌就在那，所以我们反感它并觉得它不道德。】[1]
正因为读者对于爱莎的感情在前，在加上这她与阿尔斯之间有很大的年龄差距，所以很难接受这种剧情展开。一方面读者觉得爱莎本可以有更多更好的选择，另一方面读者已经习惯爱莎这位聪明能干的妹妹待在身边的感觉。也可以推测有一部分会觉得爱莎是男主的，并认为男主其实被儿子ntr了。

而认同的读者大多都觉得这不但是一种大胆的尝试，同时也写活了爱莎这个角色，这也是我所偏向的观点，但这不代表我就认为爱莎篇是一篇完美的篇章。相反我认为爱莎篇中依然存在着很多的问题。

*** 混乱的叙事节奏
我认为一部作品有一个好的大纲框架是使这个作品好看的先决条件，例如《Re：从零开始的异世界生活》类似于自动存档的单线游戏，其本身就是一个很强调框架逻辑的作品。好的作品总能自圆其说，把自己埋设的伏笔给收回来。在这方面，无职转生本篇是令人称艳的，作品对于各个角色感情的铺垫和后续的发展把握的相当出色。至少在同类轻文作品中，有大量登场角色却可以把各个角色之间的关系理清并赋予每一个角色人格是很难做到的。无职大量的心理以及用不同角色的第一人称去推进剧情使得每一个角色都有独特的魅力，我最近看的关于第一人称叙事所进行描写并且将角色感情刻画的出色的作品是《继母的拖油瓶是我的前女友》而这一部是恋爱轻喜剧，感情刻画理应是它的重头戏。

但爱莎篇却完全没有发挥出无职转生应有的优势。对于爱莎和阿尔斯二人感情的描写显得非常不足。很多读者读完都没有感觉到无职转生应有的感情一步一步升温最终克服了考验两个人在一起。不知是碍于篇幅限制还是真如作者所说，这个蛇足篇就是写不写都可以的剧情，两人感情的开始显得非常仓促，而本来就没有对二人感情做好心理准备的读者在第二章开头就受到了强烈的冲击。

在前一章节我总结过无职转生的读者大部分都是容易接受慢热，对铺垫之后惊喜的展开抱有期待的读者。大家更愿意看到感情是两人慢慢建立最终水到渠成的结果而不是突然间的神展开，其次这个神展开本来就是不容易被人接受的剧情，导致读者对于爱莎和阿尔斯甚至其他角色的好感度下降使得后面的剧情更像是为两人前面的剧情做开脱。

除此之外，无职转生所转递的内容是对读者有正向意义的，正如作者副标题所写，在异世界就要拿出真本事，而正因为这样的剧情，很多读者在生活中也容易受到无职转生正向能量的影响。而爱莎篇的故事编排很容易给人一种二人在为自己犯下的错误开脱，而卢迪等一种角色决定去包容他们的错误。正如上文所讲，无职转生读者的代入感特别强烈，暂且不论爱莎的想法，光这样的剧情就会给读者一种，最亲近的两人对我犯错后逃避，我不但要吞下结果，还要原谅二人的感觉。

开头作者引用的童话，其中隐含的意义很难去探明，即使有很多人尝试去解读这个童话都没有做到得到很完美的答案。这一块既可以说是爱莎篇有意思的地方，因为作者使得读者对爱莎篇加上了更多的思考。也可以说是一个类似于败笔的地方，一方面是轻文这种文体本来读者就不喜欢太过于晦涩的写法，轻文的定义本来就是要易读。另一方面，即使是很多的著作也不会引一些特别难以理解的故事在文章里。文章中引用故事一般都是为了补全文章或让读者更好的理解其中的意义。比如《白夜行》中使用枪虾和虾虎鱼去指代男女主的关系。用轻文举例就比如《no game no life》中被翻拍成电影游戏人生zero的里克和休比去映射当今的空白。

*** 爱莎·格瑞拉特/爱夏·格雷拉特
爱莎在这一篇中的转变使得读者受到了强烈的冲击，本篇中聪明全能的妹妹在这一篇中却任性妄为甚至拐走哥哥的孩子。而正如我前言所提的，本篇中的爱莎真的完整吗？爱莎看似感情丰富，然而在本篇中她几乎没有负面情绪，这样的一个角色要不就是作者做出来为迎合轻文读者的设定，要不便是身上有着作者留下的悬念。

那么问题就来了，爱莎·格瑞拉特究竟是什么样的一个人？

从最开始作者对于爱莎的描写就可以看出作者对于这个角色赋予的特性，其中经常在作品中提及的就是“天才”。个人认为，天才不应该只狭义到战斗法术的天才，而应该广义在某一领域达到常人努力也无法做到的高度。卢迪在五岁时突破水圣，可谓天才。艾莉丝仅用3年从剑圣突破到剑王，可谓天才。而爱莎身上最大的才能便是可以快速学习并掌握信息，并且可以很大程度上善用这些信息。这边的信息既包括知识也包括情报，比如书本知识礼仪以及身边人的情报。

我认为这个才能的确可以被称为天才，但是可惜的是爱莎并没有将这个才能全力去发挥。作者在爱莎篇解释道，因为这般才能，爱莎被蒙蔽了双眼，反而自视甚高。而一直以来受到的歧视使得爱莎变得敏感。

而我认为一直以来爱莎都不是一个依附于谁的角色。相反她是一个由感情驱动的角色。

#+begin_quote
「妈妈从平日就一直吩咐，说我将来必须服侍同父异母的哥哥。」

「嗯，她是有说过。」

「可是啊！」

爱夏握拳用力打向地面。

「我才不愿意！」

看来她真的完全没办法接受自己的哥哥。

（台版文库第六卷）

她恐怕是想查清自己的哥哥到底是不是可以信赖的人物吧。如果我刚刚继续伪装成饲主并打算带爱夏一起走，她想必会对我完全失望。

(台版文库第六卷)
#+end_quote
虽然这一段有爱莎看出卢迪而演戏的嫌疑，但是却很好的说明了在这个年龄的爱莎已经具备了很强的个人主观意识，换句话说，她会去做自己想去做的事情而不是为了谁去做。假设卢迪真的不是她的哥哥，她肯定也会在之后寻找机会回到他的身边，因为被卢迪所救让爱莎认可了卢迪并选择了要去服侍卢迪这条路。这时的爱莎对卢迪的感情依然是恩大于情，但这却是爱莎对卢迪感情的开端。

#+begin_quote
「不过，在瑞杰路德先生拼命工作时，我妹妹她却在呼呼大睡对吧？」

「没有睡。她为了能制定最有效率地抵达这里的计划，一直都在拟定路线。」

（台版文库第十卷）

「 我明白了，要是哥哥无论如何都不肯同意，我也有自己的办法。」

当我还在犹豫时，爱夏嘟起嘴说道。

接着像是豁出去一般，她换成双手抱胸的姿势，继续抬着眼瞪向这边。

（台版文库第十三卷）
#+end_quote
从本篇中很多直接对爱莎的描写可以看出爱莎拥有自主的想法并且一旦认定这个想法就会用尽一切办法去实现这个想法。或许是因为不满童年被规定好的人生，亦或者是因为自己过人的才能，爱莎拥有了很强的自我意识。这不由得让我想到了另一部很喜欢的书中的女主--《白夜行》西本雪穗。当然雪穗比起爱莎更会利用自身的优势和能力去达到自己的目的。这样的性格从正面去看是容易专一和坚持，然而负面来看便是容易极端和偏激。

#+begin_quote
「诺伦姊每次都这样。只要事情不如自己的意就马上闷不吭声，只会在那边说不要。然后等其他人愿意妥协，如果对方稍微说了点自己不喜欢的话就会像那样大叫，好像笨蛋一样。」

（台版文库第十卷）

爱莎用死水一般的眼神看着烦恼的我，说了。

“那只猫啊，扔了吧？”

(web版第一百九十四话)

“从刚刚开始就只会这么说！ 我不是说有问题了吗！ 你这个人难不成是来妨碍我们的吗！？”

爱莎愤怒地挥举着拳头，而温蒂则缩着身子……。

暴怒的，大吼的爱莎还真是难得一见。

(web版第二百二十话)
#+end_quote
在在格瑞拉特家，爱莎只对两人出现很深的负面情绪，一个是诺伦，另一个是莉妮亚。诺伦和爱莎的冲突多出现在两人年幼并且有很多交点的时候，而毕竟二人年幼且之前受到了不平等待遇，年岁成长之后诺伦的改变使得爱莎慢慢接受了诺伦，而莉妮亚出现冲突的原因便是在家一同工作，莉妮亚既完不成工作也没有态度。温蒂的这次暴怒其中有迁怒的成分，卢迪交给爱莎的工作没有完成，出去找来补救也没有解决，万般无奈之下才出现的暴怒。

从上面便不难看出，爱莎所生气的目标经常是做不到和自己一样或者达不到同一高度的对象，并且时常会推卸自身的责任。而一旦出现情绪波动的时候，爱莎经常会将这种负面情绪引到别的人身上，这样做的一个原因是她自己会受到的负面影响很小，就有点像《黑子的篮球》中黑子一般诱导他人，使得周围的人容易去忽视这些问题。但仅这样做并不足以完全忽视，这时候爱莎出色的个人能力使得她能够将大部分事情在察觉之前都很好的补救。

也正因为如此，在本篇中爱莎很少会出现大的感情波动，也难以让人去查觉她身上所有的负面因素。这既有她的天赋的原因，也有她自己性格的因素，导致她对其他不是自己关注的人持轻蔑态度。而这其中，也包括了她自己的生父，保罗。她对保罗的冷漠当时是完全出乎我的意料的，也是第一次让我对爱莎这个角色有了一种严重的违和感。也让我认定爱莎是一个只会关注自己想去关注的事情的角色。

#+begin_quote
她过得很好。虽然保罗丧命，塞妮丝成了那种状况，爱夏还是没有任何变化，每天都很有精神。

爱夏不会像莉莉雅那样看着窗外露出忧郁表情。

也不会像诺伦那样看着保罗的剑露出辛酸表情。

（台版文库第十三卷）
#+end_quote
那么这样的性格是怎样产生的？

#+begin_quote
“区区的一个女仆，在主人离席的时候居然还继续坐着！ 是谁这样教你的！”

“非、非常对不起”

爱莎用像是要哭出来一样的表情低下头。

（web版第二百一十八话）

爱夏低着头。

不知道为什么，她的眼里满是泪水。

「……哥哥对诺伦姐比较偏心，是因为我妈妈是小妾吗？」

爱夏突然说出这种话。

(台版文库第十一卷)
#+end_quote
在卢迪之前，保罗虽然尽量平等的去对待姊妹俩，然而寻妻已经消耗了他大半精力，所以爱莎大部分时间所受到的待遇是不平等的。无论是在西隆王国，还是诺伦的家人，甚至是自己的生母莉莉娅，爱莎一直是在一种扭曲的教育观念下成长的。这样的教育既使爱莎成长出了偏激的性格，也让爱莎染上了自卑的情绪。爱莎自卑的最大体现就是害怕失败，她必须用一次又一次完美的结果去证明自己的价值。

而卢迪乌斯的出现一定程度上缓解了爱莎的负面情绪，使得爱莎有了一个正向的感情寄托，再加上格瑞拉特家的家风，爱莎这个角色没有变得消极且极端。而我认为，在格瑞拉特家，爱莎是幸福的。在这里，爱莎不需要考虑西隆王国里复杂的人情世故，不用去面对诺伦家人的人身攻击，而母亲也因为完成了她交给爱莎的任务，不再对其苛刻的严加管教。所以我相信，大部分时间爱莎的笑容是发自内心的，既是在格瑞拉特家幸福的表现，也是爱莎想向她所重视的人们展现出来的情绪。

爱莎自己究竟是怎么想的？这个角色有人主动去理解过她的心情吗？

首先一点可以肯定的是卢迪乌斯并没有，他一直逃避着面对爱莎的感情，这也是造成他发现自己和孩子疏于沟通的一个大原因。其次她的母亲也没有，莉莉娅也像当今的很多家长一样，依然将自己的价值观灌输在爱莎身上。而爱莎发现这一点之后便很难再去和母亲去交流。常年在家工作，爱莎没有什么上学读书的时间，也导致爱莎没有太多的机会和同龄人交流。而在卢迪家大家（包括大部分读者）都认为爱莎是一个主观上活泼且主观上缺少烦恼的角色，在一定程度上更了解爱莎的人反而是在旁观的一些人。

#+begin_quote
艾丽娜莉兹夫人表面上看来比我还要年轻，但却是个老于世故的人了，知道该怎么应对吧。

“是啊……正因为年轻，所以现在还不成熟，她过度的憧憬着的对象太优秀了。”

（web版第二百二十九话）
#+end_quote
正因为爱莎没有被人去理解，她被困在了自己的世界里，导致她的目光进一步缩小，所上心的范围仅限于卢迪家，这样的后果便是爱莎迟迟没有迈出下一步，而是停留在她所满足的幸福中。就如读者一般，停留在了在格瑞拉特家那个看似没有烦恼的女仆。

所以今天来看，爱莎究竟有没有那么的痴迷卢迪？

其实从正面的描写中便可以看出许多爱莎对于卢迪感情的体现，这些体现有时是不经意的，也是最能体现出爱莎对感情的不理解。她的性格使得她不敢去迈出感情的这一步，很大一个程度是因为这对于爱莎是未知，而且是无法从其他地方得到准确答案的未知。所以她并不明白怎样去对待这种心情。

#+begin_quote
爱莎张开了双眼。

接着，用不安的眼神看着我。

“哥哥，要是拒绝的话，会变得讨厌人家吗？”

“不会唷。我觉得无论如何都不愿意的话，那就算了”

（web版第一百九十五话）

叹了一口气之后，爱莎像是感到遗憾似的嘟起嘴。

“人家喜欢的是，哥．哥．唷。

哥哥既然说是为了人家的话，当然要全神灌注的做吧？”

（web版第一百九十六话）
#+end_quote
然而卢迪乌斯并没有察觉到这种心情，曲解和回避占了主要的部分，也进一步导致了爱莎的感情无法宣泄而她又不懂得如何处理，最终只能压抑在心中。

#+begin_quote
“嗯－，也没有特别讨厌唷……不过，多半，和希露菲姊，感觉有什么地方不同。有什么地方……是什么地方呢……”

“没关系我知道了。说得也是呢，有什么地方不一样呢”

虽然是很模糊的对话，但不知为何能够传达。

感觉好像有一样的感受。

（web版第二百一十七话）
#+end_quote
爱莎自主选择了卢迪乌斯，却因为卢迪乌斯的拒绝进一步束缚了自己的真心。本篇中爱莎和卢迪乌斯一直有一个类似于线索的东西存在，女仆。

#+begin_quote
那名少女的五官长相与莉莉雅有点神似，扎成马尾的褐色头发则和保罗非常相像，身上穿着过于宽松的迷你女仆服。平常那张脸应该会给人一种活泼洒脱的印象，现在却整个扭曲，还沾满眼泪和鼻水。

（台版文库第六卷）

我打开房间角落的衣柜，里面塞着三套女仆服。

每一件都有明显的缝补痕迹，似乎经常穿用。和使用者的年龄相反，全是散发出老手气势的制服。

爱夏最近一直长高，这些女仆服迟早会穿不下吧。还是莉莉雅会帮忙修改呢？

这时，我注意到衣柜角落挂着一套很有女孩子味的可爱服装。

（台版文库第十三卷）

可是她没穿着女仆服。

她再也不会穿女仆服了。

（web版爱莎篇）
#+end_quote
女仆的存在就如同爱莎和卢迪之间的维系一般，对爱莎来说，从小到大“女仆”二字总能和哥哥连接起来。当爱莎和诺伦移居到卢迪的家中后，爱莎选择留守家中服侍卢迪。这其中，占很大比例的就是她对卢迪的感情，年幼的她不知道怎么样去表达自己对于卢迪的感情，只好选择她最拿手的方式，并且在卢迪面前尽量表现的非常完美。这其中既有向卢迪展示自己并想要得到认同的原因，也有爱莎自卑的体现，她相信只有在卢迪身边持续展现价值，自己才不会因此被抛弃。

综上所述，爱莎是会因为自己的感情而做出行动，而不是完全遵循他人的常理或者顺应他人所愿，也正证实了我之前所提，如果爱莎认定自己的情感就一定会去做下去。在这样的背景下，爱莎选择和阿尔斯产生感情后做出的反常举动便可以解释。

*** 阿尔斯·格瑞拉特
阿尔斯童年度过的大部分时间都和爱莎有关，也正因为如此阿尔斯对爱莎是会产生感情的，但这种感情是懵懵懂懂的。而一个十岁左右的孩子说出我想和谁谁谁结婚其实并不是什么不常见到的事情。就比如很多人小时候和自己的表亲待的时间长了，就有可能产生情愫。但在这方面，作者对于阿尔斯的描写可用“贫瘠”二字来形容，我们依然无法断言阿尔斯经历了怎样的心路历程才向爱莎告白，或许是在这其中阿尔斯无法遏制对爱莎的感情，或许在告白的时候阿尔斯都不懂得自己对爱莎真正的感情，亦或许阿尔斯只是顺势说出了童言一般的话语。

个人在这方面倾向于选择第二种可能性，因为在后面大量的描写其实都在写阿尔斯怎么意识到喜欢一个人是应该做什么，应该是什么样的情况。从这一方面便可以看出阿尔斯对于爱莎之前的感情是不成熟的，也有可能因为格瑞拉特家血统的问题，爱莎正好符合他的审美。

#+begin_quote
「……爱丽儿殿下，继承诺托斯·格雷拉特的血缘之人，每一代都有被女性的大胸脯吸引的倾向。实际上，我从希露菲身上完全感觉不到丝毫魅力。」

诺托斯·格雷拉特喜欢巨乳。这对阿斯拉王国的贵族来说，可说是等同常识的认知。

（台版文库第九卷）
#+end_quote
当然，喜爱和情欲一向是不能分开而论的，除非是极端的柏拉图式爱情，有爱有情才是正常的表现。但当时的阿尔斯也并不完全能理解自己的想法，懵懂的感情加上初生的情愫在冲动之下所做出的告白，而在后面与家人发生冲突，被艾莉丝疯狂教育之后才渐渐懂得了什么是喜欢。

所以在这一点上我倾向于相信阿尔斯对于爱莎的喜欢是后天慢慢积累的，而且也是因为有了一系列冲突事件，他的喜欢才上升到爱这个层面。

*** 卢迪乌斯·格瑞拉特/鲁迪乌斯·格雷拉特
卢迪乌斯在这一篇章中扮演的角色便是作者想要读者去使用的观点。作者想让读者跟随卢迪乌斯的观点去了解这件事的原因，并且去判断这件事的对错。换句话说，卢迪乌斯的观点其实才是作者对于这件事的观点。对于作者所设想的剧情来说，这件事是一件无法避免的事情，而作者所能做的便是用卢迪乌斯的视角去阐释对于这件事的感想。

那么作者借卢迪的视角对于爱莎与阿尔斯这一系列事情究竟是什么态度？

首先，我不认为卢迪也是认同爱莎做法的人，相反其实他对爱莎这种做法显露出明显的反感和敌意。从很多描写卢迪乌斯的内容中我们不难看出卢迪这个和我们有基本相同价值观的人自始至终都没有完全接受这个事件。

#+begin_quote
虽然这也是理由之一，但并非最重要的理由。

无法说明我所感受到的抵拒和反感。

「那么是为啥！？只是说不行的话我可无法接受！能我接受的话就算是我也会放弃的！让我放弃吧！呐？」

「我也不明白啊！但是不行就是不行！」

说真的，我的抵拒感依然未消散。现在也依然觉得恶心很想吐。



这个世界的话，近亲通婚是蛮常发生的事。 特别是阿斯拉王国的贵族们。

就算是某些魔族也有相似的风俗。

所以都不怎么抗拒吧。

或许我才是异常的也说不定。

就算已经习惯了这个世界，我原本就是异世界的人。 自己的感性没那么容易改变的吧。

「一方面是姑姑，一方面是小时候就一直给她添麻烦的侄儿。。。不是非常不错的关系吗？还是说因为阿尔斯是长男的关系吗？可是你也并非贵族，没有必要让他继承家柄，你以前也是这么说的啊？」

「不是那方面。。。那个，果然亲族之间通婚还是不好的吧？」

「有何不好？」

那日的事在我心里留下了不可磨灭的创伤。

所以把向家族出手这件事视为禁忌。

今后也要跟孩子们谈各种各样的话题，听他们的话，跟他们一起玩。

那样的话，我肯定不会重蹈今次的覆辙吧。

（web爱莎篇）
#+end_quote
以上引文是从事情开端，过程中以及落幕三个期间卢迪的心路历程，说白了，不论哪个时段，卢迪是抗拒和不舒服同时认为这是自己的过错。前世的伦理观（同我在第二章所讲）还有前世的创伤，使得卢迪在最开始处理此事的时候遵循了自己的感情。这一点我可以理解，相信大部分人在当今社会的价值观下遇到这种事情都不可能说同意二字，尤其在事情刚刚发生头脑发热的时候。

卢迪为什么没有察觉爱莎的变化？

这里就要来探讨一下卢迪解决感情问题的方式了，不论是最初的保罗，还是后来的诺伦，甚至是在学校和其他同学的相处，卢迪无一例外都运用了他前世的经验。尤其是很多事情他都是曾以一个被害者的角度去面对过，所以当他或者他身边的人变成加害者时，他可以更好的从另一个角度去思考，使得问题解决的更完善。而爱莎这个问题不一样，他这次代入的角色是他大哥和他，他忽略了这两件事的关联性。他在那个事件中纯粹是以性为目的而做的。但爱莎这件事不是，爱莎更多的是一种情感的宣泄，而引发这个问题的根本原因，很有可能就是卢迪。这其实也导致了在这件事之后，卢迪依然没有完全理解到爱莎的心情。

但卢迪为什么最终还是选择了原谅他们？

这里面的客观因素就有很多了，除了卢迪已经在异世界生活了很多个年头，对爱莎以及阿尔斯复杂的感情，其他亲友对二人的感情支持之外，我想讲讲作者在爱莎篇中写到的一个重要的理由：他在二人的感情上看到了他和其他三个妻子的羁绊。

#+begin_quote
「那两人，就像以前的我俩呢。」

「是那样么。。。？」

听希露菲这么说，我歪了歪头。

紧紧地把阿尔斯抱在怀中。

那个身影，跟从前在贝卡利特大陆跟我结合时的洛克希的身影重叠了。

「死也。。。不让你们通过。。。！」

「是么。。。不愧是卢迪乌斯的儿子呢。」

艾丽丝突然抬头大声喊道。

对做到那个地步的阿尔斯的心情，我很了解。

阿尔斯是怀着跟我向奥尔斯蒂德发出挑战时的同样心情站在我们面前的吧。

（web版爱莎篇）
#+end_quote
这三个场景分别都代表了三个在他人生中非常重要的场景，每一个都对他的人生产生了不可磨灭的影响也对应着他所深爱的三个人，也真因为如此，经历过如此事情的卢迪能够理解在经历同样事情的长子。

纵观整件事情，卢迪从不解到反思到后悔，可以看出卢迪到最终都没有完全认同这件事情，他引以为戒并决心不再重蹈覆辙。但同时他又想要爱莎和长子获得幸福，这两种感情最终后者还是占了多数，所以他在最终选择了妥协。

*** 异世界的文化差异
无职转生中还有一项令我十分欣喜的设定，那就是作者尽力去描绘一个和自己生活的社会有相通之处却完全不同的世界。而其中很多设定也可以在我们的历史中找到相通之处，比如爱莎篇中争议很大的近亲婚姻，其实直到19世纪末期才渐渐消退，但表亲婚姻直到今日都在很多国家普遍流行，其中就包括当今日本。[2]

说个题外话，中世纪欧洲其实是一夫一妻制而不是一夫多妻，这里面最大的原因便是基督教在欧洲有很大的权重，而基督教提倡一夫一妻制，这点和无职中米里斯教团教义相似。也正因为如此加上近亲通婚，欧洲皇室和贵族生育率普遍比较低，这也直接导致了欧洲女性会经常掌权（继承人不够了）。

但这仍然和当今主流价值观相差甚远，读者包括卢迪并不能完美的融入文化，很多人也并不是很愿意站在其他文化的立场上去思考。就如同七星一般，如果在故事中没有遇到卢迪乌斯，那么七星会依然呆在自己的世界也不和异世界的人有过多的接触。当然七星不算是不想和这个异世界接触，而是发现自己不属于这里而产生的失望最终致使她自闭。

#+begin_quote
七星双手抱膝颤抖着。

不管是克里夫也好，札诺巴也好，甚至是希露菲，她都不会和对方有必要以上的交情。

然而，她却愿意听我的话。

不仅会听我的请求，也愿意参加我举办的活动。

（台版文库第十四卷）
#+end_quote
本章中文化差异便指代这种读者以及作者所描绘的世界中的文化差异使得很多读者对此不理解甚至厌恶。作者笔下的其他角色对这件事的态度便可以表现出作者的确有从异世界文化的角度去考虑这个问题。



**** 艾莉丝
作为阿尔斯生母，艾莉丝在故事中是第一个对此事做出行动的角色。她以自己独有的方式教育了儿子一顿。

#+begin_quote
阿尔斯从椅子上被打飞，撞上了墙。

虽然鼻血流下来了，但被吓着了只是呆呆的望着艾丽丝。

「你啊！竟然让爱莎说到这个地步！」

（web 爱莎篇）
#+end_quote
艾莉丝自始至终所生气的点都是儿子没有遵循自己的教导，遇事没有一个男人应有的担当，而是让爱莎挡在自己的身前。从艾莉丝的角度来讲这是她惯有的思维模式，况且对于她来本来她和卢迪也是亲属，所以她不会对近亲这个方面产生更多的想法



**** 希露菲
希露菲对于这件事的不满态度更多的表现在爱莎不信任家人并且还尝试为自己的行为做开脱这方面上，所以她也对卢迪不同意这件事抱有疑问的想法。可以从希露菲之后对此事柔软的态度看出，她从某些方面是理解并支持两人感情的。这可能也因为长耳族之间也没有如此的禁忌，从艾丽娜利兹的表现中便可以看出。所以希露菲其实是想支持二人。

#+begin_quote
艾丽娜莉兹则是一脸惊奇地说允许她们就好了嘛。

（web版爱莎篇）
#+end_quote
**** 洛克希
洛克希依然延续了知性这两字，她更多的是对自己没有及早发现并和二人沟通交流而自责，在事情发生后选择了尽量去弥补，也非常符合她的性格设定。她在家庭中的角色更多的是纠正孩子错误的事情就像老师一般。然而在爱莎篇中，明显可以看出更多担当这个角色的是爱莎，这也间接增加了阿尔斯和爱莎相处的时间。

**** 莉莉娅
莉莉娅在这件事中依然将爱莎的身段放得非常低，以一种卑微的方式去思考这个方式。她所生气的点是爱莎身为下人主动去勾引主人这一点。这也是很多读者愤慨的地方。但我认为莉莉娅如此想是很正常的，莉莉娅本身就是一个十分不幸的角色，而这种不幸又很大程度上是卢迪的父亲保罗造成的。在莉莉娅的一生中，她基本上都是以侍女的身份度过，这种奴性思维已经是不能随便改变的。

#+begin_quote
「。。。结果那个孩子果然是我的女儿，引诱本该守护的主人，用自己的身体来制造立足之地，流着卑/贱的、好似淫魔的血脉。」

（web版爱莎篇）
#+end_quote
**** 其余角色
克里夫对此事持批判态度，可以看出宗教在异世界中对伦理道德这类事情的约束。但作者并没有明讲是什么样的约束，从克里夫娶外族并有相当年龄差的妻子便可以看出，这个约束更多的可能和希露菲的想法相似，即隐瞒家人或破坏家庭和睦。

诺伦对此事也持批判态度，或许是震惊于一向理性的爱莎会做出这种举动，或许是因为她所信服的教义。

扎诺巴和爱丽儿的表现则能代表贵族对此事的想法，他们并没有认为这件事有什么不妥，一方面是在他们身边常有发生，另一方面他们更多的是关注卢迪为什么无理由拒绝接受二人。

七星不做讨论，因为她属于和我们价值观相同的同世界人物。瑞杰尔德只提到了复杂的心情，不太好做出推论，推测可能只是觉得爱莎可能受了诺伦结婚的影响。

综上所述，不论是作者对异世界的主观叙述，还是从各种人物角度出发，都基本上并不反对这两个人的感情，作者想通过这些读者熟悉的角色传达出这件事虽然在异世界并不是什么稀奇事，并希望读者能很大程度上去理解这些。

然而，这并非是一件简单的事情，我一直认为理不理解是一方面，而接不接受是另一方面。正如我在叙事节奏那一章所说，作者在这一篇中的写法很难让读者去代入爱莎篇的剧情，这也直接导致了读者和故事之间产生了严重的认知断层。

*** 爱情转移
#+begin_quote
把一个人的温暖转移到另一个的胸膛让上次犯的错反省出梦想

（爱情转移—陈奕迅）
#+end_quote
陈奕迅的歌一直是我最喜欢唱和听的，除了因为他的歌曲曲风千变，嗓音独特，还有就是他的很多歌词都很耐人寻味。而这两句词在某种意义上是对爱莎行为的一种概括。上次犯的错便是对一个不应该动情的人动了情，而之后反省出的梦想便是想和阿尔斯获得幸福。

所以爱莎是怎么喜欢上阿尔斯的？

在爱莎篇中明确的就有写出这么一段剧情。

#+begin_quote
认真的看着爱莎的阿尔斯。

年纪还小的他，样貌跟卢迪乌斯相像极了。

不是现在的卢迪乌斯。

而是像跟爱莎初次碰面那时的卢迪乌斯。

回想起来，爱莎初次见到卢迪乌斯时，他跟现在的阿尔斯一样年纪。

当时的卢迪乌斯，在自己陷入困境之时闪现帮了她。

发觉我一直都讨厌他的时候，慌忙地隐藏真身。

帮助她的时候好酷，隐藏真身的时候却又是那么地滑稽。

看着这样的他，想着一生侍奉他也未为不可。

（web版爱莎篇）
#+end_quote
很明显从这一段来看，爱莎篇爱莎对阿尔斯倾心很大程度是对自己感情的一种转移。但这也恰恰是作者在爱莎篇没有处理好的部分，爱莎和阿尔斯突兀的感情进展使得读者有一种爱莎之前的理性的形象崩塌而变成了一个仅会为感性行动的人。

然而我并不认为因感情冲动这件事本身有违一个故事的设定，处事冷静一心只为复仇的基督山伯爵唐泰斯也会在和梅尔塞苔丝会面中使得自己死心复燃，为目的不择手段的西本雪穗也会说出：

#+begin_quote
“我的天空里没有太阳，总是黑夜，但并不暗，因为有东西代替了太阳。虽然没有太阳那么明亮，但对我来说已经足够。凭借着这份光，我便能把黑夜当成白天。我从来就没有太阳，所以不怕失去。” ------《白夜行》东野圭吾
#+end_quote
爱莎在认识到自己的感情之后做出的这一份非理性冲动恰恰说明她空有才能和手段却仍然渴望被爱和爱，而也正因为如此，印证了我前文的分析，爱莎的确是一个会以自己感情为出发点而进行行动的角色。而阿尔斯主动向爱莎直观的表达了感情，使爱莎不得不直面这种情感。使得爱莎曾经被熄灭的心火重新点燃，这也佐证了爱莎这个角色并不是依附于卢迪或者母亲，而是自己的感情。



另一方面来讲这便是爱莎感性的体现，使得这个人物在我心中的形象更加完整。让爱莎从之前那个类似于媚宅产物的妹妹角色变得更加鲜活。所以从剧情上来讲，我认为作者打破了固有的观念，写出令人意外的内容。这一点在我看来是一种惊喜，因为轻小说这个载体鲜有出现将自己的思考的产物不加修饰的写在文章里。

但是爱莎真的如歌词中唱的那样幸福吗？



在爱莎章节我经过分析可以看出在爱莎的一生中，在格瑞拉特家和卢迪以及其他家人度过的日子是爱莎最幸福的时光，在这段时间里爱莎可以充分去考虑自己的事情，做自己感兴趣的东西。也是因为这样一段生活可以称为幸福，爱莎最开始所认为的幸福就是简单的两个心意相通的人尽量待在一起。

#+begin_quote
「这个故事里的阿尔斯，要怎样才能幸福呢？」

「啊？那个嘛。。。嗯，就算一直跟他心爱的女孩待在一起她也会死去，那么不去管魔王的事，而向贤者请教拯救女孩的方法，说不定就能有圆满的结局了。勇者阿尔斯跟魔王，话说那是克西莉卡大人吧。虽然没有打倒克西莉卡大人的话和平不会到访，但是在两人的余生里，人族是不会灭亡的吧。」

(web爱莎篇)
#+end_quote
虽然阿尔斯的直球加上可能与他人联姻唤醒了爱莎对于幸福的渴望，然而她自己仍然不清楚这样的感情是什么，所以最开始的时候，爱莎用“练习”来逃避面对自己感情。这一段时间的爱莎渐渐发现自己对阿尔斯的依赖越来越强，而真正的爆发点就是暴露的那一天。那一天的爱莎，在感情不被卢迪理解，爱人要被拆散的当口，思维混乱了起来。

#+begin_quote
那是在跟奥尔斯蒂德对战前，制作魔导铠的期间一直板着的险峻表情。

爱莎对那表情感到了恐惧。

但爱莎意识到了。

若是跟阿尔斯分离的话，自己肯定无法获得幸福的。

至今以来的日常不能算是幸福。

若是看见不在我身边却幸福着的阿尔斯肯定会后悔的。

（web版爱莎篇）
#+end_quote
这时候的爱莎是混乱的，是偏激的。这既来源于自己对于幸福和爱的曲解，她认为分离就不是幸福，也来源于对卢迪的恐惧，她很清楚卢迪对自己的家人有多上心。在失去了冷静的爱莎做出了十分冲动的选择，而年幼缺乏判断力的阿尔斯也选择跟随爱莎私奔。

#+begin_quote
爱莎无力地摇头。

「阿尔斯会像至今为止被我操作的人偶一样，我也肯定什么都不会有所改变。。。那样的话。。。肯定。。。」

（web版爱莎篇）
#+end_quote
最终，爱莎终于认识到一个问题，这种一厢情愿的做法并不是幸福，阿尔斯不会有改变，他变不成爱莎所理想的样子，而爱莎也做不到像以前一样快乐。她心中会永远有一个过不去的坎，因为这件事情，爱莎认识到偏激和建立在别人的担心上的幸福并不是幸福。而更重要的是，爱莎认识到如果不和别人沟通和交流，总是逃避的话是不会成长的。所以作者在爱莎篇出现的一些矛盾，其实是想表现出爱莎思想的转变过程。对爱莎来说，这件事是让她走出自己的世界的一个转折点，我也希望这件事之后的爱莎能够真正找到找到自己的幸福。

*** 童话真的是童话吗？
爱莎篇的开头所撰写的童话在很多人看来是没有任何意义的，或者很多人和我一样，隐约觉得作者搞这么一个奇怪开头肯定有什么猫腻。经过思考，反复阅读以及整理别人的答案，我想出了一套可以解释的通这个童话的方式。

首先将童话剧情排序

阿尔斯为了拯救心爱的人踏上旅程，而他的目标便是打败魔王。而他需要找到五位贤者，五位贤者分别都有排名并代表着一种精神。

首先找到了排名第二的信念

其次找到了排名第三的忠义

然后找到了排名第四的探求

在打魔王前夕找到了第五的爱

接着阿尔斯便认为自己能够打到魔王，守护自己喜欢的人

然而败于魔王的阿尔斯在绝望之际找到了排名第一的使命

在爱莎篇中，年幼的阿尔斯从小便听从生母艾莉丝和爱莎的教诲还有老故事的结局：

#+begin_quote
一个是艾丽丝所教的事：

『请保护好重要的人。』

然后是爱莎教他的事：

『有想要做的事的话，那就应该先行动去做。若是遇到困难，就该靠行动去解决。』

然后是曾经听过的老故事的结局。

『相爱的人绝对不该分开。分开的话只会遭遇不幸。』

(web版爱莎篇)
#+end_quote
也就是在懂事前，阿尔斯所懂得最多的教诲便是做事的信念。然后阿尔斯从教诲得到了启示：

遵从这三个教诲，阿尔斯这么想了：

#+begin_quote
（爱莎姐若是想那么做的话，就让她这么做好了。若是爱莎失败了而陷入绝境之时，到时就换我来帮助她、守护她。）

（web版爱莎篇）
#+end_quote
但这时的阿尔斯并不理解爱为何物，因为正如作者所说：

#+begin_quote
可是，阿尔斯还是个小孩。

不管经验还是知识都不多。

或许阿尔斯更加聪慧，又或是年长几岁的话。

在家庭会议结束后，爱莎对他说「让我们离家出走两个人过活，私奔吧！」的时候，他或许会阻止。

爱莎姐，这次换我来守护你了，我也会好好地说出自己的意见的，所以再一次跟爸爸谈谈吧。

（web版爱莎篇）
#+end_quote
所以这时趋势着阿尔斯去协助爱莎的更多是对爱莎的忠义，他认为爱莎需要他，所以他就应该无条件的支持她。在与爱莎的私奔过程中，二人吃了不少苦头，在这不断探求的过程中，阿尔斯巩固了自己的感情：

#+begin_quote
绝不会让他们接近爱莎。

就算同归于尽也要守护好爱莎。

自然的就那么想了。

（web版爱莎篇）
#+end_quote
最终在面对要将她们二人拆散的强大实力时候，他终于可以毫无迷茫诉说出自己心中所爱：

#+begin_quote
「就是这么打算的。我喜欢爱莎姐。一直给她添麻烦，一直被她帮助、养育。当然我也很感谢爸爸和妈妈，可是我觉得我亏欠爱莎更多。爱莎若是跟我说想要一生都在一起的话，我会一生都为守护爱莎而活。」

果然没有任何迷茫呢。

（web版爱莎篇）
#+end_quote
自认为已经强大到足以挑战魔王L的阿尔斯，决定拼死也要守护爱莎，他认为这就是打赢魔王L的最佳途径：

#+begin_quote
「你觉得你做得到吗？」

「做得到。」

「我倒觉得目前的你还没做不到。」

诚实地说了后，阿尔斯弯下了嘴，盯着我看。

「我跟一年前不同了。」

一边这么说，一边散发着不让你们通过，不能让你们带走爱莎的氛围，威风凛凛地站在家门前。

（web版爱莎篇）
#+end_quote
结果是显而易见的，阿尔斯没有战胜魔王L，他最终倒在了魔王A面前，魔王A狠狠教训了年轻的勇者，同时也让勇者感受到了绝望：

#+begin_quote
艾丽丝突然抬头大声喊道。

「但那样不能算是尽力保护！」

「。。。我知道。」

「现在的你，就算想要保护，也无法完全保护好！」

「。。。我知道！」

（web版爱莎篇）
#+end_quote
心灰意冷的勇者，在最终贤者L的点拨下，勇者理解了最后的要素，使命。

#+begin_quote
「你的话会怎么做呢？就这样跟艾丽丝战斗致死？死了之后的事怎样都好吗？你死了后，不管爱莎发生什么事都行吗？」

「。。。」

虽然是询问的口气，但是声音很友善。

阿尔斯顺着看向了洛克希、我、还有艾丽丝。。。

（web版爱莎篇）
#+end_quote
阿尔斯的使命不应该是牺牲来守护爱莎，也不应该是仅仅片面的站在爱莎前方，而是应该携手并进，寻找到属于二人的幸福。正如爱莎在爱莎篇最开始所说：两人一起得救，生活在一起才有可能寻找到真正的幸福。

#+begin_quote
「啊？那个嘛。。。嗯，就算一直跟他心爱的女孩待在一起她也会死去，那么不去管魔王的事，而向贤者请教拯救女孩的方法，说不定就能有圆满的结局了。勇者阿尔斯跟魔王，话说那是克西莉卡大人吧。虽然没有打倒克西莉卡大人的话和平不会到访，但是在两人的余生里，人族是不会灭亡的吧。」

（web版爱莎篇）
#+end_quote
当然我并不认为我的解释就是对童话最好的解释，希望之后能有人找出更合理，更有信服力的解释。

*** 写在最后，我永远喜欢爱莎这个角色。
理不尽在回应别人对爱莎篇的回复中提到了他也是经过长时间思考之后决定这样写下去，他的一大初衷是想让读者思考这种事一旦发生在自己身边，我们应该用什么样的态度去接受。且不论这种事可以在读者身边发生的可能性，光论文章我并不认为理不尽的表达方式非常的到位，因为如果剧情完全不被读者接受又谈何从剧情中思考感悟，况且爱莎篇其实传达出来的负面能量是远大于正面能量的，最终的解决方案并不像本篇那样团圆。

但说归说，在爱莎篇之前，我觉得爱莎只是作者创作出来的媚宅产物，她只是为了迎合读者并填补一些剧情空缺的需要。而爱莎篇之后，爱莎在我心中变成了一个鲜活的人物。同时也是一个悲情人物。令人惋惜的童年，在找到依靠之后却得不到回应。最终以一种让人难以接受的方式换来了解脱。但这样做真的是解脱吗？我宁愿相信是作者没有写好，使得爱莎篇看起来就像是没有走出卢迪的阴影。但即使如此，我依然喜欢爱莎，爱莎的开朗，专情，聪明，即使受到了不公平的待遇，爱莎依然坚强的坚持了下来。经过我的分析，我可以理解爱莎这样做的原因，所以最后只希望未来的爱莎能找到属于自己的幸福。

除了祝福，我还能做到什么呢。



*** End
by：76号旅人，首发b站，知乎。

特别鸣谢：无职转生同好会（微博）

Ps：更多的无职转生消息可以关注这个微博

*** 参考文献
- [1] [[https://www.zhihu.com/question/68522530][飞奔的马达（2019）， 知乎]]
- [2] [[https://zh.wikipedia.org/w/index.php?title=%E8%BF%91%E8%A6%AA%E5%A9%9A%E5%A7%BB&oldid=58678095][近親婚姻. (2020, March 17). Retrieved from 维基百科, 自由的百科全书]]

编辑于 2020-05-23 01:43
* 同人文
** 龙神的笔记
#+begin_quote
内容复制自b站，经搜索应该原产于[[https://tieba.baidu.com/p/9081090397][百度贴吧]]。
#+end_quote
两百次，不对，快三百次了吧，算了，不重要了。

没有朋友，没有爱的人，没有同伴，没有爱好，什 么都没有。

只有相信着自己一定有一天可以杀死人神，才能继续前进下去。

唯一的乐趣是吃河豚，为此专门学习了解毒魔法。

因为诅咒，人们怕我，可能不止人。

总之他们畏惧我，更不可能信任我，我也不想了解他们，记住他们只是因为这些可能是对抗人神有用的信息罢了。

然后，我有了一个可以称为“朋友”的人。他叫鲁迪乌斯-格雷拉特。他胆子很小，即使没有诅咒，他看见我也会慌张和因为诅咒产生的恐惧不一样，他只是单纯胆子小而已，他比较软弱和自卑，前提是家人没有收到威胁的话。他很不着调，有时会会说很蠢的烂话，有时开无聊的玩笑，偶尔还能看见他被自己妻子打，或者被自己家人吓的往地上一跪，总之完全没有一点强者，或者成熟的人该有的样子，和一个贪玩的小孩子一样。

他给我取了各种外号，老大，老板，boss，社长，吾主等等。

可能是因为他灵魂的缘故，他的家人也不怕我，他的孩子有时会围在我身边玩，张大眼睛看着我，基本是，他的每个孩子都被我抱过，或者骑过我的肩膀，有时甚至会一脸好奇的拽拽我的衣服和头发，菈菈没有这么做，她选择在我的茶水里放酱油，或者在抽屉里放青蛙。

当然他没有一直在玩，他帮我对抗我一直想战胜的敌人，他东奔西跑，非常辛苦，但他一直在努力战斗着。

有时忙了很久回来后，会跑到办公室来滔滔不绝讲上几个小时，任务完成的怎么样，他遇见了谁谁，我家孩子怎么样，我不擅长聊天，但听他讲个不停，到也不错。

偶尔他会给我送一些奇怪的料理，听说是他在另外一个世界喜欢吃的东西，每次他都会兴致勃勃的等我给出评价，像是得到了什么宝贝想向我炫耀。

他也有烦恼，比较孩子成长中的问题，孩子长大了开始叛逆，家里内部出现了特殊情况等等，他似乎一辈子都是在为了家人的幸福而战，或许这就是他自己的幸福。

他不是一个特别完美的人，但他的有种特别的魅力，感染改变了他身边的每一个人，每个人都和我曾经记忆里的不一样。

这就是鲁迪乌斯-格雷拉特。

他是我尊敬的友人。

我抬起头看看周围，这是他当初刺杀我准备的小屋，这么多年装修现在已经很有一个家的样子了。

我站起身，来到对面的椅子旁边，手往椅子上摸了一下。

好厚的灰啊。

毕竟他已经走了很多年了呢。

** （补档）菈菈的恶作剧
#+begin_quote
内容复制自[[https://tieba.baidu.com/p/10281534708][百度贴吧]]。
#+end_quote
我叫菈菈，菈菈·格雷拉特，是鲁迪乌斯家的次女，我还有五个兄弟姐妹，大姐叫露西，下面是长子亚尔斯，在再下面……啊，好麻烦，请容我省略，你知道我的意思就行。

我是人族和米格路德族的混血，所以我好像拥有米格路德族专属的念话能力，但蓝妈妈好像不会念话，小时候我向她念话她却苦笑着跟我说对不起哦，菈菈，妈妈不会这个。

不过，长大一点后我又发现这个能力好像又和米格路德族的人们有点不同，因为我只有有意愿，好像也能听到其他种族的心声，我经常这样和塞妮丝奶奶交流，塞妮丝奶奶十分健谈，是一个活泼的奶奶。

爸爸很忙，经常不在家，我知道爸爸在为了我们一家的安全而战，我很佩服爸爸，他在我心目中是个英雄，不过，爸爸也有许多秘密。

比如说，爸爸的口袋里经常放着一块神秘的白布，其实我知道，那是蓝妈妈的内裤，但爸爸把他叫做「御神体」，真是奇怪，另外，地下室好像也有所谓的「圣物」，有一次我趁大家不注意跑去偷看，实在是让我大吃一惊，爸爸的品味真是特别，不过我是不会说的，毕竟我喜欢爸爸。

话说回来，因为我可以读取每个人的内心，还可以占卜未来的大概发展，所以我一般都很少说话，毕竟跟他们三两句说不清楚，实在是麻烦，干脆不说好了，其他兄弟姐妹好像对爸爸有误解，不过那是其他的事了，我喜欢恶作剧，然后读取到他们不知所措而又尴尬不以的心声实在有趣。

今天我骑着雷欧闲逛时，发现爸爸在沙发上睡觉，白妈妈带着露西他们去散步了，蓝妈妈在学校上课，红妈妈跟着蓝妈妈去学校做剑术指导了，家里就我一个人。

诶嘿。

我突然冒出个好点子。

我偷偷把爸爸口袋里的「御神体」拿了出来，然后怎么做，对了，干脆换成我的……那当然不可能，要是被发现了估计又要被红妈妈打屁股，生气的红妈妈就像一头狮子，实在吓人，我每次都把恶作剧控制在刚刚好不会挨打的范围，露西很少犯错，其他人，尤其是亚尔斯，老是挨揍，真是不长记性。

该怎么做呢……我又想到一个好主意。

我跑去蓝妈妈的房间，蓝妈妈是衣物杂乱的扔在床上，我在上面找到了蓝妈妈爱穿的长袍，我毫不犹豫的穿上了它。

然后我就背对着爸爸，漫无目的的在客厅走着

「汪？」（你在干什么？）

请拭目以待。

「汪」（又要干坏事了吗）

请不要说的那么难听。

「唔，啊～～」

爸爸打着长长的哈欠醒来了。

「啊！洛琪希！」

然后，一把抱了过来

「洛琪希，好久不见了，我好想你啊，嘶～啊，真香 m」

有点超出预期了，不过也不坏，嗯？

爸爸开始对我上下其手。

「爸爸，麻烦你下次看清楚再行动哦」

「啊！」

爸爸像是触电了一样弹出去老远。

「菈……菈菈？」

「是我，怎么了吗？」

「实在抱歉，菈菈，爸爸不是那个意思，只是，爸爸认错人了，我还以为是蓝妈妈，是说，你怎么穿着妈妈的衣服？」

「不可以吗？我喜欢妈妈的长袍，所以想穿穿看。」

「额，当然可以，就是呢，那个……」

「如果我告诉蓝妈妈爸爸对他可爱的女儿性骚扰的话……」

「爸爸不是故意的，请你千万不要告诉洛琪希，我什么都会答应你的！」

爸爸摆出五体投地的姿势说到，真是的，你好歹注重一下所谓长辈的威严嘛。

「那么，我刚好前几天在魔法协会看到一个水晶球，至于价格……」

「不用说了，交给我吧！」

爸爸立马就开始行动，过了一会，他拿着那个特制水晶球回来交给了我。

任务完成！【图片】

** （补档）鲁迪乌斯的邪（J）恶（K）计划
#+begin_quote
内容复制自[[https://tieba.baidu.com/p/10285068566][百度贴吧]]。
#+end_quote
今天，某个人有了一项非做不可的事，其实那个人就是我，因为昨天晚上的一个梦，害我今天一天都在想这个事情。

因为实在不知道如何开口，所以我去询问七星。

七星听到我的诉求后，露出一脸傻眼的表情。

「哈？为什么你总是问我一些奇怪的事啊！这个我怎么会知道要怎么办了啦。」

果不其然，被骂了

也是，说到底，七星也就只是一个普通的女子高中生罢了，普通女子高中生怎么能理解我的苦衷呢。

本来还想问问社长大人，但果然还是算了，要是惹社长大人生气可就不妙了。

是说，求人不如求己，我已经向商店那边下了订单，接下来就是看准机会。

★希露菲观点★

昨天晚上露西一直哭个不停，非得要我跟她讲故事，结果闹到了很晚，害我睡眠不足，今天早上起的稍微迟了一些。

起床后我去餐厅吃早餐，碰上了刚好用餐完毕的洛琪希，她今天休假。

「早安，洛琪希。」

「啊，早安，希露菲，你也是刚起床吗？」

「嗯，稍微多睡了一会」

「听我说哦，希露菲，鲁迪不知道一大早就出门去干什么了。」

「咦，是吗，艾莉丝不知道这件事吗？」

「艾丽丝说「鲁迪乌斯的话，说是要准备一个惊喜！」，但是，我觉得艾莉丝有点靠不住。」

「难道说，鲁迪和七星……」

「我觉得那倒不太可能啦。」

「可艾莉丝说过前几天鲁迪去了空中要塞一趟。」

「他不是定期就会去一趟吗？」

「可是离他上次去还没过几天呢。」

「这样啊，不过我还是觉得不太可能，毕竟要是有那个意图的话鲁迪不会偷偷摸摸的……啊，菈菈，不要扯我的头发，很痛的哦」

「夫人，让我来吧。」

「麻烦你了，莉莉娅小姐。」

「也是哦。」

我是有点多虑了，真是的，我以前也不是这么疑神疑鬼的呀，不过我实在不能苟同鲁迪在对待男女关系这一块的信用啦。

至于究竟发生了什么，我到下午才知道。

★鲁迪乌斯观点★

真是气死我了。

本来我都跟商店下了加急订单，虽说有成品，不过那都是便宜货色，实在不入眼，我要的是比较高级的款式，也就是更好的布料，结果却出了问题，因为店里的学徒把订单弄丢了导致财务部和仓库那边对不上号，花了好一会才解决，难得今天洛琪希在家，而且社长交给我的工作刚好告一段落，我差点说出这种学徒干脆炒了算了，不过还算是没有坏我的好事，鲁迪乌斯大人宽宏大量，就原谅他了，不过那些都不重要了！

「让她们三个穿上这个的话，一定会是绝妙的景色！」

光是想想口水就快流出来了，得快点回去。

★★★

吃完午饭后，我把三位妻子召集了过来，希露菲难为情的搔着耳朵，洛琪希一如既往半睁着眼面无表情，艾莉丝则是以双手抱胸双脚张开的标准艾莉丝式站姿。

「所以说，鲁迪把我们叫过来是想做什么呢？」

「唔，一般鲁迪把我们一起叫来是想……」

「哼！鲁迪乌斯的话，肯定是今天早上准备的惊喜，对不对。」

艾莉丝略带骄傲的说着，一脸「看吧，我就知道」的样子。

「我把你们叫过来，是想让你们试试看这个。」

我想让她们试的，就是出自七星大师之手，统一拉诺亚大学制服的伟大之举的拉诺亚校服，当然是女生款式，也就是所谓的JK。

「我……我倒是有男生款式的，要是鲁迪想看这种的，我就穿穿看吧。」

「有点难为情，毕竟我都这个年纪了，不过我当时上学的时候还没有这样统一的制服呢，鲁迪想看的话，那就没办法了。」

前两位很轻松的接受了我的提案。

至于最后这一位嘛。

「我才不要！这种不适合我啦！」

「拜托！艾莉丝，仅限这一次，只要你能穿上，你让我做什么都可以。」

「做什么都可以！真……真拿你没办法，那我就穿穿看吧！」

艾莉丝还是那么好对付，不过我对于做什么都可以这个提议感到了一点后悔，还请艾莉丝温柔一点，毕竟我是少女乌斯，经不起折腾。

不一会儿，换装完毕的三位走到了我的面前。

这……这简直是堪比5A级景般区的存在啊。

穿上校服希露菲像是位于女子高中生顶点的高冷校花一般，平时总是露出一副严肃的冷酷表情，实际上是一个对每个人都温柔以待，一视同仁的人，即使被追求了也会莞尔一笑说「多谢你的好意，不过我已经有喜欢的人了」的遥不可及的存在。

那么，这边呢。

穿上校服的洛琪希简直就是一个可爱的国中生，一脸爱困的表情，仿佛对一切事物都漠不关心，即使被告白了也是会被回以「抱歉，我暂时没那方面的打算」残忍拒绝，并且非常容易吸引到我这种坏大叔的毒手，然后我就被警察叔叔以「就是他！这个可恶的○○控，一定要把他绳之以法！」为由抓走，不过，她可是所谓的合法○○哦。

最后，到了这一边。

以双手抱胸双脚张开的姿势站立，外套系在了腰间，还有一对显眼的山峰，活脱脱一个大姐头的模样，平常带着三五个小弟对他们呼来唤去，看到还不错的男生后便一个壁咚用几乎强迫的声音说到「喂，你看起来还蛮不错嘛，跟我交往吧！」挑逗他，然后小弟就会起哄，大姐头看上你了是你的荣幸，还不快接受！

然后，三位却同时喜欢上了一个人，唯独面对那个人时，会展现出常人看不到的样子，害羞的向那个人撒娇，而那个人，就是我。【图片】

