#+title: 同人文或笔记
#+setupfile: ./setup.setup

* 相关评论
- [[https://zhuanlan.zhihu.com/p/142949222][（知乎）禁断？乱伦？无职转生爱莎篇真的毁了这部作品吗？]]
* 同人文
** 龙神的笔记
#+begin_quote
内容复制自b站，经搜索应该原产于[[https://tieba.baidu.com/p/9081090397][百度贴吧]]。
#+end_quote
两百次，不对，快三百次了吧，算了，不重要了。

没有朋友，没有爱的人，没有同伴，没有爱好，什 么都没有。

只有相信着自己一定有一天可以杀死人神，才能继续前进下去。

唯一的乐趣是吃河豚，为此专门学习了解毒魔法。

因为诅咒，人们怕我，可能不止人。

总之他们畏惧我，更不可能信任我，我也不想了解他们，记住他们只是因为这些可能是对抗人神有用的信息罢了。

然后，我有了一个可以称为“朋友”的人。他叫鲁迪乌斯-格雷拉特。他胆子很小，即使没有诅咒，他看见我也会慌张和因为诅咒产生的恐惧不一样，他只是单纯胆子小而已，他比较软弱和自卑，前提是家人没有收到威胁的话。他很不着调，有时会会说很蠢的烂话，有时开无聊的玩笑，偶尔还能看见他被自己妻子打，或者被自己家人吓的往地上一跪，总之完全没有一点强者，或者成熟的人该有的样子，和一个贪玩的小孩子一样。

他给我取了各种外号，老大，老板，boss，社长，吾主等等。

可能是因为他灵魂的缘故，他的家人也不怕我，他的孩子有时会围在我身边玩，张大眼睛看着我，基本是，他的每个孩子都被我抱过，或者骑过我的肩膀，有时甚至会一脸好奇的拽拽我的衣服和头发，菈菈没有这么做，她选择在我的茶水里放酱油，或者在抽屉里放青蛙。

当然他没有一直在玩，他帮我对抗我一直想战胜的敌人，他东奔西跑，非常辛苦，但他一直在努力战斗着。

有时忙了很久回来后，会跑到办公室来滔滔不绝讲上几个小时，任务完成的怎么样，他遇见了谁谁，我家孩子怎么样，我不擅长聊天，但听他讲个不停，到也不错。

偶尔他会给我送一些奇怪的料理，听说是他在另外一个世界喜欢吃的东西，每次他都会兴致勃勃的等我给出评价，像是得到了什么宝贝想向我炫耀。

他也有烦恼，比较孩子成长中的问题，孩子长大了开始叛逆，家里内部出现了特殊情况等等，他似乎一辈子都是在为了家人的幸福而战，或许这就是他自己的幸福。

他不是一个特别完美的人，但他的有种特别的魅力，感染改变了他身边的每一个人，每个人都和我曾经记忆里的不一样。

这就是鲁迪乌斯-格雷拉特。

他是我尊敬的友人。

我抬起头看看周围，这是他当初刺杀我准备的小屋，这么多年装修现在已经很有一个家的样子了。

我站起身，来到对面的椅子旁边，手往椅子上摸了一下。

好厚的灰啊。

毕竟他已经走了很多年了呢。

