#+TITLE: （萌动王朝）刀剑神域08 Early and Late
#+DATE: <2023-08-15 二 11:33>
#+SETUPFILE: ../setup.setup

* 第8卷 Early and Late
** 网站信息

Sword Art Online 第8卷 Early and Late

川原砾
#+begin_center
简介

GAME OVER就等于真正的“死亡”——谜样次时代线上游戏“SAO刀剑神域”你，敢来挑战吗……?

在“完全攻略”之前……谁也别想离开!

SAO玩家-桐人，以完全攻略为目标，在游戏舞台“艾恩葛朗特”城堡里展开一连串严酷的冒
险。

途中与女剑士-亚丝娜的相遇，也为桐人带来命中注定的契机——
#+end_center
#+begin_src txt
≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

作者：川原 礫

插画：abec

原译：S.PIPI（圈内事件），J.C.T.G=SDNagi（圣剑篇）

翻译：J.C.T.G=SDNagi（初始之日）

改编：J.C.T.G=SDNagi ，上月佑一 @ lightnovel

校对：J.C.T.G=3000TK ，rockroxas @ lightnovel

二校：终焉之月 @ lightnovel

顾问：rockroxas @ lightnovel

图源：Ryuki @ lightnovel

监督：J.C.T.G=SDNagi

修图：速水伊织 @ sosg

仅供个人学习交流使用，禁作商业用途

下载后请在24小时内删除

请尊重翻译者的辛勤劳动，在线版如需转载请PM本人

下载版转载随意，但请保留译者信息

≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

本作品是由J.C.T.G和愉快的伙伴们翻译、川原 礫的作品，

请不要对作品翻译质量有过多的期待。

阅读J.C的翻译作品时，

请适度远离电脑，并保持房间明亮。

长时间的阅读有害身体健康，请适度休息。

如果在阅读过程中出现想吐槽，想呕吐的症状，

为了您的身体着想，请立即停止阅读。

而不要挑战自己身体的极限！！

J.C.T.G ALL STAFF

≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
#+end_src

** 第1章
圈内事件

艾恩葛朗特 第五十七层

二〇二四年四月

*** 第1节
到底是要干什么呀，这女的。

刚刚说，“天气真好呀所以正好来睡午觉”这话的的确是我，而为了进行演示再躺回草地的
也是我，不小心睡着的当然还是我。

不过，没想到还没睡到三十分钟，眼睛一睁开，就发现她就还真在我旁边睡熟了，要超乎别
人的预期也要有个限度呀。不知道该说是大胆还是赌气，或者——只是单纯因为睡眠不足吗？

真是没办法啊。左右摇着头表示出一副无可奈何的样子，我仍一直盯着正在发出安稳寝息的
细剑使——工会“血盟骑士团”的副团长，“闪光”亚丝娜那秀丽端庄的侧脸。

★　　★　　★

原本因为今天天气太好让我没有去迷宫区的心思，打算一整天缩在主街区传送门附近的小丘
上数蝴蝶。

实际上天气也真的是非常棒，虚拟浮游城艾恩葛朗特的四季是跟现实同步，但其重现度实在
是太过严谨了，夏季酷热冬季极寒。除了气温外，雨跟风，湿气与尘埃，再加上小虫群这类
的气候参数多到不行，通常有一个参数很好时，就会有一个其他的参数很差。

但今天却不一样。风和日丽，空气中充溢着温柔的阳光，微风既不黏人也不干燥，也没有奇
怪的虫子。就算是在春天，像这样所有的气候参数都是好条件的情况，一整年里也就差不多
五天。

这就像是数码神明在对我们说，今天就好好地恢复一下攻略带来的疲倦，好好地睡个午觉
吧——我擅自这样解释，并且打算率直地接受――虽说是这样。

就在我躺在柔软的草地斜面上时，睡得迷迷糊糊的头旁边突然出现了一双白色的皮靴。同时
有个严厉的熟悉声音传了过来，说道：

——在攻略组的大家正努力挑战迷宫区的时候，为什么你却在这里优哉游哉地睡午觉呢？

眼睛几乎没有睁开的我这么回答道：

——今天的天气可是一年中最棒的，不好好享受还能干嘛呢。

严厉的声音反驳道：

——天气什么的每天都一样。

我再度做出回应，说：

——你只要在我旁边躺下就知道了。

当然实际上的问答更口语化啦，反正到最后，这个女也不知道想了些什么，就真的在我旁边
躺了下来，甚至熟睡起来。

接下来。

时间依旧是上午，我和“闪光”毫无顾忌地躺在草地上接受着来往玩家的视线。有的人吃惊
得眼珠子都快掉出来，有些人在窃笑，居然还有拿出记录水晶进行拍照的无礼之徒。

这也是当然的。说到KoB的副团长亚丝娜，那可是个能让哭泣的小孩都不再哭泣的攻略之鬼
啊，在前线的步调如同装上了高速涡轮引擎。而说到独行【solo】玩家桐人——虽然不是我的
本意——就是个既懒又笨、成天只是在玩的，攻略组当中的不良生。

这两种人居然会一同躺在草地上，即便是身为其中一个当事人的我也都会想笑了。话说回来，
如果把她叫醒大概又会生气，就这样放着不管，我自己先闪人也不失为一个好办法。

——虽然是很想这么做，但实际却行不通。

说到为什么，“闪光”像这样继续熟睡下去的情况下，不仅很有可能会成为各种骚扰行为的
对象——最严重的话，被PK的可能性都不能说是零。

的确，现在这里是位于第五十九层主街区的中央广场的“圈内”。

更确切地说，是在“防止犯罪指令【Anti Criminal Code】有效圈内”。

在这个范围内，玩家与玩家间是绝对不可能互相给予伤害的。就算拿剑去砍，也只会出现紫
色的系统效果光，HP连一滴都不会扣除，各种毒道具也会失效。当然，道具被偷走则是另当
别论。

也就是说，只要在圈内，正如其Anti Criminal【犯罪禁止】之名，一切的直接犯罪行为都
会失效。这和名叫SAO的死亡游戏中“HP归零就等于死亡”一样，是种绝对的规则。

但很遗憾的是，还是有小伎俩可以用。

比如说玩家在熟睡的时候。经过长时间战斗的消耗，接近失神状态的熟睡玩家，有时候就算
受到小小的刺激也不会醒来。有人就会等着这个机会，使用“完全决斗模式”提出决斗邀请，
再把对手的手给移动到OK钮上按下，接着就可以任意宰割了。

或是更大胆，直接把对手的身体整个给运出圈外。双脚直立的玩家会受到“程序代码
【code】”的保护而不能强制移动，但如果使用“担架”这个道具，就能自由地搬来搬去了。

上述的两种情形，过去都实际发生过。“杀人者【红名玩家】”的这份腐朽热情还真是没有
限度啊。吸取了这些悲剧的教训，现在所有玩家都一定会在能上锁的旅馆中睡觉。连我都会
在草地上睡觉前，将“索敌技能”设定为接近警报，更何况我根本不会熟睡。

——不过。

此时此刻在旁边狂睡的“闪光”，不管怎么看都像是处在大量释放δ波的状态，就算拿化妆
道具在脸上涂鸦也醒不来。真是的，该说是大胆还是赌气，亦或是——

“好像真的……很累啊。”

我小声地自言自语道。

在SAO中如果只是为了能力构成、提升等级的话，一个人打怪是最有效率的。但是这个女的，
除了要注意公会成员的等级提升，同时也为了紧跟我的等级而坚持着强化训练。可能是以削
减睡眠时间为代价，一直奋战到深夜吧。

这样做的艰辛我也记忆犹新。四五个月前，我也同样用这种方式疯狂赚取着经验值，那时候
只要一睡着就像陷入濒死一样，好几个小时内是绝对起不来的。

把深深的叹息压了回去，从储存格内取出为长期作战而准备的饮料，再次坐回到草地上。

既然说出睡觉这话的人是我，那么，我就有责任陪她直至醒来。

★　　★　　★

等到浮游城外围的开口部映入橙色的夕照时，随着一声小小的喷嚏，“闪光”亚丝娜总算是
醒来了。

算一算，她竟然整整爆睡了八小时，根本已经不是睡午觉的程度了。我连午饭都没吃一直陪
着她，至少也让我看看冷静的副团长大人，发现这个状况究竟会露出何种有趣的表情吧。

“……恩喵……”

亚丝娜说完这谜样的话后，眨了几下眼睛，抬头看向我。

漂亮的眉毛稍微地皱了起来。接着把右手放在草地上，撑起上半身，栗色头发飘动起来，朝
着右侧、左侧，然后是右侧更远处望去。

最后又再一次，把目光投向了盘坐的我——

雪白晶莹的肌肤瞬间染上了红色（应该是害羞），接着又逐渐变蓝（可能是苦恼），最后又
一次转红（大概是激怒）。

“什……你……为什……”

对着再度说出谜样言喻的“闪光”，我露出了最高级别的笑容，说：

“早安。睡得好吗？”

戴着白色皮革手套的右手，颤动了一下。

不过，真不愧是最强公会的副团长，亚丝娜的自制心很好地发挥了作用，不仅没有拔出腰间
的细剑，也没有突然狂奔逃走。

从紧紧咬住的牙关里，挤出短短的一句话：

“……一顿饭。”

“啊？”

“吃饭，不管多少钱都请你一次。这样就算扯平了，如何？”

我并不讨厌这女的这种直来直往的个性。刚睡醒的脑子马上理解了为什么我花这么长的时间
陪她。不只是帮她防范圈内PK行为，连我是为了让她好好回复平日的精神疲劳而让她尽情地
睡觉这件事情也想到了。

我一侧的脸颊——这次是发自内心——浮现出了微笑，回答说OK。

虽说想要得寸进尺地说“那干脆去你的房间，吃你亲手作的料理”，不过还是忍住了。我两
脚用力向上一蹬，顺势站了起来，伸出右手说：

“五十七层的主街区有个不错的NPC餐馆，我们去那边吃吧。”

“……好吧。”

做出若无其事的样子抓住我的手站起来的亚丝娜，突然把脸转向一旁，仿佛要把整个晚霞吸
进胸中一样大大地伸了个懒腰。

★　　★　　★

名为“Sword Art Online”的死亡游戏，从开服那时起已经过了有一年零五个月了。

当初还认为遥不可及的浮游城艾恩葛朗特的百层楼层，一眨眼就攻破了近六成，现在的最前
线已经到了第五十九层。这么一算，每层大概只用了十天。这究竟是快还是慢，就连攻略当
事者的我也不知该如何评价。如今就稍微保持一定的速度，在中层以上的楼层惬意地过着
“享受生活乐趣”的日子吧。

第五十七层主街区“马汀【マーテン】”，也正是充满着这样浓郁的氛围。由于是距离最前
线仅仅两层下方的大规模街区，自然会成为攻略组的基地以及人气观光地。现在已经将近傍
晚，从前线楼层归来，或是从下层上来吃晚餐的玩家们共同构成了一幅热闹的街景。

从第五十九层传送门移动到马汀的我与亚丝娜，并肩走在人声鼎沸的大街上。许多过往的行
人吃惊得眼珠都快掉了出来，这种状况还挺有趣的。拥有粉丝俱乐部的孤高名花，居然和一
个行迹诡异的独行玩家如此显眼地走在一起，看到的人会不吃惊才怪呢。我想亚丝娜应该是
很想敏捷力参数全开狂奔进目标餐厅才对，但遗憾——或者说幸运的是，目的地只有我才知道。

慢慢感受着这可能到SAO全破之日都再也不会有第二次的机会，走了大约五分钟后，一家稍
大的餐厅出现在道路的右侧。

“这里？”

对着用怀疑的表情愣愣地看着店家的亚丝娜，我点了点头。

“对，比起肉类，我更推荐鱼哦。”

推开Swing Door[fn:171]，用手按住，细剑使则是若无其
事地走进店内。

NPC服务生马上就出声接待了我们，在拥挤的店内移动时，我感到许多视线在往这里集中。
这时，心中的愉快已经被些微的厌倦感给压了下去，受人瞩目成这样，每天都如此的话说实
话就不太有趣了。

但亚丝娜仍然保持凛然的步调穿越楼层中央，往最里面靠窗的桌子走去。我用不太熟练的动
作拉开椅子，亚丝娜则流畅自然地坐了下来。

明明是被请的一方，怎么搞的像是变成了保镖，怀着这种心情的我在对面坐了下来。毫无顾
忌地从餐前酒到前菜、主菜、甜点都点完后，呼地吐了一口气。

嘴唇轻触迅速送来的笛形高脚杯，亚丝娜也跟我一样，长长地吐了一口气。

亚丝娜严肃的眼神稍微放松了些，淡褐色的眼睛望向我，用勉强能够听见的音量说：

“啊……该怎么说呢，今天……谢谢。”

“欸！？”

亚丝娜盯着惊愕的我，再次说道：

“我刚才说的是，谢谢。在旁边守护着我。”

“啊……呀，嘛，那个，不，不客气。”

平日在攻略组的会议上，亚丝娜从BOSS的弱点到前卫后卫的布阵都时常会跟我发生冲突，如
今听到这些意料之外的话，让我不禁讲话都结巴了。看到我这个样子，亚丝娜“呵呵”地发
出窃笑，靠在椅背上。多了一份祥和感的眼睛望向天空，她低语道：

“总觉得……像那样好好地睡上一觉，搞不好是来到这里以后的头一回啊。”

“这……这再怎么说也太夸张了吧。”

“不，是真的。平常，顶多睡大概三个小时就会醒了。”

用杯中酸甜的液体润了润喉，我询问道：

“那个，不用闹钟也会这样？”

“嗯。还不到失眠的程度……只是，被恐怖的噩梦给吓醒的。”

“……这样啊。”

突然，胸口深处产生一阵剧痛。脑海中突然浮现出以前跟我说过同样话的人的面容。

“闪光”也只是个普通的玩家。到现在才发现这种理所当然的事情，我寻找着接下来要说的
话。

“恩……这……怎么说呢，那个，如果还想在外面睡午觉的话，就跟我说一声吧。”

说出了这番自己都觉得很白痴的台词，不过亚丝娜依旧露出了微笑，点了点头：

“说的也是。如果再出现差不多同样是最好天气设定的日子，就拜托你啦。”

这副笑容再次让我发觉到这女的不是一般的美丽，不由得说不出话来。

幸好，这种微妙的氛围被端来盛着沙拉的碟子的NPC给打破了。我用很快的速度把桌上谜般
的香料洒在五颜六色谜般的生菜上，拿起叉子开动了。

在狼吞虎咽的同时，我东扯西扯地拉开话题。

“仔细想想，明明就跟营养没有关系，为什么要吃什么生菜啊？”

“欸，不是很好吃吗？”

很有教养地咀嚼着像是莴苣的东西，亚丝娜反驳道：

“还没到难吃的地步……至少要是有美乃滋之类的东西就好了。”

“啊，是啊。我也这么想。”

“再有就是酱汁什么的……番茄酱啦……还有……”

““酱油！””

两个人同时喊出这话，并一同笑出来——

就在这一瞬间。

从远处某个地方，非常清晰地传来了恐怖的悲鸣。

“……呀啊啊啊啊啊！！”

————！？

凝息起身，手伸向背后的剑。

跟我一样把右手往细剑的握柄伸去的亚丝娜，用完全不同的犀利声音低声说道：

“在店外！”

随后将椅子踢倒，朝出口跑去。我也慌忙追在那白色骑士服背后。

来到大街上的同时，再度传来仿若撕裂丝绢的悲鸣。

大概是从与建筑物相距一个街区的广场上吧。亚丝娜稍微瞥了我一眼，这次完全没有保留地
全力冲向南边。

拼命追赶着那像白色闪电般疾驰的身影，靴底冒出火花来，向东方拐去奔入就在眼前的圆形
广场。

然后在那里，我看见了难以置信的东西。

如同教会般的石造建筑物，耸立在广场的北边。

就在二楼中央的装饰窗，垂下一条绳子，前头的圈环——垂挂着一个男人。

不是NPC。大概是狩猎归来，他穿着包覆全身的厚重板甲，戴着大型的头盔。绳子紧紧缠在
盔甲的颈项部分，但令广场上聚集的玩家们恐惧得倒吸一口气的并不是那个。在这个世界里
并不会死于绳子类道具所带来的窒息。

恐惧的根源，是一支深深贯穿男人的胸部的黑色短枪。

男人用双手紧抓住枪柄，嘴巴一张一合地动着。在此其间，从胸部的伤口处闪烁着仿佛喷出
的血液般的红色效果光。

也就是说在这个瞬间，男人的HP在持续地受到伤害。这是只有一部分枪系武器才有的特性，
“贯通持续伤害”。

看来，这把黑色短枪是特化了持续伤害的武器。枪柄上可以看到生有无数的倒刺。

我瞬间便从惊愕中回过神来，大声叫道：

“赶快拔掉它！！”

男人稍微看了我一下。两手缓慢地动起来，虽然想要把枪拔掉，但是刺进体内的武器却没那
么容易移动。死亡的恐怖，更让手使不上力气。

悬挂在壁面上的男性虚拟体，与地面最少也相距十米。以我的敏捷力状况来看，那是无论怎
样跳跃都无法触及的距离。

那只好拿投掷用的短锥[fn:32]把绳子切断了吗，但是如果丢偏，打中男人的话。那就会把残余的HP
减到零了。

按常理考虑的话，这里是“圈内”，所以这种情形是不可能发生的。但如果这么说的话，那
把枪也应该是不可能造成伤害的。

亚丝娜尖利的喊叫声，传入了犹豫着的我的耳内。

“你在下面接好！”

之后马上用惊人的速度往教会的入口直奔而去。看起来是要走里面的楼梯，直接登上二楼把
那绳子切断。

“明白了！”

对着亚丝娜背后这样大声回应道，我冲向男子的正下方。

——不过。

大约跑到一半的时候，从大型头盔下窥见的男人双眼，突然凝视起空中的一点。直觉让我察
觉到，他像是在看着什么。

自己的HP条。更确切地说，是它归零的瞬间。

在充斥着广场的悲鸣与惊叫声中，男人像是想大叫出什么来。

接着——随着像是无数的玻璃破碎的声音，蓝色的闪光照亮了漆黑的夜空。我只能呆呆地望着
爆散开来的多边形碎片。

失去了绑缚的物体，绳子无力地撞上壁面。一秒后，掉落下来的黑枪——或是称为凶器，发出
重重的金属声插进了我面前的石板上。

无数玩家发出的悲鸣，将街区里回荡着的和平的BGM压了下去。

我受到了强烈的冲击，努力地睁大眼环视着以教会为中心的宽广空间，寻找着应该存在——一
定非出现不可的东西。

也就是“决斗胜利者宣言消息”。

这里是主街区，也就是防止犯罪指令的有效区正中心。在这里发生玩家受到伤害，甚至死亡
的情况，只有一种原因。

那就是答应使用完全决斗模式，并且败北的时候。

除此之外根本不可能，绝对。

那么在男人死亡的同时，“WINNER/名字 比试时间/几秒”这种形式的巨大系统提式窗应该
会在附近出现才对。只要看到这个，马上就能知道用短枪秒杀了这名穿着全身金属铠男的人
是谁。

——理应如此，不过。

“……在哪里……”

我不由自主地念叨起来。

系统提示窗没出现。广场上哪里都没有。显示的时间只有三十秒而已啊。

“大家！找一下决斗的胜利者是谁！！”

我用压倒周遭嘈杂声的大音量叫道。玩家们好像也立刻领悟了我的意图，开始查找着四面八
方。

但是，没人出声说找到了。已经过去了十五秒。

那么就是在建筑物里吗？消息出现在垂挂着绳子的教会二楼房间里吗？这样的话亚丝娜应该
会看到。

刚想到这里，从出事的窗口刚好看到了“闪光”的白色骑士服。

“亚丝娜！！看到胜利者了吗！？”

平常根本不敢舍弃称谓直接叫她，不过现在时间紧迫，我就直接问道。但那跟衣服一样苍白
的脸，很快便左右摇了摇。

“没看到！没有系统提示窗，里头也有没任何人！！”

“……为什么……”

我呻吟着望着空旷的四周。数秒后，传来了不知是谁的低语声。

“……没办法了，已经经过三十秒了…………”

从教会一楼常驻的NPC修女旁边跑过，我冲上建筑物内部的阶梯。

二楼是如同旅馆单间似的四个小房间，不同的是无法上锁。经过的三间房间，不管是用肉眼
或是索敌技能都探测不到躲起来的玩家。我咬紧嘴唇，踏进第四间，也就是出事的房间中。

从窗旁回头看向这边的亚丝娜，虽然还是保持着镇定的表情，果然内心应该是受到了冲击吧。
我也是一样，没法掩盖眉头紧皱的样子。

“教会里没有其他任何人。”

报告完毕后，KoB副团长马上回问道：

“用有隐蔽能力的斗篷躲起来的可能性呢？”

“可以让我的索敌技能无效化的道具，就连最前线都不会掉落。而且为了保险起见，我在入
口处让玩家站在了那里堵得密不透风。就算透明化想要逃出去，只要被接触到就会马上发现。
这个建筑物也没有后门，有窗户的房间只有这间。”

“嗯……我明白了。你看下这个。”

亚丝娜点了下头，用戴着白手套的手指向房间的一角。

那里放着一张简朴的木制桌子。没办法移动，也就是所谓的“坐标固定物体”。

在它的一只脚上，绑了条有点细但是很牢固的绳子。虽说是绑，不过并不是真的用手去绑。
绳子的弹出视窗出现后，选择结束按钮，再按一次对象物体就会自动成为固定构造。只要绑
上去，在悬挂超过绳子耐久度的重物或者用刀刃砍断之前都不会自动崩断或解开。

发出黑色光泽的绳子，横跨过两米的空间，垂挂在南侧的窗户外。从这边虽然看不到，但是
前端有个环，全身铠甲男的脖子就是吊在那上面。

“嗯…………”

我低下头，念叨道：

“这情况，到底是怎么回事啊？”

“一般来说的话……”

同样也低下头的亚丝娜答道：

“……那个玩家的决斗对手绑好这条绳子，在他胸口刺上一支枪，还把他的脖子挂在那个环
上从窗户推了下去……大概是这样吧……”

“是杀鸡儆猴吗……？不，但是，在这之前。”

我大大地吸了口气，用清晰的声音告知：

“胜利者的显示哪里都没发现。广场上蜂拥而来了几十人，却谁都没看到。如果是决斗的话
一定会在附近出现才对。”

“但是……不可能啊！”

尖锐的反驳。

“在‘圈内’要给予HP伤害，只有提出决斗申请，并且答应了才有可能。这事你也是知道的
吧！”

“……啊，没错，就是这样。”

我们两人相互看了看后，都沉默了下来。

正如亚丝娜所说，绝对不可能的事情发生了。但是我们知道的，仅是有一名玩家在众目睽睽
之下死掉，至于谁、为什么、怎样做的，这些我们完全不知道。

从窗外的广场，传来的依旧是玩家们尚未停歇的嘈杂声。他们也注意到这个“事件”的异常
处了吧。

过了一会儿，亚丝娜盯着我，说：

“不能任由这事这样下去。如果真的有谁发现‘圈内PK技’之类的话，不赶快公布对抗手段
一定会酿成大乱的。”

“……虽然少有，但这次我无条件同意你的说法。”

对着点头的我，“闪光”稍微露出了苦笑，径直伸出了右手。

“那么，到事件解决前我们就互相帮助吧。不过要先声明，可没有午睡的闲暇了。”

“睡觉的不是你吗……”

低声嘟囔道，我也伸出手去。

临时组成的侦探&助手搭档——究竟谁是侦探谁是助手暂时不明——通过白与黑的手套，双手紧
握在了一起。
*** 第2节
回收完“证据物件”的绳子，我和亚丝娜走出小房间，回到教会的出入口。将同样是证物的
黑色短枪，已在行动前就放进道具储存格了。

对拜托在入口处看守的两名脸熟玩家道谢，并询问了下，果然连一个人都没有通过。走出广
场的我，朝注意到这边的看热闹的人们举起手，大声喊道：

“不好意思，从一开始就目击到刚才那起事件的人，如果在的话，可以向你请教一些事情
吗？”

几秒后，一名畏畏缩缩的女玩家从人群中走了出来。对她的脸并没有什么印象，装备也只是
NPC制的普通单手剑，大概是从中层来的观光客吧。

意外的是，女孩子看到我后露出了一副胆怯的表情，亚丝娜替我向前迈出一步，温柔地问道：

“真对不起，刚刚才遭遇可怕的事情。你的名字是？”

“那……那个，我叫，优尔可。”

这微微颤抖的声音我确实听到过。于是不禁插话道：

“难道刚刚的……最早的悲鸣声，是你发出来的？”

“是……是的。”

略显波浪状的深蓝色头发动了动，名叫优尔可的女玩家点了点头。从虚拟体的外表来推测，
年龄大概十七八岁吧。

与头发同样是深蓝色，纯朴的眼睛中，突然浮现出淡淡的泪光。

“我……我跟刚刚……被杀的人，是朋友。今天约好要来这里一起吃饭，但是在这广场走散
了……然后……然后就…………”

再也说不出更多的话，优尔可用双手捂住了嘴。

亚丝娜扶着她颤抖的柔弱双肩，带着她往教会内部走去。让她坐在几列并排放置的长椅上的
其中一张上，自己也坐在她身旁。

我站在稍远一点的位置，等待女孩子冷静下来。如果是从头到尾看到友人遭受如此残酷的手
段PK而死，受到的冲击大概很难以想像吧。

亚丝娜轻抚优尔可的背部，一段时间后，她停止了哭泣，用细微的声音道了声歉。

“嗯嗯，没关系。多久都可以等，冷静下来，好好地跟我们说，好吗？”

“好……已……已经没问题了。”

真是出人意料的坚强啊，优尔可握住亚丝娜的手调整了一下坐姿，点了点头。

“那个人……叫作凯因兹。我们曾是同一个工会的……现在，也偶尔会和他组队，或是吃
饭……然后今天，也是要在这条街上吃晚餐的……”

一度紧闭双眼的她，用还颤抖着的声音继续说：

“……但是，人实在太多了，就在广场走散了……我正在周围到处寻找时，突然，从这间教
会的窗户，有人——凯因兹掉了下来，被吊在了空中……而且，胸部，枪还……”

“那个时候，看到其他人了吗？”

对于亚丝娜的提问，优尔可瞬间沉默了下来。

接着慢慢地，但很明确地点了点头。

“有……只有一瞬间，不过凯因兹的背后，好像……站着一个人……”

我无意间紧握起双拳。

果然，犯人是在那个房间里吗？如果是这样，那就是把被害者——凯因兹从窗户推落，而且还
在众目睽睽之下悠然逃走了。

这么说，果然是使用了带有隐蔽机能的装备，不过这类型的道具，在移动中的效果会变弱。
难道是有能够补足这一缺点的高等级隐蔽技能吗？

脑海中闪现出“暗杀者”这个危险的词汇。
    
难不成在这SAO里，还有我跟亚丝娜不知道的武器技能系统存在吗？那个技能的特性，还能
够让防止犯罪指令无效化……？

大概是同时想到一样的事吧，亚丝娜的背部瞬间颤抖了一下。不过很快就抬起头来，向优尔
可问道：

“那个人影，你认识吗？”

“…………”

优尔可暂时紧紧闭上嘴陷入沉思，数秒后，像是没有答案似的摇了摇头。看到这里，我这次
尽可能的用平和的语气询问起来。

“那个……虽然听起来不舒服，不过你心里有数吗……？凯因兹先生，之所以会被人盯上的
原因……”

像是十分害怕似的，听到这话的瞬间优尔可便浑身僵硬起来。这倒也是，向朋友刚刚被杀害
的女性玩家，询问被害者是怎样的人，难道有这样做的么，我自问到。但这个问题虽然有失
考虑，不过却不能省略。如果知道有谁憎恨凯因兹的话，可是很有帮助的。

不过，优尔可这次也是摇了摇头。

看到她有些沮丧的样子，“这样啊，抱歉”我简短地道了声歉。

当然，优尔可也只是不知道这些。但是，杀了凯因兹的犯人，虽然确实是真正的杀人者，但
同时也是MMO游戏里的“Player Killer”。而PK这种行为，动机基本上都有着“想把其他玩
家杀掉”这种理由。现在，横行于艾恩葛朗特暗处的红名玩家们就是典型的这种人。

也就是说，用谜样的手段在圈内PK掉了凯因兹的玩家的候补者，除了提到的数百名橙名以及
红名者，还扩大到了那些具有这种潜在倾向的人们身上啊。说实话，究竟要怎样锁定到一个
人身上才好，现在还没有头绪。

又像是同时得出这个结论似的，亚丝娜也无力地叹了一口气。


★　　★　　★

因为优尔可说一个人回到下层很可怕，于是便把她送到最近的旅馆，之后我和亚丝娜就暂且
先回到了转移门广场。

距离事件发生已过了约三十分钟，人数也总算开始减少了。即便如此，为了听取我们的报告，
依然有近二十人还留在那里，主要都是攻略组的玩家。

我和亚丝娜告诉了他们被害者叫做凯因兹，以及杀害手法依然不明的消息。随后根据这件事，
推测出恐怕存在着未知的“圈内PK”手段的危险。

“……因为这样，就算是在街上最好也要注意，还有要尽可能进行大范围的警告。”

对于我的这番总结，大家都用严肃的表情点了点头。

“知道了。我会去拜托情报商，在报纸上也刊载这事。”

隶属某个强大工会的玩家代表其他人这样做出回应后，便就此解散了。我稍微确认了一下视
野角落处显示的时间。还只是晚上七点多，这让我有点吃惊。

“那……接下来该怎么办呢？”

对身旁的亚丝娜这么问道，不一会儿便得到了回答。

“先把手边的情报检查一下吧。特别是绳子跟枪。知道由来的话，也许就可以从那边找到犯
人。”

“原来如此……找不到动机的话，就只能从物证下手了。话说回来，这需要鉴定技能呢。你
应该……不可能练了吧。”

“当然，你也是吧……这样的话……”

此时亚丝娜的表情首次有了变化，径直看向我。

“那个‘你’的叫法能不能改一改呢？”[fn:33]

“咦？……啊，啊啊……那，那个……‘您’？‘副团长’？……‘闪光大人’？”[fn:34]

最后那个，是这个女的的粉丝俱乐部发行的会刊内所使用的称呼。效果立刻出现，亚丝娜对
我投以激光般灼热的视线，扭过头去，说道。

“普通地叫我‘亚丝娜’就好了。刚刚也是这么叫的吧。”

“知，知道了。”

哆嗦起来的我老老实实地点了下头，慌忙把话题再次拉了回去。

“那么，关于鉴定技能……有朋友之类的练了吗……？”

“嗯。”

考虑了一瞬间后，亚丝娜立刻点了点头。

“我有一个朋友是开武器店的，但现在是她最忙的时间，还是不要去拜托她比较好……”

现在这个时间，是玩家结束一天的冒险，要整理或更新装备的时间段。

“是么。那，虽说熟练度有点无法保证，拜托我认识的杂货商斧战士好了。”

“是……那个很高大的人？艾基尔先生……吗？”

对迅速打开视窗，开始写讯息的我，亚丝娜在一旁说道：

“不过，就算是杂货商，这个时间应该很忙吧？”

“管他呢。”

这么回答着，我毫不留情地按下送信键。

★　　★　　★

迎接从第五十层主街区“阿尔格特”的传送门走出来的我跟亚丝娜的，依旧是那杂乱无章的
喧闹声。

明明传送门才刚开放没有多久，已经变得热闹起来的商店街上就有许多玩家的商店开张了，
一间挨着一间。理由就是，此处开设店铺所需要租金跟下层的街道比起来，设定得简直是惊
人的便宜。

当然相对的，这里的店都很小，外观也很脏，但是喜欢这种亚洲风格——或者该说是类似于某
条电器街的混沌感的玩家也很多。我也是其中一个，最近还有在这里购买玩家房间的预定。

在由异国情调的BGM与招呼客人的叫卖声，以及从小摊飘来的令人上瘾食物香味所混合而成
的空气中，我领着亚丝娜快步行走着。白色骑士服的短裙下毫不吝惜地露出修长双腿的细剑
使的身姿，在这街上多少有些太过显眼了。

“喂，快点走……”

意识到左后方的脚步声逐渐远去，回头看去的我，眼珠像要掉出来似的大叫道：

“你在买什么吃的啊！”

咬了一大口从可疑的小摊买的可疑串烧肉，“闪光”大人不慌不忙的答道：

“因为，刚才只吃了沙拉就飞奔出来了啊……嗯，这个味道还挺不错呢。”

嘴巴一边咀嚼着，一边说“这个给你”，把左手握着的另一串朝我递来。

“欸？给我的？”

“因为今天一开始就是这么说的啊。”

“啊……啊啊……”

反射性地低下头接过串烧，我才终于发现请全餐变成请串烧。顺带一提的是，刚去的那家餐
厅的消费，在奔出店铺时直接从双方的物品栏平均扣除了。

嚼着民族风味的谜样肉串，我发誓以后绝对要让这女的亲自为我下厨，并继续向前走去。

在两支串烧彻底消失的同时，我们到了目标杂货店。握着的竹签悄无声息地消失了，我张开
手，虽然没有沾上什么污渍，但还是在皮革大衣上擦了擦，然后对着背朝着我们的店主喊道：

“哟，我来了。”

“……我才不会对不是客人的家伙说‘欢迎光临’呢。”

杂货商兼斧战士艾基尔，用与他那巨大身躯以及魁伟的面貌完全不相称的低声下气的语调，
向狭小店内的客人招呼道。

“真抱歉，今天要关店了。”

对着发出不满声音的客人，艾基尔那强壮的身躯不断低头道歉，并把所有人都请了出去，从
店铺的管理菜单中选择了关店。

在混乱至极的陈列柜自动收纳，并哗地关上外面的铁门后，艾基尔总算是朝向了这边。

“我说桐人啊，商人的处世原则一是信用二是信用，三跟四没有，五就是发横财……”

这则奇怪的格言，在看到我旁边站的玩家后就瞬间消失了。对着楞在那里，秃头下生长的胡
须微微颤抖起来的艾基尔，亚丝娜露出爽朗的笑容并低头说道：

“真是好久不见了，艾基尔先生。这样急着拜托你非常抱歉。但无论如何，我都很希望能马
上借用你的力量……”

严肃的表情瞬间瓦解，艾基尔立刻拍起胸膛答应帮忙，并且连茶都拿了出来。

男人还真是个绝对无法抵抗先天本能的悲哀种族啊。

*

在二楼的房间听完事件经过的艾基尔，好像也察觉到事情十分重大，突出的眉角下的双眼眯
了起来。

“在圈内HP变成零，是吧？——你确定这不是决斗造成的？”

听到巨汉的浑厚男中音，靠在摇椅上的我慢慢地点了点头。

“那种情况下，肯定会有人看到胜利者宣言弹窗的，我现在也是这么认为。而且……即便是
决斗，也不应该在吃饭的地方提出，还是‘完全决斗模式’应该不可能有人接受的吧。”

“在那之前还和那孩子……优尔可一起闲逛，也不像是‘睡眠PK’。”

晃着小圆桌上的马克杯，亚丝娜补充道：

“第一，如果是突发性的决斗，那未免准备得也太周到了。认为是事前就谋划好的PK比较妥
当。在那里……找到了这个。”

我调出窗口，从道具栏中首先把问题绳子实体化，交给了艾基尔。

绑在桌子脚上的那一头，当然在回收时已经解开了，但是另一端仍旧维持着大圆环的形状。

艾基尔把圆环那一头拿到眼前，表情厌恶地哼了声，用粗大的手指点了下。

从打开的弹出窗口中选择了“鉴定”菜单。没有练过这种技能的我跟亚丝娜，即使做这种事
也只会出现失败提示，如果是商人艾基尔的话，应该能获得某种程度的情报才对。

巨汉终于用他那粗重的声音，解说起只有他能看到的窗口内容。

“……很遗憾，这不是玩家制造的，是NPC商店卖的泛用品。级别也不是很高，耐久度减少
了近一半。”

我边在脑中回想着那可怕的场景，边点了点头。

“应该也是吧。把那种重装备的玩家给吊在下面，应该是很沉的重量啊。”

但以杀人者的立场来看，只要能够坚持十多秒让那名男性玩家的HP归零，爆散开来就足够了。

“嘛，本来就没有太期待绳子。真正重要的是这个。”

我点了下还开着的道具栏，把另一件道具实体化。

漆黑光泽的短枪沉重的存在感充斥着整个狭小的房间。就武器的级别来说，跟我和亚丝娜的
主武装相比简直微不足道，但问题并不在这里。这把枪，是残酷地夺走了一名玩家的生命，
真正的“凶器”。

我尽量不让它有所磕碰，慎重地交给了艾基尔。

全身都是用同种素材的黑色金属打造而成，即使在同类的武器中这也是很少见的。长度大约
一米五，握柄大概有三十厘米，沿着枪柄，十五厘米长的尖端闪烁着锐利的光泽。

而其特征，是整个枪柄上到处都长有短小的倒刺。这样的话只要深深刺入后，不拔出来就会
产生特殊效果。即便要拔出来，也会需要很高的力量值才对。

这种情况下的力量值，除了玩家设定的数值参量，也和从脑部释放并由NERvGear从延髓截获
的信号强度有关。在那个瞬间，被死亡的恐惧所吞噬的重甲男——凯因兹，没办法产生让虚拟
体活动的明确信号。所以就算两只手抓紧枪身，也没办法拔出来。

这么一想，这果然不是简单的突发PK，而可以称得上是“计划杀人”么，这种想法变得越发
强烈了。而且，由“贯通持续伤害”所带来的死亡是十分残忍的。不是因为对手的剑技，也
不是武器的威力——而是被自己的恐惧所杀害。

我这刹那间的思考，被结束鉴定的艾基尔的声音给打断了。

“是PC造的。”[fn:35]

我和亚丝娜同时向前探身。“真的吗！”不禁大叫了出来。

PC制成品，也就是习得“锻冶技能”的玩家制造的武器的话，上面一定会记录有玩家的
“铭”。也就是说这把枪，大概是特别订做的独特物品吧。只要直接询问制造的玩家，他会
还记得下单·购买者是谁的可能性也很高吧。

“这把枪的制造者是？”

听到亚丝娜急迫的声音，艾基尔望着系统窗口答道：

“‘葛林姆洛克’……拼法是‘Grimlock’。没听过啊。至少不是一流的刀匠吧。嘛，也不
是没有为了打造自己用的武器，去提升锻冶技能的家伙呢。”

连身为商人的艾基尔都不知道的锻造师，我跟亚丝娜就更不可能知道了，狭窄的房间里再度
陷入了短暂的沉默。

不过很快，亚丝娜便用僵硬的声音发话道：

“不过，应该找得出来的。既然是能作出这种级别的武器的等级，我认为他不可能一直都是
独行。只要在中层的街道打听，一定可以找到跟‘葛林姆洛克’组过队的人。”

“的确是呢。跟这家伙一样白痴的人，大概找都找不到吧。”

艾基尔深深地点了点头，与亚丝娜一同向我这个白痴独行玩家望来。

“什……什么啊。我，就算是我偶尔也会跟人组队的哦。”

“只有在BOSS战的时候吧。”

被冷静地吐了声槽，没办法反驳的我只得乖乖闭上了嘴。

哼了一声后，亚丝娜再次望向艾基尔手中的短枪。

“嘛……说真的，就算找到葛林姆洛克先生，我感觉他也不会愿意谈论这些的。”

关于这点我也持相同意见。

杀死凯因兹的，的确是订做这把枪的未知红名玩家，而不是锻造师葛林姆洛克。拿着自己打
造的，也就是记录有制造者“铭”的武器把谁杀掉了，就等同于现实世界中拿着刻有名字的
凶器菜刀刺杀了某人一样。但只要是有某种程度的知识与经验的职人玩家的话，应该可以推
断得出这把武器究竟是出于什么目的设计的。

“贯通持续伤害”，对基本的怪物对手效果很差。因为按照算法活动的Mob，是不知道恐怖
的。就算被贯通武器刺中，在Break Point[fn:36]产生后，是会被怪物握住并拔出来的。当然，那
之后也不会亲切地把武器还回来，而是会扔到很远的地方，不到战斗结束都无法回收。

也就是说，这把枪当初就是以对人使用为目的而制造的东西。我所认识的所有锻造师，只要
在被告知设计要求时就会马上拒绝委托。

但葛林姆洛克却将这把枪打造了出来。

虽说不太可能是杀人者本人——只要鉴定过就很容易暴露出名字——不过，他却是个伦理观念相
当淡薄的人，或者是隶属于秘密红名公会的玩家。

“……听了这些话，多少也应该感觉这事非同一般啊。如果你还要收取情报费的话……”

我低声说道，随后艾基尔摇了摇头，亚丝娜则是往我这瞥了一眼。

“我们平摊费用吧。”

“……知道了，反正已经上了贼船了。”

耸耸肩，朝唯利是图的商人问出了最后的问题。

“虽然不觉得会成为线索，姑且还是告诉我武器的固有名吧。”

秃头的巨汉，第三次往向窗口：

“嗯……叫作Guilty Thorn。就是罪之棘。”

“……唔。”

我再次望向短枪柄上那密布的倒刺。当然，武器的名称是系统随机命名的。所以这名字本身
也不可能会有什么“人的意志”蕴含在内。

——但是。

“罪之……棘……”

仿佛细语一样的亚丝娜的声音里，似乎带着些寒冷凄凉的感觉。
*** 第3节
我和亚丝娜，以及助手艾基尔一同经由阿尔格特的转移门，首先前往最下层的“初始之街”。

目的是要确认安放在黑铁宫里面的“生命之碑”。就算要去找锻造师葛林姆洛克氏，如果他
已经死亡的话就什么办法也没有了。

虽然已经是春天，广阔的初始之街还是被荒凉的氛围所笼罩着。

应该不止是天气参数的关系。被黄昏覆盖的宽广街道上几乎没有玩家的身影，不知道是不是
错觉，就连NPC乐团演奏出的BGM也尽是些郁闷的小调旋律。

最近，这里有着最大公会的下层自治组织“艾恩葛朗特解放军”，对玩家采取了宵禁的这类
传言，看来还真有可能是这样。在外面的玩家，都是身着制式统一的青铜局部护甲的“军
队”巡逻兵。

而且这些家伙在看到我们时，就像是辅导中学生的巡警一样马上冲了过来。不过，当看到站
在最前面的亚丝娜那绝对零度的视线时，就马上走开了。

“……这样子，也难怪阿尔格特会那么热闹呢……明明物价就很高……”

我不自觉地感叹道，艾基尔则是说出了更为可怕的谣传：

“最近，军队好像要开始向玩家们‘征税’了哦。”

“啥！？税金！？……骗人的吧，要怎么征收啊。”

“这点还无从得知……大概是从怪物的掉落中直接抽成吧。”

“你店里的营业额也会被征税的哦。”

一边持续着这类倒胃口的话题一边前进的我和艾基尔，在踏上黑铁宫的石板的一瞬间，都沉
默了下来。

正如名字所示，这是座仅仅由散发着黑色光泽的铁柱与铁板组成的巨大建筑物，气温明显要
比外面低了好几度。向前走去的亚丝娜好像也感觉很冷，搓起露在外面的双臂。

可能是因为时间比较晚了，里面没有其他人的身影。

在白天，那些不相信友人或恋人已经死亡而来这里确认，在看到名字上刻着无情的横线后泪
腺崩溃的玩家们的恸哭声不绝于耳。或许明天，被那把枪夺走性命的凯因兹的友人，同时也
是事件目击者的优尔可也会来此确认吧。这样说来，在不远的过去我也做过相同的事情。直
到现在，我也没能完全跨越这辛酸的回忆。

我们快步走在被蓝色火光照亮的无人大厅里。

来到宽数十米的生命之碑前时，在按照英文字母顺序排列的无数名字中，凝视着“G”附近。

艾基尔没有停下来，就这样向右边走去。我和亚丝娜则屏住呼吸在列举出来的玩家名字中开
始寻找，很快就发现了那个名字。

“Grimlock”。横线——并没有。

“……还活着呢。”

“是啊。”

同时呼了口气。凝视着稍远处“K”区的艾基尔很快也走了回来，用一副严肃的表情说：

“凯因兹的确已经死了。死亡时间是樱花之月【四月】二十二日，十八时二十七分。”

“……日期和时间都没错。就是今天傍晚，我们从餐馆中跑出来的时间。”

亚丝娜这样轻语后，低下头，闭上了长长睫毛下的眼睛。我和艾基尔也同时进行了简短的祷
告。被杀害的凯因兹——“Kains”的拼法已经向优尔可确认过了。

所有的事情办妥后，我们快步离开了黑铁宫，一起把压抑在心头的那口气给吐了出来。不知
何时，街区的BGM已经换成了深夜用的舒缓华尔兹。NPC商店都已经拉下铁门，照亮街道的只
剩下了矗立着的路灯。就连“军队”的巡察都看不到了。

我们无言地回到转移门广场后，走在前方的亚丝娜转过头说：

“……寻找葛林姆洛克氏的事情，就从明天开始吧。”

“也对……”

我点了点头，艾基尔魁伟的眉头皱成了八字。

“那个啊……我啊，大体上本业并不是战士而是商人呀……”

“知道啦。今天就解雇掉你这个助手吧。”

拍了拍艾基尔的背，只见他露出了安心的表情，并说了句“抱歉”。

这个老好人巨汉，也不是发自内心地认为“赚钱优先”啊“调查麻烦”啊之类。大概是讨厌
和制作那把灾祸短枪的玩家直接面对吧。并不是害怕，而是刚好相反——害怕自己那理应对怪
物发出的怒火会忍不住对着那名锻造师爆发出来吧。

加油啊，你们两位，留下这话的艾基尔便从转移门消失了，亚丝娜则是要回一次公会总部，
所以我们就在这里暂时告别了。

“明天早上九点在五十七层的转移门前集合。不要睡懒觉，准时到哟。”

你是老师还是我姐啊——虽然现实世界的我没有姐姐——听到亚丝娜的话，我苦笑着点了点头。

“知道了。你才是，今晚要好好睡觉啊。要不，继续在你身边看着——”

“才不要呢！”

丢下这话，KoB的副团长飞快地转过身，划出白与红的残像奔入了转移门中。

只剩下一个人的我，站在摇曳着蓝色光芒的转移门前，稍微回想了下今天一天发生的事。最
初只是“天气很好的日子”，和那个“闪光”亚丝娜一起午睡，然后本应两人共进晚餐，却
突然被卷入了圈内杀人事件当中，现在则是成了向事件的谜题发出挑战的侦探，或者说是助
手。

浮游城艾恩葛朗特的每一天虽然都是纯粹的“非日常”，不过自从二〇二二年十一月六日这
个死亡游戏开始以来，已经经过了一年半的现在，包含我在内的大部分——至少也是生活在中
层以上的玩家，在意识上都已经忘记了在现实世界里生活过的这件事，而是活在了剑与战斗，
金钱与迷宫交织而成“日常”中。

不过今天的事件，再次将我拉回了某种非日常中。这件事，难道会成为某个永久性变化的开
端吗……

思索着这些，我也向前走了几步，迈进了蓝色的转移门内。用声控命令指定我现在的定居点，
也就是四十八层主街区“琳达司”，随着周围的光线逐渐变强，我的身体也被一股浮游感包
围。

鞋底再次接触到地面，我踏上色泽发生了变化的石板路面，周围的景象也随之一变。我来到
琳达司的街区主城也只有一周时间，不过这里纵横交错的水路和到处都装设着水车的构造让
我非常喜欢。虽然这么说，晚上十点才回来，这个时间的街区已经被夜幕笼罩，白天时街道
上到处都能听见的锻冶屋的槌声也听不到了。

是谨遵副团长话直接回旅馆睡觉呢，还是溜进尚未关门的NPC酒馆喝一杯呢，想着这些便离
开了转移门广场的我……

突然间被六七名玩家们一起围住了。

一瞬间，我差点把背后的剑拔了出来。就算被几十人围住，只要在“圈内”就没有任何危险，
但这种常识就在这几小时内有些动摇了。

不过，我的右手指仅仅是动了动，算是控制住了拔剑的冲动。

这个集团的脸，我很肯定自己见过。他们是就算在攻略组公会中也是数一数二的最大型公会
“圣龙联合”所属的玩家。我面对半圆形队列中具有领袖气质的一名玩家，开口说道：

“晚安，修密特先生。”

被我抢得先机笑着打了招呼的高个子长枪使，顿时说不出话来，他皱了皱眉头后，用很快的
语速说道：

“……我在这里等你是有事情想打听，桐人先生。”

“欸。我的生日和血型……应该不是这个吧。”

听到我下意识做出的马虎回答，运动部主将般的短发下，粗大的眉毛微微颤动了下。

虽然同样也是攻略组，并不是什么敌对关系，但我跟“圣龙联合”却不怎么合得来。相比之
下，我还是和亚丝娜率领的“血盟骑士团”相处得要好些。

因为相对于血盟骑士团的目的“最快攻略游戏”，圣龙联合则是更倾向于“最强公会的荣
誉”。他们基本上不与公会外的玩家组队，狩猎场的情报也不怎么积极公开。更有甚者，他
们还对于给予BOSS怪物最后一击——会有道具掉落的判定加成——这点异常地执着。

不过仔细想想，他们也许是最享受SAO这游戏的人，因此我也不好再说些什么，但我却两次
拒绝过他们的入会邀请。因此，我们之间的关系并不是十分友善。

而现在，背靠转移门广场墙壁的我被七人组成的半圆包围，他们之间的间隔也保持着微妙的
距离。虽然还不到围住玩家让他无法动弹的“BOX”骚扰行为，不过只要我想走出这个包围
圈，就不可避免地会碰触到他人的身体，这也是一种很不礼貌的行为，在我犹豫时就变成了
这种“莫名其妙的BOX”状态。

抑制住自己的叹息，我改变语气对修密特问道：

“可以回答的话我就会说。你想问什么？”

“傍晚，发生在五十七层的圈内PK骚动事件。”

那立刻回答的内容，也在预料之中。我轻轻地点了点头，靠在石壁上抄起双手，用视线催促
他继续说。

“并不是决斗……这个传言是真的吗？”

听到这低沉的问话，我稍微想了一会儿，耸了耸肩说：

“至少可以确定，并没有任何人看见胜利者表示视窗。但也不能否定由于某种原因，在那里
的所有人都看漏了的可能性。”

“…………”

修密特那棱角分明的下巴紧紧地咬住，脖子附近的装甲发出了碰撞的声响。

身为圣龙公会的一员，玩家的护甲都是以银为主色，再用青色加以点缀的涂装风格。背在身
后的主装备长枪，长度有近两米，锋利的尖端还很周到地挂上了三角形的公会会旗。

短暂的沉默后，修密特用更加低沉的声音说：

“被杀掉的玩家的名字……听说是‘凯因兹’，没错吧？”

“目击了整个事件的被害者的朋友是这么说的。刚才去黑铁宫确认过了，时间和死因都是一
致的。”

咕噜，看到那粗犷的喉咙动了动，这时就连我都察觉到有些不太对劲了。于是歪了歪头，回
问道：

“是你认识的人吗？”

“……与你无关。”

“喂喂，没有我被单方面质问的道理吧……”

此话一出，立刻遭来了一阵怒吼。

“你也不是警察吧！虽然你好像跟KoB的副团长一起行动，那也没有独占情报的权利！”

声音大得就连广场外都听得到，周围的成员们也疑惑地互相看了看。看样子，是修密特并没
把事情讲清楚，就把这些人给找来了吧。

也就是说，可能与这次事件有关联的应该不是公会圣龙联合，而是修密特个人才对。原来如
此，在脑中记下这件事，眼前突然伸来了一只戴着长手套的右手。

“我知道你从现场，回收了那把PK中使用的武器。应该已经充分调查过了，给我吧。”

“……喂喂。”

这是明显违反规矩的行为啊。

在SAO中，只要是没有装备的武器掉在地上，又或者是谁刺到怪物身上后走远了，三百秒后
持有者信息就会被清除。那件道具在系统上和一般认知中就变成了接下来捡到它的人的东西。
那把黑色的枪，在夺取凯因兹性命时就已经清除了持有者信息。所以说，现在在系统上是我
的所有物。

虽然直接向别人索要武器是很强硬的行为——不过这把枪在作为武器之前，确实更是重要的证
物。不是刑警也不是宪兵的我，一点都没有想要将其占为己有的念头。

所以我这次毫不掩饰地叹了口气，挥动单手打开道具储存格。

右手握起实体化的黑色短枪，想着至少也要耍下帅吧，于是便把它用力插到我和修密特之间
的石板上。

铿锵！！修密特被迸出耀眼的火花，屹立在地上的枪所散发的气势镇住了，往后退了半步。

再次审视这把枪，更觉得它是把设计得充满灾祸气息的武器。由于造型上就只是为了杀死玩
家，会有这种感觉也是理所当然的。我把视线从只有自己能看到的掉落计时器上移开，用低
沉的声音向长枪使告知：

“你连鉴定的工夫都能省了。这把枪的固有名是‘Guilty Thorn’ 。制造它的锻造师名叫
‘葛林姆洛克’。”

这次，对方有了明显的反应。

修密特细长的双眼猛地睁开，嘴巴半开发出粗哑的喘息。

果然没错，这位运动系老兄和锻造师葛林姆洛克，以及被害者凯因兹有所关联。而且，他们
在过去一定发生过什么事。

如果这就是凯因兹被杀的动机的话，那起圈内杀人事件，就不是让我害怕的不特定杀人者所
做出的无差别PK。虽然无论如何都很想知道过去发生了什么，但就算直接询问修密特也一定
不会得到回答的。

就在我思索着这些时，只见修密特僵硬地伸出戴着厚实长手套的胳膊，把枪从地上拔了出来。

修密特用粗暴的动作打开道具栏，像是想要尽快离手似的迅速把枪扔了进去，随后猛地转过
身去。

越过背后的长枪说出的最后一句话，也实在是很老套。

“……别没事到处乱调查。我们走！”

随后圣龙联合的男人们，就这样迅速地从转移门里消失了。

——哎呀哎呀。

★　　★　　★

我和亚丝娜，以及助手艾基尔一同经由阿尔格特的转移门，首先前往最下层的“初始之街”。

目的是要确认安放在黑铁宫里面的“生命之碑”。就算要去找锻造师葛林姆洛克氏，如果他
已经死亡的话就什么办法也没有了。

虽然已经是春天，广阔的初始之街还是被荒凉的氛围所笼罩着。

应该不止是天气参数的关系。被黄昏覆盖的宽广街道上几乎没有玩家的身影，不知道是不是
错觉，就连NPC乐团演奏出的BGM也尽是些郁闷的小调旋律。

最近，这里有着最大公会的下层自治组织“艾恩葛朗特解放军”，对玩家采取了宵禁的这类
传言，看来还真有可能是这样。在外面的玩家，都是身着制式统一的青铜局部护甲的“军
队”巡逻兵。

而且这些家伙在看到我们时，就像是辅导中学生的巡警一样马上冲了过来。不过，当看到站
在最前面的亚丝娜那绝对零度的视线时，就马上走开了。

“……这样子，也难怪阿尔格特会那么热闹呢……明明物价就很高……”

我不自觉地感叹道，艾基尔则是说出了更为可怕的谣传：

“最近，军队好像要开始向玩家们‘征税’了哦。”

“啥！？税金！？……骗人的吧，要怎么征收啊。”

“这点还无从得知……大概是从怪物的掉落中直接抽成吧。”

“你店里的营业额也会被征税的哦。”

一边持续着这类倒胃口的话题一边前进的我和艾基尔，在踏上黑铁宫的石板的一瞬间，都沉
默了下来。

正如名字所示，这是座仅仅由散发着黑色光泽的铁柱与铁板组成的巨大建筑物，气温明显要
比外面低了好几度。向前走去的亚丝娜好像也感觉很冷，搓起露在外面的双臂。

可能是因为时间比较晚了，里面没有其他人的身影。

在白天，那些不相信友人或恋人已经死亡而来这里确认，在看到名字上刻着无情的横线后泪
腺崩溃的玩家们的恸哭声不绝于耳。或许明天，被那把枪夺走性命的凯因兹的友人，同时也
是事件目击者的优尔可也会来此确认吧。这样说来，在不远的过去我也做过相同的事情。直
到现在，我也没能完全跨越这辛酸的回忆。

我们快步走在被蓝色火光照亮的无人大厅里。

来到宽数十米的生命之碑前时，在按照英文字母顺序排列的无数名字中，凝视着“G”附近。

艾基尔没有停下来，就这样向右边走去。我和亚丝娜则屏住呼吸在列举出来的玩家名字中开
始寻找，很快就发现了那个名字。

“Grimlock”。横线——并没有。

“……还活着呢。”

“是啊。”

同时呼了口气。凝视着稍远处“K”区的艾基尔很快也走了回来，用一副严肃的表情说：

“凯因兹的确已经死了。死亡时间是樱花之月【四月】二十二日，十八时二十七分。”

“……日期和时间都没错。就是今天傍晚，我们从餐馆中跑出来的时间。”

亚丝娜这样轻语后，低下头，闭上了长长睫毛下的眼睛。我和艾基尔也同时进行了简短的祷
告。被杀害的凯因兹——“Kains”的拼法已经向优尔可确认过了。

所有的事情办妥后，我们快步离开了黑铁宫，一起把压抑在心头的那口气给吐了出来。不知
何时，街区的BGM已经换成了深夜用的舒缓华尔兹。NPC商店都已经拉下铁门，照亮街道的只
剩下了矗立着的路灯。就连“军队”的巡察都看不到了。

我们无言地回到转移门广场后，走在前方的亚丝娜转过头说：

“……寻找葛林姆洛克氏的事情，就从明天开始吧。”

“也对……”

我点了点头，艾基尔魁伟的眉头皱成了八字。

“那个啊……我啊，大体上本业并不是战士而是商人呀……”

“知道啦。今天就解雇掉你这个助手吧。”

拍了拍艾基尔的背，只见他露出了安心的表情，并说了句“抱歉”。

这个老好人巨汉，也不是发自内心地认为“赚钱优先”啊“调查麻烦”啊之类。大概是讨厌
和制作那把灾祸短枪的玩家直接面对吧。并不是害怕，而是刚好相反——害怕自己那理应对怪
物发出的怒火会忍不住对着那名锻造师爆发出来吧。

加油啊，你们两位，留下这话的艾基尔便从转移门消失了，亚丝娜则是要回一次公会总部，
所以我们就在这里暂时告别了。

“明天早上九点在五十七层的转移门前集合。不要睡懒觉，准时到哟。”

你是老师还是我姐啊——虽然现实世界的我没有姐姐——听到亚丝娜的话，我苦笑着点了点头。

“知道了。你才是，今晚要好好睡觉啊。要不，继续在你身边看着——”

“才不要呢！”

丢下这话，KoB的副团长飞快地转过身，划出白与红的残像奔入了转移门中。

只剩下一个人的我，站在摇曳着蓝色光芒的转移门前，稍微回想了下今天一天发生的事。最
初只是“天气很好的日子”，和那个“闪光”亚丝娜一起午睡，然后本应两人共进晚餐，却
突然被卷入了圈内杀人事件当中，现在则是成了向事件的谜题发出挑战的侦探，或者说是助
手。

浮游城艾恩葛朗特的每一天虽然都是纯粹的“非日常”，不过自从二〇二二年十一月六日这
个死亡游戏开始以来，已经经过了一年半的现在，包含我在内的大部分——至少也是生活在中
层以上的玩家，在意识上都已经忘记了在现实世界里生活过的这件事，而是活在了剑与战斗，
金钱与迷宫交织而成“日常”中。

不过今天的事件，再次将我拉回了某种非日常中。这件事，难道会成为某个永久性变化的开
端吗……

思索着这些，我也向前走了几步，迈进了蓝色的转移门内。用声控命令指定我现在的定居点，
也就是四十八层主街区“琳达司”，随着周围的光线逐渐变强，我的身体也被一股浮游感包
围。

鞋底再次接触到地面，我踏上色泽发生了变化的石板路面，周围的景象也随之一变。我来到
琳达司的街区主城也只有一周时间，不过这里纵横交错的水路和到处都装设着水车的构造让
我非常喜欢。虽然这么说，晚上十点才回来，这个时间的街区已经被夜幕笼罩，白天时街道
上到处都能听见的锻冶屋的槌声也听不到了。

是谨遵副团长话直接回旅馆睡觉呢，还是溜进尚未关门的NPC酒馆喝一杯呢，想着这些便离
开了转移门广场的我……

突然间被六七名玩家们一起围住了。

一瞬间，我差点把背后的剑拔了出来。就算被几十人围住，只要在“圈内”就没有任何危险，
但这种常识就在这几小时内有些动摇了。

不过，我的右手指仅仅是动了动，算是控制住了拔剑的冲动。

这个集团的脸，我很肯定自己见过。他们是就算在攻略组公会中也是数一数二的最大型公会
“圣龙联合”所属的玩家。我面对半圆形队列中具有领袖气质的一名玩家，开口说道：

“晚安，修密特先生。”

被我抢得先机笑着打了招呼的高个子长枪使，顿时说不出话来，他皱了皱眉头后，用很快的
语速说道：

“……我在这里等你是有事情想打听，桐人先生。”

“欸。我的生日和血型……应该不是这个吧。”

听到我下意识做出的马虎回答，运动部主将般的短发下，粗大的眉毛微微颤动了下。

虽然同样也是攻略组，并不是什么敌对关系，但我跟“圣龙联合”却不怎么合得来。相比之
下，我还是和亚丝娜率领的“血盟骑士团”相处得要好些。

因为相对于血盟骑士团的目的“最快攻略游戏”，圣龙联合则是更倾向于“最强公会的荣
誉”。他们基本上不与公会外的玩家组队，狩猎场的情报也不怎么积极公开。更有甚者，他
们还对于给予BOSS怪物最后一击——会有道具掉落的判定加成——这点异常地执着。

不过仔细想想，他们也许是最享受SAO这游戏的人，因此我也不好再说些什么，但我却两次
拒绝过他们的入会邀请。因此，我们之间的关系并不是十分友善。

而现在，背靠转移门广场墙壁的我被七人组成的半圆包围，他们之间的间隔也保持着微妙的
距离。虽然还不到围住玩家让他无法动弹的“BOX”骚扰行为，不过只要我想走出这个包围
圈，就不可避免地会碰触到他人的身体，这也是一种很不礼貌的行为，在我犹豫时就变成了
这种“莫名其妙的BOX”状态。

抑制住自己的叹息，我改变语气对修密特问道：

“可以回答的话我就会说。你想问什么？”

“傍晚，发生在五十七层的圈内PK骚动事件。”

那立刻回答的内容，也在预料之中。我轻轻地点了点头，靠在石壁上抄起双手，用视线催促
他继续说。

“并不是决斗……这个传言是真的吗？”

听到这低沉的问话，我稍微想了一会儿，耸了耸肩说：

“至少可以确定，并没有任何人看见胜利者表示视窗。但也不能否定由于某种原因，在那里
的所有人都看漏了的可能性。”

“…………”

修密特那棱角分明的下巴紧紧地咬住，脖子附近的装甲发出了碰撞的声响。

身为圣龙公会的一员，玩家的护甲都是以银为主色，再用青色加以点缀的涂装风格。背在身
后的主装备长枪，长度有近两米，锋利的尖端还很周到地挂上了三角形的公会会旗。

短暂的沉默后，修密特用更加低沉的声音说：

“被杀掉的玩家的名字……听说是‘凯因兹’，没错吧？”

“目击了整个事件的被害者的朋友是这么说的。刚才去黑铁宫确认过了，时间和死因都是一
致的。”

咕噜，看到那粗犷的喉咙动了动，这时就连我都察觉到有些不太对劲了。于是歪了歪头，回
问道：

“是你认识的人吗？”

“……与你无关。”

“喂喂，没有我被单方面质问的道理吧……”

此话一出，立刻遭来了一阵怒吼。

“你也不是警察吧！虽然你好像跟KoB的副团长一起行动，那也没有独占情报的权利！”

声音大得就连广场外都听得到，周围的成员们也疑惑地互相看了看。看样子，是修密特并没
把事情讲清楚，就把这些人给找来了吧。

也就是说，可能与这次事件有关联的应该不是公会圣龙联合，而是修密特个人才对。原来如
此，在脑中记下这件事，眼前突然伸来了一只戴着长手套的右手。

“我知道你从现场，回收了那把PK中使用的武器。应该已经充分调查过了，给我吧。”

“……喂喂。”

这是明显违反规矩的行为啊。

在SAO中，只要是没有装备的武器掉在地上，又或者是谁刺到怪物身上后走远了，三百秒后
持有者信息就会被清除。那件道具在系统上和一般认知中就变成了接下来捡到它的人的东西。
那把黑色的枪，在夺取凯因兹性命时就已经清除了持有者信息。所以说，现在在系统上是我
的所有物。

虽然直接向别人索要武器是很强硬的行为——不过这把枪在作为武器之前，确实更是重要的证
物。不是刑警也不是宪兵的我，一点都没有想要将其占为己有的念头。

所以我这次毫不掩饰地叹了口气，挥动单手打开道具储存格。

右手握起实体化的黑色短枪，想着至少也要耍下帅吧，于是便把它用力插到我和修密特之间
的石板上。

铿锵！！修密特被迸出耀眼的火花，屹立在地上的枪所散发的气势镇住了，往后退了半步。

再次审视这把枪，更觉得它是把设计得充满灾祸气息的武器。由于造型上就只是为了杀死玩
家，会有这种感觉也是理所当然的。我把视线从只有自己能看到的掉落计时器上移开，用低
沉的声音向长枪使告知：

“你连鉴定的工夫都能省了。这把枪的固有名是‘Guilty Thorn’ 。制造它的锻造师名叫
‘葛林姆洛克’。”

这次，对方有了明显的反应。

修密特细长的双眼猛地睁开，嘴巴半开发出粗哑的喘息。

果然没错，这位运动系老兄和锻造师葛林姆洛克，以及被害者凯因兹有所关联。而且，他们
在过去一定发生过什么事。

如果这就是凯因兹被杀的动机的话，那起圈内杀人事件，就不是让我害怕的不特定杀人者所
做出的无差别PK。虽然无论如何都很想知道过去发生了什么，但就算直接询问修密特也一定
不会得到回答的。

就在我思索着这些时，只见修密特僵硬地伸出戴着厚实长手套的胳膊，把枪从地上拔了出来。

修密特用粗暴的动作打开道具栏，像是想要尽快离手似的迅速把枪扔了进去，随后猛地转过
身去。

越过背后的长枪说出的最后一句话，也实在是很老套。

“……别没事到处乱调查。我们走！”

随后圣龙联合的男人们，就这样迅速地从转移门里消失了。

——哎呀哎呀。
*** 第4节
“DDA？”

听到我的报告，亚丝娜略微的皱了一下眉头。

DDA，是Divine Dragons Alliance的缩写，也就是公会“圣龙连合”的简称。连哭泣的小孩
听到此名都会安静下来，不论是谁都得靠边站，DDA就是充满此种压迫感的名字。不过此神
通力对KoB副团长的亚丝娜来说，可是行不通的。

第二天，樱花之月二十三日，天气参数的心情看来很差，从早上就一直下着毛毛细雨。虽然
对没有被天空覆盖的艾恩葛朗特来说，下雨是件很奇怪的事情，但这样说来晴天大太阳也是
不可能的。

早上七点左右，在事件现场附近，第五十七层转移门碰面的我跟亚丝娜，首先来到了附近的
露天咖啡厅边吃早餐边整理情报。最大的讨论点，就是那位昨天夜里潜伏并包围我，还硬把
情报跟凶器拿走的圣龙公会成员-修密特先生。

“啊——说起来的确有这个人呢，巨大的长枪使对吧”

“对对，就像高校里的马上枪部主将那种感觉”

“才没那种社团呢。”

一大早就冷静地把我说出的笑话给踢开，亚丝娜沉思似的双手捧起咖啡杯。

“……实际那家伙就是犯人，这应该也是不可能的吧？”

“虽然断然下决定是很危险，不过应该不是这样吧。如果怕留下证据而回收凶器的话，那一
开始就没必要将其留在现场了，那把枪我倒认为是犯人留下来的讯息。”

“这样啊……倒也是。用那种杀害手法，武器的名字是‘罪之棘’……，比起单纯的PK，更
像是‘公开处刑’哦。”

亚丝娜用阴郁的表情说着，我不禁同意。

不是无差别的PK，而是瞄准凯恩兹这个玩家的处刑。而且，过去凯恩兹，葛林姆洛克，修密
特之间发生过什么事。

我将声音放小，将推导而得的推论道出。

“也就是说——动机是‘复仇’吧。那个凯因兹在过去犯了某种‘罪’，作为‘惩罚’而把他
杀掉，犯人就是想把我们引导这条线上来啊。”

“这么一想，与其说修密特是犯人，到不如更像被盯上的目标。 以前他和凯因兹一起做了
‘什么’，结果现在有一方已经被杀，就开始焦躁起来了……”

“如果知道作了‘什么’的话，也许就马上可以知道复仇者是谁了啊。……只不过这也可能
是犯人的表演，尽量别抱着先入为主的观念比较好。”

“是啊。特别是听优尔可述说的时候。”

亚丝娜同时点点头，我再次确认了下时间。等到早上十点，再去向跟住在这附近旅馆的优尔
可，详细询问一下事情的经过。

慢慢把黑面包夹起司配上蔬菜汤的早餐吃完，时间还满充裕的，我便无意识地看着坐在对面
的亚丝娜。

今天是因为私事的关系吗，不是穿着那套白色为底，红色打边的骑士服。而是粉红与灰色的
细条纹上衫，外罩一件黑色皮质的背心，蕾丝装饰的黑色迷你裙，腿上则是带有光泽的灰色
花纹裤袜。

顺带一提，鞋子是粉红的其皮靴，如果再戴个同色的贝雷帽，还满像一回事的——虽然我这么
认为，不过也许这是女性玩家普遍的穿着也不一定，很可惜的我并没拥有能判断这点的流行
物品知识。不论如何，再怎么看，从头到脚的这套服装值多少钱，实在是无法估断。

而且是来作杀人事件的调查，也没穿成这样的理由，正当我在胡思乱想的时，亚丝娜突然朝
上瞥了一眼，接着又扭开头到一旁。

“……你在看什么啊。”

“诶……啊，这个啊……”

再怎么说都不可能问这套服装到底要多少钱，但如果直接说“好可爱的服装呢，很适合你”
这样的话来，对方不是发怒就是爆笑，只好瞒混过去再说了。

“诶……这个黏稠稠的玩意，好喝吗？”

亚丝娜眨眨眼，看了一下盛在匙上的谜样汤品，再瞄了我一眼，摆出微妙的表情后，长叹一
口气。

“……不好喝。”

随意的回答后，便把盘子推到一旁。轻咳一声，细剑使口气一转。

“我昨晚仔细想了一下，那把枪产生的‘贯通持续伤害’……”

话说回来，这还是第一次看到她没带剑，到现在才发现的我点了点头。

“嗯？”

“例如，会不会是在圈外被贯通属性的武器刺中？然后再移动到圈内，持续性伤害会怎么样，
你知道吗？”

“诶——……这个……”

不由得偏起头来。的确，这种状况到现在为止还没遇过，连想都没想过。

“不知道……但是毒这类的在进入圈内的瞬间就会消失了吧？持续性伤害不也是这样吗？”

“但是，刺着的武器会如何？自动拔掉吗？”

“越来越让人感觉不舒服呢。……好，反正还有点时间，来实验看看吧。”

对于我说出的话，亚丝娜睁圆了眼睛。

“实……实验！？”

“百闻不如一见。”

说出奇怪成语的我站了起来，调出街区地图叫，确认前往最近大门的道路。


★　　★　　★

五十七层主街区马汀外，是片被木节老树所点缀而成的草原。

就在几周前，这里是最前线的时候，我经常路过，不过现都已没什么记忆了。

可能跟春天的到来，周遭都发出新绿的嫩芽让景观改变也有关系，不过最主要的应该是，对
于已攻破楼层的圈外区域，攻略组几乎不会再来了。

沐浴着静静飘落的细雨，从市街门走出，视野马上显示“Outer Field”的警告标示。虽说
并不会马上出现怪物袭击，但内心的一部分仍旧自动紧张起来。

腰间装备着一贯的细剑，亚丝娜不耐烦的把前发上的水滴拨开，发出惊讶的声音。

“我说……实验，要怎么做？”

“就这样做。”

我摸了摸腰带，拿出一直都装备在身上的三支掷爪【ThrowingPick】之一。艾恩葛朗特存在
的各种武器，总共被分成四类属性——斩击，突刺，打击，贯通。我的主武器单手直剑是属於
斩击类，亚丝娜的细剑则是突刺类，锤矛跟锤子是打击，而杀害凯因兹的枪与修密特所拿的
长枪为贯通武器。

在这里比较微妙的是几个投掷系武器的定位。就算同样都是投掷用的东西，回力镖和圆形刀
刃的战轮类是斩击，丢掷用匕首是突刺，以及我用的丢掷爪是属於贯通属性。是的，就算是
长十二厘米的大型铁针，可也算是贯通型武器，也会产生些微的持续性伤害。

就算是拿自己的HP来作实验，搞到装备耐久度都减少就太笨了，于是把左手的手套摘下，高
举右手将丢掷爪朝着张开的手背挥下。

“等……等等啊！”

尖锐的声音，让我的手停下了。

往旁一看，亚丝娜正打开道具视窗，取出治癒水晶，我不禁苦笑道。

“太夸张啦，这种东西只是刺到手，HP只会掉个百分之一二而已。”

“笨蛋！圈外什么事都有可能发生！赶快组队让我看看你的HP槽！！”

边用姐姐骂愚笨的弟弟口气，边迅速操作视窗向我发出组队的邀请。

我缩了下脖子，马上按下接受，视野左上方HP槽下，出现了排较小的亚丝娜的HP槽。

仔细想想，跟她组队应该是第一次吧。从首领怪的攻略所产生出的意见对立，甚至发展到决
斗，都还不算太久以前的事情。

我不自觉的看向右手拿着粉红色的水晶，挂着一副紧张的神情，于一旁观看的亚丝娜。

“…………干嘛？”

“没什么……怎么说呢，没想到你会那么担心啊。”

刚说出这句话，亚丝娜白皙的脸颊就染上了跟水晶同样的颜色，睁大双眼再度向我大喊：

“才……才不是的！啊……也不是说不对……我说，赶快动手啦！！”

我全身颤抖了一下，再次将丢掷爪拿好。

“那，那我上了！”

宣言完，深吸一口气——

我便朝伸直的左手，摆出投剑Skill初级技——“SingleShoot”的准备动作。

被夹在右手两指间的丢掷爪，发出微弱的光影效果后，飞了出去随后扎穿了我的手背。

冲击过后，不爽的麻痹感和钝痛在我的神经里游走。

HP条，比预想的掉的还多一点，大概掉了百分之三左右。话说回来，现在才想起没多久以前
才刚把丢掷爪换成了高级怪的掉落品。

忍耐着不快感，边望着刺穿手的铁针，五秒后再度发出了红光，同时HP条又多扣了百分之零
点五。这也就是夺走凯因兹性命的“贯通持续伤害”。

“……赶快进入圈内！”

被紧张的亚丝娜声音催促，我点头做出回应后，两人同时注视着HP条以及丢掷爪，走进了不
远处的市街大门。

当靴子底从湿润的草皮切换成坚硬的石砖时，视野中浮现出“Inner Area”的字样。

接着——HP条的减少停止了。

虽然每五秒仍会有红色效果光闪动，不过HP一点都没有减少。果然在圈内，所有的伤害都会
被无效化。

“停止……了呢。”

听到亚丝娜低语，我也点点头表示同意。

“继续被武器刺着，但持续性伤害停止啊。”

“感觉如何？”

“依然有感觉，这大概……是怕有笨蛋把武器插在体内，在圈内到处乱跑，才做出的设计
吧……”

“这完全就是在说现在的你嘛。”

被冷冷的声音这么一说，我缩了缩脖子，把丢掷爪抓住，一口气把它拔出来。这时神经产生
一阵强烈的不快感，眉头不禁皱了起来。虽然左手背没有留下任何的伤痕，但冰冷的金属触
感仍旧没有消失，我向伤口吹着气一边说道：

“伤害确实停止了……那凯因兹是怎么死的……？那武器有什么特性吗……或者说有某种未
知的技能……呜啊！？”

最后我发出大叫的理由是——

亚丝娜突然用双手把我的左手拉到胸前，紧紧地握住。

“你做……做……做……”

数秒后副团长把手松开，用余光望着我，说：

“这样伤害的残留感应该消失了吧。”

“——嗯，嗯，是啊，谢谢。”

心脏突然开始澎通澎通的跳动，只是因为被吓到而已。

只是这样，绝对是这样。


★　　★　　★

刚好十点从宿屋出来的优尔可，似乎是没睡好一样，眨了好几次眼后才向我跟亚丝娜行了个
礼。

我们同样也回了个礼，首先跟她道歉。

“抱歉，朋友才刚去世而已……”

“不会……”

摇曳着深蓝色的头发，优尔可摇了摇头

“没关系的，我也希望早日找到犯人……”

边说出这句话，边把视线转往亚丝娜时，突然睁大了双眼。

“呜哇，好厉害呀 这套服装，全部都是阿修蕾小姐的订作品吧，集齐全身的人，我第一次
看到。”

……又出现新的名字啊，这样想的我问了下优尔可。

“那是……谁？”

“你不知道吗！？”

用像是看到废柴一样的眼神望着我，优尔可才解说道。

“阿修蕾小姐呢，她是艾恩葛朗特第一个把裁缝技升级到一〇〇〇的大裁缝哦！如果不给她
最高级的稀有布料，是不太会帮人作的哟！”

“诶！”

我坦率地发出感慨。就算像傻瓜一样整天战斗的我，把单手直剑的技能升到一〇〇〇也是不
久前的事情而已。

不觉就开始把亚丝娜从头到脚都再快速的看过一遍，细剑使这时的脸庞抽动起来，说了一句
话后开始向前走去。

“才……才不是这样呢！”

——究竟是东西不是这样啊，我完全搞不懂。


★　　★　　★

亚丝娜把对此很有心得的优尔，以及一直低着头的我，一同带到了昨夜晚餐没吃成的餐厅内。

可能是因为时间的缘故，店内并没有其他的玩家。坐到最里的桌旁后，稍微确认了下此处离
门有多少距离。如果是隔着这么远，只要不大声叫喊，对话就不会被旁人听到。虽然以前我
认为要进行秘密的谈话，必须选择旅馆的单间，再上锁才是最好的方法，但是最近才知道即
便这样也可能会被窃听技很高的家伙给偷听到。

由于优尔可也已吃了早餐，我们三人就点了杯茶，并直接奔入主题。

“首先，是报告……昨晚，我们去黑铁宫确认过生命之碑了。凯因兹先生，在那个时间确实
已经身亡。”

听到我的报告，优尔可短促的吸了口气，闭上眼点了点头。

“是……这样吗 非常谢谢你们，特地跑到那么远的地方去。”

“没关系的，想要确认的名字，另外还有一个。”

摇了摇头後，亚丝娜用有点小声的声音，说出第一个最重要的问题。

“那个，优尔可小姐，你有听过这个名字吗？大概是锻造师，叫作‘葛林姆洛克’，另外还
有个长枪使……‘修密特’？”

优尔可垂着的头，突然震了一下。

一会儿后，慢慢的，不过用很肯定地语气回答道：

“……是的，我知道。这两人，以前都是我跟凯因兹所属的公会成员。”

听到这微弱的话音，我跟亚丝娜相互望了望。

果然是这样啊。那么，另一个推测——以前那个公会，发生了“什么”足以导致此次事件的原
因，这点非得要确认清楚不可。

这一次，换我提出了第二个问题。

“优尔可小姐，我想这可能是很难回答的问题……不过为了解决事件，想请你告诉我们真正
的事情。我们认为，本次事件的起因应该是‘复仇’，凯因兹先生由于在那公会里发生了什
么事，而遭到犯人的记恨从而复仇……你想到什么吗？”

这次，优尔可并没有很快做出回答。

优尔可低着头，在漫长的沉默后，颤抖地拿起茶杯，润了润嘴唇，终於点头说道：

“……是的……有这样一件事。昨天，我没说出口，真是抱歉……那是我很想忘记……根本
不想回想起来的事情，我认为没有什么联系，所以没有说出来。——但，这次我会全部说出的。
‘那件事’……就因为那件事，让我们的公会瓦解了。”


★　　★　　★

——公会的名字为“黄金苹果”，也不是特别以攻略为目的，总共只有八人的弱小公会，只是
为了要支付住宿费以及食品的费用，在安全范围内打猎而已。

不过就在半年前……也就是去年的初秋。

潜入在中间层的普通附属迷宫时，我们遭遇到一支从未见过的怪物。

是全身漆黑的蜥蜴型，有着非常快的速度……一眼就可以看出是稀有怪，我们很兴奋的紧追
着它……结果不知道被谁丢的匕首，偶然，可说是超幸运的命中了，并把它打倒了。

掉落的物品，只有一个看起来很普通的戒指。不过鉴定后，大家都吓了一跳。可以提升20点
的敏捷值。这种魔法饰品，大概连现在的最前线都不会掉落。

接下来的事……你们就都能想得到。

拿来给公会用，还是卖掉后把钱分给大家，产生了两种不同的意见，在经过可以说是吵架的
争论后，决定使用少数服从多数的原则。结果，以五比三的结果，将其卖掉了。这种程度的
稀有道具，已经不是中层商人可以负担的，所以会长便把它拿到最前线的拍卖商去委托拍卖。

要找一家有信誉，懂行情拍卖商也是很耗费时间的，因此会长在前线待了一夜。我们则是，
兴奋的等着拍卖结束归来的会长。就算是八人分，也一定是很大笔的金额，那时候心中想的
都是要买哪间店的武器啦，买个人品牌的洋装啦，边看目录边幻想……那时候完全没想
到……会发生那种事……

……会长，从此再也没有回来。

第二天晚上，已经超出约定时间一小时了，却连一则信息都没有传回来。也没有了位置追踪
的反应，我们发过去的信息也没有回应。

会长是不可能拿着道具逃走的，大家产生了一种不祥的预感，于是其中几人去黑铁宫的“生
命之碑”进行了确认。

随后…………


★　　★　　★

优尔可紧咬着嘴唇，不断地左右摇头。

我和亚丝娜，短时间内也找不出该说什么。

幸好——该这么说吗，过了一会儿后，优尔可擦了擦眼角，脸抬起来用颤动但却很清晰的口吻
说。

“死亡时间，是会长拿戒指，前往上层的那天深夜，约一点多的时候。死亡原因是……贯通
属性伤害。”

“……拿着那种稀有道具也不可能会跑出圈外。这么说的话……是‘睡眠PK’吗？”

听到我的话，亚丝娜也略微点了点头

“半年前，也是这个手法没散布开来的时候。 那时还有不少人为了省住宿费而在公众空间
睡觉。”

“靠近前线的旅馆也很贵……但……很难想像这只是偶然 。对会长下手的，是知道戒指事
情的玩家……也就是说……”

闭起眼的优尔可，轻轻点了点头。

“公会‘黄金苹果’留下的七人……中的某位。我们当然也这样想过，只是……在那个时刻，
我们没办法调查谁在什么地方作哪些事……于是陷入了互相怀疑的境地，没用太长的时间公
会就瓦解了。”

再次，苦涩又沉重的沉默降临到了桌旁。

——真是个十分讨厌的往事呢。

——同时，也是可能的。极有可能。

为了那只有万分之一的机率才能掉落的物品，让从未有过不和气氛的友好公会崩坏的例子，
也不算太少。虽然没怎么听过，大概是因为对于当事者而言是那些都是想要消去的记忆吧。

不过，我却有个不得不向优尔可提出的问题。

看着这一副沉郁神情，低下头的年长女性，我用十分诚恳的口气问道：

“我想请你告诉我一件事。反对卖掉戒指的三人的名字是……？”

又沉默了数秒，随后优尔可下定决意似的抬起头来，很明确地回答道：

“凯因兹，修密特……还有，我。”

——这真是稍有些意外的回答啊。看着说不出话只是眨着眼睛的我，优尔可用有些自嘲的语气
继续说道。

“只是反对的理由，我跟他们有点不太一样。凯因兹跟修密特是想拿来给身为前卫战士的自
己使用。而我……当时正开始和凯因兹交往，比起公会全体的利益，我选择了遵照男友的意
思。我真是笨呢。”

优尔可紧闭上嘴，把视线投向桌子，到目前为止沉默了很长一段时间的亚丝娜，温柔地向她
问道：

“那个，优尔可小姐，难道……你跟凯因兹先生后来也一直交往吗……？”

随后，依旧低着头的优尔可，缓慢的摇了摇头。

“……公会解散的同时，就自然分手了，只是偶尔见个面，稍微聊聊近况而已……因为只要
两人呆在一起稍长一些，就肯定会想起那戒指的事。昨天也是那样，原本只打算吃个饭……
但在这之前，就发生那种事……”

“这样呀……——不过，那件事也是个令人很震惊。对不起，让你想起这么多痛苦的回忆。”

优尔可再次摇了摇头。

“不，没关系的，还有……葛林姆洛克这人……”

突然说出这个名字，我不禁坐直起来。

“……他是‘黄金苹果’的副会长，同时也是会长的‘丈夫’。”

“咦……会长是女性吗？”

不觉地反问道，优尔可则是轻轻的点了点头。

“嗯。非常强……但也只是在中等级别中……是名强大的单手剑剑士，又是漂亮，以前的我
非常憧憬她。所以……到现在都还不敢相信。那样的会长，居然会被‘睡眠PK’这种卑劣的
手段杀掉……”

“……葛林姆洛克先生应该也很震惊吧。对方可是自己是喜欢到结婚的对象啊……”

亚丝娜的低语，让优尔可的身体颤抖了一下。

“对，在那之前，是名总是挂着微笑的温柔锻治师……但事发后，就变的十分颓废……公会
解散后也没和其他人联络，现在人在哪也不知道。”

“这样……一直问这些不舒服的问题，实在很抱歉，最后请再告诉我们一件事。昨天……杀
害凯因兹的是葛林姆洛克，你觉得有可能？实际上，那把刺进凯因兹胸口的黑枪……经鉴定
后，制作者就是葛林姆洛克本人。”

这个问题，同样也等於是询问半年前的“戒指事件”的真犯人是否可就是凯因兹一样。

优尔可在长思后，微微的点了点头。

“……我想，应该有可能，不过我和凯因兹都没杀害会长，夺取戒指。虽然没有确切的证明
自己清白证据……如果昨天的事件犯人是葛林姆洛克先生的话……那个人也许会打算把反对
卖掉戒指的三人都杀掉……”


★　　★　　★

我和亚丝娜把优尔可送到旅馆，交给她数天份的食物，并交待她绝对不要从房间里出来。

出于照看，原本是想要让她住进更宽广的套房中，并提前支付一个礼拜的租金，不过在连打
发时间都没有的网路游戏艾恩葛朗特中，把一个人关在房间里也要有个限度。所以我们跟优
尔可约定好会尽早把事件解决后，便离开旅馆。

“……说真的，如果能住进KoB的本部，就更令人安心了呢……”

对于亚丝娜的这番话，让我想起刚在五十五层“铁之都”古兰萨姆【グランザム】设立的
KoB本部的威严外观，并点头标示同意。

“也是呢……不过当事人无论如何都不想去，也没办法强制带她过去。”

如果要让优尔可接受KoB本部的保护，那就不得不向公会解释理由。也就是说，要公开半年
前“黄金苹果”解散的始末。优尔可大概是为了凯因兹的名誉才拒绝的吧。

回到转移门广场，刚好街上响起十一点报时的钟声。

雨终于停了下来，路上反倒是充满了浓厚的雾气。透过那迷漫的雾纱，看着身着黑与粉红这
身统一装扮的亚丝娜，开口说道。

“那么，接下来……”

“…………？”

对于我这没头没脑的发言，亚丝娜歪着头看了过来。

虽然有些晚了——大概是这样吧，果然我还是得要说一下啊，做出此判断的我，故意咳了一声。

“啊，不是，诶。那个……很、很适合哦，那个。”

哦哦说出来了，这样我也算是个一流的绅士了。

就在我这样想时，听到这番赞扬话，并挂起一副可怕面容的亚丝娜，用右手的食指，戳了戳
我的胸口，抱怨道：

“呜——！这种话啊，在最初见到时就要说啊！！”

我去换衣服！同时以超高速转过头去，她的侧脸就连耳朵都涨红了，果然是发怒了啊。

不明白，完全不懂，女性的心理。

★　　★　　★

利用附近的无人屋换回平常那套骑士服的亚丝娜，边梳理着披在背上的长发，边走了回来。

“接下来要做什么？”

“啊，嗯，这个。选项有……其之一，在中层区找线索，询问有没有人知道葛林姆洛克的名
字以及他的住所。之二，拜访黄金苹果其他成员，确认优尔可所说的话。三……就是重新商
讨杀害凯因兹的手法。”

“恩恩。”

把手盘在胸口前，亚丝娜一副沉思的表情。

“第一个选项，只有两个人的话效率太差了，加入照现在的推测，葛林姆洛克是犯人的话，
他应该会更积极的躲藏起来。第二个……结果来看，每个成员都是当事人，根本无法打探到
内幕……”

“诶？怎么说？”

“也就是，假设我们听到跟优尔可的话矛盾的情报呢？我们并没有办法知道哪边才是真的，
只会让我们更加混乱而已，真希望能有更客观的判断材料啊……”

“那……就是第三个吗？”

眼神交汇后，我们同时点了点头。

我和亚丝娜会如此积极的参与的原因，对优尔可来说很抱歉，我们不是为了找出“黄金苹
果”会长被害事件的真相，而是为了要查出杀害凯因兹的“圈内PK”的手法。

关于昨天傍晚，发生在眼前那个事件，我们可以断定的只有一点——“圈外产生的贯通持续性
伤害，在圈内就会失效”。有必要在讨论是否有其他的可能性。

“不过……真希望能有学识渊博的人来协助啊……”

我轻声低语道，亚丝娜则是皱起了眉头。

“就算这么说，如果我们随便把情报泄漏出去，对优尔可也过意不去。必须要找绝对可以信
任，而且对於SAO系统的了解更在我们之上的人，实在很难……”

“…………啊。”

我的脑海中突然闪过一位玩家的名字，于是打了个响指。

“不是有吗。把那家伙叫出来吧。”

“谁啊？”

当我把名字说出来时，亚丝娜惊讶得瞪大了眼睛。
*** 第5节
我请你吃午餐，应该不会是被我写的补充文字给吸引了吧，亚丝娜在寄出信息的三十分钟后，
那个男人居然真的出现了，这让我多少有些惊讶。

当高大的身影无声的出现在阿尔盖特转移门时，广场周遭的玩家们开始鼓噪起来。身披暗红
色披风，背後垂着一束白金色长发，腰上以及背后没有挂任何武器——此男性完全给人一种
“魔导师”的氛围，虽然这个职业并没有存在于SAO中。他就是公会“血盟骑士团”团长同
时也是艾恩葛朗特最强的剑士，“神圣剑”希斯克里夫在看到我们后，眉头一挑，迅速地走
了过来。

亚丝娜用严肃地敬了个礼，动作还带出了响声，随后急忙解释道。

“团长非常对不起！这个笨……不不，这个人无论如何都不听，所以……”

“也没什么，刚好也是到要吃中餐的时候了，能被那个‘黑色剑士’邀请吃午餐，这个机会
可不是常有的呢。晚上得去装备部商量事宜，在那之前的时间都能陪你们。”

希斯克里夫抬起头用流利并带有钢般质感的男高音这么说道，我则是耸了耸肩。

“上次对你在BOSS攻略战中，独自抵挡了十分钟的这件事，我还没谢过你呢，刚好顺便也有
点有趣的事情想问问你。”

我把最强公会KoB的No.1跟No.2，带到了阿尔盖特我所知道的最为奇怪的谜之NPC饭馆中。虽
然绝对不是对味道中意，但是不知道为什么，店里酿造出来的气氛，却非常吸引我。

在如同迷宫一样狭窄的小路里，东转西绕的走了五分钟后，望着总算出现在眼前的昏暗小店
的亚丝娜说道：

“……回去的时候也要好好带路哦，我已经不知怎么回到传送门那了。”

“据谣言所说，这条街已经有好几十名玩家，由于没带转移结晶，一直被困在此地呢。”

我露出淡淡的微笑，吓唬人似地说道，希斯克里夫则像是什么都没发生似地注解道。

“只要向道路旁的NPC付十元，就能带你到广场了，如果连这点金额都没有的时候……”

两手往上一举，走到了店内。我则和挂着一幅五味杂陈表情的亚丝娜，紧跟在后也进入了小
店。

狭小的店内，跟期待的一样没有其他人。在可供四人使用的廉价桌旁坐下，向阴沉的店主点
了三份“阿尔盖特荞麦面”后，小口吸了些装在充满水雾杯中的冰水。坐在右侧，表情变得
更为微妙的亚丝娜，说：

“总觉得……像是在开抚慰大会一样啊……”

“错觉错觉。话说回来，为了忙碌的团长，还是快点进入正题吧。”

我瞥了一眼表情十分平淡的希兹克利夫，便开始述说起来。

昨晚事件的大概内容，亚丝娜用简洁的话语进行了说明，听完这些话后“神圣剑”的表情也
几乎没有变化。唯一只在听到凯因兹死亡的那段时，一侧的眉毛动了动。

“……事情就是这样，虽然很麻烦，但还是想借用一下团长的智慧……”

亚丝娜做出结论后，希兹克利夫又喝了一口冰水，嗯，的小声说道。

“那么，首先听听桐人君的推测吧，你觉得这次圈内杀人的手法是？”

话题转到我这儿，于是我把托在脸颊上的手拿开，竖起三根手指。

“嗯……大致上有三个，第一个是正当的圈内决斗，第二个，用已知的手段，结合出系统的
漏洞。至于第三个……就是有着让防犯罪系统无效化的未知技能，或是道具。”

“可以把第三个可能性先去掉了。”

对于马上做出回答的希兹克利夫，我不禁望向他的脸，并凝视起来。亚丝娜也是一样，在眨
了两三次眼睛后，说道。

“……很肯定呢，团长。”

“想像一下吧，如果你是这个游戏的开发者，你会设定这样的技能或是武器吗？”

“嗯……应该不会吧。”我这么说道。

“为什么呢？”

回望向那带有磁力般的琥珀双眼，我这么答道。

“那是因为……不公平，虽然承认这点有些不爽，不过SAO的规则基本上都很公平。除了一
个，你的‘Unique Skill’外。”

我带着挪揄般的微笑着道出了最后一句话，但希斯克里夫也无言地回应了一个相同的微笑。

这让我有点吃惊。就算是KoB的团长，也不应该知道最近追加进我技能栏的“那个”啊。

交替望着我和希兹克利夫那应酬般的微笑，亚丝娜叹了口气，并摇摇头，插话道。

“不管如何，现阶段去说第三种可能性什么的也只是浪费时间，是根本没办法确认的东西。
那么……就从第一个假说开始讨论吧。”

“好吧。 ……不过，这家店的料理，还真是慢呢。”

我望着皱起眉头，并看向柜台内的希兹克利夫耸了耸肩。

“在我所知道的范围内，那个老板可是艾恩葛朗特最没干劲的NPC呢。这点也很有趣哟。冰
水的话是可以无限续杯的。”

我拿起桌上那看起来很便宜的水壶，把团长大人面前的水杯再度注满

。

“——玩家在圈内死亡，都是因为决斗的关系，这点可说是常识了啊。只能这样断言，凯因兹
死的时候，到处都找不到表示胜利者的窗口啊。会有这种决斗吗？”

随后，坐在身旁的亚丝娜也歪起头来。

“……这么一说，至今为止都没注意过，不过WINNER表示窗口出现的位置是如何决定的呢？”

“咦？……嗯。”

的确，这点我也没考虑过，不过希斯克里夫毫不犹豫地立即答道。

“是决斗双方的中间位置，如果决斗时，双方的距离超过十米，那么就会在双方身旁各出现
一个窗口。”

“……你还真是清楚啊，这种条件，也就是说……会在离凯因兹最远不超过五米的地方咯。”

于脑海中回放起那件惨剧的情形后，我摇了摇头。

“在周围的开放空间内都没出现视窗，而且还有那么多目击者存在。剩下就是在凯因兹身后
的教会中，不过那时犯人也应该留在教会内啊，在凯因兹还没死前就冲进教会里的亚丝娜却
没见到那人，这就奇怪了。”

“再加上，教会中也没出现胜利者窗口。”

亚丝娜补充道。

嗯嗯，在我这么念叨后——

“……不是决斗……啊……果然。”

低语时，破旧的餐馆内，似乎笼罩了一片浓厚的黑影。

“……难道是选错了？这家店……”

小声说着的亚丝娜，像是切换思考似地把水杯中的水喝乾，再放回到桌上。我则再次用冰水
注满。用一副微妙的表情说出谢谢后，亚丝娜立起两根手指。

“那剩下的可能性就是第二种咯，‘系统上的漏洞’……有一点我很在意。”

“什么？”

“贯通持续性伤害。”

亚丝娜拔出一根在这世界根本不需要的牙签——因为这个世界牙齿不会弄脏——用这小小的武器
刺向空气。

“那把枪，我认为不只是为了公开处刑的演出。为了实现圈内PK，持续性伤害是一定必要
的……我是这么想的。”

“嗯。我也有同感。”

在点头之后，我又缓慢的摇起头来。

“但是，刚刚不是才实验过了，就算在圈外被贯通武器给刺到，只要移动到圈内，伤害就会
停止。”

“那是仅限用走的，对吧。如果……用‘回廊结晶’呢？准备一个把出口设定成教会那小房
间的水晶，从圈外传送……这种情况，伤害会停止吗？”

“会停止的。”

希斯克里夫再次迅速回答道。

“不管是徒步，用回廊结晶传送，或是谁把人丢进来，只要进入圈内……也就是步入街区的
那时起，毫无例外的‘程序’都会启动。”

“等等，那个‘街区’是只包含地面以及建筑物的内部吗？上空呢？”

我突然想到这奇妙的假设，开口询问道。

那个绳子。帮着被枪贯穿的凯因兹的脖子，在不接触到地面的情况下就那样垂挂在教会的窗
下……？

这种情况，就连希斯克里夫也露出迷惑的神情。

短短的两秒后，绑起的长发缓慢摇动起来。

“不——更严密的说，‘圈内’是从街区的边界线开始垂直延伸，直到天盖，也就是个直达下
层底部的圆柱状空间，只要移动到这个三次元坐标内时，‘程序’就会保护那个人。所以就
算把回廊结晶的出口设定成街区的上空数百公尺，从圈外转移进来，并从上空落下，也不会
产生坠落伤害。但精神上仍旧会感受到巨大的冲击。”

“诶——”

我和亚丝娜异口同声的发出惊叹。

不仅对“圈内”区域的形状，就连这些事希斯克里夫都知道。公会团长是达到这个地步就没
办法当吗，刚想到这些，脑中就出现某位不修边幅的刀客，于是这个想法立刻就被否定了。

只不过——

如果这样的话，就算是“贯通持续性伤害”，凯因兹只要待在圈内，伤害就一定会停止。也
就是说要削减他的HP，一定有短枪“罪之棘”之外的其他来源。难道有什么遗漏的地方吗。

想了想，我把推测慢慢地说了出来。

“……生命之碑上，在凯因兹的死亡时间旁，确实也记录了死亡原因。就是‘贯通属性攻
击’，还有凯因兹消灭时，留在现场的也只有那把黑枪。”

“也是呢，很难想象会偷偷使用其他的武器。”

“听好了哟……”

我的脑海闪现出了吃了一记强力怪兽的爆击时的胃内翻江倒海的感觉，继续说道。

“吃下威力很强大的一击，HP条会如何？”

都到现在了你还在说些什么啊，亚丝娜用这样的眼神看了我一眼，答道。

“当然是会大大的减少。”

“减少的方式哦，不是瞬间就消失，而是从右侧开始削减下去，也就是被击中，直到HP减少，
这其中有着细微的延迟。”

说到这里，亚丝娜终于发现我到底想说什么了。希斯克里夫还是完美保持着无丝毫变化的表
情，完全猜不透其内心的想法。

交替看了看两人，我边用手势比划边说道。

“例如，在圈外把凯因兹的HP，用枪一击从满血打到零，那家伙从装备看应该是肉盾战士，
HP总量应该满多的，要扣到最左端，应该满花时间的……有个五秒也不奇怪。在这时间内，
把凯因兹传送到教会，再把他挂在窗户下的话……”

“等……等一下。”

亚丝娜用尖锐的声音打断了我的话。

“就算不是攻略组，凯因兹也是平均层里面偏上级的玩家，要把他的HP，用单发Sword
Skill打掉这种事，先不说我……连你也不可能做到才是！”

“照你这么说也对！”

“就算用‘Vorpal Strike’打出爆击，应该也扣不到一半吧。不过，SAO有好几千玩家。不
属於攻略组的人……我跟亚丝娜也几乎都不认识，那里有等级很高的玩家，也不能否定。”

“也就是说……用那把枪杀掉凯因兹先生的是葛林姆洛克本人，还是接受了委托的红名玩家，
这些都还不清楚。不过可以确定的是，那个犯人，是能够将完全武装的肉盾战士给一击杀掉
的玩家，你说的是这个意思吧……？”

我耸了耸肩标示肯定，就像等着老师“评分”似的看了看坐在对面的男子。

半闭着眼的希斯克里夫望了望桌子，一段时间后，缓慢地点了点头。

“以手法来看，也不是不可能。的确，在圈外把对手的HP一击打掉，在HP条归零前的那短时
间内马上传送的话，看起来就像是‘圈内PK’。”

哦，难不成这是正解？刚这么想没多久，就传来一声“不过”。

“……当然你应该也知道，贯通武器的特性，一是长度，二是装甲贯通力单纯以威力来说，
是输给打击跟斩击武器的，重量级的大型长枪到还好，不过短枪的威力就……”

这倒是点中了要害之处。

我像是不服气的小孩似的嘟起嘴唇，看着这样的我，希斯克里夫轻轻笑了笑，继续说道。

“用绝对不是高级品的短枪，要把中等实力的肉盾战士一击杀死……嗯，以现在来说，我认
为等级要到一百才有可能。”

“一百！？”

亚丝娜惊讶道。

细剑使那榛色的眼瞳，看了看希斯克里夫和我后，连忙摇起头来。

“怎……怎么可能有啊，那种人。到目前为止，你跟我是多么积极地在升级，应该不会忘记
吧。等级一百什么的……就算二十四小时都待在最前线的迷宫区也不可能做到啊。”

“我也是这么认为的。”

最强公会KoB的No.1跟No.2一起做出否定，只是个独行玩家的我也没法进行反驳了。事实上，
攻略组当中也差不多算是顶尖玩家的我，等级现在也只在八十多一点。

但我还是不肯放弃似的，嘟囔道。

“……哼，也有不是靠玩家本身的能力值，而是靠技能的强悍度啊，例如……出现第二名使
用‘Unique Skill’的玩家之类的。”

听完我这话，披着暗红色披风的团长大人肩膀动了动，微笑道。

“嗯……如果有这样的玩家存在的话，我倒是想直接劝进KoB呢。”

接下来被那不知道在想什么的眼睛望着，我便放弃了继续追寻这条线下去的念头，靠在廉价
椅子靠背上。

“哼，原本觉得这想法应该行的通呢，剩下的还有……”

可以让Field BOSS怪兽给他来一下啊，在说出这白痴的想法前，旁边突然出现了一个人影。

“……久等了”

随着没啥干劲的声音，NPC店主从托盘上把三只白色海碗放到了桌上。因为那从沾满油渍的
厨师帽下延伸出的长发，完全看不到他的脸。

由于看惯了其他层即干净又有礼貌NPC，亚丝娜用呆然的目光目送店主返回柜台。

我从桌上拿起一副廉价免洗筷，掰开，将一只海碗挪到自己跟前。亚丝娜也做了相同的举动，
并低声问道。

“……这料理，是什么啊？拉面？”

“很，很像面的什么东西吧。”

回答完，我把沉在浅色汤里缩成一团的面给捞了起来。

在破烂的店内，短时间有三道吃面的声音，静静地响起。

帘外拂过干燥的风，不知名的小鸟在高声的鸣叫。

数分过後，把已经吃空的海碗推到旁边，我望向对面的男子。

“…………那个，团长大人，有什么头绪吗？”

“…………”

把汤都全部喝掉，把碗放在一旁的希斯克里夫，凝视着碗底像汉字的图，说：

“……这不是拉面，绝对不是”

“嗯，我也这么认为。”

“那么，就以这伪拉面为例子解说下吧。”

抬起头，摆好免洗筷。

“……现在可供判断‘发生了什么事’的材料还是太少了。但只有一件事可以说。听好
了……这件事情唯一可以确认的，是你们亲眼所见，亲耳所闻的第一手情报。”

“……？什么意思……？”

“也就是……”
    
希兹克利夫用那双黄铜色的双眼，依次看了看坐在一起的我和亚丝娜，说：“在艾恩葛朗特
中直接看到听到的一切，都是可以用程序转换的数据资料。在这里是没有幻觉幻听的。反过
来讲，不是数据资料的任何情报，都有可能隐藏着欺瞒。要调查这起杀人……‘圈内事件’
的话，只能用眼睛和耳朵，也就是相信自己大脑所接受到的资料。”

多谢你的款待，桐人君。

最后撂下这句话，希斯克里夫站了起来。

一边思考着剑士谜样的话，我也站起身，对向店主说了声“结帐”，就走出门去。

站在前方的希斯克里夫，小声说出的“为什么会有这种店的存在啊……”，稍稍传到了我的
耳朵。

★　　★　　★

团长的身影逐渐溶入到迷宫般的街道中，等到他消失不见后，我才转过身去，朝着身旁的亚
丝娜问道：

“……你知道刚刚那话的意义吗？”

“……嗯。”

看到她点头，哦哦真不愧是副团长啊，我便这么想到。

“是指的那个吧。也就是‘没加酱油的东京风酱油拉面’，所以才会是那种寂寞的味道。”

“诶？”

“决定了，我总有一天绝对要做出酱油给你看，不这样的话，我觉得那种不满感永远都不会
消失。”

“…………这样呀，那加油吧……”

嗯嗯的点头后，不是这样吧啊啊！！我吐槽道。

“诶？发生什么事了，桐人君？”

“让你吃那种怪东西是我不好，抱歉，拜托赶快忘掉吧。不是说这个啦，希斯克里夫那家伙，
怎么像是说出了些佛理的话题啊。他那些话的意思。”“啊……”

亚丝娜这次明确的点了下头，答道。

“那就是说，别完全听信二手消息的意思吧。对于这个事件来说，也就是动机……黄金苹果
公会的那个戒指事件吧。”

“诶诶——？”

我不禁发出反驳的声音

我不禁发出声来。

“怀疑优尔可小姐吗？那个，虽说完全没有证据……不过刚刚亚丝娜你也说了，去取证也没
意义，所以怀疑也同样是没意义的，不是吗？”

听完这话，亚丝娜不知为何瞥了我一眼，很快又把脸背过去，点了两三次点头。

“那，那个，这样说也是呢。不过正如团长所说的，断定是PK手段的材料还远远不够。这样
的话，就再去问问另一个相关者吧。突然提及戒指事件的话，他可能会不小心说漏嘴哟。”

“诶？是谁？”

“当然是从你那把枪给抢走的人咯。”
*** 第6节

★　　★　　★

视野右下的数字，刚好显示着下午两点。

平常的话，应该是结束中餐时间，大家开始前往进行午後的迷宫区攻略活动。但今天则完全
没有这种离开街上的闲功夫。通过最前线的区域，前往未攻略地下城地区的话，大概天都要
黑了。

对于我这种会用“因为天气真好”的理由而偷懒的不认真的人来说，倒是没什么啦，但连续
两天都没进行攻略的“闪光”是怎么想的呢。

边这么想，边用余光看着走在旁边的亚丝娜，很意外的是，她周围的气氛，让人觉得比平常
还要柔和。在阿尔盖特的小巷里的谜之商店乘凉，或是看往不知通往何处的暗渠时——注意到
了我的视线，“嗯？”的，偏起头并微笑了起来。

“怎么了？”

被这么问道，我也只得摇了摇头。

“不……没，没什么。”

“你这怪人——也不是现在才这样啦。”

笑了笑，把双手背在身后，踩着轻巧的舞步，让鞋后跟发出声响。

真是的，到底谁才比较奇怪呀。这位真的是，昨天在我午睡时如同落雷般大声斥责我的攻略
之鬼吗？或者说是，对那“阿尔盖特荞麦面”感到很满意？那下次，真想要带她试试味道更
混沌的“阿尔盖特烤肉”呢。

在胡思乱想中，转移门广场喧闹的声音变得越来越近。幸好这次不需要靠向导NPC的帮助就
回到这里啊。

我强制把心神不宁的内心给压下，首先咳了一声。

“咳……接下来，就剩去找修密特主将把话给问清楚而已了，仔细想想，这个时间点DDA是
不是也是去狩猎了啊？”

“嗯——这就不知道了呢。”

微笑散去的亚丝娜，用指尖抵着小巧的下颚做出了以上回答。

“如果相信优尔可小姐的话，修密特也是‘反对戒指卖出派’的人……也就是和凯因兹先生
同样的立场吧。从昨天他在你面前现身的样子来看，很明显他也有这种感觉。被谜般的‘红
名玩家’盯上……如果他也是这么想的话，还会不会走出圈内呢。”

“嗯……照你这么一说倒也是呢，不过这‘红名玩家’，很有可能有圈内PK的方法哟。就算
待在街区，也不能保证绝对的安全。”

“正因为这样，至少会想确保最大限的安全吧，躲在旅馆里，或是……”

听到这，我终于理解亚丝娜想说的话，打了个响指，继续说道。

“或是‘闭门不出’，那么，就应该在DDA的本部。”

★　　★　　★

最强工会之一的圣龙连合，前阵子才在第五十六层隆重地设立工会据点，并且是在血盟骑士
团本部的五十五层的上面一层，这绝对不是偶然。不知是出于什么情义我也被邀请去了那奢
华至极的纪念派对，并且被那与其说那是‘据点’，倒不如说是‘城堡’或者‘要塞’的夸
张度给惊呆了。至少要把这讨厌的情绪，用大吃一顿的方式来回敬他们，不过结果却让我跟
克莱因还有艾基尔三个人，因味觉信号过量的输入，接下来三天都处在腹胀感的苦恼之中。

从阿尔盖特的转移门移动出来的我，望着那耸立於小丘上，能够俯视街区的令人讨厌的饱食
之城，不由得发出反胃的声音。亚丝娜倒是没什么特别的想法，只是一步步地登上铺满红色
砖头的坡道。

看着插白色尖塔群上飘荡着的银底蓝龙的工会旗帜，我嘟囔道：

“不过，不管DDA在怎么闻名天下，也真亏他们有能买下这种东西的金钱啊。您觉得如何呢，
KoB的副团长大人？”

“嘛，虽以公会人数来说，DDA是我KoB的一倍。但还是无法接受。我那儿的公会会计大善先
生曾说过‘他们有好几个超高效率的打怪点’【farming spot】呢。”【原译注:原文中他
讲的是名古屋腔……】

“诶诶。”

Farming，是指以很快的速度刷出大量MoB并能持续不断地进行狩猎的MMO用语。去年冬，因
某原因陷入疯狂刷级的那段时间，我就是待在“蚂蚁谷”等很具代表性Farming地，不过只
要获得的经验值超过某个阈值，支配SAO世界的数码神“Cardinal-System”便会将取得刷经
验的效率向下进行修正。

也因为如此，把这些优良的Farming点向所有玩家行了公开，直到恩惠枯竭前大家都能平等
地共享，虽然这是攻略组间达成的审视协定，不过DDA却违反这项协定，藏匿了几个地点——
这就是亚丝娜想说的重点。

说狡猾确实是很狡猾，但DDA强化的话，论结果来说是攻略组总体也会得到提升，因此也不
好正面指责他们。

更进一步来说，最终也只会把攻略组存在的自我矛盾体现出来而已。以把大家从死亡游戏中
解放作为光鲜的大旗，独占大部分系统所供的资源，维持住金字塔结构的阶级制，都是出于
我们这些人的自私。

这样一想，和攻略组完全相反的组织“艾恩葛朗特解放军”主张的，把全部玩家得到的资源
一并征收，公平分配——这样的方针，也不是能一脚就能踢开的虚言妄语。没错——假如“军”
的这种主张能够实现的话，恐怕也不会发生这次的“圈内事件”。成为本案根源的戒指，在
掉落出的瞬间就会被征税，卖掉，利益被分成数万份并就这样消失掉。

“真是的……创造这死亡游戏的人，一定是不招人待见的家伙……”

更何况这还是MMO。明明像是RTS或是FPS等这些，更为公平的，瞬间就能决定胜负的游戏就
像山一样多。

SAO，就是一个考验高等级玩家的执念的游戏。是个把矮小的优越感和同伴的——甚至是所有
玩家的性命都强制放在天秤上，让玩家进行比较取舍的游戏。

戒指事件的犯人，就是被自我的执念给吞噬了。

对我而言，这并不只是他人的事情而已。对于我这种把稀有魔法道具根本比不上的秘密，独
占在能力栏中的人。

——不知是不是听到了我的自言自语，像是看透了我所有思考的亚丝娜低声说道。

“所以，这件事情才不得不由我们来解决。”

接着，她瞬间紧握我的右手，对我投来仿佛能吹走一切迷茫的毫不动摇的微笑。对着不知所
措的我留下了“在那边等等”后，亚丝娜朝着巨大城门走去。我则把留有余温的右手伸进了
大衣的口袋里，背靠在身旁的树上。

被登记为公会据点的建筑范围，基本上只有成员才能够进入。跟玩家的房屋是一样的。因此
本来是不需要守卫的，不过人手很多的公会，大部分都会轮班配置与其说是警卫，不如说是
给来客传达信息的人。

圣龙联合也不例外，华丽的城门旁有两名重装枪战士如仁王像一般的站立在那。

——说起看门的，在RPG里面一定是中等BOSS级别。思索着这些，不由得警惕起来，跟我不同，
亚丝娜则是迅速走到右侧的守卫前，问候了一声。

“你好，我是血盟骑士团的亚丝娜。”

刚说完这话，巨躯战士瞬间上身后仰了下，轻轻地说。

“啊，你好！您，您辛苦了！来这里有什么事吗！”

完全不像仁王以及中BOSS了。亚丝娜对着左侧走来的男性玩家也不吝啬的投以漂亮的微笑，
说出来意：

“有点事要找你们的成员。叫做修密特先生的人，能够帮我连络他一下吗？”

听完，两人互相看了看对方，其中一人歪起头来。

“那人现在不是在迷宫区吗？”

随后，另一名男子回应道。

“啊，不过，今天吃早餐时好像他说了‘今天有些头痛，休息一天’的话，搞不好是待在自
己的房间里，我去叫叫他吧。”

老实说他们会这么帮忙，真是出乎我的意料。DDA跟KoB都是公会，因此关系绝好不到那里去，
但私人就不适用这套原则了——或者说是亚丝娜的个人的魅力吧。如果是后者，或许我不出现
比较好。

紧靠在城门附近的树干上，顺带将隐蔽等级提高一点的时，其中一名就已经很一块的速度输
入完了信息，并发送了出去。

三十秒后，很快就像是有了回信，守卫再次操作起窗口。果然修密特躲就待在这座城内，加
入是在前线迷宫内战斗的话，是没办法这么快就回信的。

看了看回信内容的守卫，困扰似的皱起眉头。

“果然今天是在休息……不过，像是要先听听什么事，修密特就是这么说的。”

亚丝娜稍稍考虑了下，简短地答道：

“那，就请帮我转达‘有关戒指的事’就好。”

效果真是好啊。

因头痛而卧在床上的男人，马上用超快的速度冲到城门来，说出“换个地方说话”就直往山
下走去。之后亚丝娜从我面前经过时，与刚才一直没露脸的我汇合。修密特看了我和亚丝娜
一眼，便知道我们是搭档的事宜，没等我们做出反应便高速驰行起来。

走在数米前的修密特，身上的穿着仍旧是昨天找我拿枪的时候一样，看起来很高级的板甲。
下面还穿着薄链甲。虽说没背着双手长枪，但装备重量应该还是很惊人。像是感觉不到负重，
高速前行的他，与其说是肉盾战士【Tank】，不如说更像美式足球的选手。

在SAO玩家中也算是很少有的体育系壮男，在走下坡道进入市街时，总算停下脚步，铠甲发
出咖啷的声音，转身向我们问道。

“你们从谁哪听来的？”

“诶？”

听到对方的回问，并意识到了他省略了“戒指的事情”这个宾语，于是慎重的答道。

“……从公会‘黄金苹果’的老成员那里听来的。”

听到这里，尖立短发下的粗眉毛颤动了一下。

“名字是？”

我稍微犹豫了一下，假如修密特是昨天事件的犯人，他应该知道凯因兹跟优尔可在一起的事
情。现在就算不说出名字也没什么意义。

“优尔可小姐、”

回答後，壮男一瞬间像是放心般的把视线往上移，呼出一口长气。

我保持着一副扑克脸，迅速思考起来。刚刚那反应如果是“放心”的话，也就是说他知道优
尔可也同样是“发对卖掉戒指派”的这件事。

修密特果然也已经察觉到，昨天那事的意图，可能是包含葛林姆洛克在内的“卖出派”的某
人，对“反对派”的复仇，所以才会假装生病躲在公会本部里。

如今，修密特是杀害凯因兹的犯人的可能性非常小，但也不是说完全没有动机。假如戒指事
件的犯人是凯因兹与修密特，也有为了封口而把其中一方杀掉这种可能。想到这些的我，单
刀直入的问道。

“修密特先生，昨天你拿走那把枪的制作者葛林姆洛克氏，现在人在哪你知道吗？”

“不……不知道！！”

吼叫着，修密特激烈的摇摇头。

“公会解散以来一次都没有连络过，连还是不是活着都不知道！”

他以很快的速度这么说道，同时视线傍徨游离在街道各处。就像害怕会从哪里会凭空飞来一
把枪那样。

到目前为止都保持沉默的亚丝娜，平稳的语调向他说道：

“那个，修密特先生，我们并不是要找出谁杀害了黄金苹果的会长的犯人，而是昨天那起事
件的犯人……我们只是打算找出那起事件的手法，以维护‘圈内’的安全。”

亚丝娜稍微停了一会儿，随后用更为严肃的语气续说道。

“……虽然很遗憾，但目前最有嫌疑的人是打造那把枪……也就是公会会长的丈夫葛林姆洛
克先生。当然，也可能是某人刻意让我们做出此种结论，所以为了得出判断，我们无论如何
都想和葛林姆洛克先生当面谈谈。如果你有他现在的住址，或是联络方法的话，可以告诉我
们吗？”

被榛色眼瞳注视着，修密特略为挺起了上身。看来他很不擅长和女生说话啊。和我一样。

转到一旁，嘴角僵硬地打起结来。亚丝娜的正面攻击也没效的话，我叹了口气，心想“大概
没办法用一般的方法来解决了”。不过，就在一会儿后。

“…………我真的不知道他住哪里。只不过。”

修密特慢慢地开始述说。

“当时，有间葛林姆洛克非常喜欢的NPC餐厅，几乎每天都会去，也许现在也……”

“真，真的吗？”

我探出身子，同时思考起来。

在艾恩葛朗特，吃几乎是唯一的快乐，但同时，要在廉价的NPC料理中找到喜欢的味道是很
难的。如果有每天都去的餐厅的话，要中断这个习惯也是很难的。即便是我，每天的用餐也
只是在三家餐厅间互换而已。顺带一提的是，之前那个谜样的小吃店不包含在内。

“那么，那间店的名字是……”

“我有条件。”

修密特打断了我说出的话。

“告诉你们可以，但有一个条件……让我跟她，也就是优尔可见面。”

★　　★　　★

让修密特在附近的道具店等着，我和亚丝娜迅速的讨论起来

“应该……没有危险吧？是吧？”

“嗯，应该……”

被亚丝娜这么问道，但没法做出判断的我只得这么低语道。

假入修密特，或是是完全不可能的优尔可，其中一人是犯人的话，那把对方当成下次目标的
可能性非常高。在见面时，使用谜样的“圈内PK技”，出现新的死者这种情况也无法排除。

只是，在这个场合，装备武器，再让SwordSkill发动是有着绝对必要的顺序的。加上打开视
窗，选择装备等动作，最少也需要个四五秒。

“…………只要我们盯好，应该是不会有PK的机会的。——但，假如这不是这个目的的话，那
修密特这家伙，为何事到如今才要跟优尔可见面呢？”

双手往两旁一摆，亚丝娜大大的歪着头来。

“天知道……实际上是单相思，这样……应该不可能吧，嗯。”

“咦，真的吗？”

我不禁的把头转往外表可以说是木讷的修密特，但却被亚丝娜抓住领子，制止了。

“我不是说不可能吗！……总之，危不危险就交由优尔可小姐来决定，传个讯息给她确认一
下。”

“啊，好，麻烦你了。”

亚丝娜打开窗口，高速敲打起虚拟键盘。这种“Friend Message”可以马上跟对方取得联络，
虽然很方便，但就算知道对方的名字，没有成为好友，或者不是相同公会成员，以及结婚对
象的话，是没办法用的。因此才没办法用这方法跟葛林姆洛克取得联络。虽然可以用只知道
名字就能发送的“Instant Message”，但不在相同层数就无法送达，而且也不知道对方收
到没有。

不到一分钟优尔可就有了回信，亚丝娜打开窗口，瞥了一眼后点了点头。

“OK呢。那……虽然有些不安，但还是带路吧，地点就是她现在居住的那间旅馆。”

“嗯，让她外出还是很危险呢。”

同意后，我转过身朝向在道具店等候着的修密特，对他点了点头，重武装的壮汉明显的露出
一副放松的表情。

★　　★　　★

一行三人从五十七层主街区马汀的转移门出来时，街道已被夕阳所笼罩。

广场上充满着NPC以及商人玩家的露天商店，到处都是热闹又响亮的叫卖声在这之间，到处
可见为了治癒一天的疲劳而三五成群的剑士们逛着商店，不过在广场的某地，却被大家当成
了一个惊悚的空间，没有一人愿意去那里。

就是小教会附近。不用说，就是二十四小时前鸣叫凯因兹的男人，惨死的场所。我把快被吸
引过去的视线，强硬的往前固定，走在这昨天同样走过的道路上。

数分後，来到目的地的旅馆，登上了二楼。细长走廊最里处，就是优尔可目前暂住——或说被
保护的房间。

敲敲门，向对方报上“我是桐人”。

没多久，就听到微弱的回应声，我便转动门把手。被设定为“只限朋友可以打开”的门锁，
发出一声轻响便解除了。

在打开的门的正面，摆设房间中央的沙发一角处，优尔可就坐在那里

。随即，她站起身，摇动着波浪般的头发向我们轻轻一礼。

我在这场合先保持不动，轮流看着优尔可僵硬的脸还有呈现同样表情的修密特，说：

“那个……首先为了安全先确认一下，你们两人都不能装备武器，系统窗口也不能开，这两
件事请务必遵守，虽然可能会觉得不舒服，但还是麻烦了。”

“……好。”

“我知道了。”

优尔可细细的声音，以及修密特带有不高兴的声音同时回答道。随后，我领着修密特慢慢的
走进房间。

应该很久没见面，原“黄金苹果”成员的两人，一段时间就这样沉默着相互对视。

以前虽是同工会的优尔可跟修密特，现在的等级差别已经超过二十级了吧。但在我的眼中，
修密特反而看起来更为紧张些。

事实上，先开口的也是优尔可。

“……好久不见，修密特”

脸上带着薄薄的微笑，相对修密特紧紧咬了嘴唇，用沙哑声音回道。

“……嗯，原本以为再也不会见面了，我可以坐下吗？”

看见优尔可点点头，重板甲发出喀啷咖啷的声音，修密特走向沙发，在她的对面坐下。虽然
觉得很挤，但他也没有要脱下来的意思。

我和亚丝娜交换了视线，确认门已锁上后，我站在优尔可和修密特的东侧，亚丝娜则站在相
反方向。

为了被强迫待在室内的优尔可，我们租借了最高级的房间，就算四个人同时进来仍旧很宽敞。
门在北侧的墙上，西边是往寝室的另一道门，东边和南边则是巨大的窗户。

南边的窗户呈现打开的模样，带着春之残息的风正吹拂着窗帘。当然窗户同样也在系统的保
护下，有谁要闯进来是绝对不可能。此房间也比周围的建筑物稍微高一些，从白色的窗帘间
缝还可以一眼望尽染成深紫色的街道。

街道上的喧闹声乘风飘入，但被优尔可缓慢说的话声给遮盖了。

“修密特，你现在在圣龙联合了呢。真厉害，就算在攻略组中也是顶级的呢。”

虽然觉得是直率的赞美词语，但修密特的眉间却浮起些严峻的神色，低声回答：

“你什么意思。是想说，不自然吗？”

这种充满尖刺的回话也要有个限度啊，我睁大了双眼，不过优尔可却没怎么动摇。

“怎么可能，我想一定是在公会解散後，非常的努力呢。这是我和凯因兹都放弃了的事，你
真的是很厉害啊。”

稍微拨开挂在肩上的深蓝色头发，再次微笑起来。

虽说没办法跟穿重甲的修密特比较，不过今夜优尔可的穿着也是相当多。厚实的连身裙外面
罩着皮制的紧身上衣，再加上披着天鹅绒的束腰外衣，肩膀还有披巾。虽然没有金属防具，
但穿成这样也会有很高的防御力加成。虽然表面很平静，但她果然也是很不安啊。

而完全没有隐藏起紧张的修密特，铠甲发出咖啷一声，站起身来。

“我的事情怎样都好！重要的是……我想问的是凯因兹的事情”

转变成极端压抑的声音，继续说道。

“为什么现在凯因兹会被杀害啊！？那家伙……是抢走戒指的人吗？杀掉GA会长的也是他
吗！？”

GA，GoldenApple，我立刻想到这是黄金苹果的简称。不过这个台词，等于是修密特宣称自
己跟戒指事件和圈内杀人都没有关系。如果这是演技，那还真是高啊。

听到这句低声叫喊的优尔可，表情第一次发生了改变。微笑消失了，正面睨视起修密特。

“没这种事，不论是我或是凯因兹，都非常的尊敬会长，反对卖掉戒指也是因为与其大家把
钱乱花用掉，不如拿来给公会充实战力还比较有效，事实上会长应该也是想这么做。”

“那个……我也是这样想呀，别忘了，我也是反对把戒指卖掉的，而且有抢夺戒指动机的，
不只是反对派。卖出派，也就是想要钱的家伙们，也可能有想独占的人呀！”

修密特把套着铁手套的右手，拍了一下膝盖，抱起头来。

“但是却……葛林姆洛克为什麽现在才把凯因兹……是想把反对派全员都杀光吗？我跟你也
都被盯上了吗！？”

————演技，我觉得并不像。紧咬牙关的修密特侧脸，明确的刻印上了恐惧。望着害怕的修密
特，再次平静下来的优尔可，慢慢的对他说道：

“还没有认定是葛林姆洛克杀害凯因兹的呢，也可能是找他作枪的某个成员下的手，也
许……”

空虚的视线，落在沙发前的矮桌上，低语道。

“会不会是会长自身的复仇呢？圈内杀人这种事情，普通的玩家不是根本做不到吗。”

“什……”

修密特嘴巴一开一合，而我也略微打了个寒颤，无法否定这个可能。

呆然看着微笑的优尔可，修密特说：

“你刚刚不是才说，凯因兹不可能去抢夺戒指……？”

没有立即回答，优尔可轻轻地站了起来，往右挪出一步。

两手交握放在腰后，慢慢向着在南侧的窗户走去。随着室内鞋的轻微声响，柔细地声音传了
过来。

“昨晚，我一夜都没睡，想着这些。到头来杀掉会长的，是公会成员的某人，也同时是我们
全员哦。在戒指掉落出时，不要用投票，而是全权交给会长来处理就好了呢。会长不仅是剑
士还是最有实力的成员，同时最能够活用戒指能力也是她。但我们大家都没办法舍弃自己的
私欲，所以也没人说出这个提议。嘴巴上一直说总有一天要让GA成为攻略组，但实际上却不
是为了公会，而只是想让自己变强而哟。”

说完这番漫长的话，优尔可腰靠着南侧的窗缘，又附加了这样一句话。

“只有一个人，也就是葛林姆洛克先生说了把决定权交给会长。只有这个人，有着向我们全
员复仇的权利，当然，会长本人也是……”

沉默中，只有寒冷的夕风在房间内拂动。

不久，喀啦喀拉，细小的金属声传来。来源是微微震动着的修密特的覆盖全身的金属铠甲。
身经百战的顶级玩家，垂着苍白的脸，像梦呓似的低语起来。

“……………别开玩笑，可别开玩笑啊，到现在……已经过了半年，为什么现在才……”

突然挺起上半身，大叫起来。

“你难道觉得这样好吗！明明努力活到现在了，却要被这种，莫名其妙的方法杀掉，你认为
可以吗！？”

修密特，我还有亚丝娜的视线一齐往窗边的优尔可望去。

带有些许梦幻般氛围的这名女性玩家，视线望向空中，彷徨了一会儿，像是在寻找着要什么
话语一般。

没多久，唇瓣微动，就在要说出什么时——

咚，一声闷响回绕在房间中，优尔可的眼睛与嘴巴，大大的张开。接着，纤细的身体晃动起
来，像断线的人偶般踏出一步，转身用手撑在窗缘上。

此时，一阵强风袭来，把优尔口垂在背上的头发吹动起来。

我在这时，看到了难以置信的东西。

紫色的束腰上衣的中央，出现了一支黑棒般的物品。

那物品实在是太小，瞬间，完全不知道那是什么。不过在发现包覆着棒子的明灭闪烁的红光
时，我浑身战栗起来。

那个是，投掷用匕首的柄。刀身，完全埋进了优尔可的身躯。也就是说——从窗口对面的某个
地点，飞来的黑色短剑，刺穿了优尔可的背。

前后摇晃的身体，朝着窗口倒去。

“啊……！”

亚丝娜发出悲鸣般喘息。同一时间，我冲了过去。

伸出手想把优尔可的拉回来。但。

指尖只碰到披肩的一小端，优尔可就静静地从外房间侧落了下去。

“优尔可！！”

探出身子，大叫着的我的眼前。

坠落在下方的石砖上，弹起来的优尔可的身体，被青光所覆盖。

啪沙，伴随着细小的破碎声。多边形的碎片，随着炸裂所释放的蓝光朝四周扩散开来——

一秒后，传来干硬的声响，只有漆黑的匕首落在了路面上。
*** 第7节
怎么可能！！

在我脑中响起的无声呐喊【哑叫】，有着好几层意思。

旅馆的客房是被系统保护着的。即便窗户打开着，想侵入客房内部，或是把什么投掷进来都
是绝不可能的。

更何况是那么小的投掷匕首，就算有贯通持续性伤害，也绝对不可能把处于中等级别玩家的
优尔可瞬间击杀。而且从被匕首刺中到优尔可坠落，消失为止怎么算都只有五秒钟。

绝对不可能。这已不是可以用“圈内PK”来形容的了，而是惊悚至极的即死攻击。

呼吸变得困难，一股温度极低的战栗感涌上脊背，我强迫着自己把视线从屋外优尔可消失的
石板路面上移开。猛抬起头，睁大双眼，如同摄像机一样对着屋外的街道望去。

随后，我发现了那个。

大约两街道处，差不多同样高度的建筑屋顶上。

以深紫色的夕阳残照为背景，单独站立的黑衣人影——

漆黑的斗篷包住全身，无法看到脸。把脑海中立刻闪现出“死神”这个词语摒除，并大声叫
道：

“混蛋……！！”

右脚踏上窗缘，头也不回地再次叫道。

“亚丝娜，后面就拜托你了！！”

说完，便朝着街道对面的屋顶，猛地一跃。

不过，就算有敏捷值补正，没有助跑就想飞越五公尺宽的街道，还是有些无谋了。没办法直
接用脚着陆的我，伸出右手勉强抓住屋顶边缘。这次则是运用了力量值补正，利用倒立的要
领把身体甩了上去。发转一圈并立在屋顶上时，身后传来了亚丝娜急迫的声音。

“桐人君，不行！”

我很明白她制止我的理由。如果被那个投掷匕首刺中的话，我可能也会受到即死攻击。

不过，以自保为优先，而眼睁睁看着这个终于现身的杀人犯逃走，无论如何我都做不到。

负责保护优尔可安全的是我。不过，我却认为肤浅的认为只要让优尔可呆在被系统保护的旅
馆内的话就不会有危险。受系统保护的原本就是包括街道——“圈内”内所有物体。能够在圈
内进行PK的对手，应该就连旅馆的保护都能无效化，为什么之前我没有想到呢。

就像是在嘲笑我的懊悔似地，远处屋顶上的黑色斗篷迎风飘展起来。

“别跑……！！”

我大叫着，急速奔跑起来。同时拔出身后的剑。当然我的剑没办法给对方造成伤害，但应该
能格挡下飞来的匕首。

为了不让奔跑速度减缓，我直接在屋顶间跳跃着进行移动。在下方的街道上行走的玩家，一
定以为我是个在表演，炫耀敏捷值的日西厨吧，但现在管不了那么多了。外套的衣摆随风摆
荡，用如同划破黑暗的势头继续跃动着。

身着全覆盖斗篷的暗杀者，没有要逃走，或者是攻击我的意图，只是悠闲的站在那里，看着
急速接近的我。在双方的间隔只有两栋建筑这时，突然他的右手有了动作，朝斗篷内伸去。
我则屏住呼吸，把剑架在身前。

不过。

抽出来的手上握的并不是投掷用的匕首。而是在漆黑的迷宫底处，十分熟悉的，释放出蓝宝
石光泽的——转移结晶。

“可恶！”

我咒骂着，疾驰过程中，用左手从腰带上拔出三支投掷用短锥。向下振臂，猛地将三支同时
投了过去。并不是为了造成伤害，而是让那人下意识采取回避动作，延缓指令的咏唱。

但实在可憎的是对手依旧十分冷静。毫不害怕闪着银光向自己袭来的三支短锥，悠然自得地
高举起水晶。

就在接触到斗篷的刹那，丢掷短锥全被紫色的障壁阻挡，坠落到了屋顶上。此时的我竖起耳
朵，至少也要听清对方念出的指令。只要知道其转移之处，我也能用结晶追过去。

虽然是这么盘算，但这次依然出乎了我的期待。刚好这时，马汀的街道上响起巨大的钟声。

我的耳朵——正确来说是听觉区，几乎都被告知下午六点的系统音占据，没办法听到暗杀者用
最低的声音说出的指令。差一点便能到达其身边，就在此刻爆出青色的传送光忙，不祥的斗
篷姿也无声息的消失了。

“………………！！”

我发出了无声的呐喊，举起右手剑朝三秒前那家伙还站着的地方猛敲下去。散发出紫色光芒，
视界的中间出现的只有“Immortal Object”字样的系统讯息而已。

★　　★　　★

没再顺着屋顶的路，悄悄返回旅馆门前的我，在优尔可消失的路旁停下脚步，望着滚落在石
路上的那把漆黑的投掷匕首。

就是几分钟前，有一名女性玩家死了在了这里，我无论如何也不敢相信。对我而言，玩家的
死亡，是只有在付出了各种各样的努力，加上采取了多种的回避对策后，能力却依然不足时
才会迎来的结果。像那种瞬间的，无法回避的杀人手法应该是不可能存在的。

我弯下身，捡起那把匕首。虽然很小，但整体是用同一种金属素材制成，颇有重量感。剃刀
般极薄的刀刃两侧，雕刻着鲨鱼牙齿般的逆棘。没错，这跟杀死凯因兹的短枪是用同样的理
念打造而出的。

假如现在我把这玩意刺进自己的身体，我的HP也会急速减少吗。虽然被这种试验的冲动驱使，
但我却紧闭上眼将此冲动摒除，随后走进了旅馆。

走上二楼，敲门并报上自己的名字后，转动门把。“咔嚓”的系统开锁声空虚的响起，门打
开了。

亚丝娜已拔出细剑。看到是我后，浮现出激愤和安心各一半的复合表情，把声音压得极低对
我叫道：

“笨蛋，别乱来！”

呼，长吐一口气，把声音再次降低了些，继续说道。

“……那个……怎么样了？”

我微微摇了摇头。

“没追到，他用传送逃掉了。不管是脸还是声音，就连是男是女都不清楚。嘛啊……如果那
就是葛林姆洛克的话，就应该是个男的……”

SAO内同性结婚是不可能的。如果黄金苹果的会长是女性，那跟她结婚的葛林姆洛克自然而
然就是男性。而且，如果这就是费劲心思才得到的资料的话，也是份没什么用的情报。SAO
的玩家实际上将近八成是男性。

对于我番这并没多大意义的话语——

不经意做出反应的就是，在沙发上将巨大的身体尽可能的缩在一起，发出喀啷咖啷金属碰撞
声的修密特。

“……不对。”

“不对……什么不对？”

修密特没有望向亚丝娜，而更加低下了头，呻吟道：

“不是他，那个……站在屋顶上的黑斗篷，不是葛林姆洛克。他更高一些。而且……而
且……”

我跟亚丝娜，都对他接下来说的话屏息以待。

“那个带有帽子的斗篷，是GA会长的东西。她去街上，通常都会打扮成那种不显眼的样子。
没错……去卖戒指的时候，就是穿的那件！那个……刚刚的那人，就是她。她为了向我们全
员复仇而来的。那就是会长的幽灵啊。”

哈哈，哈哈哈哈，突然间传来了让我把视线从匕首上挪开的笑声。

“如果是幽灵的话，那一切就都有可能了，圈内PK还不是小菜一碟。乾脆叫会长去把SAO的
最终BOSS打倒好了，一开始就没有HP，因此也不会死掉啊。”

哈哈，哈哈哈哈，修密特继续发出这西斯底里怪笑声，我把握在手中的黑色匕首扔到他面前
的桌子上。

咚，响起沉闷的声音，仿佛切断了修密特的开关似地，笑声停止了。他凝视着散发出凶光的
锯齿刀刃好几秒钟——

“咿…………”

对于弹起上半身并向后仰去的壮汉，我压低声量对他说道：

“才不是幽灵呢，这匕首是确实存在的物品。是写入SAO服务器的几行代码程序而已。就跟
你放进储物栏的短枪是一样的，不相信的话，你就把这匕首拿去，随你怎么调查都可以。”

“不，不要！枪也还给你！！”

修密特大叫着，调出目录窗口，在颤抖的手指误操作好几次后，终于把黑枪实体化了。浮在
窗口上的武器，就像是扔到一边似地落到了匕首旁。

对着再度抱起头的巨汉，亚丝娜用安详地声音对他说：

“……修密特先生，我也认为那不是幽灵。因为，如果艾恩葛朗特出现幽灵的话，那一定不
会只有黄金苹果的会长一人而已。到目前为止死去的三千五百人，大家都一定很不甘心的。
我说的没错吧？”

就是这样，我也这么认为。即便是我，如果死在这里也一定心有不甘而化作幽灵出现的，我
有这个自信。能够接受命运而成佛的人，就我所知大概也只有KoB团长那种人吧。

不过修密特，仍旧低着的头，这次依旧是左右摇动起来。

“你们……不认识她吧。那人……葛林瑟鲁妲，可是超级强悍，态度一直都很坚决……不过，
对于不公正与耍滑头也是十分的严厉。比你还要厉害啊，亚丝娜。所以，如果有设下圈套并
杀死她的人存在的话……葛林瑟鲁妲，绝对是无法原谅的。即便是，化作幽灵也要给那人予
以制裁吧……”

苦重的沉默充满了整个宽敞的房间。

大概是亚丝娜关闭的吧，上锁的窗外，太阳已差不多落了下去。亮起几处橘色的路灯，本应
是玩家们寻找住宿的地方，而让街道变得热闹起来的时间，但不可思议的是那些喧嚣也仿佛
躲避着这个房间一样。

我深吸一口气，打破了笼罩整个房间的寂静。

“……如果你相信是那样，就随便你了。但我绝对不会相信的。这两起‘圈内杀人’，绝对
存在着系统上的逻辑。我一定会找出来给你看的……你也照约定，协助我们吧。”

“协……协助？”

“你之前说过，要告诉我们葛林姆洛克常去的店吧，到现在这已经是唯一的线索了，花几天
去监视，一定可以找到他的。”

说真的，就算找到那把黑枪，大概也是旁边那把匕首的锻造者葛林姆洛克，接下来要干什么
我一点也不知道。我们既不是“军”，也不可能去做把人监禁起来这事。

只不过，优尔可被害前说的那番话——“葛林姆洛克，大概要向我们全员复仇，杀掉会长的敌
人，他有这样的权利”，假如就像优尔可说的这样，葛林姆洛克要向反对卖掉戒指派的三人，
说不准还要对原公会所有成员复仇的话。而且动机是丈夫对死去的会长的强烈思念的话。

那么只要能见面并认真交谈的话，或许还能有所转机。事到如今，也只能赌一下这个可能性
了。

听到我说出这番话的修密特虽然再次低下了头，但不久后还是很沉重似地从椅子上站了起来。
走到墙壁边的写字桌旁，拿起已备好的羊皮纸跟羽毛笔，写下了店的地点以及名字。

望着其背影，我突然想到一件事，于是便问道：

“啊，顺便写一下原黄金苹果的全部成员名字，等一下我要再去‘生命之碑’确认一下生存
者。”

默默地点了下头，巨汉再次拿好笔，又写了几秒钟。

不久后，他就把写好的羊皮纸单手拿起，递给我的同时，说道：

“…………身为攻略组的玩家是很丢脸，不过……我暂时没心情去外面。BOSS攻略战的团队
编成，也请把我去掉。还有……”

曾经刚毅完全消失，挂着一副呆滞的神情，担任圣龙联合会长职务的长枪使低声地说：

“……接下来，请把我送回DDA本部。”

嘲笑修密特胆小的这个行为，不论是我或亚丝娜都无法做到。

我们把害怕的巨汉夹在中间，从五十七层的旅馆经由转移门再朝着五十六层的圣龙本部行进
的过程中，我跟亚丝娜一刻都没停歇地巡视着周围的暗处。如果这时有身着带帽斗篷的毫不
相关的人突然出现的话，我俩可能下意识地冲上去也说不定。

就算走进了本部的城门，但修密特仍旧没露出安心的表情。目送着他小跑进建筑物的背影，
我总算是叹了一口气。

与旁边的亚丝娜相互对视了一会儿。

“…………真不甘心呢……优尔可小姐的事情……”

对着低声说出这话，咬住嘴唇的亚丝娜，我用沙哑的声音回应“的确是啊”。

说实话，优尔可的死，带给我的冲击是凯因兹那时的数倍。在脑中回想着她从窗户坠落的身
影，我继续说道：

“到目前为止，说真的我们就像是随波逐流一样……不过现在不能这样了。就算是为了她，
也一定要把这事件解决——我现在要立刻去那间餐厅附近埋伏。亚丝娜你呢？”

刚听完我的问话，亚丝娜便抬起头来，明确地回答道：

“当然，我也要去。让我们一起查明真相吧。”

“……这样啊，那，接下来也请多多指教了。”

说真的，我很犹豫到底要不要让亚丝娜继续陪我调查。如果我们继续跟这个事件扯上关系的
话，被葛林姆洛克盯上，并成为他的新目标也不足为奇。

但就像要斩断我的犹豫似地，亚丝娜迅速转过身来，朝着转移门广场走去。我深深的洗了口
夜晚寒冷的气息，并猛地呼出，跟在了栗色长发身后。
*** 第8节
记载在凯因兹记事本上的店，是位于二十层主街区下城区的一家小酒馆。这隐藏于曲折小路
中高挂招牌店家，就起外观看去，完全不给人一种这里会有“每天吃都吃不腻”的料理。

不过，事实上往往在这种店里会藏有好吃的料理，我好不容易才克制住冲进店里，把菜单上
有的东西全点一次的冲动。如果葛林姆洛克就是那个身着斗篷的暗杀者的话，那他就应该见
过我的脸，倘若被他先一步发现我，可能就再也不会来这家店了。

躲在附近的隐蔽处，观察周围地形的我与亚丝娜，发现有一家旅馆正处于能够将问题酒馆的
情形看得很清楚的位置。抓住人群中断的瞬间跑进旅馆里，租借了二楼一间正对着街道客房。

正如预料，从窗户处可以清楚的看到酒馆入口处的情形。维持着灯光关闭的状态，搬两张椅
子到窗边后，我跟亚丝娜便并排坐了下来开始监视。

但没多久，亚丝娜就皱起眉头，“喂”的叫了一声。

“……认真起来是很好没错，但我们不知道葛林姆洛克的长相耶。”

“是啊，所以一开始我想把修密特带来，不过看他那样子也没办法……不过我勉强隔着斗篷，
近距离看过那个像是葛林姆洛克的玩家。如果发现身高体格很像的家伙突然现身的话，虽然
有点乱来，但可以用决斗申请来进行确认。”

“诶。”

听到这，亚丝娜睁大双眼，提高了些音量。

SAO中，只要视线聚焦到其他的玩家身上，就会出现绿色或者橙色的情报窗
口——“Color-Cursor”。不过，对于初次见面的人，只会显示HP条，名字跟等级都是看不到
的。

想当然这些都是预防种种犯罪所采取的措施。假如单方面被其他人知道名字的话，可能就会
收到恶意运用Instant-Message发来的骚扰信息，如果等级很简单就能被他人获知的话，等
级较低的玩家在街区被当做猎物并被跟踪，在怪点区遭受到抢劫-恐吓等一系列的事件就会
很容易发生。

不过就是因为无法看到他人的名字，像这回的找人就变得稍许有些麻烦了。

要知道初次见面的玩家名字就我所知只有一个方法。那就是一对一决斗，换而言之就是提出
决斗申请。

在主窗口点击决斗按键，在选择模式中用手指选定对象的Color-Cursor，在我的视野中便回
出现“已向某人申请发1vs1的决斗”的信息。再次看去，就能知道对手的正式英文版名字了。

不过，同一时间对手的视野中也会出现从我这里发出的决斗申请信息。因此无法在不暴露自
身的前提下查出对方的名字，而且在这之前这种行为也完全没有礼貌可言，这么一来对手马
上拔出武器接受挑战也是很有可能的。听完我的话，亚丝娜张开嘴像是要说出什么——恐怕是
“很危险啊”的这层意思的话语吧。

不过，亚丝娜很快又闭上了嘴，表情严肃的点了点头。大概是理解到没有其他方法了吧，紧
接着说出的话是——

“……但是，要和葛林姆洛克谈话时，我也要一起去。”

被她这样一说之后，我也只能把让她留在房间内等待的这话应声咽了回去。

我只得犹豫地点点头，顺便确认一下时间。下午六点四十分，差不多是玩家们回到各个街区
吃晚餐，并开始热闹起来的时间了。问题酒馆，虽然外观很普通，但Swing-Door却依然频繁
地摇动着。不过仍旧没有发现身高-体格与烙在我眼皮内的斗篷人影一致的玩家出现。

我们已经只能赌在这作为最后一条线索的店面上了，但还有一点我们不能无视的不安材料存
在。在五十七层的旅馆中，修密特呻吟而出的话“屋顶上的黑斗篷，不是葛林姆洛克。葛林
姆洛克是更高一点的”——虽然我怀疑这可能是修密特因过度恐惧而造成的判断错误，可是如
果这是事实的话，这种监视完全就是无用功，根本不会找到的。

只是望着这具有隐藏名店氛围的酒馆Swing-Door一晚上，却无法品尝料理的味道…………

就在我想着这些事时，不由得捂住了自己的胃。

随后，眼前突然伸过来一样东西。是用白纸包裹的，释放出浓郁香气的东西。我目不转睛地
看着这包东西，亚丝娜则依然盯着酒馆的方向，简短的说了句“给你”。我则是发射性做了
番确认。

“……给，给我的吗？”

“这个状况下还能给谁啊。难不成你以为我在炫耀吗？”

“没，没有，我错了。那我就收下了。”

缩起脖子，用很快的速度接下纸包。往亚丝娜处偷偷瞄去，发现她依旧继续着监视工作，同
时很灵巧地将另一包相同的物品实体化。

我高高兴兴得把纸拨开，里面装的是大份长条三明治。我呆呆的看了烘烤适中的面包内，夹
着蔬菜与烤肉一会儿，亚丝娜用冷静的声音再次说道：

“耐久度差不多要到了，会消失的哟，最好赶快吃掉。”

“咦，啊，好的，我开动了！”

听到快消失了，那可没时间发呆。食品道具的耐久度，除非使用特殊的食材要不然都是很低
的，正准备品尝的便当在手中消失的这种情况，到现在我已经体验了好几次了。唯一的方法，
只有将其放入大师级细工师才有可能制作出的“永存保存盒”中，放到此盒内的食物就算摆
到怪区也永远不会消失掉，可惜的就是这个小篮子只能放进两颗坚果。

因此，我用最快的速度张开大口，咬了一口长条三明治，暂时沉浸在那咀嚼带来的口感中。
味道简单，略带一点刺激，让人不断地咬下。食物的耐久值是不会影响味道的，只要食物还
存在，味道就不会有任何变化。

视线固定在酒馆的入口，一口气把大份的三明治给吃完，我发出满足的叹息声。望了望一下
身旁正优雅地咀嚼食物的亚丝娜，表示谢意并顺便问道：

“多谢招待，话说回来，你什么时候去买的便当啊？刚刚经过的路边摊，可没有卖这么好的
料理哦？”

“刚刚不是说耐久值快没了吗，就是想到有这种事，我从早上就准备好了。”

“诶……真不愧是KoB的攻略负责人呢。我完全都没想到吃饭的事情……对了，这是哪家店
的？”

烘烤适中的面包，夹着蔬菜与烤肉的三明治这在我的名店列表中，也是相当高排名的味道，
接下来一段时间，攻略的时候就都吃这个吧，我想着这些，所以才特意问问看。不过亚丝娜
却微微耸了耸肩，做出了一番让我十分意外的回答。

“没有卖的。”

“诶？”

“不是店里卖的。”

为什么在这里沉默下来，什么都不说了呢，我歪着头想了一会儿方法才恍然大悟。既然不是
在NPC店买的话，那就是自己做的了，也就是这位KoB副团长做的。

我发呆了大概十秒后，才发现一小小危机来临了，糟了得要说什么才行啊。早上全力忽视掉
了亚丝娜的装扮已经很失态了，不能重蹈覆辙啊。

“诶……那个，要怎么说才好呢……呃，就这样一下就吃完，感觉真浪费啊。对了，干脆拿
到阿尔盖特的市场去拍卖，一定可以赚很多的啊哈哈哈。”

咔嚓！亚丝娜用白皮靴用力踢了下椅子，让我猛地挺直了背，并颤抖起来。

充满紧张感的数分钟过去后，吃完自己那份的亚丝娜小声地说：

“……没来呢。”

“诶，嗯，嗯。对呀，不过根据修密特的话，也不是每晚都会来的样子。而且那个黑斗篷是
葛林姆洛克的话，刚PK完应该也没那个吃饭的心情……要有等上个两三天的心理准备了。”

快速的说完後，我站起来再次确认一下时间。从监视开始到现在只有三十分钟。但我已经有
直到发现葛林姆洛克为止，不管要待多久都没关系的觉悟，不过副团长大人是怎么想的呢。

我想着这些，把视线投向她那儿，发现亚丝娜深深地靠在椅子上，没有要起身的意思。

……难不成我刚刚说的话，被理解成了“两三天都住在这里”的意思？在我想到这里，手掌
冒出汗时，亚丝娜再次低声说道。

“我说，桐人君。”

“是……是的！”

接下来说的话，幸好——或是说可惜的是，跟我刚刚想的完全没无关。

“你的话会如何？如果你是黄金苹果的成员，打到超稀有物品的时候，会说什么？”

“………………………………”

我呆了一下，沉思了数秒，说：

“……说的也是呢，本来我就是讨厌这类麻烦，才一直都单打独斗的……我在SAO前玩的那
些MMO游戏中，也有曾经历过因他人藏匿稀有物品，或是私吞卖出所得等行径，而导致公会
分崩离析……”

MMO玩家的动机，刨根究底，大部分都是为了获得优越感，这点我也无法否定。而得到优越
感最简单的方法，就是“强大”。用锻炼出来的能力值，再加上强力的稀有装备将怪兽，或
者是其他玩家击败。这份快感，说极端点就是只有网游上才能体验的到。现在的我，会长时
间持续练级的理由之一，毫无疑问，也是因被人称为“攻略组”并被他人敬畏着的快感。

假如我是在某个公会中，在团队作战中打出性能十分优越的装备道具——而且在公会中，有适
合装备这物品的人在的话，我有办法说出“这应该给你用”这种话吗？

“…………大概没办法吧。”

低声说出这番话，我再次左右摇摇头。

“我想自己装备，这种话也讲不出来，也不会成为笑着让其让给公会其他成员的圣人。所
以……如果我是黄金苹果的成员，果然也会加入到卖出派当中吧，亚丝娜呢？”

被这么问道后，她毫不犹豫的回答道。

“归打到的人所有。”

“诶？”

“KoB【我们】是用这样的规定，如果是组队战斗，打到随机掉落物的话，全都是属于捡到
的那个人。毕竟SAO没有战斗纪录，谁拿到什么，全部都只能自我申报。所谓为了避免藏匿
带来的麻烦，就只能用这方法了，再加上……”

在这里她停顿一下，视线盯着酒馆的入口，眼神稍微和缓下来。

“……正因为是采用这样的系统，这个世界的‘结婚’才有价值呢。结婚的话，两人的道具
储物栏就会共同化了，不是吗？至今为止只要想藏就可以藏起来的东西，只要一结婚，就什
么都无法隐藏了。反过来说，只要有一次藏过稀有掉落物，这人就没办法和公会中的谁结婚。
‘储物栏共同化’，虽然是非常实用的系统，但也很浪漫哦。”

她说出这话的语气，让我感觉像是带着些憧憬的色彩。不禁眨了眨眼。而就是这突然出现意
义不明的紧张感，又让我将完全没有过脑的话说了出来。

“对，对了，就是这样啊。那，那，如果我跟亚丝娜你组队战斗的话，有什么掉落物我绝对
会说的哟。”

铿啷！这是亚丝娜连同椅子整个向后退去。

房间并未开灯，因此没办法看到其脸色，在青白色的光照下仅仅几秒钟亚丝娜的表情就更换
了许多次，随后“闪光”举起右手大叫道。

“你……你是笨蛋吗！这种日子，等十年都不会有的！啊，我，我是说和你组队的事情哟。
我说，你，你是认真的在监视入口吗！看丢的话怎么办！”

嘎——突然发出一阵怒吼，亚丝娜猛地把脸往后转去。就算在谈话中，一秒都没把视线离开酒
馆的我多少有点受伤，用可怜的声音反驳道“有在看呀”，并突然想到一件事。

成为公会黄金苹果崩坏的原因的那枚戒指。在打出来之后，最开始，是落入了谁的储物栏的
呢？

现在这事可能没什么大不了了。不过比起把会长杀掉再夺过来，一开始就藏起来要简单多了。
也就是自己说出掉落物品的玩家，才是唯一一个没可能杀害会长的人。

关於这件事，应该也要向修密特询问才对，我皱了皱眉。我和亚丝娜都没把他登录进好友名
单，因此也没办法发送信息进行确认。虽然只知道玩家的名字可以不用好友信息，而是使用
Instant-Message，但这个不在同一层就无法发送，而且还有字数的限制。

这件事等到下一次和修密特见面时再问应该也不迟。我们追查的毕竟不是以前的“戒指事
件”而是现在正处在进行时之中“圈内杀人事件”。想到这里，我还是不死心地拿出修密特
写的东西。

在拜托依旧摆出一副微妙神情的亚丝娜“请你注意一下店门口一会儿”后，我开始确认起写
在羊皮纸上的黄金苹果成员名一览表。

葛林瑟鲁妲，葛林姆洛克，修密特，优尔可，凯因兹……用字迹潦草的字母排列出来的八个
名字。这其中至少有三人，都已从浮游城消失了。

不能再出现牺牲者了。一定要制止葛林姆洛克的复仇，发现圈内杀人的机关。绝对要。

我把这些铭刻进心，将便条收回储物栏。

但是，在小张的羊皮纸，在将要变换成一行系统物品名前——

我的视线，被其上的一点吸引了。

“……………诶……？”

低声嘟囔道，我慌忙把脸贴近。让细节专注系统【Detail Focus System】发挥作用，使羊
皮纸上文字的解析度得以增加。

“……这，这是怎么一回事…………”

听到我自言自语，依旧盯着酒馆的亚丝娜低声地向我问道。

“怎么了？”

不过，我已毫无回答的空闲了。脑子全速运转，思考着我刚刚看到的东西的意义，以及理由，
并推测其中的意图。

——数秒后。

“……啊……啊啊…………！！”

大叫道，我猛地站起身。握在右手的羊皮纸，也因冲击过大而剧烈的震动起来。

“这样啊……原来是这样啊！！”

听到我像喘息般说出的这番话，亚丝娜用掺杂着等量迷惑与着急，还有焦躁的声音说道：

“什么呀，你到底发现什么了！？”

“我……我们……”

沙哑的声音从喉中压抑着发出，我紧紧闭起双眼。

“……我们什么都没看到。虽然觉得有看到，但只是看到错误的东西。‘圈内杀人’……将
其实现的武器或是技能，从一开始就不存在！！”
*** 第9节
这是我后来听说的。

身居公会圣龙连合的重装盾战士部队队长要职的攻略组玩家修密特，就算回到熟悉的公会本
部房间，即便是睡觉的时候，依旧没有解除重装铠甲的打算。

其房间在石造的城池——不如说是城寨的最深处，连一扇窗户都没有。事实上，公会据点是除
了成员以外都没办法进入，只要待在房间中就很安全。虽然这么说给自己听，但视线却怎么
都没法离开门把手。

当视线一离开的瞬间，会不会门把就无声的转动了呢？而从那里像影子般潜入的身披斗篷的
死神，会不会就在毫无察觉的情况下站到自己的身后呢？

周围的人都觉得是胆大的肉盾战士【tank】，实际上将修密特推上攻略组高位的原动力就只
是“对死亡的恐惧”而已。

这个死亡游戏开始的一年半前的某天，他站在初始之街的中央广场拼命思考着。不，是迷茫
着。究竟怎么做才不会死掉。最确实的做法是，留在初始之街里一步也不走出去。所有的主
街区都有着“犯罪禁止程序”的完全保护。只要留在里面，数值化了的生命——HP就一滴也不
会减少。

但是，在现实世界里既是网络玩家又是运动员的修密特深知。规则是个经常会改变的东西。
“市街是安全区域”这个SAO的规则会永远——持续到游戏被攻略那天，可以这样断言么？假
如有一天街区不再是“圈内”，或者是从所有的大门处如雪崩般涌进大量怪物的话。一步也
没离开过初始之街，一丝经验都没赚过的玩家除了不知所措地乱转外什么办法都没有。

果然，要在艾恩葛朗特活下去，就必须变强。而且是要安全地变强。在不冒任何风险的情况
下。

花了几乎一整天思考，修密特最终的选择是“让自己变得坚硬”起来。

首先去武器店，购买了金钱允许范围内的最坚硬的铠甲和盾，剩下的钱则用来购买长武器。
接着在北门募集队员的众多的队伍中，选择了最注重安全的一队。最初的狩猎是SAO内最弱
的怪兽小型野猪，十人采用围攻的阵型将其击杀。

修密特从此，通过时间来弥补经验极低的狩猎，并不断升级。正因为升级效率，虽然远不及
以小团队或者独自挑战高风险怪兽的封弊者一行人，还有那对“坚硬”无止境的执着，使他
最终成为攻略组最强的公会“圣龙联合”的队长。

拜努力之赐，现在的修密特，不论是HP，装备的防御力，以及锻链起来的防御技能等等，都
已经可说是到达艾恩葛朗特最坚固的水准了。

右手持巨大的GuardLance，左手握着塔盾摆出架势的话，就算从正面攻来三只同等级的怪物，
他还是有能撑三十分钟的自信。以修密特的观点来看，穿着像纸一样的皮甲，使用完全攻击
性取向的武器跟技能的DamageDeale——比如是数十分钟前刚见面，一身黑的独行玩家那样——
唉，只觉得那种人脑袋是不是有问题。事实上，在所有角色构成类型来看，死亡率最低的，
应该就是全身硬邦邦的肉盾战士。当然，对于那些欠缺攻击力的大型团队来说，其加入更是
必要的。

原本修密特的一身“最高等级的坚硬”就是想要抵消对“死亡的恐惧”而练就的。理应如此。

不过。

如今却出现了一位能让膨大的HP，铠甲的性能，防御技能，也就是系统上的所有守护手段都
无效化的杀人者。再加上这家伙，还很明确地盯上了自己。

幽灵——之类的，自己真的不相信。

不，这点已经没有确信了。如今，就连“防犯规则”这种绝对法则都变成黑雾穿越而过，并
用小小的一杆枪与一把匕首便能轻巧地夺取他人姓名的死神。那不正是NervGear将“她”被
杀时的怨念，写进服务器，并转生而成的电子幽灵吗？

如果真是这样，那坚固的城墙，厚重的门锁，还有公会据点的不可侵效力，全部都会没用的。

会来的。绝对就在今晚，趁我睡着时下手。用第三把带有逆棘的武器刺向我，夺走我的生命。

坐在床上，用带着银色长手套的双手抱着头，修密特拼命思考起来。

为了从她的复仇当中逃脱，已经，只剩下一条路了。

请求宽恕。跪在地上，额头贴在地面进行谢罪，让它的愤怒消散。自己的罪行——半年前，为
了变强，不，为了变得更加坚硬，而想要出走到上位的公会里所犯下的唯一一项罪状说出来，
再真心的忏悔。只要这么做，就算对方是真正的幽灵，也应该会饶恕我的。我只是一时鬼迷
心窍。被对方的话所蛊惑，内心着了魔，才犯下的些许细微的罪行——不对，那并不能称之为
犯罪，而只是些不礼貌行为。只是没想到，结果会产生那样的悲剧。

修密特摇摇晃晃的站起来，打开储物栏，从山一样多的，紧急时刻才会使用的转移结晶中拿
出一个，并实体化。用使不上力气的右手握紧，深呼吸，用沙哑的声音低声说道。

“转移……‘拉贝尔克【ラーベルグ】’。”

视界被青色的光所覆盖，等到光线变薄时，已经是独自站在夜晚当中了。

时间已经过二十二点，而且这里是已攻略层，十九层的转移门广场几乎没有其他的玩家。周
围的商铺都拉下铁门，就连在外行走的NPC都没有了，一股这并不是圈内而是站在怪区的错
觉袭来。

直到半年前，“黄金苹果”还在这村子的一角，有着个小小的公会据点，明明应是已很熟悉
的光景，不过修密特感到整个村子就像是在抗拒自己一般。

厚重的铠甲下的身体颤抖起来，让发蔫一样的双脚勉强向前移动，修密特往村外走去。

目的地是在走出主街区后约二十分钟路程的小山丘上。当然这里已经是“圈外”，防犯规则
已经不适用了。但修密特有着不得不来到这里的理由。为了让那个黑衣的死神放过自己，除
了这样，已经别无他法了。

像拖着腿登上小丘顶部，修密特远望着在杂乱的矮木丛下的立起来的一样东西，身体激烈的
颤抖起来。

那是已经风化，长苔的石制墓碑。“黄金苹果”会长，已经死亡的女剑士葛林瑟鲁妲之墓。
不知从何洒下的朦胧月光，将十字影刻印在地面上。偶尔吹过的夜风，把枯木给吹的沙沙作
响。

原本这里的树跟墓碑只是普通的地形物体。设计师毫无意图随手摆设的风景般的装饰。但在
葛林瑟鲁妲被杀害数日后，黄金苹果解散的那天，余下的七人决定把这当成她的坟墓，并把
她的长剑给埋了起来——正确来说应该是放在墓碑的下面，让它的耐久度减少自然消失掉。

所以墓碑上并没有碑铭。但如果要跟葛林瑟鲁妲谢罪，就只有这个地方了。

修密特无力的跪下，连滚带爬地来到了墓碑前。

额头抵在混杂砂石的地面上，牙齿咬不住的颤抖几下之后，竭尽所能张开了口。出乎意外地
用很清楚的声音说：

“对不起……是我不好……原谅我吧，葛林瑟鲁妲！我……我，也没想到事情会变成那
样……要把你杀掉这种事，我一点都没想过啊！！”

“真的吗……？”

传出了声音。带着奇妙的回音，像从地底发出的女声。

拼死的忍住没让意识远去，修密特畏畏缩缩地把视线往上抬。

在蜿蜒的树干阴影处，悄无声息地出现了一黑衣的身影。漆黑的全身斗篷。衣袖垂下。在黑
夜之底，完全看不到斗篷内。

不过修密特却强烈地感受到了从那里头放射出来寒冷视线。用双手紧紧捂住快发出悲鸣的嘴，
急忙的点了好几次头。

“真……是真的，我什么都不知道。我只……只是依照吩咐，稍微……真的只是稍微……”

“你做了什么……？对我，做了什么，修密特……？”

慢慢的，修密特用睁大的双眼，看见长袍的右袖伸出一条细长的黑线。

是剑，但十分得细。是几乎没人使用的单手用的，近距离贯通武器“Estoc”【エストック】。
宛如大型针似地的刀身圆截面上，像是描绘出螺旋似地长有些许细微的荆棘。

第三把，“逆棘的武器”。

咿咿咿，从喉咙深处发出细微的悲鸣，修密特不知多少次，多少次地把额头磕到地面。

“我……我只是……在决定要卖掉戒指的那天，发现了不知何时放到我口袋内的便条纸跟结
晶……上面有着指示………………”

“是谁，修密特？”

这次是男人的声音。

“是谁的指示……？”

僵硬的脖子再次紧缩，修密特如同冻住了一般。

硬是抬起那如同钢铁般沉重的头，瞥了一眼过去。差不多也在树的阴影处，第二位死神现身
了。穿着几乎一样，黑色的全身斗篷。只是身高比第一位稍微高了些。

“……葛林姆洛克……？”

再次低下头，修密特用不成声的声音呻吟道。

“你也……你也死了吗………………？”

死神并没有回答，而是踏出无声的一步。从斗篷帽下，发出阴惨歪曲的声音。

“是谁……指示你的到底是谁……？”

“不……不知道！是真的！！”

修密特急转声调喊道。

“便条……便条只写了，跟在会长身后……等她住进旅馆后，去吃饭离开房间时，偷偷把回
廊结晶的位置定在其内后，再，再把结晶放进公会共用储物栏内，就只有写了这些而已……
我，我也只做了这些！我连葛林姆瑟鲁妲的一根手指都没碰！没……没想到那人不仅偷走了
戒指，还把她杀了……我，我也没想到会这样啊！”

就算在修密特拼命辩解时，两名死神却丝毫不动。夜风吹过，让枯梢和长袍衣摆给拂动起来。

恐怖感逐渐上升并逼近限界的修密特脑中，瞬间闪过一阵回想。

半年前的那天。从腰袋中取出羊皮纸，看到的瞬间，真是胡来啊，感到十分吃惊。并同时对
这巧妙的手法十分惊讶。

旅馆的房间平常是会自动上锁的，除了睡觉外，一般都是设定成友人/公会成员可开启的状
态。利用这点，就可将回廊结晶的传送位置设定在房间中，趁房间的主人熟睡时侵入。接着
只要使用交易功能，把对方的手拉到戒指交易确认钮上按下就行了。

虽然有着不小的被发现风险，但修密特直觉到这也是在圈内唯一可以夺走道具的方法。便条
最后写的报酬是卖掉戒指的一半金额。成功的话，可以一口气得到四倍的金额，如果失败——
交易中会长醒来的话，被看到脸的也只有写下这边跳的人，也就是盗窃实施犯。就算这家伙
在这之后再说些什么，要坚持不知道这件事情就行了。只是潜入房间内设定传送点的话，证
据什么的完全不会留下。

修密特虽很迷惘，但这份迷惘就等于背叛了公会和会长。全部都是为了能马上进入攻略组。
在那里只要贡献力量帮助游戏通关，间接来说也算是帮了会长，修密特用这样的想法将自身
的行为正当化，于是便照指示上所写的去做了。

第二天晚上，修密特知晓了会长被杀害的消息。又过了一天，他在自己的床上发现了装有约
定金额的皮袋。

“我……很，很害怕呀！如果把那个便条的事告诉伙伴的话，这次会换成我被盯上……所，
所以，我真的不知道，写下便条的人到底是谁！！原，原谅我吧葛林瑟鲁妲，葛林姆洛克！
我，真，真的没想过要当杀手的帮凶啊。请相信我啊，拜托…………！”

修密特不断的把额头抵在地上，发出混杂着尖细悲鸣声的话语。

突然一阵夜风袭过，树梢发出轧轧的声响。

等到声音平息下来时，到目前为止阴惨的回音就像骗人似地完全消失了，失去了阴阴回音女
性声，静静地响起。

“全部录音下来了哟，修密特。”

听过——这是最近才刚听过的声音。修密特胆怯的抬起脸，惊愕地瞪大了双眼。

摘下漆黑的斗篷，里面出现的是，就在几小时前，的确是被长袍死神杀死的被害者的脸。波
浪状的暗蓝色头发，随风飘摆。

“……优尔可……？”

用不成声的语调轻轻说道的修密特紧接着看向优尔可身旁，也露出真实面貌的死神，差不多
快要昏死过去，并低声地说：

“…………凯因兹。”
*** 第10节
“还，还活着是指……！？”

对于惊愕而叫道的亚丝娜，我缓慢地点了点头。

“嗯，还活着。优尔可小姐，当然凯因兹先生也是。”

“但，但是…………但是。”

重复几次浅呼吸后，亚丝娜把放在膝盖上的双手紧握在一起，用沙哑的音调反驳道。

“但是……我们昨晚不是的确看到了吗，被枪贯穿，挂在窗户下面的凯因兹先生……死亡的
时候。”

“不对。”

我一度大大的摇了摇头。

“我们看到的是凯因兹的虚拟体，还有大量多边形碎片洒遍一地，放出青光并消失的场景而
已。”

“所，所以说，这不就是这个世界的‘死亡’吗？”

“……还记得吗？昨天，挂在教会窗户下的凯因兹，一直凝视着空中的一点。”

我伸出右手食指摆在眼前，这么说道。亚丝娜略微点了点头。

“那是看HP条吧？看着因贯通持续伤害，而徐徐减少HP……”

“我也是这么想的，不过并不是这样，他真正看的不是HP条，而是自己装备上的全身版甲的
耐久值。”

“耐、耐久值？”

“恩，今天早上我在实验於圈内的贯通伤害的时候，不是把左手的手套拿掉吗？圈内的话，
玩家不论作什么，HP都绝对不会减少，不过物品的耐久值会减少……就像刚刚吃的口袋饼那
样。当然装备的耐久值不会像食物那样的自然减少，但这也只限于没受到伤害的场合。听好
了，那个时候，凯因兹的铠甲是被枪插着，枪所减少的，不是凯因兹的HP，而是铠甲的耐久
值。”

说到这里时，一直皱眉的亚丝娜也瞪大了眼。

“那，那……那个时候碎裂开来的不是凯因兹先生的肉体……”

“没错，而是他穿的铠甲，我本来就觉得很奇怪了，只是吃个饭，为什麽要穿那么厚重的铠
甲……那是为了让爆散时，看起来很显眼才穿的，看准铠甲坏掉的瞬间，凯因兹就……”

“用结晶传送走吧。”

亚丝娜闭上眼在脑中回想着那个画面，说道。

“这个结果产生的就是‘放出青光的多面体破碎，飞散，玩家死亡的现象’……也就是跟死
亡特效非常像，但实际上是完全不同的东西。”

“嗯，恐怕凯因兹采取的行动，是先在圈外拿枪，连铠甲一起刺进扎进胸口，再用回廊结晶
移回教会的二楼，随后把脖子挂在绳子上，待铠甲破坏的前一刻从窗户跳下，趁着铠甲破坏
时使用转移结晶进行传送……大概是这样吧。”

“…………原来如此啊……”

缓慢且用力地点了点头，亚丝娜闭着眼睛呼出了一大口气。

“……那么，优尔可的‘消灭’也是用同样的伎俩呢……对吗………………还活着
呢…………”

亚丝娜并没发出声音，只是动了动嘴嘟囔出“太好了”，不过很快又咬紧嘴唇。

“但，但是，的确她是穿的满厚的，不过丢掷匕首是什么时候刺中她的？圈内的话应该会被
程序阻隔，身体应该连都碰不到才对啊。”

“从一开始就刺在身上了。”

我立刻做出回答。

“仔细回想看看，我和你，修密特从进入房间的时候开始，她一次都没让我们看见背后。她
在刚收到我们的讯息时，就跑到圈外把匕首插进自己背上，然后再回到旅馆内。以那种发型，
只要好好的坐在沙发上，就能完全隐藏起很小的匕首柄，然后只要注意服装的耐久度，一边
跟我们谈话，等时机差不多了就往后退走到窗前，用脚踢墙壁还是什么方法制造出声音，再
把背部往我们这边转过来，这样看起来就像匕首在那一瞬间被刺进身体一样。”

“随后自己再从窗子向外掉落……这是为了不让我们听见唱出转移指令声音吧……所以说，
桐人君你追逐的黑长袍是……”

“十有八九，那不是葛林姆洛克。而是凯因兹。”

我这么做出断定，亚丝娜则将视线移往空中，短暂的叹了口气。

“别说是犯人了，根本就是被害者呀……咦，等等。”

皱着眉头，身体往我这边靠近。

“我们昨晚不是还特地去黑铁宫的‘生命之碑’确认吗，凯因兹的名字，确实被刻上横线，
死亡时刻也一样，死因也的确是‘贯通属性攻击’。”

“你还记得，那个‘凯因兹’的名字拼法吗？”

“嗯……应该是 K，a，i，n，s 这样吧。”

“嗯，优尔可的确是那样说，我们的头脑就这样相信了。不过……你看这个。”

我把成为推理线索关键的羊皮纸片递给亚丝娜。那时数小时前，修密特写下的“黄金苹果”
成员一览表。

伸手接下的亚丝娜，在看了纸片一眼后，“诶——”的大叫一声。

“‘Caynz’……！？这是‘凯因兹’的真正拼法！？”

“如果只有一个字母就算了，但三个字母都出错的话，就应该不是修密特的记忆出错。而是
优尔可故意告诉我们错误的拼法。为了让K开头的凯因兹的死亡表记，误认为C开头的凯因
兹。”

“咦……那，那……”

亚丝娜的表情变得僵硬起来，语调也低了下来。

“那时候……我们目击到C的凯因兹的伪装死亡，同时艾恩葛朗特的某个地方，那个K打头的
凯因兹却死在贯通伤害下？应该……不是偶然呢……？难道…………”

“不是不是。”

我轻轻的笑着，大大的挥动右手。

“并不是优尔可的共犯，算准时机杀害K的那位。听好了哦，生命之碑的死亡表记是像这样
‘樱花之月二十二日 十八时二十七分’……而在艾恩葛朗特，樱花之月，也就是四月二十
二日，昨天是第二次出现了。”

“啊………………”

亚丝娜顿时说不出话，随后脸上浮现出无力的笑容。

“………………竟然是这样呀，我完全没考虑到是这样呢。是去年啊。去年的同样日期同样
时间，K打头的那位凯因兹，跟这件事毫无关系的死去了呢……”

“对，大概这就是计划的出发点。”

我再度做了次深呼吸，边整理脑中的思绪边继续说：

“……优尔可跟凯因兹，应该很早以前就知道这位读音相同但拼法不同的‘凯因兹’在去年
四月死亡了吧。最开始可能只是闲谈程度吧。只是后来可能发现，只要好好利用这个偶然，
就可以伪装出凯因兹的死亡，而且还不是普通的对怪物的战斗死亡……而是可以演出‘圈内
杀人’这种可怕的手法。”

“……的确，我跟你都完全被骗倒了。读音相同的他人死亡标记，借由贯通伤害让装备在圈
内装被破坏，加上结晶转移……把这三种手法加起来，就可以让圈内PK看起来无限接近于真
实……而这么作的目的是……”

亚丝娜用轻轻的声音继续说道。

“逼迫‘戒指事件’的犯人现身，将自己被怀疑为犯人的立场反过来利用，优尔可跟凯因兹
一起演出这场杀人事件，制造出虚幻的‘复仇者’。可以无视犯罪禁止程序，于圈内进行PK
的恐惧死神……结果，被恐怖驱使而有所行动的是……”

“修密特。”

我点点头，用手指碰了碰下巴。

“大概，最初只是有某种程度的怀疑而已。……修密特是从中坚级别的公会‘黄金苹果’，
突然能加入攻略组而且是最大的圣龙联合。这果然是很特殊的例子呢。没有超快的等级上升，
或是大幅的装备更新速度……应该是不可能的。”

“特别是DDA的加入条件又很严苛呢……那这么一说，他果然就是戒指事件的犯人吗……？
是那个人杀害葛林瑟鲁妲，夺走戒指的吗……？”

作为攻略组的作战参谋曾看次见过修密特的亚丝娜，目光有些紧张，直直的看着我。

我的脑内浮现出那个枪使的身影，同时缓缓的摇了摇头。

“……无法判断。虽然有可供怀疑的材料……但说到那家伙有没有‘红名者’的气息……”

SAO中的杀人者，也就是红名玩家，身上多少都会有特异的氛围。这也可说是理所当然的。
因为在这里杀死玩家，也等同于是妨害游戏攻略的行为，极端一些来说也就是红名玩家们是
有着‘从这里出不去也没关系’的想法的人——用积极点的说法就是有‘这个死亡游戏能永远
持续下去就好了’的愿望的人。

这种负面的愿望，不管如何都一定会表现在言行上，但是从心底害怕着黑衣死神，拜托我们
护卫到工会本部的修密特，我并没有在他身上感到这种‘红名’的疯狂气息。

“…………没办法确定。但绝对脱不开关系，这点可以充分说明……”

听完我的话，亚丝娜也表示赞同似的点了点头。背靠在并排摆放在窗边的两张椅子的椅背上，
就像忘记了对面的酒馆似的将视线投向街道上空。

“…………不管怎么说，修密特现在，已经被逼得走投无路了。他坚信有复仇者存在，认为
圈内……不，甚至连公会本部也变得极不安全了。接下来……他会采取什么行动呢。”

“如果有共犯存在，应该会联络那家伙吧。优尔可跟凯因兹大概就是看准了这点吧。但如果
修密特也不知道共犯者现今在哪的话，嗯——如果是我的话……”

会怎么做呢，输给一时的慾望跟愤怒的冲动而杀害玩家，并且还为此十分后悔，到底会做什
么呢？

到目前，我还没在这个世界夺走过玩家的性命。但是，却有因我而死的同伴。因为我的愚蠢
和丑陋的自我表现欲，让除了我以外的公会同伴们都丧命，这让我无时无刻都在后悔。我把
作为公会据点的某间旅馆的庭院中生长的小树当成他们的墓碑，虽然称不上是赎罪，但我时
常都会带着酒跟花前去。所以，修密特大概也——

“……如果有葛林瑟鲁妲的坟墓，他一定会去那里乞求原谅的。”

亚丝娜似乎也敏感察觉到我的声调变化，从椅子上方望着我，安稳的微笑道。

“没错呢，我也会这样做呢。在KoB的本部，也有着至今为止死在BOSS战中的人们的坟墓
呢。——对了，优尔可和凯因兹一定会在那里……葛林瑟鲁妲的墓那里。在那里，等待着修密
特的出现…………”

突然沉默下来，表情也变的有些阴沉。

“……？怎么了？”

“没什么……只是，稍微想到而已，如果葛林瑟鲁妲的坟墓在圈外呢？修密特如果去那地方
的话……优尔可跟凯因兹会就这样原谅他吗？虽然觉得不太可能，但说不定这次会实施真正
的复仇……？”

这预料之外的推论，瞬间我的背紧绷了起来

没办法说绝对不可能，花这么大工夫都要演出‘圈内杀人事件’的优尔可和凯因兹，也是对
戒指事件的犯人有着相当程度的憎恨才对。他们至少还使用了两颗转移结晶。考虑那两人的
等级，这应该是很庞大的费用吧。准备到这种地步，只是得到谢罪就会满足了吗……？

“啊……不对……原来是这样……”

但我在突然注意到一件事后，摇了摇头。

“不，不会的，那两人不会杀死修密特的。”

“为什么能这样断定？”

“因为亚丝娜还有把优尔可登记在好友名单上对吧？也没有看见对方那边把登录解除的讯息
吧？”

“阿……这么说来，也是呢，因为相信了在旅馆中发生的第二起杀人事件，我以为会自动解
除掉呢，但如果还活着的话，应该还会继续保持着登录才对。”

亚丝娜挥动左手，调出系统窗口，在迅速的操作之后，再次点头表示肯定。

“的确还登录着，如果早点发现这个的话，就可以察觉到事件的手法呢……但这么说，为什
么优尔可会接受好友的登录？很有可能从这里导致全计画的破绽哦？”

“大概是因为……”

我闭上眼，脑中这次描绘出的是拥有一头深蓝色发丝的女性身影。

“……是对欺骗我们的谢罪，以及相信我们的证明吧，就算注意到好友名单的登录，发现还
活着的事实，我们从这里也能推测出他们的真正意图，进而不会妨碍他们引诱出修密特的事
情。亚丝娜，追踪优尔可的位置看看。”

我睁开眼这么说道，亚丝娜点了点头，再次点击窗口。

“……现在，位置是在第十九层的圈外区域，稍微离开主街区的小丘上……那这里就是……”

“黄金苹果的会长，葛林瑟鲁妲的墓地吧。凯因兹跟修密特应该都在那。如果修密特死在那
地方，我们也知道是优尔可他们下的手。所以大概不会杀掉他吧。”

“那……反过来呢？被发现跟戒指事件有关的修密特，为了封口而杀害那两人……？”

对依旧有些担心的亚丝娜说出的话，我稍微想了一下，依然摇了摇头。

“不……这样的话也会被我们发现，更何况那个人，一定没办法承受变成犯罪者，不，杀人
者而被攻略组放逐的这件事，所以我想不用太担心他们会杀死对方……就交给他们吧，我们
在这次事件中的工作已经结束了，虽然被优尔可他们耍的团团转，但是……我也并不讨厌就
是哟。”

听到我这么一说，亚丝娜也考虑了一下，对我露出了肯定的微笑。

*

不过，我跟亚丝娜，在此时就连事件真相的一半都没看到。

这起事件，依旧没有结束。
*** 第11节
再来说说，这之后才听说的事。

*

修密特惊讶地几乎没法呼吸，交互地望着死神长袍下现身的两人的脸。

一直以为是葛林瑟鲁妲和葛林姆洛克的死神的真面目，没想到竟是优尔可跟凯因兹。不过，
这两人都应该都已死亡了的啊。凯因兹的死亡只是听到消息，但优尔可——就在几个小时前，
自己亲眼目睹了她的死亡——被从窗外射来的黑色匕首刺中，随后掉落到街道上，虚拟体爆碎
开来。

果然是幽灵吗，一瞬间差点昏过去，不过优尔可在露脸前说出的台词，勉强维系住了修密特
的意识。

“录……录音……？”

从喉咙内发出嘶哑的声音，优尔可从长袍里将手伸出，握着的是散发出淡绿色光泽的八面柱
型结晶。录音水晶。

幽灵，应该是不会使用道具来录音的。

也就是优尔可，和凯因兹的死都只是伪装而已。虽然想像不出是怎么做到的，但两人就是通
过上演了自身的“死亡”，创造出了根本不存在的复仇者，把真正应该遭到复仇的第三个人
逼上绝路。而记录下第三人告白自己的罪过，乞求原谅的声音。全部都是——为了揭发在遥远
的过去所发生的一件杀人事件而制定的计划。

“………原来……是这样啊………”

终于知晓真相的修密特，发出这不成声的自言自语。当场脱力的倒下。

他并没有因为被骗的团团转，连证据都被取得而怒气大发。而对优尔可和凯因兹的执念——也
就是深深仰慕葛林瑟鲁妲的感情，而感到惊叹而已。

“你们……对会长那么……”

对于这细弱的声音，凯因兹静静地做出了回答。

“你也是这样吧？”

“诶……？”

“你不也是，对会长一点恨意也没有，不是吗？就算有对戒指的执着，但还不至于对她产生
杀意，没错吧？”

“当……当然是这样，真的，相信我呀。”

修密特的表请扭曲，不断的点着头。

论战力而言，大概这两人加起来也没自己强吧。但，修密特完全没有浮现出当场拔出武器，
封住两人嘴的选项。首先是堕落成红名玩家的话，就再也无法在公会和攻略组待下去了。而
比这更重要的是，要是在这里把优尔可跟凯因兹杀害，自己就再也无法恢复正常了。修密特
对这一点有着确信。

所以修密特就算知道录音水晶仍旧启动着，还是反复说着过去所犯下的过错。

“我作的……只有潜入会长的房间，设定好传送门的出口而已。而因为……这件事得到的钱，
去买了高级的武器跟防具，我才能通过DDA的入团基准……”

“不知道是便条是谁写的，这是真的吗？”

听到优尔可严厉的问话，修密特再次激烈地点了点头。

“现，现在我还是不知道呀，十人的会员里面，去掉我跟你们，还有会长跟葛林姆洛克后的
剩下的三人里面才对……不过，在那之后我一次都没有连络过……你们也没有头绪吗？”

对于修密特的问题，优尔可也只轻轻地摇了摇头。

“那三个人，在公会解散后加入了一个和‘黄金苹果’差不多的中坚公会中，普通的生活着。
买入稀有装备或是玩家小屋的人一个也没有。突然跳级的只有你哦，修密特。”

“………………这样呀……”

修密特说道，把头低了下来。

葛林瑟鲁妲死的时候，送到房间的皮袋中，有着当时想都想不到的一大笔钱。在那之前都只
能流口水看着的，拍卖场内展出的超高性能装备，都能够一口气凑齐一身的程度。

如果要不花那笔钱，只放在储物栏中，那就只有钢铁的自制心了。不，在这之前——

抬起脸，修密特一瞬间忘记自己所在的困境，说出自己心中萌生的疑惑来。

“……但，但是，这太奇怪了呀……如果不用那笔钱，那为什么有要杀掉会长，都要夺取戒
指的必要呢……？”

被这出其不意的反问，优尔可跟凯因兹也的上身都稍微向后退了退。

艾恩葛朗特中，把赚来的钱放在储物栏中没什么好处。一块钱的价值，都是基于Cardinal
System的精密物品掉落率操作，时常保持恒定，通货膨胀或是紧缩都不会发生。即便购买了
高价的剑与铠甲，只要维护得当，在哪天不需要时也能卖得差不多的钱回来。因此不使用的
钱就毫无意义。也就是——

“那……那个便条的送出人是……”

拼命的思考後，修密特说出脑中朦胧浮现的一个推测

脑子拼命旋转思考，修密特将浮现出的模糊推测说了出来。

不过，由于太过于集中意识，注意到“那个”的时候已经太迟了。

“修………！”

就在眼前的优尔可发出尖细的叫声时，从背后伸望颈部的小型匕首，咚的，架在了胸部护甲
与喉部护甲的空隙处。是小型突刺武器专用技“穿甲【Armor Pearce】”与非金属防具专用
技“忍足【Sneaking】”的组合突然袭击——

一瞬间的惊愕后，用在最前线锻链出来的对应能力调整态势，修密特迅速的往后退去。就算
喉咙被切开，在这个世界也不会马上死亡。虽然是致命点，伤害会很大，但跟修密特庞大的
总HP量比仍旧很少。

不过。

在要转身的前一刻，两脚的感觉突然远去，修密特发出铿啷的声音，倒在了地上。HP条周边，
被绿色闪灭框围住。是麻痹状态。作为肉盾战士【Tank】耐毒技能应该也提升了一定的程度，
不过这却是个能够贯穿耐性的相当高级的毒。到底是谁——

“ONE DOWN！”

少年般天真无邪声音从上传了下来，修密特拼命的把视线往上移动。

首先看见的是装饰着像尖锐图钉的黑皮靴。同样是黑色的紧身皮裤。完全贴在身上的皮甲也
是黑色。右手拿着刀身泛绿的细长匕首，左手则插在口袋中。

而头上，则是戴着行囊【頭陀袋】般黑色的面具。只在眼睛部位开了圆形的小孔，意识到从
那投来的黏湿视线的同一时刻，修密特的视野中出现了玩家Cursor。并不是常见的绿色，而
是散发出鲜艳光泽的橘色。

“啊……！”

身后听到小小的悲鸣声，修密特将视线转了过去，看见的是一个体型矮小的玩家，正拿着把
极细的剑同时威吓住了优尔可跟凯因兹。他也是全身都是黑色，但素材却不是皮制，而是一
件衣衫褴褛的服装从上垂下。脸上戴着副骷髅模样的面具，暗暗的眼窝内隐隐散发出红光的
双眼。右手我着的是，和优尔可拿着的逆棘之剑虽同属Estoc类，但那自行放出血色光泽的
生金，却也说明了其压倒性的规格。Cursor的颜色也同样是橘色。

骷髅面具男伸出左手，从呆立在那里的优尔可右手上，轻而易举地将黑色的Estoc拔下。瞥
了一眼刀身，发出混杂有咻咻般摩擦声响的声音。

“设计，还不赖，嘛。就，加到，我的收藏，吧。”

这两人，修密特都认识。虽然没有直接看过。在公会本部的传阅的，被标定为尤要注意的玩
家名单最上方，刊载着他们的全身素描图。

某种意义上，是超越首领怪，攻略组最大的仇敌。杀人玩家【Red Player】。而他们就是在
其中最大最凶恶的公会，担任干部的男性玩家们。麻痹修密特的毒匕首使是“Johnny-Black
【乔尼-布莱克】”。牵制优尔可与凯因兹的针剑【Estoc】使是“赤眼的ZaZa”。

这么说来，难道——“那些家伙”也参与了吗。

骗人的吧。不要呀。这可不是开玩笑的。

就像是背叛修密特内心的惨叫似的，咔，咔，又有一靴子踩踏声传来

。

修密特战战兢兢将视线向后望去，用瞪大的双眼盯着那，能够体现出艾恩葛朗特最大级恐怖
的身影。

一直包覆到膝盖上，消光黑的雨披【poncho】。深深盖住眼睛的连头帽。

垂下的右手上握着的是，宛如中华菜刀似的四方型，以及如同血液般红黑色刀刃的大型厚重
匕首。

“…………‘PoH’…………”

修密特从嘴唇中发出这样一句话后，就像是看到了恐怖与绝望似的猛地颤抖起来。

*

杀人公会“微笑棺木【Laughing Coffin】”。

其公会成立是在名为SAO的死亡游戏开始的半年后。在那之前，他们只是从事用多人包围单
独或是少人数的玩家，强夺金钱或是道具的犯罪玩家中的一部分，由于思想过激从而演变而
成的激进集团。

这个思想也就是——“既然是死亡游戏那杀人也是想当然的”。

在现代日本是不可能被允许的“合法杀人”，但在这种极限情况下就变得可能了。因为全部
玩家的肉体在现实中是处于“完全潜行”的状态，也就是无意识状态，连一根手指都无法依
据意识活动。以日本的法律可及的范围来说，HP条归零就会把玩家给“杀死”的杀人装置
NervGear设计者茅场晶彦才是凶犯，而不是令HP减少的玩家。

——既然这样的话就杀吧，愉快的享受游戏吧。这是给予全玩家的权利。

——发表这剧毒般的言论，诱惑，洗脑了为数不少的橙名玩家，使得他们走向了发狂的PK道路，
就是拿着匕首的黑色雨披男，PoH。

*

跟这个充满幽默感的名字相反，这名散发出冰一般冷酷视线的高大男子，走近修密特简短地
命令了一句。

“翻过来。”

Johnny-Black马上就将脚的前端伸进修密特的腹下，将其身体翻了个面。看着脸朝上无力躺
着的修密特的脸，黑色菜刀男再度说道。

“Wow……的确呢，这家伙可是大猎物啊。这可不是DDA的领队大人吗？”

明明是极具张力的艳丽美声，但不知为何却有着深沉的异质感攀附其上。虽然看不见被斗篷
盖住的脸，但呈波浪状的饱满黑发垂在一旁，随着夜风飘摆起来。

认识到自己的绝望处境，修密特一半的思考都在重复着为什么，为何这类疑问词。

为什么这些家伙，会在现在这个地方出现。“Laughing Coffin”的三巨头，恐怖的象征同
时也是最高级的通缉者，不可能会毫无理由的在下层区域游荡才对。

也就是这三人，是知道修密特在这里才会来袭击的。

但这样完全说不通啊。对DDA的人也没说要去哪，也不可能是优尔可跟凯因兹泄漏情报。而
且他们两人，现在正被“赤眼的ZaZa”的Estoc威吓，脸上完全失去了血色。即便是单独行
动的修密特偶然被Laughing Coffin的成员发现，然后联络了PoH，那他们出现的速度也未免
太快了。

难不成是因为其他事，与这三人偶然在这一层相遇，这种万分之一的巨大不幸吗？还是说——
这个偶然，正是死去的葛林瑟鲁妲的的复仇呢……？

朝下看着像树干一样躺在那里，彷徨断断续续的思考中的修密特，PoH略为偏起了头。

“接着……It's show time，虽想这么做……但要怎么玩呢？”

“那个，用那个吧老大。”

Johnny-Black用高亢活泼的声音叫道。

“‘互相残杀，活下来的家伙就不杀’的游戏，但这三人的话，可能要稍微平衡一下强弱。”

“虽然这样说，但你上次不也把活下来的家伙给杀掉了。”

“啊，啊！现在说出来就玩不成游戏了啊老大！”

对这毫无紧张感，但充满惊悚的对话，渣渣只是举着Estoc咻咻地奸笑着。

事到如今，全身都被现实般的恐怖与绝望侵袭，修密特不自觉的闭上了双眼。

包裹全身的厚重金属铠甲，在不能活动的现在就只是些重重的石头。他们很快的停下这餐前
酒般的玩笑，渴求鲜血犬齿毕露吧。PoH所持的大型匕首“友切包丁”，是现今最高等级的
锻冶职人作成的最高级武器都比不上的怪物掉落物品，也就是“魔剑”。应该能够轻松贯穿
全副武装的修密特的装甲值。

——葛林瑟鲁妲，葛林姆洛克。

这如果就是你们的复仇，那我在这里死亡也是没办法的。

不过，为什么连优尔可跟凯因兹都要一起卷进去。为了抓出杀害你们的真犯人，耗费无数劳
力的他们。为什么。

就在修密特脑中被充满绝望色彩的思考所占据的时候。

紧贴在背的地面，传来微微的震动。

咚咚咚，咚咚咚这样有节奏感的震动，慢慢越来越大声，越来越明确

。很快耳朵就听到了那沉闷的声响。

PoH用尖锐的呼吸声警告两位部下。Johnny将毒匕首架好向后退去，ZaZa则是把Estoc更为贴
近了优尔可跟凯因兹的脖子。

拼命让不能动的脖子转动着，修密特的眼中看见的是从主街区的方向，沿一条直线接近着的
白色磷光。

小幅上下抖动的光，数秒后方才能认出那是仿佛溶于夜色之中的漆黑之马的蹄上所包覆的冷
炎。马背上同样也是一位全身漆黑的骑手。像是从冥府中出现的不死骑士的某人，正在荒野
中拖曳着白炎轨迹，用猛烈的速度疾奔而来。马蹄音转变为震耳欲聋的地动声，与高亢的马
叫声重合在一起。

不一会儿便到达小丘下的马匹，在经过数次跳跃后到达了顶部后，用后脚蹬地立了起来，鼻
腔猛地喷出燃烧着的白色气息。Johnny像被气势压倒似地后退了几步，接着，马上的骑手用
力拉了一下缰绳——直接从马背上摔了下来。

咚，摔到地面的同时发出“好痛！”这个抱怨声，并且音色十分熟悉。

边摸着腰边站起来的闯入者，握着巨大黑马的缰绳，往修密特看了一眼，接着又往优尔可和
凯因兹看去，发出毫无紧张感的声音。

“安全上垒呢，计程车钱从DDA那边出哟。”

艾恩葛朗特里，并没有骑乘动物之类的持有道具。不过一部分的街道或村子有NPC经营的厩
舍存在，在那里可以借到骑乘用的马，或是用来搬运储物栏放不下的大量道具的牛。但是要
乘坐的话，当然需要一定的技术，而且使用费贵得离谱，几乎没人会去借用。这个死亡游戏
之中，有闲心浪费时间到练习骑马这种事上的人，也是十分稀少的——

修密特把积在胸口的气息吐了出来，看着闯入者——攻略组独行玩家，“黑衣剑士”桐人的脸。

桐人把缰绳拉了一下，让马掉过头，同时拍了一下它的屁股。解除借用，迅速离去的黑马啼
声，跟有些欠缺魄力的声音重合了起来。

“哟，PoH，好久不见了呢，你又是这种怪异的打扮呀。”

“……我可不想被你这家伙说呢。”

PoH的回话声，包含着无法隐去的杀意。

紧接着踏出一步的Johnny-Black，明显提高了声调叫道。

“你这浑蛋……！很悠哉嘛！你搞清楚状况啊！”

用左手制住挥动匕首的部下，PoH把右手的切肉菜刀刀背顶在肩头，敲了敲。

“就和跟这家伙讲的一样，桐人，帅气的登场是很不错，但就算是你，有办法一人同时跟我
们三人对抗吗？”

依旧麻痹着的修密特用全身唯一可以动的下颚，紧紧咬着左手。

状况就跟PoH讲的一样。就算是在攻略组中拥有顶尖战斗力的桐人，要同时打倒Laughing
Coffin的三名干部也是不可能的。为什么，至少也得带“闪光”来啊？

“嘛，是不可能。”

左手摆在腰上，桐人平淡的回答。但是很快又继续说道。

“不过我已经喝了耐毒药水，也带了很多回复结晶，应该可以撑十分钟吧。有这些的话，就
足以撑到援军到来了。在怎么说，你觉得仅靠三人能跟攻略组三十人对抗吗？”

被和刚才几乎一样台词给反驳了的PoH，在斗篷中轻轻的啧了一声。Johnny和ZaZa，则用有
些不安的视线张望起周围的暗处。

“………Suck。”

不一会儿，PoH发出咒骂声，右脚向后退了一步。

左手打了个响指，两名部下也退后了数米。从红色的Estoc下解放的优尔可跟凯因兹，软软
的跪倒在地上。

PoH将右手的菜刀举起，指向桐人，低声放话道：

“…………‘黑之剑士’。就你这家伙，我总有一天会让你趴在地上。在重要同伴的血海中
悲惨的打滚，你就期待着吧。”

说完，巨大的切肉菜刀在手指上灵巧了转了几圈，收到了腰间的刀套内。黑革雨披飘动起来，
“微笑棺木”的首领转过身，悠然的从小山丘上跳了下去，两名手下则是紧追其后。

Johnny-Black还像是十分在意朝这里赶来的攻略组集团似地，快步疾行，而被破斗篷包裹的
Estoc使——赤眼的ZaZa，则是前行了数步后，又转过身来，骷髅面具下闪着昏暗光芒的双眼
盯着我，低声说道：

“样子，很气派。下次我，也会骑马，追杀你的。”

“……那，就请多多练习吧。不像看着那么简单哟。”

听着桐人这样的回答，ZaZa发出低沉的呼吸声，追赶着伙伴们消失了。
*** 第12节
三道身影走下山丘，溶进夜色中，我依旧紧盯着因索敌技效果而表示出来的橙色Cursor。

微笑棺木的首领PoH，以前曾有过一次与他遭遇和交谈的经历，但和他的两名心腹倒是初次
见面。孩子气态度与外表的毒匕首使和，穿着十分破烂外衣的针剑【Estoc】使。当然两人
的Cursor中都没有显示出名字，谨慎起见，还是去向修密特确认一下吧，我这么想道。下一
次和他们见面的时候，恐怕就是动真格地战斗了。不得不用剑相互厮杀的对手，老实我说还
真不想知道他们的名字。

所以我，在Cursor走出索敌技能的极限距离之前，都一直看着他们。

犯罪者玩家，原则上是没办法进入有犯罪防犯程序保护的街道与村庄，也就是“圈内”。一
踏进圈内，就会被像鬼一样强的大量NPC守卫袭击，而拥有转移门的各层主街区，无一例外
地都是在程序“圈内”。那三人想移动去别层的话，只能用转移结晶前往“圈外村”，或是
使用高价的回廊结晶，再不然就是从已被攻略的迷宫区塔楼徒步上下。

大概他们是用第一种方法吧，毕竟一次来回就要消耗掉六个转移结晶，这对他们来说也是不
可轻忽的支出才对。咽下口水，看到三个Cursor都从视线范围中消失的时候，我无意识地呼
出一口安心的气息。

真是的，出现了超乎预想的麻烦家伙。那三人竟然会知道修密特——公会圣龙联合的前卫队长，
在攻略组中也拥有最大级的HP与防御力的男人在这个时刻会出现在这个坐标的情报。

不过这个情报的来源，应该马上就能知道才对。

我把视线从隐没在黑暗中的荒野上移回，调出窗口，朝带着十几名玩家应该正朝此处赶来的
克莱因，以很快的速度发送了一封”Laughing Coffin已逃走，请在街区待机”的讯息。

接着拿出解毒药水放在修密特的左手上，看着这名壮汉用颤抖的手将其喝下后，我把视线移
往向稍远处的另外两人身上。

对着脸上失去血色的两名死神装扮的玩家搭话的语气，多少参杂了些讽刺意味也是无可厚非
的吧。

“能再次见面真是令我高兴呀，优尔可小姐。还有……初次见面，凯因兹先生。”

数小时前，应该在我的眼前变成多边形碎片，飞散消逝的优尔可，抬起脸看着我，露出了略
带苦笑表情。

“我原本是打算在全部都结束的那时再好好道歉的……就算这么说，你也不会相信我吧。”

“相不相信什么的，就要看你请吃我的东西的味道了。先说明哟，可别请可疑的拉面还是谜
般的什锦烧之类的。”

在呆愣住的优尔可旁，脱掉黑色长袍，看起来有点木讷的男性——“圈内事件”最初的死者凯
因兹，也把头一度深深的低下。

“初次见面——也不是呢，桐人先生。在那个瞬间，我们的眼神有对上过一次呢。”

用平静的低音说出的这番话，让我总算回想了起来。

“说起来，的确是这样呢，是在你死时，啊，不是，是在铠甲破坏时也就是转移前的那个瞬
间吧？”

“嗯，没错，那个时候其实我就有预感了，可能会被这个人看穿假装死亡的真相吧。”

“你这么说真是太高估我了。我完全被骗了。”

这次换我苦笑起来。稍微和缓下来的空气，因撑起上半身，铠甲发出声响的修密特，而再度
紧绷了起来。

“……桐人。谢谢你帮助我……但是为什么你会知道那三个人袭击这里的事情？”

我回看往死盯着我的巨汉的眼睛，稍微想了一下要怎么说。

“并不是知道。而是推测得出可能性而已。如果一开始就晓得对手是PoH的话，可能就会害
怕的逃走了哟。”

不自觉用这种含糊不清的回答也是有原因的。

我接下来要说的话，大概会给这三人——特别是优尔可跟凯因兹，带来巨大的冲击吧。写下这
全部的剧本，进行演出，甚至连两位主演都没有注意到的，换句话说就是“制作人”，就隐
藏在这个事件的阴暗角落。我缓缓的吸了一口气，用尽可能平稳的声音开始叙说起来。

“………觉得奇怪，是在仅三十分钟前……”

*

事件已经结束了，接着就交给优尔可，凯因兹和修密特吧。

在第二十层主街区的某间能俯瞰酒馆的旅馆二楼，我对亚丝娜这么说道，并深深的靠在椅背
上。

他们应该是不会互相残杀才对。那么这次的“圈内事件”幕布，让成为其导火索的“戒指事
件”当事人们去拉下是最好的。对我这番确信的发言，亚丝娜也道出“也是呢”，并点头表
示赞同。

在随后到来的静寂中——我突然觉得胸口的某处，传来一种就像被极细的尖刺勾住般的感觉。

应该还有要思考的事。明明就知道要思考的事，但却不知道应该想些什么，就是这种焦躁感。

亚丝娜在房间里，边监视着酒馆，边说出的某个内容就是这种感觉的来源。“我说……”想
着这些的我在无意识间，说出了这话。

“……什么事？”

目光转向坐在身旁的椅子上，视线上移的KoB副团长，用近乎八成思考力分析着这份违和感，
并问出了超没常识的问题。

“亚丝娜。你，结过婚吗？”

回答这问题的则是冷到骨子里，充满杀气的视线与紧握的右拳和身体向前倾的攻击预备动作。

“我开玩笑的，取消，刚刚的不算！！”

在被抓到前我赶紧大叫，双手与头都拼命地摇动起来，连忙补充道。

“不是这样的……你刚刚有讲关于结婚的事情吧？”

“有啊。那又怎样了？”

被双眼紧盯着，我全身再次颤抖了起来，但还是拼命地开口说道。

“那个……具， 具体来说是什么去了。就是，Romantic或是Plastic什么的……”

“谁也没说那些啊！”

到头来亚丝娜用就快让防犯程序发动的势头，踹了我的小腿一脚，随后修正了我的记忆。

“我说的是romantic的同时也很pragmatic才对！先说哦， pragmatic是指实用主义的意思！”

“实用的……SAO的结婚？”

“没错。就某种意义上来说，完全没有遮掩的空间了吧，因为储物空间共通化的关系。”

“储物……共通化……”

就是这个。

这番话就是扎在我胸口，那小小尖刺的源头。

结婚的玩家，储物空间会被完全的统合在一起。所持容量上限会以两人的力量值合算，在带
来极高的便利性的同时，也产生了卷走稀有道具潜逃的结婚诈欺风险。

对这个系统，我一直十分在意。

被这压倒般的焦躁感给玩弄着，我再问了一个问题。

“那，那么……离婚时，储物空间会怎么样呢？”

“诶……？”

就像是出乎意料似的，亚丝娜睁大了眼睛。稍微倾着头，将准备殴打我的拳头托在下巴上，
说：

“那个嘛……记得应该是有几个选项的。像是自动分配，或是交互选择道具这类的……其他
还有几种，但我不太记得了……”

“想知道更清楚的详情呢。怎么办呢……对了亚丝娜，试试看跟我。”

没继续说下去，该说是英明还是说侥幸呢。

比刚才多放出好几倍的杀气，左手紧握在在名刀“Lambent Light”的刀鞘上，“闪光”微
笑着说道：

“试试看和你，干什么呢？”

“……要不要和，和我……一起写询问信件呢，问希斯克里夫。”

——仅一分钟就收到了回复信件，上头简洁的写着离婚时的道具分配法，真不愧是有活系统之
名的男人啊。

刚刚亚丝娜所说的，自动等价分配，交互选择分配。再加上百分比的自动分配。也就是说，
连分手费的可能都包含进去了，真是实用的系统呀。

我边听着亚丝娜读取信件的声音，边继续思考着。

这些选项，当然是在离婚时，双方的同意下才能选择的吧。反过来说，只要不同意分配的选
项，那在系统上就无法离婚。但不可能所有的离婚事件都能理性的商量这些。如果已是非离
婚不可，但对方又不同意的话怎么办呢，这个世界可没有仲裁所之类的地方啊。

回答这个疑问的便是希斯克里夫写在回覆信件的最末的一段话。

“……‘顺带一提，无条件离婚，是将道具分配率调整为自己百分之〇，对方百分之百的情
况下才能实现，这样的话，在离婚成立，储物空间分离时，对方拿不动的道具会全部掉在脚
边，桐人君，如果你被单方面的要求离婚的话，那么我推荐你去旅馆呢’……就到这里。”

看完信件的亚丝娜，用微妙的表情将窗口取消。

无意识地看着那张脸，我不断地重复念着信件的某个地方。

自己零，对方一百，自己零……对方一百……

“啊………”

原本只是扎在胸口，有股违和感的尖刺，突然变成了尖锐的疼痛。

原本只是小小的棘刺，突然巨大化起来。焦躁到疑念，经由确信、惊愕，进而转变成了恐惧。

“啊……啊啊啊……！！”

大叫着踢倒椅子，站起来的我，抓住眼前亚丝娜的双肩。被吓到缩起身体的“闪光”，发出
了跟以往截然不同的惊叫声。

“等……怎，怎么了呀……你该不会想在这种地方……”

没时间仔细去思考这番话，我发出了呻吟般的声音。

“自己一百，对方零。能让这种离婚方法成立的方法，只有一个。”

“……诶……？说，说什么呢………？”

紧紧抓住那纤细的肩膀，拉近那精巧的小脸，轻声地说：

“那就是死别，结婚对象死亡的瞬间，储物空间会回到原本的容量，收纳不下的道具会全部
掉到脚边才对。也就是……也就是………”

颤抖的喉咙咽下一口口水，继续说道。

“……也就是，公会‘黄金苹果’的会长-葛林瑟鲁妲被某人杀害的瞬间，她储物空间中的
戒指，并不是跑到犯人那里……而是落到结婚对象葛林姆洛克的储物栏中，或是实体化掉在
其脚旁。”

近在眼前的榛色眼眸，缓慢的眨了一两下。

浮现出的疑惑神色，突然变成了深深的战栗。

“戒指……没有被夺走吗……？”

对于这几近无声的询问，我也没办法马上做出回答。把手从亚丝娜肩上移开，站了起来，背
靠在窗缘小声说道。

“不……并不是这样。应该是说被夺走了。葛林姆洛克，把存在于自己的储物空间的戒指给
夺走了。他并不是虚幻的‘圈内事件’的犯人，而是‘戒指事件’的犯人才对。”

从亚丝娜的左手滑下的细剑【rapier】剑鞘，发出沉重的金属音，落在了地上。

*

“………就在仅三十分钟前，我还觉得很奇怪……我说，凯因兹，优尔可，你们的那两把武
器……布满逆棘的短枪与匕首，是从哪里弄来的呢？”

对于我的质问，优尔可跟同伴眼神相交后，回答道。

“……对于我们的这个‘伪装成圈内PK’计划，强化持续伤害的贯通性武器是必须的。而我
们探访过许多的武器职人，都没有看到这类特殊的武器……如果用订制的，武器上也会留下
刻铭，只要询问做武器的人，马上就能知道订购者，就是被害者的我们自己吧。”

“所以我们在没办法之下，只好联络在公会解散后都未曾见过的人……会长的丈夫-葛林姆
洛克。对他说明我们的计化，请他制作必要的贯通武器。虽然不知道他人在什么地方，但好
友登录还留着……”

在接着继续说明的凯因兹话中，总算出现了这个名字。我把注意力都集中在耳朵上，专心的
听着。

“葛林姆洛克一开始，也是不太赞成。回覆来的讯息，也只写了希望能让她好好的长眠。但
是在我们拼命拜托他后，终于替我们做了那两把武器，送到的时间刚好就在凯因兹【Kains】
的死亡日期的前三天。”

从这番说词，就可以知道优尔可跟凯因兹，都把葛林姆洛克当成了是妻子被杀的受害者。

我长吸了一口气，从胸口硬是挤出会给两人带来强烈的冲击与伤害的话语。

“……很可惜的是，葛林姆洛克之所以会反对你们的计划，可不是为了葛林瑟鲁妲哦，‘圈
内PK’这种夸张的事件，会引来非常多的注目，这样可能会被谁给发现事实的真相。因为结
婚而产生的共通储物空间，在不是离婚而是死别的情况下解除时……那里面的道具会如何之
类的。”

“诶……？”

优尔可像是不知道这话含义似的，略微歪起头。

这也是没办法的，在艾恩葛朗特，就算再怎么要好，但走到结婚这一步的情侣实在很稀有。
而离婚的人就更少了吧，再加上理由是其中一方的死亡这种情形就更是少之又少了。不只是
我，就连亚丝娜都认为戒指在葛林瑟鲁妲死亡时，掉落了出来并落到了杀人者的手上。

“听好了……葛林瑟鲁妲的储物空间，同时也是葛林姆洛克的，就算葛林瑟鲁妲被杀害，戒
指也没办法被夺走的，因为在她死亡的瞬间，就会转移到葛林姆洛克那边去。修密特……你，
是收到了协助这项计划的金钱报酬了吧？”

对于我的问题，盘坐在地面的壮汉呆然的点了点头。

“能够准备如此多的金钱，戒指这次应该是真的卖掉了吧。能够做到这些的也只有得到了戒
指的葛林姆洛克，他从一开始就知道修密特是担任杀害葛林瑟鲁妲的共犯，也就是说……”

“葛林姆洛克……？那家伙，就是那张纸条送出人……还有，将葛林瑟鲁妲运到圈外，并杀
害的施行犯？”

修密特用沙哑的嗓音呻吟道。我稍微思考了一下，否定了这点。

“不，他没有直接去做这件事吧。把在宿屋里熟睡的葛林瑟鲁妲用担架运到圈外时，她要是
刚好睡醒的话会很危险的。要是被看到脸就麻烦了。我猜，杀人的实行犯，应该是拜托了专
门从事这种工作的红名玩家。不过就算是这样，也无法减轻葛林姆洛克的罪行……”

“…………”

修密特什么也不说，只是呆呆着望向天空。

这失去了魂魄似的表情，也同时出现在了优尔可跟凯因兹的脸上。数秒后，优尔可左右摇着
她那头波浪般的头发，而且动作变得更来越激烈。

“怎么可能……这种事情，你骗人！那两个人总是都在一起……葛林姆洛克先生总是一直待
在她身后……再加上……对了，那个人是真正的犯人的话，那为何要协助我们的计划！？只
要不帮忙做武器的话，我们什么都办不到，‘戒指事件’也不可能再重见天日才对，不是
吗？”

“你们有跟葛林姆洛克说过全部的计划吧？”

听到我这番唐突的质问，优尔可在紧抿了一下嘴巴后，轻轻地点了点头。

“……那么，他应该知道计划成功的话会发生什么事。也就是……被罪恶感所驱使的修密特，
会来到葛林瑟鲁妲的墓前忏悔，在这里被优尔可跟凯因兹追问的最终幕，既然这样，可以好
好的利用这点，让‘戒指事件’永远的埋葬在黑暗中。共犯修密特，以及想知道真相的优尔
可跟凯因兹，把这三人……一起灭口就好了。”

“……这样啊。所以……所以，那三人……”

看了看低声说出这话的表情空虚的修密特，一副沉郁心情的我点了点头。

“就是这样，‘微笑棺桶’的三巨头会突然现身，也是葛林姆洛克把情报给流出去的，在这
种地方，出现DDA干部等级的大猎物，加上又没有同伴随行……恐怕在委托杀害葛林瑟鲁妲
时，就有联络通道了吧。”

“…………怎么会……”

膝盖失去力气正要跪到地上的优尔可，凯因兹用右手撑住了她。但他那十分惨白的脸色，即
便在月光下也能清楚知道。

抓着凯因兹的肩膀，优尔可用苍白的声音细语道。

“葛林姆洛克先生……想杀掉我们……？但是……为什么……？而且……为什么他会想要戒
指，并不惜杀掉结婚对象………？”

“我也没办法推测出其动机。不过，在‘戒指事件’时，为了确保不在场证明，连公会据点
都没离开的他，这一次应该也不可能只是乖乖待着。毕竟这可是处分掉你们三人，一口气葬
送两次事件的机会呢。所以……详情什么的，就直接问他本人吧。”

话音刚落，我的耳中便听到了从山丘西侧斜面传来的两道足音。

首先进入眼中的是，就算在夜色中依旧放出艳丽色泽的红白相间骑士服。不用多说，那就
是”闪光”亚丝娜，右手握着拥有澄澈通透的白银之刃的细剑。就我所知这也是在艾恩葛朗
特中最纤细、美丽的剑，同时也是能够贯穿各种防御，最为凶恶的武器。

被细剑锋利的前端，以及其持有者锐利的目光催促似的，一名男性朝这走了过来。

非常修长的身材。穿着前开式革制服装，带着帽缘宽大的帽子。藏在阴影处的脸，时而反射
出月光的大概是眼镜吧。整体给人的印象，与其说是锻造系职人，更像是香港电影中杀手出
现的氛围。大概也有部分是我先入为主的印象吧。

两人Cursor的颜色，都是绿色。为了阻止此男子逃跑，我已做好了让亚丝娜暂时成为橙名玩
家的觉悟——如果发生这种了事，不用说我一定会陪着她完成能够漂白回去的非常麻烦的任
务——看到这里，我不禁放心的吐了口气，但马上又收摄心神，正面盯着这位登上山丘的男子。

银框的圆眼镜下，是一副不管谁看了都会留下柔和印象的脸。细长，下弯的眼角看起来也很
善良。不过镜片深处的稍小的黑色眼瞳，确实有着能唤醒我的警戒心的某种存在。

男人在离我约有三米的地方停了下来，首先看了下修密特，接着是优尔可，凯因兹，最后稍
微看了下长满青苔的墓碑，开口说道。

“哟……好久不见了呢，各位。”

几秒钟后优尔，才对这平静低沉的声音做出了回应。

“葛林姆洛克…先生。你……你真的……”

杀害葛林瑟鲁妲，夺走了戒指吗。然後为了隐藏这起事件，更设计出要除去在场的三个人吗。

就算没有说出口，但不论谁听了都心知肚明，对于该询问，这个男人——原“黄金苹果”副会
长，锻造职人葛林姆洛克并没有马上做出回答。

看着身后的亚丝娜收剑入鞘，移动到我的身旁后，才微笑着动起了嘴。

“……那是误会。我只是觉得有责任要知道事情的结果，才会前往这个地方的。会乖乖听从
那位可怕大姊的威胁，也只是想解开误会而已。”

——哦哦，竟然还在否定啊，我瞪大了眼睛。确实没有他把情报送给PoH的证据，但是戒指事
件在系统上来说，他应该是没有任何藉口可说的。

“你说谎！”

做出尖锐的反驳的是亚丝娜。

“你刚刚不是还隐蔽在灌木丛中吗。如果不是我用看破技能的话，你根本就没打算出来吧！”

“这也是没办法的吧，我只是个普通的锻造职人哦。正如你所见连武器都没有，为什么我要
为不敢在那些橙名玩家面前出现而受到指责呢？”

平稳的答道，同时无奈似的张开了戴着皮手套的双手。

修密特，凯因兹，还有优尔可什么话都不说只是听着葛林姆洛克的言论。大概还是半信半疑
吧。以前的副会长，委托凶恶的红名玩家来杀掉自己，这种事连想都没想过，也不愿意相信
吧，他们会这样也不奇怪。

我伸出左手，制止了依旧想说些什么的亚丝娜，终于开口说道。

“初次见面，葛林姆洛克先生，我叫桐人……只是个外人。——但是的确，你在此出现，跟
‘微笑棺木’的袭击，并没有证据能够证明这两起事件能够连在一起。就算问那些家伙，他
们也不可能会作证吧。”

实际上，如果让葛林姆洛克将好友名单可视化，查找好友发送信息的话，那里应该存在着成
为“微笑桶木”暗杀委托通道的玩家名吧，但很可惜的是，我并不知道那家伙的名字。

不过，先把谋杀修密特等人未遂的嫌疑摆在一旁，“戒指事件”应该没有借口能够用了吧。
如此确信的我，继续说道。

“不过，去年秋天，成为公会”黄金苹果”的解散原因的‘戒指事件’……一定就和你有关，
不，应该是主导才对。因为不管是谁杀了葛林瑟鲁妲，戒指一定会留在与她共有储物空间的
你手上。你却隐蔽这件事实，偷偷的把戒指给卖掉，把其中一半交给修密特。这是除了犯人
外绝不可能做到的事。而你会跟这次‘圈内事件’扯上关系的原因应该也只有一个……封住
相关者的嘴，将过去埋葬于黑暗之中。没错吧？”

我说完这番话后，浓重的沉默降临到了这个荒野之丘上。不知从何处倾注而下的青色月光，
在葛林姆洛克的脸上刻下了明显的阴影。

不久，他的嘴角歪成奇妙的形状，能让人感觉到温度有些下降的声音响了起来。

“原来如此，真是有趣的推理呢，侦探先生……不过很可惜的，这推理有个漏洞。”

“什么？”

我反射性的回问道，葛林姆洛克朝我瞥了一眼，用戴着黑手套的右手把帽子向下压了压。

“的确当时我和葛林瑟鲁妲的储物空间是共通的，所以当她被杀的时候，储物空间的全部道
具应该都会留在我的手上……这个推理是没错，只不过。”

反射出月光的圆眼镜内，向我投来了锐利视线，修长身材的锻造职人用毫无顿挫的声音继续
说向下说去。

“如果那个戒指没有被收进储物栏的话？也就是说，实体化，并装备到葛林瑟鲁妲的手指上
的话……？”

“啊…………”

亚丝娜发出了细微的声音。

被这意想不到的问题给问到的我做出了同样的发硬。的确这起事件，还有许多我完全没有考
虑到的地方。

将实体化的道具装备起来的玩家，被怪兽或者其他玩家给杀害时，就会无条件的掉落下来。
如果葛林瑟鲁妲装备上那个戒指的话，那就不会转送到葛林姆洛克的储物栏，而是落入杀人
者的手中，这种说法也成立。

是察觉到形势逆转了吗，葛林姆洛克的嘴角稍微往上弯了起来。不过这种表情很快就消失了，
锻造师用右手扶住额头，悲伤似的摇了摇头。

“……葛林瑟鲁妲是速度型的剑士。想在卖掉戒指前，体验一下那种超高敏捷补正的感觉也
没什么好奇怪的吧？听好了，在她被杀时，的确所有的东西都转到我这里来了，可那里面并
没有戒指。就是这样，侦探先生。”

我在无意识中紧紧咬牙。想寻找能够反驳葛林姆洛克主张的说法，不过要能够证明葛林瑟鲁
妲的手指上有没有装备的这件事，大概只有实际杀害她的犯人——恐怕是微笑棺木的某名成员
才行。

看着一言不发的我，葛林姆洛克轻轻地举起帽子。就这样了看了看其余的四人，殷勤地行了
一礼。

“那，我就先离开了。虽然没找到谁是杀害葛林瑟鲁妲的首谋者很可惜，但就算只有修密特
的忏悔，也能让她的魂魄安息吧。”

对着再次向下深深的拉了下帽子，俐落的转过身去的锻造职人的背——

就像把某种强烈的心情隐藏在静谧之中似的，优尔可简短的说道。

“请等一下……不，请站住，葛林姆洛克。”

停下步伐的男子，把脸稍稍转了过来。眼镜下的那双看似柔和的眼睛，浮现出一丝厌烦的神
色。

“还有什么事情吗？如果是没有任何根据的感性指控能不能算了呢，对我来说这里可是个神
圣的场所啊。”

对着用高傲的语气，流利地说出这番话的葛林姆洛克，优尔可向前踏出了一步。

难道想做些什么吗，她将视线落到举到胸前的白皙双手上。随后再次面朝前方，那深蓝眼瞳
中，浮现出目前为止都没看过的强韧光芒。

“葛林姆洛克，你刚刚是这么说的吧。会长装备上了戒指。所以没有转移，而是被杀人者给
夺走。不过……这是不可能的。”

“……哦？你有什么根据？”

望着缓慢的转身过来的葛林姆洛克，优尔可用更加严厉的声音说：

“刚打出那个戒指的时候，公会全员一起讨论要怎么处理的事情还记得吧？我，凯因兹，还
有修密特都认为要增强公会的战力，而反对卖掉。那时凯因兹虽然很想自己拿来用，但还是
说出要先让给会长。——‘黄金苹果’最强剑士就是会长，所以给她用是最好的。”

优尔可身旁，凯因兹脸上露出了有些不好意思的神情。但优尔可毫不在意，带着动作继续说
道。

“对于这些话，会长是怎么回答的，我到现在仍旧可以想起每一字每一句。那个人，笑着说
了这些。——SAO里，戒指类道具一手只能装备一个。右手的是公会会长的印记，而……左手
的结婚戒指是不能摘下来的，所以我无法使用，听清楚了吗？对那人而言，取下这两样东西
的任何一件，而去尝试稀有戒指能力的这事，这绝对是不可能的！”

尖锐的话语声响起的那一刹那，包含我在内，所有的人都屏住了呼吸。

的确，在主菜单装备Figure上设定的戒指空位，左右手各有一个。两个都被占据的话，就无
法装备新的戒指道具。不过——

太薄弱了。

就像把我心中的话语复印了似的，葛林姆洛克小声的说道。

“我还以为你要说什么。‘绝对不可能’？如果真要说这个的话，首先请说这句吧？——跟葛
林瑟鲁妲结婚的我，是绝对不可能杀害她的。你所说的事情，都是没有根据的指控。”

“不。”

优尔可用很低的声音答道。我屏住呼吸，望着这名娇小的女性玩家，只见她缓缓的，但幅度
却很大地摇了摇头。

“不。不是的。我有依据……把会长杀害的实行犯，认为毫无价值的道具就直接丢在了案发
现场。幸好被一位知道会长名字的玩家发现这些道具，并将遗物送到了公会据点。所以我们
才把这里……把这个墓碑选作了坟墓，当时我们把她用过的剑放在了墓碑下，任由其耐久值
消减并自行消失掉。但……但其实不只是这样东西。我还在此处埋下了一个……从未跟大家
提起过的另一样遗物。”

说完这话，优尔可转身过去，跪在小小的墓碑旁边，用手开始挖土。在全员无言的注视中，
终于站起身来的优尔可，把右手上拿着的东西递了过来。是件刚从地里挖出来，在月光照射
下仍旧闪烁出银色光芒的小箱子。

“啊……‘永久保存盒’……”

就如同亚丝娜所说，优尔可拿出来的是大师级细工师才能做出的‘耐久值无限’的保存箱。
由于是个边长最大不过十厘米的正方体，所以没办法放下大型道具，如果只是饰品大小的物
件的话，倒是能放下几个。只要装到这里面的道具，就算放置在荒野中，耐久值也绝对不会
自动减少并消失掉。

优尔可接着伸出左手，打开了银色小箱的盖子。

镇座於白绢上的是两个闪出光泽的戒指。

优尔可先拿出其中一个——银制，较大的戒指。在戒指平平的部位，刻着一个苹果的标记。

“这是会长一直装备於右手中指，‘黄金苹果’的印记。同样的东西我也还留着，比较一下
就能立刻知道了。”

放回去后，接着取出另一个——闪着黄金色泽的，细长的戒指。

“然后这个是——她随时都戴在左手无名指上，和你结婚的戒指哟，葛林姆洛克！内侧也清楚
的刻着你的名字！……这两个戒指都在这个地方——这就是会长被送到圈外，直到被杀害的那
时仍旧戴着它们的，不可动摇的铁证！不是吗！？如果不是的话，你就反驳我呀！！”

说到最后，已经是泪流满脸的大叫了。

大颗泪珠从脸颊滴落，优尔可把手上拿着的闪着金色的戒指，伸到葛林姆洛克的眼前。

此时，没有一个人开口说话。凯因兹，修密特，还有亚丝娜跟我，都只是睁大眼睛，屏息看
着对峙的两人。

瘦高的锻造职人，嘴角依旧歪着，定格在原地有十秒以上。终于，其嘴角发出微微颤抖，并
紧紧抿了起来——

“这个戒指……好像是葬礼那天，你问我的吧，优尔可。你想带走葛林瑟鲁妲的结婚戒指吗？
然后我回答的是，就让它跟剑一样自然消逝吧。如果那时……我说出想带走的话……”

深深低下头，把脸深埋在帽沿下的葛林姆洛克，就像是操控着修长身体的丝线被切断了一样
跪到了在地上。

优尔可把金戒指给放回箱中，阖上盖子，紧紧的抱住。仰头望向天空，泪湿的脸突然歪曲起
来，用失去锐利气息的声音说道。

“………为什么……到底是为什么，葛林姆洛克。为什么，你就那么想把戒指抢过来换成钱
吗，不惜把会长……你的妻子杀掉？ ”

“………钱？你说钱？ ”

维持着双脚跪地的姿势，葛林姆洛克用沙哑的声音说道，随后笑了起来。

挥动左手，调出了目录窗口，经过短暂的操作，实体化出来的是只稍大的皮袋。葛林姆洛克
将其抓起，随手丢到地上。沉重的声音内，带着些许伴澄澈的金属音。就凭这些声音，我便
能推断袋子中，装了数额非常庞大的金币。

“这些是卖掉那个戒指的一半金额。一枚金币都没少。”

“诶………？”

葛林姆洛克抬头看着因困惑眉头紧皱的优尔可，接着又朝我们这边看过来，用嘶哑的声音说：

“并不是为了钱。我……我是不得不把杀掉她。在她还仍旧是我的妻子时。”

圆眼镜瞬间看向生苔的墓碑，很快又移开来，锻造师继续述说着这段独白。

“葛林瑟鲁妲，葛林姆洛克，开头的葛林两字并不是偶然。我和她在SAO前玩过的网络游戏
时，也都是用同样的名字。而且如果系统允许的话，也都是夫妻。因为……因为她在现实中
也是我的妻子。”

我打从心底感到震惊，稍微张开了嘴。亚丝娜也猛地倒吸一口气，优尔可一行也露出了惊讶
的神色。

“对我而言，她是找不出一丝缺点的理想妻子。甚至夫唱妇随这话都像是为了她而设的一样，
非常可爱，又很顺从，一次吵架都没有。只是……当我们一起被困在这个世界后……她就变
了……”

葛林姆洛克左右摇了要被帽子遮起来的脸，轻轻地吐出一口气。

“进入这个强制的死亡游戏，害怕，发抖的也只有我而已。到底她身上哪里藏有这样的才能
啊……不管是战斗能力还是状况判断力，葛林瑟鲁妲……不，是‘优子’都大幅的超越我。
还不只是这样。在不久后，她还压下我反对的声音，组成一个公会，招募会员，开始锻炼。
她……跟现实世界中比起来，更加的充满生命力……一副十分充实的样子……在旁边看到她
这个样子，我也不得不承认。我所爱的优子已经消失了。就算有将游戏通关，回到现实世界
的那天，沉静又乖巧的优子也永远不会回来了。”

在身体前并起来的长衣衣肩，微微的颤抖起来。是自嘲的笑吗，或者说是对于丧失的悲痛呢，
我无从判断。那细微的声音继续说道。

“……我害怕的东西，你们能理解吗？如果回到现实世界……优子向我提出离婚的话……这
种屈辱，我一定没办法忍受。那……那么就只能在我还是她丈夫时。加上身处这个合法杀人
的世界内。把优子封锁在永恒的记忆中，我的这份愿望……应该没人能责备吧……？”

漫长，而又可怕的独白结束后，一段时间内，没有人说出过一句话。

而我却又听到了，从自己的喉咙中发出的沙哑声。

“屈辱……屈辱？因为妻子不听从自己……就为了这种理由杀人？盼望着能从SAO中解放出
来，并且锻炼同伴……总有一天会成为攻略组一员的人，你竟然……就为了这种理由……”

我用左腕按住，颤抖着差点就要拔出背上之剑的右手。

慢慢抬起脸，眼镜下方发射出细微光芒，葛林姆洛克朝我低语道。

“这种理由？才不是，这可是十分充分的理由，你总有一天会知道的，侦探先生，当你得到
爱情，却又快要失去的时候。”

“不是的，错的是你，葛林姆洛克。”

反驳的并不是我，而是亚丝娜。

分外美丽的脸上，浮现出我也不知道的表情，细剑士平静的说道。

“你对葛林瑟鲁妲抱持的并不是爱情。只是占有慾而已。如果你还爱着她，那你就把左手的
手套给脱下来吧。葛林瑟鲁妲直到被杀前都没有拔下来的戒指，你已经丢掉了对吧。”

葛林姆洛克的肩膀小小的震动起来，就像刚刚的我一样，右手紧紧抓着左手。

不过，接下来手就没有任何的动作了，锻造师保持着沉默，并没有将皮手套脱下来。

再度打破这降临的静寂的是直到目前为止都没说话的修密特。

“……桐人。这个男的处置，可以交给我们吗？当然，不会动用私刑，但一定会让他赎罪
的。”

这冷静的声音，已经没有数十分钟前的那种害怕到极点的感觉了。

我抬头望着盔甲发出响声并站起来的壮汉，轻轻点了头。

“我知道了，就交给你了。”

修密特无言的点点头，抓住葛林姆洛克的右手把他拉起来。在确认低垂着头的锻造师逃不掉
后，短短地说了句“给你们添麻烦了”后，便离开了山丘。

再次把银色小箱埋回去的优尔可跟凯因兹，走到我们身旁，深深的行了一礼后，眼神交汇，
优尔可开口说道。

“亚丝娜小姐，桐人先生，真的非常抱歉……都不知要怎么跟你们道谢才好。如果没你们的
话，我们应该早就被杀了吧……葛林姆洛克的罪行也没办法揭露。”

“不……最后幸好你想起来那两个戒指的事情，真是干的不错。如果回到现实的话，可以去
检察官或是律师哦。”

听到这里，优尔可微笑着耸了耸肩。

“不……你们可能不会相信，但那时候，我好像有听到会长的声音。想起戒指的事情吧。”

“……这样啊……”

再次的深深地行了个礼，我和亚丝娜就在原地目送着跟在修密特身后，走下山丘的两人的离
去。

不久后四个Cursor都消失在了通往主街区的方向，荒野的小丘上，只剩下青色的月光和安稳
的夜风。

“……我说，桐人。”

突然间，亚丝娜小声的说道。

“如果你……假如和谁结婚的话，发现对方不为人知的一面时，你会怎么想呢？”

“诶。”

这未曾想过的问题，让我不禁呆住了。毕竟，我也才生活了十五年半，这种人生的微妙问题
还不能完全理解。

但在拚命思考后，终于开口说出口了，多少有些欠缺深思的回答。

“运气真好啊，会这么想吧。”

“诶？”

“因……因为结婚的话，就表示光是目前看到的部分就很喜欢了吧？所以在那之后又发现新
的一面，也同样很喜欢的话……不就是两，两倍了吗？”

虽然感觉是无知到极点的说法，但亚丝娜只是稍微皱一下眉，随后歪着头，微笑了起来。

“这样啊，真是怪啊。”

“怪……怪………”

“嘛，也没什么啦。不说这些了……发生太多事情，肚子都饿了呢。去吃点什么吧。”

“也，也是呢，那……阿尔盖特名产，看起来明明是炭烧但却没有酱汁味道的那个……”

“驳回。”

果然做出回绝的亚丝娜从身后突然抓住悄然前行的我的肩膀。

稍微被吓了一跳，并转身过去，在我眼前出现是——

自从跟“圈内事件”扯上关系后，不只是第多少次的无法说明的光景迸入眼帘。

艾恩葛朗特中，各种感觉都是可以用程式代码表示的数位资料。所以不可能有灵异现象的存
在。

所以，我现在看到的东西是服务器的BUG吗，不然就是大脑所产生的幻觉吧。

在不远之处，山丘的北侧，盘根错节的古树下，孤独立着的生苔墓碑旁。

有着一位身上散发淡淡的金光，半透明的女性玩家身影。

纤细的身上，只穿着最低限度的金属铠甲。腰部系着细长的长剑。背着盾牌。留着短发，容
貌闲静十分美丽，眼瞳中绽放出我所知道的众多玩家都有的强烈光芒。

那就是，蕴藏着用自己的剑，来结束这个死亡游戏的，攻略者的眼瞳。

浮出安详般微笑的女性玩家，不发一语的看着我和亚丝娜，但在一会儿后又像是递出什么似
地，张开右手向我们这边伸了过来。

我和亚丝娜同时也伸出右手，在掌心感应到微热的时，便紧紧地握了起来。这份温度流入体
内，点燃了藏于胸中的灯火，我们张开嘴，将形成的话语说了出来。

“你的意志……我们一定会继承下去的。总有一天一定会打通这个游戏，把大家都解放出去
给你看。”

“嗯，一定会办到的，所以……请守护着我们吧，葛林瑟鲁妲小姐。”

亚丝娜的细语，乘着夜风传达到女性剑士那里。透明的脸，露出了大大的微笑——

在下个瞬间，那里谁都不在了。

我们放下手，当场呆站在原地一段时间。

没多久，亚丝娜紧紧握住我的右手，微笑着说：

“回去吧。从明天开始，又得要努力了呢。”

“……也是呢。我想在这周突破这层呢。”

接着我们转过去身，走下这座小小的山丘，朝着主街区的方向走去。

（圈内事件篇 完）
** 第2章
Caliber

Alfheim

二〇二五年十二月
*** 第1节
“哥哥，看这个。”

说出这话的同时，直叶递出薄型触控数码终端，我则是睡眼惺忪地看了看。

昨晚睡了个前所未有的好觉，而且还做了一个很长的梦。不知是不是因为这个，就算围在桌
前吃早饭，大脑的思考齿轮也无法运转起来，只得将浓郁的咖啡转来转去。即便是在这种状
态下，我头脑某处的警告指示灯也亮了起来，究竟是否要将数码终端接过来呢，我稍微有些
困惑。

大概两周前，在相同的状况时机下直叶递给我的印刷纸上，将我隐藏的恶行——也不能这么说，
就是瞒着直叶擅自从飞行系VRMMO“Alfheim Online【ALO】”中将角色转换到了枪战型
VRMMO“GunGale Online【GGO】”中的证据完完整整的刊载到了上面。这回不会又是那个吧，
但最近的我没有做什么啊，就在我想着这些时，直叶苦笑道：

“这次并不是要想责问哥哥什么啦。好了，你快点看看吧。”

直叶将终端再次递过来，接过后，我把视线落到了上面。

和上次的印刷纸一样，屏幕上面显示的是国内最大的VRMMORPG情报站“MMO tomorrow”的新
闻栏目。不过，这次的游戏不是GGO而是ALO。最上方的截屏也不是某玩家的虚拟体，而是风
景照。看来，真的不是某黑衣Spriggan【守卫精灵】又做了些什么事情啊。

我松了一口气，开始阅读起新闻导读。

但就在不久后，被其他方面的新闻所冲击，让我不由得提高了音量。

“什……什么…………”

‘最强传说级武器‘圣剑Excalibur【断钢圣剑】’，终于被发现了！’

新闻报道栏刊载了这样一句话。

我忘记了之前的倦怠，开始认真阅读起正文，发出了长长的哼哼声。

“嗯嗯————……终究还是被发现了啊……”

“嘛，都这么长的时间了啊——”

坐在我对面，正往吐司面包上涂着草莓果酱的直叶，撅起嘴回答道。

“圣剑Excalibur”。

是能够超越Salamander【火精灵】将军尤吉恩所持的“魔剑Gram【瓦兰姆】”的唯一一把武
器。但这把剑在很长一段时间内，只能在官方网站的武器介绍页最下部看到小段的记载与照
片，游戏内的入手方法没有一个人知道。

——不，正确来说，只有三名，不，是四名玩家知道。我与直叶、明日奈，以及唯。发现它的
所在地是在今年年初，二〇二五年的一月。如今已经是十二月二十八日了，仅一年时间，
Excalibur的秘密就被发现了啊。

“啊啊……既然知道会这样，就应该再去挑战一次的啊……”

我嘟囔道，从直叶那里接过自家制的果酱，把勺子伸进去，将紫色的黏稠糊状物质一股脑的
倒在吐司面包上。随后，再追加搅打奶油，均匀涂抹开来，想要将其整成大理石一样平。最
近有些微妙地像是正在控制热量摄入的直叶，来回看着我与我手上的吐司，那表情像是在忍
耐着什么似的。最终，意志的底线像是被突破了，她一言不发地把手慢慢靠近装有奶油的容
器。

不知道是不是出于那仅存的意志，直叶将取出的少许奶油仔细的涂抹在吐司上。咬了一口后，
纠正了我的错误。

“你再仔细看看，只是发现而已。好像还没人入手呢。”

“什么！”

大大地咬了一口吐司的我停下了手，再次凝视起摆在桌子上的触控板终端。新闻报道中的确
只是提到了圣剑的存在，但并没有说谁得到了它。仔细想想，如果有哪名玩家得到了它，新
闻中应该会有那个家伙手举着黄金之剑摆出骄傲造型的SS【ScreenShot 截屏】吧。

“这样啊，不要吓我啊……”

拿起吐司，再次大咬一口，边嚼边发出放心的声音。看着简直像个小孩子的我，直叶笑了起
来，拿起牛奶倒进我面前的杯子中。

★　　★　　★

二〇二五年十二月二十八日，星期日，上午九点三十分。因为我和直叶的学校从今天开始放
寒假，所以早饭吃得有些晚。母亲还剩下几件需要在年内做完的校对工作，所以刚才叼着一
片吐司急冲冲地离开了家。没有印刷所这个中间环节的电子书籍才会出现这种情况，真是有
利也有弊啊。

单身赴任纽约的爸爸还是一样很忙碌似的，发了封邮件告知自己三十号才能回来。和平时一
样，餐桌上只有我和直叶两人，因此话题才会偏向ALO吧。

吃完一片吐司，我拿起第二片，一边往上涂着金枪鱼酱，一边将浮现在脑海中的问题说了出
来。

“但是，那个究竟是怎么被发现的啊？在Jotunheim【幽兹海姆】中是无法飞行的，即便能
飞也看不到那么高的地方啊，Excalibur的所在地。”

一年前，离开Sylph【风精灵】领前往中央都市阿伦前进的我/桐人与直叶/莉法，在好不容
易看到世界树的地方被巨大的蚯蚓吞到了肚子里，经由消化管道落到了地下世界Jotunheim
中。

那里是两人根本无法打败的巨大邪神级怪物阔步的领地，朝着通往地上的阶梯处移动的我们，
看到了一出不可思议的光景。有着四只手臂的人型邪神正在攻击一个有着无数触手，并长着
如同象鼻般的水母型邪神。

被莉法请求“去帮助那只被欺负的！”的我，把四只手臂的邪神引到了水面处，由于战场转
移到了水中，象水母最终取得了胜利。被命名为“冬奇”的邪神，非但没有攻击我们，反而
背着我俩来到了Jotunheim的中央地带。之后经由虫蛹“羽化”了的冬奇，驮着我们飞了起
来并把我们送到与地上世界相连的天盖通路处——在此途中，我们发现了圣剑。天盖中央处有
着被世界树根部包裹呈现倒金字塔状的巨大迷宫，那最下部的水晶中封印着闪着光芒的金色
长剑。

像是和我一起回忆起了这段记忆的直叶，眼睛上挑，微笑道：

“哥哥那时候犹豫了很久吧。究竟是乘着冬奇就这样回到地面，还是去迷宫那里刷那把圣
剑。”

“那……也是啊，很困惑……但我敢这么说，那时不会困惑的家伙，我根本不会承认他是网
游玩家！

“一点也不酷哟，那种话！”

微笑着评价道，直叶陷入思考似地低下了头，像是在困惑着第二片吐司究竟涂什么果酱。随
后她把手伸向金枪鱼酱，同时说道。

“……冬奇，只有我和哥哥才能呼唤过来……没有其他在Jotunheim飞行的方法。不过，难
道是有谁帮助了其他的象水母，开启了这段任务FLAG呢……”

“怎么可能啊……帮助那种恶心……啊不，长得极具个性的邪神那种爱好……啊，不，是博
爱主义者除了直叶外没想到还有其他人啊。”

“一点也不恶心！很可爱的！”

今年已经年满十六周岁的妹妹，瞪着我做出了这番宣告，并继续说：

“但是，如果是这样的话，突破迷宫将那把剑成功入手也只是个时间的问题了。虽然从我们
达成FLAG条件到今天都没有人发现，但已经过了一年，而且通过系统升级导入了剑技系统，
迷宫的难易度应该也相对下降了些。”

“是……啊……”

喝了口牛奶，我点头道。

我们是在今年一月发现Excalibur。之后ALO的运营权就由雷克特制造移交到了现在的风投企
业，装载了浮游城艾恩葛朗特后，游戏发生了巨大的变革。这阵热度终于在六月平静了下来。
我和莉法、唯，还有亚丝娜再次乘上冬奇，进行了一次入手圣剑Excalibur的挑战。

之后当然是漂亮的失败了。倒金字塔型的空中迷宫里，四处横行的全都是些长着四只手臂的
巨大人型邪神，就像是欺负冬奇的邪神的首领一样，那些家伙有着让人惊呼出“太假了
吧！”的强悍实力。仅靠三人与唯前去也只是做正式挑战前的侦查，但在那时便得出了无法
攻略的结论，并作出了“变得更强后再来挑战吧！”这种誓言——不过。

艾恩葛朗特加载后最初只开放到了第十层，在九月时开放到了二十层，我们都忙于那边的攻
略了。有时也去Jotunheim刷些素材，顺便叫出冬奇一起游玩一下，但却没有做任何有关于
攻略的事宜——反正也没有人找到这里。就这样，一年过去了。

不过，在MMORPG中，是不存在永远不会被发现的道具的。虽然是如何发现的详情仍旧未知，
但那把剑的所在之地终究被刊载到了新闻站点上，现在应该已经有许多玩家进入了
Jotunheim，并且有一部分已经闯入了空中迷宫了吧。

“……怎么办呢，哥哥？”

把第二片吐司涂抹完毕的直叶，双手拿起装有牛奶的杯子问道。

对此，我轻轻咳了一声，答道：

“直叶，并不是只有追求稀有道具才能体会到VRMMO的乐趣啊。”

“……嗯，是这样。虽然武器的属性也能让人变强……”

“但是我想，我们必须回应带我们找到那把剑的冬奇的心情才行啊。那家伙一定在心中期待
着我们闯过迷宫，不是吗？因为，冬奇不正是我们的朋友吗！”

“…………你刚才，明明还说冬奇很恶心的……”

对于妹妹投来的感到可疑的视线，我展现出了最高级别的笑脸，问道：

“就是这样，直叶，你今天有空吗？”

“…………嗯，社团活动也休息了！”

好！我用右拳打在左掌上。切换了思考的齿轮，将攻略计划用很快的语速说出。

“好像，乘坐冬奇的人数上限是七人吧。我和直叶、亚丝娜、克莱因、莉兹、西莉卡……还
差一个人啊。艾基尔要看店……克里斯海特又不怎么可靠，蕾鵼应该在Sylph领才对……”

“……去邀请诗浓看看？”

“哦哦，就是她！”

啪，我打了个响指，连忙拿出携带终端，翻阅起电话簿。

这个月上旬，我因为某个事件进入了GGO——“GunGale Online”并将桐人转换了过去，在那
里认识了名叫诗浓的女生。事件解决后，诗浓与亚丝娜和莉兹成为了朋友，在她们的邀请下，
诗浓也在ALO中建立了一个新的账号。

虽然是个刚刚建立只有两周的角色，在完全技能制的ALO中，数值参数占得分量也很低。但
如果有着诗浓那种判断力与感觉，挑战高难度的迷宫已经是足够了。

我用最快速度发送起邮件，对面的直叶则是利索地将碗筷与杯子摞在一起搬到了厨房。也不
知是不是错觉，总觉得她的脚步十分轻盈。恐怕她一开始把新闻给我看时，就已经猜测到会
有这样的结果了吧。

与志同道合的伙伴共同奔赴异世界，挑战极其困难的迷宫。再也没有比这更让人高兴的事情
了吧。

将邀请邮件发送给包括诗浓在内的五人后，我小步跑动起来，前去厨房帮助直叶。

★　　★　　★

虽说是周日，但正处于过年期间，要在上午将七人团队聚集在一起，全都是靠作为召集者的
我的人格魅力——不，是“圣剑Excalibur”对所有网游玩家的吸引力吧。

碰头的地点是央都阿伦南大街挂着“莉兹贝特武具店”牌匾的工房，锻冶妖精族店主【就是
指的莉兹贝特】正挨个把大家寄放在这里的武器用回转轮砥石进行打磨。进行大任务前将装
备耐久度恢复到最大值这都是常识。

倚坐在靠墙的长椅上，以“欣赏景色”为由从一大早开始就喝着酒——虽然如此，但现实中却
滴酒不沾的——Salamander刀使克莱因，正倾听者头上顶着一只松软的水色小龙的Cat
Sith【猫妖精】族驯兽师西莉卡的问题。

“克莱因先生，正月也休息吗？”

“哦，是从昨天开始的吧。就算想工作，这个时期也没运输单进来啊。社长那个混蛋，可是
把这年初年末的一周假期当做我们公司优待员工的证据啊。”

克莱恩虽然长得这个样子，好歹也还是小规模运输公司的资深员工。他嘴边经常挂着对社长
的怨言，但从他被关在SAO的两年里都是社长在关照他，而且回来后马上让他回到工作单位
来看，那应该是一个不错的会社吧。克莱恩也像是感恩的样子，最近正利用“The Seed”捆
绑的移动摄像头架构着远程演示系统，一副认真工作的样子。我因为在那些摄像头的调整上
帮了不少忙，所以强硬地让他答应了请客任吃一次烤肉，但看在今天的任务他帮了我一把的
情义上放过他吧——

我一边想一边朝着墙边走去，克莱因突然看到了我，说：

“哦，桐人哟，这次如果要我帮忙一同去刷‘Excalibur’的话，那下次你也要帮我去刷
‘灵刀迦具土’哟。”

“诶诶……那个迷宫可是很热的……”

“如果你这么说的话，这次要去的Jotunheim不是很冷吗！”

就在我们进行着低级别的谈话时，左侧传来了这样的话。

“啊，那我也有想要的东西。‘光弓Shekinah【智天使】’。”

话音刚落，我便望了过去。说出这话的是和我一样靠在墙壁上，抄着双手，水色的短发中伸
出尖尖三角耳朵的Cat Sith族女性玩家。如果说西莉卡是与人和善的曼切堪【Munchkin】猫
的话，这边就是很酷——不，不如说是只凶猛的山猫。

“才，才创建角色两周，就想要传说武器啊。”

听到我的话，山猫细长的耳朵动了动，回复道：

“莉兹打造的弓虽然很不错，但条件允许的话我还是想再提高一些射程……”

说完这话，在工房内的作业台处，正在更换弓弦的莉兹贝特转过脸，苦笑道：

“我说啊，这边世界的弓，只是一种射程夹在魔法与枪械之间的武器！能够在百米距离狙击
别人，已经不普通啦！”

相对的，山猫微微耸了耸肩，露出爽朗的笑容。

“如果要说更高要求的话，我还想要再高一倍的射程呢！”

在作为诗浓主攻的游戏GGO中，她最擅长两千米距离的超远距狙击，知道这些的我也只得露
出了抽筋般的笑容。如果真的让她得到这把弓，在没有区域限制的决斗中，在剑碰到她之前
恐怕就被扎成刺猬直接END了吧。

水色头发的山猫——两周前刚在ALO内创建了账号的新朋友诗浓，仅仅只用了一天的练习，就
已经把难以驾驭的弓箭使用诀窍全部掌握了。说到ALO里的弓箭手，拥有机动力的Sylph使用
短弓，臂力与耐久力优秀的Gnorm【小矮妖】族装备HeavyVaristor化身为炮台这些都是惯例。
但诗浓却无视这些套路，使用强化射程的长弓，并选择了九个种族当中拥有最远视野的Cat
Sith族。最初还是让她自己尝试吧，我曾这么想到。但看见诗浓用弓箭在火属性魔法的射程
之外啪啪命中，并在怪物近身前就将其击倒的景象后，内心不由对其佩服得五体投地。

这个世界中的弓箭，如果处在适当的距离，是与魔法一样有着系统辅助修正的，但超过后就
会受到“风与重力的影响”，让箭偏离命中的地点。不过在使用同样游戏引擎的GGO中，诗
浓已经做了很长时间的自动修正“风与重力的影响”的练习。这与前往GGO时的我能够有效
的使用“读取视线”这种系统外技能，大概是相同的道理吧。也就是说可以既然能够在The
Seed规格的VRMMO连结体中转换，做到这点也是不难想象的——

就在我思考着这些时，右侧的工房大门打开了。

“我回来了！”“久等了！”

声音的主人，便是去购买药品类物品的莉法与亚丝娜。像是从市场到工房都没有将物品收纳
在道具栏，而就这样搬运了过来似的，两人从提篮内将各种各样的小瓶子以及杜松果取出放
在桌上。

从亚丝娜肩膀上飞起来的小妖精——导航妖精唯，移动并坐到了我的头Spriggan“桐人”的虚
拟体，原本长着一头如同倒刺般的长发，在唯的请求下，现在已经恢复到了跟以前相同的发
型。理由好像是“难以坐在上面【估计就是坐在上面不舒服】”。

唯坐在我头顶上，用银铃般的声音说：

“买东西的时候我顺便调查了一下情报，好像还没有其他玩家团队到达那个空中迷宫哟，爸
爸。”

“诶……那他们是怎么知道‘Excalibur’所在地点的啊？”

“可能是通过另外一种任务发现的吧，和我们发现的冬奇任务不同。作为那个任务的报酬，
NPC告知了他们Excalibur的消息吧，应该是这样的。”

将药瓶整理完毕，转过身来的亚丝娜，皱起眉毛首肯道：

“看来也不是什么安稳的任务啊。不是押运系或者护卫系，而是屠杀系【Slaughter】吧。
为此，现在应该在Jotunheim中为了争夺POP【刷怪点】而展开着杀戮吧。”

“……确实是不怎么祥和啊……”

我也歪起了嘴唇。

屠杀系，和其虐杀的名称一样，是“打倒名为〇〇的怪物〇只以上”或者“收集〇〇怪物掉
落的道具〇个”这种类型的任务。当然，为了能够单方面去狩猎指定种类的怪物，在狭窄的
区域与接受了相同任务的团队遇上时，为了争夺POP，也就是刷怪点发生摩擦也是不可避免
的。

“但是哟，不觉得很奇怪吗？”

将火酒一口气喝完的克莱因，擦了擦嘴角说道：

“‘圣剑Excalibur’不是好好的封印在恐怖邪神满处乱窜的空中迷宫最深处吗？NPC把这个
在任务报酬里进行提示又有什么用啊？”

“照你这么一说，真是这样啊。”

将头上的毕娜取下抱在胸口的西莉卡也歪起了头。

“如果是把前往迷宫的移动手段作为报酬，这样还能够理解……”

“——嘛，去了的话就一定会知道的。”

在我身旁，诗浓说出了这番和以往一样冷静的话，随后工房内的莉兹贝特大声说道：

“好了！武器都恢复完毕！”

“辛苦了！”

所有人一同说道，将散发着新品光泽的爱剑、爱刀、爱弓分别取回挂在身上。随后拥有作战
指挥能力的亚丝娜拿走了七成药瓶，装进腰上的口袋中。没有实体化的份则是收容在道具栏
中。

扫了眼视野右下方的现实时间，还是上午十一点。此时应该是吃午饭休息的时刻吧，但比起
这些来，还是先赶往空中迷宫的最初安全地带吧。

七人加一人加一匹，所有人都准备完毕后，我转身过去看了看大家，咳了一声，说：

“感谢大家在听到我的紧急召集后能够前来！我一定会报答你们的，在精神上！那就——加油
吧！”

哦！附和声中混杂着些许苦笑，但应该是错觉吧。我转过身去推开工房大门，朝着阿伦市街
通往地下世界Jotunheim的秘密地下通道，大踏步向前迈出。
*** 第2节
在地图上没有标示出的阿伦隐藏窄道中左右穿行，上下阶梯，穿过民家庭院后，一扇门出现
在了眼前。

一眼看去和普通的圆型木质门没什么区别，只会让人认为是一扇打不开的装饰物，但莉法从
口袋里取出一把小柄铜钥匙插进门锁内，旋转，咔嗒发出了清脆的声响。这把钥匙是在以前，
我和莉法被送到这个通道时，不知在何时追加到储物格内的。正因为这个原因，从阿伦这边
是绝对打不开这扇门的。

抓着铁质把手向外拉，木门从正中左右分开，里面的楼梯展现在了眼前。七人排成一列走了
进去，队尾的克莱因把门合上，门自动地上了锁。

“呜啊……这里究竟有多少阶楼梯啊。”

第一次来到这里的莉兹贝特，会低声说出这话也不足为奇。在直径约两米左右的通道地面上
建造的楼梯，被墙壁上挂着的释放出青白色光芒的灯火照亮，一直向前延续，直到视线的限
界处。

“嗯，差不多和艾恩葛朗特迷宫区内的塔楼阶梯数一样吧。”

走在队伍最前方的亚丝娜回答道，莉兹与西莉卡、克莱因同时露出了惊讶的表情。我苦笑着
强调起该通道的价值所在：

“我说，如果想用普通的方法走到Jotunheim的话，必须先前行到东南西北各距阿伦数公里
的迷宫楼道处，边打着怪物边向深处前行，最后击败守护BOSS后才能到达哟。一支队伍的话
最快也需要两个小时哟，但从这里下去只需五分钟！我和莉法打算做份生意，收取一千尤鲁
特【Urud，游戏中的金钱】作为该通道的使用费。”

“哥哥啊，从这里下到出口，如果没有冬奇前来迎接的话，可是会掉到Jotunheim的中央大
空洞中死翘翘哟！”

莉法挂着一副无奈的表情说道，但确实是这样。

广阔的Jotunheim地下世界正中，有个直径差不多有一点五公里的无底大洞，通称“中央大
空洞【Great Hole】”。封印圣剑Excalibur的倒金字塔型空中迷宫，正建造在这个空洞的
正上方。我们现正向下奔走这个阶梯的出口虽然离迷宫很近，但依旧设立在大洞的上空，所
以只要起跳就必定会落到那个无底洞中死亡，并强制回到地上的存盘点处。

咳，我用咳嗽声阻止了这番自己极想说出的话，一本正经地说：

“该怎么说呢，就因为这样，大家每向下走一步都应该毫无怨言，并怀着感恩的心哟！”

“这又不是你造的！”

我刚说完这话，走在前面的诗浓便立即做出了回应。虽然她依旧是一副极度冷淡的样子，但
此时她的那番吐槽中应该也带着感恩之心吧。

“谢谢吐槽！”

我紧紧抓住在眼前摇摆的水色尾巴代替握手作为回礼。[fn:37]

“呜啊！”

随即，山猫弓箭手大人惨叫着跳了起来。随后猛地转过身子，熟练地倒退行走，并对着我的
脸伸出两爪威吓似地晃动起来。

Cat Sith族特有的三角耳朵与尾巴，当然是人类没有的器官，但官方不知道基于什么原因也
配置了感官功能。没有习惯的玩家突然被这么抓住“可是会感觉很奇怪的哟”——西莉卡这么
说过——正因如此，反应才会这么大啊，真是让人充满兴趣又充满疑问的部位啊。

“你，下次再这么做的话，我就把带火的箭插到你的鼻孔里。”[fn:38]

哼！诗浓猛地转了回去，走在她前面的莉法、莉兹、西莉卡、亚丝娜以及肩膀上的唯全都哎
呀哎呀地摇起头来。同一时刻，“你还真是无所畏惧啊”，走在我身后的克莱因钦佩地念叨
道。

★　　★　　★

虽然预计要用五分钟，但实际并没走那么久，队伍便来到了贯穿Jotunheim地壳的阶梯通道
尽头，前方出现了白色的光芒。

同时，虚拟的空气开始慢慢变冷，脸庞周围开始有冰晶闪烁舞动起来。

数秒后，我们终于走出了地壳，Jotunheim全景尽收眼底。建造在粗大树木根部的楼梯就这
样继续在空中延伸，消失在前方约十五米处。

“呜……呜啊……！！”

“好棒啊……”

首次见到Jotunheim的西莉卡与诗浓这两只猫，同时发出惊叹声。小龙毕娜也是，在西莉卡
的头顶扇动起翅膀来。

眼下是一片被厚实的冰雪所覆盖，既美丽又残酷的，宽广的极夜世界。照明只有从我们周围
的天井处伸出的巨大水晶柱所引导的地上的光芒，其他的就只有在地表各处的邪神族城堡、
山寨里点起的青紫、黄绿色的篝火。由于从天井到地面的高度在这个中央部分大约有一公里，
因此无法看清应存在于地底区域的无数只邪神。下方能见到的，就只有仿佛吸收了所有光芒
的无底大洞，“Hole”。

视线从正下方移回，这里的景色也只能用厉害来形容。

被无数条蜿蜒而下的巨大根系——也就是屹立于地上世界Alfheim【阿尔普海姆】的世界树的
根——抱成一团的浅青色冰块从天盖处向下突出。呈现出倒金字塔的形状，这也就是我们的目
的地“空中迷宫”。底部边长三百米，全高大约也是这么多吧。冰晶内部有着无数的区域以
及通路，从这个距离也能清楚地看见。还有那徘徊其中的巨大身影。

最后，我的视线移到了倒金字塔的最下方，也就是那尖端处。

就算是有着夜视强化补正的Spriggan的眼睛，也只能看到时而绽放出的一小点儿金光。不过
绽放出那光辉的深处，却有着难以说明的吸引力。“圣剑Excalibur”。ALO最强的传说级武
器，正封印在那里。

确认完状况后，亚丝娜抬起了右手，熟练地咏唱起咒文。全员的身体被一阵青色的光芒包裹，
视野左侧HP槽下方亮起了一个小小的标记。瞬间，如同穿上了一件高质量的羽绒服一般，肌
肤的寒冷逐渐远去。这便是提高冻结耐性的支援魔法。

“OK。”

听到亚丝娜的话语声，莉法点了点头，把右手手指放在嘴唇前，吹了个响亮的口哨。

数秒后，混杂着风声，呜哦哦哦哦……这样的啼叫声从远处慢慢靠近。仔细望去，洞穴黑暗
的背景上，一个白色的身影正不断的上升。

如同扁平的鱼，或者说是饭勺般的身体侧面，伸出四对共八只鱼鳍状的白色翅膀。身体下方
则是垂着无数根如同寄生植物般的触手。头部则是长着一只很长的鼻子，并且脸部每侧各长
着三只黑色的眼睛。这便是从象水母“羽化”而来，美感怪异的邪神，冬奇。

“冬奇————！”

坐在亚丝娜肩膀上的唯大声呼唤道，不可思议的邪神再次发出啼叫。用力扇动起翅膀，沿着
螺旋状的轨迹疾速上升。其身姿逐渐变大，初次见到其模样的四人，不由得攀上阶梯向后退
去。

“没事的没事的，这家伙看起来这样其实是草食系的！”

我这么说道，莉法则是对着他们笑了起来。

“但是不久前，我从地上带来的炸鱼[fn:39]，却被它一口吃掉了哟。”

“………………诶，诶。”

克莱因等人再次向后退去一步，狭窄的阶梯没办法让他们继续后撤了。不一会儿工夫便抵达
我们眼前的冬奇，用那还是酷似大象的脸挨个看了下我们几个，随后伸长鼻子，摸了摸长着
杂乱毛发的克莱因的倒刺头。

“呜啊哦！？”

我毫不留情地推了下发出奇怪叫喊声的刀使的背。

“快啊，坐到它的背上去。”

“虽……虽然你这么说，我的爷爷可是留下了不要坐美国车与飞天大象的遗言哟……”

“前一阵子在Daisy Cafe那里，不是还吃了你爷爷亲手做的柿饼吗！还说好吃的话下次再拿
些来！”

说完，我又推了一下，克莱因才畏畏缩缩的把脚踩上冬奇的肩膀，走到了它那扁平的背上。
随后，胆量依旧很大的诗浓，喜欢动物也把冬奇包含在内的西莉卡也陆续坐了上去。“准备
好了！”莉兹贝特在喊出这句毫不符合少女情调的吆喝声后，与坐了很多次的莉法与亚丝娜
一同坐了上去。最后，我摸了摸冬奇的鼻子，跳到了全长约十米多的邪神级怪物背上。

“好了，冬奇，请你把我们带到迷宫入口处吧！”

坐在脖颈附近的莉法呼喊道，随后冬奇扬起长长的鼻子，发出了啼叫，八片翅膀按从前到后
的顺序扇动起来。

★　　★　　★

我乘坐在飞行型邪神“冬奇”的背上，包含单纯的游玩在内这已经是第五次了。虽然没说出
口，但在这次旅途中却有件不得不考虑的事件，也就是——

“……我说，这个，从这里掉下去会怎么样呢？”

我的思考，被坐在身后的莉兹贝特完美的打断了。

是这样的。在Jotunheim中原则上是所有种族的妖精都无法飞行的，但从高处跌落造成的伤
害依旧和以往无异。依据技能值的不同，大约从十米以上的高度跌落会造成伤害，超过三十
米毫无疑问会死亡。

而现在，冬奇正飞在高度约一千米的上空。从这里掉下去根本不用想，绝对会死。要说有什
么安全措施的话——那就是被冬奇腹部下方的触手抓住——虽然有这可能，但却没那勇气去尝试。

大家似乎都怀着相同的恐惧，但坐在最前方体验着“Speed Holic”的莉法，在她头上移动
的唯，还有抱着毕娜的西莉卡心情却看似不错。

回答莉兹问题的是坐在她身旁的亚丝娜。她带着有些紧张的表情，望着我微笑起来，说道：

“我们之中的某个人呢，以前曾经试图从SAO外围的柱子爬到上一层。虽然结果还是放弃了，
但估计那个人总有一天会去试试看吧。”

“……从高处落下的话，猫科动物不是更加擅长吗！”

话刚说完，两名猫科玩家就BUNBUNBUN地摇起头来。

就在大家说着这些时，冬奇的四对共八枚翅膀逐个放慢了摆速，在空中进入滑行状态。朝着
对面设在冰晶空中迷宫上部侧面的入口平台飞去。希望它能够安全驾驶啊——

我开始默默地祈愿，就在这时——

突然间冬奇所有的翅膀折成锐角，进入俯冲态势。

“呜啊啊啊啊啊！？”

两名男性玩家发出了凄惨的叫声。

“呀啊啊啊啊啊！”

女性团体发出了刺耳的尖叫。

“YAHO——O！”

这是莉法。

抓着冬奇背上长出的浓密体毛，拼命忍耐着风压，以近乎垂直的角度朝着遥远的地面渐渐逼
进。不过为什么突然会这样呢？至今为止乘坐过几次，都是在树根阶梯与冰锥之间按照一定
的步调来回飞行啊。

难道是厌烦了当出租车了吗？还是说上次莉法一时兴起喂的鱼已经消化掉了吗？考虑着这些
对身体无益的事情，被冰雪覆盖的地表细节开始高精细化。冬奇的目的地，就是巨大洞穴
“Hole”南侧附近似的。对了，我和莉法曾在那里与狩猎冬奇的Undine【水精灵】族联合团
队交战过。

随后，强烈的减速感朝身体袭来，全员都紧紧贴到了邪神的背上。冬奇将折叠的翅膀展开，
开始猛地刹车。但至少它不像是想要把身上的“行李”随便甩到地上。我呼出一口气，坐起
身来。

从再次恢复平稳巡航态势的冬奇背上朝下看去，已经处于离地面约五十米的上空的样子。从
这里看下去，就像看高比例航空照片那样，能特别鲜明地看清地面的样子。挂着下垂冰柱的
枯木，冻结的河流与湖泊，以及——

“…………啊…………！？”

发出这般尖叫的是坐在冬奇头部，拼命扯着身体的莉法。她指着地面，挤出如同悲鸣般的声
音。

“哥，哥哥，看那里！！”

按照莉法所说，我与其他五人都向着她所指的左前方望去。

就在这时，持续不断爆炸所产生的炫目FLASH特效，映入已经习惯了昏暗环境的我眼内，响
亮的重低音特效稍微迟一些传了过来。毫无疑问，那是大规模魔法咒文所造成的。

冬奇发出了“咕噜噜”的悲怆啼叫声，那理由我们很快就明白了。

被攻击的是长长的触手托着馒头状的身体，长着长鼻子大耳朵如同大象一般的大型怪兽。毫
无疑问和“羽化”前的冬奇是属于同一种族。

随后，攻击它的是超过三十人的大规模联合团队。由发色各异、体格相差很大的种族混合而
成的部队，只看外表便能知道是一般的“邪神狩猎队”。不过，不仅让莉法而是让我们全员
惊叹的是，攻击象水母的不仅是玩家的这个事实。

有着大个Gnome玩家六七倍以上的身高。体格虽是人型，但长着四只手臂和三张纵向排列的
脸，肤色是钢铁般的青白色，眼睛散发出灼热石炭般的暗红色。

这边也不用考虑，就是与冬奇初次相见时想要杀掉它的人型邪神一族。每只手都拿着一把钢
筋般的大剑，正用那看似很钝的刀刃一次又一次地敲击着象水母的背脊。硬质外壳一次又一
次的出现龟裂，体液迸发出来，玩家们的魔法与箭矢、剑技也一次又一次在其背部击打出裂
痕。

“那是……怎么一回事？那个人型邪神难道被谁驯服了吗？”

亚丝娜气喘似的低声说道。西莉卡则是猛地摇起头来，回答道：

“这，不可能！驯服邪神怪物的成功率，就算是技能达到最大值，再使用专用装备强化，也
没有一丝概率！”

“这也就是说……”

克莱因挠着自己那倒刺般红发，念叨道。

“该怎么说呢……难道是‘借势’吗？趁着四臂巨人攻击象水母，进行追加击打……”

“但，也不可能如此精准地控制仇恨值啊。”

诗浓眉头紧锁，做出了冷静的分析。的确就像她所说的，就算预测出邪神的活动方式，能够
在如此近的距离连续多次施展魔法技能，即使没有对其造成伤害，巨人的攻击目标会转移到
玩家这边也不足为奇。

怎么也搞不清楚状况，只得紧咬嘴唇的我们眼前，象水母邪神巨大的身体摇晃起来，发出响
亮的声音倒在雪地上。随后，致命一击的铁剑与大型咒文向其袭去——

“咻噜噜噜噜噜噜……”

象水母发出最后的惨叫，膨大的身体化作多边形碎片，四散而去。

咕哦哦哦哦……冬奇再次发出悲怆的声音。坐在其头上的莉法肩头也颤动起来，莉法头上的
唯也深深地低下了头。

看着两人，我什么话也说不出，只得将视线转移到下方的联合部队处。

之后，新的惊愕出现在眼前。

既不是驯服状态，也不是煽动状态，更不是幻惑状态的四臂巨人“噗噜噗噜噜”发出胜利的
吼叫，在其脚旁，数十名玩家也做出了胜利的姿势，两方像是一同开始寻找新的目标。

“为……为什么非得战斗啊！？”

我用沙哑的声音说出这话，此时在我身旁的亚丝娜像是觉察到了什么似的，抬起了脸。

“啊……看啊，那边！”

她所指的地方是右侧远处的山丘。在那里，战斗特效的光芒激烈地闪烁起来。仔细望去，果
然是大规模的玩家集团，这次是和两匹人型邪神合力，对付鳄鱼形态的多脚邪神。

“这个……这里，究竟发生了什么啊……”

听到克莱因呆然的话语，莉兹贝特低声说道。

“……难道说，就像亚丝娜刚才说的那样，是在Jotunheim最新出现的屠杀系任务……可能
是这样吧？与人型邪神协力，歼灭动物形态的邪神……像是这种……”

“…………！”

听到这话的六人，不约而同地倒吸了一口气。

大概正如她所说。在进行任务的时候跟特定的MOB共同战斗并不是少见的情况。但是如果是
这样的话，任务报酬会是“圣剑Excalibur”就太奇怪了。既然那把剑是被封印在人型邪神
的根据地——空中迷宫里的话，一般是必须打倒人型邪神才能拿到手的报酬才对……想到这里，
我不由得抬起头来，仰望起被冰包裹的大型金字塔来。

不过，却什么话也说不出。因为，在冬奇背上最后方，本应没人的地方，突然悄无声息地出
现了光之颗粒并凝结起来——出现了一个人影。

身着披风似的长身衣衫。如同波浪般的金色长发从背部滑下直达脚旁。是个优雅又有着超然
美貌的，女性。

但从我，以及同样转过身去的克莱因口中，下意识说出的，怎么也不像是看到美女时说出的
话。

“哦…………”

“…………啊！”

不过这也不是没有原因的。因为女性的身高，少说也高出我们一倍，大约有三米多。

所幸的是，我俩说出的第一句话像是没有破坏神秘的巨大美女的心情似的，她仍旧保持着一
副静谧的表情，张开嘴来。传出的声音也与玩家的语气毫不相同，带着庄重的效果。

*

“我是‘湖之女王’兀儿德【ウルズ，Urd Urer Urthr，出自北欧神话，是诺伦三女神其中
之一，同时也是世界树（Yggdrasil）赖以灌溉的泉源。两个妹妹分别是贝露丹迪、诗寇蒂
】！”

*

巨大的金发姐姐，接着对我们这样说道。

“与吾之眷属结下羁绊的妖精们哟！”

嗯，眷属？我在心里犯起了嘀咕。这个词，如果指的是我们正乘坐的垂直飘在空中的冬奇的
话，那么这位美女应该也是栖息Jotunheim中动物型邪神的伙伴，应该是这样吧……

此时，我终于注意到了眼前这位名为“湖之女王”的巨大女性并不是百分之百的人型。垂到
脚部的金发发梢，如同触手般分离开来，从长袍的间隙可以看到其手脚上布满了珍珠色的鳞
片。她和冬奇同样是拥有奇怪形态的巨大生物，但暂时选用人类的姿态——给人以这种印象也
不足为奇。

“我和我的两个妹妹，有一个请求想要拜托你们。望你们将这个国度，从‘霜之巨人族’手
里救下吧。”

话听到这里，我又产生了一个疑问，这个巨大的美女究竟是“什么来头”。

视线集中也没有彩色箭头出现，看来不是玩家用幻惑魔法变成的。不过，这是没有害处的事
件NPC吗，还是攻击MOB的任务陷阱吗，或者是人类GM所操纵的虚拟体吗，这些都无从判断。

突然间，左肩上感到些许重感。同时传来了可爱的细语声。是唯。

“爸爸，这人是NPC。但稍微有些不同。不像一般的NPC只会做些固定的回答。其核心程序大
概是连接到了语言引擎模块。”

“……也就是AI化了吗？”

“就是这样，爸爸。”

脑海的一部分思考着唯的那番话的含义，同时继续倾听着女性的话。

NPC——“湖之女王兀尔德”，慢慢抬起那闪着珍珠色光泽的右手，指向宽阔的地下世界，说：

“以前这片‘Jotunheim’与你们的‘Alfheim’一样，受到了世界树尤古朵拉西
【Yggdrasil】的恩宠，被美丽的水流与绿色所覆盖。我们‘丘之巨人族’与野兽眷属们，
过着平静祥和的生活。”

说话的同时，周围被冰雪所覆盖的区域，景色悄无声息的发生了晃动，变得淡薄起来。出现
了第二重影像，就像兀尔德说的那样，是一片充满花草树木，并且充溢着清澈河流的世界。
比起地上的Gnome领地与Salamander领地还要丰饶。

更加令人惊奇的是，女王兀尔德身后存在的无底大洞“Great Hole”在另一重世界中根本不
是洞穴。而是闪着光泽满是水的广阔湖泊。并且，如今从世界的天盖处垂下的世界树的根部，
集中在一起直达湖泊，朝着四周扩散而去。

在水面茁壮生长的粗大根系上，建造着许多用原木制成的房屋，不，是街道。那景色，与地
上世界的“央都阿伦”很相似。

兀尔德放下右手，幻之风景也消散而去，Jotunheim变成了之前寒冷的冰之世界。她用满不
在乎，但又不知是不是错觉总觉得有些悲伤地的眼神看着我们，开口说道：

“——Jotunheim的更下层，存在着冰之国‘Niflheim’。支配着Niflheim的霜之巨人族的国
王‘Thrym【スリュム，Trymr，是北欧神话中的一名霜之巨人，名为索列姆】’，在某一天
伪装成大神的样子潜入了这个国度，将锻冶之神Wayland【ヴェルンド，V?lundr 问号处的
字母为 o上两点 估计是拉丁文】所打造的‘能将所有的钢铁与木头全部斩断之
剑’Excalibur扔到了该世界的中心‘兀尔德之泉’中。剑切断了世界原本就很粗大的根部，
那个瞬间，Jotunheim从尤古朵拉西那里获得的恩宠便消失了。”

兀儿德这次抬起了左手。再次出现了一副幻视景象，那里映出的美丽风景，让我们无暇说话
只是盯着观看。

直达巨大的湖泊——“兀儿德之泉”的世界树的根，断裂开来，慢慢向上收去，朝着天盖方向
不断缩小。根系上建造的城镇也一个不剩的全部崩坏。

同一时间，所有树木的树叶都落光了，草也干枯了，光线也暗了下来。河流被冻结，冰霜落
下，暴风雪肆虐起来。“兀儿德之泉”的大量湖水也在一瞬间就被冻结了，变成了一个巨大
的冰块，包在世界树的根上被拖到了空中。湖中栖息的大型生物，从冰块中剥离，啪啦啪啦
地落了下来。其中就有和冬奇一样的象水母生物。

世界树的根上升到了Jotunheim天盖或者说是Alfheim的地壳附近，其包裹的巨大冰块一半刺
入了天顶当中。那个冰块，毫无疑问就是现处于Jotunheim上空的伟岸的“冰之倒金字塔”。
冰块的最下端，冰锥的尖端处，可以看见闪耀着的金色光芒。毋庸置疑霜之巨人王Thrym投
下的，将世界树与Jotunheim这两个世界分离开来的剑，Excalibur。

所有的水都散去时，曾经美丽的湖泊，变成了一个无底的大洞。

兀儿德放下左手，幻之景象再次消去。但这次的景色却没有多大的变化。上空冰块的整体形
状大概是个直线状的迷宫。Excalibur就存在于那金字塔底部，这点我和莉法都确认过了。

“Thrym王麾下的‘霜之巨人族’，从Thrymheim中大举进攻Jotunheim，并修建了大量的城
寨关押被捕获的‘丘之巨人族’。Thrym王曾经在‘兀儿德之泉’内也就是现在的冰块内建
造的王城‘Thrymheim’，继续支配着这片大地。我和我的两个妹妹，从冻结的泉底逃了出
来，但却失去了原有的力量。”

兀儿德半闭上眼，讲述着这个大概已经接近尾声的故事。我们差不多把她是NPC，以及这个
故事只是游戏内的任务的这件事都忘记了，一言不发地仔细倾听。

“霜之巨人族，像是依旧没有满足，依旧想要把这片大地上，苟延残喘的吾之眷属全都消灭
掉。如果这样的话，我的力量就会全部消逝，Thrymheim就会上浮到地表Alfheim上去！”

“什……什么！这样的话，阿伦街区不也会被破坏吗！”

听到这些话，像是已经忘记了自己正处于潜行中的克莱因愤怒地叫道。并不是按照固定模式
进行回答的AI女王兀儿德，听到这话，点了点头，说：

“Thrym王的目的就是把你们所处的Alfheim也紧闭在冰雪之中，并攻到尤谷朵拉西的树梢上
去。得到那里的‘黄金苹果’。”

……有这种东西吗，我思考了一会儿，很快就有了答案。的确在世界树天边附近，有着强悍
的大鹫型Named MOB驻守的无法靠近的区域。难道说，黄金苹果就存在于那里。

兀儿德望向地面，出于伤感地皱起眉头，继续说：

“对于没有把我们消灭殆尽而发怒的Thrym王与霜之巨人将军们，终于开始利用妖精的力量
了。把Excalibur作为报酬吸引妖精，让他们去猎杀我们的眷属。但，Thrym王是绝对不会将
那把剑交给妖精们的。Thrymheim在失去Excalibur时，这片大地就会重归尤古朵拉西的恩宠，
他的城堡也会溶解并坍塌的。”

“诶……那，那个，也就是说把Excalibur作为报酬什么的，都是假的咯！？有这样的任务
啊！？”

听到莉兹贝特毫无掩饰的怒声，女王文雅的点头说道：

“恐怕，届时给予的是锻冶之神Wayland铸剑时，因多打了一锤从而破损并被丢弃的，外表
酷似Excalibur的‘伪剑Caliburn【偽剣カリバーン】’吧。虽然那剑也很厉害，但却没有
真正的力量。[fn:40]”

“好，好狡猾啊……身为王居然能干出这种勾当……”

莉法呆然的说道。兀儿德再次点了点头，深深呼出一口气来。

“那份狡猾也是Thrym王的强力武器。不过，他因为急于消灭我的眷属而犯下了一个大错。
其麾下的巨人们，为了前来协助被花言巧语欺骗的妖精们，几乎全部都从Thrymheim王城来
到了地表。如今，那个城堡的守备力量已经很单薄了。”

说到这里，我们终于明白了这个任务——不，是“女王的请愿”的内容。

湖之女王兀儿德，用那粗大的手臂直直指着上空“Thrymheim”，说：

*

“妖精们哟，请你们侵入Thrymheim，把插在‘中枢台座’上的Excalibur给拔下来吧！”
*** 第3节
“……总感觉，这事变得很不得了了啊……”

“湖之女王兀儿德”化作光之水滴溶解并消失了，坐在再次上升——这回速度相当缓慢——的冬
奇背上，亚丝娜率先这么说道。

紧接着再次陷入思考的诗浓，晃动着水色的尾巴，说：

“这个，是普通的任务……吧？但是，那也太大了……消灭所有的动物型邪神的话，这次地
上也会被霜之巨人族占领？”

“……是啊。”

点了点头，我抄起手，思索起来。

“但是，运营方没有通过升级，以及事件通知的话应该不会这么做吧？其他MMO游戏也是，
如果有‘BOSS袭击城镇’的话，一般来说至少要提前一周进行告知……”

嗯嗯，全员都点了点头。

随后，坐在我左肩上的唯飞了起来，停在半空中，用大家都能听到的音量，说：

“那个，虽然不是百分之百确定，只是个推测……”

究竟该怎么说呢，唯考虑了一会儿，随后继续说道：

“——这个‘Alfheim Online’与其他的‘The Seed’MMO游戏还是有着一个很大的不同点。
那就是运转游戏的并不是‘Cardinal System’的机能缩水版，而是旧‘Sword Art
Online’所使用的Fullspec副本。”

的确是这样。虽然不想提及，但ALO确实是一名执迷不悟，把旧SAO一部分玩家用作违法研究，
将原本SAO服务器完全照搬过来的人制作而成的实验台。当然驱使世界运转的自运行系统
“Cardinal”，与SAO拥有相同的性能。

唯看了看听着这些话的我们，继续说道：

“本来Cardinal System的缩水版就是对原系统进行删减形成的，但还是保留了些原机能。
其中之一就是‘任务自动生成系统’。通过网络模块，收集世界各地的传说以及代代传承下
来的古话，利用和改编那些固有名词和故事模式持续不断地创造新任务的任务生成器。”

“什，什么？”

克莱因把手托在长满胡须的下颚上，惊讶地说：

“也就是说，我们在艾恩葛朗特中完成的那些任务，全都是系统自动生成的？”

“……不都是这样，但我想大多数都是这种。在七十五层时，情报商的任务数据库内就已经
记载了超过一万个任务……”

当时，为了赚取资金而积极地接受任务的KOB副团长也摇起头来。身旁的西莉卡望着远方说：

“这也是偶然听到的。在三十几层时，有一个打倒戴着奇怪面具，手持锯条的食人魔的任务，
不管怎么杀掉它，下周依旧会出现在公告板上。那个传说的源头究竟是什么啊……”

关于这种记忆我也有很多，但再这么说下去的话到达冰之金字塔前这个话题会没完没了，最
终会成为旧艾恩葛朗特牢骚大会了，我咳了咳将话题转移回正轨来：

“这么说来，唯，这个任务也是Cardinal System自动生成的吗？”

“根据之前NPC的举动来看，这个可能性很高。可能是运营商的某些操作，让至今为止都停
摆了的自动任务生成器启动了也说不定。”

唯低着头，一副复杂的表情，继续说道：

“如果是这样的话，故事会展开到那种地步也是可能的。冰之迷宫浮到地面‘Alfheim’上，
阿伦崩坏，周边区域被邪神级怪物所占据……不，如果这样的话……”

稍微闭上嘴唇一会儿的AI少女，露出一副畏惧的表情，低声地说：

“……根据动态数据库的资料，现在的这个任务以及其涉及的ALO原型是北欧神话，也就是
说应该包含着‘最终战争’在内。不单单只是霜之巨人族攻占Jotunheim，Thrymheim，还会
有炎之巨人族从存在于更下层的名叫‘Muspelheim【ムスペル，Muspel Muspell，北欧神话
的火巨人】’的灼热世界出现，把世界树焚烧殆尽……这种事情……”

“……诸神之黄昏【Ragnarok】！”

由于喜欢神话这些古老传说，房间里有好多本这类书的直叶——莉法低声说道。大大睁开祖母
绿色的眼瞳，“但是！”这么叫道。

“那个……不管怎么说，游戏系统让其自行管理的地图全部崩坏这种事怎么可能……！”

这确实是件很不得了的事。但，唯却左右摆了摆头。

“……Original Cardinal System有着将世界地图全部破坏的权限。因为，旧Cardinal最后
的任务，就是让浮游城艾恩葛朗特崩坏。”

“…………”

这次我们只能默不出声，静静地呆在那里。

接下来开口的是到现在为止都在一直倾听着的诗浓。

“——如果，假使诸神之黄昏真的要发生，如果运营商有意的话，将这个服务器还原也不是不
可能的！”

“哦……哦哦，是啊，这样也是啊。”

克莱因嗯嗯的点了点头。“还原”简而言之就是用备份包覆盖如今的数据。主要是因为程序
的错误或者BUG，让玩家获得了预想之外的利益时实行的。如果这次Alfheim化为焦土，虽然
玩家个人的经验值以及道具都不会有影响，但谁也不会期望妖精乡整个大地都变成如同
Salamander领地‘邦恩特兰德【バーントランド】’一样。

但是，不知为何，唯这次却点了点头。

“运营商手动进行数据备份，并将其保管在物理分隔的介质上那就有可能……利用Cardinal
的自动备份更新，应该不仅能够还原玩家的数据资料，地域信息也包含其中。”

“…………”

全员再次沉默了两秒。突然克莱因“那么！”叫了起来，打开菜单窗口。不过，很快就“不
行啊！”地抱起头来。

“……你怎么了啊？”

听到莉兹贝特的问话，刀使一副不好意思的表情看着她。

“那个，呼叫GM，确认一下对方知不知道这个状况。可现在正处于人工服务时间外……”

“年末，星期天，而且是上午啊……”

我呼出一口气，仰望上空。

巨大的冰锥金字塔逐渐接近鼻尖。大约三百米高左右的冰锥，如果就这样突破地壳的话阿伦
可能会引发一阵骚乱吧——应该不止这样。至今为止，已经约有一半以上的人口搬迁到了世界
树上部构筑的“依古朵兰西·辛迪【イグドラシル·シティ】”城镇中，开始攻略起阿伦高原
的上级迷宫，作为各种族的首都同时也是交易市场，一到周末夜间就会十分热闹。还有就是，
那里对于我来说是个回忆感触颇多的地方。

“……既然这样就只有放手一搏了，哥哥。”

莉法将挂在右手上的奖牌高高举起。

此奖牌是“湖之女王兀儿德”给予的，上面镶嵌着一枚经过完美抛光的巨大宝石。不过，现
在抛光面六成以上都变成了漆黑色，没有一点反光。

当那块宝石全部染成漆黑时，就是地上的动物型邪神全部被猎杀殆尽的时刻，也就是兀儿德
力量完全消失之时。那时，“霜之巨人王Thrym”便会开始进攻Alfheim。

“……这样啊。本来我们今天集结于此，就是为了攻入那座城堡，夺取‘Excalibur’。守
卫单薄正如所愿。”

我点了点头，调出窗口，开始简短地操作起装备栏。

在背上挂着的，莉兹贝特武器店打造的长剑基础上，又将数日前在新艾恩葛朗特十五层BOSS
怪掉落的剑装备上去。

看见了很久没有见过的装备上两把剑的我，克莱因笑着叫了起来。

“哦，今年最后的大任务！漂亮地将其完成，就能登到明天的MMO tomorrow刊物的一个版面
了啊。”

虽然是即兴说出的话，但莉兹贝特也跟着叫了起来。全员“哦——！”进行了附和，脚下的冬
奇，也猛地扇动起翅膀，“咕噜噜！”地啼叫起来。

“再等一会儿哟，冬奇。绝对会让你夺回自己的国家的。”

朝向正前方，腰部微微弯曲，拔出长剑。这时候，两扇冰之大门已经高高的屹立在手握武器
的我们前方。

要是以前的话，在这附近必须得先和守卫进行交战不可，但正如兀儿德所说，这次门很快就
打开了。相互交流了下眼神，很快便组成了由我与克莱因、莉法担任前卫，莉兹贝特与西莉
卡担任中卫，后卫交由亚丝娜与诗浓负责的阵型，随后我们踏上了冰之大地，朝着巨大城堡
“Thrymheim”冲去。

★　　★　　★

ALO中一支小队的上限人数与其他游戏稍微有些不同，为七人。

其他游戏几乎都是六人或者八人，也不知道是出于什么理由。顺带一提的是，联合部队的上
限为七乘七也就是四十九人。获得的金钱由自动分配机能进行分配，如果手动计算的话会变
得很麻烦的。

不过，对于这七人的上限，光用好友组成大概也只会占用五人。我、亚丝娜、莉兹贝特、西
莉卡、莉法，全员都是高中生，而且四人在一所学校，我和莉法又住在一起，因此集结起来
很容易。

第六、第七个人则是不确定的，由公司职员克莱因、咖啡店兼酒吧吧主艾基尔、很忙的高级
官员大人克里斯海特、莉法的真实世界好友蕾鵼，在他们方便的时候加入。蕾鵼也是高中生，
但在以前的“依古朵兰西·辛迪【イグドラシル·シティ】攻略作战”中，被风妖精领主朔夜
赏识因此被挖角，现成了领主馆成员并常驻苏依露城，所以能够一同前往Sylph领上空的艾
恩葛朗特的时间有限。

这次为了凑够人数，能让GGO中的熟人弓箭手——写成弓箭手读作狙击手的诗浓加入也是件很
高兴的事，但这还是无法解决队伍的一大问题所在。

那就是法师太少了。常驻队员在魔法技能上很积极的就只有Undine的亚丝娜一人，而且她还
为了能够提升细剑技能，掌握的魔法就只有支援、恢复系。莉法虽然是魔法剑士，但能用的
也只有战斗用妨碍系咒文与回复量不多的治愈魔法。西莉卡虽然稍偏向于魔法系，但主要会
的也是些支援系，莉兹的技能多半都是锻冶系，艾基尔三成是商人系，而我和克莱因则是全
部加到物理近战系，也就是“硬冲”派。至此为止，能够使用攻击咒文的人没有一个。

偶尔，使用黑暗魔法谜之能力构成的Sylph短刀使蕾鵼，以及使用让领主都称赞的冰冻系魔
法的克里斯海特会作为第七人加入，团队的战斗实力能够得到很大的提升，果然没有火力输
出型法师真是坏处颇多啊。

但这也是没办法的。因为我们大多数人都是从SAO——排除一切魔法的剑之世界中移居过来的。
我是单手直剑，亚丝娜是细剑，莉兹是战锤，西莉卡是短剑，克莱因使刀，艾基尔用斧，莉
法的长剑与诗浓的弓，很早以前它们就不单单只是武器了，说的夸张一点就是自身存在的证
明。如今要捡起那些被丢弃的魔法技能也是不现实的。深知做那些事毫无效率，因此干脆怀
着战斗方式以物理攻击为主的这份自豪，战斗到现在——

既便如此，也遭遇过许多尴尬的局面。

★　　★　　★

“糟糕了，哥哥，金色的家伙，物理抗性太高了！”

左侧的莉法用很快的语速说道。

就在我转过身去，还没来的及回话时，那个金色的家伙便高举起了战斧。

“冲击波攻击，还有两秒，一、零！”

坐在我头顶的唯，用小小的身体猛地大声说道。倒数结束时，前卫、中卫五人朝左右分散开。
轰然挥下的斧刃，砸在了其间隙，产生的冲击波径直朝前飞去，猛地击打到对面的墙壁上。

突入冰之王城“Thrymheim”，已经过去了二十分钟。

正如“湖之女王”所说，迷宫内敌影相当少。通路上与杂兵MOB遭遇近乎为零。楼层的一半
中BOSS都不在。但守在通往下层阶梯前平台处的楼层BOSS依旧存在，依旧有着之前让我和亚
丝娜、直叶一同发出“不可能吧！”这话的压倒性攻击力。

即使如此，我们还是打倒了以前让我们束手无策第一层的单眼巨人BOSS，并穿过第二层，再
次抵达了BOSS房间——

在此等待我们的是牛头人身的巨人，也就是“牛头人”型大型邪神。而且是两只，左边闪着
金光，右边全身乌黑，双方的武器都是有着如同餐桌一般大小刀刃的战斧。

完全不会施展魔法攻击，最初我认为这比落满冰锥的上一层的BOSS“独眼巨人”要有趣多了，
但还是有一个问题。看起来，黑色家伙的魔法耐性，金色家伙的物理耐性分别被设定成了很
高的数值。

那就干脆一口气做掉黑家伙，之后再强攻金色的那个，得出这种作战也是理所当然的。但没
想到这两头牛却有着意外的羁绊，在黑色的HP减少时金色的家伙会不顾一切地攻上来，趁此
机会黑牛退后缩成一团，运用冥想能力什么的进行HP回复。

被他们搞了这么一回后，那就干脆趁黑牛冥想期间击中攻击金牛，但那家伙的物理抗性太高
了，HP几乎打不动。当然我们的这边的HP也是一样，虽说能躲过即死级大招，但也会受到范
围伤害，只靠亚丝娜一人进行恢复也支撑不了多长时间，这点我们都很明白。

“桐人，按照这种步调，还有一百五十秒MP就见底了！”

听到身后亚丝娜的叫喊声，我举起握在右手的剑作为回应。

打持久战时，如果治疗者的MP耗尽的话，接下来的就是队员逐个被击破——也就是团灭。即便
生存一人，将残存之火一个一个复活也是不可能的，那需要很多的时间。如果全灭的话，当
然会返回央都阿伦的存盘点。问题是，不知道还有没有剩余那么多的时间——

就像读出了我心中所担心的事情，身旁的莉法再次低声说道：

“奖牌，差不多七成都黑了。像是没时间‘死去重来’了。”

“我知道。”

点了点头，我深吸一口气，挺直腰。

如果是旧艾恩葛朗特的话，二话不说会下达撤退命令。在那个世界，“赌上可能性”的行为
不能被允许的。但如今的ALO并不是死亡游戏，就算Cardinal System让Alfheim全境化为焦
土，到那时我们应该做的还是“享受游戏的乐趣”，其中也包含着相信自己跟伙伴的力量的
意思。“各位，既然如此，大家能做的事就只有一件了！”

避开金牛的斧头攻击，确认后方黑牛的HP正在进行恢复，我大声叫道。

“事已至此也只能碰碰运气了，大家将剑技集中到那只金牛身上，打倒它。”

“剑技【Sword skill】”。

这也是曾经的SAO最具有SAO特征的游戏系统。

今年五月，在艾恩葛朗特加载的同时，运营商将剑技导入到了ALO中。不过还是做了些许修
改，其中之一就是“追加了属性伤害”。如今的上级剑技，不再是通常武器攻击带来的物理
属性，而是具备了地水火风圣暗的魔法属性。正因为这样，物理耐性高的金牛应该也会受到
伤害。

当然，这也是有风险的。连击数多的剑技，在施展后会有很长的硬直时间。那时如果受到战
斧直击的话，HP会被全部清空。如果是横向范围攻击的话前卫和中卫会全部阵亡。

不过伙伴们也像是明白了这点，很快都点了点头。

“上吧！就等你这话了，桐人！”

右侧的克莱因将爱刀摆出大上段姿势。左侧的莉法将长剑架在腰部。身后的莉兹，西莉卡分
别握紧了战锤以及短刀。

“西莉卡，反击的‘气泡’交给你了！——二、一，就是现在！”

盯着金牛一举一动的我下达了指示，西莉卡大叫道：

“毕娜，‘泡泡吐息【Bubble Braze】’！”

一般来说，对宠物下达的命令，不管是什么成功率都不到八成。不过我却没有看到过毕娜无
视西莉卡指令的情况。这次也是，飞在西莉卡上方的小龙按照期望那样，猛地张开嘴，突出
七彩色的气泡。

在空中飘动的气泡，撞到了挥舞着战斧施展大招的金牛鼻尖上。魔法耐性低的金牛，只用了
一秒便被幻惑魔法所迷惑，停止了活动。

“GO！”

配合着我的大叫声——除开亚丝娜的所有人的武器，都迸发出了五颜六色的炫目光斑特效。

★　　★　　★

浮游城艾恩格朗特的创造者——茅场晶彦，到底是为了什么才把“独特技能”这种超常规的力
量写入系统的呢？

那其中蕴含的真正意义，直到现在我还是无法理解。

如果只是存在于他拥有的“神圣剑”内的话倒是不难理解。最强公会血盟骑士团的领队、冲
在无数玩家之前高举绝对防御之十字盾的圣骑士。只要让这些传说按他所设计的剧本在九十
五层里完全反转过来，那个男人就会成为比有史以来任何一个RPG里的最终BOSS更穷凶极恶
的魔王了吧。

在那一瞬间，“玩家没行动主线故事却仍在继续的MMORPG”这个矛盾就会具体化。
An·Incarnating·Radius——具现化的世界。为了实现这种有如创造世界一般的目的，他无论
如何都得保持着最强的圣骑士这个形象。即便依靠的是“神圣剑”、“不死属性”还有“超
级辅助”这些非常规的力量。

但是，如果是这样的话，独特技能只要有神圣剑一种就够了。MMO里边，能与魔王正面对战
的唯一的勇者是不被需要、更是不应存在的。当然，让玩家之间出现明显的战力差异并没有
好处——这种理由也是建立在公平的规则之下才有意义的。

而他却把“二刀流”，恐怕还有其他的几个独特技能给予了玩家。这种超越了规则的力量会
促进力量差距的发展，让世界的发展偏离他所执导的剧本，这种事他应该也是明白的。事实
上，我在跟希兹克利夫打赌让亚丝娜退出公会的那次决斗里，如果没有“二刀流”这个技能
的话，那家伙也无需使用超级辅助就能取得胜利。而如果没有体会过那一刻的违和感的话，
我就根本不会在七十五层时觉察到希兹克利夫的真面目。正是因为给予了我独特技能，他想
象的世界——故事才会在原本的四分之三的地方迎来最终一幕。

ALO世界里，在少有地握起两把剑的时候，我总是不由得分出一份心神去思考。这到底是为
什么呢。

而同时我也感到少许的罪恶感。当然，在七十五层打倒了希兹克利夫——这件事我绝对不后悔。
如果不在那时把游戏通关，事件的牺牲者总数必然会增加。而且其中可能包括我最重要的人
们，甚至还可能是我自己。

但无论如何，我都无法抑止这种想法。那种结局真的圆满了吗？我们不是应该登上艾恩葛朗
特的最后一层，然后在那里跟魔王希兹克利夫交战的吗？不，并不是“应该如此”，只是我
想要这么做，也就是我的任性而已。那是最糟糕的自我主义。所以，不管在什么情况下，我
都对在Alfheim里装备两把刀这件事带有抗拒心。

——虽说如此，至少这个世界里并不存在独特技能。聪明的新运营者们，投入大量人力测试了
天文数字般的剑技，把有着怪异条件的几个——传闻似乎是十个——技能从系统中删除掉了。

所以我已经再也用不出原来的二刀流剑技，“Double Circular【双重扇形斩】”跟“Star
Burst Stream【星爆气流斩】”之类的招式了。但我却能不依靠系统辅助百分之九十九地再
现那些招式，在对人·对怪物战的实验里也证明了其有效性，但遗憾的是现在就算用出来意
义也不大。再怎么说，靠自己重现出来的二刀流剑技并没附加魔法属性，对于物理耐性极高
的金色牛头人之类的怪物是不起作用的。

但是，“装备两把刀的情况下用单手剑剑技”也有着一种——按莉法的说法就是“在竹刀尖端
装上铅块就能让对方受到百倍的身心重创”的优势。

★　　★　　★

小龙毕娜的“泡泡吐息【Bubble Braze】”让金牛的大招出现了瓦解，面对着大约麻痹了一
秒钟的金牛，我从正面，克莱因从右侧，莉法从左侧，莉兹与西莉卡分别在左右两侧进行蓄
力。

“呜……哦哦！”

发出吼叫，将各自习得的最高级剑技施展而出。克莱因的刀被火焰猛地包裹，莉法的长剑被
疾风缠绕并发出闪光，西莉卡的短刀迸发出水的飞沫，莉兹的战锤放出雷光并发出鸣叫。以
及从更后方持续飞来的闪着光泽的冰之箭，精准的击中牛的鼻头要害处。

同一时刻，我将被橘红色光芒包裹的右手剑全力击出。

从高速五连刺转为下斩，随后上挑，再全力挥下。单手剑八连击剑技“Howling Octave【蜂
鸣八度】”。属性是物理四成，火焰六成。在单手剑中算是相当强的技能。当然，技后硬
直——Skill Delay也是很长的。不过。

“…………”

伴随着无声的咆吼，我将意识从使出了极限攻击的右手中抽离。努力去想象——把脑部传送到
AmuSphere的运动命令，一下子被全部截断的样子。然后开始传送下个命令，这次是只集中
到左手上去。

右手被辅助系统自动操纵着，释放出了最后的斩击。就像要和右手平行似的，左手也动了起
来，剑在后方画了个巨大的圆。刀刃上释放出了蓝色的闪电。

右手剑深深砍进了牛头人裸露的腹部。本来这时出于Delay，我的虚拟体应该产生硬直。不
过，水平发动的左手剑技却覆盖了这个Delay。画一条弧线的水平斩击，将牛头人的右腹切
开。

自己的身体，不，左脑和右脑，像是分别在进行不同的思考似地，让我感受到了前所未有的
违和感。不过如果这时意识统一的话，剑技就会停下来的吧。任由右手技自动收束，把意识
全部集中到左手剑上。

水平斩击埋入敌方虚拟体的剑，发生了九十度的回旋。我按下剑柄，刀刃弹起垂直将其腹部
切开。随后又将刀刃拔出，从上向下垂直斩下。对大型怪物有效的三连重攻击，“Savage
Fulcrum【野蛮支轴】”。物理与冰冻属性各占五成。

就在左手准备施展出致命一击时——

我再次切换了脑部的出力区域。

时机过早或是过晚技能都不会发出的，虚拟体进而会产生硬直。能够允许的误差只有不到零
点一秒。三个月前，我偶然间发现了这个连携现象，为此进行了大量的练习，但成功率到现
在都只有五成以下。可能是出于怀着一份祈祷吧，右手剑又开始舞动了起来。

“咕……哦！”

借着短暂的气势，刀刃闪出水色光泽。用差不多反手的姿势垂直下砍，随后是上下连携，最
后则是使出全力的上段劈斩。高速四连击“Virtual Square【垂直立方斩】”——

至此，我已经施展了合计斩击数十五下的连续技。这已经是逼近二刀流高级技能的数量了。
由于持续吃下这些攻击的敌人也处于Delay中，因此没有防御的必要。

Virtual Square开始释放时，伙伴们的技能硬直也结束了。

“呜哩呀啊啊啊啊！”

随着克莱因的大叫声，第二波的集中攻击将金色牛头人包裹。迷宫的地板发出微微颤动，敌
人庞大的HP槽被很快的削减。

最后的上段斩施展而出时，我企图用出连自己都毫无确信的第四次“剑技连携”。

单手剑技并不是所有的技能都能连接在一起的。根据系统辅助进行活动，非攻击侧手腕的活
动，必须要和下一个技能的初始模式几乎一致才行。

右手施展出Virtual Square时，左臂后弯，肩头抬起。就这个身体稍微有些弯曲的动作，就
完成了“将剑像是抗在肩头似地蓄力，同时另一只手向前伸出”的姿势。左手剑发出了深红
色的特效。如同喷气式飞机般的轰鸣声从后方靠近，我的手臂以超高速击出。单发重攻击，
“Vorpal Strike【魔剑侵袭】”，物理三成，火焰三成，暗系四成。

吱嘎啊啊啊！爆发出强烈的轰鸣声，剑身全部没入敌人的下腹。比我大五倍的巨大身体向后
猛地退去。此时，克莱因一行人的第二次剑技也结束了。这次，我和大家一样，虚拟体陷入
了长长的Skill Delay中。

金色牛头人的HP，变成了红色并继续减少——

到了只剩两成时停了下来。

长着巨大犄角的牛头，露出了狰狞的笑容。从之前的硬直了恢复了过来，将战斧水平握起。
高速回旋的范围攻击，被击中会立即死亡。意识虽然在不断的发出“后退！”的命令，但身
体却不停指挥。战斧发出凶暴的光辉，龙卷风从它的脚旁卷起……

“不……要啊啊啊！”

此时传来了一声尖叫。我的右侧，有一阵青色的疾风闪过。右手握着的细剑，以眼睛无法看
清的速度进行了五次刺击。施展的是高级细剑技，“Neutron【中子冲击】”。物理两成神
圣八成的属性伤害，将挥舞着战斧的金色牛头人的HP一声不响的全部夺去。

邪神停止了活动。不远处，用冥想将HP全部恢复的黑色牛头像是在夸耀自己的胜利似的将大
斧挥起。但，就在这之后，一直守护着黑牛的搭档发出了的尖锐的惨叫声——随着硬质的音效，
巨大的身体朝着四周爆裂开来。

…………诶。

从硬直状态中解除的我们七人一齐将视线移到了，眼睛像是要瞪出来的黑牛身上。

“……好的，接下来就是你这家伙了！”

克莱因用很快的速度水平摩擦着牙齿，这样说道。
*** 第4节
刀使克莱因对着因忧郁与愤怒乱舞大招的黑色牛头人邪神使出致命一击后，毫不理睬敌虚拟
体爆炸地点掉落的道具，转过身来叫道：

“我说，桐人啊！你刚才用的那是什么啊？”

我很明白他所指的就是装备了单手剑两把，施展而出的连携剑技攻击，但要将技能组合从头
开始说明也太麻烦了，我将内心想法原原本本体现出来，挂起一副显得极度麻烦的表情，说：

“……不说不行吗？”

“当然不行了！我不能当做没看见啊！”

向我走来的克莱因将懒散的胡须推了推，用极其简洁的话语答道。

“系统外技能哟，‘Skill Connect’。”

哦，西莉卡、莉兹以及诗浓发出惊呼声，亚丝娜不由得用手指按着右侧太阳穴，念叨道：

“呜……刚才这个反应，总觉得似曾相识啊……”

“那是错觉吧！”

我耸了耸肩，拍了拍明明是负责后方支援职务，却突然冲上来施展了一记犀利的特攻，并将
金牛亲手击倒的治疗师的背，大声地说：

“好，没有时间闲聊了。莉法，时间还剩多少？”

“啊，嗯。”

随着一声清脆的音符，长剑收到后腰的剑鞘内，莉法低下头将奖牌拿起。就算是离她有数步
的距离，也能看见上面镶嵌的宝石几乎失去了光泽。

“……按照这种速度，大概也就一小时或者两小时吧。”

“这样啊。——唯，这个迷宫是全四层的构造吧？”

我紧接着问道，坐在我头上的小妖精做出了麻利的回应：

“嗯嗯，第三层的面积大约是第二层的百分之七十，第四层就只有BOSS的房间。”

“谢谢！”

用右手指尖摸了摸唯的头，并很快地分析了一下如今的状况。

此刻，在遥远下方的Jotunheim的大地上，接受了“霜之巨人族”任务前来猎杀动物型邪神
的玩家们应该还在不断的增加。一小时这个数字大概也只是个理论值了。最终BOSS——大概就
是Thrym王本人吧——如果与之战斗需要三十分钟的话，必须用三十分钟通过第三层，踏上第
四层不可。

如果再能有多点时间的话，就能向区域内的玩家们说明状况，让他们放弃眼前的任务，一同
加入迷宫的讨伐，但现在根本没时间回到地面。就算成功说服了领主增派援军，那也得从遥
远山脉尽头的首都那里集结部队，向阿伦高原移动，突破阶梯迷宫抵达Jotunheim，当他们
抵达时，恐怕太阳都落山了。

也就是说，只能靠我们七人应对这个绝望的状况——先不说这些，根据Cardinal的任务自动生
成机能，如果“女王兀儿德”的任务失败，Thrymheim城上浮，大概各处就会宣布
“Ragnarok”任务的开始吧。那样的话，毫无疑问就只能怪那个性格恶劣的创造者了。

这些暂且不论——

“……如果那样的话，那就只能将那个不认识的邪神之王，咚咚地打倒了！”

莉兹贝特咚地拍了下我的背，大声说道，其余所有人都“哦！”地做出了回应。这些人大概
已经接受了这个毫无章法的任务了吧，我这么想到，并点了点头。

“——好，所有人的HP、MP都回满了。那就赶紧扫平第三层吧。”大家再次一同说道，同时七
人猛踏着地面，朝着BOSS房间所在的冰锥下方冲去。

★　　★　　★

和唯说的一样，第三层比起第二层果然要狭窄很多。倒金字塔的下方会这样也是当然的，不
过虽然通路很狭窄，但依旧有很多岔路。按照一般攻略的话，为了防止迷路应该是先顺右走
再顺左，但我的头顶上有着一个连最新型的智能导航系统都自愧不如的导航妖精正坐在那儿。

用禁招进入地图数据库将地图解禁，我们依据唯的指示在曲折的道路中全速前进。接下来出
现的，杠杆，齿轮，还有踩踏开关的谜题也没怎么思考就这么解决掉了。假使有人从外面看
到这个情形，可能会将其认为是最速通关表演吧。

包括途中的两次中BOSS战，我们也仅用了十八分钟便抵达了第三层的楼层BOSS房间。在这里
等待我们的是有着上层牛头人的两倍体格，修长的下半身就像蜈蚣一般左右分别有十只脚的，
面相十分凶恶的巨人，不过其物理耐性却很普通。当然其攻击力却也是很高，持续成为目标
的我和克莱因才中了几下HP槽便红了，不管谁死可能都会导致团灭，这场能让人胃部抽筋的
战斗就这样持续了九分钟。既便如此，莉兹、西莉卡、诗浓还有毕娜还是很努力地将巨人的
脚一只只切掉，最后我用“Skill Connect”使出多重剑技了结了无法动弹的BOSS。就用这
种雪崩般的势头攻入了第四层。带着击败Thrym王，让其王城化成二进制数据的气势踏上通
往最终BOSS的房间的通路，此时在我们眼前，出现了一个无法判断的状况。

那便是在墙边的一个用冰锥搭建而成的牢笼。

从地面到天盖，如同钟乳石一般的冰之栅栏内有一个人影。并不是巨人的尺寸，由于倒在地
面上，无法辨认其身份，但其身高大概与Undine族的亚丝娜一样。

肌肤如同刚落下的粉雪一样白皙，深金茶色的长发。透过覆盖在身体上的极少布料能够窥视
到的胸部尺寸，虽然基于政治立场我不能这么说，但确实相比起在场的五名女性都是压倒性
的。柔弱的双手双脚上都被粗犷的冰之枷锁禁锢。

这种预料外的光景让我们停下了脚步，不知是不是觉察到了这点，趴在地上被囚困的女性，
肩头微微一震，青色的锁头发出声响，她抬起脸来。

眼睛的色泽也跟头发一样的金茶色，其脸蛋如果换做是玩家虚拟体的话，必须是有着相当高
的幸运值或者是用压倒性的财力持续购买才能有的俏丽面容。而且是一张在游戏内很少见的，
洋溢着西欧风韵的美貌。

长长的睫毛上下眨了一下，女性用纤细的声音说：

“拜托……把我……从这里，放出去…………”

我揪住被吸引到冰之监牢处的刀使的头巾末端，就这样把他拖了回来。

“是陷阱。”

“是陷阱哟。”

“是陷阱吧。”

后两句话是诗浓与莉兹的话。

挺直身体再次望去的克莱因，露出一副微妙的表情搔了搔头。

“哦，哦……是陷阱，啊……这是陷阱，吗？”

看着不肯轻易死心的刀使，我小声的问了问唯。坐在头上的妖精，很快做出了回答。

“是NPC。和兀儿德一样，是连接着语言引擎模块的。——但有一点不同。这个人的HP处于
Enable状态。”

Enable，说白了就是“有效化”。通常来说，任务中登场的NPC其HP槽是无效的，也就是说
不会受到伤害。但护卫任务的对象却是例外，或者说这个NPC实际上是——

“是陷阱哟。”

“是陷阱吧。”

“我想是陷阱。”

亚丝娜、西莉卡、莉法同时说道。

我拍了拍眉毛摆成八字，眼睛睁大，撅着嘴的一副奇怪表情的克莱因的肩膀，用很快的语速
说：

“当然也有可能不是陷阱，但我们也没有工夫去试了。必须尽早一秒的感到Thrym所在地。”

“哦……哦，嗯，嘛啊，是这样啊，嗯。”

克莱因微微点了点头，视线从冰之监牢处移开。

但就在我们朝着眼前的阶梯深处走去时，声音再次从身后传来。

“……拜托了……谁来……”

——说实话，我也想去救。NPC虽然是系统自动生成的，但我并不把它们看做是单纯的活动物
体，而是生长在这个世界的居民。如果是在一般的任务中，我一定会救下那名女性，带着她
一同前行，在故事的结尾我的这个一时兴起的举动大概会在背地里被人说成“呜哈哈哈那个
笨蛋家伙”吧。但是，如今不是背负这种无用的风险的时候。这一点克莱因一定也——

整齐划一向前行进的其中一个足音出现了凌乱，与冰之地面产生了摩擦。

转过身去，长身的瘦弱刀使，双手紧握，深深低下脸停了下来。那布满无精打采的胡须的嘴
中，挤出了低低的声音。

“……这是陷阱。陷阱，我明白的。——但是，即使是陷阱。我知道那是陷阱……”

啪，克莱因抬起头，可能是我的错觉吧，他的眼角处渗出了薄薄的泪水。

“即使这样我啊……无论如何，不能把那人留在那里！即使……这个任务失败了……阿伦崩
坏……我也要帮助她，这就是，我的生存方式——拥有武士道精神的人哟！”

随后他猛地转身，回到冰牢处，望着他的背影，在我们胸口涌动的两种感情——也就是——

……笨蛋啊。

不过——

克莱因好酷啊！

再怎么想，也无法判断出怎么做才是对的——这是个永远得不出正确答案的问题啊。

望着双手支撑着身体的囚困女性，克莱因叫喊着“现在就来救你！”握上了左腰的爱刀。下
一个瞬间，居合系剑技“旋风【ツジカゼ】”施展而出，冰锥监牢被横向劈开。

★　　★　　★

从冰之监牢中救出的美女，瞬间变成了巨大的怪兽朝我们袭来——幸亏她不是这种忘恩负义之
徒啊。

克莱因的刀发出四次闪光，斩断了束缚双手双脚的冰之锁链，美女无力的抬起脸，低语道：

“……谢谢，妖精剑士大人。”

“可以站起来吗？没受伤吧？”

蹲下，伸出右手的克莱因已经完全“入戏”了。嘛啊，反正现在也还处在VRMMO的任务之中，
投入到故事剧情中也是正确的态度。我们也是，接下了女王兀儿德的邀请，全力进行着挫败
Thrym王野心的目的，退一步来说我们和克莱因完全一样。虽然完全一样，但，该怎么说呢——

“诶诶……没关系的。”

点了点头，站起来的金发美女，很快就变得轻松起来。作为绅士克莱因还是用手扶住她的背，
进而问道：

“这里离出口很远，要一个人回去吗，小姐？”

“…………”

听到这话，美女闭上眼睛沉默了一会儿。

Cardinal System具备的“自动应答/言语模块引擎”，简而言之就是：当玩家说出A的时候
则回答B，这样的一个有着超复杂的情景对应列表的系统。因为具备着高度的预测机能以及
学习机能，所以跟系统相连接的NPC，在某种程度上跟玩家作出很自然的对话——当然只是模
拟的——也是可能的。

这种模块虽然有了几点突破，但能拥有人类的“情感”，拥有无限的“智慧”就只有坐在我
头上的小妖精唯，如今能自动应答的NPC，还远远不及唯的程度。但也比固定应答的NPC无论
玩家说些什么，总是用相同的台词回复对方要强许多，既便如此无法识别玩家言语的场合也
有很多，那时玩家就必须寻找“正确的提问方式”不可。

这回金发美女的沉默大概也是这样吧，出乎意料的是NPC在克莱因询问新的问题之前便抬起
了头，说道：

“……我不能从这座城池逃走。我是为了取回被巨人王Thrym盗走的一族之宝而潜入这个城
内的，但却被第三扇大门守卫发现而抓了起来。如果不取回宝物，我是不会走的。请无论如
何，把我一起带到Thrym王的房间去。”

“哦……嗯……嗯……”

这次“按武士道方式生存的男子”克莱因没有立即回答，反而是很苦恼的念叨道。从数米之
外的地方看着他的我的身旁，亚丝娜低声说道：

“感觉，这展开有些可疑啊……”

“是啊…………”

一副害羞表情的克莱因将视线从美女面前挪开，望着点头回答了亚丝娜的我，说道：

“喂，桐人哟……”

“……啊，真是的，我明白了，明白了。既然都这样了也只能把这分支走到底了。毕竟不是
百分百肯定这是陷阱嘛。”

我这么回复道，克莱因笑了笑，对着美女高兴地说：

“哦耶，被接受了哟小姐！从现在开始我们便是一莲托生的伙伴了，一同去把Thrym给打倒
吧！”

“谢谢你，剑士大人！”

金发美女握着克莱因的手腕蹲了下来，同时只有队长能够看见的我的视野中，出现了一个是
否同意NPC加入的弹出窗口。

“毕竟从唯那里问出些微妙的事情的也是我呢。”

我嘟囔着，同时按下YES按钮。视野左上，伙伴的微型HP/MP槽的位置，追加了一个第八人的
格子。

美女的名字叫做“Freyja”。读作芙蕾娅，像是从哪里听过似的。HP与MP都相当的高，特别
是MP数值十分惊人。大概是法师类型的吧。

如果她能一直到最后都还作为伙伴帮忙的话，应该会有不少的帮助吧，这么想着的我瞥了一
眼挂在莉法胸口的奖牌。多边形的宝石，差不多九成都被染黑了。剩下的时间，照先前的情
况来判断，只有三十分钟了吧。我深吸一口气，说：

“按照迷宫的构造，下了这个阶梯大概就是最终BOSS的房间了。虽然会比之前遇到的BOSS都
要强，但我们也没工夫念叨这些，只能将其击倒了。序盘时，摸清BOSS攻击方式之前都是以
防御为主，反击的时机到了会给出指示。BOSS的血槽变成黄色，或者变成红色时，要注意攻
击方式的转变。”

我挨个看了看点了点头的伙伴们，鼓足力量大声说道：

“——最终战，让我们火力全开把那家伙踢飞吧！”

“哦！”

这个任务开始以来的第三次呐喊，坐在我头上的唯，西莉卡肩膀上的毕娜，以及更名叫做芙
蕾娅的NPC金发美女也都一起呐喊了起来。

★　　★　　★

往下的阶梯，从途中开始慢慢变宽，周围柱子上的雕像以及装饰物品也变得华丽起来。“靠
近BOSS房间地图数据也会变得庄重起来”，这个从艾恩葛朗特以来就有的传统，看来这里也
好好的延续了下来啊。

道路的尽头，是被两匹狼雕像所夹的厚实冰晶大门。这里就是Thrym王的玉座之间了吧。虽
然确认了周围没有机关，但还是谨慎地朝门靠近。

就在踏入离门扉五米内的范围时，大门便左右自动打开了。里面的冷气，以及难以用言语表
达的压力吹了出来。亚丝娜重新为大家施加了支援魔法，芙蕾娅也加了进来，将全员的HP大
副提升并加上了许多未知的支援魔法。

HP/MP槽下方并列排列着几个支援标记，所有人用眼神进行了交流。点了点头，朝着门内冲
去。

内部，是个纵横方向都很长的巨大空间，墙壁与地板都是相同的青色冰晶，冰做的烛台上晃
动着让人不舒服的青紫色火苗，遥远的天花板并列挂着几个相同颜色的枝型吊灯。不过最先
吸引我们视线的是，从左右的墙壁一直连到房间深处的，数不清的耀眼反射光线。

黄金、金币以及由黄金制成的装饰品，剑、铠、盾、雕像、家具堆积成山，数也数不清。由
于房间深处光线昏暗，完全无法看清全部宝藏的规格。

“…………总额，得值多少Urud啊……”

队伍中唯一一名经营着店铺的莉兹贝特呆然地说道。不过，我却在脑海中想着“早知道就把
物品栏清空就好了！”，但这话没对其他人说。

站在队伍右侧，克莱因这次也不知是不是出于武士道的冲动驱使，朝着宝山走了数步。不过，
就在他想要再向前迈出脚步时——

*

“……有苍蝇飞进来了啊！”

★　　★　　★

广阔而昏暗的内部，传来了如同能够震动地面般的重低音话声。

“我听到了嗡嗡嗡的惹人烦的振翅声。哼，就让我在你们做坏事前，把你们个个击溃吧！”

咚！地板震动。咚！咚！震动逐渐靠近，就像是要把冰之地面踩碎似的，声音不断的逼近。

终于，在闪电可以攻击到的范围内，突然出现了一个人影。

巨大——并不能用这个词来形容。其身高数倍于在地上徘徊的人型邪神以及到刚才为止在这个
城堡内交战过的BOSS邪神。高高在上的头部，也不知道到底距离地面有多少米。即便我使劲
全力一跳，也无法抵达那如同巨木一般的腿部膝盖处。

肌肤的色泽，是如同铅一样的暗青色。腿以及手腕，缠绕着不知道要剥下多少只大型野兽才
能制作而成的黑褐色毛皮。腰上绑着每一块都如同小船一般大小的板筋铠甲。上半身虽然赤
裸，但那结实的肌肉就像是任何武器都砍不进去似地。

强壮的胸脯上，落着一缕很长的青色胡须。上面的头部，没入阴影之中只能看清轮廓。不过，
戴在额头上的金色王冠，以及那散发出让人胆寒的青色眼窝，都在黑暗中闪现出鲜艳的光泽。

旧艾恩葛朗特，为了遵守一层迷宫只能一百米高的这个绝对限制，迷宫区的BOSS房间也不能
高于天井，不管什么样的BOSS其纵向尺寸是要受到控制的。所以，我在迷宫区看到如此之高
的敌人的经验可以说是没有。不能飞，究竟要怎么战斗啊。挥剑作战要想砍到它就要费很大
力气。

正当我思考这些时，高大的巨人——虽然我不想用这种双重表现来描绘它——又向前踏出一步，
用那如同敲打铜锣般的声音，不屑地说：

“呵、呵……原来是Alfheim的苍蝇们啊，受到兀儿德的唆使潜入到这里来了啊。怎么样啊，
小矮子们。只要告诉我那女人的所在之处，你们就能拿走这个房间里的一件黄金器具哟，嗯
嗯——？”

粗犷的身躯，额头上的王冠，以及现在说出的这番话，毫无疑问这家伙就是“霜之巨人王
Thrym”。

面朝着与兀儿德，芙蕾娅一样AI化的大巨人，回答巨人王刚才的那番问话的是克莱因。

“……诶，武士食言的话可是会成为笑柄的！不要以为我们会被这种便宜的诱惑所吸引！”

在挂着微妙呆然表情的我们眼前，克莱因将爱刀从刀鞘中拔出。

以此为信号，其他的六人也都握起了武器。

虽然没有传说级别的武器，但所有武器都是拥有固有名的古代级武器，以及大师级锻造师莉
兹贝特打造的得意名品。不过，巨人王Thrym即便是看到剑光，它那长有长长胡须的嘴依旧
没有失去那自傲的笑容。或者说也是想当然的，如果是那家伙的话，我们的剑打在它身上可
能就跟挠痒痒一样。

黑暗的眼窝现出磷光，巨人从高处凝视我们的视线，落到了站在队伍最后的刚加入的第八名
队员上。

“……呵、呵。站在那里的不是芙蕾娅殿下吗。从监牢中走出来了啊，是要下决心做我老婆
了吗，嗯嗯？”

听到破钟般的声音，克莱因发出了几乎和之前完全不同的叫声。

“啊，老婆！？”

“是的，那女人，是为了要成为我的老婆才被我带到城里来的。不过，在宴会前晚，居然潜
入了老夫的宝物库。为了教训她，我才把她关押到冰牢中的，呵、呵。”

——由于情况有些复杂，我在脑海中做了一下整理。

名叫芙蕾娅的金发美女，刚才说了“是要将其一族被盗走的宝物取回才来到这个城里”的吧。
不过，仔细想想，浮在空中的Thrymheim城只有一处入口，想要进来应该是很复杂的。所以
才假装要当Thrym的老婆堂堂正正的通过了城门，并于夜晚闯入玉座之间，想要把宝物偷回。
不料却被门卫发现了，被锁到了牢房之中——应该是这样的设定吧。

如果这是真的，那在战斗中从身后受袭的可能性就很低。不过，现在就连这个整体剧情都没
摸清。即便这个是支线任务也很麻烦。而且，芙蕾娅“一族”究竟是不是Alfheim九种族之
一呢？被夺走的宝物又是什么呢？

既然这样，在她成为伙伴时就应该问一下的，不过却没有那种时间，我内心这么想道。随后
担任左翼前卫的莉法扯了扯我的衣袖，低声地说：

“我，哥哥。我，好像，在书上看过这个……Thrym与芙蕾娅……盗走宝物……那个，诶诶，
好像是……”

不过，就在莉法的记忆还没有成功调取出来前，站在后方的芙蕾娅毅然地说：

“谁是你的妻子啊！事以至此，我要和剑士大人们一同打倒你，把你夺走的宝物拿回来！”

“呜、哈、哈，气势不错哟。不愧是，美貌、胆识都蜚声九界的芙蕾娅殿下啊。不过，我可
是很喜欢摧残气质高贵的花朵哟……把苍蝇们击溃后，再你给特别的爱哟，呜哈哈哈哈……”

Thrym用巨大的手摸着胡须说出这话，让我怀疑这个刚好勉强擦着全年龄边的脚本，真的是
自动任务生成器生成的吗。

周围的女性都一起皱起了眉头，站在前方的克莱因左拳颤抖，叫道：

“你，你，你这混球！休想做出这种事情！站在这里的克莱因大爷，是不会让你碰芙蕾娅小
姐一根手指的！！”

“HOHO，我又听到了嗡嗡的振翅声了。哦，我就先把你们踩瘪，作为Jotunheim全土成为老
夫囊中物的提前祝贺吧…………”

咚，巨人王再次踏出一步，这个瞬间我的视野右上角，出现了条很长的HP，而且有三排。要
削减光这些看来要费一番工夫了啊。

不过，新艾恩葛朗特的凶恶楼层BOSS，为了不打击玩家的士气都不会把HP显示出来。想跟他
们战斗的话，抓好战斗的节奏是最最重要的。

“——来了！大家仔细遵照唯的指示，序盘以回避为主！”

我叫喊道，随后Thrym那如同巨岩般的右拳高高举起——缠绕着青霜之暴风，猛地砸了下来。

★　　★　　★

Thrymheim城最后一战——恐怕是这样——和预想的一样，会成为一场从未经历的大激战。

Thrym王的序盘攻击方式，是左右拳施展的砸打，右脚连续三连踏，直线轨道的冰之吐息，
还有从地面上生出的十二只冰之矮人。

虽然最麻烦的就是生成出的矮人，但却被队伍最后方的诗浓的弓箭，以极其精准的射击击中
弱点，不到一会儿就解决了。之后的直接攻击，都能看准时机完全回避，在唯的分析帮助下，
三名前卫总能在万分惊险的情况下避开了正面攻击。

防御态势做好之后，就要开始进攻了，但要说起来进攻才是很难做到的。就和刚才担心的一
样，我们的剑只能刺到其腿部，被厚实的毛皮包裹有着与不亚于金牛的物理抗性。抓住机会
拼命施展而出的三连击剑技，虽然能够削减HP，但Delay时间短的技能属性攻击也很低。那
手感就像是在敲击着完全不能破坏的物体一样。

这种状况下能够让我们士气大振的就是芙蕾娅的雷系攻击魔法。顺便一提，之后我一定要向
克莱因全力的说声“抱歉！”啊。因为是NPC所以连携能力很差，但是偶尔从后方倾注而下
的紫色闪电，确实是消减了Thrym不少的HP。

奋战了十分钟以上，最初的一条HP，终于消失了，巨人王发出了强烈的咆哮。

“攻击方式要改变了！注意！”

我大声叫道，同时听到了在身旁举剑的莉法的紧张的声音。

“糟糕了，哥哥。奖牌上的光线只剩下三束了。大概剩下不到十五分钟了。”

“………………”

Thrym的血条有三根。消灭一条需要十分钟以上。剩下两根要在十五分钟内消除是相当难的。

但对于这个对手，恐怕之前对付金牛的那套“Skill Connect”会不起作用吧。要让它出现
硬直——也就是行动延迟的话，必须得“攻击弱点，造成集中的大规模伤害”才行。Thrym没
有什么剑和魔法的弱点，即便是连续施展四次剑技，考虑到整体的HP量要造成很大的伤害大
概是不可能的吧。

那一瞬间，我仿佛看到了大地变成焦土一般——

Thrym的两胸突然间如同充气一般膨大起来，吸入了大量的空气。

卷起了强烈的风，前卫与中卫五人都被吸了过去。糟糕了，这一定是大规模全体攻击的前兆。
必须要使用风魔法中和其吸引力不可。像是同样考虑到这点似的，莉法举起左手，开始了咒
文咏唱。

不过，恐怕在见到敌人的攻击方式后再开始的话就赶不及了。

“莉法，各位，防御姿势！”

听到我的声音，莉法中断了咒文，双臂在体前交叉，保护身体。所有人也摆开了同样的姿势，
就在这时。

从Thrym口中，喷出了和之前呼出了几次的直线吐息不同的，广范围散开的冰晶星尘
【Diamond Dust】。

发出的青白色光芒将我们包裹住。贯穿了亚丝娜辅助魔法的冷气，就像是切开了肌肤似地，
发出了，嚓，嚓，的刺耳声响，五人的虚拟体瞬间被冻结。我、莉法、克莱因、莉兹以及紧
紧将毕娜护在怀中的西莉卡，变成了冰雕。

但这个方式没有让我们的HP减少，不过却不能放心。这个大招，应该是会随着时间流逝不断
造成伤害吧。

朝前直起身子的Thrym，抬起巨大的右脚。糟了，麻烦了，危险——我在内心大叫起来，也差
不多在这时。

“呜哦哦哦！”

随着一声咆哮，Thrym猛地跺向地面。产生的冲击波，将冻住的我们全部吞噬，产生了激烈
的震动——

咔嚓！震动产生了了令人恐惧的破碎声，包裹在全身的冰碎掉了。眼睛产生了眩晕。伤害特
效的光芒退去，落到了地面上。

视野一角，并排的八条HP槽的上方五条，一下子被染成了红色。

★　　★　　★

前卫五人被卷入Thrym的大规模范围攻击期间，射程范围外的后卫三人也没有就这么看着。

就在我们的HP减少了八成左右时，柔和的水色光线倾注而下，治愈伤口。这是亚丝娜的高级
全体恢复咒文。如果不是预测到伤害的发生预先咏唱咒文的话，几乎是不可能能够在这么关
键的时刻释放而出。

不过，游戏的大型恢复咒文，大部分都是需要“时间持续回复【Heal Over Time】”的，也
就是“几秒恢复几点血量”的类型。失去的血量不能很快恢复。恢复中如果再遭受攻击，即
使治愈的效果依旧持续着也会被击倒。

Thrym终于站起身准备继续对我们施以追击，开始前进。垂着长胡须的下巴喉结处——突然不
断的受到了燃着红色火炎的箭矢攻击，发生了巨大的爆炸。是诗浓的双手长弓系剑技
“Explode Arrow【爆炎箭】”。物理一成，火炎九成的属性正中霜之巨人族的弱点，HP明
显被扣去了很多。

“呜啊啊啊！”

Thrym发出怒吼声，改变了前进的方向。朝着诗浓冲去。抗击打能力很弱，但强化了攻击火
力输出的后卫用漂亮的过量攻击转移了仇恨值，让BOSS的攻击从前卫身上发生了转移，虽然
像是犯了初学者的失误，但实际并不是这样。她是为了让我们重整态势而争取时间，才冒着
必死的决心担当诱饵的角色。

“诗浓，拜托你争取三十秒。”

我大声叫道，同时取出恢复药剂饮用。周围的克莱因、莉法等人也饮用起红色的液体。西莉
卡的搭档毕娜，在主人的防御技能下好不容易生存了下来。这个世界虽然和艾恩葛朗特不同
有着复活魔法，但是需要耗费时间的，在战斗中施展是很难的。

焦急地等待着HP的恢复，同时凝视着那一头不断躲避着Thrym猛攻的水色Cat Sith。没怎么
来过ALO的诗浓，其躲闪手法也是十分完美。作为GGO里一名完全不要防御技的狙击手，对于
攻击型玩家的近身攻击也只能脱逃，或者说她就是凭借着这种经验生存下来的。

“……准备攻击。”

差不多恢复了八成左右的HP，我将视线挪开，对着伙伴们说道。握紧左右两把剑，开始倒数，
就在这一刹那——

“剑士大人！”

突然间身旁传来的声音，把我的注意力转移了过去。

那里的是，站在亚丝娜身旁的第八名队员——芙蕾娅。

不可思议的金褐色眼睛望着我，AI化的NPC说道：

“这样下去，即便打倒Thrym我的愿望也不会实现。我唯一的愿望就是，夺回埋藏在房间内
的吾之一族的秘宝。如果取回那样秘宝，我真正的力量就会苏醒并能将Thrym击退！”

“……真，真正的力量……”

我吸了一口气，陷入了很大的迷惑当中。

随后做出了决断。如今，没工夫害怕取回真正力量的芙蕾娅加入Thrym那边袭击我们了。持
久战再这样继续下去的话，即使不被干掉，任务时间到头的可能性也很高。如此一来，也就
只能尝试一下各种可能性了。

“我明白了。宝物是什么样的？”

我用很快的速度说出NPC能够勉强识别的话，芙蕾娅将双手打开约三十厘米左右。

“大约这么长的，黄金槌。”

“……啊？槌，槌子？”

“是金槌子！”

我呆然了半秒望着重复说出这话的芙蕾娅的脸。此时，被逼到玉座之间右后方墙壁处的诗浓，
终于被Splash的攻击击中了，HP减少了两成左右。不能再让她一个人成为目标了。于是我对
着克莱因与莉法等人，飞快地说：

“你们先去援护！我很快就与你们汇合！”

“好的！”

刀使大叫一声，吼叫着冲了出去。不一会儿就传来了集团作战的音效，我则是转过身巡视起
整个玉座之间。

青冰墙的附近堆放了许多闪着金光的物品。其中就隐藏着一把大槌？确实“搜索”是差使系
任务的定式，但这难度也未免太高了吧。

恐怕这个任务是以最少三十人的联合部队为基准设定的吧。人手不足，要从这宝山当中寻找
一件道具简直是天方夜谭。

“…………唯！”

怀着此心情，我叫了下坐在头上的导航妖精，她却是用摇头的方式做出了回应。

“不行，爸爸。地图资料没有将关键道具标示其中。恐怕，是在进入这个房间时，随机配置
的吧。不把发现的道具交给芙蕾娅鉴定也无法知道这是不是关键道具，这也是个问题。”

“是啊……呜呜……～～嗯……！”

如同耳朵要冒出浓烟一般绞尽脑汁思考。不过却怎么也想不出好主意来。只能期待那万分之
一的幸运，到附近的宝山中发掘了——

此时，在战场上奋斗的莉法，一瞬间对着我大叫起来：

“哥哥！用雷系技能！”

“雷，雷系……？”

顿时哑然的我睁大双眼，不过在下一个刹那，我还是高举起了右手剑。

只学到了初级幻影魔法的我，释放雷属性攻击是唯一的手段。

“……呀啊啊！！”

借势，我猛地蹬踏地面。朝着前方跳去，同时将手上的剑朝着地面刺去。单手剑类里少有的
重型范围攻击“Lighting Form[fn:41]”。物理三成，雷击七成。

发出清脆的雷鸣声，剑深深的刺入地面中。中心朝着四周发出了全方位的闪电。我急速起身，
高速回旋，望向被横切开的物品群——

“…………！”

看见了！在黄金宝山的深处，就像回应了雷击似的，发出了短暂的紫色光芒。我咬紧牙，朝
着房间左上猛冲。看了下右侧玉座之间的巨大椅子，扎到宝山中，双手将高价的物品一件一
件的向后抛去——

“……这就是！？”

数秒后，在眼前出现的是，看起来十分短小，细细的黄金槌柄，白金的槌头上镶嵌着宝石的
槌子。我伸手过去，握住，往上一提，瞬间那重量让我的身体趴了下去。呜啊，我重振气势，
面向小槌，大叫道。

“芙蕾娅，这个给你！”

借势将小槌远投出去，有些焦急起来。这个行为可能会让NPC认为是攻击行为吧。所幸的是，
祥和的金发美女，伸出纤细的右手将我投去的超重小槌漂亮的接住了。

随后，就像承受不住重量似的，身体蜷缩起来。长长的头发散开，外露的白皙背部微微颤抖
起来。

……诶，难道说错了吗？还是扔给了她糟糕的东西了？

再次陷入焦急的我的耳中——听到了芙蕾娅的低语声。

*

“……充……”

*

啪，空中闪现出了火花。

“……充满……充满了哟……”

这微妙的台词怎么有些像年轻貌美的魔女说出的啊。Cardinal的语言引擎模块难道是偶尔发
生了错误吗。而且声音也有些奇怪。一直以来都很娇艳的声音，变得低沉沙哑起来。

啪啪，火花逐渐变强。金褐色的头发浮了起来，纯白色的裙摆也飘动起来。

“充满……力量了啊啊啊啊啊啊啊啊啊啊————！”

第三次迸发出的叫声，已经不是以前的那个芙蕾娅了。讨厌的预感，不，已经超越了这个次
元，只能睁大眼睛呆呆望着的我的眼前——美女白皙的四肢与背部的肌肉如同绳结一般膨胀起
来。同时，白色的连衣裙也破裂，消失了。

这个瞬间，不知是不是秘奥义“超感觉”发动的原因，我感觉身后的克莱因也望向了这头。
望着如今一丝不挂的芙蕾娅的身姿，双眼如同要掉出来一般，不过紧接着，下巴也掉了下来。

这也是想当然的。全身放出雷光的芙蕾娅，慢慢的开始巨大化。三米……五米……依然在不
断的上升。手腕与脚变得如同巨木一样，胸板像是要超过Thrym一样。右手握着的金槌也跟
着逐渐变大。不一会就变成了连Gnome族都无法装备的大小，朝着四周放出激烈的雷光。

此时，我与克莱因看到了，让我们受到有史以来最大最凶残的冲击的影像。

对着地面，粗犷的脸颊和下巴上，长出了金褐色的长长的、长长的——胡须。

“大……”

“叔啊！”

整个房间响起了两名男子的惨叫。

是的，现在，让克莱因燃起武士道精神拯救出的那名被囚困的美女已经不在了。取而代之的
是，具有压倒性魄力的身躯，高约十五米的巨人，不管怎么看都是四十岁以上的中年人。

“哦哦哦…………哦哦哦哦哦————”

巨大的大叔，发出让人颤抖的重低音咆哮，朝着另一侧停下脚步的Thrym王，迈出那不知何
时穿上了厚重皮靴的右脚。

我战战兢兢地挪动视线，望向视野左侧八个并列的HP、MP条，确认了下最下方的名字。

数十秒前还写着“Freyja”的文字列，不知何时变换了。

“Thor【トール，T?rr，托尔，北欧神话中的雷神 问号处的字母为o上一提】”，这就是我
们的新伙伴的名字。
*** 第5节
虽然对神话类的知识知道的不多，但这点我还是听过的。

他就是在北欧神话中，与主神奥丁与道化神洛基并列的有名的——雷神Thor。手持呼唤雷电的
槌子，击倒一个个巨人的英姿，是许多电影以及游戏的原型。

随后，我又从莉法那里听到了些，北欧神话中确实有着“Thor想要夺回被巨人王Thrym盗去
的金槌”的这个故事。那时的Thor变装成芙蕾娅假装要成为对方的妻子，在宴会时多次利用
借口离开会场与同行的洛基机智地将金槌取回，并将Thrym手下的巨人杀掉的搞不清真假的
做得有些过了的残酷故事，恐怕Cardinal System就是收集了这个故事并将其做成了副本任
务吧。

也就是说，如果有谁知道详情的话，最初听到芙蕾娅这个名字就会做出她不会是内奸的这个
判断吧。对于在那个牢房前，凭直觉救助了芙蕾娅的克莱因真是要感谢感谢啊——但在明晰了
其“真面目”之后，他的心情又会是怎样呢？

“呜啊啊啊……卑鄙的巨人，作为盗窃吾之秘宝‘Mjollnir【ミョルニル，Thor的武器雷神
之槌】’的代价，你就用命来偿还吧！”

雷神Thor高高举起右手的黄金槌，踏着厚实的地面向前冲去。

“做出这种勾当的神哟，居然敢骗老夫！看我把你的胡子从你脸上拔下来，再把你遣送回
Asgard【アースガルズ，阿斯加尔德，北欧神话中的神之居所】！”

仔细想想的话，Thrym可能是因为真的相信了他就是芙蕾娅女神本尊，并筹办了婚礼的缘故
吧。因为发现了是假的，所以多少还是有些发怒的权利啊。

广场中央，金胡子与青胡子两个大巨人，手持的黄金大槌与冰之战斧轰然击打在一起。发出
的震撼让整个城堡摇动起来。围着这两个巨人，还没能从芙蕾娅那出人意料的巨大化——不，
是大叔化的打击中恢复过来的我们，只能干瞪眼望着。不一会儿，身后传来了HP恢复完毕的
诗浓的尖锐的声音。

“趁Thor成为目标的期间大家一起攻击Thrym啊！”

是啊，就是这样。雷神Thor也不能保证会陪我们到最后。我将剑挥起，大声叫道：

“好，全力攻击！不用顾虑什么尽管使用剑技吧！”

随后七人都奔跑起来，从四周与Thrym搏斗起来。

“呜哦哦哦哦哦————！”

释放出强烈的气场，将刀高高举起突进的克莱因眼角似乎有什么闪闪发光的物体，作为战友
这里还是应该当做没看见吧。不管什么技能硬直，我们施展着三连击以上的剑技朝着Thrym
的双脚砍去。亚丝娜不知何时也将法杖切换成了细剑，运用神速的突刺扎着Thrym的肌腱。
身旁的莉兹贝特则是，用双手握着的战锤击打着Thrym的小趾。

“咕……呜啊……！”

Thrym发出无法忍受的声音，身体晃动起来，左膝终于跪倒了地面上。王冠周围出现旋转并
一闪一闪的黄色光效。是麻痹状态。

“就是现在……！”

配合着我的声音，全员放出了最大的连续攻击。炫目的攻击特效，包裹了Thrym裸露的上半
身。闪着橘红色光泽的箭雨更是从天而降。

“吼！把地底还回来吧，巨人王！”

最后，Thor用右手的金槌给了Thrym致命一击。王冠被打碎了，之前还决定是不可战胜的
BOSS怪物，发出响亮的声音倒在了地面上。

HP条完全消失了。巨大的身躯从四肢与胡须尖端开始，发出咔咔的声音，变成了冰块。

漆黑的眼窝中散发出的青色磷光也暗淡下来，开始消失。此时，长着胡须的嘴中传出了低沉
的笑声。

“呜，哈哈哈…………就趁现在好好夸耀自己的胜利吧，苍蝇们哟。把Asgard神当做朋友可
不会有什么好下场啊…………他们才是真正的——”

咔嚓！Thor猛烈的踩踏，让几乎完全冻结了的Thrym巨大的身躯炸裂开来。

卷起一阵大规模的End Frame，霜之巨人王变成了无数块冰片四散开来。特效产生的压力让
我们不由得抬起手来，退后数步，雷神Thor从高高的上空用金色的双眼俯视着我们。

“…………真是的，我要谢谢你们啊，妖精剑士们。我终于洗雪了被夺取宝物的耻辱——这个，
就当作犒赏了。”

抬起左手，碰了下右手紧握的华丽大槌槌柄。取下一颗镶嵌的宝石，之后宝石发出光芒，变
成了一只小号的，人类可操控大小的槌子。

本体缩小版的黄金槌，Thor把它扔给了克莱因。

“‘雷槌Mjollnir’，为了正义的战斗去使用吧。那就——再见了！”

Thor抬起右手的瞬间，咔咔！青白色的雷光贯穿整个宽广的房间。我们反射性的闭上双眼，
再睁开眼来时，已经没有其他人了。成员离队的标示浮了出来，第八条HP、MP悄无声息的消
失了。

Thrym消失的地点，如同瀑布般掉落的物品，自动收入到了团队临时储物格内并消失了。

收纳玩这些东西时，BOSS房间的光线开始明亮起来。堆积在墙壁周围的黄金物品，很遗憾的
全部消失了。嘛，反正全员的储物格也满了，也没有想去拿的意思。

“…………呼……”

我轻轻的呼出一口气，走到了克莱因身旁，把手搭在他肩膀上，说：

“得到了传说武器，恭喜你！”

“……我，根本没有提升什么槌系技能啊！”

我对着握着闪着华丽光芒的单手用战锤，哭笑不得的克莱因，努力微笑着回应道：

“那，如果给莉兹的话，她应该会很高兴的。不过她也只有将其熔炼成铸块素材了
啊…………”

“我说！我再怎么也不会做那么浪费的事情！”

听到莉兹贝特的反驳，身旁的亚丝娜严肃的说：

“但是莉兹，将传说武器熔炼的话，应该会得到很不得了的铸块素材哟！”

“诶，真的吗？”

“啊……我说啊！我还没说要给她呢！”

将槌子紧紧抱住的克莱因大声叫道，望着他，周围的人都发出了愉快的笑声，也就在此时——

响起了声能让震撼到身体内部的超响重低音，同时冰面激烈的晃起来，如同波浪一样。

“呀啊啊啊！”

三角耳耷拉下来的西莉卡发出惨叫声。身旁尾巴卷成了S形状的诗浓也跟着发出了叫声。

“动……动了！？不，是浮起来了……！”

在她说出来的同时，我也注意到了。

巨城Thrymheim如同生物一般，开始震动起来，慢慢开始上升。究竟怎么了啊——不——难道说，
就当我想到这些时。

低下头看着奖牌的莉法，发出了尖叫声。

“哥……哥哥！任务，仍在继续！！”

“什……什么？！”

克莱因叫道。当然我和他的感受一样。霜之巨人族领袖Thrym已经死了，任务当然是结束了
啊——不过，我想起了，“湖之女王兀儿德”委托给我们任务时说的话。

攻入Thrymheim，将圣剑Excalibur从台座上拔下来。恐怕不止是打倒Thrym。强敌Thrym也只
是任务进行过程的一个环节而已——

“最后的光也开始闪动起来了。”

就像响应莉法的叫声一样，唯也做出了激烈的反应。

“爸爸，玉座后方生成了通往下方的阶梯！”

“………………！！”

没有时间回应，我猛地踩踏地面，朝着玉座奔去。

形状是椅子，但因为是高度有十五米左右的霜之巨人王Thrym的专用品，走近一看就跟一小
房间一样。如果不是事态紧急的话，大家都想在上面坐着玩一下，不过现在却无暇观望，径
直朝左侧跑去。

绕到后面的入口，确实如同唯所说，冰面上出现了一个开口，内有一通往下层的窄小阶梯。
无法让霜之巨人族通过，人类——不，是能容许妖精一个人勉强通过的尺寸。听着伙伴们跟随
在后方的足音，毫不犹豫地迈进昏暗的入口。

踏在螺旋的阶梯一步三阶向下奔去，头脑某处则陷入了思考。如果我们接受的兀儿德的任务
失败了——就等于是，地上多数玩家进行的虐杀系任务成功了，冰之巨城Thrymheim就会这样
浮出到央都阿伦吧，不过抱有侵略Alfheim野望的Thrym已经不存在了。总之，虽然不认为剧
情会以“平安无事生还”作为结束，但也没有想到Cardinal System会如此拘泥细节，强行
将故事进行展开。

全速奔跑的同时在进行着思考，就像是看透了我的思绪一般，身后的莉法搭话道：

“……我说，哥哥。虽然这项记忆不怎么清楚了……好像，在真正的北欧神话中，
Thrymheim城的主人并不是Thrym。”

“诶……诶诶！？那，名字是……”

“虽然是这样。但，在神话中，好像是叫……斯……斯……”

莉法口齿不清起来，坐在我头上的唯像是通过外部网络检索似的，即刻回答道：

“‘Thjazi【スィアチ】’，神话里兀儿德所说的，想夺取黄金苹果的，实际上不是Thrym
而是Thjazi。从这里开始是ALO虚构的，而委托玩家进行那种有问题的虐杀系任务的人，好
像是配置在Jotunheim地域最大城堡里的NPC‘大公Thjazi’。”

“……也就是说，一开始就指定好后继人了吗…………”

恐怕，Thrymheim如果上升到阿伦处，Thjazi就会作为最终BOSS登上玉座之间君临天下吧。
如今的事件不正是渐渐的，按照Cardinal所计划的央都崩坏，阿伦高原被占领的剧本走去了
吗，但走到这一步的我根本没想过放弃。这并不是因为想要得到那把Excalibur，而是自己
无法面对朋友冬奇而已。既然接受了某件事就必须把它做到最好，不也正是这个意思么……

就在想着这些时，城堡的抖动渐渐加强。时而重力加速度的变化也传了过来，城堡所在的
Jotunheim朝着天井向上升的感觉越来越明显。屏住呼吸，朝着不知道要下到哪里的螺旋阶
梯，以几乎坠落的方式向下跑去。

“————爸爸，五秒后就会抵达出口！”

“OK！”

明亮的光线进入视野，我一口气跳了过去。

进入的是一间冰晶正八面体，也就是与金字塔上下形状相重合的空间。也就是“玄室”。

墙壁十分的薄，透过下方的冰块可以展望整个Jotunheim大地。从天盖处剥离的无数块崩坏
岩石与水晶碎片从周围落下。螺旋阶梯一直穿过玄室的中央，延续到最底处。

在其前方——有着一个发出清澈黄金光泽的存在。

毫无疑问，那便是我和莉法坐在冬奇背上，从冰之城最下方远眺的光泽。只过了一年的时间，
我们就来到了这里。

七人排成一列朝下进发的阶梯终于到头了，我们摆出半圆队形围着那把剑。

正圆形的楼层中央，有一个边长为五十厘米的冰晶立方体。内部像是封闭着一个小东西。仔
细一看，才注意到那是一块细小柔弱的树木根系。放出无数根如同细丝般的毛细管，延续到
附近粗大的，根部。

直径五厘米的根，在某处华丽的被切断了。切断它的就是，刻着微小Rune【ルーン，卢文字，
如尼文】文字的轻薄锐利刀刃——剑刃。闪烁着黄金色泽的长剑垂直立着，剑身一半从冰之台
座中露出。形状十分精致的护手盘，用纤细的黑色皮革编制而成的握柄。剑柄末端处镶嵌的
巨大宝石绽放出七色光芒。

我曾经一度见过，不，是握过跟与其相同的剑。

将ALO作为其野心的男子，为了将我斩杀想用GM权限将其生成。不过，那时权限已经移到了
我这里，为了决出胜负的我将此剑物质化了。

当时的我，脑海中就只有做出世界最强之剑这一个想法——不，其实我对做出那把剑怀着强烈
的厌恶感。如果哪天能够通过正当手段入手的话，应该就能抵消这份情感了吧，我是这么想
的。虽然事态的发展大部分都是偶然，但这个时刻还是到来了。

…………等很久了吧。

我在内心嘟囔道，朝前迈出一步，右手握起长剑——传说级武器，“圣剑Excalibur”的剑柄。

“………………！！”

使足气力，想将其从台座上拔出。

不过，剑仿佛与台座，不，整个城堡全体一体化了似的，纹丝不动。我把左手也放到了上面，
双脚踏上，倾注全身之力。

“咿呀……哦…………！！”

不过，结果是一样的。一股讨厌的预感掠过背脊。

ALO这个游戏，和SAO与GGO不同，臂力与敏捷等数值状态，不会在窗口内明示出来。武器、
铠甲的装备界限也很模糊不清，从“很轻松的驾驭”到“稍有些适应”、“搬动都很困难”
等不断向前推移。所以，在玩家当中，侥幸入手武器后即便明显超重也不会放弃，不由分说
地装备上导致战斗失败的人也为数不少。

不过，说到底在系统上玩家的臂力等还是用数值进行管理的，也就是“隐性参数”。种族、
体格决定了基本值，技能加强以及魔法装备的加成、支援魔法等也会产生补正效果。光从基
本值来看，比起Spriggan的我，Salamander的克莱因臂力就要强一些。

不过，作为以技为特长的刀使，技能以及装备补正都是分配给了敏捷。相对而言，我由于偏
向喜好重剑所以强化值偏向于臂力。结果，在场七人中毫无疑问我的臂力最强。也就是说，
我拿不起这把剑，其他的人就根本不用说了。大家像是都知道这点似的，谁也没有出手。

相对的，我听到了身后传来的加油声。

“加油，桐人！”

是亚丝娜。我提高了音量立即回答到“就差一点了”。莉法、西莉卡、克莱因也送来了各自
的声援声。

西莉卡叫着“拿出毅力来！”，唯则是努力喊着“爸爸，加油！”，毕娜也发出了“咕噜噜
噜噜！”的声音。

作为团队的召集者，我绝不能在此处低头。用辅助魔法将数值提升到最大后，剩下的就是毅
力和气势了。并不是数值不够，我相信入力与时间的加算会让其解锁，我使出有限的臂力，
不，是意志力。

视野周围开始变白，眼前出现了光点，在这样继续下去的话AmuSphere可能会因为脑电波异
常而自动切断——就在这时。

哔，传来一声锐利的声响。同时，微微的震动传到我手上。

“啊…………！”

不知是谁发出了声音。突然间，脚下的台座迸发出了强烈的光线，我的视野被金色的光芒所
充溢。

随后，传出了比起到处都能听到的音效都要厚重的，爽快的破碎声。我的身体猛地伸直——在
四散的冰块中，右手握住的长剑在空中划出了一条黄金的轨迹。

向后仰去并飞起的我，被六名伙伴挡了下来。我忍耐着怀中剑的重量，向上望着大家，与六
人向下的视线交汇。全员张开了嘴，露出了笑脸，发出了盛大的欢呼——但比起这些，另一个
现象却更快一步来临了。

冰之台座上解放的，小小的树根。

浮在空中的它，突然伸展开来，不，是开始了生长。

极细的毛细管，朝着下方延伸。断面上部出现了新的组织，垂直向上延伸。

上方犀利的轰鸣声慢慢靠近。抬头望去，我们通过的洞穴，螺旋的阶梯正被破坏，不知什么
东西正在靠近。那就是根系。包裹着Thrymheim的，世界树的根——

以猛烈的速度将正八角形的空间贯穿的粗大的根，与台座上解放的小根接触到了一起，缠绕
起来，融合到了一起。

随后——

至今为止摇动程度约为一级的微震冲击波，将Thrymheim整个城堡吞没。

“呜啊……坏……要坏掉了……！”

克莱因大叫起来，所有人拼命抓着对方，就在同一时刻周围的墙壁上出现了无数条裂痕。

能把耳膜冲破般的大声响依旧在持续。马车般大小的厚实的冰壁一块一块分离开来，朝着下
方的“Great Hole”坠下。

“……！Thrymheim正体开始崩坏了！爸爸，赶紧逃离这里！”

坐在头上的唯大声说道。我看了下右侧的亚丝娜，同时叫道：

“话虽如此，但楼梯已经！”

是的。刚才利用并抵达玄室的螺旋形阶梯，已经被突过来的世界树的根毁得连渣也不剩。只
能回到之前我们来到这里时，使用的开在空中的平台。

“抓住根向上爬……”

在这种情况下依旧冷静的诗浓，望着上空说道。

“……看来不行啊！”

随后又耷下了肩膀。的确，玄室有一半的部分都是被世界树根部固定在天花板上的，但离我
们所在的正圆型平台最近的毛细根部却至少有十米左右。怎么看也不是能跳过去的距离。

“我说世界树啊！你不要这么无情啊！”

莉兹贝特举起右拳，叫喊道，不过对手可是树啊。也应该不会回答抱歉的。

“好，好吧……既然如此，就让你们见识一下克莱因大人那奥林匹克级别的垂直高跳吧！”

勉强站起身的刀使，在直径仅有六米的圆盘上拼命助跑起来——

“啊，笨蛋，别胡来……”

没等我阻拦，便看到他华丽跳出的背影。记录，假定是两点一五米。用如此短的助跑距离能
够做到这点也很不容易了，但还是在离根部很远的地方耗尽气力转为了抛物线，直直地往平
台中央掉了下来。

由于这个冲击——所有人都这么一致认同——周围的墙壁，猛地开始塌陷。

玄室最下部，也就是Thrymheim城最下方的角，终于与本体分离了。

“咕……克莱因那个笨蛋！”

即时是不擅长大叫的西莉卡，也不由得喊出了平时绝对不会听到的认真的叫骂声——而伴随着
这声叫骂，七人加一人加一只所站立的圆盘朝着遥远的地面开始了自由落体运动。

如果是漫画的话，现在应该坐下来，大家开始品茶吧。

不过，在VRMMO中从这么高的距离落下，说实话是很恐怖的。在Alfheim的云上飞行，那是有
着可靠的翅膀。在不能飞行的情况下，即便是在迷宫中，要初学者的女玩家从五米左右的高
度跳下也是很恐怖的。我也很不喜欢。

因此，我们七人只有趴在冰之圆盘上，用尽全力发出惨叫来表达我们的愤慨。

圆盘四周，与和我们同时崩落的巨大冰块相互碰撞在一起，分解成更加小的碎片。向上望去，
巨大的Thrymheim城，下部开始逐个解体，同时被解放的世界树的根也开始晃动起来。

最后，我从圆盘的边缘，畏畏缩缩的看了看正下方。

一千米，不，差不多有八百米的Jotunheim大地上，开着一个漆黑的“Great Hole”大洞。
想当然的，我们七人乘坐的圆盘正朝着大洞中央落去。

“……落到那里会怎么样啊？”

听到身旁诗浓的话，我勉强做出了回答。

“如，如果，如果落下去的话，就和兀儿德说的一样，可能会穿过，ni，ni，Niflheim也说
不定啊！”

“那里不冷就好了啊……”

“不，不，不要啊，那里很冷的！因为，那可是霜之巨人的故乡啊！”

听到这些对话终于感觉到腹部有些压迫感的我，双手紧紧抱着Excalibur，对着左侧的莉法
说：

“莉法，虐，虐杀系任务怎样了？”

随后，黄绿色马尾辫垂直悬在空中的Sylph，停止了惨叫——我很怀疑那里头是否带有欢呼的
成分——看了下胸前的奖牌。

“啊……赶，赶上了哟，哥哥！光点只剩下一个了！太好了……！”

笑！莉法喜笑颜开，双手张开，我抚摸着她的头，内心思考起来。

如果世界树恢复原状的话，兀儿德和她的眷属应该会取回力量，也不会被人型邪神继续猎杀
了吧。如果这样的话，就算落到“Great Hole”中，在洞穴途中死亡或者坠落到Niflheim死
去，也不是白白牺牲的。

唯一在意的就是，我全力确保的“Excalibur”。在任务结束后，其所有权会归谁是件很微
妙的事。恐怕，只有生存下来与兀儿德再会，才是真正地将任务划上终结符吧。

既便如此，我还是在莉法没看见时，赶紧将窗口打开，试着把Excalibur装进去。但剑却和
自己预想的一样，弹出窗口，无法收容。

——嘛，即使如此，能够将其拿在手上。好了好了，反正金光闪闪的传说武器也不是我喜欢的
东西。

正当我用这些酸葡萄理论来安慰自己的时候。

抱着我脖子的莉法，突然抬起头来。

“…………听到什么了吗？”

“诶…………？”

反射性的倾听起来，但听到的只有咻咻的空气摩擦声。离地面已经十分近了。坠落到洞穴中
大概也只有六十秒了吧。

“又来了！”

莉法再次说道，同时离开我在圆盘上灵巧地站了起来。

“喂，喂，很危险的……”

我这么叫道，但也就在这时，耳朵听到了，咕哦哦哦哦——……的啼叫声从远处逐渐靠近。

巡视四周。满是冰块群的那头，南侧的天空，出现一小小的白光。描绘出一条弧线，朝此处
靠近的是，如同鱼一样流线型的身体，以及四对八只翅膀，还有那长长的鼻子——

“…………冬奇————！”

双手架在嘴旁，莉法疾呼起来。冬奇再次发出咕哦哦哦的声音作为应答。没有错。那就是，
把我们送到Thrymheim入口处的飞行邪神冬奇。仔细想想，既然是它送我们来的，那来迎接
也不奇怪。或者说，它一定得来啊。

“这……这里这里！”

莉兹叫喊起来，亚丝娜也挥起手。将头埋在胸口紧抱的毕娜体毛中的西莉卡，也战战兢兢的
抬起头来，诗浓则是摇起尾巴来。

依旧一副超级高跳着地姿势，摆出一个大字的克莱因也抬起了脸，笑着伸出了右手大拇指。

“呵呵……我啊，最初就相信……那家伙绝对会来救我们的……”

——骗人！

我，恐怕还有其他五人在内心也会这么叫到吧，不过至今为止我们确实也一样忘记了冬奇。
一直都很矫健的邪神，滑行般接近克莱因。大概在坠落前将所有人转移到其背上时间像是很
充足。

由于圆盘周围落着许多冰块，冬奇的巨大身躯只得在五米开外的间隙处悬停。不过，这个距
离即便是重量级的玩家也能跳过去。

首先是莉法，她哼着歌没有一丝多余的动作跳了过去，完美的落到了冬奇背上。随后朝着这
边伸开双手，“西莉卡酱！”这么叫道。

西莉卡点了点头，双手抓着小龙毕娜的双脚，象征性地助跑了几步后跳了出去。吊着西莉卡
的毕娜啪嗒啪嗒地扇着翅膀，借此延长滞空距离。这也是拥有飞行系宠物的特权。她就这样
平安无事的，落到了莉法的怀中。

接下来，莉兹贝特“呜哩啊啊啊！”发出带有气势的吼叫，跳了过去，随后亚丝娜也做出了
一记流畅的长距离跳跃。诗浓则是在空中进行了两次空翻，落到了冬奇的尾巴附近。

望着一副僵硬面孔的克莱因，我挥了挥手“你先来吧！”

“哦呀，就让你们看看，本大爷华丽而充满魅力的……”

说话的同时计算好了时机纵身一跃。像是助跑距离不够似地，跳跃的距离稍微有些不足，好
在冬奇伸长了鼻子在空中接住了他。

“哦，哦哦哇啊啊啊！？好恐怖啊啊啊啊！？”

无视他的叫唤声，我再次看了下下方。透明冰晶圆盘的那头，已经没入了“Great Hole”中。
我面朝前方，正准备进行短暂的助跑——

此时，我注意到了一个恐怖的事情。

跳不起来。

正确来说，怀中的巨大重石——“圣剑Excalibur”，抱着它根本无法跳到五米处。就这样站
立着，鞋底就有些没入到了冰面中。

我突然站着不动的原因，坐在冬奇背上的一行人也像是立即觉察到了似的。

“桐人！”

“桐人君！”

紧张的声音传了过来。我低着头，面对着这极度纠葛的选择，一瞬间咬紧了牙。

二选一——要不抱着Excalibur就这样摔死，或者扔掉它逃生。就像是很露骨地在测试玩家的
欲望与执着一般的这最后的五米距离，难道是偶然生成的吗？或者说是Cardinal System的
有意图的阴谋吗……？

“爸爸……”

听到头顶上唯担心的声音，我点了点头。

“……真是的……Cardinal这个系统！”

苦笑着，低声说道。

下一个瞬间，我将右手握着的剑，平躺着扔了下去。

身体就像变魔术一般变得轻巧起来。黄金之光，闪动回旋着落到了视野的一侧。

轻轻助跑，踏着冰面，我丝毫没有改变身体的朝向跳了过去。Excalibur虽然那么重，但还
是慢慢地，如同不死鸟的羽翼一样，闪烁着，闪烁着，朝着无尽的大坑内落下。

我背着脸落在冬奇的背上，顿时八只翅膀大大的展开。一阵减速感袭来。至今为止一直跟着
圆盘一同落下的冬奇切换成了悬停状态，停止了下落。

亚丝娜把手搭在了我的肩膀上。

“……我们一定会得到那把剑的哟！”

“我会为爸爸固定坐标的哟！”

唯也紧跟着说道。

“……啊啊，是啊。一定会在Niflheim的某处，等着我们的。”

我低声念叨道，在心中对着那曾经握在手中的最强之剑，开始了告别——就在此时。

左手将挂在肩膀上的长弓取下，右手加上银色的细箭。

“——二百米！”

念叨道，紧接着开始了咏唱。箭矢被白色的光芒包裹。

在沉默观望着的我们眼前，弓箭手同时也是狙击手的诗浓，熟练地拉开弓。

朝着四十五度下方，不，应该是Excalibur的更下方，射了出去。箭矢在空中拖出一条银色
的细线，向前飞去。这是弓箭手专用咒文“Retrieve Arrow【リトリーブ·アロー】”。箭
矢会拖出一条带有伸缩性的丝线。通常是为了回收用过的箭矢，或者是没法拿到的物品才用
的便利魔法，不过细线的轨道却歪斜的很严重，实用度近乎为零，就算在很近的距离也无法
命中。

终于理解诗浓用意的我，“不管怎么说这也！”在内心念叨起来。

大概行不通吧。二百米这个距离，是莉兹所制的弓有效射程的两倍。不，即便在射程以内也
没有狙击的条件。脚部不断晃动，冰块持续的坠下，还有目标也处于不断下落中。

不过——不过，不过。

另一头朝着下方落下的黄金之光，与朝着其更下方飞翔过去的银色箭矢，就像有引力一般慢
慢靠近，靠近……

嗒！发出了清脆的音符撞到了一起。

“好！”

诗浓，猛地用右手拉起魔法丝线。黄金之光突然减速，停了下来，紧接着开始上升。慢慢的
回转，逐渐接近。光点慢慢变成了细长状，变成了剑的形状。

两秒钟后，应该从我手中永远告别了的传说武器，握到了诗浓的手掌中。

“呜啊，好重……”

念叨着，同时用双手握住的Cat Sith转身过来。

“““诗……诗……诗……”””

六人与唯的声音完全重合到了一起。

*

“““诗浓，你太厉害了啊——————！”””

*

在全员的称赞声中，动了动三角耳——因为双手提着剑的缘故——作为应答的诗浓，最后看了下
我，双肩微微耸了耸。

“给你，你不用摆出那副表情。”

——看来不知不觉间，我的脑门上像是用黑色魔术笔写上了“把它给我吧！”的字样。不由得
将视线向左上方移去的诗浓，发出“嗯”的声音，同时把剑递了过来。

轻微的既视感。大约两周前，在GGO最强者决定活动“Barrett of Bullets 3”本大会
Battle Royal的最后，诗浓也是做出了同样的动作同时给了我一样东西。我下意识接过来的
东西却是一击便能让HP完全消散的等离子手雷，随后我和诗浓紧密贴在了一起迎来了一同被
炸死的结局。那个场景在网络上的解释究竟是怎样的呢，因为想起就有些恐怖所以一直没有
调查。

不过，这次剑应该不会爆炸吧。

“谢……谢谢！”

行了个礼，我伸出双手准备接过来——但诗浓却突然把剑收了回去。

“在这之前，你得答应我一件事！”

水色头发的Cat Sith，露出了进入ALO以来最高级别的、灿烂的笑容并说出了——有着相当于
十个脉冲手雷破坏力一样的话。

“——你拔出这把剑时，心中，一定要想起我哟！”

咻。

空气被冻结了，我从诗浓手中接过黄金圣剑“Excalibur”。不过却感受到了前所未有的重
量，脊背流下了虚拟的冷汗。

“哦哦，真是辛苦啊，好受欢迎啊。”

右侧像是没有读懂氛围的克莱因说出了这番话，我沉默着跺了他一脚，尽可能平静地说道：

“……嗯，我会想起你的，感谢你。谢谢你，刚才那漂亮的射击！”

“不用谢！”

诗浓送出了这一记必杀秋波后，转过身，走到了冬奇的尾巴附近。从右腰的箭筒内，拿出一
薄荷草叼在嘴上，整理了一下衣服。虽然做出了这极其符合狙击手的冷酷无比的动作，但水
色的尾巴却在微微的颤抖，这些都被我看在眼里——那是在忍耐着大笑的举动。被打败了！我
在内心这么念叨道，周围女性团体的注目视线更是让我不知如何是好。

就在这时，却是冬奇帮我解了围，这出乎了我的预料。

“咕哦哦哦——嗯……”

发出长长的啼叫声，八枚翅膀强烈拍打着向上飞去。被吸引似的向上空望去，本次任务最后
恐怕也是最大级别的景象已经开始了。

深深扎在地底世界Jotunheim天盖中央处的Thrymheim城，已经完全坍塌了下来。

虽然城堡下部发生了很严重的崩坏，但其整体形状依旧保留着。一直以来，都呈现为倒金字
塔形状的城堡，就像是隐藏着其上部是相同的尺寸似的。也就是说，整体形状都是如同
Excalibur沉睡的玄室一样的正八面体。

边长三百米。上下顶点间的距离也是三百米的等对角线正方形，300×√2，也就是,424.26
平方米。记得东京天空树的特别展望台是有四百五十米高，难怪这里看上去的魄力接近那地
方。这个迷宫，不是一旦登上上边就再也不能往下走的结构真是太好了。

就在计算着这些如今没多大含义的面积时，冰之巨城发出了雷鸣般的声响，整个坠落了下去。
出于风压，崩坏变得更加激烈。两头的冰块缝隙分别向上向下延续，最后分裂成了几个大块。

“……那个迷宫，我们只闯了一次就消失了啊……”

“地图探开率，也就是百分之三十七点二啊。”

在我头顶的唯，用十分遗憾的声音补充道。

“虽然很浪费——但，本大爷，觉得很开心哟！”

双手叉腰，克莱因点了点头。像是想起了什么似的，转过头来，用奇怪的声音说：

“……莉法哟。怎么说呢，这个……那个应该是真正的女神吧？和那个Thor大叔不一样，对
吧？”

“嗯，是的。”

莉法点了点头，开心的笑了。

“哦，这样啊。那一定会在哪里遇见她的。”

“……可能吧。”

在这里已经不存在Asgard神族所居住的世界了，体贴的诗浓没有将这番话说出。仔细想象，
在Thrym被Thor杀死前一刻好像说出了什么话似的。确实是，Asgard神族不会……什么什么
的……

我的脑海虽有些许记忆，但最终还是消失在了Thrymheim城毁灭的超大声响中。

从遊弋着的冬奇背上，仿佛伸出手就能触及的巨大冰块群不断地坠下。被下方无尽的大洞
“Great Hole”所吞没，消失在无尽的黑暗中——

……不，不是这样。

洞穴底部，像是出现了光线，一闪一闪，摇动着的青色光泽。对，那是水，是水面。从无底
洞的深处，发出了和刚才不同的轰鸣声，大量的水涌了上来。依旧落下的冰块全数没入水中，
随即融化化为一体。

“啊……上面！”

含着薄荷草的诗浓，抬起右手。

反射性抬起头，一副前所未有的景色映入眼帘。

天盖附近萎缩的世界树的根，在Thrymheim破坏的同时被解放了，如同生物一般摇动着不断
变粗。相互聚集，像是寻求着什么似的向下突进，就像是巨人把大木桩扔下一样。一言不发
的我们的眼前，世界树的根，没入了满载清水的“Great Hole”当中，产生巨大的波浪，并
向四周散去。随后广阔的水面如同网格一般被覆盖，根直达彼岸。

这景色，如同在女王兀儿德那里见到的幻像一样。停止了活动的世界树，从那枝干处延长而
出的巨大根系，像是产生了某种强烈的波动一样。就像是长时间辗转于酷热的沙漠中的旅行
者，终于找到了绿洲的泉水一样的欢喜。

“看啊……根部，发芽了……”

听到亚丝娜的低语声，放眼望去，的确延伸到四面八方的根部，小小的绿芽——当然，如果以
我们的尺寸来看的话就是一棵棵的大树——拔地而起，黄绿色的树叶慢慢展开。

风吹拂而过。

和至今为止Jotunheim中吹过的，冻到骨头里，让树木落叶的寒风不同。是暖和的，春风。
同一时刻，世界整体的光亮也加倍。再次仰望，发出微弱光线的明灯一样的水晶群，一个一
个都如同小太阳一样，绽放出强烈的白光。

在风与阳光的抚慰下，覆盖在大地上的雪，小河上的冰，渐渐溶解。下方，黑色的大地渐渐
被新绿色覆盖。各处的建筑，人型邪神的城寨，也瞬间被绿色笼罩变成了废墟——

“咕哦哦哦哦——嗯…………”

突然，冬奇猛地将八枚翅膀与大大的耳朵，还有鼻子举起，发出高亢的吼叫。

数秒后，从世界各地，传来了哦哦，咕哦哦，的回应声。从四处的泉水，河流的水面，以及
覆盖在巨大湖泊的世界树的根部上，出现的是如同馒头一般的身体，长着长长触手的象水母。
不仅是它们，还有如同多脚鳄鱼一样的家伙，长着两个头的豹子一样的，各种各样的动物型
邪神，在地面以及水面上出现，并阔步起来。

不，在片绿野上，它们已经不再是“邪神”了。是享受着微风、绿叶、阳光的安稳的居民——
抛开体格不论。欺负它们的那些人型邪神，一只也没有了。

不知不觉间冬奇下降了很大的距离，可以看见遍布在原野四处，看上去很小的，呆掉了的联
合部队。他们大概也不知道发生了什么吧。从NPC“大公Thiazi”那里领到任务，奋战了数
小时终于要达到目标时，巨人伙伴突然消失了，并且地域突然发生了突变，他们会惊呆也是
想当然的。

就和克莱因在出发前说的一样，必须对“MMO tomorrow”的记者以及情报屋那里做一些程度
的必要说明才行，这个任务就交给他吧——想着这些无责任的事情，突然看到了身旁紧贴着冬
奇的莉法。

她抚摸着冬奇宽广背脊上的白色毛发，轻轻地说：

“……太好了。太好了，冬奇。看啊，你有很多伙伴哟。那里……还有那里，有那么多……”

看着她脸颊上流淌下的水滴，连我这种木头人也伤感起来。很快西莉卡抱住莉法也哭了起来，
亚丝娜与莉兹也擦了擦眼角。抄着双手的克莱因也像是要隐藏什么似的背过身去，诗浓也不
住的反复眨起眼来。

最后，唯从我头顶飞下，落在亚丝娜的肩膀，把头埋入头发中。最近，唯很讨厌让我看到她
哭泣的样子，不知道是跟谁学到的……

就在这时，我们听到了这样的声音。

“你们很漂亮的完成了委托。”

★　　★　　★

猛地把头朝向正前方。

冬奇大大的脑袋处，出现了一位被金色光芒包裹的人影。

明明只经过了两小时，却让人感觉很久远的身影，毫无疑问就是委托给我们这项任务，身高
三米的金发美女“湖之女王兀儿德”。

不过，这次和之前透明的身体不同，完全是实体。大概是从躲避Thrym魔掌的泉水中脱出了
吧。可以看到珍珠色鳞片的手脚，尖端如同触手状的金色发丝，穿在身体上的淡绿色长衣在
阳光的照射下，闪耀着光泽。

不可思议的青绿色眼睛眯了起来，兀儿德再次说道：

“‘能够切断所有钢铁与树木’的Excalibur已经被移除，Yggdrasil被切断的‘灵根’终于
回到了母亲的怀抱。树的恩宠再次临幸这片大地，Jotunheim取回了原来的样子。这全都是
你们的功劳。”

“不……这个。说到底要是没有Thor的协助，我们也打不倒Thrym啊……”

听到我的话，兀儿德点了点头。

“之前的那股雷神之力，我也感受到了。不过……要小心哟，妖精们。他们Asgard神族虽然
是霜之巨人的敌人，但也绝不是我们的朋友……”

“那个……Thrym本人想也是这么说的，那是，什么意思……？”

擦干眼泪站起身来的莉法这么问道。不过这个模糊不清的问题，不知道是不是没有被
Cardinal的自动应答系统识别，兀儿德没有回答，微微浮了起来。

“——我的妹妹们，也想谢谢你们。”

说出这话的同时，兀儿德右侧如同水面一般摇动起来，出现了一个人影。

身高比姐姐要小一点——虽说如此但我们依然要仰望。头发也是金色，稍微短一些。长衣是深
青色。如果姐姐是“高贵”的话，这位就是“优美”。

“我的名字是贝露丹迪【ベルザンディ】。谢谢你们，妖精剑士们。能让我再次见到绿色的
Jotunheim，啊啊，就像梦一样……”

用甜美的声音说道，贝露丹迪轻柔优雅的挥了下右手。在我们眼前出现了许多道具与Urud，
自动装入到团队临时储藏库内，消失了。七人团队的容量虽然很大，但也快要到极限了。

不过，在兀儿德左侧刮起了一阵旋风，出现了第三个人影。

是一副铠甲装。头盔左右以及鞋子侧面，伸出长长的羽翼。脸庞美丽而富有英气，左右伸出
的扎在一起的金色头发摇动起来。

这第三名姐妹，拥有着惊人的特征。人类，不，是妖精大小。只有姐姐兀儿德的一半那么大。
这让克莱因从喉咙深处发出了奇怪的声音。

“我叫‘诗寇蒂【スクルド】’！请接受我的谢意，战士们！”

用严肃的语气说出这番简短的话，随后诗寇蒂高举起手。再度出现了报酬道具的瀑布。视野
右侧的信息区域，出现了容量告急的警告。

两名妹妹左右退去，兀儿德再次走上前来。如果她也要给予报酬的话，毫无疑问储藏格就会
装不下了。那时就只能将多余的道具实体化，堆在冬奇的背上——不过，不知道是不是幸运，
兀儿德对着我微笑道：

“——我把这把剑给你。不过，你可不要再把它扔到‘兀儿德之泉’里去了哟。”

“是，是的，我绝不会的。”

像个小孩一般点了点头——

在我手中紧握的黄金长剑，传说武器“Excalibur”突然消失了踪影。当然是收纳到我的物
品格中了。虽然想叫出“好棒啊啊啊啊！”这番孩子气的话，单卧还是握紧了拳头作为回应。

三名女性慢慢的离开了，一同说道：

“谢谢，妖精们。再见。”

同一时刻，视野中央，出现了用粗字体标示的系统信息。宣告任务完成的一段话，随后三人
转过身，飞走了。

此时，克莱因跑了过来，叫道：

“诗，诗诗诗寇蒂小姐！联系方式！”

————你啊，这就忘了芙蕾娅小姐了吗！！

————NPC又怎么会有邮箱地址呢！！

不知道该如何吐槽他才好的我，就这样站在那里——

该怎么说他才好啊。

姐姐两人消失了，最小的妹妹却转过身来，不知是不是错觉，感觉她露出一副觉得很有趣的
表情，再次轻摆起手。不知什么闪闪发光的东西划过天空，飞到了克莱因的手中。

之后，战女神也消失了，剩下的只有沉默与微风。

不一会儿，莉兹贝特摇了摇头，低声说道：

“克莱因，我现在发自内心地尊敬你啊。”

同感，真是同感啊。

★　　★　　★

不管怎么说——

二〇二五年十二月二十八日早上突然开始的我们的大冒险，就这样画上了句号结束了。

“……那个，接下来，我们办一个庆祝兼忘年会怎么样啊？”

听到我的提案，有些疲劳亚丝娜会心一笑，说：

“赞成！”

“赞成！”

坐在肩膀上的唯，将右手笔直举起。
*** 第6节
突然决定的忘年会，究竟是在ALO内依古朵兰西·辛迪处，我与亚丝娜的房间内举办，还是在
现实中举办稍微有些苦恼。

如果在ALO的话，在这次任务中活跃的唯百分之百能够参加。不过，亚丝娜从明天也就是二
十九日开始的一周，都要去京都的父亲本家，如果错过了今天年内就没有机会了。

早早就显出一副当家相的女儿，虽然不太情愿，还是说了“在现实吧！”，所以决定了于午
后三点在台东区御徒町的“Daisy Cafe”举办忘年会。再次回到世界树阶梯后，我们挥手与
冬奇告别，回到了和任务开始前一样热闹——虽然Thrymheim开始上升时多少有些骚动——的央
都阿伦中并登出。

在床上醒来后，首先便打电话给艾基尔进行预约，虽然他嘴上说着“这么突然叫我们怎么准
备足够的食材啊”之类的牢骚，但还是在这点时间内把店里的特别推荐——猪排骨以及烤豆充
分地准备好，简直就可以去当商人的榜样了。

天气预报说傍晚会有雪，因此我和直叶两人没有乘坐摩托车而是去坐电车。由于这次还带着
一个大型行李，我那辆载物空间狭小的破烂125CC摩托根本装不下。

说到琦玉县川越市，包括克莱恩在内的东京人们露出了世界末日般的表情，但其实乘坐东上
急行线到御徒町其实也只需要一小时。大约两点时打开Daisy Cafe店门时，发现住在离此很
近的诗浓已经到达了。

与忙着准备料理的店主打了声招呼后，将搬运来的硬纸盒打开了。里面放的是拥有四个可动
摄像头以及操控用的笔记本PC。

“……这是，什么？”

诗浓皱起眉，帮着直叶在店内四处地点架设摄像头。这是由市场上买到的内置麦克风以及大
容量电池的无线网络摄像头改装得来的，就算不仔细选择安放地点，四只就足以将整个房间
全部覆盖其中。

让笔记本电脑识别摄像头，确认影像动作后，最后通过网络和安放在川越自家内的High
Spec内置机相连。接上小型音响设备，说：

“怎么样，唯？”

“……能看见。看得很清楚，也听的很清楚，爸爸！”

唯那可爱的声线通过耳机，以及PC扬声器传了出来。

“OK，慢慢移动摄像头看看。”

“是！”

回答后，离我最近的小口径摄像头的镜片动了起来。

现在的唯，正在一个Daisy Cafe影像虚拟而成的3D空间内，如同小妖精一般自由的飞翔。虽
然画质很低，应答很差，但也比一直以来用手机上的摄像头观看现实世界，自由度要高很多。

“……原来如此，也就是说摄像头与麦克风，就是唯酱的终端……感官一样的东西吧。”

听完诗浓的话，我和直叶都点了点头。

“是的。这是哥哥在学校学到的Mecha……Mechatroni……”

“Mechatronics【机械工程学】！”我补充说道。

“这虽然是工程学课程的课题作业，不过却全都交给唯去做了。”

“尽管提出要求就好！”

啊哈哈，三人笑了起来，望着他们，我边喝着很辣的生姜饮料，边反驳道：

“不，不止这些哟！摄像头还能更加小，如果能够装载肩膀或者头上的话，就能更加方便的
携带了……”

“所以这也是唯做得吧！”

完全无法反驳。

不过，这还离暂定名为“视听觉双向通信探测器”系统的完成形态差得很远。为了能让唯将
现实世界识别得和虚拟世界一样，摄像头以及麦克风终端还必须得有自动移动机能，接收器
也远远没达到要求。说到理想，如果这个能自动行走的设备是人型就更好了。但无论如何以
高校的设备是绝对无法做到的，要是有个努力的机械师正在开发美少女外形的机器人就好
了……

就在我不断思考着这正经的妄想时，亚丝娜、克莱因、莉兹以及西莉卡按照顺序都来到了这
里，并在一起的两张桌子上也并排摆上了料理与饮料。最后，在隆重的灯光照射下端上了大
盘猪排骨，所有人都对着店长拍手称赞。摘下围裙的艾基尔也入席了，并将无酒精饮料以及
香槟酒注入到玻璃杯中——

“庆祝‘Excalibur’以及‘Mjollnir’入手！辛苦了，为二〇二五年，干杯！”听到我这
番省略的话，所有人都跟着一同大声呼喊起来。

★　　★　　★

“……话说回来，那个。”

坐在右侧的诗浓说出这话，是在经过了一个半小时，吃完东西并开始收拾的时候。

“为什么要叫‘Excalibur’呢？”

“诶？为什么？”

无法理解其问话的含义，我歪起头来，诗浓将叉子在指尖上灵巧的旋转起来，补充说道：

“一般来说……怎么说呢，在其他幻想小说，漫画里不都是把‘Excalibur’叫做
‘Caliber’吗？”

“啊……啊啊，是这样啊。”

“诶，诗浓，看了那方面的小说了啊？”

对面的直叶问道，诗浓害羞似的笑了笑。

“中学时，在图书馆看的。那时读了几本亚瑟王传说的书，翻译我记得都是叫做
‘Caliber’的。”

“嗯，这道也是，这恐怕也是ALO中设定那件道具的设计者的嗜好吧……”

看到我一点感情起伏都没有，坐在左侧的亚丝娜苦笑起来。

“确实，在主流的传说中是有着各式各样的称呼。刚才任务中所说的伪剑‘Caliburn’，其
实也是圣剑的另一个称呼哟。”

随后，桌上的扬声器中传来了唯麻利的回答声。

“主要的称呼有，‘Caledwlch【カレドヴルフ】’、‘Caliburnus【カリブルヌス】’、
‘Kalibor【カリボール】’、‘Callbrande【コルブランド】’、‘Caliburne【カリバー
ン】’、‘Exalibor【エスカリボール】’等等。”

“呜啊，有这么多啊！”

我惊讶的说，那为什么会有“Calibur”与“Caliber”这种误差般的称呼呢，当我想到这里
时，诗浓再次开口说道：

“嘛啊，其实没什么太大含义……说到‘Caliber’，我听说过其他的意思，只是有些在意
罢了。”

“诶，其他的意思？”

“枪的口径，英语是叫做‘Caliber【キャリバー】’的。比如，我的HecateII是五零口径，
就叫做‘Fifty Caliber’。但Excaliber的前缀和此意义完全不同。”

诗浓闭上了嘴一会儿，瞥了我一眼，继续说道：

“……就是说，从前缀去联想的话，也有着‘人的器量’这种意思。‘a man of high
caliber’，也就是‘可能性很大的人’或者‘能力高超的人’。”

“诶诶，赶紧记下来……”

直叶由感而发，“大概考试不会出哟”，诗浓笑着说出了这番话。

不知何时开始倾听我们对话的莉兹贝特，在桌子另一侧默默的笑了起来。

“那也就是说，Excalibur的持有者必须得有很大的器量啊。好像听说，最近某人，去做了
短期打工赚了一笔收入啊。”

“呜…………”

我从总务省菊冈那里，得到那笔“死枪事件”的调查协力费就像是昨天的事情一样。不过，
那些钱已经花费到了升级唯所在的内置机器机能的一系列部件——以及直叶的碳纤竹刀——上，
余额早已所剩无几了。

不过，这才是考验器量的时候。我拍了拍胸，宣告道：

“当，当然，一开始我就想说了，今天的花费都包在我身上。”

话音刚落，四周便响起了热烈的拍手声与克莱因的口哨声。

我举起手作为回应，同时内心思考起来。

在SAO、ALO、GGO这三个游戏内的经历，如果说我学到了什么做人的学问的话，那就只有
“一个人是什么也背负不起来”这句话。不管在哪个世界，我都经历过许多挫折，是在许多
人的帮助下才得以继续前行，这么说一点也不为过。这次的突发冒险，也正可以说明这点。

所以，我的——不，大家的“Caliber”，一定能把伙伴们的手联系成一体，成为“大家”这
个圆的直径。

这把黄金之剑，我绝不会为自己一人使用。

做出此决意的我，把手伸向桌上的玻璃杯，准备再一次与所有人碰杯。

（圣剑篇 完）
** 第3章
初始之日

艾恩葛朗特第一层

二〇二二年十一月

*** 1
死亡游戏。

这并不是给出了明确定义的说法。如果说是“肉体上存在风险的竞技”，那么格斗技与攀岩、
motor sports等都会包含在内。能够分别危险的体育运动与死亡游戏的条件，恐怕就只有这
一条了。

明确的将“死”作为惩罚，写在规则当中。

并不作为偶然的突发事故的结果。而是在玩家失误或者败北时，按照规则中的惩罚，强制给
予玩家死亡。也就是杀掉。

如果以此为前提，世界的第一个VRMMORPG“SwordArt Online”现如今已明确地死亡游戏化
了。游戏开发者同时也是支配者的茅场晶彦自身，也在二十分钟前，很明确的宣告了这些。

HP变成零——也就是“败北”的话就会被杀死。或者说是把NervGear取下——也会被当做“违反
规则”被杀掉。

没有现实感。或者说是不应该会这样。如今的脑海中，无数的疑问化作一旋涡。

——这种事真的可能吗？使用这个分类归结为“家庭用游戏机”的NervGear，真的能将人类的
大脑破坏掉吗？

——在此之前，为什么要这么做呢？把玩家困在虚拟世界作为人质，要求赎金倒还可以理解。
不过，却让玩家赌上性命攻略这款游戏，这对茅场来说毫无物质上的利益。此时此刻，至今
为止他所建立的游戏设计者、量子物理学者的名声都会尽失，并堕落成史上最恶的犯罪者。

无法理解。理性上完全无法理解。

同一时刻，本能却领悟到了。

茅场的宣告都是真实的。作为SAO舞台的艾恩葛朗特，从一个充满感动与兴奋的异世界，蜕
变成了囚困一万人的死亡监牢。茅场在之前演说的最后说出的——“这个状况，才是我的最终
目的”这番话，完全都是发自内心的。那个危险的天才，是为了实现这个死亡游戏，才会创
造SAO……进而开发NervGear的。

正因为相信这些，我——LV1的单手剑士桐人，现在才会如此拼命的奔走。

独自一人，在广阔的草原正中。抛弃了在这个世界里初次结识的伙伴。

为了自己一人能够生存下去——

*** 2
浮游城艾恩葛朗特，是个由一百阶楼层层层堆叠而成的建筑。

由于从下到上由大到小，因此城堡整体呈现圆锥状。面积最大的第一层，直径近乎十公里。
“主街区”，也就是第一层最大的都市“初始之街”位于该层南端，是个直径一公里的半圆
形地域。

街区周围建起了高耸的城墙，所有的怪兽都无法侵入此地。而且，街区内部还被“犯罪禁止
代码”所保护，作为玩家的真实生命的HP值一丝也不会受损。换句话说，就是只要待在初始
之街就会很安全，绝对不会死掉。

不过，我就在茅场经验做完首次演讲后，就下定了决心要走出这个街区。

理由有好几个。我并不相信“代码”是永久性的。也很忌讳会在玩家间必然产生的不信赖与
不和。还有那深入骨髓的，作为MMO游戏玩家的升级欲。

不知出于什么，我非常喜欢科幻小说中的死亡游戏这些的东西，古今中外的小说、漫画，还
有电影所有的一切都有涉及。当然游戏的题材也有很多，当然它们之间也存在着某种共通点。

在死亡游戏中，“安全”与“解放”是相互矛盾的。如果说出生点是安全地带的话，只要停
留在那里就生命不会有危险。但，如果不冒着风险前进的话，就不可能会有解放的出现。

当然，我也不是怀着要用自己的剑砍到一百层内的怪兽，将这个游戏打穿的勇者般的愿望。
只不过，囚困在这里的一万名玩家中，应该会有很少的一部分人有这样的想法吧——最少应该
也有一千人以上。总有一天他们会单独行动或集结起来走出初始之街，狩猎周遭的弱小怪兽，
开始赚取经验值吧。提升等级，更新装备，变得更强。

这里还有第二个定式。

死亡游戏中，玩家的敌人不仅仅是规则和陷阱以及怪兽。同样是玩家的人也会成为敌人。没
有这些的死亡游戏，我还真不知道。

SAO内在街道外也就是“圈外”区是允许PK的。虽说如此，但也不会杀死对方吧——因为这会
成为真正的杀人事件——但遗憾的是我无法保证用武器威逼并抢夺对方道具的玩家不会出现。
要是某个带有敌意的玩家，拥有着比自己强上很多的数值参数——光是想象一下那种情况，现
实性的危机感跟恐惧就会化为苦涩涌上口中了。

正因为以上这些理由——

要我留在初始之街，放弃安全并强化自身的这个选择，我无论如何也不会接受的。

为了提高等级，我没有时间站在那里发呆。街区周边比较安全的一些草原怪区，应该会有许
多“决定行动的玩家”聚集在此吧。SAO的怪物刷新，都是每个怪区按照一定的时间更新几
只。把最初的猎物狩猎殆尽后，就会拼命寻找下一个POP点，偶尔和其他玩家发生争夺也是
不可避免的。

为了回避以上这点，并能更加高效的升级，选择“比较安全的”后的——“稍微有些危险”的
区域是十分必要的。

当然，对于什么都还不懂的新手来说，这无疑是自杀行为。不过我却因为某些原因，我对这
个今天才正式开服的，名为SAO的游戏，其底层的地形以及出现的怪兽都是十分熟知的。

走出初始之街西北门，穿过广阔的草原，走过迷宫般的小道，便会抵达名为“ホルンカ
【Horn】”的小村落。虽然很小但也是“圈内”，并且还有旅馆，武器店，道具屋，足以作
为狩猎的据点使用。周围的森林，不会刷出【POP】会使用麻痹毒以及装备破坏这类危险技
的怪兽，因此即便单独打怪也不会出什么意外而死亡。

为抵达ホルンカ为据点，我一天便从一级练到了五级。现在的时间是下午六点十五分。周围
的草原，都被从艾恩葛朗特外围射入的夕阳染成了金色，远方所见的森林则在黄昏时变成了
浅青色。但所幸的是，ホルンカ周边即便是进入夜晚，也不会出现强力的怪兽。只要夜以继
日的不断狩猎，一定能够在其他玩家发现这个村落时状态数值以及装备都能达到可以前往下
一个据点的程度吧。

“……利己也有不错啊……这是独行玩家的准则啊，真是的……”

离开街区便一直全力奔走的我，第一次在嘴中念叨起了这话。

如果不是说出这玩笑般的话，也就无法打消从我嘴中流露出与恐惧感不同的另外一种苦痛——
自我厌恶的情感吧。

至少也该邀请那位人品很好的戴着印花大手帕的海贼刀客与自己一同行动吧。帮助他提升等
级，借助这种大义名分生存下去的话，多少也能抹消一些自身的罪恶感吧。

不过，我却丢下了，那名为克莱因的，在这个世界中我唯一的朋友离去了。正确来说，是我
邀请他一同前往ホルンカ时，他却说要和在其他游戏中组过公会的伙伴们一同留下不可。

那就邀请他们一同前往吧，我本可以这么提议。不过却没这么做。那里和只会刷出些LV1也
能够轻松击打的野猪与大青虫的草原不同，前方的森林多少也会刷出些危险的毒蜂、捕食植
物系怪兽。应对那些特殊攻击稍有失误，HP会瞬间变成零……也就是死去。

我很害怕克莱茵的朋友死去，不，是克莱因看到自己朋友死去时，投向自己的视线。我不想
给他那种不好的回忆，也不想他受到伤害，就是这个念头，让我丢下了在这个世界中第一个
跟我打招呼，并邀请我组队一同游戏的男子……

“…………！！”

就算念叨着这些自虐的话，也无法压抑腹腔底部涌上来的厌恶感，我咬紧牙，把右手放到挂
在身后的剑柄上。

不远处的草丛中，刷出了一头青色的野猪。由于没有主动攻击意识，我本想放过它，不过却
任由冲动驱使拔出了初期装备的朴素直剑，就这样发动了单发剑技“Slant”。

被击中的目标做出了回应，野猪怒视起我。右前脚猛地搓起地面。这是突进攻击动作。此时
如果胆怯，将剑技停下的话反而会受到极大的伤害。焦急与冷静不断在脑海中交替的我凝视
着这只怪兽，瞄准其脑后的弱点将剑技施展而出。

刀身发出浅色的水光，随着尖锐的效果音虚拟体半自动的活动起来。剑技特有的系统辅助，
能够将斩击动作的威力进行补正。在行动的那一瞬间，就像是注意到了不要拖慢速度似地，
有意地用脚蹬地得意提高右臂的速度，让剑技的威力进一步提升。为将此技巧铭记于心，我
曾将街道里的训练人偶作为对手就这样持续练了近十天。

LV1的数值参数与初期装备的规格当然是贫弱至极，即便如此加速了的“Slant”如果能够命
中弱点，造成Critical的话，一击也能勉强将青色野猪——正式名为“Frenzy Bore”的HP全
部消除。一阵强烈的手感传来，我正面施展而出的斩击命中了冲过来的野猪的鬃毛部位，全
长一米二十的野兽猛地向后方弹去。

“唧咿咿咿咿咿咿！”

发出惨叫同时从地上弹起，在空中不自然的停止了。啪嚓！一阵强烈的光效。野猪，在青色
的光芒中，化作数千多边形片四散开来。

看都没看得到的经验值，还有掉落的素材道具名，我脚不停歇的穿过那特效光芒。毫无爽快
感。我快速将剑收回挂在背上的剑鞘中，面朝着终于就在眼前的昏暗森林，用敏捷参数能够
允许的最大速度跑去。

*** 3
在森林中慎重的回避着怪兽的反应圈，并尽可能快的顺着小道前进，终于在夕阳完全落下前
抵达了目的地“ホルンカ村”。

站在村落入口前的我看了看这民家与商店合起来只有十多间房屋的村落。视野中浮现的所有
颜色指示器都是NPC的标示。看来是我最先抵达此处啊，这么想也是当然的。就在茅场的演
说结束时，我连话都没说便奔了出来。

首先还是去下自己正面对着的狭窄广场内的武器店吧。就在演说开始前——也就是SAO还是普
通的游戏时，由于我克莱因一同狩猎了数只怪兽，所以道具栏中储藏着几个素材。由于没有
提升生产系的技能，所以只能将这些积攒起来的道具卖给NPC店主。然后将这些得到的少量
金币全部用来买了一件防御力比较高的茶色皮制HalfCoat。

购入的同时毫不犹豫的点下了即刻装备。初期装备的白麻衬衫与灰色马甲上，放出了光芒同
时一件皮革质感的装备实体化了。这少许增加的安心感让我呼了一口气，并从安放在武器店
墙壁上的镜子中看了下自己的大概样子。

“……这就是……我啊……”

不由得嘟囔道，柜台处打磨着短剑剑鞘的首位老店主抬了抬一侧的眉毛，很快就作业完毕走
了回来。

镜子中浮现出的虚拟体，除了身高和性别之外，其他都和自己之前苦心打造的“桐人”有着
很大的不同。

身体纤细了许多，脸上也没有点粗放的感觉。额头上的黑发长长垂下，瞳孔虽然也是黑色，
但比之前的要更暗了一些。这让人吃惊的精细建模，完全再现了现实世界中我的样子——

这个虚拟体，如果像之前的桐人那样身着闪着光芒的金属铠甲，一想到这些，身体就出现了
一股强烈的拒绝反应。所幸的是SAO中，即使是轻量的皮革装备，也能提供给速度型的单手
剑士以充分的防御力。当然还是无法成为吸引怪兽注意的肉盾战士，不过如果独行玩家要是
选择肉盾型构成的话那也就没有任何含义了。

今后在情况允许的条件下就一直穿皮革装备吧。而且尽量要使自己不那么显眼。

下定决心后，我走出了武器店。这次只是换上了HalfCoat，盾还不急，剑也是初期的就好。
随后又来到了武器店旁的道具店内，只买了回复药瓶与解毒药剂，持有的金钱便完全用光了。

没有买武器是有原因的。这个村落的武器店内出售的唯一单手剑“BronzeSword”虽然在威
力方面比初期装备的“SmallSword”要高，但耐久度的耗损却要快一些，而且不擅长应对植
物怪兽释放的腐蚀液。如果仅考虑数量的话还是SmallSword要更好一些。虽说如此，但也不
能总是用这把贫弱的初期用剑。从道具店走出的我，奔跑着来到了位于村落最里处的一户民
家内。

在厨房内搅拌着锅，诚然一副“女主人”模样的NPC转过身来，对着我说：

“晚上好，旅行剑士先生。你一定很累了吧，本应端上吃的招待你的，但现在却什么都没有。
能拿出来的，也只有这一杯水了。”

我立即用系统能够识别的清晰的话语应答道。

“这就行了。”

本来说出“好”或者“YES”这些就够了，刚才之所以说出那些也只是氛围的问题。不过出
于礼仪应该说出的“不用客气”这番话却怎么也说不出来。

NPC把古旧的被子装满水，放到了我前面的桌子上。我坐到椅子上，将水一口气喝干。

稍微笑了笑，女主人再次调理起锅内的东西。明明在煮着些什么，却说“拿不出吃的东西”，
可能是某种暗示吧。我一直等候着，终于从身旁的房门处，传来了咳咳，的小孩的咳嗽声。
女主人悲伤似地垂下了肩膀。

又等了几秒钟，终于在她的头上，出现了金色的任务标示记号。这就是产生任务的标记。我
立即开口说道：

“你有什么困难吗？”

这便是几种接受NPC任务方法的其中之一。慢慢望向这里的女主人头上的“？”开始闪烁起
来。

“旅行剑士先生，实际上是我的女儿……”

——女儿因患重病，光靠煎煮这些市场上购买的药草（也就是锅内的东西）还是无法医治，还
需要栖息于森林西部的捕食植物的胚珠一同饮用才行，但那种植物十分的危险，并且还有一
盛开着花的个体守护着它，所以自己根本无法得到，如果剑士先生能够代替自己将其取来的
话就把先祖传下来的长剑当做回礼献上。

女主人却夹杂着姿势与手势道出了大意就是以上那些的话来，我则是强忍着听完了。不听到
最后任务是无法进行下去的，说话期间还时不时的听到了隔壁女主人的女儿传来的咳嗽声，
但我却无论如何也怜悯不起来。

女主人终于闭上了嘴，视野左侧的任务记录中更新了内容。

我站起身，大声叫道“就交给我吧！”——虽然没必要，但这都是心情上的问题——随后便离开
了该户民家。

不久后，广场中央的小型高台上奏响了可以传遍整个村落的钟声。午后七点。

现实世界的现在又是什么样子呢。毫无疑问会产生巨大的骚动。大概此时母亲与妹妹，正站
在戴着NervGear躺在自己房间的我的身旁吧。

不过，我能像现在这样继续在艾恩葛朗特内生存者，大概是因为母亲与妹妹并没有强行将
NervGear给取下吧。也就是说，两人对于茅场晶彦的警告，以及我还生存的这些事，应该都
是很相信的吧。

要想从这个死亡游戏中生还，就必须有人突破那高达百层的浮游城艾恩葛朗特的最高一层，
打倒那不知是不是怪物的，无法想象的最终BOSS，将游戏Clear掉才行。

当然我根本没想自己去完成这个目标。我所做的，不，是要去做的事就只有一件，尽全力生
存下去，仅此而已。

首先必须得变得更加强大。至少在这个层，不管怎么样的怪兽来多少只……或者是被恶意的
玩家袭击，都必须守护住自己的性命。今后的事情还是今后再去想吧。

“……抱歉，妈妈。让你担心了……抱歉，直叶。你讨厌的VR游戏，居然会变成这样……”

无意识说出这些话，多少让自己也有些吃惊。最后用省略形叫出妹妹名字，都已经是三年前
的事情了。

如果——如果能够生还，再次碰面的话，我想再用“直叶”去称呼她。

没有任何理由，下定决心的我，穿过村落的大门，朝着让人毛骨悚然的夜之森前去。

*** 4
由于艾恩葛朗特内部并不是中空的，下一层的底部就建在头顶上百米处延展而开，因此能够
直接看到太阳的时间也只有在早上与傍晚。当然月亮也是如此。

虽说如此，但白天也不是昏暗，晚上也不是一片漆黑，VR空间由于有着空间照明，因此依旧
保有充分的亮度。即便是在夜间的森林，虽没有白天那么亮但依旧有着淡青色的光芒照到脚
边，行走完全不会有所不便。

但，心理上会产生不寒而栗的感觉那就是另外的问题了。周围究竟有什么，身后突然会出现
些什么，这种不安的感觉周期性的涌起。这种时候虽然想起了团队游戏时的安心感，但现在
也没办法返回了吧。不论是距离上，还是系统上。

等级为一级时被赋予的“剑技孔槽”只有两个。

在今天午后一点游戏正式开始时，我便将其中一个用“单手直剑”给填上了，本想空着另外
一个好好想想究竟要嵌入什么。不过，在那恶魔般的演说在初始之街出现之后，烦恼究竟要
装什么技能的乐趣就业被夺去了。

作为独行玩家，必须要有几个技能。其中最重要的就是“索敌”与“隐蔽”。不论这两个当
中的哪一个都能提升生存率，与在提升狩猎效率有所帮助的前者不同，后者由于某些原因在
森林中的效果稍微有些薄弱。所以我率先选择了索敌技能，等到下一个技能槽开放时再添加
隐蔽技能进去。

不过，这些技能，对于原本安全性就很高，用人力——也就是眼睛索敌，范围也很广的团队协
作的玩家来说并不受到重视。也就是说，选取了“索敌”的现在，我就必须得贯彻独行这条
道到底不可了。即便是后悔选择了这些的时刻来临，但至少不是现在……

脑海某处思索着这些，并不断向前行走的我的视野中，出现了一小小的ColorCursor。由于
索敌技反应距离得到了提升，但本体却依旧无法识别。Cursor的颜色虽是识别为怪兽的红色，
但色泽却要更为浓郁，已不是RED而达到了Magenta【品红】的程度。

从红色的浓淡，可以大致推测出敌人的相对强度。无论怎么也无法取胜，具有压倒性等级差
的怪兽其Cursor颜色会比血色还要浓郁，达到Dark Crimson。相对，是那些打了许多只经验
却得不了多少的杂兵怪兽的话，颜色则是接近白色的Pale Pink。同一级别的敌人，则是用
Pure Red。

现在，在我视野内出现的Cursor，其色泽要比红色稍微深一点。怪兽的名字是“Little
Nepente【荷兰语，食虫植物】”。虽然写的是Little，但却是个身长约有一米半的自走捕
食植物。由于等级是三，因此在等级为一的我看来，Cursor会带有些紫色。

虽不是那种可以轻视的对手，但也无需害怕。稍有些紫色Cursor外，还有一条狭长的黄色边
框。标示了此Mob就是该次任务的目标。

我停下脚步，确认周围有没有其他的Mob后，正面对着LittleNepente奔去。对付这种没有长
眼睛的怪兽，采取背后偷袭的手法一般是无法奏效的。

顺着小路前行，绕过巨大的古木，怪兽的模样终于映入了眼帘。

猪笼草【Nepenthes】般的下体上生长着无数根不断蠕动着的移动用根。长在左右两侧带有
锋利叶片的藤蔓则在蜿蜒扭动，头部附近捕食“嘴”则是一张一合地，不断地流淌出粘液。

“…………没有遇上啊。”

到了终于可以辨清的距离，我低声这么说道。我期望的是嘴上长有一盛开花朵的家伙。在ホ
ルンカ村接受的任务的关键道具“Little Nepente的胚珠”，只能从长有花朵的Nepente上
刷到。并且那品种的出现率还不到百分之一。

不过，即便是普通的Nepente，只要持续不断的打倒，带花的品种的出现率也会随之提升。
因此这并不是白费工夫的战斗，但这里还是得有一点必须注意不可。

和带花的家伙几乎相同的概率，会刷出长有果实的Nepente。那品种完全就相当于“陷阱”，
战斗中只要攻击果实就会发出巨大的声响并炸裂开来，散出恶心气味的烟尘。烟尘虽然无毒
也无腐蚀性，但会把很远范围内的Nepente吸引过来，使战况变为不利。如果区域刷怪点枯
竭就无法召来很多，不过要是现在的话应该会吸引来无法招架的数量吧。

我再次望去，确定敌人是没有果实的家伙后，拔出了背上的剑。同一时间Nepente也觉察到
了我，威吓似地将两只藤蔓高高举起。

此Mob的攻击方式是，用前端如同短剑般的藤蔓斩击或突刺，以及从口中喷出腐蚀液。虽然
攻击方式比起只会一个劲的突进的青野猪要丰富许多，但就凭它不会使用剑技这点，就比
Kobold还有哥布林这种亚人型Mob要容易对付多了。

除开以上这些，此怪兽在能力上侧重于攻击，防御则很薄弱。在“之前的艾恩葛朗特”中我
最擅长的就是对付这种怪兽。可以在短时间内毫发无损地猎杀许多只。

“咻呜呜呜呜！”

捕食器嘴发出咆哮，Nepente的右侧藤蔓刺了过来。瞬时我便看穿了其攻击轨道，向左跳去
回避了此攻击。迂回到了那家伙的侧面，举剑朝其猪笼草部分与粗大茎的接合处——也就是弱
点处猛砍下去。

手感很充足。Nepente的HP顿时减少了近两成以上。

再次发出怒号声，植物怪兽将猪笼草部分膨胀起来。这就是腐蚀液发射的预备动作。射程有
五米长，只要朝后方退去便能躲避开来。

如果被击中的话HP与武器防具的耐久度会大幅减少，除此之外其粘着力还会在一段时间妨碍
行动力。不过其效果范围只限于很狭窄的正前方三十度。我抓住那千钧一发的时机，在猪笼
草部分膨胀停止的瞬间，这次毫不犹豫的向右侧闪去。

噗咻！淡绿色的液体如喷雾般发射而出，落在地面上冒出白色的蒸汽。不过我却一滴都没有
粘上，回避后的我，立即右脚蹬地，高举直剑，再次朝着相同的弱点给予痛击。Nepente发
出惨叫并向后弯曲，其捕食上出现了黄色螺旋光效。气绝状态。植物会气绝真是个奇妙的事
情啊，不过这个时机是不能放过的。

我再次将剑拉回到右后方，这瞬间的动作便是剑技的开始，刀身被浅水色的光泽包裹。

“……啊啊！”

这场战斗中——我可能是SAO正式开服以来第一次卯足全力去蹬踏地面吧。单发水平斩击技能
“Horizontal”。只是在轨道的斜度与水平角度上与“Slant”不同，不过却能更容易地击
中Little Nepente的弱点。

由于之前两次斩击损失了近五成HP的植物Mob，就在从Stun状态恢复前的刹那，其外露的茎
部遭到了剑技的直击。当然我是用蹬地与右臂的动作将威力提到了最大限度。闪耀着光泽的
刀身，深深的砍进硬质的茎内，留下了极短时间的手感——

撕拉！干涩的声音响起，猪笼草部与茎被切断了，球状部分整个飞了出去。剩余的HP全部染
成了红色，从右侧开始不断减少。在变成零的瞬间，Little Nepente的巨大身躯便凝结成青
晶。随后，四散开来。

剑依旧保持着前斩的技后动作，我的动作就这样停了下来。视野中浮现出了差不多两倍于野
猪的经验值加算标示。战斗时间约四十秒。用这个步调继续狩猎的话，应该是十分有效率的。

右手垂在下方，我巡视起四周。在索敌范围的临界处，出现了复数个Little Nepente的
Cursor。但依旧没有发现玩家的标记。

在其他人来到这个狩猎场前，要尽可能的赚取经验值才行。得拿出把这一带的POP清光的势
头来。就算再怎么往好的方向想这也是过于自我主义了，但博爱主义的独行玩家才是自相矛
盾的存在吧。

抛开情感并锁定了下一个目标的我，再度在深邃的森林中奔跑起来。

*** 5
接下来的十五分钟内，我又击杀了十几只Little Nepente。

很遗憾的是到现在为止都没发现一只带花的个体。套用游戏用语来说在那些“依靠现实幸运
值”——也就是被玩家本人运气的好坏所左右——的任务中，我从未被幸运眷顾过。

令人不爽的是，这个世界居然存在着，能够频繁刷出调出率只有百分之〇点〇〇几超级稀有
道具，还能够连续十数次成功强化武器，并且还能在游戏中和女生搞好关系的，以豪运为傲
的玩家。与他们相对的是，我就只能不断的尝试，别无他法。当然说是尝试也只是在刷稀有
道具的方面，就算是遇见了女性玩家我也不打算前去打招呼。[fn:42]

而且，在已经称神的茅场的手段下，游戏内的虚拟体都和现实的姿态同一化的现在，艾恩葛
朗特的女性玩家应该是锐减了很多。不过这也免去了怀疑对方的真实身份究竟是不是男人，
不过这对于那些装扮为女性角色，并且取了女生气的姓名&选择了武器装备的家伙来说应该
是个很大的试炼吧。他们唯一能做的，就是祈祷茅场会为他们准备能获得改名道具的补救任
务了吧……

不知是不是有些从容，边在脑海中思索起这些事，边击倒了第十一只植物Monster的我的耳
中，突然听到了一阵欢快的乐曲声。同时，全身被金色的特效所包裹。加上死亡游戏开始前
我和克莱因一同狩猎的野猪的份，经验值总算是超过了升级所需的必要值。

如果是团队作战的话，此时应该会有“祝贺你”的声音从身旁传来吧。不过，此时却只有古
木树梢发出的沙沙声，我把剑收入身后的鞘中。右手的食指与中指并在一起向下挥动，调出
菜单窗口。点击并进入状态栏，把得到的三点贵重状态提升点，分配给了力量一点，敏捷两
点。在没有魔法存在的SAO中，可视的状态只有这两项，因此完全没有犹豫的必要。不过相
对的，却设定了大量的战斗系-生产系技能——因此，在技能槽增加那时，应该也会十分苦恼
的吧。

不过，今天这一天，这一小时中我不得不拼命生存下去。考虑到未来，必须确保等级的充裕，
也就是“安全保障”才行。

加完点数，将窗口消去时，我的身后——

突然间，啪啪啪的，连续响起了某种清脆的音效。

“……！！”

向后纵身一跃，把手放在剑柄上。专注于窗口操作而疏忽了身后的警戒，这犯可是初学者的
错误啊。

内心责骂着自己同时进入战斗态势的我的眼前，从森林中出现了一人型怪兽——不对，是个人。

并且不是NPC。而是玩家。

是个比我稍高一些的男性玩家。年纪差不多。防具则是在ホルンカ村购买的轻量革铠与圆形
盾。武器也是同为初期装备的SmallSword。虽说如此但并没有握在手中。空着的双手在身体
前不断地拍打，张开着嘴。

也就是说，刚才的啪啪的SE音效，就是这个少年，对我的等级提升投来的拍手声吧。

我呼出一口气放下右手，少年对着我投来了僵硬的微笑，行了一礼。

“……抱，抱歉，吓着你了吧。我一开始应该打声招呼啊。”

“…………没，我才是……反应有点过激了。”

嘟哝着回应了对方，并把不知该摆在哪里的手插进口袋中。第一印象给人一种严肃的少年，
露出了笑脸，也不知道是何手势，他把右手指放到了与右眼同高处。很快又像是很抱歉似的
把手放了下来。在现实世界中，此人应该是戴着眼镜吧。

“祝贺你升、升级。很快嘛。”

听到少年的话，我不禁缩了缩头。就像是刚才思索“如果是在团队作战中”的这个想法被看
穿了似的，感觉很尴尬。随后又慌忙摇起头来。

“也不怎么快……——真要说起这些，你不是也一样。我认为还要两、三个小时才会有人赶到
这个森林来呢。”

“啊哈哈，我也以为自己是头一个呢。这里的路十分难记啊。”

听到这话的瞬间，我终于觉察到了这点，虽然有点晚。

他，和我一样。

并不是说的武器与性别。也不是因为他与我都囚困在SAO内。

这个少年知道跟我相同的事情。ホルンカ村的位置。没有购买BronzeSword的理由。还有这
个Little Nepente大量出现的地带。也就是——

“原β【封测】者”。和我一样。

召集了一万名玩家的，世界上第一个VRMMO游戏的SwordArt-Online正式服务器，是在今天，
也就是二〇二二年十一月六日开服的。不过，就在三个月前，曾公开用抽选的方式募集了一
千人，进行了游戏启动试验——也就是实施了βTest。

对于寄去的数十万封申请函的内测，当时的我发挥了前所未有的现实幸运值（现在恐怕只有
坏运气了），被抽中了。测试期间几乎都在八月。由于是在暑假这个时间，我便从早到晚——
正确来说是从白天到第二天一早都潜行于其中，完全沉浸在了这个还没架起死之门槛的艾恩
葛朗特中，重复着挥剑，然后死去这一过程。不知多少次，多少次。

经由这无限次的Try&Error，我积攒了大量的知识。

地图上没有标示的小道，近路。街道与村落的位置，商店里出售的东西。还有出售武器的价
格和规格。任务的发生条件以及攻略法。怪兽的出现区域与战斗力，还有弱点——

正因为有这些知识，我才会活着来到这里——来到这个远离初始之街的森林深处。如果不是
βTester而是完全的新手的话，大概根本不会考虑一个人从那个街区离开吧。

数米开外的少年，大概也是如此吧。

头发比我稍长些的单手剑士，毫无疑问和我一样，都是有经验的封测玩家。知道这条在这片
森林的迷宫般的小道，以及言谈举止，不论哪一点都能告诉我，此人完全习惯了SAO原创VR
引擎。

用了数秒才展开至此的我的推测，少年却用一句话漂亮的道破了。

“你也是在做吧，‘森林的秘药’这个任务。”

毫无疑问，这就是我刚才在村落的民家内接受的任务名。既然被看穿了那也就不好再否定了。
我点了点头，只见对方再次推了推那看不见的眼镜，笑了起来。

“那可是，单手剑士必须要做的任务啊。得到那把作为报酬的‘Anneal Blade’的话，可以
能够一直用到第三层哟。”

“……不过外表看起来不怎么样啊，那把剑。”

我补充道，少年啊哈哈哈的发出了爽朗的笑声。很快又停了下来，吸了一口气，再次张开嘴。
说出这番多少出乎我意料的话来。

“的亏我们能遇到一起，任务，要我帮忙吗？”

“诶……但是，这可是定额为一人的任务哟。”

下意识的回答道。即便是处于组队状态，也不可能让所有人都能完成，“森林的秘药”就是
这种。由于关键道具“Little Nepente的胚珠”一匹只刷到一个，即便是团队挑战到头来道
具也不可能每人一把。

不过，少年像是预料到了我的这番话似的，笑了起来。

“虽说如此，但‘带花的品种’只要不断地刷普通种就能提高出现率吧。两人一起刷的话效
率更高哟。”

的确是这样。独行玩家的我只能猎取那些孤立的怪兽，两人的话就能同时应对两只了。也会
缩短选取目标的时间，狩猎的时间随之也会增加——这样以来带花的家伙的出现率也会提升的。

就在我准备点头时，突然虚拟体整个僵硬起来。

就在一小时前，将性格豪爽、名为克莱因的刀客……也是我最初交到的朋友抛弃的我，难道
现在有和其他人组队的资格吗，我这么想到。

不过，少年像是把我的犹豫理解成了其他的意思，慌忙摇了摇头。

“不，不组队也没关系的哟。因为接下来要做的还是你一个人，最初掉落的关键道具当然也
会让给你。只要持续狩猎不断提升几率的话，很快就会出现第二只的哟，那时你再让给我就
行……”

“啊……啊啊，这样啊……那，就不好意思了……”

我咬着牙不好意思的说道，并点了点头。如果组队战斗的话，怪兽掉落的东西并不是归个人
所有，而是贮存在一个临时的团队储藏格中，原理上那个关键道具也会是这样。我大概就是
怕这点吧。实际上我并没有心细到那种地步，只不过现在也无法再做出更正了。

对于我的应答，少年再次露出微笑，走到身旁递出右手。

“太好了，那就事不宜迟，赶快行动吧。我叫‘柯贝尔’。”

既然同为封测者，即便是相互认识也不会奇怪，不过我却没有听说过这个名字。

当然也有可能是使用了与封测时代完全不同的名字，而且他的Color Cursor上也没有名字出
现，因此无法断言这就是其“本名”。同样，我也有使用假名的可能性。不过，由于十分不
擅长起名字，到现在为止我在各种各样的游戏中使用的名字，都是自己本名的省略，因此要
我突然想出一个虚假的名字来，这点我怎么也做不到。

“……请多关照，我叫桐人。”

名为柯贝尔的少年——轻轻偏了偏头。

“……桐人……阿勒，像在哪里…………”

看来，对方是从其他人那里听到了封测时期的我的事情啊。下意识感到不妙的我，即刻回答
道：

“你弄错人了。那，就让我们狩猎吧。在其他玩家赶到这里来前，打出两只‘胚珠’吧。”

“嗯……嗯，是啊。加油吧。”

点了点头，我和柯贝尔便朝着附近有两只Little Nepente在一起的地方奔去。

*** 6
不愧是原封测者，柯贝尔的实力不容小觑。

单手剑的间隔与怪兽的举动，还有剑技的使用等等都十分清楚。在我眼中看来虽然是太有些
注重防御了，不过考虑到现如今的状况，这样做也不无道理。柯贝尔最先选择的是，被我极
力攻击了弱点的那只，并与我产生连携，被两人一个接一个盯上的猎物最终都化作了多边形
的碎片。

狩猎十分平稳，但仔细考虑的话，就会发现一个奇妙的状况。

我和柯贝尔从开始到现在，对于SAO的现状什么都没有谈及。茅场的宣言是真的吗？在这里
死去，真的会死吗？今后这个世界会变得怎么样呢……？这些疑问柯贝尔当然也应该感觉到
了，不过我俩从最开始到现在商讨的却只有任务及其道具。而且对话也很自然。

也就是说——两人，大概都是重度的MMO中毒者吧。这个世界变成了死亡游戏，登出的按键也
消失了，既然在游戏当中总之还是先去做任务和赚取经验。完全没有考虑如何才能被救出的
事，仔细想想，柯贝尔既然也应征参与了SAO的封测【βTest】，那么毫无疑问他也是名深
入到骨髓的网游玩家。单单只是因为，比起死的恐怖，想要去强化角色的冲动要更为优先
吧……

不。

不，这也不对。

不论是我还是柯贝尔，一定都，无法直视这个现实吧。

升级效率以及怪点的枯竭虽然能够预算出这些，但根本上来说思考却已经停止了。HP变为零
时NervGear就会发射一种高强度的电磁波烧毁大脑，两人把视线从此现实上移开，只是将打
怪升级作为一种逃避的手段，胡乱地朝着“前方”走去。倒不如说，依旧留在初始之街的玩
家们，在很大程度上能够更为冷静地去理解当前的状况吧。

不过，如果这样的话——

我现在能够这样以平常心应战恐怖的怪兽，大概也是因为没有看到现实吧。无法感受到死的
恐怖，并以最小限度的动作，回避着可能会杀掉自己的锋利的藤蔓和那危险的腐蚀液。

领悟到这些的瞬间，我同时直接感受到了。

啊啊……再过一阵的话，我一定会死掉的吧。

“现实的死”，无法理解死亡游戏这条首要的规则的话，也就代表着无法看清那条不该踏入
的线在哪里。仔细想想，我一人独自离开街道，踏进这不详的夜之森林区域，还真是个无谋
的举动啊。

抖！一阵恶寒从脊背传到手脚的末端，妨碍了我的虚拟体的活动。

就在这时，我已经举剑对准了不知道是第多少只LittleNepente的弱点处，再僵硬个半秒的
话可能就会受到猛烈的反击吧。

回过神来，再次启动的剑技“Horizontal”，勉强斩断了植物的茎部。响起了破碎的音符，
无实体的玻璃碎片穿过我的身体向四周散去。

背对着我，和另一只Nepente作战的柯贝尔，所幸没有觉察到我的异常。大约晚了五秒钟，
他便在没有使用剑技的情况下斩杀了那只怪兽，呼出一口气转过身来。

“……没有出来啊……”

声音透漏出了一股疲惫的神色。从我与柯贝尔搭档狩猎开始，已经持续了一个小时以上。两
人加起来应该干掉了近一百五十只Nepente，但“带花”的品种却依旧没有刷出。

我把刚才一直盘踞在背部的那股寒气摒去，用大幅度的动作耸了耸肩。

“可能出现率和封测时期有所变化吧……稀有道具掉落率，在正式开服之后会有所修正，我
在其他MMO游戏中也曾听说过……”

“……可能是这样吧……——接下来怎么办？等级也提升得够多了，武器也应该耗损了很多，
还是先回下村里……”

就在柯贝尔说出这话时，离我们差不多有十米远的树下，出现了淡淡的红光。

空间中描绘出了几个凹凸不平外形粗糙多边形块，并组合到了一起，慢慢形成大致的轮廓。
这也是本人见怪不怪了的光景——怪兽的刷出【POP】。

就和刚才柯贝尔所说的一样，到现在为止的“胡乱狩猎”已经赚取了大量的经验值，两人一
同达到了三级。最适合攻破第一层的等级，封测时期大概是十级。想要继续向前还为时尚早，
再猎取一只Nepente的话也没必要那么慌张。敌人的Cursor Color也由Magenta【品红】降成
了Red【红色】。

“……”

我与柯贝尔站在草丛中，呆呆着望着涌出的怪兽。数秒后，第一百十几只Nepente细节变得
精细起来，摇晃着藤蔓开始走动。散发出生物光泽的绿色茎部，以及那具有个体差异的猪笼
草模样的彩色捕食器，还有在顶上的——即便在昏暗处也能看到那发出的剧毒般的红色光辉的
类似郁金香的巨大花朵。

“…………”

我俩就这样呆呆的望了数秒，随后无言的对视起来。

“……——！！”

发出了无声的欢呼。架起各自的剑，如同准备袭击老鼠的猫咪似的，朝着出现的“花朵”飞
奔而去——

但就在到达前，我双脚猛地刹车，同时伸出左手将身旁的柯贝尔也拦了下来。

怎么了！？看着望向我的伙伴，我伸出左手用食指指了指，“花朵”更远处的地方。

被树木阻挡很难辨认，不过在那个方向，是还有着另一个Nepente的身影。能够注意到，都
是亏了本人索敌技能的熟练度稍有上升的缘故。柯贝尔不知道是不是没有升级索敌技能，只
见他聚精会神地盯着黑暗处，花了数秒钟终于辨识了那个的正体。

如果隐藏在带花种后方的是普通的Nepente的话，那就没有理由不去攻打。不过就是因为那
第二只的捕食器上方，顶着一个巨大的肿块在不断晃动着。

如果也是花的话，那我就能将“现实运气很低”的招牌给摘下来了。不过，挂在第二只
Nepente纤细的茎部上的，是一只直径二十厘米的圆球——“果实”。只要稍微碰一下那富有
弹性的膨胀物的话，便会立即炸裂开来，散发出带有气味的烟尘。烟尘会把附近变得狂乱的
Nepente群招到此处，即便等级有所提升，也会让我们陷入无法脱身的境地。

该如何是好。

我迷茫了。在战力上，要想无伤做掉“花朵”有很大的可能性。不过也不是绝对。稍有不慎
就会有死亡的危险，这里还是先忍着，等着花与果实分离开来吧。

不过，在封测时期听过的传言加速了我的迷茫。Little Nepente的“带花”种，是能掉出任
务关键道具的稀有怪兽，如果POP【从怪点刷出】出来后放着不管的话，是会变化成危险至
极的陷阱怪兽“果实”的……这都是当时从旁人那里听来的。

这也不是不可能的，说起来倒像是真的。就这样待在草丛中望着对面，数十米开外移动着的
带花Nepente的花朵一片一片散去，正中间的圆形果实不断膨胀，加上之前那只，果实
Nepente可能会变成两只吧——

“……怎么办……”

不知如何是好的我，这么说道。此时陷入迷茫，不正是因为自己无法分辨危险与安全的分界
线的证据吗。被迷惑所困，就无法由理性做出判断，不过现在单品理性去判断也没什么信用
度了。

如同中了Stun攻击似的，无法动弹的我的耳中，传来了柯贝尔的低语声。

“——上吧。我去压制‘果实’，桐人请速攻击倒那只‘花朵’。”

没等我做出回应，他便冲了出去。

“…………明白了。”

我应答道，跟着追了出去。

虽没有斩断迷茫。但也只能上了。即便状况有什么变化，也只能将精力集中到剑与虚拟体的
操作上了。如果什么都不做的话，就真的会死的。

首先是带花的Nepente觉察到了柯贝尔的接近，咕噜的将身体转了过来。捕食器那如同人类
唇瓣的边缘抖动起来，发出“沙啊啊啊啊！”的吼声。

花朵将向右迂回，朝着更远处的果实方向前进的柯贝尔锁定为目标。利用这个空隙，冲到它
跟前的我，毫不犹豫地挥下了右手剑。

虽然是出现率只有百分之一以下的稀有怪兽，但带花种类的Nepente的数值也和普通的种类
无异。防御力与攻击力虽然高了一点，但经过了一小时的狩猎，等级达到三级的我看来，就
像是没有一样。

脑中虽然还有许多疑惑，但经由封测时期积累下来的战斗经验却让虚拟体自动活动了起来，
用弹返跳跃回避掉Nepente的藤蔓攻击，并给予回击。十秒便让其HP变成了黄色，一度向后
跃去的我对其施展出了致命一击的剑技。

持续的战斗让单手直剑的技能熟练度也得到了提升，技能的发动速度与射程的上升也很有实
感。准备吐出腐蚀液的Nepente，在其捕食器还未膨胀到一半时，单发水平斩击
“Horizontal”划出一条青色的弧线，响起清脆的音符，切断了肉质的茎。

发出了与普通种类不同的惨叫声。分离开来的猪笼草部分落到了地面上，就在其化作多边形
碎片散开前——位于头顶处的花唰啦唰啦地凋零了。

花中落下一只拳头般大小，闪着浅色光泽的球体。咕噜咕噜地滚到我的身旁，并被我用脚停
了下来，就在这一刻，Nepente的身体与捕食器一个接一个的爆碎开来。

我弯下身子，用左手拾起发光的球体——“Little Nepente的胚珠”。为了入手这个关键道具，
恐怕击倒了超过一百五十只怪兽，而且在过程中还陷入了各种各样的迷茫之中。

想着这些的我只想一屁股做到草地上，但脱力还为时尚早。必须得去援护就在不远处，压制
住“果实”的柯贝尔不可。

“抱歉，让你久等了！”

我抬起头大声说道，将左手握着的胚珠放到了腰间的口袋中。打开窗口将其放入道具栏中应
该更为安心，不过现在不是悠闲地进行这种操作的时候。我再次握紧剑，跑出去数步————

虽说如此，脚为何停了下来呢。

自己也不清楚原因。前方的，突然和自己成为伙伴的柯贝尔，正用剑与圆盾抵抗者Nepente
的攻击。大概是原本就很善于防御吧，在战斗中还有空闲似的时不时看看这边。给人十分严
肃的印象，稍微有些眯的双眼，正一直盯着我——其，视线像是蕴含着什么意思，让我停下了
脚步。

为何？为何柯贝尔要用那种眼神看着我？怀疑，或者说是哀悯的眼神。

将Nepente的藤蔓攻击用挑击猛地弹开，中断了战斗的柯贝尔，望着我，简短的说出了这样
一番话。

“抱歉，桐人。”

随后视线再次回到怪兽上，将右手剑高高举起。刀身发出浅青色的光芒。这是剑技发动的瞬
间。那准备动作——是单发垂直斩击，“Vertical”。

“不要……不行啊，那个会……”

因柯贝尔刚才的那番话陷入困惑的我，无意识中这么说道。

出于茎上部隐藏在坚硬的捕食器中的Little Nepente的弱点，原本用纵向斩击就起不到多大
的效果。而且，如今柯贝尔也知道不能使用纵向斩击的原因。他也应该很明白这点的。

不过，释放而出的剑技是无法停下来的。被系统辅助半自动操作了的虚拟体，猛地蹬踏地面，
发光刀身对准Nepente的捕食器——上部摇摆着的圆形“果实”砍去。

啪啊啊啊！

巨大的破裂声让整个森林都摇摆起来。

我是第二次听到这个声音了。第一次当然是在封测期间。那时，临时组建的小队伙伴用长枪
刺了过去，面对这些被气味吸引过来的大批Nepente，等级只有两三级的四名伙伴还没来得
及逃走就死掉了。

将果实打得粉碎的柯贝尔的“Vertical”，就这样直接避开了Nepente的捕食器，将HP全部
扣光。即便怪兽瞬间灰飞烟灭，但残留在空中的淡绿色烟尘，以及我嗅到的异样气息却未消
散。

我望着避开烟尘向后退去的柯贝尔，呆然地说：

“为…………为什么…………”

这不是事故。是有意图的攻击。柯贝尔基于自身的意志，对着“果实”砍了过去，并让其破
裂开来。

在这一小时，和我共同作战的原封测者，看也没看我，就这样再度说道：

“……抱歉。”

在其虚拟体的方向，出现了几个Color Cursor。

不管是右边，还是左边。甚至是身后也出现了。那些都是被烟尘吸引而来的LittleNepente。
在这片区域POP出的个体，毫不保留的都聚集到了此地。总数，二十……不，超过三十只。
不行，得出此判断的瞬间我的腿擅自想开始逃走，不过却没有办法脱身。即使突破包围圈，
Nepente也有着那光看外表所无法想象的最高速移动，而且在脱离时也会成为其他怪兽的目
标吧。几乎可以说是无法脱离——

也就是说，这是，自杀。

连同我一起，死在这里吗？柯贝尔，已经被“现实的死”所击溃，想从这个死亡游戏中投降
吗？

站在那里，我恍惚地思索着。

瞥都没瞥我一眼的柯贝尔将剑收到左腰的鞘内，转过身，朝着附近的树丛跑去。那步伐并不
犹豫。他还没有放弃生存。只不过。

“没用的……”

我从喉咙内发出这不成声音的话来。

LittleNepente的大部队已经全方位的杀来了。即便从间隙中窜行，用剑杀开一条道也是十
分困难的，假如能够成功也会被其他怪兽所阻截。不，既然此时要逃走，那之前，柯贝尔为
何要用“Vertical”去砍那果实呢。既然想死，那又为何要害怕大规模怪兽的到来呢，到了
最后还要去挣扎呢。

我用已半数陷入麻痹的意识某部分，不断思考着这些，并紧跟着逃进了树丛中的柯贝尔。被
丛生的密林遮挡，虚拟体虽然无法看见，不过Color Cursor应该能——…………

不过却没有显示出来。明明距离还不到二十米，柯贝尔就从我的视线中消失了。是使用“转
移结晶”紧急脱逃了吗，一瞬间会做出此反应也不足为奇。不过那个道具应该是很高的价格，
而且在游戏序盘是无法买到的，而且在第一层也没有能够掉落此道具的怪兽存在。

那么，答案就只有一个。“隐蔽”技能的特殊效果。将Cursor从玩家的视野中消除，不会成
为怪兽攻击的目标。柯贝尔的第二个技能槽并没有空置，而是装载了隐蔽技能。所以，在最
初遇见时，我才没有发现从身后接近我的他……

感受着朝此赶来的怪兽群的步伐所致的地震效果，我做出了以上推论，最后终于——未免有些
晚了，意识到了这点。

柯贝尔并不是害怕自杀而逃走的。

他是想杀掉我。

为此他才会切开“果实”，将周围的Nepente吸引过来。完成后再利用隐蔽技能躲避起来。
超过三十只怪兽，全部会将不会隐蔽的我视为目标。真是个名为
“MPK【Monster-player-kill 说白了就是引怪过来杀死玩家】”古老手段啊。

知道了这点，其动机也就明晰了。柯贝尔是为了抢夺我刚才拾起的任务关键道具“Little
Nepente的胚珠”。只要我死了，没有收纳进道具格的物品就会这样落到地上。等到Nepente
集团散去后，他再拾起“胚珠”，返回村里，完成任务。

“…………是这样啊…………”

终于怪物群接近到了无须借用Cursor就能识别的距离，我远眺着它们，这么说道。

——柯贝尔。你不是无法正视事实啊。反倒是完全相反。你很早就认清了这个死亡游戏，并作
为玩家在这个舞台上展开表演。欺骗其他玩家，隐瞒事实，伺机展开抢夺，都是为了自己能
够活下去。

不可思议的是，我竟然没有一丝怒火与憎恨。

完全落入了陷阱，就要被杀掉了，但头脑却奇妙的平静了下来。其理由就是，仅存于柯贝尔
计划中的一个“疏漏”之处，我或许已经察觉了。

“……柯贝尔。你还真是不知道啊。”

就算是听见了，也会不明所以吧，我对着远处的茂林这么说道。

“大概，你也是第一次使用‘隐蔽’技能吧。那虽然是很方便的技能，只不过，也不是万能
的。这对于拥有视觉以外其它感官的怪兽来说，更是效果甚微。即使是Little Nepente那样
的。”

咻咻地发狂似的，如雪崩之势袭来的捕食植物的一部分，很明显是朝着柯贝尔隐蔽的方向冲
去了。他大概还没察觉，隐藏着的自己已经成为目标了吧。我之所以优先选取索敌而不是隐
蔽，也正是出于这个理由。

依旧保持着平静，转过身，将视线锁定到朝我这里突进的Nepente队列上。身后的敌人都朝
柯贝尔袭去了，暂时可以放着不管。在身后的家伙被干掉前，如果能够歼灭前方的敌人，就
有可能生还下去。当然，这大概也只有万分之一的可能性吧。

明明离死这么近，却依旧没有将其视为“现实”的我，重新握紧了手中的Small Sword。至
今为止进行了一百多回的战斗，耐久度应该耗损了许多吧，刀刃的许多地方都崩裂了。如果
继续胡乱使用的话，很有可能在这场战斗中折断。

斩击回数，要尽可能的少。要把借由蹬踏与振臂提高威力的“Horizontal”，精准地命中位
于捕食器正下方的敌人的弱点处，用一击干掉一只敌人。如果不能做到这点，毫无疑问就会
迎来武器消失这种最坏的死法吧。

身后，传来了怪兽的咆哮声与攻击音，还有柯贝尔在喊着些什么。

不过我没有回头，只是全身心地应对自己的敌人。

*** 7
接下来的数分钟——或者说是数十分钟的详细情况，我都无法一一想起来。

伦理般的思考近乎丧失。存在的只有，眼前的敌人与简朴的剑，还有操纵肉体——正确来说是
大脑发出的运动指令。

从怪兽的准备动作预测出攻击种类与轨道，用最小限度的动作进行回避，并用剑技施以回击。
虽然以往的战斗也是如此，但不同的是这回割舍掉了多余的动作，提高了精准度。

SAO中不存在“必中的魔法攻击”。所以，理论上来说，只要玩家的判断力与反应力具有压
倒性的实力的话，持续躲闪任何攻击也是可能的。既便如此，对于技能没有多少的我来说，
敌人的数量太多了，想要完全回避也是不可能的。前后左右一同袭来的藤蔓擦过四肢，接下
来皮革大衣也被零星腐蚀液烧出了大洞。为此HP也出现了损失，虚拟以及现实的“死”正一
步一步逼进。

不过，我却依旧勉强地回避着直击，继续挥舞手中的直剑。

回避掉直击后行动有个半秒延迟的话，刹那间就会被毫无间隔的，直到将HP减为零的追击打
中。要不就是我的HP慢慢被削减到零，就是在我停下来之后被瞬杀。

在封测时期，不，是以前玩过的大量MMO游戏中，我也有很多次陷入类似这种穷途末路的境
地。那时的我，在不服输地挣扎一下之后，就会想着“取回那些死亡惩罚扣除的东西真是麻
烦啊”、“只要武器不丢就好”这些想法，任由HP被减少到零。如果想在这个世界追求“现
实感”的话，现在也像那么做就好了。至少能知道茅场宣言的那番话到底是真的，还是单纯
地惹麻烦的恶作剧。脑海中像是微微听到了这些话。只不过我却无视了这些，将不断涌现的
Nepente，用“Slant”以及“Horizontal”一个接一个把它们的脑袋砍飞。

还不想死吗？当然啦。

但，却还有另外一个什么动机在继续支撑着我的战斗。如今，能够让我的嘴角狰狞地歪了起
来——并转变成笑容的什么原因。

就是这个，我这么想到。

那就是SAO。我在封测期间少说也连续潜行了两百小时以上，但却依旧没有弄清SAO这个游戏
的本质。并没有真正意义上的战斗过。

剑并不单单只是武器道具，身体也不仅仅是可以活动的物体。在他们与意识在极限领域一体
化时，就能到达这个境地。而我还只是在这个世界的入口处朝里窥视而已。还想知道以后的
事情。还想走得更远。

“呜…………哦哦哦哦啊啊啊啊！！”

吼叫着，踏着地面。

将光效抛在后方，释放而出的“Horizontal”，连续将纵向并在一起的两只Nepente的捕食
器削来，高高飞起。

随后，在身后稍远处，咔沙！发出了锐利，短暂的声音。

那和怪兽爆散开来的音效明显不同。是玩家死亡的声效。

被十多只怪兽围攻的柯贝尔，终于精疲力竭倒下了。

“…………！！”

下意识地想要转过身去，不过却忍住了了的我，将围在我身旁最后两只怪兽一个接一个地斩
杀了。

此时我才转了过去。

解决完最初目标的Nepente，像是渴求血液似的集中到了我这里。数量，七只。柯贝尔在那
种状况下至少解决了五只啊。到最后一刻也没发出惨叫，那并不是没有发出悲鸣的时间，而
是出于原封测者的矜持吧。

“…………辛苦了。”

我将这番应对着登出的玩家说出的话语脱口而出，把破烂不堪的剑架在正前方。此时逃走也
是有可能的，但在我的脑海内浮现的却只有一个选项。

发现新猎物，并向前突进的七只Nepente的最前方一只，其捕食器上方盛开着一朵鲜红的
“花”。

没有被MPK做掉的我，只要稍微努力一下，就能把柯贝尔的那份“胚珠”拿到手了。不过，
现在说这些也是没用了。行动的选择和结果。都是一样的。

HP已经不到撕成，再下去就会落入危险域的红色了，但我却感受不到一点死亡的气息。觉察
到右侧两只进入腐蚀液喷射状态的我，全力飞奔了过去，将处于蓄力而停止行动的敌人一同
解决掉了。
    
剩下五只，在接下来的二十五秒内便消灭掉了，战斗结束了。

*** 8
柯贝尔消失的地方，散落着他的SmallSword和圆盾。两者都和我的剑一样，消耗了很多。

他在这个浮游城艾恩葛朗特中战斗了数小时，然后死去了。正确来说是HP变成零，虚拟体四
散掉了。不过，在现实世界的日本的某个街区，躺在某个家中的，应该正操作着虚拟体的陌
生人可能真的死去了吧，虽然我无法确认这些。我能做的就只有目送这位名为柯贝尔的剑士。

我思索了一会儿，拾起他的剑，插到附近最大的一棵树的根部。紧接着把第二只花朵
Nepente上掉落的“胚珠”放到了树下。

“这是你的，柯贝尔。”

说完，我站了起来。放置在地面上的道具耐久度不断减少，最终还是会消失掉吧，这把剑也
只能在数小时内作为墓碑吧。

我转过身，顺着朝东的小路走去，打算回到村落。

被欺骗，与死神擦身而过，目击欺骗自己的人死掉，自己却勉强活了下来，但“死亡游戏的
现实感”却依旧很淡薄。不过，至少这份情感，也比之前要加深了许多。并不只是为了生存，
同时也是想知道SAO内的剑技的顶峰，也就是人类无止尽的欲求。

不知是不是两人胡乱的狩猎让这里的POP产生了枯竭，几乎没有和怪兽相遇，我就这样回到
了ホルンカ村。

时间是——晚九点。在茅场的演说结束后，已经过了三小时。

再怎么说，村落的广场上也应该有些玩家的身影了。他们大概也是原封测者吧。按照这个步
调，有封测经验的玩家应该会走到很前面啊，总有一天会和大多数毫无经验的玩家产生深刻
的隔阂吧……但，我应该没有害怕这点的资格吧。

现在没心情和任何人交谈，我为了不让玩家发现自己，使用小道朝着村落深处走去。所幸的
是，NPC还没有进入深夜活动模式，目的地的民家窗口依旧亮着橘黄色的灯光。

还是讲究形式敲了敲，随后再推开门，里面依旧没有任何变化，女主人还在那里煮着些什么。
头上，正浮着任务进行中的“！”记号。

我走到她身边，从腰间的口袋，掏出中心闪着淡绿色的球体——“Little Nepente的胚珠”递
了过去。

女主人仿佛一下子返回到了二十岁似地，脸部放出了光芒，接过了胚珠。在如同连珠炮一般
说出致谢的话语时，左侧视野上的任务记录依旧写着进行当中。

将胚珠扔到锅里的年轻女主人，朝着房间南侧的长柜走去，打开了盖子。从里面拿出一把，
有些古老，但释放出和初期装备在存在感上有着阶段差别的红色长剑。回到我跟前，再次行
了个礼，同时双手将剑递出。

“…………谢谢。”

说着这话，我把剑接了过来。右手传来一股沉重的感觉。体感大概是Small Sword的一点五
倍吧。为了找回封测时期帮了自己很大忙的剑——“Anneal Blade”的手感，看来还得再练习
一阵子啊。

视野中央蹦出了任务完成的信息，奖励经验值加算后，等级变成了四级。

以前的我，精神饱满地从这个村庄跑了出去，将出现在西部森林深处的“Large Nepente”
选为了此新剑的对手。

不过现在的我却没有任何力气了，在把新剑收纳到储存栏后，坐到了附近的椅子上。

明明完成了任务，但年轻的女主人却连一杯水都没端过来。而是背对着我，再次搅拌起锅子
里的东西。

事到如今才感到很大一股疲劳感向全身袭来，我就呆呆地继续看着NPC的举动。就这样，经
过了数分钟。在我视线前方，年轻的女主人从橱柜上拿下一只木杯子，把国内的东西倒了进
去。

女主人比刚才捧剑还要仔细似地端着这冒出热气的杯子，朝着里面的门走去。

我毫无理由的站了起来，追了过去。把门推开的NPC，来到了这间昏暗的小屋内。好像在封
测时期，我在想要推开这扇门时，应该是被系统锁上了的啊。虽然犹豫了一会儿，但还是迈
了进去。

这里时间小小的卧室。家具只有靠墙的衣柜，窗户旁边的床铺，以及一张小椅子。

床上则是躺着一位年约七八岁的少女。

即便在月光下也能知道少女的脸色很差。脖颈很细，从被单可以看到那瘦骨嶙峋的肩膀。

少女意识到了母亲的前来，微微睁开了眼，接下来——看了看我。诶，这不由得让我停了下来，
那毫无血色的嘴唇，微微现出了微笑。

母亲伸出右手，托着少女的背将其扶起。顿时，少女曲起了身体，咳、咳的咳嗽起来。茶色
的三股辫，在白色的睡衣上毫无气力的摆动起来。

我再次确认了一下，标示在少女身旁的Color Cursor。毫无疑问是NPC的符号。名字是
“Agatha”。是叫阿卡莎，吧。

温柔地轻抚少女——阿卡莎背的母亲，坐到了旁边的椅子上，说：

“阿卡莎，看啊，旅行的剑士大人，从森林里为你取来药了哟。喝了这个的话，一定会好起
来的。”

随后把左手拿着的被子放到了少女手中。

“……嗯。”

阿卡莎用可爱的声线点头回应道，并双手托住杯子，咕咚，咕咚地喝光了。

啪的一束黄金光线倾注而下，脸色突然变好了，少女从床上跳了起来，开始奔跑——这些都是
不可能。不过，将杯子放下的阿卡莎的脸，不知是不是错觉，稍微增加了些红润。

将空空如也的杯子还给母亲，阿卡莎再次望了眼站在门旁的我，微笑起来。

嘴唇动了动，说出的这番稍有些发音不清的话，就像是细小的宝石一样。

“谢谢你，哥哥。”

“…………啊……”

不知道该怎么回答，只得发出这种声音的我，睁大了双眼。

以前——

很久很久以前，也曾发生过这样的事。

妹妹……直叶感冒了，躺在床上。父亲依旧是在海外赴任，母亲也不得不回一趟公司，因此
两小时都是我一人在看护。当时，还是小学……究竟是几年级去了。说实话，当时我虽然感
觉很麻烦，但还是没有抛下她一个人去玩，而是给直叶擦汗，不断地将冷却的毛巾放到她额
头上，并将原有的取下。

就在这时，她却突然提出要喝姜汤水。

我马上给母亲打了电话，寻求了制作方法。随后将生姜挤出的汁水还有蜂蜜溶入到热水中，
虽然手法很差，但比起在艾恩葛朗特中的料理还是要简单很多，但料理等东西不知为何让我
来操作就会变得难度很高。手指在制作过程中被削皮器弄伤，经过百般折磨后总算是完工了，
在我把姜汤水搬到直叶跟前时，一直对我恶言相向的她，居然也投来了钦佩的目光————

“…………呜…………呜…………”

不经意间，这种声音，擅自从喉咙内传了出来。

想见。

想见直叶，母亲，还有老爸。

极强的冲动涌上整个虚拟体，我踉跄地，用双手按住阿卡莎的床。就这样跪了下来，紧紧握
住白色的被单，发出了更为低沉的声音。

想见他们。但却无法实现。NervGear发射的多重电波，已经完全将我的意识从现实世界中切
断，整个封闭在了这个世界当中。

强忍着不让喉咙内的呜咽声传出，此时，我终于感觉自己领悟到了这个世界的“真实”。

我所领悟到的，并不是死，或者生这种东西。“死”的实感什么的，打一开始就不可能得到。
要说为什么的话，那就是我在现实世界里——跟这里一样是“死了的话就真的是死了”的那个
世界，也从来没近距离接近过死亡。所以我所领悟到的跟生死无关——而是这里是“异世界”
这一点。无法见到自己想见的人。这正是唯一的真实。也是这个世界的“真实”所在。

把脸深深埋进被单中，紧咬嘴唇，身体不断抖动。但泪水却没流出。不，在现实世界中躺在
床上的，真实的我的脸颊上可能留出了眼泪吧。很有可能，就在身旁守护着的直叶眼前。

“…………怎么了，哥哥？”

听到这样的声音，同时柔软的小手擦拭起我的脸颊。

最后那手拘谨地抚摸起了头发。一次，又一次。

就像是要让我停止哭泣一般，小小的手一直在那抚慰着。

（初始之日篇 完）
** 后 记
我是川原 礫。谢谢你们阅读了《SwordArt·Online 8 Early·and· Late》。

这是继第二卷以来的短篇集。就和标题写的一样，本书除了收录SAO世界的最新故事（按照
正确的时间序列来看，是在第七卷《Mother's·Rosario》发生前的一周），还有SAO世界最
老的故事（正确来说是在第一卷《艾恩葛朗特》的第一章还要往前一小时哟<笑>）

从第一卷开始（或者是Web版开始）就一直陪伴着我的读者大人们，你们知道吗，这个SAO的
故事，最开始只写了从“SwordArt·Online”开始后两年到通关那时为止期间的三周的故事。
之后，又用补完过去章节的形式写了四篇短篇集收录在第二卷中，实际在电击文库出版时，
我还是十分的迷茫哟。并不是把WEB版就这样出书，而是有相当于文库一、两卷的部分重写
过，再新添一部分内容了的。我都干脆在想要不要把SAO的事从头到尾详细说一次了。

当然这个想法最终还是实现了（也正因为这个才会写出如此之多的页数，自己想想都觉得有
些恐怖啊<笑>），“在初始之街与克莱因离别时桐人”的身影，长时间停留在我心中。作为
封测者，想要变得更强，并在最短的路线上全力奔跑的他，心中会想些什么，会有何种的感
受呢，真想和他一同追求啊——此种情感，依旧残留在我心中。

第八卷，既然收录了在Web上已发表的两篇（《圈内事件》和《圣剑篇》），那么就在多写
一篇那一日桐人朝着荒野走去的故事吧！想到这里，于是便写出了《初始之日》。仔细想想，
从写了SAO第一部开始，已经过去近十年的岁月，桐人的人物形象也难道没发生了许多变化
吗，如果你们也能乐在其中的话那我也会很高兴的。今后，如果有机会的话，我还想写一篇
桐人用最初得到的爱剑挑战第一层的故事。还请大家耐心等待吧！[fn:43]
*** 1
接下来是管理的抱歉单元……本卷收录的《圈内事件》，真是个悲催的附加作啊，与第一卷
中的记述发生了许多不一致的地方（比如在第一卷中提及的“桐人也没有和亚丝娜去过NPC
餐馆”的表述，这回也应如此……）刹那，我想到了如果是去玩家经营的餐馆就差不多能符
合了吧，为此产生了很大的疑惑，但由于没有找到根本的解决办法所以最后还是放弃了。我
想应该还有很多让大家感到“哦呀？”的部分吧，关于这些，还望大家多多宽恕下这个由大
量荒诞怪奇的过程所构成的作品吧！

接下来，就利用这个势头再次谢罪吧，用侦探小说的形式写了《圈内事件》的谜题与解决篇，
我想应该会让侦探小说迷们发出“这不可能吧！”的怒吼声吧。我也是十分喜爱侦探小说爱
好者，因此想挑战一下，很抱歉实力依旧不足啊！我会重新修行，哪天会再挑战一回的。

接下来的不是谢罪而是宣传，此本的《圣剑篇》换句话说是“攻略成功版”，IF展开的“失
败版”已收录到了二〇一一年六月发售的电击文库Magazine当中。如果有机会的话，将那个
和本书一起欣赏的话，我想会获得一点二倍的乐趣哟！
*** 2
在编辑部处于搬家的兆级【Mega，电脑硬盘存储术语】忙碌期间，我却忘记了提交后记，从
而给担当三木先生带来千兆【Giga】般地困惑，还有因六月加八月不间断的工作安排，从而
倍加努力的插画家abec老师，这次真是谢谢你们了！还有就是，各位读者们，从第九卷开始
终于要进入第四部了哟，届时还请多多关照！

二〇一一年五月某日 川原 礫

* Footnotes
[fn:171] 【译注：西部电影中常见于酒吧的那种门】
[fn:43] 【译者注：应该就是《无星夜的咏叹调》】

[fn:42] 【译者注：你确定自己以后不会前去打招呼？】
[fn:41] 【雷霆一击，译者注：表打我，真是想不出什么名字了】

[fn:40] 【译者之声：亚瑟王泪目，吾王泪目】
[fn:39] 【译者注：原文为“鱼上げる”，但推测应为“鱼揚げる”，否则解释上会有问题】

[fn:38] 【译者注：桐人你该】
[fn:37] 【译者注：桐人的咸猪手啊，大家一起来剁吧】

[fn:36] 【译者注：应该是指伤害判定或硬直】
[fn:35] 【译者注：PC制造，也就是人造。】

[fn:34] 【译者注：这里的“您”，日文是“貴女/あなた”】
[fn:33] 【译者注：这里的“你”，日文是“おまえ”，是种很不礼貌的用法】

[fn:32] 【译者注：原文为投げ針/throwing pick】
