#+TITLE: （萌动王朝）刀剑神域18 Alicization篇（10）
#+DATE: <2023-08-15 二 11:33>
#+SETUPFILE: ../setup.setup

* 第18卷 Alicization篇（10）
** 片头

第十八卷 全一卷
** 第8章（承前）
*** 第62节
克里特不禁将身体靠在控制台上，发出了短短的咒骂声。

数万规模的黑点群，从中心向外被急速消灭。

也就是说，基于瓦沙克的策略而投入Under World的中国和韩国VRMMO玩家们，被通过某
个手段歼灭并自动注销了。

黑色圆环的中央部位，用蓝色表示的人界军和用乳白色表示的日本人部队大概还剩余一
千人左右。就算想无视他们这个数量也太多了，而且如果这一千人有着击破三万中韩联合军
的力量就更危险了。

「瓦沙克那个笨蛋到底干了什么啊……」

吐着舌头的克里特又看向主显示器。

在日本人部队的近处，还残存着一个闪着强光的红点。是通过2号STL使用自己的帐号转
换进去的瓦沙克。

是因为被捕获或是别的情况而动不了了吗？还是说，他还有单独一人能够对抗上千敌军
的什么手段呢？

克里特忍住自己跑到隔壁STL室把摇着瓦沙克的衣领把他叫起来的冲动。

在对服务器进行GM权限操作被锁定的现状下，无法将帐号初始化。也就是说，如果瓦沙
克被强制注销，现在这个帐号就无法再次使用了。唯一可能做到的，就是进行具有将The
SEED程序分离的功能的内部时间加速倍率的操作，但就算采取这个措施，也需要慎重考虑时
机。

克里特神深呼吸了一下，向下看去。

在Under World的最南端，还有一个红点正在高速移动。是袭击部队的队长加百列·米勒
中尉。

现在需要考虑的，是人界军追上并阻止目前正打算捕获或是正在追踪爱丽丝的米勒中尉
的可能性是否依然存在。

将美国、中国、韩国的总计数十万玩家们转换进去的结果，大大阻碍了敌方向南前进的
步伐。如今米勒中尉已经在内部离他们有数百英里了。当然，如果用战斗机的话可以一瞬间
飞过去，但很难想象Under World有这样的工具。恐怕最多就是有翼生物的级别而已。

——他们追不上的。

克里特思考了三秒后作出了这样的判断。

距离护卫舰突入的时间，大概还有现实情况下的十个小时。虽然米勒中尉指示在剩余八
小时的时候再次启动加速，但在从外部投入的玩家集团几乎全灭的现在，维持等倍速率的意
义已经没有了。

那么，就应该再次让内部进入一千倍的加速模式，为米勒中尉捕获爱丽丝的任务提供充
足的时间。

「没办法……瓦沙克，就让我们看看你的胆量好了……」

对着如今在北部战场上仍然一动不动的红点低语后，克里特将手伸向了STRA倍率操作的
操纵杆。

抬头看向和操纵杆联动的主显示器上的滑块窗口时，突然他的视线停在了水平刻度上。

现在滑块的指针位于最下方×1的位置。在那上面跨过×100的刻度，在×1000的位置出
现了第一个分隔线。

其实再将视线向上看去，可以看到×1200的位置又有一个分隔线。这似乎是人类通过
STL潜入Under World的场合时的安全上限。

然后，滑块窗口继续延伸到了×5000的位置。如果居民只有Light-Cube中的人工Fluct
Light的话，可以将内部时间加速到这个倍率。

时间加速倍率是通过操作控制杆，然后按下旁边的开闭式保护盖下的按钮加以确定的。
克里特尽量让自己不要碰到按钮，轻轻将控制杆向上推去。

随着显示器上滑块的上升，他同时将视线切换到旁边的数字。

在×1000的位置，感觉到了一点抵抗感。

加上力后，控制杆再次动了起来，在×1200的位置停下了。之后不管怎么用力，都没有
一点动起来的迹象。

「呼呒…………」

被好奇心刺激到的克里特，仔细观察者像是飞机操纵杆一般的大型控制杆。

然后他注意到，在确定按钮的对面，有一个闪着银色光芒的钥匙孔。

「原来如此。」

克里特用一根手指挠着和尚头轻轻笑了出来。

安全限制是一千两百倍，也就是说实际的危险区域在稍微更高的倍率。在以防内部时间
所剩无几的场合下，试着解除安全装置也不算坏事。

回过头去的克里特，对围着只剩下弹孔的机器人说着「为什么？」「为什么？」的队员
们打了个响指。

「喂，谁会开锁的？」

怎么这么软……味道好香……

这无疑是几个月来睡的最舒服的一觉了，所以比嘉健拼命地抵抗着摇着他想要让他醒来
的外部刺激。

「……喂，比嘉君！稍微睁开眼睛啊，喂！！」

但这么做也太过分了吧。

简直不就是像我快死了一样吗。

不管怎么说也太夸张了。我怎么可能被人刺中或是开枪击中……

「——呜哦！？」

随着意识醒来，记忆也一口气复苏。比嘉睁开眼睛叫了出来。

在他面前的，是黑框眼镜反着强光的三十多岁的男人的脸。

「呜哇！！！」

比嘉又喊了出来。

虽然想要退后，但身体却动不了。代替这个动作的，是比嘉因右肩感到一阵剧痛而第三
次发出的怪声。

——对了。

我在电缆管道里被那个男人开枪打中了……

把大量出血不当一回事，只以STL操作为优先事项。虽然将三个女孩子的Fluct Light输
出和桐之谷君的STL直接连接但他还是没醒……然后，发生了什么来的……

「……桐，桐人君怎么样了？」

比嘉用微弱而沙哑的声音问道。

回答他的女性，用带着清凉感的声音说着：

「Fluct Light活性……已经完全恢复了。不如说活动的过头了。」

「这……这样，吗……」

比嘉呼地叹息了一下低声说着。

从那种状态恢复过来简直可以说是奇迹。而且自己在大量失血的状态下活着也算是奇迹
般的——

这时他才想到确认自己所处的状况。

自己睡在副控制室的地面上。右肩缠着绷带。左臂连接着输血包。

然后，醒来时见到的戴眼镜的菊冈中校和脱下白大褂的神代博士各自坐在自己身体的左
右位置。

菊冈叹了口气，摇摇头说道：

「真是的……居然这么乱来……不，没能发现在技术人员里有间谍的我也有过错……」

一直仔细梳好的刘海如今一片凌乱，眼镜的镜片里也可以看到汗珠。仔细看去，神代博
士似乎也满头大汗。看样子是两人对比嘉做了急救措施吧。那么，如同梦中一般感觉到的那
种感触，那时候是……

——嗯？

是谁做了心脏按摩，谁做了人工呼吸呢？

虽然比嘉不禁想要发问，但还是把话停在了嘴边。在世上还有着不该去知晓的真相。[fn:140]

「Under World……爱丽丝怎么样了？」

菊冈轻敲着比嘉的左臂回答道：

「来自美国、中国和韩国的连接者已经全部被击退了。而且，似乎是桐人君一个人将中
韩玩家解决掉的。该说不愧是他呢还是果然如此呢，那个力量实在太厉害了……这也是，比
嘉君努力的结果呢。」

「诶……还有从中国和韩国来的人吗！？不是作为援军……而是作为敌人！？」

比嘉不禁想要做起身体，但却因为从右肩到指尖传来的剧痛而开始喘气。

「喂，别这么乱来！虽然打穿身体的子弹好歹没有伤到神经……关于中国和韩国的玩家，
似乎是被网民间的紧张推动才会连接过来的。虽然确实有转移战场的效果……」

「是……这样吗……」

比嘉轻轻叹了口气。原本在他参加这个Alicization计划的原因中，为了回报在伊朗战
争中牺牲的韩国朋友这一点就占了相当的部分。明明这样，进行中的计划却加强了日本和韩
国年轻网民间的对立情绪，实在大大出乎他的意料。

他好不容易摇了摇头，将思考转向别的内容问道：

「从中国和韩国……来了多少人？」

「似乎超过了四万人。从日本本土前来支援的两千名玩家几乎全灭……」

菊冈用苦涩的声音低声回答。

「当时中国和韩国的玩家大概还有三万人，幸好桐人君……」

「诶，你说什么？」

比嘉不禁打断了指挥官的话。

「桐人君一个人把三万大军消灭了！？……这不太可能。Under World里根本就没有能
发动如此大规模和高威力攻击的武器或是命令。应该是……没有，的……」

说出这句话的时候，比嘉才彻底想起，被那个间谍——柳井开枪打中前后发生的事情。

柳井似乎是被那个名叫『最高祭司Administrator』的Under World人彻底控制了。到底
经历了怎样的事情，才会变成那样的事态呢。

而且还有那个和桐之谷和人的STL连接的，Main Visualizer内的异常Fluct Light。明
明只是个物品，却有着模拟人类意识的功能，之前根本就没有设想过这种情况。

「……那个……菊先生…………」

比嘉感觉到有别于大量失血的寒气袭向身体，向指挥官低声说道：

「莫非……我们……做出了，什么不得了的……」

这时，从控制台传来的尖锐的警报声响彻房间。

是比嘉设置的时间加速倍率变动警报。

 我将自己和亚丝娜的身体和装备全部转换成Under World内拥有移动速度最快的属性的
光元素，在天空中飞行。

就算这么说，这个速度离现实中的光速也相差甚远。要追上前往遥远的南方的爱丽丝，
至少也要三分钟时间。

想要在这段时间里，向亚丝娜说出的、谢罪的、感谢的话已经多到自己都数不清了。然
而，我却不论怎样都无法直视牵着我的手在右侧飞翔的亚丝娜那闪光的身影。

而其理由——

在觉醒后那如同全身的血液都变为火焰的万能感慢慢平静下来后，近期的记忆开始一点
一点经过整理而鲜明地显现出来。

问题是在昨天的深夜。

亚丝娜、爱丽丝和萝涅围坐在睡在马车货架上的我的旁边，一个一个将我的回忆——或者
说是恶行——揭露出来的那一幕，不称其为地狱又该称为什么好呢。

——桐人前辈还是近侍的时候，可是在超漂亮的上级生毕业的时候送上了只在西部帝国才
会开放的花束，让人家大哭了一场呢——

——这么说来，整合骑士团的女副团长不知道怎么回事也被他迷住了呢。那个人好像还叫
他「小伙子」来的……

「呜…………」

我不禁双手抱住了头。

「呀————」

这算是呻吟吗……

然而在这个瞬间，由于意识不再集中，身体的属性立刻恢复原状。强烈的风压敲打全身，
我一下子陷入了绕着圈子下落的状态。[fn:141]

虽然低声说了一句糟糕，但总之还是将大衣下摆变成翅膀形状，从而控制身体的平衡，
然而——

「呀啊啊啊啊啊啊！！」

按着裙子的亚丝娜从上空笔直落了下来。

我又喊出一声糟糕，慌忙伸出双手。

好不容易将她接住的一瞬间，亚丝娜那大大睁开的榛色眼睛，一下子盯住了我。就是这
里。只能在这里谢罪了。

「亚丝娜……不是这样的！！」

这根本不是谢罪而是借口吧。然而已经没法回头了。

「我和索尔缇莉娜前辈以及法娜提欧副团长之间真的什么事情都没发生过！我向丝提西
亚神发誓，绝对什～～～么都没发生过！！」[fn:142]

听着我拼命辩解的话的亚丝娜的脸——

慢慢缓和了下来。她那小巧的双手揪住我的脸颊，像是被惊呆了一般说道：

「……桐人君你真是一点都没变呢。明明以为你在这里努力了两年，好歹也成熟了…… 一
点……呢…………」

亚丝娜的双眼突然溢出了透明的泪珠。她的嘴唇如同发抖一般颤动着，挤出了沙哑的声
音：

「太好了……桐人君……一点都，没变啊……我的……」

「怎么会……我就是我啊。怎么可能会变啊。」

「因为……那简直就像神一样啊。将那么多人的军队，一瞬间就解决掉了……又把两百
人一下子回复过来……而且，还飞在天上……」

听她说到这里，我不禁苦笑着回答道：

「只是比别人稍微熟悉一点这个世界的机制罢了。像飞行这种程度的，亚丝娜只要习惯
了很快就能做到了。」

「就算做不到也没什么。」

「诶？」

「能这样抱着我飞就好了。」

笑脸上带着泪光的亚丝娜这样说着，将双手从我的脸移到背后，紧紧抱住了我。脸颊被
她松开的我也紧紧抱住她，重新开口说道：

「真的……谢谢你，亚丝娜。明明受了那么重的伤，还保护了人界的人们……明明那么
痛……」

这个世界内痛苦的鲜明程度，我在两年前的终结山脉里被哥布林队长砍到的时候就了解
了。那时，只不过是肩膀被划到而已，就已经痛到让我一段时间内站不起来了。

明明如此，在被外部连接者的大军包围之下，亚丝娜带着全身那凄惨的伤口仍然战斗到
了最后。如果亚丝娜没有这么努力的话，缇卓和萝涅她们所在的人界部队，大概早就被歼灭
了吧。

「嗯……不光是我哦。」

听到我的话的亚丝娜，将紧靠着的脸颊稍微转动了一下。

「诗诺诺、莉珐、莉兹、西莉卡、克莱因、艾基尔……还有，瞌睡骑士团和ALO的各位，
都已经非常努力了。而且还有整合骑士雷恩利先生、人界军的卫士们、萝涅和缇卓也……」

说到这里，亚丝娜像是吃惊了一般，突然伸直了身体。

我在听到她的下一句话前，就明白她这样做的理由了。

「啊……对了，桐人君！骑士长……贝尔库利先生，为了追赶敌人的皇帝，一个人……」

「…………」

我慢慢摇了摇头。

我已经感觉到，到头来连对话都没能做到的，贝尔库利那宏伟的剑气，已经不存在于这
世上了。

我曾和他在这战争开始之前，仅有一次以想象力之刃——他称之为《心意》——互相交手。
在徐徐复苏的我的记忆中，贝尔库利在那时已经预感到自己会死去了。

他在三百年人生的终点，选择了为保护爱丽丝而战斗。

领悟到我动作中的含义，亚丝娜的双臂抱的更紧了。她轻轻啜泣着，但很快就停下呜咽，
向我问道：

「……爱丽丝……没事吧……？」

「嗯，还没有被抓到。很快她就会到达世界的尽头……第三个系统控制台了。」

「这样啊……那么，我们一定要保护她。为了贝尔库利先生。」

轻轻和我分开的亚丝娜的脸上，虽然全是泪水，但却充满了强烈的决心。我慢慢点了点
头。然而，亚丝娜的眼睛，却稍微摇动了一下。

「不过，现在……这一会，就这一会，只做我一个人的桐人君吧。」

随着她的低语而靠近过来的嘴唇，将我的嘴唇塞住。

在异世界的血红天空之下，缓缓拍动着黑翼的我，和亚丝娜交换了一个长长的，长长的
吻。

在这个瞬间——我终于想起，自己为何会在两年半前落入这个世界了。

在那个六月份的雨天。

在送亚丝娜回家的路上，我们被《死枪事件》的最后一名主犯，《微笑棺木》的干部
Johnny Black袭击了。由于被注射了大量的肌肉松弛药物，记忆完全中断了。恐怕我因为呼
吸停止，脑部受到了相当的损伤，为了治疗我才动用了STL和Under World吧。

可以称之为SAO时代的怨灵的，赤眼XaXa和Johnny Black都被逮捕，而不知为何混在
《海龟》袭击者中间的《微笑棺木》的首领PoH如今也已被变为小树的形态束缚在这个世界。
如果时间加速再次启动，他在被外部强制切断连接前都会在感觉被阻断的状态下度过几天或
是几周的时间，精神上应该会受到不小损伤。至少也和这半年间的我一样。然而我绝对不会
认为这是残酷到做过了头的事情。

因为那家伙说了，他会盯上亚丝娜。[fn:143]

在经过足以让存在融为一体的令人目眩的时间后，我和亚丝娜的嘴唇分开了。

「想起那时候的事情了呢……」

亚丝娜刚一说出话就突然停了下来。我马上就明白她这么做的理由了。

那个时候——是SAO被攻略后，浮游城崩毁的时候，红色的晚霞下的那个吻。没错，那是
别离之吻。

我微笑着，如同要将这不吉利的预感赶走一般坚定地说道：

「那就出发吧。打到敌人，救下爱丽丝，大家一起回到现实世界……」

我的话没能说完。

从我的脑海中响起紧张的大声呼喊：

『桐人君！桐之谷君！！听得到吗！？桐人君！！』

这苦涩的声音是——

「诶……是你吗，菊冈先生？」

『对，能听到！不好意思……出大麻烦了！！时间加速倍率……那帮混蛋，把STRA限制
给……！！』
*** 第64节
克里特带着些微不安，注视着额头上迸出血管，用两根电线插进钥匙孔里来回转动的布利格
留着胡子的脸。

虽然他很有气势地说着「开锁就交给我好了」，但STRA的操纵杆的安全程度和廉价公寓
的旧式转筒锁可不一样。他指尖的动作越来越粗暴，而嘴里吐出的脏话的声音也越来越大。

站在布利格后边的汉斯，看着左手上带着的表，像是很开心的说道：

「喂——，过了三分钟了哦。再过两分钟就要给我五十刀了呢～」

虽然电线戳动的声音与其说是开锁还不如说是破坏行为，但克里特还是把「果然还是算
了吧」的话停在了嘴边。从这两个人打赌开始，到决出结果之前谁都没法阻止他们。

「还剩一分钟了～差不多可以准备钱包了哦～」

「Holy Shit！！」[fn:144]

随着一声大喊，布利格突然站了起来，将电线被切断的一段扔在了地上。

克里特安心下来，想到他果然还是放弃了吗，这时——

脸上一片通红的士兵，无言地从腰间的枪套里拔出巨大的手枪，将枪口指向钥匙孔。

「喂……等等…………」

一声枪响。接着又是一声。

布利格在哑口无言的众人面前将沙漠之鹰收回腰间。接着他先看向汉斯，接着又看向克
里特，耸了耸肩说道：

「开了。」

克里特张大嘴巴，将视线移向如今变成了直径两英寸的黑洞的钥匙孔。

在黑暗的深处，闪起两三次火花后，停在倾斜状态的操纵杆再次动了起来。操纵杆动了
大约五英寸后，带着咔的一声轻响停了下来。克里特看向显示器上的数字，比之前设定的
1200倍稍微往上——的位置，被设定为上限的×5000的数字闪着光芒。

这时，又响起咔的一声。

操纵杆向更深处倾斜。

「喂……骗人的吧…………」

在自言自语的克里特面前，显示的数字超过了5000——超过了10000……

不，还没什么。只要不按确定按钮，实际倍率就不会发生变动。还是可以轻轻将操纵杆
拉回，当成什么事情都没发生的。

「喂……别碰！！谁都别碰！！」

克里特喊着话，挥手将汉斯和布利格从控制台边赶走。

接着他回过头，向操纵杆伸出右手。

砰。

还没等他的手碰到操纵杆，就响起了轻微的爆炸声。

在黑客面前，红色的按钮和透明的保护盖都一起被炸飞了。

主控室正面墙上的大显示器染成一片红色，从扬声器里传来震耳欲聋的警报声。

比嘉在听到时间加速机能被再次人为操纵的警报的瞬间，就再次想要坐起来，因剧痛而扭起
了脸。

「比……比嘉君！都说了叫你不要乱来……」

神代博士跑过来用手撑住比嘉的身体。紧接着……

副控室的主显示器被染成一片红色。

「什……什么！？」

喊出声音的是菊冈。越过跑向控制台的指挥官的肩膀，被支撑着站起来的比嘉拼命凝视
着屏幕。

显示器上用巨大的字体显示的，是通知对STRA机能加以限制的三段限制器全被解除，
Under World整体将进入《极限加速阶段》的倒计时。

「什么…………」

代替无言喘息着的比嘉，神代博士尖锐地问道：

「极限加速是怎么一回事！？STRA倍率的上限不是一千二百倍吗！？」

「那……那个，是有人潜入Under World时候的限制倍率……只有人工Fluct Light的时
候，上限是……五千倍……」

听到如同自动回答一般的比嘉的话，神代打了个冷战睁大了眼睛。

「五千！？也就是说……这边的一秒，对应内部的八十分钟……这边的十八秒在那边不
就是一天了吗！！」

听到神代的声音，比嘉和菊冈对视了一下——然后一起机械地摇了摇头。

「诶……有什么不对的吗？」

「一千二百倍是考虑到现实世界的人类灵魂寿命设置的安全上限……五千倍是从外部可
以观察Under World的上限……哪个都不是硬件层面上的极限倍率……」

比嘉从喀拉喀拉快要干枯的喉咙里拼命挤出了话。支撑着他的神代博士的手臂颤抖了一
下。

「那，那么……硬件层面的上限……到底是……」

「就像你已经知道的一样，Under World是用光量子构筑并计算出来的。通信速度事实
上没有限制……也就是说上限，是根据下位服务器搭载的架构规定的……」

「赶紧说啊！到底是多少倍！？」

比嘉闭上眼睛说道：

「在《极限加速阶段》……STRA的倍率，会稍稍超过#五百万倍#。通过卫星线路连接的
位于六本木的两台STL，没法对应那样的速度，所以会自动断线……但对在这里使用STL的两
个人……」

现实世界的一分钟——对应内部的十年。

瞬间心算出这个对应关系的神代博士睁大的双眼轻轻地痉挛了一下。

「怎么会……这样……快点……不让明日奈小姐和桐之谷君赶紧从STL出来的话！！」

这次比嘉紧紧按住了打算站起来的博士的手臂。

「不行，凛子小姐！在已经进入初期加速阶段的情况下，随便把他们从机器里拉出来，
Fluct Light会飞走的！！」

「那就赶紧开始断线处理啊！！」

「我就在想刚才为什么要刻意从电缆管道下去了！STL操作只能在主控室进行！！」

比嘉反驳着，视线转向控制台前的指挥官。

菊冈立刻察觉到了他想说的话。

「……菊先生。我要再下去一次。」

指挥官听到他的话，点点头回答道：

「明白了，我也去。背着你从梯子上下去的体力我还是有的。」

「不……不能去，中校！！」

中西上尉喊了出来。面无血色的他踩着靴子向前走了几步。

「太危险了。这个任务就由下官……」

「隔墙还要再开一次，你们必须做好通道的防御工作。没时间了，这是命令！」

听到带着至今从未有过的锐利表情的菊冈说出的话，中西一下子张大下巴，低下了视线。

比嘉战战兢兢地抬起右手，确认还很痛的指尖还能正常活动，同时拼命思考着。

显示器上显示的，距离进入《极限加速阶段》的倒计时已经不足十分钟了。

然而现在就再度开放耐压隔墙，从那长长的梯子上降下，通过连接装置进行STL切断操
作不管怎么算也要三十分钟。

在这二十分钟的时间差里，Under World内的时间要经过——二百年。

这是远远超过人类灵魂寿命——一百五十年的岁月。

在此之前，Under World度过了这近乎无限的年月……但现实世界的人，到底还是没法
承受……

在Under World的内部……

「对……对了！！」

比嘉喊出了声音，左手向着菊冈挥动。

「菊，菊先生！！刚才操作STL的时候，我保留了和桐人君间的通信频道！请呼叫C12号
线路！！」

「可，可是……要说什么……」

「让他们从内部脱离！！在剩余的十分钟内到达系统控制台，或是天命全损的话，STL
会自动开始切断处理！！但是，控制台在进入了《极限加速阶段》之后会无法运转，如果死
掉就会变成最糟糕的情况！！在全部感觉都被阻断的状态下度过二百年……只有这个事情要
强烈警告他们！！」
*** 第65节
「二…………」

二百年！？

我好不容易才将到了嘴边的话收回去。

眼前的亚丝娜带着紧张的表情看着我。她听不到菊冈的声音。

『听好了，桐人君，还剩十分钟！在时间限制前到达控制台，然后自行注销！！如果不
管怎样都做不到的话，也有让自己天命全损的方法……但这既无法确定，而且也非常危险，
理由……』

因为可能不得不在近乎死亡的状态下度过二百年的时光。

领悟到这一点的我，打断了菊冈的话说道：

「知道了，我会想办法从控制台脱离的！当然，我们会带上爱丽丝，所以请做好准备！」

『……抱歉，但是，现在相比确保爱丽丝的安全，你们两个人的脱离更为重要！听好了，
就算在注销后删除记忆，二百年的时间也远超过人类灵魂的寿命了！意识恢复正常的可能
性……接近于零……』

我平静地回答声音中带着苦涩的菊冈：

「别担心，一定会回去的。然后，菊冈先生。半年前……不，是昨晚，对你说了很过分
的话，抱歉。」

『不……我们早就把被指责当成理所当然的事情了。考虑到会被你打一顿，这边已经准
备好药膏了……貌似比嘉君做好准备了，我也要走了。』

「好的。那就十分钟后再见了，菊冈先生。」

之后，通话就切断了。

我拍着将大衣下摆变成的翅膀浮在半空，注视着臂弯里的亚丝娜。

「……桐人君，和菊冈先生取得联系了吗？发生了什么……不好的事情吗？」

慢慢摇了摇头——我回答道：

「不……他只说十分钟后会再次启动时间加速，让我们赶快注销。」

亚丝娜眨了眨眼睛，露出淡淡的微笑点点头说道：

「是呢，要是一直这样子的话就对不起爱丽丝了呢。那就去救她吧！」

「嗯。那就要再飞了呢。」

我紧紧抱住亚丝娜，再次将二人转换成光元素。无数的颜色变成了金色的光辉。

捕捉到前往遥远南方的爱丽丝，和追逐着她的巨大的异样气息——我们再次飞了起来。

被追上了。

在雨缘的鞍上回头看向后方的爱丽丝轻轻咬住了嘴唇。

在血红色天空的背景下，漂浮在空中的黑点，比五分钟前变得更大了。相比逐渐加速的
敌人，两头飞龙的力量则已经消耗殆尽。

虽然是在几乎毫不休息的情况下一直飞行，但努力到这个地步也近乎奇迹了。只花了半
天时间就飞过了数倍于人界直径的距离。两头飞龙无疑是消耗着自己的天命持续着极限飞行。

然而——那个追踪者到底是什么。

通过远视术的确认，那个人似乎坐在和飞龙不一样的奇怪的有翼生物的背上。然而，那
种生物在人界和暗之领域根本就没有见过。

追上来的人应该就是借助了暗黑神贝库塔的《Real World》的人了。

然后，他曾经被骑士长贝尔库利的舍身之剑杀死了。但他却再次获得了新的生命进入这
个世界，追逐着爱丽丝。

爱丽丝为这贬低了贝尔库利的死亡的做法，感到绝不可原谅他的愤怒。

然而，爱丽丝在这数个小时的飞行中，终于明白自己要做的事情了。

如果敌人在这个世界是不死的存在的话——

那就在《Real World》里杀掉他。

为此，无论怎样都要到达《世界尽头之祭坛》。虽然她下定了决心，但似乎怎样都无法
将其实现了。

爱丽丝将视线转回前方，看着透过正前方血红色的天空，那有着惊人规模的伸向天空的
薄薄的断崖绝壁。那就是传说中《世界的尽头》。和可以乘坐飞龙越过的《终结山脉》不同，
环绕暗之领域的断崖，有着几乎无限的高度。

在那断崖近处，和飞龙们差不过相同的高度上——

有一个小小的浮岛飘浮在空中。

底面是尖脚杯的形状。推测不出它是凭借怎样的力量才能在空中漂浮的。

集中视线，在平坦的浮岛上面中央，可以看到人工建筑物。恐怕，那个就是自己所赶赴
的《尽头之祭坛》吧。世界的出口。通向《Real World》的入口。『真实』所在之处。

虽然很可惜，但相比背后的敌人，还是有点远了。

爱丽丝轻轻闭上眼睛，深深吸一口气，然后慢慢呼出。

她用右手轻轻抚摸爱龙的头，命令道：

「谢谢了，雨缘，还有滝刳。到这里就可以了，降落到地面吧。」

两头飞龙鸣着微弱的声音，一起开始螺旋降下。

下面的地形，在稍微一点时间前，变为如同将虚无具现一般的黑色沙漠。在似乎要将神
之创造吞没一般荒凉的沙漠之海中划出长长的轨迹，两头龙以近乎倒下的姿势着陆了。

爱丽丝立刻从喉咙深处发出呼噜噜噜噜的沙哑声音，身体横躺在地上的雨缘背上下来。
她摸索着腰间的口袋，取出最后一小瓶灵药。

将蓝色的液体一半注入飞龙半张着的嘴巴，然后将剩下的一半一滴不剩地注入旁边的飞
龙。就算是神圣教会制作的灵药，也完全不够回复飞龙巨大的天命，但让它们再次起飞还是
可以做到的。

爱丽丝的双手，轻轻抚摸着两头飞龙生长着软毛的下颚。

「雨缘，滝刳。」

爱丽丝呼唤着，两眼间自然地浮出了泪水。她拼命忍耐着，继续说道：

「就在这里分开吧。这是最后的命令……飞到人界，回到西域的龙巢，雨缘去寻找丈夫，
滝刳去寻找妻子吧。生下小孩，将它们茁壮地养育起来。去生下总有一天驮着骑士飞翔的，
强大的孩子吧。」[fn:145]

突然，雨缘抬起头，舔舐着爱丽丝的脸颊。

滝刳将鼻子贴近爱丽丝的腰部，闻者垂在那里的星霜鞭的味道。

在两头飞龙的头离开的同时，爱丽丝下了命令：

「去吧！！不要回头，笔直地向前飞吧！！」

咕噜噜噜！！

两头飞龙同时抬起头，发出高声的鸣叫。

如爱丽丝所命令的一般，它们没有回头，开始笔直地向西助跑。

在咚咚咚咚的沉重脚步声后，伸展开来的双翼卷起了沙漠之风，巨大的身体漂浮在宇宙
中。

兄妹龙以双翼几乎碰到的距离拍打着空气，一口气提升了高度。

然后——

雨缘那长长的头转了回来。

它那银色的眼睛，笔直地注视着爱丽丝。在飞龙的眼角，一颗大大的泪珠流过，闪着光
辉在空中消散。

「雨……缘……？」

没等爱丽丝的话说完——

将头转回前方的飞龙和它的兄长，激烈地拍打着左翼，身体转动了九十度。

响起猛烈的鸣叫的同时，两头飞龙开始全速升空，笔直地向着已经接近到可以用视觉确
认的距离的追踪者直线飞翔。

「不可以……不可以！雨缘，不可以！！」

爱丽丝尖叫着跑了起来。

然而，沙漠中黑色的沙粒缠住了她的长靴。

在倒在沙漠中，伸出手的爱丽丝的视线前方，雨缘和滝刳划着两道螺旋，向不死之敌即
将到达的高空突进。

银色的龙鳞反射出赤红色的阳光，如同火焰一般闪耀着。

排列着尖锐牙齿的龙颚大大张开。

两头飞龙毫不考虑追踪者是否进入了射程，拼命吐出了热线。爱丽丝看到了贯穿长空的
纯白光芒，仿佛飞龙的生命在燃烧一般。

坐在怪物背上的敌人，虽然看到了袭来的超高热量，却一点也没有改变行动轨道。

他只是毫不掩饰地伸出左手，张开五指。

他防御不住的。飞龙的热线，乃是除了整合骑士的记忆解放攻击和高位术士的集合多重
术式之外在这个世界有着最高优先度的攻击。而且还是两条。不管怎样他都不可能有在如此
短的时间内组成能够与之对抗的防御术的余地。

爱丽丝推测着——或者是祈祷着。

然而。

伴随高亢的共鸣袭来的两条热线将敌人的身体吞没烧尽的瞬间之前，发生了超出爱丽丝
理解能力的奇怪现象。

以追踪者的左手为中心，漆黑的暗之漩涡扩散开来。

周围的景色如同落入黑暗一般开始歪斜。连包含了惊人的威力的飞龙的热线都不例外。
以直线轨道前进的热线被扭曲，颜色变为蓝紫色，就这样被吸入了那个男人的左手——

只有数道光芒飞散，连声音、闪光和爆炸都没有，两条光线被黑暗吞没了。

虽然那个男人在不论怎样的术式或剑技都无法够到的高空中飞行，从地面上看过去只是
一个黑点，但爱丽丝却看到了敌人的嘴边露出了淡淡的微笑。

紧接着。

咔！！随着震耳欲聋的响声，从男人左手中盘旋的黑暗中，迸出数道漆黑的闪电。

简直就像是将飞龙的热线吞噬、咀嚼、消化后变为自己的力量后吐出的攻击，无情地贯
穿了正在飞翔的雨缘和滝刳的身体。飞龙们的身体剧烈摇晃，鲜血和白烟在空中弥漫开来。

「雨……雨…………」

喘息着的爱丽丝，尽力将手伸向高空喊道：

「雨缘——！！快逃！！已经够了，快逃——！！」

爱丽丝的悲鸣确实传到了飞龙们的耳边。然而两头飞龙宛如听到爱丽丝的声音重新下定
了决心一般激烈地拍打着双翼，再次开始突进。

飞龙的嘴巴大大张开。从牙齿的缝隙间，出现如同阳光一般的热气，白焰闪耀着光芒。

噼啪！！

第二次放出的热线在空中灼烧。

这一次男人再次展开了暗之盾，将光之箭挡了下来。

明明知道和之前一样的反击会再次袭来，两头飞龙仍然果敢地向前突进。飞龙们的双翼
猛地拍动着空气，向敌人直线飞去。

从贯穿两头飞龙的身体的伤口处飞散的鲜血化为火焰，逐个剥落下来的银色鳞片变为闪
光的粒子在空中飞舞。

两头飞龙，将自己变成了光。

飞龙燃尽生命放出的热线，填满了暗之漩涡，使其渐渐饱和了。男人的左手，开始因无
法承受熊熊热气而涌出白烟。

然而——这时。

敌人的全身被蓝黑色的暗之面纱包裹住了。从左手放出的虚无漩涡逐渐增强，紧接着，
从漩涡中央放出的黑色闪电开始将白色的热线推回。

互相冲突的白色与黑色的力量，仅仅持续了一秒左右。

然后一下子逆转了。

无数的黑色闪电，向着因力量耗尽而减慢了拍动双翼的速度的雨缘和滝刳飞去——

「不要啊——！！雨缘！！雨缘——！！」

爱丽丝的尖叫，随着泪水在沙漠的空气中散去的这一瞬间。

星辰从天上坠落。

两个闪光，从天上以惊人的速度降下。

其中一个就这样落向地面。

而另一个，在飞龙和追踪者的中间，毫无缓冲地停了下来。白光一下子飞散，露出了藏
在里面的身影。

是人。

是个剑士。

尖锐的黑发和同样一片漆黑的大衣在风中摇摆。后背上则装备有交叉着的黑白两把长剑。
他将双臂抱在胸前，傲然地注视着袭来的暗之闪电。

啪！！啪！！

随着冲击声，闪电打到了剑士身上。不，正确来说，是还没碰到就被弹开了。在那抱着
双臂站在空中的身影前方，被不可见的障壁阻挡，空然散发着威力消失了。

爱丽丝只是屏住呼吸，睁大眼睛仰望天空。

黑衣的剑士慢慢回头，看向地上的爱丽丝。

虽然还留有少年的痕迹，但那锐利的容貌上却露出了淡淡的微笑，漆黑的双眼闪着强烈
的光芒。爱丽丝感觉到，内心深处散发出剧烈的火花。那与其说是感情，不如说是如同有着
真正的让爱丽丝的心燃烧起来的力量。

爱丽丝意识到从自己的双眼又流出了新的泪水，低声说道：

「桐……人…………」

从长达半年的沉睡中苏醒的青年，一瞬间露出可靠但又有点不好意思的笑容点了点头，
接着转过身体笔直抬起右手。

在他的背后，濒死的两头飞龙正用最后的力量拍动翅膀。飞龙双翼的末端，和长长的尾
巴尖端，宛如被光溶解一般开始消失了。

雨缘看着在露莉德郊外的家中一起住了半年的桐人，歪着头，轻轻发出咕噜噜噜的声音。

桐人向它点了点头，闭上了眼睛。

突然，虹色的光膜覆盖在两头飞龙上，简直就像是用巨大的泡沫包裹住了一般。

然而两头飞龙却毫不害怕，折起双翼，弯下了头，将身体缩了起来。

在爱丽丝的头上，两个光球开始慢慢飞舞而下。

在忘记了呼吸，只是抬头仰望的爱丽丝的视线前方，发生了不可思议的现象。

被七色光芒缠绕的雨缘和滝刳的巨体，一点一点变小了。不，与其说是变小——不如说是
变得越来越幼小了。

锐利的钩爪变圆了。银色的鳞片变成了柔软的绒毛。尾巴和头部也一点点变短，双翼从
皮膜变为长长的羽毛。

等到被爱丽丝伸出的双手轻轻接住的时候，两头飞龙的身体全长已经不足50Cen了。有
着蓝白色毛皮的滝刳闭上了眼睛，似乎陷入了沉睡。

然后，如同绿色软毛球一般的雨缘——变成了和过去，两头飞龙的母亲天命归零时，在臂
弯间悲啼时一样的姿态的爱龙，笔直地仰望着爱丽丝，从珍珠一般的牙齿间发出了短短的声
音：

「啾噜」

「雨……缘……」

从低语着的爱丽丝脸颊上流下的眼泪，弹在飞龙的皮毛上闪着光芒。

紧接着，包裹两头幼龙的虹色光开始一口气增加了亮度。爱丽丝的手臂，被切实的硬度
压住了。在她眨了眨眼睛后，臂弯间的两头幼龙已经变成了两个龙卵。

白银色的龙卵一点点变小，直到最后变成可以在手掌中并排的大小后，七色的光辉这才
消失。

爱丽丝将两个小小的龙卵轻轻放在脸旁，模糊地推测着这个现象的意义。判断出雨缘和
滝刳的天命已经损耗到无法通过术式回复的程度的桐人，将两头飞龙的天命上限降到了最低
限度——也就是将它们从幼龙还原成卵，使其免于被消灭。

就算是如今已经成为世界最强术士之一的爱丽丝也无法想象要通过怎样整合术式才能实
现这样的效果。然而，她已经不会对此感到惊讶了。

双手温柔地抱着龙卵的爱丽丝，笔直地仰望天空，带着呜咽低声说道：

「谢谢你……欢迎回来，桐人。」

虽然声音无法传到遥远的高空，但黑衣人仍然点了点头，露出了微笑。

爱丽丝的耳边，传来了怀念的声音。

——我才该道谢……这么长时间，让你担心了。

——谢谢你，爱丽丝。

——之后就在《Real World》见面吧。

接着，桐人慢慢转过身体，面对被黑暗缠绕的追踪者。

二人之间的空间，因无法承受压迫空间的心意而发出白色的火花。

「……桐人……」

那个敌人，就算是你，也无法用寻常的攻击击毙。

恐惧着的爱丽丝咬紧了嘴唇。

突然，从旁边传来了声音。

「没事的，爱丽丝。」

爱丽丝回过头，看到穿着珍珠色装备的一名从《Real World》来的少女站在那里。

「亚丝娜……」

柔软的茶色头发在空中飘舞。亚丝娜微笑着拍了拍爱丽丝的后背。

「相信桐人君吧。我们要赶紧去《尽头之祭坛》了。」

「诶，诶诶……」

虽然点了点头，但爱丽丝知道这已经没那么容易了。

重新转向正南方的爱丽丝，仰望着屹立于遥远的地平线上的《世界的尽头》的断崖，和
在断崖近处漂浮的白色浮岛。

「我想《尽头之祭坛》大概就是那个浮岛了……已经没法乘坐飞龙的现在，不管怎么样
都到不了那种高度……」

「没关系，交给我吧。」

亚丝娜点点头，从腰间拔出华丽的细剑。

她将细剑笔直指向远处的浮岛，闭上长长的睫毛。

「啦————」

突然，昨夜听到的天使们的合唱响彻高空。

七色光芒从天空向漆黑的沙漠直线降下。

咚！！

随着沉闷的声音，面前的沙海中，浮现出白色的石板。

咚！咚咚咚咚！

在石板的另一端，出现了更高的一块石板，接着又是一块。

在屏住呼吸的爱丽丝面前出现的伸向遥远天边的白色大理石阶梯，仅过了不到二十秒就
与浮岛连接起来。

完成地形操作垂下细剑的亚丝娜，一下子跪在了沙漠上。

「亚、亚丝娜！！」

「我……没事的。快走吧……距离祭坛关闭，只有不到八分钟了……」

关闭？

爱丽丝仓促间没能理解这句话的意思。在她想要提问之前，右手已经被紧紧握住了。

站起来的亚丝娜以惊人的速度在阶梯上奔驰，被她拉着的爱丽丝也跑了起来。在前进的
途中，爱丽丝又一次回过头，仰望在高处与敌人对峙的黑衣剑士。

——桐人，想要对你说的话，想要对你问的话，已经数也数不清了！！

——一定要赢啊。战胜那个敌人，然后再一次回到我的身边吧。[fn:146]

#+begin_quote
Sord Word Online 4 「Alicization」
#+end_quote
** 第八章(继上回)
*** 37
漆黑沙漠中的大理石浮空阶梯，和在阶梯上飞奔着的两位少女剑士的身影，美的令人
叹息。可以说是诗一般的象征了。

我将这一景象印入脑海，在心中自言自语。

——爱丽丝，亚丝娜。

——在此……永别了。

我没有将下次时间加速倍率将到达五百万倍，以及如果在此之前不能自行脱离的话就要
在这个世界度过二百年的事情告诉亚丝娜是有原因的。

如果知道了的话，亚丝娜也好，爱丽丝也好，一定会选择和我一起战斗的吧。哪怕这意
味着无法在十分钟的期限内脱离这个世界。

我在感觉到追逐爱丽丝的敌人气息的那个瞬间，就为其异样感而大为战栗。不。已经不
能用气息来表达了。位于那里的，只有虚无。将一切信息吞没的，连光都不放过的黑洞。

在时间限制前将这样的对手击败，然后三人一起平安脱离的可能性相当低。因此，我自
然而然地确定了行动的优先顺序。

让亚丝娜和爱丽丝确实地从Under World注销。

此外的优先事项就没有了。一个都没有。

我将这如同版画一般美丽的景象深深刻入记忆，接着转过视线，笔直看向面前『敌人』
的身影。

终于与我相遇的那家伙——不，那个，可以说是只能称之为奇特的存在。

是一个男人。这点我知道。

然后，我也只知道这一点了。

脸部的外形，如果说这是自己制作的形象的话，恐怕是意图再现『白人男性普通的容貌』
吧。眉毛也好眼睛也好，鼻梁、嘴角、轮廓都没有任何特征。只能表现出白皮肤蓝眼睛，以
及淡金色的头发而已。

体格在白人中也相当普通。既不胖也不瘦的身体上，穿着类似军服夹克的衣服。但也不
能就此说这个男人就是军人。因为在夹克上下涂抹的黑色和灰色迷彩，如同某种粘液一般不
断流动。只能说这是那个男人的『不定』特征的表现形式了。而且，左腰装备的也不是枪，
而是长剑。

在移动中，我已经从亚丝娜那里知道这个男人是袭击了《海龟》的特种部队——恐怕和美
军有关——的一员。那么，他应该是被打算夺取人工Fluct Light相关技术的组织或企业重金
雇佣的佣兵了。然而，我无法想象这个在稍微远一点的地方用如同玻璃一般的眼睛看着我的
男人，只是个寻求现实利益的人。不，甚至感觉不到他像是个人了。

在大约一秒钟的思考与观察结束后，我开口说道：

「……你是什么人？」

即刻传来了回答。男人用顺滑到到像是什么金属一般的声音说道：

「追求、盗取、掠夺之人。」

缠绕男人全身的蓝黑色的暗之蠕动的势头又增强了。我的脸颊可以感到微弱的风。空气，
不，是『信息』被吸进了黑暗中。

「追求什么？」

「灵魂。」

随着问答的一来一去，吸引力也在增强。不仅是构成空间的信息。感觉我的意识也在一
点一点被虚无的重力吸取。

男人嘴边第一次露出了表情。那是如同稀薄的气体一般的笑容。

「你又是谁？为什么会在这里？又是基于什么立场站在我的面前？」

他反过来向我提问了。

我——又是什么人呢？

降临Under World的勇者？——怎么可能。

守护人界的骑士？——不对。

脑内浮现出否定的话语，有什么东西从我的身体里被吸出来夺走的感觉。然而，不知为
何思考就是停不下来。

通关SAO的英雄？——否。

最强的VRMMO玩家？——否。

《黑色剑士》？《二刀流》？——否、否。

不论哪个，都不是我所期望并描绘出的存在。

那么，我又是什么人呢……？

意识逐渐淡薄的瞬间。

那个怀念的声音，从心底深处呼唤我的名字。

我将不知何时低下的脸抬起，叫出那个被呼唤的名字。

「我是桐人。剑士桐人。」

啪！！

飞出的白色火花，将缠绕着我的暗之触手切断。思考立刻恢复了清醒。

刚才的现象到底是什么！？

这个男人——通过两台STL，可以直接干涉到这边的意识吗？

我展开想象力的防御壁，凝视着男人的眼睛。那眼中只有虚无。将他人的心灵吸收的，
深不见底的黑暗。

这场战斗，恐怕要凭借定义自己如何强大，以及对手对自己的定义来决出胜负了。

「你的名字又是什么？」

我无意识地大声问了出来。

男人稍微思考了下，说出了名字。

「加百列。我叫加百列·米勒。」

我凭着直觉明白，这既不是角色名，也不是假名，而是这个男人的真名。

因为，说出这句话时男人的容貌发生了变化。目光变得异常锐利，带着如同寒冰一般的
冷酷感。嘴唇稍微变薄，脸颊也变得瘦削了。

同时，从全身喷出的暗之气氛一口气增加了厚度。

直到这时，我才第一次注意到男人的右臂从肩部向下都有所缺损。到刚才都如同手臂一
样蠕动的不定形的黑暗，开始慢慢伸长，碰到了腰间的剑。

随着滑腻的声音拔出的剑，并没有实体的刀身。

只有蓝黑色的暗如同一米长的火焰一般燃烧着。正所谓非存在的存在。

男人挥动从右肩伸出的影之手臂握着的暗之剑，发出了奇怪的震动声。

我稍微拉开距离，将背后的双剑同时拔出。左手握着青蔷薇之剑，右手则是握着夜空之
剑。

如果说是暗色的话，切削基加斯西达的树枝作出的夜空之剑绝不在那把剑之下。然而，
与夜空之剑如同黑曜石般反射着阳光相反，男人的剑简直就像要将空间分离出去一般。绝对
不是资源吸收属性这样的等级。恐怕……

「——上了，加百列！！」

我勇猛地喊出敌人的名字，拍动变形成双翼的大衣下摆。

飞向高空的同时，将双剑在身体前方交叉。

「Generate All Element！」

【生成全部元素】

将全身的体表想象成末端，并同时将全部属性的元素各自生成数十个，我在急速降下的
同时将它们一口气发射出去。

「Discharge！！」

元素化为炎之剑、冰之枪、以及有着其他色彩的几种光线在空中疾驰。

如同要追上术式一般，我挥动手上的双剑。

加百列·米勒没有做出任何回避行动。

他仍然露出淡淡的微笑，只是轻轻张开双手。

八色光芒向着被蓝色的黑暗缠绕的身体突刺。

我没有放过他上半身稍微摇晃了一下的空隙，将右手的剑挥下，左手的剑贯穿过去。黑
暗砰的一声飞散，在交错而过的我的体表留下寒气。

就这样继续全力飞翔，在上升的同时回头的我看到的——

是将流出的暗一点点收回，像是什么事情都没发生过一般回头看向这里的加百列的身影。
在包裹着他的身体的黑夹克上，没有留下一个伤口。

果然。

那个男人的属性，是对斩击、突刺、火焰、冻结、旋风、岩弹、钢箭、晶刃、光线、暗
咒的吸收【Drain】。

在交错的那一瞬间，被虚无之刃划过的我的右肩，大衣和肌肉如同被撕裂一般消失，鲜
血噗的一声飞散开来。
*** 第63节
加百列·米勒确认到了正在漫长的空中阶梯上奔跑着的《爱丽丝》和另一位少女的身影。根
据他的估算，二人距离到达系统终端还需要五六分钟的时间。

因此，已经没有让自己缠身于和突然出现的碍事者间的战斗的余地了。虽然将其立刻无
力化后赶往浮岛是合理的判断，但他却因对新出现的敌人起了些微兴趣，而停在了空中。

敌人一眼看过去不过是个小孩子而已。

相比先前战斗过并同归于尽的老年骑士，他的威慑感可以说几乎没有。虽然他大概是和
《诗浓》一样协助K组织的，来自现实世界的VRMMO玩家，但在给人造成的压力上还不如那个
少女。

要说原因的话，眼前这个黑衣的年轻人，几乎没有散发出任何斗气。

只在询问他是什么人的时候，吸出了相当少量的意识，然而这个通路很快就被切断了。
此后，他就像被透明的壳包围了一般不断弹开加百列的思考搜索。和无法体会到心的敌人战
斗，实在太过无趣。

加百列也考虑过立即将他从状态数值的层面上杀死并排除，然后继续追赶爱丽丝。

然而在看到年轻人将大衣下摆变成了蝙蝠翼的形状，而且还同时操纵所有属性的魔法后，
他的想法稍微改变了。加百列感觉到，他已经适应了这个世界。

在确保爱丽丝到手，带着STL技术逃到第三国后，还有着只在自己世界的一角构筑自己
爱好的工作。为了提高这个工作的效率，将年轻人的操作技术夺过来倒也不坏。

为此，就需要破坏那个想象力之壳。

加百列带着淡淡的笑容向黑衣少年说道：

「三分钟。让我好好享受一下吧。」

「……还真是够大方的呢。」

我用指尖轻抚了一下塞住伤口，低声说道。

然而，加百列如此游刃有余也有着相当多的原因。不管怎么说，他可以无伤应对所有属
性的攻击。

——不对，只对唯一一种伤害不适用。将那家伙的右臂从肩部打飞的，恐怕是先行出发的
诗浓吧。她通过想象力做出了狙击步枪，击中了那家伙。也就是说，加百列无法吸收《枪击》
属性的攻击。

理由恐怕和那个男人穿着时髦的军服姿态有关。因为他基于身为士兵的经验所知的大口
径枪支的威力，所以在自己被击中时无法将损伤无效化吧。

然而，诗浓能在Under World内具现出枪支的这一特技，是因为她将爱枪Hecate II当作
了自己身体的一部分才能做到的。我无论如何也做不到这点，就算做出一把手枪，也不会有
与其相应的威力。

因此我需要找到，能让那个奇怪的男人认为会对自己造成损伤的攻击类型。

也就是，要了解这个名为加百列的人。必须看破他过着什么样的生活，期望着什么，又
为何会在这里。

架起手上的双剑，我的嘴边露出了笑容：

「也好，就让我享受下好了。」

那个态度的来源到底是什么。

虽然可以确定那个人在长时间潜入Under World后已经适应了这个系统，但他也不过是
个小孩子游戏玩家而已。明明他知道两手夸张地握着的剑也好，华丽的魔法攻击也好都会被
无力化，为什么还能露出那么厚颜无耻的笑容。

加百列带着淡淡的不快感思考后，得出了他只是为了拖延时间而虚张声势的结论。

就算在这个世界死掉，现实世界的肉体也不会受到任何伤害。那么，他大概是只想要在
另一位同伴确保爱丽丝的安全前尽量延长战斗时间。

到头来不过是个愚蠢的小孩。跟他战斗用三分钟时间都太长了。

用临时作出的右臂晃着手中握着的虚无之刃——加百列将它毫不掩饰地刺入了自己乘坐的
有翼生物的后背。

原本这个怪物是和剑及十字弓一样的，将原本名为《沙多拉撒》的帐号所有的飞行用背
包转换到Under World时的产物。虽然可以通过自己的意识控制，但只用双脚站在上面还是
缺乏安定感。和那个少年一样，将其变为自己的翼才更为合理。

身体被贯穿的怪物，发出了短短的悲鸣，一点点被吸入了虚无。加百列将通过剑流入右
臂的数据转到后背，开始集中意识。

啪嚓。

与翅膀张开的声音一起，和少年一样的黑翼从肩胛骨上伸出。然而，黑翼并非如同蝙蝠
一样的皮膜型，而是生有尖锐羽毛的猛禽之翼，可以说和持有天使之名的自己更为相称。

「……这样就拿到一个了呢。」

将虚无之刃笔直指向年轻人的加百列低声说道。

原本打算将下一次攻击指向被敌人乘坐着的圆盘形飞行生物的我，因被抢了先手而一瞬间判
断力下降了。

加百列没有放过这个机会，展开黑色的猛禽之翼，滑过了我们之间的这段距离。

毫无动作便突入进来的刀刃速度相当惊人。哪怕他对剑技相关的知识毫无了解，这速度
也相当可怕。我如同抢救般将交叉成十字的双剑从下方挥上挡住。

嘎咻！

随着一声异样的声响，蓝黑色的暗之剑停在了我的鼻尖。

青蔷薇之剑和夜空之剑与其激烈地拉锯着。只是没有被虚无吞没而已的情况，不如说是
在交锋中出现了一个封闭空间。不难想象，这对剑的天命会增加巨大的负担。

然而，不通过后退来回避，而是冒着危险挡住他的攻击也是作战的一部分。我利用将从
下面挥上的剑被再次斩下的势头，尽量将身体后转。

「哈！！」

随着一声大喊，我对着加百列的下巴使出一记飞踢。

拖着橙色光芒伸出的脚尖，捕捉到了他尖锐的下颚。随着黑暗「嘣」的一声飞散，敌人
向后仰去。

——怎么样！？

双翼拍动着空气拉开距离的我确认着敌人的情况。如果枪击不行的话，就用《打击》——
如果那家伙真的是特种部队的士兵的话，应该受过格斗术的训练，将打击认知为会造成损害
的攻击的可能性也是存在的。

然而，咔地一声转回头的加百列，身体的表面却毫发无损。

从下颚处飞散的黑暗，立刻凝集回原处变成了光滑的皮肤。用左手抚摸着那里的敌人露
出了轻蔑的笑容：

「原来如此。很遗憾，那只不过是用来在电视上作秀的技巧而已。真正的体术……」

砰！！

加百列说到一半，拍动空气，以如同要让身体模糊起来的速度突破。我反射性地用青蔷
薇之剑弹开从左上方挥下的剑，同时用右手的剑反击。虽然砍进了敌人的肩膀，却感到了如
同被高浓度的粘液包围的手感，连动都动不了。

伸直的右臂被紧紧缠住。是加百列的左臂。他如同黑蛇一般卷住我的右臂，将它慢慢向
反向扭转——

咔。

随着这令人不快的响声，我的脑海中传来如同银色的电流一般的剧痛。

「呜啊……」

加百列在近距离窥视呻吟着的我的眼睛，低声说道：

「……就是这么一回事。」

紧接着，他开始发动猛烈的连续攻击。

虚无之剑以近乎无限连发的连续技进行超高速打击，虽然用右手的剑不断将攻击弹开，
但偶尔会突破防御的一击，还是浅浅地打中了身体。已经根本没有为了回复被折脱臼的左臂
而集中精神的闲暇了。[fn:147]

「咕……哦……」

虽然不禁漏出呻吟，我还是为了拉开距离而拼命拍动双翼。

全力后撤后，用右手的两根手指在拼命握着剑的左臂上滑动。

白光开始聚集的时候。

加百列一下子抬起左手，将五指如同钩爪般弯曲，然后一口气张开。

十余根漆黑的线如放射状伸出，在途中折了个锐角笔直地向我袭来。[fn:148]

我咬紧牙关展开想象力的防御壁。虽然在弹开袭向爱丽丝的飞龙们的同样技能时有着强
烈的确信，但现在的精神却有一半被用于治愈了——这样的认识，使得盾的强度下降——

啪。

身体的数个部位发生了震动。

贯穿了防御壁的三根暗之光线，穿透了身体和双脚。在感觉到疼痛之前，有剧烈的冷气
传入身体。仔细看去，蓝黑色的虚无纠缠着被击中的部位，正吞噬着我的存在。

「咕……！！」

我再次发出呻吟，深吸一口气，大声喊了出来。这才将虚无剥去，从新的伤口出流出了
大量鲜血。

「哈哈哈。」

我听到清脆的声音而抬起头，加百列·米勒如同虚无之刃一般，扭曲着的表情上露出了
笑容。

「哈哈哈，哈哈哈哈哈。」

不对，他没在笑。虽然嘴唇扬起，但眼睛却一动不动，在如同玻璃一般的蓝眼睛里涌起
了饥渴的漩涡。

加百列将双臂慢慢交叉在身前，做出如同要让力量集中的动作。

让人不寒而栗的黑暗，如同火焰一般剧烈摇晃，厚度不断增加。

「哈——！！」

他大声喊叫着，将双臂向左右打开。

嘶。新出现的两枚翅膀，从已经存在了的双翼上方伸展开来。然后下面又是一对。

加百列从上向下拍动总计六枚的巨大翅膀徐徐上升。被抚平的金发如同波浪一般伸展，
头上出现了漆黑的光环。

两眼不知何时也已不是人类的眼睛了。只有蓝色的光充满眼窝。

简直就是——死亡天使。

狩猎并夺取人类灵魂的先知。面对有着如此自我印象的人，到底怎样的攻击才会奏效。

我从如同恐怖的具现化一般的这个身影上移开视线，确认拉着手在空中阶梯上奔跑的亚
丝娜和爱丽丝的身影。她们才跑到了一半。到达终端还需要两分钟，不，还需要三分钟。

我已经无法确信，自己能够拖过这短短的时间了。

这是何等的全能感。

在遍布全身的如此强大的力量下，加百列第三次哄笑出来。

原来如此，这就是这个世界里存在着的想象力的精髓——《心意》吗。

终于明白将自己变为龙卷巨人的暗黑将军的力量，和斩断时间的敌方骑士的力量的秘密
了。加百列一直以为他们的技能都存储于未知系统命令之中，但并不是这样。只需要能确信
自己有着强大的力量就可以了。所有的都藏在那个小孩在眼前这样那样的演示的阴影之中。

在感谢的意义上，就给你一分钟吧。

加百列大大张开六枚翅膀，将暗之剑挥向高空。

在一分钟的时间里，将这个小鬼的一切存在切断，抽出他的灵魂并加以吞噬。为了将这
更强大的力量变为自己的东西。

加百列带着蓝紫色的闪电，进入了突击态势。

我只是抬头看着已经无法称为军人的敌人的身影。

已经没法将那个男人——那个存在认知为恐惧和威胁了。而且如同要证明枪击已经无效一
般，应该已被打断的右臂，不知何时也已经完全再生了。

毕竟，我的觉悟还不够。

并不是低估了加百列·米勒这个人。那异样的气息足以让人进入最高戒备状态。但正是
如此，我说不准在这战斗开始之前，或许已经放弃了胜利的想法。如果拖延时间——也就是在
爱丽丝和亚丝娜脱离之前延长战斗的话，我和敌人都会被囚禁在两百年的时间之牢中，无法
再次回到现实世界。

啊……这样啊。

难道说我是在期待着吗？

超越了艾因葛朗特的，真正的异世界。茅场晶彦期望的，他所要创造出的理想之国。
Under World实在和它太相称了。

我在过去被囚禁在SAO内的两年间，经常会为自己到底是否真的想要离开而迷惑着。能
够在这迷惑中作为攻略组的一员在前线不断战斗，是因为我认识到在那个世界里的生活也是
存在着严厉的时间限制。因为躺在医院的床上的，通过注射而延续着生命的肉体不知何时就
会突破衰弱的极限。

然而，有着时间加速的Under World并非如此。特别是在倍率变为五百万倍的情况下，
没有必要去考虑现实中肉体的事情。我直到灵魂的寿命耗尽为止，都会一直留在这个异世界。
虽然是无意识中的想法，但我真的能断言自己没有这么想过吗？

结果——

我没有想过我最重要的人们，到底会悲伤到什么样的地步。

直叶、妈妈、爸爸、小唯、克莱因、艾基尔、莉兹、西莉卡……还有那众多拯救了我的
人。

还有爱丽丝。

亚丝娜。

他们会怎样叹息，怎样痛苦，怎样流泪，都没有……想过……

到头来，我仍然是个无法理解人心的人。

从初中时抛弃了第一个朋友，在假想世界里杀死了他的时候开始，一点都没有改变……

——不是这样的，桐人。

怀念的声音。

冰冷的左手，传来微弱的温暖。

——你不想离开这个世界，并不是为了你自己。而是因为你爱着在这个世界认识的那些人们。

——西露卡、缇卓、萝涅、露莉德村的村民们、在央都和学院里认识的人们、整合骑士和
卫士们……Cardinal女士、说不准还有Administrator……而且，大概还包括了我。

——你的爱，如此宏大，如此宽广，如此深远，足以背负整个世界。

——然而，那个敌人却不一样。

——那个男人，不知道人心，也无法理解人心。所以他才会去探索，才会去夺取，才会去
破坏。也就是说……

他在害怕。

加百列·米勒看到黑衣少年的脸颊上流下细细的泪水。他握着剑的双手，如同胆怯一般缩在
胸前。

是恐惧吗。

濒死者的恐惧正是对加百列而言最甜美的调味剂。至今为止加百列都曾用舌头品味着在
他手上死去的无数人的泪水并因此而陶醉。

感觉到了从体内涌上的巨大的饥渴，加百列的舌尖舔着嘴唇，挥动左手的指尖。

渐渐出现的无数黑球，如同蝇群一般嗡嗡叫着。

加百列将指尖指向那个小鬼的同时，黑球全部变为极细的激光，在空中奔驰。

咚。咚咚。

传来确切手感的同时，激光穿透了少年瘦弱的身体。黑暗夹杂着鲜血迸发出来。

「哈哈哈哈哈！！」

哄笑着一口气接近到零距离的加百列，将虚无之剑向后拉去——

一口气贯穿了少年的腹部。

在这时间如同被压缩了一般的刹那。

黑衫和大衣覆盖着的身体，被暴走的虚无撕裂，一下子分断开来。

血肉、骨骼、脏器一起飞散。

加百列将左手刺向如同红玉一般美丽的光辉。

抓住了悬在少年上半身上的，还在跳动着的最大的宝石——心脏，将它扯了下来。

加百列将掌中似乎想要抵抗着咚咚跳动的肉块慢慢放到嘴边，向带着空虚的表情漂浮在
空中的濒死的少年低声说道：

「你的感情、记忆、心灵和灵魂的一切……我现在可要吞噬掉了。」

我只是从半闭着的眼皮下注视着说出这句话的死亡天使的身姿。

加百列将红唇大大张开，如同咀嚼成熟的苹果一般，对着从我这里夺走的心脏露出了纯
白的牙齿。

……嚓。

响起了如同恐惧心在摇晃着一般的巨大声响。

白皙的脸庞扭曲起来，从嘴里流出了大量的鲜血——那无疑不是我的鲜血。

这是理所当然的。

因为他被我在自己的心脏里用钢素生成的无数利刃刺到了。

「咕……」

我对呻吟着按着嘴后退的加百列用沙哑的声音说道：

「心也好，记忆也好，怎么可能……在哪里啊。身体什么的……不过是容器罢了。回
忆……永远都在……」

在这里。

和名为『我』的意识融合，化为一体，永远不会分开。

身体被撕裂的痛楚已经剧烈到无法用痛楚形容的地步了。然而这一瞬间，是最大也是最
后的机会。如果放过的话，就再也没有下一次了。

优吉欧哪怕身体被打断了，也还在战斗。

我将双手中的剑张开——飞溅着鲜血喊道：

「Release Recollection！！！」

蓝白与纯黑色的光芒同时炸裂。

从指向前面的青蔷薇之剑上，流出数株冰之藤蔓，将加百列的身体捆住了两三层。

然后，从笔直指着的夜空之剑上——

巨大的黑暗之柱划向长空。

伴随着轰鸣声向上延伸的漆黑，贯穿深红色的天空到达高处——然后如同与太阳激烈地冲
撞了一般，向四面八方延伸。

天空被覆盖了。

血色以惊人的速度被抹去，正午的阳光消失了。

黑暗在数秒内到达了地平线，然后继续向远处延伸。

不，这不是虚无的黑暗。而是有着光滑的质感和些微温度的——

无限的夜空。[fn:149]

诗浓一个人躺在在无人的荒野上林立的乱石堆的底部，等待着天命全损的那一刻。

被打断的双腿的伤口的疼痛，让意识有一半以上都模糊起来。虽然右手如同握着生命线
般紧握着留在胸口的项链被打断的那一端，但也已经慢慢使不上力了。

在逐渐模糊不清的思考，已经无法分辨是注销的预告还是真正的失神的那一刻。

天空的颜色变了。

明明是中午却被怪异的血色铺满的天空，被从南侧袭来的黑暗以惊人的速度覆盖。太阳
光也被折断，灰色的云彩涂抹天空——之后，黑暗彻底包围了诗浓。

不对。不是彻底的黑暗。

从各处流下的淡淡磷光，将头顶的石山，枯萎的树木和脖子上的锁链映成一片蓝色。吹
来的温暖微风摇晃着她的刘海。

夜晚。将这广阔的世界，温柔而平稳地包裹并治愈的夜晚。

诗浓突然想起了过去的情景。

在和这里不一样的异世界的沙漠中的一夜。诗浓将被每日被幼年时遭遇的事件的记忆折
磨的痛苦吐出，敲打着他，哭泣着呼唤着他的事情。那时轻轻抱住她的后背，将之承受的手
臂的坚强和温暖，正充满了头顶的夜空。

这样啊……这个夜晚，就是桐人的心啊。

那个人绝对不是眩目的太阳。他从没有站在人们的前方，发出灿烂的光辉。

但在痛苦和难受的时候，他无论何时都会在背后支撑着自己。治愈自己的悲伤，擦干自
己的泪水。就像那发出微弱但确定无疑地存在的光辉的星星一般。就像这夜晚一般。

那么，拜托了——将我的心，传达过去。

诗浓湿润的眼睛拼命仰望着夜空，祈祷着。

在她头顶的正上方，一颗淡蓝色的星星闪耀着。

莉珐躺在无数半兽人和拳斗士们围成的空地上，等待着最后的时刻。

连为了使用泰拉利亚的回复能力而踏出右脚的力量都没有了。被劈砍和贯穿的全身如同
被冰冻一般寒冷，指尖根本无法动弹。

「莉珐……不要死啊！绝对不要死掉啊！！」

跪在旁边的半兽人族长利尔皮林，如同吼叫着一般喊道。莉珐带着淡淡的微笑仰望从他
的小眼睛里流出的透明的泪水，低声说道：

「不要……哭啊。我，一定会……再回来的。」

莉珐看着听到这句话的利尔皮林缩起身体颤动着肩膀的样子想着。

——虽然没能直接帮到哥哥，但是这样就已经很好了。我已经很好地完成了任务了。对
吧……？

就在这一瞬间，如同回应了莉珐的心声一般——

天空一下子褪去了颜色。

正午的天空突然变成黑夜，让半兽人和拳斗士的人群中出现了惊讶的声音。利尔皮林抬
起已经湿润的脸，睁开双眼看向天空。

但是，莉珐既不惊讶，也不害怕。如同要追随黑暗一般从南方吹来的，温柔地拂过脸庞
的夜风，让她感觉到了哥哥的味道。

「哥哥……」

她低语着，深吸了一口气。

桐人对莉珐而言，可以说是最近也是最远的存在。

哥哥大概在自己发现真相前，就在无意识中察觉到如今的父母并不是自己真正的双亲了
吧。在莉珐刚刚懂事的时候，桐人就已经被孤独和隔绝的色彩重重包围了。他绝不和任何人
结下深刻的羁绊，从产生了些许友情时起就不断将自己摧毁。

虽然正是因这个性格让他沉溺于网络游戏，也正是这份沉迷将他导向了『将SAO攻略的
勇者』的结果，但莉珐并不将这当成偶然的讽刺，也没有当成预定中的救赎。

那是各个自己选择的道路。选择了这条道路，拼命地背负着什么。这才是名为桐人的他
的强大之处。

头上的夜空一定是桐人将这个世界和世上所有人都背负起来的决心的证明。因为——

……哥哥比我还更像一个剑士。

莉珐用最后的力量动起已经失去知觉的双臂，如同握住竹刀一样将双手紧紧握在胸前。

然后，她祈祷着。

将我的心的力量，传达到哥哥的剑上吧。

头上的远处，一颗绿色的星星正发出强光。

莉兹贝特紧握着西莉卡的手，无言地仰望太阳已经消失的天空。

天空被黑夜覆盖的这不可思议的景象，让她想起了那一天发生的事情。

那是SAO开始运营后两年的，初冬某一天的下午。

跑出店铺的莉兹贝特，看到了将上层的底部铺满的系统信息上显示着的，死亡游戏终于
被攻略的通告。那一瞬间，她想，一定是桐人做到了。桐人挥舞着我锻造的剑，打倒了最终
Boss。

在回到现实世界后，桐人对莉兹贝特说了这样的话。

——我那时其实已经输了。被希斯克利夫的剑贯穿的我，HP确实变成了零。然而，不知道
为什么，我没有立刻消失。在仅剩的几秒钟内我动起右手，刺穿了希斯克利夫。我想赐予我
那短暂时间的，是包括莉兹、亚丝娜、和克莱因在内的大家吧。所以，在真正的意义上，攻
略的SAO的勇者并不是我。包括莉兹在内的大家都是勇者。

那时，虽然自己笑着说这是什么谦虚话，还敲了敲他的后背，但那大概是桐人的真心话
吧。他曾经这么说过，真正强大的力量，就在人们的心与心的连接之中。

「……呐，西莉卡。」

莉兹贝特将视线从夜空移开，看向旁边的友人。

「我……果然，还是喜欢桐人啊。」

西莉卡也微笑着回答：

「我也是呢。」

然后二人一起回头看向闪着微弱的磷光的黑夜。

闭上眼睛之前，她看到了在稍远处高高举起拳头的克莱因，和双手叉腰低声说着什么的
艾基尔的背影。

莉兹贝特听到了，和他们一样，以各自的方式祈祷着、许愿着的数百名玩家的低语。

——虽然我们只是通过AmuSphere连接到这个世界……但是，一定会传达给桐人的。因为
我们的心连在一起。

在他们头顶，同时出现的数百颗星星一下子遍布夜空。

整合骑士雷恩利左手抚摸着骑龙·风缝的头，右手握着少女练士缇卓的左手，连呼吸都忘记，
就这样注视着突如其来的黑暗。

白天变成黑夜，这是教会留下的任何史书上都没有记载过的恐怖现象。然而，雷恩利已
不再害怕了。

在身体被两柄长枪贯穿，正要走向不可避免的死亡时，从空中降下的光之雨将致命伤毫
无痕迹地治愈了。如今的这个夜晚，有着和那场雨几乎一样的温暖。

雷恩利既对自己活到了最后感到不可思议，也无法原谅这个事实。他坚定地认为，像骑
士艾尔德利耶一样在战斗中英雄般地死去，才是报答已经连名字都想不起来的旧友的唯一一
条道路。

然而，雷恩利在那光之雨中感受到了。

连从轮椅上站起来都做不到的黑衣剑士，他也失去了唯一的朋友。之后，他以这死亡责
备并折磨着自己，封闭了自己的心。

明明这样，那个人还是站起来了。然后，操纵着和雷恩利的神器·比翼一样的身为自己
和朋友分身的双剑，发挥出惊人的力量歼灭了数万敌军。他的背影让雷恩利明白了。

活下去。将生存、战斗、生命和心灵连接的东西。那是——只有那才是……

「那才是，强大的证明。」

雷恩利自言自语着，向握着缇卓的手中轻轻注入力量。

用另一只手牵着黑发朋友的手的红发少女，抬头注视着雷恩利。她眼中闪着的红叶色光
芒缓和下来，小心翼翼地点了点头。

三人再次笔直仰望漆黑的夜空，以各自的方式祈祷着。

在瞬间出现的数百个星星中，变为三个闪着强光的星座。

拳斗士团长伊修凯恩，在稍远处注视着被跪在地上的半兽人们包围的如今正逐渐走向死亡的
绿发少女，心中有着说不出的感慨。

那个少女的战斗方式，连鬼神都望之莫及。看到她的样子，伊修凯恩觉得自己似乎终于
可以明白为何半兽人们会背叛皇帝的命令前来救援拳斗士团的理由了。也就是说，半兽人族
人相信那个少女比皇帝还要强大。

然而他错了。

半兽人族长利尔皮林告诉他，一万名半兽人服从她——不，是恭顺她的理由只有一个：她
说他们也一样是人类。带着骄傲向伊修凯恩说出这句话的利尔皮林的单眼中，那过去如同漩
涡般的憎恨之色已经如同谎言一般消失了。

「喂，女人……不对，是谢塔。」

伊修凯恩呼唤着站在旁边的灰衣女骑士的名字。

「力量……或是强大，到底是怎样的东西呢……？」

已经成了无刀之骑士的谢塔，摇了摇扎成一束的长发歪起了头。她那冷淡的眼睛，先是
看向站在背后的飞龙，又看向双肩缠着绷带的巨汉，然后才回到伊修凯恩身上。她轻轻开口
说道：

「你应该已经明白了吧。比愤怒和憎恶还要强大的力量。」

这个瞬间——

已经看惯的暗之领域的血色天空，沉入了黑暗之中。

在屏住呼吸向上看去的伊修凯恩正面，只有一个绿色星星闪烁着光芒。

谢塔伸出手指向星星说道：

「就是那个。真正的力量，真正的光芒。」

「……对……对，是这样啊。」

伊修凯恩自言自语着。星星闪耀着的绿光，渗入了他从左眼流出的泪水。

拳斗士长将遍布伤口的拳头，第一次不是为了殴打他人而握紧，为了胜利以外的什么祈
祷着。

在离绿色星星稍远一点的地方，红色的星星如同火焰一般燃气。旁边，灰色的光如同紧
靠着一般浮现出来。

紧接着，随着活下来的拳斗士们低声唱和着战歌的声音响起，数百颗星辰遍布天空。

一万名半兽人军人和他们一样仰望夜空祈祷着。

在他们背后站着的暗黑骑士们也在祈祷。他们中的一部分，和半兽人军团一样从谜之军
队手中守护了拳斗士团。

星星的数量逐渐增多，达到了数千，达到了数万。

留在东之大门的人界守卫军、整合骑士法娜提欧、迪索鲁巴特还有几名下位骑士，也都无言
地注视着夜空。

虽然在他们心中游走的思绪各自不同，但祈祷和许愿的想法却是一样的。

法娜提欧为已然离世的整合骑士长贝尔库利所爱着的这个世界，为还在体内孕育的新生
命即将诞生的世界祈祷着。

迪索鲁巴特用右手轻轻包住左手手指上闪着光辉的小戒指，为和过去曾戴上同样戒指的
什么人一起活在的这个世界祈祷着。

其他的骑士和卫士们，为他们所爱的世界能够回到和平而祈祷着。

遥远北方的山区中，山地哥布林在祈祷。

荒野中，平地哥布林在祈祷。

东方的湿地中，等待丈夫和父亲归来的半兽人在祈祷。

西方的高台上，巨人们在祈祷。

无主的帝城奥布西蒂亚的街区内，有着浅黑色皮肤的人们，和东南部草原地带的食人魔
都闭上眼睛祈祷着。

夜空的前端，越过了终结山脉，一瞬间到达了人界。

在遥远的北方，露莉德村的教会里，正汲取用于洗澡的井水的见习修女西露卡，被从东
南角方向来的黑暗覆盖清澈的蓝天的景象夺走了视线，呆立在那里。绳子从手中滑落，落到
水面的桶激起轻轻的水声，但她并没有听见。

她的嘴边漏出颤抖着的低语：

「……姐姐…………桐人……」

现在，就在这个瞬间——

西露卡通过夜风感觉到，自己比任何人都爱着的二人，正拼命地战斗着。

也就是说，桐人再次醒来了。从失去了优吉欧的悲伤之崖的边缘，再一次站起来了。

西露卡跪在矮草坪上，将双手握在胸前。她闭上眼睛低声说道：

「优吉欧，拜托了……请保护姐姐和桐人吧。」

她随着祈祷而再次抬头看去的夜空中，有一个蓝色的星星闪耀着。

在蓝色星星的周围，出现了各种颜色的星星。一眼看去，之前还在院子里游玩的孩子们，
也无言地跪在地上，紧握着他们的双手。

在教会前的广场上，商人和主妇们在祈祷。

在牧场和麦田中，劳作着的男人们在祈祷。

在村长办公室里，爱丽丝的父亲加斯胡特在祈祷。

在森林的边缘，加里塔老人在祈祷。

没有一个人因这景象而恐惧或慌张。

露莉德村上空，在数秒内被无数的星星覆盖。

同样，在位于南方的扎卡利亚镇的上空，也遍布无数的星辰。

在四帝国各地点缀着的村庄或城镇中，居民们也一样无言地祈祷着。

在位于人界中央的巨大都市圣托利亚，市民们和修剑学院的学生们也在祈祷。

连隶属神圣教会的修道士和祭司们都不例外。

负责操纵大教堂第50层到第80层的升降板的的少女，做出了在漫长的人生中第一次做的
事情。在工作中的她将手从玻璃制的风素生成筒上放开，仰望天窗另一端无限的星空，握住
了双手。

她并不了解大教堂之外的世界。最高祭司的死亡也好，暗黑界军队的侵略也好，对少女
的人生从未造成过任何变化。

因此少女只为一件事情而祈祷。

祈祷着能和那两位年轻的剑士再一次见面。

在包围了广阔的Under World全部领土的正午的夜空中，闪着各种颜色光芒的星辰超过了十
万。

这些星辰，从终结之边境起，一个个奏响如同铃音一般的声音向着一个位置流动。

向着世界的最南端。

向着距离名为World End Alter的浮岛近处，笔直指向天空的一把长剑。

正在好不容易可以看到天边的阶梯上全速奔驰的爱丽丝，发现脚边映在大理石板上的影子，
被更巨大的影子覆盖了。

她吸了口气向后看去，飞入她的视野的，是令人难以想象的景象。

挥舞着虚无之剑的，有着六枚黑翼的敌人。

将那身体重重缠绕，封住动作的冰之藤蔓。

而握着冰藤的来源——闪着蓝白色光辉的长剑的，是有着飞龙之翼的黑衣剑士。

剑士的身体从胸部往下的部分都已经不在了。在瞬时间就会天命全损的状态下，还能继
续战斗的心意之力让人震惊。

然而，真正的奇迹却并非仅此而已。

从向空中高高扬起的剑士的右手握着的漆黑长剑迸发出巨大的暗之奔流，屹立着，覆盖
了天空和广阔的世界。

不，那并不是毫无光明的黑暗。

在遥远的北方闪烁的无限的色彩、无数的光点——那是星星。发出静谧的光辉的星群，让
夜空染上了色彩。

随后——

星星开始移动。

奏出如同银铃又如竖琴版清澈的重奏，笔直地向这里集中。拖着白色、蓝色、红色、绿
色、黄色的长长细线，在夜空中描绘出巨大的彩虹。

爱丽丝感觉到了，那所有的星星，显现出了全世界所有人的心意之力。

人界人。

暗黑界人。

人类。

亚人。

如今，整个世界在祈祷中化为一体。

「……桐人…………！！！」

爱丽丝呼唤着他的名字，高高举起左手。

把我的心也传过去吧。哪怕是这人造的骑士的，仅仅经过了短暂年月的伪造的心，但这
份感情——在这心中洋溢着的感动，一定是真实的。

从左手出发的，闪着令人目眩的光辉的黄金之星，向着桐人的剑直线飞了过去。

亚丝娜没有回头。

她知道，唯一能做到的能够回应桐人的奋斗的事情，就是不浪费一分一秒，向着系统控
制台前进。

所以亚丝娜只是拉着爱丽丝的手，用从心灵到身体的全部力量拼命奔跑着。

然而，洋溢在胸中的这份炽热的感情，却怎样都抑制不住。

感情化为两滴泪珠，划过睫毛，漂浮在空中。

随着夜风飞舞的两滴泪珠融为一体，变成了闪着七色光辉的星辰。

亚丝娜一瞬间抬头看着在黑暗中拖着极光的痕迹笔直飞上天空的星星，毫不回头地奔跑
着。她相信桐人可以做到。

加百列·米勒没能理解为何自己会被拘束的如同寒冰一般。

难道刚才不是将所有属性的术式攻击和斩击都完全无效化了吗。

确实，嘴被埋伏在心脏里的暂时形成的利刃伤到了。但这也只是口腔将咀嚼的动作实体
化了而已。如今他的全身已经被虚无的想象重重包围了。

我乃收割之人。我乃夺去一切光、一切热、一切存在之人。

我乃深渊。

「NU……LLLLLLLL！」

加百列的喉咙中，迸发出已经无法形容为人声的异质咆哮。

从后背伸出的三对黑翼，全部变为和右手的剑一样的虚无之刃。

虚无之刃发出剧烈的冲击声，将周围的空间全部割裂。终于将蓝白色的藤蔓切开，让身
体恢复了自由。

「LLLLLLLLLLLLL！！」

加百列伴随着咆哮将七把虚无之刃伸展开来。

空着的左手笔直指向前方，为从这一边将那个小鬼绑住而打算放出暗之线的时候——

加百列这才注意到，空中的红光已然消失。

以及从头顶一个个降下的，无数的流星。

在解放夜空之剑的时候，我并没有想象出任何具体的事物。

然而，从剑中迸发出的黑暗将白昼变为了黑夜，如同其名字一般，创造了夜空。

在夜空中突然流过的无数星辰化为虹色光柱流入剑身的时候，我察觉到了发生的事情。

夜空之剑的力量，是从广泛空间内吸收空间资源的能力。

而在这个世界上，最强大的空间资源，绝对不是太阳和大地在系统上供给的空间神圣力。
是人们心灵的力量。是祈祷、许愿、希望的力量。

降下的近乎无限的星光的最后一枚，终于也被吸入了剑身。

然后，仅有两颗的从地面飞舞而上的，金色和虹色的星星与剑刃融为一体的这个瞬间——

整把剑发出了不可思议的纯白强光。

强光从剑柄流入我的手臂，充满了身体。之前已然破碎的下半身，也伴随着白色的强光
在一瞬间再生了。

在被星光包围的左臂前端握着的青蔷薇之剑也发出令人眩目的光——

「哦……哦哦哦哦哦哦！！」

我将两把剑打开，喊出了声音。

「LLLLLLLLLLLLLLL！！」

在我面前，打破了青蔷薇的束缚的加百列·米勒也一样发出了奇怪的咆哮。

加百列的身形，已经不能称作是人类了。如同漆黑的流体金属般闪着不自然的光辉的裸
体被蓝黑色的光晕覆盖，从眼窝里放出的紫蓝色的光简直就像从地狱中发出的一般。

他将右手握着的，狭长的虚无之刃挥向高空，将变为同样刀刃的六枚翅膀全方位张开。

紧接着，从笔直地指向我的左手中出现了无数稠密的冰冷细线，向我飞了过来。

「……哦哦！！」

我大喊一声放出光之壁，将它们全部弹回。

接着，用力将从背后伸出的闪着光辉的翅膀张开。

架好左右两把剑后，一下子踢向天空。

敌我的距离仅差毫厘，突击的时间不过一瞬。然而，围绕着我的加速感，让我感觉这段
时间已经近乎永恒。

我的右边，出现了什么人的身影。

蓄着黑色的美髯，带着巨大长刀的不认识的壮年剑士。抱着浅黑肌肤的女剑士的男人，
看着我说道：

『年轻人啊，舍去杀意吧。那人的虚无之魂，以杀之心意的话是无法斩落的。』

之后，左边出现了威严的老年男人。全身纯白，佩戴着钢色的长剑。骑士长贝尔库利那
魁伟的容貌上露出了笑容。

『少年，无需恐惧。你的剑上，承载着世界的重量。』

在贝尔库利的身边，出现了肤色纯白，披着长长的银发的少女。

最高祭司Administrator，带着谜一样的银色眼瞳向我微笑着说道：

『就让我看一下吧，从我这里继承的，你全部的神威之力。』

最后，如同要抱住我一般，带着学者帽，穿着斗篷的年幼的女孩子出现了。披着棕色卷
发，肩上有一只小小的蜘蛛的，是另一位最高祭司Cardinal。

『桐人啊，去相信吧。汝所爱的，爱着汝的，无数人的心灵。』

小小的眼镜里，深褐色的眼睛温柔的眨了一下。

之后，他们的身影就消失了——。

与最后的敌人，加百列·米勒接近到最近距离。

我将全身的力量充满双臂，放出过去修炼最久，也是最为信赖的二刀流剑技。

《Star-burst Stream》。十六回连续攻击。

「呜……噢噢噢噢噢噢噢！！」

充满星光的剑，以照耀宇宙的轨迹击出。

同时，加百列的六枚翅膀和虚无之刃，从全方位向我袭来。

光和虚无发生激烈碰撞，巨大的闪光和爆炸震荡世界。

快一点。

再快一点。

「噢噢噢噢——！！」

我发出咆哮，将与意识一体化的肉体不断加速，挥舞着双剑。

「NULLLLLLLLLLLLLLL！！」

加百列发出吼叫的同时以虚无之刃还击。

十。

十一。

互相攻击放出的能量灼烧着周围的空间，化作轰鸣的闪电。

十二、

十三。

我的心中，已经再无愤怒、憎恶与杀意。只有充满全身的无数的星辰——祈祷之力驱动着
我和剑。

——去承受、

十四。

——这个世界中的、

十五。

——所有人的心之光辉吧！！加百列！！

最终的第十六击，慢了一步从左上段全力斩下。

用眼睛确认了攻击的加百列的蓝色眼睛，如同确信胜利般眨了一下。

比直接放出的斩击快了一步，敌人左肩伸出的黑翼，将我的左臂从根部斩飞。

充满了光的左臂在一瞬间爆散，空中只有青蔷薇之剑飞舞。

「LLLLLLLL——！！」

发出高声哄笑的同时，加百列右手握着的虚无之剑，直接向我的头上挥落。

啪。

响起让人信赖的声音，一双白色的手握住了空中漂浮的青蔷薇之剑的剑柄。那并不是我
的手。

与凄厉的炸裂音一起，无数的星辰飞散——

青蔷薇之剑与虚无之剑相击。

握着剑的优吉欧，摇了摇短发看着我说道。

『去吧——就是现在，桐人！』

「谢谢，优吉欧！」

我以坚定的声音回应。

「呜……噢噢噢噢噢——！！！！」

我的第十七击以右上段斩的态势，带着全身的力量挥向加百列的左肩。

漆黑的流体金属飞散，深深斩入的剑，在到达心脏的位置后停了下来。

瞬间——

我和优吉欧、充满了夜空之剑和青蔷薇之剑的所有光芒，注入加百列的身体，在各处奔
流。

加百列感觉到，自己体内突然有压倒数量的正之能量的大瀑布流入了宽广而空虚的深渊。

视线被无数流光覆盖，耳边听到了一个个声音。

——神啊，请让那个人……

——那个孩子，请平安地……

——让战争结束吧……

——我爱你……

——将这个世界……

——将这个世界，

——将这个世界守护吧……！

「……哈，哈，哈。」

虽然心脏被少年的剑贯穿，加百列却张开双手和六枚翅膀哄笑了起来：

「哈哈哈，哈哈哈哈哈哈！！」

何等愚蠢，何等愚昧，何等愚劣至极！

竟想将我的饥渴，将这无尽的虚无填满！

这到头来不过是想要用人手温暖宇宙这样的不敬之举——为何还不明白！！

「那我就一滴不剩，全部吸干——将它们全部吞噬！！」

加百列的双眼和口中闪烁着蓝色的虚无之光喊道。

「你做得到吗！！只不过恐惧着、害怕着人心之力的你做得到吗！！」

全身被黄金波动缠绕着的少年也一样喊了出来。

一层强光覆盖在剑上——产生进一步的热和光，刺入了冰冻的心脏。

视野逐渐白热，听觉也被切断了。

即使如此，加百列仍然大笑着。

「哈哈哈哈哈，哈——哈哈哈哈哈哈！！！」

我已经不再恐惧。

就算敌人深处的虚无如同无边的黑洞，在我心中由人们的心灵和祈祷产生的巨大的银河
正闪着光之漩涡。

加百列眼窝和口腔中的紫红色光，开始一点点变了颜色。

从紫到红，到橙，再到黄——最后是纯白。

噼。

随着微弱的声音，吞没了夜空之剑的漆黑流体金属身体，出现了一道小小的龟裂。

又一道。而且是从胸口到喉咙。

从龟裂中溢出了白光。后背上的六枚翅膀，也从根部被白色的火焰包围。

仍然哄笑着的嘴大大张开，肩部和胸部都开了大洞。

即使身体各处都出现了锐利的光柱，加百列的嗤笑却毫无终止的迹象。

「哈哈哈哈哈哈哈哈哈哈啊啊啊啊啊啊啊啊啊啊啊啊啊————」

声音的频率逐渐上升，最后变成金属质地的高频率声波。

虚无的天使被遍布全身的白色龟裂缠绕——

一瞬间，开始向内崩溃、收缩。

然后解放。

有着令人恐惧的规模的爆炸光，描绘出螺旋形状向天边飞驰。

「————哈哈哈哈哈哈哈！！」

加百列·米勒在哄笑中一下子坐了起来。

映入视野的，是铺着灰色金属板的墙面。接线和管道上贴着几张日语写的注意事项贴纸。

「哈哈哈，哈，哈…………」

带着混乱的呼吸收起笑声，加百列眨了几下眼睛，向左右看去。

这里毫无疑问是《海龟》的第一STL室。似乎是因为预料之外的原因自动注销了。

何等美中不足的结局。要是就那样吞噬近乎无限的灵魂之流的话，明明最后就能将那个
小鬼的心也一起吞噬掉的。现在立刻再度登录的话还赶得上吗。

苦笑着回过头的加百列看到的。

是躺在STL的座椅上，闭着眼睛的高个头白人男性的样子。

……谁啊。他一瞬间想着。

袭击小队里有这个队员吗？而且这个家伙，在我用来潜行的机器上做了什么……

想到这里的时候，他才注意到。

那个人，那张脸，是他自己。

是加百列·米勒。

那么，看到这幅场景的我……到底又是谁？

加百列眺望着自己抬起的双手。他看到的，是有着半透明感的，发着朦胧的光的东西。

这是什么啊。发生了什么。

这时——

从背后传来了轻轻的声音。

「……你终于来到这里了呢，盖博。」

加百列一下子回过头。

站在那里的，是一个穿着白衬衫和深蓝色百褶裙的幼小少女。

有着长长的柔软金发的头深深的低了下去，所以看不到她的脸。然而加百列立刻就明白
了那个少女是谁。

「……艾莉西亚。」

加百列自言自语着。

「为什么，你会在这里，艾莉……」

艾莉西亚·克林格曼。加百列为了自己探求灵魂的崇高目的，而杀死的第一个人——身为
他青梅竹马的少女。

加百列一直为没能捕获当时看到的有着清亮光辉的艾莉西亚的灵魂而痛恨不已。然而，
那个灵魂从没有离开他，一直都好好的呆在他的身边。

加百列忘记了自己面前这奇怪的现象，微笑着伸出了右手。

咻。艾莉西亚的左手快速伸出，用细小的五指紧紧握住了加百列的手。

好冷。简直就像冰一样。冷气像是尖针一样一点点刺进了手里。

加百列反射性地想要将手拉回来。然而，艾莉西亚的左手如同钳台一般动也不动。加百
列的笑容消失了。他皱起眉头说道：

「……好冷啊，放开我的手，艾莉……」

听到加百列的低语，金发突然左右摇摆了起来。

「不可以哦，盖博。从此我们要永远在一起啊。来，我们走吧。」

「去是……要去哪里啊。不行，我还有要做的事情。」

加百列低声说着，全身使劲想要将手拉回。然而根本就动不了。反过来，右手还被一点
点往下拉了。

「放开我……放开我，艾莉西亚。」

在加百列稍微严肃地出声的同时。

艾莉西亚一下子抬起了头。

在那仔细梳好的刘海下面的脸进入视野的瞬间——

加百列感觉到心脏一下子收缩起来。

内脏在翻滚。呼吸变得混乱。身体开始起鸡皮疙瘩。

这是什么啊。这个感情到底是什么啊。

「啊……啊，啊，啊……」

发出奇怪呻吟的加百列，慢慢摇了摇头：

「放开我。住手。放开我。」

虽然他无意识中抬起左手，但艾莉西亚却如同飞过来一般将那只手也紧紧抓住了。如同
冰冷的金属一般的手指，一点一点嵌了进去。

呜呼呼。

艾莉西亚笑了。

「这就是恐怖哦，盖博。就是你一直想要知道的真正的感情哦。怎么样，很厉害对吧？」

恐怖。

在至今为止探求灵魂的实验中杀死的人们，在濒死之时露出相同的表情的来源。

然而，这种感觉实在没法说让人感到很舒服。不如说相当让人不快。可不想知道这种东
西。赶紧结束吧。

但是——

「不可以哦，盖博。从现在起要一直继续下去呢。你只会永远感觉到恐怖哦。」

随着吱的一声，艾莉西亚小小的皮靴沉入了金属地面。

接着，加百列的脚也陷了进去。

「啊……啊……不要啊。放开我……不要啊。」

虽然加百列神志不清地说着，可沉陷却根本停不下来。

突然，从地面上砰地飞出一只白色的手臂，缠住了加百列的脚。又是一只。然后又是一
只。

加百列的直觉告诉自己，这是至今亲手捕获的猎物们的手。

恐怖感开始不断上升。心脏以惊人的速度跳动，汗水从额头上流下。

「不要……不要，不要不要不要……！！」

加百列终于开始惨叫。

「快过来，克里特！起来，瓦沙克！！汉斯！！布利格！！」

虽然呼唤着部下们，但面前的大门却依然保持沉默。躺在旁边的STL上的瓦沙克也没有
起来的迹象。

不知何时，身体从腰部以下都已经没入了地面。拉着自己双手的艾莉西亚，已经只能看
到肩膀以上的部分了。

那张『脸』在完全没入地面前的一瞬间，大笑了一下。

「啊……啊啊啊……呜哇啊啊啊啊啊——！！」

加百列发出了哀鸣。

一次，又一次。

肩膀，脖子，然后连脸都被白色的手缠住了。

「啊啊啊啊……啊啊啊…………啊………………」

随着咚的一声，视野陷入了黑暗。

加百列·米勒因领悟到了自己的命运——将被永远流放而迸出高声的哀鸣。

之后——

Under World的时间流，开始再次加速。

在与此同时切断信号的瞬间，通过AmuSphere进入Under World的几百名日本人也被自动切断
了连接，在各自的房间或网吧单间里，在浸染胸中的各自的感慨中醒来。

他们都无言地记忆着、思考着、在心中刻入在异世界体验到的事情。然后拭去眼角的泪
水，操作着携带终端或AmuSphere。为了向在之前的战斗中倒下并注销的友人们，传达在那
个世界发生的一切。

诗浓和莉珐在再次加速的瞬间前，就因天命全损而离开了Under World。

在《拉斯》六本木分室的STL上醒来的二人，等待仍飘在神经中的痛楚的余韵散去，互
相对视着，深深点了点头。

诗浓和莉珐都毫不怀疑桐人会苏醒、打倒敌人、拯救世界，很快就会回到现实。

下次见到他的时候——

就算无法传达过去，也要好好地将这份感情说出来。

下定了决心的两人意识到对方的想法，露出了淡淡的微笑。

——然而。

完全解除限制的STRA系统，正将Under World内流动的时间脉搏，向远超过去的高速领
域加速。

超过了一千倍。

超过了五千倍。

向着名为《极限加速阶段》的，相当于现实世界流速五百万倍的时间之壁的远方前进。

我的身体漂浮在星光已然散去的空中，无力地拍动着背上的双翼。

应该已被斩断消失的左臂不知何时已经再生了。我以仅存的力量拼命握着手中的青蔷薇
之剑，忍住要从眼中渗出的泪水。

我明白，烙印在剑中的，至今为止无数次拯救了我、激励了我的优吉欧的灵魂，在那个
瞬间——毫无动摇地挡住了加百列的剑刃的那一刹那，终于彻底燃尽了。

死者无法复生。

所以回忆才如此宝贵，如此美丽。

「……是这样的吧，优吉欧……」

虽然我低语着，却并未听到回应。

我将手中的双剑慢慢收回后背上的剑鞘。

随后，头顶夜空的颜色开始变淡。

黑暗逐渐溶解流去，光芒在另一端苏醒。

……蓝色。

然而，再次出现的暗之领域的天空，却并非之前的血色。

只有清澈透明的湛蓝色，在各处蔓延。
*** 第64节
 [fn:150]

#+begin_center
我无法确定，这是因终于开始的《极限加速阶段》的影响而导致的结果，还是十余万人
的祈祷引发的奇迹。
#+end_center

不论哪一个理由，透明的蓝天都美丽到令人想要落泪。我感到自己被强烈的乡愁和感伤浸染，
将这湛蓝一口气吸入身体。

闭上眼睛，呼出长长的一口气，然后将身体转向另一个方向。

睁开眼睛后看到的，是从下方开始无声崩坏的白色大理石阶梯。

我张开双翼，如同要追赶崩解的阶梯一般缓缓向浮在空中的小岛降落。

圆形的浮岛上，有无数有着近乎溢出的鲜艳颜色的花朵在开放。穿过花田的白色石板路，
向中央如同神殿一般的建筑物延伸。

我在石板路上着地，将双翼变回大衣的下摆，接着环视周围。

鼻子里闻到了甘甜而清爽的蜜香。几只琉璃色的小蝴蝶轻飘飘地飞舞，小鸟在树梢上鸣
叫。在蔚蓝的天空与柔和的阳光下的这幅景象，显得如此美丽，简直就是一幅名画。

上面空无一人。

不论是小路上，还是小路前方排列着圆柱的神殿中，都找不到任何人的身影。

「……太好了。赶上了吗。」

我孤零零地自言自语着。

我靠着感觉，知道了随着加百列·米勒被吸入光之螺旋中消失，这个世界再次基于STRA
的倍率开始加速。对于亚丝娜和爱丽丝，能否平安从控制台脱离，可以说是微妙的时间点。
然而，二人在时间限制内跑过了漫长的阶梯，到达了那里。

爱丽丝——身为这个世界产生的理由的灵魂，突破Fluct Light极限的少女，终于开始了
通向现实世界的旅行。

从此以后，大概还有无数的苦难等待着她吧。她必须和运转原理几乎完全不同的世界、
不自由的机械躯体、以及可能将真正的人工智能用于军事领域的企图战斗。

然而，爱丽丝一定能做到的吧。因为，她是最强的骑士。

「……加油…………」

我抬头望向天空，为再也无法相见的黄金的整合骑士祈祷。

没错——

《极限加速阶段》开始的现在，我已经完全失去了从内部自行注销的手段。这个世界内
的三个系统控制台已经全部被冻结，如果天命全损，就只能在没有感觉的黑暗中等待加速阶
段结束。

如今，虽然身处外部的菊冈等《拉斯》工作人员正为关闭我的STL而奋斗，但最短也要
二十分钟才能完成。

在这二十分钟内，我要在这个世界度过两百年日月。

我不知道自己是会因灵魂寿命耗尽而意识消失，还是因无法长时间忍受五百万倍的加速
而在更早的时间点消失。

唯一能确定的，就是我已经无法回到现实世界了。

父母、直叶、诗浓、克莱因、艾基尔、莉兹、西莉卡。

学校里的朋友们，ALO内的玩家好友们。

爱丽丝。

还有，亚丝娜。

已经再也见不到我爱着的人了。

我的双膝缓缓跪在白色的石板上。

用双手支撑着无力的上半身。

视线开始模糊，摇动着无数闪烁的光，一次又一次落到磨光的大理石板上。

大概——我只有现在，才有稍微哭泣一下的权利吧。

为了已经失去的，不会再次回来的，重要的事情而哭泣。从紧咬的牙齿间漏出呜咽，泪
水变为泪珠落下。

啪。啪啪。

耳边传来了水滴落在石板上的声音。

啪。

啪。

——叩。

叩、叩。

突然，响起了有着确切的密度的和声。

叩、叩。离我越来越近了。从指尖传来微弱的颤动。

空气在摇曳。在浓密的花香中，仿佛传来了新的香气。

叩。

……叩。

声音在我的眼前停下。

之后，有什么人，呼唤了我的名字。

神代凛子坐在副控制室的操作席上，屏住呼吸注视着控制台位于正面偏左位置的小型玻璃舱
门。

舱门上面的液晶窗口，闪烁着『EJECTING...』的红色文字。

抽出压缩空气的声音，在耳边低声回响。

终于，窗口的另一端，出现了一个小小的黑色正方形。液晶窗口变为绿色，闪耀着
『FINISH』的光芒。

凛子伸出颤抖的手，打开玻璃舱门将它拿了出来。

坚固的金属封装。边长约六厘米的正方体。相当沉重。被毫无缝隙地封闭着的一个面上，
有一个超微型连接装置。

《爱丽丝》的灵魂——就沉睡在里面。

从设置在《海龟》基部的巨大Light-Cube集群内，依照系统命令弹出了一个晶体立方体，
自动封入金属封装后，又被传送到长长的传送带上，终于到达了这里。

这同时也是从名为《Under World》的内部世界，通向名为《Real World》的外部世界
的旅程。

凛子在一瞬间因不知何以言表的深切感慨而失声，但很快就恢复意识，紧握着金属封装
喊道：

「亚丝娜小姐，爱丽丝的弹出工作结束了！接下来是你了，抓紧时间！！」

她瞬间瞥向染成一片红色的主显示器上的倒计时。

「只剩下30秒了！！快点……注销！！」

一瞬间的沉默。

接着，从扬声器里传来的——是意料之外的话。

「对不起，凛子小姐。」

「诶……？为，为什么……？」

「对不起。我要……留在这里。一直以来都麻烦你了。凛子小姐所给予我的帮助，我绝
对不会忘记。」

从扬声器中传来的结城明日奈的声音，安稳而温柔，却似乎已下定了决心。

「爱丽丝就拜托你了。爱丽丝，是个很温柔的人。她有着无数的爱，也被无数的人爱着。
为了那些为她而消失了的灵魂们……还有，为了桐人君，请绝对不要将她用于军事用途。」

在无言以对的凛子耳边，又传来了明日奈最后的话：

「请告诉大家。抱歉……再见了……谢谢你。」

紧接着，倒计时变成了零。

随着长长的警报声音，无数机械的运转声在狭窄的电缆管道内回响。

管壁另一端的冷却系统开始全速运转。几个大型风扇正拼命将支撑Under World的系统
群放出的大量废热吸收并排出。如今如果从海上眺望《海龟》的话，大概可以看到金字塔顶
端附近的微弱蒸汽在摇晃吧。

「…………开始了……」

比嘉健低声说道。

「啊。」

以简短的话语回答的，是背着比嘉沿着细长的梯子下降的菊冈诚二郎。

二人在判断无法避免进入《极限加速阶段》的时间点就立刻开始准备，潜入了电缆管道，
可光是用安全绳固定负伤了的比嘉的身体就花了八分钟。

加速在菊冈以汗水如同要喷出来一般流下的势头在管道中降下到达耐压隔壁之前，就已
再度开始。

比嘉以祈祷一般的心情按下对讲机上的开关，呼叫位于副控制室的神代博士。

「凛子小姐……怎么样了？」

在噪音和线路连接音后，另一端却保持着沉默。

「……凛子小姐？」

「……对不起。已经确保爱丽丝平安无事了。只是……」

神代博士拼命忍住声音，说出了后面的话。

比嘉屏住呼吸后，紧紧闭上了眼睛。

「……明白了。这边也会尽力的。开放舱门的时机，会在之后联络。」

挂断通话后，比嘉这才将屏住的气一口气吐了出来。

不知是不是察觉了状况的菊冈并没有问什么。只是以他那全是肌肉的身体拼命地跳跃着。

「……菊先生……」

几秒钟后，比嘉才终于低声向指挥官传达了神代博士的话。

克里特呆呆地看着主显示器上新出现的窗口以及上面的字母。

上面所显示的，是从集群内排出了一个Light-Cube，并将其运送到耐压隔墙另一端的副
控制室的消息。

也就是，K组织已经拿到了爱丽丝的意思。

换句话说，从Under World内部发现并夺取爱丽丝的超过了十小时的作战完全失败了。
瓦沙克和米勒中尉潜入Under World，率领暗黑界的军队侵略人界，展开如同好莱坞电影一
般宏大的战争，还欺骗近十万美国、中国和韩国人卷入的努力全部化作了泡影。

克里特咔咔挠着和尚头，发出一声鼻音后将思考切换到别的方向。

在剩下的五小时里，有没有能够从物理上再次夺取爱丽丝的可能性呢？

耐压隔墙没法从这一边破坏。但是，像之前那样上边开放隔壁的情况就是另一回事了。

再说，之前打开舱门到底又是搞什么？难道他们真的认为让那样一个机器人搭载烟雾弹，
这边就会有什么动作吗？

如果那是佯动作战呢？如果有其他开放隔墙的目的的话，那个目的到底又是什么呢？

克里特回过头，向队员们说道：

「喂，谁把《海龟》的设计图拿过来——」

接着，布利格和仍然争吵着刚才的赌博不成立的汉斯，根本没往这边看就将叠成几层的
纸拿了过来。克里特带着一脸「真是的」的表情摇摇头，将设计图接过来展开。

「嗯……？这里是主轴……耐压隔墙在这里横断……机器人突进的楼梯是这里吧……」

此时，显示器上的倒计时变成了零，整个房间都响起了低沉的机械声音。时间加速再次
开始了。然而，因为布利格的乱来破坏了操纵杆，倍率正变成不得了的数值。

然而，Under World变成什么样已经没有关系了。作战失败就等于瓦沙克和米勒中尉大
概在潜行中『死亡』，他们现在应该在旁边的房间中进行注销处理吧。

现在，在米勒中尉回来之前，需要先行确定下一个作战选项。

克里特在昏暗的灯光下拼命瞪着地图，这才终于注意到它。

「哦，这里也有一个小舱门……这什么啊，电缆管道……？」

向比嘉健传达完情况的凛子，在沉痛的叹息后将后背靠在操作席上。

为了已确定不可能在时限前脱离的桐之谷和人，自己也留在了Under World的结城明日
奈的决心，是如此的年轻而直率，又是如此的宝贵而美丽。

凛子无论怎样都无法让自己不想起，过去她曾爱着的那个男人，将她留在现实世界，消
失在遥远的异世界的事情。

如果那时，有自己可以一同前往的机会的话，又会做出怎样的选择呢？会选择是和他一
样，在原型STL内将大脑灼烧殆尽，只留下意识的复制体这条单行道吗？

「晶彦……你…………」

闭上眼睛的凛子，以不能称作声音的声音自言自语。

当初他的愿望，应该就是创造由浮游城艾因葛朗特，以及被囚禁在其中的五万名玩家构
成的《真正的异世界》。

然而，在长达两年前的浮游城内的日子里，他看到了什么，知道了什么。这『什么东西』
改变了他的想法。

在前方——更前方，存在的东西。

他注意到，SAO世界并不是终点，而只是一个起点。所以，他才在长野被原始森林包围
的山庄里，将Nerve Gear的信号输入输出原件加以高密度化，终于完成了将自己杀死的试作
机。

被他托付了基础资料的凛子，开发了医疗用高精度NERDLES机器——也就是Medicuboid。

《拉斯》和比嘉健又在与这Medicuboid连续连接了数年的一位少女提供的庞大数据的基
础上，完成了STL。

这样想的话，可以说名为Under World的终极的异世界，就是以他——茅场晶彦的想法而
诞生的。

那么，Under World的完成，就是茅场所期待的那个终点吗？

不，一定不是。

因为，他所留下的另一个种子，名为《The SEED》程序包的碎片还有着未解之谜。

确实，可以说正是因为《The SEED》规格的VRMMO已经标准化，在之前的外部势力袭击
Under World时，日本玩家们才能通过帐号转换加以对抗。

然而，就算是茅场也不可能在几年前就预料到会有这等事态。基于转换机能的Under
World内潜行，只能说是一个副产物。

要是这样，目的又是什么呢……为什么有必要让全世界的VR世界，以共通规格相互连接
呢……

「……士，神代博士。」

听到背后的声音，凛子一下子睁开眼睛。

回过头去，有着刚毅容貌的中西上尉，立刻敬了个礼后报告道：

「针对隔墙再开放的对应准备已经完成了。随时可以启动。」

「啊……知，知道了。非常感谢。」

凛子看向显示器确认时间。从进入《极限加速阶段》后，已经过了一分钟。内部时间则
是……十年。

令人难以置信。桐之谷和人和结城明日奈灵魂的年龄，已经超过了凛子。

快一点……一分一秒也好，早一点注销。如果，能在灵魂寿命彻底耗尽前脱离的话，还
可以重置《极限加速阶段》开始后的全部记忆。然而，为了能这么做而剩下的时间，理论上
已经不足十二分钟了。

比嘉君……菊冈先生。

快一点！！

凛子紧咬着嘴唇，在心中说道。

菊冈中校从喉咙里吐出的呼吸声音，已经如同快要坏掉的风扇一般。流下的汗让上衣变色，
连比嘉的衣服都湿透了。

比嘉好几次将「从这里我就自己下去」的话咽了下去。

被柳井射出的子弹击中的右肩，虽然注射了极限剂量的镇痛剂仍然极为疼痛，身体因大
量失血也如同灌了铅般沉重。不管怎样都没法自己抓住梯子。

就算这样——比嘉想着。

在这种事态之下，菊冈中校还如此拼命，实在不让人不感到意外。

身为Alicization计划精髓的，突破极限的Fluct Light《爱丽丝》，已经确保在手中了。
之后只要解析爱丽丝的构造，发现其与之前的Fluct Light间所存在的差异，就可以做到真
正Bottom-Up型Ai的量产。在即将到来的无人兵器时代，能够创立日本独有的技术基础，从
美国军事生产系统中脱离——这一《拉斯》的设立目的也终于达成了。

这就是，名为菊冈诚二郎的这个人的愿望。

在转到总务省前就埋头于SAO事件也好，创造自己的角色和年轻的VRMMO玩家们交流也好，
一切都是为了这个目的。

因此，要说菊冈的行动优先顺序的话，现在应该会选择彻底关闭耐压隔墙，在护卫舰突
入前都死守爱丽丝的Light-Cube吧。

哪怕这等于被困在Under World里的桐之谷和人和结城明日奈灵魂崩坏，把一定会激烈
反对的神代博士软禁在房间里也在所不辞。

「你肯定，觉得……这，很意外……吧。」

菊冈中校在急促的呼吸中突然说出的话，让比嘉漏出了奇怪的声音。

「不，不是，那个……嘛，总觉得这么做一点都不像你啊……」

「真……是的。」

菊冈全力向不远距离处的舱门降下，喉咙里嘿嘿笑出了声。

「但是……我说过，的吧。这也是……有，打算过的，行动……啊。」

「诶……诶？」

「我……平常是，考虑到最糟糕情况，的人。现在……敌人，还有，再次夺取……爱丽
丝的，可能性，还是这么想比较好。」

「最，最糟糕……吗。」

还有着比敌人注意到这个电缆管道，在耐压隔墙开放的情况下从下面突入还要糟糕的情
况吗。

然而，在比嘉想要推测下去之前，菊冈的战斗靴靴底，终于碰到了钛合金舱门。

代替停下动作，只是剧烈呼吸着的指挥官，比嘉按下了对讲机上的开关：

「凛子小姐，我们已经到了！请解除耐压隔墙的锁定！！」

「啊……动真格的么，居然开了——！」

克里特看着主显示器上显示的耐压隔墙开放警告喊道。

到底为什么。为了什么。

怎么想都不对头。已经确保了爱丽丝的现在，K组织居然故意让防御出现破绽，到底有
什么理由。

然而现在已经没有想这想那的时间了。克里特回过头，挥手向队员们喊道：

「……那个，啊，布利格留下，包括汉斯在内的所有人突入主通道！迂回攻击，确保隔
墙另一侧！」

「还真是简单啊……」

汉斯咋着舌扛起了步枪。十几名队员跟在他的后面。

「喂喂，我又要怎么办……」

克里特看向一脸不服地撅着嘴唇的布利格长着胡须的脸，打了个响指说道：

「好好地有工作呢——需要你的手腕的，重要的任务啊——」

当然他的脑子里想着别的事情。最好别让这个笨蛋离开自己的眼睛比较好。

「听好了——我们两个去看看这边的电缆管道。不管怎么样我都觉得这里才是敌人最重要
的地方——」

「哦……哦，这样啊。是这样没错。」

看着笑了一下，以大剌剌的动作确认突击步枪的枪机的布利格，克里特忍住自己轻轻的
叹息。

经过汉斯他们出去的主控制室的门，准备跑向另一个方向之前，克里特瞥了一下里面的
门——第一STL室。

这么说的话，注销需要花这么长时间吗？瓦沙克那家伙难道是在悠闲地抽烟吗？

虽然想着是不是应该先去确认，但此时布利格已经跑了起来。

再次咽下叹息，克里特追在他的后面。
** 第八章(继上回)
*** 38
几十秒后，他们到达了目标地点。一眼看去，只不过是通道的末端而已。然而根据地图，
眼前的小舱门的另一端，应该有一个和主轴上部架构连接的电缆管道。

克里特用渗着汗的手握住回转式的开闭手柄，然后转动起来。

拉开沉重的金属门的克里特最先看到的，是被暗橙色光照着的相当狭窄的隧道。正面的
墙上，设计着近乎垂直的阶梯。

接着他毫不在意地看向脚边——

「……呜哦！？」

克里特发出破碎的声音，一边赶紧后退。

那里嵌着一个身体似乎被弯成了U字形的男人。背后的布利格一下子架起了步枪。然而
他接着就压下声音说道：

「……死了耶。」

确实，侧脸看向他们的男人的颈椎，以不自然的角度弯曲着。克里特紧锁眉头仔细看着
那个男人的脸，眨了几下眼睛。

「诶……这家伙不是他么，提供K组织情报的那个人……怎么回事，难道是间谍身份暴
露了吗……？但是，这种死法……」

战战兢兢地用指尖接触男人的皮肤，感觉冰冷湿润。从温度来看，他恐怕在隔墙第一次
开放时候就死了。也就是说，第一次开放是因为这个男人想要脱离到下层吗？然后，踏空了
梯子，摔死了？

然而，这样的话，为什么隔墙会再次打开呢。

克里特转向布利格说道：

「还是先去看看管道上面怎么回事吧。」

留着胡须的巨汉鼻子响了下，伸出右手随意将间谍的尸体拉到了通道内。他架起步枪，
上半身探入昏暗的隧道里——

喂喂，别连头都伸进去啊。克里特这么想的一瞬间——

「见鬼！！」

随着一声喊叫，突然有人开枪了。

黄色的闪光反射到克里特的视网膜上，有两种音调不同的射击声敲打着他的鼓膜。

压下哀鸣跑过去的他的面前，布利格巨大的身体，像是被看不到的锤子打中一般落到了
地上。

「喂！！什么啊，可恶！！」

克里特这么喊着，向后跌倒了。布利格上半身就位于刚才间谍的实体所在的地方，已经
一动也不懂了。不仅是姿势，连命运都和那个间谍一样——这一点再清楚不过了。

——接下来，要怎么办。

全身冷汗的克里特思考着。

把步枪从布利格手中回收，和隧道里的敌人互相射击来复仇吗？怎么可能！我不过是个
电脑死宅，工作只是敲键盘罢了。

擦了擦磨得粗糙的裤子，克里特向主控制室后退，继续思考着。

至少这样可以明白为什么K组织会如此积极攻击的意图了。但是，战斗力很明显是这边
占优。如果战斗的话，那边当然会有牺牲。如果他们失败了，整个上半部分都被占领，爱丽
丝也会被再次夺取。

难道K组织的指挥官还考虑到比这还『糟糕』的情况吗？他想过这里有将《海龟》整个
炸掉的火力吗？怎么可能，手持C4炸药连耐压舱门都炸不开……

火力…………

克里特突然倒吸一口凉气。通道前面横陈的两具尸体已经没有了意识。

有。

将《海龟》整个破坏，让爱丽丝和K组织全都变成海藻的办法。只有一个。

确实，客户的命令里提到，在判断不可能夺取爱丽丝的场合下，至少也要将其完全破坏。
然而，为此就要让这个巨大的自走式大型浮台，和数十位成员成为陪葬品。

自己下不了这么可怕的决定。肯定会成为缠绕自己一生的噩梦。

克里特站起来，为了得到指挥官的判断，奔跑着。

「菊……菊先生！没事吧，菊先生！！」

比嘉强压声音问道。从管道最下方的舱门出现的敌人，至少用步枪打出了三发子弹。

没有回应。背着比嘉，右手握着梯子一边，左手拿着手枪的菊冈中校，像是把肩膀靠在
墙上一般无力地垂着头。

「菊……」

菊冈先生！！！

比嘉正要喊出来的时候，中校激烈地咳嗽了一下。

「切……喂，真是的……中招了。如今想想，本来该穿着防弹衣来的……」

「那……那是当然的！结果你居然真穿着夏威夷衫就过来了……」

比嘉安心地吐了口气，再次询问是否受伤。

「嗯，貌似中了一枪。相比这个，你没事吧？有没有被跳弹伤到？」

「诶……没有。身体倒没受什么伤。」

「那就抓紧吧。连接装置马上就到了。」

在再次开始降下的菊冈背上摇晃着的比嘉再次在心中深感意外。

原本以为菊冈中校在身体相关的技能上是个相当不擅长的人，但他宽广的后背上的肌肉
如同钢铁一般，还有刚才的射击。挂在梯子上，只用左手向下狙击的这种恶劣条件下，居然
只用两发连射就正确地击中了敌人的喉咙和额头。

真是个不论怎样交往都不知底细的大叔。

比嘉轻轻摇了摇头，在右手中准备用于和已经进入视线的检查用接线器连接的线缆。

回到通道里的克里特，听着从上方响起的步枪连射声音，跑向主控制室。

房间里仍然没有米勒中尉和瓦沙克的身影。还没从STL里出来吗。明明从时间加速再次
开始后已经过了五分钟了。

虽然脑子里这么想着，但克里特还为要不要向他们说明而迷茫着。他相信，听到消息的
二人肯定会立刻下达将《海龟》炸掉的命令。他们可不是会关心为了达到目的会牺牲多少人
的人。

克里特没能得出结论，只是一口气打开了第一STL室的房门。

「队长！爱丽丝，被敌人…………」

本该接下去的话，却变成了嘎吱嘎吱的声音从喉咙里发出。

在他的正面，躺在一号STL床上的，从额头往上都被巨大的机器吞没的米勒中尉的脸，
露出了之前一次都没见过的表情。

不对。克里特从来没在任何人的脸上看到过那样的表情。

蓝色的双眼像是要飞出来一般大大睁开。嘴部的下颚关节像是脱臼一般张开到极限，而
且还歪斜着。突出的舌头扭向奇怪的方向，简直就像是别的生物了。

「队……队……长……？」

克里特喘息着，膝盖开始颤抖。现在，如果米勒中尉突出的眼球转动一下，他相信自己
肯定会发出惨叫。

克里特的牙齿咔咔咬着，战战兢兢地伸出手，轻轻抓住简直就像是防备着什么一般伸出
的中尉的左手腕。

脉搏已经没了。

身体冷得像冰一样。强袭小队指挥官加百列·米勒中尉，明明身上没有一处伤口，却已
经彻底气绝了。

拼命压下从胃部涌起的翻滚，克里特用沙哑的声音喊道：

「瓦沙克……快起来！队长……死，死……」

他拖着双脚绕过一号STL，看向里面二号机的位置。

这次克里特真的发出了惨叫。

副队长瓦沙克·卡扎尔斯，一眼看上去似乎很安详地睡着。闭着眼睛的脸上毫无表情，
双手和身体也伸的笔直。

然而——

闪着黑色光芒的，鲜艳的长卷发，如今已经变成了如同百岁老人一般干枯的白发。

已经不想确认瓦沙克的脉搏了。克里特没有听到话，颤抖着膝盖后退。身为只信奉理性
和代码的黑客的克里特，相信自己必须赶紧离开这个房间，不能再和两个人对视了。

跌跌撞撞地转过身从还开着的入口跑出，用右脚立刻把门关上。

这时克里特才长出了一口气，拼命地让自己重新开始思考。

既不打算调查队长和瓦沙克发生了什么，也不想知道发生了什么。能够推测的，就是在
Under World里发生了什么事情，因此他们的灵魂和现实中的肉体大概都被破坏了。

到这里，作战已经失败了。指挥官死掉的情况下，已经无法判断要不要将爱丽丝连船一
起破坏了。已经没有留在这里的意义了。

克里特拿起控制台上的通话机，挤出沙哑的声音说道：

「汉斯……回来。布利格、瓦沙克和队长都死了。」

几十秒后，跑进控制室的花花公子的脸上，露出如同反着强光的小刀一般异样的表情。

「布利格死了！？为什么！？」

「在……电缆管道里，被从上面射击……」

克里特拼命拉住不知道听没听到刚才的话，架起步枪准备跑出去的汉斯。

「住手！敌人的攻击是佯动。已经，没有战斗下去的意义了……」

汉斯沉默了一会。之后，他敲了一下墙壁发出剧烈的声音，一下子转过身跑了过来。

「……不对，还有一个命令。没法夺取的话，就破坏掉。你肯定有什么办法吧？」

被汉斯一下子提起来，如同自己要被逼问着的他吃掉一般的克里特点了点头。

「啊……啊啊，也不是没有……不，不行啊。没有队长，做不了判断。」

「说啊，给我说！！」

汉斯突然用突击步枪闪着青光的枪口指向克里特。对着和布利格一直以搭档身份在中东
和南美的战场上战斗的佣兵那锐利的眼神，克里特没法反抗。

「发……发动机——」

「发动机？你说这艘船？」

「没错……这艘大船的发动机，是核动力炉……」

已经经过了十分钟。

神代凛子在无意识中紧握着双手，凝视着无情地刻在显示器上的数字。

进入《极限加速阶段》后，Under World内过去的时间——已经达到了一百年。

桐之谷和人和结城明日奈对着漫长的时间会有怎样的感觉，已经远超过了自己的想象。
唯一能够确认的，就是二人的Fluct Light记忆容量正逐渐接近极限。

根据比嘉的预测，人类的灵魂在蓄积了一百五十年分量的记忆时就会无法做出正常的动
作，开始崩坏。当然，这并非实验所确认的情况。实际的极限可能比这更长——或者，可能比
这更段。

如今只能祈祷能在灵魂开始崩坏之前完成注销处理了。如果能够做到的话，就还有变回
二人原本样子的可能。

比嘉君……菊冈先生。拜托你们了。

正在祈祷的凛子没有注意到，楼下响起的微弱枪声不知何时突然消失了。将这个事情告
诉她的，是跑回副控制室的中西上尉。

「博士！敌人开始撤退了！」

「撤……撤退！？」

抬起头的凛子哑然重复着。

为什么这个时候撤退了。耐压隔墙再次开放的现在，对袭击者来说难道不是夺取爱丽丝
的最后机会吗。放弃的话也太早了。离护卫舰突入还有四个多小时。

凛子敲打着键盘呼出显示舰内各处状况的窗口，向上尉询问道：

「战斗……有出现伤者吗？」

「啊……轻伤两人，重伤一人，不过在治疗中，应该不会有大问题。」

「是……这样吗。」

凛子将屏住的呼吸轻轻吐出。瞥过一眼，注意到有着刚毅面容的上尉在脸颊骨的位置贴
着一块大纱布，从纱布里渗出了一点血。他大概把自己也算在轻伤者中了吧。

为了让他们的奋战不被浪费，一定要将两个年轻人救出来。

至少，敌人开始撤退这件事是个好消息。凛子将视线转回状态窗口，确认船底的水中码
头正在开门。

「嗯，似乎是正在通过潜水艇脱离的样子……但就算这样……也太慌张了……」

正当她皱起眉头，轻轻咬住嘴唇的时候。

与之前完全不同的震动，让主轴整体都摇动了起来。

从巨大的浮台内发出「轰」的如同寒风一般的响声。桌子上的圆珠笔滚落到地面上。

「这……这是什么！？发生了什么！？」

「这是……啊……难道说，那帮家伙……！！」

中西上尉低声呻吟着。

「这个震动，是主机全力运转造成的，博士！！」

「主……机？」

「主发动机……也就是，主轴基部的，压水型核动力炉……」

跑向控制台的上尉，代替愕然睁大双眼的凛子用不刁惯的动作操作着状态窗口。在一个
个出现的新窗口中，有一个出现了模糊的图像。

「混帐！！控制棒全都被压下去了！！那帮混蛋做了什么！！」

凛子以沙哑的声音向砰地敲了一下桌子的上尉问道：

「但是，安全装置应该还有的吧……？」

「当然，在炉心到达临界状态前，控制棒会自动突入，将核裂变停下来。但是……这里，
您看这里。」

上尉指向的是显示器上核动力炉所在房间的实时画面。虽然因红光而很难分辨，但大规
模机器的一部分，贴着一个小小的白色东西。

「这个恐怕是C4……塑胶zhadan。虽然这个尺寸应该没法破坏炉心，但这个位置是用于
让控制棒上升到炉心位置的驱动装置，如果这里被破坏了的话……」

「核裂变会……停不下来？这样的话，又会变成怎样……？」

「首先是一次冷却水会蒸汽爆炸，破坏储藏容器……最糟糕的情况下，融解的炉心会落
到海面，引发大量的蒸汽，恐怕会把主轴内部……从主控制室、Light-Cube集群到这个副控
制室整个炸飞吧。」

「什…………」

凛子不禁看向脚边的地面。超高温的蒸汽会打破这坚固的金属袭来——？

要是变成那样的话，好不容易至今都没有出现牺牲者的《拉斯》人员、躺在STL上的和
人和明日奈、还有封存在Light-Cube集群里的十余万人工Fluct Light们，都一点也不会剩
下……

「我去拆除zhadan。」

突然，中西上尉低声说道。

「那帮家伙应该是设定了潜水艇足够离开《海龟》的起爆时间。差不多还有五分钟……
应该有十分钟。」

「但，但是，中西先生，发动机室里的温度，已经……」

「什么啊，也就是桑拿那种程度罢了。跑进去拔掉引信挺简单的。」

——但那也是穿好防护服之后才能做到的事。然而，已经没有准备的时间了。

凛子没能将心中的这句话说出来。走向房门的上尉那宽阔的后背，如同将一切柔弱和感
伤都赶走的钢板一般。

然而。

有什么人在发出嘎嘎声音的战斗靴到达房门前，从通道一侧拉开了门。

凛子凝视着在昏暗的通道里站着的什么人的身影。

传来了「嗡」的一声。是马达驱动的声音。接着是金属踏上金属地面的喀嚓声。

从像是蹒跚着一般弯下腰的中西上尉的另一侧，出现在灯光下的身影——是有着暗淡光泽
的无骨四肢的、有着搭载了复数个棱镜的头的，人型机器。

「Ni、Niemon……试作二号机！？为什么，自己动起来了……！？」

机器人无视喘着气的上尉，笔直注视着凛子，说道：

『我去。』

这个声音。

飘在房间里的，蜡和油的味道。

几天前，到达《海龟》的那一天夜晚，在梦中听到，嗅到的……

凛子慢慢站起，向前走出几步，挤出沙哑的声音：

「……晶……是晶彦吗……？」

发出淡淡绿光的传感器，如同眨眼般闪烁了一下。机器人点了点头。

如同被吸引过去一般接近着的凛子，用颤抖的双周，轻轻触碰着铝制外装。随着微弱的
驱动音抬起的双手，碰到了凛子的后背。

『这么长时间让你一个人生活，实在很抱歉，凛子。』[fn:151]

虽然是电子信号合成的声音，但他无疑是神代凛子过去爱上的唯一一名男子——茅场晶彦。

「居然会在……这种地方见面……」

凛子轻声说着应当早已忘记的方言。她的两眼溢出了泪水，渗入了传感器的光中。

『没时间了。所以，我只把必要的说出来。凛子……我能够和你相遇，感觉非常幸福。
能将我和现实世界连接起来的，就只有你一个人了。希望……以后，你也能这么做。将我的
梦想……如今还被分隔开来的，两个世界……』

「嗯……当然……当然。」

注视着不断点头的凛子的机械的脸上，露出了微笑。

退开身体的机器人，流畅地移动重心转向，以如同跑起来一般的速度向通道走去。

在无意识地想要追上去的凛子面前，门带着微弱的声音关上了。

凛子深吸一口气，紧紧咬住牙齿。现在还不能离开这个副控制室。自己必须确认各处的
状况。

所以，她看向发动机室的录像，紧握胸前的火箭模型，最大程度的祈祷着。走到她旁边
的中西上尉，像是叹息一般低声说出「拜托了」的话。

比嘉健在听到电缆管道下方传来的涡轮的沉重声响时，终于明白了菊冈所害怕的『最糟糕的
情况』的真面目。

「菊……菊先生……那帮家伙，把核动力炉……」

沙哑的呻吟被强音盖过。

「我知道。现在还是全神贯注在STL关机作业上吧。」

「啊……知道。可是……」

再次将带状电缆的连接器插入好不容易够到的检测面板，可比嘉后背上的汗却停不下来。

假设核动力炉爆炸，这个工作也就没有意义了。到时候，Under World也好，爱丽丝的
Light-Cube也好，都会被高温蒸汽和高能量放射线彻底破坏掉。

然而核动力炉爆炸可没这么简单。覆盖炉心的厚壁金属容器用小手枪怎么也没法破坏，
而且控制部分也加上了数道安全保护措施。假设无谋地让其不断全力运转，安全装置应该很
快就会运作，将核裂变停下来。

这时，菊冈若无其事地以和平常一样的声音问道：

「嗯，比嘉君。接下去的一个人可以吗？」

「诶……嗯，如果用背带固定在梯子上的话，可以继续工作……但，但是，菊先生，你
难道要……」

「不不，只是去看看情况，不会乱来。马上我就回来。」

菊冈这么说着，马上将固定二人的背带揭开，用几个扣环紧紧固定在梯子上。确认比嘉
的身体已被固定后，他开始向下降落。

「那之后就拜托你了，比嘉君。」

看向上方的黑框眼镜深处，眯细的眼睛露出了笑容。

「小，小心一点！说不准那帮人还留在里面！」

菊冈对比嘉的声音做出一点也不像他的，突出右手大拇指的动作，接着以惊人的速度爬
下梯子。

到达最下端的舱门后，谨慎地窥视里面，然后他爬到了通道内。

当比嘉注意到的时候，菊冈的身影已经消失了。

右手敲着终端的比嘉，用左手胡乱整理系在腹部的背带时，感觉到有什么湿润的东西。
他在大惊中看向左手手掌，被在橘色的紧急灯下显出黑色的液体润湿了。

这明显不是比嘉的血。

几分钟前还被袭击者们占据的主轴下半部，虽然内部摄像头几乎全被破坏，但位于核动力炉
所在的动力室的摄像头仍然完好无损。

凛子看向将摄像头拍摄下的画面放大显示的主显示器，双手紧握着火箭模型等待着。

左边的中西上尉靠在控制台上，也一样紧紧握住双手。位于他们背后的，从楼下的防线
上来的警备人员和技术人员们，也做出各种各样的姿势，各自在心中默念着。

凛子之前曾请求他们至少退避到船头的舰桥位置。然而，没有一个人离开主轴。

在这里的所有人，都过着在无法公开的伪装企业《拉斯》进行研究开发工作的人生。他
们将自己的梦想和愿望，托付给了定能开拓真正的Bottom-Up型人工智能的新时代。

直到今天的这个瞬间前，凛子都认为自己不过是船上的一个过客。无论怎样，她都无法
和菊冈诚二郎这个看不透真心的人一起工作。

然而，凛子还是来到了拉斯。然后，她终于明白了。

人工Fluct Light，并不只局限于无人兵器搭载用AI这一狭窄的领域。

同样，Under World也并不仅是社会发展的模拟。

它们都是巨大的变革的开始。

让不断封闭的现实世界改变的，另一个现实。让想要打破现有系统的年轻人们的意志，
在他们眼前以看不见的力量具现出来的世界【An INCarnate RADius】。

——这大概才是你所期望的吧。

你在浮游城里的两年间注意到，发现到的，『他们』的可能性。那是令人目眩的心之光
辉。

我一定会将它们连接起来的。所以——

拜托了，晶彦。守护大家的世界。

像是对凛子的祈祷做出回应一般，显示器上的远程录像内终于有了动作。

是被两重厚墙封锁的压水型核动力炉。通向炉心的狭窄通道上，出现了《人工Fluct
Light搭载用人形机器试作二号机》的身影。

不知是不是电池输出功率降低的原因，步伐非常缓慢。机器人像是与钛骨架的脚承受的
重量战斗一般，发出咔嚓咔嚓的声音前进着。

凛子无法想象，茅场晶彦的思考复制体，到底是在什么时候潜伏在那个身体内的。然而
唯一可以确定的就是，现在潜伏在那个机器的物理内存内的程序，应该是他唯一的本体意识。
所有的智能，都无法承受自己是有着复数存在的复制品这一认知。

电子系统几乎裸露在外的试作机器，到底能忍耐炉心的高温到什么程度呢。

拜托了，请平安拆除zhadan，再一次回到我的身边吧——祈祷着的凛子咬紧了嘴唇。

恐怕，茅场晶彦已经有了在这里消失的觉悟了。

过去即使将大脑烧毁也留下了意识的他，终于到达了目标，找到了应当死在的场所。

嗡的一声。马达在鸣叫。

喀嚓一声。是制音器的声音。

虽然极为勉强，但机器人还是步行走到了第一道门前。

它伸出右手，操作开关面板。随着噗的一声油压机的声音，厚合金门向内侧开启——

这时。

从扬声器里迸发出步枪的高声咆哮。

从打开的合金门深处，一个穿着黑夹克的士兵，喊着什么话跑了出来。

如同之前一样，头盔和风镜挡不住他的脸。看上去是个美男子的脸上，留着修正得很整
齐的胡子。

「什么……还留下了一个人！？为什么！？想死么……！？」

中西上尉惊愕地呻吟着。

显示器上，二号机将双臂交叉在身体前方，守护着躯干部位。但接着就被几发子弹打中
了。

伴着弹出的火花，铝制外装被打出了几个孔。各处的线缆被打断，细小的齿轮和螺栓飞
散开来。

「住……住手！！」

凛子不禁发出了哀鸣。然而画面内的敌兵似乎在愤怒之下用英语喊着什么，继续扣动步
枪的扳机。机器人蹒跚着后退了一步。

「糟……糟糕！Niemon的简易外壳承受不住子弹！！」

虽然已经赶不上了，中西上尉还是拿起手枪准备跑出去。

这个瞬间。

新的枪声从另一侧的扬声器中传来。

第三个人用手枪乱射着，跑进了通道。敌兵的身体左右剧烈摇晃了一下。从二号机的背
后，连一发误射都没有的连续射击。如此厉害的技术，到底是谁——

已经忘记了呼吸，只是睁大了眼睛的凛子面前，敌兵的喉咙部位终于冒出鲜血，瘦高的
身体如同被弹开一般向后倒去，再也没有动弹。

接着，救援者也在通道中慢慢跪下——

身体横着倒了下去。

额前的刘海。已经歪斜了的黑框眼镜。嘴边似乎可以看到淡淡的笑容。

「菊……菊冈先生！！」

「中校……！！」

凛子和中西一起喊了出来。

这次自卫官以如同要摔倒般的势头跑出了房间。凛子已经无法阻止他了。

一名技术人员替代他跑到控制台边，以飞快的速度敲打键盘，在显示器上呼出似乎是显
示二号机状态的窗口。

「左臂，输出为零……右脚，百分之七十。电池剩余容量百分之三十。可以，它还能
动！！」

如同听到了技术人员的喊声一般，二号机再次开始前进。

嚓。嚓。随着蹒跚的步伐，被打断的电线上散发出火花。

已被打得破碎的身体穿过门缝，从里面将门关上。摄像头的画面切换到了炉心内部。

第二道耐热门，是用大型控制杆加以物理锁定的。二号机的右臂抓住控制杆，将它按下。
肘部的离合器空转着，有大量火花飞散出来。

「拜托了……」

与凛子的自言自语一起，副控制室里的众人也一起声援着：

「加油，Niemon！！」

「就是那，就差一点了！！」

咔。轰。

控制杆降了下去。同时，沉重的大门如同被内部的压力推开一半打开了。可以从显示器
上清楚地看到里面喷出的大量热气。

二号机蹒跚着前进。后背右侧的粗电线，突然迸出激烈的火花。

「啊……啊，不好！！」

技术人员突然喊了出来。

「什么……怎么了！？」

「连接电池和主控制板的电线损伤了！！那里如果断线的话……整体的电力供应就会停
掉……会彻底动不了的……」

凛子和其他人员都无言以对。

附着在二号机上的茅场自己，大概也意识到这是重伤了吧。像是用右肘按住摇晃的电线
一般，机器人继续慢慢前进着。

终于到达了核动力炉的内部。仍在全力运转的炉心散发出的高热无法排出，内部已经成
了人类无法直接承受的高温状态。

恐怕，很快安全装置应该就会动作，自动送入控制棒将核裂变停下来吧。

然而，在此之前，如果被设在那里的塑胶zhadan爆炸，破坏了控制棒驱动装置的话，从
核燃料里放出的大量中子，会继续让铀原子在链式反应中崩毁，最终导向无法控制的临界状
态。

溶解的炉心让下方的一次冷却水一次性大量蒸发，撕碎容器，炉心在重力作用下贯穿船
底到达海面的话——

凛子的脑海中，一瞬间闪过喷出的白烟贯穿《海龟》的画面。

她一瞬间闭上眼睛，再次祈祷着：

「拜托了……晶彦……！！」

众人再次开始声援。如同要让将他们按回去一般，试作二号机踏入了主机室。

摄像头的映像再次切换。

接着，扬声器里传来巨大的噪音。显示器上的画面染成了一片红色。

撇开热气，像是拖着一只脚前进着一般的二号机，距离贴在容器上的塑胶zhadan已经只
有五六米了。

机器人向引信抬起右手。身体的各处不断有火花飞散，被割裂的外装碎片落在金属地面
上。

「加油……加油……加油……！！」

只有这句话在副控制室里回响。紧握双拳的凛子也嘶哑地喊着。

还有四米。

三米。

下一步——

与此同时，二号机的后背上，迸发出如同爆炸一般的火花。

被打裂而摇晃着的黑色电线，简直就像受伤的内脏一般。

脸上的所有传感器都熄灭了。右臂也慢慢沉了下去。

两膝在油压减震器的驱动下，慢慢弯曲——

二号机，彻底沉默了。

显示器上的状态窗口内摇动着的几排彩虹色的输出显示条，全部落回左端，变成了一片
黑色。

技术人员如同低语一般说道：

「……全部输出信号，都……消失了……」

——我从不相信奇迹。

过去，SAO在比预定时间还要更早地被攻略，所有玩家被解放出来的那一天，在山庄内
的床上醒来的茅场晶彦对凛子这样说道。

他的眼睛里充满安稳的光彩，留着乱糟糟的胡茬的嘴边露出了淡淡的微笑。

——不过啊，我今天，第一次看到了奇迹。

——被我的剑贯穿，HP应该完全归零的他，简直是像在反抗系统一般……拒绝了消灭，驱
动右手，贯穿了我的胸膛。

——说不准……我，只是在期待着那个瞬间吧……

「……晶彦！！」

凛子完全没有注意到胸前握着火箭模型的右手已经滴下鲜血，只是大喊着：

「……你是……《神圣剑》希斯克利夫对吧！！是那个《二刀流》桐人的，最好的对手
对吧！！那么，你也……创造一次奇迹，让我们看看吧！！」

咔。

咔咔。

二号机双眼内的测距传感器闪着绿光。

膝盖的关节部位内的齿轮，吱拉吱拉地转动着。

就像是在反抗一般。

状态窗口的左端，紫色的光在微弱的闪烁——

显示四肢与躯干的输出状态条，一口气延伸到了最右端。猛然放出驱动音的各处驱动装
置散发出火花。

「二……二号机，再次启动！」

技术人员发出了悲鸣。

凛子的两眼已经全是泪水。

「去啊——！」

「去吧！！」

所有人都在喊着。

机器人抬起右脚，向前，一步。

伸直身体，向高处伸出右手。

一步。再一步。

小小的爆炸。身体摇晃了一下。再往前一步。

伸长到极限的右手手指，终于碰到了炉心容器下面贴着的塑胶zhadan。

拇指与食指，找到了插进去的引信。

手、肘、肩部的关节都已经如同濒死一般散发着火花，二号机将已经到达时限的引信拉
下，高高举起右手。

闪光将画面染成一片白色。

右手与炸裂的引信一起被吹飞的二号机，整个身体慢慢倒下——。

砰地触及地面。传感器稍微闪动，然后熄灭的同时，出力状态条再次陷入了黑暗。

没有人说一句话。

数秒后，涌起的欢呼声，让副控制室为之摇晃。[fn:152]

如同寒风般的涡轮咆哮，终于逐渐减弱，最终完全散去。

比嘉长出了一口气。被敌人强制全力运转的核动力炉，终于沉寂了下来。

用左手的袖口拭去额头上的汗水，透过被弄脏了的眼镜凝视着小型终端的显示器。

两台STL的关机处理进程，好不容易完成了百分之八十。从《极限加速阶段》开始已经
过了十七分钟，相当于Under World内的一百七十年。

这是远超过比嘉预测的Fluct Light寿命极限的漫长时间。只从理论上考虑的话，桐之
谷和人和结城明日奈的灵魂已经崩毁的可能性很高。

然而比嘉已经承认，自己根本就不了解Under World和Fluct Light。确实，他设计、构
筑并让这个世界运转起来了。然而，在那闪着美丽光辉的稀土积层晶体内诞生的世界，达到
了《拉斯》技术人员们从未想象到的高度。

而如今，最了解这个世界的现实世界的人，无疑就是桐之谷和人。不过是十八岁的高中
生的他，在那个世界全力承担、适应、进化，最终显现出了四个超级帐号都未能拥有的强大
力量。

这并不是名为桐之谷和人的这个人与生俱来的能力。

他一开始就将被《拉斯》的所有工作人员仅仅当成实验用程序的人工Fluct Light们视
为和自己一样的人类。作为人类，和他们接触，战斗，守护他们，也爱着他们。

所以，Under World及生活在那个世界的所有人选择了他。作为一个守护者的他。

如果是这样，在比嘉等人所想象不到的某种奇迹之下，他能够承受两百年的时间流的可
能性也是存在的。

——是这样的吧，桐人君。

——我现在明白了，为什么菊冈中校需要你的帮助到了那等地步。而且，从现在开始，你
也是必要的存在吧。

——所以……

「……拜托了，回到这个世界吧。」

自言自语着的比嘉，紧紧盯视着显示器上进行到只剩最后几个百分点的关机处理过程。

只有凛子一个人留在副控制室。

其他人都为了救助菊冈中校和恢复对主控制室的控制权而抢先跑了出去。

凛子其实很想跑到安放核动力炉的房间，保护应该倒在监控摄像头范围之外的试作二号
机和还留在它的物理内存内的茅场晶彦的复制体。然而，现在还不是可以离开的场合。在比
嘉完成STL关机处理之后，必须去确认还在隔壁沉睡着的桐之谷和人和结城明日奈的状态。

凛子相信，他们两人会平安无事地醒来的。

想要让他们握住爱丽丝的Light-Cube，说出「是你们保护了她」的话。

恐怕在到楼下去的技术人员们处理几分钟后，《极限加速阶段》就会结束，Under
World的时间流速会回到等速率吧。想要向二人传达那个意志和存在守护了那个世界的话——
过去曾将他们囚禁，让他们战斗并在其中受尽痛苦的那个男人，驱动着电源被切断了的机械
身体，保护了Under World和《海龟》。

她不想请求他们原谅他。

杀死了两万个年轻人的茅场晶彦的罪，不论怎样都无法补偿。[fn:153]

然而，无论如何都想让和人和明日奈理解茅场留下的想法和目标。

凛子用渗着血的手掌捧着爱丽丝的Light-Cube封装，闭上眼睛的时候，耳边的对讲机里
传来比嘉微弱的声音：

「……凛子小姐，两位的注销处理完成还剩六十秒了！！」

「明白了。马上会让人去迎接他们的。」

「拜托你了。果然我一个人还是没法从梯子爬上去啊……而且，菊先生好像去下面看情
况了，他怎么样了？好像他也受伤了啊……」

凛子没有立刻回答。距离中西上尉前去救助在通向核动力炉的通道里和敌兵互相射击，
之后倒下的菊冈中校已经过了三四分钟，但现在还没传来消息。

然而，菊冈会是为了这个目的而死掉的人吗。那个一直带着轻浮而深不见底的态度的，
在幕后回转自如的男人会这样做吗。

「……嗯，中校可是相当活跃呢。简直就像是好莱坞的动作演员一样。」

「嘿，还真不像他啊……还剩三十秒了。」

「那么我去STL室吧。如果有什么状况再联络。就这样。」

凛子挂断通话，双手轻轻捧着黑色的金属立方体，离开控制台走向隔壁的房间。

在她碰到房门之前，室内的扬声器里传来了楼下工作人员的声音。

既不是中西上尉，也不是赶赴主控制室的技术人员。是为了以防万一，赶往温度开始下
降的核动力炉安放室拆除塑胶zhadan本体的警备人员的声音：

「这里是发动机室！博士……听得到吗，神代博士！」

凛子抑制住砰砰的心跳，切换对讲机的线路喊道：

「嗯，听得到！怎么了！？」

「那，那个……zhadan平安取下来了，但是那个……不在。」

「不在……是，什么不在……？」

「二号机不在。不论在发动机的哪个地方，都找不到试作二号机的躯体！」

便宜的数字表上设定的倒计时，已经到达了零。

跪在强袭登陆用小型潜水艇的座舱里，听着外部声纳的克里特，在确认过了好几秒后仍
然没有传来理应听到的爆炸声后，吐出了颤抖的气息。

他自己也不明白，这是安心，还是失望。

唯一能确认的，就是安放在《海龟》的核动力炉上的C4zhadan因为某个原因而没有爆炸，
因此控制棒驱动装置未被破坏，核反应炉也没有发生炉心融解。

如果留在核动力炉那边的汉斯没事的话，大概会手动炸掉吧。但似乎那个男人也被除掉
了。

应该只以钱为目的的佣兵，却在绝对会死的情况下没有脱离，实在让人意外。汉斯从知
道他的搭档布利格死掉的时候开始样子就很奇怪，总不会是连死的地方都想和他一样吧。

「……嘛，大概有很多事情吧……」

摘下声纳耳机的克里特自言自语着。

没错，在汉斯他们之前死掉的米勒队长和瓦沙克，除了钱大概也有各种事情吧。正是这
种障碍，杀死了他们。

要是这么说的话，克里特和潜水艇上其他的其他队员，也被作战以完全失败告终这一相
当巨大的障碍逼迫着。被身为他们所有人的雇主的民间警备公司——实际上是美国军工企业雇
佣的处理违法事件的公司抛弃掉也不过是瞬间的事情吧。恐怕在他们回到本土的那一瞬间，
所有人被灭口的可能性也不是不存在。

克里特透过衣服，轻轻抚摸着内口袋里作为保护自己的保险而从《海龟》偷偷拿出的一
枚软盘。[fn:154]

靠这个东西到底能与他们对抗到怎样的程度呢——但至少，被杀的时候大概还是会被爆头，
所以相比瓦沙克和米勒中尉那吓人的死法还是好的多了。

「真是的……」

克里特鸣了下鼻子，眺望着逐渐接近的显示海狼级核潜艇《吉米·卡特》所在位置的光
点。

从《极限加速阶段》开始的，十九分四十秒后——

设置在《海龟》第二STL室的两台Soul Translator的关机处理终于完成了。之后又过了
三分钟，时间加速也被解除，冷却系统减速，船内恢复了静寂。

经神代凛子博士之手从机器里解放出来的两位少年和少女，桐之谷和人和结城明日奈——

却仍然没有醒来的迹象。

Fluct Light的活性降低到了极限，基于灵魂的精神活动很明显已经接近消失。

博士握着二人的手，流着泪，拼命地呼唤着他们。

深深沉睡着的和人和明日奈的嘴边，露出了淡淡的微笑。

叩。

……叩。

声音在我的眼前停下。

之后，有什么人，呼唤了我的名字。

「……桐人君。」

安稳、清澈而慈爱的声音在空气中响起。

「还是一点没变呢，一个人的时候就变成爱哭鬼了……我早就知道你是这样了……什么
嘛。」

我慢慢抬起被眼泪沾湿的脸。

两手绕在背后，头稍微歪着的亚丝娜，带着微笑站在那里。

不知道该说什么才好。所以我就这样，一直注视着亚丝娜的脸，以及那怀念的榛色眼睛。

风从旁边安稳地吹过，空中飞舞的蝴蝶从我们中间穿过，消失在蓝天中。

目送它们离去的亚丝娜，转过视线向我伸出右手。

如果碰到的话，大概就会如同幻影一般消失吧。

不，怎么可能会这样。

亚丝娜也明白的。这个世界马上就要被关闭了。再次回到现实世界的话，大概要在那无
限流动的时间的另一端了吧。所以，她才留下了。为了我。如果立场反过来的话，我也会做
出同样的选择。

我伸出手，将亚丝娜的小手紧紧握住。

我就这样被她拉起来，重新注视着近处美丽的榛色眼睛。

果然还是什么都说不出来。

然而，大概已经没有说什么的必要了。所以，我只是，将她纤细的身体拉过来紧紧抱住。

将头埋在我胸前的亚丝娜，轻声说道：

「……回到那边的时候，爱丽丝大概会生气吧。」

我在脑内想象了一下那个好胜的黄金骑士，蓝眼睛如同要放出火花一般地叱责我们的场
景，然后露出了微笑。

「没问题的。我们肯定都会记得的。和爱丽丝一起度过的时间，一秒都不会忘掉。」

「……嗯。是啊。爱丽丝……莉兹、克莱因、艾基尔、西莉卡……还有小唯，我们都一
直记得的话就没问题的，对吧。」

我们放开拥抱彼此的手，点了点头，一起看向无人的神殿。

功能已经停止的大理石遗迹，静静地沉睡在世界尽头的柔和日光之下。

回过头，握着彼此的手，我们就这样在铺着石子的小道上前进。

在无数色彩的花朵间，稍微前进了一段后，到达了浮岛的边缘。

湛蓝色的天空之下，是广阔无边的世界。

亚丝娜看着我问道：

「我、我们要在这个世界，度过多长时间呢？」

我稍微沉默了一下，吐出了真相：

「大概最短也要两百年吧。」

「嗯。」

亚丝娜点点头，露出和过去一样的笑容：

「只要和你在一起，就算一千年也一点都不长……来，出发吧，桐人君。」

「……啊。走吧，亚丝娜。要做的事情还有好多……这个世界，才刚刚诞生呢。」

我们拉着手，张开双翼，向着无限的青空踏出最初的一步。

（第八章 终）
* Footnotes
[fn:154] 【rkl：这泥马，都2016年了居然还用diskette（软盘）！】
[fn:153] 【rkl：这里怎么回事？我记得Web版也就死了一万人，这里怎么又变成两万了？川原你不能这么手滑……】

[fn:152] 【rkl：没想到，这么一段剧情，能比桐人一刀秒三万人和对加百列的16连击更让我燃起来……而且这两人肯定是一辈子的好机油……】
[fn:151] 【rkl：你们有这个废话功夫还不快去拆zhadan……】

[fn:150] 吐个槽：我怎么也没想到学刁（xi）的这个“xi”字会被和谐的，真的找了我老半天……因此，下文中的刁自行替换成“xi”吧
[fn:149] 【rkl：所以我都说了，AW里的心意技什么的都弱爆了……】

[fn:148] 【rkl：总觉得这就是Chrome Disaster(Silver Crow version)的Laser Lance的高级版……】
[fn:147] 【rkl：川原你这是手滑吧，前面还是右臂被折，这里怎么变成左臂了……】

[fn:146] 【rkl：其实那段咚，咚咚咚咚在翻译的时候不由自主地想起了Intel的广告……我自重。】
[fn:145] 【rkl：实际上在这里吐槽我总觉得不合适，但Under World里连动物都有伦理限制系统（众人：我们都知道你往破坏伦理的方向去想了。）】

[fn:144] 【rkl：这次中枪的是DOTA……】
[fn:143] 【rkl：kirito的方针就是，敢动我妹子的统统去死……】

[fn:142] 【rkl：这句话的吐槽点，就是在神的面前乱发誓……你真的不怕被天罚么……】
[fn:141] 【rkl：你看看你，你看看你……就算女儿不在，你这推土机的黑历史不是照样被曝光了么……】

[fn:140] 【rkl：噗……】